### ISSUE TITLE
[CONAN] cannot find system mp3lame

### ISSUE THREAD

**Issue by carlo-bramini** [audacity/audacity#1009]
You are trying to detect system libmp3lame by using pkg-config, but it seems to me that this kind of support does not exist into the library.
You cannot find `.pc` script in CYGWIN package:

https://cygwin.com/cgi-bin2/package-cat.cgi?file=x86_64%2Flibmp3lame-devel%2Flibmp3lame-devel-3.100-1&grep=mp3lame

neither into the Debian package:

https://packages.debian.org/sid/amd64/libmp3lame-dev/filelist

neither into the latest sources of mp3lame from their repository:

https://sourceforge.net/p/lame/svn/HEAD/tree/trunk/lame/

So, it is not clear to me how this is expected to work.
And, when you configure Audacity, mp3lame 3.100-1 cannot be compiled in CYGWIN/MinGW/MSYS2 as it is because there is a bug into the source code (already fixed into SVN head, hopefully).

**Comment by crsib** [comment]
>You are trying to detect system libmp3lame by using pkg-config

This was an original behavior, ported over to the Conan system. It will be fixed in #1008.

>And, when you configure Audacity

There is a fixed recipe available as `libmp3lame/3.100@audacity/stable`. It is not used in master yet, because #949 is not yet fully fixed.

**Comment by mikhailnov** [comment]
This was described in https://github.com/audacity/audacity/issues/554

**Comment by crsib** [comment]
Fixed by #1008
