### ISSUE TITLE
Improve Audacity Support

### ISSUE THREAD

**Issue by AnitaBats** [audacity/audacity#1015]
You can help Audacity's users by adding and improving the Audacity Support page. 

More details can be found at https://support.audacityteam.org/contributing/tutorials
and https://github.com/audacity/audacity-support/issues

Communication regarding this generally happens on the [dev discord](https://audacityteam.org/devserver).

**Comment by petersampsonaudacity** [comment]
Please be aware that the Audacity App and the Manual are intertwined - many pages in the Manual are effectively part of the app.

Most errors/warning dialogs, all Effects/Generators/Analyzers, all Preferences dialogs have a "?" help button that drives the user to the relevant page in the Manual for context-relevant guidance.

**Comment by LovenSaini** [comment]
Can I still contribute to this issue?
