### ISSUE TITLE
label-sounds.ny not working for me, both mac and windows.

### ISSUE THREAD

**Issue by SinisterSpatula** [audacity/audacity#1032]
**Describe the bug**
Label-sounds plug-in is only able to detect the entire audio track as one sound, no matter what values I try.  I have tried both Windows and Mac and get the same behavior.  If I try the other plug-ins (Silence Finder, Sound Finder, etc) they work as expected and successfully mark the track with multiple detections.  I'm running v3.0.2 both under Windows and Mac.  The label-sounds.ny says it's version 4, release 3.0.0.

**To Reproduce**
1. Import an audio track.
2. Use sound labeler with any values.
3. It will label just the entire track as a single label (either surrounding, at the beginning or at the end).

**Expected behavior**
I expect to see more than one label, the same behavior that I can get from silence finder, sound finder, etc.

**Additional information (please complete the following information):**
 - OS: Windows 10 and Mac OS Big Sur (tried both).
 - Version Audacity 3.0.2

**Additional context**
I really want Sound Labeler to work because I would prefer it's functionality of minimum label interval which all the others do not have.

**Comment by SteveDaulton** [comment]
Please come and talk to us on the help forum so that we can resolve this. I'm expecting that it is just a matter of settings, but if it turns out to be a bug I'll fix it. The forum is here: https://forum.audacityteam.org

**Comment by SinisterSpatula** [comment]
Thanks, I made a post in the windows section of the forum.

**Comment by SteveDaulton** [comment]
Confirmed that this is a bug.
"Label Sounds" fails when sample  rate is 22050 Hz.
Logged as bug 2809.

**Comment by SteveDaulton** [comment]
Pull request sent with fix: https://github.com/audacity/audacity/pull/1036

**Comment by SinisterSpatula** [comment]
Thank you so much Steve for all your help!!  Should I test other sample rates too, or do you think it was only going to affect 22050 Hz?

**Comment by SteveDaulton** [comment]
The bug will affect some other sample rates, but the fix will work with  any sample rate.

**Comment by petersampsonaudacity** [comment]
I tested this and closed the bug on Bugzilla:
https://bugzilla.audacityteam.org/show_bug.cgi?id=2809
