### ISSUE TITLE
Wrong German translation for "Save changes to"

### ISSUE THREAD

**Issue by joriki** [audacity/audacity#1037]
This German translation is wrong:

https://github.com/audacity/audacity/blob/77dab158c37fcb7e448a103400810ac16eda4686/locale/de.po#L4825

It would be a correct translation if "to" were used to indicate the destination of the save operation, but it actually indicates the object "to" which changes were made. The correct translation for that is:

`msgstr "%sÄnderungen an %s speichern?"`

**Comment by Paul-Licameli** [comment]
Fixed in Release branch at 7bdc25039ffcd07db64895ddb1efe1b49c165a9e
