### ISSUE TITLE
Windows: 64-bit Audacity cannot export/import FFmpeg reliant audio files

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1044]
Testing on 64-bit as the current intention is to release 3.0.3 as 64-bit

Audacity fails to locate a 64-bit FFmpeg library and hence cannot export (or import) FFmpeg reliant audio files.

The full bug is logged as a P1 (release blocker) on Bugzilla
https://bugzilla.audacityteam.org/show_bug.cgi?id=2811
Bug 2811 - Windows: 64-bit Audacity cannot export FFmpeg reliant audio files

**Comment by petersampsonaudacity** [comment]
In addition to providing a 64-bit FFmpeg there are other issues to decide
a) where to host it
b) the Manual may need updating

**Comment by crsib** [comment]
I've sent the links to Martin

**Comment by petersampsonaudacity** [comment]
Testing on W10 with Audacity_Windows_64bit_968951902_70bb6a6  (3.0.3 build)
and with 64-bit FFmpeg library supplied by MUSE (Buanzo will be hosting this)

64-bit FFmpeg test ran smooth as silk ...
1) used the exe to install the 64-bit FFmpeg library in C:\Program files
2) Installed 3.0.3 64-bit from GitHub: https://github.com/audacity/audacity/actions/runs/968951902
3) launched 64-bit Audacity
4) Observe: no error message on launch complaining about missing FFmpeg
5) import an AAC/M4A file 
6) Observe it imports fine
7) export it as AAC/M4A file 
8) Observe: it exports fine
9) Examine Libraries preferences
10) Observe correct entry for 64-bit FFmpeg

**Comment by petersampsonaudacity** [comment]
I will not close this until we also test the hosting by Buanzo

**Comment by petersampsonaudacity** [comment]
I tested the hosting from Buanzo's site and all is fine - the Manual is updated accordingly
