### ISSUE TITLE
Accessibility in Crash Report Dialog

### ISSUE THREAD

**Issue by AnitaBats** [audacity/audacity#1045]
Screen readers (like windows build-in and VoiceOver in MacOS 10.16) skip reading contents of a wxStaticText, which describe what had happened. Also, currently, dialog does not support TAB navigation between elements at all.

**Comment by DavidBailes** [comment]
It would be helpful for others who might be interested in this issue to have a description. Thanks.

**Comment by vsverchinsky** [comment]
> It would be helpful for others who might be interested in this issue to have a description. Thanks.

Added

**Comment by Paul-Licameli** [comment]
#1052 was merged into the RELEASE branch.  But David raises remaining problems.

**Comment by Paul-Licameli** [comment]
https://github.com/audacity/audacity/pull/1052#issuecomment-866846116

**Comment by LWinterberg** [comment]
#1056 ought to have fixed this
