### ISSUE TITLE
can't build on archlinux

### ISSUE THREAD

**Issue by axelpersevalle** [audacity/audacity#1047]
hello,

when I try to compile audacity, I have an issue. i'll put the cmake and make command in a txt file. I try to compile  audacity 3.0.2 on archlinux.
[cmake_audacity.txt](https://github.com/audacity/audacity/files/6696102/cmake_audacity.txt)
[build_failure_audacity.txt](https://github.com/audacity/audacity/files/6696103/build_failure_audacity.txt)

thanks for your help

P-S: i just hope it can compile

**Comment by crsib** [comment]
Hi! This is a known issue, it was addressed in https://github.com/audacity/audacity/pull/1030/commits/4931de7213707feffdb024e22fab24b31299fb0a

It will be merged in sometime soon, you can apply the patch manually in the meantime

**Comment by axelpersevalle** [comment]
thanks, i just have a last question, how do i apply the patch?

**Comment by SteveDaulton** [comment]
The easiest way, since it is just one line, would be to open the file
libraries/lib-utility/MemoryX.h 
in a plain text editor, and add the line:
#include <limits>
directly after the line:
#include <functional> (line 12)

Then do a fresh (start from the beginning) build.

**Comment by axelpersevalle** [comment]
thanks for the response and sorry i wasn't here but i compiled it again and it works so thanks 
![image](https://user-images.githubusercontent.com/78932119/123306870-1dc53580-d522-11eb-8aec-d3615877c5a5.png)
