### ISSUE TITLE
Updates dialog should not spoil recordings in case of screen readers

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#1048]
If the check-for-updates dialog pops unexpectedly while there is a recording in progress, and a screen reader is in use, then the recording may be spoiled.

Fix that by delaying the dialog until after the recording ends.

**Comment by petersampsonaudacity** [comment]
Why are we even considering having an update check while Audacity is recording - or even just active or open.

I thought we had discussed this recently and decided that update checks at timed intervals were unnecessary and the the update checks would only be done on Audacity launch.
