### ISSUE TITLE
P1s in the Manual that need fixing for 3.0.3

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1058]
There remain several P1s in The Manual that require fixing for 3.0.0

1) View Menu changes
Most concern menu image/imagemap updates for a new command that was added to the View Menu (for Show Track Names).  This affects the View Menu page itself and its submenus. These images are normally updated using the magicke spelles that James Crook wrote - you may need to consult with him to find out how these spelles are applied.
- https://alphamanual.audacityteam.org/man/View_Menu
- https://alphamanual.audacityteam.org/man/View_Menu:_Zoom
- https://alphamanual.audacityteam.org/man/View_Menu:_Track_Size
- https://alphamanual.audacityteam.org/man/View_Menu:_Skip_to
- https://alphamanual.audacityteam.org/man/View_Menu:_Toolbars

2) Scripting Reference
https://alphamanual.audacityteam.org/man/Scripting_Reference
needs updating for new colorways in 3.0.3 (parameters for Set Track Visuals command)

**Comment by DavidBailes** [comment]
And there's now an application section in Preferences,

David.

**Comment by petersampsonaudacity** [comment]
>And there's now an application section in Preferences,

Indeed so that page need to be created - AND all 18 Preferences pages in the manual need their images and images updating (I have added P1s on each of those pages).

Had I been consulted in advance I would have recommended placing this new preference on the Warnings pref pane as a way of minimizing the work needed in the manual at a very late stage in the development cycle, just before Release Candidates..

**Comment by petersampsonaudacity** [comment]
I have added a new skeletal page in the Manual with a P1 for its creation.
https://alphamanual.audacityteam.org/man/Application_Preferences

See also:  https://github.com/audacity/audacity/issues/1005
Add page in alphamanual.audacityteam.org for application preferences like: https://alphamanual.audacityteam.org/man/Application_Preferences #1005
