### ISSUE TITLE
Extract lib-project-file-io

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#1134]
- [x] #1142 
- [x] #1138

**Comment by Ryan-Miller-Audacity** [comment]
As noted in the QA instructions in the pull request, I tesed the saving and loading of a variety of projects within the branch build is working as expected including for large files as well. I confirmed that these processes are still happening at similar speed and operation to previous releases as well. 

One issue to note (which wasn't enough to stop testing in its tracks): The title at the top of the Audacity window is not being displayed. This is true for both the default before saving (Audacity) and also once a project is saved the title is not updated to reflect the name change. I compared this behavior to the most recent release (3.2.4) which handled this behavior fine (displaying the default "Audacity" title before saving and the updated file name after saving).

**Comment by Ryan-Miller-Audacity** [comment]
Confirmed bug fix and the app is working as intended now.
