### ISSUE TITLE
Scrolling While Song is Playing

### ISSUE THREAD

**Issue by Enigma56** [audacity/audacity#1169]
**Describe the bug**
When attempting to scroll through a song/mix, the slider would get stuck and be unable to move past where the line-indicator for the currently playing clip is. It would keep glitching and moving back to where the audio clip is currently playing from. 
For Example, the clip is playing at 3:20 and scrolling past that would set the screen back to the "playing carrot"

**To Reproduce**
1. Open up a song of any length, *zoom in* on the audio so that the time increments are small
2. Move the window scroller to the right while the song is playing
3. See error - scrolling bug

**Expected behavior**
Even when a song is playing, the user should be able to scroll/pan past where the clip is currently playing from

**Screenshots**
If applicable, add screenshots to help explain your problem. - N/A

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version Audacity 3.0.4
 - (if relevant) Sound Device *Not Relevant*

**Additional context**
I am new to audio editing so I am unsure if this is something that exists on other sound editing software or not. My presumption is that this is a bug and it does not exist elsewhere

**Comment by LWinterberg** [comment]
![image](https://user-images.githubusercontent.com/87814144/156548380-15434dfd-94b7-436e-aabb-56884b4911a3.png)
Uncheck this checkbox
