### ISSUE TITLE
Updated Manual needs pulling for 3.0.3

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1171]
Testing on W10 with the latest alpha 3.0.3 build:  https://github.com/audacity/audacity/actions/runs/972351942

The Manual needs pulling again as there have been some important updates
1) 64-bit FFmpeg installation for Windows
2) Preference page added for the new Application Preferences
3) All other Preferences pages updated to show (and link to) the new Applications Preferences page
4) Update to the image and imagemap of the View Menu page for the new "Track Name" menu entry

Number 1 is VERY important as we need to ensure that the switch to 64-bit on Windows goes smoothly

**Comment by petersampsonaudacity** [comment]
Re-opening this as the Manual has had some necessary changes and correction since this was closed.

Plus it may need further updating if the GUI/UX for update checking changes

**Comment by crsib** [comment]
Manual is pulled automatically by CI
