### ISSUE TITLE
Audacity crashes when the output directory for Macros is set to C:\

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1174]
**Describe the bug**
Audacity crashes when the output directory for Macros is set to C:\ (and I suspect any unwritable location)

**To Reproduce**
1. Go to Directories preferences
2. Set the default location for Macro output to be C:\
3. Observe: Audacity does not stop you doing this (Bugzilla Bug #2740)
4. Tools > Macros
5. choose the shipped MP3 Conversion Macro
6. Apply Macro to: Files
7. choose any audio file for processing
8. Observe: Audacity crashes when it reaches the Export step in the Macro

**Expected behavior**
a) at Step 2 Audacity should block the use of C:\ and other unwritable locations for ALL default directories
b) At step 8 a sensible and helpful error message should be shown to the user.

Step b) is required even if step a) i.e. Bug #2740 is fixed - a folder location that was writable at the time the user visited Directories preferences may later become unwritable.

**Additional information (please complete the following information):**
This crash happen with 3.0.2, 3.0.3 and 3.0.4 alpha - it does not occur on 3.0.0 as that does not have the prefs setting for Macro output.  So technically this is a regression on 3.0.0

I discovered this issue when I was testing around on Bug #2740 as Paul has recently allowed the PR for a user fix for this issue
https://github.com/audacity/audacity/actions/druns/975549297

Sadly, in addition to this crash, that PR does not seem to fix the Bug 2740 issue when I test on 3.0.4 master build.

**Additional context**
OS: Windows 10 Home
Audacity versions:  3.0.2-3.0.4

I have flagged this bug as P2 - it is marginal P1, as that is what is used for most crashes, but only the very incautious and unwise user will set their default Macro output directory to be C:\ hence P2 and non-blocking, but still serious.

See:  https://bugzilla.audacityteam.org/show_bug.cgi?id=2740
P2 Bug 2740 - Directories in Directories preferences can be set to unwritable locations

**Comment by petersampsonaudacity** [comment]
I just researched an realized that this was lready reported as Bug 2738
https://bugzilla.audacityteam.org/show_bug.cgi?id=2738
P2 Bug 2738 - Audacity crashes with Macros on files when the macro-output folder is in an unwriteable location

**Comment by petersampsonaudacity** [comment]
See also Bug 2739
https://bugzilla.audacityteam.org/show_bug.cgi?id=2739
P2 Bug 2739 - If Temporary files directory is set to be unwritable then Audacity has a catalog of cryptic unhelpful errors

**Comment by gera-gas** [comment]
**Reproduce**

OS: Windows 10 Home
Audacity: master branch 4770b1f0a4c91c71eea8e54a180a7ba99b77834d

**Set the default location for Macro output to be `C:\`**
At this step, Audacity blocked the use of `C:\` and other unwritable locations with the following message:
![0 - unable_set_unwritable_dir](https://user-images.githubusercontent.com/1660969/124120114-0800c480-da7c-11eb-98d8-0884ba5847b4.png)

**Folder location that changing the status from writable to unwritable..**
Set folder to macro output writable directory with name `ttttttttt`
![1 - set_macro_directory](https://user-images.githubusercontent.com/1660969/124120624-a42acb80-da7c-11eb-8b12-840c4ca4b44c.png)

Then lock this directory for writing.
![2 - lock_directory](https://user-images.githubusercontent.com/1660969/124120739-c7557b00-da7c-11eb-9848-6b67e4a7079b.png)

Run MP3 Conversion Macro and apply to `Files`
![3 - run_macro_tool](https://user-images.githubusercontent.com/1660969/124120952-008deb00-da7d-11eb-80bb-402a76f670ad.png)

After that Audacity show message with a problem to the writing result and then successfully continue working.
![4 - message_after_macro](https://user-images.githubusercontent.com/1660969/124121200-477be080-da7d-11eb-9d70-7bb08656bb03.png)

**Comment by gera-gas** [comment]
@petersampsonaudacity, could you please me provide print screen with Audacity crash when used unwritable directory for macro output? Because I tried to reproducing this steps and still can't get the same result (crash).

**Comment by petersampsonaudacity** [comment]
@gera-gas 
![image](https://user-images.githubusercontent.com/50205984/124274529-490ade80-db39-11eb-801c-f2dec1e42809.png)

**Comment by petersampsonaudacity** [comment]
When I set the Macros output folder to be a sub-folder of C: (I used C:\Program Files) - I get no crash, but I do get this error message:

![image](https://user-images.githubusercontent.com/50205984/124275104-f67df200-db39-11eb-8ae4-85167ad686e3.png)

**Comment by petersampsonaudacity** [comment]
Audacity 3.0.4 alpha now blocks the use of C:\ (and other unwritable system files) with the pulling in to audacity:master for 3.4.0
of this Pull Request:
https://github.com/audacity/audacity/pull/1185
Add Directory permission check for Open, Import, Macro Output, and Temporary directory in Directory Preference #1185

This enabled me to mark P2 Bug 2740 as RESOLVED FIXED
https://bugzilla.audacityteam.org/show_bug.cgi?id=2740

But also importantly it means that this issue can no longer occur - so I shall close this.

Please note that this is fixed for 3.0.4 - but NOT for 3.0.3 (which is still in RC stage right now).

**Comment by petersampsonaudacity** [comment]
I tested this on W10 with audacity-win-3.0.4-alpha-20210704+0cef813-64bit
this is a branch build: https://github.com/audacity/audacity/actions/runs/999270883

1) clear Audacity settings folder
2) launch 3.0.2
3) Directories preferences
4) set the Macro output directory to be C:\
5) Exit Audacity
6) Launch 3.0.4 branch alpha with the fix
7) Tools Macros
8) choose the shipped MP3 Conversion Macro
9) Apply Macro to: Files
10) choose any audio file for processing
11) Observe: Audacity does not crash but displays the following error message when it reaches the Export step in the Macro

![image](https://user-images.githubusercontent.com/50205984/124466466-98961800-dd8e-11eb-8a36-69831d966587.png)
