### ISSUE TITLE
Freeze (or more like some sort of focus lost) on press play using space

### ISSUE THREAD

**Issue by ovROG** [audacity/audacity#1176]
I've just add mp3 and press space. Program won't went to "not responding" status but I can't press or do anything

1. Drag and drop mp3
2. Press space (not play button on UI)
3. Freeze

**Screenshots**
![1](https://user-images.githubusercontent.com/43468716/123651173-edd4a580-d833-11eb-94e2-dc62d047d0f1.gif)

 - OS: Win 10
 - Version Audacity 3.0.3 RC1 x64
 - MME (usb behringer um2)

**Comment by petersampsonaudacity** [comment]
I cannot reproduce this on W10 or Mac
