### ISSUE TITLE
Decompose stackable effects 

### ISSUE THREAD

**Issue by AnitaBats** [audacity/audacity#1179]
1. Details are TBD - requires meeting
2. Decomposition for Stackable effects: FE part - Anton, BE part - Paul
3. Please add description per each part

Paul: 2 hours to produce descriptions of tasks for future sprint.  (Mostly about dependency cycle breaking problems)

**Comment by Paul-Licameli** [comment]
@AnitaBats what is "FE" in the description?

**Comment by gera-gas** [comment]
Decompose required: 6-8 hrs

**Comment by gera-gas** [comment]
**Description of FE part decomposition.**
All estimation times have two borders: this is not 100% precision time frame, this is the approximate time window for solving task.

 1. Add effect button ("Add effects") for side menu on/off.
    1.2 Add draw functions: like as `MuteOrSoloDrawButton()`.
    1.3 Add button handler, inherited from `ButtonHandle` class.
    1.4 Add button description to `TCPLine` and `StaticTCPLines()` method.
    **Estimation:** 8, 10 hrs

 2. Add realtime effect panel frame.
     2.1 Mark up space for panel in `InitProjectWindow()` function by `wxBoxSizer` using.
     2.2 Create and add panel dialog window by `ShuttleGui` for effects list manipulations.
    **Estimation:** 4, 6 hrs

 3. Add buttons and handlers for realtime panel.
     3.1 Add buttons for effects manipulations, standard and bitmap buttons like as `mMenuBtn` in `EffectUIHost`.
     3.2 Add UI plugin control button into `EfectUIHost` class like `Enable` checkbox for bypass effect, etc.
     3.3 Add event listeners to panel when track focus changing like as `MixerBoard::OnTrackChanged` for example.
    **Estimation:** 14, 18 hrs

 4. Add menu item for open side effect list panel.
     4.1 Add command in `PluginMenus.cpp` file, `GenerateMenu()` method like as `OnManageGenerators()` for call exist side panel dialog.
    **Estimation:** 3, 4 hrs

 5. Final behavior tests.
     **Estimate:** 2, 3 hrs

Total estimate: 31 - 41 hrs.

**Comment by AnitaBats** [comment]
decomposition is done
