### ISSUE TITLE
Clip names

### ISSUE THREAD

**Issue by AnitaBats** [audacity/audacity#1182]
### User Story
As a user of Audacity, I would like to have individual clip names, and be able to rename clips.

### Description
Currently, there is no concept of clip names in Audacity, only track names. Individual clip names are very useful when organising a project, or separating between copies or takes. The new affordance design has a space for clip names top right.

The design at https://github.com/audacity/audacity/issues/1258 describes how to rename clips as a user.

**Generated/default  clip names**

When recording to a track, the auto-generated clip name should be derived from the track name by default: trackname#XX, where #XX is the number of the recording/take. This can be changed to anything afterwards

When importing an audio file to a track, the clip name should be the file name. This can be changed to anything afterwards

### Rules for auto-naming split/joined clips and copies

Suggested rules for auto-clips naming:
- New clip recording: "{track_name} #{take_number} {channel}"
- Merge clips: "{first_clip_name}"
- Split: "{clip_name} {index}"
- Import: "{track_name}"
- Copy: "{original_clip_name} copy {number}"
- Copy/Paste selection(part of a clip): "{original_clip_name} samples [range]" 

 suggested scheme may produce results like: "Clip 1 1" "Clip 1 2" "Clip 2" when splitting "Clip" into "Clip 1" and "Clip 2" and then splitting "Clip 1" into "Clip 1 1" and "Clip 1 2", similar would happen with copy-pasting a clip or it's parts. Is it ok, or is there some better scheme for such cases? 
 
 ### Additions
 
- basic RTL appearance

**Comment by vsverchinsky** [comment]
Est.: 16hrs

**Comment by vsverchinsky** [comment]
Suggested rules for auto-clips naming:
- New clip recording: "{track_name} #{take_number} {channel}"
- Merge clips: "{first_clip_name}"
- Split: "{clip_name} {index}"
- Import: "{track_name}"
- Copy: "{original_clip_name} copy {number}"
- Copy/Paste selection(part of a clip): "{original_clip_name} samples [range]" 
@jounih suggested scheme may produce results like: "Clip 1 1" "Clip 1 2" "Clip 2" when splitting "Clip" into "Clip 1" and "Clip 2" and then splitting "Clip 1" into "Clip 1 1" and "Clip 1 2", similar would happen with copy-pasting a clip or it's parts. Is it ok, or there some better scheme for such cases?

**Comment by petersampsonaudacity** [comment]
See also Discussion #1499 
>Thought-piece: labels for merged clips #1499
