### ISSUE TITLE
Fix wave clip record starting position

### ISSUE THREAD

**Issue by AnitaBats** [audacity/audacity#1183]
Currently when recording is started with selection cursor placed at some distance from track ending (same as the end postion of the latest clip in the track), this gap is filled with "silence", which should be removed. New clip should start from selection starting position, or from the end of the track (if selection starts prior to track ending)

**Comment by Paul-Licameli** [comment]
Please explain why this bug fix is necessarily a part of the affordances project.  I think it is an independent issue.

**Comment by vsverchinsky** [comment]
> Please explain why this bug fix is necessarily a part of the affordances project. I think it is an independent issue.

Agreed, but as i understood this bug should fixed as a part of the affordances project

**Comment by Paul-Licameli** [comment]
@AnitaBats I can review this change at #1265, but it is unclear to me how this specification entered the schedule.  Who specified this change, and why?

This looks like a design change, not a bug fix.  Did one of our designers request it?  But their names are not in this issue.  Did you specify it, or @vsverchinsky ?  Did designers agree the change is correct?

And again it is in no way a necessary part of the clip affordances project, but an independent improvement, if it is agreed that it should be done.
