### ISSUE TITLE
Audacity-win-3.0.3-RC1-x64: Export to WAV takes twice as long with x64 build

### ISSUE THREAD

**Issue by deus-e-x** [audacity/audacity#1188]
Audacity v3.0.3 RC1 for Windows:

Export of audio to WAV (signed 16-bit PCM) takes more than twice as long with the x64 build compared to the x86 build.

I tested both audacity-win-3.0.3-RC1-x64 and audacity-win-3.0.3-RC1-x86 on Windows 10 Pro x64 21H1 (official build 19043.1081).  I imported a FLAC file with a size of 248 MB, then exported the entire audio to WAV (signed 16-bit PCM). It takes ~15 seconds with the audacity x86 build, while with the x64 build it takes ~32 seconds.

Note:
Interestingly, the import of the 248 MB FLAC file takes ~8 seconds with the x64 build, while for the x86 build it takes ~9 seconds. Both the v3.0.3 RC1 x64 and x86 build import audio slightly faster than v3.0.2.

1. Load an audio file into Audacity (e.g. a FLAC file)
2. Select entire audio data (Ctrl+A)
3. Export selected audio (Ctrl+S)
4. Choose "WAV (Microsoft)" (signed 16-bit PCM) as the output format
5. Click "Save"

**Expected behavior:**
The time required to export audio to "WAV (Microsoft)" should be nearly identical both for the x64 and x86 build, perhaps with x64 taking a slight lead, as can be seen with the current import timings.

**Additional information (please complete the following information):**
 - OS: Windows 10 Pro x64 21H1 (official build 19043.1081)
 - Version: Audacity 3.0.3 RC1 x64 and x86

**Comment by DavidBailes** [comment]
A possible cause for the slowdown is that Audacity's version of float_cast.h does not contain any function definitions for 64 bit Windows. On 32 bit Windows, one or more of the definitions is needed to speed up export to WAV.

**Comment by crsib** [comment]
Thank you, David, I'll look into

**Comment by crsib** [comment]
You were absolutely right, David. I have added SSE2 implementation for x64 builds and it runs 4 times faster than the MSVC builtin functions

**Comment by Paul-Licameli** [comment]
@DavidBailes do you wish to review PR #1189 ?  Any objection?

**Comment by DavidBailes** [comment]
> @DavidBailes do you wish to review PR #1189 ? Any objection?

thanks for asking but no to both questions.

**Comment by Paul-Licameli** [comment]
I made a review and merged it.  Looking up the documentation to be reminded of the surprising fact that a long is still 32 bits on 64 bit builds, so the machine instructions used, return 32 bits, were really correct.

Which makes me think we need to review uses of lrint that should be llrint.  There may be such misuses in Audacity, which might rarely have some effect with long recordings.  But those will not be regressions on past versions, or the fault of these implementations.

**Comment by deus-e-x** [comment]
The issue has been solved successfully. Thank you very much, guys. :)

**Import FLAC file 248 MB, export to WAV 16-bit signed, timings:**

audacity-win-3.0.3-RC2-x86: import 9.5 seconds, export 14 seconds      
audacity-win-3.0.3-RC2-x64: import 7.0 seconds, export 10 seconds
