### ISSUE TITLE
Labels track items selection, navigation, editing changes

### ISSUE THREAD

**Issue by vsverchinsky** [audacity/audacity#1195]
### User Story
As a developer I need a document, describing in details what changes should be applied to the appearance and behaviour of the labels track and label track items. 

### Description

Currently label range selection and label name are interlinked and overlapping visually - we would like to decouple these two, so you can click on the label range to select that range, and on the label name to change the name.

The idea is not to take away being able to select a label range, but to decouple the two tasks - changing the label text, and selecting the label range. ..The long rectangle should also made slightly larger than currently (for easy clicking), and dragging it should move the label.

Keyboard navigation with tabbing between selected labels should still work, and to edit a label name we could use "Enter" key once a label has been selected.

![2 5 label change name@2x-1](https://user-images.githubusercontent.com/10109867/124916808-fde64500-dfea-11eb-94e9-e59326adc490.jpg)

![2 5 label select range@2x](https://user-images.githubusercontent.com/10109867/124916823-00e13580-dfeb-11eb-9e86-2721b48b67fa.jpg)

**Comment by Paul-Licameli** [comment]
@AnitaBats why closed?  This is meant as a design or implementation issue?
