### ISSUE TITLE
QA: Make a bug review in Bugzilla and Github

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#1196]
Check relevance.
Are all bugs reproducible with a current stable release?
Check and correct bug priority ( if necessary)

**Comment by Penikov** [comment]
Estimate: 16h

**Comment by AnitaBats** [comment]
Thanks to @petersampsonaudacity the bugs were moved from Bugzilla to Github. We review and plan the work for these bugs, so no additional effort from Pavel is required at this point

**Comment by petersampsonaudacity** [comment]
> Thanks to @petersampsonaudacity the bugs were moved from Bugzilla to Github. We review and plan the work for these bugs, so no additional effort from Pavel is required at this point

@AnitaBats - I stopped with the P2s and P3s - there are still P4s, some of which may be considered important enough for transfer to GitHub - plus some lowly ranked P5s

**Comment by LWinterberg** [comment]
[The list of P4s](https://bugzilla.audacityteam.org/buglist.cgi?action=wrap&bug_severity=Repeatable&bug_severity=RepeatableAll&bug_severity=Locale&bug_severity=Accessibility&bug_severity=MoonPhase&bug_severity=HeisenBug&bug_severity=Summary&bug_severity=Review&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&order=changeddate%20DESC%2Cbug_status%2Cpriority%2Cassigned_to%2Cbug_id&priority=P4&query_based_on=&query_format=advanced) for reference. I'm not noticing anything which feels like it requires continued attention there, but I did see bugs which I expect to be fixed as a side effect of other stuff (eg updating FFMPEG, VST3 support, Qt migration eventually, etc), and one (#581 in here) which I couldn't reproduce. So from my side I'd say it's all good.

**Comment by petersampsonaudacity** [comment]
If I get time I'll work on a pass through the P4s to see if I think any need transferring to GitHub . If that's OK?

**Comment by AnitaBats** [comment]
absolutely! thank you
