### ISSUE TITLE
QA: Make a smoke test plan for daily builds

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#1197]
Make a smoke test plan and put it on TestLink

**Comment by Penikov** [comment]
Estimate: 10h

**Comment by petersampsonaudacity** [comment]
See Suggestions for Macros improvements:  https://github.com/audacity/audacity/discussions/885

**Comment by Penikov** [comment]
The task was about macros but the smoke test plan is more relevant for now, so that is why I changed this task.

**Comment by AnitaBats** [comment]
Done
