### ISSUE TITLE
Updates: Download and launch the installer from github when user clicks install

### ISSUE THREAD

**Issue by AnitaBats** [audacity/audacity#1199]
Estimation: 6-8 hrs

**Comment by gera-gas** [comment]
Estimation: 6-8 hrs

**Comment by mikhailnov** [comment]
What about users from places from where Guthub does not allow to access it, e.g. Crimea?

**Comment by petersampsonaudacity** [comment]
@AnitaBats @gera-gas @crsib   - surely yhsi si done for 3.0.3 - and can be closed ?

**Comment by AnitaBats** [comment]
I think the code review for this is not complete yet, right @Paul-Licameli ?

**Comment by Paul-Licameli** [comment]
There was another round of review, and I expected the remaining changes to be few, but I'm still waiting the final PR.
