### ISSUE TITLE
All legal documentation should accessible easily from within the app

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1215]
All legal documentation should accessible easily from within the app

1.  The launch splash screen
2.  Help>About Audacity
3.  Menu item(s) in the Help menu

Links to go to the legal documentation on the Audacity Website.

**Comment by DavidBailes** [comment]
The privacy policy is not accessible to keyboard users from within the app. This is because the about dialog uses wxHtmlWindow controls to display information, and the links within these controls are not accessible for keyboard users.
The privacy policy could be made accessible by providing a menu item in the Help menu, as suggested by Peter.
I think that this should be fixed before 3.0.3 is released.

**Comment by petersampsonaudacity** [comment]
I agree with David's point here about accessibility -  accordingly I'll flag this as a bug

**Comment by DavidBailes** [comment]
A link to the privacy policy was added in commit 01da348. This is not accessible to keyboard users. See my previous comment.

**Comment by harshprajapati1** [comment]
Hi I want to contribute to this project. Could you please help me out in catching up?
I am a newbie and have knowledge in C++ , DS algorithms.

**Comment by petersampsonaudacity** [comment]
For non VI users this issue would appear to be fixed:

1. on initial launch of 3.0.3 the Update checking dialog has a link to the Privacy Policy
2. Error messages that phone-home have a link to the Privacy Policy
3. There is a link to the Privacy Policy from Help > About Audacity >Legal

But David Bailes' point still stands in that these links (and thus the Privacy Policy) are unattainable ny VI users and keyboard users (non-mouse & non-trackpad) - hence this bug remains open for this residual.

**Comment by petersampsonaudacity** [comment]
I have just tested on W10 with 3.0.3 latest alpha using Narrator

1.  the fill text is read out
2. the links are identified as links
3. the user can tab to the links
4. user can then hit Enter to avtivate the Link(s) - and thus can view PP or easily visit Application prefs

@DavidBailes  - is this satisfactory ?

**Comment by DavidBailes** [comment]
> I have just tested on W10 with 3.0.3 latest alpha using Narrator
> 
> 1. the fill text is read out
> 2. the links are identified as links
> 3. the user can tab to the links
> 4. user can then hit Enter to activate the Link(s) - and thus can view PP or easily visit Application prefs
> 
> @DavidBailes - is this satisfactory ?

Yes.

**Comment by petersampsonaudacity** [comment]
Closing this (and the VI residual) and the basis of David's comment.
