### ISSUE TITLE
Audacity banning anyone under 13 years of age from using this application

### ISSUE THREAD

**Issue by jg777** [audacity/audacity#1226]
**Describe the bug**
[Audacity's new privacy policy](https://www.audacityteam.org/about/desktop-privacy-notice/) now bans anyone under 13 years of age from using this application

**To Reproduce**
1. Be the shady Muse Group
2. Infect Audacity with telemetry
3. Change Audacity privacy policy to hand over all data to Law Enforcement (or other entities we do not know about)
4. Change Audacity privacy policy to ban anyone under the age of 13 years old from using Audacity

**Expected behavior**
The product should remain the same. **NO ONE SHOULD BE BANNED FROM USING IT!**

**Screenshots**

**Additional information (please complete the following information):**
 - OS: [e.g. Mac High Sierra, Ubuntu 18.04, Windows 10]
 - Version [e.g. Audacity 2.5.1]
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]

**Additional context**
Shady Muse Group should be ashamed of themselves by discriminating the use of this great application from ANYONE

**Comment by ohno9119** [comment]
This pointless age restriction violates both GPL2 and GPL3.

**Comment by ThatOneCalculator** [comment]
I used audacity when I was 11 to record piano samples and now I got into college for a double major for music performance and computer science. Fuck you audacity.

**Comment by onlytruethomas** [comment]
> This age restriction violates both GPL2 and GPL3.

Indeed.

GPL v2:
`The act of running the Program is not restricted ...`

GPL v3:
`This License explicitly affirms your unlimited permission to run the unmodified Program.`

The question now is, when will the Shady Muse Group be sued for their obvious and deliberate violation?

**Comment by ThatOneCalculator** [comment]
Do I smell a class action?

**Comment by epstein-suicider** [comment]
can you guys stop crying over some dumb ass papers literally just run audacity

**Comment by ohno9119** [comment]
Also the "offline mode" argument does not work because you have to disable a function of the application or find ways around it (example using a firewall or disconnecting from the internet) and thus that can go under restrictions on freely running the application.

**Comment by TechandMusic462** [comment]
> The question now is, when will the Shady Muse Group be sued for their obvious and deliberate violation?

I'm hoping something like the FSF could step in and take Muse to court for breaking the license. I have no idea what chances such a case has, but crowdfunding it might be an opportunity to at least try.

**Comment by ajayyy** [comment]
@TechandMusic462 Only a copyright owner can do that. They've already said that they've talked to most contributors and have gotten copyright transfered

**Comment by ThatOneCalculator** [comment]
@TechandMusic462 Ratio
> A person may be able to start a class action if he or she is injured, either financially or physically, because of the wrongful actions of a corporation and believes others were harmed in the same way. Class action lawsuits allow hundreds or potentially thousands of individuals to join together and take legal action against a person or entity in instances when it would not be financially viable for them to file individual lawsuits.

**Comment by JulianGmp** [comment]
This is the point in time where we all collectively decide to make a fork and have that be "the real version" that makes its way into the repos of GNU/Linux distros.

**Comment by ThatOneCalculator** [comment]
Most distros will ship main, not forks.

**Comment by JulianGmp** [comment]
> 
> 
> Most distros will ship main, not forks.

then make the fork the new main

**Comment by ThatOneCalculator** [comment]
Lmao, this repo will always be main whether you like it or not.

**Comment by JulianGmp** [comment]
And if more people use the fork than the "real main" that won't matter.

This might sound overly optimistic, but I can very much see distro maintainers refusing to pull newer versions of audacity.

I mean, just look at LibreOffice.

**Comment by flexagoon** [comment]
@JamesCrook other maintainers at least try defend themselves, you just go and SILENTLY close all of the issues about your shady bullshit

**Comment by GraionDilach** [comment]
@ThatOneCalculator The forks vs. main distribution is case-specific. Many distros shipped Go-oo instead of OpenOffice.org main already prior to LibreOffice (considering that LibreOffice also started from Go-oo, the transition to Libre was easier in these distros). If a fork gains enough traction/resolves an issue in a way so that the distro packager picks it up and supports it, then the fork is in and the main is out (also see Iceweasel vs Firefox in Debian).

**Comment by lemon-sh** [comment]
@JamesCrook I'd like to inform you that this issue has not been resolved. Thus, closing it was not the expected maintainer behaviour.

**Comment by CITIZENSIXTYNINE** [comment]
Closing this Issue is straight up blasfemy.

I don't understand how @JamesCrook can just close this issue without giving a concrete reason. I do understand that this place is manly for reporting bugs or suggesting features, but closing an issue addressing a mayor problem that affects the entire community is straight up disrespectfull. I hope this issue can be resolved without the need of class action lawsuits or any action that may affect the community as a whole.

**Comment by ThatOneCalculator** [comment]
I think @JamesCrook is living up to his last name :^)
