### ISSUE TITLE
RapidJSON and ThreadPool dependencies

### ISSUE THREAD

**Issue by hfiguiere** [audacity/audacity#1227]
**Describe the bug**
(building on Linux)

Audacity requires RapidJSON and ThreadPool even though network is disabled.... `-Daudacity_has_networking=Off`
It should be in the same block as the CURL dependency in the CMake files. 
And they can't be disabled with a CMake option.

**Expected behavior**
Disabling network at build time with `-Daudacity_has_networking=Off` shouldn't require RapidJSON not ThreadPool, that conan still tries to download.

**Additional context**
You have made it very hard to build Audacity without network access during the build. In a bugfix release. This is just a signle symptom.

**Comment by crsib** [comment]
This issue was fixed long ago
