### ISSUE TITLE
Memory leak when exiting Audacity 3.0.4 alpha [Windows 10]

### ISSUE THREAD

**Issue by Nuclearfossil** [audacity/audacity#1228]
**Describe the bug**
When compiling and debugging on 
- Windows 10
- compiled using Visual Studio 2022

a memory leak is observed when closing the application.

This is not observable in Release.

**To Reproduce**
1. Generate a Visual Studio Solution, using CMake/CMake-GUI.
2. Open the project in Visual Studio 2022. 
3. Compile in Debug
4. Start a Debug session
3. After Audacity opens, immediately close the application
4. You should then see  the Microsoft Visual C++ Runtime Library issue a 'Debug Error!' where "The block at 0x00000292DFC23EA0 was not allocated by _aligned routines, use free()" is observed (or a similar address)
5. Pressing 'Retry' will show you the appropriate call stack.
![image](https://user-images.githubusercontent.com/398853/124500820-4bf21300-dd75-11eb-8e6d-608c21314b70.png)
6. This appears to be an issue where ugAudioIO has entries added not using any aligned memory operations. 

**Expected behavior**
No assertions or memory leaks at the end of the application lifecycle

**Screenshots**
![image](https://user-images.githubusercontent.com/398853/124500952-865bb000-dd75-11eb-80a5-903a2c4be0be.png)

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version: 3.0.4 alpha [1f83f07cfe8e256811b5eaceb735bfaeeebdf461]

**Comment by Paul-Licameli** [comment]
Not really a leak, but a warning related to over-alignment (alignas with more than 8) in C++17.  Warning already suppressed by https://github.com/audacity/audacity/issues/1042
