### ISSUE TITLE
[GDPR] Data Protection Officer Information missing as well as Link to Privacy Policy missing from README

### ISSUE THREAD

**Issue by alexanderpas** [audacity/audacity#1229]
There is no reference in the README of this project to the Privacy Policy applicable to this project.

Additionally, there is no information available about the Data Protection Officer as defined under the GDPR.

Under the GDPR, this could lead to a fine of up to €10 million, or 2% of the firm’s worldwide annual revenue from the preceding financial year, whichever amount is higher.

**Comment by maietta** [comment]
I like this idea. To hell with them.

**Comment by bachmannn** [comment]
Users in GDPR countries can lodge a legal complaint for breaking GDPR, for example here's how

https://ec.europa.eu/info/law/law-topic/data-protection/reform/rights-citizens/redress/what-should-i-do-if-i-think-my-personal-data-protection-rights-havent-been-respected_en

**Comment by differentprogramming** [comment]
@bachmannn I'm pretty sure that would make things worse, possibly prevent the current "privacy document" from being fixed and throw a wrench into development.
They're already WAY TOO PARANOID about GDPR and similar laws.  That's the mess we're in.

**Comment by Wavy667** [comment]
Yikes. They really shot themselves in the foot

**Comment by dancojocaru2000** [comment]
> I'm pretty sure that would make things worse, possibly prevent the current "privacy document" from being fixed and throw a wrench into development.

1. If this is the way they "develop", then throw all the wrenches in.
2. Not fixing the privacy policy would just mean they will be fined out of existence.

I would personally make that complaint however the authorities in my country aren't really the best at dealing with this stuff.

**Comment by TayouVR** [comment]
as far as i know this is also not allowed per GDPR, this toggle needs to be off by default.
![image](https://user-images.githubusercontent.com/31988415/124975206-13c92980-e02e-11eb-8069-90b3febcf505.png)

**Comment by petersampsonaudacity** [comment]
The Privacy Policy is readily available from within the app and the Audacity Website:

1) App:  Help > About Audacity > Legal

2) Website:
![image](https://user-images.githubusercontent.com/50205984/128164800-5eb33cc0-fefa-4886-93d0-9eaa47bbe8fc.png)
