### ISSUE TITLE
I will be adding Audacity to my list of banned applications for being spyware.

### ISSUE THREAD

**Issue by maietta** [audacity/audacity#1231]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by maietta** [comment]
Your last name says it all.

**Comment by maietta** [comment]
Every time you close this, I will re-open. I don't take kindly to censorship.

**Comment by maietta** [comment]
Re-opened.

**Comment by LWinterberg** [comment]
For people coming upon this randomly, note that the spyware accusation got addressed in #1353
