### ISSUE TITLE
What the Hell -- PRIVACY

### ISSUE THREAD

**Issue by ata-star** [audacity/audacity#1235]
Read this: https://www.audacityteam.org/about/desktop-privacy-notice/
Watch This: https://youtu.be/mceXl_ayl8s

**Comment by shoogle** [comment]
Check for updates is the only networking feature enabled by default (it is opt-out while the others are opt-in).

This, and your IP address, is the only information sent during a check for updates:

```http
GET /feed/latest.xml HTTP/1.1
Host: updates.audacityteam.org
Accept: */*
Accept-Encoding: deflate, gzip
User-Agent: Audacity/3.0.3 (Windows 10_0_19042; x64)
```

You can see this in the source code [here](https://github.com/audacity/audacity/blob/87d94fe24918fb155feab831f52ba5e24e4db646/src/update/UpdateManager.cpp#L69) and [here](https://github.com/audacity/audacity/blob/1ac4df1f83b57d729806a06c377068edf8449b51/libraries/lib-network-manager/curl/CurlHandleManager.cpp#L224-L239). The IP address is stored on the server as a hash and becomes irretrievable after 24 hours when the salt is discarded.

Discussion in #1225
