### ISSUE TITLE
Privacy policy is a violation of GPL-3 and is unfair

### ISSUE THREAD

**Issue by Get-DevVed-YT** [audacity/audacity#1236]
The recent changes to the privacy policy are unfair and non-compliant with GPL-2.

By restricting access to those 13+, you are prohibiting probably many minors who were using Audacity to use it anymore.
GPL-2 grants the right for everyone to use it under the license rules. 
By restricting access to those 13+, you are breaking the terms of the license under which Audacity is sourced under.

My solution would be to make telemetry opt-in. This way minors can still use the program but those who want to help Audacity can opt-in telemetry data. 

Also, I really wonder what an audio program has to share with the government...
You need to be upfront on what specific data you share with the government. 

One more thing. Don't think that closing the issues addressing this is going to help you. It's not.

**Comment by GalaxyGamingBoy** [comment]
Very true

**Comment by DevElonCoin** [comment]
Use Sneedacity instead

**Comment by Odyssey346** [comment]
I wonder what the Audacity developers were on when they decided adding telemetry and data collection to a fucking audio program was a good idea.

**Comment by craigbarnes** [comment]
> Use Sneedacity instead

Based.

![1625330456263](https://user-images.githubusercontent.com/494077/124586315-33096080-de4e-11eb-8377-373962e006fe.jpg)

**Comment by D0nnieD4rk0** [comment]
welp we all knew this would happen sooner or later, although all u rly have to do is block it from accessing the internet

**Comment by Axel-Erfurt** [comment]
I believe that audacity  can no longer be part of Linux distributions in the future with this privacy policy.

**Comment by luke2m** [comment]
I started using Audacity when I was under 13. These policy changes are harmful and obviously violate the GPL.

**Comment by J0sueTM** [comment]
For sure. There's probably forks that still hold on old audacity's ideology.

**Comment by Wavy667** [comment]
Imagine having an age rating on an open-source audio editor.

Like seriously?

**Comment by Summertime** [comment]
A company can't violate their own license.

**Comment by AlgoRythm-Dylan** [comment]
> 
> 
> A company can't violate their own license.

Forgive my superficial understanding of software licensing but I am under the impression that if Audacity uses any libraries that are licensed under GPL, they must also license it under GPL, as per GPL requirements, which makes breaking GPL illegal. Or perhaps more accurately, it makes using any libraries licensed under GPL illegal?

**Comment by nulldg** [comment]
>If anyone else wants to get around this, try downloading Audacity from this fork I found.
https://github.com/temporary-audacity/audacity

The latest windows build of this fork is still outdated and has telemetry in it. If you want people to avoid the telemetry, don't advice people use this fork until the collaborators have actually released a no-telemetry build.

**Comment by Get-DevVed-YT** [comment]
> > If anyone else wants to get around this, try downloading Audacity from this fork I found.
> > https://github.com/temporary-audacity/audacity
> 
> The latest windows build of this fork is still outdated and has telemetry in it. If you want people to avoid the telemetry, don't advice people use this fork until the collaborators have actually released a no-telemetry build.

Apologies. Do not install from this fork. Wait for a valid non-telemetry fork

**Comment by falkTX** [comment]
> > If anyone else wants to get around this, try downloading Audacity from this fork I found.
> > https://github.com/temporary-audacity/audacity
> 
> The latest windows build of this fork is still outdated and has telemetry in it. If you want people to avoid the telemetry, don't advice people use this fork until the collaborators have actually released a no-telemetry build.

This is false. You can see from the commits in the repo that telemetry and sentry (crash reporting) were completely removed, not just disabled.

**Comment by nulldg** [comment]
> This is false. You can see from the commits in the repo that telemetry and sentry (crash reporting) were completely removed, not just disabled.

Please look at the commit of the release `Audacity-3.0.3-RC2` ("Always run CPack, even on Windows in release mode"). Every fork has this commit https://github.com/tenacityteam/tenacity/commit/84d5e63dbc0f23da75202bb434f04654984d2081

The commit on the tenacity fork is from BEFORE the telemetry removal commit. https://github.com/tenacityteam/tenacity/commit/bbf352d36d725335962718f91fc3591a1037f39b

**Comment by Dell-Glitch** [comment]
They restricted because to 13+ because with telemetry they don't want to get a lawsuit because of underage/minors crap

**Comment by AlgoRythm-Dylan** [comment]
> They restricted because to 13+ because with telemetry they don't want to get a lawsuit because of underage/minors crap
Yes, that would be the issue(s)

**Comment by yash-fn** [comment]
I used audacity at the age of 10. Granted I knew almost nothing but it was my first exposure to audio editing and I created many remixes from songs of that era. This is morally wrong and reeks of corporate hubris blinding leadership from the people that actually use their products. Not to mention a clear violation of GPL. Many people contributed code to this project and you therefore have no right to determine how that code, however insignificant, is licensed.

**Comment by maxgerhardt** [comment]
>They restricted because to 13+ because with telemetry they don't want to get a lawsuit because of underage/minors crap

Imagine as a company having the choice between adding telemtry to the program and requiring every user to be 13+ to not be sued and letting children use your software (as is being done by educators for a very long time), and choosing the first one. The lack of understanding of the project, its uses, and the [4 essential freedoms](https://www.gnu.org/philosophy/free-sw.en.html) postolated by the GPL is staggering.

**Comment by EndlessEden** [comment]
> 
> 
> > This is false. You can see from the commits in the repo that telemetry and sentry (crash reporting) were completely removed, not just disabled.
> 
> Please look at the commit of the windows release `Audacity-3.0.3-RC2` ("Always run CPack, even on Windows in release mode"). Every fork has this release [tenacityteam/tenacity@84d5e63](https://github.com/tenacityteam/tenacity/commit/84d5e63dbc0f23da75202bb434f04654984d2081)
> 
> The commit on the tenacity fork is from BEFORE the telemetry removal commit. [tenacityteam/tenacity@bbf352d](https://github.com/tenacityteam/tenacity/commit/bbf352d36d725335962718f91fc3591a1037f39b)
> [tenacityteam/tenacity@Audacity-3.0.3-RC2...master](https://github.com/tenacityteam/tenacity/compare/Audacity-3.0.3-RC2...master)

This was already handled in a manual edit. - if there is further issues, make a issue on their issue tracker as they are unaware.

**Comment by sunnyjim5** [comment]
> I wonder what the Audacity developers were on when they decided adding telemetry and data collection to a fucking audio program was a good idea.

Its likely sure they were smoking crack made in someones toilet

**Comment by waltercool** [comment]
> They restricted because to 13+ because with telemetry they don't want to get a lawsuit because of underage/minors crap

Or maybe they could just make telemetry optional, for people above 13yo...

**Comment by FeedFall8** [comment]
> 
> 
> Imagine having an age rating on an open-source audio editor.
> 
> Like seriously?

facts

**Comment by petersampsonaudacity** [comment]
The revised Privacy Policy released as part of 3.0.3 has no age restriction
