### ISSUE TITLE
GPL3.0 Violation

### ISSUE THREAD

**Issue by peepopoggers** [audacity/audacity#1242]
The terms of service is a GPL3.0 violation and it breaks the terms by restricting access to those of younger age.
This violates legal terms of the code and is illegal! 

Fix this or the program will lose popularity.
Also lose the telemetry stuff, or the community will never get your trust back.

;)

**Comment by peepopoggers** [comment]
#1236

**Comment by ODIRFY** [comment]
So, true! I will never use original audacity again.

**Comment by Drakeo** [comment]
It is a waste of ink Team audacity.  It is under the GPL.
you may recommend an age use. but your blowing wind.
Stop wasting key strokes. 
 This policy not needed after they passed all IP can collect and sell data.  In the USA.

**Comment by fcolecumberri** [comment]
Just as a sidenote, you should change the title to `GPL2 Violation` since this is not GPLv3 https://github.com/audacity/audacity/blob/master/LICENSE.txt

**Comment by petersampsonaudacity** [comment]
The age restriction has been removed from the final Privacy Policy released as part of Audacity 3.0.3
