### ISSUE TITLE
Audacity will fail to start if TEMP location is unwritable

### ISSUE THREAD

**Issue by crsib** [audacity/audacity#1243]
**To Reproduce**
1. Set the "Temporary files location" to an unwritable location
2. Realauch Audacity
3. Audacity will fail with Can't_open_new_empty_project error

**Expected behavior**
Audacity opens without issues

**Comment by AyHa1810** [comment]
Stfu and fix the spyware and GPL-v2 violation bullshit bruh

**Comment by gera-gas** [comment]
I caught this moment, but in this case, Audacity continues to work fine, just showed an error window by `ShowExceptionDialog`.
1. What I can do in this case
1.1 Just checking Temp directory on unwritable, then showing a message with it information, that can be more useful for user (after reading this message, user can fast solve this problem by change directory in preferences).
1.2 or leave as now.

2. What I should be doing yet (necessarily)
Seems this problem also actual for all directories in preferences, that can be used for data output. I need to check all directories for this case.

**Comment by petersampsonaudacity** [comment]
@gera-gas  I think you also need to trap the use case in Directories preferences where the user types "C:\" 
just the same as you trap the use case where the user users the Browse button to make C: a default directory.

**Comment by crsib** [comment]
We still need a fallback. I can set the directory in the config manually or the directory may become unwritable later on

**Comment by petersampsonaudacity** [comment]
> We still need a fallback. I can set the directory in the config manually or the directory may become unwritable later on

Yes indeed, I agree - a better example is that it may have been set in an earlier version of Audacity (that's how I was testing the fallback earlier).

But I hope you agree we need to trap both use cases at point-of-use in Directories prefs?

**Comment by crsib** [comment]
I surely do. 

There is also a bug in FFmpeg location dialog, which ignores keyboard input completely.

**Comment by petersampsonaudacity** [comment]
> There is also a bug in FFmpeg location dialog, which ignores keyboard input completely.

OOH - is that already logged, or do you need to log it ?

**Comment by crsib** [comment]
I even do have a fix for it xD

**Comment by petersampsonaudacity** [comment]
You are GOOD @crsib   🥇

**Comment by jounih** [comment]
How about something like this?

![image](https://user-images.githubusercontent.com/10109867/125305052-f940ca00-e325-11eb-85c5-3ca2dd9ee4ca.png)

**Comment by petersampsonaudacity** [comment]
> How about something like this?

Looks good to me

**Comment by petersampsonaudacity** [comment]
Testing on w10 with Audacity_Windows_64bit_1037187455_50f8e10

Yes I get the error new error message with the link to Directories Prefs - but if I ignore that and just dismiss it with the "OK" button then Audacity appears to launch OK - but if I try to record, import or generate I get the following warning 
![image](https://user-images.githubusercontent.com/50205984/125944619-5d3d0368-5d5f-4c0b-8125-4d539a1c4ea8.png)
ET phoned home with the OK button on the message.

This message will be totally opaque to most users and offers them no guidance on what to do to redress the situation


Steps to reproduce
1) in 3.0.3 set temp directory to be c:\
2) exit 3.0.2
3) launch 3.3.3
4) Observe the new error message telling you that the temp directory is invalid
5) ignore the advice to go to Directories prefs
6) press OK
7) Observe Audacity launches
8) Press Record
9) Observe the warning as shown above

**Comment by petersampsonaudacity** [comment]
And because the reset of temp directory only takes t effect after relaunch ...

If in the new message you accept the advice and click the link to go to Directories prefs and reset it to a writeable location.
Then Audacity remains open and you then get the phone-home error messages if you try to use Audacity.

This ENH is Bugzilla has some bearing on this
https://bugzilla.audacityteam.org/show_bug.cgi?id=2548
Bug 2548 - ENH: changed temporary directory location should be implemented immediately - not after restart

**Comment by AnitaBats** [comment]
Cannot reproduce, fixed
