### ISSUE TITLE
GPL2 license broken due to age restrictions.

### ISSUE THREAD

**Issue by GalaxyGamingBoy** [audacity/audacity#1244]
Repost because I said. I Won't stop till you reply. Do NOT Close it I will repost it.

Describe the bug
Your privacy policy is the bug.

To Reproduce
Hhmmmmm
Read your own privacy policy! It brakes the GPL2 License as previously said!

Expected behavior
Backstabbing yourself and losing millions of users. Also maintainers Do not Close this issue to hide. I can and WILL repost this.
Schools that use the software won't use it. Maybe add an opt in or opt out of data collection

Additional information (please complete the following information):
Fix it now

**Comment by awslabspl** [comment]
I fully agree. Seriously. Its outrageious. Not that company bought Audacity, this can ( and should ) happen. Outrageious is that they **ignore** current users, commiters, ( possible ) developers......... everyone.

**Comment by danielteberian** [comment]
> I fully agree. Seriously. Its outrageious. Not that company bought Audacity, this can ( and should ) happen. Outrageious is that they **ignore** current users, commiters, ( possible ) developers......... everyone.

It is quite outrageious, isn't it? It is also outrageous, but that goes without saying.

**Comment by zunjae** [comment]
> Schools that use the software won't use it. 

They will simply stick to an older version. Don't worry, schools will be fine

**Comment by Megalomaniak** [comment]
@awslabspl nobody bought the software, what was purchased was the trademark/IP. The logo graphic, the name 'Audacity'. Feel free to use a fork if you don't trust this source here. :shrug:

**Comment by ed6767** [comment]
@GalaxyGamingBoy - while I agree with you, spamming issues is not constructive and fragments discussion. You don't need to be uncivil. As explained by @Tantacrul, this issue is out of the main maintainers hands and an issue with Muse Group. They aren't trying to "hide" anything.
