### ISSUE TITLE
VOTING! For the new fork

### ISSUE THREAD

**Issue by JYamihud** [audacity/audacity#1245]
There are 1.6k forks of Audacity as of today. And the number grew with 200 forks with in last day. The forks exist, we need to choose one. Leave the Muse Group alone. They may do what ever they want. It shouldn't bother us anymore.

Libre Office was ones a fork of Open Office, since it was sold to Oracle. And people didn't like it. Libre Office was the chosen fork.

I opened a voting page on LBRY [here](https://odysee.com/@blenderdumbass:f/Voting-for-the-new-audacity-fork:4). LBRY is a Free Software, block chain network for publications. I'm afraid an issue here is not safe, Muse Group might close it.

**Comment by Remzi1993** [comment]
I think: https://github.com/temporary-audacity/audacity is the fork everyone got behind on, they are voting now for a new name for the project and software.

**Comment by grubeli** [comment]
https://github.com/tenacityteam/tenacity

**Comment by imachug** [comment]
Hey, I want you all to know that the issue tracker of temporary-audacity aka Tenacity seems to be censored with no comment, along with quite a long interesting discussion (see https://github.com/tenacityteam/tenacity/issues/93, or a backup here: https://github.com/imachug/talk/issues/3). Please consider https://github.com/SartoxOnlyGNU/audacium instead.

**Comment by Emobe** [comment]
Just let nature take it's course as with all forks. It's not going to be sorted in one day, nor a week. A fork will prevail just let it naturally happen.

**Comment by J0sueTM** [comment]
There's no need to vote. Just pick one and go with it.

**Comment by ishimotoshinobu** [comment]
https://github.com/Sneeds-Feed-and-Seed/sneedacity

**Comment by MrRoy** [comment]
The most active fork right now is https://github.com/Sneeds-Feed-and-Seed/sneedacity and it doesn't have any drama.

**Comment by dontfwiththestream** [comment]
yes, the sneedacity team is not a closed dev team like tenacity and isn't filled with drama

**Comment by jaw20** [comment]
Audacium and Sneedacity are two acceptable forks for consideration.

**Comment by nulldg** [comment]
There is no need for a vote. Just pick whatever fork(s) you like and support them.

In my opinion:
- **Sneedacity** has a Simpsons reference for a name... but it's also the most active fork and has the best chances. It has also removed all of the telemetry properly and plans to remove conan and update wxWidgets, something I haven't seen in other forks yet.
- **Audacium** is also very good and much easier to take seriously, but it's currently run by one person and needs more contributors. Please help it out if you can.

**Comment by falkTX** [comment]
Sneedacity is an obvious joke/satire and not meant to be taken seriously. :facepalm: 

After they get tired of playing around and harassing other forks, things will calm down and things can finally move on from there.

For now it is just better to wait.

**Comment by MrRoy** [comment]
> Sneedacity is an obvious joke/satire and not meant to be taken seriously. 🤦
> 
> After they get tired of playing around and harassing other forks, things will calm down and can finally move on from there.
> 
> For now it is just better to wait.

Why shouldn't it be taken seriously? It's very active right now, I don't see why a simpsons reference would make it "not serious"

**Comment by notevenaperson** [comment]
Sneedacity may have started as a lighthearted joke, but it has picked up so much steam it has become a legitimate option.

**Comment by notevenaperson** [comment]
> There is no need for a vote. Just pick whatever fork(s) you like and support them.
> 
> In my opinion:
> 
>     * **Sneedacity** has a Simpsons reference for a name... but it's also the most active fork and has the best chances. It has also removed all of the telemetry properly and plans to remove conan and update wxWidgets, something I haven't seen in other forks yet.
> 
>     * **Audacium** is also very good and much easier to take seriously, but it's currently run by one person and needs more contributors. Please help it out if you can.

Joining Audacium and Sneedacity would unite the efforts of the majority of *actual* code contributors, IMO.

**Comment by dascar5** [comment]
There is no doubt Sneedaucity is the true fork. Sneed supremacy can not, will not, and must not be stopped
![sneed](https://i.ytimg.com/vi/qeTw0c6vxO8/mqdefault.jpg)

**Comment by RandomErrorMessage** [comment]
> Sneedacity is an obvious joke/satire and not meant to be taken seriously. 
> 
> After they get tired of playing around and harassing other forks, things will calm down and can finally move on from there.
> 
> For now it is just better to wait.

Sneedacity is a very serious and active Audacity fork. It is not encumbered by the bike-shedding, drama and lack of actual developers that other Audacity forks are currently experiencing.

While I appreciate and use your pro-audio software, I'd also appreciate it if you took a more objective look at this. The uncritical and ignorant tribalism isn't a good look.

**Comment by gakzerk5** [comment]
Sneedacity
Or we can merge Sneedacity and Audacium into something Sneed related
However
The Sneed name is non-negotiable

**Comment by ecoflute** [comment]
> Sneedacity is an obvious joke/satire and not meant to be taken seriously. facepalm
> 
> After they get tired of playing around and harassing other forks, things will calm down and can finally move on from there.
> 
> For now it is just better to wait.

Just because of the name? The FOSS scene is full with robust software with silly names, such as GNU's Not Unix and WINE Is Not an Emulator.

**Comment by parkbanks** [comment]
Also, I bought the sneedacity.com, sneedacity.org, and sneeda.city domains, and will start development on a main website there. So there's plenty of room for growth with that project.

**Comment by festadurador** [comment]
Sneedacity has a great potential since it has been the most active at this moment, telemetry has already been completely removed and is fully functional and buildable (as far as I know), the name is a reference to a joke but it doesn't mean it IS a joke.

**Comment by dascar5** [comment]
I suggest we report everyone abusing sneedacity and the devs working on it, I already sent reports for couple of people. Tenacity has a convicted pedophile, scam artist and a false flagger running it, yet no one is abusing them. Each to their own, but Sneedacity ACTUALLY HAS people working on it. Case closed.

**Comment by bl-ue** [comment]
Is anyone aware of https://github.com/tenacityteam/tenacity?

**Comment by dascar5** [comment]
> Is anyone aware of https://github.com/tenacityteam/tenacity?

The "devs" of that fork are extremely toxic, drama driven, and they're web devs, none of them has any clue about C, C++ or audio engineering.

**Comment by RandomErrorMessage** [comment]
At this point I'm not sure if tenacity has any developers, it seems entirely "staffed" by community manager-esque people who have done a spectacularly poor job of community management. It comes off more like a PR stunt with a profit motive (the founder stated he wanted to use the fork to "pay his rent").

**Comment by bl-ue** [comment]
Based on the profiles of the maintainers of Sneedacity, the project looks most unpromising to me.  One of the maintainers _joined GitHub yesterday._

Where's their story?  How can I tell that they're in earnest and the other forks aren't?

**Comment by dascar5** [comment]
> Based on the profiles of the maintainers of Sneedacity, the project looks most unpromising to me. One of the maintainers _joined GitHub yesterday._
> 
> Where's their story? How can I tell that they're in earnest and the other forks aren't?

Go to bed @cookiengineer, you suck at falseflagging.

**Comment by ishimotoshinobu** [comment]
> Based on the profiles of the maintainers of Sneedacity, the project looks most unpromising to me. One of the maintainers _joined GitHub yesterday._
> 
> Where's their story? How can I tell that they're in earnest and the other forks aren't?

I'd show my history of software development but GitHub janni... I mean moderators blocked me. I've been doing quite a lot software in c and c++ and I'm pretty sure the team of sneedacity can make fork better!

**Comment by bl-ue** [comment]
we'll see (leaving this thread now)

**Comment by nek0bit** [comment]
I think that we can do this! We should really set home on sneedacity, and it actually (and ironically, despite all this nonsense drama) has the least drama. The guy behind it who created also seems friendly and is willing to cooperate with non-channers or those not interested in the meme aspect(In fact, Tox was made my /g/ users; /g/ has a pretty clean track record for making collaborative software)

As intended, this whole name raid thing wasn't to start drama to begin with, cookie cutter decided to take it extremely personally, which caused it's own drama. At best, the name wouldn't be picked and it was some other name, nothing bad would've happened... but here we are

**Comment by SchizophrenicToilet** [comment]
From what I have seen more work has been done on sneedacity than any other forks. They removed telemetry, fixed bugs and you can build it on most platforms, someone's even working on a choco package for Windows and a ppa for Ubuntu based distributions.
Despite all the drama, they have been the most professional since the beginning and they actually have C and C++ knowledge.
I mean at the end of the day you choose the fork you want of course but I know which one I'll be using and if you can help sneedacity that would be great.

**Comment by 0xKap** [comment]
I'm just here to show my support for Sneedacity - Cookiemonster is a sociopathic baby bitch. 

/g/ ❤️

**Comment by InventorXtreme** [comment]
Is there any way to create a poll on a website other than odysee, I have no account for it, it is janky, and apparently I have to pay money to be able to vote. When I try to pay, it states that the USA is not a supported region. Either I am very stupid, or the site is absolutely terrible to make polls on.

**Comment by JYamihud** [comment]
> Is there any way to create a poll on a website other than odysee, I have no account for it, and apparently I have to pay money or wait to be verified (which may take days) to be able to vote. When I try to pay, it states that the USA is not a supported region. Either I am very stupid, or the site is may not be a good choice to make polls on.

InventorXtreme You don't have to verify Odysee account for making a comment. You need to make small channel. With a name. ( A user name )

**Comment by sneedsfeednseed** [comment]
https://github.com/Sneeds-Feed-and-Seed/sneedacity
This fork is pretty active and has no drama so its pretty good right now

**Comment by binex-dsk** [comment]
Sneedacity has no drama or moderators censoring issues, along with many devs with actual skill in C[++] (unlike tenacity), I think this should be the new fork

**Comment by taylordwright44** [comment]
The sign is a subtle joke. The shop is called "Sneed's Feed & Seed", where feed and seed both end in the sound "-eed", thus rhyming with the name of the owner, Sneed. The sign says that the shop was "Formerly Chuck's", implying that the two words beginning with "F" and "S" would have ended with "-uck", rhyming with "Chuck". So, when Chuck owned the shop, it would have been called "Chuck's Fuck and Suck".

**Comment by RandomErrorMessage** [comment]
Oh wow, haha, how did The Simpsons get away with this one?
