### ISSUE TITLE
Privacy Policy is hard to find on the Audacity Website

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1248]
**Describe the bug**
The Privacy Policy is hard to find on the Audacity Website

**To Reproduce**
1. Go to the Audacity website
2. Try to locate the Privacy Policy
3. Observe: (eventually) it is under the "Contact" tab

**Expected behavior**
I would expect to see it located under the "About" tab - along with similar related entries: License, Terms of Service, Voluntary Product Accessibility Template etc, 

It is not really a "Contact" issue ...

**Screenshots**

![image](https://user-images.githubusercontent.com/50205984/124727434-9d7dd780-df06-11eb-912f-6091bc046cd0.png)

![image](https://user-images.githubusercontent.com/50205984/124727679-d74ede00-df06-11eb-9e8a-ba9b736760e2.png)

**Comment by danielfleischer** [comment]
It's gone; the privacy policy in the "Contact" tab is regarding mailing lists; the privacy policy we are talking about is now missing and nowhere to be found.

**Comment by petersampsonaudacity** [comment]
@Tantacrul  - Looking at the Audacity Website today on the About tab I see:
![image](https://user-images.githubusercontent.com/50205984/126901139-85521fb1-eb8d-46d7-b731-860ce3aa1aab.png)

a) note that the Privacy policy(s) are shown on the right in the "About" links - but they have no corresponding links in the About dropdown menu (as all the other entries do).

b) And personally I would place the privacy policies as the bottom two entries in both the drop-down menu and the "About" links list - leaving the much more important "News" at the top of the menu and list.

**Comment by petersampsonaudacity** [comment]
@Tantacrul And the Error Reporting Privacy
![image](https://user-images.githubusercontent.com/50205984/126901453-bf055f07-6b1f-4a00-9898-9822c3b05d2a.png)
Is just a placeholder and NOT a policy document.

Since 3.0.3 has error checking I would have thought that this Error Reporting Privacy Notice should be properly extant on the Website prior to 3.0.3 release.

**Comment by petersampsonaudacity** [comment]
>And note that if you click on the Privacy Policy link in an error message - the link takes you to the "Desktop Privacy Notice" 
>and NOT the "Error Reporting Privacy Notice" - should this logged as a new bug ?

Logged as GitHub Issue #1361

**Comment by petersampsonaudacity** [comment]
In Issue #1248 @crsib wrote:
>This is not a bug, there will be single privacy policy for error reporting and updates

 In which case the separate link to "Error Reporting Privacy Notice"  needs removing from the Website

**Comment by shoogle** [comment]
The public link to the privacy policy has now been published along with the release of 3.0.3.

![image](https://user-images.githubusercontent.com/11011881/127074672-0c0b9502-0626-41d5-aaa6-a300da5bb0a7.png)

The ordering of the About list has also been fixed.

![image](https://user-images.githubusercontent.com/11011881/127074705-1af6205f-4014-4e65-aed9-05d6105937b0.png)
