### ISSUE TITLE
(Maybe) Age restrictions doesn't break GNL (and correct some misconceptions) 

### ISSUE THREAD

**Issue by DooDooDot** [audacity/audacity#1249]
From [https://www.gnu.org/licenses/gpl-3.0.html]():

> When we speak of free software, we are referring to freedom, not price. Our General Public Licenses are designed to make sure that you have the freedom to distribute copies of free software (and charge for them if you wish), that you receive source code or can get it if you want it, that you can change the software or use pieces of it in new free programs, and that you know you can do these things.

GPL refer to freedom of distribution and modification, says nothing about freedom of use for all ages.

The age restriction is **NOT** due COPPA but GDPR. 

From [https://gdpr-info.eu/art-8-gdpr/]()

> Where point (a) of Article 6(1) applies, in relation to the offer of information society services directly to a child, the processing of the personal data of a child shall be lawful where the child is at least 16 years old. Where the child is below the age of 16 years, such processing shall be lawful only if and to the extent that consent is given or authorised by the holder of parental responsibility over the child. Member States may provide by law for a lower age for those purposes provided that such lower age is **not below 13 years**.

But Audacity new terms are still an issue, tho.

**Comment by Dymstro** [comment]
Both the GPLv2 and GPLv3 have parts that say that running the software is not restricted
GPLv2: `The act of running the Program is not restricted`
GPLv3: `This License explicitly affirms your unlimited permission to run the unmodified Program.`

While age is not explicitly mentioned, I don't see why this would not apply to someone under a certain age.

https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html
https://www.gnu.org/licenses/gpl-3.0.en.html

**Comment by DooDooDot** [comment]
> Both the GPLv2 and GPLv3 have parts that say that running the software is not restricted
> GPLv2: `The act of running the Program is not restricted`
> GPLv3: `This License explicitly affirms your unlimited permission to run the unmodified Program.`
> 
> While age is not explicitly mentioned, I don't see why this would not apply to someone under a certain age.

Gnu is a copyleft license, just the opposite of a copyright, this gives people unlimited permission to run the unmodified Program not restricted and without legal consequences.

Not that “everyone of every age can use it", thing that people that are on Github should know.

**Comment by josephbburg** [comment]
Yes, it is explicitly "everyone can use ur unrestricted". You went from "maybe" to definitely pretty fast. Makes me wonder.

**Comment by DooDooDot** [comment]
it's uselessness speak with 10 ignorants that disliked the obvious and a troll

**Comment by MrRoy** [comment]
> 2. Basic Permissions.
> All rights granted under this License are granted for the term of copyright on the Program, and are irrevocable provided the stated conditions are met. This License explicitly affirms your unlimited permission to run the unmodified Program. 

It's pretty obvious, to me anyway, that, by `This License explicitly affirms your unlimited permission to run the unmodified Program.`, and specifically, by `unlimited`, it means that anyone, regardless of race, gender, age, sexual orientation or any other factor can use this program, unrestricted.
So yes, the new ToS are in violation of the GPL.

**Comment by DooDooDot** [comment]
> It's pretty obvious
It's not so "obvious“ people are mistaking license wording for start a riot and troll or play the white knights.
At this point, think what you want.

**Comment by MrRoy** [comment]
>It's not so "obvious“

`unlimited` means unlimited, it means no restrictions whatsoever.

>people are mistaking license wording for start a riot and troll or play the white knights.

What riots are you talking about?

>At this point, think what you want.

I will, but why open this issue if you are not opened to discussing it? You might as well close this issue.

**Comment by Qtamo** [comment]
> this gives people unlimited permission to run the unmodified Program
> 
> Not that “everyone of every age can use it"

I'm trying (and failing) to understand your argument, aren't you contradicting yourself in the same post? The GPLv2 and GPLv3 seem pretty clear to me.

> GPLv2: `The act of running the Program is not restricted`
> GPLv3: `This License explicitly affirms your unlimited permission to run the unmodified Program.`

I'm interpreting "is not restricted" (for GPLv2) and "your unlimited permission" (for GPLv3) as anyone can use it, otherwise running the program would be restricted (by age) and the permission would be limited (by age)?

**Comment by josephbburg** [comment]
"Everyone who disagrees with me is an ignorant troll"
OK, you got me with that one. I can't argue with that.

**Comment by fcolecumberri** [comment]
> From https://www.gnu.org/licenses/gpl-3.0.html:
> 
> > When we speak of free software, we are referring to freedom, not price. Our General Public Licenses are designed to make sure that you have the freedom to distribute copies of free software (and charge for them if you wish), that you receive source code or can get it if you want it, that you can change the software or use pieces of it in new free programs, and that you know you can do these things.
> 
> GPL refer to freedom of distribution and modification, says nothing about freedom of use for all ages.
> 
> The age restriction is **NOT** due COPPA but GDPR.
> 
> From https://gdpr-info.eu/art-8-gdpr/
> 
> > Where point (a) of Article 6(1) applies, in relation to the offer of information society services directly to a child, the processing of the personal data of a child shall be lawful where the child is at least 16 years old. Where the child is below the age of 16 years, such processing shall be lawful only if and to the extent that consent is given or authorised by the holder of parental responsibility over the child. Member States may provide by law for a lower age for those purposes provided that such lower age is **not below 13 years**.
> 
> But Audacity new terms are still an issue, tho.

I don't understand why you are citing GPLv3 when this is GPLv2

> > It's pretty obvious
> 
> It's not so "obvious“ people are mistaking license wording for start a riot and troll or play the white knights.
> At this point, think what you want.

**obvious** is the fact that you are mistaking the license, you have not read the entire license and then argue that others mistakes the wording. GPLv2: `The act of running the Program is not restricted` means The act of running the Program is not restricted by age (among other things).

> it's uselessness speak with 10 ignorants that disliked the obvious and a troll

useless is arguing the license with someone that has not read the license file https://github.com/audacity/audacity/blob/master/LICENSE.txt

P.S.: BTW you are not “speaking” you are writing.

**Comment by alevesely** [comment]
> From https://gdpr-info.eu/art-8-gdpr/
> 
> > Where point (a) of Article 6(1) applies, [...] such lower age is **not below 13 years**.
> 
> But Audacity new terms are still an issue, tho.

It is still not clear which new terms imply that audio recording is personal data.

**Comment by petersampsonaudacity** [comment]
The final revised Privacy Policy released as part of 3.0.3 has no age restriction
