### ISSUE TITLE
Please stop helping the evil people!

### ISSUE THREAD

**Issue by ghost** [audacity/audacity#1254]
BOYCOTT the evil terrorists at the uk gov. Don't protect their evil "national" "service".
BOYCOTT google for promoting the uk's evil "national" "service" and for promoting people who work for them. STOP USING ALL GOOGLE PRODUCTS. Google is a fake clown (and so is microsoft/yandex/duckduckgo etc. etc.) WHO ARE NOT ENGINEERS. They are fake clowns who claim to be Engineers, WHEN THEY ARE NOT, AND WILL NEVER BE CLOSE TO ENGINEERS.
BOYCOTT people who mention other people using "titles".
DO NOT give ANY telemetry to the evil terrorists and arrogant people.

bye bye.....

**Comment by TheMisir** [comment]
Wtf 😅 is this IT a kind of "anti-vaccine" campaign?

**Comment by peepopoggers** [comment]
?
