### ISSUE TITLE
Importing is slow for large Audacity projects.

### ISSUE THREAD

**Issue by crsib** [audacity/audacity#1266]
**Describe the bug**

Importing is slow if `project.doc` BLOB is large and consumes an immense amount of memory. This issue was discovered when working on helping https://forum.audacityteam.org/viewtopic.php?f=46&t=118979.

Importing required > 2Gigs of RAM thus it broke WIN32 builds.

**To Reproduce**
1. Get an aup3 file with the large project 
2. Open it

**Expected behavior**
Converting binary XML used in Audacity to normal XML should be quick and memory constrained.

**Comment by LWinterberg** [comment]
has this been fixed by your recent serialization/deserialization efforts?
