### ISSUE TITLE
Seeking Clarification on GPL licensing

### ISSUE THREAD

**Issue by mariaWitch** [audacity/audacity#1270]
The wording for Audacity's GPL licensing is inconsistent across it's two official sources. Specifically, the Audacity website states that: (https://www.audacityteam.org/about/license/)
>You may also copy, distribute, modify, and/or resell Audacity, under the terms of the GNU General Public License (GPL) as published by the Free Software Foundation – either version 2 of the License, or (at your option) any later version. In granting you this right, the GPL requires that the source code you distribute is itself available under the GPL. If you distribute or recommend Audacity in any way, please cite our trademark by referring to Audacity as “Audacity(R)”.

However no such clause exists in the provided license found in the audacity repository. So my question is, are forks of audacity allowed to update the license to GPLv3 at their own permission without needing to jump through any hoops or red tape as stated on the audacity website or are we required to maintain the GPLv2 license?

Additionally, the site has had this wording since at least 2015 (https://web.archive.org/web/20150620220728/http://audacityteam.org/about/license) which predates this commit here: https://github.com/audacity/audacity/commit/e78d209a68d46a529437f85a6f17c2a9581a8815

Any clarification or official statement on this matter would be greatly appreciated.

**Comment by imachug** [comment]
What bothers me is that according to readme Audacity has been licensed under GPL 2 or later for 11 years, but some source headers say the source is GPL 2 only and on #932 the maintainers said some code is not GPL 2+.

**Comment by SteveDaulton** [comment]
> What bothers me is that according to readme Audacity has been licensed under GPL 2 or later for 11 years, but some source headers say the source is GPL 2 only and on #932 the maintainers said some code is not GPL 2+. Either maintainers are lying or something is very wrong with licensing.

The wording in the  original Audacity license was:
```
Note: Audacity is distributed under the terms of the GNU GPL.
This includes everything in the source code distribution
except code in the lib-src directory.  Code in the lib-src
directory may be released under a different license
(which is GPL-compatible).
```
So strictly speaking, the later license that said `Note: Audacity is distributed under the terms of the GNU GPL Version 2.` was wrong, as GPLv3 states:
```
If the Program does not specify a version number of the
GNU General Public License, you may choose any version ever published
by the Free Software Foundation.
```
For my own contributions to Audacity, my intention was  that it should be open source, and GPL (whatever version) seemed like a suitable license, though  personally I'm more interested in audio and software than in the intricacies of license versions. I suspect that most audio software developers feel the same way.

**Comment by imachug** [comment]
> The wording in the original Audacity license was:

Yet the original README said it's 'GPL 2 or later' from the beginning, and the wording in LICENSE file has been fixed afterwards to be explicit about GPL 2.

**Comment by mariaWitch** [comment]
@SteveDaulton So to be absolutely clear, forks are allowed to update their GPL licenses carte blanc without needing permission first as long as the GPL version is 2 or later?

**Comment by SteveDaulton** [comment]
> @SteveDaulton So to be absolutely clear, forks are allowed to update their GPL licenses carte blanc without needing permission first as long as the GPL version is 2 or later?

I'm a musician and software developer, not  a lawyer.

**Comment by ValZapod** [comment]
What??? There is no "or later" part in a ny cpp file!!! So that means just like linux kernel this is ONLY GPL 2.0, not GPL2.0+

See: https://code.videolan.org/videolan/x264/-/blob/master/x264.c#L16

Wikipedia does not mention it but GPL2.0+ is the same as in GPL 2.0 in COPYING file. The difference comes in source files.

**Comment by shoogle** [comment]
@ValZapod, see the [licensing statement in README.txt](https://github.com/audacity/audacity/blob/d068b9341b6251e26564a3902765d2d856e7a49f/README.txt#L41-L43). Also, while a small number of source files do indeed mention GPLv2 without the "or any later version" text, we [have been asking](https://github.com/audacity/audacity/discussions/2142) the contributors of those files for their permission to release under later versions.

**Comment by LWinterberg** [comment]
closing this issue in favor of #2298
