### ISSUE TITLE
Change Tempo introduces sound glitch/distortion

### ISSUE THREAD

**Issue by fulvio314** [audacity/audacity#1273]
**Describe the bug**
Applying change tempo introduces sound distortions.

**To Reproduce**
It is not easy to reproduce this bug on any file, it happens randomly, I didn't find any logical clues. On the attached file it is clear and evident.
1. open the attached file 'original.wav'
2. Apply 'change tempo' 5%, high quality ON
3. listen carefully around 1,2", 1,6" and 1,9", you can hear a series of soft "pops" and "glops". For convenience, there is 'changed.wav' attached also.
4. Note, the low quality/fast 'change tempo' (with high quality OFF) introduces much less distortion.

**Additional information:**
  -  OS: Windows 10 Pro build 19041.1083, 64 bit (updated 2021 july 08)
  -  Pentium dual core 3.2GHz, 5GB RAM
  -  Audacity 3.0.2

**Additional context**
If it helps, I tryed with Audacity 2.3.2 and there is the same problem.
[wave files.zip](https://github.com/audacity/audacity/files/6793010/wave.files.zip)

**Comment by LWinterberg** [comment]
This probably is just tied to how the sound stretch algorithm works ("high quality" uses SBSMS, while the normal one uses SoundTouch). We may find a better algorithm to do sound stretching in the future, that's currently being discussed in #1524.

**Comment by fulvio314** [comment]
Thank you, I'll wait. I use Audacity a lot, lately for vitual choir. For this kind of production I have to sync many tracks, sometime up to 30, each recorded independently and individually. Everyone has some sync errors here and there, up to 500 ms. Anyway, even the real choir (not vitual) when recorded with multitrack, gives sync misalignments. 'Change tempo' is very useful for this kind of job.
