### ISSUE TITLE
Feature Request: "File --> Import...---> From Web/URL/Network Location..."

### ISSUE THREAD

**Issue by richaardvark** [audacity/audacity#1276]
_[link: From my original response/request on the Audacity Forum...](https://forum.audacityteam.org/viewtopic.php?f=28&t=93945&p=430120#p430120)_

**Is your feature request related to a problem? Please describe.**
Not a major problem, but it work be very helpful if I could quickly and directly open an audio file from a network/Internet source.

**Describe the solution you'd like**

A new "File" menu option:
- "Open --> From Web/Url/Stream..."
⠀⠀⠀⠀⠀⠀⠀⠀⠀or
- "Import --> From Web/Url/Stream..."

A simple one-line text input box appears and the user inputs their desired URL. On the back-end/in the coding, a simple wget or cURL command points to whatever URL/file location the user has entered. The file downloads to a temporary/cached directory somewhere and the regular Audacity audio import process begins.

If the URL/location entered doesn't directly/quickly yield a recognized audio file (WAV, MP3, OGG, AIFF, FLAC, MP4, etc.) then simply return a one-sentence message to the user: _"The location you have entered is not a direct link to a supported audio file."_

If there is worry that material being imported from a WWW source might potentially be copyrighted material, then include a simple one-sentence disclaimer warning message, for example something such as _"Material from the Internet may be copyright protected content - only import audio content for which you are the owner or for which you have permission from the owner to import... blah blah blah"_, but I don't really feel this is necessary as the onus to not work with copyright-protected audio content is on the user and is not the responsibility of Audacity to worry about or to be held liable for.  Any audio from any source can potentially be copyrighted material - this is simply another way to access audio content and is something that should really be standard in 2021 when computing and file storage is more and more cloud/external network based.

**Describe alternatives you've considered**

I am running Audacity on Linux (Debian 10, "Buster") and I suppose if Audacity isn't directly able to access a file from an external network URL that I could potentially configure the XFCE-based "File Open/File Management" dialogue box to somehow point to an external/Internet URL source, but it would be really nice if Audacity itself could simply open Internet-based direct media content links, save the content to a temporary/cached directory, and then follow the existing audio import process to load the content into Audacity.

**Additional context**
Perhaps look at VLC Media Player as an example of a tool that has this feature.  I realize VLC is a media _player_, which is a different type of tool (though in all actuality VLC is more than a simple player as it allows for content to be modified/converted/saved).  I just think this would be very simple to implement and is very necessary in this day and age.

**Comment by LWinterberg** [comment]
Fwiw: The Windows explorer can open network files directly, I can just paste eg `https://upload.wikimedia.org/wikipedia/commons/0/0e/Eternity_from_Light_Years_by_Stellardrone.flac` in the "Import Audio" browser, it just works. This used to be ubiquitous on Linux as well with eg Konqueror.

> Perhaps look at VLC Media Player as an example of a tool that has this feature. I realize VLC is a media player, which is a different type of tool (though in all actuality VLC is more than a simple player as it allows for content to be modified/converted/saved). I just think this would be very simple to implement and is very necessary in this day and age.

VLC is a bad comparison here as it's name is short for "VideoLAN Client" - it's literally a internet streams-first application.
