### ISSUE TITLE
Help>Check for Updates - does not actually check for updates

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1279]
**Describe the bug**

**To Reproduce**
1. Go to Help>Check for Updates
2. Observe: you are taken to the Update page of the Audacity Website
https://www.audacityteam.org/download/?from_ver=3.0.3&Time=Jul9202117:10:00

**Expected behavior**
Given that Audacity now has internet enabled update checking - check for updates should actually perform a proper update check - not just take the user to a wen page where they must do the checking.

This command should temporarily over-ride the setting a user may have in Application preferences for Update Checking to be "off" - BUT it should **_NOT_** change that setting to be on.  It is a perfectly valid use-case  that a user may wish to make a one-off on-demand check without having auto-checking turned "on"

**Screenshots**
Not applicable.

**Additional information (please complete the following information):**
 - Tested on W10 with latest 3.0.3 alpha:  Audacity_Windows_64bit_1015901279_01da348 
 - But applies to all OS

**Additional context**
None.

**Comment by gera-gas** [comment]
**Fixes way:**
1. Make the opt-in of `Help>Check for Updates` item by `audacity_has_updates_check` CMake option.
2. Call `UpdateManager::Get().GetUpdates(true)` from `Help>Check for Updates` to checking new version (download and installing) if update option was enabled.

**Comment by gera-gas** [comment]
Task required: 6-8 hrs

**Comment by Paul-Licameli** [comment]
@LWinterberg Remember manual updates for this?

**Comment by petersampsonaudacity** [comment]
Tested on W10 with audacity-win-3.1.0-alpha-20210924+97ca83e-64bit

This now looks fine

![image](https://user-images.githubusercontent.com/50205984/134725795-b5908333-7462-4424-aa8a-7f8f4353038f.png)

**Comment by Penikov** [comment]
Well, there are three ways to check updates now. 
- automatically (once per day, raises the message if updates are available )
- help-check for updates (that is @petersampsonaudacity mentioned)
- the link on the welcome screen that leads a user to the website
![изображение](https://user-images.githubusercontent.com/25851359/135604138-fd009ebd-7816-4448-8513-3e7044354806.png)


All three are working good now.
