### ISSUE TITLE
Macro command "Get Preference" fails

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#1289]
**Describe the bug**
Macro command "Get Preference" fails

**To Reproduce**
1. "Extra menu > Scriptables I > Get Preference
2. Observe, the "Get Preference" dialog fails to appear.

**Expected behavior**
The "Get Preference" dialog should open.

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version: Audacity 3.0.4-alpha-20210711

**Additional context**
Original report here: https://forum.audacityteam.org/viewtopic.php?p=430283#p430283

**Comment by SteveDaulton** [comment]
See also: https://github.com/audacity/audacity/issues/1293

**Comment by petersampsonaudacity** [comment]
Works for me on W10 with 3.0.2, 3.0.3 RC2 and 3.0.3 latest alpha

But fails on W10 with 3.0.4
