### ISSUE TITLE
Audacity has an error while Sonic Studio Virtual Mixer is on

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#1291]
**Description**
Every time when the user opens audacity, a window pops up about a debug report and the user can't launch Audacity.
When the user disabled Sonic Studio Virtual Mixer in Device Manager then Audacity started successfully.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run Audacity
2. See the debug message

**Expected behaviour**
1. Run Audacity
2. Audacity runs successfully

**Screenshots**
---

**Environment:**
 - OS: Windows 10
 - Audacity 3.0.2
 - **Sonic Studio Virtual Mixer is on**

**Comment by AnitaBats** [comment]
@crsib can you reproduce?

**Comment by crsib** [comment]
Nope, turns out my MB doesn't support it.
