### ISSUE TITLE
"Scriptables" commands fail

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#1294]
**Describe the bug**
Most or all of the commands in "Extra > Scriptables I" and "Extra > Scriptables II" fail.

**To Reproduce**
1. Select a command from either "Scriptables I" or "Scriptables II".
2. Observe, nothing happens.
3. The "Scriptables" commands that I've tested via mod-script-pipe also fail.

**Expected behavior**
The Scriptables commands to work.

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version: Audacity 3.0.4-alpha-20210714

**Additional context**
See also: https://github.com/audacity/audacity/issues/1289 and https://github.com/audacity/audacity/issues/1293

**Comment by SteveDaulton** [comment]
This bug also  breaks many Nyquist scripts.
Example:
1. Launch Audacity
2. Add a track
3. Select part of the track
4. Run this Nyquist command in the Nyquist Prompt using the Debug button: `(aud-do-command "chirp")`
5. Observe a long and cryptic error message, beginning with:

```
; loading "/tmp/aud-do-debug-data-cache.lsp"
Debug data cache refreshed.
; loading "/tmp/aud-do-debug-data-cache.lsp"
error: misplaced right paren
Function: #<Subr-(null): #0x55989e3d8528>
Arguments:
  #<File-Stream: #0x55989e89ef30>
  #\)
```

**Comment by SteveDaulton** [comment]
Bug bisects to first bad commit: https://github.com/audacity/audacity/commit/02b61532fe1d5de459de705ccfe81e3c8d7cda89

**Comment by Paul-Licameli** [comment]
> Bug bisects to first bad commit: [02b6153](https://github.com/audacity/audacity/commit/02b61532fe1d5de459de705ccfe81e3c8d7cda89)

Thank you for the bisection.  So this is only a problem in 3.0.4.

**Comment by SteveDaulton** [comment]
Yes, seems OK in 3.0.3 RC2.
