### ISSUE TITLE
Many parts of Dark theme Audacity are not really "dark"

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1296]
**Describe the bug**
Many parts of Dark theme Audacity are not really "dark" - in particular
1. Error messages
2. Preferences dialogs
3. Menu bar
4. Device toolbar
5. horizontal and vertical toolbars
6. Selection toolbar
7. Drop-down menus
8. History window
9. Plug-in Manager
10. Log file window
11. dialogs for Effects, Generators and Analyzers
12. The "affordances" drag bars for tracks and clips introduced in 3.0.4
13. there may be more ...

**To Reproduce**
1. Edi> Preferences>Interface
2. In Theme, select "Dark"
3. Observe: many parts are not really dark'

**Expected behavior**
A more consistent darkness

**Screenshots**
![image](https://user-images.githubusercontent.com/50205984/125619744-cef4a7e5-927d-4949-908b-411a04ad0607.png)

![image](https://user-images.githubusercontent.com/50205984/125619938-23715020-2c63-47e4-a8ce-7643c004b36c.png)

**Additional information (please complete the following information):**
 - All OS
 - All Audacity versions since Themes were introduced

**Additional context**
Also applies to High Contrast theme.

**Comment by petersampsonaudacity** [comment]
Another example was previously logged on Bugzilla 1717
Bug 1717 - ENH: On opening new project in Dark or High Contrast theme, area to left of horizontal scroll bar is filled with Light theme color
https://bugzilla.audacityteam.org/show_bug.cgi?id=1717

![image](https://user-images.githubusercontent.com/50205984/147676480-7d6877e0-5952-4ad4-acab-bdabebce0aae.png)

This also occurs if you set dark theme, exit Audacity and then relaunch.

_Sometimes during the use of Audacity in Dark theme that area can turn black - but I cannot find repeatable steps to reproduce this transition._

**Comment by petersampsonaudacity** [comment]
Flagging @Tantacrul as a UX/GUI issue

**Comment by LWinterberg** [comment]
this is a consequence of wxWidgets using system-native elements for many things. (with the little area in the latest comment possibly being a bug). There's very little to be done here until we switch to a system that actually allows us to touch these buttons and design them ourselves (eg Qt), hence why I marked this as known issue.

**Comment by zag2me** [comment]
Is there any news on this or a roadmap? 
I've just been trying to roll out 3.13 to our school departments, but our music department mentioned that the interface looks like its from the 1990's :)
They want to buy Adobe products instead :(

**Comment by LWinterberg** [comment]
This is on the roadmap for Audacity 4.0

> They want to buy Adobe products instead :(

On a school level, I don't think there's much that Audition can do that Audacity can't do, so I recommend to push back on that particular ask. However, if they want a DAW (ie a thing that also can handle MIDI and make music from within the computer), I recommend Bandlab or Cakewalk (both free)
