### ISSUE TITLE
Clip names: right to left languages

### ISSUE THREAD

**Issue by jounih** [audacity/audacity#1324]
Clip names should also support RTL settings - the position of the title should be mirrored

**Comment by jounih** [comment]
![Clip names@2x](https://user-images.githubusercontent.com/10109867/126167060-98b35627-b47e-4d28-98e8-10b67f31fc33.jpg)

**Comment by AnitaBats** [comment]
Design is ready, can be moved to implementation.

**Comment by AnitaBats** [comment]
Done in scope of #1533 task. Needed QA when #1533 is done
