### ISSUE TITLE
vertical shift-click&drag in the affordances drag bars causes Audacity to crash

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1329]
**Describe the bug**
1) Using shift modified click&drag to vertically move multiple clips to a different track causes Audacity to crash.

2) Using unmodified vertical click&drag in the affordances drag bar successfully moves the single clip to a new track.

3) Horizontal shift modified click & drag works fine, moving all clips in a track in sync together.

Using the Time-shift tool with shift modified vertical click&drag also produces the same crash.

**To Reproduce**
1) get some audio with two separate clips
2) Add a second empty track
3) Shift-click&drag (left or right)  in one of the affordances drag bars
4) Observe: both clips move left or right in sync _(this is expected and documented behavior)_
5) Shift-click&drag downwards to the second track in one of the affordances drag bars
6) Observe: Audacity crashes

**Expected behavior**
All the tracks in the track should be moved to the new track
**Screenshots**
Step 1
![image](https://user-images.githubusercontent.com/50205984/126292050-467465cb-3555-488c-ac70-8d61c3cee1c2.png)

**Additional information (please complete the following information):**
 - OS: W10
 - Version latest 3.0.4 alpha  -  audacity-win-3.0.4-alpha-20210720+95e7008-64bit
 - ET phoned-home with the error dialog

**Additional context**
I have not yet tested for regression

**Comment by petersampsonaudacity** [comment]
Further testing shows that shift modified vertical click&drag of multiple clips in a track also crashes in 3.0.2 and the latest alpha for 3.0.3 - so this crash should really be fixed for 3.0.3

**Comment by SteveDaulton** [comment]
Confirmed on Linux with Audacity 3.0.2 and Audacity 3.0.4-alpha-20210718
Shift + vertical drag of clips crashes  (even when shifting only one clip).

**Comment by petersampsonaudacity** [comment]
This is a MUST-FIX for 3.0.3 as Audacity should not crash like this.

**Comment by petersampsonaudacity** [comment]
This behavior first appears in version 3.0.0.

In all previous versions it was impossible to vertically move all clips in a track with shift-modified use of the Timeshift tool - it was just blocked with no crash.

Thus this is a regression on 2,4.2

**Comment by petersampsonaudacity** [comment]
The Manual has never mentioned the possibility of moving all clips (or multiple clips) vertically

> **Shifting clips vertically**
> When there are multiple audio tracks, a selected audio clip may be dragged up or down to another audio track of the same type. Mono audio clips may only be dragged to mono tracks and stereo clips may only be dragged to stereo tracks. To prevent unwanted left or right movement while dragging, press and hold the Ctrl key while dragging (on Mac, hold down the ⌘ key). 

But it dose do so for horiziontal movement

> **Time Shifting clips to left or right**
> An individual clip always shifts when dragged, though if the clip is partially selected, dragging to left or right from outside the selection region moves the clip without moving the region itself.
> 
>     To shift a group of adjacent clips in one or more tracks to left or right, leaving other clips alone, use Selection Tool to drag a selection region over the clips you want to shift, then switch to Time Shift Tool and drag from any clip inside that region. Dragging from white space between clips will do nothing.
>     To shift all clips in one track to left or right, hold Shift then drag. If you perform the SHIFT-drag from inside a selection region, all the clips will shift and the region will move with the clips. 


So to fix this bug either
a) prevent vertical moves of multiple clips (and block the crash), or
b) enable vertical moves of multiple clips

Option a) is existing behavior in 2.4.2 and earlier - but option b) would be a good improvement for users - and quite expected as an extension of the horizontal behaviors with multiple clips.

**Comment by petersampsonaudacity** [comment]
I also confirm the same erroneous behavior on Mac

macOS 11.4 Bug Sur - latest release-3.0.3 build

**Comment by DavidBailes** [comment]
> The Manual has never mentioned the possibility of moving all clips (or multiple clips) vertically

Though it can be  done using track selection and time selection to define the clips that are moved.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with audacity-win-3.0.3 RC3

This now appears to be fixed.

We have reverted to the behavior as it was in 3.4.2 and earlier wherr Shift-modified click and drag of clips with the Timeshift tool will not move the multiple clips (and importantly no crash)

**Comment by petersampsonaudacity** [comment]
I have updated the manual to provide greater clarity: https://alphamanual.audacityteam.org/man/Time_Shift_Tool#vertical
