### ISSUE TITLE
Update the on hover text for clip affordance

### ISSUE THREAD

**Issue by AnitaBats** [audacity/audacity#1332]
New hover text for clip affordance:
"Drag clips to reposition them. Hold Shift and drag to move all clips on the same track."

**Comment by petersampsonaudacity** [comment]
Should also mention the shift-modified behaviors.

But see Gihub Issue #1329

**Comment by Tantacrul** [comment]
Hmmm, I definitely mentioned during one of our design meetings that I thought that text was weird.

'Click and drag to move clips horizontally or place them on different tracks. Hold Shift to drag all the clips in your project at the same time'

I'm not sure we need to articulate the function of single click.

**Comment by petersampsonaudacity** [comment]
> I'm not sure we need to articulate the function of single click.

+1 to that

**Comment by DavidBailes** [comment]
> I'm not sure we need to articulate the function of single click.

"drag" rather than "click and drag" according to both microsoft style guide, and "read me first!",
eg, drag clips....

**Comment by Tantacrul** [comment]
> > Click and drag to move clips horizontally...
> 
> "drag" rather than "click and drag" according to both microsoft style guide, and "read me first!",
> eg, drag clips....

Makes sense. Changed.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with audacity-win-3.0.4-alpha-20210803+f90698c-64bit

Looks much better now with default window size.
