### ISSUE TITLE
Affordances: When copying and pasting a clip, it is desirable that it does not 'push out' clips to the right.

### ISSUE THREAD

**Issue by AnitaBats** [audacity/audacity#1333]
From an implementation point of view, we may want to handle this separately but it does need to be addressed

**Comment by jounih** [comment]
I think we resolved this on the call - there is a setting for this already - Tracks->Track behaviours->Editing a clip can move other clips

![image](https://user-images.githubusercontent.com/10109867/126345569-d3260d32-031f-4f52-8b38-c82829cbc425.png)

We will want to have a design overlapping clips, but that is a separate issue (and not for development in 3.1) - will create a new issue for this.
