### ISSUE TITLE
Affordances: Verify that "Fit to Height" acts as in version 3.0.3.

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#1339]
(View > TrackSize submenu, or hot key Shift + Ctrl + F )

Relates to minimization of tracks.

This command is supposed to apportion the vertical height of the screen equally among tracks, so that there is no scrollbar, except when tracks are so many they minimize and can't become short enough.

Scrollbar should appear in 3.1.0 only for the same number of tracks as in 3.0.3.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with Audacity 3.0.4-alpha-20210721

This does not work properly cf. 3.0.2

At default window size I imported 3 stereo tracks and used Fit to Height - the third tack was barely on-screen

![image](https://user-images.githubusercontent.com/50205984/126758425-f55734b5-c34e-4025-bb98-5b2271fb146d.png)

**Comment by petersampsonaudacity** [comment]
It's even more problematical with a full-screen window and a single stero track as you (mostly) lose the select and resize buttons:
![image](https://user-images.githubusercontent.com/50205984/126759119-9db58fa6-dd3c-4269-9301-e0255f0e9e74.png)
And note that the scroll bar can't scroll to reveal them.

And if you minimize the window than to default size its's even worse
![image](https://user-images.githubusercontent.com/50205984/126759295-e9c95b01-ffad-48cf-9a64-86f72c8bccd9.png)

**Comment by Paul-Licameli** [comment]
@vsverchinsky

**Comment by petersampsonaudacity** [comment]
The workaround is 
**View > Tracksize > Collapse All Tracks** - shortcut  **Ctrl + Shift + C**

**Comment by petersampsonaudacity** [comment]
Also fails on W10 with subsequent master build audacity-win-3.0.4-alpha-20210812+d4fb834-64bit

**Comment by petersampsonaudacity** [comment]
See also Issue #1455

**Comment by petersampsonaudacity** [comment]
#1422 looks like a duplicate if this issue

**Comment by petersampsonaudacity** [comment]
Now that 1442 has been pulled into master

Testing on W10 with latest alpha master build for 3.1.0/3.0.4 

This now woks fine

![image](https://user-images.githubusercontent.com/50205984/129229530-d8f64012-206e-4b70-9f2d-a7004cba0625.png)
