### ISSUE TITLE
Redesign splash screen and icon

### ISSUE THREAD

**Issue by SNDST00M** [audacity/audacity#1350]
**Is your feature request related to a problem? Please describe.**
This splash and icon design has been used for a decade. Hell, I've been using the same Classic theme most of that time. As new OSes get released, these assets stand out more and more. It's time to go the way of GIMP and redesign all brand assets to a flatter more modern design.

**Describe the solution you'd like**
Adoption of a flat, stylised and gradientless logo and splash screen.
Formalisation of a modern color palette for the Audacity "brand" (project).
These files should be designed as vectors or rasterised versions of vectors.

**Describe alternatives you've considered**
None exist to be honest.

**Additional context**
Branding updates will be necessary on the repository and the wiki.

**Comment by petersampsonaudacity** [comment]
> Branding updates will be necessary on the repository and the wiki.

And the Forum and the Manual

_and the T-shirts and the mugs_

**Comment by Paul-Licameli** [comment]
Don’t forget the PUMPKIN!

**Comment by 4086606** [comment]
I'm sure the colors will stay mostly the same 😁

**Comment by Paul-Licameli** [comment]
It’s Dark Theme!

**Comment by Paul-Licameli** [comment]
![](https://wiki.audacityteam.org/w/images/6/64/Pumpkin.png)

**Comment by SteveDaulton** [comment]
> This splash and icon has been used for a decade

The Mercedes-Benz logo has been virtually unchanged since 2008!
In fact, here's the logo from 1909 side by side with 2021

![merc](https://user-images.githubusercontent.com/11681097/126557761-d39a1a9f-8658-4b36-952e-d6ada3429678.png)

Audacity's logo was last updated on 8 Feb 2018. Here's the old and new:
![AudacityLogo](https://user-images.githubusercontent.com/11681097/126557078-6ac3ce02-e840-4b5f-aa48-9863a7e2b1a8.png)

**Comment by 4086606** [comment]
I like it but the saturation of the blue is too strong for my (material) tastes.

**Comment by 4086606** [comment]
Tbh I dream of Audacity looking like [this](https://www.deviantart.com/higorsm25/art/Audacity-for-Windows-10-Concept-Dark-861514024) but that's far fetched and would probably necessitate a full redo from scratch

**Comment by SteveDaulton** [comment]
> Tbh I dream of Audacity looking like [this](https://www.deviantart.com/higorsm25/art/Audacity-for-Windows-10-Concept-Dark-861514024) but that's far fetched and would probably necessitate a full redo from scratch

:-) That is NOT to my taste at all :-)
Luckily for both of us, I believe there is currently some work being done to make Audacity look  more  modern and more customizable.

**Comment by 4086606** [comment]
[Here's a different one](https://cdn.dribbble.com/users/4972614/screenshots/10830988/media/a505936a47fea4817b49490f75da63fe.jpg?compress=1&resize=1600x1200) that's less radical but let's focus.

If I publish the SVG here, can you all generate all the other XPM and PNG files?

**Comment by SNDST00M** [comment]
Did this go the way of the dodo? 🤔 I do get the feeling there's a big crowd in support of the logo as is

**Comment by LWinterberg** [comment]
a bug tracker isn't really the right place to discuss logo choices :)

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@LWinterberg, I suggest conversion of this into a GitHub Discussion.
