### ISSUE TITLE
Error dialogs link to wrong Privacy Notice

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1361]
**Describe the bug**
Error dialogs link to wrong Privacy Notice, linking to the "Desktop Privacy Notice" on the Audacity Website rather than the "Error Reporting Privacy Notice"

**To Reproduce**
1. create small AUP3 project
2. Copy the AUP3 file to C:\
3. Try to open the project from C:\
4. In the error message click on the Privacy Policy link
5. Observe: you are taken to the "Desktop Privacy Notice" on the Audacity Website 

**Expected behavior**
The link should take you to the "Error Reporting Privacy Notice"

**Screenshots**
![image](https://user-images.githubusercontent.com/50205984/126904273-da138409-2109-479f-86cc-6f8af607e59e.png)

**Additional information (please complete the following information):**
 - OS: W10 - but assume all OS
 - Version Audacity 3.0.3 alpha (latest)

**Additional context**
Note that the "Error Reporting Privacy Notice" page on the Website is just a placeholder

**Comment by crsib** [comment]
This is not a bug, there will be single privacy policy for error reporting and updates

**Comment by petersampsonaudacity** [comment]
See also Gihub Issue #1248

**Comment by petersampsonaudacity** [comment]
> This is not a bug, there will be single privacy policy for error reporting and updates

In which case the Audacity Website needs changing to have just the single Privacy Polict
