### ISSUE TITLE
Integrating Butterworth filter in Android

### ISSUE THREAD

**Issue by umamakhalid** [audacity/audacity#1362]
I am creating an android app using android studio in native c++. I need to apply butter worth filter on my audio before playing it. How can I use your Biquad.cpp class to apply butter worth filter on my audio? Is there any main class code in you repository? Do i need to call CalcButterworthFilter() function first then process() function?
Which function will take my audio as an input and which function will return processed audio?

Can any one help me integrating this code in android studio?

**Comment by rbdannenberg** [comment]
This doesn't sound like an Audacity issue. Feel free to find me online and contact me directly.

**Comment by umamakhalid** [comment]
Right Thank You.
Yes it is not an issue actually. I just want help in integration.
Details are in email.
