### ISSUE TITLE
GUI. Incorrect track displaying in Multi-view mode

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#1368]
**Describe the bug**

**To Reproduce**
1. Launch Audacity
2. Import a stereo track 
3. Switch track view to Multi-view (Spectrogram + Wave )
4.  The spectrogram has been displayed partly

**Expected behavior**
The spectrogram is displaying with no overlapping with other GUI elements

**Screenshots**
https://user-images.githubusercontent.com/25851359/127133267-308920d9-8dba-4a40-a07d-ed0f10446e68.mp4

**Additional information (please complete the following information):**
 - OS: Windows 10 X 64
 - Version: Audacity 3.0.4-alpha-20210726 (x64)

**Comment by petersampsonaudacity** [comment]
This is a regression on 3.0.3 

Note that if you switch back to waveform view you get a similar 1/2 right channel persistence of the spectrogram.

This is just a te,prary drawing glitch - clicking in the Audacity Window will correct the problem.

**Comment by petersampsonaudacity** [comment]
Also note that the Multi-view does not actually display until you move the cursor over the track area.

And the same applies when you turn Multi-view off to return to simple waveform view.

This particular behaviour is a regression on 2.4.2

**Comment by petersampsonaudacity** [comment]
Testing this on W10 with latest master alpha build  audacity-win-3.0.4-alpha-20210812+7da6a53-64bit

This does not appear to be fixed:
![image](https://user-images.githubusercontent.com/50205984/129221282-11dfdeb3-a6d2-49ad-ac36-ba27e3c9696b.png)

Therefore reopening this issue

**Comment by petersampsonaudacity** [comment]
Also fails on W10 with subsequent master build audacity-win-3.0.4-alpha-20210812+d4fb834-64bit

**Comment by petersampsonaudacity** [comment]
Now that 1442 has been pulled into master

Testing on W10 with latest alpha master build for 3.1.0/3.0.4   audacity-win-3.0.4-alpha-20210812+8f8ec41-64bit

This now woks fine
