### ISSUE TITLE
Note tracks have a black line under their affordances (Clip-handles)

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1370]
**Describe the bug**
Note tracks have a black line under their affordances Clip-handles - this is inconsistent with audio tracks (see attachment)

**To Reproduce**
1. Import an audio track
2. Import a Note track
3. Observe: black line under affordances Clip-handles in Note track
4. Observe: NO black line under affordances Clip-handles in audio track

**Expected behavior**
Consistency with both track types

**Screenshots**
![image](https://user-images.githubusercontent.com/50205984/127148191-c84bc328-badc-4fb9-b219-b6910acc8d73.png)

**Additional information (please complete the following information):**
 - OS: Windows 10 - but assume all OS
 - Version Audacity 3.1.0 alpha  (though it's badged 3.0.4 in the build)

**Additional context**
Note that though the next release nomenclature is planned to be 3.1.0 the latest alpha "master" builds identify as 3.0.4

**Comment by vsverchinsky** [comment]
These lines can be seen in older builds (current release 3.0.3, for example). It somehow releated to the piano roll, but not sure about the exact meaning of this
![image](https://user-images.githubusercontent.com/20165230/128170311-f20a3e1c-fbc9-4c8f-a86e-8266a1102ecb.png)
