### ISSUE TITLE
Label tracks do not have affordances (Clip-handles)

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1371]
**Describe the bug**
Label tracks do not have affordances (drag bars).

This is inconsistent with Audio tracks and Note tracks

**To Reproduce**
1. get an audio (or Note) track
2. add a label
3. Observe: the label track does not have affordances Clip-handles

**Expected behavior**
Affordances Clip-handles in Label tracks
a) for consistency with Audio and Note tracks
b) to make it easier to move them (in sync)

**Screenshots**
![image](https://user-images.githubusercontent.com/50205984/127149195-ceb32771-0a31-429c-b674-612f0579d8c4.png)

**Additional information (please complete the following information):**
 - OS: Windows 10 - but assume all OS
 - Version 3.1.0/3.0.4

**Additional context**
The workaround is to :
a) switch to the Timeshift tool
b) click&drag in the label track to move all labels in that track in sync

Note that this is an awkward workaround as the user has to revert to the selection tool for normal working - or learn to deal with the complexities of the Multi-tool

**Comment by vsverchinsky** [comment]
Can't labels be moved by holding and dragging the bar in the middle (between handles)?
![image](https://user-images.githubusercontent.com/20165230/128148468-4f953cb0-8b04-446b-b543-241b135637c2.png)

**Comment by petersampsonaudacity** [comment]
Yes, that is the case now in 3.0.4/3.1.0 withe the fatter bar which has now become a drag bar.

But in 3.0.3 and earlier the thinner bar was not a drag bar - the way to move a label was the Shift_clock on the chevron or the dot - much less "discoverable"

And (in 3.0.3 and earlier) you can move all labels in a track together in a track by selecting the Time Shift Tool and clicking&dragging in the gray space of the Label track.

BUT if the Time Shift tool is decided to be redundant and removed as per this GitHub Issue #1411 
then without a Clip-handle (formerly "affordance") for the label track there would be no way to move all the labels in a label track in sync.

**Comment by petersampsonaudacity** [comment]
@vsverchinsky   -  thanks for this insight Vitaly, I didn't know these had become drag-bars - it made me set P1s in the manual for the change _(and I suspect there are more than a few pages in the Manual with images of region labels)_.

**Comment by Tantacrul** [comment]
I'm adding a little note in the design to fix the cursor icon for label tracks and also to allow Shift + drag to move all labels too. Closing this issue.

**Comment by Tantacrul** [comment]
Thanks @petersampsonaudacity!
