### ISSUE TITLE
 GUI. Switching spectrogram color scheme causes a problem with the time toolbar

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#1373]
**Describe the bug**
Switching spectrogram color scheme causes a problem with the time toolbar

**To Reproduce**
1. Launch Audacity
2. Import an audio track
3. Switch track appearance to multi-view
4. Go to preferences - Tracks - Spectrograms and change spectrogram colour scheme to another one, then click OK

**Expected behavior**
Colour spectrogram scheme changing does not affect on time toolbar

**Screenshots**
![изображение](https://user-images.githubusercontent.com/25851359/127152375-28823a37-8728-48ec-baba-157efc55573b.png)

**Additional information (please complete the following information):**
 - OS: [Windows 10 x 64
 - Version: Audacity 3.0.4-alpha-20210726

**Comment by Ryan-Miller-Audacity** [comment]
I can no longer reproduce this issue in the most recent Audacity Release 3.2.1. The time toolbar displays as expected after updating spectrogram color scheme. I do briefly see the toolbar flicker and display "doubled" but it doesn't stay like this.

**Comment by Ryan-Miller-Audacity** [comment]
@Penikov / @petersampsonaudacity Can either of you reproduce this?

**Comment by petersampsonaudacity** [comment]
@Ryan-Miller-Audacity 

Testing on W10 with 3.2.1

Briefly after pressing the OK button the effect the color change I see the same messed up Time toolbar (as in @Penikov 's image above) but it immediately rights itself (presumably the Time Toolbar is being redrawn,

_But this begs the question: just why is a reset of the spectral colorway messing with the Time Toolbar at all?_

**Comment by Ryan-Miller-Audacity** [comment]
I'd say given the relatively low impact (although I agree the fact that updating preferences causes redraws etc is not great) of this issue, and the bad display no longer sticks, we can close this in favor knowing that this will not be carried over in the migration to QT. 

If @LWinterberg disagrees we can reopen.
