### ISSUE TITLE
GUI. The effect list in Main Menu blocks other menu sections.

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#1374]
**Describe the bug**
The effect list in Main Menu blocks other menu sections and it could be annoying to newbies like bug author )

**To Reproduce**
1. Launch Audacity
2. Point the cursor at the main menu (e.g. at File section),  then click on it.
3. Pull the cursor to the right side of the screen from one main Menu section to another.

**Expected behavior**
Then the cursor reaches the Effect section, fall-down list doesn't close the Main Menu sections.

**Screenshots**
https://user-images.githubusercontent.com/25851359/127156368-1fd48ac6-fbb1-4268-909a-8c7c86c2d4b4.mp4

**Additional information (please complete the following information):**
 - OS: Windows 10 x64
 - Version: Audacity 3.0.4-alpha-20210726

**Comment by petersampsonaudacity** [comment]
This affects Windows - but dies NOT happen on Mac,

This was observed a while back, but never logged as it was dismissed as Windows behavior oddity and NOt-A-BUG.

**Comment by petersampsonaudacity** [comment]
> 
> 
> This affects Windows - but dies NOT happen on Mac,
> 
> This was observed a while back, but never logged as it was dismissed as Windows behavior oddity and NOt-A-BUG.

The underlying problem is that the Effect menu in its default display mode is ridiculously over-log and needs better management for an improved UX.  One workaround is to set the Effects preferences to sort by type.  When I was doing a lot of production work _(converting my LPs and tapes)_ I shortened the effects list by disabling all the ones I knew I didn't need.

**Comment by petersampsonaudacity** [comment]
Grouped by Type:
![image](https://user-images.githubusercontent.com/50205984/127161986-9e24af77-c565-4902-a4f8-81505c4d5727.png)

**Comment by petersampsonaudacity** [comment]
Effect menu trimmed (with many Disables) for a suitable set for LP/Tape concersion:
![image](https://user-images.githubusercontent.com/50205984/127163229-11c61027-9ef1-44cd-960b-b1c6676e9f58.png)

**Comment by petersampsonaudacity** [comment]
One possible solution that has been discussed many times but never implemented is to give the user a simpler mechanism to create a set of favorites for their commonly used effects.

**Comment by LWinterberg** [comment]
This will get fixed by #501

**Comment by LWinterberg** [comment]
closing in favor of #501
