### ISSUE TITLE
Duplicate Nyquist effects if 3.0.3 64-bit is installed without first uninstalling previous 32-bit 3.0.2

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#1381]
**Describe the bug**
On Windows, if a 64bit version of 3.0.3 is installed without first uninstalling any existing 32bit versions then:
1. On the effects menu, there are duplicates for the nyquist effects which are shipped with Audacity: for each a effect there's sub menu with two items.
2.  If you uninstall the 32 bit version after installing the 64 bit version, there are no entries for Audacity in the start menu.

On Windows , users should be recommended to uninstall any 32 bit versions before installing a 64bit version.

**To Reproduce**
1. Open effects menu.
2. There are sub menus for the nyquist effects shipped with Audacity

**Expected behavior**
On the effects menu, there should be items for nyquist effects, not sub menus.

**Additional information (please complete the following information):**
Windows 10
Audacity 3.0.3 64bit

**Comment by petersampsonaudacity** [comment]
Basically what the user is getting is the old 32-bit versions of the Nyquist effects plus the new 64-bit versions of the dame effects.

Note that both the 64-bit and 320bit versions of the Nyquist effects seem to work in 64-bit Audacity (testing on W10)

But it is tedious for the user to have to make the extra click and selection - poor UX:
![image](https://user-images.githubusercontent.com/50205984/127463410-3c236ae0-9f2f-49ff-b478-00eefe74a508.png)

**Comment by AnitaBats** [comment]
@jounih could you please take a look?

**Comment by jounih** [comment]
Are we able to remove/disable the previous 32bit nyquist plugins when the user installs one of the newer 64bit versions? I think this would be the ideal way to deal with this. It seems it's just some leftovers from a previous install which the user hasn't uninstalled

**Comment by petersampsonaudacity** [comment]
What about if a user wants to run both 64-bit Audacity and an older 32-bit Audacity - using plug-ins ?

**Comment by jounih** [comment]
we could disable the old 32bit versions by default, and the user can always enable them again from the plugin manager. But I don't see many use cases for running both versions to be honest

**Comment by petersampsonaudacity** [comment]
> we could disable the old 32bit versions by default, and the user can always enable them again from the plugin manager. But I don't see many use cases for running both versions to be honest

I think you're right @jounih - so removal may be the best option.  

Perhaps you could pop a dialog to the user asking if they want the 32-bitters removed or disabled.
