### ISSUE TITLE
AppImage is missing localization

### ISSUE THREAD

**Issue by crsib** [audacity/audacity#1382]
AppImage only contains English localization. 

**Expected behavior**
AppImage is localized to all supported languages

**Comment by petersampsonaudacity** [comment]
See also this Forum post:  audacity-wxgtk2 3.0.3 do not portuguese language
https://forum.audacityteam.org/viewtopic.php?f=48&t=119499

**Comment by SteveDaulton** [comment]
Workaround (previously posted here: https://forum.audacityteam.org/viewtopic.php?p=431498#p431498).

The audacity.cfg file may be manually edited (while Audacity is NOT running) to select the required language. For example, for French:

```
[Locale]
Language=fr
```
The Audacity 3.0.3 AppImage will then open with the selected language (in this case, French).

**Comment by Penikov** [comment]
Works fine.
![изображение](https://user-images.githubusercontent.com/25851359/133771419-7b344d29-0e94-4730-b5fe-10fc0f69c639.png)
