### ISSUE TITLE
Auto duck misses sections

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#1389]
Initially reported on https://forum.audacityteam.org/viewtopic.php?f=46&t=119468

**Describe the bug**
Auto duck misses sections on long audio files, if the control track has quiet sections, but not full silences and the threshold is choosen to be very low.

**To Reproduce**
1. Have a long audio file (1h+); generated tone works
2. Have a control track of equal length which has quiet sections (-72dBFS), ie a noise floor. A full mute won't reproduce this. 
3. Select the entire track to duck
4. Apply the auto duck effect using a -50dB threshold (-49dB didn't reproduce this)

**Expected behavior**
All sections are ducked

**Screenshots**
can be found in the forum: https://forum.audacityteam.org/viewtopic.php?f=46&t=119468

**Additional information (please complete the following information):**
 - OS: Windows 10 (OP), Ubuntu (steve)
 - Version: Audacity 3.0.3, 3.0.2 and 3.0.0 tested

**Additional context**
It works when ducking shorter sections (~20 mins) of the whole file. 
There is a workaround available (temporarily amplify the control track, apply the auto-duck with a higher threshold, de-amplify it again).

I'll try finding a root cause next week.

**Comment by SteveDaulton** [comment]
It doesn't actually need to be a long audio file. It can be reproduced with quite short tracks:

1. Generate 30 second tone (default settings)
2. Duplicate the track
3. In the duplicate track, make a selection about 3 or 4 seconds duration in the first half of the track
4. Normalize the selection to -60 dB
5. Make a selection around 3 or 4 seconds duration in the second half of the duplicate track
6.  Normalize the selection to -60 dB
7. Select all of the first track
8. Apply "Auto Duck" with settings: -24, 0, 0, 0, 0, 0, -45 (It may be necessary to set the "Threshold" slightly higher or lower to reproduce the exact symptoms described)
9. Observe that the second "silence" is ignored.
10. "Undo"
11. Reverse the second track
12. Select the first track
13. Apply Auto Duck with the same settings (It may be necessary to set the "Threshold" slightly higher or lower to reproduce the exact symptoms described)
14. Observe that the second "silence" is ignored.

The precise threshold setting required for Auto Duck to (incorrectly) miss only the second "gap" is likely to be in the range -40 to  -50 dB. (I've not seen it ignore only the first gap).

**Comment by SteveDaulton** [comment]
There is also a documentation issue: The manual implies that the "Threshold" setting is a peak amplitude setting, but it appears to actually be some sort of mean square over a 100 sample window??
https://manual.audacityteam.org/man/auto_duck.html

**Comment by DavidBailes** [comment]
In bool EffectAutoDuck::Process(), I changed rmsSum to be a double rather than a float, and can no longer reproduce the bug using Steve's steps.
