### ISSUE TITLE
Text height in AudacityLogoWithName.xpm is streatched

### ISSUE THREAD

**Issue by scootergrisen** [audacity/audacity#1392]
Audacity 3.0.2

It seems the text "Audacity(R)" in the logo used on the splashscreen when Audacity starts and in About dialog is streatched twice it's normal height.

This is the https://github.com/audacity/audacity/blob/master/images/AudacityLogoWithName.xpm file converted to PNG so you can see it here (Notice how the "(R)" is not circular).
![AudacityLogoWithName](https://user-images.githubusercontent.com/1836590/127757954-9b24f596-18e8-4d6f-9f6a-f5e7ce087eb9.png)

Same logo but i reduced the height of the text 50% and moved the text.
![AudacityLogoWithName_2](https://user-images.githubusercontent.com/1836590/127757987-c5545bb0-a337-4ab2-8a5a-17068e55a4e3.png)

The height might have been done on purpose but i don't like to see it streatched. Just like i don't like watching a 4:3 movie streacthed to 16:9.

Compare with the logo from the website. I inverted the colors so you can see it on the white background.
![logo-text_2](https://user-images.githubusercontent.com/1836590/127758133-6932fdf1-1cd7-4bc5-854c-5da791b518a1.png)

**Comment by petersampsonaudacity** [comment]
Its the same with the Help>About Audacity dialog:
![image](https://user-images.githubusercontent.com/50205984/127777844-416c11dd-aebe-4bc8-8537-037537599323.png)

**Comment by petersampsonaudacity** [comment]
In the alpha Manual the ain logo has no stretching (nive round circle around the "R" - but the loao at the top left above the nav bars is slightly stretched:
![image](https://user-images.githubusercontent.com/50205984/127777932-7f412635-8af1-4bd9-bdf8-de99f55d70a3.png)
