### ISSUE TITLE
Plug-in Manager: Preferences for the custom plugin search path.

### ISSUE THREAD

**Issue by gera-gas** [audacity/audacity#1396]
#1180  
- Using `StringSetting` for economy time.
 - The path will be separated by `;`, and this is a not a problem to parse this by `wxTokenizer`.
 - Second, need patch `PluginManager::FindFilesInPathList()` with additional search directories from settings.
Estimate: 4 - 6 hrs.

**Comment by LWinterberg** [comment]
hey, we have that in 3.6
