### ISSUE TITLE
Plug-in Manager: Vamp plugins verification

### ISSUE THREAD

**Issue by gera-gas** [audacity/audacity#1398]
#1180 
Needed a static method for validation each plugin instance of each plugin type, something like: `VSTEffectsModule::Check()` and `VSTEffectsModule::DiscoverPluginsAtPath()`.
 - Create this check method for VAMP (4,5 hrs).
 - CLI checking methods by `STDOUT` (2,3 hrs).
 - Call this methods at startup (for example in `PluginManager::Initialize()` or `CheckForUpdates()` for comfortable calling from dialog (when user press on Rescan plugins) and collect failed information (2,3 hrs).

Estimate: 8 - 11 hrs

**Comment by petersampsonaudacity** [comment]
BTW it is Vamp not VAMP - it is not an acronym - I was assured of this long ago by Chris Cannam who wrote the Vamp plug-ins
