### ISSUE TITLE
Windows x64 build failure

### ISSUE THREAD

**Issue by csevast** [audacity/audacity#1409]
I follow the instructions to build Audacity in Windows but it fails. The part of the log describing the error is the following:

ERROR: expat/2.2.9@audacity/stable: Error in build() method, line 94
	self._build_cmake()
while calling '_build_cmake', line 60
	cmake = self._configure_cmake()
while calling '_configure_cmake', line 56
	self._cmake.configure(build_folder=self._build_subfolder)
	ConanException: Error 1 while executing cd C:\Users\csevast\.conan\data\expat\2.2.9\audac
ity\stable\build\4f1710918aa542fccb5a54d7bd712e4b0750b50d\build_subfolder && cmake -G "Visual Studio 16 2019" -A "x64" -DCONAN_LINK_RUNTIME="/MDd" -DCONAN_IN_LOCAL_CACHE="ON" -DCONAN_COMPILER="Visual Studio" -DCONAN_COMPILER_VERSION="16" -DCONAN_CXX_FLAGS="/MP8" -DCONAN_C_FLAGS="/MP8" -DBUILD_SHARED_LIBS="ON" -DCMAKE_INSTALL_PREFIX="C:\Users\csevast\.conan\data\expat\2.2.9\audacity\stable\package\4f1710918aa542fccb5a54d7bd712e4b0750b50d" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DCONAN_EXPORTED="1" -DEXPAT_BUILD_DOCS="Off" -DEXPAT_BUILD_EXAMPLES="Off" -DEXPAT_SHARED_LIBS="True" -DEXPAT_BUILD_TESTS="Off" -DEXPAT_BUILD_TOOLS="Off" -Wno-dev C:\Users\csevast\.conan\data\expat\2.2.9\audacity\stable\build\4f1710918aa542fccb5a54d7bd712e4b0750b50d

CMake Error at cmake-proxies/cmake-modules/conan.cmake:631 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake-proxies/cmake-modules/AudacityDependencies.cmake:233 (conan_cmake_install)
  cmake-proxies/cmake-modules/AudacityDependencies.cmake:251 (_conan_install)
  CMakeLists.txt:509 (resolve_conan_dependencies)

**Comment by crsib** [comment]
Hi! Usually, this means that you have run CMake from the x86 developer tools command line. It is difficult to say without having the full log

**Comment by csevast** [comment]
Thank you very much. I fixed it. My case is not exactly as it is described in the proposed BUILD text, so I should describe what I did. 

Because I didn't want to mix my Python environments, I downloaded and installed CONAN as a stand alone application for Windows --to be more specific, I installed with Chocolatey. Then, I added the path to CONAN executable folder to my PATH environment variable.

Because my Visual Studio 2019 installation didn't have the CMAKE-GUI --I don't know why--, I installed it as a stand alone application. The problem was that I was starting CMAKE-GUI from the Windows Start. As you suggested, I started the x64 developer tools command prompt for Visual Studio and I executed the CMAKE-GUI from there, finding the full path to it's stand alone installation.

I answered as I am waiting the building to be finished --It takes long time on my laptop-- and I hope it will be successful.

Thank you very much, again.

**Comment by werame** [comment]
>  this means that you have run CMake from the x86 developer tools command line

So where are you suppose to run it from? Plain cmd?

**Comment by LWinterberg** [comment]
in each case a 64 bit cmd. Or just the cmake-gui.

**Comment by werame** [comment]
Doesn't work anyway. Same errors. The only thing that makes a slight difference is using the x86_x64 dev cmd. That one works around [one error](https://github.com/conan-io/conan-center-index/issues/8936).

**Comment by werame** [comment]
In hindsight, I see the failure in your first build happened in expat. 

```
ConanException: Error 1 while executing cd C:\Users\csevast.conan\data\expat\2.2.9\audac
ity\stable\build\4f1710918aa542fccb5a54d7bd712e4b0750b50d\build_subfolder
```

Those are [intermittent failures](https://github.com/audacity/audacity/issues/2430). But you don't have the conan log above, only the cmake one, which lacks detail on what conan was doing.

All the extra legwork you've done may or may not have had any real impact. The problem may have really "fixed itself" due to luck.
