### ISSUE TITLE
Clip-handles (affordances) make the Time Shift tool redundant

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1411]
**Describe the bug**
The new Clip-handles (affordances) make the Time Shift tool redundant.

It is much easier to use the Clip-handles to reposition clips that to use the Time Shift tool, which involves:
a) changing to the Time Shift tool in the Tools toolbar
b) moving the clip(s)
c) returning to the Tools toolbar to revert to the previous tool - normally the Select tool

**To Reproduce**
1. Use the Clip-handles to reposition clip(s)
2. Observe that it works without changing the currently active tool in Tools toolbar (default Select tool)

**Expected behavior**
Removal of the Time Shift tool

**Screenshots**
Not applicable

**Additional information (please complete the following information):**
 - OS: All
 - Version Audacity 3.0.3/3.1.0
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]

**Additional context**
It would be good if the Tools toolbar could be removed altogether with alternative ways to effect
a) envelopes
b) draw repairs
c) and certainly zooming

Removing the Tools toolbar and its associated shortcuts would remove one of the frequently recurring bear-traps in Audacity - whereby users accidentally press one of the shortcut function keys and then find themselves in a tool mode that they don't understand and not knowing how to return to the default (and most useful) Selection tool.

See: https://wiki.audacityteam.org/wiki/ToDo:_Unstick_%27Stuck_In_a_Mode%27#beartrap
>Wiki>Stuck in a Mode - Bear-Traps

**Comment by Tantacrul** [comment]
I know we call this 'affordances' but I've always thought of this as the 'replace timeshift tool job'.

I wholeheartedly support this suggestion and I want to subscribe to the PSampson newletter!

**Comment by Paul-Licameli** [comment]
Before you do this, make sure you understand all the existing behavior, involving sync-lock, and interactions with selection, and so on.

For instance is there a way to move all labels of one track together (as there is to move all clips)?

**Comment by petersampsonaudacity** [comment]
> Before you do this, make sure you understand all the existing behavior, involving sync-lock, and interactions with selection, and so on.
> 
> For instance is there a way to move all labels of one track together (as there is to move all clips)?

Yes, all labels in a track can be moved in sync simply by clicking in the gray space of a label track and dragging left or right.

The sync lock behavior appears to be be the same with the Clip-handle drag bars and the Time Shift tool - but in both cases the behavior with Sync-Lock is a little janky and inconsistent.

=========================================================

Testing on W10 with latest 3.0.4/3.1.0 alpha  audacity-win-3.0.4-alpha-20210803+f90698c-64bit

Start with a project like this with 3 clips and three corresponding labels and Sync-lock turned on:
![image](https://user-images.githubusercontent.com/50205984/128053759-42a44259-0652-486b-a544-e0159c38b1b3.png)

**Use case 1**
1) Select the middle clip
2) Use Time shift tool on the audio track
3) Observe the clip and its label move in sync

**Use case 2**
1) Select the middle clip
2) Use Clip-handle drag bar on the audio track
3) Observe the clip and its label move in sync

**Use case 3**
1) Select the middle clip
2) Use Shift modified Time shift tool on the audio track
3) Observe all the audio clips move in sync - but their associated labels don't move

**Use case 4**
1) Select the middle clip
2) Use Shift modified Clip-handle drag bar on the audio track
3) Observe all the audio clips move in sync - but their associated labels don't move

**Use case 5**
1) Select the middle clip
2) Click in the gray space of the label track and drag left or right
3) Observe all the labels move in sync - but their associated audio clips don't move

a)  Use Cases 1 and 2 are (I believe) expected and indeed good behavior

b) Use cases 3 and four are decidedly liffy, with sync-lock ignored

c) Use Case 5 is also  iffy, with sync-lock ignored

But comparing UC1/UC2 and UC3/UV4 indicates that the behavior is consistent with sync-lock for Clip-hande drag bars compared with Time Shift tool - even if the sync lock is not always observed, it is at least consistent between the two methods.

Sync-lock has been long-known to be poorly (somewhat sketchily) designed - for a start the method of defining a Sync-locked Track Group (aka SLTG) by having a label track underneath is poor and weak UX - not obvious and certainly not discoverable.

**Conclusion**
So my summary conclusion is that the old Time Shift tool and the new Clip-handle drag bars behave the same both with and without Sync-lock.

**Comment by petersampsonaudacity** [comment]
To move all clips and all labels in syc with the above test project

**Use Case-6**
1) use click&drag with the Select tool to select all clips and all labels
2) Use Time Shift tool anywhere in the selection and drag left or right
3) Observe all clips and all labels move in sync

**Use Case-7**
1) use click&drag with the Select tool to select all clips and all labels
2) Use the Clip-handle drag bar (in any of the 3 clips) and drag left or right
3) Observe all clips and all labels move in sync

**Use Case-8**
1) use click&drag with the Select tool to select all clips and all labels
2) Use the Shift-modified Clip-handle drag bar (in any of the 3 clips) and drag left or right
3) Observe all clips move in sync - but the labels don't move

d) Use Cases 7 & 8 show again that behavior of Clip-handle drag bars and Time Shit tool is consistent

e) Use Case 8 looks a bit iffy to me (as a user).  Is this expected or desired behavior ?

**Comment by petersampsonaudacity** [comment]
See also GitHub Issue #1371 
Label tracks do not have affordances (Clip-handles) #1371
