### ISSUE TITLE
[SOXR] Cannot detect 'system' library.

### ISSUE THREAD

**Issue by carlo-bramini** [audacity/audacity#1415]
After adding `-Daudacity_lib_preference=system`, CMake can detect my system libraries, except libsoxr.
I have installed the latest version, that is 0.1.3.
But the configure script does not find it:
```
-- Checking for module 'soxr >= 0.1.1'
--   Package 'soxr', required by 'virtual:world', not found
-- Using 'soxr' local library
```

Sincerely.

**Comment by LWinterberg** [comment]
The build system has changed since this was made, try again. Closing bug as stale.
