### ISSUE TITLE
Warp line doesn't display correctly on a time track

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#1417]
**Describe the bug**
A warp line doesn't display correctly on a time track. 

**To Reproduce**

1. Launch Audacity, then open a test project/import an audio track
2. Add a time track
3. Pick up the warp line and bull it to the bottom of a track.

**Expected behavior**
The warp line is displaying correctly without interruption or breaking

**Screenshots**

https://user-images.githubusercontent.com/25851359/128138670-53f7501d-353e-42d6-8f9e-c1d5ac9872dd.mp4

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version: Audacity 3.0.4-alpha-20210730

**Comment by petersampsonaudacity** [comment]
Testing on W10 with audacity-win-3.0.4-alpha-20210803+f90698c-64bit

a) the graphic corruption only seems to occur when the Timeline is below the audio track.

b) The graphic corruption appears to be only temporary, just while Timeline points are being moved, Once the cursor is released the Timeline appears to be drawn correctly

**Comment by DavidBailes** [comment]
> a) The graphic corruption only seems to occur when the Timeline is below the audio track.

Yes, looks like there are problems when the envelope points are within the height of the clip handle from the bottom of the tracks. Some maths gone astray.
As the number of audio tracks above the time track increases, the problem increases.

**Comment by petersampsonaudacity** [comment]
This is a regression on 3.0.3

**Comment by SteveDaulton** [comment]
I'm seeing a very similar issue when using "Envelopes" on audio tracks (Xubuntu 20.04, audacity-linux-3.0.4-alpha-20210803+f90698c-x86_64.AppImage)

![Envelope](https://user-images.githubusercontent.com/11681097/128165830-842f0460-044d-44d8-ae3b-5cd1193fa512.gif)

**Comment by Penikov** [comment]
> 
> 
> I'm seeing a very similar issue when using "Envelopes" on audio tracks (Xubuntu 20.04, audacity-linux-3.0.4-alpha-20210803+f90698c-x86_64.AppImage)
> 
> ![Envelope](https://user-images.githubusercontent.com/11681097/128165830-842f0460-044d-44d8-ae3b-5cd1193fa512.gif)

This behaviour affected many track types. It was fixed in the last build.

![изображение](https://user-images.githubusercontent.com/25851359/128328216-89010344-65ee-416c-a9c7-344e9291578f.png)

**Comment by Penikov** [comment]
I have mistaken. It probably depends on the project. In another project, incorrect behaviour is still presented.

**Comment by DavidBailes** [comment]
And there's a similar issue with the draw tool,

David.
