### ISSUE TITLE
When dragging a clip down to another track, user has to drag further down than expected

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#1418]
**Describe the bug**
When dragging a clip down to another track, the clip is only moved when the centre of the mouse pointer is below the region used by the clip handles/title bar/drag bar or whatever it's called.

**To Reproduce**
1. If I drag a clip up to the previous track, as soon as the centre of the mouse pointer is within the area of the previous track, the clip moves to that track.
2. If I drag a clip down to the next track, it's only when the centre of the mouse pointer is below the drag bar region of the next track that the clip is moved, rather than when it's within the area of the track. I don't think there's a good reason for this behaviour, and I don't think it's what the user would expect to happen - it shows up especially when the heights of tracks are small.  (Reaper doesn't have this odd behaviour.)

**Expected behavior**
Whether dragging a clip up or down to another track, the clip should move as soon as the centre of the mouse pointer lies within the track area.

**Additional information (please complete the following information):**
tested on Windows 10

**Comment by petersampsonaudacity** [comment]
The Time Shift tool behaves in exactly the same way - so this is not a new issue created by the Clip-handles,

**Comment by LWinterberg** [comment]
This is technically not a new issue. The track in which the clip goes is determined by the cursor position. Pre-3.1, your cursor would probably drag from the center-ish of the clip, post-3.1 you drag from the top of the clip. So moving a clip downwards goes on forever, while moving it upwards is very fast. 

Moving a clip really should allow it to "float" and place a "ghost" where it'll ultimately be placed, somewhat similar to what the stackable effects do
![image](https://user-images.githubusercontent.com/87814144/184116157-e513c60d-75e4-43d2-bf4b-a096fcf82a89.png)

I've added it to the design backlog. I'll make a new issue with the specs once it's time (which may be post-4.0)
