### ISSUE TITLE
When dragging a clip to a different track, yellow snap guides can appear when clip boundaries are not aligned.

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#1419]
**Describe the bug**
When dragging a clip to a different track, yellow snap guides can appear when clip boundaries are not aligned.

**To Reproduce**
1. Start with two mono tracks. No clips in the first, and two in the second.
2. With a single drag, drag one of the clips horizontally, then vertically to the first track, then horizontally in the first track passing over the other clip, the yellow snap guides appear when the clip boundaries don't have the same position in time. Note that the problem only occurs if this step is executed using a single drag.

**Expected behavior**
Yellow snap guides should only be shown when clip boundaries align.

**Additional information (please complete the following information):**
tested on Windows 10

**Comment by petersampsonaudacity** [comment]
@DavidBailes is this a regression David?

**Comment by DavidBailes** [comment]
> @DavidBailes is this a regression David?

No.

**Comment by LWinterberg** [comment]
closing in favor of #2260
