### ISSUE TITLE
Show track name as overlay

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#1421]
**Describe the bug**
"Show track name  as overlay" does not work in audacity-linux-3.0.4-alpha-20210803+f90698c-x86_64.AppImage without a restart.

**To Reproduce**
1. Open a project with at least one named audio track
2. Enable "Show track name  as overlay" in Preferences
3. Observe that the track name is NOT shown on the audio track(s)
4. Restart Audacity
5. Observe that the track name is now shown as an overlay.
6. Disable "Show track name  as overlay" in Preferences
7. Observe that the track names are still displayed as overlays

**Expected behavior**
When "Show track name  as overlay" is enabled in Preferences, I'd expect the track name to show as an overlay on the track immediately without requiring a restart.

**Screenshots**
This is what "should" happen:
![audio_track_with_track_name_superimposed_translucent](https://user-images.githubusercontent.com/11681097/128164564-cafcb1dc-ee45-4942-8a76-adbf54aeffd0.png)

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version: audacity-linux-3.0.4-alpha-20210803+f90698c-x86_64.AppImage

**Additional context**
https://manual.audacityteam.org/man/tracks_preferences.html

**Comment by petersampsonaudacity** [comment]
Confirmed on W10 with 3.0.4/3.1.0 alpha audacity-win-3.0.4-alpha-20210803+f90698c-64bit

Plus I can get situations where the track name dies appear - but then I can't turn it off.

This is a regression on 3.0.3

**Comment by SteveDaulton** [comment]
Observed that the "name as overlay" does work after restarting Audacity (a restart should not be necessary).
Original bug report updated.

**Comment by SteveDaulton** [comment]
It seems that it a broader issue affecting many other preference settings, for example, changing "Display samples" from "Stem Plot" to "Connect dots" does not take effect until Audacity is restarted.

**Comment by petersampsonaudacity** [comment]
Tested on W10 with latest 3.1.0/3.0.4 alpha:   audacity-win-3.0.4-alpha-20210809+cf09f0a-64bit

I confirm that this now works correctly again on Windows.
