### ISSUE TITLE
Label affordance hint text

### ISSUE THREAD

**Issue by AnitaBats** [audacity/audacity#1426]

**Comment by petersampsonaudacity** [comment]
We have the text in the Status Bar - but (additionally) hovertext tool-tip at the drag-bar would be more obvious to the user as thet is where they are placing/hovering the cursor.

**Comment by LWinterberg** [comment]
I think as a rule, the project area (anything right of the track control panels, including affordances) should stay tooltip-free. This is consistent with pretty much everything, both within Audacity as well as with pretty much all programs (MS Paint, GIMP, Libreoffice, everything Adobe, ...) The way to indicate that something is draggable is through cursor indications (ie the hand), which is currently being done.
