### ISSUE TITLE
Affordances: fix drawing

### ISSUE THREAD

**Issue by vsverchinsky** [audacity/audacity#1430]
Zoom in wave track (left or right edge):
![image](https://user-images.githubusercontent.com/20165230/128358745-4b26df36-42b6-4cf4-ac1d-6dbc49e0faec.png)
Observe gap between frame and clip background

**Comment by Paul-Licameli** [comment]
Is this problem independent of the affordances project?

**Comment by vsverchinsky** [comment]
> Is this problem independent of the affordances project?

Clip affordances change the visual (not actual) boundary of the clip. With old boundaries (which are used do draw a background) the first clip sample was overlaping with clip frame

**Comment by LWinterberg** [comment]
This appears fixed in master
![image](https://github.com/audacity/audacity/assets/87814144/bcd4f021-a241-4bee-a577-0168c2c87b9d)
