### ISSUE TITLE
FFmpeg startup failed

### ISSUE THREAD

**Issue by te-agma-at** [audacity/audacity#1433]
**To Reproduce**
1. Launch Audacity
2. Configure FFmpeg (Preferences > Libraries)
3. Restart computer
4. Restart audacity
5. See error

**Expected behavior**
FFmpeg starts up automatically without error

**Screenshots**
![image](https://user-images.githubusercontent.com/72958435/128438864-edf0def6-f61e-4720-8683-b1cfb2715977.png)

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version: Audacity 3.0.3

**Additional context**
A popup that appears that is so annoying that I may have to use a different sound editor if I experience this popup again.

**Comment by SteveDaulton** [comment]
Previous Audacity releases for Windows were 32-bit.
If you installed the 64-bit version of Audacity 3.0.3, you will need to upgrade FFmpeg to the 64-bit version.
Other 32-bit plug-ins (such as any VST effects that you've added) will also need to be updated or they won't work.

If you need to update FFmpeg, uninstall your current version of "FFmpeg for Audacity", and then follow the instructions here: https://manual.audacityteam.org/man/installing_ffmpeg_for_windows.html

**Comment by ValZapod** [comment]
> then follow the instructions here:

Are you going to update to latest ffmpeg?? 4.4 that is. Because otherwise, it is better to do ffmpeg -i file output.wav/w64
