### ISSUE TITLE
Spectrum view in Hebrew is backwards

### ISSUE THREAD

**Issue by ghost** [audacity/audacity#1435]
When choosing the Hebrew version "Draw Spectrum" It shows the spectrum from left to right, but writes the horizontal axis from right to left.
It needs to be fixed.

**Comment by dozzzzer** [comment]
Cannot reproduce this as of 3.4.2:

<img width="546" alt="image" src="https://github.com/audacity/audacity/assets/70063970/136c49a4-d812-4632-9129-74cc66c63009">
