### ISSUE TITLE
Sync lock can move touching labels

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1436]
**Describe the bug**
If you have labelled clips that are touching and have sync lock on and then move one of the clips with its clip-handle drag-bar (formerly known as "affordances")

**To Reproduce**
1. get some Audio
2. Time shift it to the right
3. Set cursor partway through the clip
4. Edit > Clip Boundaries > Split
5. Label both clips
6. Turn on sync-lock
7.  Use the Clip-handle drag-bar in either of the clips to move the clip away from the other clip
8. Observe: not only does the label for the move clip move but it also drags the adjacent touching label with it

It consistently does this when you move the right hand clip - but only sometimes when you move the left hand clip.

**Expected behavior**
The adjacent touching label should not move and should stay with the clip it belongs to.

**Screenshots**
![image](https://user-images.githubusercontent.com/50205984/128542110-70f08e01-ddf8-4ea3-acc3-2a70678b64e1.png)

**Additional information (please complete the following information):**
 - OS: Windows 10 - but assume all
 - Version Audacity 3.1.0/3.0.4

**Additional context**
The same happens if at Step 7 you use the Time Shit tool instead - so this is not a new issue created the Clip-handle drag-bars.

**Comment by petersampsonaudacity** [comment]
Consider this use case
1. record a couple of seconds of audio
2. drag it into the middle of the window with Clip-handle drag bar (or Time Shift tool)
3. Place point labels at the exact beginning and end of the clip (use the yellow snap guides for accuracy)
4. drag the audio clip left or right with Clip-handle drag bar (or Time Shift tool)
5. Observe: the two labels move in sync with the audio clip

Now this may (or may not)  be desired behavior, but if it is seen as desired and useful then the original use case posted as this bug report can be called into question as "expected" behavior.

**Comment by petersampsonaudacity** [comment]
See also #1540 Sync-lock not honored when Timeshifting labels

**Comment by petersampsonaudacity** [comment]
Bumping this issue as this surface again as a user complaint on the Forum today:
https://forum.audacityteam.org/viewtopic.php?f=46&t=121920&p=440655

**Comment by petersampsonaudacity** [comment]
@vsverchinsky Vitaly can you please a P rating to this

**Comment by petersampsonaudacity** [comment]
@Penikov  Pavel can you please assign a P rating for this (I think it's P3 marginal P2)

**Comment by dozzzzer** [comment]
The issue remains to be the case in 3.3.2
