### ISSUE TITLE
Inconsistent, asymmetric, use of drag-bars in Sync-lock

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1438]
**Describe the bug**

**To Reproduce**
1. Turn on Sync-lock
2. Record 2-3 seconds of audio
3. Use the Clip-handle drag-bar to move it to the center of the track window
4. Select the clip
5. Label the clip
6. send cursor to T=0 with Home _( just to clear the selection - but not essential)_
7. Using the Clip-handle drag-bar move the clip left or right
8. Observe:  the clip and its associated label move together locked in sync
9. Using the new label drag-bar drag the label left or right
10. Observe: only the label moves, the clip does NOT move in sync with the move label but stays put

**Expected behavior**
I am not sure if this is a "bug" or a "feature" (hence the "Design" label I flagged this with):
a) there is an easy way to move both the label and the track in sync (see Steps 7-8)
b) it could be seen as advantageous to be able to move the label independently.

But at the end of the day this is asymmetric and inconsistent - and could confuse users - so I a minded to see it as a "bug".

The b) above can readily be achieved by turning off Sync-Lock and moving the label independently of the audio clip

**Screenshots**
This is the result after Step 9
![image](https://user-images.githubusercontent.com/50205984/128604022-25a5b536-bffb-4182-9acc-65dae62dca32.png)

**Additional information (please complete the following information):**
 - OS: Windows 10 - but assume all OS
 - Version Audacity  3.1.0/3.0.4

**Additional context**
If this behavior is retained it needs to be clearly explained on this page in the Manual:
https://alphamanual.audacityteam.org/man/Sync-Locked_Track_Groups_-_Time_Shifting

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
