### ISSUE TITLE
Portaudio 19.6 cannot recognize a TV tuner that previous Portaudio versions could

### ISSUE THREAD

**Issue by gapc** [audacity/audacity#1448]
I recently tested Audacity 3.0.3 on my laptop (unzipped, not installed) and unlike the 2.0.5 version I was using until then, it could not recognize audio devices (the infamous "Internal PortAudio error" appeared) due to an USB tv/radio tuner (KWorld UB490-A) that I use on weekdays for recording a pair of radio programs and could be recognized by the version 2.05, so I cannot allow myself to disable it in order to this new version of Audacity to be able to recognize the other audio devices. After testing 2 other versions of Audacity, 2.4.2 and 2.3.3 (unzipped too) and finding out that only the latter of these could recognize the TV tuner, I guess the culprit is the Portaudio version 19.6.

Computer: Lenovo G40-70
OS: Windows 10
Sound card: Conexant SmartAudio HD, version 8.66.4.0
TV/radio tuner: KWorld UB490-A

**Comment by LWinterberg** [comment]
Did this get fixed by the update to 19.7 in #1431 ? You can download current development snapshots in the Actions tab, eg [here](https://github.com/audacity/audacity/actions/runs/1195384142#artifacts)

**Comment by gapc** [comment]
Yes, it got fixed with this update.

**Comment by LWinterberg** [comment]
Awesome!
