### ISSUE TITLE
Learn sound model like Adobe Audition for sound removel

### ISSUE THREAD

**Issue by hotarugali** [audacity/audacity#1451]
**Noise Reduction** in audacity doesn't work very well, it often distort the original audio. 

To the best of my knowledge, there is **Learning Sound Model** functionality in adobe audition. And after learning the noise fragment, adobe audition can remove the noise from the audio with almost no loss of original audio. I don't know exactly how it works. But it is really cool.

I would appreciate it if audacity will provide such functionality in the future. Thanks a lot.

**Comment by LWinterberg** [comment]
This is the way Audacity works currently: You first select a sample of noise only, then click "get noise profile", then select all audio and then apply the noise reduction. Is this how you were using noise reduction in Audacity as well? @hotarugali

**Comment by hotarugali** [comment]
Thanks for rely.

**Comment by LWinterberg** [comment]
Right, but this is a problem of the noise removal algorithm, not the lack of a "get noise profile" / "Learn sound model" workflow. We will be looking into changing up the way effects work anyway in Audacity 3.2, so I'm closing this for now as I'll be making detailled descriptions of what's needed for these effects relatively soon.

**Comment by Paul-Licameli** [comment]
> Right, but this is a problem of the noise removal algorithm, not the lack of a "get noise profile" / "Learn sound model" workflow. We will be looking into changing up the way effects work anyway in Audacity 3.2, so I'm closing this for now as I'll be making detailled descriptions of what's needed for these effects relatively soon.

It is not necessarily a problem of the noise removal algorithm.  One must also select the settings properly, and it may take experimentation.

The expectation that it all should just work automatically with one button simple push is questionsable.
