### ISSUE TITLE
The track in the bottom of the screen is always hiding under the toolbar

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#1455]
**Describe the bug**
When the user added a few tracks and they are not fit on the screen, then the toolbar closes the last track at the bottom.

**To Reproduce**
1. Launch Audacity
2. Add a few tracks
3. Scroll the sidebar to the bottom

**Expected behavior**
![изображение](https://user-images.githubusercontent.com/25851359/129006155-d42a7a00-8d28-441c-9679-7254604578f8.png)

**Actual behaviour**
The track is been closed by the toolbar

**Screenshots**
![изображение](https://user-images.githubusercontent.com/25851359/129006378-94429329-ac93-41a5-a810-4a8071f226da.png)

**Additional information (please complete the following information):**
 - OS: Win 10, Mac, 
 - Version Audacity 3.0.4-alpha-20210806

**Comment by Penikov** [comment]
Already fixed in Audacity 3.0.4-alpha-20210809

**Comment by petersampsonaudacity** [comment]
Not fixed in latest master build on W10   -  audacity-win-3.0.4-alpha-20210811+a758491-64bit

Is this something to do with the space for the drag-bars bot being calculated and allowed for ?

**Comment by petersampsonaudacity** [comment]
See also Issue #1339

**Comment by petersampsonaudacity** [comment]
Now that 1442 has been pulled into master

Testing on W10 with latest alpha master build for 3.1.0/3.0.4   audacity-win-3.0.4-alpha-20210812+8f8ec41-64bit

This now works fine

![Uploading image.png…]()
