### ISSUE TITLE
Linux: Text too large in Spectral Selection Toolbar

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#1456]
**Describe the bug**
Linux: Text too large in Spectral Selection Toolbar

**Screenshots**
![Spectral-Toolbar](https://user-images.githubusercontent.com/11681097/129024933-a3ba21d8-1986-411e-ac60-09d50cbb2a5d.png)

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version: Audacity 3.0.4 Commit Id: cea4a9

**Comment by petersampsonaudacity** [comment]
Looks fine on W10 with audacity-win-3.0.4-alpha-20210811+a758491-64bit

![image](https://user-images.githubusercontent.com/50205984/129040016-6c9505f3-18b0-4de2-9775-7ecc1b0fd484.png)

**Comment by petersampsonaudacity** [comment]
Fine on macOS 11.5 Big Sur with audacity-win-3.0.4-alpha-20210811+a758491-64bit

<img width="320" alt="Screenshot 2021-08-11 at 16 47 01" src="https://user-images.githubusercontent.com/50205984/129061565-d728371e-ad83-42f2-b195-b4523ad7348a.png">

**Comment by SteveDaulton** [comment]
It was OK on Linux with Audacity 3.0.2.

The bug is also present in audacity-linux-3.0.4-alpha-20210804+7d3d8fc-x86_64 AppImage.

**Comment by LWinterberg** [comment]
this will get fixed with the qt transition
