### ISSUE TITLE
Cannot join adjacent labels

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#1458]
**Describe the bug**
In Audacity 3.0.2 and earlier, adjacent labels may be "joined" so that they share a common boundary. In Audacity 3.0.4 cea4a9 this no longer appears to be possible.

**To Reproduce**
1. Create two region labels with approximate positions: 5 to 15 seconds, 16 to 26 seconds.
2. Shift + Click on the circle in the label flag at 16 seconds, and drag the label towards the first label
3. Drag until the first and second label share a common boundary (see screenshot)
4. I can't do step 3 with Audacity 3.0.4 cea4a9

**Expected behavior**
As shown in screenshot.

**Screenshots**
![First Track000](https://user-images.githubusercontent.com/11681097/129183503-cd177fdf-fb55-40f4-9275-042f480fe076.png)

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version Audacity 3.0.4 alpha cea4a9

**Additional context**
https://manual.audacityteam.org/man/editing_resizing_and_moving_labels.html#junction

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest master 3.1.0 build  20210812+d4fb834-64bit

This works for me:
![image](https://user-images.githubusercontent.com/50205984/129222879-357a3106-6c11-489e-a307-6c718b5aa890.png)

**Comment by LWinterberg** [comment]
seems like it works again
