### ISSUE TITLE
Add support for WavPack

### ISSUE THREAD

**Issue by crsib** [audacity/audacity#1470]
Add support for WavPack importing and exporting. 

WavePak is an open, patent-free codec supporting lossless and hybrid compression. 

WavPak supports 8, 16, 24, and 32-bit integer PCM; 32-bit float PCM.

The compression performance is relatively high - 78 MB/s for 32-bit float, which makes it to be a possible candidate for the persistence layer of Audacity.

**Comment by LWinterberg** [comment]
@PratyayAmrit75 Sure, go ahead! I'll keep you assigned for a week or so, so you can get started. Please report back with your progress - you may want to [make a draft pull request](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) when you get it in a state where the idea of your implementation becomes apparent, but it doesn't quite work yet.

**Comment by LWinterberg** [comment]
@PratyayAmrit75 you may want to ask in the discord server: 
https://discord.gg/N3XKxzTrq3

**Comment by Subhra264** [comment]
Hello, want to work on this issue...

**Comment by LWinterberg** [comment]
Hello @Subhra264! Do you know where to start?

**Comment by Subhra264** [comment]
> Hello @Subhra264! Do you know where to start?

Yeah, I hope so,. Here's what I need to do( I think)---
1. Somehow add the libwavpack library
2. For wavpack import, create a ImportWavPack.cpp file next to ImportMP3.cpp
3. Write code to import wavpack following other ImportX.cpp files
4. Similar steps for ExportWavpack.cpp

**Comment by LWinterberg** [comment]
Alrighty! I'll assign it to you for a bit; if you've got any questions, feel free to ask on our [discord](https://audacityteam.org/devserver)

**Comment by Subhra264** [comment]
Looks like, now in a position to open a pull request.

>  you may want to [make a draft pull request](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) when you get it in a state where the idea of your implementation becomes apparent, but it doesn't quite work yet.

 So I need to create a Work In Progress Pull Request right?
