### ISSUE TITLE
Unable To Parse Project Information may not have to be fatal.

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#1479]
Although the error "Unable to parse project information" is a generic error, on the forum
there are three posts by three posters with this error but also with identical fingerprints including this cryptic text:

===begin===ã¼€ç €æ´€æ°€â€€à°€ (sic)
===end===
16:18:09: DBConnection SetError
ErrorCode: 0
LastError: Unable to parse project information.
LibraryError: Error: not well-formed (invalid token) at line 1

Here are the posts:

https://forum.audacityteam.org/viewtopic.php?p=424666#p424666
https://forum.audacityteam.org/viewtopic.php?p=432504#p432504
https://forum.audacityteam.org/viewtopic.php?p=432487#p432487
(Note that the first two of these posts are on the same thread.)

Because these reports seem to be very specific and identical in every way I suspect they are caused (and may be corrected) by the same chain of events.

I found one of these .aup3 projects to be completely recoverable (by swapping the project and autosave database records).  I have not seen the other two.  Perhaps there is enough information in these posts to prevent this database damage or if not, then possibly to somehow recognize and recover the data rather than telling him his data is irretrievably lost.

**Comment by JohnColket** [comment]
Just so you know, this issue has been reported once again on the forum, here: https://forum.audacityteam.org/viewtopic.php?p=435172#p435172

**Comment by JohnColket** [comment]
This issue is similar to Error#1745

**Comment by petersampsonaudacity** [comment]
#1745
