### ISSUE TITLE
File >Print fails to print the Timeline correctly or usefully

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1481]
**Describe the bug**
The command **File >Print** fails to print the Timeline correctly or usefully

**To Reproduce**
1. Get some audio
2. File > Print  (I printed to PDF)
3. Observe the Timeline is unreadable

**Expected behavior**
A legible and useful Timeline printed

The Manual states:
>**Print...**
>Prints all the waveforms in the current project window (and the contents of Label Tracks or other tracks), 
>with the Timeline above. Everything is printed to one page. 

(or removal of this not very useful command)

**Screenshots**
This is the result of the File > Print command - with an illegible sort-of timeline at the top - zooming in (a long way) shows the plethora of tiny numbers do properly go from 0 to 2.02 (which is the project length) but 
a) there are far too many of them
b) they are too tiny to be legible
c) they are not really a "Timeline" just a string of numbers
![image](https://user-images.githubusercontent.com/50205984/129483012-391e59bd-f905-4c2e-9a8c-3be3e1caa18c.png)

In contrast this is a screenshot of my project:
![image](https://user-images.githubusercontent.com/50205984/129483090-da4bb551-6ebe-48cf-a057-c204b1492c5e.png)

**Additional information (please complete the following information):**
 - Windows 10 - but assume all OS
 - Version Audacity 3.1.0/3.0.4

**Additional context**
For my money this is a particularly less than useful command and we could consider removing it - rather than fixing this bug.

No user has ever complained about this (it was only discovered recently by @Paul-Licameli ) - which indicates to me that no-one probably uses it.

**Comment by petersampsonaudacity** [comment]
This is not a regression this behavior has obtained for 2.0.0 and even 1.2.6

Note that Audacity 1.0 did not have a File>Print command

**Comment by petersampsonaudacity** [comment]
The labels in a label track are pretty illegible too - this image is scaled at 100%:
![image](https://user-images.githubusercontent.com/50205984/129483784-d12df353-52de-41ad-a602-d0b990aa184c.png)


And again in contrast a screenshot of my project shows a nice legible label:
![image](https://user-images.githubusercontent.com/50205984/129483846-d9cd2b6c-1ff1-447d-9e93-6358478d71ff.png)

**Comment by Paul-Licameli** [comment]
Is P6 a thing yet?  😄
