### ISSUE TITLE
Update ImageCache in Theme.zip in Audacity Wiki

### ISSUE THREAD

**Issue by Endy3032** [audacity/audacity#1487]
The current ImageCache.png image is currently outdated in the Audacity Wiki. It will be nice if it is updated so it matches the new version

**Comment by LWinterberg** [comment]
Relevant wiki page would be https://wiki.audacityteam.org/wiki/Theming_HowTo, file in question is https://wiki.audacityteam.org/wiki/File:Theme.zip 
I'll need to update the entire thing to the current state of affairs eventually.

**Comment by LWinterberg** [comment]
Updated https://wiki.audacityteam.org/wiki/File:Theme.zip with help from @Paul-Licameli. Thanks Paul!!

**Comment by JohnColket** [comment]
@LWinterberg @Paul-Licameli Should there be 4 .png files?  One each for "Classic", "Light", "Dark", "High Contrast" ?

**Comment by crsib** [comment]
What we really should do now is to provide a way building that cache from the set of images. GitHub workflow, maybe

**Comment by svArtist** [comment]
> Updated https://wiki.audacityteam.org/wiki/File:Theme.zip with help from @Paul-Licameli. Thanks Paul!!

This uses a mismatching pair of bitmap/HTML title map.
.htm file uses the (I'm guessing old?) layout with only one row of red background tools above the appIcon, but the .png uses the one with two black blocks added and everything shifted over.

**Comment by vaclavmuller** [comment]
My Python script can convert the theme file for Audacity of different versions. (currently from version 1.3.x to 3.7.x)
https://github.com/vaclavmuller/AudacityThemeVersionConverter
