### ISSUE TITLE
Manual: Prepare for 3.0.4 hotfix

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#1503]
- [x] Update what's new page
- [x] Copy what's new page to wiki
- [x] Update manual main page
- [x] Create https://wiki.audacityteam.org/wiki/Release_Notes_3.0.4

Post-launch
- [ ] update https://wiki.audacityteam.org/wiki/Category:Release_Notes

**Comment by LWinterberg** [comment]
@petersampsonaudacity thanks for helping along! Am I missing anything on the checklist?

Also, I ended up not following the usual formatting for the release notes since much of it doesn't seem too relevant for this release

**Comment by petersampsonaudacity** [comment]
> @petersampsonaudacity thanks for helping along! Am I missing anything on the checklist?

That's fine Leo.

I checked for any occurrences of the text string "3.0.1" throughout the Manual with the **Replace Text** tool in the **tools > Special pages** from the Manuals nav bar (only visible to logged-in editors).  _This is a very useful tool for Manual maintenance I've always found._

I have archived a copy of the What's new in 3.1.0 in the Wiki:
https://wiki.audacityteam.org/wiki/Audacity_Versions#whatsnew


> Also, I ended up not following the usual formatting for the release notes since much of it doesn't seem too relevant for this release

Looks sensible to me
