### ISSUE TITLE
Metadata: Embedded album art and lyrics metadata discarded

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1505]
**Describe the bug**
If you import a file that has metadata for album art and lyrics, these are discarded by Audacity on export.

This represents a serious data loss to users, we get many complaints abot this on the Forum

**To Reproduce**
1) Import a file type such as MP3 that contains embedded image and lyrics
2) Export as file type that supports images and lyrics.
3) Observe: Image and lyrics discarded.

**Expected behavior**
The Album art and Lyrics metadata should be retained by Audacity and exported properly when exporting the audio file

**Screenshots**
![image](https://user-images.githubusercontent.com/50205984/130058216-5d5b00d0-f316-4717-b73e-b473da3bb2fb.png)
I have several audio files lying on my desktop for QA testing use, they all have nice album art which shows as the icon on the desktop for rapid identification and use.

One recent QA test involved
1.  Import an AAC (with album art metadata) file into Audacity
2. process it as part of QA testing
3. Export it back out to same location (this was the actual QA test after a Forum complaint)
4. Observe: the nice album art is lost - just abandoned and thrown away by Audacity

**Additional information (please complete the following information):**
 - OS: All
 - All Audacity versions up to and including 3.0.3

**Additional context**
This is marked as a High Severity bug as it involves the loss of a user's data - something that we take very seriously/

This was formerly Bugzilla Bug #701 - originally logged seven and a half years ago - and many users have complained since:
Bug 701 - Metadata: Embedded album art and lyrics metadata discarded
https://bugzilla.audacityteam.org/show_bug.cgi?id=701

**Comment by LWinterberg** [comment]
Improving metadata handling is not planned for the moment, closing for now. There may be a bigger metadata release eventually, follow #1464 for that.
