### ISSUE TITLE
Metadata: custom entries are ignored by Audacity on export

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1506]
**Describe the bug**
Metadata custom entries are ignored by Audacity on export, they are not exported with the exported audio file

**To Reproduce**
1) clear the audacity settings folder
2) record some Audio
3) Export as MP3
4) in the metadata dialog enter and populate two custom fields: Composer and Album Artist
5) press OK to make the export
6) Examine/edit the file With Windows Explorer > Properties > Details
7) Observe: no entries for Composer or Album Artist now
8) Import the MP£ file into iTunes
9) Examine the Song Info
10) Observe: no entries for Composer or Album Artist

**Expected behavior**
A user's carefully entered custom metadata should be exported with the audio file - especially as Audacity enables and facilitates the entry of such custom metadata in the Metadata Editor

**Screenshots**
Not applicable

**Additional information (please complete the following information):**
 - OS: All
 - Version: all

**Additional context**
This was formerly logged in Bugzilla as Bug #2802
https://bugzilla.audacityteam.org/show_bug.cgi?id=2802
Bug 2802 - Metadata: custom entries are ignored by Audacity on export

I have flagged it as high priority as it involves the loss of a user's data - and they may not realize till long after the export that their custom metadata is missing

**Comment by petersampsonaudacity** [comment]
The use case examples in the steps Composer and Album Artist are standard fare for iTunes and other player apps - so reasonable that a user may want/need these.

Maybe we should consider expanding Audacity's default metadata set, so that items like these get mapped and handled properly.

**Comment by petersampsonaudacity** [comment]
Bugzilla Bug 2525 would seem to relate this too:
https://bugzilla.audacityteam.org/show_bug.cgi?id=2525
Bug 2525 - Metadata: FFmpeg export fills in metadata tags in a way not compatible with other software

Where the user wrote:



`  
 Reuben Thomas 2020-08-21 18:42:58 UTC

It seems that the tags could be filled in in a more compatible way.

When I fill in the tags in EasyTag, it uses "DATE" instead of "year" and "ARTIST" instead of "author". The former names (as used by EasyTag) are documented at https://xiph.org/vorbis/doc/v-comment.html

From looking at the source of Audacity, I see in `export/ExportFFmpeg.cpp` and `import/ImportFFmpeg.cpp` that the list of tags used is set there, irrespective of the file type.

I'm not sure what the problem is here: do the tag names used with FFmpeg need to be adjusted according to the format, perhaps?
 `

**Comment by petersampsonaudacity** [comment]
See also this Bugzilla entry:
Bug 541 - Metadata: Audacity non-default ID3 frames rewritten as TXXX, rendering them invisible in WMP and iTunes
https://bugzilla.audacityteam.org/show_bug.cgi?id=541

where Gale Andrews (RIP) wrote back in 2012

===================================================
The same problem applies to any other tags that are not the seven defaults
offered in Metadata Editor. Those other tags will be rewritten as TXXX. 

Clearly 1) a decision must be made on expanding the default tags to include
universal default tags. This would imply including as a minimum, "Album Artist"
(TPE2), "Composer" (TCOM) and  "BPM" (TBPM), which would then not be rewritten.

2) Ideally, Audacity would not rewrite any per-specification frames as TXXX but
leave the frame as it is.  

====================================================

**Comment by LWinterberg** [comment]
Improving metadata handling is not planned for the moment, closing for now. There may be a bigger metadata release eventually, follow #1464 for that.
