### ISSUE TITLE
Metadata: Export Multiple substitutes default metadata for user-entered metadata

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1507]
**Describe the bug**
Metadata: Export Multiple substitutes default metadata for user-entered metadata

**To Reproduce**
1) Open the metadata editor
2) Enter some easily-identifiable info in the fields, such as “The Track Title”, “The Artist”, “The Album Name”, “The Genre”, “The Comment”. Maybe “99” for the Track Number and “2030” for the Year.
3) Click “Set Default” and close the metadata editor
4) Import or create some audio
5) Enter a few labels in preparation for Export Multiple
6) Open the metadata editor and enter new information in all the fields, or just clear some (such as Year or Genre); make sure to enter something different from the defaults.
7) Do Export Multiple as MP3 (or any format that supports metadata)
8) Import one of the exported files into a new project
9) Open the metadata editor
**Note:**
The Track Name and Track Number have been filled in properly by the Export Multiple command
All other metadata fields have been filled in from the “defaults” (steps 2 and 3) rather than what was entered in step 6.

**Expected behavior**
The user-entered metadata to be used

**Screenshots**
Not applicable

**Additional information (please complete the following information):**
 - OS: all
 - Version all

**Additional context**
This was originally logged on Bugzilla:
https://bugzilla.audacityteam.org/show_bug.cgi?id=2750
Bug 2750 - Metadata: Export Multiple substitutes default metadata for user-entered metadata

Flagged as High severity as it involves the loss of a user's carefully entered data.

**Comment by petersampsonaudacity** [comment]
A fix for this was provided by @MalevolentStrix 
https://github.com/audacity/audacity/pull/1320

1. I black-box tested this as OK
2. @Paul-Licameli 's code review unearthed some changes he wanted made

**Comment by Paul-Licameli** [comment]
The question was whether #1320 would revert the fix for https://bugzilla.audacityteam.org/show_bug.cgi?id=2240

**Comment by Paul-Licameli** [comment]
"Set Default" button in Metadata editor does not set the default during Export Multiple" https://bugzilla.audacityteam.org/show_bug.cgi?id=2240

**Comment by LWinterberg** [comment]
closing this issue in favor of #2615
