### ISSUE TITLE
 Enh: Metadata - FLAC export lacks seekpoints and metadata padding

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1508]
**Is your feature request related to a problem? Please describe.**
FLAC export lacks seekpoints and metadata padding

**Steps to reproduce**
1)Export a FLAC file.
2) Examine with metaflac editor kid3 or metaflac --list outfile.flac
3) Observe: There are no seekpoints and no padding.

**Describe the solution you'd like**
For a good user experience when using flac, it is recommended to have seekpoints at least every 10 seconds.

Also padding in the metadata can be advantageous for other apps that work with flac files.  It can save them from rewriting files when modifying the metadata only.

**Describe alternatives you've considered**
The original poster provided a patch 10 years ago ...

**Additional context**
This was originally logged as an ENH on Bugzilla in 2011
https://bugzilla.audacityteam.org/show_bug.cgi?id=325

**Comment by LWinterberg** [comment]
Improving metadata handling is not planned for the moment, closing for now. There may be a bigger metadata release eventually, follow #1464 for that.
