### ISSUE TITLE
Ogg decoding can hang (old vorbis library)

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1509]
**Describe the bug**
Ogg decoding can hang (old vorbis library)

**To Reproduce**
1. Attempt to import https://upload.wikimedia.org/wikipedia/commons/0/0f/Claude_Debussy_-_Premi%C3%A8re_Arabesque_-_Patrizia_Prati.ogg
2. Observe: : Audacity hangs, unresponsive.

**Expected behavior**
The audio file should import correctly

**Screenshots**

**Additional information (please complete the following information):**
The poster - James Crook, wrote:

=================================================

 James Crook 2021-04-15 12:38:05 UTC

This will be fixed by an upgrade to Vorbis 1.3.7 or later.

It's the same bug as reported here:

https://forum.juce.com/t/ogg-vorbis-file-puts-juce-oggreader-in-infinite-loop/41148

This loop is going round forever, because begin reaches zero and stays there.

  while(offset==-1){
    begin-=CHUNKSIZE;
    if(begin<0)
      begin=0;

    ret=_seek_helper(vf,begin);
    if(ret)return(ret);
    // other stuff
  }

This bug was also present in Audacity 2.4.2, so is not a regression.

=======================================================

**Additional context**

**Comment by petersampsonaudacity** [comment]
This was originally logged on Bugzilla 2748:
https://bugzilla.audacityteam.org/show_bug.cgi?id=2748

**Comment by crsib** [comment]
Voribs was updated to 1.3.7 in #1445

**Comment by petersampsonaudacity** [comment]
Tested on w10 with latest 3.0.4 alpha audacity-win-3.0.4-alpha-20210817+7949a0d-64bit

This now imports fine
