### ISSUE TITLE
 Macros: OpenProject2 causes macros to fail

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1510]
**Describe the bug**
When using  Macros, OpenProject2 causes macros to fail

**To Reproduce**
0) create the necessary AUP3 project for the Macro to open
1) Launch Audacity 3.0.3 alpha 
2) Observe: empty Audacity window
3) Run the AUP3 IO speed tests macro (see attachment, you will need to edit file locations)
4) Observe: Audacity opens a new window for the project
5) Observe: the project opens properly
6) Observe: the menu halts at that point and makes no exports/imports

**Expected behavior**
OpenProject2 should work when used in a Macro.

**Screenshots**
Not applicable.

**Additional information (please complete the following information):**
 - OS: all
 - Version: all

**Additional context**
This was originally Bugzilla 2812
https://bugzilla.audacityteam.org/show_bug.cgi?id=2812
Please see that bug thread for additional detail and discussion not copied over to here on GitHub.

See also Bugzilla 2798
https://bugzilla.audacityteam.org/show_bug.cgi?id=2798
Bug 2798 - Macros: command Open Project2 fails to "open" projects and audio files

**Comment by petersampsonaudacity** [comment]
The Speed tests macro that I have for testing the IO speeds of audio file imports/exports fails on the OpenProject2 Macro command.

I open an empty project and attempt to run the Macro on the "Project"

What happens is:

a) rather than opening the project in the existing open window, Audacity opens it in a new window

b) the Macro than just stops and does not proceed to the select and export commands


This is a regression on 3.0.2 and 3.0.0 where the Macro runs successfully to completion

Tested on W10 with 32-bit and 64-bit latest alphas - but assume all platforms

**Comment by Paul-Licameli** [comment]
Sorry, I refuse to fix this, for reasons explained in the bugzilla issues.

The macro system was never properly equipped to handle things, like multiple projects or commands like undo/redo happening within macros and it should not be pushed to do so.

Please pay attention to the Journalling system I am developing as a better alternative for developing automated QA tests.  I gave a demonstration to @Penikov lately and I'll gladly do so for you too.

**Comment by Paul-Licameli** [comment]
See #1402 for the summary issue and #1403 and #1404 for what has been done so far with journalling.

**Comment by Paul-Licameli** [comment]
See also #1055

**Comment by Paul-Licameli** [comment]
I gave my won't-fix reasons for this above.
