### ISSUE TITLE
Compressor works incorrectly when selected audio is partly in negative time

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1512]
**Describe the bug**
The Compressor effect works incorrectly when selected audio is partly in negative time.

When the compressor is used on an audio selection that is partially in negative time erroneous effects occur
1) Audio from negative time is added from =0 for the duration of the selection that is in negative time
2) The waveform that was in positive time is trimmed from the right by the amount of negative time in the selection

My steps show the effect with an initial silence for clarity - but similar happens if you omit the silencing and just work the steps with a complete 30 second chirp.

This happens consistently  for me on W10 and Mac Big Sur with 3.0.2 - Steve says this does also fail on Linux

This is a regression on 2.4.2 where it works properly.

Rated as P2 as
i) it's a recent regression
ii) it results in the loss of waveform data on the right end of the track (which the user may easily fail to notice until it is too late)

It's actually an improvement on 3.0.) where
a) on Windows, Audacity crashes at Step 9
b) on Mac, Audacity generates an error
>Internal error at WaveTrack.cpp line 1374

This was originally reported on the Forum by user tac2
https://forum.audacityteam.org/viewtopic.php?f=70&t=117577

This does not appear to affect other Effects when they are used at Step 9 in place of Compressor (I tried several - but not all).

**To Reproduce**
1) Generate 30 second chirp
2) select from 0-10 seconds
3) Silence that selection with Ctrl+L
4) Ctrl+A to select all
5) Effect>Compressor 
5b) Ensure that "Makeup gain" is enabled.
5.1) Observe proper compression (see attachment TBP)

6) Undo to remove the compression
7) Drag track leftwards with Timeshift tool so 9 seconds are in negative time
8) Ctrl+A to select all
9) Effect>Compressor 
9.1) Observe erroneous compression (see attachment TBP)

10) drag waveform right with Timeshift tool so that all the audio is in positive time starting at T=0 
10.1) Observe: extra silence and truncated waveform (see attachment TBP)

**Expected behavior**
The Compressor should work

**Screenshots**
See:  https://bugzilla.audacityteam.org/show_bug.cgi?id=2753

**Additional information (please complete the following information):**
 - OS: All
 - Version 3.0.3

**Additional context**
This was originally logged as Bugzilla 2753
https://bugzilla.audacityteam.org/show_bug.cgi?id=2753

**Comment by san-coding** [comment]
Hey can you help me out, I am new to open source, what files should I change

**Comment by SteveDaulton** [comment]
> Hey can you help me out, I am new to open source, what files should I change

Start with [/src/effects/Compressor.cpp](https://github.com/audacity/audacity/blob/master/src/effects/Compressor.cpp) and [/src/effects/Effect.cpp](https://github.com/audacity/audacity/blob/master/src/effects/Effect.cpp)

**Comment by Paul-Licameli** [comment]
We think that fixing this bug will be mostly investigation in the debugger to find out the place in the code to fix, and then a small fix once that is known.

**Comment by NoobMaster1999** [comment]
I can't reproduce the bug in windows 10 after step 9  windows alpha 3.0 version crashed

**Comment by LWinterberg** [comment]
this is unlikely to get fixed any time soon, if at all - negative time is such a niche concept in an audio editor

**Comment by SteveDaulton** [comment]
> negative time is such a niche concept in an audio editor

Some DAWs support "negative time" by offsetting (or allowing to be offset) the timeline so that there's a few bars space before t=0. Personally, that's always seemed like a much better way to handle it. Typically the "before zero" region would be used for adding a "count in" when overdubbing.
