### ISSUE TITLE
Win/Mac: Excessive slowness for some Windows and Mac users

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1514]
**Describe the bug**
On Windows and Mac, some users report Excessive slowness in Audacity use.

This does not affect all users but there have been several reports of this on the Forum.

**To Reproduce**
a) No clear steps.
b) Some Windows 10 and Mac users are experiencing dramatic slow downs in editing, after working on a project for a while.
c) Some reports are from users who have used both 3.0.0 and 3.0.2.

**Expected behavior**
Audacity to work in a responsive manner (as it did in previous versions.

**Screenshots**
Not applicable, add screenshots to help explain your problem.

**Additional information (please complete the following information):**
 - OS: Windows and Mac
 - Version 3.x

**Additional context**
This was originally logged as Bugzilla 2777
https://bugzilla.audacityteam.org/show_bug.cgi?id=2777
please see the bug thread for additional details

**Comment by petersampsonaudacity** [comment]
See also  
Pasting "Room Noise" Stalls Audacity #1357

**Comment by petersampsonaudacity** [comment]
@AnitaBats  - I can never reproduce this on either Win or Mac

**Comment by LWinterberg** [comment]
Has there been any additional knowledge gained regarding this? @petersampsonaudacity 
If not, this probably can be closed

**Comment by petersampsonaudacity** [comment]
This has never been an issue that I have observed personally on either of my two W10 PCs or on my Macbook Pro (currently running Monterey 12.0.1 - nut it ran fine on earlier macOS too).

I don't red the Forum assiduously enough to recall if this remains a problem for other users.

_It is of course possible that slowness can be caused by using cloud/network drives or slow US drives for a project._

**Comment by LWinterberg** [comment]
Right. In that case I'll close this for now, if there's slowness with a plausible cause, feel free to make a new bug
