### ISSUE TITLE
Export to Opus (OggOpus) is not available on Mac - Opus import fails on Mac

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1515]
**Describe the bug**
Export to Opus (OggOpus) is not available on Mac - Opus import fails on Mac.

Export to OPUS (OggOpus) as an explicit export from Export and Export Multiple was introduced in 2.4.0.

OPUS export works on W10 and Linux - but does not work on Mac.

**To Reproduce**
1) get some audio
2) File > Export > Export Audio (or Export Multiple)
3) Click on Save as type
4) Observe: in the dropdown menu there is no entry for:
OPUS (OggOpus) Files (FFmpeg)

Import Use case
5) Try importing an Opus audio file
6) Observe: it fails with an error message

**Expected behavior**
Audacity to support Opus audio on Mac (as it already does on Windows and Linux)

**Screenshots**

**Additional information (please complete the following information):**
 - OS: macOS
 - Version 3.0.3 and earlier]

**Additional context**
This was originally logged as Bugzilla 2381
https://bugzilla.audacityteam.org/show_bug.cgi?id=2381

**Comment by LWinterberg** [comment]
this will get fixed with #443, closing
