### ISSUE TITLE
Right clicking in Clip-handle affordance changes selection

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1518]
**Describe the bug**
Right clicking in Clip-handle drag-bar affordance changes selection from existing selection made by the user to selecting the clip.

**To Reproduce**
1. get two clips
2. make a selection in one of the clips
3. Right-click in the Clip-handle affordance of the second clip
4. Observe: the selection  from step 2 is removed and the whole of the second clip is selected

Alternatively
1. get some audio - i.e. a single clip
2. make a partial selection in the audio
3. Right-click in the Clip-handle affordance of the audio
4. Observe: the selection  from step 2 is removed and the whole of the audio is selected

**Expected behavior**
With right-click in the Clip-handle affordance I would expect either:
a) null - no action, or
b) a drop-down context menu

The user's carefully made selection should not be changed by a single right-click in the Clip-handle affordance

**Screenshots**
Not applicable

**Additional information (please complete the following information):**
 - OS: Windows 10  -  but assume all OS
 - Version latest master 3.1.0 (but still badged as 3.0.4)  audacity-win-3.0.4-alpha-20210820+45a90e3-64bit

**Additional context**

**Comment by petersampsonaudacity** [comment]
This only happens if you right-click in the Clip-handle affordance and release the mouse button without moving the mouse.

If you right-click in the Clip-handle affordance and move the mouse without releasing the mouse button then the clip moves - and wnh you release the mouse button the selection is no changed.

I would **_really_** not expect to move the clip with a right-click&drag in a Clip-handle affordance.

**Comment by Tantacrul** [comment]
I don't think this is a bug per se. However, I do agree that we should utilise the RC menu when ready to provide useful options, like 'Joining', changing colour, etc.

**Comment by Paul-Licameli** [comment]
My pull request #1504 may incidentally fix this.

**Comment by petersampsonaudacity** [comment]
> I don't think this is a bug per se.

Well if it's by _"design_" then it's pretty idiosyncratic and more than unusual.

I can't think of an app that I use where right click either doesn't bring up a context menu or simply does nothing. 


>However, I do agree that we should utilise the RC menu when ready to provide useful options, like 'Joining', changing colour, etc.
Indeed.

**Comment by DavidBailes** [comment]
> I can't think of an app that I use where right click either doesn't bring up a context menu or simply does nothing.

But dragging using the right mouse button is used in other apps. For example in File Explorer, you can right-drag files and folders around, and in Reaper dragging using the right mouse button is used by default for marquee selection.

**Comment by petersampsonaudacity** [comment]
> But dragging using the right mouse button is used in other apps. For example in File Explorer, you can right-drag files and folders around

Ooh so it does - I never knew that.

But in the context we are discussing here in alpha Audacity 3.1.0 the RMB actions duplicate and are exactly the same as the LMB actions and that is an unnecessary waste of gestures in a GUI.

1. Click and release =>  Select clip
2. Click&drag => move the clip
3. Double-click => no action

**Comment by DavidBailes** [comment]
> But in the context we are discussing here in alpha Audacity 3.1.0 the RMB actions duplicate and are exactly the same as the LMB actions in a Clip-handle affordance and that is an unnecessary waste of gestures in a GUI.

But until different actions are defined for using the right mouse button, I don't think it too much of a problem that they're just duplications at the moment.

**Comment by Penikov** [comment]
I have double-clicked on the clip handle (clip affordance) and it was selected then. 
Single right-click doesn't do anything, but double-click does.
Does it work as designed?

BTW if you try to click rapidly on the clip handle by the mouse wheel, the clip will be selected.

**Comment by petersampsonaudacity** [comment]
@SteveDaulton wrote on Discord:
>Mouse double right click on clip drag bar.
>Expected behaviour: Nothing - double right click is not a standard action.

I am minded to agree.
