### ISSUE TITLE
Internal PortAudio error on Windows 10

### ISSUE THREAD

**Issue by jeffagwm** [audacity/audacity#1519]
**Describe the bug**
I have recently purchased a new computer. I have Adobe Audition, Vegas Pro, and Audacity installed. I also have multiple mics and sound devices installed. Audition and Vegas both work well. Audactiy will not start. I get an error stating 'Internal PortAudio Error' When I click to dismiss that message Audacity will open but there are no audio devices for either recording or playback. I have uninstalled and reinstalled the latest version of Audacity.

My Computer is an Asus Zenbook Duo with i9-10980HK, 32Gb, Win 10 Pro 64bit with both Focusrite and Lexicon USB Sound cards.
I have attached screenshots of what I am seeing.

![AudacityError1](https://user-images.githubusercontent.com/18256914/130267967-58608794-f927-4161-ab31-068c4df840b6.jpg)
![AudacityError2](https://user-images.githubusercontent.com/18256914/130267977-0e7fa134-0ba7-447d-8201-2718cc4b1c12.jpg)

**Comment by SteveDaulton** [comment]
If ASIO is in use, it will grab exclusive control of the audio device, which will prevent Audacity (and any other non-ASIO apps) from accessing the device.

**Comment by jeffagwm** [comment]
@SteveDaulton I don't have anything esle currently running. It still does not work if I reboot the computer and the just try to open audacity, it does not detect and devices and gives the Internal PortAudio Error

**Comment by jeffagwm** [comment]
@SteveDaulton So it appears that it is something to do with the built-in speakers on my laptop. If I disable them, Audacity opens, if I re-enable them, Audacity again will have the same error. The driver, from Realtek, is up to date with a driver date of 7/6/2021 and a version number of 6.0.9202.1
