### ISSUE TITLE
Cmake error macOS 

### ISSUE THREAD

**Issue by markusqw1** [audacity/audacity#1520]
I am on macOS big sur and i keep getting cmake errors. I have followed the building.md. Please help

CMake Error at /usr/local/Cellar/cmake/3.21.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
  wxWidgets_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.21.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.21.1/share/cmake/Modules/FindwxWidgets.cmake:1025 (find_package_handle_standard_args)
  vcpkg/scripts/buildsystems/vcpkg.cmake:782 (_find_package)
  lib-src/libnyquist/CMakeLists.txt:263 (find_package)

**Comment by crsib** [comment]
You probably have mistaken this repo with Tenacity. We do not use VCPKG
