### ISSUE TITLE
Build fails because portaudio.com is down

### ISSUE THREAD

**Issue by efokschaner** [audacity/audacity#1523]
**Describe the bug**
Conan step fails during CMake configure because portaudio.com is down.
The conan recipe for portaudio defined by audacity project https://github.com/audacity/conan-recipes/blob/main/portaudio/all/conandata.yml#L3 references http://files.portaudio.com/archives/pa_stable_v190700_20210406.tgz which fails to download.

See https://github.com/PortAudio/portaudio/issues/634 for the upstream issue report.

**To Reproduce**
1. Clone this repo (on windows but it probably affects all conan-using platforms)
1. Follow the build instructions to CMake configure
1. See an error downloading http://files.portaudio.com/archives/pa_stable_v190700_20210406.tgz

**Expected behavior**
CMake configure should complete without error

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version: master (45a90e38a3dd5f799244057b3c512943dca8e3e8)

**Additional context**
The issue appears to be able to be worked around by using the source distribution from the GitHub release, rather than the portaudio.com website. The main fix looks like this:
```
    url: "https://github.com/PortAudio/portaudio/archive/refs/tags/v19.7.0.tar.gz"
    sha256: "5af29ba58bbdbb7bbcefaaecc77ec8fc413f0db6f4c4e286c40c3e1b83174fa0"
```
I'll throw a PR over to the https://github.com/audacity/conan-recipes repo in case it's a desirable solution.

**Comment by crsib** [comment]
Sounds really good to me!

**Comment by crsib** [comment]
This issue should be now fixed, thank you again!
