### ISSUE TITLE
Quiet Sound

### ISSUE THREAD

**Issue by gemgithuberror** [audacity/audacity#1530]
Open audacity, begin recording and despite settings being the same as normal, the sound comes out extremely quiet and cannot not be enhanced with filter curve features.  

It used to work and now it doesn't. It also works sometimes but not others times. 

I opened it and recorded and it seemed to be working ok and then I clicked the 'x' to get rid of the recording and start again and then began recording and it went quiet again and I can't work out why and how to fix it. 

I thought it was the blue yeti mic I was using but I have a replacement and the same issue occurs. It worked before so I can't see why it would be my device but I have no other device to check it on. Have you experienced this issue before? What can be done to fix it? 

Here is a normal recording:
![image](https://user-images.githubusercontent.com/89518294/130771510-2b063e21-8b3d-4a62-a364-266a2bd9084e.png)

and here is what is looks like when the error occurs:

![image](https://user-images.githubusercontent.com/89518294/130771660-753c28ce-b68d-46f0-873b-f440ef0130fb.png)

The version is 3.0.3 

I am using a dell laptop and Windows 10 version 21H1

I am using a Blue Yeti USB mic - https://www.bluemic.com/en-gb/products/yeti/ 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional information (please complete the following information):**
 - OS: [e.g. Mac High Sierra, Ubuntu 18.04, Windows 10]
 - Version [e.g. Audacity 2.5.1]
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]

**Additional context**

**Comment by LWinterberg** [comment]
Hello! The bug tracker isn't the best place for troubleshooting like this, so sorry for the late reply. 

I think this isn't an Audacity bug, as your input volume seems to have been the same. You say that you can replicate this with different mics - but can you reproduce this with a different USB cable, connected to a different USB port, or even a different computer if you've got access to that? If not, my guess is that this would be a hardware issue.

**Comment by SteveDaulton** [comment]
Ensure that Windows Sound "Enhancements" are all disabled for the USB device (See: [Why do my recordings fade out or sound as if they were made in a tunnel](https://manual.audacityteam.org/man/faq_recording_troubleshooting.html#enhancements))

If that doesn't fix it, I'd recommend asking on the Audacity forum: https://forum.audacityteam.org/viewforum.php?f=46
