### ISSUE TITLE
 Linux: Interface issues with GTK3

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1536]
**Describe the bug**
Linux: Some elements of the interface are malformed when Audacity is built with GTK3.

When Audacity is built with gtk3 on Linux, some elements are malformed, notably the Device Toolbar appears to be empty, and text in the track's control panel is tiny.

Originally logged as Bugzilla P2 2705 (which is now closed in favor of this GtiHub Issue)
https://bugzilla.audacityteam.org/show_bug.cgi?id=2705
Bug 2705 - Linux: Interface issues with GTK3

**To Reproduce**
1. Build Audacity with gtk3.
2. Observe the Interface.

**Expected behavior**
Properly formed GUI

**Screenshots**
None available yet

**Additional information (please complete the following information):**
 - OS: Linux
 - Version [e.g. Audacity 2.5.1]
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]

**Additional context**
The tiny text in the track's control panel appears to be related to "Font dpi" settings. 

Whereas increasing the Font dpi is supposed to make text bigger, in the case of the track's control panel, increasing the Font dpi makes the text smaller!

----

The malformed Device Toolbar appears to be independent of the Font dpi. 

The first and last drop-down menus "appear" to be empty with default settings. The text in the boxes is aligned such that the right hand end of the longest string is aligned to the right hand end of the box. All shorter strings are displaced to the left by trailing whitespace.

Because the default text is much smaller than the longest item in the list, all that is visible by default is the trailing whitespace.

**Comment by LWinterberg** [comment]
outside of HiDPI stuff (see https://github.com/audacity/audacity/issues/503), GTK3 builds look alright to me. Not that it matters too much as the appimage remains on GTK2 and the switch to Qt makes this not worth tackling.
