### ISSUE TITLE
Mac/Linux: No error message when attempting to save to SMB drive

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1537]
**Describe the bug**
Mac/Linux: No error message when attempting to save to SMB drive.

Originally logged as Bugzilla P2 2755 _(which is closed in favor of this GitHub Issue)_
https://bugzilla.audacityteam.org/show_bug.cgi?id=2755
Bug 2755 - Mac/Linux: No error message when attempting to save to SMB drive 

**To Reproduce**
See this Forum post
https://forum.audacityteam.org/viewtopic.php?f=70&t=117675
Can't open/save .aup3 projects to network drive (3.0.2)

**Expected behavior**

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS: macOS & Linux
 - Version: Audacity 3.0.2

**Additional context**

**Comment by LWinterberg** [comment]
This is not actionable - remote drives generally don't appear any different to other drives, depending on how they're mounted. Additionally, with the right infrastructure, network drives can be similarly fast and low latency as internal drives, which won't cause errors.
