### ISSUE TITLE
 Linux: Font size scales incorrectly

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1538]
**Describe the bug**
 Linux: Font size scales incorrectly

The system provides an "Appearance" app for selecting default fonts and scaling.
On high dpi monitors it is necessary to increase the scaling so that apps are comfortably usable.

When the scaling factor is > 100%, fonts should be bigger, but in Audacity some of the fonts become smaller! (example, text in the track's control panel).

Even on my (Steve's) 1920 x 1080 display this makes it difficult to read parts of the interface. I don't have a 4k or 5k monitor, but we have multiple reports on the forum that Audacity is virtually unusable on high dpi displays.

**To Reproduce**
1. Launch Audacity on a high dpi monitor.
2. Observe that some of the text is minute.

**Expected behavior**
Font size scaling correctly

**Screenshots**

**Additional information (please complete the following information):**
 - OS: Linux - tested on Xubuntu 20.04 LTS
 - Version all

**Additional context**
This was originally logged as Bugzilla P2 2757 _(which is now closed in favor of this GitHub Issue)_
https://bugzilla.audacityteam.org/show_bug.cgi?id=2757
Bug 2757 - Linux: Font size scales incorrectly

**Comment by LWinterberg** [comment]
Btw, just to give some context on how this bug actually looks like: This is it on default settings, where Gnome automatically identified my 4k@15.6" screen should be scaled 200%. 

![Bildschirmfoto von 2021-09-01 13-39-29](https://user-images.githubusercontent.com/87814144/131665292-e09c1af1-7db7-49c5-941f-2a8a85a5e524.png)

**Comment by a-munro** [comment]
I also have this issue on Ubuntu 20.04. Appearance similar to LWinterberg's screenshot.

**Comment by Frydac** [comment]
Just to add another screenshot, using Manjaro with Gnome with 1.5 scaling on a 27" 4K monitor:

![audacity_scaling](https://user-images.githubusercontent.com/2588526/159958009-1701cd0d-435a-4bdf-8ae5-b903f83cc7bf.png)

I use this tool a lot as an dev working in the audio industry, but now I have my 4K monitor.. not so usable anymore

**Comment by LWinterberg** [comment]
we're not looking to address HiDPI support in the current wxWidgets version, but will certainly do in Qt (Audacity 4.x).
