### ISSUE TITLE
Sync-lock not honored when Timeshifting labels

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1540]
**Describe the bug**
Sync-lock is not honored when Timeshifting labels.

If you have sync-locked audio clip and associated label:
a) when you timeshift the selected label (either from the Clip-handle drag-bar affordance or by using the Time Shift tool) then the label moves on sync with the clip.
b) BUT if you select the label and timshift it (either with the new label drag-bar or by using Time Shift Tool) the only the label moves - and thus the sync-lock is ignored

This was originally logged as Bugzilla 2813 _(which is now closed in favor of this GitHub Issue)_
https://bugzilla.audacityteam.org/show_bug.cgi?id=2813
Bug 2813 - Sync-lock not honored when Timeshifting labels 

**To Reproduce**
1) create a project with 3 labeled audio clips (see screenshot below)
2) Turn on sync-lock
3) select just the second audio clip
4) Observe: synced clock icons in the associated label
5) with the Clip-handle drag-bar affordance (or the Time Shift Tool)  move the audio clip left or right
6) Observe: the label moves in sync with the audio - _expected behavior_
7) select just the second label range in the label track
8) Observe: synced clock icons in the associated audio
9) with the label drag-bar or the Time Shift Tool move the label left or right
10) Observe: the label moves but the audio does not move in sync - _incorrect behavior, sync-lock ignored_

**Expected behavior**
Sync-lock to be honored regardless of the selection

**Screenshots**
![image](https://user-images.githubusercontent.com/50205984/130963275-ec351d95-dbc1-4a36-b316-7a78ad1ed02f.png)

**Additional information (please complete the following information):**
 - OS: Windows 10 - but assume all OS
 - Version Audacity 3.1.0

**Additional context**
With the focus on drag-bars for 3.1.0 I think it's fairly important to fix this for 3.1.0 release.  Hence I logged this here as P2 upping it from the previous P3 it had on Bugzilla.

The original bug was logged pr drag-bars so the Steps then only focused on Tome Shift tool

**Comment by petersampsonaudacity** [comment]
@Penikov   Pavel can you please assign a P rating for this (I think it's P3 marginal P2)

**Comment by LWinterberg** [comment]
this won't get fixed and instead be replaced with grouping
