### ISSUE TITLE
The cursor doesn't change appearance while it's hovering a label handle or dragging the label (affordance)

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#1544]
**Describe the bug**
The cursor doesn't change appearance while it's hovering a label handle or dragging the label (affordance)

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a label track
2. Add some selection labels
3. Hover or drag the label handle

**Expected behavior**
![изображение](https://user-images.githubusercontent.com/25851359/131110255-5c234532-4856-4ae9-b968-f62a87f74f2b.png)

**Screenshots**

https://user-images.githubusercontent.com/25851359/131110378-ec8d4b5a-8541-4917-abf6-2a210be8e01e.mp4

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version Audacity 3.0.4

**Comment by AnitaBats** [comment]
Please test after #1444 is done @Penikov

**Comment by Penikov** [comment]
Fixed
