### ISSUE TITLE
German keyboard: Trying to enter digit 8 or 9 into project sample rates opens a dialog instead

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1548]
**Describe the bug**
With a German keyboard: Trying to enter digit 8 or 9 into project sample rates opens a dialog instead

This was originally logged on Buzilla as
https://bugzilla.audacityteam.org/show_bug.cgi?id=2781
Bug 2781 - German keyboard: Trying to enter digit 8 or 9 into project sample rates opens a dialog instead

**To Reproduce**
1) Focus the project sample rate field
2) Type digit 8 into sample rate field
3) Observe dialog
4) Close the dialog for adjusting the left selection border that just opened
5) Type digit 9 into sample rate field
6) Observe dialog
7) Close the dialog for adjusting the right selection border that just opened

**Expected behavior**
The ability to enter 8 or 9 into project sample rate.

**Screenshots**
See attachment in Bugzilla bug thread

**Additional information (please complete the following information):**
 - OS: all
 - Version Audacity all

**Additional context**
**Workaround:** 
The keyboard shortcuts for left at playback position and right at playback position are [ and ] respectively. If you either
a) clear them or 
b) set them to g and h, for example, 
that will fix the problem.

**Comment by LWinterberg** [comment]
I can reproduce this. It only appears with the "normal" digits, not the numpad digits.

**Comment by LWinterberg** [comment]
superseded by #5868
