### ISSUE TITLE
Win/Mac: Audacity fails to play 256 stereo tracks

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1551]
**Describe the bug**
While Auadacity will happily plat audio from a project with 128 stereo tracks it fails when you double that to 256 tracks (so the failure occurs with some number larger than 128 and smaller than 256, it is theought the boundary limit may be 214 but YMMV.

The user gets two error messages, neither of which is at all helpul or informative.

This was originally logged as P3 Bug 2804
https://bugzilla.audacityteam.org/show_bug.cgi?id=2804

**To Reproduce**
1) create a project with 128 x 1 minute stereo tracks
2) Press Play
3) Observe Audacity plays properly
4) Select all
5) Ctrl+D to create aan addition 128 tracks
6) Press Play
7) Observe: Error message (acually an "i" information)
>Out of memory
8) Press OK
9) Observe: error message
>Error opening sound device

Now the first error message is somewhat meaningless to the user, not helful as it gives them no idea what is wrong - or how thay may correct it.

The second message is just plain wrong and misleading to the user - there is nothing wrong with the sound device as step 3 shows.  Indeed using Ctrl+Z after Step 9 to revert to just 128 devices and pressing Play one observes that again Audacity plays just fine.

**Expected behavior**
a) the ability to play a lage number of tracks
b) as sensible informative helpful error message when it fails

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS: Windows a0 and macOS
 - Version: all

**Additional context**
Note that while Audacity will not play the 256 tracks, once you have dismissed the erroneous "error opening sound device" error dialog, you can select all and apply effects quite happily.

**Comment by Ryan-Miller-Audacity** [comment]
I retested this against 3.2.2 and had no issues playing a large (obscenly large at that (256+)) number of tracks. Playback worked as expected and no error messages were experienced.

Closing as no longer reproducible.
