### ISSUE TITLE
Screenshot incorrect after first screenshot

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1554]
**Describe the bug**
The screenshot tool produces incorrect images after the first screenshot of the same kind.

Taking a second screenshot of a track, or the main window (or probably any other option) works correctly the first time, but if you modify the view and then take another screenshot of the same type, the second screenshot is wrong.

Example include:
1. Screenshot of main window.
2. Resize the window.
3. Take another screenshot of the window.

1. Screenshot of a track
2. Zoom in or out.
3. Take another screenshot of the track.

This was originally logged on Bugzilla as P3 2719
https://bugzilla.audacityteam.org/show_bug.cgi?id=2719

**To Reproduce**
1. Launch Audacity
2. Generate or import a visually distinctive audio track.
3. Take a screenshot of the track
4. Zoom in or out so that the visible track is visibly different.
5. Take another screenshot of the track.
6. Observe that the second screenshot does NOT match the appearance of the track.

**Expected behavior**
Screenshot tool to work correctly each time the user uses it.

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS: all OS
 - Version all Audacity 

**Additional context**
On Bugzilla James asked if this was a regression on 2.4.2

This does not appear to be a regression on 2.4.2 - with both 2.4.2 and latest 3.0.3/4 I get the same erronouus image from both of then when I ask screenshot for "First Track".

The second use is the same image result.

I note that the dialog for the Screenshot tool starts out over the Audacity Window and thus has to be moved away from the Audacity window as otherwise (part of) the Screenshot dialog is captured superimposed.

**Comment by NoobMaster1999** [comment]
I can't reproduce the bug
the screenshots are fine for me

**Comment by SteveDaulton** [comment]
It's also working for me with Audacity 3.1.0 alpha.
Tested on Xubuntu 20.04.
