### ISSUE TITLE
Mixer Board shows wrong no. of tracks when splitting or joining stereo tracks

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1557]
**Describe the bug**
The Mixer Board shows the wrong number of tracks when splitting stereo tracks (to either mono or split stereo)and when joining mono tracks to make stereo.

Happens on both Win and Mac so assume all platforms.

This is a regression on 2.3.0, introduced in 2.3.1

The situation corrects itself when you add further tracks.

Originally logged on Bugzilla as Bug 2693
https://bugzilla.audacityteam.org/show_bug.cgi?id=2693

**To Reproduce**
1) get a stereo track
2) View > Mixer Board
3) Observe: a single track in the Mixer Board (expected OK)
4) Split the stereo track
5) Observe: MB still shows incorrectly only one track

A1) get a mono track
A2) View > Mixer Board
A3) Observe: a single track in the Mixer Board (expected OK)
A4) duplicate the mono track
A5) Observe: MB correctly shows two tracks
A6) join the two mono tracks to make a single stereo track
A7) Observe: MB still shows wrongly 2 tracks not 1

**Expected behavior**
The correct number of tracks ro be shown in the Mixer Board

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS: all OS
 - Version Audacity 3.0.4

**Additional context**
This just looks bad ...

**Comment by Ryan-Miller-Audacity** [comment]
I found this to still be the case in Audacity 3.2.2; however, this will likely be held off since the mixer will get a full rework/redesign during the QT migration/upcoming releases. Therefore, we'll close this item for the time being as a known issue not planned for immediate timeline.
