### ISSUE TITLE
Mac: no thousands separator in toolbars: Timer, Selection or Spectral Selection in Deutsch locale

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1558]
**Describe the bug**
On macOS in Deutsch locale there is no thousands separator in the following toolbars: 
a) Timer, 
b) Selection,
c)  Spectral Selection 

This was originally logged as Bugzilla P3 2662
https://bugzilla.audacityteam.org/show_bug.cgi?id=2662

**To Reproduce**
1) change the Time toolbar to "Seconds"
2) show the Spectral Selection toolbar
3) change the Selection toolbar to seconds
4) In Interface preferences change the language to Deutsch
5) Observe: the radix (decimal) separator is correctly "," comma
6) Observe: there is no separator for the thousands

**Expected behavior**
A thousands separator to be shown (as happens in other locales)

Deutsch locale this should be:  narrow-space (a Unicode character)

**Screenshots**
None 

**Additional information (please complete the following information):**
 - OS: macOS
 - Version:  all Audacity

**Additional context**
Prior to 3.0.0 the thousands separator used was "."  (period/full-stop) in the Timer and Selection toolbars (the Spectral Selection toolbar had no thousands separator for Hz fields.

We fixed Bugzilla #2659 on Windows for 3.0.0 by using the preferred narrow-space (a Unicode character).
>Number separators are wrong in the German locale

On testing that fix this residual remains whereby there is no thousands separator displayed on Mac in the three toolbars: Timer, Selection and Spectral Selection.

It is possible that this may be down to the way that Mac handles (or does not handle) Unicode characters.

**Comment by dozzzzer** [comment]
Still the case in 3.3.2

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
