### ISSUE TITLE
With focus on a track, changing settings in a floated toolbar causes the track to lose focus

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1559]
**Describe the bug**
With focus on a track, changing settings in a floated toolbar causes the track to lose focus.

Curiously the track's focus is restored if you redock the toolbar immedaitely after the setting change.

Having the focus behave as expected is important for keyboard users. For them, it's not a minor issue.

This was originally logged on Bugzilla as P3 Accessibility issue 1921
https://bugzilla.audacityteam.org/show_bug.cgi?id=1921

**To Reproduce**
1. undock/float any toolbar with a slider from the tooldock areas
2.  get some audio
3.  ensure focus is on the track
4.  change the slider settings on the floated toolbar
5.  observe yellow focus border disappears from the track
6.  redock the toolbar in either tooldock
7.  observe yellow focus border is restored to the track

**Expected behavior**
Focus to remain on the track

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS: all OS
 - Version [e.g. Audacity 3.0.4 and earlier

**Additional context**
This is a close relative of Bug 1920 
https://bugzilla.audacityteam.org/show_bug.cgi?id=1920
(which is a Mac-only bug) - this happens on W10 as well as Mac so assume all

Leland wrote on Bugzilla:
>My comment in 1920 pertains here as well.  Once undocked, a toolbar simply becomes a modeless dialog and if you click in a modeless dialog the focus transfers to it, thus the track focus ring disappears since it no longer has the focus.
I do see what you're getting at here though.  An undocked Edit toolbar probably shouldn't take the focus since having to switch back to the track panel each time

**Comment by petersampsonaudacity** [comment]
See also:
 Mac: undocking any tool removes track focus #1560

**Comment by LWinterberg** [comment]
Any sort of docking behavior won't survive to Qt, and this particular bug won't be fixed beforehand.
