### ISSUE TITLE
 "Editing a clip can move other clips" ignored when "Sync-Lock" enabled

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1570]
**Describe the bug**
The "Editing a clip can move other clips" preference setting is ignored when Sync-Lock is enabled. When Sync-Lock is enabled, editing a clip can move other clips regardless of the setting in Preferences.

The setting "Editing a clip can move other clips" appears to be clear and unambiguous. 
* If you want editing a clip to be able to move other clips, then this setting must be enabled.
* If you do not want editing a clip to be able to move other clips, then this setting must be disabled.

Unfortunately that's not what happens if Sync-Lock is enabled.

Originally  logged on Bugzilla as P3 2601
https://bugzilla.audacityteam.org/show_bug.cgi?id=2601

**To Reproduce**
1. Create a track with two clips and a small gap between the clips.
2. Ensure that "Editing a clip can move other clips" is disabled.
3. Copy some audio that is longer than the gap between the clips.
4. Enable "Sync-Lock" (note there are no Sync-Locked groups)
5. Paste the clipboard into the first clip (at a point within the first  clip).
6. Observe that the second clip moves.

**Expected behavior**
The "Editing a clip can move other clips" preference setting should not be ignored when Sync-Lock is enabled

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS: all OS
 - Version Audacity 3.0.0 and on

**Additional context**
Steve wrote on Bugzilla:
>I see that this was introduced here:
https://github.com/audacity/audacity/commit/2d2f282c83574a39f4935d93b5ca1a13f7f9c806
In my opinion this fix is wrong because it makes an unambiguous setting ambiguous.
The bug that this fix was intended to remedy was about "assertion violation" (see bug 825) but the fix goes much further and overrides a preference setting without warning.
Note that "Editing a clip can move other clips" is ignored even when there are no Sync-Locked groups.

**Comment by LWinterberg** [comment]
this part of sync lock functionality will get replaced by clip grouping
