### ISSUE TITLE
The project file is being corrupt if it's opened while Audacity is running.

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#1571]
**Describe the bug**
The project file is being corrupt if it's opened while Audacity is running.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run Audacity
2. Open some project
3. Press Cmd + O and open another project

**Actual behaviour**
Audacity corrupts the second project

**Expected behaviour**
Another project is opened successfully

**Screenshots**
https://www.srut.de/audacity/audacity-3040-problem--opening-a-file-via-keyboard-shortcut-corrupts-file-irreversibly.mov

**Additional information (please complete the following information):**
 - OS:  Mac OS Big Sur
 - Version Audacity 3.0.4

**Comment by JohnColket** [comment]
This issue has been reported by at least four(4) different users on the forum on the following two threads:
"aup-3 files are empty when they are opened":  https://forum.audacityteam.org/viewtopic.php?f=47&t=119330&sid=18e2f302da2d3b1fd5bad5a0c59c4542
and "Opening a file via keyboard shortcut corrupts project file irreversibly": https://forum.audacityteam.org/viewtopic.php?f=47&t=119956
The four reporting users are: Baum123, Carpezaldo, lilouch, and mathpoli.

**Comment by petersampsonaudacity** [comment]
I cannot reproduce this on W10 with 3.1.0 alpha audacity-win-3.1.0-alpha-20210831+6d3dd0c-64bit

Both projects open fine - no cirruption that I can detect

**Comment by mathpoli** [comment]
Hi, may I point you to what I have found out and posted on the Audacity forum?
https://forum.audacityteam.org/viewtopic.php?f=47&t=119956&start=20

**Comment by mathpoli** [comment]
SUMMARY:
So far I have tested on these iMacs and had on all the bug:

– 1x iMac (Retina 5K, 27 Inch, Late 2015), Intel Core i5, with macOS 10.15.7 (internal Fusion Drive): Audacity v3.0.4.0, Audacity v3.0.3.0, Audacity v3.0.2.0
same iMac with macOS Big Sur (external USB drive): Audacity v3.0.4.0
same iMac with macOS 10.14.6 (external USB drive): Audacity v3.0.4.0

– 2x iMac (Retina 5K, 27 Inch, Late 2015), Intel Core i7, with macOS 10.15.7 (internal SSD, first partition), Audacity v3.0.4.0
same 2 iMacs with macOS 10.13.6 (internal SSD, second partition): Audacity v3.0.4.0

– 1x iMac (21.5 Inch, Late 2009), Intel Core2Duo, with macOS 10.11.6 (internal HD): Audacity v3.0.4.0

Audacity v3.0.0.0 runs on all the above iMacs without the bug.

Four different iMacs, four different OS. I may have the opportunity to test on two more Macs: 1x MacMini (i7, Late 2012, with 10.15.7) and 1x iMac Retina 5K (i7?, 2017?, with 10.15.7) if it helps.

**Comment by mathpoli** [comment]
Has this been reported only by Mac users? The above mentioned 4 users (Baum123, Carpezaldo, lilouch, and mathpoli) all have Macs.

**Comment by JohnColket** [comment]
Yes. This appears to be a MAC only problem.

**Comment by thynus** [comment]
Downloaded and installed v3.0.4.0 from audacity.
I cannot reproduce this on the following macos systems:

macos 10.13.6 i5 macbook pro early 2015 RAM 8GB SSD 70 GB unused
macos 11.5.2 m1 mac mini RAM 8GB SSD 120 GB unused

Created 2 aup3 projects with 3 clips in each.  Each test project was 261MB and 158.8MB Opened using both keyboard and menu mouse clicks.  Audacity created a 0 byte .wal file for each project which then disappeared once Audacity was closed.

Contents in either project did not disappear; changes when saved persisted.  Quitting without any change in the project
