### ISSUE TITLE
Odd behavior of selection by label clicking with multiple SLTGs

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1572]
**Describe the bug**
When using more than one sync lock group and selecting a label by clicking on it, the actual selection made in audio tracks may involve tracks in other sync lock groups too.  What gets selected is not what you'd expect, making clicking on a label to select audio less useful than it should be.

Originally logged in Bugzilla as P3 2461
https://bugzilla.audacityteam.org/show_bug.cgi?id=2461

**To Reproduce**
1. get two mono tracks
2. add a label track
3. add a label, test-1, for part of the range
4. add two more mono tracks
5. add a label track
6. add a label, test-2, for part of the range (different to range in Step 3)
7. add a mono track
8. add a label, test32, for part of the range (different to range in Steps 3 and 6)
9. turn on sync-lock

10. Click in any of the 3 tracks (audio or label) in the first SLTG
11. Click in the test-2 label in the second SLTG
12. Observe:  the selection is for the length of test-2, but is in the track that was clicked in in track 7

**Expected behavior**

**Screenshots**
Attachment shows an example of setup for the test
![image](https://user-images.githubusercontent.com/50205984/131353574-6002ac26-f68f-4172-81c1-2e5bb2d06e42.png)

**Additional information (please complete the following information):**
 - OS: all OS
 - Version Audacity 2.4.2 and onwards

**Additional context**
The steps to reproduce are just one example.  Basically what seems to be happening is that 
a) if you have point or range selections on single or multiple tracks
b) click on a label in an SLTG which is not part of the selection(s) in step a
c) then the selection is made of the length of the label in step b - not in that SLTG but in all of the tracks selected in a)

It's also a bit odd trying to make selections in a situation where you have audio tracks and a label track effectively a SLTG - but it doesn't matter if sync-lock is on or not.

1. get several audio tracks
2. add a label track
3. add a range label
4. make a selection in one or some of the audio tracks
5. click in the label from step 3
6. Observe:  selection is made for length of label in the previously selected tracks.

7. Click anywhere in the label track (or in the gray space)
8. click in the label from step 3
9. Observe:  selection is made for length of label for the whole project

Now these may (or may not) be expected/designed behaviors, but I'm pretty sure that we haven't documented them.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
