### ISSUE TITLE
Plot Spectrum mishandles Nyquist frequency

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1573]
**Describe the bug**
Plot Spectrum: Frequencies close to the Nyquist frequency may display much higher than the actual level.
If the selected audio has audio at the Nyquist frequency, the spectrum plot shows that content much too high.

This is easiest to see with a very small window size (128 or 256) and Linear scale.

A suitable test tone may be generated in the Nyquist prompt with this code:

(sum
(mult 0.8 (hzosc 689.0625))
(mult 0.05 (osc (hz-to-step 22050) 1 *table* 90)))

Expected result with the test tone:

A large peak on the left side of the plot, and a much smaller peak at the right edge.

Actual result, big peaks on both the left and right edges. The plot at the right edge appears to go off the scale.

Originally logged as Bugzilla P3 2412
https://bugzilla.audacityteam.org/show_bug.cgi?id=2412

**To Reproduce**
1. Analyze audio that contains audio at the Nyquist frequency with Plot Spectrum. 
2. Observe: the peak at the right edge is considerably higher than expected.

See bug description for a convenient way to generate a test tone.

**Expected behavior**

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS: all OS
 - Version 2.4.0 and onwards

**Additional context**
An analyzer that gives wrong results is not fit for purpose, and should be release noted.

It is suspected that DC is also incorrect, though this is difficult to confirm visually, and the exported data excludes the DC component.

**Comment by dozzzzer** [comment]
The issue is no longer reproducible as of 3.4.2:

<img width="450" alt="image" src="https://github.com/audacity/audacity/assets/70063970/93eeeab7-97d6-42b0-a0bb-b68de2f53233">
