### ISSUE TITLE
Scrubbing head moves left to right in right to left scrubbing

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1575]
**Describe the bug**
Scrubbing head moves left to right in right to left scrubbing

Originally logged on Bugzilla as P3 1960
https://bugzilla.audacityteam.org/show_bug.cgi?id=1960

**To Reproduce**
1. Record 10 seconds of audio.
2. Zoom in to about one second of it.
3. Use scrubbing to play the audio, scrubbing both left to right and right to left.
4. Observe:   When scrubbing right to left, the play head repeatedly moves left to right and then jumps.

5.  Set the latency buffer length to 5000ms
6.  Set Audio host to MME or WDS
7.  Record 10 seconds of audio.
8.  Use scrubbing to play the audio, scrubbing both left to right and right to left.
9. Observe: Again, when scrubbing right to left, the play head repeatedly moves left to right and then jumps.

**Expected behavior**
Scrubbing head to move smoothly

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS: all OS
 - Version 2.3.0 and onwards

**Additional context**
Paul wrote on Bugzilla:
>I observe it isn't always right-to-left movement that is bad.
It seems, whichever movement you do first, is good, but then reversal of direction shows the bad behavior.  The good and bad directions remain the same throughout the scrub thereafter, even if there are other reversals.

I Observed:  Actually in Seeking the head judders left-rofght-left-right-left ...

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
