### ISSUE TITLE
Scrubbing & Seeking breaks down at 5 x zoom-in levels and greater

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1576]
**Describe the bug**
If you zoom in more than five times from normal default zoom level you will find that scrubbing produces erratic playback

With all 3 hosts: MME, WDS & WASAPI  (but assume all platforms) Scrubbing works properly when zoomed in only to four levels of zoom-in.  Further zooming will cause Scrubbing to become erratic (see "Steps...").

The more you zoom in the worse it gets.

Originally logged on Bugzilla as P3 1976
https://bugzilla.audacityteam.org/show_bug.cgi?id=1976

**To Reproduce**
1. get audio at normal zoom level
2. zoom in 5 times
3. start Scrubbing
4. move cursor to left edge to get backwards scrubbing
5. observe when Scrubhead reaches the leftmost waveform edge scrubbing breaks up and is erratic

6. move cursor back to middle of waveform
7. Subscribing becomes very erratic, only eventually calming down and stopping

8. move cursor to right edge to get forwards scrubbing
9. observe when Scrubhead reaches the rightmost waveform edge scrubbing breaks up and is erratic

10. zoom in further
11. observe the above problems getting worse

12. zoom normal & zoom in 4 times
13. observe that scrubbing is ok

**Expected behavior**
Scrubbing & Seeking to work at 5 x zoom-in levels and greater.

**Screenshots**

**Additional information (please complete the following information):**
 - OS: all OS
 - Version: Audacity 2.3,0 and onwards

**Additional context**
None.

**Comment by Penikov** [comment]
Still reproducible in 3.1.3

**Comment by LWinterberg** [comment]
we're planning a new scrub behavior eventually which will incidentally fix this
