### ISSUE TITLE
Bad link to FFmpeg on the Plug-ins page on the Audacity Website

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1579]
**Describe the bug**
A Forum user has reported a bad link to FFmpeg on the Plug-ins page on the Audacity Website:
https://forum.audacityteam.org/viewtopic.php?f=20&t=120063

**To Reproduce**
1. Go to https://www.audacityteam.org/download/plug-ins/
2. Scroll to the bottom of the page
3. Click on "FFmpegFAQ" link
4. Observe bad link: https://manual.audacityteam.org/man/#ffdown

**Expected behavior**
"FFmpegFAQ" should link to:
https://manual.audacityteam.org/man/faq_installation_and_plug_ins.html#ffdown

**Screenshots**
![image](https://user-images.githubusercontent.com/50205984/131467590-7c6a018d-0337-47f0-80b2-5f506aa32051.png)

**Additional information (please complete the following information):**
 - OS: all OS
 - Version [Audacirt version not applicable
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]

**Additional context**
This should be fixed ASAP

**Comment by LWinterberg** [comment]
fixed
