### ISSUE TITLE
Journal play/record interrupted by stop button

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#1592]

**Comment by SteveDaulton** [comment]
This issue makes no sense.
Surely there has to be a way to "interrupt" recording so that it does not continue for eternity (?)

**Comment by LWinterberg** [comment]
@SteveDaulton This is about journaling - Paul is working on a thing that, when enabled, automatically logs every action you take in Audacity and lets you replay them later, for QA purposes. 

With that background, my assumption for this task is that Paul wants to make the stop button work in journals :)
