### ISSUE TITLE
Equalization, Change effects and some other effects ignore and remove any amplitude envelope

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1595]
**Describe the bug**
Equalization and Change effects ignore and remove any amplitude envelope.

Using either of the two EQ effects or any of the three Change effects (Sped, Pitch or Tempo) ignore and corrupt an amplitude envelope.

Originally logged on Bugzilla as P3 1686
https://bugzilla.audacityteam.org/show_bug.cgi?id=1686

**To Reproduce**
1. Create a mono DTMF.
2. Use envelope tool to reduce it to 1/4 amplitude.
3. Select 5s to 15s.
4. Apply Equalization (or Filter Curve or Graphic EQ)
5. Observe:  The audio in that section is boosted back to full amplitude.

**Expected behavior**
The EQ should observe/honor the envelope amplitude

**Screenshots**
![image](https://user-images.githubusercontent.com/50205984/131620687-dc67734b-93f6-4747-af65-e3abe4e9a711.png)

**Additional information (please complete the following information):**
 - OS: all OS
 - Version Audacity 3.0.4/3.1.0

**Additional context**
A fix was made for this up to and including 3.0.3 - but the fix was reverted for 3.0.4

See: Revert Bug 1686 - Equalization effects ignore and remove any amplitu… CMake Build #2522

and:   Release 3.0.4 #1526

**Comment by petersampsonaudacity** [comment]
Upgrading this to P2 
a) this was previously fixed for eralier versions and is this technically now a regression pn 3.0.3
b) Audacity should not be damaging users' audio data like this

**Comment by petersampsonaudacity** [comment]
Paulstretch is similarly afflicted.

**Comment by petersampsonaudacity** [comment]
Because so many effects are afflicted by this I have raised this to P1

**Comment by Penikov** [comment]
The issue is duplicating this one https://github.com/audacity/audacity/issues/1500

**Comment by Paul-Licameli** [comment]
@petersampsonaudacity call it regression, but the problem was not fixed properly and the change now reverted caused the explosion of envelope points for some users, with slow editing and extreme file sizes in GB.

whereas research of the bugzilla history shows the bug was tolerated for years as a low priority issue.
