### ISSUE TITLE
Bad results in Envelope, joining clips with gap between

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1600]
**Describe the bug**
Bad results in Envelope, joining clips with gap between.

Originally logged on Bugzilla as P3 1643 by Paul Licameli
https://bugzilla.audacityteam.org/show_bug.cgi?id=1643

**To Reproduce**
1. turn on full keyboard shortcuts in Keyboard prefs
2.  Create a wave track with two clips with a gap between
3.  Add envelope points to each clip.  (Various cases, below)
4.  Select a region that includes the gap, or just select all.
5.  Ctrl + J to join clips into one, with silence inserted in the gap.
6.  Observe: If the left clip contains one point or none, any point is lost, and the envelope level over the left part changes to match the start of the right clip.
7.  Observe: If the left clip contains at least two points at different levels, then the envelope in the gap extends level from its ending value at the left clip, and makes a discontinuity at the start of the right.

**Expected behavior**
It would make more sense to leave envelope levels always unchanged, and in the new silence, ramp from one level to the other, rather than extending flat from one or the other (why, aribitrarily, the left and not the right?).

**Screenshots**
After Step 7
![image](https://user-images.githubusercontent.com/50205984/131730760-b1b2f6a9-c28c-4e27-b20a-3af926dcde67.png)

**Additional information (please complete the following information):**
 - OS: [e.g. Mac High Sierra, Ubuntu 18.04, Windows 10]
 - Version [e.g. Audacity 2.5.1]
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]

**Additional context**
James wrote by email:
>1643 is not totally cosmetic, as the envelope affects generated audio that you could now add in - i.e. makes a difference not just to appearance.

**Comment by dozzzzer** [comment]
The issue is no longer reproducible.
