### ISSUE TITLE
Highest resolution selection formats don't show split line snap guides when they should when Snap-To is on

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1601]
**Describe the bug**
**A clear and concise description of what the bug is.**
Highest resolution selection formats don't show split line snap guides when they should when Snap-To is on

**To Reproduce**
1. 1) Create a tone. 
2.  Enable Snap-To (Prior or Nearest) in Selection Toolbar with format set to the default hh:mm:ss + milliseconds. 
3.  Add a label track or label.
4.  Click anywhere in the tone, or drag a region.
5.  Edit > Clip Boundaries > Split.
6.  In the label track, click as close to the split line as you can, or drag carefully to the split line. 
7.  Observe: No snap guide appears.  
8.  Zoom in and try to click in the label track directly under the split line. 
9.  Observe: No guide appears. 
10. Click or drag in waveform and split again, click again under the split line. 
11. Observe: No guide appears. 
12. Turn Snap to off, then as expected you can snap the pointer under the split line. 
13. Turn Snap to on again, create a new split, and label it. Now you can see the snap guides for this split line.

**Expected behavior**
Yellow snap guides to be shown

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS: all OS
 - Version: originally reported in 2,1,2 0 but still extant in 3.0.4 and alpha 3.1.0

**Additional context**
Gale Andrews wrote when he looged this in 2015
>None of the other lower resolution formats I tried creating split lines with e.g. seconds or hh:mm:ss + hundredths or CDDA frames have this problem.  hh:mm:ss + samples and samples have the above problems, but seemingly less so.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
