### ISSUE TITLE
Custom shortcuts can be overwritten without warning using Full set or importing shortcuts 

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1603]
**Describe the bug**
If when working with the default Standard shortcut set you set a custom shortcut that conflicts with one that is assigned in the Full shortcut set (but not in play) and then implement the Full set of shortcuts then your custom shortcut will be overwritten without warning.

If a user has the Standard set of shortcuts (default) - and then they
set a custom shortcut and select a key that is in the extended Full set.
a) this is allowed
b) it is silent with no warning
c) If the user then decides they want to activate the full set, their previously set custom shortcut is silently over-writtten with no warning message.

This can also happen at c) (Steps 5-6 in the Steps) if the user attempts to import a set of shortcuts which would cause an over-write (again with no warning).  While the no-warn behavior at step 3 (or b here) is probably OK, as the requested custom key/key-combination is available - and there is no loss of settings.  However at Steps 5-6 (c here) then a warning should be issued giving the user the  chance to accept the overwrite - or abort the Full set/import.

Note that Audacity does already give such a warning when a user manually tries to set a shortcut is already in use - so a warning in this use case here would be consistent.

Originally logged on Bugzilla as P3 1800
https://bugzilla.audacityteam.org/show_bug.cgi?id=1800

**To Reproduce**
1. clear config files (default Standard shortcuts)
2.  set "A" as a shortcut for "Tracks>Sync-Lock Tracks (on/off)
3.  observe that this works ok with no warning or blocking error
4.  test that the "A" shortcut works as intended to to, toggling Sync-Lock
5.  Edit>Preferences>Keyboard and select the "Full" set of shortcut
6.  observe that this works ok with no warning or blocking error
7.  Now test the"A" shortcut - it advances through the Tools in the Tools toolbar - and does not toggle the Sync-Lock state
8.  Edit>Preferences>Keyboard - a  search on the key "A" confirms that it is no longer assigned to sync-lock
9.  Restore the Standard shortcut set
10.  Observe: this works ok with no warning or blocking error
11.  Observe: the "A" shortcut now does nothing

**Expected behavior**
No overwriting of the custom shortcuts

**Screenshots**
None
**Additional information (please complete the following information):**
 - OS: all OS
 - Version: reported for Audacity 2.3.2  - bit still extant with 3.0.4 and alpha 3.1.0
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]

**Additional context**
Workaround:
1) temporarily set the Full short cut set to be on
2) try adding your custom shortcut(s_
3) if conflicts exists you will be warned
4) restore the reduced Standard set of shortcuts
5) now add your custom shortcuts

**Comment by LWinterberg** [comment]
we'll need to figure out better shortcuts but in general, if you reset your shortcuts to a default (whether it's the full set or the standard set), it's definitely not unexpected for them to reset your custom ones.
