### ISSUE TITLE
Linux: Toolbars malformed when not docked

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#1609]
**Describe the bug**
When not docked, most toolbars are malformed.

**To Reproduce**
1. Launch Audacity
2. Drag some toolbars out of their docked positions so they are "floating".
3. Observe that most of them are malformed and unusable.
4. Observe that the "Edit toolbar" is just a horizontal  black line, so can't even be dragged back and docked.

**Expected behavior**
Toolbars to be properly formed.

**Screenshots**
![toolbars](https://user-images.githubusercontent.com/11681097/131845673-ddb0583c-ed0e-47af-b874-5c32a2d1acb5.png)

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version audacity-linux-3.0.4-x86_64.AppImage

**Additional context**
See also: https://forum.audacityteam.org/viewtopic.php?f=46&t=119971

**Comment by SteveDaulton** [comment]
Bug is still present in Audacity 3.1.1

**Comment by LWinterberg** [comment]
this will get fixed with the switch to qt
