### ISSUE TITLE
Screenshot tool fails on dual monitor

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#1611]
**Describe the bug**
When using the screenshot tool on a dual monitor setup, most functions of the screenshot tool fail to save with the error "Failure trying to save file <path>". The only tool that works is the fullscreen screenshot, which will take a screenshot of screen 0 (ie the main screen), or a quarter of it anyway if you're on HiDPI, see #1608. 

**To Reproduce**
1. Use a dual monitor setup
2. Attempt to use the screenshot tool
3. observe the error it throws. 

**Additional information (please complete the following information):**
 - OS: Windows 11
 - Version Audacity 3.1.0-alpha-20210901
 - Screens: 4k @ 250% (Gigabyte Aero 15xv8 built-in), HD @ 100% (Sony Bravia TV)

**Comment by petersampsonaudacity** [comment]
See also:   Screenshot incorrect after first screenshot #1554 

They may be linked - or thay may be the same bug ...
