### ISSUE TITLE
Linux: Multiple problems with Label Editor

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1615]
**Describe the bug**
For non-mouse users navigating the Label editor using the keyboard (tab key) can be problemmatical.  The situation is worst on  Linux, but Mac and Windows both have accessibility issues.

The Label Editor does "mostly" work on Linux, but it is unintuitive and looks extremely buggy compared to previous Audacity releases.

Originally logged on Bugzilla as P3 2222
https://bugzilla.audacityteam.org/show_bug.cgi?id=2222

**To Reproduce**
1. Right click on a label and select "Edit".
Observe:  It is not possible to Tab into a cell. Is this by design?

2. Press F2 and the label name has focus.
Observe: Tab does not move focus to the next cell. I have not found any keyboard key to move focus to the next cell. Is there a magic key, or is this broken?

3. Click ONCE on the "Start Time" cell.
I would expect some visual indication that the cell is selected (such as a bold cell border). There is none.

4. Either click again in the "Start Time" cell, or press F2.
Observe: The Time Ctrl is active, but it is not possible to highlight any digit. It is therefore not possible to see which digit is selected for editing.

5. Type a new start time and Press Tab to move to the next cell.
Observe: Focus moves out of the Start Time cell, but there is no indication where focus has moved to. It does not appear to have moved to the next cell.

6. Click twice on the End Time cell.
Observe: The Start Time of the label is not yet updated, so blind faith that the label has updated as requested.  Again, there is no indication of which digit is selected in the Time Ctrl

7. Enter an End Time and tab out of the End Time cell.
Observe:  The End Time of the label is not yet updated, so again it is blind faith that the label has updated as requested.

8.  Keep tabbing
Observe:   Eventually, focus moves to the buttons (?)

9. Press "Enter".
Observe:  The Label is updated.

**Expected behavior**
Label editing to work properly for VI users on Linux

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS: Linux
 - Version: originally reported with 2.3.3 but believed to be still extant in 3.0.4 and alpha 3.1.0

**Additional context**
See Bugzilla bug thread for further discussion
https://bugzilla.audacityteam.org/show_bug.cgi?id=2222

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
