### ISSUE TITLE
Filter Curve (and other frequency scales) cut off higher frequencies

### ISSUE THREAD

**Issue by FedoraGameDev** [audacity/audacity#1617]
**Describe the bug**
The graph that displays Hz frequencies sporadically changes the frequencies shown. Usually, the frequencies go all the way up to 20K, however I can only see up to about 7K now. This makes using Filter Curve EQ impossible to use in those frequencies. When I import a preset, you can see the handles going off screen at the edge and the EQ does affect those frequencies properly, however there's no way to change the handle positions.

**To Reproduce**
1. Load in audio and select a range
2. Launch Filter Curve EQ Effect

**Expected behavior**
Graph should show the full spectrum by default. Alternatively, if we had handles added that let us zoom back out, this would be much better all around.

**Screenshots**
![image](https://user-images.githubusercontent.com/44219789/132057663-6528f728-7975-4f3c-b8df-966880e30df0.png)

**Additional information**
 - OS: Windows 10
 - Version: Audacity 3.0.4

**Additional context**
Every once in a while the graph will appear correct, however I have not been able to show it consistently.

**Comment by petersampsonaudacity** [comment]
I cannot reproduce this when testing on W10 with 3.0.4 and alpha 3.1.0

I consistently get the full frequency spectrum

![image](https://user-images.githubusercontent.com/50205984/132086336-d8605619-5197-471d-9d09-f2226e5e35fb.png)

**Comment by SteveDaulton** [comment]
Check the track sample rate (in the box on the left end of the track (See: https://manual.audacityteam.org/man/audio_tracks.html)

My guess is that the track sample  rate is 16000 Hz.
The highest possible audio frequency in a track is half the sample rate. If the track sample rate is 16000Hz as I suspect, then the track has an upper frequency limit of 8000 Hz, thus the the Filter Curve Eq range automatically adjust to 0 to 8000 Hz.

(If you're interested, the technical explanation is described here: https://en.wikipedia.org/wiki/Nyquist_frequency)
