### ISSUE TITLE
Insert Chinese Label, Audacity broken!

### ISSUE THREAD

**Issue by kewtgh** [audacity/audacity#1618]
**Describe the bug**

**When I inserted a label and switch to Chinese input method, the program stuck. 
Whatever I did, It doesn't respond.
It happened since version 3.03 and 2.* is OK. 
I use google pinyin as my Chinese input method.**

**To Reproduce**
1. Open an Audacity record.
2. Click on 'Edit'
3. Then click on 'Labels'
4. Then click on 'Add label at selection'
5. I can only insert English. Then CTRL+SHIFT to switch the input method.
6. See error, it stuck.

**Additional information (please complete the following information):**
 - OS: [Windows 10]
 - Version [Audacity 3.0.4]
 - Input APP [Google Pinyin 2.7]

**Additional context**

**Comment by LWinterberg** [comment]
Google Pinyin appears to be a dead program; [Google no longer offers it for download](http://tools.google.com/pinyin/). 

Using Microsoft Pinyin (which you can install via the Windows settings/language packs), I cannot get Audacity to hang. However, I also can't get any Chinese character recommendations/inserts to appear. 

Also, you say this happened with 3.0.3 - that happens to be the first version with 64-bit support. Maybe Google Pinyin doesn't play nice with 64 bit? You may want to try the 32-bit version of Audacity and see if that works.

**Comment by DavidBailes** [comment]
A work around would be to make use of the option to enter the name of the label in a dialog box.
In Preferences, on the Track behaviors page, check the "Use dialog for the name of a new label" check box.

**Comment by kewtgh** [comment]
Thanks for replying. @LWinterberg @DavidBailes 


@LWinterberg 
I tested with Microsoft Pinyin. The problem still happened. 
When I inserted the label it stuck. When I use the keyboard shortcut "CTRL+B", it stuck, too.

I can't insert anything. After screenshot, Audacity would be OK.
I can only edit and paste Chinese words but can't input.

@DavidBailes 
I am using Microsoft Pinyin input method and disable Google Pinyin.

When I open Preferences, other options are OK.
But when I click any option of Tracks Behaviors，it stuck, too.
And after screenshot it would be OK.
![2](https://user-images.githubusercontent.com/55637096/132354653-ebdd9f79-9896-4432-97c8-ba09f2735e83.png)
![5](https://user-images.githubusercontent.com/55637096/132354663-c813a156-74f0-4346-b6b1-07310035bb86.png)
![6](https://user-images.githubusercontent.com/55637096/132354671-d70779fd-f7c1-4780-8c13-a827d7c7fcf0.png)

**Comment by LWinterberg** [comment]
I cannot reproduce getting stuck when switching input language, or when directly inputting the language. 

And as David pointed out, when using the text boxes to input (or the Edit > Labels > Edit Labels... box), I can input things:
![image](https://user-images.githubusercontent.com/87814144/132485638-fb1719d4-a5a3-48a3-987c-1cb71ed0c2d2.png)

**Comment by kewtgh** [comment]
@LWinterberg 

Thanks a lot for your help.

I solve the problem by @DavidBailes's method.

But the first step is changing the language of Audacity to simple Chinese. Then _in Preferences, on the Track behaviors page, check the "Use dialog for the name of a new label" check box._

When I insert Chinese words it worked and hasn't stuck again.

However, it stuck when I click any option of Tracks Behaviors in English language.

Thanks again for your help @LWinterberg.

**Comment by laymanal** [comment]
This problem can be solved by turning on the compatibility option of the input method.

**Comment by chazo1994** [comment]
> A work around would be to make use of the option to enter the name of the label in a dialog box. In Preferences, on the Track behaviors page, check the "Use dialog for the name of a new label" check box.
Thank you so much. It worked with vietnamese on macos.
