### ISSUE TITLE
start behind?

### ISSUE THREAD

**Issue by 2Andrew4** [audacity/audacity#1619]
The new downloadable image for linux tells after starting how in instruction given:

sh audacity-linux-3.0.4-x86_64.AppImage
audacity-linux-3.0.4-x86_64.AppImage: 1: audacity-linux-3.0.4-x86_64.AppImage: Syntax error: "(" unexpected

also with double-click is there nothing to get

**Comment by 2Andrew4** [comment]
i beg your pardon - image found at
https://www.audacityteam.org/download/

**Comment by LWinterberg** [comment]
did you mark the image as executable? `chmod +x`
