### ISSUE TITLE
Audacity writes double Year and Comment metadata (but only for other apps)

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1620]
**Describe the bug**
Audacity writes double Year and Comment metadata.  This does not show in Audacity - but does in other apps (MP3Tag and other player apps)

**To Reproduce**
1. purge Audacity settings folder (ensures cleared matadata)
2. launch Audacity
3. Edit>Metadata
4. Observe: empty metadata fields
5. record a short piece of audio
6. File>Export>Export as MP3
7. fill in the metadata fields (see example below)
8. press OK to make the export
9. exit Audacity
10. relaunch Audacity
11. Edit metadata
12. Observe: metadata fields are empty (expected behavior)
13. Import the MP3 fole from stes 6-8
14. Edit>Metadata
15. Observe: metadata is same as at Step 7 - correct single entries  (see image below)
16. File>Export>Export as MP3 (to a modified filename)
17. Observe: on Export the metatdata is the same as at steps 7 and 15
18. Launch Mp3tag
19. Examine the two MP3 files
20. Observe: both the year filed and the comment fieldd entries are doubled-up, separated with a double backslash, for both MP3 files (see image below)

**Expected behavior**
Metadata to be handled correctly and consistently.

**Screenshots**
Step 7 - metadata entered in Audacity
![image](https://user-images.githubusercontent.com/50205984/132121088-9df9e0fd-1a36-49eb-8ec1-712f8933d9bf.png)

Step 15 - metadata drom imported MP3
![image](https://user-images.githubusercontent.com/50205984/132121264-595e8581-bfec-40c7-b8f1-13ad2a2a34ad.png)

Step 20 - MP3tag shows double-year and double-comment
![image](https://user-images.githubusercontent.com/50205984/132121512-130bee44-6d01-408b-b8ef-8f09aa66f4e2.png)

**Additional information (please complete the following information):**
 - OS: Windows 10 - but assume all platforms
 - Version Audacity 3.0.4 and latest alpha 3.1.0

**Additional context**
a) This was originally logged on GitHub by user cubetroniv in December 2019:
 year tag gets doubled #401 

b) It was logged on Bugzilla (which had primacy for bug tracking at the time as P3 bug 2291
Bug 2291 - Metadata: Exported MP3 shows double year in MP3tag metadata
https://bugzilla.audacityteam.org/show_bug.cgi?id=2291

c) Both these logs were closed because at the time I could not reproduce this

d) The isue resurfaced on the Forum:
https://forum.audacityteam.org/viewtopic.php?f=47&t=116661#p434345

e) This led me to retest - and this time I could find a way to reproduce the users' complaints - so I logged this fresh bug to replace the prvious two logs

**Comment by petersampsonaudacity** [comment]
When I load the MP3 from Step 8 into iTunes:

a) I do not get a double enty for the "comment"

b) I get no entry for the Year filed

c) I get bo entry for the track number

![image](https://user-images.githubusercontent.com/50205984/132121867-fb9a6e94-3c1f-4f4a-a5c7-3ce154bea82d.png)

**Comment by petersampsonaudacity** [comment]
The original GitHub post reported

>Foobar2000 renders the new date as 1998, 1998 in the player but 1998; 1998 in the Properties Editor. This may be similar to how Audacity is only showing one year when the actual tag data is 1998; 1998.
Vanilla Music fails to understand the date 1998; 1998, so when sorting music by date, it is not sorted properly. I think it treats it as an invalid date.

See:  year tag gets doubled #401

**Comment by JohnColket** [comment]
See also related Audacity Issue #1696

**Comment by LWinterberg** [comment]
Improving metadata handling is not planned for the moment, closing for now. There may be a bigger metadata release eventually, follow #1464 for that.
