### ISSUE TITLE
Playback lopping

### ISSUE THREAD

**Issue by gera-gas** [audacity/audacity#1641]
Design of this feature [here](https://www.figma.com/file/odPgVM0lWc6MdsJWxpgPJl/Audacity?node-id=1657%3A2905)

Some clarifications after the design review:
 * the "quick play" functionality will be replaced on "playback looping".
 * possible simplifications (like in current "quick play" mode) for looping during playback.

**Implementation stages:**
 1. Create and add icon resources.
    1.1. [Methodics](https://wiki.audacityteam.org/wiki/Theming_HowTo)
    1.2. Estimation: 4,6 hrs

 2. Add playback looping button.
     2.1. Methodics: in `ControlToolBar.cpp` file need add looping button by `ControlToolBar::MakeButton` and use `mPause` button like as example for handlers implementation.
    2.2. Estimation: 3,5 hrs

3. Add looping range GUI for Timeline bar.
   3.1. Methodics: Use `QuickPlayIndicatorOverlay` and `QuickPlayRulerOverlay` in `AdornedRulerPanel.cpp` like an example.
   3.2. Estimation: 14,18 hrs

4. Add mouse event handler for looping range GUI.
   4.1. Methodics: Using "quick play" events handlers (`AdornedRulerPanel::QPHandle::Click (const TrackPanelMouseEvent &event, AudacityProject *pProject)`, etc) with looping by Shift key for add playback looping support.
   4.2. Estimation: 12,15 hrs

5. Remove "quick play" preferences like a checkboxes.
    5.1. Note: do it after full "playback looping" support and tests.
    5.2 Estimation: 1.2 hrs

__Final estimation__: 34, 46 hrs

**Comment by AnitaBats** [comment]
closed as a duplicate
