### ISSUE TITLE
Nyquist: Intermittent failure of PHASEVOCODER

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#1642]
**Describe the bug**
When running the Nyquist PHASEVOVODER function, the returned audio will sometimes be corrupt.
The corruption is evident from either a huge peak in the waveform at the beginning of the processed audio, or the presence of NaNs in the processed audio.

**To Reproduce**

Short Test, but failure is rare:
1. Apply this code via the Nyquist Prompt effect:
```
(let* ((dur (get-duration 1))
       (map (abs-env (pwlv 0 (* 2.0 dur) dur))))
  (phasevocoder *track* map))
```

Long Test, which usually fails:
1. Install this Macro:
[vocoder-test.txt](https://github.com/audacity/audacity/files/7129205/vocoder-test.txt)
2. Generate 1 second of silence
3. Duplicate the track 4 times so that there are 16 tracks total
4. Collapse all tracks so that they can be seen in the Audacity window
5. Select All
6. Apply the Macro

**Expected behavior**

Short Test: 2 seconds of silence.

Long Test: 16 tracks, each containing 1 second of silence.

**Screenshots**
Actual result from Long Test:
![Screenshot_2021-09-08_14-29-05](https://user-images.githubusercontent.com/11681097/132520528-57a2f32b-491f-46f0-8570-5224d3eff6a1.png)

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version: Audacity 3.1.0-alpha-20210908 Commit Id: 1c2a91

**Additional context**

**Comment by SteveDaulton** [comment]
Additional screenshot from another run of "Long Test":
![Fullscreen000](https://user-images.githubusercontent.com/11681097/132535123-34398292-695f-4f61-b7f8-99cde5c1cc3f.png)

**Comment by Paul-Licameli** [comment]
Are you going to debug this yourself, @SteveDaulton ?

**Comment by Paul-Licameli** [comment]
Is this vocoder.ny or some other effect that is not shipped?

**Comment by SteveDaulton** [comment]
> Are you going to debug this yourself, @SteveDaulton ?

It's a tough  one, especially as I don't speak C.
I've discussed it with rdb and he's looking into it, but it has proved elusive so far. The steps described here have enabled rdb to reproduce the issue (he had not been able to reproduce it in standalone Nyquist).

It's this phasevocoder: https://www.cs.cmu.edu/~rbd/doc/nyquist/part8.html#index551

To date, I'm only aware of one Nyquist plug-in in the wild that uses phasevocoder, but it is such a cool function that I'd expect it to become popular with Nyquist plug-in authors. While most users are unlikely to encounter this bug now, it may well become more common, and when it does go wrong, it goes very badly wrong. Potentially it could destroy a user's project.

**Comment by rbdannenberg** [comment]
Yes, I got it to fail on Win10Pro, and would like to track it down. Unfortunately, my previous installation stopped working, so I'm back at the stage of trying to compile Audacity -- this always takes a few days.

**Comment by rbdannenberg** [comment]
I think I've fixed both the NaN problem and the corruption problem Steve's test reveals where initial samples of phase-vocoded silence is not silent. I'll communicate directly with Steve and Paul about getting this into Audacity. Nyquist sources are updated.
