### ISSUE TITLE
Clip names should be editable by macro programming

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#1644]
Making this new user-modifiable attribute of a project changeable with macros is needed to complete the clip naming project, consistently with other such things in Audacity such as changes of track name.

The existing SetClipCommand class could be adapted to have one more parameter for this purpose.

See #1258

The command is also accessible in menus under Extra > Scriptables I

@LWinterberg See this manual page needing update https://manual.audacityteam.org/man/extra_menu_scriptables_i.html#set_clip

**Comment by LWinterberg** [comment]
- [x] Updated image
- [x] Updated relevant section in the manual
