### ISSUE TITLE
Release source tarball reports as alpha version after compiling

### ISSUE THREAD

**Issue by beew** [audacity/audacity#1645]
I downloaded and compiled the audacity 3.0.4 release tarball from https://www.audacityteam.org/download/source/

When it starts I am greeted with the welcome popup that screams "get the official release version of audacity" and that this is an Alpha Test Version in bold. So where do I get the source for the release version?

**Comment by LWinterberg** [comment]
Did you build Audacity as a debug version or a release version?

**Comment by beew** [comment]
I don't remember, it should be release.
