### ISSUE TITLE
Fix default font size in clip names

### ISSUE THREAD

**Issue by vsverchinsky** [audacity/audacity#1649]
![image](https://user-images.githubusercontent.com/20165230/132686274-30a5dc06-d011-4aa7-9f27-a02a7208cb31.png)

https://github.com/audacity/audacity/discussions/1535#discussioncomment-1301097

**Comment by LWinterberg** [comment]
I think these are xfce specific settings (cc @SteveDaulton )

**Comment by SteveDaulton** [comment]
Xfce default settings:

![Xfce-track](https://user-images.githubusercontent.com/11681097/144241190-e2f21a08-08e2-4831-bac1-f8dc2c226714.png)


Gnome default settings:

![Gnome-track](https://user-images.githubusercontent.com/11681097/144241226-25202c91-ed1f-41e0-9b66-33c72172b305.png)


Xfce 140% font size:

![Xfce-track2](https://user-images.githubusercontent.com/11681097/144241315-6f8a6715-3240-4904-84c5-c76727048bf0.png)


On hidpi displays it is usually necessary to scale the font size. I think this is part of a more general hidpi support issue for Audacity.

**Comment by LWinterberg** [comment]
I agree with Steve, this is not a bug on its own but a consequence of #503
