### ISSUE TITLE
The Journaling fails on recording playback button

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#1657]
**Describe the bug**
When the user presses the playback button, the Journaling raises an error message

**To Reproduce**
Steps to reproduce the behaviour:

1. Import the track
2. Click the Playback button

**Expected behaviour**
The Journaling works fine
 OR it does not record interaction with the playback button and does not raise any error messages.

**Screenshots**
![изображение](https://user-images.githubusercontent.com/25851359/132849813-1a85a3d7-2a40-4300-9b41-3dad22a82fb0.png)

**Additional information (please complete the following information):**
Audacity 3.1.0-alpha-20210910

**Comment by Paul-Licameli** [comment]
This duplicates other issues I already opened.

**Comment by Penikov** [comment]
Duplicated
