### ISSUE TITLE
In MIDI Devices preferences, "Host:" has no effect

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#1661]
The key `/MidiIO/Host` is updated in the preferences file (audacity.cfg), but that preference path is used nowhere else.

A search of source code history shows that this has been so at least since 2010.

This manual page shows the control, but has no description of what it does.  https://manual.audacityteam.org/man/midi_devices_preferences.html

Either we remove it or perhaps @rbdannenberg can explain what the intention was for this incomplete feature.

**Comment by SteveDaulton** [comment]
I'm not sure about Windows or macOS, but on Linux at least there can be more than one host available. Options that I'm aware of are ALSA, OSS, Jack and RTP.
For best performance, Jack MIDI is often recommended, though Audacity appears to currently only supports ALSA MIDI.
