### ISSUE TITLE
Label tracks and Note tracks do not have right-click context menus - inconsistent with audio tracks

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1662]
**Describe the bug**
Now that @Paul-Licameli has introduced right-click context menus for audio tracks - an inconsistency shows whereby Label tracks and Note tracks do not have right-click context menus.

**To Reproduce**
1. Right-click in a Label track or a Note track
2. Observe: no context menu is shown

**Expected behavior**
Right-click context menus for Label tracks and Note tracks.

Both have edit functionality available and thus it would make sense, and provide consistency, if they had context menus available. Because of the lack of consistency I have logged this as a bug rather than an enhancement.

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS: Windows 10 - but assume all OS
 - Version: Audacity 3.1.0

**Additional context**
Giving users context menus with audio tracks could well expect to see the sane for Label tracks and Note tracks

@Tantacrul and @jounih  what is your UX take on this please?

**Comment by LWinterberg** [comment]
Interestingly, right-clicking on a label text does produce a context menu

**Comment by petersampsonaudacity** [comment]
> Interestingly, right-clicking on a label text does produce a context menu
Interestingly Leland did that overnight at the AU14 un-conference  in Preston back is October 2014 after a short discussion with Steve and myself about deleting labels - _that's rapid development for you ..._

**Comment by jounih** [comment]
Yes, why not, it makes sense for consistency.

For note tracks we were thinking of doing this after the midi editing is
more developed, but at a clip level we could do this already I suppose,
though I don’t think many people use midi with Audacity in its current
state.

For label tracks it would be nice definitely, will add to the spec!

**Comment by petersampsonaudacity** [comment]
@jounih - yes I agree that the Note tracks are less important and can wait - It will be good to see them for label tracks

**Comment by Penikov** [comment]
This is Ok on this iteration. Question about right-clicking context menus is aroused.  Another question is what options for label context menus should be. 

This is obviously not a bug and works as designed (at present). So I'll turn this bug into a feature request.

**Comment by Penikov** [comment]
This is Ok on this iteration. Question about right-clicking context menus is aroused.  Another question is what options for label context menus should be. 

This is obviously not a bug and works as designed (at present). So I'll turn this bug into a feature request.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest alpha audacity-win-3.1.0-alpha-20210916+cb1931f-64bit

Is there any good reason why the empty gray-space in a track right-click context menu has fewer menu items  then when right-clicking in the audio clips?  

Since the context menus work on Audacity cursor position or selection and not the position of the mouse cursor it surely makes sense that both context menus have the same set of commands.

**Comment by jounih** [comment]
You can't copy empty space, but can copy a clip - though this should be
related to clip / audio selection state rather than where you click on, as
you said. Will chat through with Paul today
