### ISSUE TITLE
Left Sample Point Obliterated by Clip Line

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#1663]
**Describe the bug**
The line marking the left clip boundary is drawn right on top of the left-most sample data point, making it virtually impossible to read.

**To Reproduce**
1) Generate Tone: Sine, 1000Hz, .9, .001 seconds
2) Select waveform from .0001 to .0004
3) Edit > Clip Boundaries > Split
4) Notice that Clip lines are drawn on top of sample points.
5) Also note that zooming does not change visibility.

**Expected behavior**
There seems to be plenty of space for the clip line.  If it could be moved a couple of pixels to the left the data point could be made visible.  Alternatively, perhaps the data point could be made larger, possibly when zooming.

**Screenshots**
![First Track006](https://user-images.githubusercontent.com/76828213/132948451-2a550dc5-9ff8-43a2-b39a-59899d64c9b1.png)

**Additional information (please complete the following information):**
 - OS: Windows
 - Version current Audacity Alpha (Audacity_Windows_64bit_1216946555_6013304)
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]

**Comment by petersampsonaudacity** [comment]
See also:  Clip visuals become unpredictable on sample-level zooms #1689

**Comment by petersampsonaudacity** [comment]
This has been the case certainly since 2.2.0 when stem plots for samples were introduced.

It may well have been the case in earlier version, just harder to see

**Comment by LWinterberg** [comment]
this gets fixed with #2330
