### ISSUE TITLE
Recording loopback in mono with certain Realtek cards causes hard-to-understand "-9996 Invalid Device Error!"

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#1682]
**Describe the bug**
Audacity generates "Error opening recording device. Error code: -9996 Invalid device." and offers to send a crash report to Audacity simply because MONO was selected instead of STEREO.  Certainly this behavior and lack of a useful error message for such a common situation is inappropriate.

**To Reproduce**
1. Windows WASAPI
2. Input device: Speaker/Headphone (loopback)
3. STEREO
4. Record from Youtube: OK.
5. Change STEREO to MONO.
6. Repeat record from Youtube: Error -9996 Invalid Device Error!

**Expected behavior**
A mono recording, or advise that source is in STEREO.

**Screenshots**
![Full Window004](https://user-images.githubusercontent.com/76828213/133444722-81ad5655-facc-45b7-b3bf-ddea894bd2a9.png)

![Window Plus-Error-000](https://user-images.githubusercontent.com/76828213/133444340-e5cf1d2f-edaf-4e20-bb36-490bdde6f882.png)

**Additional information (please complete the following information):**
 - OS: Windows 10 Home 21H1 19043.1237 Windows Feature Experience Pack 120.2212.3530.0
 - Version: Audacity 3.0.4 AND current Alpha Audacity 3.1.0-alpha-20210915 (0cbb89 of Tue Sep 14 23:09:01 2021 -0400)
 -Windows WASAPI, Internal Realtek High Definition Audio

**Additional context**

**Comment by LWinterberg** [comment]
I can reproduce this on my machine (Gigabyte Aero 15x v8), but only with the Realtek loopback set to mono. All my other loopbacks (a Scarlett Solo, a monitor, and a virtual Nvidia broadcast unit) work just fine, as does the Realtek mic in mono. 

As a note on the STR steps 3+4 may be skipped, it breaks just as well if you don't record in stereo before.

**Comment by LWinterberg** [comment]
actually, @JohnColket, is this a bug report (that particular device is playing foul and you don't want the error to occur), or an enhancement request (you recognize that the device being silly may not be something we can fix, but we should make the error message more useful)?

**Comment by JohnColket** [comment]
@LWinterberg: Thanks, Leo.  I am reporting this error, because what Audacity sees as an "Invalid Device Error" is, from the perspective of most of Audacity's users, an Audacity software bug.

This may be a simple design limitation within Port Audio, but from the user's perspective it is not only scary but appears to be a major structural flaw within the Audacity software.

I am glad that you were able to reproduce this issue that, I suspect, a great many Audacity users have seen as well - and they just keep pressing buttons until it goes away (or they give up).

**Comment by LWinterberg** [comment]
I'll have someone look through the sentry data to see how common this is

**Comment by petersampsonaudacity** [comment]
I cannot reproduce this on with W10 HP Envy laptop, with 3.1.0 alpha , with card Realtek High Definition Audio(SST)

**Comment by LWinterberg** [comment]
I added a link to https://support.audacityteam.org/troubleshooting/error-codes in the error dialog, so now users have some indication on how to solve this issue. Outside of wrangling the driver to work with mono loopback recordings, this is probably all we can do, so I consider this issue done.
