### ISSUE TITLE
Compressor fails on multiple tracks

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#1687]
**Describe the bug**
The compressor effect may produce the wrong output when multiple tracks are selected.

**To Reproduce**
1. Generate a "Chirp" (default  settings)
2. Duplicate the track twice
3. Adjust the position of the clips as shown below
![Tracks001](https://user-images.githubusercontent.com/11681097/133925272-52ea5798-7e4d-4bdc-afa1-4058bf9f9586.png)
4. Select All
5. Apply the Compressor effect with default settings

**Expected behavior**

![Tracks002](https://user-images.githubusercontent.com/11681097/133925309-230adce6-d485-420d-b2fc-ff7a68225c32.png)

**Actual behavior**

![Tracks003](https://user-images.githubusercontent.com/11681097/133925324-967102a4-28b6-472b-bd4c-ee5a97324d8d.png)

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04 (Issue reported on Windows 10)
 - Version: 3.1.0-alpha-20210913 (original report was *probably* 3.0.4)

**Additional context**
https://forum.audacityteam.org/viewtopic.php?f=46&t=120415

**Comment by SteveDaulton** [comment]
See also: https://github.com/audacity/audacity/issues/1512

**Comment by jpuddy** [comment]
Confirming this issue is present on 3.2.1 on Mac OS Monterey. All you need is 2 tracks, aligned end to end. Select All and run the compressor, the 2nd track will lose some audio from the beginning.

**Comment by hasheddan** [comment]
Observed this behavior on Ubuntu 22.04 as well -- not an ideal solution, but the following worked for me:
1. Align all clips to 0.
2. Select all and run `Compressor`.
3. Move clips back to desired positions.

**Comment by LWinterberg** [comment]
I can no longer reproduce this in Audacity 3.5 alpha. It likely was fixed in  https://github.com/audacity/audacity/pull/5703
