### ISSUE TITLE
Clip visuals become unpredictable on sample-level zooms

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#1689]
**Describe the bug**
Instead of looking like clips, the clips seemingly extend over empty space, terminate twice, and more. Hovering over the actual clip won't highlight the actual clip but the wrong side of it. 

**To Reproduce**
1. Have a clip
2. Zoom way in (to the sample level and then 1-4 steps further still

**Expected behavior**
They remain looking like clips

**Screenshots**
![image](https://user-images.githubusercontent.com/87814144/133983919-134552b1-eb3d-4d85-b028-c19b881f491c.png)
![image](https://user-images.githubusercontent.com/87814144/133983988-ea7c9325-2d01-4888-a8df-d858688131e1.png)
![image](https://user-images.githubusercontent.com/87814144/133984109-52137933-f751-4945-ac5d-045e7fa2f749.png)
![image](https://user-images.githubusercontent.com/87814144/133984288-d014341d-6baf-4a88-8948-b02deeda9b0b.png)

**Additional information (please complete the following information):**
 - OS: Windows 11
 - Version Audacity 3.1.0-alpha-20210916

**Comment by LWinterberg** [comment]
![image](https://user-images.githubusercontent.com/87814144/133985328-b1ebf3fb-e2da-469c-808a-d239d2f4801c.png)
for completeness: It also happens at the end of the clips. Some levels are fine, some are wrong-way-round

**Comment by Penikov** [comment]
@LWinterberg Looks like this is a win11-specific bug. I've tried to reproduce this on Win10 and haven't got the same glitch:

![изображение](https://user-images.githubusercontent.com/25851359/133986003-265e2eb9-4394-4f8b-bb95-0cbded722812.png)

**Comment by Penikov** [comment]
@LWinterberg Looks like this is a win11-specific bug. I've tried to reproduce this on Win10 and haven't got the same glitch:

**Comment by vsverchinsky** [comment]
> @LWinterberg Looks like this is a win11-specific bug. I've tried to reproduce this on Win10 and haven't got the same glitch:
> 
> ![изображение](https://user-images.githubusercontent.com/25851359/133986003-265e2eb9-4394-4f8b-bb95-0cbded722812.png)

I was able to reproduce it on win10, seems like drawing needs some workaround, quite simple though

**Comment by Penikov** [comment]
@vsverchinsky Yes, you right )
But I meant this one )
![изображение](https://user-images.githubusercontent.com/25851359/133987124-6918c69e-e43d-4f4e-8eab-2908f250be20.png)

**Comment by Penikov** [comment]
@vsverchinsky BTW, I finally got what you mean )
![изображение](https://user-images.githubusercontent.com/25851359/133987305-b573899a-b289-436c-921e-2d541e5d73b8.png)

**Comment by petersampsonaudacity** [comment]
See also@   Left Sample Point Obliterated by Clip Line #1663

**Comment by LWinterberg** [comment]
This seems to only occur for clips longer than 25-ish seconds

**Comment by AnitaBats** [comment]
@vsverchinsky please check if you can reproduce with your latest build

**Comment by petersampsonaudacity** [comment]
Testing with @vsverchinsky 's latest build:  audacity-win-3.1.0-alpha-20210923+da495d3-64bit
This looks much better to me:

![image](https://user-images.githubusercontent.com/50205984/134533150-be8a0454-ac5b-4022-8afc-02b78dbad84e.png)

**Comment by petersampsonaudacity** [comment]
But observe this little minor audio glitch - repeatable with different zoomed clips - 
a) always in the right clip and 
b) always adjacent the the last dot in the left clip

![image](https://user-images.githubusercontent.com/50205984/134534757-d747f33c-60b4-4eee-a5c5-b9b0ca0e9e43.png)

**Comment by DavidBailes** [comment]
Just to point out that the start and end of a clip indicated by the new clip visuals are not consistent with existing visuals for the start and end of the clip. I think the existing visuals are OK and consistent.
Here's a 10 sample clip of noise, which has been selected - note the start and end indicated in the timeline:
![image](https://user-images.githubusercontent.com/11887021/134639801-35a62dfc-74b4-4c51-b7cc-85b11740edf9.png)

After pressing J to move to the start of the clip:
![image](https://user-images.githubusercontent.com/11887021/134639910-91b79011-87d2-42f6-b5b4-475e9862ad94.png)

After pressing K to move to the end of the clip:
![image](https://user-images.githubusercontent.com/11887021/134639982-b9a2a40e-252a-413b-b01a-688160c6a8a1.png)

**Comment by Penikov** [comment]
> 
> 
> But observe this little minor audio glitch - repeatable with different zoomed clips - a) always in the right clip and b) always adjacent the the last dot in the left clip
> 
> ![image](https://user-images.githubusercontent.com/50205984/134534757-d747f33c-60b4-4eee-a5c5-b9b0ca0e9e43.png)

I think it is relative to this topic, but it would be better to separate these issues.

**Comment by petersampsonaudacity** [comment]
> I think it is relative to this topic, but it would be better to separate these issues.

@Penikov  - so do you want me (as the finder) to log this - or do you want to do it?

**Comment by LWinterberg** [comment]
that already is logged as #1663

**Comment by petersampsonaudacity** [comment]
> that already is logged as #1663, or am I missing something?

Yes - but before I looked closely I opened another issue for it - and then rapidly closed it - issue #1789  _<blushes deeply>_
