### ISSUE TITLE
When splitting a clip using a range selection, the clip names should be 1, 2, 3 instead of 1, 2 1, 2 2

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#1692]
STR:

1. Select a range 
2. Split clip (Ctrl+I)

Current behavior: 

![image](https://user-images.githubusercontent.com/87814144/134005545-cd911fb0-def5-47c4-8f12-991b98acae7d.png)

Wanted behavior:

![image](https://user-images.githubusercontent.com/87814144/134005621-7047b837-5417-454f-a2cc-2ea18c719392.png)

That would make at least this part of the automated numbering way less confusing.

**Comment by crsib** [comment]
How should be the case, when you split the first clip 2 times work? I. e. how should be the middle clip named?

**Comment by LWinterberg** [comment]
In a perfect world, if you start out with one source file and split it up into smaller and smaller pieces, the numbering should remain in order. Maybe once you start moving clips to new places where they aren't connected to the main thing anymore they should get their own subdivisions (that is to say, clip 3 1, clip 3 2 and so on), but the details are probably for @jounih and @Tantacrul to figure out. 

Practically, I think that we can keep the current behavior for point-selection splits for now, because while it's not terribly useful, I can at least figure out as a user why splitting a clip named clip 1 would now name it clip 1 1 and clip 1 2. Whereas with range selection, it's completely confusing why a selection I made in clip 1 and turned into a clip itself now is called clip 1 2 1.

**Comment by petersampsonaudacity** [comment]
Also note that when you Split New to move the clip to a new track you get a label that includes it's time range which is a little odd:
![image](https://user-images.githubusercontent.com/50205984/134024917-202233e3-3313-406d-ab14-09efbc35ea0b.png)

**Comment by petersampsonaudacity** [comment]
And if you Split New a few more times you get this odd concoction for a clip label
![image](https://user-images.githubusercontent.com/50205984/134026050-16b39124-6bad-49bf-8094-855d17cfda71.png)

**Comment by DavidBailes** [comment]
I think that a reasonable case can be made for not adding any numbers when a clip is split - the split clips just have the same name as the original clip:
1. After a user has split a clip, if necessary they can rename any of the clips with names which are meaningful to the user.
2. After the smart clip feature is introduced, the split clips are all views of the same audio. If the user goes on to adjust the start and ends of the views, then the automatic numbering may quickly become meaningless.
3. Why make the user interface look more complicated than it needs to be.

**Comment by SteveDaulton** [comment]
I agree with David that automatic numbering of clips has very limited usefulness and significant negatives.

There's also a related frequently requested feature to add a time stamp when using Sound Activated Recording (SAR). One possible implementation could be to create a new clip each time SAR starts, and name the clip with a time stamp.

**Comment by petersampsonaudacity** [comment]
@Tantacrul  @jounih - This is **_more_** than a mere Enhancement request - this is a matter of getting it right in 3.1.0 for the users.  The numbering system now is both irrational and illogical for both split clips on the same track and for Split New clips on a New track.  This is a serious UX issue.

If it is not sorted expect to get a lot of queries and complaints on the Forum (and on GitHub)

**Comment by LWinterberg** [comment]
We'll be removing the numbering for clip splitting, but keep numbering for new recordings and copypasting. Details are found in #1698, I'll be closing this issue in favor of it
