### ISSUE TITLE
Audacity changes audio server playback frequency at launch if using an audio interface.

### ISSUE THREAD

**Issue by AesaraB** [audacity/audacity#1694]
**Describe the bug**
During startup, Audacity does _something_ to the audio server that changes the playback frequency for all applications. This may be more appropriately directed to the Pipewire issues tracker, but so far Audacity is the only application I've used that messes with the playback in such a way, so it may be useful to know why this occurs.

**To Reproduce**
This issue seems to be hardware specific (see below), when Audacity is launched on a client running the Pipewire server, the audio playback hangs for a moment (similar behaviour occurs when creating/opening a project in Ardour), and afterwards the audio playback frequency is lowered.

**Expected behavior**
Audio playback frequency should not be affected.

**Additional information (please complete the following information):**
 - OS: Fedora 34 Workstation
 - Version: Audacity 3.0.2-3 from the Fedora updates repo.
 - Audio Server: Pipewire 0.3.36-2 from the Fedora updates repo.
 - Audio Interface: Steinberg UR242

**Additional context**
 - The issue persists after Audacity is closed.
 - Switching the playback device from the audio interface's digital output to its analogue output or visa versa reverses this change. 
 - If I launch the Ardour DAW the playback frequently returns to normal.
 - This issue has been reproduced on different computers using the same audio interface, it does not occur on the onboard audio playback devices.
 - Thus far I've only tested this on the PipeWire audio server, and on this specific audio interface.

**Comment by LWinterberg** [comment]
I could reproduce something similar on my scarlett solo on Ubuntu 21.04 , where opening Audacity would turn my audio all crackly for myself. However, MelonDS would do the same thing, as would a handful of other programs which currently elude me, so I'm not sure this really is an Audacity thing, but something about a common library.

**Comment by LWinterberg** [comment]
This is a [known issue](https://github.com/audacity/audacity/wiki/Known-Issues).

**Comment by SimonPilkington** [comment]
@LWinterberg I am also experiencing issues with Audacity and Pipewire and the wiki page you linked is dead. Can you please add a new reference to the known issue?
