### ISSUE TITLE
Linux: Clicking on track slider fails to display value

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#1709]
**Describe the bug**
Clicking on the track's Pan or Gain slider should display the current setting of that slider.  On Xubuntu it just displays a thin horizontal line.

**To Reproduce**
1. Click on a track's Gain or Pan slider
2. Observe that the slider value is not visibly displayed.

**Expected behavior**
The track slider value to be displayed

**Screenshots**

![track-slider](https://user-images.githubusercontent.com/11681097/134403954-7dc01020-33c5-491f-9d31-4ed6abaffb6c.png)

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version: 3.0.4

**Additional context**

**Comment by harsha20032020** [comment]
Hello @SteveDaulton 
Can you maybe elaborate more on that issue?
Because the slider value is being displayed in the application.
![Screenshot 2021-09-28 15:49:16](https://user-images.githubusercontent.com/71493353/135069490-89b12d1f-f9a5-4a06-a9b6-6d193b080a28.png)
I'm working on an Ubuntu 21.04 but with the latest Audacity Version 3.1.0 Alpha.

**Comment by SteveDaulton** [comment]
> Can you maybe elaborate more on that issue?

See where your image displays "Pan: 40% Right"
See where my image displays "_____________"

**Comment by harsha20032020** [comment]
So you want the Pan value to be displayed even when the slider is not being touched or moved?

**Comment by SteveDaulton** [comment]
Same happens with the Play At Speed slider.
![playatspeed](https://user-images.githubusercontent.com/11681097/143104106-7c64297d-a05e-4882-a4ba-114afd7ab8b5.png)

**Comment by SteveDaulton** [comment]
Also occurs on the Mixer Toolbar (Reported on the Audacity forum today with Audacity 3.1.3)
![slider](https://user-images.githubusercontent.com/11681097/166149352-4b7210fa-8927-4b9a-adc4-e6eec7557b01.png)

**Comment by LWinterberg** [comment]
@SteveDaulton please retest with the gtk-fix, the tooltips show up for me both in 100% and 200% scaling and they're back to being yellow

**Comment by SteveDaulton** [comment]
I'm seeing proper tooltips on hover, but still only see a horizontal line on those that appear on click (for example, click on a slider in the Mixer Board, or click on a track's "Gain" slider).

Tested on self-built 3.2.0-alpha, Xubuntu 20.04.
