### ISSUE TITLE
Effects may be applied to "wrong" audio

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#1721]
**Describe the bug**
Effects may be applied to audio that is not selected rather than to audio that is selected.

**To Reproduce**
1) Make a selection
2) Open any built-in effect
3) Preview the effect
4) Change the selection
5) Apply the effect.
6) Observe: The effect is applied to the original selection, not the current selection.

**Expected behavior**
Either:
1. Non-real-time effect windows are fully modal (so that the selection cannot be changed while the effect window is open)
2. The effect to be applied to the audio that is actually selected.

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version: Audacity 3.1.0 alpha

**Additional context**
Transferred from: https://bugzilla.audacityteam.org/show_bug.cgi?id=1063

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest 3.1.0 main alpha:  audacity-win-3.1.0-alpha-20210923+1cf0c3f-64bit

This does **_not_** happen on Windows - at Step 5 the effect is applied to the new selection made at step 4

**Comment by SteveDaulton** [comment]
Testing with Audacity 3.0.3 on macOS, the behaviour is different again.
At step 4 it is not possible to change the selection.

**Comment by LWinterberg** [comment]
seems like the windows are fully modal now
