### ISSUE TITLE
Native AUP3/AUP project files should be listed independently of imported audio files in Recent Files list

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1727]
**Describe the bug**
In addition to native file formats (i.e. project files) being listed in Recent Files, Audacity also adds entries for any imported audio files.

The big downside of that is that if you import a lot of audio files into a project than your project itself can be pushed off the Recent Files list.

This is a regression against 1.3.6 which only stored the recent projects in the recent files list.  By 1.3.10 the audio files were also being added (I don't have the intervening versions for more accurate regression testing)

Originally logged on Bugzilla as Big 2735
https://bugzilla.audacityteam.org/show_bug.cgi?id=2735
Originallly reported on Audacity 3.0.0, testing on latest alpha 3.1.0 shows that this issue remains 

**To Reproduce**
1) Clear the recent files list
2) record some audio
3) Save the project
4) Import a few audio files
5) File > Recent Files
6) Observe: in addition to the project from step 3 the audio files from step 4 are listed

**Expected behavior**
Projects and audio files to be listed separately in the recent files list _(see "Additional context" below)_

**Screenshots**

![изображение](https://user-images.githubusercontent.com/25851359/135847697-f435fb60-e61b-4fb8-9d39-c55d652670b9.png)

![изображение](https://user-images.githubusercontent.com/25851359/135847732-2d7346f0-5199-48ed-a2e5-c984379fa32c.png)

**Additional information (please complete the following information):**
 - OS: all OS
 - Version Audacity 3.x

**Additional context**
It was suggested on the quality email list that first aired this:
>It might be a useful enhancement if the list was split into "projects" 
>above a divider and "audio/MIDI/LOF files" below the divider.

Perhaps as many as ten of each - or maybe seven would be better
(If we were being super thorough we might even create a couple of new prefs settings for the counts - with zero being allowable for the recent imported audio files)

**Comment by LWinterberg** [comment]
I don't think this needs to be fixed. That said, the Qt version is going to have a home screen which probably will solve this problem somewhat better than this.
