### ISSUE TITLE
Changed temporary directory location should be implemented immediately - not after restart

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1728]
**Describe the bug**
If a user changes temporary directory location in Directories preferences then they have to close Audacity and restart it for this change to take effect,

The user should not need to close their project(s) in order to force the change, for a start this is inconsistent with the way we handle other preference settings.

I do realize that this means that we would have to move the temp files (if any) to a the new directory location, but surely that is a price worth paying.

It's particularly tiresome if it's the first thing you do on launching Audacity as at that stage (provided there are no recovery files) there will be nothing in the Session Data directory.

Initially logged on Bugzilla as Bug 2548
https://bugzilla.audacityteam.org/show_bug.cgi?id=2548

**To Reproduce**
1) Directories Preferences
2) change the location of the temporary directory
3) Observe: a warning that you must close and restart Audacity for this to take effect

**Expected behavior**

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS:  all OS
 - Version: Audacity 3.1.0 _(originally reported against 3.0.0)_

**Additional context**
Careful consideration needs to be given to the Multi-Project-Wormcan use case when there are multiple unsaved projects open.

**Comment by LWinterberg** [comment]
We have no plans of adding this
