### ISSUE TITLE
Clips with small numbers of sample are invisible at normal zoom levels

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1729]
**Describe the bug**
Clips with small numbers of sample are invisible at normal zoom levels - and even a 1,000 sample clip on;y shows as a black line at normal zoom

Originally logged on Bugzilla as 2125
https://bugzilla.audacityteam.org/show_bug.cgi?id=2125
Enh: Small clips become invisible when zoomed out

**To Reproduce**
1) Generate > Tone
2) set duration to 100 samples
3) Zoom out 3 times
4) drag the clip to the right of the Window (to get it away from T-0)
5) Ctrl+2 for normal zoom level
6) Observe: the track appears to be empty
7) Zoom in 3 times (YMMV)
8) Observe: a black line appears in the track - this is the short clip
9) Zoom in 3 more times
10) Observe the clip looks like an audio clip

**Expected behavior**
The user needs some visual cue that such a clip is present in a track

**Screenshots**
![image](https://user-images.githubusercontent.com/50205984/134681225-a203a519-6f16-4b37-97a5-3e685c289314.png)

**Additional information (please complete the following information):**
 - OS: all OS
 - Version: Audacity 3.1.0

**Additional context**
With 1,000 samples at normal zoom level you only see a black line (see image above)

With 2,000 samples you can barely see that it is an audio clip at normal zoom levels

**Comment by LWinterberg** [comment]
The clips are not invisible; they remain visible as a black line. In the far future, should per-clip coloring become a thing, the black line may be replaced by a red/blue/green/... line at smaller widths

Additionally, the current confusion with the point selection (a black line) and a small clip (also a black line) will get resolved in the future as well by turning the point selection into more of a playhead looking thing. 

But all of that is separate to this issue.
