### ISSUE TITLE
Audacity needs an easier way to avoid clipping on multiple tracks

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1732]
**Is your feature request related to a problem? Please describe.**
If you Export or Mix with a lot of loud tracks than clipping is likely to occur.  This topic surfaces regularly on the Forum as user complaints.

Wiki Feature Requests has "One-step way to avoid clipping on multiple tracks (30 votes). 
https://wiki.audacityteam.org/wiki/Feature_Requests#noclipping
There was earlier agreement we must make it easier for users to control the overall level of their mix, but different solutions. Some of these solutions are quite simple or automatic (and would fix this enhancement issue if implemented). Other solutions add more functionality and complexity. 

**Describe the solution you'd like**
An automated way of ensuring that when exporting a project with multiple tracks (or mixing multiple tracks_ that the resultant exported audio (or mix) will not be clipped.

**Describe alternatives you've considered**
Otherwise this has to be done manually by trial and error.

**Additional context**
There is a Proposal page for hammering out ideas at 
http://wiki.audacityteam.org/wiki/Proposal_Easy_Avoid_Clipping_on_many_tracks . 

Originally logged on Bugzilla back in 2012 as ENH 565
https://bugzilla.audacityteam.org/show_bug.cgi?id=565

**Comment by petersampsonaudacity** [comment]
@SteveDaulton  wrote in the Bugzilla thread in 2019:

I think this "Enh" is too broad. There are multiple different issues related to this.

A) The "problem" as described in the proposal http://wiki.audacityteam.org/wiki/Proposal_Easy_Avoid_Clipping_on_many_tracks is very easy to "solve". We just tell the user to "Mix and Render" and then "Normalize" before exporting.
We could even provide a Macro or Nyquist Macro to "Mix and Render" then "Normalize"in one go.

B) Another problem is that when using the Mixer Board with a multi-track project, it's difficult to adjust the level of the overall mix without affect the relative levels of different tracks. (This also applies to using track gain sliders).
This is a weakness in Audacity that could be improved.

C) User error.
> 3) no indication of clipping is shown to the user

Other than it sounds distorted and when played, and the playback meters are slammed up into the red.

Not listening to a mix before exporting it is user error (gross negligence on the part of the user). How can they have any confidence in the mix if they haven't listed to it?

There is no way to tell if a mix will clip without mixing it. For long tracks, this takes time.

I'm not in favour of this suggestion, but if our prime concern is to dissuade users from shooting themselves it the foot, we "could" pop up a warning prior to exporting multiple tracks to say:
>Perhaps you should Mix and Render first so that you can check the mix level

**Comment by LWinterberg** [comment]
This is something I've been thinking about on and off over the past several months - the "noob proof" solution would be a master effects stack with a brick-wall limiter at the 20th position, like FL studio does. But that comes with it's own set of problems, namely that a limiter still is a limiter which messes with your audio in a different way to distortion, and actually *hides* the fact that you're clipping from you. 

We have one solution in place for the qt version which has the playback meter turn solid red for a second every time you clip, so it should be more noticable there. In addition to that we probably should do a gain staging tutorial at some point to educate users how to deal with this properly. 

I don't believe there's a magimatic solution here, rather, it's the sort of thing that you need to be burnt by once before understanding what's going on - similar to learnings about super noisy/echoey/clipping/... recordings which can't generally really be salvaged to the degree that a novice user might want them to.
