### ISSUE TITLE
Karaoke view still adds spaces even when there are hyphens

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1738]
**Describe the bug**
The manual states:
>"You may want to split up lyrics such that the ball bounces per syllable rather than just for the whole word. To do this, create a label for each syllable, and end each with a hyphen ("-"), except the last syllable. For example, "Aud-" "a-" "ci-" "ty". The hyphen tells Audacity to not put a space between the syllables, as it does between words."

This does not appear to work.
This issue was reported on the forum: https://forum.audacityteam.org/viewtopic.php?p=424906#p424906

Originally logged on Bugzilla as 2786
https://bugzilla.audacityteam.org/show_bug.cgi?id=2786

**To Reproduce**
1. See bug description

**Expected behavior**
As stated in the Manual:
https://manual.audacityteam.org/man/karaoke.html

**Screenshots**

**Additional information (please complete the following information):**
 - OS: all OS
 - Version: all Audacity since Karaoke was introduced _(in 1.3.11 we believe)_

**Additional context**
The original poster on the Forum wrote:

>"Karaoke" window seems to ignore hyphens in label track
It seems that the karaoke view in Audacity 3.0.2 ignores hyphens in the label track.
Tested with 3.0.2 and 2.5.2, Windows 10 Pro and Manjaro.

>According to the manual it's supposed to remove the spacing between the labels, such as "Aud-" "a-" "ci-" "ty" is shown as a single word, but the "ball" jumps according to the syllables:.

>What's actually happening is that the labels are rather shown as-typed, aka "Aud-" "a-" "ci-" "ty" is shown as "Aud- a- ci- ty" instead of "Audacity".

**Comment by petersampsonaudacity** [comment]
Steve wrote to me on email:

>I don't use the Karaoke feature, and I guess that it is not widely used, but it is an embarrassment that it is so badly broken.

>I think that it should be a module, along with many other niche / specialist features. I've thought for a long time that Audacity should be a general purpose app that is highly customizable. That's not going to happen for a while yet, but I expect it will go that way eventually.

>Re. _[Bugzilla]_ bug 2786, I think that P4 is about right. I'd say higher if it were a more widely used feature.

**Comment by rbdannenberg** [comment]
It's amazing this "feature" even exists. It was added to demo a class 
project in the early days, when Audacity was simple enough that you you 
do something like that as a quick hack.

**Comment by LWinterberg** [comment]
I'm not sure if we'll touch this thing ever again other than removing it, so closing for now
