### ISSUE TITLE
ENH: Slicker Noise Reduction GUI

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1744]
**Is your feature request related to a problem? Please describe.**
The GUI for Noise Reduction in Audacity is a little clunky with its two-pass process that requires you to launch the effect twice.

And once you're in the NR effect (for the first time) it ca be confusing, unless you read the text and realize that you must make a small selection first - and that of course necessitates leaving the NR effect to make the noise sample selection.

It would of course be much slicker if you could make both the pass-1 noise profile selection and the pass 2 noise reduction (which would involve a second selection) from within the effect, without having to leave it.

Originally logged on Bugzilla as ENH 2048

**Describe the solution you'd like**
It would be good to be able to stay within the Noise Reduction dialog to make the two passes.

@Tantacrul @Jouni : The UI will need some careful consideration

**Describe alternatives you've considered**
None

**Additional context**
This ENH was logged on Bugzilla following a user email that @JamesCrook  dealt with and a subsequent discussion that James and I had by email.

For background the original user email:

> I have been using audacity for a while and recommend it quite often. 
>I wanted to share my thoughts about using the Effect “Noise Reduction…”
>
> It seems at first use that it does not work correctly. 
>Opening the window initially it provides 2 steps:
>
> “Step 1 Select a few seconds of noise so Audacity knows that to 
>filter out, then click Get Noise Profile:”
>
> In Windows you are unable at this time to select a few seconds of noise. 
>Focus is stuck in the Noise Reduction Window. Is this worded incorrectly 
>where you should click the “Get Noise Profile” button and then Select a 
>few seconds of noise? I think the wording needs adjustment so that the 
>user knows what to do at each step in the process.

**Comment by petersampsonaudacity** [comment]
@SteveDaulton wrote in the Bugzilla thread:

>(In reply to Peter Sampson from comment #0)
For this type of noise reduction, there has to be "two passes"; one to analyse the noise, and a second to apply "corrective filtering" based on that analysis.
>
>This is similar to the Normalize effect, which also has to analyse the audio before it can apply DC offset correction. The difference in this case is that the Normalize does this automatically.
>
>For the Noise Reduction effect, automating the two passes (so that the user only has to apply the effect once) is more difficult than for the Normalize effect. The required analysis is more complex, requires some tricky statistical analysis, and there could be difficulties making it fast enough to not be annoying. I believe that these difficulties could be overcome.
>
>I think it is also incorrect (and counter-intuitive) that increasing "smoothing" increases the "damage". This happens because the smoothing control expands the parts that are removed, rather than expanding the parts that are retained. The latter would give a relationship:
More smoothing => less noise removed => less damage
rather than what we have now:
More smoothing => more noise "and sound" removed => more damage

**Comment by SteveDaulton** [comment]
The Noise Reduction effect is (probably)  the only remaining built-in effect to use the old API. Updating the Noise Reduction effect would allow a clean up  of Effect.h and Effect.cpp.

**Comment by LWinterberg** [comment]
Related: 
* #2572

**Comment by LWinterberg** [comment]
one day.

**Comment by WangleLine** [comment]
I really like how Izotope RX handles this. The interface is quite intuitive there. Would be nice to have this in audacity too.

**Comment by Tantacrul** [comment]
Hey @WangleLine! Nice to see you here.
