### ISSUE TITLE
Clip edit cursor do not disappear (with multiple tracks)

### ISSUE THREAD

**Issue by AnitaBats** [audacity/audacity#1759]
Steps to reproduce:
 * Create two or more tracks
 * Add a clip to the first one (on top)
 * Start edit clip name in direct mode (double click on clip handle, make sure option 'Use dialog for the name of a new label' is disabled) 
 * Click at any empty space on same track or another track
 
Observe: clip name edit cursor is still visible
 Expected behavior: edit cursor should be dismissed after time selection changed/activated

**Comment by Tantacrul** [comment]
Changed to P2 because I've found that this issue can block you from editing. It could arguably be a P1.

**Comment by Penikov** [comment]
Works well only with the Selection tool and only inside the track panel.
In other cases, the problem still remains.

I talked with @vsverchinsky and we decided to add another issue because this one was partly fixed and merged.
