### ISSUE TITLE
Slow drives are allowed for project use but can be very slow

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1760]
**Describe the bug**
Slow drives are allowed for use but can be very slow (for example exFAT USB Clip drives).

Originally logged on Bugzilla as bug 2620
https://bugzilla.audacityteam.org/show_bug.cgi?id=2620

**To Reproduce**
1) use a USB exFAT formatted drive
2) launch Audacity
3) Generate a one hour stereo chirp
4) Save the project to the USB drive
5) Observe: you can (it works but it is very slow)

6) open directories preferences
7) set the Temporary files directory to be on the exFAT USBdrive
8) Observe: you can do so

9) close Audacity
10) relaunch Audacity
11) Generate a one-hour stereo chirp
12) Observe: it works but is very slow

**Expected behavior**
The user should be warned that the drive they propose to use is likely yo be slow.

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS:  all OS
 - Version: all Audacity

**Additional context**
This should be a warning and not a block - small USB clip drives can be useful for certain QA testing, in particular running out of disk space,

**Comment by LWinterberg** [comment]
This is becoming less of a problem as the adoption of USB3 and USB4 increases. I don't think this needs a fix.
