### ISSUE TITLE
Spectrogram Settings unavailable when playing, recording or paused

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1761]
**Describe the bug**
Spectrogram Settings unavailable when playing, recording or paused.

This is a regression on 2.1.2 (which is when we first introduced Spectrogram Settings into the Track Control Panel drop-down menu).

In all subsequent versions of Audacity Spectrogram settings is grayed out and unavailable when
a) playing
b) recording
c) paused

Originally logged on Bugzilla as bug 2423
https://bugzilla.audacityteam.org/show_bug.cgi?id=2423

**To Reproduce**
1. Generate a chirp
2. Click Play and Pause
3. Switch to Spectrogram View (or Multi-View)
4. Attempt to change Spectral Settings from 8KHz range to 16Khz.
5. Observe: Spectrogram Settings is greyed out.

**Expected behavior**
Spectrogram Settings to be available when playing, recording or paused

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS: all OS
 - Version Audacity 2.1.3-3.0.4 and 3.1.0 alpha

**Additional context**
@SteveDaulton wrote in the Bugzilla thread:

>Is there a reason why spectral settings can't be changed while playing?
If not, then the restriction is an unnecessary inconvenience for anyone that wants to do so, and imo should remain logged (as an "enhancement" issue would be OK).
>
>We shouldn't be imposing arbitrary restrictions on what users can / cannot do without good reason. IF there is a good reason to not allow spectral settings to be changed during Play, that reason should be logged and then this issue can be closed as "won't fix".

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
