### ISSUE TITLE
 Pinned play-head button not updated across projects

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1762]
**Describe the bug**
The  Pinned play-head button is not updated across projects.

Originally logged in 2017 on Bugzilla as 1769
https://bugzilla.audacityteam.org/show_bug.cgi?id=1769

**To Reproduce**
1. Open audacity 
2. create something, say 1 minute chirp
3. Ctrl+N to create a new project
4. create something, say 1:30 noise
5. pin the playhead
6. Press Play and stop
7. Alt-Tab to 1st project - or Select it
8. press Play
9. Observe: 1st project shows unpinned head but plays pinned.

**Expected behavior**
The  Pinned play-head button should be updated across projects

**Screenshots**

**Additional information (please complete the following information):**
 - OS: all OS
 - Version: originally reported on Audacity 2.2.0 - but still the case in 3.0.4 and latest 3.1.0 alpha

**Additional context**
@SteveDaulton wrote in the Bugzilla thread

>Perhaps not surprisingly, the issue also occurs when unpinning the playhead.
>
>1) Launch Audacity
2) Click the "pin playhead" button. 
  The icon indicates that the playhead is pinned.
3) Open a new (second) project. 
  The icon indicates that the playhead is pinned.
4) Click the playhead button in the second project.
  The icon indicates that the playhead is unpinned.
5) Add some audio to the first project and start playback.
  Note that the button in the first project indicates that the playhead is pinned, but playback is with un-pinned. The "Pinned Play/Record Head (on/off)" menu item indicates that the playhead is unpinned.

**Comment by LWinterberg** [comment]
this is fixed now in that the button and playhead no longer are visibly stateful
