### ISSUE TITLE
Tabbing between point labels now has an almost invisible visual cue

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1767]
**Describe the bug**
Tabbing between point labels now has an almost invisible visual cue.

This is as a result of design changes made for 3.1.0 for region labels giving then a drag-bar affordance.

In 3.0.4 and earlier when tabbing to a label the label text box was highlighted with focus.  In 3.1.0 the focus is now on the drag bar affordance - which means that for point labels there is no drag-bar, so there is no highlighting as a visual cue - just a couple of little tiny dots either side of the circle of the point label.

This is effectively a regression on 3.0.4 and earlier

**To Reproduce**
1. create some audio with point labels and region labels
2. Open the project in 3.0.4
3. Tab between labels
4. Observe: clear highlighted visual cues to show which label is selected, both point and region labels
5. Open the project in 3.1.0 alpha
6. Tab between labels
7. Observe:  only the region labels have a clear highlighted visual cue

**Expected behavior**
Good clear visual cue to show that the tabbing has indeed moved to a point label

**Screenshots**
1) 3.0.4 - Tab to region label
![image](https://user-images.githubusercontent.com/50205984/135064960-223381eb-b65c-4b9d-9135-d0bd20fa7526.png)
Here the region label is clearly shown to be focused - note the focus (and thus highlighting) on the label's text field

2) 3.0.4 Tab to point label
![image](https://user-images.githubusercontent.com/50205984/135065187-c380b3df-78ae-450c-839f-b24ba51b7b2c.png)
Here the point label is clearly shown to be focused - note the focus (and thus highlighting) on the label's text field

3) 3.1.0 alpha Tab to region label
![image](https://user-images.githubusercontent.com/50205984/135065451-6f3e0ea7-6d57-4aeb-ac8d-d3c1d0f4085e.png)
Here the region label is clearly shown as focused - but not the focus is on the drag bar and not the label text.

4) 3.1.0 alpha Tab to point label
![image](https://user-images.githubusercontent.com/50205984/135065795-846f7346-1b7a-460e-a7e6-067e40ae9b9d.png)
Here there is an almost invisible visual cue - just the two small black dots above and below the circle of the point label, this is janky.
So, yes there is also the cursor movement in the Timeline - but when the user is tabbing between labels their visual attention is on the label track and **_NOT_** the Timeline.

**Additional information (please complete the following information):**
 - OS: Windows 10 - but this will be all OS
 - Version: 3.1.0 alpha  audacity-win-3.1.0-alpha-20210927+25d7d1d-64bit

**Additional context**
I stumbled across this while working on a live project - I labelled some Microsoft dings that had corrupted my Timed Recording as I wanted to edit them out.  The images above are from this live project (the region label was just added for testing purposes).  This changed behavior made me revert to 3.0.4 so when tabbing between my point labels I could clearly see which label (and which Microsoft ping) I was at.

There will be a similar lack of visual cue when the length of a region label  becomes visually small, for example when zoomed out.

This is a GUI and UX issue so flagging this for the attention of: @Tantacrul and @jounih

**Comment by petersampsonaudacity** [comment]
Also if you highlight a region label text box for editing and then press tab - what this does is shift focus to the drag-bar and does **_NOT_** tab to the next label, that requires a second press of the tab key.

I am totally failing to understand why tabbing in the label track tabs to the drag-bar rather than the label text as it did previously

With focus on the label text:
a) the label bar still highlights as yo move or hover over it - with the drag-hand cursor
b) you can drag the clip
c) you can double-click on the drag-bar to select region label and audio

**Comment by petersampsonaudacity** [comment]
Copying in @DavidBailes - as he was  discussing similar on Discord (IIRC) a while back. - and label tabbing is a useful VI feature, I believe.

**Comment by DavidBailes** [comment]
> - and label tabbing is a useful VI feature, I believe.

When tabbing resulted in the name of the label being opened for editing, tabbing was of little use to users of screen readers, because the custom edit box which is used can't be made accessible for screen users using the accessibility framework used by wxWidgets.
So for screen reader users, being able to just select a label without its name automatically being opened for editing is good news. However, issues #1710 and #1780 would have to be fixed for it be of much use.

**Comment by crsib** [comment]
@Tantacrul looks like a design issue

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
