### ISSUE TITLE
Audio track. The 'track cursor' has white reflections on the track at the high-scaling level.

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#1770]
**Describe the bug**
When a user zooms the track at the sample level, the audio cursor (don't confuse with play head, please) has white reflections on the audio track

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch Audacity
2. Import/Record an audio track
2.1. Switch Audio track view to the Waveform view
3. Zoom in the track to the sample level.
4. Point the cursor at any position on the track.

**Expected behaviour**
The audio cursor shouldn't cast shadows or reflections or whatever at the track.

**Actual behaviour**
![изображение](https://user-images.githubusercontent.com/25851359/135165039-99bbc74e-99c8-432e-8b88-a1f4ec6fd575.png)
![изображение](https://user-images.githubusercontent.com/25851359/135165147-71f46366-9351-42d6-81ce-b24a2807bb49.png)

https://user-images.githubusercontent.com/25851359/135165273-75fbca2c-388d-46df-88fe-6344dc0ee568.mp4

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Audacity 3.1.0-alpha-20210928

**Comment by SteveDaulton** [comment]
I'm not sure if this is the same issue, but it may be: https://forum.audacityteam.org/viewtopic.php?p=436197#p436197

**Comment by AnitaBats** [comment]
not a bug, works as intended
