### ISSUE TITLE
A label can be created by typing regardless of option setting

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#1780]
**Describe the bug**
If a label is selected, then you can type to create a label, even if the "Type to create a label" option is disabled.

**To Reproduce**
1. Disable the Type to create a label option in the track behaviors page of preferences
2. Create a label track with one or more labels
3. Tab to a label to select it (or click on a region label)
4. Type a letter.
5. A new label is created.

**Expected behavior**
If "Type to create a label" is disabled, then typing never creates a label.

**Fixing this bug:**
Once this issue has been fixed: https://github.com/audacity/audacity/issues/1710,
then I think the fix is straightforward:
In LabelTrackView::DoCaptureKey(), the lines:
if (IsValidIndex(mTextEditIndex, project) || IsValidIndex(mNavigationIndex, project)) {
      if (IsGoodLabelEditKey(event)) {
         return true;
      }
   }
should be changed to:
In LabelTrackView::DoCaptureKey(), the lines:
if (IsValidIndex(mTextEditIndex, project)) {
      if (IsGoodLabelEditKey(event)) {
         return true;
      }
   }

If this change is made before #1710 is fixed, then the Enter key will no longer be captured for the hardcoded use of Enter to edit the label name. The code would have to be modified to capture this, but it shouldn't be hardcoded, so best to fix #1710 first.

**Comment by petersampsonaudacity** [comment]
And it creates a second label in the same range of the region label.

**Comment by DavidBailes** [comment]
Example of the effects of this bug:
With "type to create a label" disabled:
1. Select a label.
2. Press spacebar for playback.
3. Press P for Pause. Rather than pause a new label is created starting with P.
