### ISSUE TITLE
Files cannot be opened from the macOS Finder when a project window already exists 

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#1781]
This almost certainly is caused by the fix we made in 3.0.5 / #1701 

First reported in https://forum.audacityteam.org/viewtopic.php?f=47&t=120630, description follows: 

When Audacity v3.0.5 IS NOT RUNNING, opening a project file form the Finder via
– Cmd-O
– double-click and
– open with…
works fine: the project file is opened in Audacity.

But when Audacity v3.0.5 IS RUNNING, opening a project file form the Finder via
– Cmd-O
– double-click and
– open with…
does NOT work fine: the project file is NOT opened in Audacity.

Video:
https://www.srut.de/audacity/305/AUDACITY-305-Problem--Project-does-not-open-when-Audacity-305-is-running.mp4

System:
macOS 10.15.7 Catalina
iMac (Retina 5K, 27 Zoll, Late 2015)
3,3 GHz Quad-Core Intel Core i5
24 GB RAM

German Audacity version

**Comment by Penikov** [comment]
Cannot reproduce it on my Mac with any combinations of languages(

**Comment by mathpoli** [comment]
> Cannot reproduce it on my Mac with any combinations of languages(

Have you also set the decimal separator to "decimal comma"?

In my case: Language German + decimal separator to "decimal comma" = file does not open from the finder when AUDACITY is already running.

[https://srut.de/audacity/305/decimal-separator.jpg](url)

**Comment by SteveDaulton** [comment]
Another report of this bug here: https://forum.audacityteam.org/viewtopic.php?p=440326#p440326

**Comment by LWinterberg** [comment]
Another similar report: https://forum.audacityteam.org/viewtopic.php?f=47&t=121983
