### ISSUE TITLE
macOS: Light theme toolbar buttons have no mouse-over state different from "up"; other 3 themes do have it

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#1783]
Since version 2.2.0 in 2017, Audacity has had four built-in themes.

In each theme, there are big toolbar buttons (play, record, etc.) and small ones (tools toolbar, edit, play-at-speed, pinned playhead).

In three of them (Classic, Dark, High Contrast) each button distinguishes an "up" and a "down" background, but also a third background for mouse-over when a button is up and clickable.

But Light theme -- the default -- does not distinguish "Up" from mouse-over.

This surprising omission could be simply fixed with regeneration of the "sprite sheet" in LightThemeAsCeeCode.cpp.

**Comment by Paul-Licameli** [comment]
See also #1768

**Comment by chinakov** [comment]
Fixed within the scope of https://github.com/audacity/audacity/pull/6650.
