### ISSUE TITLE
Add a discontinuous selection method

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#1790]
This is from the todo.txt

Currently, selections all happen in one piece: you click and drag and it selects everything where you clicked and dragged. This means that if you want to apply an effect to clips 1, 4, 5 and 8, you need to apply it 3x (4+5 can be selected together, but the others can't). 

The common modifier for this to use would be ctrl+click (eg in windows explorer).

**Comment by petersampsonaudacity** [comment]
And **Shift + Click** to select a range of clips

**Comment by petersampsonaudacity** [comment]
Multiple selections from within a continuous clip would also be useful - has has been requested by users many times in the past

**Comment by SteveDaulton** [comment]
The poor man's version of this is "Edit menu > Labelled Audio > ...", but that is limited to editing (not applying effects). It would be nice (and much requested) to have a better / proper approach to discontinuous selections.

**Comment by LWinterberg** [comment]
This is planned for "smart clips 2.0" - basically, a selection of clips that works independent of time selection, making discontinuous time selection unnecessary

**Comment by Paul-Licameli** [comment]
> This is planned for "smart clips 2.0" - basically, a selection of clips that works independent of time selection, making discontinuous time selection unnecessary

This is not the same thing as selecting multiple intervals of time, so I understood.  It is about the discrete on/off selection of clips as clips.

**Comment by LWinterberg** [comment]
Correct @Paul-Licameli. It's just that a clip-level on/off would solve the exact problem I put up in the OP.
