### ISSUE TITLE
FFmpeg freeze when try to loading audio

### ISSUE THREAD

**Issue by p0008874** [audacity/audacity#1794]
**Describe the bug**
FFmpeg freeze when try to loading audio

**To Reproduce**
1. Loading ogg file with newest FFmpeg on it.

**Expected behavior**
Freeze and won't able to load.

**Screenshots**
https://cdn.discordapp.com/attachments/561726350432403486/893118694610321438/unknown.png

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version Audacity 3.0.5 64bit

**Additional context**
none.

**Comment by petersampsonaudacity** [comment]
What version of FFmpeg ?

**Comment by p0008874** [comment]
> What version of FFmpeg ?

3.0.5 64bit

**Comment by petersampsonaudacity** [comment]
@crsib any insights on this Dmitry ?

**Comment by crsib** [comment]
3.0.5 is a hotfix release. It contains no changes to FFmpeg and only works with avformat-55. 

It is worth mentioning though that OGG export is not based on FFmpeg in Audacity. It uses `libvorbis` directly. Audacity 3.1.0 will ship with the latest version of the codec. Still, this case is strange, as Audacity 3.0 had a fix specifically for this.

It is possible to export OGG using FFmpeg. To do so, please install FFmpeg as described in the manual: https://manual.audacityteam.org/man/installing_ffmpeg_for_windows.html

Then, select `Custom FFmpeg Export` in the export dialog, press `Open custom FFmpeg format options`, and select OGG from the dialog.

**Comment by petersampsonaudacity** [comment]
Thanks  @crsib  Dmitry ...
