### ISSUE TITLE
Linux: Spectral Selection Toolbar malformed

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#1800]
**Describe the bug**
The text in the menu button of the Spectral Selection Toolbar is much too big and partially hidden.

**To Reproduce**
1. Enable the Spectral Selection Toolbar.
2. Use a moderately high definition monitor

**Expected behavior**
The text in the Spectral Selection Toolbar menu button to be the same size as in other menu buttons

**Screenshots**
![SelectionToolbar](https://user-images.githubusercontent.com/11681097/135613247-400c9f9b-cbb8-48d9-ab99-74aca420568d.png)

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version: Audacity 3.0.5 Release build

**Comment by petersampsonaudacity** [comment]
Looks fine on W10 with latest 3.1.0 alpha audacity-win-3.1.0-alpha-20210930+6750576-64bit

**Comment by SteveDaulton** [comment]
Same problem here with the latest 3.1.0 "master" branch code.

**Comment by Penikov** [comment]
What DE on Xubuntu it is?

**Comment by SteveDaulton** [comment]
> What DE on Xubuntu it is?

The default XFCE.

**Comment by prsndp** [comment]
Hi, @SteveDaulton I would like to work on this issue. Could you please assign me?

**Comment by SteveDaulton** [comment]
Hi prsndp, thanks for offering to take this on. It's not my decision to assign issues, but  as far as I'm aware, if you want to have a go at fixing it then you can just go ahead, make a fix, and send a pull request.

Just so that you are aware and to avoid  frustration, there is currently a long delay (sometimes several weeks) between sending a pull request and having it reviewed / pulled. Hopefully this will improve over time.

**Comment by prsndp** [comment]
@SteveDaulton thanks:)

**Comment by Penikov** [comment]
@prsndp Hello!
Thank you for participating )
I think @crsib could decide this. I let him knew.

**Comment by LWinterberg** [comment]
like #1456, this will get fixed in the qt version
