### ISSUE TITLE
Shortcut for Multi-tool has changed to be F5

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1803]
**Describe the bug**
The shortcut for Multi-tool has changed to be F5 .

this is a regression as in all Audacity versions 1.2.x - 3.0.5 the shortcut for Multi-tool has been F6.

This will be greatly annoying for folk who have learned this and burned it into their muscle memory over the years.

**To Reproduce**
1.  Launch 3.1.0 alpha  audacity-win-3.1.0-alpha-20211001+27a591d-64bit
2. Hover your cursor over the Multi-tool
3. Observe: hovertext indicates that F5 is the shortcut
4. Press F6
5. Observe: nothing happens
6. Press F5
7. Observe: Audacity switches to Multi-tool mode

**Expected behavior**

**Screenshots**
F6 to be the shortcut for Multi-tool

**Additional information (please complete the following information):**
 - OS: Windows 10 - but assume all
 - Version: Audacity 3.0.1 alpha  audacity-win-3.1.0-alpha-20211001+27a591d-64bit

**Additional context**
Probably caused by the planned removal of the Time-shift tool - see issue #1411 

@Tantacrul :  A good case could be made for the removal of the Tools toolbar altogether - and with it the removal of the tools modes.

It would also remove a bear-trap that many folk fall in to when they inadvertently press one f the buttons F2-F6 and switch tool mode - and then have no idea how to get back to simple Select tool mode - we have seen this countless times on the Forum over the years.

**Comment by petersampsonaudacity** [comment]
@LWinterberg Leo if this remains unfixed in this state then some pages in the Manual will need to be changed.

**Comment by Tantacrul** [comment]
No 'good' answer here. However, my feeling is that @petersampsonaudacity is right. It should remain F6.

Sacrificing logic for muscle memory.

**Comment by petersampsonaudacity** [comment]
Confirmed OK on W10 with audacity-win-3.1.0-alpha-20211006+917d8a1-64bit
