### ISSUE TITLE
Linux: Nyquist unavailable after installing

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#1804]
**Describe the bug**
After building Audacity 3.0.5 from source and installing, Nyquist is unavailable.

**To Reproduce**
1. Download https://github.com/audacity/audacity/archive/refs/tags/Audacity-3.0.5.tar.gz
2. Extract and build
3. Test Audacity within build folder and observe that Nyquist is available and works correctly
4. Install Audacity
5. Launch Audacity 3.0.5 from Apps menu
6. Observe that Nyquist effects are missing
7. Observe that Nyquist is does not appear as an option in "Preferences > Effects"

**Expected behavior**
Nyquist to be available in Audacity 3.0.5

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version: Audacity 3.0.5

**Additional context**
Regression.

**Comment by SteveDaulton** [comment]
Also occurs with Audacity 3.0.4 Release build.

"Help menu > About Audacity -> Build Information" says:
`Nyquist (Plug-in Support) Enabled`
but Nyquist does not appear in "Edit menu > Preferences > Effects"

**Comment by SteveDaulton** [comment]
Also occurs with Audacity 3.0.3.

The last version in which Nyquist is available (after installing) is Audacity 3.0.2.

**Comment by SteveDaulton** [comment]
This bug may depend on Audacity being previously installed from the Ubuntu repository.

**Comment by LWinterberg** [comment]
I cannot reproduce this in 834d47c1cb3cf246f0e9db365bc2dc43a52d5718

**Comment by dozzzzer** [comment]
I cannot reproduce this in 3.3.2
