### ISSUE TITLE
At certain zoom levels label drag bars become invisible thus precluding selection

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1805]
**Describe the bug**
At certain zoom levels label drag bars become invisible thus precluding selection. 

In the Steps to reproduce
a) at 3x zoom-out the drag-bar is no longer visible all - so label and associated audio cannot be selected by clicking on the label
b) even at 2x zoom-out the drag bar is still showing but so small that when I try to hover over it it fails to light up and I therefore can't click on it to make the selection of audio and label.

This is a regression on 3.0.5 - and comes about as the design decision when introducing the label drag-bar to make that the selection tool.  

In 3.0.5 and earlier one could click on the label text field (always visible no matter how much you zoom out) and that
a) selected the range of the label in both the label track and the audio track(s)
b) it opened the label text for editing

In 3.1.0 clicking on the label text only
b) opens the label text for editing

**To Reproduce**
0. Normal zoom level (Ctrl+2)
1. Get some audio
2. make a 1 second selection
3. label that selection with a range label (Ctrl+B)
4. select elsewhere
5. click on labels' drag-bar
6. Observe: range label and its associated audio are selected (screenshot 1)
7. select elsewhere
8. zoom out 3 or 4 times
9. Observe: the label's drag bar is not visible (hidden by the drag circles and chevrons ( Screenshot 2)
10. Try to select the label and audio by clicking
11. Observe you can't

**Expected behavior**

**Screenshots**
1) At normal zoom level I can easily select the audio defined by the range label by clicking on the drag-bar:
![image](https://user-images.githubusercontent.com/50205984/135751431-40576e1d-4559-407a-afe1-d2175cc337fb.png)

2) When zoomed out - in this case just 3x the drag-gar disappears and it is no longer possible to select the audio defined by the range label with the drag bar:
![image](https://user-images.githubusercontent.com/50205984/135751547-7b4d25e2-0ca7-4a7b-a1a6-358e7d5dd54a.png)

**Additional information (please complete the following information):**
 - OS: Windows 10 - but assume all OS
 - Version: Audacity 3.1.0

**Additional context**
I realize this is a design decision but nonetheless it induces a regression on all earlier Audacities 3.0.5 back to the 1.3.x Beta series.

Flagging this to @Tantacrul and @jounih as this is a UX/GUI issue

BTW this is not just a test example, rather this comes from a real-life project I am working on where I inadvertently got a couple of Microsoft pings in an unrepeatable recording _(@Paul-Licameli  and @SteveDaulton are kindly helping me try to reduce/remove the pings)_

**Comment by petersampsonaudacity** [comment]
This, of course also precludes the use of such an invisible zoomed-out label drag-bar from being used for its primary purpose which is to drag the label about.

**Comment by petersampsonaudacity** [comment]
On the plus UX side I did deliberately choose to use 3.1.0 alpha for this project as I wanted the convenience of using the drag-bars to move the clips around to line stuff up.

Thus avoiding the faff of having to switch back and forth between Selection too and Time Shift too - or have to struggle with the Multi-tool.

**Comment by petersampsonaudacity** [comment]
The workaround is, of course, to zoom out sufficiently that the label drag-bar becomes visible.

**Comment by petersampsonaudacity** [comment]
@LWinterberg  and @Penikov  - do you have any thoughts on this ?

**Comment by crsib** [comment]
@Tantacrul we need your opinion here, please!

**Comment by Tantacrul** [comment]
I don't think we should prioritise for 3.1, since the user can easily move the label by zooming in a little.

About fixing this issue, I think we could design a special state for labels when the user is zoomed-out enough. I fear trying to do that now will throw up more issues and bugs which will hold up the release of 3.1 unnecessarily. 

For 3.1, I think labels are 'net' easier to use and we can add refinements over successive releases.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
