### ISSUE TITLE
Clip-names are not shown when left edge of clip is not visible

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1814]
**Describe the bug**
Clip-names are not shown when left edge of clip is not visible

**To Reproduce**
1. Generate a 30 second chirp
2. Observe Clip-name is "Audio Track"
3. split the clip at 15 seconds (Ctrl+I)
4. Observe: Clip-names "Audio Track 1" and "Audio Track 2"
5. Zoom in 1x at 15 secs
6. Observe the left hand clip "Audio Track 1" does not have its name displayed
7. Move cursor to 25 secs and zoom in 1x
8. Observe no Clip-names at all (the zoomed clip is "Audio Track 2"

**Expected behavior**
Names of clips to be visible when any part of a clip is on screen - provided the length of the clip is sufficient for the display, in which case a right-truncated clip-name should be displayed.

**Screenshots**
1) Step 6
![image](https://user-images.githubusercontent.com/50205984/135869617-8ceb5c91-8ef0-4aaa-af88-368bc009db25.png)

2) Step 8
![image](https://user-images.githubusercontent.com/50205984/135871100-3f88e859-24a8-48c6-8442-fcb669ef2348.png)

**Additional information (please complete the following information):**
 - OS: Windows 10 - but assume all OS
 - Version: Audacity 3.1.0
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]

**Additional context**
Logging this "design issue" as it is a UX issue @Tantacrul and @jounih 
It is (would be that is) extremely useful for the user to see the actual name of the clip(s) they can see on-screen.

I'm pretty confident that if this doesn't get addressed for 3.0.1 with the introduction of Clip-handle drag-bar affordances then you are likely to see complaints from users about this on the Forum and GitHub.

**Comment by Tantacrul** [comment]
I agree, this is a desirable refinement. It would be great for the names to always show if a clip is visible.

**Comment by DavidBailes** [comment]
And there's an equivalent issue when the language is RTL (when only the left hand part of a clip is visible).

**Comment by augustya0new** [comment]
> I agree, this is a desirable refinement. It would be great for the names to always show if a clip is visible.

I would like to take this task and work on the issue

**Comment by LWinterberg** [comment]
@augustya0new Thank you for your interest! So, this task is already part of the current sprint and assigned to @vsverchinsky, so the expectation is that it's fixed within a week or two, so we can get it included in the upcoming release. I think it'd be better if you chose something that's not as time-critical as this feature - maybe some of these? https://github.com/audacity/audacity/projects/15
