### ISSUE TITLE
Impossible to select point audio with cursor at shared clip boundaries

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1815]
**Describe the bug**
It is impossible to select point audio at shared clip boundaries using the cursor, as the left-click joins the two clips

This happens because a single left-click on the shared clip boundary results in joining the two clips together.

The only workaround is to use the Selection tool bar input fields (provided you know **_precisely_** where the shared clip boundary is).  Or if you have dropped a label the the join as in step 3 - then you can select in the label track.

**To Reproduce**
1. Generate a 30 second chirp
2. set the cursor at 15 seconds
3. drop a point label (for reference only) - Ctrl+B
4.  Split the clip (Ctrl+I)
5. move the cursor elsewhere in the audio track
6. Now try to select with the cursor at the shared clip boundary in the audio track
7.  Observe the selection is made - BUT the two clips are now joined

**Expected behavior**
1) Left-click at a shared clip boundary  **_not_** to join clips

2) Alternative method:  
2.1) right click in the audio track pops the drop-down context menu.  
2.2) The menu to have a Join menu item added
2.3) Selecting that "Join" context menu command joins all clips that have a shared boundary with the clip that has been right-clicked in.

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS: Windows 10 - but suspect all OS
 - Version: Audacity 3.0.1

**Additional context**
This is a UX/GUI design issue:  @Tantacrul and @jounih 

Previous Audacity versions have all done this clip joining when left-clicking on the shared clip boundary - _(so technically this would be a minor regression)_ but I think it would be a good improvement if this were changed for 3.1.0 with the increased focus on clips with the introduction of the Clip-name drag-bar affordances

**Comment by LWinterberg** [comment]
IMHO the black "click to join clips" line needs to go anyway and its functionality transferred into a right-click menu. You should be able to join clips by selecting 2 (or more!) clips and then right-clicking > join clips instead. The black line only causes trouble: It gets in the way of point selections and will get in the way of smart clips, it gets in the way of samples (#1663) and it also isn't even aligned to the actual border between clips

**Comment by Tantacrul** [comment]
> MHO the black "click to join clips" line needs to go anyway and its functionality transferred into a right-click menu. 

Agreed

**Comment by Paul-Licameli** [comment]
It is in incorrect that there is no way to do it but with the selection toolbar.

The ESC key before mouse button down has been the little known way to resolve conflicts among hit tests since about 2.2.0 when I rewrote all the event handling spaghetti in TrackPanel.

Actually I’m wanted the Tab key for this purpose (it rotates among alternative things in other contexts) but @DavidBailes objected.

Why cant some such convention for disambiguating  close hit test targets be well known and uniform?

**Comment by petersampsonaudacity** [comment]
See related issue #2330

**Comment by LWinterberg** [comment]
this gets fixed with #2330

**Comment by SteveDaulton** [comment]
> * Now try to select with the cursor at the shared clip boundary in the audio track

Why not just click on the label track to set the cursor position? 
Or if you want to make an audio selection, just click and drag "to" the clip boundary and stop when the yellow snap line appears?

I do recall one or two users on the forum having difficulty with this over the last 15 years, but mostly it looks like a non-issue to me.
The bigger issue as I see it is that regions within a few px of clip boundaries are becoming overloaded with multiple functions (joining, resizing, selecting, dragging) without clear indication of which will be triggered.

**Comment by SteveDaulton** [comment]
> That works fine if you have a label track

As in the "steps" that you posted

> and if it's visibly close enough to be seen in conjunction with the audio track - otherwise not ...

Realistically, if you have so many tracks that you can't easily see the label track, then it's unlikely that all tracks have splits at exactly the place that you need to place the cursor. Having completed literally hundreds of multi-track projects, I can't honestly say that this has ever been a problem.

If, for example, I needed to create a point label at a clip boundary, and it had to be sample accurate, then I'd zoom in all the way and click between the clips. If it didn't have to be sample accurate, then I could click a short distance before or after the clip (and optionally drag the label closer  to the boundary if necessary. At worst, click twice (_not_ double click) then "Ctrl + i".

I agree that this is not as slick as it might  be, but I've never found it to be a problem - perhaps a P5 enh.

**Comment by SteveDaulton** [comment]
There is one thing here that looks very weird to me:
1. Drag a selection to a clip boundary
2. Shift + click + drag the end of the selection that is not at the clip boundary, to the clip boundary
3. Note that step 2 is impossible! The selection jumps from one side of the boundary to the other, but cannot be snapped to the boundary.

This behaviour seems to be fairly new, whereas it was previously a simple workaround for the issue being discussed.
