### ISSUE TITLE
The slider setting value for AAC/MP4 export is not honored by Audacity - and the slider cannot make precise settings

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1818]
**Describe the bug**
a) The slider setting value for AAC/MP4 export is not honored by Audacity.

b) Plus it is very hard (perhaps impossble) to set precise values - I found it impossible to set it to the "standard" rates of 192kbps and 256kbps

**To Reproduce**
1. Get some stereo audio
2. File > Export > Export Audio
3. choose M4A(AAC) Files FFmpeg
4. Set the Quality slider to 320kbps
5. Click "Save" to make the export
6. Examine the file (on W10 I used Windows Explorer)
7. Observe the file is not 320kbps (mine was 465kbps YMMV)

**Expected behavior**
a)  Audacity should export at the rate the user selects
b) The slider should allow for more precise setting (making it wider may help_
c) the user should be able to set a precise kbps value by typing it in _(cf. MP3 export and mic/speaker sliders)_

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS: tested on Windows 10 - but assume all
 - Version: Audacity 3.0.5 and 3.1.0

**Additional context**
1) Note that I am using the "recommended" FFmpeg the 64-bit Win downloaded from Buanzo's site
    This of course may change with an updated FFmpeg version ...

2) This does not happen with MP3 export in Audacity - the precise value is used for the exported file

3) Note that MP3 export uses a picking list and not a slider for the kbps setting - so we have an **_inconsistency_** issue here

4) The AACs that I have were made in iTunes,  
4.1) I export fro m Audacity as 16-bit WAV files
4.2) I import those WAV files into iTunes
4.3) I use iTunes to convert these WAVS to AAC files choosing 256kbps
4.4) I observe that iTunes converts these to 256kbps AAC files:
![image](https://user-images.githubusercontent.com/50205984/135894858-26143f29-2805-41b1-b0a5-12e6ef5c3f6a.png)

**Comment by petersampsonaudacity** [comment]
This was reported today on the Forum:
https://forum.audacityteam.org/viewtopic.php?f=46&t=120701&p=436404

It looks to be the same issue as this one logged in Bugzilla, which I shall close in favor of this GitHub issue
https://bugzilla.audacityteam.org/show_bug.cgi?id=2161
Bug 2161 - Enh: Same quality setting and range used for mono and stereo M4A (AAC).

**Comment by petersampsonaudacity** [comment]
This of course may change with an updated FFmpeg version ...

**Comment by Penikov** [comment]
Related to b) 
There is a way around it. You can choose the desired bitrate with the left-right keys.
![изображение](https://user-images.githubusercontent.com/25851359/135899080-ccc53101-7811-48f6-9d57-1b0271f73ba6.png)

**Comment by petersampsonaudacity** [comment]
Well whoever knew that? 

Is is documented or just an easter-egg ?

**Comment by petersampsonaudacity** [comment]
Looks like an easter-egg to me:
https://alphamanual.audacityteam.org/man/AAC_Export_Options

**Comment by Penikov** [comment]
I don't think this is documented feature.

**Comment by petersampsonaudacity** [comment]
> I don't think this is a documented feature.

It's not a documented feature - I looked earlier this morning, that's why I said it's an easter-egg ;-)

Apart from that one has to ask the question: just why us the slider so small in width anyway?  There is plenty of additional screen real-estate in the M4A(AAC) export dialog to widen it and make it easier to use.

**Comment by petersampsonaudacity** [comment]
OK so now for the upcoming 3.1.0 I have revealed this Easter-Egg in a tip div:
{{tip|You can use the keyboard left and right arrows to move or fine-tune your slider position.}}

See:  https://alphamanual.audacityteam.org/man/AAC_Export_Options#Format_Options

**Comment by werewolfgold** [comment]
Are there any updates on this? I'm still getting the same problem in version 3.1.3 of Windows 10 64-bit.

**Comment by petersampsonaudacity** [comment]
@crsib Dmitry does this need updated FFmpeg in order to fix this ?

**Comment by SteveDaulton** [comment]
> Related to b)
> There is a way around it. You can choose the desired bitrate with the left-right keys.

Perhaps "b)" should be split off into a separate issue, as the more serious issue is (a) that the exported file does not have the bit-rate specified by the user, and there is no good workaround for this issue.

**Comment by petersampsonaudacity** [comment]
> the more serious issue is (a) that the exported file does not have the bit-rate specified by the user, and there is no good workaround for this issue.

And of course the user usually has **_no idea_** at all that the bit-rate is not the one they specified and that is why this is important to get fixed ...

**Comment by SteveDaulton** [comment]
> BTW there is a good workaround:

I don't think it's particularly "good" for a software development company if they have to say "use a different app" to do something that their app is supposed to be  able to do. Perhaps a better workaround is to use Audacity's command line encoder, for example:
`ffmpeg -i - -b:a 96k "%f.m4a"`
but that's not very user friendly.

**Comment by petersampsonaudacity** [comment]
As it looks likely that this bug is unlikely to get fixed any tome soon I have updated this page in the manual with Advice divs about this bug to warn the user:
https://alphamanual.audacityteam.org/man/Tutorial_-_Exporting_to_iTunes

**Comment by petersampsonaudacity** [comment]
BUMP - and yesterday/today is yet another Forum user complaining about this issue:
https://forum.audacityteam.org/viewtopic.php?f=46&t=126426&start=10

@LWinterberg @dozzzzer @Tantacrul  this really should be getting fixed, not just because it is a P2 - but mainly because it's just plain sloppy - and leads to poor UX

**Comment by petersampsonaudacity** [comment]
The other thing I note about Audacity's M4A?AAC export dialog is that there is no option to choose between CBR and VBR'

This is _**not**_ the case with MP3 export where the user **_can_** choose.

And note that the poor old user is left in the dark with M4A/AAC export as tio which is being used.  I tend to infuer from the dialog GUI that it _**may**_ be CBR - but who knows ...

**Comment by crsib** [comment]
We should fix the docs about how to get FFmpeg as well or send Buanzo the new builds as well @LWinterberg

**Comment by Tantacrul** [comment]
> BUMP - and yesterday/today is yet another Forum user complaining about this issue: https://forum.audacityteam.org/viewtopic.php?f=46&t=126452
> 
> @LWinterberg @dozzzzer @Tantacrul @crsib this really should be getting fixed, not just because it is a P2 - but mainly because it's just plain sloppy - and leads to poor UX

Unless I'm mistaken, this really seems like a separate issue. I agree, it should be an exposed parameter for sure.

**Comment by petersampsonaudacity** [comment]
@Tantacrul  the recent Forum post is complaining about the issue as stated "The slider setting value for AAC/MP4 export is not honored by Audacity - and the slider cannot make precise settings"

I added a related issue for VBR/CBR - is that what you are saying is a separate issue?  If so do you want me to raise a new issue for it?

**Comment by crsib** [comment]
Probably let's just update this issue title and description. We need to investigate first the possible inputs for ABR/VBR/CBR anyway

**Comment by crsib** [comment]
I can say for sure, that VBR expects the quality from 1 to 6, not the bitrate

**Comment by petersampsonaudacity** [comment]
Bump @LWinterberg @dozzzzer @crsib 

This is a long-standing bug that really should be fixed (we get lots of user complaints about this). 

Any chance it can get fixed for 3.2.0 please?

**Comment by LWinterberg** [comment]
As you can see it got added to the 3.2 milestone yesterday

**Comment by petersampsonaudacity** [comment]
Still the case on 3.2.0 Beta on W10

See this recent Forum post with yet another user complaining about this:
https://forum.audacityteam.org/viewtopic.php?f=46&t=126899

**Comment by petersampsonaudacity** [comment]
@LWinterberg  

Testing @ksoze95 's  Kit's latest branch build on W10:  https://github.com/audacity/audacity/actions/runs/3068870464

Testing the STR - i.e requesting a 320 kbps AAC file I get much closer now with 317 kbps.

I have not had time today to test other settings _(I may be able to do that over the weekend)_

**Comment by petersampsonaudacity** [comment]
Further testing with @ksoze95 latest branch on W10 and macOS 12.5/1  -  https://github.com/audacity/audacity/actions/runs/3068870464

I get vastly different results on both platforms  -  test file id track 1 fro Sergeant Pepper's Lonely Hearts Club Band.

### W10
**requested    actual      Size
rate             rate         MB**
32                195         2.88    
64                195         2.88 
128              195         2.88 
160              195         2.88    (default rate)
192              195         2.88    
256              254         3.75
320              317         4.67

Also note that for **_any_** selected rate below 98kbps the "remembered rate" on the next visit to File Export as AAC is always 98kbps


### macOS 12.5.1
No matter what I select fro the requested rate  the rate of the output file I get is always 196kbps and the file size is always 3.1MB

Also on Mac the last-used rate is never "remembered" and re-offered on the next visit to  File Export as AAC - instaed it always offers the default rate of 160kbps

**Comment by LWinterberg** [comment]
The W10 behavior looks roughly intended:
```cpp
 q = wxClip( q, 98 * mChannels, 160 * mChannels );
      // Set bit rate to between 98 kbps and 320 kbps (if two channels)
```
which is the restriction the old slider had; it goes no lower than 98 kbit/s for mono and 196 kbit/s for stereo, and no higher than 160 for mono and 320 for stereo. 

What I don't know is how necessary this exact range is. The Wikipedia article on AAC has the unhelpful line
> The [MPEG-4](https://en.wikipedia.org/wiki/MPEG-4) audio coding algorithm family spans the range from low bit rate speech encoding (down to 2 kbit/s) to high-quality audio coding (at 64 kbit/s per channel and higher).

Hydrogenaudio and the Fraunhofer AAC encoder apparently recommend a range of 8kbit/s-288 kbit/s per channel for AAC-LC, with the built-in VBR modes supporting 20-112 kbit/s per channel: 
https://wiki.hydrogenaud.io/index.php?title=Fraunhofer_FDK_AAC

no idea what the problem is for mac.

**Comment by petersampsonaudacity** [comment]
> which is the restriction the old slider had; it goes no lower than 98 kbit/s for mono and 196 kbit/s for stereo, and no higher than 160 for mono and 320 for stereo.

### iTunes created AAC files
In contrast iTunes allows one to go down as low as 64kbps Stereo (or 32kbps mono):
![image](https://user-images.githubusercontent.com/50205984/190893919-e45ef48d-8b7a-45ab-bd0b-4448856de384.png)
And BTW also offers the choice of VBR (default) or CBR

And when one examines the file in iTunes it says that it's 64 kbps, 256 kbps - bot some number that's close as Audacity is doing,


### Audacity 3.1.3
In Audacity 3.1.3 the restriction is made clear as we had the slider to indicate the allowable range:
![image](https://user-images.githubusercontent.com/50205984/190894165-b6314707-69d8-4c1d-bc3c-5fa48906a4d3.png)


### @ksoze95 Kit's branch
In this branch build the limit(s) are not made clear to the user via the GUI 
![image](https://user-images.githubusercontent.com/50205984/190894391-38564c18-cc4b-4dc5-ac07-51cb2ceafbff.png)
If one clicks in any of the other data entry fields then (in the case shown here) the rate is changed to 98kbps, which the user may or may not notice (I certainly didn't when I was testing yesterday, only to be surprised by the kpbs rates when I examined the exported files).

Really if the user types an out of range number in that field a warning should be issued and the correction made immediately.


### Continuous range of values or discrete values
In contrast with iTunes AAC conversion and also Audacity's MP3 conversion where a pick-list range of discrete values is offered - Audacity's AAC conversion offers a continuous range 98-320 (this has always been the case with Audacity's Audacity conversion).  Maybe it would be better (and more consistent) if we followed that Audacity MP3 model:
![image](https://user-images.githubusercontent.com/50205984/190894793-5c7df207-1bb3-4bbb-a353-c1d447a6113d.png)
Note too that Audacity's MP3 export offers kbps rates much lower than can be obtained with AAC export in Audacity - though iTunes only goes down to 64kbps stereo 32kbps mono.

**Comment by crsib** [comment]
AAC is very complex codec with different implementations doing compression differently. We can only rely on the "native" FFmpeg encoder, there is no way to guarantee the Fraunhofer encoder is present. Default encoder from Apple is definitely not usable now.

What makes everything even more complex - Fraunhofer and FFmpeg "native" encoders are configured quite differently.

> and indeed restrict 

I'm not sure what you mean. Setup for M4A file format was never done right. There is a possibility, that FFmpeg changed the meaning of `q:a` significantly, but for the few latest version it definitely does not expect the values Audacity passed to it.

> Maybe it would be better (and more consistent) if we followed that Audacity MP3 model:

AAC and MP3 handle bitrate differently. We can extend the input range, though. It is quite hard to tell, when native ffmpeg encoder will fail.

**Comment by petersampsonaudacity** [comment]
@crsib  Dmitry,  boy oh boy - this makes me real glad that I always exported as WAV and then used iTunes to make the AAC conversion

**Comment by ksoze95** [comment]
@petersampsonaudacity 

> Really if the user types an out of range number in that field a warning should be issued and the correction made immediately.

I was working on the text entry validation, but unfortunately did not manage to get it working  before I took my annual leave.  A later PR will address this issue.

**Comment by dozzzzer** [comment]
@ksoze95 @petersampsonaudacity 
When exporting, if I set **160 kbps** and **320 kbps**, I'm getting 198 kbps and 329 kbps respectively.

**Comment by crsib** [comment]
Generally FFmpeg does not really allow to set the precise value. You can play with `ffmpeg -c:a aac -b:a 320k -i input.file -o out.m4a` to see how the command line handles it. The results will be slightly different anyway, but this shows how "native" FFmpeg AAC encoder handles the bitrate.

Optionally you can change the codec to `libfdk_aac` and play with that as well :-)
