### ISSUE TITLE
AppImage 3.0.5 fails on Arch Linux x86-64: "libgio-2.0.so.0: undefined symbol: g_module_open_full"

### ISSUE THREAD

**Issue by ericfont** [audacity/audacity#1821]
**Describe the bug**
Downloading audacity-linux-3.0.5-x86_64.AppImage and executing it on a newly-installed Arch Linux x86-64 machine fails to execute with the error:
`/tmp/.mount_audaciQb55nE/bin/audacity: symbol lookup error: /usr/lib/libgio-2.0.so.0: undefined symbol: **g_module_open_full**`

**To Reproduce**
1. download https://github.com/audacity/audacity/releases/download/Audacity-3.0.5/audacity-linux-3.0.5-x86_64.AppImage
2. make executable
3. execute it from terminal

**Expected behavior**
AppImages should have all necessary libraries properly included to work out-of-the-box

**Screenshots**

**Additional information (please complete the following information):**
 - OS: Linux 5.14.9-arch2-1 #1 SMP PREEMPT Fri, 01 Oct 2021 19:03:20 +0000 x86_64 GNU/Linux
 - Version Audacity 3.0.5

**Comment by ericfont** [comment]
for the record, I am able to self-compile 3.0.5 via git on my same machine and run it fine.  So the issue lies with packing the necessary libraries into the AppImage.

**Comment by ericfont** [comment]
And if you don't want to install arch, you can also [reproduce the error using docker instead](https://docs.appimage.org/packaging-guide/testing.html#using-the-docker-based-appimage-testsuite):

```
git clone https://github.com/aferrero2707/appimage-testsuite.git
cd appimage-testsuite/
./run.sh ~/Downloads/audacity-linux-3.0.5-x86_64.AppImage manjarolinux
```

and then inside the container when run `# /aitest/aitest.sh` I get a bunch of output ([audacity-in-manjaro-appimage-error.txt](https://github.com/audacity/audacity/files/7282741/audacity-in-manjaro-appimage-error.txt)).  At the end this since it is a fresh bare-bones manjaro container, the test script produces a slightly different error that libasound.so.2 is missing:

`/AppDir/squashfs-root/bin/audacity: error while loading shared libraries: libasound.so.2: cannot open shared object file: No such file or directory`

which can be fixed with `pacman -S alsa-lib` (which is presumably already installed on a desktop).  Then get error of missing 

`/AppDir/squashfs-root/bin/audacity: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory`

which can be fixed with `pacman -S libx11`(which also is presumably already installed on a desktop).  Then get:

`/AppDir/squashfs-root/bin/audacity: error while loading shared libraries: libpango-1.0.so.0: cannot open shared object file: No such file or directory`

which can be fixed with `pacman -S pango`.  Then get:

`/AppDir/squashfs-root/bin/audacity: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory`

which can be fixed with `pacman -S atk`...

BUT now I am at the same point in this docker container as I am with my arch linux desktop...I get the same error about libgio-2.0 g_module_open_full:

`/AppDir/squashfs-root/bin/audacity: symbol lookup error: /usr/lib/libgio-2.0.so.0: undefined symbol: g_module_open_full`

(full output of `/aitest/aitest.sh`: 
[audacity-in-manjaro-appimage-error-after-install-a-bit.txt](https://github.com/audacity/audacity/files/7282778/audacity-in-manjaro-appimage-error-after-install-a-bit.txt))

**Comment by ericfont** [comment]
and incase anyone is interested in testing other OSes via docker, that appimage-testsuite says:

The following Linux distributions are supported out-of-the-box:
* Ubuntu 14.04, 16.04 and 18.04
* CentOS 6 and 7
* Fedora 26 and 27
* Debian stable and testing
* Manjaro (Arch Linux derivative)
* Sabayon (Gentoo Linux derivative)

**Comment by LWinterberg** [comment]
Is this the thing that #1797 fixes? @crsib

**Comment by crsib** [comment]
Yeppers!

@ericfont Thank you a lot for pointing in the direction of appimage-testsuite! We will look into it, looks a good way to automate Linux testing (@Penikov)
