### ISSUE TITLE
Create new default settings for the spectrogram.

### ISSUE THREAD

**Issue by Tantacrul** [audacity/audacity#1825]
These are the settings that I landed on, which I feel achieve the following:

1. It opened the range up so users can see overtones that occur within the range of hearing
2. It runs much more smoothly
3. I found it easier to spot distinct sounds more clearly, which helped a little with the brush tool 
3. Since the resolution is higher, it is much more beautiful to look at, which is a bonus

![image](https://user-images.githubusercontent.com/21022311/136016685-a55da5ac-ab49-4ab4-9854-84cc8fb90ee8.png)

Some people have balked at using 'Bark' because it is apparently obscure. I liked it mainly because it left more space in the higher frequencies for users to brush on. However, there are a few other settings which (for this purpose) are nearly the same. Open to suggestion :)

**Comment by petersampsonaudacity** [comment]
Note that if this goes ahead then many images in the manual will once again need updating @LWinterberg

**Comment by SteveDaulton** [comment]
>  I liked it mainly because it left more space in the higher frequencies for users to brush on. However, there are a few other settings which (for this purpose) are nearly the same. Open to suggestion :)

"Logarithmic" also provides more space in the higher frequencies, is  one of the most common scaling methods, provides equal spaced frequency bands, and is consistent with the default [Plot Spectrum](https://manual.audacityteam.org/man/plot_spectrum.html) display.

**Comment by Tantacrul** [comment]
> "Logarithmic" also provides more space in the higher frequencies

I preferred Bark to Logarithmic because it had more space in the higher frequencies, similar to ERB.

I then tested on Audition, which also doesn't default to 'full Logarithmic' for what I imagine are the same reasons: to provide a range that will most likely allow users to isolate frequencies without having to fiddle with settings first.

**Comment by SteveDaulton** [comment]
I assume that you are aware that a non-linear spectrogram scale causes the new "spectral brush" tool to resize vertically according to which part of the spectrum is being drawn on.
Personally, I think that looks weird.
![First Track003](https://user-images.githubusercontent.com/11681097/136033631-83837584-9ac7-4f41-9d37-813044e6127f.png)

**Comment by Tantacrul** [comment]
Yep. It's a trade off. Ultimately, I think we need the 'brush' itself needs to correct for this. It was very much built without interaction in mind. I still think it is a 'beta' tool as is.

This isn't a useful comment for 3.1 but I think we need to expose those settings so they're more discoverable. I also think the spectrogram option is also too hidden.

**Comment by Paul-Licameli** [comment]
I do not like arbitrary changes in "Gain" "Range" and "High Boost" away from the defaults that users may be accumstomed to.

**Comment by Paul-Licameli** [comment]
iZotope uses Mel as default (scan for "default" on this page): https://s3.amazonaws.com/izotopedownloads/docs/rx6/07-spectrogram-waveform-display/index.html

**Comment by Tantacrul** [comment]
> I do not like arbitrary changes in "Gain" "Range" and "High Boost" away from the defaults that users may be accustomed to.

I actually did not change anything in 'colors'. I've mentioned over the last few days that my defaults are for some reason very different to everyone else... despite resetting them. I figure this might be a hangover from the time I tested the 3D spectrogram build ages ago.

Regardless, I don't propose to alter the 'color' defaults. So ignore that part.

**Comment by Tantacrul** [comment]
> iZotope uses Mel as default (scan for "default" on this page): https://s3.amazonaws.com/izotopedownloads/docs/rx6/07-spectrogram-waveform-display/index.html

Seems like a good choice to me.

**Comment by Paul-Licameli** [comment]
> > iZotope uses Mel as default (scan for "default" on this page): https://s3.amazonaws.com/izotopedownloads/docs/rx6/07-spectrogram-waveform-display/index.html
> 
> Seems like a good choice to me.

Both those scales came from psychoacoustic research, and Mel is more modern.

**Comment by Paul-Licameli** [comment]
> These are the settings that I landed on, which I feel achieve the following:
> 
> 1. It opened the range up so users can see overtones that occur within the range of hearing
> 2. It runs much more smoothly

More smoothly than what?  Than previous defaults?  No.  The old defaults were window size 1024 and zero padding size 1.

Your choices of 2048 and 2 imply more computation than those defaults.  That implies an FFT window size 4x as large as defaults.  But the growth of computation time there is only N * log N.

But I have noticed you were accustomed to using the non-default Reassignment algorithm.  So it will run smoother than what you were using.    Reassignment multiplies computation time by at least 3x.  Reassignment does some math magic to correct "spectral leakage" and can make the overtones draw as very narrow, bright curves.  But it is expensive.

You specify zero padding of 2 but I don't know how important that is to you.  You mentioned to me that you were not clear on what zero padding does.  To understand it, experiment perhaps with smaller window sizes and varying zero padding.  Small window size means less frequency resolution in the FFT, and zero padding does not change that (does not get more information out of the signal), but does affect the drawing so it is visually smoothed out, less blocky.

**Comment by Tantacrul** [comment]
I have not touched padding either. Again, I'm at the mercy of the defaults that I have on my machine.

To be clear: The only settings I willingly altered were all the options in 'scale' and everything in 'algorithm' apart from 'Zero padding factor'.

When I say that the result is smoother and less laggy - it is. And yes, I'm aware why it is too :)

**Comment by Paul-Licameli** [comment]
> I have not touched padding either. Again, I'm at the mercy of the defaults that I have on my machine.
> 
> To be clear: The only settings I willingly altered were all the options in 'scale' and everything in 'algorithm' apart from 'Zero padding factor'. Nothing else.
> 
> When I say that the result is smoother and less laggy - it is! And yes, I'm aware why this is true :)

Zero padding was defaulted to 1 before, so for those (as with the numbers in Color settings) I think you changed them at some time but forgot about it.

There is a PR already making padding 2.
