### ISSUE TITLE
Linux: Closing one project crashes all other open projects

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#1827]
**Describe the bug**
When more than one project is open, closing one project crashes all other open projects

**To Reproduce**
1. Open two or more projects
2. Close one of them
3. Observe that the other projects crash

**Expected behavior**
Audacity to not crash

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version: Audacity 3.1.0-alpha-20211004

**Comment by Paul-Licameli** [comment]
Is it fixed at d4d045873cb1c7fea856d56ccdb68b9c40c25469?

**Comment by petersampsonaudacity** [comment]
This does not happen on W10 with latest 3.0.1 alpha master:  audacity-win-3.1.0-alpha-20211005+39b3048-64bit

**Comment by SteveDaulton** [comment]
> Is it fixed at [d4d0458](https://github.com/audacity/audacity/commit/d4d045873cb1c7fea856d56ccdb68b9c40c25469)?

Yes, that seems to have fixed it.
(There is still a problem that Audacity does not shut down if the log window is open, but that's a different issue)
