### ISSUE TITLE
Brush tool: Internal error/crash at WaveTrack.cpp line 1085

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#1830]
**Describe the bug**
When attempting to use the "spectral data control panel", the error "Internal error at WaveTrack.cpp line 1085" appears

**To Reproduce**
1. Launch Audacity
2. Generate some white noise
3. Change to Track spectrogram view
4. Click on the "brush" icon
5. Click on the track spectrogram
6. Press "Del" key
7. Observe error message

**Expected behavior**
A spectral region of "brush size" to be deleted.

**Screenshots**

![error](https://user-images.githubusercontent.com/11681097/136042097-abfd18f0-f03f-4e91-9a09-e733974054ec.png)

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version: Audacity 3.1.0 alpha

**Additional context**

**Comment by Paul-Licameli** [comment]
Known but thanks for making the formal issue

**Comment by petersampsonaudacity** [comment]
Does not happen on W10 with latest 3.0.1 alpha master:  audacity-win-3.1.0-alpha-20211006+660d167-64bit

![image](https://user-images.githubusercontent.com/50205984/136176446-9e439be4-3b79-48a2-8476-05d2b8b73e0b.png)

**Comment by SteveDaulton** [comment]
> Does not happen on W10 with latest 3.0.1 alpha master: audacity-win-3.1.0-alpha-20211006+660d167-64bit

Note that step 5 is "Click on the track spectrogram", and not "Click and drag..."
The bug does not happen with "click and drag", only with "click".

**Comment by petersampsonaudacity** [comment]
> Note that step 5 is "Click on the track spectrogram", and not "Click and drag..."
> The bug does not happen with "click and drag", only with "click".

Ahh - then this is much worse on W10 as 
a) I don't get the error message
b) I DI get a crash - a silent crash with no "ET phone home"

Accordingly assigning P1 to this bug for the silent crash

**Comment by crsib** [comment]
Crash reporting is only enabled for builds from `release-*` branches.
