### ISSUE TITLE
Split New produces a clip with a somewhat nonsensical label with start/end clip times

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1831]
**Describe the bug**
The Split New command produces a clip with a somewhat nonsensical label with start/end clip times.

The split clip on a new track carries the name of the original clip appended with the start and end time of the clip.
a) the time is expressed in seconds to two decimal places i.e.seconds plus hundredths 
b) note that the default accuracy of the Selection toolbar is thousandths of a second, 3 decimal places 
c) note that the added text says "samples" wheb the units used are "seconds" (fractional)
d) the timings make absolutely no sense at all as soon as you slide the new clip along the timeline
e) most users will be puzzled by this - it took me a while to figure it out

In contrast the two clips on the original track are sensibly named as **original-name 1** and **original-name 2**

**To Reproduce**
1. Import some audio
2. select a section in the middle
3. Edit > Clip Boundaries > Split New
4. Observe: the new track's split clip has a name with start/end seconds+hundredths appended

**Expected behavior**
Name the new split clip on the new track as:  **original-name 3**

**Screenshots**
![image](https://user-images.githubusercontent.com/50205984/136053593-3f67809a-ede7-42d1-9a87-d06c65391a50.png)

**Additional information (please complete the following information):**
OS: W10 but assume all OS
Version: Audacity 3.1.0 latest alpha audacity-win-3.1.0-alpha-20211005+39b3048-64bit

**Additional context**
There is no value to the user in these appended temporal data,

Given that named clips is the major new feature in 3.10 it woulkd be good to get this as polished as possible

@Tantacrul this is a UX GUI design issue, it just looks **_janky_** ...

_This was previously discussed on Discord a while back_

**Comment by petersampsonaudacity** [comment]
The problem compounds each time you make a fresh Split New
![image](https://user-images.githubusercontent.com/50205984/136057114-62e3b82d-f136-4ed3-837b-0c3a4d6c1473.png)

...

![image](https://user-images.githubusercontent.com/50205984/136057366-78f956d2-2d99-47f4-8dab-bbe5d206fe98.png)

**Comment by vsverchinsky** [comment]
There are some changes requested in this issue #1698 and implemented by #1832, new proposed scheme does not use numbers in name patterns when clip is split.
