### ISSUE TITLE
[Clip Renaming] Double-clicking to rename a track should automatically mark the entire clip name

### ISSUE THREAD

**Issue by crsib** [audacity/audacity#1834]

**Comment by Penikov** [comment]
At the first double-click, it works well, but next double-clicks do nothing. 
So this task is done, I'll add a new bug:

https://user-images.githubusercontent.com/25851359/137305900-a31875f0-9ebc-4e91-8c32-3cc539b7aaf0.mp4


https://user-images.githubusercontent.com/25851359/137305904-bac599fb-7850-4e5b-8acd-a2a65d1f83d6.mp4
