### ISSUE TITLE
"Editing a clip can move other clips" defaults to "off"

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#1844]
**Describe the bug**
By default I should be able to generate audio or paste audio into a track without being told there isn't room

**To Reproduce**
1. Reset Audacity preferences
2. Observe that "Editing a clip can move other clips" is disabled.

**Expected behavior**
 I should be able to generate audio or paste audio into a track without being told there isn't room

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version 3.1.0-alpha-20211006

**Additional context**
This is a regression.

**Comment by LWinterberg** [comment]
This is intentional. It's very evident why the error message appears and thanks to cliphandles, it now also is very evident how to work around it. 

The old default did end up breaking sync between tracks when editing on multiple tracks. We found that behavior to be way more annoying and so flipped the default.

**Comment by SteveDaulton** [comment]
> The old default did end up breaking sync between tracks when editing on multiple tracks.

It was also the way that VI users bring tracks into alignment when editing on multiple tracks.



> and thanks to cliphandles, it now also is very evident how to work around it.

Not so evident if the track has many clips and the user is unfamiliar with moving multiple clips together. Rather than simply pasting a clip at an arbitrary position in the track, they may now have to zoom out, move multiple clips out of the way, paste into the gap, move the clips back to close up excess space. The workaround for me is obvious, I can just change the preference setting, but not everyone will know how to  do that.

**Comment by SteveDaulton** [comment]
> The old default did end up breaking sync between tracks when editing on multiple tracks.

How does disallowing pasting / generating into a track help with that issue? If the user needs to insert audio into a track, they need to insert audio into a track, and making that more difficult does not keep multiple tracks synchronized.

If the concern is that "deleting" audio from a track sync between tracks, then why not address that directly and make "Split Delete" the default delete action (and "modifier + delete" for "old style" delete)?
