### ISSUE TITLE
Floating Toolbars can block Audacity if it is the only Windows application.

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#1845]
**Describe the bug**
Audacity loses focus altogether if meter toolbars are floated and if Audacity is the only currently running Windows application.
This issues was reported on the Audacity forum here: https://forum.audacityteam.org/viewtopic.php?f=7&t=120638&sid=d44c3c0f53f7d72b46a138aa006520e2

Note that since the report is in French, you may benefit from the use of Google translate here: https://translate.google.com/

**To Reproduce**
1) Create a Windows desktop shortcut for Audacity.
2) Close all Windows. (Alt-Tab should do nothing).
3) Startup Audacity from the shortcut.
4) Tools > Reset Configuration
5) Resize Audacity window to occupy roughly the right two-thirds of screen.
6) Float both Microphone and Speaker Meter toolbars to Windows desktop outside of Audacity screen and change their configuration to vertical by dragging resize bar.
7) Close Audacity.
8) Startup Audacity from the shortcut.
9) Notice that Audacity menu is grayed out and there is no way to close Audacity.
10) Close Audacity from the Windows taskbar.
11) Note that steps 8 through 10 can be repeated.
12) Start Notepad (or any other application).
13) Note that Audacity now functions properly.

**Expected behavior**
The Audacity menu should not be grayed out.

**Screenshots**
See: https://forum.audacityteam.org/viewtopic.php?f=7&t=120638&sid=d44c3c0f53f7d72b46a138aa006520e2

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version: Audacity 3.0.4; Also fails on current alpha: Audacity 3.1.0-alpha-20211006 Commit Id: 12e21a

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
