### ISSUE TITLE
Make Stereo Track can result in a track with different  clipnames for each channel

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1850]
**Describe the bug**
The Make Stereo Track (from the TCP dropdown menu) can result in a track with different  clipn ames for each channel

**To Reproduce**
1. Import a stereo track
2. Split the stereo track
3. rename the clip of the bottom track
4. re-join the stereo track
5. Observe: the two channels of the stereo track now have different names

**Expected behavior**
This may be by design - and comes about by the design decision to have clip names per channel when making stereo tracks from two mono tracks - or a split left and right channel.

But I am posting this here for public discussion.

**Screenshots**
![image](https://user-images.githubusercontent.com/50205984/136351897-c258939e-e522-411b-8121-4256c1141396.png)

**Additional information (please complete the following information):**
 - OS: Windows 10 but assume all
 - Version Audacity 3.1.0 alpha

**Additional context**
This just looks most odd to me ...

Flagging this for @Tantacrul  as this is a UX GUI design issue

**Comment by LWinterberg** [comment]
this is going to get fixed with the stereo clip refactor and doesn't need a separate issue anymore
