### ISSUE TITLE
Smart Clips. A clip may collapse and become invisible if a user drags clip borders too much

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#1860]
**Describe the bug**
If the user works at sample-level scales, all goes well. The clip has borders and is still visible even when the 'virtual range' of a clip changed to one sample.

But when the user changes track length at a lower scale, clip borders tend to disappear. At some scales the clip becomes invisible.

![изображение](https://user-images.githubusercontent.com/25851359/136449462-3b1f57ca-4330-4756-b919-2ecf9442b28d.png)

![изображение](https://user-images.githubusercontent.com/25851359/136449539-a455cd30-0ec8-40da-be82-b3ca73990891.png)

How it works in dynamic:

https://user-images.githubusercontent.com/25851359/136450715-8257c138-fc23-4f5c-a132-eda320fab5fc.mp4

**Steps To Reproduce**

1. Make a clip
2. Set a track scale to any "ordinary" level. 
3. Pull any clip border to the opposite one until the clip becomes collapsed.

**Expected behaviour**

There is not a simple design issue, but I think the same behaviour is appropriate to Audacity:

https://user-images.githubusercontent.com/25851359/136452000-f6cab997-a29d-43b9-83c0-accb50879093.mp4

You see, the UI in the video has some bugs too, but this concept of the clip shrinking looks good to me.

 - Version Audacity 3.1.0-alpha-20211007

**Comment by Penikov** [comment]
@Tantacrul what do you think?

**Comment by Tantacrul** [comment]
Completely agree with expected behaviour.
