### ISSUE TITLE
Smart Clips. Clip shrinking doesn't work with the Zoom tool 

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#1861]
**Description**
A Clip shrinking works with all kinds of tools, except the Zoom tool. 

**Steps to reproduce**
Steps to reproduce the behaviour:
1. Make a clip
2. Switch to the zoom tool
3. Try to shrink the clip

**Expected behaviour**
Shrinking in the zoom tool mode works as well.

**Screenshots**

https://user-images.githubusercontent.com/25851359/136455107-32e09b93-83a9-422a-913a-22ed8edc6fc7.mp4

**Additional information:**
 - OS: Windows 10
 - Version: Audacity 3.1.0-alpha-20211007

**Comment by Paul-Licameli** [comment]
I consider this not-a-bug.

Zoom tool is not my least favorite button in the tools toolbar, but anyway when you are in it, none of the usual click-drag-release actions of the track panel work at all.  There is only zooming.  That’s how it is.

This is not a bug special to the new smart clips implementation.

**Comment by Penikov** [comment]
Sure. Technically this is not a bug. 
But I'm not sure this works as designed.
Anyway, we can remove this issue from the release scope. Because it is annoying a little, but not critical at all.
