### ISSUE TITLE
Audacity's volume slider should not control system volume

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#1866]
Because it can cause hearing damage to unsuspecting users: https://twitter.com/parallax_fifths/status/1446167466007142424

**Comment by crsib** [comment]
The point is that this behavior:

* Not expected by users.
* Is exclusive to Audacity.

**Comment by LWinterberg** [comment]
You know what's longer-standing than this behavior of the program? Ear damage. That stuff actually can be life-long.

Considering that every other volume slider in the world doesn't touch the system volume (not even VLC's weird one that goes to 125%), the fix is simple (as per crsib), and that it **_prevents bodily harm_**, I think we definitely should get it in ASAP.

**Comment by werame** [comment]
I for one am glad this got fixed/changed. It wasn't working consistently, by the way. With MME selected as output mode it was changing the system volume, but not when DirectSound or WASAPI were used, if I recall correctly.

**Comment by Nicholas-Steel** [comment]
I just checked it out in v1.3.1 and this seems to still be an issue. If I adjust the Microphone/Recording volume in Audacity it will adjust the Master Volume in the Windows Volume Mixer. So if I increase the recording volume than playback volume of every program on my PC will be increased.

I have Audacity set to record Windows WASAPI.

The first time this happened it scarred the shit out of me, no one would think increasing recording volume would doubly ffect playback in Audacity (recording volume is louder and playback volume is louder) nor would anyone expect it to affect playback volume of everything system wide.
