### ISSUE TITLE
The Timer Record TimeText controls do not interact intuitively with the Date controls.  

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1869]
**Describe the bug**
The Timer Record TimeText controls do not interact intuitively with the Date controls.  Users find the spinner data-entry for time values to be confusing and un-natural, causing incorrect entry values.

It is far too easy to mismange the tumbler settings as this Forum user did recently:
https://forum.audacityteam.org/viewtopic.php?f=46&t=120783&p=436727
Leading them to think that Timer record was not stopp ing at the allocated time - it was, nut the user had nudged the controls to get a much longer recording time than they had planned

**To Reproduce**
1. Use the tumbler settings in Timer Record
2. Observe: it is far too easy to mis-set them often by a day or so

**Expected behavior**
easy to use controls for Time Record,  improvements to the time data-entry spinbox controls:

- Simplified spinner controls for time entry with hh:mm only _(I doubt that anyone uses seconds except when testing)_.
- hh (and mm) to be a single field rather than separate digits of units and tens. Thus the up/down arrows would operate on hh (and mm) as an entity.
- No ripple-through interaction from the hours field to the date field.
- No ripple-through interaction from the minutes field to the hours field.
- The minutes field to be limited to its logical maximum of 59 minutes.
- The hours field to be limited to its logical maximum of 23 hours. 

 
**Screenshots**
None

**Additional information (please complete the following information):**
 - OS: all OS
 - Version: all Audacity including 3.1.0

**Additional context**
Flagged for @Tantacrul  as a UX/GUI issue

This occurred to me several times in the past sometimes causing me to miss a Timer Recording as the start time was accidentally incorrect.  This led me to write this up as a proposal in the Wiki 5 years ago:
https://wiki.audacityteam.org/wiki/Proposal_Improvements_to_the_Timer_Record_time_data-entry_spinbox_controls
I have now learned to check the box settings **_VERY_** carefully each time I use Timer Record.

In that proposal Gale wrote:
>There are at least two cases where the Start and End spinboxes interact unintuitively with Date:

- You cannot type a spinbox character that results in a time in the past; the input is ignored and the selected digit is advanced. In particular there is a clearly expressed expectation that setting hours to the past would advance the date forwards. 
- The hour spinbox increments the date perfectly in a forwards direction by typing or up arrow (even incrementing by a day and changing hours to "07" if you have 21 hours and increment the "2" to "3"). However incrementing hours backwards with down arrow does not move the date backwards when you reach "00" hours (even if the previous day would still be a time in the future); moreover a further down arrow from "00" hours zeroes all the digits.
- The above are not apparently bugs but arguably reasonable behaviour for TimeText controls as used in Selection Toolbar. Perhaps these are not good behaviours in a Timer and may suggest using another type of control integrated with the date. Or perhaps time controls should increment date backwards and a time in the past can be set, but it greys out OK.

**Comment by LWinterberg** [comment]
this is planned for much later (Audacity 4.x), closing for now
