### ISSUE TITLE
Classic Filters Crash when used in a Macro

### ISSUE THREAD

**Issue by ElijahHamilton** [audacity/audacity#1873]
Using Classic Filters in a Macro causes Audacity to crash.
No matter what you try, the only way to use Classic Filters is to apply it manually.

1. Add Classic Filters into a macro.
2. Restart Audacity
3. Apply the Macro.
4. Audacity crashes.

Audacity is expected to apply Classic Filters with parameters specified in the Macro. (without crashing)

Screenshot:
![Capture](https://user-images.githubusercontent.com/72035925/136601861-2a9e836b-690c-46f4-892b-9b2c75012fb3.PNG)

**Additional information (please complete the following information):**
 - OS: Windows 10.
 - Version: Audacity 3.0.4. Has affected versions 2.3 and up.
 - Sound device: Affects all drivers/devices.

Problem details:
[debug.txt](https://github.com/audacity/audacity/files/7313324/debug.txt)

**Comment by LWinterberg** [comment]
I can reproduce this on the current master

**Comment by LWinterberg** [comment]
This is a [known issue](https://github.com/audacity/audacity/wiki/Known-Issues). We are not looking to fix this bug. You may want to use a plugin instead.
