### ISSUE TITLE
Stable snap update reports as Alpha test version

### ISSUE THREAD

**Issue by jsamples062** [audacity/audacity#1875]
Audacity snap on Ubuntu 20.04.3 updated and now reports that I am running an Alpha test version. Either the build is not a stable or the version info is incorrect.  I reported this to the publisher diddlesnaps (aka diddledani) and they said it was an upstream issue.

I installed 3.0.2 as a snap a couple weeks ago and it recently updated to 3.0.5 alpha, even though I believe I am only tracking for stable.

At launch, this message now appears:
"The version of Audacity you are using is an Alpha test version."

Help | About reports this build info:
Audacity 3.0.5-alpha-20211007

The Build
```
Program build date:
Oct 7 2021
Commit Id:
e0431d of Tue Sep 28 18:24:00 2021 +0300
Build type:
CMake Release build (debug level 1), 64 bits
Compiler:
GCC 9.3.0 (Audacity)
Installation Prefix:
Settings folder:
/home/devel2/snap/audacity/920/.audacity-data
```

What should have happened?
Only stable release versions should be posted to stable channel.

Output of snap info audacity
```
devel2@ubuntu:~$ snap info audacity
name:      audacity
summary:   Audio software for multi-track recording and editing
publisher: Dani Llewellyn (diddledani)
store-url: https://snapcraft.io/audacity
contact:   https://github.com/diddlesnaps/audacity/issues
license:   unset
description: |
  Audacity® is a free, easy-to-use, multi-track audio editor and recorder for
  Windows, Mac OS X, GNU/Linux and other operating systems. The interface is
  translated into many languages.
  
  You can use Audacity to:
  * Record live audio
  * Convert tapes and records into digital recordings or CDs
  * Edit WAV, AIFF, FLAC, MP2, MP3 or Ogg Vorbis sound files
  * Cut, copy, splice or mix sounds together
  * Change the speed or pitch of a recording
  * Apply a wide range of other effects to audio recordings
  
  Upstream Project: https://www.audacityteam.org/
  snapcraft.yaml Build Definition:
  https://github.com/diddlesnaps/audacity/blob/master/snap/snapcraft.yaml
commands:
  - audacity
snap-id:      KTe2wdAu5JKdRDUgYBuXXGjDXyzobvFI
tracking:     latest/stable
refresh-date: today at 12:50 EDT
channels:
  latest/stable:    3.0.5 2021-10-08 (920) 194MB -
  latest/candidate: ↑                            
  latest/beta:      ↑                            
  latest/edge:      3.0.5 2021-10-07 (920) 194MB -
installed:          3.0.5            (920) 194MB -
devel2@ubuntu:~$
```
Output of snap connections audacity
```
devel2@ubuntu:~$ snap connections audacity
Interface               Plug                      Slot                              Notes
alsa                    audacity:alsa             :alsa                             manual
audio-playback          audacity:audio-playback   :audio-playback                   -
audio-record            audacity:audio-record     -                                 -
content[gtk-2-engines]  audacity:gtk-2-engines    gtk2-common-themes:gtk-2-engines  -
content[gtk-2-themes]   audacity:gtk-2-themes     gtk-common-themes:gtk-2-themes    -
content[icon-themes]    audacity:icon-themes      gtk-common-themes:icon-themes     -
content[sound-themes]   audacity:sound-themes     gtk-common-themes:sound-themes    -
desktop                 audacity:desktop          :desktop                          -
desktop-legacy          audacity:desktop-legacy   :desktop-legacy                   -
gsettings               audacity:gsettings        :gsettings                        -
home                    audacity:home             :home                             -
jack1                   audacity:jack1            -                                 -
network                 audacity:network          :network                          -
network-bind            audacity:network-bind     :network-bind                     -
pulseaudio              audacity:pulseaudio       :pulseaudio                       -
removable-media         audacity:removable-media  -                                 -
unity7                  audacity:unity7           :unity7                           -
wayland                 audacity:wayland          :wayland                          -
x11                     audacity:x11              :x11                              -
devel2@ubuntu:~$
```

Output of snap version
```
devel2@ubuntu:~$ snap version
snap    2.51.7
snapd   2.51.7
series  16
ubuntu  20.04
kernel  5.11.0-37-generic
devel2@ubuntu:~$
```

**Comment by LWinterberg** [comment]
diddlesnaps/audacity#33 cc @diddledani 

When I set `AUDACITY_BUILD_LEVEL` to `2` in CMake, it reports as a stable version for me: 
![image](https://user-images.githubusercontent.com/87814144/136647642-8cc5524f-4f5b-45e7-8d9f-ad0e3a7cd4a6.png)

Is this bug specific to 3.0.5? If so, be aware that 3.0.5 is a hotfix release for macOS only. You may want to continue packaging 3.0.4 instead.

**Comment by crsib** [comment]
This is a known issue for 3.0.3+. It will be fixed in 3.1.0

**Comment by crsib** [comment]
There is an issue with source code distribution. Currently BUILD_LEVEL is only set on CI which is unexpected to package maintainers. As 3.0.4 and 3.0.5 were hotfixes, the fix for this issue was not included.

**Comment by jsamples062** [comment]
From an end-user perspective, I would like to see the wrongly-reporting snap rolled back to one that does not show invalid version info.  E.g. 3.0.2 snap behaved correctly as far as I can tell.  It is very disconcerting for a supposedly stable/mature package to suddenly notify me it updated itself to an "alpha test version."  I don't want to work with alpha test versions.  And if it isn't really an alpha test version, then what else may be incorrectly built, who can say?

**Comment by SteveDaulton** [comment]
> From an end-user perspective, I would like to see the wrongly-reporting snap rolled back

That's an issue for the package manager (DiddleDani)

**Comment by jsamples062** [comment]
I posted the same rollback request to the package manager.  Still nothing has yet been fixed.  It seems to me this should be an urgent rollback as this blunder affects all Linux snap users of Audacity...

**Comment by SteveDaulton** [comment]
> I posted the same rollback request to the package manager. Still nothing has yet been fixed. It seems to me this should be an urgent rollback as this blunder affects all Linux snap users of Audacity...

The Snap package is not made by us, so we can't do anything about it.
Using this cmake configuration will produce a release build of Audacity 3.0.5:
`cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DAUDACITY_BUILD_LEVEL=2 -Daudacity_use_ffmpeg=loaded`
The critical switches are:
`-DCMAKE_BUILD_TYPE=Release`
`-DAUDACITY_BUILD_LEVEL=2`
