### ISSUE TITLE
Manual page for keyboard preferences needs more screenshots

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#1877]
See: https://manual.audacityteam.org/man/keyboard_preferences.html

Each of the three choices for the radio button changes the appearance of the listing.  The text describes it all well, but a picture of each would be more helpful.

**Comment by Paul-Licameli** [comment]
@petersampsonaudacity

**Comment by petersampsonaudacity** [comment]
> @petersampsonaudacity

@LWinterberg  ...
