### ISSUE TITLE
Sawtooth spectrum with subharmonics

### ISSUE THREAD

**Issue by jserquera** [audacity/audacity#1880]
Why I only get a correct spectrum of a sawtooth signal with 256 Size? With larger sizes of the spectrum menu I get subharmonics in the graph.

**Comment by rbdannenberg** [comment]
Is it a band-limited sawtooth or a "perfect" sawtooth that has been sampled? The latter will have significant aliasing, which could show up as subharmonics or inharmonics. Also, windowing introduces modulation - a short-time FT with windowing is not a depiction of the FT of an infinite signal. At the root of all this is the fact that while an infinite periodic function has pure harmonics (and only exact harmonics), a windowed periodic function is no longer periodic -- it has a beginning and an end -- and thus the signal is neither periodic nor composed of harmonics.

**Comment by SteveDaulton** [comment]
> It is the sawtooth that Audacity generates.

That's just a simple "straight line" triangle, and as Roger wrote, it has significant aliasing.
This Nyquist plug-in will give you a nice looking triangle wave with virtually no aliasing: https://wiki.audacityteam.org/wiki/Nyquist_Generate_Plugins#HQ-Tone
