### ISSUE TITLE
Clip Names. The Cursor editing mode doesn't off with a click in toollbars

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#1896]
**Describe the bug**
The Cursor editing mode doesn't off with a single click on toolbars or scrollbars.

**To Reproduce**
Steps to reproduce:

1. Create two or more tracks
2. Add a clip to the first one (on top)
3. Start edit clip name in direct mode (double click on clip handle, make sure option 'Use dialog for the name of a new label' is disabled.
4. Click in any toolbar

**Actual behaviour:**
Observe: clip name edit cursor is still visible

**Expected behaviour**
The edit cursor should be dismissed after time selection changed/activated

**Screenshots**
These red rectangles point to the areas where clicking doesn't off the clip name editing mode.
![изображение](https://user-images.githubusercontent.com/25851359/136423104-8a9b3fe0-df2f-43a0-b968-8d88594707d3.png)

Relates to: #1858

**Comment by petersampsonaudacity** [comment]
Confirmed on W10 with master audacity-win-3.1.0-alpha-20211012+0cf12fb-64bit

**Comment by Paul-Licameli** [comment]
I don't understand what the latest video is demonstrating.  Describe the steps.  Where is the last mouse click, which should cause the editing cursor to disappear, but does not?
