### ISSUE TITLE
Play position cursor can be virtally invisible against track spectrogram

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#1897]
**Describe the bug**
The cursor gets lost in the black background, especially on audio that has silence sections.

**To Reproduce**
1. Generate a chirp
2. Switch to track spectrogram view
3. Click somewhere near the middle of the track
4. Observe that the play position cursor is barely visible

**Expected behavior**
To be able to see the play position cursor reasonably easily.

**Screenshots**

![cursor](https://user-images.githubusercontent.com/11681097/136961039-4efd4089-460c-426d-85c6-7577c3cb588b.png)

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04 (originally [reported on Windows](https://forum.audacityteam.org/viewtopic.php?p=436914#p436914))
 - Version 3.0.5 and 3.1.0

**Additional context**
Perhaps a 2 px thick cursor with contrasting colours, as in the lower image.

**Comment by LWinterberg** [comment]
We'll change the point selection to more of a playhead looking thing, which will alleviate this issue. That will be tracked as part of a different task however.

![image](https://user-images.githubusercontent.com/87814144/209995747-b4d01e09-38e7-42dd-84fc-033c6b652e92.png)
