### ISSUE TITLE
New Loop button does NOT control looping

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1899]
**Describe the bug**
The new Loop button does NOT control looping, rather it toggles locking and unlocking of the play region, this duplication the actions of the  pre-existing commands:  Transport > Play Region >Lock\Unlock

This contravenes what is clearly stated in the Figma spec where it says
>The user can click on the playback loop button to turn looping on or off
The button is just a toggle button and doesn't start playback

**To Reproduce**
1. Launch 3.1.0 alpha main audacity-win-3.1.0-alpha-20211012+f6c0305-64bit
2. Observe that it fails to control looping by toggling looping on/off
3. Observe: what it actually does is to toggle the lock/unlock state of a Timeline play regiom

**Expected behavior**
a) What it says in the spec - toggle the ability to loop on or off
b) when off the normal single play obtains
c) when on the play button changes to a loop button and loped play obtains when that is pressed
d) when toggled off again the Play button reverts to its normal green triangle

**Screenshots**
Snapshot from Figma spec
![image](https://user-images.githubusercontent.com/50205984/136998615-ad279c94-180f-47e4-8b44-73836601a243.png)

**Additional information (please complete the following information):**
 - OS: Windows 10 - but assume all OS
 - Version: 3.1.0 alpha main audacity-win-3.1.0-alpha-20211012+f6c0305-64bit

**Additional context**
Reaper provides a good example of this working as the Audacity spec indicates

**Comment by Paul-Licameli** [comment]
Commit f6c0305 is not what you should test.  Instead, try this draft pull request.
https://github.com/audacity/audacity/pull/1868

**Comment by petersampsonaudacity** [comment]
Tested this again today with @Paul-Licameli 's latest branch build:  audacity-win-3.1.0-alpha-20211012+8196af6-64bit

The behavior had changed with this build with the loop button appearing to work a a control for on/off of looping - and no longer a lock/unlock toggle for locking/unlocking the play region

Accordingly I shall close this issue.
