### ISSUE TITLE
Resizing length of clips can create invisible, zero length clips

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#1901]
**Describe the bug**
Zero length clips needs to be considered a bug as they can cause unfathomable problems for users.

**To Reproduce**
1. Generate a 30 second tone
2. Drag the left edge of the clip to the right until the clip disappears
3. Click anywhere on the track
4. Now try to find the clip - it is still there, but invisible.

**Expected behavior**
Audio clips should never become invisible.

**Screenshots**
A track containing 4 audio clips:
![First Track000](https://user-images.githubusercontent.com/11681097/137007779-0c2c1a17-9c81-4649-acb2-88421f2d004c.png)

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version: 3.1.0-alpha-20211012

**Comment by vsverchinsky** [comment]
Duplicate issue #1860
