### ISSUE TITLE
Crash when exporting loud audio as MP3

### ISSUE THREAD

**Issue by GameParrot** [audacity/audacity#1905]
**Describe the bug**
When you make a recording and apply Bass and Treble with Volume at 30.0 dB like 20 times, Audacity crashes when you try to export it.
**To Reproduce**
1. Record audio
2. Go to the effects menu
3. Click in "Bass and Treble"
4. Set volume to 30.0 and Bass and treble should be at 0.0
5. Click "Apply" 20 times and close the Bass and Treble window
6. Export the audio as MP3
7. Audacity crashes

**Expected behavior**
the audio should export

**Additional information (please complete the following information):**
 - OS: macOS Big Sur 11.6
 - Version : Audacity 3.0.5

**Additional context**
The command line output when the crash occurs is "Failed to start handler: No such file or directory" or "INTERNAL ERROR IN VBR NEW CODE (1313), please send bug report"

**Comment by petersampsonaudacity** [comment]
Exporting this extremely amplified project as a 16-bit PCM WAV file works fine though FWIW ...
