### ISSUE TITLE
Playback Volume Slider. Adjusting playback volume slider causes "analogue" noises

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#1911]
**Describe the bug**
When a user is adjusting the playback volume slider, it causes little retro-noise in both channels
![изображение](https://user-images.githubusercontent.com/25851359/137122127-446835fd-5017-4e6c-9a1a-f6a036ecf5d0.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Import an audio
2. Run playback 
3. Adjust the playback volume slider quickly from 0 to 100
4. Listen to quiet ticks while the slider is moving.

Note 1: Ticks don't appear when silence is replaying.
Note 2: Ticks appear only when the playback is running.
Note 3: Seems like ticks correspond somehow with the scale of the slider

**Expected behaviour**
The playback slider is moving silently

**Screenshots**

https://user-images.githubusercontent.com/25851359/137124289-dd6bf57e-b90c-4b71-8624-9b381a1ffe9a.mp4

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version: Audacity 3.1.0-alpha-20211012

**Comment by LWinterberg** [comment]
This happens with all volume sliders as suddenly decreasing the volume is identical to what a crackle would do. The solution would be to have some sort smoothed/fading "actual" slider which slowly (0.1s-ish?) slides towards the user-set slider to prevent the crackling. 

Considering the same happens in browsers and stuff, I think this is more of a P4 and not really necessary for 3.1

**Comment by Penikov** [comment]
@LWinterberg Right, this is an old problem, and not necessary to fix it in the current sprint. 
But I've added this to the actual sprint because Dmitry was about to check this after the release. So this is sort of reminder to me )
