### ISSUE TITLE
Smart Clips. Sticky clip edges when a clip is shrinking

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#1918]
**Describe the bug**
This is not the bug actually, but it might be useful for a lot of users.
Audacity already has the same behaviour at clips: When you try to move a clip along the track it sticks exactly at the same point as the border of another clip from this or another channel of the track:

https://user-images.githubusercontent.com/25851359/137143356-0e206911-e686-41cd-84e5-3096892517b7.mp4

But if you try to shrink the clip on one channel up to the clip border on another channel, there are no sticky edges appeared:

https://user-images.githubusercontent.com/25851359/137144711-41ae5fbc-c7f1-4928-90e1-47ff27f5ba1c.mp4

**To Reproduce**
Steps to reproduce the behaviour:
1. Add some stereo clips
2. Split the track
3. Move clips to make them asynchronous
4. (upd. step) Make stereo 
5. Try to shink clips 

**Expected behaviour**
Clip borders (edges) behaves the same way as moving clips

**Additional information (please complete the following information):**
 - OS: All
 - Version: 3.1 alpha

**Comment by AnitaBats** [comment]
@Penikov please test if already fixed
