### ISSUE TITLE
Cut Preview. A Looping region affects to a cut preview

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#1923]
**Describe the bug**
When a user uses cut preview with a track selection, all works well. But if the user set up the playback looping region once, the cut preview starts ignoring track selection and starts working only with the playback looping region. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a clip
2. Make a selection of the wave track.
3. Hold the Ctrl key and click the Play button
All goes well)
4. Select any other range on the track, run the playback looping then stop it.
5. Make another selection on the wave track 
6. Hold the Ctrl key and click the Play button Again

**Expected behaviour**
The Cut Preview works only with a wave track selection  OR
The Cut Preview works only with A playback looping selection OR
The Cut preview works both with a wave tack selection and with a playback looping selection AND 
can prioritize any kind of selection (for instance, if we add new preferences, a user would choose what to utilize - a playback looping selection or a wave track selection)

**Actual behavior**
Playback skips the selected looped region

**Screenshots**

https://user-images.githubusercontent.com/25851359/137321491-575104f1-b174-4688-bf58-05c6bb35268a.mp4

**Additional information (please complete the following information):**
 - OS: any
 - Version: Audacity 3.1.0-alpha-20211013

**Comment by LWinterberg** [comment]
Cut preview is on its way out, this won't get fixed
