### ISSUE TITLE
Play defaults to loop play 

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#1928]
**Describe the bug**
In the 3.1.0 EXE version Play defaults to loop play

**To Reproduce**
1. Install 3.1.0 EXE: https://github.com/audacity/audacity/actions/runs/1342278423
2. reset to factort settungs - ckear audacity settings folder
3. launch 3.1.0
4. get some audio
5. make a short selection
6. Press Play
7. Observe: the selection is loop played
8. Press Stop
9. Shift+Play
10. Observe: the selection gets a single play

**Expected behavior**
Unmodified playback with the loop button off should just plat a selection the once.

**Screenshots**
None
**Additional information (please complete the following information):**
 - OS: Windows 10 - but assume all
 - Version: 3.1.0 EXE: https://github.com/audacity/audacity/actions/runs/1342278423

**Additional context**
This a regression on all former Audacities

**Comment by petersampsonaudacity** [comment]
This is still the case with the 3.0.2 master:  audacity-win-3.2.0-alpha-20211014+19a5cf5-64bit

And the latest 3.1.0 Beta:  audacity-win-3.1.0-alpha-20211014+0ee7c1b-64bit Beta-1

**Comment by Paul-Licameli** [comment]
Old model in Audacity is that once-only play is the default, but loop enabled play is the unusual case that you start with a modifier key.

New model is that once only play is the unusual case instead.

But the default case isnt supposed to be looping play always — but rather it is looping play if also a loop region is enabled.

That is my corrected understanding of design intent now, but I may have mistaken the intent in this implementation.  @Tantacrul

**Comment by petersampsonaudacity** [comment]
> I implemented it so that the loop region, when first enabled, default to the selection but only if it has no zero length; otherwise it defaults to the first four seconds. Very arbitrarily, yes I agree, but that was in a version of the spec. Maybe we revise that. @Tantacrul

I am struggling to understand just why it is thought necessary to create a default loiop region when the user just presses the Loop button to turn looping on.

Surely the workflow should be:
1.  user presses Loop button
2. Observe: button is down - implies looping is available and the order of the day
3. user makes a loop range selection 
4. User presses Play button
5. Observe: loop play commences
6. User Presses Loop button to deactivate looping
7. Observe: Play continues in once-only mode from where the Play cursor happens to be in the loop
8. Importantly the loop range should not be just invisible it should be discarded.
