### ISSUE TITLE
Misleading fr translation, about saving empty project

### ISSUE THREAD

**Issue by jpcima** [audacity/audacity#1929]
On saving an empty project, the text of the message box in french is incorrect.

It tells the user that "The project is *not* empty", as opposed to "now empty", which is nonsense.

https://github.com/audacity/audacity/blob/19a5cf59674f3579791f6eeab7e8fe36180b7ca9/locale/fr.po#L4650

ping @trebmuh, in case you'd like to have a look.

**Comment by trebmuh** [comment]
Thanks for the ping @jpcima .

**Comment by jpcima** [comment]
No problem, by the way:
```
"Annuler, Édition > Annuler, jusqu’à ce que toutes les pistes\n"
"soient ouverte, puis Fichier > Sauvegarder le projet.\n"
```

that should be "ouvertes", plural

**Comment by trebmuh** [comment]
Fixed too. Thanks.
