### ISSUE TITLE
Missed localisation for [Main menu]-[Help]-[Check for Updates]

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#1932]
**Is your feature request related to a problem? Please describe.**
There are clear and fine translations for [Preferences]-[Application]-[Update notifications], but [Main menu]-[Help]-[Check for updates] still unlocalized. 

**Describe the solution you'd like**
Localize the [Main menu]-[Help]-[Check for updates] dialog

**Additional context**
![изображение](https://user-images.githubusercontent.com/25851359/137450736-5f2da3a1-12d6-4e10-a715-b1f43a38cb93.png)

**Comment by LWinterberg** [comment]
is this fixed?
