### ISSUE TITLE
3.1 beta does not compile

### ISSUE THREAD

**Issue by monochromec** [audacity/audacity#1937]
Compilation breaks on Ubuntu 20.10 with the following error:

- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/home/xxx/.conan/data/portaudio/19.7.0/_/_/build/d840b1f7fa55383480ff217b65d4e070c094723b/sources/JACK_INCLUDE_DIR
   used as include directory in directory /home/christoph/.conan/data/portaudio/19.7.0/_/_/build/d840b1f7fa55383480ff217b65d4e070c094723b/sources
JACK_LIBRARY (ADVANCED)
    linked by target "portaudio" in directory /home/xxx/.conan/data/portaudio/19.7.0/_/_/build/d840b1f7fa55383480ff217b65d4e070c094723b/sources

-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_NO_PACKAGE_REGISTRY
    CMAKE_INSTALL_BINDIR
    CMAKE_INSTALL_DATAROOTDIR
    CMAKE_INSTALL_INCLUDEDIR
    CMAKE_INSTALL_LIBDIR
    CMAKE_INSTALL_LIBEXECDIR
    CMAKE_INSTALL_OLDINCLUDEDIR
    CMAKE_INSTALL_SBINDIR

CMake Generate step failed.  Build files cannot be regenerated correctly.
portaudio/19.7.0: 
portaudio/19.7.0: ERROR: Package 'd840b1f7fa55383480ff217b65d4e070c094723b' build failed
portaudio/19.7.0: WARN: Build folder /home/xxx/.conan/data/portaudio/19.7.0/_/_/build/d840b1f7fa55383480ff217b65d4e070c094723b
ERROR: portaudio/19.7.0: Error in build() method, line 122
	cmake = self._cmake_configure()
while calling '_cmake_configure', line 116
	cmake.configure(build_folder=self._build_folder)

**Steps to reproduce**
- Clone git repo
- Configure build per README.md

**Expected behavior**
Compilation breaks with above error message

**Additional information (please complete the following information):**
 - OS: Ubuntu 20.10 (impish)
 - Audacity 3.1 beta

**Comment by crsib** [comment]
This would be rather dangerous, as the jack server must match the jack client. I think that a proper fix will be to provide an option to disable Jack.

**Comment by crsib** [comment]
In case Jack2 is not present we will disable Jack support
