### ISSUE TITLE
Smart Clips. Rounded clip handles turn to angular

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#1939]
**Describe the bug**

![изображение](https://user-images.githubusercontent.com/25851359/137505750-7fcd5dc6-f654-4eb5-a420-de344bdc12ea.png)

**Expected behaviour**

![изображение](https://user-images.githubusercontent.com/25851359/137505966-4ce97d80-8370-4f90-91e6-dad8897a7d0b.png)

**Additional information (please complete the following information):**
 - OS: Ubuntu Studio 21.4
 - Version: 3.1 beta
 - KDE, qt

Also, there are angular buttons on Windows 10:
![изображение](https://user-images.githubusercontent.com/25851359/137506710-d812618d-deec-444f-848d-9687a839885b.png)

**Comment by vsverchinsky** [comment]
It seems like we can't do much about clip frame corners, because that's how wxDC behaves on different platforms.
