### ISSUE TITLE
3.1.0 beta 1: Make new Clip-name adjustable/toggle-able

### ISSUE THREAD

**Issue by deus-e-x** [audacity/audacity#1945]
Audacity 3.1.0 beta 1 introduces a new track label _(Moderator note: it's a Clip-name not a track name_), located on top of each track and spanning the entire track (see screenshot below, red marker). This new label visually disconnects the audio data from the time bar which makes it difficult to make exact selections, because there is no visible selection indicator on the time bar anymore.

![screenshot](https://user-images.githubusercontent.com/45689656/137566663-332d51af-2686-4e80-a8c0-0295a473c0a0.png)

**Describe the solution you'd like**
Please add (optional) vertical lines representing the start/end of the audio selection, that visually connect the selected audio with the time bar.

**Describe alternatives you've considered**
1. Add an option to change the position of the new track label to alternatively have it displayed on the bottom of the track, so that the audio selection visually connects with the time bar, as was the case in earlier releases of Audacity, like v3.0.4.

2. Add an option to turn the new track label off.

**Comment by petersampsonaudacity** [comment]
With 3.1.x and new looping the Timeline behavior has changed so with the new settable Loop region the Play region is no longer shown in the Timeline.  In the older Audacities 3.0.5 and earlier the Play region in the Timeline was the same as the selction.
![image](https://user-images.githubusercontent.com/50205984/144090381-51fab0f6-241d-4cf9-8a20-4e9e09838d7f.png)


And even if the user locked the Play region, then a selected region in the waveform (or label track) would have a visual cue in the Timeline:

**Comment by petersampsonaudacity** [comment]
This may seem trivial in the single track use cases I posted above - but consider the multi-track use-case where ther is now no Timeline indicator of a selection.
![image](https://user-images.githubusercontent.com/50205984/144091442-107d7722-4538-442d-af83-3abb4cf89418.png)

Flagged for @Tantacrul as a UX issue

**Comment by deus-e-x** [comment]
Release v3.1.3: "Added a new selection region indicator in the timeline (identical in function as the one found pre-3.1, but with updated visuals)​"

Hello Audacity team, thank you very much for adding the new selection indicator. I'm loving it! ❤️
