### ISSUE TITLE
Playhead / Cursor does not appear in the timeline when I press 'play' (Mac OS Catalina)

### ISSUE THREAD

**Issue by Tantacrul** [audacity/audacity#1968]
See video:
https://www.dropbox.com/s/knhymdsxm40o4j8/Cannot_See_Play_Cursor.mov?dl=0

For some reason, for the last two weeks or so, the timeline does not appear on builds of Audacity 3.1 on my mac (Catalina: 10.15.4)

However, if I run an older version of Audacity on 3.0.2, I **_do_** see the playhead.

I'm wondering if there is something unique to my settings that has caused this. Regardless, the problem is very significant and we will need to make sure it isn't happening on other Macs. I note that this issue is not happening on @Paul-Licameli's Mac, which is interesting.

**Comment by crsib** [comment]
Hmm, not even by my fix? Can you please provide more details on it @Paul-Licameli @Tantacrul ?
