### ISSUE TITLE
Built-In Declipper

### ISSUE THREAD

**Issue by ElijahHamilton** [audacity/audacity#1975]
**Is your feature request related to a problem? Please describe.**
The Nyquist declipper often crashes when I attempt to declip a 5+ min track.

**Describe the solution you'd like**
Would it be possible to implement a better declipper?
If possible, it would be preferred to be implemented in c/c++, or as a built-in effect.

**Describe alternatives you've considered**
The only alternatives I have considered are SA Perfect Declipper, but it costs money to use.

**Additional context**
None.

**Comment by Penikov** [comment]
@ElijahHamilton Could you tell, please, what Audacity version do you use?

**Comment by SteveDaulton** [comment]
> If Audacity is crashing when applying ClipFix to 5 mins audio, then that's a bug that needs to be fixed, but I can't reproduce that problem.

I've also tested with Audacity 3.1.0-alpha-20211019 on Xubuntu 20.04. A 40 minute selection, stereo, 44100 Hz sample rate, completed successfully, though it took several minutes on an i7 laptop, and used over 400 MB of RAM (ClipFix processes the audio one channel at a time in RAM).
