### ISSUE TITLE
Playback Looping: Very short loops overwhelm the system

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#2000]
**Describe the bug**
When using playback looping on very short timescales (eg 5 samples), the system gets overwhelmed in the following ways: 
* Audacity freezes for several seconds when initiating playback
* Once playback occurs, it produces a high pitched sound (this is expected), but after another second or so, the sound shifts into something more dirty (square-wave-y)
* When you click stop, Audacity enters a weird state in which the play button stays in the "on" state and the stop button twitches for a while, until it finally enters the stopped state
* (Pause works as expected)

**To Reproduce**
1. Have a very short loop
2. hit play
3. observe
4. hit stop
5. observe

**Expected behavior**
Audacity shouldn't freeze, and the loop should produce a constant sound.

**Additional information (please complete the following information):**

* OS: Windows 11
* Version latest release-3.1.0 (115f463)

**Comment by petersampsonaudacity** [comment]
Fails on W10 with the edge case of a single sample loop and up up to 5 samples or so

But it works fine on W10 with 10 samples for the loop - however if while the loop is playing you contract the loop region to a single sample or less it goes doolally - technical term ;-) 

1) generate a 1 second chirp
2) set cursor to mid point 
3) zoom in to sample level
4) select 10 samples
5) Set loop to selection
6) turn looping on
7) Press Play
8) Observe it works fine
9) while it is looping contract the loop region in the timeline
10) Observe that at about 5 samples it stops playing
11) contract the loop region some more
12) Observe: as the loop region gets minimally small the playback goes doolally
13) zoom to fit selection
14) Observe: the selection remains but the loop region has disappeared

**Comment by petersampsonaudacity** [comment]
Note too that if you have a real-life loop that you are adjusting you can drag the right loop edge to the left of the left edge and vice versa (expected behavior)

But if you line up the left and right  edges of a loop region so that they coincide then the loop region disappears altogether.  
a) Is this intended, designed, behavior?
b) is it desired behavior?
