### ISSUE TITLE
Incorrect error message in Spectral Multi-Tool

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2004]
**Describe the bug**
The "Spectral Multi-Tool" may return an incorrect error message

**To Reproduce**
1. Make a spectral selection from less than 10 Hz (but more than 0  Hz), up to the top of the spectral display.
2. Apply "Spectral Multi-Tool"
3. Note that when the lower frequency is set and the upper frequency is not set, the "Spectral Multi-Tool" acts as a low-pass filter.
4. Observe the error message:
```
Error.
Notch filter parameters cannot be applied.
Try increasing the low frequency bound
or reduce the filter 'Width'.
```

**Expected behavior**
The error message should not refer to "Notch filter" and the "width" is meaningless for a low-pass filter.

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version Audacity 3.0.2

**Additional context**
The "steps to reproduce" are difficult to perform due to https://github.com/audacity/audacity/issues/1921

**Comment by vivekKr24** [comment]
I would like to work on this issue.
Please guide me through.

**Comment by LWinterberg** [comment]
@vivekKr24 My guess would be that you need to change this line:

https://github.com/audacity/audacity/blob/95a7fc6362729594565204b6db927b2e025d20c0/plug-ins/SpectralEditMulti.ny#L53

Feel free to ask on audacityteam.org/devserver if you have more questions
