### ISSUE TITLE
Crash on paste after running batch macro

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2021]
**Describe the bug**
When there is audio on the Audacity clipboard, attempting to paste after running a batch processing macro causes Audacity to crash.

**To Reproduce**
1. Copy some audio to the clipboard
2. Clear all tracks from the project
3. Run a macro on one or more files (example, "MP3 Conversion") and wait for the batch to complete.
4. "Edit menu > Paste"
5. Observe crash

**Expected behavior**
The copied audio to be pasted.

**Screenshots**

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04 / first reported with Windows 10.
 - Version: Confirmed with Audacity 3.0.2 / 3.0.3 / 3.0.5 / 3.1.0

**Additional context**
The original report on the forum was due to a user attempting to use a macro that they were previously using (successfully) in Audacity 2.4.2, in which they would copy audio to the clipboard, then use a macro to append the audio to multiple files:
```
SelectAll:
Normalize:ApplyGain="1" PeakLevel="-0.1" RemoveDcOffset="1" StereoIndependent="0"
CursTrackEnd:
Paste:
ExportMp3:
```
While this did not crash, the macro failed to append the audio from the clipboard. The user has reverted  to Audacity 2.4.2.

**Comment by crsib** [comment]
Oh wow, it's one of the most common crashes in Audacity! Thank you for STR, @SteveDaulton!

**Comment by crsib** [comment]
Another way:

1. Run Export MP3 on a larger file
2. Cancel
3. Repeat 1

**Comment by crsib** [comment]
Optionally, apply the macro to a few files. If the macro succeeds on the first file and fails on any later - Audacity crashes

**Comment by crsib** [comment]
1. Generate sound
2. Copy to clipboard
3. Remove track
4. Use macro on file
5. Paste
6. Undo
7. Use macro on file

Audacity crashes

**Comment by crsib** [comment]
As for the original issue with Paste not working for the user - the behavior was disabled by @Paul-Licameli: https://github.com/crsib/audacity/commit/105558c7bf07e4bb4f26b222a01a6c17a9e2ef61 while fixing https://bugzilla.audacityteam.org/show_bug.cgi?id=2567

Do we want to restore it?

**Comment by SteveDaulton** [comment]
It's a useful feature (as demonstrated by the fact that this bug came to light). I don't think that useful features should be removed unless they are replaced by a superior alternative.

**Comment by crsib** [comment]
I have split this issue in two. The issue reported on the forum has now moved to https://github.com/audacity/audacity/issues/2254
