### ISSUE TITLE
Welcome screen. Disappeared string on the dark theme

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2024]
**Describe the bug**
<img width="609" alt="Screenshot 2021-10-26 at 18 24 36" src="https://user-images.githubusercontent.com/25851359/138911268-39ff1b68-a30f-4f7e-b00d-fe5913134049.png">

<img width="647" alt="Screenshot 2021-10-26 at 18 25 30" src="https://user-images.githubusercontent.com/25851359/138911609-61676c8a-74e2-48d7-8994-d5e621ee6815.png">

**To Reproduce**
1. Apply the dark theme
2. re-launch Audacity

**Additional information (please complete the following information):**
 - OS: Mac OS Big Sur
 - Version: Audacity 3.1.

**Comment by kathenas** [comment]
I would propose that this issue be reconsidered for fixing sooner than later or not at all.

**Comment by LWinterberg** [comment]
Why? You can disable it in **Preferences > Interface > Show "how to get help" at launch** if it bothers you right now, and we're moving to a new UI system anyway which probably won't even have this dialog in the first place.
