### ISSUE TITLE
Make commands / shortcuts for selecting audio clips easier to find

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2028]
**Is your feature request related to a problem? Please describe.**
I was looking for the keyboard shortcuts to select audio  clips. 
1. The commands ("Alt + ." and "Alt + ," - select the next  clip in the selected track) are hidden away in "Selection menu > Clip boundaries", which seems highly non-obvious.
2. The commands ("Tab" and "Shift + Tab" - move selection to the next clip boundary in the focused track) are nowhere to be found (not even in the [Keyboard Shortcut Reference](https://manual.audacityteam.org/man/keyboard_shortcut_reference.html))

**Describe the solution you'd like**
- [x] Rename "Clip boundaries" sub-menu -> "Audio Clips"
- [x] Document "Tab" and "Shift + Tab" in the keyboard reference

**Additional context**
https://github.com/audacity/audacity/issues/1997

**Comment by LWinterberg** [comment]
What's the difference between Tab/Shift+Tab vs Alt+./Alt+,? They look identical to me
