### ISSUE TITLE
AppImage: mod-script-pipe non-functional

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2042]
**Describe the bug**
mod-script-pipe fails to create or connect to pipes in /tmp

**To Reproduce**
1. Ensure that mod-script-pipe is enabled in Preferences and restart if necessary
2. Attempt to use mod-script-pipe
3. Observe that it is non-functional

**Expected behavior**
mod-script-pipe to work when enabled.

**Screenshots**

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version Audacity 3.1.0

**Additional context**

**Comment by j4cobgarby** [comment]
Yes I'm getting this issue too, here's what the `pipe_test.py` script says:

```
$ python pipe_test.py 
pipe-test.py, running on linux or mac
Write to  "/tmp/audacity_script_pipe.to.1000"
 ..does not exist.  Ensure Audacity is running with mod-script-pipe.
```

**Comment by T-vK** [comment]
I'm having a very similar issue with the AppImage. For me the modules don't even show under `Preferences: Modules`, so I can't even enable `mod-script-pipe` to begin with. Am I missing something?
