### ISSUE TITLE
Adjusting clips UI difficulties and seems to conflict with changing the selection region (linux/Ubuntu)

### ISSUE THREAD

**Issue by stmueller** [audacity/audacity#2052]
**Describe the bug**
I am using aud 3.1 on linux via the appimage. It is possible that this is a platform-specific thing, since I have not seen it reported elsewhere.

There are several issues with adjusting the edges of clips.  
* The cursor often does not change when hovering over one or the other edge of a clip so adjusting the clip cannot be done at all.
* Ability to adjust the clip sometimes appears to depend on whether the clip is selected or 'activated' by clicking on the label, but it is not clear whether that selection does anything other than reset the selection region to the exact region of the clip.
* Without any clicking, hovering over the edge of a clip region sometimes does nothing, sometimes is the region selection, and sometimes is the clip resizer.
* Frequently, the selection gets adjusted instead of the clip.
* There is no visual indication that you have extended the clip to its maximum size in either direction, so a drag of the clip region appears to do nothing. This wouldn't be so bad if there were so many other cases in which it didn't work, but there could be a different color edge indicating the clip is being clipped.

**Screencast**
A 90-second screencast of me fumbling around to show each of these is here:

https://youtu.be/Xn7OGPoWSzA

**Additional information (please complete the following information):**
 - OS: ubuntu 21.4
 -  Version audacity 3.1 from linux appimage
 -

**Comment by stmueller** [comment]
Note that the clip resizing seems to work reliably when I hover over the edge of the clip label rather than the wave data area.

**Comment by LWinterberg** [comment]
> Note that the clip resizing seems to work reliably when I hover over the edge of the clip label rather than the wave data area. It seems like it might be the top 20% of the wavetrack extending below the label even.

Yes, this is intentional: The top 30% or so of the clip are used to trim it, the bottom part is used to select audio (so you can do things like select from the beginning of the clip, without accidentally resizing every time.

Note that the cursor for selecting a region is -> or <-, but the cursor for trimming clips always is <->. That said, we definitely should come up with some better cursors so it's easier to understand which cursor causes which action.

**Comment by Tantacrul** [comment]
Agreed the similarities of the cursors on linux is a problem. I also think we might be wise to consider an on-hover UI prompt to show where the draggable area is.

Also agreed that it would be ideal to show the full extent of a clip (probably as you are dragging, or when you have the clip selected) to show the full extent of the wave data that has been trimmed. We'll pay some attention to this with our next set of functional improvements to clips.

**Comment by stmueller** [comment]
If this is intentional, it is not discoverable  because you need to hover over a magic region with no visual indication of where the hotzone is.  Note that I was not confused about the shape of the cursors.  In this design decision, adjusting a single side of the selection region is prioritized over adjusting the smart clip boundary--if both sides of the region are going to change a user will just select the new region.  I don't have a good sense for how often will someone need to change only one side of the selection region when it is matching the smart clip region. Maybe it is frequent, but maybe it is almost never.
