### ISSUE TITLE
Shrinking clip size to 0 width makes clip unable to reexpand

### ISSUE THREAD

**Issue by stmueller** [audacity/audacity#2053]
**Describe the bug**
If you adjust the clip region to size 0 by either moving the left bound to the right of right or the right bound to the left of left, the clip becomes a single pixel wide and cannot be expanded again, and so must be deleted. It can still be moved.  I was able to resize when I zoomed into the max zoom level and the edges were only slightly apart, but this would not be something most people would think of. This could also be addressed by adding a context-menu option to resize the clip to full size when right-clicking, or making a size-0 clip have 2 pixels--one for each edge.

**To Reproduce**

1. create a clip.
2. Resize to size 0
3. Clip become unadjustable (unless you zoom in to max level)

 - OS: Ubuntu 
 -  Version 3.1 using appimage from website

**Comment by stmueller** [comment]
If clip starts at 0, resizing the right boundary to match the left also disappears the entire clip. I assume it is still there but I cannot see it or move it (or hear it on playback).

**Comment by AnitaBats** [comment]
@Penikov please test on the later versions, and add details if needed

**Comment by Penikov** [comment]
This is the behaviour that @stmueller have reported:

https://user-images.githubusercontent.com/25851359/143003225-6229ee69-ef5b-4109-9c13-ac0aacb2d7a0.mp4

When the clip is trimmed to a single-sample wide, it is very hard to expand it even at the largest scale.

**Comment by Penikov** [comment]
I think it happens because the cursor focuses on the opposite clip edge from time to time.

**Comment by Penikov** [comment]
Also, if you point the cursor precisely like this:
You will always get the right side of a clip.

![изображение](https://user-images.githubusercontent.com/25851359/143015499-db9a1417-0e3b-4ad3-8376-ad7955c066da.png)

**Comment by petersampsonaudacity** [comment]
Testing on W10 with 3.1.2 and 3.1.3

Even when shrunk down to a single pixel loop region (an oddity in itself) I can grab the line in the Timeline and expand the loop region left or right - at normal zoom, zoom to fit (3 min song) or max zoom in.

What I can't do is move the single point clip region

**Comment by LWinterberg** [comment]
We'll be introducing new hit targets to resize clips in the near future (probably 3.3) at which point this should stop being an issue.
![image](https://user-images.githubusercontent.com/87814144/172702415-0ab5f1af-23c0-48e2-8614-2ef495f46f71.png)

**Comment by petersampsonaudacity** [comment]
@LWinterberg 

This behavior still persists - and as @stmueller pointed out that his workaround "would not be something most people would think of".

So this begs the question as to just why this issue has been closed (as "not planned") without a fix being applied?

**Comment by SteveDaulton** [comment]
> We'll be introducing new hit targets to resize clips in the near future (probably 3.3) at which point this should stop being an issue.  **Closed on Jun 8, 2022**
Over a year later ...
Maybe better to wait until a bug has been fixed and tested before closing.
