### ISSUE TITLE
Audacity does not start on kubuntu with Korean language

### ISSUE THREAD

**Issue by tmvkrpxl0** [audacity/audacity#2057]
**Describe the bug**
Audacity does not start on Kubuntu

**To Reproduce**
1. Boot up Kubuntu 21.10
2. Download Audacity 3.10

**Expected behavior**
It should start like it did with Ubuntu a few months ago.

**Additional information (please complete the following information):**
 - OS: Kubuntu 21.10
 - Audacity 3.10

**Additional context**
It does show up splash image, but that's all, the splash image disappears after few seconds
This is the log I got from running it on terminal: https://www.toptal.com/developers/hastebin/gefujidota.coffeescript
This just halts, no additional log is printed

**Comment by crsib** [comment]
I could not reproduce this issue in Kubuntu 21.10 and Ubuntu 21.04 with the official AppImage for 3.1.2. Can you please provide more details?

**Comment by tmvkrpxl0** [comment]
Hello, sorry for late reply, I have re-tested it with 3.1.2, but I still wasn't able to run the App Image
There was nothing special on what I did, I just downloaded 3.1.2 App image on Audacity web page and ran on terminal it after setting permission using `chmod +x`
Since I ran Audacity on terminal I was able to see logs, and here they are: https://www.toptal.com/developers/hastebin/efeheqacuf.coffeescript
All of symptoms it shows are still same, it shows splash image for about 2 seconds and it disappears, but Audacity process is still alive, and I can kill it with CTRL+C on terminal

Actually there are some things I tried before and they may be causing issue, I had this issue a long time ago, and tried to build audacity from source, and I downloaded python-conan and other dependencies, maybe these are causing conflicts?
I'm still on Kubuntu 21.10 and Audacity is 3.1.2
KDE Plasma is 5.22.5, and I use NVIDIA 470 driver. I use X11

**Comment by tmvkrpxl0** [comment]
I forgot to mention that I use AppImage Launcher, I've tried it again without it and it was same

**Comment by tmvkrpxl0** [comment]
bump

**Comment by tmvkrpxl0** [comment]
bump2

**Comment by LWinterberg** [comment]
I could not reproduce this either on KDE Plasma is 5.22.5, NVIDIA 470 and X11. 

> Actually there are some things I tried before and they may be causing issue, I had this issue a long time ago, and tried to build audacity from source, and I downloaded python-conan and other dependencies, maybe these are causing conflicts?

It shouldn't but it might be worth a shot: Can you try using a clean Kubuntu live image and running the appimage from within that?

**Comment by tmvkrpxl0** [comment]
> I could not reproduce this either on KDE Plasma is 5.22.5, NVIDIA 470 and X11.
> 
> > Actually there are some things I tried before and they may be causing issue, I had this issue a long time ago, and tried to build audacity from source, and I downloaded python-conan and other dependencies, maybe these are causing conflicts?
> 
> It shouldn't but it might be worth a shot: Can you try using a clean Kubuntu live image and running the appimage from within that?

So I just did that, downloaded Kubuntu 21.10 iso and ran Audacity 3.1.3
and I observed exact same behavior, just splash screen for 2 seconds and audacity process freezing entirely
This is log I got from virtual machine:
https://www.toptal.com/developers/hastebin/ayejigegob.coffeescript

**Comment by tmvkrpxl0** [comment]
It's bit strange.. it should run on Virtualbox, is there problem with my hardware?
I should note that I recently downloaded cuda from NVIDIA on host machine and now I have nvidia driver 510

**Comment by tmvkrpxl0** [comment]
bump

**Comment by tmvkrpxl0** [comment]
My hardware info, in case if it's necessary
[hardinfo_report.zip](https://github.com/audacity/audacity/files/7923802/hardinfo_report.zip)
It's zip file containing html document

**Comment by LWinterberg** [comment]
I wonder - it's definitely not your hardware, else it'd be working in the VM. It's also definitely not kubuntu alone, else it'd not be working for us either. 

Is it your language setting? What happens if you try running it on the VM with the OS language set to English?

**Comment by tmvkrpxl0** [comment]
It seems to be running on VM with English, it still runs when I change it back to Korean.
It launches with English settings, both before and after changing language to Korean

**Comment by Penikov** [comment]
Can confirm. Audacity hangs at the startup if the system language is Korean.
But the bug reproduces only with 21.10. On Kubuntu 20.04 Audacity launches as usual.

**Comment by tmvkrpxl0** [comment]
Well, it's good that this issue can be reproduced

**Comment by Penikov** [comment]
Also, this is the Kubuntu-21.10 specific file. 
In Ubuntu 21.10 with Korean as system language Audacity runs well:

![image](https://user-images.githubusercontent.com/25851359/150974022-570f10e8-57fb-456b-b4a2-00033b89d691.png)

**Comment by Penikov** [comment]
I believe there are no issues with Audacity on Kubuntu 21.10, but there is an issue with Kubuntu 21.10 itself so I would like to assign the distro-bug label.

**Comment by tmvkrpxl0** [comment]
I want to run Audacity with English as temporary solution. How do I do so?

**Comment by tmvkrpxl0** [comment]
> > I want to run Audacity with English as temporary solution. How do I do so?
> 
> The solution works on my computer. I run the audacity appimage with env `LANG=C` prefix and I see the lovely window in the end. The whole command is like: `LANG=C ./audacity-linux-3.1.3-x86_64.AppImage`

Thanks!

**Comment by LWinterberg** [comment]
Does this still happen with the 3.2.1 appimage?

**Comment by tmvkrpxl0** [comment]
@LWinterberg 
Yes it does

**Comment by imxys** [comment]
> Does this still happen with the 3.2.1 appimage?

I upgraded my Ubuntu to 22.04 last month, and I'm using cinnamon instead of KDE now (btw I don't know why KDE shows black screen after login on 22.04) .
The 3.2.1 appimage runs well on my computer.
