### ISSUE TITLE
Only 1 channel x6 on 5.1 bugg?

### ISSUE THREAD

**Issue by starinspace** [audacity/audacity#2062]
**Describe the bug**
When Open a ac3 with 6 channels (5.1) it does open left, left, left, left, left, left with is wrong. Same with e-ac3-files as well. Stereo ac3 works and opens as it should.

**To Reproduce**
1. Drag a 5.1 ac3-file to open.

**Expected behavior**
Every channels, left, right, center, bas, surround left, surround right to open.

**Screenshots**
<img src="https://i.ibb.co/zXG9m14/Sk-rmklipp.png" />

**Additional information (please complete the following information):**
 - Windows 10 (latest to date)
 - Audacity 3.1.0

**Comment by crsib** [comment]
This issue is already fixed, the release is planned to be very soon! Stay tuned!

**Comment by starinspace** [comment]
> 
> 
> This issue is already fixed, the release is planned to be very soon! Stay tuned!

Oh, how great. :)
