### ISSUE TITLE
Ctrl+X doesn't use smart clips

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#2075]
Instead, it destructively cuts the clip

**To Reproduce**
1. Have some audio
2. select part of it
3. ctrl+x
4. paste onto a new track

**Expected behavior**
You can use smart clip capabilities to reveal the clip

**Screenshots**

**Additional information (please complete the following information):**
 - OS: Windows 11
 - Version 3.1

**Comment by LWinterberg** [comment]
Specifically, the following interaction: 
1. put a selection cursor in the middle of a clip
2. split clip (ctrl+i)
3. move the new clip (probably the right-side part of it) where you need it
4. un-trim the clip a bit

should also be achieved using
1. select part of the clip
2. ctrl+x
3. paste where you need it
4. un-trim the clip a bit

This was not part of the original spec (sample selections don't cause smart clips), but considering ctrl+x is **the** major shortcut for this, maybe it should be. 

I suppose this is something to discuss for a time when we get to make proper clips a thing though.

**Comment by DavidBailes** [comment]
> I suppose this is something to discuss for a time when we get to make proper clips a thing though.

But users have to deal with the current implementation, which is not documented, and is not intuitive.
Depending precisely how they create a new clip they may or may not be able to un-trim it in the future. So they create a clip assuming that it can be un-trimmed in the future, and then find out later that it can't.
Another example is if you select a region in a clip, then then execute either split or split new. The first case results in a middle clip which you can un-trim, the second case not.
