### ISSUE TITLE
Copying sample ranges from inside a clip causes the copy to not use smart clips

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#2076]
Instead, it only copies the sample range

**To Reproduce**

* Have some audio
* select part of it in the middle
* ctrl+c
* paste onto a new track

**Expected behavior**
You can use smart clip capabilities to reveal the clip; just like you could if you had used ctrl+c on an entire clip or ctrl+i instead.

**Additional information** (please complete the following information):

* OS: Windows 11
* Version 3.1

**Comment by vsverchinsky** [comment]
As per design:
![image](https://user-images.githubusercontent.com/20165230/139923118-927bf5b6-5404-46d8-9cf6-f2faa4f86832.png)
