### ISSUE TITLE
Tab/Shift +Tab in label track does not ensure that the selected label is visible

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#2078]
**Describe the bug**
Tab/Shift +Tab in label track does not ensure that the selected label is visible.

**To Reproduce**
1. Create a label.
2. Using Zoom and horizontal scrolling, arrange for the label not to be visible. For example if you've created a label at say about two seconds. press Home, and then press Ctrl+1 until the label goes off the right hand side of the window.
3. Press Tab to select the next label
4. The tracks are not scrolled horizontally so that the label is visible.

**Expected behavior**
Tab/Shift +Tab in label track should ensure that the selected label is visible

**Additional information (please complete the following information):**
- Windows 10
- Audacity 3.1.0

**Additional context**
Reported on the forum:
https://forum.audacityteam.org/viewtopic.php?f=70&t=121197#p438043

**Comment by LWinterberg** [comment]
This also is true for clips

**Comment by petersampsonaudacity** [comment]
I tested @DavidBailes '  branch build for this on W10:  audacity-win-3.2.0-alpha-20220107+82c9d83-64bit - David Bailes 2078 fix

This now works fine on W10 - at Step 4 the track is scrolled so that the label is visible - either a point label or the beginning of a range label.

**Comment by petersampsonaudacity** [comment]
Tested on W10 with audacity-win-3.2.0-alpha-20220111+f133869-64bit

I confirm this now works properly on Windows
