### ISSUE TITLE
Cannot edit labels without switching to mouse for each label

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2079]
**Describe the bug**
Previously I could quickly edit (add text to) a large number of labels by tabbing  from one to the next, typing the text, Enter to close the label, then tab to the next. In Audacity 3.1.0  on Xubuntu it is now necessary to mouse click in the label to open it for editing.

**To Reproduce**
1. Use "Regular Interval labels" to generate 100 labels
2. Add or modify the text in each label
3. Observe that it is now takes longer, and is less convenient (impossible for user that can't use a pointing device)

**Expected behavior**
Avoidance of regressions.

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version Audacity 3.1.0

**Additional context**
https://github.com/audacity/audacity/issues/2078
https://github.com/audacity/audacity/issues/1997
https://forum.audacityteam.org/viewtopic.php?f=70&t=121197

**Comment by LWinterberg** [comment]
This is xfce-only, correct?

**Comment by SteveDaulton** [comment]
> This is xfce-only, correct?

Apparently not. Here's a Windows 10 user complaining about this bug: https://forum.audacityteam.org/viewtopic.php?p=444252#p444252

**Comment by werame** [comment]
I can confirm with 3.1.3 on Win10 that tab switches to the next label, but it's not in edit mode anymore. There's no default key bindig to go back in edit mode. After pressing tab while editing the 1st label it looks like this.

![image](https://user-images.githubusercontent.com/97036286/151064341-29f3fd1a-a2d5-4eb4-a595-e7fafa3eb4ed.png)

Also, in the "Edit Labels..." spreadsheet tab moves right, not down, although Enter does move down. So using the spreadsheet mode is a workaround.

**Comment by SteveDaulton** [comment]
> Oh, I discovered the "hidden", i.e. hardcoded shortcut Ctrl+F2 to edit directly from the labels track.

"Ctrl + F1 ... to F9" are the XFCE shortcuts for switching workplace 1-9.
https://defkey.com/xfce-shortcuts

**Comment by SteveDaulton** [comment]
2 years later and this bug is still being reported by Audacity users. https://forum.audacityteam.org/t/tab-no-longer-goes-to-the-right-spot/84974/1

**Comment by LWinterberg** [comment]
Audacity 4 has new accessibility options, including for labels
