### ISSUE TITLE
Smart Clips. Clip Names. A Clip name goes out of the field of view when a clip is partially placed beyond the screen.

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2080]
**Describe the bug**
Audacity can show a clip name even when a clip is partially moved beyond the screen
![изображение](https://user-images.githubusercontent.com/25851359/140052347-f65cbb94-b476-4ff2-a3b7-c336b9e13a87.png)

![изображение](https://user-images.githubusercontent.com/25851359/140052389-722e11d1-ea23-4ffe-a4e4-8fcefdc90920.png)

But if you try to edit the clip name, it will run out of the field of view:

![изображение](https://user-images.githubusercontent.com/25851359/140052516-bb85b4f7-1476-42e7-8203-7586c8c86d1d.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a clip
2. Move the clip to the left along the track so that the clip is partially placed abroad the screen.
3. Try to edit the clip name

**Expected behaviour**
A clip name stays visible in editing mode

**Additional information (please complete the following information):**
 - OS: All
 - Version: 3.1 +

**Comment by dozzzzer** [comment]
Not reproducible anymore
