### ISSUE TITLE
Fix dependency cycles in prototype realtime effects implementation

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#2085]
Leland Lucius left us a prototype implementation of stackable realtime effects, with a very good implementation of per-project and per-track stacks, with persistency of effect choices and settings.

The branch introduced undesirable dependency cycles, involving WaveTrack.cpp and others, which would interfere with library extraction efforts.

Adapt this branch to avoid cycles, and merge some parts of it into master.

**Comment by crsib** [comment]
I think this one should be closed; it doesn't look relevant anymore.
