### ISSUE TITLE
Unable to load tracks from YouTube

### ISSUE THREAD

**Issue by ramlaxman** [audacity/audacity#2093]
**Describe the bug**
Unable to load YouTube which consists of several mp3 as a single file

**To Reproduce**
1. After loading MP3, it gives pop while processing "Looks like malformed mp3"

**Expected behavior**
MP3 file should load without any error.

**Screenshots**

**Additional information (please complete the following information):**
 - OS:  Windows 10
 - Version: Audacity 3.0.0

**Additional context**

**Comment by ramlaxman** [comment]
I've tried it with y2mate.com. I'll try with another converter and let you know soon.

**Comment by LWinterberg** [comment]
Does it work if you use a different YouTube downloader?
