### ISSUE TITLE
Play cut preview plays a preview of the loop region rather than a selection

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2104]
**Describe the bug**
Play cut preview plays a preview of the loop region rather than a selection.

This really makes **_no_** sense as the **_whole point_** of Play Cut Preview is to audition what the sound is like when you are about to delete a selected section of your audio.   

Delete does not work _(and is not intended to work)_ on a loop region in the Timeline.

**To Reproduce**
1. generate a 30 second chirp
2. select 5-10 seconds
3. Play cut preview
4. Observe: plays preview of selection, 3-5 secs followed by 10-11 secs
5. make a loop region selection in the Timeline form 15-20 seconds
6. Play cut preview
7. Observe: plays preview of before and after loop-play region and not the selection – I,e 13-15 secs followed by 20-21 secs
8. clear the loop region (but leave looping turned on)
9. Play cut preview
10. Observe nothing happens - no preview of cut selection

If after step 10 you then turn looping off, then play cut preview
works on the selection.

**Expected behavior**
Play cut preview should _**always**_ work on the selection and _**never**_ on a loop region.

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS: Windows 10 - but assume all OS
 - Version: 3.1.0

**Additional context**
This is very confusing behavior for the user.

I have not set a P rating _(as @Paul-Licameli has asked me to no longer do this)_ - but I would rate this as a P2

**Comment by AnitaBats** [comment]
probably related to #1923

**Comment by petersampsonaudacity** [comment]
Still the case on W10 with latest 3.2.0 release build

**Comment by LWinterberg** [comment]
Cut preview is on its way out, this won't get fixed
