### ISSUE TITLE
Theme Does not work anymore.

### ISSUE THREAD

**Issue by starinspace** [audacity/audacity#2105]
**Describe the bug**
The theme does not show up at all.

**To Reproduce**
1. I created a folder called "Theme" in %appdata%\audacity
2. In the Theme folder I put the file "ImageCache.png" (I did also try out 8 different themes) and it did not work when changing to Custom in Preference. (It did work in older Audacity)

**Expected behavior**
To work.

**Additional information (please complete the following information):**
 - OS: [Windows 10, latest 64-bit]
 - Version [Audacity 3.1.0]

**Additinal question**
Also, where Is the new feature "loop" in the png located?

**Comment by starinspace** [comment]
I just found this was made before me. I did search but didn't see it. Sorry for double.

https://github.com/audacity/audacity/issues/2043

**Comment by LWinterberg** [comment]
thanks for the report anyway!
