### ISSUE TITLE
Making Up Selection Error

### ISSUE THREAD

**Issue by borfirbora** [audacity/audacity#2108]
# Making Up Selection Error

## Error Description

On my keyboard using a field using your shots, if I don't choose it from the 'Create' menu, I will sometimes get it as time. I am forced to disappear.

## eats error

1. Stream any audio you have and predict with `Enter` important.
2. your keyboard help play visit next to `Space` and it's right where it should be ahead.
3. By means of `Shift+Right Arrow` an area of about half a second is opened.
4. By emphasizing `compose` overall Tone, you will not be entering the realm that will and will happen at the time the tone is created. This situation `problematically affects the whole in the generating system in a comprehensive way.`

## My System Configuration

- Operating System: Windows 10, 20H2 (19042.1288)
- Audacity Version: Audacity 3.1.0

**Comment by AnitaBats** [comment]
@borfirbora could you please add a video of what's going wrong? That would really helps us understand the problem!
