### ISSUE TITLE
audacityteam.org blocks Chinese IPs

### ISSUE THREAD

**Issue by TurnOffNOD** [audacity/audacity#2109]
**Describe the bug**
When I visit audacity's website www.audacityteam.org, I will get an error page and can't see the webpages.

**Screenshots**
The screenshot is here
![2021-11-10_232703](https://user-images.githubusercontent.com/2140029/141141822-73662b78-1a8b-4f40-b7a7-56d6fd85262f.PNG)

So, what's the problem with the website?

**Comment by SteveDaulton** [comment]
https://www.audacityteam.org/ is working  fine for me. Do you still see the problem?
This site is also showing no problems: https://downforeveryoneorjustme.com

**Comment by TurnOffNOD** [comment]
> 
> 
> https://www.audacityteam.org/ is working fine for me. Do you still see the problem? This site is also showing no problems: https://downforeveryoneorjustme.com

The latter website downforeveryoneorjustme.com shows no problems to me too. When I access this site, it shows a checking webpage from "DDos Protection By Cloudflare", after a few seconds, it will go into normal website.

But the website audacityteam.org is still showing "Error 1020". And it also says "Performance & Security by Cloudflare".

**Comment by LWinterberg** [comment]
Seems like you're running into our firewall for some reason. I'll ask our network admin what's up with that.

**Comment by Penikov** [comment]
Please check your IP address in services of spam dadabases. I have been the same problem with my IP on a few websites. This happens because internet providers have added there your IP for some reason.

**Comment by lhy7889678** [comment]
Some additional information: it seems that all IPs in China (at least the ones I have tried) have been blacklisted, whatever the location and Internet provider. Maybe this is a little bit extra...

The website has been inaccessible for at least several months. However, previously (maybe years ago), it used to work fine.

Now the only way to access the Audacity site here is to use a VPN. Ironically, VPN is a usual way to conduct DDoS attack, but now I have to use it to bypass the attack prevention system...

**Comment by Penikov** [comment]
@lhy7889678 Does it shoes you some kind of webpage or just kicks you silently?

**Comment by lhy7889678** [comment]
It shows "Error 1020" and "Access Denied" along with some extra information, just like what happened to the OP.

Here is a screenshot:
![图片](https://user-images.githubusercontent.com/66711810/142364820-22842822-2a3d-4acc-8fa2-c9dbc98bc3b6.png)

**Comment by LWinterberg** [comment]
Using https://web-tester.appinchina.co/ and https://www.dotcom-tools.com/china-firewall-test, I can confirm that all Chinese IPs appear to be blocked.

**Comment by Penikov** [comment]
> 
> 
> It shows "Error 1020" and "Access Denied" along with some extra information, just like what happened to the OP.
> 
> Here is a screenshot: 

Sorry, I have missed you've posted it already.

**Comment by Tantacrul** [comment]
Yikes. We've notified the right admins to fix this. Hopefully it will be resolved very soon.

**Comment by LWinterberg** [comment]
A little bit of an update: We are not actively blacklisting China right now. However, there are some blacklists for known spam IPs, which likely include the data centers used in my earlier comment. 

@TurnOffNOD @lhy7889678 Is this still happening for you? If yes, can you try to get some of your Chinese friends (preferably, far away ones) to check whether the site is blocked for them, too?

**Comment by lhy7889678** [comment]
(Sorry for the late reply. Our semester ended and I just went back home.)
Yes, the issue persists. Still Error 1020 from _every_ test:

- Mudanjiang (China Unicom & China Telecom)
- Beijing (China Unicom & CMCC & CERNET)
- Shanghai (China Telecom)

**Comment by TurnOffNOD** [comment]
> A little bit of an update: We are not actively blacklisting China right now. However, there are some blacklists for known spam IPs, which likely include the data centers used in my earlier comment.
> 
> @TurnOffNOD @lhy7889678 Is this still happening for you? If yes, can you try to get some of your Chinese friends (preferably, far away ones) to check whether the site is blocked for them, too?

Sorry for my very late reply. I was busy with my examination.

The problem still exists, Error 1020 is still happening.

I tested in Beijing (China Unicom home broadband and mobile network) and Tangshan(Hebei province, I tested in China Unicom home broadband and CMCC mobile network), all of them had no luck.

**Comment by ulivz** [comment]
Unfortunately, as a user for about 10 years, this issue still existed in 2022.

**Comment by SteveDaulton** [comment]
According to http://www.websitepulse.com/help/testtools.china-test.html the site https://www.audacityteam.org/ works fine from their test locations in Shanghai, Beijing, Guangzhou, and Hong Kong.

**Comment by LWinterberg** [comment]
@SteveDaulton Cloudflare's 1020 error is sending with a HTTP 200 OK. If you use a tool that produces screenshots (linked above), you can see it's still dead - and it definitely is dead for users as well. 
![image](https://user-images.githubusercontent.com/87814144/161953600-9bd2c7ce-60ce-467e-a401-080d2cf8d820.png)

**Comment by SteveDaulton** [comment]
> @SteveDaulton Cloudflare's 1020 error is sending with a HTTP 200 OK. If you use a tool that produces screenshots

That screenshot should be sufficient for the SysAdmin to locate the rule that is blocking, and to fix it should you wish to.

**Comment by LWinterberg** [comment]
can y'all try again?

**Comment by LWinterberg** [comment]
I'm assuming that no comment means it works again

**Comment by lhy7889678** [comment]
Yes, it works now. Thanks!
