### ISSUE TITLE
The timeline freezes if a user try to scroll the screen with arrow buttons

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2116]
**Describe the bug**
The timeline freezes if a user try to scroll the screen with arrow buttons

**To Reproduce**
1. Add a clip and adjust scaling to have a scrollbar

![изображение](https://user-images.githubusercontent.com/25851359/141356483-89918f5e-e192-4b7f-81e1-9bd24375ddeb.png)

2. Hold on the arrow button 

![изображение](https://user-images.githubusercontent.com/25851359/141356741-1ac9599e-e3e6-421e-af0e-13e65404385a.png)

3. See the timeline freezes while the button being holding.

**Expected behavior**

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version: Audacity 3.1

**Comment by dozzzzer** [comment]
Not reproducible as of 3.4.2
