### ISSUE TITLE
Data loss on joining clips

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2119]
**Describe the bug**
Joining clips in a track may cause data loss

**To Reproduce**
1. Generate 30 second chirp
2. Split at around 5 seconds
3. Split at around 20 seconds
4. Select across the second split (from around 18 to 22 seconds
5. Join the clips ("Ctrl + J")
6. Observe data loss in first clip.

**Expected behavior**
The selected split to join and no data loss

**Screenshots**

![First Track000](https://user-images.githubusercontent.com/11681097/141360530-1076abd9-895b-4e30-a687-8a825c15bd7a.png)

![First Track001](https://user-images.githubusercontent.com/11681097/141360583-42d05252-9c8b-4c5f-96d1-e1ce5986360e.png)

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04 and Windows 10
 - Version: Audacity 3.1.0 and 3.1.1

**Additional context**
Hot fix requested asap. On a large project the user may not notice the bug until it is too late to recover.

**Comment by Penikov** [comment]
Confirm.

But there is a workaround with splitting with double-click on clip borders

**Comment by DavidBailes** [comment]
> But there is a workaround with joining with double-click on clip borders

But not for keyboard users.

**Comment by vsverchinsky** [comment]
It's not lost but rather hidden behind the new clip... it's still a bug anyway

**Comment by Paul-Licameli** [comment]
> It's not lost but rather hidden behind the new clip... it's still a bug anyway

Hidden behind— overlapping?  Clips should never overlap.
