### ISSUE TITLE
Crash. 3.1.1 crashes on Mac

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2124]
**Describe the bug**
Audacity 3.1.1 crashes on Mac

**To Reproduce**
1. Run Audacity 3.1.1

**Additional information (please complete the following information):**
 - OS: Mac OS Monterey
 - Version:  Audacity 3.1.1

**Comment by JohnColket** [comment]
Note: this same project also crashes on Windows.

**Comment by AnitaBats** [comment]
@Penikov please add more info, logs

**Comment by JohnColket** [comment]
@AnitaBats please see: https://forum.audacityteam.org/viewtopic.php?f=47&t=121501#p439135
And let me know if there is anything else you need.

**Comment by petersampsonaudacity** [comment]
I get **_NO_** crash on macOS 12.0.1 Monterey when I launch or run it - I van play, record, import and edit ...

**Comment by Penikov** [comment]
The bug hasn't reproduced anymore. 
it is odd a bit... But Audacity runs normally now.
