### ISSUE TITLE
Audacity 3.1.1 will crash while opening projects containing very small double values

### ISSUE THREAD

**Issue by crsib** [audacity/audacity#2127]
**Describe the bug**
This issue was reported on the Audacity forum: https://forum.audacityteam.org/viewtopic.php?f=47&t=121501#p439135

Checking the provided AUP3 it was observed, that projects contain small double values (10^-17) and the formatter was asked to format them using only 10 digits after the decimal point.

This issue will be irrelevant after #2121 is merged, still, the bug in ToChars needs to be fixed

**To Reproduce**
Open the project from the forum

**Expected behavior**
Project is opened

**Comment by JohnColket** [comment]
I just wanted to report that this problem also happened to one of my own projects.  The symptoms are Audacity 3.1.1 simply disappears without a trace (no crash report) while attempting to open my project.  (Re-)starting Audacity 3.1.1 results in recovery process.  And of course, this process loops, each time adding an additional (null?) project to be recovered.

I was able to recover from this (nightmare) by loading my (damaged) project with Dmitry's Artifact here: https://github.com/audacity/audacity/actions/runs/1453936647 and then saving.  This fixed my project in all of about 5 seconds.  I was then able to run it in 3.1.1 with no issues.

I am making this report after being nudged by Peter to do so....

**Comment by JohnColket** [comment]
That will be a good thing - here is yet another forum post with the issue: https://forum.audacityteam.org/viewtopic.php?f=46&t=121597&p=439520#p439520

**Comment by JohnColket** [comment]
And another one here: https://forum.audacityteam.org/viewtopic.php?f=47&t=121501&start=10#p439475
