### ISSUE TITLE
Manuals are showing incorrect version

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2130]
**Describe the bug**
a)  the Manual for 3.1.1 shipped as part of the part of the download is showing as 3.1.0

b) The online Manual is showing as 3.1.0 - whereas the current release is 3.1.1

c) The alpha Manual is still showing as 3.1.0 - but 3.1.2 appears to be the current alpha build.

**To Reproduce**
1. Access the Manuals
2. Observe: wrong versions displayed on main page

**Expected behavior**
Correct versions displayed on Main page.

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS: Windows 10 - but assume all OS
 - Version: Audacity 3.1.1

**Additional context**
None

**Comment by petersampsonaudacity** [comment]
@LWinterberg  Leo, With the release of 3.1.2 this is still the case with the Manual distributed as part of the app and the online Manual still showing as 3.1.0.

It might be better if you just badged the Manual with a generic 3.1 designation _(to deal with maintenance releases like 3.1.1 and 3.1.2 etc.)_


The Alpha Manual is still showing as 3.1.0

**Comment by LWinterberg** [comment]
good call.
