### ISSUE TITLE
Project fails to open when clip handle contains multi-byte character

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2132]
**Describe the bug**
When a clip name contains a multi-byte character, the project cannot be opened

**To Reproduce**
1. Add an audio clip and name it 大
2. Save the project and quit
3. Try to open the project
4. Observe the error:

`{
    "timestamp": 1636894463,
    "event_id": "a95d4dd2ec54495d88f331960ec7827f",
    "platform": "native",
    "release": "audacity@3.2.0",
    "contexts": {
        "os": {
            "type": "os",
            "name": "Unix",
            "version": "5.11.0"
        }
    },
    "exception": {
        "values": [
            {
                "type": "Error_Opening_Project",
                "value": "Unable to parse project information.",
                "mechanism": {
                    "type": "runtime_error",
                    "handled": false,
                    "data": {
                        "log": "12:51:39: Audacity <path>-alpha-20211112\n12:51:39: sqlite3 message: (1) no such table: project in \"SELECT 1 FROM project LIMIT 1;\"\n12:54:09: sqlite3 message: (1) no such table: project in \"SELECT 1 FROM project LIMIT 1;\"\n12:54:23: ParseString error: Error: not well-formed (invalid token) at line 3\n===begin===(null)\n===end===\n12:54:23: DBConnection SetError\n\tErrorCode: 0\n\tLastError: Unable to parse project information.\n\tLibraryError: Error: not well-formed (invalid token) at line 3\n"
                    }
                }
            }
        ]
    }
}`

**Expected behavior**

**Screenshots**

**Additional information (please complete the following information):**
 - OS: [e.g. Mac High Sierra, Ubuntu 18.04, Windows 10]
 - Version [e.g. Audacity 2.5.1]
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]

**Additional context**

**Comment by Penikov** [comment]
@SteveDaulton Could you tell, please, what Audacity version has been crashing in your case?

**Comment by SteveDaulton** [comment]
> @SteveDaulton Could you tell, please, what Audacity version has been crashing in your case?

"platform": "native", "release": "audacity@3.2.0"
