### ISSUE TITLE
Zero length clips

### ISSUE THREAD

**Issue by vsverchinsky** [audacity/audacity#2139]
It's possible to make a zero-length sequence.

1. Create two mono tracks
2. Resample both tracks to sample rate 192kHz
3. Add a clip to the first track
4. Copy a single sample from the first track and paste it into the second track
5. Change sample rate of the second track to 44.1kHz
Observe: clip disappear

The same could be achieved using clip trimming: reduce the length of the clip to a single sample and then resample the track.

Expected behavior: ??? 

Additional context:
The issue is also reproducible in the older Audacity version (3.0.5), but with clip trims introduced it seems that it became quite easy (maybe unintentionally) to create zero-length clips during resampling. Taking into account that there are hidden data such clips will generate "garbage" in the project because they are copyable.

**Comment by SteveDaulton** [comment]
How are you changing the sample rate in step 5? I'm guessing that you mean "Resample to 44100" (rather than changing the sample rate from the track's context menu)?

**Comment by SteveDaulton** [comment]
Expected result from resampling one sample would be one sample.

**Comment by vsverchinsky** [comment]
> How are you changing the sample rate in step 5? I'm guessing that you mean "Resample to 44100" (rather than changing the sample rate from the track's context menu)?

I used a Tracks->Resample dialog. With track's context menu (menu->Rate->...) it will work as well.

**Comment by LWinterberg** [comment]
@vsverchinsky did you fix this with #2136?

**Comment by LWinterberg** [comment]
I have not seen this issue pop up in the last 2 years. I think we got some check for this somewhere these days.

**Comment by SteveDaulton** [comment]
I've tried following the "Steps to reproduce the behavior". Step 4 is not possible - nothing is pasted.
