### ISSUE TITLE
Play-at-Speed has reverted to being non-dynamic

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2149]
**Describe the bug**
The Play-at-Speed has reverted to being non-dynamic.  

@JamesCrook  upgraded this several releases back (2.3.0) so that it was dynamic - i.e. while PAS was playing moving the slider would cause the play sped to change while PAS was playing.

This is now broken in 3.1.0 and 3.1.1 - and is a regression on 3.0.5.

**To Reproduce**
1. Get some audio
2.  click the Play-at-Speed button
3. move the slider during PAS playback
4. Observe the speed of play does not change.

**Expected behavior**
Play speed for PAS to change dynamically.

On this page it the Manual it says it does:
https://manual.audacityteam.org/man/play_at_speed_toolbar.html
where it clearly states:
>Play-at-Speed playback can be adjusted dynamically with the slider with playback is in progress.

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS: Windows 10 - but assume all OS (@SteveDaulton tested on Linux and it fails there too)
 - Version: Audacity 3.1.0/3.1.1

**Additional context**
Assigned P1 due to the regression.

Originally reported by a user in this Forum post:
https://forum.audacityteam.org/viewtopic.php?f=46&t=121594&p=439466

**Comment by petersampsonaudacity** [comment]
I assume this is likely to have been caused by the playback changes made for the new looping in 3.1.0

**Comment by petersampsonaudacity** [comment]
Play-at-Speed loop play is also similarly non-dynamic

**Comment by DavidBailes** [comment]
Tested with Audacity 3.1.1 on Windows 10, preferences->Playback->"Vari-speed play" checked.

1. Click the play-at-speed button, then adjusting the speed slider has no immediate effect.
2. Shift+Click the play-at-speed button, then adjusting the slider has an immediate effect.

Using the commands on the Extra->Play-at-speed submenu:
1.  Play-at-speed, then adjusting the speed slider has no immediate effect.
2. Play-at-speed once, then adjusting the speed slider has an immediate effect.

Fixing the bug should include fixing the commands on the Extra->Play-at-speed submenu.

**Comment by LWinterberg** [comment]
Downgrading to P2 - has a workaround and doesn't corrupt projects

**Comment by Paul-Licameli** [comment]
The solution to this may be more difficult than I thought.  Can we reevaluate its priority for 3.1.3?  Can it wait for 3.2?  I think this is a less discoverable problem.

**Comment by petersampsonaudacity** [comment]
> I think this is a less discoverable problem.

In fact this was "discovered" and reported (complained about) by a Forum user) - but just the one complaint so far ...

**Comment by TheRealAyCe** [comment]
By me, I use play-at-speed a lot. :P

**Comment by crsib** [comment]
@Tantacrul @AnitaBats

**Comment by AnitaBats** [comment]
Will review on the standup

**Comment by Tantacrul** [comment]
Not nice but I don't think it should be a P1. I think we should target the fix for 3.2, assuming @Paul-Licameli does not discover a fast/simple fix.

**Comment by Paul-Licameli** [comment]
I'm fixing this issue so that you can move the slider, but also adust loop play bounds, and have all respond as expected.  It was not possible to do both things before.  So this will be not just a bug fix, but an enhancement.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with audacity-win-3.2.0-alpha-20211217+8340b56-64bit and the latest 3.1.3 build.

This now works fine on non-looped play with the slider once again acting dynamically.  So the bug as stated looks to be fixed OK


But with looped PAS it doesn't observe the bounds of the loop,  it usually does appear to play a loop but the loop range extends beyond the end of the loop.

Plus when I move the loop bounds wile PAS is active in loop mode then I get little clicks/ticks when I move either of the loop boundaries.

Also if I change the loop region wile PAS is active in loop mode it plays to then end of and slightly beyond the end of the project and does not loop at all.

**Comment by petersampsonaudacity** [comment]
Play-at-Speed plays more than the actual audio

1. Generate 30 second chirp
2. Press Play-at-Speed
3. Observe: Audacity plays the 30 second chirp and then an extra c. 7.5 seconds of silence beyond the chirp

![image](https://user-images.githubusercontent.com/50205984/146639145-89e66ef3-6f99-4548-baa5-7f0edd437c58.png)

**Comment by petersampsonaudacity** [comment]
1. generate a 30 second chirp
2. make a loop region from 10-15 seconds
3. Press Play-at-Speed
4. Observe: Audacity plays 10-15 seconds and continues playing to about 24 seconds
5. Observe: Audacity loops back to 10 seconds and plays to 15 seconds
6. Observe: Audacity "plays" from 15 to about 24 seconds, but plays silence on second and subsequent passes through the errant loop.

![image](https://user-images.githubusercontent.com/50205984/146639626-69d55ab0-b2f8-456f-be66-a93cce85164e.png)

**Comment by petersampsonaudacity** [comment]
I also find that after this, for both normal and looped PAS, I cannot use:
a) File>New, File>Open or File>Close (they are grayed-out)
b) nor can I delete the track using its top left "X".

**Comment by petersampsonaudacity** [comment]
Testing with @Paul-Licameli 's branch build  Audacity_Windows_64bit_1600640254_9e004a6 

The issues raised above all look to be fixed:
a) a full selection and only the selection gets played with PAS
b) the loop region is played properly with PAS
c) PAS is dynamic

There remains one little odd residual that I can see
1. Generate 30 second chirp
2. select from 10-15 seconds
3. press Play-at-Speed
4. Observe: after the selection plays the green play cursor remains and flickers (sometimes at the end but more often returns to the beginning of the selection)
5. Now move the PAS slider
6. Observe: the selection gets payed once more

This behavior is inconsistent with use of the normal Play button where the play cursor disappears once the playback of the selection is completed.

It looks like using Play-at-Speed leaves Audacity in play mode - as clicking on the Stop button causes the flickering play cursor to disappear.

**Comment by petersampsonaudacity** [comment]
Tested on W10 with latest 3.1.3 alpha build Audacity_Windows_64bit_1602134390_7887ba0

PAS is now dynamic - so this bug, as state, is fixed.

BUT we still have the residual I wrote about in my last comment in this thread.  I will log that as a new issue.

**Comment by petersampsonaudacity** [comment]
> we still have the residual I wrote about in my last comment in this thread. I will log that as a new issue.

Logged as:   Play-at -Speed with a selection gets stuck in Play mode #2316
