### ISSUE TITLE
Playback looping. Incorrect behaviour of the playhead at cycled playback.

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2153]
**Describe the bug**
In some cases, especially on trimmed clips, the playhead moves very odd.

**To Reproduce**
1.Add a clip (mono or stereo)
2. Put the narrow 'Looping region' after the clip:
3. Put the cursor in the end of the track as shown on the fig. below:
![изображение](https://user-images.githubusercontent.com/25851359/142142355-89818d28-0068-4e2f-b4e5-907a7e328e72.png)

 
3. Click the playback button
**Actual behaviour**
Audacity replays empty space. 

https://user-images.githubusercontent.com/25851359/142142825-940ae188-10b1-4524-a627-8d5c946f1d41.mp4

**Expected behavior**
That is a question )
My suggestion is Audacity should raise a warning that selection of the looping region is incorrect

**Additional information (please complete the following information):**
 - OS: Win 10
 - 3.1 +
 
 
 **Additional context**
 In case of normal playback Audacity works correct.

**Comment by dozzzzer** [comment]
The original issue isn't reproducible anymore as of 3.4.2: it won't play at all when trying to play in the case as on the video. There's a ticket for that issue:
https://github.com/audacity/audacity/issues/5783
