### ISSUE TITLE
Smart Clips. The function to synchronize left and right channels to avoid separated handles

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2154]
**Is your feature request related to a problem? Please describe.**
Currently there is an issue with additional clip handles on both channels if clips in channels are unsynchronized:
![изображение](https://user-images.githubusercontent.com/25851359/142178560-44afc6c5-bae4-41b2-b789-df9b1aeebdeb.png)

**Describe the solution you'd like**
![изображение](https://user-images.githubusercontent.com/25851359/142178475-ab3f9b8b-1be3-4aac-a23d-91630fa22b70.png)

**Comment by LWinterberg** [comment]
IMHO: There never should be an instance where you can have a stereo channel with non-synchronized content. It just causes chaos. This got recently reported on discord: 
![image](https://cdn.discordapp.com/attachments/874050504685133894/948537533581651968/Animation.gif)


related: #1966

**Comment by LWinterberg** [comment]
This has been fixed; stereo tracks now never are misaligned
