### ISSUE TITLE
Playback. Audacity can run playback behind zero

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2155]
**Describe the bug**
Audacity can run playback behind zero

**To Reproduce**
1. Generate 3-5 sec of tone.
2. drag the clip behind zero
3. Click the Play button

https://user-images.githubusercontent.com/25851359/145040886-0e1c701f-9061-401c-b944-68e5da43372d.mp4

**Expected behavior**
Playback shouldn't start behind zero

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version: Audacity 3.1.2+

**Additional context**

P2 because once it is reproduced, playback doesn't work correctly for this track. You need run playback on another track to get correct playback for your clip

**Comment by AnitaBats** [comment]
@Penikov  Pavel when this is happens exactly, what are the exact conditions? What's the frequency of occurrence?

**Comment by Penikov** [comment]
> @Penikov Pavel when this is happens exactly, what are the exact conditions? What's the frequency of occurrence?

I have updated the bug description.

**Comment by dozzzzer** [comment]
Not reproducible anymore as of 3.4.2
