### ISSUE TITLE
Playback Looping. Inconsistent behaviour of the looping toggle

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2156]
**Describe the bug**
If you set up a new looping region via a timeline, the looping button will be turned on.
But if you set a new looping region from a selection of the waveform, the looping button will be inactive.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a clip
2. Make a selection of the waveform
3. Point the cursor on the timeline, then click 'Set loop to selection' in the context menu
4. Observe the playback toggle still inactive

![изображение](https://user-images.githubusercontent.com/25851359/142253511-8dd313a9-c8c0-46b1-9dc9-0ebf56685fb5.png)

**Expected behaviour**
The playback looping button should be turned on automatically.

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version:  Audacity 3.1+

**Comment by dozzzzer** [comment]
The issue is no longer reproducible
