### ISSUE TITLE
Playback looping. Incorrect vizualization of the playhead

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2157]
**Describe the bug**
When an audio cursor is placed at the end of the project, the playhead moves incorrectly while the audio is replaying by the loop.

**To Reproduce**
1. Add a clip
2. Select the whole clip with double LMB on the clip handle
3. Click the looping toggle
![изображение](https://user-images.githubusercontent.com/25851359/142409147-33232f33-7339-4649-a458-c146136e7a4a.png)
4. Click the Skip to end button (it turns the audio cursor to the end of the track)
![изображение](https://user-images.githubusercontent.com/25851359/142409357-9f7166a6-4dd3-41c3-8f54-b26b7820c1d5.png)
5. Click the Play button

**Actual behaviour**

![изображение](https://user-images.githubusercontent.com/25851359/142409530-d52d6757-d3b5-4a74-8fd2-0644cad4f299.png)

**Expected behaviour**
The playhead moves as usual )

**Additional information (please complete the following information):**
 - OS: Win 10
 - Version: Audacity 3.1.2

**Additional context**

Please note that if you point the audio cursor at the middle of a clip and start looped playback then, the playhead will move correctly.

**Comment by LWinterberg** [comment]
cannot reproduce anymore
