### ISSUE TITLE
Moonphase: false error dialog re inaccessible configuration file

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2158]
**Describe the bug**
On launching Audacity 3.1.x I occasionally get an "Audacity Configuration Error" dialog telling me that the audacity.cfg configuration file is inaccessible (see Screenshot.  It suggests that the disk my be full or I may not have write permissions - neither of which is true.

If I just wait and ignore that dialog Audacity will normally launch and I can make Prefs and settings changes that successfully get written back to the audacity.cfg file

**To Reproduce**
1. Launch 3.1.2
2. Observe:  "Audacity Configuration Error" dialog 
3. Wait
4. Audacity lunches OK
5. Make preferences change(s)
6. Observe: these take effect with no error
7. close Audacity
8. relaunch 3.1.2
9. Observe: the prefs change(s) made at step 5 are still extant (i.e. the audacity.cfg file was successfully written to)

**Expected behavior**
No such error dialog to be shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/50205984/142418821-8f8c3e87-75fd-4811-b673-931340d6513a.png)

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version: Audacity 3.1.x

**Additional context**
This is only a moonphase bug for me - I have seen it on several occasions but cannot force it to happen - it certainly has afflicted 3.1.3 - I can't recall if it also afflicted 3.0.x.  I recall seeing several similar postings from users on the Forum and Facebook.

This certainly never happened with Audacity 2.x.x - and so is a regression.

**Comment by petersampsonaudacity** [comment]
Just got this again - and out of curiosity I clicked the "?" help button - this resulted in a 404 page not found error

**Comment by LWinterberg** [comment]
I've never encountered this, and unless this turns into a widespread problem, I don't think we'll address it
