### ISSUE TITLE
CommandIDs for Play-at-speed and Play-at-speed Once are very confusing.

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#2164]
**Describe the bug**
The CommandID for Play-at-speed is "PlayAtSpeedLooped"
The CommandID for Play-at-speed Once is "PlayAtSpeed"

This confusing both in terms of the IDs used for shortcuts now, and in terms of how shortcuts assigned before 3.0.5 are interpreted. There is no longer any Play-at-speed looped command.

**Expected behavior**
CommandIDs for Play-at-speed, and Play-at-speed Once should be something like "PlayAtSpeed", and "PlayAtSpeedOnce" respectively.

**Additional information (please complete the following information):**
- Audacity 3.1.2

**Comment by LWinterberg** [comment]
this is out of scope for now - if we redo macros/scripting in general in a way that breaks backwards compatibility anyway, renaming commands can happen
