### ISSUE TITLE
Problems with Windows build following BULDING.md

### ISSUE THREAD

**Issue by SteveALee** [audacity/audacity#2170]
**Describe the bug**

I carefully followed the Windows build instructions in [BUILDING.md](https://github.com/audacity/audacity/blob/master/BUILDING.md) but cannot get a successful build. I also spotted a couple of issues.

The *prequisites* section says "A working C++ 17 compiler" but that is platform specific. With `VS 2019` as specified the `cl.exe` version is 19

The instructions to install `conan` are `pip install conan` but they did not work as pip is not on the path. Rather, I used `py -m pip install conan` as specified somewhere else in the Audacity dev docs.

I installed the following tools:

- VS community 2019 (AKA 16 )
- cmake 3.2.2
- python 3.10.0

I chose the following options in `cmake` GUI:

- source `c:\projects\audacity\` - where I cloned `Audacity-3.1.2` too
- VS 16 2019
- x64 (default)
- native compilers

Get error " conan executable not found" even though I installed it as described.

```
Make Error at cmake-proxies/cmake-modules/conan.cmake:795 (message):
  Conan executable not found! Please install conan.
Call Stack (most recent call first):
  cmake-proxies/cmake-modules/conan.cmake:841 (conan_check)
  cmake-proxies/cmake-modules/AudacityDependencies.cmake:6 (conan_add_remote)
  CMakeLists.txt:175 (include)
```

![image](https://user-images.githubusercontent.com/618922/142723790-0c04f3d7-8729-49ac-bae7-6895f17665c4.png)

The `CMAKE_INSTALL_PREFIX` value seems odd for a dev build. I di not set it.

So I uncheck `audacity_conan_enabled` and try again

Get error ZLIB not found. The only value i can set for this option is `system` and Windows doesn't have a system version. Previous builds used the wx version of zlib and peeking at the cmake config files it looks like that should still be the case.

```
CMake Error at cmake-proxies/cmake-modules/AudacityDependencies.cmake:186 (message):
  Failed to find the system package ZLIB
Call Stack (most recent call first):
  cmake-proxies/CMakeLists.txt:1 (add_conan_lib)
```

![image](https://user-images.githubusercontent.com/618922/142724005-4a4f8605-a42e-495f-8eff-08f868d921ea.png)

I tried using the `cmake` command in CLI with same results (I'm working towards updating my [automated build script for asio](https://gist.github.com/SteveALee/da24c2be633340b8791066dd98eb5d0b) )

Any help much appreciated

thanks.

**Comment by SteveALee** [comment]
I suddenly thought I've been following the HEAD build instructions buit building a potenitally older a tagged release for 3.1.2! But on checking I see the instructions are identical.

**Comment by crsib** [comment]
Hi, Steve! Conan needs to be in PATH at least during the first configuration

**Comment by SteveALee** [comment]
@crsib 

Thanks. Really? I thought it was a tool used for docs only? I did see loads of refs to it in the cmake config files though  :)

OK, I'll try to figure out how to do that as I've not done any python since before pip was a thing. Any clues appreciated

**Comment by crsib** [comment]
Conan is a 3d party dependency management software. Like pip Python or Cargo in Rust.

The location of conan.exe really depends on how pip was run. It can be in %LocalAppData%\Programs\Python\PythonXY\Scripts  or the Python binary directory itself.

**Comment by SteveALee** [comment]
> Conan is a 3d party dependency management software.

Make sense and I gussed as much as nolonger need to explicitly build wx.

So I found an option in the python 3.10 installer that makes pip and then conan apear on the cmd line.

Cmake gui gets a lot further now but the `expat` build fails as it can't find - yes, you guessed it - `cmake`!

Time to reboot.

**Comment by SteveALee** [comment]
@crsib Thank for your help. I now have a build, with ASIO. Will submit a PR soon

I may be wrong but the build takes WAY longer that it used to. That seems partly due to repeated build platform feature tests and partly extra dependencues, like strawberry perl.

**Comment by crsib** [comment]
Just the first configuration :-)

**Comment by SteveALee** [comment]
Thanks the build is much simpler now. My little script is less important but still may make it easier for others who are less technical and need ASIO.
