### ISSUE TITLE
Unexpected info in the About box with own builds

### ISSUE THREAD

**Issue by SteveALee** [audacity/audacity#2172]
**Describe the bug**

When I build for Windows with ASIO using the `BUILDING.md` instructions or [own my own script](https://gist.github.com/SteveALee/da24c2be633340b8791066dd98eb5d0b) there are a couple of surprises in the about box.

1. I grab the 3.1.2 release code using the `audacity-3.1.2` branch/tag. But the about box says `Audacity 3.1.2-alpha-20211120`! .I'd understand if you have some release process you apply to the binaries after building but it's disconcerting to say the least!
2. Although I build with ASIO there's nothing in the Build Information tab of the about box to say that.

**Comment by LWinterberg** [comment]
your build script is missing an `-DAUDACITY_BUILD_LEVEL=2` in the cmake options to mark it as release - that said, the building.md also doesn't mention that.

**Comment by crsib** [comment]
The best way is to use the source tarball, which has all the values set properly. https://github.com/audacity/audacity/releases/download/Audacity-3.1.2/audacity-3.1.2-source.tar.gz

The alternative provided by Leo will work as well.

**Comment by SteveALee** [comment]
That sorted the version out thanks. 

But still no mention of ASIO. But if you have an active ASIO driver you can soon tell/
