### ISSUE TITLE
Audacity log appears to clear on clicking "OK" in Preferences

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2180]
**Describe the bug**
When the Audacity Log is open, clicking "OK" in Preferences resizes the log window to its very small default size and blanks the text, making it appear to be empty.

**To Reproduce**
1. Open the Audacity Log
2. Resize the log to a reasonable size so that you can easily see the contents
3. Open Preferences
4. Click the OK button in Preferences
5. Observe that the log is resized back to its very small size and appears to be empty.
6. Observe that opening Preferences again and clicking "Cancel" brings back the log text (though does not restore the user set window size).

**Expected behavior**
The log window to remain unchanged

**Screenshots**

Before clicking OK
![Before](https://user-images.githubusercontent.com/11681097/143092805-d4fff87f-e70b-44c1-8666-83456f7fcc13.png)

After clicking OK
![After](https://user-images.githubusercontent.com/11681097/143092821-4f9c2a73-3d6f-43ad-98e5-ef76c9c94b8e.png)

**Additional information (please complete the following information):**
 - OS: [Xubuntu 20.04
 - Version Audacity 3.1.3 AppImage

**Additional context**
The disappearing text is a regression against 3.0.2
The  changing window size bug was also present in 3.0.2

**Comment by vivekKr24** [comment]
Please review my PR for the this issue.
Thanks
