### ISSUE TITLE
Looping: It is too easy to accidentally trigger a looping region by clicking on the timeline

### ISSUE THREAD

**Issue by Tantacrul** [audacity/audacity#2182]
**Describe the bug**
When some users try to use Quick-Play by clicking on the timeline and inadvertently moving the mouse a little, they accidentally create a very tiny loop region, which in turn, activates the loop button and causes a degree of irritation. We've heard enough complaints about it to warrant a fix soon. On the plus side, I think the fix is probably very easy.

**Expected behaviour**
The threshold for dragging needs to be larger, so that a loop region isn't created when the user clicks and drags just a pixel or two. We will need to set a threshold of something like 10-20 pixels (possibly more... but we'll need to test). It is extremely unlikely that a user would set a **very very** small loop region only a few pixels apart, so we can probably bump up the 
threshold to avoid the possibility of contradicting the user's intention.

I can help test to make sure we get the threshold just right. :)

**Comment by petersampsonaudacity** [comment]
We have had lots of complaints about this on the Forum - so fixing this would be very helpful to such users.

**Comment by petersampsonaudacity** [comment]
I have been testing on older Audacity versus new 3.1 Audacity with new Audacity with new looping.

One of the reasons that I think this issue is egregious and annoying to users is that with earlier Audacity when the user accidentally moved their mouse in this way it didn't just create a play/loop region - it actually played the small Timeline range.  

I suspect that it the apparent lack of anything really happening apart from a visual range (the new loop range) that surprises and confuses users.

---------------------------------------------------------------------------------------

I've been thinking a lot more about this and I think it would be much-improved if user controls when looping is active or not by the use of the Loop button:

a) when active, "down", then click&drag (for a reasonable number of pixels) in the Timeline creates a loop region,

b) when "up", inactive, then no loop region is shown and Timeline simply does QuickPlay - and no loop regions can be created.

The tolerance zone would still be needed though as looping users with their Loop button down may still well want to use QuickPlay as well.

**Comment by petersampsonaudacity** [comment]
On a close-cousin related issue aee this Forum post:
https://forum.audacityteam.org/viewtopic.php?f=46&t=121807

Thu user here is confused as they are trying to create a "selection" for editingbut they are actually creating a loop region in the Timeline.

**Comment by SteveDaulton** [comment]
> We will need to set a threshold of something like 10-20 pixels (possibly more... but we'll need to test).

The threshold that I set in the old Timeline Quick Play seemed to work pretty well. I don't recall the exact size - it was pretty small, but the absence of complaints suggests that it was enough, while still allowing users to mark short loops.

**Comment by petersampsonaudacity** [comment]
I just tested @Paul-Licameli 's  build for this on W10
Don't change play region for very short mouse drags CMake Build #3257
https://github.com/audacity/audacity/actions/runs/1530570708

Testing shows (to me at least) the the tolerance region works well,  Small moves in either direction do not create a loop region and when the mouse button is released Quick-Play starts.  Looks good to me.

@Paul-Licameli  Out if interest, Paul, what size is the tolerance, how many pixels?

**Comment by Paul-Licameli** [comment]
> I just tested @Paul-Licameli 's build for this on W10 Don't change play region for very short mouse drags CMake Build #3257 https://github.com/audacity/audacity/actions/runs/1530570708
> 
> Testing shows (to me at least) the the tolerance region works well, Small moves in either direction do not create a loop region and when the mouse button is released Quick-Play starts. Looks good to me.
> 
> @Paul-Licameli Out if interest, Paul, what size is the tolerance, how many pixels?

Up to four pixels either side of the mark.  That was how it used to work, happily, in the time ruler, and so I used the same tolerance.

**Comment by ProfessionaFiddler** [comment]
so the "fix" was to add a resolution based smoothing? mind-blowing. making new features optional and letting users turn them off? nah, godda go the extra mile and reinvent the wheel. screw people with widescreen or 4k monitors, they can continue to suffer.

**Comment by Tantacrul** [comment]
@ProfessionaFiddler 

We don't accept whining and pointless rudeness on GitHub. Speak like that to us again and I'll ban you.

You can also feel free to contribute in some meaningful way rather than complaining at others to do it for you.

**Comment by Tantacrul** [comment]
Actually, I'm just going to ban you. Don't let the door hit you on the way out!

**Comment by SteveDaulton** [comment]
It might be worth considering making the px tolerance dependent on the detected dpi. For example, +/- 4px for regular displays, but more for high dpi.

**Comment by Tantacrul** [comment]
@SteveDaulton for sure. We actually just completed 8 user tests on the alpha - and all but one of the testers encountered this issue and they were pretty confused by it.

We think there are some simple enough fixes:

- What you said - change tolerance
- Change the action to something harder to do by accident. Probably right-click and drag (users who want looping can still hit the loop button)
- When looping is de-activated, we remove the loop region altogether, rather than greying it out
- Make sure the cursors work correctly. At the moment, there's a bug where the cursor doesn't change from a pointer to a 'hand' symbol or an 'stretch' symbol when hovering over the edges.

In general, this problem is worse in AU4 because we notice a lot of people dragging the new playhead along the top bar, which greatly increases the chances of the mistake happening.

**Comment by Thespikedballofdoom** [comment]
This has been bothering me a lot and it's sad to see there is no disable feature. It's like really annoying that any amount of dragging makes a loop, now you have to be all surgical about when you hold and click. I could bind something and mash it every single drag, but at that point...
