### ISSUE TITLE
Audacity 3.1.1 gets stuck when it is about to play after recording audio on Windows 10

### ISSUE THREAD

**Issue by Honghe** [audacity/audacity#2194]
**Describe the bug**
Audacity 3.1.1 gets stuck when it is about to play right after recording audio on Windows 10.
It happens most of the time.

**To Reproduce**
1. Click Record
2. Click Play
3. Audacity gets stuck.

**Expected behavior**
Audacity can play the recorded audio.

**Screenshots**
![image](https://user-images.githubusercontent.com/1092722/143728782-2208d9f0-d797-4e1d-a844-ab3e0f59baf2.png)

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version  Audacity 3.1.1
 - MME

**Comment by petersampsonaudacity** [comment]
I can't reproduce this on w10 with 
a) 3.1.1
b) 3.1.2 current release
c) 3.1.3 Beta-1 test build

Peter.

**Comment by Honghe** [comment]
@petersampsonaudacity I seems it is not the problem. Sometimes, I change window to other app and back to audacity, audacity get stuck too, the UI dos not respond.

https://user-images.githubusercontent.com/1092722/143770392-5435ad92-f524-414e-8871-b99c6c2b4978.mp4

**Comment by LWinterberg** [comment]
I also cannot reproduce this. To me, this feels like some sort of driver problem and better suited for the forum: https://forum.audacityteam.org/index.php

Maybe using a different output device (or using WASAPI or DirectSound instead of MME) changes things?
