### ISSUE TITLE
Clip names lost when pasting between projects

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2196]
**Describe the bug**
Pasting clips from one project to another may cause clip names in the target project to be lost.

**To Reproduce**
1. Generate a Chirp
2. Split the chirp into two sections
3. Name the two clips "A" and "B"
4. Create a new project
5. Generate a tone
6. Split the tone into two clips
7. Name the clips "1" and "2"
8. Select all of the track from the first project and copy it
9. Paste the copied audio to the start of the second project
10. Observe that the names of the clips in the second project are now: "A", "B", "Audio Track", "Audio Track 1".

**Expected behavior**
At step 10, the clips names are expected to be "A", "B", "1", "2".

**Screenshots**

**Additional information (please complete the following information):**
 - OS: Reported on Windows10. Confirmed on Linux.
 - Version Audacity 3.1.2 and 3.1.3 alpha

**Additional context**
Reported here: https://forum.audacityteam.org/viewtopic.php?p=440425#p440425

**Comment by petersampsonaudacity** [comment]
Works fine for me on W10 with 3.1.2

![image](https://user-images.githubusercontent.com/50205984/143902777-046138fd-3ccc-4b58-860f-8c158b6841f4.png)

**Comment by SteveDaulton** [comment]
> Works fine for me on W10 with 3.1.2
Sorry if it wasn't clear, but step 9 should be:

9. Paste the copied audio into the track that contains clips "1" and "2", so that you (expect to) get 4 clips in one track:  "A", "B", "1", "2".

Is that clearer?

**Comment by petersampsonaudacity** [comment]
> > Works fine for me on W10 with 3.1.2
> 
> Sorry if it wasn't clear, but step 9 should be:
> 
>     9. Paste the copied audio into the track that contains clips "1" and "2", so that you (expect to) get 4 clips in one track:  "A", "B", "1", "2".
> 
> 
> Is that clearer?
 Still works for me on w10 with 3.1.2

![image](https://user-images.githubusercontent.com/50205984/144081515-9ae31bd6-0b27-43fd-9977-d8e64256f6cf.png)

**Comment by petersampsonaudacity** [comment]
OIC - further testing shows the corruption if you paste in at T=0 i.e. before the existing audio in the second project

![image](https://user-images.githubusercontent.com/50205984/144082092-4eb7aab0-f0f3-4dff-be48-acdbba00e11e.png)

**Comment by petersampsonaudacity** [comment]
A user on the Forum has been complaining about this recently:
https://forum.audacityteam.org/viewtopic.php?p=442320

I observe that this is not on the list of issues to be addressed for 3.2.0:
3.2 backlog tracking #2353 

Given that named clips are an important new feature for Audacity P4 would seem a little low as a priority rating.  

Audacity should not be corrupting users' carefully constructed project data, this leads to poor UX, _as can be seen expressed on the Forum post_.

@Penikov @crsib @Tantacrul

**Comment by Penikov** [comment]
If this is a data corruption this bug should be rated as p1

**Comment by vsverchinsky** [comment]
I can't reproduce this bug without "Editing clip can move other clips" option enable, but with this option it could be reproduced within same project (when pasting into another track before existing audio). 

@dozzzzer @Ryan-Miller-Audacity Also similar bug could happen when  **Sync lock** and **...clips can move** options are enabled and there are more than one track and one of them is being edited
Pasting into **Audio 1** in position between **abc** and **ABC** (sync lock enabled):
![image](https://user-images.githubusercontent.com/20165230/209135543-1f7a8897-2a63-43d8-a0c8-5dab52804bb3.png)
Result:
![image](https://user-images.githubusercontent.com/20165230/209135719-89aff105-69e7-4257-b201-c2b7df13f2c2.png)

**Comment by dozzzzer** [comment]
Verified
