### ISSUE TITLE
Comment on a specific part of project

### ISSUE THREAD

**Issue by ultraomid** [audacity/audacity#2197]
I request a feature on this software to allow users to comment on different parts of Audio tracks. This feature lets the content creators manage their projects better.
Thanks for your consideration.

**Comment by LWinterberg** [comment]
Audacity has two ways of doing that already: Clips and labels

![image](https://user-images.githubusercontent.com/87814144/143918292-d9d8d25a-7a0d-4996-a2b0-016a12574108.png)

What exactly do you want to do which goes beyond that?

**Comment by ultraomid** [comment]
Sorry, I didn't know that this feature already has been added. This is the exact feature I wanted.
Thanks for your help.
