### ISSUE TITLE
Clip Names. Audacity crashes when a user clicks 'Cancel' at clip renaming dialog

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2198]
**Describe the bug**

 Audacity crashes when a user clicks 'Cancel' at clip renaming dialog

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a couple of tracks with clips

2. Turn On [Menu]-[Tracks]-[Sync Lock Tracks]

3. Go to [Preferences]-[Tracks]-[Tracks Behaviors] turn on the tickbox "use the dialogue for the name of new label"
![изображение](https://user-images.githubusercontent.com/25851359/143918281-72de7439-b329-4779-8a07-53c80a05a69c.png)

4. Open the 'Set wave clip name' dialog with Double-click
5. Click the 'Cancel' button and close the dialog

**Additional information (please complete the following information):**
 - OS: Windows 10, Mac OS Monterey
 - Version: Audacity 3.1.2 +

**Additional context**

Steps to reproduce on Windows:  are the same, except the last step. 
The last step on Windows should be:
5. Click the 'Close' button 
![изображение](https://user-images.githubusercontent.com/25851359/144010663-48e8b1ce-fd55-4820-8573-b9c9e34d1ccd.png)

relates to #2199

More details: https://youtu.be/trb0yqqw96Q?t=340

**Comment by AnitaBats** [comment]
reproducible on Windows as well
