### ISSUE TITLE
Clip names automatically deselect when attempting to change name with many collapsed tracks

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2200]
**Describe the bug**
When working with large multi-track projects, it is often necessary to collapse tracks so as to see all, or as many as possible tracks in the available screen space. In this scenario, selecting the name of a clip frequently deselects itself before the name can be edited.

**To Reproduce**
1. Create a stereo track
2. Generate some audio into the stereo track
3. "Duplicate" 4 times so that there are 16 stereo tracks in the project
4. "Collapse" all tracks so that you can see all (or most) of them
5. Double click on the Clip Handle of the first track and change the name to "01"
6. Double click on the Clip Handle of the second track and change the name to "02"
7. Continue likewise for all 16 tracks
8. Observe that after double clicking on the clip name, it frequently becomes selected then immediately reverts to unselected, making the process frustratingly arduous (I ended up having to "Expand" each track, rename the clip, then "Collapse" it again).

**Expected behavior**
Double click selects the clip name for editing regardless of the number of tracks or whether they are collapsed or expanded.

**Screenshots**

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version: Tested with Audacity 3.1.2 and Audacity 2.1.3 alpha

**Additional context**

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
