### ISSUE TITLE
Changing the loop region changes the selection

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2205]
**Describe the bug**
Changing the loop region changes the selection

**To Reproduce**
1. Get some audio
2. make a small selection
3. click and drag in the Timeline to create a loop region - NOT the same as the selection
4. Observe: the selection changes to be the same time range as the loop region

Also happens if you have a loop region and a selection the same and then expand or contract the loop region - then the selection changes to be the same as the Loop region.  BUT if in that case you expand or contract the selection then the loop region does not change - so this is asymmetric behavior.

**Expected behavior**
My understanding was that the loop region a=in the Timeline and the selection region in the Timeline are supposed to be independent

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS: Windows 10 - bt assume all OS
 - Version: Audacity 3.1.2 and 3.1.3 Beta-1

**Additional context**
Users may well get upset at losing their carefully made selection like this.

**Comment by LWinterberg** [comment]
Did you turn on "Enable dragging selection" by accident? (right-click on the timeline)

**Comment by petersampsonaudacity** [comment]
> Did you turn on "Enable dragging selection" by accident? (right-click on the timeline)

@LWinterberg  - this is possible as I was testing earlier in the week with selection dragging following a Forum post.

So I tested again this morning:

1. purge the Audacity settings folder to reset to OOTB factory settings 
2. Launch 3.1.2
3. import some audio
4. Right click on Timeline
5. Observe: "Enable Dragging Selection" is off
6. make a short selection in the audio
7. click&drag in the Timeline to make a loop region (in a place that is not the selectio from step 6
8. Observe: the selection remains unchanged where it was at step 6

So yes it is indeed the "Enable Dragging Selection" status that changes and controls this behavior.

BUT there remains an oddity:
At steps 4-5 the "Enable Dragging Selection" is grayed out and inoperable.  It is only after I have created a loop region in the Timeline that the "Enable Dragging Selection" in the context menu becomes available and operable (no grayed out).  Is this a bug or intentional designed behavior?

Flagging @Tantacrul as this may be a UX issue

The Manual has little to say on this:
https://alphamanual.audacityteam.org/man/Timeline#menu

And note that there it talks about a "Play Region" - but surely now with new looping the "Play Region" has been replaced with a "Loop Region" - a loop-play region.  So surely it should be called "Loop Region" in the Manual.

**Comment by petersampsonaudacity** [comment]
There is also possible confusion caused by the
a) Enable dragging selection - in the Timeline context menu
https://alphamanual.audacityteam.org/man/Timeline#menu

and the similarly named
b) Enable dragging selection edges - in Tracks Behaviors preferences
https://alphamanual.audacityteam.org/man/Tracks_Behaviors_Preferences

Which appear to effect different behaviors AFAICT

**Comment by petersampsonaudacity** [comment]
And I then also find this page confusing in it's somewhat thin explanation of the Enable dragging selection  in the Timeline context menu behavior:
https://alphamanual.audacityteam.org/man/Tutorial_-_Looping

**Comment by LWinterberg** [comment]
The tutorial has it mentioned in passing as it's needed in step 3 to make a clip out of the loop that you've been fiddling with. I'll say that the entire concept of having a loop region connected to a selection is highly unusual to begin with, as is having this connection one-way (adjusting the selection does not affect the loop region).

**Comment by DavidBailes** [comment]
> I'll say that the entire concept of having a loop region connected to a selection is highly unusual to begin with, as is having this connection one-way (adjusting the selection does not affect the loop region).

I too find the one-way connection strange, but don't understand why you think a two-way connection is highly unusual.
Reaper has the option of a two-way linking of the loop range and the selection range.
And I have made the suggestion of having this option in Audacity on discord, and a user has made the suggestion in the forum https://forum.audacityteam.org/viewtopic.php?t=121332#p438749

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest 3.2.0 alpha master audacity-win-3.2.0-alpha-20220323+6c64dc4-x64-msvc2022

This no longer appears to be the case.

@LWinterberg @Penikov  - I suspect this can be closed
