### ISSUE TITLE
Incorrect use of format  directives in some Nyquist plug-in strings

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2206]
**Describe the bug**
Some translatable strings in some shipped Nyquist plug-ins have been incorrectly updated to use the "~%" format directive instead of "\n" for a new line

**To Reproduce**
1. Attempt to reinstall an already installed "custom" Nyquist plug-in, with "Allow overwriting" set to "Disallow".
2. Observe the "~%" in the error message.

**Expected behavior**
A new line rather than "~%".

**Screenshots**

![Screenshot_2021-11-30_19-11-13](https://user-images.githubusercontent.com/11681097/144117925-dd928823-83b6-488e-a55e-1d2dda9d7ced.png)

**Additional information (please complete the following information):**
 - OS: Linux / Any
 - Version Audacity 3.x

**Additional context**
My guess is that these changes were made due to a bug / limitation in the Audacity code that handles translations of strings in Nyquist plug-ins.
I don't know if the bug / limitation still exists, but there is a note on the Audacity wiki:

> **Translation for shipped effects**
> ...
> **Limitations:**
> Control characters like \n (new line), \t (tab) are not supported. The workaround is to use Lisp format directives instead: 

Unfortunately there seem to have been several of these errors made:
https://github.com/audacity/audacity/commit/dad9823ed2b1bc2425203c3d566805a9ce81a0c2
and 
https://github.com/audacity/audacity/commit/29c7133dd9b35dd3fa9fcd092600f2458fe24ec4

**Comment by SteveDaulton** [comment]
If the limitation / bug with control characters in strings still exists, then the quick fix is to change the affected strings from string literals to formatted strings.

**Comment by SteveDaulton** [comment]
Another one:

![Screenshot_2021-11-30_19-07-35](https://user-images.githubusercontent.com/11681097/144126965-be6fc2df-47ae-48b7-b648-2a34e8644721.png)

**Comment by harsh628** [comment]
I want to contribute in this.
