### ISSUE TITLE
feature request: move audio to different track

### ISSUE THREAD

**Issue by oldcodewizard** [audacity/audacity#2207]
Hi

I'm a big fan of the recent 'handles' to move and trim audio in a track.
Wouldn't it be nice to be able to move audio using this same handle to another track, to add it to that track?
Or is this already officially possible?  

Example: 2 tracks are opened (1 imported, which is below the first) and you want to concatenate track 2 to track 1 by moving track 2 'into' track 1 by dragging it using the handle.

Maybd i'm telling nonsense but I would use this feature to merge tracks in an easier faster way.

**Comment by LWinterberg** [comment]
This is something you can do with the clip handles. Note that both tracks must be of the same type, so if you have a clip on a mono track, it only can be dragged into other mono tracks. Also note that there must be enough room for the clip to fit in.
