### ISSUE TITLE
feature request: zxtune support

### ISSUE THREAD

**Issue by ghost** [audacity/audacity#2208]
Hi

No idea if this is possible or if any developer sees anything in this idea, but I personally play a lot of chiptune/game music and I would love to edit or merge files (and save as flac for example)

Similarly how ffmpeg allows many audio formats to be imported, I would like to request a zxtune importer for chiptune and video game music (vgm) files: https://github.com/vitamin-caig/zxtune
VGM files are widely used for storing game music, so this feature would certainly be unique to audacity then because I never saw an audio editor that can import such files.
Zxtune supports any chiptune/game music file format you can think of.

(I currently export the music files to wav using a chiptunes player, then load into audacity this way.)

Thx

**Comment by oldcodewizard** [comment]
As an additional idea: maybe a sort of universal plugin system for audio importers can be developed? This can then be used to allow different open source cross platform libraries (like zxtune) import new audio formats in audacity.
I don't know anything of audacity'source code, so my apologies if this already exists. (I'm only aware of ffmpeg installer)

**Comment by LWinterberg** [comment]
Emulation of specific soundchip hardware from retro consoles may be good for a VSTi, but doesn't seem like a good fit for an Audacity-native instrument.
