### ISSUE TITLE
Additional shortcuts for looping behaviors

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2209]
**Describe the bug**
There are no system-defined default shortcuts for the new commands introduced in 3.1.x
a) Transport > Looping > Clear Loop
b) Transport > Looping > Set Loop to Selection

**To Reproduce**
1. Go to Transport > Looping menu
2. Observe: no shortcuts for "Clear Loop" or "Set Loop to Selection"

**Expected behavior**
System-defined default shortcuts for the new commands (in both the Standard and Full set)
a) Transport > Looping > Clear Loop
b) Transport > Looping > Set Loop to Selection

**Screenshots**
![image](https://user-images.githubusercontent.com/50205984/144223280-33254057-8872-46ad-a523-f0f820d9581d.png)

**Additional information (please complete the following information):**
 - OS: Windows 10 - but assume all OS
 - Version Audacity 3.1.x
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]

**Additional context**
Now that more focus has been placed on looping with 3.1 with efforts to try to make it more "discoverable" and thus used more widely it would helpful to the user if in addition for the new shortcut "L" to turn looping on/off there were also default shortcuts for the other new commands "Clear Loop" or "Set Loop to Selection".

Especially given that turning looping off does not of itself clear a loop region.

Also note that using the Transport menu takes 3 clicks to achieve the goal - and using the Timeline context menu involves a right-click followed by a left-click,

Flagging @Tantacrul as a UX issue

_**Workaround:**
Of course the reasonably smart user can create custom shortcuts for these commands - but my past experience shows that for a user finding an unused shortcut key is tricky and tedious_

**Comment by petersampsonaudacity** [comment]
@DavidBailes  - might VI users benefit from frther shortcuts in the "Full" set for:
a) Set Loop In,
b) Set Loop Out?

**Comment by DavidBailes** [comment]
> @DavidBailes - might VI users benefit from further shortcuts in the "Full" set for:
> a) Set Loop In,
> b) Set Loop Out?

I currently don't think that those commands will be used very much. I'm not sure in which use cases the designers thought that these commands would be used.

**Comment by petersampsonaudacity** [comment]
> I currently don't think that those commands will be used very much. 

Thanks @DavidBailes 


>I'm not sure in which use cases the designers thought that these commands would be used.

I'm strongly minded to agree - for me they look like bloatware

**Comment by petersampsonaudacity** [comment]
See also this thread:
 Selected region is not shown on Timeline #2067

**Comment by petersampsonaudacity** [comment]
The following single letter shortcuts remain available - I tested against the Full shortcut set

E, F, G, H, M, N, O, S, T, V, W, Y

I would recommend S for Set Loop to Selection (because of the alliteration)

and then E  for Clear Loop as it is close to the S key - and it "Empties" the Timeline of its Loop region

**Comment by DavidBailes** [comment]
> The following single letter shortcuts remain available - I tested against the Full shortcut set
> 
> E, F, G, H, M, N, O, S, T, V, W, Y
> 
> I would recommend S for Set Loop to Selection (because of the alliteration)
> 
> and then E for Clear Loop as it is close to the S key - and it "Empties" the Timeline of its Loop region

Note that the  addition of default shortcuts has already been included in https://github.com/audacity/audacity/issues/2101.

As I commented on that issue, I think that, because of their convenience, single letter shortcuts should only be used for commands which are going to be very frequently used. It's very useful for there to be some unassigned single key shortcuts so that users can assign these to the commands which they use frequently in their particular workflow.
@LWinterberg 's, suggestion of Shift+L for setting the loop range to selection seems fine to me.
I question whether there needs to be a default shortcut for clearing the looping range. Could you give some examples where you think a user would use that command?

**Comment by Tantacrul** [comment]
I'm very cautious about filling up those primary shortcuts just now. When we have a new designer hired, we need to look ahead and figure out what kind of primary functions these shortcuts could be assigned to.

For example: E: (opens realtime effects panel)

**Comment by petersampsonaudacity** [comment]
> @LWinterberg 's, suggestion of Shift+L for setting the loop range to selection seems fine to me.

I'd be happy with that


> I question whether there needs to be a default shortcut for clearing the looping range. Could you give some examples where you think a user would use that command?

It's because when you
1) turn looping off any existing loop region remains visible and extant.
2) If you then turn looping back on and make a selection in the audio the loop region remains as it was in step 1

But if there is no loop region and you then tun looping on and then make a selection in the audio the selection creates a matching loop region in the Timeline which can be useful.

Though for me that basis issue is that I really think that when looping is turned off then any existing loop region should just be discarded.

**Comment by petersampsonaudacity** [comment]
> I'm very cautious about filling up those primary shortcuts just now. When we have a new designer hired, we need to look ahead and figure out what kind of primary functions these shortcuts could be assigned to.

I see your point - but we could have a similar compound shortcut like the one that @LWinterberg and @DavidBailes suggest for Set Loop to Selection surely

**Comment by LWinterberg** [comment]
I'd be fine with Shift+L for "Set Loop to Selection" and would like Alt+L for "Clear Looping Region"*, but I see that it's already taken in the full set. Is the standard set a strict subset of the shortcuts found in the full set? Or is it more of a "set of shortcuts from previous releases", with the standard set being allowed to change and evolve independently of it?

*aside, this is something I really like about blender's latest shortcut redesign. They made it so that `Alt+key` generally does the opposite of `key`, eg `h`=hide, `alt+h`=unhide, which makes it pretty easy to remember)

**Comment by petersampsonaudacity** [comment]
> Is the standard set a strict subset of the shortcuts found in the full set?

Yes it is @LWinterberg

**Comment by DavidBailes** [comment]
> It's because when you
> 
> 1. turn looping off any existing loop region remains visible and extant.
> 2. If you then turn looping back on and make a selection in the audio the loop region remains as it was in step 1
> 
> But if there is no loop region and you then tun looping on and then make a selection in the audio the selection creates a matching loop region in the Timeline which can be useful.

But you could equally well just execute the command to set the loop range to the selection. It's one command either way.

**Comment by DavidBailes** [comment]
> *aside, this is something I really like about blender's latest shortcut redesign. They made it so that `Alt+key` generally does the opposite of `key`, eg `h`=hide, `alt+h`=unhide, which makes it pretty easy to remember)

Using Alt+alphanumeric you just have to be careful that there are no conflicts with any of the access keys for the names of the menus in the menu bar (and for all the translations of the menu names).

**Comment by Paul-Licameli** [comment]
I am assigned this easy task for 3.1.3, but I do t see the simple spec for what exactly the shortcuts must be.  Please reach agreement and edit the issue description.

Shift+L for setting loop to selection is agreed, but which key to clear the loop?

**Comment by petersampsonaudacity** [comment]
> Shift+L for setting loop to selection is agreed, but which key to clear the loop?

This is not my vall - it's down to @Tantacrul is my understanding.  

I understand his reticence to use a single-key for this so how about  **Alt + C**   ?

**Comment by Tantacrul** [comment]
@Paul-Licameli - let's discuss next week. @petersampsonaudacity, I'll confer with you on what it should be exactly. Apologies, we're still in hiring mode right now :(

**Comment by Paul-Licameli** [comment]
I think we have agreed elsewhere that the shortcuts shall be Shift + L and Shift + Alt + L.

**Comment by petersampsonaudacity** [comment]
Tested on W10 with @Paul-Licameli 's branch build  

The new shortcuts are in the Transport>Looping men - and they work as intended.

![image](https://user-images.githubusercontent.com/50205984/145972936-6de60393-f872-4378-b726-e5bf49e46778.png)

**Comment by petersampsonaudacity** [comment]
Tested on W10 with audacity-win-3.2.0-alpha-20211217+8340b56-64bit and the latest 3.1.3 alpha build.

This is now fine in both that alpha builds.   The shortcuts are there in both the standard an full sets - and they work as intended.
