### ISSUE TITLE
Windows build in cmake-gui is slow as it builds 4 versions

### ISSUE THREAD

**Issue by SteveALee** [audacity/audacity#2211]
**Describe the bug**

CC @crsib 

More an observation and discussion for possible improvement.

I noticed the initial build using cmake-gui is very slow and it turns out this is a four versions get built. I dount all four are ever wanted, rather usually Debug or Release? In my script I just build  Release and that is not quite four times as fast.

On the commandline I define `MAKE_CONFIGURATION_TYPES=Release`

```
cmake -G "Visual Studio 16 2019" -DCMAKE_CONFIGURATION_TYPES=Release -Daudacity_has_asio_support=On -DAUDACITY_BUILD_LEVEL=2 -S %AUDACITY% -B %AUDACITY_BUILD% 
```

But I cannot find anyway to set in the gui. Passing `-D` when invoking cmake-gui doesn't work.

Perhaps the environment can be updated interactively or a set of presets provided?

**Comment by crsib** [comment]
>Debug or Release

That makes sense. However, the proper set of configurations is a question. We use Debug and RelWithDebInfo, and you use Debug and Release :-)

The ideal scenario will be to set up the job for `https://github.com/audacity/conan-recipes` so binaries are cached for Windows and macOS builds, but this will take some time

>presets provided

This would help as well, excellent idea! Thank you!

**Comment by SteveALee** [comment]
Having a cache is a great idea and now I know about conan that seems to be how it can work best. I'm impressed by it. :)

**Comment by werame** [comment]
For what's worth it, [it seems](https://github.com/conan-io/cmake-conan/issues/156) one could control what conan builds by setting e.g. `CMAKE_BUILD_TYPE=RelWithDebInfo` before running conan *might* force it to use/build just one kind of output targets, but I haven't tested this myself (because I have all of them built, LOL.) Will try that a bit later on a different machine, because I want to debug another conan issue, separately from possible Audacity interference.

**Comment by crsib** [comment]
Actually, the `CMAKE_CONFIGURATION_TYPES` is the one. For example, `-DCMAKE_CONFIGURATION_TYPES=Debug` will produce only the `Debug` configuration

**Comment by werame** [comment]
Yeah, the check is a bit hairy https://github.com/conan-io/cmake-conan/blob/f2559b844620a834065d82ad9bc8d488934e2d47/conan.cmake#L468

**Comment by crsib** [comment]
https://github.com/audacity/audacity/blob/9f0133746b76112dd4aad1c340cb3ee09e8997cd/cmake-proxies/cmake-modules/AudacityDependencies.cmake#L273-L275
