### ISSUE TITLE
3.1.3 looping fixes

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#2214]
Fixes to the following bugs are in-scope for the 3.1.3 release. 

- [x] #2182 
- [x] #2067 
- [x] #2122 
- [x] #2209 
- [x] #2294
- [x] #2149
- [ ] #2304 
- [x] #2314
- [x] #2316 
- [x] #2318
- [x] #2323

**Comment by petersampsonaudacity** [comment]
I would like to request that the recently logged issue for the adding of a couple of default shortcuts for new looping commands add this one to the hotfixes for 3.1.3,.  

This should be very quicjk and easy to do - I have made life easier by researching the currently available single-letter keys for shortcuts:
https://github.com/audacity/audacity/issues/2209

**Comment by Paul-Licameli** [comment]
> This regression should probably be added here too
> Play-at -Speed with a selection gets stuck in Play mode #2316

Fair enough.

I'm not happy.  Once again, I'm doing enhancement, not simple bug fixes, in a release branch.  Reconciling adjustable speed and loop bounds is a new thing.

**Comment by LWinterberg** [comment]
Since #2304 got moved to 3.2 and #2331 addresses the other two open bugs, I'd say we're done here!
