### ISSUE TITLE
Mac M1 version

### ISSUE THREAD

**Issue by ghost** [audacity/audacity#2223]
Hi

I have a MacBook Pro M1 having a M1 ARM processor.
I can't find a version of audacity for my Mac. The intel version doesn't do anything (it doesn't start). I have no Intel processor, that's all I know. It's the Apple M1 processor I have. Mac OS is latest version too.

Is there somebody who can provide a version?

**Comment by crsib** [comment]
Itel version runs just fine for me. Do you have Rosetta 2 installed?

**Comment by oldcodewizard** [comment]
Sorry i'm not an expert.
What are you talking about?

I just tried audacity intel version but it doesn't do anything.

**Comment by LWinterberg** [comment]
Rosetta 2 is a program that allows Intel programs to run on M1 macs: https://support.apple.com/en-us/HT211861

**Comment by andrew-jolley** [comment]
I agree that the Intel version works on M1, but an Apple Silicon or Universal version would improve performance even more

**Comment by theLMGN** [comment]
Using Audacity on my M1 laptop runs at 100% cpu scrolling around, playing audio and the UI runs at 3 frames per second.

**Comment by Ein-Tim** [comment]
I support this, especially exporting could be much faster if the app would be optimized for M1 Macs.

**Comment by Ein-Tim** [comment]
@crsib 

Okay, thanks for your kind & fast response! Appreciate your work!

**Comment by andrew-jolley** [comment]
@crsib ok thank you. That’d be great to see soon!

**Comment by taxilian** [comment]
For those unaware, apps run in rosetta 2 -- while amazingly performant -- still use meaningfully more battery and cpu than those running native arm.

That said, are there things that those of us in the community with development experience and m1 macs can do to help?

**Comment by EETagent** [comment]
<img width="384" alt="Snímek obrazovky 2021-12-26 v 19 58 06" src="https://user-images.githubusercontent.com/20557318/147417551-b3733eb4-3a87-4198-95eb-6eb784ba4926.png">

<img width="1052" alt="Snímek obrazovky 2021-12-26 v 20 00 44" src="https://user-images.githubusercontent.com/20557318/147417574-e8f82ce2-d5df-445e-8fbc-bdd2410f62d9.png">

I just compiled latest Audacity from a source and it works great so far natively on Apple Silicon

`cmake -DCMAKE_BUILD_TYPE=Release -Daudacity_use_mad="off" -Daudacity_use_id3tag=off ..`

In` cmake-proxies/cmake-modules/AudacityDependencies.cmake`
replace`list( APPEND settings "arch=x86_64" )`   `list( APPEND settings ENV "CONAN_CMAKE_SYSTEM_PROCESSOR=x86_64")`
with armv8

In `cmake-proxies/libsbsms/CMakeLists.txt` ` set( ENABLE_SSE NO)`
In `cmake-proxies/libsoxr/CMakeLists.txt` delete SIMD
In `lib-src/libsoxr/src/util32s.c` delete SIMD

**Comment by SteveDaulton** [comment]
> I just compiled latest Audacity from a source and it works great so far natively on Apple Silicon. 

Can you quantify the performance benefit?

**Comment by jacop5** [comment]
> I just compiled latest Audacity from a source and it works great so far natively on Apple Silicon.
Everything for ARM64 support is already in place.

I tried doing all your steps @EETagent  but XCode just doesn't build it in the end...
<img width="1512" alt="Schermata 2021-12-27 alle 15 01 04" src="https://user-images.githubusercontent.com/96621577/147478759-e047ba14-d63d-4fc2-90d7-da486a1b39a6.png">

It seems like it tries to build x86 things but fails... I don't know since I am not a a programmer and I need this for school...

**Comment by EETagent** [comment]
I do not have Xcode installed, nor Rosseta 2, so i can't comment on that or Intel build performance, used Unix Makefiles generator for building

https://send.vis.ee/download/b0ffe22ebd4f508e/#M95jVCRPSFQSxQqgQaLzcQ

If the application's launch is completely broken, and doesn't even bring up an unknown developer's window, you'll need it to codesign it yourself

<img width="649" alt="Snímek obrazovky 2021-12-28 v 10 17 58" src="https://user-images.githubusercontent.com/20557318/147550548-c58757eb-2036-44e7-a278-5b3a60a3f0e2.png">

`xattr -cr /Applications/Audacity.app`

`codesign --force --deep --preserve-metadata=entitlements,requirements,flags,runtime --sign - "/Applications/Audacity.app/Contents/MacOS/Audacity"`

`codesign --force --deep --preserve-metadata=entitlements,requirements,flags,runtime --sign - "/Applications/Audacity.app/Contents/MacOS/Wrapper"`

**Comment by jacop5** [comment]
Amazing! Thanks a lot!
I can't use FFmpeg for some reason though.

**Comment by EETagent** [comment]
> Amazing! Thanks a lot!
> I can't use FFmpeg for some reason though.

<img width="613" alt="image" src="https://user-images.githubusercontent.com/20557318/147577369-1af40087-6285-4faa-9ff1-62c15bb464ed.png">

<img width="561" alt="image" src="https://user-images.githubusercontent.com/20557318/147577406-a2bde544-af75-4e5b-a7c7-ad1b3d837a5c.png">

You can compile FFmpeg yourself and then link Audacity against your libavcodec dynamic library, FFmpeg exports works fine from my testing

https://ffmpeg.org/releases/ffmpeg-4.3.1.tar.xz 4.3.1 works for me, master doesn't, i haven't tested another versions or ffmpeg from homebrew

**Comment by jacop5** [comment]
>You can compile FFmpeg yourself and then link Audacity against your libavcodec dynamic library from settings, FFmpeg exports works fine from my testing
https://ffmpeg.org/releases/ffmpeg-4.3.1.tar.xz 4.3.1 works for me, master doesn't, I haven't tested another versions or ffmpeg from homebrew

Great, I'll let you know as soon as I get it working

**Comment by jacop5** [comment]
I managed to get it working by using the `ffmpeg` version I had previously installed via Homebrew by pointing to `/opt/homebrew/Cellar/ffmpeg/4.4.1_3/lib/libavcodec.58.134.100.dylib`.

**Comment by danielktdoranie** [comment]
So y'all are having to compile it yourselves? Jesus Christ Audacity just release a download FFS.

**Comment by danielktdoranie** [comment]
> Itel version runs just fine for me. Do you have Rosetta 2 installed?

The point is one shouldn't have to use Rosetta 2 or run Intel code. Rosetta 2 can be and eventually will be pulled by Apple. Rosetta 2 is memory hog. Clearly it's not hard to release an arm64 M1 native version if anons are compiling it themselves. 

The M1 ISA was announced in June 2020 with developer Mac minis released at the same time. In November 2020 the first retail M1 Macs were being sold by Apple. Why the procrastination?

**Comment by jacop5** [comment]
I agree that they should release arm64 builds too.

**Comment by danielktdoranie** [comment]
> I agree that they should release arm64 builds too.

Yeah and saying this apparently hurts their feelings and they mark my comment, my opinion, as “disruptive”.

wow.

**Comment by Ein-Tim** [comment]
@danielktdoranie & @jacop5 

Did you see https://github.com/audacity/audacity/issues/2223#issuecomment-992908948?

**Comment by LWinterberg** [comment]
Please refrain from adding endless +1 comments. ARM support is planned and +1 comments won't make it go any faster.

**Comment by jacop5** [comment]
> @danielktdoranie & @jacop5 
> 
> Did you see https://github.com/audacity/audacity/issues/2223#issuecomment-992908948? 

Yes, I did. But since Audacity is really popular and M1 macs have been out for a while I was expecting to find an official build... and most of all, I expected it to work without lagging

But I found a workaround for the Rosetta build

**Comment by danielktdoranie** [comment]
> Please refrain from adding endless +1 comments. ARM support is planned and +1 comments won't make it go any faster.

It’s not an endless comment it had an end. Work on your reading comprehension. 

I don’t need to go any faster, I already found a better and native alternative. 

Maybe instead of complaining about my opinion you could get to coding?

**Comment by danielktdoranie** [comment]
> @danielktdoranie & @jacop5
> 
> Did you see [#2223 (comment)](https://github.com/audacity/audacity/issues/2223#issuecomment-992908948)?

Yep. Poster says “it’s coming” so is next Christmas. Should already be done.
