### ISSUE TITLE
WIN32: cannot configure portmixer.

### ISSUE THREAD

**Issue by carlo-bramini** [audacity/audacity#2225]
Hello, I tried to configure Audacity for building a native build for Windows, but I got this error:

```
CMake Error at /home/carlo/audacity/lib-src/portmixer/cmake/CheckPaWinMME_GetStreamInputHandle/CMakeLists.txt:16 (find_package):
  By not providing "FindPortAudio.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "PortAudio", but CMake did not find one.

  Could not find a package configuration file provided by "PortAudio" with
  any of the following names:

    PortAudioConfig.cmake
    portaudio-config.cmake

  Add the installation prefix of "PortAudio" to CMAKE_PREFIX_PATH or set
  "PortAudio_DIR" to a directory containing one of the above files.  If
  "PortAudio" provides a separate development package or SDK, be sure it has
  been installed.


CMake Error at lib-src/portmixer/CMakeLists.txt:26 (try_compile):
  Failed to configure test project build system.
```
At the moment, according to the suggestion received from CMake, I added this line:

```
set( CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/../../../../cmake-proxies/cmake-modules" )
```
to the `CMakeLists.txt` into `lib-src\portmixer\cmake\CheckPaWinDS_GetDeviceGUID` and `lib-src\portmixer\cmake\CheckPaWinMME_GetStreamInputHandle` and the problem seems solved. What do you think?

**Comment by crsib** [comment]
Worth trying for sure, although it is odd that it has popped up, as CI surely works fine :-(

**Comment by carlo-bramini** [comment]
> Worth trying for sure, although it is odd that it has popped up, as CI works fine :-(

This is the current code:
```
set( MODULE_DIR "${CMAKE_BINARY_DIR}/../../.." )

set( CMAKE_MODULE_PATH 
    ${MODULE_DIR}
    ${CMAKE_MODULE_PATH}
)
```
To tell you the truth, I don't understand it.

**Comment by LWinterberg** [comment]
The build system has changed since this was made, try again. Closing bug as stale.
