### ISSUE TITLE
Remember and use previous window size for Manage Plug-ins

### ISSUE THREAD

**Issue by Secret-Code** [audacity/audacity#2228]
**Is your feature request related to a problem? Please describe.**
Whenever I open the Manage Plug-ins dialogue window (via Add / Remove Plug-ins...), the window is too small in height and shows only about 4 plug-ins. As there can be lots of plugins, this means lots of scrolling, or resizing the window. Resizing the window every time I use this dialogue is frustrating.

**Describe the solution you'd like**
The dialogue window geometry (height and width, possibly also top and left position) should be saved e.g. when it is closed, via OK or Cancel or the x button. 
This geometry should be restored next time the dialogue is opened.

**Describe alternatives you've considered**
Making the *default* window size larger would help, but has less flexibility and might cause issues with smaller screen sizes. 

**Additional context**
Discussed on the user forum at [Add / Remove Plug-ins dialogue box is too small](https://forum.audacityteam.org/viewtopic.php?f=48&t=121959)

![Manage_Plugins](https://user-images.githubusercontent.com/11174125/144636953-4a0cd282-f317-4f9e-87a2-a2aef06801f7.png)

.

**Comment by petersampsonaudacity** [comment]
Sounds like a sensible idea to me

**Comment by LWinterberg** [comment]
I don't see us addressing this any time soon and might completely re-do the plugin manager before getting to this. Closing for now.
