### ISSUE TITLE
Very slow project load with 3.1.3 beta 1 (10+ minutes)

### ISSUE THREAD

**Issue by tux3** [audacity/audacity#2229]
**Describe the bug**
When importing projects created in previous versions of Audacity (2.3.2) with 3.1.3 beta 1, loading times are orders of magnitude slower. I've tried with a few different projects created in 2.3.2 and they all load much slower.

**To Reproduce**
1. Create a project in Audacity 2.3.2
2. Import long audio tracks, save as AUP
3. Open with 3.1.3 beta 1
4. I have not actually tested the repro, hopefully that triggers the slow load =)

I can't directly share the full project files (it's 5+GB, and I'm not sure I have license to publish those), but I've recorded a screengrab comparing 3.1.3b1 and 2.4.2, and I've attached the AUP for the project in the recording, in case that's enough to help diagnose the issue.

**Expected behavior**
3.1.3 beta 1 should not load much slower than 2.4.2.

**Recording**

https://user-images.githubusercontent.com/5155966/144660710-f7845e9b-4ab3-42fc-9a4e-3e5b7ebd58a9.mp4

[Download AUP file from recording](https://github.com/audacity/audacity/files/7651914/alicon.aup.log)

(Please truncate the .aup.log extension, Github doesn't accept this file name)

**Additional information (please complete the following information):**
 - OS: Debian 5.15.3-1 (2021-11-18) x86_64 GNU/Linux
 - Version 3.1.3 beta 1

**Comment by crsib** [comment]
Whoa, that's definitely extreme. Do you use AppImage?

Also, keep in mind, that the project format has changed, so when you open the AUP file you import the data. In this case, Audacity needs to read all the data and write it back in a different format. Depending on your hard disk performance, this can take a while.

I will look into the performance for your file. Probably it will help to improve the import process to some extent.

**Comment by tux3** [comment]
Yes, I downloaded the AppImage from the Github release.  Thanks for taking a look!   
If the AppImage is a problem and/or you can't repro, I can probably make a build and throw a profiler at it if that'd help

**Comment by petersampsonaudacity** [comment]
I have a 2.4.2 project 2 hours of stereo so about 2.5 GB  -  when I open this with 3.1.3 Beta-1 this took only 1m 15s

**Comment by crsib** [comment]
After investigation, I will have to close this issue.

The project format has changed to `aup3,` and the `aup` is now considered a foreign format (as an MP3, for example). Working directly with the `aup` file is no longer supported; I think @petersampsonaudacity has better insights on the reasons behind it.

Opening the `aup` file is an import now, so all the data must be read from the `aup` and written into the `aup3`. If the disk is slow, this process can be time-consuming. This can additionally depend on OS and kernel versions. I can see much better performance on Manjaro than on Ubuntu.
