### ISSUE TITLE
Idea Proposal: Unfading

### ISSUE THREAD

**Issue by 1131PM** [audacity/audacity#2234]
Is your feature request related to a problem? No 
Please describe.
The inverse of fading, taking low sound in db and amplifying exponentially (or linearly) to loudness you desire to remove a baked in fade in/out

Context
![Screenshot 2021-12-04 22-18-20](https://user-images.githubusercontent.com/94157220/144732155-a0e7883e-5bdf-40fb-b7a2-2e8c02200132.png)

**Comment by LWinterberg** [comment]
You can use the Adjustable fade effect to un-fade: https://manual.audacityteam.org/man/adjustable_fade.html

Relevant forum thread: https://forum.audacityteam.org/viewtopic.php?t=95992
