### ISSUE TITLE
Crash when cancelling Nyquist Prompt

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2239]
**Describe the bug**
When cancelling the Nyquist Prompt, Audacity may crash

**To Reproduce**
1. Generate a tone
2. Open the Nyquist Prompt and enter the code:

;control test "Test" float "" 5 0 10
(print test)

3. Click the "OK" button
4. Click the "Cancel" button
5. Observe crash

**Expected behavior**
Not crash

**Screenshots**

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version: Audacity 3.2.0-alpha-20211205

**Additional context**
This is a regression

**Comment by Paul-Licameli** [comment]
I introduced this bug.  It happens only in the development branch.  See the linked PR for the fix.
