### ISSUE TITLE
macOS: insertion point jumps to end of file name after typing a single character in the Save pane

### ISSUE THREAD

**Issue by paulpalinkas** [audacity/audacity#2241]
When I attempt to name the file I am saving, the insertion point moves to the end of the name after typing a single character in the Save pane.

**To Reproduce**
1. New File. 
2. Click on 'File ‣  Save As…
3. Click on file name field (which used to be selected by default) 
4. Type the first character for the new file's name.

**Expected behavior**
1. The file name field should be selected. 
2. The field should already include the file extension .aup
3. the cursor insertion point should be at the beginning of the file name field 

**Screenshots**
<img width="953" alt="Screen Shot 2021-12-05 at 9 22 45 PM" src="https://user-images.githubusercontent.com/6475182/144792355-f9e807ac-cad9-46a8-9dd5-1691faab70b7.png">

**Additional information (please complete the following information):**
 - OS: MacOS Monterey 12.0.1
 - Version: Audacity 3.1.2

*I think this is likely Monterey-specific.*

**Comment by Penikov** [comment]
I haven't reproduced this behaviour on my Mac OS Monterey.
I've tried to do this with various languages, at a new project or existing one.

**Comment by paulpalinkas** [comment]
There's another report here https://forum.audacityteam.org/viewtopic.php?p=438324#p438324 
As with his report, I also see this behavior when exporting a file. Are there some settings that might affect this behavior?

**Comment by Penikov** [comment]
> There's another report here https://forum.audacityteam.org/viewtopic.php?p=438324#p438324 As with his report, I also see this behavior when exporting a file. Are there some settings that might affect this behavior?
> 
> EDIT: There's an Audacity bug and a macOS bug. The Audacity bug is that the Save As… field is unpopulated by default, instead of being populated with "Untitled.aup3". This then leads to the insertion point bug, which I can also repro in TextEdit if I select "Untitled.rtf", Delete, then type a single character. I’ll file a bug with Apple on the latter.

I see. The filename in the field should be selected by default. 
Thank you!

**Comment by dozzzzer** [comment]
I don't see the problem anymore in version 3.3.2 on macOS 13.0:

1. the focus _is_ in the project name field
2. **.aup3** doesn't show up in the field but is added to the project name when the project is saved
3. the cursor moves as it should, i.e. as the characters are typed, it remains at the end of the string

Closing.
