### ISSUE TITLE
the alphamanual -> manual converter is skipping/not updating pages

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#2244]
Crucially, https://manual.audacityteam.org/man/time_shift_tool.html is not updated despite the alpha manual having been updated since october: https://alphamanual.audacityteam.org/man/Time_Shift_Tool

**Comment by petersampsonaudacity** [comment]
@LWinterberg  Leo, does that mean that other parts of the released manual(s) may not have been updated too ?

**Comment by petersampsonaudacity** [comment]
> Crucially, https://manual.audacityteam.org/man/time_shift_tool.html is not updated despite the alpha manual having been updated since october: https://alphamanual.audacityteam.org/man/Time_Shift_Tool

Ahhh - I suspect that may well be that this is an "almost orphan" page in the manual - nothing really links to it apart from a couple of translated pages and one of @JamesCrook 's pages.

It was updated and left in to deal with links that may exist elsewhere to that page (from the Forum for example).  

A workaround would be to create an ednote on a page (the drag-bars page would be good) and link to this "almost orphan" page from within the ednote.  That way it would have a link from a published page but one that is invisible to the user.  I think that would work, @JamesCrook do you agree ?

**Comment by JamesCrook** [comment]
That probably will work.  I say 'probably' because there is a small change that the links are only followed after processing the page, after ednotes are removed.

A failsafe way is to include an actual visible link rather than an ednote, and then edit it out of the html file after having fetched the manual.  If the ednote way works it is nicer, as it will continue to work for future updates too.

**Comment by petersampsonaudacity** [comment]
> A failsafe way is to include an actual visible link rather than an ednote, and then edit it out of the html file after having fetched the manual. If the ednote way works it is nicer, as it will continue to work for future updates too.

@LWinterberg  Leo. or I suppose one could put a (user-visible) note or advice div on this page:
https://alphamanual.audacityteam.org/man/Tools_Toolbar

saying that the old Time Shift tool has been replaced by Clip-handle drag-bars and link there to the currently semi-orphan page.

**Comment by LWinterberg** [comment]
Let's try that. I've added a note there now, can someone try to regenerate the manual?

**Comment by crsib** [comment]
`time_shift_tool.html` is not present in the archive or in the master branch (https://github.com/audacity/audacity-manual/tree/master/manual/man)

So I suspect the script that updates the manual. I'll try to get access to it shortly

**Comment by crsib** [comment]
The script was fixed, the file was removed
