### ISSUE TITLE
Redesign cursors

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#2247]
Some of the current cursors look somewhat funky:
![image](https://user-images.githubusercontent.com/87814144/145030403-78c9da97-069f-4817-a719-5c8bb9039874.png)

While some are ambiguous: 
![image](https://user-images.githubusercontent.com/87814144/145030546-a35595ce-5c84-4e78-8524-cd356dfb31ec.png)
(this is trying to expand the *left* side of the clip, causing #2053)

An on HiDPI screens / for low-vision users, some of the current cursors are hard to see: 
![image](https://user-images.githubusercontent.com/87814144/145031281-e403c2de-f3fe-400e-915c-9805cca92ab6.png)

Redesigning the cursor set might solve some/all of these problems. 

Sub-bugs:
- [ ] #2053
- [ ] #2307 
- [ ] #2456 
- [ ] #3144

**Comment by petersampsonaudacity** [comment]
See also:   Incorrect cursors/pointers for Tool grabbers #2307

**Comment by petersampsonaudacity** [comment]
Note that when holding down control (testing on W10 with 3.1.3) when over the waveform to zoom with the mouse-wheel you get a most odd, idiosyncratic, cursor icon which is the rightward-pointing gloved-hand (as in @LWinterberg Leo's first post in this thread).

If I was going to see any icon change there I would expect a magnifying glass as that would be a visual cue for zooming @Tantacrul

See:   Stuck when using mouse wheel to zoom in #2348

**Comment by Tantacrul** [comment]
Yes. They definitely need to be replaced. When messing around with a similar problem recently, @vsverchinsky and I noticed one or two seemingly custom icons that were not being used. I just need to figure out how they were created technically and it should then be trivial to replace this hand cursor (and update a few others).

However, we may wait until a larger UI refresh is done before we do it.

**Comment by LWinterberg** [comment]
this is being tracked elsewhere
