### ISSUE TITLE
Export as MP3. Audacity doesn't warn a user if the export settings are unacceptable

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2257]
**Describe the bug**
Audacity doesn't warn a user if the export settings are unacceptable

**To Reproduce**

1. Set up the project rate as 8000 Hz ![изображение](https://user-images.githubusercontent.com/25851359/145546351-20117123-1892-4106-af26-aa322bd71295.png)
2. Generate an audio clip
3. Click [File][Export As MP3] and set a destination folder for a resulting file
4. Set Up the bit rate mode as 'Preset'
5. Set up Quality (bitrate) as Insane, 320 kbps
6. The channel mode setting is doesn't matter
7. Import the file
8. Check the properties of the resulting audio. They have been changed because the MP3 format doesn't allow such audio properties were being settled up. But Audacity does not warn about it.  

**Expected behavior**
Audacity raises the warning dialog and ask a user to change the properties of the resulting file.

Like this:

![изображение](https://user-images.githubusercontent.com/25851359/145548359-5f4dacc2-ff5c-4f69-a39c-6a347f6c9246.png)

**Additional information (please complete the following information):**
 - OS: All
 - Version: All

**Comment by crsib** [comment]
I still insist that only the name of the preset is wrong here. It should be just "Insane", not "Insane (320 kbps)". LAME does not guarantee any specific bitrate in this case

**Comment by SteveDaulton** [comment]
I agree with crsib.
The result from Audacity is the same as when using LAME from the command line, namely:
`-m m -V 4 -q 3 -lowpass 4 -b 64`
which produces 64.0 kb/s CBR for 8000 Hz sample rate mono audio.

The official [LAME documentation](https://svn.code.sf.net/p/lame/svn/trunk/lame/USAGE) says:
```
--preset x Enable one of the presets

   Setting         Meaning
--preset medium	   -V 5
--preset standard  -V 2
--preset extreme   -V 0
--preset insane    -b 320
```
which is a little misleading as preset "Insane" only produces 320 kbps when the sample rate is 32000 or higher.

Other documentation, such as https://forums.afterdawn.com/threads/list-of-recommended-lame-mp3-encoder-settings-the-highest-quality-mp3-encoder.256290/ does nothing to clarify the issue:
```
-------------------------------------------------
Recommended encoder settings:
-------------------------------------------------

--alt-preset standard (~190 kbit/s, typical 180 ... 220)

--alt-preset fast standard (~190 kbit/s, faster but potentially lower quality)

--alt-preset extreme (~250 kbit/s, typical 220 ... 270)

--alt-preset fast extreme (~250 kbit/s, faster but potentially lower quality)

--alt-preset insane (320 kbit/s CBR, highest possible quality)
```

Personally I'd close this issue as I don't think there's a problem other than LAME's documentation being a bit vague.
