### ISSUE TITLE
Clips can be joined while modal effect window open

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2259]
**Describe the bug**
Clips may be joined while a modal effect window is open.

**To Reproduce**
1. Generate a Chirp
2. Split it somewhere near the middle
3. Select All
4. Open the "Amplify" effect
5. Click "Preview"
6. Stop preview playback, or wait for it to stop
7. Click on the split and  observe that it is possible to join the clips.

also

8. "Edit menu > Undo Merge" is not greyed out, but does not work.

**Expected behavior**
Modal windows should block everything outside of the window

**Screenshots**

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version [3.2.0-alpha-20211210

**Additional context**

**Comment by LWinterberg** [comment]
this gets fixed with #2330
