### ISSUE TITLE
Audacity crashes when it been closed with opened Logging window

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2264]
**Describe the bug**
Relates to #2114

The bug is the same as #2114, but now it happens on MacOS

Audacity 3.1.3

**Comment by crsib** [comment]
I do not agree that they are the same. #2114 resulted in an inability to launch Audacity again. Also, it's worth noting, that crash requires closing using Cmd-Q.

**Comment by dozzzzer** [comment]
Not reproducible anymore in the latest master. I was able to close Audacity via `Cmd + Q `and then re-launch with no issues.
