### ISSUE TITLE
Linux: Mod-script-pipe not installed

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2265]
**Describe the bug**
On running `sudo make install`, mod-script-pipe.so is **not** copied to the system.

**To Reproduce**
1. Build Audacity 3.2.0 alpha
2. `sudo make install` from the build directory
2. Observe that mod-script-pipe.so is not installed to `/usr/local/share/audacity/modules/`

**Expected behavior**
mod-script-pipe.so to be copied to `/usr/local/share/audacity/modules/`

**Screenshots**

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version 3.2.0-alpha-20211210
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]

**Additional context**

**Comment by imciner2** [comment]
That module is architecture dependent, so it should not be in any `share`-based folder on a Linux system - those folders are for files that are not dependent on the CPU architecture. It actually belongs inside `lib/audacity`, and I think it is currently installed to `lib/audacity/modules`.

**Comment by SteveDaulton** [comment]
Found it - it's installed to `/usr/local/lib/audacity/modules/`.
In that case, the problem is that Audacity does not find the module in `/usr/local/lib/audacity/modules/`.
Audacity *does* find the module if it is placed in `/usr/local/share/audacity/modules/`.
