### ISSUE TITLE
"Resample" dialog accepts invalid user input

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2269]
**Describe the bug**
The "Resample" dialog requires the input to be a positive integer, but allows negative, decimal, and non-numeric input.

**To Reproduce**
1. Select a track
2. "Tracks menu > Resample"
3. Observe that characters that are not numbers may be entered.

**Expected behavior**
Positive integer input only.

**Screenshots**

![Resample](https://user-images.githubusercontent.com/11681097/145716295-7715eceb-5121-40d1-8763-8bf5f5bf32a4.png)

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version: 3.2.0-alpha-20211210

**Comment by MridulTi** [comment]
So, from what I understood, the expected behavior is that other than positive integers no other characters should be typable in this dialogue box, right?

**Comment by SteveDaulton** [comment]
> So, from what I understood, the expected behavior is that other than positive integers no other characters should be typable in this dialogue box, right?

Right.

**Comment by LWinterberg** [comment]
we'll rework the resample/mixdown menus/dialogs in an upcoming release
