### ISSUE TITLE
Linux: No file or folder icons in file browser

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2270]
**Describe the bug**
File and folder icons are missing from Audacity's file browsers

**To Reproduce**
1. Open an Import / Export / Save dialog
2. Observe that file / folder icons are not shown.

**Expected behavior**
File / folder icons to be shown in Audacity's file browsers.

**Screenshots**

As the "Open" dialog appears with 3.2.0-alpha-20211210 (built from source)

![file-dialog-aud320](https://user-images.githubusercontent.com/11681097/145716946-a3ca5395-d773-4f72-9296-7f36be800925.png)

Expected view (mock up):

![file-dialog-good](https://user-images.githubusercontent.com/11681097/145716960-7918d216-70e8-47a5-8a1d-25e992e7e0fd.png)

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version: 3.2.0-alpha-20211210

**Additional context**

**Comment by SteveDaulton** [comment]
Also reported on the forum with Audacity 3.1.1 built from source on Xubuntu 21.10
https://forum.audacityteam.org/viewtopic.php?p=439449#p439449

**Comment by LWinterberg** [comment]
Fixed by #3571
