### ISSUE TITLE
Unable to see clip handle text when editing clip that extends left of screen

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2272]
**Describe the bug**
When renaming an audio clip that extends off-screen to the left, it is not possible to see what you are typing because the text is off-screen.

**To Reproduce**
1. Create a long track
2. Select the  last few seconds
3. Zoom to selection
4. Double click on the clip name to edit it
5. Observe that you can't see what you are typing

**Expected behaviour**
The clip name to always be visible while editing it.

**Screenshots**

Video: https://youtu.be/_kzc3zW47WU

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version: 3.2.0 alpha

**Additional context**

**Comment by petersampsonaudacity** [comment]
Tested audacity-win-3.2.0-alpha-20220121+3265124-64bit on W10  @vsverchinsky  Vitaly's branch

Looks to be fine now in this branch
