### ISSUE TITLE
VST3 support

### ISSUE THREAD

**Issue by vsverchinsky** [audacity/audacity#2277]
- [x] #2276 
- [x] #2275 
- [x] #2274 
- [x] #2273

**Comment by LWinterberg** [comment]
all tracked issues are fixed - can this be closed?

**Comment by DavidBailes** [comment]
> all tracked issues are fixed - can this be closed?

Can you clarify what you mean by a "tracked issue"? There are a number of vst3 issues still open.

**Comment by LWinterberg** [comment]
this here is a tracking issue, the 4 issues listed in OP are being tracked here: 
![tracking bug example](https://user-images.githubusercontent.com/87814144/157031568-06f28719-91a0-4f91-a11d-f348383c5d37.png)

The question is, is this tracking issue still useful? if yes, the remaining vst3 bugs should get added, if not, this issue should get closed.

**Comment by DavidBailes** [comment]
Thanks for the explanation.
