### ISSUE TITLE
"Labeled Audio" commands fail when audio selected

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2278]
**Describe the bug**
"Labeled Audio" commands fail when audio is selected.

**To Reproduce**
1. Create a project with two audio tracks
2. Add some labels
3. Select the first audio track, and the label track
4. "Edit menu > Labeled audio > Split"
5. Observe that the command silently fails.

**Expected behavior**
[The manual](https://manual.audacityteam.org/man/edit_menu_labeled_audio.html) describes the expected behaviour:

> If none of the audio tracks are included in the selection, the Labeled Audio commands apply to all audio tracks in the project. However if you include only certain audio tracks in the selection, the Labeled Audio commands will only affect those selected audio tracks. 

In the specific case "To Reproduce", the expected behavior is that splits are applied to the first track (because it is selected).

**Screenshots**

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version 3.2.0-alpha-20211210

**Additional context**
Regression.

**Comment by werame** [comment]
Something even simpler seem to fail regarding labels, only having one audio track.

1. Generate a Tone to a new track.
2. Select some middle region of it and generate Silence over that middle region.
3. Analyze the whole track for silence to get the obvious labels looking like this

![0gGQt5f](https://user-images.githubusercontent.com/97036286/148120320-acd760c7-9fd8-4462-9acd-bd577b630204.png)


4. Select the labels track only and try do "Labeled Audio ->Detach at Silences (Alt + Shift + J)"

But nothing happens at the last step. It's not everything with labels that fails though, Split Cut (Alt + Shift + X) on the same labels selection does work.

I don't have 3.1.2 installed on the same box to test how "Detach at Silences (Alt + Shift + J)" used to work, but I'll check a bit later.

**Comment by SteveDaulton** [comment]
> But nothing happens at the last step.

Nothing should happen in that case.
The "Labeled Audio" commands (should) apply the appropriate command to parts of the audio that are labeled. In your example, none of the labeled sections are silent, so "Labeled Audio > Detach at Silences" should do nothing.

If you had another region label between the "Sound 01" and "Sound 02" labels, then the silence withing the region defined by that middle label should be removed (but isn't, due to this bug).

The examples in the manual are helpful: https://manual.audacityteam.org/man/edit_menu_labeled_audio.html

**Comment by werame** [comment]
Oh, I see now, it was meant to remove silence *within* the regions labeled.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
