### ISSUE TITLE
Dynamic library path does not change unless using "Browse..." dialog

### ISSUE THREAD

**Issue by wildwestrom** [audacity/audacity#2282]
**Is your feature request related to a problem? Please describe.**
There's a link to download a `.pkg` file containing dynamic libraries required for audacity to work. These are outdated, and probably the reason why I can't import various formats supported by ffmpeg (opus for example). 
When I try to point to the path `$HOMEBREW_PREFIX/Cellar/ffmpeg/4.4.1/lib/*.dylib` nothing happens, it uses the same path as before.

**Describe the solution you'd like**
I'd much rather use the libraries provided by the homebrew package. This way I can use the latest stable or nightly release of ffmpeg.

**Describe alternatives you've considered**
I thought to try compiling the libraries myself, but I don't know how to do it in such a way that Audacity will accept the libs. It looks like it's expecting these three:
`ffmpeg.55.64bit.dylib ffmpeg_utils.52.64bit.dylib ffmpeg_codecs.55.64bit.dylib`
Homebrew creates these:
```
main@MacBook ~/h/C/f/4/lib> ls
libavformat.58.76.100.dylib  libpostproc.55.dylib
libavcodec.58.134.100.dylib  libavformat.58.dylib         libpostproc.a
libavcodec.58.dylib          libavformat.a                libpostproc.dylib
libavcodec.a                 libavformat.dylib            libswresample.3.9.100.dylib
libavcodec.dylib             libavresample.4.0.0.dylib    libswresample.3.dylib
libavdevice.58.13.100.dylib  libavresample.4.dylib        libswresample.a
libavdevice.58.dylib         libavresample.a              libswresample.dylib
libavdevice.a                libavresample.dylib          libswscale.5.9.100.dylib
libavdevice.dylib            libavutil.56.70.100.dylib    libswscale.5.dylib
libavfilter.7.110.100.dylib  libavutil.56.dylib           libswscale.a
libavfilter.7.dylib          libavutil.a                  libswscale.dylib
libavfilter.a                libavutil.dylib
libavfilter.dylib            libpostproc.55.9.100.dylib
```
It seems Audacity is hardcoded to only accept certain filenames: https://github.com/audacity/audacity/blob/0b3ba4fd7075ff96c59b04538cefe132056713cd/src/FFmpeg.cpp#L180-L192
https://github.com/audacity/audacity/blob/b630259884e84d5039304b01e48fa33c93958a1d/libraries/lib-ffmpeg-support/FFmpegFunctions.cpp#L125-L137

**Additional context**
N/A, maybe later

**Comment by crsib** [comment]
Audacity 3.1+ should be able to load `libavformat.58.dylib` just fine (i.e., just pasting the full path should help), although the "FindFFmpegDialog" dialog needs fixing...

I will check, but just one small question - do you have an Intel Mac?

**Comment by wildwestrom** [comment]
@crsib Yes, it is an Intel Mac.

**Comment by wildwestrom** [comment]
Ok, it seems to load `libavformat.dylib` okay.
I had to navigate manually instead of putting in the full path.
![Screen Shot 2021-12-13 at 14 23 49](https://user-images.githubusercontent.com/77174844/145875031-97ac4351-0a2a-4950-b448-e16d330e1cb9.png)

**Comment by wildwestrom** [comment]
It should either be clear that the text box to input the path does nothing, or fix that functionality. Right now the only way to change the dylib path is to use the `Browse...` dialog.

**Comment by crsib** [comment]
Turns out that the check was very confusing (and quite wrong). It was expected that the path would be a full path to a dylib.
