### ISSUE TITLE
The Journaling Tool. Audacity crashes at replaying the comand of a clip generating

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2284]
**Is your feature request related to a problem? Please describe.**
The Journaling tool hasn't been able to journal and replay the clip-generating commands such as Chirp, DTFM tones, Noise, Silence,     Tone.

**Describe the solution you'd like**
I would like to have a feature of journaling and automated replaying for generating
In the current version, Audacity just crashes in an attempt of replaying this type of command.

**Comment by dozzzzer** [comment]
I ran repeatedly into the same issue: when playing a journal.txt file, Audacity freezes.
STR:

1. Open Audactiy with the "Write Journal" option enabled
2. Generate > DTMF tones... > OK
3. Quit and confirm
4. Launch Audacity via Terminal with the path to the journal file

Act. result: Audacity launches, creates a blank track and freezes
Exp.: Audacity launches, creates DTMF tones track and quits

OS: MacOS Big Sur 11.6
Audacity version: [audacity-macOS-3.2.0-alpha-20220329+defe745-universal](https://github.com/audacity/audacity/suites/5847072124/artifacts/196742830
[journal.txt](https://github.com/audacity/audacity/files/8380006/journal.txt)

https://user-images.githubusercontent.com/70063970/160824247-0e5e8cba-bf34-4e55-9144-68932cba8bce.mp4

)
