### ISSUE TITLE
Audacity Rendering Performance

### ISSUE THREAD

**Issue by crsib** [audacity/audacity#2289]
References: #1693

## Goals

The ultimate goal: `OverlayPanel` drawing should be "real-time." More specifically, `TrackPanel::OnPaint` and `AdornedRulerPanel::OnPaint` should have a low enough CPU budget to match the VSync rate without messing up with the audio engine.

Sub-goals:
* No more drawing outside the `paint` event. macOS doesn't support it adequately anymore.
* No more Erase/Draw hacks. They are expensive with modern display resolutions.
* Do not use wxDC functions:
  * Windows uses GDI, which is slow per se.
  * Path rendering is used even when it shouldn't be. 
  * Batching is not possible. 
* Do not use path rendering for waveform RMS display.

## Proposed implementation

* Façade for "vector" graphics
  *  `wxGraphicsRenderer` will do the trick for Windows and macOS (will it?) for path-rendering.
     *  Linux performance is under the question. Cairo is not real-time. CoreGraphics is CPU-based as well and doesn't work well when asked to render thousands of lines either.
     * Probably we will have to have separate Direct2D, CoreAnimation and OpenGL (?) implementation, falling back to `wxGraphicsRenderer`
  * A new cache for time-domain data
  * A new approach for "levels" rendering: waveform and spectrum plots. The current approach renders thousands of lines, which is slow.
   * A pure software approach just setting pixels.
   * Potentially hardware accelerated approach:
     * OpenGL
     * Direct3D
     * Metal (OpenGL will work on macOS as well)
   * Hardware  gradient for spectrum view (?)

**Comment by Paul-Licameli** [comment]
Will this new facade incidentally help replatforming too?
