### ISSUE TITLE
Dock icon is duplicated on elementaryOS when run as flatpak

### ISSUE THREAD

**Issue by stan-janssen** [audacity/audacity#2292]
**Describe the bug**
When audacity is run as flatpak on elementaryOS, the dock icon gets duplicated, because the Dock cannot associate Audacity's main window with the flatpak application we just launched.

This can be easily solved by explicitly specifying the StartupWMClass in the `.desktop` file, for which I have a [pull request](https://github.com/audacity/audacity/pull/2293) available.

**To Reproduce**
1. Install audacity from flathub on elementaryOS
2. Launch audacity
3. Observe that a second icon in the dock appears next to the just-launched audacity icon. This second icon persists while the first disappears after a few seconds.

**Expected behavior**
The Audacity dock icon is  stable and is associated with the running application.

**Screenshots**

![audacity](https://user-images.githubusercontent.com/12174852/146329875-78fe8823-764b-4d6d-b39b-2417811055f5.gif)

**Additional information (please complete the following information):**
 - OS: elementaryOS 6
 - Version 3.1.2 (flathub)

**Comment by sempasha** [comment]
Same problem with [qBittorrent](https://www.flathub.org/apps/details/org.qbittorrent.qBittorrent)
