### ISSUE TITLE
Scrub preview doesn't appear

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#2294]
**To Reproduce**
Transport > Scrubbing > Scrub Ruler
Just move the mouse (in the Scrub Ruler)
Compare 3.1.0 with earlier behavior.

**Expected behavior**
Green line on the tracks and double-headed arrow on the scrub ruler

**Comment by petersampsonaudacity** [comment]
Testing on W10 I confirm that this is a regression on 3.0.5

**Comment by petersampsonaudacity** [comment]
@Paul-Licameli is the green line missing in the tracks related to the white line missing when hovering in the Timeline?

See Issue #2122

**Comment by Paul-Licameli** [comment]
Lik

> @Paul-Licameli is the green line missing in the tracks related to the white line missing when hovering in the Timeline?
> 
> See Issue #2122

Likely so.  I call attention to this as a separate matter for QA to verify.  I also hope QA will do more testing of scrubbing and Design will suggest how to improve this user interface that never wholly satisfied us.

**Comment by Paul-Licameli** [comment]
Problem bisects to 11627702b919566c9c186e2501916a4708faf8ab

**Comment by petersampsonaudacity** [comment]
Tested on W10 with latest 3.1.3 alpha build Audacity_Windows_64bit_1602134390_7887ba0

This looks good to go
