### ISSUE TITLE
The GUI for Screenshot Tool could do with serious improvement

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2306]
**Describe the bug**
The GUI for Screenshot Tool is very poor and hard to use leading to poor UX.

Flagging @Tantacrul as this is a UX issue

**To Reproduce**
1. Tools > Screenshot
2. Observe:  messy hard to use GUI

**Expected behavior**
A much better GUI and UX

Recent testing work has ked me to look closely at Screenshot Tools - and what is apparent is that the GUI is atrocious (bewildering and intimidating to the user) to the extent of letting us down.

It has three sections each with a bewildering array of buttons.

These sections should be capable of being replaced with three dropdown menus. With a sensible set of defaults for the three settings many users could then just press an OK button.  Plus we should have a Cancel button.  Note that there are no such clear action keys on the current dialog pane.

These cahnges would make this dialog much more consistent with other dialogs in Audacity, making it more Audacity-like and a lot more usable at the same time.

We could also add a Help button to link the user to the appropriate Manual page (as has been proposed for effects).

The default file lcation is not ideal either
i) on Windows it offers C:\Users\<user-name>
ii) on macOS it offers /Users/<username>

We should instead offer the same default as we have reset for 2.1.3 for Exports
i) on Windows C:\Users\<user-name>\Documents\Audacity
ii) on Mac /Users/<username>/Documents

**Screenshots**
![image](https://user-images.githubusercontent.com/50205984/146646840-61e21e39-e029-445b-be62-2a417527268d.png)

**Additional information (please complete the following information):**
 - OS: Windows 10 and Mac - assume all OS
 - Version:  Audacity 3.1.2/3.1.3 alpha/3.2.0 alpha

**Additional context**
This was originally logged on Bugzilla as ENH 1598
https://bugzilla.audacityteam.org/show_bug.cgi?id=1598

Audacity offers as the default location for the  screenshot image to be in the user's top level directory - this is far from good practice.

There is an option to change the target location (which mitigates this), but:
a) this user didn't spot that and ploughed straight on to the capture
b) the default of the users' top level directory is not a good default setting.

It would be far more sensible to offer as a default the user's "Documents" folder - or better still Documents>Audacity.

**Comment by LWinterberg** [comment]
We won't be improving this particular mess of a button minefield. If anything, we'll replace it with the short version (and maybe add a browse button next to the path)
![Screenshot from 2022-04-08 21-09-23](https://user-images.githubusercontent.com/87814144/162508744-7b445bd9-caed-4f32-ab17-e4df30f09cbd.png)
