### ISSUE TITLE
Incorrect cursors/pointers for Tool grabbers

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2307]
**Describe the bug**
The cursor used for the Tool grabbers for all tools in the tooldocks are incorrect (according to both Microsoft and Apple design guidelines - and in line with common usage elsewhere in most other apps)

What is used is the normal arrow pointer - when it should be the hand grabber.

See:
a)  https://docs.microsoft.com/en-us/windows/win32/uxguide/inter-mouse
b)  https://developer.apple.com/design/human-interface-guidelines/macos/user-interaction/mouse-and-trackpad/

**To Reproduce**
1. Hover over any of the toolbars, but nor in the left-hand grab-bar
2. Observe: the cursor/pointer is a north-west arrow
3. move the cursor leftwards to be over the grab-bar
4. Observe: the cursor remains as the north-west arrow

**Expected behavior**
a) on hovering over any Tool grab-bar the cursor/pointer should be the open-hand (to indicate the possibility of dragging)
b) On clicking there the cursor/pointer should change to the closed hand for the actual drag and reposition 

**Screenshots**
Can't do this as screenshots don't capture the pointers

**Additional information (please complete the following information):**
 - OS: Windows 10 and macOS 12.0.1 Monterey- but assume all OS
 - Version Audacity - all including all 3.1.x and 3.2.0 alpha

**Additional context**
@Tantacrul  - flagging this as a UX issue
Changing the pointer to the hand-grabber would be a good visual cue to indicate to the the user that a tool can be moved or undocked - making this facility much more "discoverable".

Note that we use the closed-hand pointer when we move a track by clicking in the gray (empty) area of the Track Control Panel to move it (and this was changed to be so after similar discussion to this).

**Comment by petersampsonaudacity** [comment]
See also:   Redesign cursors #2247

**Comment by Tantacrul** [comment]
100% we need to do this

**Comment by petersampsonaudacity** [comment]
See also:   Incorrect cursor/pointer for moving/dragging Loop Regions #2456
