### ISSUE TITLE
FFMPEG Version 59 Support

### ISSUE THREAD

**Issue by CanadianJeff** [audacity/audacity#2311]
this is a semi duplicate of pull request #1623 

ffmpeg had a major bump from 58 to 59 (Apr 7th 2021) audacity does not yet support version 59

https://github.com/FFmpeg/FFmpeg/commit/85ba17f36dbfde1baeaa47e14d30c337add52c0d#diff-71c3db3f92e0a37cdf32f89ad4b90183704a7c1b62e38f0fdf7d4220609e0305

loading this version in will yield version (58.77.100) as shown in the screenshot

https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2021-03-31-12-39/ffmpeg-N-101776-gd4575982f4-win64-lgpl-shared.zip

![](https://i.imgur.com/Og2Zszp.png)

**Comment by crsib** [comment]
We will add 59 right after it's released. The latest release is 4.4.1 "Rao" packaging avformat 58.76.100

**Comment by CanadianJeff** [comment]
in that case gonna close this feel free to reopen

**Comment by CanadianJeff** [comment]
January 17th, 2022, FFmpeg 5.0 "Lorentz"

**Comment by LWinterberg** [comment]
#2445
