### ISSUE TITLE
Glitch at the end of playback.

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#2314]
**Describe the bug**

**To Reproduce**
1. Generate a few seconds of a tone
2. select some audio within this
3. playback
4. There's a "glitch" at the end

**Expected behavior**
No glitches!

**Screenshots**
Audio selected in Audacity:
![image](https://user-images.githubusercontent.com/11887021/146763062-ee0e96d8-6fb0-4a6a-9d8b-fa1aecdba675.png)

Playback recorded using loopback in Reaper - note spurious audio after the correct audio has been played:
![image](https://user-images.githubusercontent.com/11887021/146763182-a6ae9e71-6e5d-42fd-b049-24f2d7614dba.png)

Using Audacity 3.1.2, same project, recorded using loopback in Reaper - no spurious audio:
![image](https://user-images.githubusercontent.com/11887021/146763994-08a1f99f-fc26-4b6e-b70d-95a796979b69.png)

**Additional information (please complete the following information):**
- Audacity 3.1.3 commit: fa4ef2
- Windows 10

**Comment by DavidBailes** [comment]
Using chirp instead of tone to give more info as to what spurious audio is being played:
Audio selected in Audacity:
![image](https://user-images.githubusercontent.com/11887021/146765583-23d72ed5-6dac-49ad-9865-955fe82fa48a.png)

Using Audacity 3.1.3, playback recorded using reaper:
![image](https://user-images.githubusercontent.com/11887021/146766108-04a3863c-26b2-4b12-9075-9dc582df0680.png)

Using Audacity 3.1.2, playback recorded using reaper:
![image](https://user-images.githubusercontent.com/11887021/146765799-eb5b1309-e68d-4b1d-8058-ca6e410b0f38.png)

**Comment by petersampsonaudacity** [comment]
Confirmed on W10 with altest 3.2.0 alpha

And I have a sneaking suspicion it's related to:   Play-at -Speed with a selection gets stuck in Play mode #2316

**Comment by Paul-Licameli** [comment]
> Confirmed on W10 with altest 3.2.0 alpha
> 
> And I have a sneaking suspicion it's related to: Play-at -Speed with a selection gets stuck in Play mode #2316

No, not related

**Comment by Paul-Licameli** [comment]
The problem bisects to 81f74f72485c81dc90e21894270e9bea34e03a0a

I can fix it by increasing the numbers in `NewDefaultPlaybackPolicy::SuggestedBufferTimes` such as to `0.05, 0.05, 0.25` but this will have the consequence of making the response to the changing slider more laggy.

**Comment by DavidBailes** [comment]
> I can fix it

Please fix it. If a user selects some audio for playback, then that audio should be played back - not the audio and bit of what comes afterwards. This could lead to inaccurately positioned edits. If this bug remains in 3.1.3 then I won't be using it.

**Comment by Paul-Licameli** [comment]
> > I can fix it
> 
> Please fix it. If a user selects some audio for playback, then that audio should be played back - not the audio and bit of what comes afterwards. This could lead to inaccurately positioned edits.

I fear endless rounds of grief if I do it that way, because the complaint about lagginess will predicatably follow.  I hope to find a different way that can reconcile both demands but it is not obvious yet.

Adjustable play-at-speed really is getting a total reimplementation so it can also accomodate loop region changes on the fly.
