### ISSUE TITLE
Play-at -Speed with a selection gets stuck in Play mode

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2316]
**Describe the bug**
When you use Play-at-Speed to play a selection, once playback of the selection has finished Audacity appears to be stuck in Playback mode with the play cursor flickering at the end of the selection (sometimes the beginning) and with the Play button down (see attachment)

It looks like using Play-at-Speed leaves Audacity in play mode - as clicking on the Stop button causes the flickering play cursor to disappear and the Play button becomes "up".

This behavior is inconsistent with use of the normal Play button where the play cursor disappears once the playback of the selection is completed.

**To Reproduce**
1. Generate 30 second chirp
2. select from 10-15 seconds
3. press Play-at-Speed
4. Observe: after the selection plays the green play cursor remains and flickers (sometimes at the end but more often returns to the beginning of the selection)
5. Now move the PAS slider
6. Observe: the selection gets played once more
7. Observe: the green play cursor remains and is flickering

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/50205984/146781398-c18f2196-5534-4ac9-94a4-d28749e5b85a.png)

**Additional information (please complete the following information):**
 - OS: Windows 10 - but assume all OS
 - Version:  latest 3.1.3 alpha build Audacity_Windows_64bit_1602134390_7887ba0

**Additional context**
This is a regression on 3.1.2 and all earlier Audacities

**Comment by petersampsonaudacity** [comment]
This is a residual issue from  Play-at-Speed has reverted to being non-dynamic #2149

**Comment by petersampsonaudacity** [comment]
I have a sneaking suspicion that this is related to:   Glitch at the end of playback. #2314

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @Paul-Licameli 's latest brabnch build Audacity_Windows_64bit_1611009809_e4601c5 

This issue looks to be fixed on Windows

**Comment by Paul-Licameli** [comment]
@petersampsonaudacity @LWinterberg 
This issue needs to be REOPENED, for the development branch (3.2) only.  I think GitHub only lets Leo do that, as the one who closed it.
I think commit bedc1d87a1af8c5b6eba7ecef26e394d7ed88972 is at fault.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with audacity-win-3.2.0-alpha-20220104+109e94f-64bit

I confirm that once again this fails

**Comment by petersampsonaudacity** [comment]
Testing on W10 and macOS 12.5.1 Monterey  today's latest 3.2.0 build  
https://github.com/audacity/audacity/actions/runs/3081056287

This no longer occurs - presumably fixed by some or other refactoring change.

Accordingly I shall close this issue
