### ISSUE TITLE
Clicking in a label's text box fails to move the cursor

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2319]
**Describe the bug**
Clicking in a label's text box fails to move the cursor to the point label position (or select the audio with the range of a region label).

This is a regression on 3.0.5 - and was a useful and easy way for the user to move the cursor or play region to a precise location

Originally reported by a Forum user in this post@
https://forum.audacityteam.org/viewtopic.php?f=70&t=122256

**To Reproduce**
1. Generate a 30 second chirp
2. create a point label at 10 seconds
3. Create a range label from 15-20 seconds
4. Click at 5 seconds to move the cursor
5. Click in the text box of the point label
6. Observe: the cursor remains at 5 seconds
7. Click in the text box of the region label
8. Observe: the cursor remains at 5 seconds

**Expected behavior**
When a label's text box is clicked:
a) for a point label the cursor should move to that position,
b) for a region label the audio within the range of that label should be selected.

**Screenshots**
![image](https://user-images.githubusercontent.com/50205984/146803593-a847f7dd-9a4e-4945-8516-447c8985f9ad.png)
**Additional information (please complete the following information):**
 - OS: Windows 10 - but assume all OS
 - Version: Audacity 3.1.2, and latest alphas for 3.1.3 and 3.2.0

**Additional context**
a) There is mitigation for region labels as you can now click on the label's drag-bar.
b) There is **_no_** mitigation for point labels as there is no drag-bar for a point label.

Flagging @Tantacrul as this is a UX issue

**Comment by petersampsonaudacity** [comment]
There are no drag-bars for a point label - but a point label can be moved with the circle in the grabbers - so perhaps clicking on that could be an action to move the cursor there - but note that this requires precise clicking as
a) a small movement will move the label
b) a click slightly off target could land on one of the chevrons and this could accidentally create a region label  - _don't ask me how I know, i have been burnt by just this in the past ..._

![image](https://user-images.githubusercontent.com/50205984/146804624-e2c8ae6e-850a-4193-be6e-20fa36a053ea.png)

**Comment by petersampsonaudacity** [comment]
This also means that if the next label is off-screen not currently in the window then tabbing to it in the label track will no longer move the audio so that the label and its associated audio is show,

_I just got burned by this and it took me a while to figure out what was occurring._

**Comment by DavidBailes** [comment]
> if the next label is off-screen not currently in the window then tabbing to it in the label track will no longer move the audio so that the label and its associated audio is show

Already logged:
https://github.com/audacity/audacity/issues/2078

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
