### ISSUE TITLE
 Zoom cursor should not have "+" sign iconography

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2327]
**Describe the bug**
The cursor used for zooming has confusing, inconsistent, iconography with a "+" sign regardless of whether you are zooming in or out.
### 
1) Multi-Tool
when right clicking on the waveform in Multi-Tool mode when you right click to zoom out the zoom cursor magnifying glass icon has a "+" plus-sign on it.  This is inconsistent with the Zoom toolbar where plus-sign indicates zoom-in not out.

It's OK for right click&drag as that is a zoom-in to the zoom selection.

### 2) Zoom Tool
Similarly with the zoom tool the zoom cursor magnifying glass icon has a "+" plus-sign on it regardless of whether you are
a) left-click, zooming in or
b) right-click zooming out

This cosmetic issue was originally reported on the Forum by user CliffyPop
https://forum.audacityteam.org/viewtopic.php?p=424807

**To Reproduce**
1) get some audio
2) switch to Multi-Tool
3) right click in the waveform and hold the right mouse button down
4) Observe: magnifying glass cursor has a +" sign
5) release the right mouse button
6) Observe: Audacity zooms out x2 (expected behavior)

**Expected behavior**

**Screenshots**
The zoom cursor magnifying glass icon should really have no "+" or "-" iconography displayed on it.

**Additional information (please complete the following information):**
 - OS: Windows 10 - but assume all OS
 - Version: Audacity 3.2.0/3.1.3 and earlier
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]

**Additional context**
Originally logged on Bugzilla as P4 2773
https://bugzilla.audacityteam.org/show_bug.cgi?id=2773

Flagging @Tantacrul as he previously expressed an interest in Audacity's many magnifying glasses

**Comment by petersampsonaudacity** [comment]
There are two P2s in the Manual noting this issue in note divs.   

These note divs can be removed if and when this issue gets resolved:
a) https://alphamanual.audacityteam.org/man/Zoom_Tool#Zooming_out
b) https://alphamanual.audacityteam.org/man/Multi-Tool

**Comment by gerhean** [comment]
I am a new contributor and I would like to take on this problem, but I am not sure if this issue is already taken.

**Comment by LWinterberg** [comment]
There is nobody working on this currently @gerhean

**Comment by gerhean** [comment]
Actually does it make sense if holding down the right mouse button switches it from "+" sign to a "-" sign?

**Comment by petersampsonaudacity** [comment]
If I were doing it I would probably use a simple magnifying glass icon with no plus or minus sign for both the zoom-in and the zoom-out.

_Just as the magnifying glass icon for the Zoom tool in the Tools toolbar is a plain magnifying glass with no plus or minus - and that tool facilitates control of  both zoom-in and zoom-out._

**Comment by petersampsonaudacity** [comment]
Also be aware of this logged UX/GUI issue

 Redesign cursors #2247

**Comment by PrateekBaluni** [comment]
Hi,  I'm a new contributor and I would like to take on this problem. But i'm not sure that whether this issue is already take by someone

**Comment by surajbhola** [comment]
I am a new contributor; I think I can solve this issue please guide me where I can find that particular file in the complete repository, and what are the steps to move further!?

**Comment by gerhean** [comment]
Sorry I'm not really working on this anymore, feel free to work on it.

The file to look at is `.\src\tracks\ui\ZoomHandle.cpp`

**Comment by petersampsonaudacity** [comment]
Note that the Zoom tool has been removed from Audacity's Tools Toolbar for version 3.2.0 onwards.

**Comment by Tantacrul** [comment]
Yes. Let's close this issue for that reason.
