### ISSUE TITLE
Audacity crashes at startup

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2329]
**Describe the bug**
Audacity crashes at startup on Windows

**To Reproduce**
1. Close a project without saving in a previous Audacity version to get the project recovery dialog at Audacity startup
1. Download the latest 3.1.3 Windows build 
2. Launch Audacity
3. Click the Skip button:
![изображение](https://user-images.githubusercontent.com/25851359/147058035-bb42f2b8-23ab-433c-b8e2-87e6b63282fa.png)

4. Just wait for a few seconds.

 **Additional context**
 Crashes both on macOS and Windows

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest 3.1.3 alpha Audacity_Windows_64bit_1609129642_e1da409 

I created a crashed project in 3.1.2 - crashed with Task Manager ank killing the Audacity process tree (the most extreme crash with TM)

I confirm the Skip button crashes Audacity as reported

But also Discard and Recover buttons also cause the crash 

_I did use the Send button for ET to phone home the crash reports_

**Comment by LWinterberg** [comment]
fixed by https://github.com/audacity/audacity/commit/e939c8e24ba02b645c049968ecdab48524ab4807

**Comment by petersampsonaudacity** [comment]
Tested on W10 with Audacity_Windows_64bit_1610683695_e939c8e 

I confirm that this looks to be fixed on Windows

a_) no crash with use of the Skip button

b) using the Recover button properly makes the recovery

c) the Discard button works properly too

**Comment by petersampsonaudacity** [comment]
@crsib - thanks for fixing this so quickly Dmitry
