### ISSUE TITLE
Screenshot tool tracking bug

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#2335]
- #2336
- [x] #2306 
- [ ] #1608
- [x] #1611
- [ ] #1378 
- [x] #1554

**Comment by petersampsonaudacity** [comment]
> * Should the screenshot tool be deprecated? #2336

I would vote for deprecating it. 

In all the images I #captured for the manual over the years (and there were very many) I never used the screenshot tool.  Rtaher I used the Windows Print Screen button and MS Paint to perform any trims or edits.

Mac too has perfectly good screen capture tools - albeit accessed by shortcuts and not a simple "discoverable" button on the keyboard.

If the screen shot tool were to be retained it would a lot of improvement, particularly in the GUI - and for my money that would represent a poor ROI.

**Comment by Penikov** [comment]
I don't think we should rid of the Screenshot tool. There is a tool called UI Vision. It could be integrated into Jenkins CI. 
We can set up Jenkins as a separate CI for automated tests. UI vision can capture the whole screen, but it works slow comprising a small image of the part of  UI. 
Better if we just point UI Vision to a folder with a set of reference images. The screenshot tool provides that. Apart from that, UI Vision works more precisely with small pictures than with full-screen images.

Yes, honestly, I do not use that tool in my daily testing. But if we talk about the coverage, developing Continuous Testing processes - that tool will be very useful.

**Comment by LWinterberg** [comment]
general thinking for now is to keep the screenshot tool 2 (with the dropdown) around for QA purposes into 4.x, but to not really put in any effort into the many-buttons screenshot tool. in each case, it's not going to be touched any time soon.
