### ISSUE TITLE
<tgmath.h> header deprecated

### ISSUE THREAD

**Issue by gerhean** [audacity/audacity#2344]
**Describe the bug**
`<tgmath.h>` header is used in `BrushHandle.cpp`, but it is officially deprecated.

**To Reproduce**
1. Followed Windows instruction to build Audacity from `BUILDING.md`
2. In step 7, Visual Studio gave this error: `Cannot open include file: 'ctgmath.h': No such file or directory	Audacity` for the file `audacity\src\tracks\ui\BrushHandle.cpp`.	

**Expected behavior**
Step 7 should be executed with no problem. 

**Screenshots**
![image](https://user-images.githubusercontent.com/16630400/147346653-5b90ba84-265c-4426-9791-162c68978e85.png)

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Visual Studio Community 2019
 - Not sure what compiler is being used
 - Master branch

**Additional context**
According to the [Microsoft Documentation for Visual Studio 2022](https://docs.microsoft.com/en-us/cpp/standard-library/ctgmath?view=msvc-170), the `<ctgmath>` header is deprecated in C++17 and removed in C++20.

I checked the repository, and the `<tgmath>` header is not used anywhere else.

The `<ctgmath>` header is effectively replaced by the C++ overloads in `<complex>` and `<cmath>`, but I did not notice the file `BrushHandle.cpp` using any functions from `<complex>`. In fact, replacing `<tgmath>` with just `<cmath>` allowed Visual Studio to compile the application with no errors.

**Comment by gerhean** [comment]
I am a first time contributor to Audacity, and I want to try making a PR to solve this, but I am not sure if this the correct procedure.

**Comment by crsib** [comment]
This is odd, as I do not have this problem with local 2019/2022 and 2019 on CI. You are more than welcome to fix that, though! Making a PR is a proper way.
