### ISSUE TITLE
Build on stock Impish fails

### ISSUE THREAD

**Issue by monochromec** [audacity/audacity#2354]
**Describe the bug**

Build attempt according to instructions at https://github.com/audacity/audacity/blob/master/BUILDING.md fails
with the following error message:

/usr/bin/cc    -o CMakeFiles/cmTC_3b5f9.dir/SIZEOF_OFF64.c.o -c /home/user/build/CMakeFiles/CheckTypeSize/SIZEOF_OFF64.c
/home/user/build/CMakeFiles/CheckTypeSize/SIZEOF_OFF64.c:27:22: error: ‘off64_t’ undeclared here (not in a function); did you mean ‘off_t’?
   27 | #define SIZE (sizeof(off64_t))
      |                      ^~~~~~~
/home/user/build/CMakeFiles/CheckTypeSize/SIZEOF_OFF64.c:29:12: note: in expansion of macro ‘SIZE’
   29 |   ('0' + ((SIZE / 10000)%10)),
      |            ^~~~
gmake[1]: *** [CMakeFiles/cmTC_3b5f9.dir/build.make:85: CMakeFiles/cmTC_3b5f9.dir/SIZEOF_OFF64.c.o] Error 1

**To Reproduce**
1. Get sources
2. Prepare cmake environment with `cmake  -G "Unix Makefiles" -Daudacity_use_ffmpeg=loaded -DCMAKE_BUILD_TYPE=Release ../audacity`

**Expected behavior**
Successful build

**Additional information (please complete the following information):**
 - OS: Ubuntu 21.10
 - Version Audacity 3.1.3
 - gcc/g++ 11.2.0
 - cmake 3.18.4

**Additional context**
Please let me know if more information is required - happy to help.

**Comment by sunsdy2018** [comment]
I have the same problem. My environment is :
OS: Ubuntu 20.04 
Version Audacity: 3.1.3
gcc/g++: 9.3.0
cmake: 3.16.3

**Comment by monochromec** [comment]
Any progress on this?

**Comment by LWinterberg** [comment]
works for me on 22.04
