### ISSUE TITLE
Enh: Meter options in Mixer Board

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2355]
**Describe the bug**
The Mixer Board has no options or facility for metering independent of the main Audacity window - just pan and gain

Originally logged as ENH Bug 2190 on Bugzilla
Bug 2190 - Enh: Meter options in Mixer Board 
https://bugzilla.audacityteam.org/show_bug.cgi?id=2190

**To Reproduce**
1. Get a few tracks
2. View > Mixer Board
3. Observe: there are no metering options - just pan and gain

**Expected behavior**
Metering options to be added to the Mixer Board

**Screenshots**
![image](https://user-images.githubusercontent.com/50205984/147677302-e0c49ec7-dc0c-48d1-95be-c83861570c4c.png)

**Additional information (please complete the following information):**
 - OS: Windows 10 and macOS 12.0.1 Monterey - but assume all OS
 - Version Audacity 3.1.3 and previous

**Additional context**
None

Flagging @Tantacrul as a UX/GUI issue

**Comment by LWinterberg** [comment]
Mixer improvements are planned: 
* #1024
