### ISSUE TITLE
Windows: no input stream for WASAPI loopback freezes recording without warning

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2356]
**Describe the bug**
On Windows if there is no input stream for WASAPI loopback freezes recording (or fails to start recording) without warning,

Originally logged on Bugzilla
Bug 1911 - ENH: Windows: no input stream for WASAPI loopback freezes recording without warning
https://bugzilla.audacityteam.org/show_bug.cgi?id=1911

**To Reproduce**
1. Launch Audacity on W10
2. set Host to WASAPI
3. Set input device to loopback
4. Ensure no audio is playing (or paused) on the PC
5. Press Record
6. Observe: red recording cursor stats at T=0 and no recording occurs
7. Observe: in particular, no waning message is shown

**Expected behavior**
A warning message to advise the user that there is no audio stream present

**Screenshots**
![image](https://user-images.githubusercontent.com/50205984/147678571-33544101-ad69-4361-b335-76b161823308.png)

**Additional information (please complete the following information):**
 - OS: [e.g. Mac High Sierra, Ubuntu 18.04, Windows 10]
 - Version [e.g. Audacity 2.5.1]
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]

**Additional context**
One of my testers who was testing Bugzilla 42 https://bugzilla.audacityteam.org/show_bug.cgi?id=42 
fell foul of this and initially assumed that Timer record was at fault when it turned out to be his soundcard.  The user pointer out that Foobar , in contrast, does report the absence of an audio stream.
So if Foobar can do this then one assumes that Audacity could do similar.

We get many, many, reports of this from very confused users on the Forum and the Facebook channels, puzzled as to why their recording won't start or that it stops mid-recording unexpectedly.

Flagging this for @Tantacrul  as a UX issue

**Comment by petersampsonaudacity** [comment]
@SteveDaulton  wrote in the Bugzilla thread

>Perhaps we should pop up a message if Audacity is left waiting too long.
>Example:
>"Waiting for audio stream to start."
>
>and close automatically when the audio stream is detected.

**Comment by LWinterberg** [comment]
see also #1480

**Comment by LWinterberg** [comment]
closing in favor of https://github.com/audacity/audacity/issues/1480
