### ISSUE TITLE
Import Raw Floating Point PCM File

### ISSUE THREAD

**Issue by CanadianJeff** [audacity/audacity#2357]
after a few days of poking at this I have gone crazy.....
https://streamable.com/pxgji8

ffprobe will detect my audio stream as
`Stream #0:0: Audio: pcm_f32le, 48000 Hz, stereo, flt, 3072 kb/s`

which does translate into "pcm" "floating point" "32bit" "little endian"
but when using that in audacity import raw it just plays as static

**Comment by LWinterberg** [comment]
Via @SteveDaulton on discord: https://www.jazz2online.com/articles/288/j2b-format/

j2b is deflate-compressed (like a ZIP file) so importing it as raw won't work.
