### ISSUE TITLE
Inconsistent quoting of names with '...' or "..." or not at all in user-visible messages

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2362]
**Describe the bug**
Throughout the app there is inconsistent quoting of names with '...' or "..." or not at all in user-visible messages

This was originally logged by @Paul-Licameli  in September 2017 on Bugzilla
https://bugzilla.audacityteam.org/show_bug.cgi?id=1747

**To Reproduce**
1, Scan the source code for '%s'
2. Then scan it for \"%s\"
3. Observe: There should be consistency.  The first seems to preponderate, but the second are not very few.
4. Besides this, there are probably many names left unquoted in messages, but not so easily listed.

**Expected behavior**
Consistency in the grammar used for user-visible messages

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS: all

**Additional context**
Flagging for @Tantacrul as a UX design issue

**Comment by Paul-Licameli** [comment]
Whichever is chosen, it might be nicer to use smart quotes, but they are non-unicode characters, and if used in C++ string literals, they might cause problems for xgettext

**Comment by Aamir-Ansari-almost** [comment]
Greetings!
I would love to take up this issue.
So are we supposed to replace all the "...." with '....', or the other way around?

**Comment by HarshAulakh** [comment]
Hi all, I would love to pick this up. I have setup and build the project and looking for good first issue.

**Comment by LWinterberg** [comment]
I think a good first step for this is to investigate whether Unicode (ie U+201C and U+201D) does cause problems with xgettext, or anything else for that matter. I see that [there is a parameter](https://www.gnu.org/software/gettext/manual/html_node/xgettext-Invocation.html) to switch from default ASCII to Unicode. I personally would prefer double smart quotes if they're possible, if not, normal double quotes.

For the actual finding and replacing of strings, you two could collaborate together @HarshAulakh @Aamir-Ansari-almost.  It seems to be a lot of work, particularly adding missing quotes.

**Comment by himanshi-2602** [comment]
@HarshAulakh and @Aamir-Ansari-almost  are you guys working on this issue?? even I am also interested in working on this issue
@LWinterberg can you assign me this issue if no one is working?

**Comment by Aamir-Ansari-almost** [comment]
Yes, I am working on the issue

**Comment by LWinterberg** [comment]
alright @HarshAulakh @Aamir-Ansari-almost @himanshi-2602, feel free to figure out a way to work together on this. You can use the [dev server](https://audacityteam.org/devserver) to talk to each other if necessary. 

Alternatively, here's some other issues you can work on: https://github.com/audacity/audacity/projects/15

**Comment by darkthunder0** [comment]
hey can i also help in this issue ................. @LWinterberg

**Comment by Midas847** [comment]
Hey guys, midas here. If you don't mind can I take up this issue?

**Comment by LWinterberg** [comment]
Why are y'all piling up onto this bug? There already are 3 people working on it, while we still have many, many unclaimed things on [this project board](https://github.com/audacity/audacity/projects/15)

**Comment by LWinterberg** [comment]
on second thought, this would just take up a lot of time for not much gain. Let's not do this.
