### ISSUE TITLE
Clipping indicators in Mixer Board cannot be cleared without restarting playback

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2364]
**Describe the bug**
The Clip indicators in the Mixer Board cannot be cleared without restarting playback.

This is inconsistent with the clip indicators in the Audacity Meter Toolbars which can be cleared during playback (or recording) by clicking on the meters.

Both the Mixer Board meters and the main meters reset the clip indicator on restarting playback.

Originally logged on Bugzilla in January 2017 by @SteveDaulton 
https://bugzilla.audacityteam.org/show_bug.cgi?id=1581

**To Reproduce**
1. Get some audio with and without clipping - see screenshot
2. View > Mixer Board
3. Start Playback in a clipped section of audio
4. When audio reaches a non-clipped section:
5. click on the main Playback meter
6. Observe: the red clip indicator (shows that clipping HAS occurred previously) is reset to off
7. click on the meters in the Mixer toolbar
8. Observe the clip indicator is not similarly reset (see screenshot)

**Expected behavior**
For consistency the Mixer Board's clip indicators should be reset and cleared when the user clicks on the meter

**Screenshots**
![image](https://user-images.githubusercontent.com/50205984/147766015-7962f243-ece4-4a9d-8be7-f15f1b291266.png)

**Additional information (please complete the following information):**
 - OS: Windows 10 and macOS 12.0.1 Monterey
 - Version:  Audacity 3.1.3

**Additional context**
@SteveDaulton  wrote in the Bugzilla bug-thread

>In the main meters, the clip indicator may be cleared by clicking on it, but in the Mixer Board the clip indicators cannot be reset other than by restarting playback. There is consensus among QA that it should be possible to clear the clip indicators in the Mixer Board by clicking on them.

Tagging @Tantacrul  as a UX/design issue

**Comment by LWinterberg** [comment]
the mixer needs a major rework, so this will probably will get touched once we do that (see also #1024)
