### ISSUE TITLE
Play-at-Speed speed setting should be saved in audacity.cfg and project

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2365]
**Describe the bug**
The Play-at-Speed speed setting should be saved in audacity.cfg and project, remembered and re-used by Audacity on next launch.

The setting should **_not_** be reset to 1x at the start of each new project or session. 

This was originally logged on Bugzilla by Gale Andrews back in 2014
https://bugzilla.audacityteam.org/show_bug.cgi?id=711

**To Reproduce**
1. Use play at speed and set it to x3.
2. Restart Audacity
3. Observe: The play slider is back to x1.

**Expected behavior**
When you open a new project window, its Play-at-Speed slider should take the slider setting from the audacity.cfg settings file, so it will have the same value as any previous project you had open. If you move the slider in the mew project window, the slider in the previous project window should remain at its current setting. 

If you explicitly save a project, then that project has the slider setting saved into it and will open at that setting, whatever the current setting in audacity.cfg is.

**Screenshots**

**Additional information (please complete the following information):**
 - OS: W10 and macOS 12.0.1 Monterey
 - Version: Audacity 3.1.3

**Additional context**
@JamesCrook write in the Bugzilla bug-thread
>I prefer a different enhancement where we merge the functionality of 'play-at-speed' and 'play', so that all play is play at speed.  If we do this a few users might not discover how to reset the speed back from chipmunk to x1, and in that case we would want a restart of Audacity to be forgetful and bring us back to x1.
>
>If though someone wants to persist this setting in the Audacity we currently have with two play buttons, I won't stand in their way.

**Comment by petersampsonaudacity** [comment]
Flagging @Tantacrul as a UX/design issue

**Comment by LWinterberg** [comment]
I disagree that play-at-speed should be stored permanently. To me, it feels more of an "in the moment" kinda thing, similar to the currently active tool (selection, envelope, ...) or looping region placement.
