### ISSUE TITLE
Website still states that Audacity is developed by "volunteers"

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2369]
**Describe the bug**
On several pages the Audacity website still states that Audacity is "Developed by a group of volunteers " - in  particular the main page of the website:
https://www.audacityteam.org/

Logging this is we have had several posts on the Forum asking how they can donate as this is a volunteer project - this is just the latest:
https://forum.audacityteam.org/viewtopic.php?f=46&t=122519

Other pages affected:
a) https://www.audacityteam.org/community/
b) https://www.audacityteam.org/community/users/

**To Reproduce**
1. Go Audacity website:  https://www.audacityteam.org/
2. Observe the text:  "Developed by a group of volunteers as open source."

**Expected behavior**
On Discord @SteveDaulton suggested
>"Audacity is free, open source software"

**Screenshots**
1)  Main Webpage
![image](https://user-images.githubusercontent.com/50205984/147873104-8066dd05-c747-491a-bbc7-f2f0376dabf9.png)

2) Get Involved page
![image](https://user-images.githubusercontent.com/50205984/147873303-4d9b0a1f-5a59-49dd-a859-4f471ffe8307.png)

3) Get Involved>Users
![image](https://user-images.githubusercontent.com/50205984/147873394-acadb8ad-4c8d-44b3-b65f-639349c80873.png)
This sentence is basically back to front - it should really say
>Audacity is maintained by a small team of professional designers and developers, in collaboration with an open source community. If you appreciate Audacity and would like to help out, here are some ideas:

**Additional information (please complete the following information):**
 - OS: all
 - Version: Audacity version not applicable

**Additional context**
Flagging @LWinterberg  and @Tantacrul

**Comment by petersampsonaudacity** [comment]
See also:
Too many placeholders in strings making it harder to translate #681 
![image](https://user-images.githubusercontent.com/50205984/147873523-34e859b2-9fd1-4426-b962-dedc7518318a.png)

**Comment by LWinterberg** [comment]
done, thanks!

**Comment by petersampsonaudacity** [comment]
> done, thanks!

@LWinterberg  - many thanks for that. much appreciated :-)
