### ISSUE TITLE
Suggestion: sync theme with system

### ISSUE THREAD

**Issue by rcmero** [audacity/audacity#2370]
When I heard about the dark mode in Audacity, my first thought was whether it would be nice if the theme would sync with the system's theme. I have an application on my system (Windows 10 2004) that automatically enables dark mode at night, and it would be nice if Audacity would automatically enable dark mode when the system is set to dark mode, like how it's done with Microsoft Office for example.

If it's not possible to change the theme on the fly checking when the application starts up would be a nice compromise.

**Comment by LWinterberg** [comment]
Fwiw, Microsoft hasn't yet published any documentation on the relevant API, so I'm not sure if we can use it just yet

**Comment by LWinterberg** [comment]
this is planned for much later (Audacity 4.x), closing for now
