### ISSUE TITLE
`(return "something")` done twice in the Nyquist prompt hangs Audacity

### ISSUE THREAD

**Issue by werame** [audacity/audacity#2372]
**Describe the bug**
Nyquist Prompt `(return "something)` hangs Audacity when done twice

**To Reproduce**
1. Open a Nyquist Prompt.
2. Type
```
(return "something")
```
3. And click "OK".
4. Repeat steps 2, 3, 4. 
5. Audacity hangs.

**Expected behavior**
As at step 3:  the dialog is just quietly dismissed.

**Screenshots**
![image](https://user-images.githubusercontent.com/97036286/147941010-a6bdfd48-8a33-4ab0-9959-aeaacf4679ac.png)

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version Audacity 3.1.3

**Alternative reproducer (clicking Debug instead of OK hangs on empty track as well)**
Audacity doesn't hang when running the exact same snippet of Nyquist code given above if either there's no track selected or even if the mono track is empty tough. I.e. if at step 1 above one does just (the clicking equivalent equivalent of) NewMonoTrack, then no hang occurs, but nothing is returned to the user via a dialog box either.

However, "scenario 2", one can make it hang even with a empty track if instead of "OK" one clicks Debug in the Nyquist Prompt dialog, i.e. the following sequence also hangs Audacity:

1. Have an empty mono track selected or no track selected, in which case Audacity will auto-generate an empty mono one when one enters the Nyquist Prompt.
2. Open a Nyquist Prompt.
3. Type
```
(return "something")
```
4. And click "Debug" (instead of OK, as in the previous scenario).
5. Audacity hangs.

**Additional context**
Also, it doesn't matter if it's the top-level function that's being returned, the following also hangs in the circumstances described

```
(defun foobar (x)
    (return "something")) ; also hangs

(foobar 10)
```

On the other hand, a proper use of `return-from` instead of `return` works as one may expect

```
(defun foobar (x)
    (return-from foobar "something")) ; ok, no hang

(foobar 10) ;  "something" returned in dialog box
```

The uses of `return` above were incorrect because XLisp doesn't support it from a (named) function context. Only `return-from` (as in the last example) is supported in a named block, which includes the ones generated by `defun`. Still the [XLisp documentation for return](https://www.audacity-forum.de/download/edgar/nyquist/nyquist-doc/xlisp/xlisp-ref/xlisp-ref-225.htm) doesn't say that `return` from the wrong (i.e. unnamed) context may result in undefined behavior, but only that an error (exception) is returned.

Nested exits from an unnamed block suck as prog work ok though, e.g. the following both work properly.

```
(defun foobar (x)
	(prog ()
		(return-from foobar "something")
		"not reached"))
		
(foobar 10) ; ok, "something" is the value returned
```
Likewise
```
(defun foobar (x)
	(prog ()
		(return "something")
		"not reached"))
		
(foobar 10) ; also ok, "something" is the value returned
```
Also no hang occurs if `return` used in the proper context at top-level

```
(prog ()
	(return "something") ; ok, no hang, this is the value returned
	"not reached")
```

Finally, what's the name for the top-level function at the Audacity Nyquist Prompt, if there is one, so one can `return-from` it early, i.e. not need an explicit `prog`? SAL supports a `return` from its top-level at the same prompt so, I'm guessing a function wrapper is used, at lest for SAL.

**Comment by petersampsonaudacity** [comment]
Testing on W1- with Audacity 3.1.3 Audacity does **_not_** hang at step 5

**Comment by SteveDaulton** [comment]
I've been able to reproduce the hang on Linux. It does not always hang, and it does not always hang straight away. When it does hang, I see 100% CPU on one core.

**Comment by SteveDaulton** [comment]
I can reproduce the problem reliably like this:

1. Launch Audacity
2. Generate a Chirp
3. Open the Nyquist Prompt
4. Type the code: `(return)`
5. Press the Debug button
6. Dismiss the error log with the OK button
7. Open the Nyquist Prompt (again)
8. Press the Debug button
9. Observe hang.

**Comment by SteveDaulton** [comment]
I've not been able to reproduce the hang in standalone Nyquist, so the problem seems to be specific to Audacity.

**Comment by werame** [comment]
I'm guessing there's a problem with the top-level function name being left on the Lisp stack (or something like that) when `return` is used.

**Comment by SteveDaulton** [comment]
Nyquist is getting stuck in an infinite loop at line 67 of [xljump.c](https://github.com/audacity/audacity/blob/master/lib-src/libnyquist/nyquist/xlisp/xljump.c)

```
    for (cptr = xlcontext; cptr; cptr = cptr->c_xlcontext)
        if (cptr->c_flags & CF_RETURN && cptr->c_expr == name)
            xljump(cptr,CF_RETURN,val);
```

**Comment by werame** [comment]
There are some interesting comments https://github.com/audacity/audacity/blob/95a7fc6362729594565204b6db927b2e025d20c0/nyquist/sal.lsp#L510 on how SAL manages to not blow itself up like that. It always uses a function and SAL's return essentially does a Lisp `return-from`. 

> This works like SAL-COMPILE, but if there is a top-level
;; return statement (not normally legal), it is compiled into
;; a function named MAIN. This is a shorthand for Audacity plug-ins

So, just trying something just in case the same is done for plain XLisp in Audacity...

```
(return-from main "something")
```

Unfortunately that also hangs, so it's probably set up differently for XLisp than for SAL.

**Comment by rbdannenberg** [comment]
Very interesting. In command-line nyquist, a top level return raises the error "no target for RETURN" and  invokes the debugger (if enabled). Probably some study of how Nyquist implements the outer-most read-eval-print loop in C and how it catches RETURNS there would be helpful.  nyquist/xlisp/xlisp.c defines xlisp_main() and there I see
` /* build an outer-most context */`
and the use of flag CF_TOPLEVEL, so that looks like a good model for how to sit at the "bottom" of the stack.

**Comment by werame** [comment]
I should add that it only hags when you run `(return-from main "something")` *a second time* in the same Audacity, even with no track. That probably explains why some people could not reproduce the first bug. It seems that if you run of those it corrupts the Lisp stack somehow, so it hang later.

**Comment by Paul-Licameli** [comment]
I took the liberty of editing the bug title and steps to reproduce.  It is not relevant whether there is a track or not.  All that matters, is doing the prompt twice.

I believe the bug is in nyx.c which is not used in standalone Nyquist.  The functions in that file are only for Audacity's interface to Nyquist.

**Comment by Paul-Licameli** [comment]
I couldn't help myself but had to fix this.

I invite @werame to verify the fix too, and understand it in the debugger.

Be warned, the XLisp interpreter does some weird control flow with `setjmp` and `longjmp`.

The bug wasn't really in the old XLisp interpreter itself but in a layer of new entry points that Nyquist added to it.

**Comment by werame** [comment]
Thank you, I shall. I was a bit absorbed with finishing my first PR/patch (which you can see as a PR now), which is not on this issue though.

**Comment by werame** [comment]
Belatedly, I tested the patch too. It worked for me as well. Now it properly errors with 

```
error: no target for RETURN
Function: #<FSubr-RETURN: #000002229EFDA010>
1> 
```

even on multiple `(return)` attempts.
