### ISSUE TITLE
Windows: Audacity debug report can be removed by cleanup apps

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2374]
**Describe the bug**
On Windows the Audacity debug report can be inadvertently removed by cleanup apps / anti-virus apps.

Originally logged on Bugzilla by Gale Andrews in 2016 as 1289
https://bugzilla.audacityteam.org/show_bug.cgi?id=1289
https://bugzilla.audacityteam.org/show_bug.cgi?id=1289

**To Reproduce**
1. Launch Audacity
2. Crash Audacity with Task Manager _(kill the Process Tree in Details for a full pukka crash)_
3. Run Norton's Windows Temporary File Cleaner or similar. 
4. Observe: the Debug Report is deleted.

**Expected behavior**
Windows: Move the Audacity debug report location to that not scanned by cleanup apps

In the original Bugzilla report Gale wrote:
>Suggest moving to %localappdata%\Audacity\Debug Reports.

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version: originally reported against Audacity 2.1.2 - but still believed to be the case]
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]

**Additional context**
Flagging @crsib

**Comment by LWinterberg** [comment]
The solution to this would be "don't run cleaning programs after generating the debug report", no?

**Comment by LWinterberg** [comment]
Fwiw, the popularity of these cleaning thingies has *massively* declined since the original bug: https://trends.google.com/trends/explore?date=all&q=ccleaner,malwarebytes,avg%20pc%20tuneup,Avast%20Cleanup

**Comment by SteveDaulton** [comment]
> The trouble is that for some users cleaning apps can run automatically and unbidden.

It looks to me that it is the user's choice if they want to use overly aggressive clean-up apps, rather than a problem in Audacity.
Personally I think this is a non-issue.

**Comment by petersampsonaudacity** [comment]
Also, consider now that many of the serious error messages now have the ET-phone-home button to send such diagnostic data straight to MUSE.

I agree that this can thus probably be closed.
