### ISSUE TITLE
The Compressor effect has no grid lines

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2375]
**Describe the bug**
The Compressor effect has no grid lines, thus making harder to use accurately.

This was originally logged on Bugzilla by Gale Andrews as part of 153
https://bugzilla.audacityteam.org/show_bug.cgi?id=153

**To Reproduce**
1. Get some audio
2. Effect > Compressor
3. Observe no grid lines in the graph - see Image 1

**Expected behavior**
Grid lines in the graph - see mock-up Image 2

**Screenshots**
1) as is
![image](https://user-images.githubusercontent.com/50205984/148049667-4669a838-ab2c-4aa4-92f2-e9c573251497.png)

2) mock-up with grid-lines - light gray would be better for the gridlines _(consistent with Plot Spectrum and Filter Curve EQ)_
![image](https://user-images.githubusercontent.com/50205984/148050093-79f47779-30c4-4a77-8b42-87f70c9d4fcc.png)

**Additional information (please complete the following information):**
 - OS: all
 - Version: Audacity 3.1.1 and all earlier
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]

**Additional context**
Compare this with say:
a) Analyze > Plot Spectrum 
b) Effect > Filter Curve EQ
where Audacity does have useful grid-lines.

Flagging @Tantacrul  as a UX/Design issue.

**Comment by LWinterberg** [comment]
We'll need to redesign the compressor UI overall IMHO to be more easily usable, so I don't think we'll work on this request. Closing for now.
