### ISSUE TITLE
Compressor effect has no edit boxes for sliders

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2376]
**Describe the bug**
Compressor effect has no edit boxes for sliders this makes it hard for VI users

This was originally logged on Bugzilla by Gale Andrews in April 2010 as part of 153:
https://bugzilla.audacityteam.org/show_bug.cgi?id=153

**To Reproduce**
1. Get some audio
2. Effect > Compressor
3. Observe no edit boxes for the sliders - see Image 1

**Expected behavior**
Sliders in Compressor effect to have edit boxes (in common with most other effects)

Gale wrote in the original Bugzilla bugthread
>Add Edit box for sliders (as per most effects) so that VI users can hear/set values expressed in the slider units rather than in percentages.

**Screenshots**
1) Compressor effect - observe no edit boxes
![image](https://user-images.githubusercontent.com/50205984/148051908-36878688-e918-4b4c-87a8-6ca351bbccaf.png)

2) Wahwah effect - observe edit boxes
![image](https://user-images.githubusercontent.com/50205984/148052066-cf8515f7-aac3-48e4-9605-a350014e05c3.png)

**Additional information (please complete the following information):**
 - OS: all
 - Version: all

**Additional context**
Flagging @Tantacrul  as a UX/Design issue

Note that most other effects with sliders have edit boxes - see Image 2 for an example (Wahwah effect)

**Comment by LWinterberg** [comment]
We'll need to redesign the compressor UI overall IMHO to be more easily usable, so I don't think we'll work on this request. Closing for now.
