### ISSUE TITLE
Keyboard seeking commands don't work for MIDI playback

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2377]
**Describe the bug**
Keyboard seeking commands don't work for MIDI playback.

Originally logged on Bugzilla  by @Paul-Licameli in January 2031
https://bugzilla.audacityteam.org/show_bug.cgi?id=2635

**To Reproduce**
1. Create a project with a MIDI track
2. Play
3. Use one of the keystroke commands to move the play head (including left or right arrow, or period or comma, with or without Shift)
4.  Observe:  play head moves correctly but MIDI playback does not remain synchronized

**Expected behavior**
Keyboard seeking commands should work for MIDI playback

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS: all
 - Version: Audacity 3,1,3 and 3.2.0 alpha

**Additional context**
Flagging @Pokechu22

**Comment by Paul-Licameli** [comment]
I’m a time traveler!
