### ISSUE TITLE
Mix Stereo Down to Mono applies Pan incorrectly

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2386]
**Describe the bug**
Mix Stereo Down to Mono applies Pan incorrectly

**To Reproduce**
1. Create a stereo track with easily identified left and right channel content (such as Brownian noise in one channel, and DTFM tones in the other).
2. Pan the track all the way to the right
3. "Tracks menu > Mix > Mix Stereo Down to Mono"
4. Observe a silent mono track

**Expected behavior**
As it says [in the manual](https://manual.audacityteam.org/man/tracks_menu_mix.html#mix_stereo_down_to_mono):

>Converts the selected stereo track(s) into the same number of mono tracks, combining left and right channels equally by averaging the volume of both channels. The tracks will be rendered **with any amplitude envelope or gain and pan settings applied**. 

In the above case, that would be the right channel only.

**Screenshots**

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version Audacity 3.1.3 and 3.2.0 alpha
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]

**Additional context**
Regression

**Comment by chuckkh** [comment]
Hi. I'm trying to figure this one out. I'll be in touch if I spot it.
I thought it might be because the eventual output track is a clone of the left track, but that doesn't seem to be related. I changed it to clone the right track instead and it behaved the same way.

**Comment by LWinterberg** [comment]
It should 

1. apply the gain/pan/envelope to the waveform destructively
2. mix down the stereo to a mono track, deleting the stereo track. The new mono track has the default gain/pan/envelope (ie no gain, pan, or envelope control points)

**Comment by Paul-Licameli** [comment]
The mix-down now makes a flat waveform, and that is an old regression somewhere between 2.3.3 and 2.4.1.

**Comment by Paul-Licameli** [comment]
> It should
> 
> 1. apply the gain/pan/envelope to the waveform destructively
> 2. mix down the stereo to a mono track, deleting the stereo track. The new mono track has the default gain/pan/envelope (ie no gain, pan, or envelope control points)

But in 2.3.3, the result is one Mono track panned hard-right, and the track control panel says "Right."  Because there is a distinction between ordinary Mono tracks, and one-sided Mono tracks.

**Comment by Paul-Licameli** [comment]
In 2.3.3, still the pan slider setting is preserved in the result even though the waveform is not flat.

**Comment by Paul-Licameli** [comment]
Suspect commit at e8f9f4a7e9065df4417d25ae6c59e6efc3a450b7

**Comment by petersampsonaudacity** [comment]
> The mix-down now makes a flat waveform, and that is an old regression somewhere between 2.3.3 and 2.4.1.

Testing on W10 with latest alpha 3.2.0  -  this works for me but reduces the amplitude which looks wrong to me.

### Before the Mix down to mon
![image](https://user-images.githubusercontent.com/50205984/188111480-3dbf4fbf-960a-4930-8d50-a6087e293a74.png)

### After the mix down to mono
![image](https://user-images.githubusercontent.com/50205984/188111722-75b3bb11-276b-45e5-97e7-5abedaf2b03c.png)

**Comment by Paul-Licameli** [comment]
@petersampsonaudacity original steps to reproduce include panning hard right before the mix-down, which incorrectly results in a silent track.

**Comment by petersampsonaudacity** [comment]
> @petersampsonaudacity original steps to reproduce include panning hard right before the mix-down, which incorrectly results in a silent track.

@Paul-Licameli OK - so i will log this as a new bug (it's a regression on 2.0.6 BTW) and then purge this from this thread ...

**Comment by LWinterberg** [comment]
potentially related: #4114

**Comment by dozzzzer** [comment]
Tested
