### ISSUE TITLE
FFmpeg 59 libavfomat support (with photos)

### ISSUE THREAD

**Issue by CanadianJeff** [audacity/audacity#2388]
https://github.com/audacity/audacity/blob/release-3.1.3/libraries/lib-ffmpeg-support/impl/ffmpeg-4.2.4-single-header.h#L4161
![version 59 support](https://i.imgur.com/7x9nW0s.png)

would suggest that libavformat 59 "should just work"

however trying to import it into audacity yields only 58.77.100 works

![import in audacity](https://i.imgur.com/MZM8RvA.png)

downloaded 59 from ffmpegs autobuild github........

58 works
`https://github.com/BtbN/FFmpeg-Builds/releases/tag/autobuild-2021-03-31-12-39`
59 does not
`https://github.com/BtbN/FFmpeg-Builds/releases/tag/autobuild-2021-04-30-12-35`

**Comment by SteveDaulton** [comment]
> would suggest that libavformat 59 "should just work"

Why should it work? 
It says `< 59` (less than).
Also, the [commit message](https://github.com/audacity/audacity/commit/98ec91c3ac91d8e6ad5697d7efacd93e6978801f)

**Comment by CanadianJeff** [comment]
so why hard code the requirement of under 59?????? something seems really fishy here........

**Comment by crsib** [comment]
The latest released version is 4.4, which bundles avformat 58.76.100. avformat 59 is not yet released and is a subject of an ABI break. The support for avformat 59 will be added after the official FFmpeg release

**Comment by CanadianJeff** [comment]
that just sounds like a major cover up

**Comment by LWinterberg** [comment]
As per https://wiki.audacityteam.org/wiki/Release_Notes_3.1
> FFMPEG now supports avformat 55, 57 and 58.

Also, note that https://github.com/audacity/audacity/tree/release-3.1.3/libraries/lib-ffmpeg-support/impl has 3 different files, one per supported avformat version. So I don't really get why you call this a "cover up". 

> why prevent unreleased versions 

Because avformat 59 is not yet released and is a subject of an ABI break. 

> why close the issue?

Because avformat 59 is not released yet and as long as it's not, it won't be added. Once it is released, we plan to add support for it to the next version we release.

**Comment by CanadianJeff** [comment]
again I dont know much about ABI but my take is how compat ffmpeg is with audacity and how compat audacity is with ffmpeg...........

I still think giving the user a choice to load in an unsupported "External Lib" should be allowed that way people can find out whats support and whats not.....

maybe prompt the user to "proceed at his/her own risk if they attempt to use an unsupported ffmpeg version

**Comment by BtbN** [comment]
The 59 bump ABI instability period is long over.
5.0 has been branched and is in its final polishing before being tagged as first 5.0 release. No further ABI breaks will occur there anymore (or in master for a long while).

Generally, FFmpeg does not break ABI outside of a short ABI instability period after every major bump in master.
