### ISSUE TITLE
Macro access to the track drop-down menu commands

### ISSUE THREAD

**Issue by werame** [audacity/audacity#2391]
I'd like to be able to invoke [track drop-down menu commands](https://manual.audacityteam.org/man/audio_track_dropdown_menu.html) command from macros, both "traditional" Audacity ones and Nyquist macros. Meaning these commands:

![drop-down menu](https://user-images.githubusercontent.com/97036286/148588641-8356662d-6a1d-40f1-8e73-1123c211fc2f.png)

Presently that seems [not possible](https://forum.audacityteam.org/viewtopic.php?f=46&t=122634&p=442938#p442956) because those track drop-down commands like "Make Stereo Track" or "Split Stereo Track" don't seem to have a macro name binding, i.e. they don't show up in the macro builder's catalogue of available Audacity commands that can be invoked from macros, e.g. there's nothing that starts with "Make" in the screenshot below:

![no make](https://user-images.githubusercontent.com/97036286/148589401-34071c39-6335-43ba-bd2e-6657606ce674.png)

I'm trying to resist comparison with other software, but the comparable Adobe product (Audition) has an object model that allows per track or even per-clip properties to be set (and read) from (CEP) scripts.  So, besides the mere parameter-less commands like "Split Stereo Track", changing things like the view mode or displayed color of a track (as these are also in the same track drop-down menu) from a macro would also be interesting, although just invoking the track specific parameter-less commands would already be of substantial help to me. Actually, setting the track colors is possible from macros with [Set Track Visuals](https://manual.audacityteam.org/man/extra_menu_scriptables_i.html). But there's no getter equivalent. So someone needed something else from that track drop-down menu as a command 🧁 

As it's commonly done in a transposition of object-oriented stuff to procedural, having the track's name as an explicit first argument of such macros seem the approach to take, API-wise, at least for the traditional Audacity macros. Since XLisp has objects, I'm guessing a more object-oriented approach might be possible for Nyquist macros in terms of accessing per-track commands or properties. In fact some of those are already exposed as read-only (I think) properties with `(get '*track* 'pan)` etc., which I've [already used](https://github.com/werame/funky-nyquist-stereo-plugins/blob/80d662a0b0d32330a821225b7f24bd83bb3309a5/src/sweep.lsp#L34). But things like splitting a track don't seem possible in that properties-only approach.

**Comment by SteveDaulton** [comment]
> having the track's name as an explicit first argument of such macros seem the approach to take

That may be problematic as Tracks often have non-unique names. However, a track context command could be applied to the track that has focus. (There are already macro / scripting commands for setting focus).

I agree that this feature request would be very useful.

**Comment by petersampsonaudacity** [comment]
> That may be problematic as Tracks often have non-unique names.

Maybe they should have unique names to aid distinguishing them:

a) new created tracks could be Audio-Track-1, Audio Track-2 etc, in a project.

b) the user could be prevented from renaming a track to the same name as another existing track in the project.

**Comment by petersampsonaudacity** [comment]
Flagged for @Tantacrul  as a UX/design issue

**Comment by SteveDaulton** [comment]
> b) the user could be prevented from renaming a track to the same name as another existing track in the project.

Most users will never use track dropdown commands with macros.
I think users should be able to name tracks as anything they want.

Track dropdown menu commands should only be applied to one track at a time as applying to multiple tracks could have weird or unexpected consequences.

When pressing the context menu key, the track dropdown menu for the track that has focus is opened. I think it would be sensible to follow this behaviour when running a track dropdown menu command from a macro.

**Comment by werame** [comment]
Actually, this is practically a duplicate of #1629 in hindsight, since most other actions besides those split / make-stereo seem to be accessible.
