### ISSUE TITLE
Create a Chris-like compressor for Audacity

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2397]
**Describe the bug**
We often recommend downloading and using '''Chris's Dynamic Compressor''' on both the Forum and in several Places in the Manual (for example at the foot of the [https://manual.audacityteam.org/man/compressor.html '''Compressor built-in effect page on the basis that is simpler to use than our in-built Compressor and produces better results.  
|Chris's dynamic compressor by the late Chris Capel is a popular [http://en.wikipedia.org/wiki/Nyquist_%28programming_language%29 Nyquist] plug-in that tries to even out abrupt changes of volume by employing "''lookahead''" (this attempts to anticipate volume changes by starting to apply compression before the volume rises to the threshold level). There are options to soften the softer audio and invert loudness.}}

We cannot host this or distribute it ourselves due to licensing restrictions. We have no control or guarantees regarding the plug-in hosting on https://theaudacitytopodcast.com/chriss-dynamic-compressor-plugin-for-audacity/  _(though we expect that he will  continue to host the plug-in as I expect he derives a lot of traffic from it)_. The 1.1 version is very similar to other versions, so the wayback machine link gives us some assurance that a version of the plug-in remains available, even if theaudacitytopodcast.com goes off-line.

On this page https://manual.audacityteam.org/man/chris_s_dynamic_compressor.html in the Manual we have long stated 
>We hope to make a freely-licensed version of this plug-in available for separate download later, based on Chris's 1.2.7 Beta version which has a free MIT License."'' Unfortunately the 1.2.7 beta version includes problematic experimental features which prevent us from recommending this version.

**To Reproduce**
1. Use Effect > Compressor
2. Install and use Chris's Dynamic compressor
3. Observe: compare the two

**Expected behavior**
*Develop a new built-in Nyquist compressor effect effect that is as easy to use, and as effective with voice and music as Chris's Dynamic Compressor v1.2.6. 
*Ship this bundled with the Audacity app as part of our standard set of pre-enabled Nyquist effects.
*It does not need to be an exact copy of Chris's compressor, but the characteristics of Chris's compressor are nice - it can apply significant compression without "sounding" like it is compressed.
*Document the new compressor in the Manual
*We should attempt to remove the one drawback of Chris's Compressor whereby it doesn't handle the beginning and ends of audio well.  The simple workaround is to temporarily add audio to front and back, run Chris's and then remove the temporary audio.
*One thing that @SteveDaulton thinks both Koz and Trebor would see as an improvement over Chris's Compressor, would be a slightly more aggressive default ''(they both routinely recommend using a slightly higher compression setting than the default)''.
*One key advantage is that we would have to document the new compressor properly in the Manual.  Despite recommending Chris' we have never provided documentation for it.

**Screenshots**
Chris's Dynamic Compressor v1.2.6 at default settings 
![image](https://user-images.githubusercontent.com/50205984/148681323-3ea17646-ea37-4646-9555-f058db9e3c57.png)

**Additional information (please complete the following information):**
 - OS: all
 - Version:  all

**Additional context**
This could either be an additional effect in Audacity or it could be used to replace the existing Compressor effect in Audacity.

This was originally logged as a Proposal in 2018 in the Audacity Wiki:
https://wiki.audacityteam.org/wiki/Proposal:_Chris-like_compressor

**Comment by petersampsonaudacity** [comment]
@LWinterberg @DilsonsPickles @Tantacrul 

If this were to be developed then it would be excellent if it could be made real-time capable so that it would work in the new effects stack.

**Comment by petersampsonaudacity** [comment]
@saintmatthieu  this could be a very good addition to Audacity's armoury -a s the existing Compressor effect in Audacity is known to be not very good.

Do you agree?

**Comment by saintmatthieu** [comment]
Hi @petersampsonaudacity, sorry for the late reply, was on vacation the last three weeks.
I'm afraid I cannot contribute anything new to this conversation yet, as I have tried neither. I may know the basics of compressors but don't have that much experience with them either. When the team decides the time is right for it then it'll be my pleasure to look into this in more detail, though.

**Comment by petersampsonaudacity** [comment]
Hi @saintmatthieu  - thanks for the reply

The reason for posting this particular request is that long years on the Forum have shown that the Audacity built-in Compressor effect is not very good.  One if the Forum elves Greg Kozikowski _(Koz as he is known on the Forum)_ always recommends Chris's Compressor as a much better alternative - his opinion is valuable as he is a long-standing sound recording engineer in LA.

Chris himself can no longer contribute to improving his compressor as he is sadly no longer with us (RIP).

A compressor must be one of the most-used tools in any audio editor or DAW - so providing the best seems like a compelling argument.

**Comment by SteveDaulton** [comment]
I think  it's a bit unfair to say that Audacity's compressor "is not very  good", because it does what it was designed to do effectively and reliably. The main problems with Audacity's compressor are:
* It is limited to long attack / release times, 
* It is quirky and unconventional.

If you actually want a very slow acting, destructive compressor, with look-ahead and automatic normalization to 0 dB, then the Audacity compressor is probably a good choice. For any other dynamic compression needs, then it is probably the wrong tool for the job. 9/10 times it will be the wrong tool for the job.

**Comment by LWinterberg** [comment]
superseded by #6305, which would see improvement past its initial implementation
