### ISSUE TITLE
Custom Resets for Toolbar Layouts

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2398]
**Describe the bug**
There is no Audacity GUI available way for a user to save/restore their carefully created Audacity settings for Toolbars layouts, their Audacity environment(s).   It is all too easy to mess up your Toolbar layouts (or want temporarily to deviate from your normal Toolbar layouts) so a simple straightforward way to achieve reset would be useful.

The only workaround available is for the user to save the audacity.cfg file somewhere on the their file structure.  Then subsequently copy this saved audacity.cfg back into the '''...\Appdata\Roaming\Audacity''' folder ''(Windows file structure, similar exists on macOS and Linux)''.  This may be deemed a little too technical, too inaccessible to many of our users.  Furthermore it "restores" more than just the Toolbar layouts it also "restores" the user's Preferences.  The other issue with this workaround is that you must close all open Audacity projects before you can copy back your saved audacity.cfg.

This was originally logged as a Proposal in the Audacity Wiki in 2017:
https://wiki.audacityteam.org/wiki/Proposal:_GUI_Custom_Resets_for_Toolbar_Layouts 

The trigger for this proposal was this forum post:
https://forum.audacityteam.org/viewtopic.php?f=46&t=94527&start=10 

**To Reproduce**
1. Customize you toolbar layout
2. Tools > Reset Configuration
3. Try to restore your customized toolbar layou
4. Observe: it has to be done Manually

**Expected behavior**
Introduce commands for Save and Restore for Toolbar layouts, to enable the user to create named configurations of Toolbars.  A "Factory Settings" for restore to default to be included.  ''This is like saving presets in effects.''

Saved and restored would be: 
1. the user's Toolbar selections, 
2. their settings and their positionings 
3. and the window size.

@SteveDaulton suggested in the Proposal:

**View > Toolbars > Reset to default** replaced by

**View >Toolbars > Reset > [default / custom1 / another / ...]**

where **[default /.../...]** is an additional menu level (difficult to show in text).

It would be good if this final menu level was sorted alphanumerically, so then the user could prefix a number to get their favorites at the top. The first item would always be "default".

**Screenshots**
![image](https://user-images.githubusercontent.com/50205984/148919341-a4a7efe0-4717-44e1-83c1-fbf9e8c421c9.png)

**Additional information (please complete the following information):**
 - OS: all
 - Version: all

**Additional context**
Over the years we have had many support posts on the Forum where people have screwed up their toolbar layouts - or in some cases an Audacity bug has screwed up the layouts for them.

Flagging @Tantacrul as a UX/design issue

**Comment by petersampsonaudacity** [comment]
@SteveDaulton wrote in the Proposal: 
>I may want one layout for recording music, in which I have a full screen width recording meter. Of course for that I need a full screen width window. I may want another layout for recording narration where I have Audacity and a text window side by side, with a smaller recording meter. 'Not' saving the window size just means more clicks for the user (and no practical benefit that I can see).

**Comment by petersampsonaudacity** [comment]
### Screen size to be part of saved layout
It would be more helpful and more useful/usable if the screen size was part of the saved layout. 

If the window size is saved as part of the layout, then the restored layout actually looks like the layout that was saved. If the window size is not saved, then the layout could look very different.

**Comment by LWinterberg** [comment]
This is planned with #1022, and it'll definitely be more discoverable than a sub-sub-menu

**Comment by petersampsonaudacity** [comment]
> This is planned with #1022, and it'll definitely be more discoverable than a sub-sub-menu

Great news
