### ISSUE TITLE
Indicate a 0-position for gain/pan sliders

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2406]
**Describe the bug**
It is all too easy to accidentally nudge the Pan or Gain sliders in a track's Track Control Panel and not realize or see that you have thus made potential changes to the audio (on rendering or export). 

The visual cues for non-zero default state are not very good, particularly for small changes. 

This was originally logged on the Audacity Wiki as a Proposal in 2017:
https://wiki.audacityteam.org/wiki/Proposal_Locking_and/or_Hiding_Pan_and_Gain_sliders

**To Reproduce**
1. Get some audio
2. nudge the Pan or Gain slider 
3. Observe no good visual cue to show you that you are off the default setting

**Expected behavior**
Improving the visual cue would be good mitigation, but it could be improved with lockable/hideable sliders.
1. Add the ability to hide/restore the Pan and Gain sliders ''(many users don't need them at all) - leave them visible by default.
2. Add the ability to Lock/Unlock the Pan and Gain Sliders - either per ''(selected)'' track or global.
3. Improve the visual cue for non-zero default state of the Pan and Gain sliders.

### Hide/Display Pan&Gain sliders
This to be a global setting.
Add a commands to the '''Tracks''' menu:
* **Pan & Gain Sliders**
with on on/off toggleable setting - default = "on" ''(for discoverability)'' 
Both must either be on or off in unison, no independent settings.
Cannot be set to "off" if any tracks have non-zero settings for the Pan or Gain sliders.

### Lock/Unlock Pan&Gain sliders
This is trickier as one may want either a global or a per track setting:
1. For a per track setting we would need a lock/unlock command in the audio track's Track Control Panel dropdown menu.
2. For a global setting this would be a Lock Pan and Gain Sliders in the Tracks menu with toggleable on/off setting - default to be "off".
We may (and probably do) want both settings, in which case I would suggest that an individual track's setting from its TCP would override a global setting. 

### Visual Cue
* Gale suggested in the related Forum thread:  ''the knobs could light up when moved away from centre ... ?'' 
* Ed suggested in the related Forum thread: ''Maybe change the knob image when it is not centered/zeroed?''  
* I (Peter) would suggest that we change the color of the sliders to say green to indicate that they are active and non-zero default.

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS: all
 - Version: all

**Additional context**
From real-life reports on the Forum:
a) A way to delete or disable these controls in the preferences. There has been several times when working with several audio files at once these controls get bumped, so my gain is bad or my balance is out. I will backtrack tying to figure out how I "screwed this up" usually think the filter I applied didn't work right or something. I normally NEVER use them when editing. Typically I minimize the tracks I'm not working on to maximize the workspace which will hide a tweaked gain or balance control.  
See this archived Forum thread:  https://forum.audacityteam.org/viewtopic.php?f=20&t=90870

b) Lock pan and volume sliders in Track Control Panel: I repeatedly bump pan or volume in my efforts to move tracks around and I usually can't figure out what is wrong for a while. Unless there is already a way to lock them, I think that would be a useful feature.
 See this Forum post for details:  https://forum.audacityteam.org/viewtopic.php?f=20&t=94640&p=320842#p320842 

_Further: I personally have been bitten by this a few times.  In these cases I never saved a project just exported the WAV files (which renders the pan and gain settings) - and by the time I notice later I had no project to go back to to correct the situation._

**Comment by werame** [comment]
Please don't switch to circular knobs without allowing sliders as an option. I know knobs save space, but for a finger as opposed to mouse driven interface, e.g. touch screen, the knobs are much more fiddly to set to a desired setting compared to the linear sliders.

**Comment by LWinterberg** [comment]
What knob interaction do you have in mind? The new musescore thing has the rule "drag up or right to increase value, drag down or left to decrease", so it would remain a linear motion @werame

**Comment by petersampsonaudacity** [comment]
> What knob interaction do you have in mind?

@Tantacrul has mused elsewhere about the possibility of knobs for this ...

**Comment by SteveDaulton** [comment]
Knobs can be space-saving, but I'm not very keen on "linear drag to rotate" as:
a) I prefer things that do what they say on the tin. "Linear drag to rotate" is a slider masquerading as a knob.
b) "Linear drag to rotate" assumes that the knob is positioned on scree with sufficient space to drag, which could be a problem in some cases (such as the bottom track of a large multi-track project).
c) The intuitive user interaction with a knob is "rotate to rotate".

**Comment by Tantacrul** [comment]
Linear drag is the predominant method found today. Rotating using you mouse is practically a bit of a pain. We've just gone through some testing on this with MuseScore. Initially, you had to rotate it until enough community members complained. I agree with them.

**Comment by SteveDaulton** [comment]
> Rotating using you mouse is practically a bit of a pain.

Which is why we used sliders.

**Comment by werame** [comment]
It's even more of a pain to rotate with fingers on a touch screen. Yeah, the "looks like a knob but acts as a linear slider" is a fair compromise between space saving and still being able to interact with it in a non-contorting way (esp. on touch screen), but there's the surprise factor between looks and how it works with that "looks like a knob but acts as a linear slider".

Somewhat related: I'm quite glad that Audacity offers an alternative, simple linear slider view of VST plugins controls. Some creators of such plugins can get really... creative with their custom drawn UI controls, often at the expensive of usability (and sometimes even discoverability, as in "oh, that was really knob!")

**Comment by werame** [comment]
In Reaper one can choose between knobs and sliders https://youtu.be/G-aZE97PD4w?t=64 Admittedly most other DAWs don't have that feature.

**Comment by LWinterberg** [comment]
this is planned for much later (Audacity 4.x), closing for now
