### ISSUE TITLE
Proposal Label Track Info

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2410]
**Describe the bug**
When there are more than a handful of labels it's often difficult to determine their exact number and type (point or region); one must either visually count them or open the Label Editor dialog, scroll to the bottom of the dialog, and examine the line number of the final item. 

Occasionally there will be labels before time-zero; this can occur when a label exists at a place in the track which has been shifted before zero with the clip-handle drag-bars.

This was originally logged in 2014 as a Proposal in the Audacity Wiki:
https://wiki.audacityteam.org/wiki/Proposal_Label_Track_Info

**To Reproduce**
1. generate a **_large_** number of labels
2. try to count them
3. Observe: it;s hard and possibly inaccurate

**Expected behavior**
1. Add some text in the otherwise unused portion of the Label Track's Track Info Panel which shows a running count of one or more of Point, Region & Pre-Zero labels.
2. Optionally, give the user some control over which of the three (Point, Region or Pre-Zero) types are displayed.
3. Optionally, give the user some control over the font employed when drawing this text in the Track Info Panel. This could be either by inheriting the user's choice for the Label's font or allowing the user to customize the font. If the user may customize the font it could be global (all Label Track Track Info Panels) or per-Label Track.

**Screenshots**
These images are from a heavily customized version of Audacity
![image](https://user-images.githubusercontent.com/50205984/148991970-98b7c127-7749-46a6-9523-b824769b6be9.png)

![image](https://user-images.githubusercontent.com/50205984/148992151-f5cb2a5b-6948-4eb2-ab21-0a4e7eeabefe.png)

![image](https://user-images.githubusercontent.com/50205984/148992234-2106c63e-a2a5-4924-b854-b1aebd5c2540.png)

**Additional information (please complete the following information):**
 - OS: [e.g. Mac High Sierra, Ubuntu 18.04, Windows 10]
 - Version [e.g. Audacity 2.5.1]
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]

**Additional context**

**Comment by SteveDaulton** [comment]
> 1. generate a **_large_** number of labels
> 2. try to count them
> 3. Observe: it;s hard and possibly inaccurate

Personally I've never found this to be a problem, but it would be fairly easy to write a Nyquist plug-in to get a summary of the labels in a project. Would that be a suitable solution for those that want / need this functionality?

**Comment by petersampsonaudacity** [comment]
> ... it would be fairly easy to write a Nyquist plug-in to get a summary of the labels in a project. Would that be a suitable solution for those that want / need this functionality?


That sounds like a good idea - a plug-in that could be added to the Tools menu perhaps.

**Comment by LWinterberg** [comment]
There are plans to feature both macros, nyquist plugins, and other kinds of plugins on a plugin download page for 3.2, so I think a downloadable nyquist plugin would be best for this.

**Comment by SteveDaulton** [comment]
How about something like this:
(Note: The weird icon in the top left corner is the open bug https://github.com/audacity/audacity/issues/2279)

![LabelSummary](https://user-images.githubusercontent.com/11681097/149136729-b4d6148c-6253-4f16-85e1-163d4293f959.png)

**Comment by SteveDaulton** [comment]
> There are plans to feature both macros, nyquist plugins, and other kinds of plugins on a plugin download page for 3.2, so I think a downloadable nyquist plugin would be best for this.

Is that in addition to, or instead of: https://wiki.audacityteam.org/wiki/Download_Nyquist_Plug-ins

**Comment by SteveDaulton** [comment]
"Label Track Info" plug-in available on my blog: https://audionyq.com/label-track-info/

Peter requested that the plug-in could include a count of the number of labels that start before zero (currently it just  says if any label tracks start before zero). I may add this feature if I have time.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with 3.1.3 and @SteveDaulton 's new plug-in

This works fine:
![image](https://user-images.githubusercontent.com/50205984/149352859-46b631f7-e500-453b-89f3-f5f9770ce648.png)

**Comment by SteveDaulton** [comment]
If this plug-in is to be shipped with Audacity, the strings will need to be updated so as to be translatable. (Paul L knows how to do this).
