### ISSUE TITLE
Proposal Effect Presets - show preset name when in use

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2417]
**Describe the bug**
Currently, when a named user preset is loaded there is no indication of this.

It would be useful to the user to know this, especially when revisiting the effect later as Audacity "remembers" and recalls the last-used settings for the effect - but the user may have forgotten what they used last time.

Originally logged as a Proposal in the Audacity Wiki by Bill Wharrie in 2019:
https://wiki.audacityteam.org/wiki/Proposal_Effect_Presets

**To Reproduce**
1. Get some audio
2. select it
3. apply any effect that can have Managed presets
4. choose one of the presets (system or user custom-defined)
5. Observe: there is no indication in the effect dialog of which preset is in play

**Expected behavior**
1. Display the name of a named user preset when it is loaded.
2. If the sure manual changes or sets the curve then this field will show a blank preset (or possible "un-named")

**Screenshots**
Example based on the Telephone preset deployed in Filter Curve EQ
![image](https://user-images.githubusercontent.com/50205984/149161998-2466073d-14c7-42dd-bc2b-6517f16eafb3.png)

Other effects may not have such an obvious space to locate the preset name - but such space could be created

**Additional information (please complete the following information):**
 - OS: all
 - Version: all

**Additional context**
None

**Comment by LWinterberg** [comment]
IMHO, the entire "manage" button could be replaced with a preset dropdown, perhaps like Adobe has it: 
![image](https://user-images.githubusercontent.com/87814144/149171494-4d887f07-282d-4101-ac63-93c86f09aaa6.png)

I'm not quite sure where I'd put the managing options (save current settings to preset, delete preset, favourite preset, import/export preset) though. I always found Adobe's row of random buttons in the effects quite confusing.

**Comment by LWinterberg** [comment]
closing in favor of https://github.com/audacity/audacity/issues/5158
