### ISSUE TITLE
Scrubbing/Playing/Recording using the keyboard: playback/recording cursor is not shown

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#2421]
**Describe the bug**
When scrubbing using the keyboard, the playback cursor is not shown

**To Reproduce**
1. Create some audio in a track
2. Position the cursor somewhere in the audio
3. Hold down either U or I to scrub backwards or forwards respectively.
4. The playback cursor is not shown. However, the audio is played, and the playback position in the time toolbar is updated correctly

**Expected behavior**
The playback cursor should by shown during keyboard scrubbing.

**Screenshots**

**Additional information (please complete the following information):**
- Windows 10
- Audacity 3.2.0 alpha, commit: 7129052

**Additional context**
This bug was introduced by commit: 7129052, and is a regression.

**Comment by LWinterberg** [comment]
cc @Paul-Licameli

**Comment by Paul-Licameli** [comment]
@DavidBailes It was surely not introduced exactly at commit 7129052 which is only a merge.  Do you know a bracket for bisection?

**Comment by Paul-Licameli** [comment]
> @DavidBailes It was surely not introduced exactly at commit [7129052](https://github.com/audacity/audacity/commit/71290526d3a03c07a1da298ffceea503c6d45113) which is only a merge. Do you know a bracket for bisection?

I have a bracket.  Certainly something in that group of commits.

**Comment by petersampsonaudacity** [comment]
When I test 3.1.3  on W1 - I do see the Playback cursor

BUT the Playback speed in both directions is slow

**Comment by DavidBailes** [comment]
Just in case people haven't noticed, when scrubbing using a mouse, the playback cursor is also not shown.

**Comment by Paul-Licameli** [comment]
I notice the playhead is absent even with ordinary play.  It started at commit d5250002f705c656eafce0cc4a69456dd06f6ea8

**Comment by petersampsonaudacity** [comment]
> BUT the Playback speed in both directions is **_slow_**

OIC - at normal zoom level it plays at half speed
Zoom out one level and the U and I shortcuts play at normal speed

This is un-obvious and not readily "discoverable"

**Comment by petersampsonaudacity** [comment]
> I notice the playhead is absent even with ordinary play. It started at commit [d525000](https://github.com/audacity/audacity/commit/d5250002f705c656eafce0cc4a69456dd06f6ea8)

OK so testing on W10 with latest alpha:  audacity-win-3.2.0-alpha-20220113+7129052-64bit

I do get the missing play cursor, both normal play and scrubbing - I also got a crash and sent the ET phone-home error report

**Comment by petersampsonaudacity** [comment]
Tested on W10 with audacity-win-3.2.0-alpha-20220114+b92b638-64bit

I confirm that this now works fine on W10 - the play/record cursors are back again
