### ISSUE TITLE
Prevent projects being on cloud or networked drives

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2423]
**Describe the bug**
Since Unitary Project format (AUP3) was introduced in 3.0.0 we have experienced many users with damaged projects, often down to damaged SQLite database.

On the Forum Jademan (aka @JohnColket ) donates a fair amount of his time repairing such projects for folk when he can

Based on his experience with this he wrote on this Forum thread:  https://forum.audacityteam.org/viewtopic.php?f=47&t=122625&start=10
|So I am going to rephrase my note above to say that I believe many of the reported issues of corrupted projects were born on networked or cloud drives. Other than that, I am going to stick to repairing these projects and let others deal with the whys and wherefores.

**To Reproduce**
1. Save a project to a cloud or networked drive
2. Close Audacity
3. Relaunch
4. Open the Project from the cloud or networked drive
5. Observe:  the project **_may_** be corrupted YMMV 

**Expected behavior**
I suggest that Audacity be made to block the following commands from operating on a cloud or netwirked drive
1. **File > Save Project > Save Project**
2. **File > Save Project > Save Project As**
3. **File > Open**

It is debatable as to whether or not **File > Save Project > Backup Project** should be allowed or not.
_In some ways it would seem eminently sensible to allow this for a backup - but note that 3. above would mean that the backup project could not be opened from the clod/networked drive - the user would need to copy the backup to a pukka drive._

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS: all
 - Version: Audacity 3.x.x

**Additional context**
Doing this could:
a) result in fewer damaged AUP5 project
b) reduce @JohnColket 's volunteer workload quite a lot

As this bug can result in data loss I would suggest that this should really be rated at P1 @Penikov

**Comment by petersampsonaudacity** [comment]
An alternative would be to allow the use of such drives, but issue a strong warning against to the use - and it really should be a **_STRONG_** warning I can't help thinking.

**Comment by crsib** [comment]
I'm not sure that there is any reliable way to identify that some folder is backed with a cloud provider

**Comment by SteveDaulton** [comment]
One part of the problem is that some users don't know if they are using a network drive.

Example: Google Drive / One Drive / Dropbox / ... may appear as normal drives (and in some cases may work without problems).

Example 2: In educational environments, the user's home directory may be mapped to a network drive, while to the user it may look like a local drive.

**Comment by petersampsonaudacity** [comment]
We have long had warnings like this in several pages in the Manual
|You are '''''strongly''''' advised '''''NOT''''' to save your active project to an external USB stick/disk, networked storage or cloud storage as it is unlikely to be fast enough for satisfactory recording and editing.
*Audacity blocks you from using FAT/FAT32 disks for saving project files as they are limited to a maximum 4GB per single file and this can easily be exceeded when editing. 

On this page: https://alphamanual.audacityteam.org/man/Audacity_Projects

And on 
1. Save Project page,  
2. FAQ:Opening and Saving Files


The page for File>open fails to mention this - perhaps it should ...

**Comment by crsib** [comment]
> One Drive / Dropbox

They simply sync folders. Google Drive has an option with a drive but allows syncing any directory as well

**Comment by SteveDaulton** [comment]
> They simply sync folders.

Although we don't have many _clear_ reports yet, some forum posts appear to indicate that sync folders can cause problems. Perhaps if the folder is being synchronized / updated while the project is open?





> I'm not sure that there is any reliable way to identify that some folder is backed with a cloud provider

I think that's right, though give the surprising regularity of these problems, perhaps it would be worth showing an "are you sure?" warning if the address looks like it is probably an external / network / some other kind of "special" drive.

**Comment by Penikov** [comment]
Despite the probability of data loss, this is an old known issue, and it has appeared with .aup3 format. 

The problem Peter spotted is not a bug but a change request. 
I'm sure we need to prevent data losses. It will reduce the unnecessary load for @JohnColket and will make user experience better. 

I see there two aspects that probably need to be reconsidered: 
- Technical aspect. What is wrong with .aup3 and what we can fix/improve in .aup3 format if a problem is there?
- UX aspect. Do we want to control if a user uses a proper drive? Maybe it would be better to show dozens of warnings to let a user know that placing the project file on a shared folder/network disk is not a good idea.

So my point here is we need to get users informed where to place project files properly.

**Comment by LWinterberg** [comment]
So, the long and short of this issue seems to be:

* From a technical standpoint, it's both very difficult / potentially impossible to identify networked drive, and even moreso cloud synced drives
* From a UX standpoint, banning cloud drives is just bad as interferes with common use cases.

The better solution may be to make the project file play nicer with networked drives in general.
