### ISSUE TITLE
Audacity 3.2 crashes when recovering files

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#2424]
**To Reproduce**
1. Start 3.2, make some sound
2. Kill Audacity (such as with Help > Diagnostics > Test Segfault Report)
3. Restart and see project recovery dialog
4. Choose "Recover Selected" and "OK"
5. Boom

This was only recently introduced with the Observers branch, and the fix is known

**Comment by petersampsonaudacity** [comment]
This only appears to affect the above-the-line non_Nyquist effects - i.e the built-in effects

**Comment by petersampsonaudacity** [comment]
Apply Macro crashes Audacity too

**Comment by petersampsonaudacity** [comment]
Tested on W10 with audacity-win-3.2.0-alpha-20220114+b92b638-64bit

I confirm that this now works fine on W10 with no crash
