### ISSUE TITLE
Effects, Generators (and Macros) crash latest 3.2.0 alpha

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2426]
**Describe the bug**
Effects crash latest 3.2.0 alpha  -  audacity-win-3.2.0-alpha-20220113+7129052-64bit

**To Reproduce**
1. Launch Effects crash latest 3.2.0 alpha
2. get some audio
3. Select some audio
4. Apply any effect
5. Observe: crash

**Expected behavior**
Effect to be applied properly with no crash

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version audacity-win-3.2.0-alpha-20220113+7129052-64bit

**Additional context**
This warrants P1

This is a regression on 3.1.3 and the earlier 3,2,0 alpha  -  audacity-win-3.2.0-alpha-20220111+f133869-64bit

**Comment by petersampsonaudacity** [comment]
Applying Macros also crash the latest 3.2.0

**Comment by petersampsonaudacity** [comment]
Some but not all Generators also cause a crash.

**Comment by SteveDaulton** [comment]
Also repeatable on Linux.

Even better, on relaunching Audacity and selecting "Recover", Audacity appears to recover the audio then immediately crashes again.

**Comment by Paul-Licameli** [comment]
PR #2425 will fix this too

**Comment by petersampsonaudacity** [comment]
Tested on W10 with audacity-win-3.2.0-alpha-20220114+b92b638-64bit

I confirm that this now works fine on W10 with no crash
