### ISSUE TITLE
Linux: Playback stutters at start

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2427]
**Describe the bug**
The audio stutters when playback starts. This is a regression against 3.2.0-alpha-20211210

See
e4f215f Good
e2b1a2b Bad

**To Reproduce**
1. Generate a Chirp
2. Press Play
3. Hear a stutter as playback starts.

**Expected behavior**
Playback to start without stuttering.

**Screenshots**

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version : 3.2.0-alpha-20220113
 - (if relevant) Sound Device: ALSA default (internal sound card)

**Additional context**
Playback cursor does not move.

See also #2314, #2331

Bisected to: 81f74f7
Consider commit range: 81f74f72485c81dc90e21894270e9bea34e03a0a...fc458eb314d633b10bf0e688da6d269488bfef03

The commit fc458eb314d633b10bf0e688da6d269488bfef03 fixed similar issue #2314

**Comment by Penikov** [comment]
Audacity 3.2. not only stutters but stucks at the playback on Win10

**Comment by SteveDaulton** [comment]
In 3.2.0-alpha-20220115, the playback cursor moves with playback, but the stuttering still occurs.

**Comment by AnitaBats** [comment]
@SteveDaulton could you please tell the bisection bracket?

**Comment by SteveDaulton** [comment]
e4f215fa645dfb8a6f6aaedf53c134d9aba9e503 Good
e2b1a2be6b92661628bbb054f915bc50b211c020 Bad

**Comment by SteveDaulton** [comment]
81f74f72485c81dc90e21894270e9bea34e03a0a is the first bad commit

**Comment by werame** [comment]
I've been using my own builds from based on https://github.com/audacity/audacity/commit/fc587e67556a940a5d46eb0fe9fbdbfcbfc0b43e and they don't stutter. 

There is a strange issue when switching to asio as it takes a few seconds to "think about it" in the drop-down menu for the output type switching, but playback is ok otherwise.

**Comment by SteveDaulton** [comment]
> I've been using my own builds from based on [fc587e6](https://github.com/audacity/audacity/commit/fc587e67556a940a5d46eb0fe9fbdbfcbfc0b43e) and they don't stutter.

On Linux?

**Comment by werame** [comment]
Windows. No ASIO on Linux, afaik... On a quick test, all 4 interfaces (WASAPI, MME, DS, ASIO) are ok with that build. 

I recall in the past that it was a pita to get SuperCollider to work properly on Linux. Depending on the pulseaudio, jack vs jack2 and what not it would stutter sometimes. It also uses portaudio as its library, IIRC.

**Comment by SteveDaulton** [comment]
> I recall in the past

Early implementations of PulseAudio were horrible. Ubuntu was guilty of making it their default sound system long before it was reliable. It has improved immeasurably since then.

**Comment by Penikov** [comment]
Just have caught the same bug on Fedora 35, Gnome

**Comment by SteveDaulton** [comment]
Also reported on the forum: https://forum.audacityteam.org/viewtopic.php?p=448766#p448766

**Comment by kalsan** [comment]
I'm also experiencing this problem under Debian 11, audacity `2.4.2`. 

```
$ lspci | grep -i audio
00:1f.3 Audio device: Intel Corporation 100 Series/C230 Series Chipset Family HD Audio Controller (rev 31)
01:00.1 Audio device: NVIDIA Corporation GP102 HDMI Audio Controller (rev a1)
```

**Comment by jhdedrick** [comment]
Also happens on Windows, version 3.2.2

This has made Audacity unusable for me.  Could you post the last version known not to suffer from this bug?

**Comment by voidiums** [comment]
Transport -> Transport options -> "Software Play-through - On" fixed the problem on my side (Linux); no more stuttering at the beginning.

Maybe the bug is coming from some Hardware play-through function (if such thing exists)?

**Comment by SteveDaulton** [comment]
> Transport -> Transport options -> "Software Play-through - On" fixed the problem on my side (Linux); no more stuttering at the beginning.

I can confirm that this does dramatically reduce stuttering on starting playback, though it's a tedious workaround to have to be continually enabling and disabling software playthrough.

**Comment by voidiums** [comment]
> I can confirm that this does dramatically reduce stuttering on starting playback, though it's a tedious workaround to have to be continually enabling and disabling software playthrough.

Euuh... I don't know what you mean by "have to be continually enabling and disabling software playthrough."  because once I ticked that checkbox it stays on even if I close and reopen audacity (so only have to be done once) unless there are reasons for turning it on and off for other parts of the software (I only know the basics in audacity).

**Comment by SteveDaulton** [comment]
> "have to be continually enabling and disabling software playthrough."

If you want to record streaming audio, Software Playthrough must be OFF.
If you want to record from a microphone without hearing a delayed echo in your headphones, Software Playthrough must be OFF.
If you want to record a MIDI synth without hearing an echo, Software Playthrough must be OFF.

In short, if you are _only_ using Audacity for editing, then it's probably OK to leave Software Playthrough enabled, but if you are also using Audacity for recording then you will probably need to disable Software Playthrough before recording, and back on again to work around this playback issue.

**Comment by voidiums** [comment]
Thanks, Good to know (even if I'm only using it for editing purposes).

**Comment by voidiums** [comment]
One more thing, I tried both the official AppImage and the flatpak of version 3.2.3 on a fedora rawhide virtual machine and I didn't get any stuttering, without me changing anything (software playtrough was off).

**Comment by Ryan-Miller-Audacity** [comment]
Testing in my Linux VM in an older version of Audacity I was able to reproduce the playback stutter as described and confirmed that I no longer observe the stutter in this build. I also sanity checked Windows and MacOS and confirmed no changes in behavior there.

**Comment by SteveDaulton** [comment]
Although this stuttering issue is not as bad as when I opened this issue, Audacity still stutters on starting playback about 50% of the time. Personally I wouldn't consider that to qualify as "fixed".

**Comment by crsib** [comment]
It appears that issue is back, I don't really know why.

**Comment by crsib** [comment]
TBH I don't understand when and how it went wrong, the fix seems to be embarrassingly simple...

**Comment by crsib** [comment]
@SteveDaulton thank you a lot for checking this again!
