### ISSUE TITLE
libmp3lame fails to built with the native x64 compiler on Windows due to bad conan file that only targets the x86_64 cross-compiler

### ISSUE THREAD

**Issue by werame** [audacity/audacity#2431]
When building the current master with the native x64 VS2019 compiler (`[vcvarsall.bat] Environment initialized for: 'x64'`):

```
--- HIP DECODING LIBRARY UPTODATE ---

libmp3lame\bitstream.obj : fatal error LNK1112: module machine type 'x86' conflicts with target machine type 'x64'
libmp3lame/3.100: 
```

I traced down the problem to the conan file for libmp3lame

```
  def _build_vs(self):
        with self._msvc_build_environment():
            shutil.copy("configMS.h", "config.h")
            tools.replace_in_file("Makefile.MSVC", "CC_OPTS = $(CC_OPTS) /MT", "")
            command = "nmake -f Makefile.MSVC comp=msvc asm=yes"
            if self.settings.arch == "x86_64":
                tools.replace_in_file("Makefile.MSVC", "MACHINE = /machine:I386", "MACHINE =/machine:X64")
                command += " MSVCVER=Win64"
            command += " libmp3lame.dll" if self.options.shared else " libmp3lame-static.lib"
            self.run(command)
```

There's a MACHINE substitution done for `x86_64`, but that's (just) the cross-compiler. The substitution of the `/machine:I386` bit in the build file also needs to happen for the native `x64` compiler string.

It appears that the upstream/origin for that file might be https://github.com/bincrafters/conan-libmp3lame/blob/testing/3.100/conanfile.py but it seems no longer maintained (repo is set to archive mode), so Audacity would have to take ownership of the file and patch it.  Ah, ok there's a new "mega-upstream" at https://github.com/conan-io/conan-center-index/tree/master/recipes/libmp3lame but they have even more open issues that Audacity.

**Comment by crsib** [comment]
There is an easy workaround for this issue - just do not build from the dev tools environment. x64 is not a valid value for the `settings.arch`. Please note, that Conan values do not necessarily match the values used by a specific platform. Conan needs to have consistent architecture names across all platforms.

Running from the dev command prompt potentially prevents Conan from setting the correct environment: https://github.com/conan-io/conan/issues/3673

Generally, there is no need to run CMake from the dev tools command prompt anyway.

**Comment by werame** [comment]
Well, it kinda is if you use VS-supplied cmake, because it's not the in the path otherwise. But I ended up installing the 3.22.1 version separately anyway due to its /FS bug fix (which turned out not to outfox the MS Defender though, which still managed to hose the build occasionally during pbd file writes, even with exclusions set, but that's another story).
