### ISSUE TITLE
Windows build: pass global /LTCG flag to linker from the get go?

### ISSUE THREAD

**Issue by werame** [audacity/audacity#2434]
This is not exactly a bug nor a killer feature, but when (finally) managed to build Audacity on Windows, I noticed at the final liker step:

```
  mp3lame.lib(lame.obj) : MSIL .netmodule or module compiled with /GL found; re
  starting link with /LTCG; add /LTCG to the link command line to improve linke
  r performance
LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/LTCG' specification [M
:\gh\aud-build\src\Audacity.vcxproj]
```

Looking at https://stackoverflow.com/a/37747549/3588161 what that means is that code generated (with /GL) in `mp3lame.lib(lame.obj)` would not actually work without that global /LTCG linker flag. I'm not sure how much quicker the linker step would go if we followed the advice in that warning and issued /LTCG from the get go. It took about 30s on my pretty dusty computer the way it's done now.

Alternatively, I'm not sure if  Link Time Code Generation (which seems to be more or less the same as whole program optimization in MS lingo) is worthwhile doing *in just one object*, i.e. just in `mp3lame.lib(lame.obj)`.

For some other projects like those [using Qt](https://www.qt.io/blog/2019/01/02/qt-applications-lto), LTCG can some improvements in VM size (ok, that Qt article does have a [misleading graph](https://en.wikipedia.org/wiki/Misleading_graph#Truncated_graph); the real VM improvement was a reduction by a factor of 0.86, i.e. some 14% less), but for that to be (more) effective for Audacity more libraries/objects would have to be compiled with /GL, besides that lone one in mp3lame.lib, I think.

**Comment by werame** [comment]
Actually, with warm caches this is nowhere near as bad. A RelWithDebInfo re-build after changing some files succeeds surprising fast at the linker stage, like less than 5 seconds to link, even though it prints the some warning/complaint. So I guess it's not really worth the hassle to fix.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444) which uses a different build system. This bug should no longer be applicable.
