### ISSUE TITLE
Smart clips cause incorrect effects

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2435]
**Describe the bug**
Smart clips may cause effects to produce the wrong result

**To Reproduce**
1. Generate 10 seconds tone, amplitude 1.0.
2. Split the track so there are two clips
3. Select all
4. Amplify to -6 dB
5. Normalize to -1 dB
6. Observe that the peak level goes down to -7 dB

**Expected behavior**
Same as Audacity before Smart clips

**Screenshots**

**Additional information (please complete the following information):**
 - OS: Linux / Windows (probably also  macOS but not tested)
 - Version 3.2.0-alpha-20220115
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]

**Additional context**
The hidden part of the clips is affecting the gain calculation.
Labelled P1 because many users (especially audiobook producers) rely on accurate amplitude effects.

**Comment by werame** [comment]
Pretty related, I guess:  #2271 The fact that the user can't tell (unless they rely on their memory) which clips have hidden data and which don't is an issue in this case.

> Expected behavior
> Same as Audacity before Smart clips

I guess you mean that it should drive the not currently in-clip-window (i.e. "invisible") parts into clipping, if necessary.

**Comment by SteveDaulton** [comment]
> I guess you mean that it should drive the not currently in-clip-window (i.e. invisible) parts into clipping, if necessary.

Shouldn't it act only on the visible part of the clip?

**Comment by werame** [comment]
I guess it depends what semantics one wants for invisible data. If the fx is applied only to visible data, then if the user shifts (or enlarges) the smart clip window later, it would work as a distortion effect of sorts in that case as it would apply only to some part of the smart clip. In DAWs that support per-item non-destructive fx (like Reaper), if you shift or enlarge the window then you get the fx applied to the new window automagically. I'm not sure what happens in Reaper with a "stem-based" work flow [like this](https://youtu.be/TNpAAhnR09A?t=277) (which by the way, was the motivation for another enh. request of mine  #2464). I'll have to test it out, but I think in Reaper you can't change/enlarge the window anymore after making a "take", which applies an effect destructively.  So maybe that's a 3rd solution to this conundrum: applying an fx could just discard the invisible data... although I see you think  that's a (different) bug #2479 when it happens in Audacity.

I suppose that a less surprising approach would be to pop a dialog box and ask if the effect should apply to invisible data or not, perhaps also tied to global or per-project preference. (I'm not sure if Audacity can do per-project preferences right now, by the way. I mean SQLite3 makes that easy to do, but I think there's no UI for per-project preferences. )

**Comment by SteveDaulton** [comment]
> if you shift or enlarge the window then you get the fx applied to the new window automagically

Of course you do, because the fx have not been applied to the actual audio data, they are just applied to the playback (until you export / mix-down).

**Comment by Tantacrul** [comment]
@SteveDaulton, I've followed the steps but I'm stuck at the last bit:

Observe that the peak level goes down to -7 dB

Here's what I'm seeing:
<img width="1719" alt="image" src="https://user-images.githubusercontent.com/21022311/206753871-e2898fec-b628-4aa3-8b81-e5ffae276bfa.png">

**Comment by SteveDaulton** [comment]
The bug appears to be fixed in the current version.

**Comment by Tantacrul** [comment]
That would explain it. Thanks!
