### ISSUE TITLE
Progress indicator error for shipped effects and generators (non-Nyquist) - also Find Clipping

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2447]
**Describe the bug**
The progress dialog for the shipped non-Nyquist effects has two regression faults against 3.1.3 and earlier
1. Initially the progress bar fails to move while the Remaining Time counter racks up ridiculous amounts of time
2. Eventually the progress bar appears but is immediately drawn at half-way and remains there while the Elapsed Time and the Remaining Time counter remain in increasing lock step second by second,

1 will be disconcerting/alarming to the user - and 2 is just plain wrong.

**To Reproduce**
You need a longish project to observe this regression error
1. Get a 2 hour stereo project
2. Select all the audio
3. Effect > Amplify _(or any shipped non-Nyquist effect)_
4. Observe: the progress dialog appears
5. Observe: the Elapsed Time counter increases properly second by second
6. Observe the green progress bar is not shown
7. Observe the Remaining Time counter climbs alarmingly high to 6~7 minutes - see Image 1
8. Observe: After 20 secs or so _(YMMV)_ the progress bar appears immediately at half way and gets stuck there.
9. Observe: the Remaining Time Counter resets to be the same no. of secs as the Elapsed Time Counter - see Image 2
10. Observe: the effect eventually completed at 50 seconds (plus a 10 second hiatus for the redraw) and then all was well

I observe that the non-Nyquist above-the-line shipped Generators are also afflicted by this bug.
Analyze > Find Clipping is also afflicted _(Nyquist Analyzers seem to be unaffected)_

**Expected behavior**
1. a more accurate calculation of initial Remaining Time
2. Progress bar to work properly indicating progress
3. Remaining Time counter to work properly counting down to 0 seconds

**Screenshots**
1)  Step 7
![image](https://user-images.githubusercontent.com/50205984/149919032-176dde77-e14e-44a9-a3be-a97c38b78b26.png)

2) Step 9
![image](https://user-images.githubusercontent.com/50205984/149919157-133203a8-5ff5-485e-b0b8-7eb9d13e6b5f.png)

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version: audacity-win-3.2.0-alpha-20220117+a92a9c5-64bit
 - The Amplify finished 4 seconds later with both counters showing 50 seconds

**Additional context**
I experienced this this morning when working on my regular overnight Monday recording of a Timer Recording of a webcast.
a) my initial work is t trim the 5 minutes off the front and the 10 minutes off the back so I just get the 2 hour show and then use Amplify to normalize to -2db (and the export a WAV and Save the project.
b) to revalidate I relaunched and reopened the project (clean and compacted) and repeated the test => same results
c) I also checked with a 2 hour stereo chirp in an unsaved project => same result

@Penikov  Pavel and @LWinterberg Leo - I'm thinking this regression warrants a P1/P2 rating
3.2.0 should not be seen as releasable like this.

Update from @Paul-Licameli : this bisects to 881ee943b44ed202c1ba8a4173dbbda23b6085b3

**Comment by petersampsonaudacity** [comment]
BTW if after Step 10, I exit Audacity and choose not to save the project Compaction takes 25-30 seconds

**Comment by SteveDaulton** [comment]
> a) choose not to save the project Compaction takes 25-30 seconds

Why do we ever have "Compaction" when an unsaved project is being closed without saving? Can't it just be closed and deleted?

**Comment by petersampsonaudacity** [comment]
Testing on macOS 12.1 Monterey with audacity-win-3.2.0-alpha-20220117+a92a9c5-64bit

I see the same problem on Mac - but the highest forecast time is much lower climbing to only 1h6m and the amplify itself takes a mere 6 seconds compared with 50 seconds on Windows.


> > a) choose not to save the project Compaction takes 25-30 seconds
> 
> Why do we ever have "Compaction" when an unsaved project is being closed without saving? Can't it just be closed and deleted?

In my tests for Step 1 I opened a previously saved project.
Then I made the changes and exported a WAV
And then exited without choosing to save

**Comment by petersampsonaudacity** [comment]
I observe that the non-Nyquist above-the-line shipped Generators are also afflicted by this bug.

**Comment by Paul-Licameli** [comment]
Update from @Paul-Licameli : this bisects to https://github.com/audacity/audacity/commit/881ee943b44ed202c1ba8a4173dbbda23b6085b3

**Comment by Paul-Licameli** [comment]
See #2546

**Comment by petersampsonaudacity** [comment]
Testing on W11 with audacity-win-3.2.0-alpha-20220822+be66b5b-x64-msvc2022

@Paul-Licameli  I confirm that this now appears to be fixed properly.  I tested with Amplify and a selection of other effects.

BUT see also:   Progress dialogs for effects (and generators) show erroneous durations #2959 
Which is now OK for effects (i.e. thsi logged issue) - but fails for Generators.

**Comment by dozzzzer** [comment]
I've tested this on MacOS using various effects and have two main concerns:

1. the progress bar basically has three states: 0% -> 50% -> 100%; I wonder if can use more atomic increments rather than incrementing the progress indicator by half each time.
2. the initial and subsequent calculation of Remaining Time isn't accurate. 
For example, with the Invert effect over a 6h-long track (to have the progress bar stay longer), I've observed the following: it grows up to 4h 11m untill the progress reaches 50%, and then the **Remaining Time** counter starts showing the exact same value as the **Elapsed Time** does: ...17s, 18s and finally 0 when the process terminates. Instead, the initial time should be calculated properly (showing appr. 24s value in my case), then should be gradually going down till it reaches zero and not be in sync with elapsed time value.

https://user-images.githubusercontent.com/70063970/186254213-6d597689-24ee-4467-a33c-40d89ffdd8a9.mp4

**Comment by petersampsonaudacity** [comment]
@dozzzzer @Paul-Licameli 

I just tested this again on W11 with latest alpha master  -  audacity-win-3.2.0-alpha-20220823+bd58f72-x64-msvc2022

I used a six hour stereo project amd used Invert - the progess dailog worked properly.  Paul's change looks to have fixed this, for Windows at least.

_I cannot test on Mac today - but I will be back in Manchester tomorrow so should be able to test on Mac then or on Friday_

**Comment by dozzzzer** [comment]
@petersampsonaudacity @Paul-Licameli 
I think I was testing the fix using the wrong build. Please disregard my previous comment, all seems to be in order now. Closing the ticket.
