### ISSUE TITLE
Playback. When a clip partially dragged behind zero, the playhead stuck in the end of the clip

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2448]
**Describe the bug**
When a clip partially dragged behind zero, the playhead stuck in the end of the clip
Actually there is a lot of scenarios. But more often the bug had been caught after dragging the clip behind zero. 

**To Reproduce**
1. Generate a chirp
2. Drag the clip behind zero partially as shown in the figure below:
3. Select a random region by the cursor. For example:
![image](https://user-images.githubusercontent.com/25851359/149934170-fcb7f122-f93e-47e8-a3ae-417d65447a99.png)

4. Left-click on empty space below the track/tracks.
![image](https://user-images.githubusercontent.com/25851359/149934117-6f2c52bf-0066-4fff-ad61-d1ef5341f9a2.png)

5. Click the Play button
6. Observe the playhead have run along the track, but stuck at the end of selection indicator on the timeline and playback is running, 
In some cases it would be vary. A playhead could stuck at the end of a clip or even at the end of a project (at the last clip of the project)

Please note: This is kind of heisenbug. So be ready to reproduce it many times before it will have caught )

**Expected behavior**
Playback has stopped at the end of the clip/selection/project as usual

**Additional information (please complete the following information):**
 - OS: Win 10. Mac OS
 - Audacity 3.2.+
 
 Related to #2453

**Comment by AnitaBats** [comment]
may be related to #2453, #2316

**Comment by Penikov** [comment]
Still reproducible 
![image](https://user-images.githubusercontent.com/25851359/150494662-78130c64-6391-4d09-8074-c7322cb12096.png)

The issue is a kind of flaky bug. So you need to try several times before it has been reproduced.

**Comment by LWinterberg** [comment]
I can no longer reproduce this at all
