### ISSUE TITLE
The playhead stuck at the end of a clip while playback is running

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2453]
**To Reproduce**
1. Add a clip
2. Select the whole clip with double LMB on the clip handle
3. Turn on the looping toggle.
4. Click the Skip to end button (it turns the audio cursor to the end of the clip/track)
5. Click The Play button
Observe: the playhead is stuck at the end of a clip while playback is keep going on.

**Expected behavior**
While playback is running, a playhead moves along the track as usual

**Screenshots**
![image](https://user-images.githubusercontent.com/25851359/150097160-66fe8276-b5ce-4404-a204-ac282673761b.png)

**Additional information (please complete the following information):**
 - OS: Windows 10, MacOS
 - Version: Audacity 3.2+

**Additional context**
This issue is not to be confused with this one: #2448
They are different but related

**Comment by AnitaBats** [comment]
may be related to https://github.com/audacity/audacity/issues/2316

**Comment by werame** [comment]
Thanks for filing this. I noticed it too and for a while I thought it was a bug I introduced in my (not yet merged) PR/patch.

For some reason it seem more likely to happen when you have multiple tracks of different lengths in the project.

**Comment by Penikov** [comment]
Highly likely related to #2448

**Comment by LWinterberg** [comment]
I can no longer reproduce this

**Comment by petersampsonaudacity** [comment]
See also:   "Play Cut Preview" does not exit "play mode" #3792
