### ISSUE TITLE
Playback Looping. Bizarre behavior if a looping region is crossing zero

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2454]
**Describe the bug**
If the looping region is partially dragged behind zero while playback is running, the part of a loop that appears on the negative timeline plays silently. 
That might look bizarre to users.

**To Reproduce**
Steps to reproduce the behaviour:
1. add a clip (for example, 30 sec. tone)
2. Point an audio cursor at the 5th second
3. Assign a new 15-sec looping region from 0 to 15
4. Click the play button then drag the looping region partially behind zero as shown below while playback is running :
![image](https://user-images.githubusercontent.com/25851359/150107374-8611f7e4-2ccd-435e-86d9-02afc386d56c.png)

Observe: The playhead is disappeared, playback is running silently up to zero point, but then audio plays as usual.

**Expected behaviour**
The correct behaviour is: If the looping region crosses zero point, playback always starts from zero.

**Additional information (please complete the following information):**
 - OS: Windows 10]
 - Version: Audacity 3.2]

**Additional context**
Relates to: #2143, #2448

**Comment by petersampsonaudacity** [comment]
Testing this on W10 with audacity-win-3.2.0-alpha-20220117+a92a9c5-64bit

a) I note I **_cannot_** click in the left (or right) edge of a loop region, _to shorten or extend the loop region_,  and drag it before T-0 - the drag is forcibly stopped at T=0
For this I get the double-headed arrow icon <->

b) However I can click in the loop region whereby I get the drag-hand - and with this I van drag the clip (or part of it al least) to be before T=0

This begs the question: if a is blocked then why is b allowed.  To my mind it make sense foe both of them to be blocked:
1. this provides consistency
2. it really makes no sense to have part of a loop region to be before T=0 (I, certainly, can think of no practical use case)

**Comment by petersampsonaudacity** [comment]
BTW the hand icon is **_not_** implemented correctly for the loop region drag:

a) when hovering over the loop region you get the open-hand icon.  This is correct as it indicates the **_potential_** for dragging.

b) but when you then click the open hand-should change to a closed-hand to indicate the drag.

Does this need to be logged as a separate issue @Penikov @LWinterberg @Tantacrul  ?

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
