### ISSUE TITLE
Playback. MIDI. Adjustment of global playback volume is ignored for MIDI

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2455]
**Describe the bug**
Adjustment of global playback volume is ignored for MIDI

![image](https://user-images.githubusercontent.com/25851359/150121486-4d02bb08-89e8-4cfd-8ee6-ef774afbd145.png)

**To Reproduce**
1. Import a MIDI file
2. Adjust Playback volume to 0.00
3. Run playback

MIDI ignores global playback volume adjustment

**Expected behavior**
Playback volume adjustment works the same as for other types of audio. 

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version. 3.2.0

**Comment by SteveDaulton** [comment]
What if an external hardware synth is being used to play the MIDI? Would you expect Audacity's playback volume to control the playback volume of the external hardware?

Comparison with Ardour 5:
When playing MIDI using an internal synth plug-in, the master mixer slider controls the output from the plug-in.
When playing MIDI using an external synth, the master mixer slider has no affect on the external synth, though MIDI track sliders do affect the playback level (through  MIDI Volume commands).

Although it may not be apparent to Windows users, Audacity always uses an "external" synth for MIDI playback. https://github.com/audacity/audacity/issues/2393 would change that, but has been closed.

**Comment by werame** [comment]
What does Audacity even use a MIDI synth on Windows? The wiki says it only works on Mac and  Linux, but to my surprise it works on Windows too... I don't see a separate process though. Does it use some in-process library? In that case setting the volume would not be so difficult. Even for an external app, there might be an API.

**Comment by Penikov** [comment]
I believe the playback volume handle should work equally for everything that could be replayed in Audacity
And I expect that external hardware or software devices and MIDI tracks (which are not a track for sure) have their own volume adjustments. If not, a user should have to manage volume for that kind of device somehow. 

By the way, does Audacity can manage playback on external devices?

**Comment by Penikov** [comment]
In other words, from a technical point, there is no issue, But there is a kind of inconsistency.

**Comment by SteveDaulton** [comment]
> What does Audacity even use as MIDI synth on Windows?

Windows has its own MIDI synth. Audacity uses that by default.


> I believe the playback volume handle should work equally for everything that could be replayed in Audacity

but that's the point - MIDI is not playing "in" Audacity because Audacity does not have a synth. If the user wants the synth to play more quietly, they should turn down the synth's output volume. If Audacity shipped with its own synth, then sure you could have a master volume control for it, though I would strongly suggest that it should be separate from the master audio volume.

**Comment by Pokechu22** [comment]
Regarding the Windows MIDI synth: if you right-click the sound icon on the taskbar, select "Sounds" (which opens the old sound dialog box and not the new UWP settings), switch to the playback tab, right-click any audio device (well, at least most will show it), and select "About Software MIDI Synthesizer", you get this:

![image](https://user-images.githubusercontent.com/8334194/150207929-e3802b7d-6d00-44ce-a951-23720bef5521.png)

If I recall correctly, when Audacity's global playback volume slider changed the system volume, it did affect MIDI volume as well; however, the global playback volume slider no longer does that (see #1866).

**Comment by werame** [comment]
> when Audacity's global playback volume slider changed the system volume

That was honestly pretty annoying behavior. And was also inconsistent. It worked with MME (IIRC) but not with WASAPI nor with DirectSound, and probably not with ASIO either.

**Comment by rbdannenberg** [comment]
MIDI has a volume pedal control. If you wanted to send volume changes in response to the Audacity main volume, you could do it, but it would fight with volume control changes in MIDI tracks themselves. The idea of a remote master volume is not supported in MIDI, and while you could make up conventions for how people should use synthesizers, it seems like a bad idea for a general tool like Audacity.

**Comment by Pokechu22** [comment]
Note that audacity already has a velocity slider for note tracks, which is used to modify existing volume changes in the track during playback.  The global volume control could be changed to apply to that as well, but then you have to do with differing units (and differences in velocity not necessarily resulting in linear (or, I guess, logarithmic) scaling with decibels).

**Comment by werame** [comment]
@rbdannenberg This is about Windows. In MS's vision (since Win 7) apps have separate "wet" volumes, later mixed by the system. So the MIDI GS having its own volume API on Windows isn't surprising.

**Comment by rbdannenberg** [comment]
But MIDI is not a Windows app and may not be synthesized by any Windows app, and I don't think there's a general way to get from MIDI port selection to the application who's volume control will affect that MIDI port's playback volume. Even if I always used a software synthesizer, I wouldn't expect or want Audacity to be adjusting its volume.

**Comment by werame** [comment]
Yeah, it will be much more of challenge to implement volume control over an arbitrary synth, especially on Linux and [OS X](https://apple.stackexchange.com/questions/10902/application-level-volume-control-in-os-x).
