### ISSUE TITLE
Mac builds are failing on master

### ISSUE THREAD

**Issue by werame** [audacity/audacity#2469]
**Describe the bug**
In case nobody noticed.

https://github.com/audacity/audacity/runs/4909375703?check_suite_focus=true

It doesn't seem temporary as it happened on my own fetch of the post-XLisp-fixes master.

https://github.com/werame/audacity/runs/4920143257?check_suite_focus=true

First Mac build failure seems to have been this:

https://github.com/audacity/audacity/runs/4909457248?check_suite_focus=true

Some kind of github snafu I suspect though since

https://github.com/audacity/audacity/actions/runs/1724422830

worked. But then

https://github.com/audacity/audacity/actions/runs/1734218822

failed. Although they seem to be same files?! And then the merge also built ok

https://github.com/audacity/audacity/actions/runs/1734834639

I guess GH problem then.

**Comment by werame** [comment]
My own build with a PR/patch worked a bit later based on the same master

https://github.com/werame/audacity/actions/runs/1739847676

So definitely was GH problem then.

**Comment by crsib** [comment]
Well, actually this is a CPack issue. I think it's fixed in a branch I'm currently working on.

**Comment by werame** [comment]
@crsib Should I reopen it then, so it can be more properly closed when you merge your fix/branch?

**Comment by crsib** [comment]
Makes sense
