### ISSUE TITLE
New track control panel button: effects

### ISSUE THREAD

**Issue by AnitaBats** [audacity/audacity#2474]
@Higherself1133 please add details to this task.

**Comment by Higherself1133** [comment]
<img width="322" alt="Screen Shot 2022-01-26 at 10 20 44 AM" src="https://user-images.githubusercontent.com/97682925/151136488-4ea7ee02-7756-475a-b701-2e32bc47e13e.png">
<img width="443" alt="Screen Shot 2022-01-26 at 10 20 59 AM" src="https://user-images.githubusercontent.com/97682925/151136495-5a5fb6c7-623b-4cfd-8105-f36da502e70a.png">

Figma Link: https://www.figma.com/file/odPgVM0lWc6MdsJWxpgPJl/Audacity?node-id=5822%3A58269

**Comment by DavidBailes** [comment]
Please could these figma diagrams also always include a specification for how keyboard users can execute a task - not just a specification for mouse users.
