### ISSUE TITLE
Add sidebar and make sure it shows and hides: effects

### ISSUE THREAD

**Issue by AnitaBats** [audacity/audacity#2475]
@Higherself1133 could you please populate the description?

**Comment by thirdxlabs** [comment]
Here's the structure for the Realtime Effects panel. When there are no effects added, + graphic and onboarding text would be there. The onboarding graphic would be updated soon (some UI polishing work needs to be there)

Panel opens upon clicking the button "Add Effects" on the audio track. User can close the panel by clicking the x button on top right.


<img width="853" alt="Screen Shot 2022-01-28 at 2 10 45 PM" src="https://user-images.githubusercontent.com/72258608/151552558-72535795-c5e5-469e-bc0d-82146262ccef.png">

For now, the proposal is to use the key 'E' to open and close the realtime effects panel.

**Comment by Higherself1133** [comment]
Here's the structure for the Realtime Effects panel. When there are no effects added, + graphic and onboarding text would be there. The onboarding graphic would be updated soon (some UI polishing work needs to be there).

<img width="734" alt="Screen Shot 2022-01-28 at 2 03 23 PM" src="https://user-images.githubusercontent.com/97682925/151552975-dda9eb66-9154-40e1-88cc-81a11329e37d.png">


Panel opens upon clicking the button "Add Effects" on the audio track. User can close the panel by clicking the x button on top right.

<img width="853" alt="Screen Shot 2022-01-28 at 2 10 45 PM" src="https://user-images.githubusercontent.com/97682925/151553020-3acbb076-ff75-4055-8ade-6ceb95eed934.png">


For now, the proposal is to use the Keyboard shortcut 'E' to open and close the realtime effects panel.
