### ISSUE TITLE
Some effects delete hidden part of clips

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2479]
**Describe the bug**
Graphic EQ and Filter Curve EQ delete the hidden part of smart clips

**To Reproduce**
1. Generate a Chirp
2. Shrink the clip by dragging the left edge a bit to the right, and the right edge a bit to the left.
3. Select the clip
4. Apply one of the EQ effects
5. Observe that the clip cannot be restored to its original length - the hidden parts appear to have gone.

**Expected behavior**
The hidden parts of the clip to be unaffected by effects.

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04, macOS, Windows
 - Version: 3.3.2

**Comment by LWinterberg** [comment]
Related: 
* #1902

**Comment by Penikov** [comment]
I thought this bug is a regression, but it was introduced with clips. 
EQ is definitely a non-destructive effect.

**Comment by dozzzzer** [comment]
The ticket is a special case of #1902 . Closing in favor of #1902
