### ISSUE TITLE
Metadata Editor may have a minimum height greater than the display height

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2482]
**Describe the bug**
The Metadata Editor appears to have a minimum height set on open to fit the contents. If there is a lot of metadata, this may be greater than the display height

**To Reproduce**
1. Open the metadata editor
2. Add 20+ custom tags
3. Click the "Set Default" button
4. Close and relaunch Audacity
5. Open the Metadata Editor
6. Observe that the minimum height is very large.

**Expected behavior**
The Metadata Editor to always have a minimum height <= about 600 px so that the buttons at the bottom are always available.

**Screenshots**
![Screenshot_2022-01-26_16-05-48](https://user-images.githubusercontent.com/11681097/151200247-16116535-03c0-4630-a95c-0ba7ac3796ae.png)

**Additional information (please complete the following information):**
 - OS: Reported on Windows 10, confirmed on Xubumtu 20.04
 - Version: Audacity 3.x
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]

**Additional context**

**Comment by Penikov** [comment]
Tested on Ubuntu 20.04
Looks good even at a low resolution like 1024x768

![image](https://user-images.githubusercontent.com/25851359/151335372-58ad6291-abcd-41bc-bda9-b0ab91007754.png)

**Comment by petersampsonaudacity** [comment]
I tested this on W10 with latest master build audacity-win-3.2.0-alpha-20220127+4a69e09-x64-msvc2019
Which is the build that allegedly fixes this issue

I added 47 extra tags A-Z and 1-21

a) Observe: by default the bottom row of buttons (and the bottom right resizer are not visible

b) dragging the Metadata dialog as far up the screen as possible (use the header at the top of dialog)
Observe@ this reveals the second row of buttons but fails to show the triangle resizer


![image](https://user-images.githubusercontent.com/50205984/151546654-2398d85b-d9ab-49ad-8643-0cd2bfe0d9a4.png)

![image](https://user-images.githubusercontent.com/50205984/151547578-b242ca3d-5d38-4999-a975-d71a19862617.png)

@Penikov Pavel I therefore think this issue need to be reopened

**Comment by SteveDaulton** [comment]
> a) Observe: by default the bottom row of buttons (and the bottom right resizer are not visible

The fix is based on the original design of showing as much data as possible.


> b) dragging the Metadata dialog as far up the screen as possible (use the header at the top of dialog)
> Observe: this reveals the second row of buttons but fails to show the triangle resizer

but can you resize the window by dragging the top downwards?
The problem (bug) was that it was impossible to resize the window smaller (vertically) than the number of rows that populated the window when it was opened. This should now be fixed - that's all that the fix does.

If the window can be resized so that it fits on screen, then the bug as stated is fixed.
If you want additional improvements, then that's a new feature request / enhancement.
(Personally I'm not concerned about residual enhancement issues, as it is such a rare problem.)

**Comment by petersampsonaudacity** [comment]
Yes, I can resize by first dragging downwards and then upwards - like this
![image](https://user-images.githubusercontent.com/50205984/151565334-8f749bc6-e558-4644-a4a4-123c0ea9251d.png)


But It really would be **_much_** better if the whole dialog, all controls, always initially fitted on the screen.

**Comment by SteveDaulton** [comment]
> But It really would be **_much_** better if the whole dialog, all controls, always initially fitted on the screen.

To be honest, over the last 15 years I've only ever seen one real-life case where that didn't happen.

**Comment by petersampsonaudacity** [comment]
> If the window can be resized so that it fits on screen, then the bug as stated is fixed.

Actually retesting with latest 3,2,0 on W10 I find I sometime/often cannot drag-down to reduce the dialog window size - in those cases the window stays the same size with even more of it shunted off-screen - so this is a bit moonphasey ...
