### ISSUE TITLE
Master build crashes at startup

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2483]
**Describe the bug**

One of the recent PRs brokes down master branch so Audacity crashes at startup

**To Reproduce**

1. Download the latest master build
2. Run Audacity

**Additional information (please complete the following information):**
 - OS: Windows 10

`>	
        lib-transactions.dll!TransactionScope::Commit() Line 58	C++
 	Audacity.exe!UndoManager::RemoveStates(unsigned __int64 begin, unsigned __int64 end) Line 239	C++
 	Audacity.exe!UndoManager::ClearStates() Line 252	C++
 	Audacity.exe!ProjectHistory::InitialState() Line 52	C++
 	Audacity.exe!ProjectManager::New() Line 389	C++
 	Audacity.exe!AudacityApp::InitPart2() Line 1548	C++
 	Audacity.exe!AudacityApp::OnInit() Line 1384	C++
 	wxbase313ud_vc_x64_custom.dll!wxAppConsoleBase::CallOnInit() Line 93	C++
 	wxbase313ud_vc_x64_custom.dll!wxEntryReal(int & argc, wchar_t * * argv) Line 491	C++
 	wxbase313ud_vc_x64_custom.dll!wxEntry(int & argc, wchar_t * * argv) Line 184	C++
 	wxmsw313ud_core_vc_x64_custom.dll!wxEntry(HINSTANCE__ * hInstance, HINSTANCE__ * __formal, char * __formal, int nCmdShow) Line 306	C++
 	Audacity.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * __formal, int nCmdShow) Line 799	C++`

**Comment by werame** [comment]
Probably one of the last 15 commits or so. It worked a couple of days ago.

**Comment by crsib** [comment]
I've checked the builds from your branch and observed no issue
