### ISSUE TITLE
VST3. Audacity does not see .vst3 in the home directory

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2487]
**Describe the bug**
According to VST3 spec, there are three directories for vst3 plugins. 
One of them is ~/.vst3
For some reason, audacity can't see installed plugins in  ~/.vst3

**To Reproduce**
1. Install VST3 plugin in ~/.vst3 directory
2. Launch Audacity
3. Open Plug-ins manager 
4. look for .vst3 plugins in the 'New' section

 - OS: all Linux disrtos

**Comment by crsib** [comment]
I've checked - the flow works as expected. What is important is that VST3 can be packaged as a directory and the whole directory should be copied into `.vst3`
