### ISSUE TITLE
Does not load FFmpeg's libavformat.so.58.76.100

### ISSUE THREAD

**Issue by lfam** [audacity/audacity#2489]
**Describe the bug**
I am using Audacity 3.1.3 as [packaged](https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/audio.scm?id=f870977e6ac5a37f1e42af7e97c78c1e28dadfc8#n724) by GNU Guix (this is Linux), and I am having trouble using FFmpeg. I am trying with FFmpeg 4.4.1. But, I cannot make it work.

I know that Audacity stopped linking to FFmpeg in recent releases, so I am attempting to load it.

I go through the menus `Edit -> Preferences -> Libraries -> Locate...`, browse to the correct location, and select the correct path, `/gnu/store/31fag7lys7fa4rxb0cbmdc43qh26lnsh-ffmpeg-4.4.1/lib/libavformat.so.58.76.100`. This is the location of the library on Guix.

However, Audacity still does not make use of it, and when I return to the `Libraries` menu, it says `FFmpeg Library Version: FFmpeg library not found`. Also, I check `audacity.cfg`, and it shows that the library's location was not registered:

```
[FFmpeg]
Enabled=0
FFmpegLibPath=
```

I can manually edit `audacity.cfg` to contain these lines:

```
[FFmpeg]
Enabled=1
FFmpegLibPath=/gnu/store/31fag7lys7fa4rxb0cbmdc43qh26lnsh-ffmpeg-4.4.1/lib/libavformat.so.58.76.100
```
But, when starting Audacity, it shows me the dialog `FFmpeg was configured in Preferences and successfully loaded before, but this time Audacity failed to load it at startup.`

For that case, I launched Audacity in strace and noticed that it does successfully stat `libavformat.so`:

```
[pid 51608] newfstatat(AT_FDCWD, "/gnu/store/31fag7lys7fa4rxb0cbmdc43qh26lnsh-ffmpeg-4.4.1/lib/libavformat.so.58.76.100", {st_mode=S_IFREG|0555, st_size=2527096, ...}, 0) = 0
[pid 51608] openat(AT_FDCWD, "/gnu/store/ny3b7qlnkhxaxvswsnnvddp2y45irfi5-audacity-3.1.3/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 16
[pid 51608] newfstatat(16, "", {st_mode=S_IFREG|0444, st_size=43264, ...}, AT_EMPTY_PATH) = 0
[pid 51608] mmap(NULL, 43264, PROT_READ, MAP_PRIVATE, 16, 0) = 0x7f20c4100000
[pid 51608] close(16)                   = 0   
[pid 51608] openat(AT_FDCWD, "/gnu/store/xvg1ziqdx7gl72hcgnlxzawzqhb91z2c-wxwidgets-3.1.5/lib/glibc-hwcaps/x86-64-v3/libavformat.so.58", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 51608] newfstatat(AT_FDCWD, "/gnu/store/xvg1ziqdx7gl72hcgnlxzawzqhb91z2c-wxwidgets-3.1.5/lib/glibc-hwcaps/x86-64-v3", 0x7ffc77e41940, 0) = -1 ENOENT (No such file or directory)
[pid 51608] openat(AT_FDCWD, "/gnu/store/xvg1ziqdx7gl72hcgnlxzawzqhb91z2c-wxwidgets-3.1.5/lib/glibc-hwcaps/x86-64-v2/libavformat.so.58", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 51608] newfstatat(AT_FDCWD, "/gnu/store/xvg1ziqdx7gl72hcgnlxzawzqhb91z2c-wxwidgets-3.1.5/lib/glibc-hwcaps/x86-64-v2", 0x7ffc77e41940, 0) = -1 ENOENT (No such file or directory)
[pid 51608] openat(AT_FDCWD, "/gnu/store/xvg1ziqdx7gl72hcgnlxzawzqhb91z2c-wxwidgets-3.1.5/lib/tls/haswell/x86_64/libavformat.so.58", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)[pid 51608] newfstatat(AT_FDCWD, "/gnu/store/xvg1ziqdx7gl72hcgnlxzawzqhb91z2c-wxwidgets-3.1.5/lib/tls/haswell/x86_64", 0x7ffc77e41940, 0) = -1 ENOENT (No such file or directory)
[... many more attemps to find libavformat.so where it does not exist ...]
```

Can you offer any advice? Is there anything I can do to assist with debugging?

**Comment by LWinterberg** [comment]
can you try again with the current alpha? https://audacityteam.org/nightly

**Comment by LWinterberg** [comment]
https://issues.guix.gnu.org/53591

this has been fixed by the guix maintainers
