### ISSUE TITLE
Audacity crashes on opening after building from source

### ISSUE THREAD

**Issue by dlh-0492** [audacity/audacity#2490]
Whenever I'm trying to build Audacity 3.1.3, I get this error:
`CMake Error at cmake-proxies/cmake-modules/AudacityFunctions.cmake:140 (message):
  Invalid value "local" for option audacity_use_zlib.  Valid values are:
  system
Call Stack (most recent call first):
  cmake-proxies/cmake-modules/AudacityDependencies.cmake:183 (cmd_option)
  cmake-proxies/CMakeLists.txt:1 (add_conan_lib)
`
This is without any modifications to any of the build files whatsoever.

**Comment by crsib** [comment]
Please try with a clean build directory

**Comment by dlh-0492** [comment]
I've been trying that, and now all I get are a bunch of "no package found" errors

**Comment by crsib** [comment]
Unfortunately CMake*.log are useless in most of the cases. Can you please share the actual CMake output? And the command line you are using.

**Comment by dlh-0492** [comment]
So I tried it again and this is where the errors start:

`-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: checking conan executable
-- Conan: Found program /usr/local/bin/conan
-- Conan: Version found Conan version 1.44.1
Found gcc 9
gcc>=5, using the major as version

************************* WARNING: GCC OLD ABI COMPATIBILITY ***********************
 
Conan detected a GCC version > 5 but has adjusted the 'compiler.libcxx' setting to
'libstdc++' for backwards compatibility.
Your compiler is likely using the new CXX11 ABI by default (libstdc++11).

If you want Conan to use the new ABI for the audacity_build profile, run:

    $ conan profile update settings.compiler.libcxx=libstdc++11 audacity_build

Or edit '/home/awmr/.conan/profiles/audacity_build' and set compiler.libcxx=libstdc++11

************************************************************************************



Profile created with detected settings: /home/awmr/.conan/profiles/audacity_build
-- Conan: Adding audacity remote repository (https://artifactory.audacityteam.org/artifactory/api/conan/audacity-binaries) verify ssl (True)
-- Conan: Adding conan-center-cache remote repository (https://artifactory.audacityteam.org/artifactory/api/conan/conancenter) verify ssl (True)
-- The ASM_NASM compiler identification is unknown
-- Didn't find assembler
-- Build Info:
--   Host System: Linux-5.4.0-96-generic
--   Host System Name: Linux
--   Host System Processor: x86_64
--   Host System Version: 5.4.0-96-generic
--   Host System Architecture: 64-bit
-- 
--   Compiler: /usr/bin/c++
--   Compiler Version: 9.3.0
--   Compiler Standard: 17
--   Compiler Standard Required: ON
--   Compiler Extensions: 
-- 
--   Current Commit: 4a69e09dc
-- 
-- Looking for pow in m
-- Looking for pow in m - found
-- Looking for __atomic_fetch_add_4 in atomic
-- Looking for __atomic_fetch_add_4 in atomic - found
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Performing Test HAVE_MMX
-- Performing Test HAVE_MMX - Success
-- Performing Test HAVE_SSE
-- Performing Test HAVE_SSE - Success
-- Performing Test HAVE_SSE2
-- Performing Test HAVE_SSE2 - Success
-- Looking for 4 include files float.h, ..., string.h
-- Looking for 4 include files float.h, ..., string.h - found
-- Looking for assert.h
-- Looking for assert.h - found
-- Looking for fenv.h
-- Looking for fenv.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for malloc.h
-- Looking for malloc.h - found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for fileno
-- Looking for fileno - found
-- Looking for flock
-- Looking for flock - found
-- Looking for gmtime
-- Looking for gmtime - found
-- Looking for gmtime_r
-- Looking for gmtime_r - found
-- Looking for lrint
-- Looking for lrint - found
-- Looking for lrintf
-- Looking for lrintf - found
-- Looking for lstat
-- Looking for lstat - found
-- Looking for mlock
-- Looking for mlock - found
-- Looking for posix_fadvise
-- Looking for posix_fadvise - found
-- Looking for posix_memalign
-- Looking for posix_memalign - found
-- Check size of short
-- Check size of short - done
-- Check size of int
-- Check size of int - done
-- Check size of long
-- Check size of long - done
-- Check size of float
-- Check size of float - done
-- Found Python3: /usr/bin/python3.8 (found version "3.8.10") found components: Interpreter 
-- Adding Conan dependency ZLIB
-- Adding Conan dependency expat
-- Adding Conan dependency wxWidgets
-- Adding Conan dependency libmp3lame
-- Adding Conan dependency libid3tag
-- Adding Conan dependency libmad
-- Adding Conan dependency Ogg
-- Adding Conan dependency FLAC
-- Adding Conan dependency Opus
-- Adding Conan dependency Vorbis
-- Adding Conan dependency SndFile
-- Adding Conan dependency PortAudio
-- Adding Conan dependency libuuid
-- Adding Conan dependency PortMidi
-- ========== Configuring sqlite ==========
-- Using 'sqlite' local library
-- ========== Configuring vamp ==========
-- Using 'vamp' local library
-- ========== Configuring lv2 ==========
-- Using 'lv2' local library
-- Checking for module 'x11'
--   Found x11, version 1.6.9
-- Checking for module 'gtk+-2.0'
--   Found gtk+-2.0, version 2.24.32
-- Checking for module 'gtk+-3.0'
--   No package 'gtk+-3.0' found
-- Checking for module 'gtk+-x11-2.0'
--   Found gtk+-x11-2.0, version 2.24.32
-- Checking for module 'gtk+-x11-3.0'
--   No package 'gtk+-x11-3.0' found
-- Checking for module 'QtGui >= 4.4.0'
--   No package 'QtGui' found
-- Checking for module 'Qt5Widgets >= 5.1.0'
--   No package 'Qt5Widgets' found
-- ========== Configuring portsmf ==========
-- Using 'portsmf' local library
-- ========== Configuring sbsms ==========
-- Using 'sbsms' local library
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- ========== Configuring soundtouch ==========
-- Using 'soundtouch' local library
-- ========== Configuring twolame ==========
-- Using 'twolame' local library
-- Executing Conan:             REQUIRES zlib/1.2.11;expat/2.2.9@audacity/stable;wxwidgets/3.1.3.2-audacity;libmp3lame/3.100;libid3tag/0.15.2b@audacity/stable;libmad/0.15.2b-1@;ogg/1.3.4;flac/1.3.3;opus/1.3.1;vorbis/1.3.7;libsndfile/1.0.31;portaudio/19.7.0;libuuid/1.0.3;portmidi/r234
            GENERATORS cmake_find_package_multi
            BUILD_REQUIRES 
            
            OPTIONS zlib:shared=True;expat:shared=True;wxwidgets:shared=True;wxwidgets:zlib=zlib;wxwidgets:expat=expat;wxwidgets:compatibility=3.0;wxwidgets:png=libpng;wxwidgets:jpeg=libjpeg-turbo;wxwidgets:tiff=off;wxwidgets:secretstore=False;wxwidgets:opengl=False;wxwidgets:propgrid=False;wxwidgets:ribbon=False;wxwidgets:richtext=False;wxwidgets:stc=False;wxwidgets:webview=False;wxwidgets:help=False;wxwidgets:html_help=False;wxwidgets:fs_inet=False;wxwidgets:protocol=False;libjpeg-turbo:SIMD=False;libid3tag:zlib=conan;ogg:shared=True;flac:shared=True;opus:shared=True;vorbis:shared=True;libsndfile:shared=True;portaudio:shared=True;portaudio:with_wdmks=False;portmidi:shared=True
        
-- Configuring packages for Release
-- Conan: checking conan executable
-- Conan: Found program /usr/local/bin/conan
-- Conan: Version found Conan version 1.44.1
-- Conan executing: /usr/local/bin/conan install . --build missing --profile:build audacity_build --settings:host build_type=Release --settings:host compiler=gcc --settings:host compiler.version=9 --settings:host compiler.libcxx=libstdc++11 --settings:host compiler.cppstd=17
Configuration (profile_host):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=17
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

conanfile.txt: Installing package
Requirements
    expat/2.2.9@audacity/stable from 'audacity' - Cache
    flac/1.3.3 from 'conancenter' - Cache
    libid3tag/0.15.2b@audacity/stable from 'audacity' - Cache
    libjpeg-turbo/2.0.5 from 'conancenter' - Cache
    libmad/0.15.2b-1 from 'audacity' - Cache
    libmp3lame/3.100 from 'conancenter' - Cache
    libpng/1.6.37 from 'conancenter' - Cache
    libsndfile/1.0.31 from 'conancenter' - Cache
    libuuid/1.0.3 from 'conancenter' - Cache
    ogg/1.3.4 from 'conancenter' - Cache
    opus/1.3.1 from 'conancenter' - Cache
    portaudio/19.7.0 from 'audacity' - Cache
    portmidi/r234 from 'audacity' - Cache
    vorbis/1.3.7 from 'conancenter' - Cache
    wxwidgets/3.1.3.2-audacity from 'audacity' - Cache
    zlib/1.2.11 from 'conancenter' - Cache
Packages
    expat/2.2.9@audacity/stable:2af715f34a7c8c2aeae57b25be0a52c4110dc502 - Cache
    flac/1.3.3:21e4edd0abae17cbf23735110c3ebfb23cb32003 - Build
    libid3tag/0.15.2b@audacity/stable:3dee800c280dacfcf6071938b45825abeb550a03 - Build
    libjpeg-turbo/2.0.5:800091a8f8a4dca1d0ba7ea17b02314c9bf7993b - Cache
    libmad/0.15.2b-1:636c64d2b7eed69efb2896f23b8aca5b02784897 - Cache
    libmp3lame/3.100:6af9cc7cb931c5ad942174fd7838eb655717c709 - Build
    libpng/1.6.37:7929d8ecf29c60d74fd3c1f6cb78bbb3cb49c0c7 - Build
    libsndfile/1.0.31:efaf8344e73439c3688a50732878421f350352fb - Build
    libuuid/1.0.3:6af9cc7cb931c5ad942174fd7838eb655717c709 - Build
    ogg/1.3.4:2af715f34a7c8c2aeae57b25be0a52c4110dc502 - Build
    opus/1.3.1:2af715f34a7c8c2aeae57b25be0a52c4110dc502 - Build
    portaudio/19.7.0:30f2c4b730408f1b530f1d56c0414873be0ed3c4 - Build
    portmidi/r234:43210353fd7084c5b95e27c1675921b6024a3e6d - Build
    vorbis/1.3.7:470776a885bfe99cc02deb0b0e8b7a512e39e8cb - Build
    wxwidgets/3.1.3.2-audacity:46e8c46ff3b55839a6f39a08b398397312d621a6 - Build
    zlib/1.2.11:2af715f34a7c8c2aeae57b25be0a52c4110dc502 - Build
Build requirements
    autoconf/2.71 from 'audacity' - Cache
    automake/1.16.4 from 'audacity' - Cache
    gnu-config/cci.20201022 from 'audacity' - Cache
    libtool/2.4.6 from 'audacity' - Cache
    m4/1.4.19 from 'audacity' - Cache
    nasm/2.15.05 from 'audacity' - Cache
    ninja/1.10.1 from 'conancenter' - Cache
Build requirements packages
    autoconf/2.71:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    automake/1.16.4:258f6f05ca54813b3d7180161753df7f9ccf7e1d - Cache
    gnu-config/cci.20201022:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    libtool/2.4.6:445047bf696d55be0de53e5d97c24a63a4218039 - Cache
    m4/1.4.19:24647d9fe8ec489125dfbae4b3ebefaf7581674c - Cache
    nasm/2.15.05:24647d9fe8ec489125dfbae4b3ebefaf7581674c - Cache
    ninja/1.10.1:24647d9fe8ec489125dfbae4b3ebefaf7581674c - Cache

Installing (downloading, building) binaries...
expat/2.2.9@audacity/stable: Already installed!
gnu-config/cci.20201022: Already installed!
gnu-config/cci.20201022: Appending PATH environment variable: /home/awmr/.conan/data/gnu-config/cci.20201022/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin
libjpeg-turbo/2.0.5: Already installed!
libmad/0.15.2b-1: Already installed!
m4/1.4.19: Already installed!
m4/1.4.19: Appending PATH environment variable: /home/awmr/.conan/data/m4/1.4.19/_/_/package/24647d9fe8ec489125dfbae4b3ebefaf7581674c/bin
m4/1.4.19: Setting M4 environment variable: /home/awmr/.conan/data/m4/1.4.19/_/_/package/24647d9fe8ec489125dfbae4b3ebefaf7581674c/bin/m4
nasm/2.15.05: Already installed!
nasm/2.15.05: Appending PATH environment variable: /home/awmr/.conan/data/nasm/2.15.05/_/_/package/24647d9fe8ec489125dfbae4b3ebefaf7581674c/bin
ninja/1.10.1: Already installed!
WARN: wxwidgets/3.1.3.2-audacity: requirement expat/2.2.9 overridden by your conanfile to expat/2.2.9@audacity/stable 
ogg/1.3.4: WARN: Package binary is corrupted, removing: 2af715f34a7c8c2aeae57b25be0a52c4110dc502
ogg/1.3.4: WARN: Build folder is dirty, removing it: /home/awmr/.conan/data/ogg/1.3.4/_/_/build/2af715f34a7c8c2aeae57b25be0a52c4110dc502
ERROR: 404: Not Found. [Remote: conancenter]
The 'ogg/1.3.4' package has 'exports_sources' but sources not found in local cache.
Probably it was installed from a remote that is no longer available.

CMake Error at cmake-proxies/cmake-modules/conan.cmake:638 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake-proxies/cmake-modules/AudacityDependencies.cmake:306 (conan_cmake_install)
  cmake-proxies/cmake-modules/AudacityDependencies.cmake:330 (_conan_install)
  CMakeLists.txt:573 (resolve_conan_dependencies)
`

**Comment by crsib** [comment]
Judging by the output - you are building from the master, not the releases 3.1.3. Running `conan remove "*" --force` will most likely help you.

**Comment by dlh-0492** [comment]
So yeah, I did that and the build appeared successful. Now Audacity crashes whenever I try to open it.

**Comment by LWinterberg** [comment]
Was the crash on open #2483? Ie, is it fixed if you try current master?

**Comment by crsib** [comment]
I would be surprised, as that fix was very MSVC specific :)

**Comment by LWinterberg** [comment]
building from source works just fine for me, no update from OP
