### ISSUE TITLE
3.2.0 alpha mac universal build opens in German on my Mac

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2493]
**Describe the bug**
3.2.0 alpha mac universal build opens in German on my Mac

**To Reproduce**
1. Install mac universal  audacity-macOS-3.2.0-alpha-20220127+4a69e09-universal 
2. clear the audacity settings folder to OOTB factory settings
3. launch 3.1.3
4. Observe: Audacity is in English
5. Quit Audacity
6. launch 3.2.0  -  audacity-macOS-3.2.0-alpha-20220127+4a69e09-universal 
7. Observe: Audacity is in German
8. Audacity > Einstellungen > Oberfläche
9. Observe:  Sprache: states "System"

**Expected behavior**
Audacity to open in may native locale for the Mac which is English

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS: macOS 12.1 Monterey
 - Version:  audacity-macOS-3.2.0-alpha-20220127+4a69e09-universal 

**Additional context**
_I am currently trying to learn German with Duolingo - but the technical terms in Audacity auf Deutsch are a bit of a fast-track for me_  ;-)

**Comment by crsib** [comment]
Is there a chance that you have per-app setting in macOS somehow (System Preferences -> Language & Regions -> Apps)?

**Comment by crsib** [comment]
(And that setting, well, sticks. I removed it weeks ago and Russian is still returned as a system language)

**Comment by petersampsonaudacity** [comment]
> Is there a chance that you have per-app setting in macOS somehow (System Preferences -> Language & Regions -> Apps)?

I don't think so - because if I run 3.1.3 (or earlier) after the German 3.2.0 3.1.3 spins up properly in English.

**Comment by petersampsonaudacity** [comment]
> Is there a chance that you have per-app setting in macOS somehow (System Preferences -> Language & Regions -> Apps)?

Under Language & Regions -> General it shows Region: United Kingdom
and Preferred languages:  English - English (UK)- Primary

Language & Regions -> Apps  -  I have no language settings, all fields are blank

**Comment by Penikov** [comment]
These are Language and Region preferences on my macOS 12.01, but the universal build demonstrates Russian localization instead of English

<img width="972" alt="Screenshot 2022-01-28 at 21 43 21" src="https://user-images.githubusercontent.com/25851359/151596873-41bd65e4-0eda-400d-90f3-8296ef4be5b2.png">



And this is what x64 build shows
<img width="1048" alt="Screenshot 2022-01-28 at 21 33 19" src="https://user-images.githubusercontent.com/25851359/151597079-59c36aae-a464-48b6-86a0-3a4f0a0e867e.png">

**Comment by crsib** [comment]
Sounds like ... macOS

**Comment by petersampsonaudacity** [comment]
Testing on macOS 12.2 Monterey,   with the Intel Mac build  audacity-macOS-3.2.0-alpha-20220127+4a69e09-x86_64 

This launched properly in English _(the universal build still opens auf Deutsch on 12..2)_

**Comment by david-macrae** [comment]
The same thing happened to me. M1 mac with Monterey 12.2. But only a few items were in German like the save dialog box and the rest in english. I have never had another language on my machine. It was in the universal build. So, I Installed the apple silicon only version and I works as expected. I have been testing it for a couple days and have not had any problems.

**Comment by petersampsonaudacity** [comment]
Testing for Issue #2504
 Mac: latest 3.2.0 alpha master builds crash on launch #2504 

This remains an issue for the universal Mac build, opening up auf Deutsch
audacity-macOS-3.2.0-alpha-20220203+4252745-universal

and remains OK properly in English for the Intel Mac build
audacity-macOS-3.2.0-alpha-20220203+4252745-x86_64

**Comment by petersampsonaudacity** [comment]
Testing on mac)S 12.1 Monterey with latest alpha master:   audacity-macOS-3.2.0-alpha-20220221+2ef7629-x86_64 

I confirm this is still the case

**Comment by crsib** [comment]
Fun observation - this problem occurs only in builds created by CI in the main repo :-)

In this case `wxLocale::GetSystemLanguage()` surprisingly returns a language, otherwise it returns unknown.

**Comment by petersampsonaudacity** [comment]
Testing on my Macbook Pro macOS 12.4 Monterey with latest universal Mac build:  audacity-macOS-3.2.0-alpha-20220711+468fad9-universal 

This now opens properly in English - the native locale

**Comment by david-macrae** [comment]
The latest [Audacity 3.2.0 Alpha 1](https://github.com/audacity/audacity/releases/tag/Audacity-3.2.0-alpha-1) posted to the releases page has the bug again where dialog box (like for open) are in german again

**Comment by david-macrae** [comment]
![Screen Shot 2022-08-31 at 11 25 22 PM](https://user-images.githubusercontent.com/2224292/187826055-657d6b8a-3a67-4cf0-937d-c218c1f759dc.jpg)

here is an image.
