### ISSUE TITLE
AppImage: Don't set environment variables in Exec

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#2498]
Reported on https://forum.audacityteam.org/viewtopic.php?f=48&t=123282 and https://github.com/TheAssassin/AppImageLauncher/issues/490

> `Exec=` settings in auto-generated desktop entry is incorrect.
> 
> Audacity's AppImage sets `Exec` to `env UBUNTU_MENUPROXY=0 audacity %F` in the desktop entry file. In AppImageLauncher's desktop entry, `Exec` becomes `/opt/AppImages/audacity-linux-3.1.3-x86_64_e2b11597c4ef63e68e102b057c5cd759.AppImage UBUNTU_MENUPROXY=0 audacity %F`, which actually passes `UBUNTU_MENUPROXY=0`, `audacity` and `%F` as file list to open to audacity, which does not make sense.
>

**Comment by LWinterberg** [comment]
The proper way apparently is: 

> The audacity team should not abuse `Exec` for setting env vars. They may use a shell script for their AppImage's `AppRun`.

**Comment by crsib** [comment]
Arch docs are on our side: https://wiki.archlinux.org/title/Desktop_entries

**Comment by crsib** [comment]
So really, this is a problem of AppImageLauncher, not Audacity

**Comment by imciner2** [comment]
Yea, I think AppImageLauncher is broken here, according to the FreeDesktop spec, the `exec` key should just be a command line with special field codes for replacement: https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s07.html. They seem to be making a lot of assumptions about portability of the exec line and decided to do a wholesale replacement of the first complete word in the desktop file.

**Comment by LWinterberg** [comment]
https://github.com/audacity/audacity/pull/3574 has provided a workaround
