### ISSUE TITLE
Default clip titles should not be named "Audio Track"

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#2499]
In the past (#1698) we made a clip name logic which takes the current track name and attaches numbers to it, which makes sense as far as the system goes, but ends up being confusing for users as now there are clips named track. With clips becoming a focus for 3.3, we'll need to revisit this at some point. 

Particularly, the following scenarios should be avoided: 
* The current behavior: A clip named `Audio Track #1`
* A double mention: `Audio Track Clip #1`
* Solutions which require regex parsing as we don't want to surface regex to translators (eg "regex-replace `Track` with `Clip`") - this had been a problem previously.

Discussion for potential solutions can happen here: 
* #1535

Related: 
* #1796

**Comment by petersampsonaudacity** [comment]
See this Forum post expressing user confusion over this:
Terminology: Tracks versus Clips
https://forum.audacityteam.org/viewtopic.php?f=46&t=123254&p=444871
