### ISSUE TITLE
Audio Marking with different key

### ISSUE THREAD

**Issue by djsg** [audacity/audacity#2505]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When doing recording, Ctrl+m key combination leaves a marking. I wonder whether it can be configured to be other key stroke like Insert or Home, etc. It's easier to press one key than 2 key combination.

**Describe alternatives you've considered**
A configuration page 

**Additional context**

**Comment by petersampsonaudacity** [comment]
You can customize most of the shortcuts - and that includes this one.

Please see:  https://manual.audacityteam.org/man/keyboard_preferences.html#custom

**Comment by djsg** [comment]
Thx for the tip. Didn't know that.
