### ISSUE TITLE
Playback. The playhead has stuck at the end of the selected region

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2508]
**Describe the bug**
![image](https://user-images.githubusercontent.com/25851359/152515968-ff979c1e-3eee-4333-b846-f597a54441a0.png)

**To Reproduce**
1. Generate 1-sec plug
2. Select a region from 0.1 to 0.25
3. Click the Playback button

The playback hasn't been ended. The playhead is stuck at the end of the selection.

**Additional information (please complete the following information):**
 - OS: Windows 10, macOS
 - Version: Audacity 3.2 alpha

Related to: #2448

**Comment by Penikov** [comment]
In some cases, this bug also could be reproduced without selection on a track. 
![image](https://user-images.githubusercontent.com/25851359/152517707-a718a9e2-3ceb-48f3-8285-830bffa60f82.png)

**Comment by petersampsonaudacity** [comment]
Testing on w10 with audacity-win-3.2.0-alpha-20220203+4252745-x64-msvc2022

this appears to be a regression on 3.1.3
