### ISSUE TITLE
Scrubbing and seeking. Pinned playhead not so pinned

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2512]
Originally, this issue seemed to me like a bug, but it turned out a feature. 
Anyway, it would be more convenient and clear to users if that feature will be less surprising without a careful reading of the manual. 

**Original description of the 'bug'**
According to the Audacity manual, Scrub & Seek feature has an alternate mode with a pinned playhead.

![image](https://user-images.githubusercontent.com/25851359/152530766-4d879b32-77f2-4617-83ff-15f85fff55a0.png)

Unfortunately, in 3.2 alpha (and earlier) it doesn't work as expected.

**To Reproduce**
1. Pin the playhead
2. Turn on Scrub scrub mode [Transport][Scrubbing][Scrub]
3. Move the cursor over tracks t
4. See the playhead is not pinned works as usual.

**Expected behavior**
https://manual.audacityteam.org/man/scrubbing_and_seeking.html#scrubbing

**Screenshots**

**Additional information (please complete the following information):**
 - OS: All
 - Version: Audacity 3.2 alpha

**Comment by petersampsonaudacity** [comment]
Testing on W10 shows that this is a regression on 2.2.2  -  bug introduced in 2.3.0, so this bug has been around since September 2018

**Comment by petersampsonaudacity** [comment]
Ahhhhh ....

But a careful read of the Manual says:
>**Pinned play head Scrubbing and Seeking**
>In order to achieve pinned play head scrubbing and seeking you will need to turn "off" the option for "Always scrub unpinned" in Playback preferences.

And this is set "on" by default
![image](https://user-images.githubusercontent.com/50205984/152556570-cec11363-39d2-4516-a9dc-c15a13ad7edc.png)


So this is **_not_** a bug - but is the behavior that @Paul-Licameli intended AFAICT

**Comment by petersampsonaudacity** [comment]
I have updated the 3.2.0 alpha Manual, upgrading that Note div to and Advice dive to give it more emphasis:
![image](https://user-images.githubusercontent.com/50205984/152558005-34a98d93-8b3f-4790-9c70-26bfb7766c47.png)

But for my money the default Off-ness of pinned playhead scrubbing is not very "discoverable" _(it certainly led @Penikov to quite reasonably add this as a "bug"._

**Comment by Penikov** [comment]
@petersampsonaudacity thanks for the clarification. Definitely, this is not a bug.

**Comment by petersampsonaudacity** [comment]
> thanks for the clarification. Definitely, this is not a bug.
I can't for the life of me right now remember why @Paul-Licameli  set it so that "Always scrub unpinned" is default = "on".

I would have thought that honoring the pinned head state by default would be the more logical and obvious choice.  

@Penikov you may want to check with Paul just why he set it that way ...

**Comment by LWinterberg** [comment]
we'll be replacing the current scrubbing behavior entirely and won't take action on this.
