### ISSUE TITLE
Transport toolbar. The play button a bit truncated in recording mode

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2519]
**Describe the bug**

**To Reproduce**
1. Launch Audacity
2. Open Preferences then click the OK button to refresh Audacity UI and avoid possible artefacts from previous versions.
3. Run recording
![image](https://user-images.githubusercontent.com/25851359/152742456-c1fdf74b-3b9c-490c-af3f-328a1d8eecab.png)

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Audacity 3.2

**Comment by petersampsonaudacity** [comment]
Testing on W10 

This also appears to be the case when Audaccity nis inactive, not recording.   

It appears to also affect the Play-at-Speed button too

This image is from 3.1.3 at 250% magnification - 3.2.0 layest alpha master shows the same:
![image](https://user-images.githubusercontent.com/50205984/152772453-53488cf6-eac2-4670-86d1-b29bccc87d0e.png)

Regression testing shows that this is a regression on 2.1.2, introduced in 2.2.0 when we changed the buttons from the old round shape to the new (and current) square-rounded-edge shape

**Comment by petersampsonaudacity** [comment]
In contrast here is 2.1.3 at 2.5 x mag:
![image](https://user-images.githubusercontent.com/50205984/152774434-9d8180fe-56e3-4ca0-87cf-be010f91384c.png)

**Comment by LWinterberg** [comment]
It's a regression on an 3.1.0-alpha; #1907 was fixed at some point

**Comment by petersampsonaudacity** [comment]
> It's a regression on an 3.1.0-alpha; #1907 was fixed at some point

I thought this truncated icon was ringing a bell in the back of my mind - and yes I now do remember this being spotted and fixed before.   ;-)

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest alpha master:  
audacity-win-3.2.0-alpha-20220708+5d10d6f-x64-msvc2022

@LWinterberg @dozzzzer  this appears to be fixed with the recent changes to the button icons:

![image](https://user-images.githubusercontent.com/50205984/178113530-a9cc26f3-53a9-4b46-bc3c-948db474f9cc.png)

When recording the Play button is now nicely grayed-out and appears to be no longer truncated at the bottom.

**Comment by LWinterberg** [comment]
hooray!
