### ISSUE TITLE
GUI. Audacity UI is blinking applying effects 

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2520]
**Describe the bug**
Audacity GUI has been 'blinking' at some actions by design. But since the latest updates were introduced in Mater, those 'blinks' have become quite visible on many effects and previews.

In some cases, that behaviour reveals not as Audacity disappearing but as focus changing. In this case, third-party windows or dialogues will be seen for a moment. 

**To Reproduce**
1. Generate a pluck for 1 sec
2. Open Change pitch effect
3. Click the Preview button
4. See how Audacity GUI has blinked for above a half-second.

**Additional information (please complete the following information):**
 - OS: Windows 1
 - Version: Audacity 3.2

**Comment by LWinterberg** [comment]
could not reproduce - any "blinking" would be caused by the preview progress bar getting focus
