### ISSUE TITLE
Labels. Ctrl+A shortcut at editing a label name leads to whole project selection

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2523]
**Describe the bug**
The basic behaviours for CTRL+A, CTRL+C, CTRL+V keystrokes in a label text field is broken.

**To Reproduce**
1. Add a label of any type
2. Give any name to a label
3. Put the cursor in the middle of the text field:
![image](https://user-images.githubusercontent.com/25851359/152784984-e92c6123-c3a4-4a5e-a3ee-36f4b04d7cbf.png)
4. Try to select a whole string with CTRL+ A keystroke

**Actual Behavior**
CTRL + A keystroke in the label text field made selected the whole project

![image](https://user-images.githubusercontent.com/25851359/152785318-02016644-ee55-4ae3-921d-f20d3ea70287.png)

**Expected behavior**
Instead of selecting a whole project, CTRl+A should select only a label string 
![image](https://user-images.githubusercontent.com/25851359/152785531-2c39adde-dfe0-4019-9304-4c3204cd85d2.png)

**Additional information (please complete the following information):**
 - OS: Windows 10 (but works fine with Audacity)
 - Version: Audacity 3.2
 
**Additional context**
Proposed behavior already implemented in clip hames.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest 3.2.0 alpha master

I cannot reproduce this, at step 4 I just get the whole string selected:
![image](https://user-images.githubusercontent.com/50205984/152791032-8f38b63a-cc61-4403-9fd8-8ca29f2167d0.png)

And Ctrl+C and Ctrl+V work fine when in label edit mode.

**Comment by Penikov** [comment]
On my machine, CTRL+A works fine only for the send tine. But at the first press of CTRL+A it selects a whole project.

So on my PC, it looks like:
1) Put the cursor into the label text
2) press CTRL+A
![image](https://user-images.githubusercontent.com/25851359/152796369-0cf4466a-8ea8-4013-973c-b56b25d78ed8.png)

3) press CTRL+A again:
![image](https://user-images.githubusercontent.com/25851359/152796407-8448af8d-bca6-4eb4-b637-480189bd49b9.png)

4) Press Backspace
![image](https://user-images.githubusercontent.com/25851359/152796565-ee3e1624-3a42-45a9-b558-c088e3edce40.png)


but the Delete key after step 3 will delete only text in a label string.

**Comment by dozzzzer** [comment]
The issue isn't the case anymore in version 3.3.2.
