### ISSUE TITLE
MIDI. MIDI clip couldn't be renamed

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2526]
**Describe the bug**
Despite the clip renaming feature has implemented for audio clips, MIDI 'clips' couldn't be renamed. 

**To Reproduce**
1. Import a MIDI file
2. Click on a MDI clip
3. Try to rename via double left-click or CTRL+F2
4. nothing happens

**Expected behavior**
The same as for audio clips

**Additional information (please complete the following information):**
 - OS: Win 10
 - Audacity 3.2

**Comment by LWinterberg** [comment]
Note tracks / MIDI don't have the concept of clips. What they display instead are the track name

**Comment by Penikov** [comment]
Yes, I know that in Audacity MIDI has been implemented differently. But from the UX point of view, imported MIDI looks as a clip.
Since it has such attributes as clip name (at least something similar to clip name) it would be nice to provide editing such attribute.

Anyway, this is definitely not a high priority Issue.
