### ISSUE TITLE
Overdubbing on Windows fails with WASAPI with default Recording device

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2530]
**Describe the bug**
Overdubbing on Windows fails with WASAPI host with default Recording device

**To Reproduce**
1. Clear Audacity settings folder (to ensure overdub is "on" and  Detect dropouts are both "on"
2.  Set host to WASAPI - leave Recording device as the default Mic
3.  Press Record and record a few seconds of audio
4. Observe: recording works fine
5. Press Stop
6. Press Shift+Record (to overdub record)
7. Observe: error message re. invalid sample rate (see Screenshot)

This does **_not_** fail if you set the recording device to be Loopback instead of the default mic.

This does **_not_** happen on W10 if the host is set to be either MME (default) or Windows DirectSound

**Expected behavior**
Since the first track records fine with WASAPI host (step 4)  I fully expect the overdub recording to work fine too (steps 6-7)

**Screenshots**
![image](https://user-images.githubusercontent.com/50205984/152988970-54aeaa56-c08e-44d7-9c23-c296f74261c7.png)

**Additional information (please complete the following information):**
 - OS: Windows 10  _(I will try to test later on Mac)_
 - Version: latest master alpha audacity-win-3.2.0-alpha-20220208+2f132fd-x64-msvc2022
 - Sound Device Windows WASAPI, onboard Realtek High Definition Audio(SST)  Sound card - default Mic input

**Additional context**
No problem on Mac.

This does not appear to be a regression this is the same all the way back to 2.1.0 where WASAPI with multiple input devices was added _(in late series 2.0.x WASAPI was first added but the only host available was loopback)_.

**Comment by petersampsonaudacity** [comment]
Curiously you get the same error message if you try to record with WASAPI as the host and default mic input device - with 
a)  overdub turned off and 
b) Software Playthrough turned on

**Comment by Penikov** [comment]
I tried to reproduce this bug recently. But overdub with Dropout detection works fine on my PC with WASAPI host in Audacity.
But I got the same error if one of the i/o devices has re-connected by Windows for some reason. In my case, this is a USB driver issue. 

Reloading Audacity or [Transport]-[Rescan Audio devices] always helps me 
![image](https://user-images.githubusercontent.com/25851359/153639370-249f8b0e-f8b7-4ad6-a89e-f2c757c4976d.png)

**Comment by LWinterberg** [comment]
Say @petersampsonaudacity does this also occur for you when recording in mono?

**Comment by petersampsonaudacity** [comment]
with mono set - at step 7 I get

![image](https://user-images.githubusercontent.com/50205984/178518114-c195d50d-0d58-4162-be10-b2d38bd7ac03.png)

**Comment by dozzzzer** [comment]
I'm still seeing this in the latest stable build

**Comment by dozzzzer** [comment]
Tested

**Comment by petersampsonaudacity** [comment]
Looks good to me testing on W10 with latest 3.4.0 master:  audacity-win-3.4.0-alpha-20231017+50de045-x64-msvc2022
