### ISSUE TITLE
Move rendering code away from WaveformView. WaveformView should only supply data to the renderer.

### ISSUE THREAD

**Issue by AnitaBats** [audacity/audacity#2531]
* Implement software waveform rendering. 
* Implement new cache for waveform imagery (reusable later by spectrum view)

**Comment by crsib** [comment]
Original case:
[rendering_test.zip](https://github.com/audacity/audacity/files/8033480/rendering_test.zip)

![image](https://user-images.githubusercontent.com/2660628/153221742-bdd63726-9df5-4cf4-b5c4-dbb8d8ba86d4.png)
