### ISSUE TITLE
Dropout detection warning only comes after recording has been stopped

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2533]
**Describe the bug**
Dropout setection warning only comes after recording has been stopped.

This means that the user only gets notification of possible dropouts when they have finished the recording (and it could be a long recording - and thus much wasted time).

**To Reproduce**
1. Record some audio with dropouts (see #2529 for one method of doing this)
2. Press Stop
3. Observe:  only once the recording has stopped do you get the dropout warning and the label track identifying dropouts

**Expected behavior**
Some method for warning the user dynamically during recording that they are experiencing dropouts.

**Screenshots**
![image](https://user-images.githubusercontent.com/50205984/153038596-2e0ca986-4ec4-436b-9e89-4dc10ea0a172.png)

**Additional information (please complete the following information):**
 - OS: Windows 10 - but assume all
 - Version: Audacity 3.1.3 and latest 3.2.0 alpha
 - 

**Additional context**
An earlier warning would enable the user to more quickly deal with dropout issues and avoid potentially long wasted recordings.

Flagging @Tantacrul as a UX issue.

**Comment by petersampsonaudacity** [comment]
A simple way of getting (faux, simulated) dropouts is

1. Run an alpha build
2. Tools > Simulate Recording errors _(only available in alpha test builds)_
3. Ensure Dropout detection is turned on in Recording prefs
4. Press Record and record for a few seconds
5.

**Comment by Penikov** [comment]
Makes sense
