### ISSUE TITLE
Audacity hangs on Stop when playing MIDI that has notes before T=0

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2539]
**Describe the bug**
If you have a MIDI track that has part of its Note track before zero, when yo stop playback Audacity hands for over half a minute (37 seconds on my W10 PC and my macOS 12.2 Monterey Mac.

This is a regression on 3.0.0 - introduced in 3.1.0 with the new Clip-handle drag-bars (affordances)

**To Reproduce**
1. Import a MIDI file
2. Use the Note track's drag-bar to position part of the Note track before zero
3. Press Play
4. Press Stop
5. Observe: audacity hangs
6. Observe: BOTH the Play and Stop buttons are shown as down
7. Observe: the playhead remains where playback was stopped
8. Observe: on W10 Blue -circle-of-death  -  on Mac spinning beachball-of-death
9. Wait 37 seconds (YMMV)
10. Observe:  It clears and all seems OK again

Note that this does not happen if you use an Audio track rather than a Note track

**Expected behavior**
Pressing Stop to stop playback immediately with the playhead restored to play start position and no Transport toolbar buttons down.

**Screenshots**
![image](https://user-images.githubusercontent.com/50205984/153216923-321c7cdf-79c1-4b82-9f65-ed44e0f64c6e.png)

**Additional information (please complete the following information):**
 - OS: Windows 10 and macOS 12.2 Monterey - so assume all OS
 - Version Audacity 3.1.0 onwards

**Additional context**
There is a possibility that this may be linked to this earlier reported issue
 MIDI playback starts from beginning regardless of cursor position #2359

**Comment by petersampsonaudacity** [comment]
Things get worse if at Step 4 instead of pressing Stop you re-press the Play button (which should reset the play position to the original location ans re-start playback from there) - but in this case Audacity just hangs interminably and must be force-quit.

**Comment by petersampsonaudacity** [comment]
This does not happen if at Step 2 you drag the Note track to the right or leave it starting at T=0

**Comment by petersampsonaudacity** [comment]
Further testing shows that the hang/pause at step 9 appears to be the time for the amount of the Note track that is hidden before T=0 in negative time.

**Comment by Penikov** [comment]
I think this bug could be related to #2448

**Comment by AnitaBats** [comment]
See PR: https://github.com/audacity/audacity/pull/2378
