### ISSUE TITLE
WaveTrack naming template

### ISSUE THREAD

**Issue by vsverchinsky** [audacity/audacity#2543]
The name of the WaveTrack should be generated according to this template:
`[DefaultTrackName] [N]`
Where `N` is minimum possible positive number so that name is unique.

Est.: ~2hrs

**Comment by petersampsonaudacity** [comment]
I've just been playing around with @vsverchinsky  Vitaly's branch build for Issue #2543 re track naming. 
audacity-win-3.2.0-alpha-20220215+2e0317d-x64-msvc2022  

One little residual I note is that if you:
a) don't have Track name overlays turned on, or
b) don't have enough of a clip showing to show the full clip name
then the nice new track name differentiation is lost.  
Less of a problem with the clip-name IRL - but the track name in the Track Control Panel remains an issue.

![image](https://user-images.githubusercontent.com/50205984/154237673-5917be74-de3e-48f8-b9b4-455e48514e1d.png)

A simple solution would be to change the track nomenclature to:
Audio 1
Audio 2
etc.

**Comment by vsverchinsky** [comment]
@petersampsonaudacity I've changed the default name to "Audio", now it should be fine, there was also changes that affects the text composed for screen readers - now the template is always "Track [N]: [track name]"

**Comment by petersampsonaudacity** [comment]
Hi @vsverchinsky  Vitaly, 

testing on W10 with your branch audacity-win-3.2.0-alpha-20220216+0beecb3-x64-msvc2022 
that looks good to me.  👍 

There is residual issue where Label tracks are always labelled Label Track.  Perhaps, for diferentiation, they should be labelled:
Labels 1
Labels 2
etc.

![image](https://user-images.githubusercontent.com/50205984/154472415-45a79eea-a5e2-499a-aeff-4c8e3f7c2834.png)

_Note that the label tracks do not have clip-handle drag-bars so the is no name display that way - only if you turn on "Show track name as overlay" in Tracks preferences._

**Comment by petersampsonaudacity** [comment]
**Time Track** is fine as it as - as there can only ever be one time track in a project.

**Comment by petersampsonaudacity** [comment]
@LWinterberg this does cause an interesting problem for the manual Leo as there are many, many, places, in the manual where the labelling in the tracks in the Track Control Panel is "**Audio Track**" and "**Label Track**"

**Comment by petersampsonaudacity** [comment]
> @petersampsonaudacity As you suggested I also changed the default name of the label tracks, 

@vsverchinsky  tested on W10 with your branch audacity-win-3.2.0-alpha-20220218+25d112a-x64-msvc2022 

This looks ok now 

>but probably it's not a final PR update

Does this mean:
a) it's going to be improved more, or
b) it may not happen in a release master?

**Comment by vsverchinsky** [comment]
> This looks ok now

Thanks!

> Does this mean: a) it's going to be improved more, or b) it may not happen in a release master?

improved

**Comment by petersampsonaudacity** [comment]
@vsverchinsky  Vitaly

testing on W10 with your latest branch:  audacity-win-3.2.0-alpha-20220222+9070458-x64-msvc2022 ,

I'm liking the Clip name numbering

![image](https://user-images.githubusercontent.com/50205984/155307783-8432cf6b-d9a0-4f45-b999-cf0d4c3b9d96.png)

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest alpha master:  audacity-win-3.2.0-alpha-20220322+b1dc193-x64-msvc2022

This looks good to me:
![image](https://user-images.githubusercontent.com/50205984/159476063-34990c51-e204-4d65-bb8b-39a120ba7b93.png)
