### ISSUE TITLE
Windows & Linux: malformed default upper tooldock with Audacity 3.1.x

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2544]
**Describe the bug**
On Windows from 3.1.0 onwards, and including 3.2.0 alpha, the default layout of the upper tooldock has changed, making this a regression on Audacity 2.4.2 (and note it is a different layout now to that shown in the Manual, which may unsettle readers).

The changes mean that the upper Tooldock is occupying an additional single height toolbar, thus reducing the space available for tracks.

@SteveDaulton confirms that this also happens on Linux

Oddly, this does **NOT** happen on macOS 12.2 Monterey where 2.4.2 and earlier and 3.1.0 and later.  I cannot test on Linux, 

**To Reproduce**
1. Purge the Audacity settings folder (to get OOTB factory default settings)
2. Launch 3.0.5
3. Observe the upper tooldock layout (see screenshot 1 below)
4. Quit audacity
5. Launch 3.1.3  _(or 3.1.0 or 3.2.0 alpha master)_
6. Observe: the layout of the upper tooldock is different that that at step 3 (see screenshot 1 below)

**Expected behavior**
The default layout to remain unchanged
a) as it was in 3.0.5 and earlier on Windows
b) consistent with 3.x.x, 2.x.x and earlier layout on Mac
c) consistent with the layout(s) shown in the Manual

**Screenshots**
### 1) 3.0.5 upper tooldock layout
![image](https://user-images.githubusercontent.com/50205984/153426304-34a69807-1eed-44a6-b1be-351ddf9494f9.png)
note that this layout is neat and wastes very little space in the upper tooldock.

### 2) 3.1.3 upper tooldock layout
![image](https://user-images.githubusercontent.com/50205984/153419306-d50ffd48-3df1-4735-8d29-39f0af496cbb.png)
Note that this leaves untidy and wasted spaces in the upper tooldock 
_and the additional single-height line needed unnecessarily reduces the space available for tracks._

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version Audacity 3.1.0 _was where this change originated_

**Additional context**
What is odd about this is
a) the default window width appears unchanged
b) the length of the meter toolbars appears unchanged

Widening the window on 3.1.x (and later) by 4mm or 5mm provides enough room for the meter toolbars to automatically migrate to their normal default position at the right in the double-height toolbar at the top - and the entire upper tooldock returns automatically to the former default layout.

Flagging @Tantacrul as a UX/GUI issue

**Comment by petersampsonaudacity** [comment]
@Penikov @LWinterberg  Pavel, Leo, can you please assign a P rating to this issue - I would suggest that P2 is most appropriate ...

**Comment by Penikov** [comment]
I've assigned P2, but this is just a 'first approximation. This P rate may be changed by the team after the backlog grooming

**Comment by SteveDaulton** [comment]
In case it's not obvious, the addition of the "loop" button has made the Transport toolbar wider, which pushes the Tools toolbar to the right, so there is no longer room for the Meter toolbars on the top row.

**Comment by LWinterberg** [comment]
a new layout will get established with either #2779 #2717 - whichever is completed last
