### ISSUE TITLE
Mac:  Effects. Audacity hangs when available room for applying an effect is not enough

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2545]
**Describe the bug**
Audacity hangs when available room for applying an effect is not enough

**To Reproduce**
Steps to reproduce the behaviour:
1. Generate a couple of 0.5 sec plucks
2. Arrange them along the track with 0.5 sec interval
3. Apply Paulstretch effect to the first one.

**Actual behaviour**
Audacity will show a warning dialog 'There is not enough room available and then hangs.

**Screenshots**

**Additional information (please complete the following information):**
 - OS: Reproducible on macOS Monterey
 - Version 3.2 +

**Comment by petersampsonaudacity** [comment]
Testing on macOS 12.2 Monterey with latest 3.2.0 alpha master audacity-macOS-3.2.0-alpha-20220210+698f8ae-x86_64 

I confirm this bug on my Mac

**Comment by petersampsonaudacity** [comment]
Testing on macOS 12.2.1 Monterey with:  audacity-macOS-3.2.0-alpha-20220221+976b796-x86_64 

I confirm that this now works properly

**Comment by Paul-Licameli** [comment]
Needs re-verification after commit 17bfc141daa3f81b471ada94392dfafc1139bffb

**Comment by petersampsonaudacity** [comment]
Testing on my Macbook Pro macOS 12.3.1 Monterey with latest alpha master:  audacity-macOS-3.2.0-alpha-20220412+17bfc14-x86_64 

I get the expected error message but _**NO**_ crash

**Comment by dozzzzer** [comment]
Tested on MacOS 11.6 and [audacity-macOS-3.2.0-alpha-20220412+17bfc14-universal](https://github.com/audacity/audacity/suites/6090408627/artifacts/211109259)
