### ISSUE TITLE
Alignment of Buttons on webpage 

### ISSUE THREAD

**Issue by Raeskaa** [audacity/audacity#2548]
**Problem**
When I reduce the screen size for the [Audacity-Webpage](https://www.audacityteam.org/), the notify-me button in the "Get notified section" sticks to the search box ( There's no padding-top there )
![image](https://user-images.githubusercontent.com/84667136/153740057-506bd315-9e6f-4445-9089-3fb08befea40.png)
![image](https://user-images.githubusercontent.com/84667136/153740730-f198406d-1163-4f0e-b7e2-aba46a1a5f05.png)

**To Reproduce**
1) Go to the webpage of Audacity
2) Just reduce the screen width on your system

**Expected behavior**
![image](https://user-images.githubusercontent.com/84667136/153740048-2075c5e7-81a4-469a-983d-e5028391066b.png)

**How to solve** 
Just add a class  to the div and add padding-top to it
![image](https://user-images.githubusercontent.com/84667136/153740160-838ac8e5-1054-46c7-af21-e355f174d967.png)
![image](https://user-images.githubusercontent.com/84667136/153740176-4f863358-55ac-4132-8386-b56e32cca95d.png)

**Comment by Penikov** [comment]
@Raeskaa Hello! What browser are you using? And what is the screen resolution?

**Comment by Raeskaa** [comment]
> @Raeskaa Hello! What browser are you using? And what is the screen resolution?

Chrome & Res ( 1920 x 1080 )

**Comment by Penikov** [comment]
Works fine to me: 
![image](https://user-images.githubusercontent.com/25851359/154481890-8c71513b-aacc-4e07-aeec-d4dc53daa681.png)

Checked this in Edge  and Chrome on Windows

**Comment by Raeskaa** [comment]
Hey @Penikov 
![image](https://user-images.githubusercontent.com/84667136/154660341-84abcae9-c690-4e87-b490-ac8409bacb34.png)
This works fine for me too - but when we shrink the screen size 

https://user-images.githubusercontent.com/84667136/154661893-3ab380ad-b588-49b4-92c0-ba7f6b8ac906.mp4

**Comment by Penikov** [comment]
@Raeskaa Oh, I see. I asked incorrectly. 
I mean this:
![image](https://user-images.githubusercontent.com/25851359/154794091-770576e2-c2d0-479c-8a76-dc6bc521364a.png)

So this is actually a viewport resolution for sure. 
And yes, if the viewport width is less than 1200 px, adaptive layout changes and button snaps to the text field. 
But the fix is elementary. 10px margin at the top of the button will help.

**Comment by Raeskaa** [comment]
> @Raeskaa Oh, I see. I asked incorrectly. I mean this: ![image](https://user-images.githubusercontent.com/25851359/154794091-770576e2-c2d0-479c-8a76-dc6bc521364a.png)
> 
> So this is actually a viewport resolution, not a screen resolution. And yes, if the viewport width is less than 1200 px, adaptive layout changes and button snaps to the text field. But the fix is elementary. 10px margin at the top of the button will help.

Yes!

**Comment by LWinterberg** [comment]
This is a [known issue](https://github.com/audacity/audacity/wiki/Known-Issues) and out of scope of this bugtracker
