### ISSUE TITLE
Hide/collapse one channel in a stereo track

### ISSUE THREAD

**Issue by hmijail** [audacity/audacity#2550]
**Is your feature request related to a problem? Please describe.**
I want to use Audacity for music education purposes (showing a multitrack recording while playing sections of it). Seeing the waveforms is useful, but having on screen the 2 channels of every stereo track is unhelpful; it halves the screen space for basically redundant information. It would be enough to see one of the channels for each track.

I tried mixing the tracks down to mono, so that they naturally only show one channel, but the sound quality suffers.

I also tried using the vertical splitter in the track to make the unwanted channel smaller. That  helps, but there is a limit to how small I can make it. 

**Describe the solution you'd like**
Removing the minimum limit to the vertical splitter is probably the natural solution to this kind of problem. I'd say this is the typical behavior whenever this kind of splitters appear in other software.

**Describe alternatives you've considered**
The macro `SetTrack:Height="0"` when applied to a channel would also be nice; currently looks like the macro execution rejects the 0 (but it isn't working anyway as reported in #2549, so maybe I'm missing something).

Any way to hide/totally collapse one of the channels in any/all tracks would be welcome.

**Comment by AsRaNi1** [comment]
HI, i would like to work on this issue! Thank you

**Comment by hmijail** [comment]
I realized that using a macro with `SetTrack:Height="0"` actually does work (my issue #2549 was wrong). So I am using that now.
Still, it'd be just natural to be able to collapse a channel in a track as described.

**Comment by hmijail** [comment]
Also, running such a macro causes an alert saying 
> Set Track: Could not load settings below. Default settings will be used.
> Height="0"

And yet, the macro runs as expected, so this alert seems wrong.

**Comment by hmijail** [comment]
Ugh, it's even messier.

The macro `SetTrack:Height="0"` triggers the mentioned alert, and some "default settings" get reapplied. In theory this should avoid the 0 parameter.

However, those "default settings" can come from the macro management dialog, which allows me to set 0 as the height parameter! So after all my 0 gets applied and so I can collapse the channel, as I wanted. So this is a parameter sanitization failure turned into a underhanded feature.

SO: please, remove that attempt at sanitization against low Height parameters in SetTrack macros, so it accepts 0.

**Comment by LWinterberg** [comment]
I'll close this bug for the time being but keep the tracking bug open.
