### ISSUE TITLE
LED meters (as in DarkAudacity)

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2558]
**Describe the bug**
LED meters (as in DarkAudacity) - this would give the GUI a nice refresh giving the meters a more modern look - a more "digital look".

**To Reproduce**
1. Install DarkAudacity - http://www.darkaudacity.com/download.html
2. launch 
3. Import some audio
4. Press Play
5. Observe the LED default meters (see Screenshot 1)
6. Click on the loudspeaker icon in the Playback meter
7. Select Options
8. Observe the options dialog defaults to LED - _but retains the current Audacity default RMS and the older, original, Audacity Gradient metering_ - see Screenshot 3

Note that the meters can be floated an enlarged if required -0 see Screenshot 2

**Expected behavior**
An added option (on by default) for LED metering

**Screenshots**
### 1) default LED meter
![image](https://user-images.githubusercontent.com/50205984/154077191-30527549-dbb5-42b7-a73e-e14d6fe34988.png)

### 2) enlarged, floated, LED meter
![image](https://user-images.githubusercontent.com/50205984/154077381-9b0497a7-3ffd-43d4-a3ac-675f38c41d03.png)

### 3) options / settings
![image](https://user-images.githubusercontent.com/50205984/154077567-057fd730-5571-433b-9eb9-82b8a832a1f7.png)

**Additional information (please complete the following information):**
 - OS: W10 and macOS 12.2.1 Monterey - but assume all
 - Version 3.1.3/3.2.0 and earlier

**Additional context**
Flagging @Tantacrul as a UX/GUI issue

Note that many/most of the other features that James changed for DarkAudacity have now already migrated into mainstream Audacity (including the Dark (optional) theme) - but this one somehow escaped. See:
http://www.darkaudacity.com/download.html

James advised me of this permalink for where the LED meter code is.
https://github.com/audacity/audacity/blob/c3aee46a01afb8f8a1f4929f03616af5482e43dd/src/widgets/Meter.cpp#L683
He added:
>[it will need] rework it as it is rough and ready and with no customisation.

Note that  with this implementation (for all three metering modes in DA) James removed the numbering.  
I **_strongly_** think that numbers on the meters should be retained, if only as an option.

**Comment by petersampsonaudacity** [comment]
### Aside 1
Note that as part of this rework James consolidated the meters and the Mixer toolbar thus saving some screen real estate.

Observe the orange movable sliders in the meters:
![image](https://user-images.githubusercontent.com/50205984/154079329-c2b4011d-2895-461a-b44c-7b0d6acfd395.png)

This does **_not_** form part of this enhancement request, but is something that could be considered for the future.

**Comment by petersampsonaudacity** [comment]
### Aside 2
Note too that with this implementation James also removed the Device toolbar and placed (most) of its functionality in the meter options - but he omitted the stereo/mono setting (which I think was a serious omission).

![image](https://user-images.githubusercontent.com/50205984/154079802-19e958fa-84df-4e8d-ad5b-fb1274f5bb41.png)

Note that these settings, including the stereo/mono can be made in Devices preferences:
https://alphamanual.audacityteam.org/man/Devices_Preferences

This definitely does _**NOT**_ form part of this enhancement request - but again is something that could ne considered for the future as a way of saving screen real estate,

_The Device toolbar could also be retained - but then it could be turned "off" by default._

**Comment by Tantacrul** [comment]
I also much prefer this option to the separate sliders / input meters. Let me discuss this with the team. There's a lot of stuff in this that we were planning for the next release, although the details are a little different here and there. Thanks!

**Comment by DavidBailes** [comment]
@Tantacrul 
If it's decided to combine the sliders and meters in some way, please can the design include a specification of how both the sliders and the meters remain accessible for users of screen readers. (Rather than it being left to be fixed up at some later date.)

**Comment by LWinterberg** [comment]
Aside 1 got spun off into #2779

We will not be adding this version of the LED meter. The LEDs are not functional (that is, they don't discretely light up but instead are just an overlay over the normal meter) and they don't appear to be tied to any meaningful volume interval (eg 1dB, 3dB). 

That said, using plain color segments instead of a gradient is something we're looking into.
