### ISSUE TITLE
Can't activate VST Plugin, Audacity 3.1.3 via AppImage

### ISSUE THREAD

**Issue by anarchist912** [audacity/audacity#2563]
Linux Xubuntu 21.10
Audacity 3.1.3, AppImage via AppImageLauncher
added BalanceSPTeufelsbergReverb.so and mverb-vst.so to ~/.vst

They appear in the "New" plugins tab, clicking activate and "OK" doesn't have any effect. No import dialog, no new entry in the effects section. If I go back to the add/remove plugins dialog, they reappear under "New" again. Also no effect after restart of Audacity. Tried deleting AppImage, removing ~/.audacity & ~/.audacity-data, and readding AppImage. No effect. There are no corresponding logs when running AppImage from terminal. I attached the startup logs as screenshot.

I do have a 64bit system and these plugins are 64bit, too. I attached them here as well. 

[mverb-linux.zip](https://github.com/audacity/audacity/files/8079743/mverb-linux.zip)
[BalanceSPTeufelsbergReverbLinux64_v101.zip](https://github.com/audacity/audacity/files/8079744/BalanceSPTeufelsbergReverbLinux64_v101.zip)

![image](https://user-images.githubusercontent.com/30655359/154262412-ddbb1595-bf8b-416e-8885-c824cea40d09.png)

**Comment by Penikov** [comment]
Confirmed on Fedora 35

**Comment by crsib** [comment]
In the latest builds Audacity finds and loads BalanceSPTeufelsbergReverbLinux64_v101 just fine. mverb is compiled for 32-bits CPU and is not compatible with 64-bit Audacity.
