### ISSUE TITLE
Smart Clips fail to copy correctly between project windows

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2568]
**Describe the bug**
Copying smart clips from one project window to another can paste in wrong places, wrong sizes, and overlapping.

**To Reproduce**
1. Launch Audacity
2. Generate 30 second Chirp
3. Split at around 10s and 20s
4. Resize the first clip so that it ends at around 5s
5. Resize the middle clip so that it starts around 12s and ends around 17 s
6. Resize the third clip so that it starts around 25s
7. Drag the second clip to the end of the first clip
8. Drag the third clip to the end of the second clip
9. Select from about 2s to around 2s before the end
10. Copy
11. New Project
12. Paste
13. Observe the clips are messed up

**Expected behavior**
Clips to be not messed up at step 13

**Screenshots**
![bug](https://user-images.githubusercontent.com/11681097/154545455-04d43303-9c2d-4479-b94a-f649c5ff57b6.png)

**Additional information (please complete the following information):**
 - OS: Reported on macOS. Confirmed on Linux
 - Version Audacity 3.1.3 and 3.2.0

**Additional context**
Quote from the Audacity forum:
> How can I prevent this from happening (as I don't realize it until I've already exported everything)

Considering that this can ruin a person's work after they have spent a lot of time and effort, and in addition to the *many* other "smart clip" bugs, I think that fixing smart clips needs to be treated with utmost priority, hence labelling as P1.

**Comment by dozzzzer** [comment]
Verified both on Win 10 x64 and MacOS Monterey.

![image](https://user-images.githubusercontent.com/70063970/164478786-bdc95d0c-62ba-4d55-873a-096084a57a22.png)
