### ISSUE TITLE
Audacity says "-9997 Invalid sample rate" when stereo/mono setting is incorrect.

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#2574]
**Describe the bug**
When a user tries to record stereo into an existing mono track, Audacity complains that the sample rate is incorrect.  This message is incorrect, misleading, confusing, and can cause the user to waste a lot of time spinning his wheels and pulling out his hair, possibly giving up altogether on trying to use Audacity.

**To Reproduce**
1. Start an empty project in Audacity
2. Press "r" to start recording from the internal microphone.
3. Notice that a stereo track is created OK.
4. Stop recording, and delete the track.
5. Create a new track with Tracks > Add New > Mono Track.
6. "r" to start recording.
7. -9997 Invalid sample rate error occurs.
8. Delete the track.
9. Create a new track with Tracks > Add New > Stereo Track.
10. "r" to start recording.
11. Observe no error.

**Expected behavior**
A clear and concise description of why the recording in step 6 failed.

**Additional information (please complete the following information):**
 Windows 10 WASAPI; Audacity 3.1.3

**Comment by petersampsonaudacity** [comment]
Testing on W1o with 3,1,3 I Cannot reproduce this

At Step 7 I get a stereo track recorded _(expected behavior)_

So WORKSFORME

**Comment by dozzzzer** [comment]
This is still the case in 3.3.3

**Comment by dozzzzer** [comment]
Not reproducible as of 3.4.2 either on macOS or Windows (even with WASAPI selected as a host):

#### Step 6:
<img width="450" alt="image" src="https://github.com/audacity/audacity/assets/70063970/dc89bd98-fb59-4639-8dfd-85569b0a4898">
