### ISSUE TITLE
Failing to build

### ISSUE THREAD

**Issue by simondvt** [audacity/audacity#2579]
**Describe the bug**
During the build I get the following error messages: [pastebin](https://pastebin.com/FQS3SnBJ)

**To Reproduce**
1. Unpack the sources
2. Create and go to the build directory
3. Run `cmake` as follows
`cmake -G "Unix Makefiles" \`
`        -Daudacity_conan_enabled=Off \`
`        -DCMAKE_BUILD_TYPE=Release \`
`        -Daudacity_use_ffmpeg=loaded \`
`        -Daudacity_lib_preference=system \`
`        -Daudacity_obey_system_dependencies=On \`
`         ..`
4. Run `make`

**Expected behavior**
Compilation should be successful

**Additional information (please complete the following information):**
 - OS: ArchLinux
 - Version: Audacity 3.1.3

**Additional context**
I have installed all the required libraries from my distribution packages. `cmake` runs fine.

**Comment by crsib** [comment]
Which version of wxWidgets do you have? It seems that you are building against 3.0

**Comment by simondvt** [comment]
> Which version of wxWidgets do you have? It seems that you are building against 3.0

I have wxWidgets 3.0.5.1

**Comment by crsib** [comment]
Audacity requires wxWidgets 3.1 since the Audacity 2.4.1.

**Comment by simondvt** [comment]
> Audacity requires wxWidgets 3.1 since the Audacity 2.4.1.

Got it. Thank you for your help.
