### ISSUE TITLE
Output switching on MacOS - e.g. headphone inserted after app launch

### ISSUE THREAD

**Issue by davecates** [audacity/audacity#2583]
**Describe the bug**
Once Audacity is launched it is not possible to switch to headphones as an output if they are connected after the launch of the app.

Also, if headphones are connected before Audacity launch but then disconnected then Audacity throws an error. 

**Expected behavior**
Audacity should dynamically gracefully detect additional output devices or those removed. Previous versions worked well.

**Additional information (please complete the following information):**
 - OS: MacOS Monterey 12.2.1
 - Version Audacity 3.1.3
 - MacBook Pro 14" Apple Silicon M1 Max 64GB RAM

**Comment by petersampsonaudacity** [comment]
This is a known issue (and has been so for a long time)

Please see this more generic all-platforms issue logged for this: Proposal Auto Detect Audio Device Changes #2409
