### ISSUE TITLE
Improving 2 channel recording UX

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2589]
**Describe the bug**
In some cases, stereo can be recorded to separated mono tracks 

**To Reproduce**
1. Add a 2 mono tracks
2. Switch audio interface setting to stereo mode
![image](https://user-images.githubusercontent.com/25851359/155521967-4f1856e6-9ea2-49b2-aec1-2f9918bcdb72.png)

3. Press R or click the Record button
4. Press Shift+R to record into a new track

**Wanted behavior**
When 2 mono tracks are present: 

* Record should record the stereo into 2 mono tracks, center-panned
* Shift+record should make an additional 2 mono tracks, center-panned. 

When multiple tracks are present: 

* When a mono track has another mono track adjacent to it below, selecting just one mono track should record to it and the track below
* When shift+record in a stereo track, a new stereo track should be created. When shift+record in a mono track using a 2-channel input, 2 new mono tracks, center-panned, should be created.

<details>

<summary>original report continues</summary>

**Actual Behaviour**
![image](https://user-images.githubusercontent.com/25851359/155522099-78dd2956-f7a9-4220-9226-d7509deca47c.png)

**Expected behavior**
Despite the manual says 'However, if you have two mono tracks and try to append record in stereo, Audacity will place one stereo channel in each mono channel. If you have many mono tracks, you can select two of them and record the left channel in the first and the right channel into the second.'
that behavior brings inconsistency and leads users to mistakes in stereo recording and mixing. So my point is if a user needed to record stereo to split stereo track or two mono tracks, the user should firstly merge separated channels to stereo to ensure the record will be on the right track.

**Additional information (please complete the following information):**

 - Version: All

</details>

**Comment by petersampsonaudacity** [comment]
And note that it records to center-panned mono tracks - and **_not_** left and right panned tracks (as you would get if you used **Split Stereo Track** fro a stereo track's Track Contro Panel dropdown menu.

**Comment by petersampsonaudacity** [comment]
> that behavior brings inconsistency and leads users to mistakes in stereo recording and mixing. So my point is if a user needed to record stereo to split stereo track or two mono tracks, the user should firstly merge separated channels to stereo to ensure the record will be on the right track.

I am minded to agree with this.

**Comment by LWinterberg** [comment]
this has been superseded by a multi-track recording design
