### ISSUE TITLE
Audicity 3.1.3 sometimes freezed when using Ctrl+mouse wheel to zoom

### ISSUE THREAD

**Issue by 0x391F** [audacity/audacity#2591]
**Describe the bug**
Audicity 3.1.3 sometimes freezed when using Ctrl+mouse wheel to zoom

**To Reproduce**
1. Import any file into audacity
2. Using Ctrl+mouse wheel to zoom
3. See error

**Expected behavior**
This bug shouldn't appear. 

**Screenshots**
N/A

**Additional information (please complete the following information):**
 - OS: Windows 10 Enterprise LTSC 2021 x64 (21H2)
 - Version: Audacity 3.1.3
 - (if relevant) Sound Device: not relevant

**Additional context**
N/A

**Comment by petersampsonaudacity** [comment]
I can't reproduce this on W10 with 3.1.3

**Comment by LWinterberg** [comment]
possibly the same as: 
* #2348
