### ISSUE TITLE
No visual cue for stored cursor position

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2592]
**Describe the bug**
There is no visual cue for the stored cursor position.

The stored cursor position can be created with the **Select > Store Cursor Position** command has no visual cue to show/declare its presence.

_Note that this command is mostly used in conjunction with its menu neighbor **Select > Cursor to Stored Cursor Position** - and the absence of a visual cue for a stored cursor position can make the use of this command somewhat vague._

**To Reproduce**
1. Get some audio
2. set the cursor somewhere
3. Select > Store Cursor Position
4. Observe: there is no visual cue for the stored cursor position

**Expected behavior**
A clear visual cue for the stored cursor position

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS: W10 and macOS 12.2.1 Monterey
 - Version: all Audacity

**Additional context**
Tagging @Tantacrul as a UX/GUI issue

**Comment by petersampsonaudacity** [comment]
Note that there is even and advice div in the manual to warn users _(those that bother to RTFM)_ of this shortcoming:

![image](https://user-images.githubusercontent.com/50205984/155748310-acfdc518-8bf1-480f-954a-9a5e2ce092ef.png)

**Comment by LWinterberg** [comment]
The stored cursor concept is on its way out; I'm currently investigating alternatives
