### ISSUE TITLE
empty or corrupted MIDI track

### ISSUE THREAD

**Issue by jserquera** [audacity/audacity#2595]
Great software!

Here is a bug I found in different versions since 3 years ago, including recent versions. In Windows at least.

Steps to reproduce:
- Import MIDI file in a new empty window or project
- Save project and close.
- Open the project. Error: the MIDI tracks appears but empty of notes.

**Comment by petersampsonaudacity** [comment]
I cannot reproduce this on W10 with 3.1.3 - works fine for me

**Comment by jserquera** [comment]
It happens to some of my students. It's what I can say

**Comment by Pokechu22** [comment]
I'm unable to reproduce this on Windows 10 with Audacity 3.1.3 as well.  I also know that I was able to successfully save and open projects containing MIDI files when I was working on it in the past (~2017-2019), but that was before the change to AUP3.

Are you yourself able to reproduce it (consistently), or has it only happened to your students?

If you're able to reproduce it consistently, can you zip a copy of the affected project file?

Also, just as a guess, did the name of the file being imported contain any non-English characters or other special characters?

**Comment by jserquera** [comment]
I tried myself and I got the error.

the original midi file is attached. The aup3 file is attached, too, with a corrupted MIDI track. The track is not empty but it is not the original.

This time was with Audcity 3.1.0

[out.zip](https://github.com/audacity/audacity/files/8152514/out.zip)

**Comment by petersampsonaudacity** [comment]
> I tried myself and I got the error.
> This time was with Audcity 3.1.0

You need to test with the latest version Audacity 3.1.3 - _nobody is going to fix bugs in old superseded versions of the bug no longer exists in the latest version_

**Comment by petersampsonaudacity** [comment]
> the original midi file is attached. The aup3 file is attached, too, with a corrupted MIDI track. The track is not empty but it is not the original.

Well your out.aup3 opens fine and plays properly for me
![image](https://user-images.githubusercontent.com/50205984/155978780-7b0323d7-ba59-4f41-b21b-0491d6fe9be3.png)

**Comment by petersampsonaudacity** [comment]
_And incidentally it all works fine for me too if I test with the old superseded Audacity 3.1.0 that you were using_

**Comment by jserquera** [comment]
I'll upload a screenshot of the midi track with the error. I don't have it with now.

**Comment by jserquera** [comment]
![Captura de pantalla 2022-02-28 131821](https://user-images.githubusercontent.com/68276128/156202442-ad7a7e9b-8b6f-47ba-bf9c-2d4a3af85133.jpg)

It is full of notes, but wrong notes.

**Comment by jserquera** [comment]
Í tried at work, with another computer, not latest version and I got the same issue.

I just tried with latest version 3.1.3 in my laptop and I get the same issue

**Comment by Pokechu22** [comment]
That's weird.  It looks like all of the note starts/ends got moved to the nearest quarter-note.  Does this issue also affect MIDI playback, or does it sound correct when played?

**Comment by jserquera** [comment]
It doesn"t sound correct when played.

**Comment by Pokechu22** [comment]
Can you import it into audacity, and then select File &rarr; Export &rarr; Export MIDI, then change the "save as type" value to "Allegro file (*.gro)", and then upload the file produced by that here?

**Comment by jserquera** [comment]
[out_313.zip](https://github.com/audacity/audacity/files/8164244/out_313.zip)

Here it is, zipped.

**Comment by Pokechu22** [comment]
Alright, I can reproduce with that one.  I expect the same thing will happen in this case, but can you also import the original MIDI, then select File → Export → Export MIDI, and save it as `out2.mid`, and upload that here?  (You might need to change "save as type" back to MIDI).

**Comment by jserquera** [comment]
[out2.zip](https://github.com/audacity/audacity/files/8164413/out2.zip)

here you are

**Comment by Pokechu22** [comment]
Indeed, the same thing happens there.  A minor correction to my earlier comment: note starts/ends are getting moved to the nearest _second_, not beat, but the original MIDI file doesn't actually have tempo information (instead it just has 1 beat per second).  Unfortunately I don't have any further guesses as to _why_ this is happening when you import the original file (and more importantly, why it's happening to you but not to me).

**Comment by jserquera** [comment]
I see.

The error is not with Import only. Then I save project, close and open again.

**Comment by Pokechu22** [comment]
I'm able to reproduce... and the reproduction steps are kinda weird:

1. Launch Audacity.
2. Select Edit &rarr; Preferences...
3. Under interface, set language to <span lang="es">Espa&ntilde;ol</span>.
4. Select accept.
5. Close Audacity.
6. Launch Audacity.
7. Select <span lang="es">Archivo &rarr; Abrir</span> (File &rarr; Open)
8. Open Out.aup3

Importing out.mid does not reproduce the issue for me, only out.aup3.  However, out.aup3 works correctly when in English, which is also really weird.  To return to English:

1. Select <span lang="es">Editir &rarr; Preferencias...</span> (Edit &rarr; Preferences...)
2. Under <span lang="es">Interfaz</span> (Interface), set <span lang="es">Idioma</span> (language) to English.
3. Select <span lang="es">Aceptar</span> (Accept).

My brief guess is that some variable related to allegro (the library used for MIDI), possibly `units_are_seconds`, is not being initialized in all cases and the user interface language happens to change what's already in memory enough that it behaves differently in English and Spanish.  But I'm not sure.

Can you check whether the issue still happens to you if you change the language to English?

**Comment by jserquera** [comment]
Very good, you are right.

The issue doesn't happen to me if I change the language to English.

**Comment by jserquera** [comment]
This is a bug, then, right?

**Comment by Pokechu22** [comment]
Yes.  There's a work-around for it (switching to English), but it happening at all is a bug.

**Comment by jserquera** [comment]
@LWinterberg shall we change the label?

**Comment by jserquera** [comment]
Now, it happens even with English language

v 3.2
