### ISSUE TITLE
Gone: https://www.facebook.com/AudacityTeamOfficial/

### ISSUE THREAD

**Issue by elvey** [audacity/audacity#2596]
**Describe the bug**
We direct people here, but it seems to be gone.  Archive.org suggests it disappeared in January.

**To Reproduce**
1. Go to [https://www.audacityteam.org/community/users/](https://www.audacityteam.org/community/users/) and see we direct Users there. 
3. Click to see the facecrack page is gone. 
4. (optional) See it existed - http://web.archive.org/web/20210105025219/https://m.facebook.com/AudacityTeamOfficial/

**Fix?**
If it can be restored and should, that's the fix.  
If not, the fix is to update the site ([this page](https://www.audacityteam.org/community/users/) and probably others)
<hr>
PS After posting this, I noticed that https://twitter.com/getaudacity hasn't posted since 2019.  Yet (as, e.g. https://github.com/audacity/audacity/issues/2493 and https://github.com/audacity/audacity make clear) active development continues apace. 

So perhaps the issue is _a social media/community admin is needed_?

**Comment by LWinterberg** [comment]
ah. The facebook page is now on facebook.com/audacity, we missed the link on the website. 

as for twitter.com/getaudacity, the admin died. I need to get around making a new one.

**Comment by petersampsonaudacity** [comment]
Seems to work fine now Leo @LWinterberg  - the Facebook link on that Audacity website page now goes to:
https://www.facebook.com/Audacity

So WORKSFORME
