### ISSUE TITLE
Change "Flatten" to "Reset EQ" in Filter Curve EQ effect

### ISSUE THREAD

**Issue by junaayd123** [audacity/audacity#2600]
it was hard for me to find the button to reset the EQ... maybe change the text in the button to "Reset EQ" to help us understand the button better?

**Comment by LWinterberg** [comment]
Fwiw, there also is a Manage > Factory Presets > Defaults you can select. A fix for that is discussed in #2417. I'm closing this issue in favor of that as resetting to default is probably a good thing to have accessible everywhere and not just in the EQ :)
