### ISSUE TITLE
Check plugins on startup

### ISSUE THREAD

**Issue by AnitaBats** [audacity/audacity#2607]

**Comment by dozzzzer** [comment]
@vsverchinsky 

- [ ] after a VST plug-in is enabled, it has no identifier displayed next to its full path in the Plug-in Manager window:

<img width="844" alt="image" src="https://user-images.githubusercontent.com/70063970/170029455-4b3a3150-c84f-4eb3-b153-0d3596c03cd0.png">

Only VST3 plug-ins have it.

**Comment by crsib** [comment]
Why do you consider that it is a bug?

**Comment by crsib** [comment]
And it is not even something new. Here is how 3.1.3 handles LV2 for example

![image](https://user-images.githubusercontent.com/2660628/170033025-dfa46317-d8fa-4c47-9e6e-b8994a42b76f.png)
