### ISSUE TITLE
Selection indication on the time bar does not correspond to selection

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2614]
**Describe the bug**
![image](https://user-images.githubusercontent.com/25851359/156559629-ef8bf200-7100-4457-ac05-519772ace0c2.png)

**To Reproduce**
1. Generate a clip
2. Click the Add Effect button
3. Select a random region on a track

**Expected behavior**
The timeline should be bound to track area

**Additional information (please complete the following information):**
 - OS: All
 - Version: Audacity 3.2.0-alpha-20220302

**Comment by petersampsonaudacity** [comment]
Note that the Timeline is out of kilter too.

In the image above the audio appears to start at ~4.3 seconds

**Comment by petersampsonaudacity** [comment]
This may be related to:
 With 3.2.0 the track area can be dragged totally off screen #2620

**Comment by petersampsonaudacity** [comment]
Testing on W11 with @vsverchinsky  Vita;'s branch build  audacity-win-3.2.0-alpha-20220316+f36d06b-x64-msvc2022 

This is looking much better

a) works fine at default size of the ne (nlank as of now) effect pane
b) the pinned playhead works fine too
![image](https://user-images.githubusercontent.com/50205984/158771047-4b464833-cd3d-4b76-86d1-5f7b87bd7f0b.png)


c) and works with increased size effects pane
![image](https://user-images.githubusercontent.com/50205984/158771268-6f87f649-4cba-4088-8351-6eecbca2f5dd.png)

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest alpha master audacity-win-3.2.0-alpha-20220412+17bfc14-x64-msvc2022

Looks good to go to me

**Comment by dozzzzer** [comment]
Testing on MacOS 11.6, looking good. Moving to 'Done'.
