### ISSUE TITLE
Export Multiple improvements

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#2615]
There are many opportunities to improve the "Export Multiple" dialog. Logged so far:

- [x] #703 
- [x] #58
- [x] #1507

Thought to the end, for full flexibility of an export multiple dialog, there'd need to be variables for the user to set, like reaper does: 
![image](https://user-images.githubusercontent.com/87814144/156562877-c7b15d8a-6c68-4a57-810e-2c070eff4a31.png)

Alternatively, the Export Multiple feature might stay simple and somewhat unflexible, with a clear idea that anyone who does need approximately 150 different variables for their file names would use scripting instead.

**Comment by petersampsonaudacity** [comment]
> Alternatively, the Export Multiple feature might stay simple and somewhat unflexible, with a clear idea that anyone who does need approximately 150 different variables for their file names would use scripting instead.

Big +1 for keeping it simple

That mock-up GUI looks horrendous - making for poor UX

**Comment by LWinterberg** [comment]
With the merger of the export dialogs, adding enough variables to do every use case justice becomes detrimental, but this is an excellent use case for some sort of scipting-based thing.
