### ISSUE TITLE
With 3.2.0 and later the track area can be dragged totally off screen

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2620]
**Describe the bug**
The track area can be dragged totally off screen if the Effect button has been used

**To Reproduce**
1. Launch 3.2.0 alpha
2. get some audio
3. Click the new **Effect** button in the TCP
4. Observe the (currently) empty effect panel opens up blank
5. Hover your cursor over the left boundary of the track - the Track Control Panel
6. Observe: double-headed arrow (visual cue to indicate movement possible)
7. Click and drag rightwards (partway)
8. Observe the track moves rightwards - thereby expanding the empty effect panel
9. Again, hover your cursor over the left boundary of the track - the Track Control Panel
10. Click and drag rightwards - but this time all the way to the right
11. Observe: now we have no track and no way of getting it back (see screenshot image)

**Expected behavior**
It should not be possible to entirely drag the track off the Audacity window - and with no means of recovery, pulling it back

**Screenshots**
### After Steps 7-8
![image](https://user-images.githubusercontent.com/50205984/156603500-05cfde94-e704-4e64-9d9d-6fa887f5ab9a.png)

### After steps 10-11
![image](https://user-images.githubusercontent.com/50205984/156601452-e5562090-0163-4f67-a360-9f2b949e0b43.png)

**Additional information (please complete the following information):**
 - OS: Windows 10 - but assume all OS
 - Version 3.2.0 latest alpha master

**Additional context**
I can find no way of getting the track back displayed in the Audacity window.

**Comment by petersampsonaudacity** [comment]
Interestingly pressing Play does cause the track to play and the Timeline moves - but of course the track never hoves into view.

Choosing pinned playhead fails to ameliorate the situation as I was hoping it might.  Rather the pinned playhead:
1. appears to be stuck ar wher the TCP would normally end abd the track would start,
2. flickers (it shouldn't do this),
3. cannot be dragged to a new position on the Timeline (as it should).

**Comment by petersampsonaudacity** [comment]
If after Step 8 you choose pinned playhead and press play you can get a pinned head that is above the effects panel and not the track:
![image](https://user-images.githubusercontent.com/50205984/156606226-a93e7b13-c1fc-4e94-9fb9-8e6c5fe653ec.png)

**Comment by petersampsonaudacity** [comment]
This may be related to:
 Selection indication on the time bar does not correspond to selection #2614

**Comment by Penikov** [comment]
I'm not sure this is a bug. 
In concept of vertical stack for effects that wide panel doesn't look bizarre to me.
@Tantacrul

**Comment by petersampsonaudacity** [comment]
> I'm not sure this is a bug.

If it's not a bug - then just how do you get waveforms restored to show on the screen once you've pulled the waveform over so thet the Effects stack pane occupies the whole Audacity window.

I, certainly, could find no way to do that _(apart from closing Audacity and restarting)_.

**Comment by LWinterberg** [comment]
Self-compiled I reach some debug info:
![image](https://user-images.githubusercontent.com/87814144/187143488-a44a52ac-2722-41ae-ba9f-c91d4049fad6.png)

https://user-images.githubusercontent.com/87814144/187142843-d3727732-328a-4a6e-a7d1-bb825ae017e9.mp4

when using something that fell out of CI, it can be dragged all the way, at which point it cannot be back because the window resize kicks in instead. 

https://user-images.githubusercontent.com/87814144/187200140-365ea80a-c0f8-4bb6-b74f-7abb635f9456.mp4

**Comment by petersampsonaudacity** [comment]
@Tantacrul   

Martin, have you noticed the odd corruption that you get in the top of the real-time effects panel as you drag it wider?
![image](https://user-images.githubusercontent.com/50205984/190208562-496530c3-39e3-40a2-bc89-69fed3cb02e2.png)

**Comment by Tantacrul** [comment]
No, not seen that yet.

**Comment by petersampsonaudacity** [comment]
> No, not seen that yet.

I logged that as:   Visual corruption on Windows when enlarging the real-time effecs stack pane #3641

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest 3.2.2 beta:

Mitigated somewhat by the **"X** at top right to escape this
![image](https://user-images.githubusercontent.com/50205984/200835262-c878ad47-e8b4-4b50-b3f9-b78232393e07.png)
Which dumps the user out of the effects stack

**Comment by petersampsonaudacity** [comment]
Testing on W10 with the latest Beta for 3.2.3:  audacity-win-3.2.3-beta-20221219+0b46906-x64-msvc2022

This now seems to be fixed - the widest I can now drag the Effects Stack to is just under half the available window
![image](https://user-images.githubusercontent.com/50205984/208421526-6eedf6e4-dca5-45b9-9dff-a6862025dac7.png)
This looks fine to me

**Comment by petersampsonaudacity** [comment]
Ah - buy I note it seems to be a fixed maximum size of 10cm or so.

This is what I get if I expand the above project to full screen
![image](https://user-images.githubusercontent.com/50205984/208422096-e4665c09-ddd3-4a45-ba96-32a36ccb582a.png)


### And it plays nicely if the narrow the width of the window
![image](https://user-images.githubusercontent.com/50205984/208422534-d106eb6c-832f-4c39-88a4-a6868d29831b.png)

**Comment by dozzzzer** [comment]
Verified
