### ISSUE TITLE
Text on Input and output drop-down lists go out of frames

### ISSUE THREAD

**Issue by Charlie-Ramirez-Animation-Studios-de-MX** [audacity/audacity#2624]
**Describe the bug**
in the audacity 3.1.3 GUI the text in the drop down windows for server selection, audio input and output, pops out of the boxes or hides/overlaps when trying to resize making it impossible to move them out of position unless they expand up to a very large size and there is another free area of ​​the same size
**To Reproduce**
1. On a Debian 11 Computer with a KDE Plasma desktop
2.  Download or install audacity 1.3.1 in any of its available versions [Flatpak and/or Appimage package].

3. Open the app.
You will notice that the dropdown lists one of them is not visible and the others are truncated.

4. If you click on them they continue to work, but it is complicated to use since they tend to overlap one list with another [Trying to move them from position is impossible, trying it will open the audio servers tab (due to the overlap)]
5. Try changing the size to a very large one The lists should be moderately aligned or accommodated enough to be able to see the text and drag its position

**Expected behavior**
Texts and click areas should be kept "centered" (or at least visible text with left alignment) and auto-fit-hide to bounds based on the size of the dropdowns as in the case of previous versions

**Screenshots**
### For Flatpak:
![image](https://user-images.githubusercontent.com/64709446/156678183-7e88c06c-2737-4db6-9730-403b0fb0c73a.png)
![image](https://user-images.githubusercontent.com/64709446/156678438-6b5be48b-c89c-4f37-b17a-b3593d0df986.png)
### On Appimage [The problem is more tolerable [does not cause overlapping on click] however the dropdown icons have disappeared]
![image](https://user-images.githubusercontent.com/64709446/156678968-dc4cd712-f7a4-4a9f-b586-6f067682984a.png)
![image](https://user-images.githubusercontent.com/64709446/156679144-7b3a72d0-6a0f-46da-b784-598b7ee0502f.png)

**Additional information (please complete the following information):**
 - OS: Debian 11 x64 (KDE Plasma Desktop) -Testing Packages Enabled
 ### -Flatpak
 - Version [Audacity 3.1.1 - Tested on Flatpak and Appimage Ver.]
 Fecha de compilación: Jan 17 2022 Commit Id: ff6d67 of Wed Dec 22 16:35:36 2021 +0100
Tipo de compilación: CMake Compilación de distribución (nivel de debug 1), 64 bits
Compilador: GCC 11.2.0
wxWidgets  3.1.5 (Librería de entorno gráfico multiplataforma)
### -Appimage
-Fecha de compilación:Dec 22 2021
Commit Id:ff6d67 of Wed Dec 22 16:35:36 2021 +0100
Tipo de compilación: CMake Compilación de distribución (nivel de debug 1), 64 bits
Compilador:GCC 7.5.0 (Audacity)
Prefijo de instalación:
wxWidgets(Librería de entorno gráfico multiplataforma) 3.1.3 (Audacity)
**Additional context**
Despite the Deb testing packages, all are up to date and the problem does not affect the Old DSFG version of Audacity Available in the debian APT.

**Comment by LWinterberg** [comment]
the missing dropdown icons in the appimage got fixed by #3571. Flatpak will probably be untestable until sometime after the 3.2 release, so not sure what to expect there.

**Comment by crsib** [comment]
Flatpak is packaged differently. #3571 only affects AppImage packaging

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
