### ISSUE TITLE
Pressing Home on the Audacity Forum takes you to the Audacity Website

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2631]
**Describe the bug**
Pressing Home on the Audacity Forum takes you to the Audacity Website - the home page:
https://www.audacityteam.org/

**To Reproduce**
1. Go to the Audacity Forum
2. Click on Home
3. Observe: you are taken to the Audacity Website

**Expected behavior**
Pressing Home on the Forum should take you to the Forum (as it always used to)

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS: Windows 10 - but assume all OS
 - Version no applicable

**Additional context**
There is, and always has been, an intentional Easter-egg on the Forum - click on the Audacity logo and _**that**_ takes you to the Audacity website

**Comment by SteveDaulton** [comment]
I've fixed this from the ACP.
