### ISSUE TITLE
The Timeline moves asynchronously during playback

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2636]
**Describe the bug**
Watch the video:
https://user-images.githubusercontent.com/25851359/156878871-e49ce060-c75a-4d41-be9e-1829fe586dd4.mp4

**To Reproduce**
1. Switch the playhead into pinned mode
2. Run playback

**Expected behavior**
The timeline moves relatively synchronously with the waveform 

**Additional information (please complete the following information):**
 - OS: Win 10
 - Version: Audacity 3.2

**Comment by LWinterberg** [comment]
@crsib does it make sense to tackle this issue on its own or is this something that naturally falls out of your drawing performance work?

**Comment by crsib** [comment]
It's the way Audacity paints, so I would call it "won't fix"

**Comment by LWinterberg** [comment]
Alright, so a wontfix it is - with increased performance, neither of this will be visible
