### ISSUE TITLE
At default size stereo recording does not fit properly on the screen with 3.2.0 

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2651]
**Describe the bug**
At default size a stereo recording does not fit properly on the screen wuth latest 3.2.0 alpha master:  audacity-win-3.2.0-alpha-20220309+7abb499-x64-msvc2022

**To Reproduce**
1. purge the Audacity settings folder
2. launch Audacity
3. Press Record
4. Observe: **stereo track overfills the screen with trimming at the top**
5. Close Audacity
6. launch 3.1.3 (or earlier)
7. Press Record
8. Observe: the entire stereo track is visible on the screen

**Expected behavior**
The full stero track the be (height-wise) visible on screen at default bsettings

**Screenshots**
### 3.2.0 alpha
![image](https://user-images.githubusercontent.com/50205984/157414174-8445d34b-795f-4692-b596-597b1970955a.png)

### 3.1.3
![image](https://user-images.githubusercontent.com/50205984/157414381-ebf10743-64ff-49e5-b901-ba6879b7ed63.png)

**Additional information (please complete the following information):**
 - OS: Windows 11
 - Version:  audacity-win-3.2.0-alpha-20220309+7abb499-x64-msvc2022

**Additional context**
I suspect that this may be down to the new Effects button in the TCP - but I also note that the height of the two channels has been increased.

**Comment by petersampsonaudacity** [comment]
This does **_not_** happen if I import an audio file into 3.2.0 alpha

![image](https://user-images.githubusercontent.com/50205984/157415746-a64ae7e8-a606-4391-95b2-852d64d14e32.png)

**Comment by petersampsonaudacity** [comment]
> Could not reproduce on 3.2, Windows

I am in Zurich right now - so this is on my smaller HP Envy laptop with a 35cm 13 inch screen.

Compare the sizes of te height of the channels - have they increased from 2.1.3 to 3.2.0 ?

**Comment by Penikov** [comment]
I will try again with smaller screen

**Comment by petersampsonaudacity** [comment]
Also look at the height of the two channels - it looks to me as though they have been increased in 3.2.0 - in which case one has to ask:  for waht purpose?

**Comment by petersampsonaudacity** [comment]
> Could not reproduce on 3.2, Windows

I just tested this on my wife's even smaller 13 inch HP Pavillion - and I can't reproduce this with the latest 3.2.0 alpha master.

The **_BIG_** difference bewteen the two machines is that mine is now "upgraded" to Windows 11 - while hers (for now at least) remains on Windows 10 - so maybe it is an OS version issue ...

**Comment by petersampsonaudacity** [comment]
I then started to explore the Windows Display settings - I noticed that by default the scaling was set to 150% and stated as "Recommended".

I turned this down first to 100% which made everything too small (odd for a 100% setting I can't help thinking) - and then I settled on 125% as a good compromise for my scree sisize and my eyes:
![image](https://user-images.githubusercontent.com/50205984/157539437-d8d3330e-967f-44f8-86cb-1878f447d02f.png)

And now at 125% scaling the isue appears to have gone away - W11 on HP Probook 125% Display scaling:
![image](https://user-images.githubusercontent.com/50205984/157540043-f830af13-38f6-4042-ad24-20455099b9fe.png)


So it looks like this is an issue with the silly 150% default Display scaling I got on upgrading to W11 yesterday.  
So it looks like this is nit an Audacity issue - but something that support folk might like to take careful note of in order to be able to advise W11 users in the future,

**Comment by petersampsonaudacity** [comment]
Testing back in the UK with my bigger screen laptop with w10 and latest alpha master audacity-win-3.2.0-alpha-20220329+de34a21-x64-msvc2022

This does not happen on this PC so
a) this may be a Windows 11 issue
b) this may be a smaller screen issue.

I cannot test with W11 on this big-screen PC as Microsoft deems it unsuitable for W11 _(and it's only 5 years old!)_

**Comment by petersampsonaudacity** [comment]
Testing again in Zurich following several W11 updates since my last visit and using latest 3.2.0 alpha Master: audacity-win-3.2.0-alpha-20220603+ab8ed63-x64-msvc2022

This no longer occurs at the 125% scaling that I choose to use nor with the suggested Microsoft default of 150%.

Accordingly I shall close this issue
