### ISSUE TITLE
"An unrecoverable error has occurred during startup" MacOS Big Sur

### ISSUE THREAD

**Issue by mallardtheduck** [audacity/audacity#2656]
**Describe the bug**
When I try to launch Audacity (first time ever on this system), I get "An unrecoverable error has occurred during startup" and the application quits.

Using a debugger I was able to determine this happened because the server semaphore (used in AudacityApp::CreateSingleInstanceChecker, AudacityApp.cpp) had a value of "0" even though no other instance of Audacity was running. Using a tool to manually set this to "1" made Audacity work, but that doesn't explain how/why this happened. Since the semaphore ID is derived from "ftok", it's possible a collision occurred, apparently these are not that rare.

As an aside, line 1975 of AudacityApp.cpp calls "ftok" with an proj_id of 0, but according to POSIX "the behavior of ftok() is unspecified if these bits are 0". I doubt that's what's causing a problem here, but it's probably a good idea to fix it.

**To Reproduce**
Well, in my case, I just start the program... But there's probably something about my system that's causing this.

**Expected behavior**
The program should run, rather than quitting with this error.

**Screenshots**
N/A

**Additional information (please complete the following information):**
 - OS: MacOS Big Sur (11.6.1)
 - Version: Both version 3.1.3 downloaded from audacityteam.org and 3.2.0-alpha-20220309 built from source exhibit the issue.
 - (if relevant) Sound Device: Not relevant.

**Comment by Penikov** [comment]
Not a crash, but I have assigned that label as more appropriate.

**Comment by dozzzzer** [comment]
@mallardtheduck Could you please re-check if your problem persists in the latest version of Audacity?
