### ISSUE TITLE
Typo in "check updates" dialog

### ISSUE THREAD

**Issue by Penikov** [audacity/audacity#2681]
**Describe the bug**
![image](https://user-images.githubusercontent.com/25851359/158336980-d6dcb303-8194-4d0d-89dd-e452b55b3dc3.png)

Similar to https://github.com/audacity/audacity/issues/1933

**To Reproduce**
1. Switch Audacity to Russian
2. Open "Check updates dialog"

**Comment by Penikov** [comment]
Doesn't affect core functions, but looks messy.

**Comment by dozzzzer** [comment]
Not the case anymore in version 3.3.2:
![image](https://github.com/audacity/audacity/assets/70063970/27809123-1f99-4fd4-8b49-27b23a8176fb)
