### ISSUE TITLE
Add a linear-scale dB vertical ruler

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#2683]
Currently, there is an option between linear scale (from 1 to -1) and a fairly well-hidden logarithmic scale (from -0dB to -60dB by default). This causes confusion for beginners as they look at the waveform and peak at 0.5, thinking they're way too low - while in reality that's equivalent to -6dB, so already bordering the "red" area. 

Using the logarithmic dB scale by default comes with a set of problems on its own (see https://github.com/audacity/audacity/issues/2399#issuecomment-1009916140), so using it as default is not an option. 

However, using a linear dB scale is a well-established idea, using Audition as example: 
![image](https://user-images.githubusercontent.com/87814144/158396992-59a9c024-bc5f-4289-81b3-2edefa812680.png)

relevant files:
https://github.com/audacity/audacity/blob/master/src/widgets/Ruler.cpp
https://github.com/audacity/audacity/tree/master/src/tracks/playabletrack/wavetrack/ui

**Comment by SteveDaulton** [comment]
Yes please :)

**Comment by micpap25** [comment]
I'll work on resolving this issue today.

**Comment by micpap25** [comment]
I began working a little bit ago; this might take longer than expected given that the codebase is built on having exactly two types of scales for the Waveform Ruler.

**Comment by micpap25** [comment]
To add a linear db scale, I'm at least going to have to rename variables in the vast majority of the waveform-drawing functions throughout the code, so I'm going to wait for a response before I go ahead.

The code consistently makes the distinction as "This is either linear or decibel" and so I also don't want to move forward until I fully understand which behaviors a linear db scale should borrow from linear integer, and which it should borrow from logarithmic db.

**Comment by LWinterberg** [comment]
The waveform is identical to a linear waveform (ie Audacity's default, going from 1 to -1). The only thing that changes is the ruler on the side, which instead of eg {1, 0.5, 0, 0.5, 1} would read {0, -6, -inf, -6, 0}

**Comment by micpap25** [comment]
I appreciate the advice in regards to focusing on the Ruler class. I will try to minimize my changes to other classes; I still will have to add the option to select the linear decibel ruler, which is found in the Waveform parts of the code.

I've been busy last night and this morning; I'll do my best to complete this by Friday night.

**Comment by micpap25** [comment]
Status update: I've finished all the code for selecting the Linear (dB) ruler. I just need to create the ruler now. 
![image](https://user-images.githubusercontent.com/34077605/163632225-c731cd5d-5992-42d1-b9b7-bebe0db0a34d.png)
![image](https://user-images.githubusercontent.com/34077605/163632285-a4c8b11e-c81d-44e7-a305-058672fae659.png)

**Comment by micpap25** [comment]
As for the previously mentioned issue of the name of the `dB` variable in many places; I've left a comment next to one instance of that, and I'll open an issue after the PR gets merged. But it's not such a big deal that it would stop me from making the ruler.

**Comment by petersampsonaudacity** [comment]
Tested on W1- with branch build https://github.com/audacity/audacity/actions/runs/2176996124

This branch build looks good to me for this new view:

![image](https://user-images.githubusercontent.com/50205984/163708820-4d4a47ca-0e86-40b3-8821-e6d89a23552e.png)

**Comment by SteveDaulton** [comment]
This is a good start on a feature that imo is long overdue, though these tick marks don't make much sense:
![Screenshot_2022-04-17_11-48-48](https://user-images.githubusercontent.com/11681097/163711360-83a03a06-b4a2-4003-9262-dedc580e3c54.png)

**Comment by petersampsonaudacity** [comment]
And when you zoom out you see this odd fractional numbering in the scale

![image](https://user-images.githubusercontent.com/50205984/163712194-d78c74ff-8083-422e-a3b7-bebaf6e9d0bb.png)
