### ISSUE TITLE
Failed to find the system package vst3sdk

### ISSUE THREAD

**Issue by guiguidu60** [audacity/audacity#2693]
When compile Audacity on Fedora 35 & 36 pre-release, this error appears:
![audacity_bug_vst3sdk](https://user-images.githubusercontent.com/1296525/159110910-69d7a163-0d05-4f7b-86f1-e2ec671f6eaa.jpg)
This package is not available in the package manager, so...
It may be this package: https://github.com/steinbergmedia/vst3sdk
So I would have to compile the missing package myself ?
How to install it ?

**Comment by LWinterberg** [comment]
VST3 support is currently in development, you may want to try compiling without the VST3 flag in the meantime, or use the last release.

**Comment by crsib** [comment]
I don't think that VST3 support will be ever available with the system-packages-only build.

Please configure with `-Daudacity_has_vst3=Off`

**Comment by guiguidu60** [comment]
Ok, thanks.
