### ISSUE TITLE
Amplify fails to default offer amplification to 0db

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2700]
**Describe the bug**
Amplify fails to default offer amplification to 0db

This is a regression on 3.1.3 - and a regression on the previous alpha master that I have:
audacity-win-3.2.0-alpha-20220302+b7708d1-x64-msvc2022

**To Reproduce**
1. Purge the Audacity settings folder (to get OOTB factory settings)
2. Launch latest 3.2.0 alpha master
3. Generate default 30 minute chirp - default max amplitude 0.8
4. Effect > Amplify
5. **Observe: amplify offers to amplify by -  -0.915 dB**
6. Press OK to apply the effect at default setting
7. **Observe: the negative amplification is applied**

**Expected behavior**
On invoking Amplify the default amplification offered by the effect should be that which is required to raise the maximum signal level to 0dB _(i.e. maximum volume)_

**Screenshots**
### with the latest 3.2.0 alpha master
![image](https://user-images.githubusercontent.com/50205984/159270891-314d88de-5052-48ed-96ec-460725410e6f.png)

### With 3.1.3
![image](https://user-images.githubusercontent.com/50205984/159271409-6fb2a5b1-f934-4064-8a0a-a5fc8eac556c.png)

**Additional information (please complete the following information):**
 - OS: Windows 10 - but also reported on Linux by @SteveDaulton  - so assume all OS
 - Version: latest alpha 3,2,0 master - audacity-win-3.2.0-alpha-20220321+a994066-x64-msvc2022

**Additional context**
This makes it very hard almost impossible for the user to achieve full maximum volume 0dB with the Amplify effect.

See also:
Normalize OK button is grayed out (on first use) #2701

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest alpha master audacity-win-3.2.0-alpha-20220412+eb33420-x64-msvc2022

I confirm this is fixed  :-)

**Comment by Paul-Licameli** [comment]
The problems for Normalize and Amplify will not bisect to the same place.  The Amplify one is more recent.
