### ISSUE TITLE
Normalize (and Loudness Normalization) - OK & Preview buttons are grayed out (on invoking the effect)

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2701]
**Describe the bug**
When invoking the Normalize or the Loudness Normalization effects the OK button and the Preview button are both greyed out and the effect cannot be implemented on the selected audio.

This is a regression on 3.1.3 - and a regression on the previous alpha master that I have:
audacity-win-3.2.0-alpha-20220302+b7708d1-x64-msvc2022

**To Reproduce**
1. Purge the Audacity settings folder (to get OOTB factory settings)
2. Launch latest 3.2.0 alpha master
3. Generate default 30 minute chirp - default max amplitude 0.8
4. Effect > Normalize
5. **Observe: the OK button is grayed out - and so is the Preview button**
6. change the value in the peak amplitude box
7. Observe: now the OK button becomes un-grayed and available - and works

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/50205984/159274748-9c0351c0-74e6-4f82-9df0-dd6a445b23fe.png)

**Additional information (please complete the following information):**
 - OS: Windows 10 - but also reported on Linux by @SteveDaulton  - so assume all OS
 - Version: latest alpha 3,2,0 master - audacity-win-3.2.0-alpha-20220321+a994066-x64-msvc2022

**Additional context**
Simple workaround  - but does not look good to the user

See also:
Amplify fails to default offer amplification to 0db #2700

**Comment by petersampsonaudacity** [comment]
This also affects

### Loudness Normalization
![image](https://user-images.githubusercontent.com/50205984/159280108-4f4afe3f-79a6-4f9f-93c8-88dccce8d40c.png)

**Comment by LWinterberg** [comment]
I'll note that the "(Maximum 0dB)" disappears when you check any button, and also that the unit text (dB / LUFS - see screenshot above) gets cut off before you resize the window.

**Comment by LWinterberg** [comment]
this has persisted across the recent UI change, see #3495 for screenshots

**Comment by Paul-Licameli** [comment]
Bisects to 652588d268b3c4e7abea303a92d3943a9c1e0a0f -- same as for #3234

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest 3.2.0 alpha  -  

### Amplify is OK now
which also has the benefit for VI users that you can tab around properly
![image](https://user-images.githubusercontent.com/50205984/188272429-abff3b6a-0d8b-4235-8a5a-98911fb4a77c.png)


### Normalize and Loudness Normalization however still have the Preview button grayed out
![image](https://user-images.githubusercontent.com/50205984/188272523-3c6a64df-efb5-4601-ba54-e6ddf5ac2c60.png)

![image](https://user-images.githubusercontent.com/50205984/188272612-d0387d8f-5c0e-4a39-a05a-b161acda23b9.png)

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest 3.2.0 alpha - audacity-win-3.2.0-alpha-20220907+591f227-x64-msvc2022

@Paul-Licameli @LWinterberg @dozzzzer 

This now appears to be working correctly on Windows - in both effects the Preview and Apply buttons are no longer grayed-out and inaccessible when invoking the effect.

**Comment by SteveDaulton** [comment]
The "Preview" button is still greyed out in Loudness Normalization.
Tested with Commit Id: 18d277 on Xubuntu 20.04.

**Comment by Ryan-Miller-Audacity** [comment]
Tested and verified fixed in latest alpha branch.
