### ISSUE TITLE
Moonphase:  Corruption when resizing from partial screensize window to full screen-size on Windows 10

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2702]
**Describe the bug**
I occasionally get corruption when the Audacity window is redrawn at fill sreen size from partial screen size - but this is Moonphase and hard to reliably reproduce.

This is a regression on 3.1.3

**To Reproduce**
1. Purge the Audacity settings folder (to get OOTB factory settings)
2. Launch latest 3.2.0 alpha master
3. Generate get some audio
4. Resize Audacity window to full scree
5. Observe) sometime the redraw is corrupted - see screenshot
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/50205984/159281678-e27c6a2d-3321-4ff3-8c2b-2b210c8d7c89.png)

**Additional information (please complete the following information):**
 - OS: Windows 10 
 - Version: latest alpha 3,2,0 master - audacity-win-3.2.0-alpha-20220321+a994066-x64-msvc2022

**Additional context**
None

**Comment by LWinterberg** [comment]
this has never happened on my system and I haven't seen anyone else with this problem yet, so I'll close this as known issue. It'll probably go away with Qt anyway
