### ISSUE TITLE
With 3.2.0 the output signal is hotter than with 3.1.3 (distortion can occur)

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2703]
**Describe the bug**
With 3.2.0 the output signal is hotter than with 3.1.3 
Distortion can, and does, occur - and thus this is a regression on 3.1.3

For testing I used a known audio file _(well known to me and much-used for QA testing)_: 
- track 01 of Sgt Pepper, AAC file M4A/AAC 192 kbps as ripped from CD with iTunes

This never maxes out on playback with 3.1.3 or earlier but does do so with 3.2.0 - and is thus a regression on 3 1.3

**To Reproduce**
1. Launch 3.2.0
2. get some audio from a known file with sensible levels, say peaking at -2 to -3 dB
3. Play
4. Note the signal levels _(on the Playback meter)_
5. Launch 3.1.3
6. Import the same audio file
7. Play
8. **Observe: signal levels _(on the Playback meter)_ are higher and sound can be distorted**

**Expected behavior**
Output signal levels in 3.2.0 to be the same as in earlier Audacities

**Screenshots**
### 1) Sgt Pepper with 3.2.0
![image](https://user-images.githubusercontent.com/50205984/159302220-a0c84c73-5c55-4163-9ae9-b2f7e3ee69cd.png)

### 2) Sgt Pepper with 3.1.3
![image](https://user-images.githubusercontent.com/50205984/159302533-f3be112a-36b2-459e-a711-1db457b7e972.png)

### 3) amplify with 3.1.3 - this shows plenty of headroom
![image](https://user-images.githubusercontent.com/50205984/159303375-fa415e13-2032-416d-a54f-ad0e24736754.png)
This can't be tested right now on 3.2.0 due to issue #2700

**Additional information (please complete the following information):**
 - OS: Windows 10 -0 but @SteveDaulton  reports the same on Linux - so assume all OS
 - Version: Audacity 3.2.0
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]

**Additional context**
None

**Comment by petersampsonaudacity** [comment]
I just tried making a short recording from a known website (Gimme Country)
a) the recording peaked at -3db
b) playing back the recording the peak in the left channel maxes aout and overloads
![image](https://user-images.githubusercontent.com/50205984/159310479-5e892f55-60df-474b-8d5e-40ba3dee0bc6.png)

**Comment by petersampsonaudacity** [comment]
See:   Stereo tracks play too loud #3022 
for a good use case set of steps to reproduce this issue

**Comment by SteveDaulton** [comment]
I'd suggest closing this issue in favour of #3022 as I think the description there is a better match for what is happening.
