### ISSUE TITLE
Collapsed stereo tracks with double Clip-handle drag-bars display no audio

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2708]
**Describe the bug**
Collapsed stereo tracks with double Clip-handle drag-bars display no audio - only the two drag-bars.

This is technically a regression on 2.4.2 and earlier as
a) In 2.x there were no drag-bars so this issue did not occur
b) 2.x projects with stereo tracks when opened /imported in 3.1.3 (or 3.2.0 alpha) have stereo tracks each with two drag-bars, one per channel 

**To Reproduce**
1. Get some stereo track
2. Split the stereo track to split stereo or two mono tracks
3. rejoin the stereo track
4. **Observe:  the track now has not one but two Clip-handle drag-bars**
5. collapse the track
6. **Observe: no audio is visible only the two drag bars**

**Expected behavior**
Audio to be visible for collapsed stereo tracks, as was the case in earlier Audacity versions.

**Screenshots**
### Step 1
![image](https://user-images.githubusercontent.com/50205984/159479625-821f2548-6811-45d9-bd01-74c0f0485daa.png)

### Step 4
![image](https://user-images.githubusercontent.com/50205984/159479891-de03a68b-e78f-48ab-8f00-88fc41223d96.png)

### Step 6
![image](https://user-images.githubusercontent.com/50205984/159480080-0e5a861f-4dd4-477f-98bf-cde719567c37.png)

### Step 6 with Audacity 2.4.2
![image](https://user-images.githubusercontent.com/50205984/159480506-22c89189-3fb5-48f4-88e4-8ba9d4864046.png)

**Additional information (please complete the following information):**
 - OS: Windows 10 - but assume all
 - Version: Audacity 3.1.3 & 3.2.0 alpha
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]

**Additional context**
The symptoms of this when importing 2.4 projects into 3,x were originally reported with a confused Forum user:
https://forum.audacityteam.org/viewtopic.php?f=46&t=124445&p=448137
I will log this as a separate issue.

_Note that the double drag bar when joining stereo tracks was a "design decision" made and implemented at the creation of the Clip-Handle drag-bars,_

Flagging @Tantacrul as a UX/design issue

**Comment by petersampsonaudacity** [comment]
see #2618 (or duplicate #2709) for another use-case of how this may occur - opening/importing a 2.x project with stereo tracks in 3.x (whereby the user is "gifted" with two Clip_Handle drag-bars for each stereo track).

**Comment by LWinterberg** [comment]
closing in favor of #2722
