### ISSUE TITLE
Moving a clip from one colored instrument track to another doesn't recolor the clip

### ISSUE THREAD

**Issue by nekohayo** [audacity/audacity#2712]
With Audacity 3.1.3 (dark theme):

1. Import some audio
2. Create a second track
3. Split some of the audio into a clip and move it to the new track
4. Click the "Audio track" name/dropdown widget and set it to `Wave color > Instrument 3`; the track's contents turns green instead of orange
5. Split another clip portion out of the 1st (orange) track and drag it into track 2

Result: the clip dragged into track 2 (instrument 3) doesn't get recolored, it remains orange instead of green. Telling the track to set its  wave color to "Instrument 3" again recolors it, but I shouldn't have to do that manually, recoloring clips should happen as they move across tracks.

**Comment by petersampsonaudacity** [comment]
I recall that this behavior is a deliberate "design decision" much-discussed and then implemented at the time that @JamesCrook developed the different track colors.

**Comment by nekohayo** [comment]
> I recall that this behavior is a deliberate "design decision"

With all respect, the behavior seems contradictory with what the UI presents as an affordance. If it's a per-file/sample color, then I would expect the coloring to be done at the selection or clip interaction level (i.e. with right-clicking on a selection to change the color of the selected parts) rather than something at the track level presented in the track's menu; otherwise the natural resulting presumption is that the wave color is associated with the track itself, and that whatever moves across tracks inherits the "Wave Color" of the track (which is also what I've seen happen in other multitrack audio editing apps I've tested)...

**Comment by LWinterberg** [comment]
Aye. To elaborate on my earlier comment: Assigning colors to tracks is a thing that's somewhat common on audio editors, however, other than "it looks prettier", I have not yet found any use for it. Coloring clips however does have some use, eg to mark different kinds of content in a single track recording. 

As right-clicking in a waveform is an invention of 3.1 and right-clicking to do stuff with an entire clip won't be a thing until 3.3, my best guess would be that this was the sort of compromise to add all needed parts of the functionality without having to re-do major parts of the UI. 

Again, I think that this feature really is (and should be) a "set clip color" thing implemented somewhat weirdly, and that it should be set in a clip-level context menu. We'll look into whether that's within the scope of 3.3 (hence why #511 is targeted for that release right now) - if you feel like that'd be an acceptable resolution to this problem, feel free to close this issue.

**Comment by nekohayo** [comment]
I agree that this sounds like an acceptable solution. If I may, I would suggest you retitle issue #511 to "Allow changing waveform colors in clips and selection/samples, instead of tracks" for searchability and clarity of intent (because it was not clear for me by reading the existing title and description).
