### ISSUE TITLE
Improve color picker for clip colors

### ISSUE THREAD

**Issue by nekohayo** [audacity/audacity#2713]
If you click on the "Audio track" menubutton of a track, there is the "Wave Color" submenu that contains

* Instrument 1
* Instrument 2
* Instrument 3
* Instrument 4

However that is not terribly helpful because it involves a lot of trial and error, especially for those who use Audacity occasionally and haven't memorized everything. Instead, it should spell out the colors, like this for example:

* `Instrument 1 (blue)` in the light theme, and `Instrument 1 (orange)` in the dark theme, depending on the situation
* Instrument 2 (red)
* Instrument 3 (green)
* Instrument 4 (black)

...or maybe it doesn't even need the arbitrary notion of "instruments", and could just use the colors.

**Comment by LWinterberg** [comment]
Wouldn't it be better still to just show colored squares or otherwise an actual preview of how the clip in question would look like?

**Comment by nekohayo** [comment]
That could work too, but I suspect it would be much more complicated to implement than just adding a word to a text label... that said, if you folks want to go all fancy, I won't stop you there :smile:

If you mean a live preview _in the timeline, for real_ (while the mouse is over each menu item) rather than as an extra widget in that menu, then not only would this be cool, but it would also not be incompatible with being explicit in the menu items labels either, you could do both...

**Comment by LWinterberg** [comment]
> That could work too, but I suspect it would be much more complicated to implement than just changing the words in text labels... that said, if you folks want to go all fancy, I won't stop you there 😄

The short answer is that there currently are so many big improvements to be made across all areas that these kinds of micro-improvements will fall under the radar, for our team at least. What we're looking to do is no less than a complete overhaul of the entire app, both in a technological sense (VST3, real time effects, multi-threadedness, wxWidgets -> Qt, to name a few) and in a UX sense. For the UX, we want to strike a balance between moving to more modern controls while still keeping the app "feel" like the Audacity everyone loves, and to simplify the interactions while expanding the functionality. If you want to help out with this kind of more big-picture work, let me know, then I can tell you the long answer in a call or something :)

**Comment by LWinterberg** [comment]
as we'll only get to this post-4.x, I'm closing this for now
