### ISSUE TITLE
"Play/Stop and Set Cursor" shortcut doesn't work properly since Audacity 3.1.3

### ISSUE THREAD

**Issue by nekohayo** [audacity/audacity#2714]
In the keyboard shortcuts preferences, I have mapped "Spacebar" to "Play/stop and set cursor", which gave me a real play/pause workflow like I would expect (being used to Vegas, the video editor that started out as an audio editor). This used to work in Audacity 3.0, but apparently it broke it 3.1.3: now everytime I stop playback, the cursor gets reset to position 0 on the timeline when I press spacebar to play again, so I can never resume from where I actually stopped.

In comparison, the "Play/stop" shortcut still works, but that one requires me to set/move the playhead with the mouse all the time. I really want a true play/pause feature where the playhead stays at the last played position, like what "Play/stop and Set Cursor" did until now.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with 3.1.3 and the latest alpha test master build I have for the upcoming 3.2.0

This works fine foe me:

a) if I use the default "X" shortcut
b) if I reset that shortcut to be the spacebar

**Comment by nekohayo** [comment]
Huh, that's interesting, I would have thought it would be an internal bug rather than something else... I am running on Fedora Linux, on Xorg/X11. I originally tested with the [Flatpak version from Flathub](https://www.flathub.org/apps/details/org.audacityteam.Audacity), where the issue occured, then uninstalled it, tested the Fedora package from RPMfusion and the issue did not occur. Re-installed the flatpak version, tested it again and... it works.

I don't understand how it is possible that reinstalling it would solve it (since config files are persistent), but I guess since the symptom is suddenly gone that means it might be a heisenbug that is hard to trigger.
