### ISSUE TITLE
Feature request: Zoom mode that can center around the "editing cursor" instead of the mouse cursor

### ISSUE THREAD

**Issue by nekohayo** [audacity/audacity#2715]
Change the ctrl+scroll zoom behavior to not zoom on the mouse cursor but the edit cursor or playhead instead. Specifically:

- When not playing: Ctrl+scroll to Zoom in on selection, same as the zoom+/- buttons
- When playing with "update display while playing": Zoom in on playhead
- When playing with pinned playhead: Zoom in on playhead
- When playing without either option: Zoom on selection

<details>
<summary>Original report</summary>

When using the Ctrl+Scroll shortcut, Audacity zooms in/out based on the _mouse_ cursor position, rather than the "editing cursor" (thin vertical gray line) position when no region is selected.

The problem with the mouse-centric approach is that it is error-prone (the mouse may not always be at the exact position you marked with the ~playhead~ _editing_ cursor), and it also accumulates errors as you zoom in/out. It's a little bit hard to explain/conceptualize, but basically since the contents under the mouse shift depending on the zoom level, you "accumulate" precision errors,  especially if you zoom in/out repeatedly like I do.

An advantage of ~playhead~ "editing cursor"-anchored zooming is that it lets you quickly and confidently zoom "without looking/aiming", because you know the position of the mouse on the screen is not important when your ~playhead~ _editing cursor_ is set as an anchor for it. Another advantage is that it lets you zoom in/out at the very edges of the timeline, by using the Home/End key to slam the ~playhead~ _editing cursor_ against position 0 or the end of the timeline, and then zooming in/out at will without having to constantly readjust the horizontal scroll (which is a problem with mouse-centric zooming); it allows sticky zoom, essentially.

So I would really want an additional zoom feature/mode that clamps to the ~playhead~ _editing cursor;_ once you've tried "editing cursor"-centric zoom (like what was/is found in Vegas Pro), usually you never want to go back to the wobbly experience of "mouse cursor"-centric zoom. "Mouse cursor"-centric zoom is genuinely consistently disorientating to me (i.e. I literally keep losing "where I was at" because of it), especially since the zoom levels are discrete instead of smoothly continuous.
</details>

**Comment by nekohayo** [comment]
> a) Surely zoom is play-centric when Playback is actually occurring.

_Sort of._ I can see that it is buggy/jumping around the self-moving playback playhead, but I'm under the impression that it only _seems_ that way, but actually is still centered around the _mouse cursor's_ position and just so happens to re-set its scroll as the playhead moves. I realize now that what I referred to as the playhead was actually the set playback _cursor_ (sorry for the terminology confusion there!)...

> b) IF play is stopped there is no playhead, THEN zoom is cursor-focused (or selection-focused)
> c) IF Play is paused rather than stopped, THEN zoom is cursor focused (or selection focused)
> So would you want an option to change the c) behavior?

Thanks for the prompt for clarification. I would say B and C, based on the set cursor (vertical gray line, when there is no region selection); to me there is no distinction to be made between pausing and stopping when it comes to zooming.

That there is "no [visible, green] playhead" in situation B is a bit of theoretical construct, though I realize/remember now that there is the visual distinction between the "set position cursor" (gray line) vs active "playhead" (green line, that appears and disappears during playback or while "paused")... So nevermind the playhead, I was inaccurate in my terminology, sorry; what I meant was rather the _set cursor_ (vertical gray line) that happens when you click (without dragging) with the "Selection tool"; when there is no region selection, that vertical gray line cursor exists as a position in time (both in the UI and in the internals/backend) when you start/stop playback or set its position by clicking, and this is what I would like the zoom to center around when there is no active live playback going on: the "vertical gray line" cursor that occurs when clicking and no region is selected), rather than the _mouse cursor_ or the green playhead. In practice, it would be "clicking to set a zooming anchor point", so to speak.

-----

As a sidenote, it seems to me like Audacity having a standalone "pause" action that "isn't allowed to start playback when playback has not already been started" is a bit of a "theoretical, not super useful in practice" distinction compared to "Play/Stop and Set Cursor" (which, in its behavior, is closer to the functional equivalent of " _Play_ / Pause"). Would it be worth me filing a ticket about that specific part too?

**Comment by petersampsonaudacity** [comment]
But this is precisely what Audacity does do - it zooms focused on the existing editing cursor position or selection (a pint cursor position is effectively just a zero time length "selection".

I'm stretching my ageing brain to recall the long discussions that we (the old Audacity Team) had over where zoom focus should be.  I seem to recall that in early Audacity versions it may bell have had zoom focused on current _mouse cursor_ position and IIRC that was by consensus (eventually) thought not to be a good thing.  Hence the current behavior, which has been in place a fair time now.

### Update
Playing with this further it does indeed look to me that zooming with the mouse (hold down Ctrl and move the mouse-wheel backwards/forwards) does seem to zoom focuses on the mouse cursor position - which seems sensible to me if you are using the mouse to zoom.

In my earlier tests for zoom focus based on edit cursor/selection I was using the Zoom-in and Zoom-out shortcuts Crtl+1 and Ctrl+3.   I don;t normally encounter this as I tend to use the many magnifying glasses in the Edit toolbar for zooming.

**Comment by nekohayo** [comment]
I could definitely tell, even at a glance, that the current behavior is "mouse-cursor"-centric rather than "editing-cursor"-centric, indeed. When an app's zoom is centered around the editing cursor, you can really _feel_ it, it's hard to describe, it's a sort of "mechanical robustness" where your eye can trust the waveform or contract to expand _around_ the editing cursor and where your visual points of reference don't shift around, even if you are using peripheral vision; when done this way, things don't jitter and they're predictable, they're like fine clockwork. I think you've experienced this sort of accuracy using, as you've pointed out, the Ctrl+1 and Ctrl+2 shortcuts (which I'm used to seeing mapped to the Keypad Plus and Keypad Minus shortcuts, usually). I'd just like to be able to achieve that with the mousewheel too.

Zooming centered around the "editing cursor" * when using the mousewheel is what I've seen not only in Vegas (which started out as an audio editor originally) but also Avid Media Composer, Adobe After Effects, Adobe Premiere, and Final Cut Pro, if I recall correctly.

----

 *: as a sidenote, in many/most video editing applications, like the ones mentioned above, the "playhead" does double-duty as an editing cursor, hence my initial Audacity terminology mix-up when initially reporting this issue earlier above.

**Comment by LWinterberg** [comment]
closing in favor of #4212
