### ISSUE TITLE
Clean up top navigation bar

### ISSUE THREAD

**Issue by AnitaBats** [audacity/audacity#2716]
@LWinterberg could you please add a few words as a description for this task? 

@ksoze95 please contact @LWinterberg for designs and spec details

**Comment by LWinterberg** [comment]
![image](https://user-images.githubusercontent.com/87814144/159689812-16d1553b-6076-4923-88cc-445ce96a03a2.png)

Legend: 
* Delete stuff crossed out in red
* Hide stuff (=disable by default) crossed out in pink
* Move stuff as described by green 
* Optional: Move stuff as described by yellow.

**Comment by petersampsonaudacity** [comment]
### Upgrade from 3.1.3 to 3.2.0
There is an oddity if you upgrade from 3.1.3 (with the old toolbar layout and size) to 3.2.0.  The Window stays the old size with a very odd layout - and note that the Device toolbar still remains showing and is not hidden - and the Play-at-Speed toolbar remains in the top tooldock:
![image](https://user-images.githubusercontent.com/50205984/161114448-61e3e199-01dd-4aa9-aa2b-67d807bc91a1.png)

### After Reset Configuration
After doing a Reset configuration the new layout (sort of) obtains - but is cramped up as the new Window width is not implemented by the reset:
![image](https://user-images.githubusercontent.com/50205984/161115144-bf9012af-6fbc-413d-9c48-b22dd17a9947.png)


### Widen the window
If you then click&drag on the right to enlarge the window only then di you get the intended layout - the one you get with a virgin install of 3,2,0
![image](https://user-images.githubusercontent.com/50205984/161115575-1469dfff-33f6-4adf-9313-c020cf65957a.png)

**Comment by dozzzzer** [comment]
Re-opened. @ksoze95 please see the comment above.
In addition, please move **the playback meter toolbar** to the right as per @LWinterberg 's comment above:

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/70063970/161264415-e053a6c7-5e8b-49c9-a347-f88fe6fbe42c.png">

**Comment by LWinterberg** [comment]
playback meter was optional to this task and has been spun off into #2757

**Comment by petersampsonaudacity** [comment]
There is an underlying issue which maybe a separate issue in its own right:

**Tools > Reset Configuration** does **_not_** reset the Audacity window size to default size - perhaps it should,

Do we need a separate issue to be logged for this?

**Comment by dozzzzer** [comment]
> Do we need a separate issue to be logged for this?
I don't think that a separate issue is needed here as it can be fixed within this task.

@ksoze95 could you also take a look at the issue with not resizing Audacity Window to default and fix it within this task if possible?

**Comment by ksoze95** [comment]
@dozzzzer Will do

**Comment by petersampsonaudacity** [comment]
@ksoze95 

Testing on W10 with latest 3.2.0 alpha master   audacity-win-3.2.0-alpha-20220414+2a04bce-x64-msvc2022

some residuals remain

a) upgrading to 3.2.0 from 3.1.3 still gives the corrupt layout and the old 3.1.3 size

b) following a Reset Configuration in 3.2.0  the window size is correctly set to default _**BUT**_ the window location is not the default centre of screen positioning.  Rather the position of the reset size window appears to be based on where the top-left corner of the prior window was - this remains the top left position of the resized window.  This can result in awindow that is small and at bottom right being largely off-screen after the Reset Configuration:

### Before
![image](https://user-images.githubusercontent.com/50205984/163422343-cc7a340a-7e46-4670-8674-476141b70695.png)

### After Reset Configuration
![image](https://user-images.githubusercontent.com/50205984/163422429-b4627a3a-4ed5-4604-8811-893c168910c1.png)

**Comment by dozzzzer** [comment]
I confirm @petersampsonaudacity's comnent, after reset configuration the window's moved to the right bottom corner:
![image](https://user-images.githubusercontent.com/70063970/164019506-a175225f-ae7a-4d1b-808d-c315685425ba.png)

**Comment by LWinterberg** [comment]
This is out of scope for this task.

**Comment by LWinterberg** [comment]
If you want to make a P5 issue about it, feel free to.
