### ISSUE TITLE
Separate What's New dialog from the How to get Help dialog

### ISSUE THREAD

**Issue by AnitaBats** [audacity/audacity#2718]

**Comment by Tantacrul** [comment]
I think we should reset everyone's configuration by default and not provide an option. Otherwise people will just have a massively broken UI.

However, I do agree we should have a 'What's new' popup.

**Comment by LWinterberg** [comment]
Separating the What's new from how to get help would result in 3 popups occurring at first launch (update checking, whats new, how to get help). Given that we can just keep resetting the preference for this if we have something important to say (ie a new release video), I think the current way of doing things is acceptable until such time that a musescoreesque "home" tab manifests in 4.x

**Comment by Tantacrul** [comment]
Agreed.
