### ISSUE TITLE
Track name width insufficient ; show the track names in tooltips?

### ISSUE THREAD

**Issue by nekohayo** [audacity/audacity#2719]
If you set anything longer than "Audio track" as the name for a track, you basically can't read it because the track controls widgets area have a fixed width.

To alleviate this, two possible improvements (not mutually exclusive) could be done:

* Allow that area's width to be resizeable by the user (but that can only go so far when it comes to solving the problem...)
* Mention the full track name in the various tooltips when hovering the track controls's widgets, for example:
  * `Close` should be `Delete track "%s"`
  * `Open menu... (Shift+M)` should probably be `<b>%s</b>\nOpen menu... (Shift+M)`
  * `Mute (Shift+U)` should be `Mute <i>"%s"</i> (Shift+U)`
  * `Solo (Shift+S)` should be `Solo track <i>"%s"</i> (Shift+S)`
  * The general tooltip (when the mouse is over the empty areas of the track's controls area) should probably say: `Ctrl+Click to select or deselect track <i>"%s"</i>.\nDrag up or down to change track order.`
  * `Expand track <i>"%s"</i>` and `Collapse track <i>"%s"</i>`

The only other approach I can imagine is overlaying transparent text of the track name on the track waveforms background, but that would probably not work well and would surely be considered distracting by various users.

**Comment by LWinterberg** [comment]
> The only other approach I can imagine is overlaying transparent text of the track name on the track waveforms background, but that would probably not work well and would surely be considered distracting by various users.

this is the option that got implemented in `View > Track Name (on/off)`

**Comment by petersampsonaudacity** [comment]
The Track naming will be changing for the upcoming 3.2.0
![image](https://user-images.githubusercontent.com/50205984/159505012-65d7e892-f23d-4701-98b5-e935ad915ee3.png)


But apart from that there is already a mechanism to show the full track name as a transparent overlay.

Just go to Tracks Preferences and check "Show track name as overlay" to be "on"
