### ISSUE TITLE
Wrong playing state after playing generated tone

### ISSUE THREAD

**Issue by pietro68** [audacity/audacity#2721]
**Describe the bug**
Generate a tone then play it; when its end is reached, it looks as if the play state is still "playing" (as far as the play/stop buttons are concerned)

**To Reproduce**
1) Start Audacity, no project loaded
2) Generate | DTMF tones...  (or silence, noise - any kind of generation)
3) press OK, tone will be generated
4) press Play button, let the generated tone be played until the end

**Expected behavior**
the play state is stopped, i.e. the play button is not higlighted

**Actual behavior**
the play state is "playing", i.e. the play button is higlighted as if the clip is still being played, and one must press the stop button to make the highlight go away.

**Additional information:**
 - OS: [Windows 10]
 - Version: this happens on master branch, since at least commit ab7a1a9 (but possibly also earlier than that - I just stopped backtracking at that commit)

**Comment by LWinterberg** [comment]
may be fixed together with #2617
