### ISSUE TITLE
Linux: Journal recording failed

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2726]
**Describe the bug**
After enabling "Write Journal" in Tools menu and restarting, "Journal recording failed" error appears on play or record.

**To Reproduce**
1. Enable "Write journal"
2. Restart Audacity
3. Start recording
4. Observe error.
5. Observe zero byte journal.txt file

**Expected behavior**
A journal to be written.

**Screenshots**
![Screenshot_2022-03-24_22-08-20](https://user-images.githubusercontent.com/11681097/160018551-27e9fb77-de7d-483e-abac-605f7d26a8a3.png)

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version Audacity 3.2.0 6c64dc 
 - (if relevant) Sound Device 

**Additional context**

**Comment by Paul-Licameli** [comment]
Thanks for testing the journaling feature.  It is known to need much more work to be useful.

This replicates Issues #1591, #1592.  See this list of other known problems, mostly written by me.  https://github.com/audacity/audacity/issues?q=is%3Aissue+is%3Aopen+journal

**Comment by SteveDaulton** [comment]
Will this feature be disabled in the official Audacity 3.2.0 release?
