### ISSUE TITLE
attempting to locate FFMPEG is broken

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#2727]
STR:

1. Go to Preferences > Libraries
2. click the locate FFMPEG button
3. when asked whether you want to override the automatic detection, click yes
4. find the avformat DLL

![image](https://user-images.githubusercontent.com/87814144/160080514-4e58f6a3-49e8-465f-8e4e-ee2cb1f1a7bc.png)

OS: Windows 11
Regression on 3.1.3
Using 6c64dc455 - I have not attempted further bisection

**Comment by abcasada** [comment]
Workaround - install v3.0.5, then find the DLL, then reinstall latest version (3.1.3 as of now), and it should still have the FFmpeg library.

Other old versions may work also. Verified on Windows 10.

**Comment by abcasada** [comment]
Update to previous workaround - a few relaunches later, v3.1.3 failed to load FFmpeg. Going back to v3.0.5, FFmpeg is found again. Hopefully v3.0.5 won't lose it.

**Comment by patheticcockroach** [comment]
For me, ffmpeg doesn't work in 3.0.5 either. I'm stuck with version 2.4.2 for the moment. In 3.0.5 and 3.1.3, when I locate the DLL manually, Audacity just seems to ignore it.
Tried with both avformat-55.dll and avformat-59.dll, on Windows 10.

**Comment by crsib** [comment]
This will be fixed in 3.2

**Comment by crsib** [comment]
@Ryan-Miller-Audacity I think that you've verified this already. It should be fully fixed now, all the code required is in master

**Comment by dozzzzer** [comment]
Verified on Windows 10 x64

**Comment by Ryan-Miller-Audacity** [comment]
> @Ryan-Miller-Audacity I think that you've verified this already. It should be fully fixed now, all the code required is in master

I did check this with #3097 and double checked this again with the most recent master branch and verified it's working as expected.
