### ISSUE TITLE
CMake error occurs on Qt build with claims of missing lib dependencies on Arch

### ISSUE THREAD

**Issue by hpetrus** [audacity/audacity#2728]
**Describe the bug**
CMake error occurs on Qt build with claims of missing lib dependencies on Arch

**To Reproduce**
1. Turn on audacity_enable_experimental_qt_support in CMakeCache.txt
2. Hit configure
3. Errors are returned as follows:

```
ERROR: The following packages need to be installed:
 libxcb
libfontenc
libice
libsm
libxaw
libxcomposite
libxcursor
libxdamage
libxdmcp
libxft
libxtst
libxinerama
libxkbfile
libxrandr
libxres
libxss
libxvmc
xtrans
xcb-util-wm
xcb-util-image
xcb-util-keysyms
xcb-util-renderutil
libxxf86vm
libxv
xkeyboard-config
xcb-util
util-linux-libs

xorg/system: ERROR: while executing system_requirements(): Aborted due to CONAN_SYSREQUIRES_MODE=verify. Some system packages need to be installed
```

**Expected behavior**
I expect it to configure cleanly, but it does not.

**Additional information (please complete the following information):**
 - OS: Arch Linux 5.16.16-arch1-1
 - Version current Qt

**Comment by crsib** [comment]
This is highly experimental branch and it will take months to get the Qt MVP.

**Comment by hpetrus** [comment]
Ah!  I figured as much.  It's exciting to see, though.  This will likely solve a lot of the long-standing Audacity scaling issues on Plasma desktops.  Thanks for the reply.
