### ISSUE TITLE
Tabbing to labels in a Label track no longer updates the display to show the new selection or cursor position.

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2737]
**Describe the bug**
Tabbing to labels in a Label track no longer updates the display to show the new selection or cursor position.
This is a regression on 3.0.5.

When tabbing to labels

**To Reproduce**
1. Get a two minute (or so) song 
2. Zoom fit project to width  -  Ctrl+F
3. Add a few range labels and a point label (see screenshot 1)
4. Click in the Label track and Tab to select the first label
5. Observe: the temporal range of the first label is selected - BUT only in the Label track
6. Observe: the label itself is not selected _(was so in earlier Audacity versions)_
7. Repeat tabbing
**8. Observe: with a point label the visual cue is very minimal only a small thin black line in the timeline to indicate cursor position (see screenshot 1)**
9. Observe: the temporal range of each label is selected in turn
10.  Tab in the Label track to get the first label selected
11. Zoom out so only the first label is visible on screen
12. Tab in the Tab in the Label track to go to the next label to be selected
13. Observe: in the Selection toolbar the range has changed to the second label
14. **Observe: the on-screen view is not changed to show the second label  -   _(was so in earlier Audacity versions)_**

**Expected behavior**

**Screenshots**
### 1) Project at Zoom to fit
![image](https://user-images.githubusercontent.com/50205984/160292909-c1fbf7ee-5fb9-4a63-a972-a44fe3f33929.png)

### Step 8 - extreme minimal visual cue for a point label selected by tabbing
![image](https://user-images.githubusercontent.com/50205984/160293022-69fe0ac0-53d8-49d0-a209-cae4bc55382c.png)
A similar selection in the waveform would extend that little black line down through the waveform - a lot more obvious

### 3)  Steps 13 and 14
![image](https://user-images.githubusercontent.com/50205984/160292314-060ba049-5b29-44c9-b7ea-39fe466eaa0e.png)

**Additional information (please complete the following information):**
 - OS: all OS
 - Version: 3.1.3 and 3.2.0 alpha

**Additional context**
There are a number of regressions here:

1) Step 14 - in 3.0,5 and earlier the display was helpfully updated to move the tabbed-to label to be on-screen

2) Step 8 - in 3.0,5 and earlier the point label itself was selected (ready for text editing) giving a clearer visual cue

3) in 3.0.5 and earlier = all tabbed to labels were selected (ready for text editing)  -  making life easier for VI folk

4) In 2,4.2 and earlier not only was the temporal range of the label in the label track selected but also selected was the same temporal range in the wave track.
![image](https://user-images.githubusercontent.com/50205984/160292796-99c1214f-dfc9-425b-88b7-20ceb37d466b.png)

All 4 of these regressions make working with labels much harder than in previous Audacity versions in some cases especially so for VI folk.

Flagging @Tantacrul as a UX/design issue

**Comment by petersampsonaudacity** [comment]
My personal use case for this is the massive project I undertook to transcribe all my vinyl and tape _(and my wife's)_ to digibits.

1) I would record both sides of a an album 
2) I would drop temporary approximate (point) labels on song boundries
3) Export a backup WAV of the initial recording of the album
4) fine tune the label positions and content
5) manage the fades (in and out)
6) Various editing - click removal etc
7) Export WAVs and MP3s
8) backup the WAVS - 2 local and one remote USB disk
9) use the MP3s on my iPod(s) 0 and WAVS on my hi-fi "juke-box"

For steps 4 and 5 accessing each song in turn I look back and I'm **_jolly glad_** that I had the label behaviors that Audacity had back then rather than the current 3.1/3.2 behaviors.

**Comment by DavidBailes** [comment]
> There are a number of regressions here:
> 
> 1. Step 14 - in 3.0,5 and earlier the display was helpfully updated to move the tabbed-to label to be on-screen

This has been fixed in 3.2.0: https://github.com/audacity/audacity/issues/2078

> 3. in 3.0.5 and earlier = all tabbed to labels were selected (ready for text editing)  -  making life easier for VI folk

This didn't make life easier for VI folk, as the custom edit box is not accessible for users of screen readers (and can't be made so using the accessibility api which is used by wxWidgets. (There's an existing issue logged for using a dialog as an alternative: https://github.com/audacity/audacity/issues/1909 )

**Comment by petersampsonaudacity** [comment]
> > There are a number of regressions here:
> > 
> > 1. Step 14 - in 3.0,5 and earlier the display was helpfully updated to move the tabbed-to label to be on-screen
> 
> This has been fixed in 3.2.0: #2078

OOPS - and embarrassingly I note that I tested that fix as OK back in January _<blushes very deeply>_

**Comment by petersampsonaudacity** [comment]
> > There are a number of regressions here:
> > 
> > 1. Step 14 - in 3.0,5 and earlier the display was helpfully updated to move the tabbed-to label to be on-screen
> 
> This has been fixed in 3.2.0: #2078

Following @DavidBailes '  comment - and further testing on latest alpha master for 3,2.0 I shall close this as the bug as stated in the title of this issue definitely appears to be fixed for 3.2.0.

The other regressions remain 
a) no label selection for editing on tabbing
b) no corresponding selection in the waveform(s)
