### ISSUE TITLE
Multiview error when resizing 

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#2752]
Steps to reproduce:

1. Have a clip
2. Enable multi-view
3. resize the sub-views (eg make the spectrogram section smaller)

Error that shows up: 

![image](https://user-images.githubusercontent.com/87814144/161004679-5f50e9a8-89a3-4647-baa5-19dcb41d895f.png)

If you click "continue" on this error, it'll work as it should anyway. 

Windows 11, using 54c144722

**Comment by petersampsonaudacity** [comment]
I cannot replicate this on W1- with 3.1.3 or latest 3.2.0 alpha
