### ISSUE TITLE
Add support for vertical meters

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#2757]
spun off from #2716

**Comment by petersampsonaudacity** [comment]
I do hope that this does not mean _**only**_ vertical meters - but rather vertical meters added as a option

I, and I suspect many other users, would want to continue using horizontal meters - _I often like to spread my recording meter the whole window width,_

**Comment by LWinterberg** [comment]
> vertical meters added as a option

correct

**Comment by LWinterberg** [comment]
this isn't planned any time soon
