### ISSUE TITLE
Compressor effect loses settings between restarts

### ISSUE THREAD

**Issue by evertvorster** [audacity/audacity#2762]
**Describe the bug**
Built-in Compressor effect loses it's settings between restarts of Audacity.
Also, saved presets does not save the "Threshold" value

**To Reproduce**
1. Set up a the built-in compressor effect. 
2. Save the effect as a pre-set
4. Exit Audacity
5. Start Audacity again
6. Open the built-in Compressor effect.
7. Sometimes you get an error message stating that it could not load it's values, and it will be loading default values, sometimes it does not complain, but the "Threshold" value is zeroed out. 

**Expected behavior**
The effect to have the same settings as the last time it was used, same as all the other effects.

**Screenshots**
It's 100% repeatable on my system. 

**Additional information (please complete the following information):**
 - OS: [Arch Linux]
 - Version [Compiled from source, pulled from git master 2022-03-26]

**Additional context**
The other effects do not display this error, only this one.

**Comment by evertvorster** [comment]
Just pulled from git master now and recompiled. 
It is still the same.

**Comment by dozzzzer** [comment]
I was able to reproduce the issue on MacOS 11.6. In my case, I see an error message saying that it could not load its values, and it will be loading default values. 
Threshold and Noise Floor values are zeroed, the rest were reset too.

Build: [audacity-macOS-3.2.0-alpha-20220328+b02659a-universal](https://github.com/audacity/audacity/suites/5825460030/artifacts/195418137)

**Comment by JohnColket** [comment]
Bump.  This issue is still present on Alpha-1

**Comment by Ryan-Miller-Audacity** [comment]
Tested in latest Alpha branch and verified fixed.
