### ISSUE TITLE
Allow editing during playback

### ISSUE THREAD

**Issue by thebiblelover7** [audacity/audacity#2763]
**Is your feature request related to a problem? Please describe.**
My podcast that I edit has a lot of breaths and spaces between sentences and I would like to cut them out while I'm listening. e.g. I am playing at minute 3:15 and editing a gap that is at minute 3:45.

**Describe the solution you'd like**
My proposed solution is to allow edits to be done during playback. I don't know if the libraries used allow such a thing, but I think it is a vital feature for anyone editing podcasts.

**Describe alternatives you've considered**
I have considered switching to Adobe Audition, but the thought of non-FOSS software keeps me trying to find a way to make Audacity work.

**Comment by LWinterberg** [comment]
Fwiw: There is a Truncate Silence effect which lets you automatically remove spaces

**Comment by thebiblelover7** [comment]
@LWinterberg That's cool, will definitely check it out. Still I would prefer to be able to edit levels of audio, etc. manually during playback.

**Comment by LWinterberg** [comment]
Aye. This is a valid feature request, just pointing out a tool for your specific use case :)

**Comment by Paul-Licameli** [comment]
You want to “edit levels of audio.”  I think you want automation curves perhaps.

Allowing editing of the project in full generality seems too difficult.

**Comment by thebiblelover7** [comment]
@Paul-Licameli Yes, it does seem a bit more complicated to implement. Maybe just cutting parts of a track? For example, being able to cut out some mistake I notice ahead of when I listen to it will definitely quicken my workflow :smiley:.

**Comment by LWinterberg** [comment]
closing for now - there are no concrete plans to work on this any time soon
