### ISSUE TITLE
Playback does not stop automatically

### ISSUE THREAD

**Issue by evertvorster** [audacity/audacity#2770]
**Describe the bug**
In some situations, playback does not stop automatically. This causes the effects and undo history to be greyed out, among other things usually not allowed to happen while playback is in progress. 
This happens only if the selection goes beyond the audio clip's end.

**To Reproduce**
1. Select audio, and be sure to include select some audio after the end of the recorded audio. 
2. Click on "Play" button. 
3. Let the audio playback reach the end of the clip. 
4. Wait for a while, until the playback would have reached the end of the selection, too. 
5. Try to apply an effect, or undo the last action.

**Actual behavior**
The UI appears as if playback of the clip has not stopped. 

**Expected behavior**
The playback to stop automatically either on the end of the actual recording, or end of the selection... it's gotta stop somewhere!

**Screenshots**
If applicable, add screenshots/video to help explain your problem.

**Additional information (please complete the following information):**
 - OS: Arch Linux
 - Version: Built from sources pulled from git master on 2022-04-05
 - Using KDE desktop

**Additional context**
The editing is done on a single stereo audio clip, recorded through kdenlive, and imported into audacity on opening.

**Comment by petersampsonaudacity** [comment]
I cannot reproduce this on W10 with 3.1.3 or the latest master alpha test build I have for the upcoming 3.2.0 audacity-win-3.2.0-alpha-20220405+793cd28-x64-msvc2022

**Comment by evertvorster** [comment]
I just pulled another copy from git today, and now it seems fixed, must have been a transient issue. I'll close the ticket.

**Comment by LWinterberg** [comment]
fwiw, #2721 may be related
