### ISSUE TITLE
Volume Level Controller Issue

### ISSUE THREAD

**Issue by omiazad** [audacity/audacity#2784]
Since Audacity 3.1.x I found the volume level controllers are not controlling system volume.

Take a look at this image -
[https://pasteboard.co/JYQMNvkg6RBg.png](url)
This is microphone volume control. If you change the level on the right, which is in Audacity. It do not effect the system level on left. So while recording, if you change the level, nothing happens. The level change do not impact with the input range. You have to find and go to system controls and control your input range. 

Also take a look at this image -
[https://pasteboard.co/EvrOSPkTpA6j.png](url)
This is speaker volume. If you change the level on the right, it do not effect the system level on left.

It worked fine on older versions.

**Comment by omiazad** [comment]
> The speaker volume is intentional - https://wiki.audacityteam.org/wiki/Release_Notes_3.1
> 
> > The main volume controls no longer change the system volume.
> 
> The mic volume should be synced with the system though.

Unfortunately neither Mic nor Speaker works with System levels. See, people like me who is using this application since last 10 years are not happy to change anything. Graphic EQ change was a big shock for us.

They could just put an option to let us use the level controllers independently or with system. It should not be that hard I assume.

**Comment by dozzzzer** [comment]
Couldn't reproduce this one. For me mic input level in Audacity is in sync with the system mic level; latest master build on Win 10 machine.
![image](https://user-images.githubusercontent.com/70063970/163363760-2171a457-fdb6-4ecd-911a-51391250bed4.png)

**Comment by crsib** [comment]
There could be issues with some devices on some hosts. but generally input level affects the system input level as well.

**Comment by omiazad** [comment]
OK,
I did some more investigation and found this.

I have multiple mics.
![image](https://user-images.githubusercontent.com/3358147/163480302-179a3876-4a5e-4adb-9d96-2c34e0184d2a.png)

When I change mic volume, it changes the level of Logitech Brio,
![image](https://user-images.githubusercontent.com/3358147/163480657-382fa863-c86b-41cd-b8b0-df273f291b05.png)

But if you look here:
![image](https://user-images.githubusercontent.com/3358147/163480356-1674f9bc-2128-416e-8409-a0ab5eb20d7a.png)
You can see that the Logitech mic is not selected as input in Audacity.

When I disable the Logitech hardware, Then it controls the Sennheiser Handmic.

I believe the bug is more clear now for you to fix. 🙂

By the way, I am on Windows 10 and using audacity-win-3.1.3-64bit
