### ISSUE TITLE
Reset Configuration ( and Reset Toolbars) fail to reset Tools toolbar to the default I-beam Selection tool

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2793]
**Describe the bug**
Using **Tools >Reset Configuration** fails to reset Tools toolbar to the default **I-beam** Selection tool.

Also using **View > Toolbars > Reset Toolbars** similar fails to restore the default **I-beam** Selection tool.

This is a regression on 3.0.5 introduced in the development of 3.1.0

The Manual clearly states that this should be the case:
1) https://manual.audacityteam.org/man/reset_configuration.html
2) https://manual.audacityteam.org/man/view_menu_toolbars.html

**To Reproduce**
1. Launch 3.2.1 or 3.2.0 alpha
2. change the tool in Tools toolbar to any tool other that the I-beam Selection tool
3. Tools > Reset Configuration ( or View > Toolbars > Reset Toolbars)
4. Observe: the Tools toolbar is not reset to the I-beam selection tool

**Actual behavior**
Tools toolbar is **_not_** reset to the **I-beam** selection tool on using Reset Configuration or Reset Toolbars

**Expected behavior**
Tools toolbar **_should_** be reset to the **I-beam** selection tool on using Reset Configuration or Reset Toolbars.

This was the case in Audacity 3.0.5 and earlier

**Screenshots**
![image](https://user-images.githubusercontent.com/50205984/162617529-06c8bf97-afae-4fbc-b9de-da1e41e77fe2.png)

**Additional information (please complete the following information):**
 - OS: W10 but  assume all OS
 - Version 3.1.3 and 3.2.0 alpha master

**Additional context**
This is a UX issue _(flagging @Tantacrul )_ as amongst other things the Reset Configuration command designed to help confused users get dug out from the bear-trap of being in the wrong tool and not how to get back to selection.

**Comment by petersampsonaudacity** [comment]
@crsib @LWinterberg @dozzzzer @Tantacrul 

Bump:  any chance this can be fixed for 3.2.0 please?

A common bear-trap that folk fall into is to accidentally switch the tool and then not know now to revert to the Selection tool.

**Comment by Tantacrul** [comment]
I think it's one we'd like to fix if we've time, although I suspect the impact of this would be quite minimal. If someone has selected a different mode and didn't realise, then they're still going to encounter this problem.

In a release coming soon, we're going to essentially turn on the multi-tool by default and remove both the Draw tool button and the Multi-tool button. The envelope tool will then be an on/off switch which will effectively remove all the modes.

In case it needs saying, we won't be removing any functionality!

**Comment by petersampsonaudacity** [comment]
Still the case on W10 with 3-2-0 Beta

**Comment by Tantacrul** [comment]
Yes - we're not tackling this for 3.2. In fact, rather than fixing this issue we're going to instead very soon just remove the modes once and for all.

**Comment by LWinterberg** [comment]
wontfix as the modes are going away soon
