### ISSUE TITLE
Non-display track properties moved into ChannelGroupData: selection state, name, gain, pan, mute, and solo

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#2804]
Internal representations election state, name, gain, pan, mute, and solo reimplemented.

QA:  test the modifying of all of those, and behavior when splitting and joining stereo tracks, and undoing and redoing.

Note that Mute and Solo are properties of MIDI as well as audio tracks.

**Comment by Ryan-Miller-Audacity** [comment]
Tested and confirmed good behaviors of various states of name, gain, pan, mute, and solo including modifying each, undoing/redoing, splitting/joining stereo tracks etc. Specific checks are listed in the summary of the PR.

Testing of this PR resulted in the discovery of an issue introduced by this Pull Request that was fixed and tested after merge in a new build: 

1. **(FIXED)** Gan and Pan sliders do not allow for free placement along the slider bar. They tend to stick to various positions and do not allow further movement (Gain sticks to 0.0 and Pan like to stay 100% right).

Testing was completed within Windows, and brief checks were completed within MacOS, and Linux distro.
