### ISSUE TITLE
New plugins don't get enabled automatically

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#2810]
**Describe the bug**
When new plugins are found, they are set to "New" status, not "Enabled"

**To Reproduce**

1. Run Audacity with clean config
2. After plug-in scan is finished, go to Plug-in Manager
3. Check the statuses set to the new plug-ins

**Actual behavior**
The new plug-ins are in "New" status and aren't plresent under "Effect" menu

**Expected behavior**
The new plug-ins are in "Enabled" status and are plresent under "Effect" menu

**Additional information (please complete the following information):**
 - OS: Win10 x64
 - Version: [audacity-win-3.2.0-alpha-20220411+3cc8dd9-x64-msvc2022](https://github.com/audacity/audacity/suites/6075123286/artifacts/210202710)

**Comment by petersampsonaudacity** [comment]
I would urge caution with this ...

The user may want to have a large set of plug-ins downloaded (in my case Chris Cannam's Queen Mary Vamp plug-ins) but only have one of two of them actually showing in the Effect menus (i.e. "enabled") at any particular time.

Maybe the user should be offered the option of auto-enabling.

 Flagging @LWinterberg  this as a UX issue to be considered

**Comment by Paul-Licameli** [comment]
The swh package of ladspa plugins numbers 96

**Comment by LWinterberg** [comment]
I can only get 82 to show up in the effect menu, but yes. They'd be under a single entry, `Steve Harris <steve@plugin.org.uk>`, so if you don't want to use any of swh's plugins, they also don't get in your way. 

![image](https://user-images.githubusercontent.com/87814144/163030566-39ee0db5-edef-40d6-bf27-111597fae572.png)

Incidentally, if you only need like 7 of swh's plugins, the trip to the plugin manager to disable the unwanted ones is about as long as going to the plugin manager and only enabling these 7 plugins from the list.

**Comment by SteveDaulton** [comment]
I hope that a fresh install of Audacity will **not** automatically install all plug-ins. Like many musicians, I have a lot of plug-ins that I use in other apps that I would not want to be installed in Audacity. There may even be some that crash Audacity if installed (I've not checked lately, but I recall that some of the old LADSPA plug-ins could crash Audacity).

**Comment by Paul-Licameli** [comment]
@LWinterberg where did you obtain the swh ladspa plug-ins?  Your own build from source, or the download from the “old versions” tab of our Fosshub page?

@JamesCrook do you know when those binaries were last updated?

**Comment by Paul-Licameli** [comment]
I have been suggesting that we make updated binaries available.  The MacOS ones won’t work any more in recent operating system versions, and the Windows are only in 32 bit.

I don’t think there is any licensing obstacle for us to host builds of this other open source repo.  Maybe we should tell Steve Harris as a courtesy.

Maybe we might also make binaries of the lv2 versions of the swh plug-ins available too.

ladspa allows multiple plug-ins to exist in one dynamically loaded library, but swh isn’t set up to do that and instead makes dozens of little libraries, one for each effect.  Would there be any advantage in figuring out how to package all of swh in fewer binaries?

**Comment by Paul-Licameli** [comment]
As I mentioned to @Tantacrul , the sc4 compressor used to be packaged with Audacity.  I don’t recall why we decided to discontinue that.  Martin tells me the same sc4 was also once packaged with MuseScore too.

**Comment by Paul-Licameli** [comment]
Did you observe the bug in recent builds that Ladspa effects crash when you apply them ?  My recent pr will fix that.

**Comment by JamesCrook** [comment]
> @LWinterberg where did you obtain the swh ladspa plug-ins? Your own build from source, or the download from the “old versions” tab of our Fosshub page?
> 
> @JamesCrook do you know when those binaries were last updated?
No I don't.

**Comment by dozzzzer** [comment]
Verified
