### ISSUE TITLE
Following a Reset Configuration the fields for Mic, Channels and Speaker are shown blank

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2814]
**Describe the bug**
Following a Reset Configuration the fields for **Mic** input, no. of **Channels** and **Speake**r output are shown blank - but checking in Devices preferences shows that the reset to default settings has been made (just not displayed).

This is a regression on 3.1.3

**To Reproduce**
1. purge the Audacity settings folder (for OOTB factory settings)
2. Launch 3.2.0
3. View>Toolbars and select the Device toolbar  - (now hidden by default in 3.2.0)_
4. Observe: Device toolbar is properly populated
5. Tools > Reset Configuration
6. View>Toolbars and select the Device toolbar
7. **Observe: blank fields in the Device toolbar**
8. Edit > Preferences > Devices
9. Observe the relevant fields are populated properly here

**Actual behavior**
Blank fields in the Device Toolbar after a Reset Configuration command.

**Expected behavior**
Properly populated fields in the Device Toolbar after a Reset Configuration command.

**Screenshots**
### Step 4 - fully populated Device toolbar
![image](https://user-images.githubusercontent.com/50205984/162980078-fa5fb620-c9e7-45b7-be81-42e10021efca.png)

### Step 7 - blank fields
![image](https://user-images.githubusercontent.com/50205984/162980523-03f7e72c-560f-4482-9284-b93b8c292733.png)

### Step 9 - But OK in preferences
![image](https://user-images.githubusercontent.com/50205984/162981182-9998076f-316c-493f-86ba-4f5dfbfe1622.png)

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version [e.g. Audacity 3.2.0 latest master alpha audacity-win-3.2.0-alpha-20220412+17bfc14-x64-msvc2022

**Additional context**
Also does this in @ksoze95 's latest branch build 
https://github.com/audacity/audacity/actions/runs/2154616436

_Note that many/most users will be unlikely to see this bug now that in 3.2.0 the Device toolbar is hidden by default._

See also #2793

**Comment by petersampsonaudacity** [comment]
Note that **View > Toolbars >Reset Toolbars** does **_NOT_** appear to exhibit this behavior.

Note that the Device toolbar does get hidden by the use of this command - _and that is intended behavior_

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest alpha master audacity-win-3.2.0-alpha-20220616+00bdba3-x64-msvc2022

This is no longer the case - no idea what fixed it, but it appears to be fixed.

Discovered while testing @ksoze95 Kit's new Audio Settings stuff now that it's in master

**Comment by petersampsonaudacity** [comment]
BUMP - @LWinterberg @dozzzzer 

I think this can be closed - it works fine for me on W10 with latest 3.2.0 alpha - audacity-win-3.2.0-alpha-20220830+14f4922-x64-msvc2022

And it worked fine for me on my W11 Zurich PC when I was there recently.

**Comment by LWinterberg** [comment]
works for me
