### ISSUE TITLE
Limiter for Loudness Normalization

### ISSUE THREAD

**Issue by audacitymike** [audacity/audacity#2823]
**Is your feature request related to a problem? Please describe.**
It's easy to get clipped audio when running Loudness Normalization, depending on the level of the original audio for spoken word. 

**Describe the solution you'd like**
A built-in limiter in the Loudness Normalization screen could eliminate any clipping and conform to the LUFS standards for peak audio.

**Describe alternatives you've considered**
Applying the Limiter after doing Loudness Normalization doesn't always correct the distortion that occurred during Loudness Normalization.

**Comment by SteveDaulton** [comment]
> Applying the Limiter after doing Loudness Normalization doesn't always correct the distortion that occurred during Loudness Normalization.

It does for me.
Can you give steps to reproduce that bug?

**Comment by LWinterberg** [comment]
rereading this issue, it probably has to do with 16 bit recordings distorting when clipping. Using 32-bit float (the default) prevents clipping artefacts for all intents and purposes during editing/processing steps.
