### ISSUE TITLE
Reverb effect preview of stereo track is played through one channel only

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#2836]
**Describe the bug**
When playing a preview of the Reverb effect, it plays only through one channel.

**To Reproduce**
1. Select a region in a stereo audio clip
2. Go to Effect > Reverb
3. Click Preview

**Actual behavior**
The preview is played through one channel only (left in my case)

**Expected behavior**
The preview is played through both left and right channels.

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version: [audacity-win-3.2.0-alpha-20220419+cf11077-x64-msvc2022](https://github.com/audacity/audacity/suites/6172809599/artifacts/216577262) 
 
Update from @Paul-Licameli 
Steps to reproduce won't work at commit 8a7fbf5cc9b50ed973b0eff167dd9402c63a0534, but I claim the bug was only hidden (by the change of Reverb to realtime capable), and was fixed at the next commit 41d501eca7daa6c7b80f6dc52eb7ec63e90368cd.  

Do this:
- Generate a mono chirp
- Duplicate the track
- Make stereo track
- Mix and Render
- Select all
- Open Reverb and Apply, destructively (don't play preview)

Observe before the fix:  right channel of result is silent (like what originally happened generating preview)
After:  right channel is non-silent

Some explanation:  Destructive effect preview makes temporary hidden tracks to play, and shares code with Mix and Render. The bug in that produced a track in an unexpected state, wherein, the Reverb effect would misbehave like this.

Further inspection shows Reverb is the only effect that would be affected by the bug.  It involved the `chanMap` in `EffectReverb::Instance::InstanceInit` having incorect values.

**Comment by Paul-Licameli** [comment]
Does the misbehavior exist in version 3.1?

**Comment by dozzzzer** [comment]
@Paul-Licameli no, works well on 3.1.3 release build

**Comment by Paul-Licameli** [comment]
I observe that the bug does not reproduce when you have a mono track.  Selected material must be stereo.  I edited the description.

**Comment by Paul-Licameli** [comment]
You might assign only P4 to this, but I want to fix it promptly as it indicates I did something wrong recently in an important part of effects processing.

**Comment by Paul-Licameli** [comment]
I know more about this bug:

It had a common cause with #2898, but was indeed very specific to the Reverb feature, not other features.

Before the fix for #2898, this bug with preview of Reverb was hidden -- because of the change of Reverb to realtime capability.  So the bug was latent, but not demonstrable in that build.

I think, though, that I can suggest alternative steps to reproduce.
