### ISSUE TITLE
Reduce much verbosity and repetition in AudioUnit code

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#2841]

**Comment by dozzzzer** [comment]
@Paul-Licameli I'm getting a crash when trying to open up an AU plug-in.
OS: MacOS Monterey
Version: [audacity-macOS-3.2.0-alpha-20220511+d54f67f-universal](https://github.com/audacity/audacity/suites/6466694314/artifacts/238943396)


https://user-images.githubusercontent.com/70063970/168112815-f2813f09-bd2d-49be-a8c7-272856319995.mp4

Crash Report:
[Audacity_dbgrpt-28294-20220512T173139.zip](https://github.com/audacity/audacity/files/8680557/Audacity_dbgrpt-28294-20220512T173139.zip)

AU Plugin used:
https://www.audiopluginsforfree.com/tdr-nova/

**Comment by dozzzzer** [comment]
> Did you enable your AU plug-ins in another build? I am failing to enable new AUs in master now.

Yes, I enabled them in an earlier version.
