### ISSUE TITLE
Add&Remove effects from the sidebar

### ISSUE THREAD

**Issue by AnitaBats** [audacity/audacity#2845]

**Comment by DavidBailes** [comment]
Is there a design specification for this which includes the keyboard user interaction?

**Comment by DavidBailes** [comment]
@LWinterberg : Is there a design specification for this which includes the keyboard user interaction?

**Comment by dozzzzer** [comment]
Reopened: a few issue were discovered

### **Issue 1: An effect called from sidebar UI doesn't apply if playback is stopped.**

STR:

- generate a track/load an audio clip
- click [Add Effects]
- select an effect
- play the clip

Actual result: no changes to the audio (see the video attachment); the effect applies _only_ when selected during playback
Expected result: the audio is changed according to a selected effect

https://user-images.githubusercontent.com/70063970/170982832-0f286b69-a972-4948-99cc-0de95cb22079.mp4

### **Issue 2: Audio Unit modules of some plug-ins aren't populated to the list of effects in the stackable effects UI**

Compare: 3 instances (AU, VST, VST3) of the effect when called from 'Effect...' menu:
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/70063970/170983086-f31314c8-e094-4124-ba49-3b723a820aae.png">

vs only 2 instances of the same effect when called via stackable effects UI:
<img width="412" alt="image" src="https://user-images.githubusercontent.com/70063970/170983171-e636c348-bc0f-4a3c-8fad-2c20df9e7592.png">

**Comment by dozzzzer** [comment]
**### Issue 4 (minor): Hover state of the "Add new effect" button is missing**
<img width="269" alt="image" src="https://user-images.githubusercontent.com/70063970/171145417-d340a036-ccc3-46f7-9ebd-51b6d0a9760a.png">

**Comment by Paul-Licameli** [comment]
I think these various new problems could have separate new issue cards referred to by a checklist

**Comment by LWinterberg** [comment]
issues mentioned above have been split out to new bugs (3113~4), closing
