### ISSUE TITLE
User presets for generators do not save and restore duration

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#2848]
@petersampsonaudacity wrote:

> @Paul-Licameli @LWinterberg @dozzzzer Further testing on 3.1.3 shows that for all the other generators (Chirp,Noise, Silence, Tone, Pluck and Rhythm Track) the Duration **_is_** stored as part of a user preset and is properly restored when that preset is invoked.
> 
> Thus it is **_only_** DTMF that fails to store the duration - and thus this inconsistency really should be fixed. Do we need a new separate issue logged for this.

I find you are incorrect about the behavior of 3.1.3.  Exactly what I did with that version (which is following Pietro's steps):

- delete pluginsettings.cfg
- start Audacity
- open the Silence dialog (duration is its only control)
- Enter 10 in the control, Manage > Save Preset... , enter "ten", OK
- Enter 20 in the control, Manage > Save Preset... , enter "twenty", OK
- Manage > UserPresets > ten

Expected: control changes its value to 10
Observed: no change

- (Alternatively: reset to factory defaults, or Import effect settings that were previously Exported, also make no change when you expect they should)

So this problem with durations not saved in presets is a real problem, but not a regression in this development cycle.  I think it is an old problem never noticed before.

_Originally posted by @Paul-Licameli in https://github.com/audacity/audacity/issues/2822#issuecomment-1104551989_

**Comment by DavidBailes** [comment]
There may have been a reason why duration wasn't included in the presets. When using a generator to replace a selected region, you wouldn't want the duration to be changed when you chose a preset. See:
https://manual.audacityteam.org/man/generate_menu.html#Duration

**Comment by petersampsonaudacity** [comment]
> There may have been a reason why duration wasn't included in the presets. When using a generator to replace a selected region, you wouldn't want the duration to be changed when you chose a preset. 

A **_very_** good point @DavidBailes

**Comment by Paul-Licameli** [comment]
So there may be work to specify reasonable correct behavior.

If Silence has nothing but duration for its settings, and that should not be part of presets, then maybe it's silly to allow doing that in the Silence dialog.

But maybe duration as part of presets does make sense when selection has zero duration.

**Comment by SteveDaulton** [comment]
> So there may be work to specify reasonable correct behavior.

I thought the duration for generators was specified:

1. When there is a selection, the duration defaults to the length of the selection.
2. When there is not a selection, the duration defaults to the last used duration.
3. When there is no selection and no last used duration, the duration defaults to 30 seconds.

**Comment by Paul-Licameli** [comment]
> > So there may be work to specify reasonable correct behavior.
> 
> I thought the duration for generators was specified:
> 
> 1. When there is a selection, the duration defaults to the length of the selection.
> 2. When there is not a selection, the duration defaults to the last used duration.
> 3. When there is no selection and no last used duration, the duration defaults to 30 seconds.

Yes it behaves like that now, but some generators have a control that you can adjust, which is not saved and restored as part of a user preset.  Should it be?  If still no, then this is a nonissue.

**Comment by SteveDaulton** [comment]
> but some generators have a control that you can adjust, which is not saved and restored as part of a user preset.

Nyquist generators are a bit different because of GUI limitations, but I don't think that any of the built-in generators save the duration in presets (do they?). When testing, take care to ensure that there isn't a temporal selection.

**Comment by Paul-Licameli** [comment]
> > but some generators have a control that you can adjust, which is not saved and restored as part of a user preset.
> 
> Nyquist generators are a bit different because of GUI limitations, but I don't think that any of the built-in generators save the duration in presets (do they?). When testing, take care to ensure that there isn't a temporal selection.

Peter said they were saved and 3.2 regressed, but I retested and see it’s not a regression in fact.

**Comment by petersampsonaudacity** [comment]
> Peter said they were saved and 3.2 regressed, but I retested and see it’s not a regression in fact.

Sorry for starting this un-necessary hare running (I totally forgot the behavior protocols for generators that @SteveDaulton  has helpfully reminded us of).

BTW Silence is and odd one her as it enables user presets to be Saved and retrieved - but since the only datum it has is the duration, and that is not saved, any saved preset for Silence is specious.

**Comment by SteveDaulton** [comment]
> If still no, then this is a nonissue.

I think that this is a non-issue as it stands (and so can be closed), but it has raised some related issues:

1. Is the current specification optimal, or would it be better if duration was saved in presets?
* Note that such a change would break compatibility with existing macros
* Even if saved, I think we would definitely still want: "When there is a selection, the duration defaults to the length of the selection".
2. If the current specification is retained, then ideally, saving presets for Generate Silence should be disabled (there's nothing to save).
3. If possible, it would be nice if Nyquist plug-ins could have a duration control that behaves the same way as built-in plug-ins. Perhaps this could be done with the addition of a new `;duration` widget.

Personally, I'm happy for this to be left as it is. If changed, then I would see some benefit in the saved duration overriding the "default". Thus:
1. When there is a selection, the duration defaults to the length of the selection.
2. When there is not a selection, the duration defaults to the saved value.
3.  When there is no selection and no last used duration, the duration defaults to the saved value.
