### ISSUE TITLE
Broken grid in Filter Curve EQ effect on startup 

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#2853]
**Describe the bug**
When initialzied, Filter Curve EQ effect has weird green lines grid.

**To Reproduce**
1. Initialize Filter Curve EQ effect
2. Observe

**Actual behavior**
![image](https://user-images.githubusercontent.com/70063970/164737512-6a636a48-0024-422d-8b87-7b5f6653f9c2.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/70063970/164737715-667c75b3-fac0-4119-becc-6d6c62ac6375.png)

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Lates master build

**Additional context**
The issue is not easy to reproduce and initially observed by @crsib

**Comment by petersampsonaudacity** [comment]
Confirmed on W10 with latest alpha master for 3.2.0  audacity-win-3.2.0-alpha-20220422+74b333b-x64-msvc2022

But what I get varies - sometimes its the ,any green lines - and sometimes I get a coloured line at the top:
![image](https://user-images.githubusercontent.com/50205984/164755580-3bfb1839-01f8-4393-9fc6-9ee6e5a3e026.png)

**Comment by Paul-Licameli** [comment]
Problem bisects to my commit at f5d2ed042aa5f6080304b2ec6cee51ee4f705e08

Something must have become uninintialized there.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest alpha master:  audacity-win-3.2.0-alpha-20220707+e7a76b9-x64-msvc2022

I confirm this is now fixed on Windows

**Comment by dozzzzer** [comment]
Verified on MacOS Monterey:

<img width="921" alt="image" src="https://user-images.githubusercontent.com/70063970/177959261-62537bec-3efe-4a33-a4e9-5dad8010afe1.png">
