### ISSUE TITLE
Make WahWah effect stateless

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#2858]

**Comment by dozzzzer** [comment]
While testing the solution, several issues were observed.

- [ ] 1: Changing sliders' position/effect parameters doesn't affect the preview playback when using the WahWah effect <img width="350" alt="image" src="https://user-images.githubusercontent.com/70063970/166976560-1fadec20-0d42-43bd-91a5-23a3453bfded.png">
- [ ] 2: Start Playback label doesn't change to "Stop Playback" once pressed
- [ ] 3: Repeatedly clicking [Start Playback] doesn't cause the playback to stop
- [ ] 4: [Skip Backward] and [Skip Forward] buttons don't make any effect during the playback
