### ISSUE TITLE
When scrolling a track horizontally at the maximum zoom the values on the timeline are changing

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#2860]
**Describe the bug**
When a track is zoomed in and scrolled horizontally, time marker values on the timeline keep changing so it's hard to cut/edit using precise time values.

**To Reproduce**
1. Load an audio clip or add a blank mono track
2. Zoom in at maximum
3. While holding Shift key, scroll the mouse wheel up and down to see the values chaning

**Actual behavior**
The distance between the time markers on the timeline remains the same but the values are changing.
The sequence is changing from `1.371730, 1.371750` etc. to `1.371740, 1.371760` and then back to  `1.371730, 1.371750` and  `1.371740, 1.371760` as you keep scrolling the mouse wheel.
https://user-images.githubusercontent.com/70063970/165302150-7fb22ca5-430d-4ec1-be53-a30c0f738585.mp4

**Expected behavior**
The timeline values remain consistent.

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version Audacity 3.1.3

**Comment by petersampsonaudacity** [comment]
Testing on W10 I think that what you are seeing is correct behavior.

Holding shift and using the mouse wheel is supposed to (and does) give you horizontal scrolling of the waveform (which is what you are seeing)

Trey
1.  zoom in at maximum
2. click on one of the points to select it
3. now scroll slowly with the Shift modified mousewheel
4. Observe: the time ruler stays in sync with the selection

You can see it a bit more clearly if you zoom out a bit.

**Comment by dozzzzer** [comment]
@petersampsonaudacity the problem here isn't about holding Shift and using the mouse wheel giving horizontal scrolling of the waveform. It's about time markers display being inconsistent with mouse wheel scroll. I just want them to remain the same as I scroll through the waveform and not change on every other scroll move. Does it make sense to you?
The placement of the time values is correct though.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
