### ISSUE TITLE
Audacity hangs when monitoring is stopped

### ISSUE THREAD

**Issue by crsib** [audacity/audacity#2861]
**Describe the bug**

Audacity hangs when monitoring is stopped, or when record or play is pressed while monitoring

**To Reproduce bug #1 - at monitoring stop**
1. Start Audacity
2. Click on Input Meter Panel to start monitoring
3. Click on Input Meter Panel to stop monitoring

**To Reproduce bug #2 - at record pressed**
1. Start Audacity
2. Click on Input Meter Panel to start monitoring
3. Click on record

**To Reproduce bug #3 - at play pressed**
1. Start Audacity
2. have a track ready to play something
3. Click on Input Meter Panel to start monitoring
4. Click on play

**Actual behavior**
Audacity hangs

**Expected behavior**
Monitoring is stopped + Audacity does not hang

**Screenshots**
If applicable, add screenshots/video to help explain your problem.

**Additional information (please complete the following information):**
Happens in `master` branch

**Additional context**
Main thread waits for audio thread to stop in `AudioIoCallback::WaitForAudioThreadStopped()`

**Comment by pietro68** [comment]
This happens since commit `de00e9f` done by me, so I will take on the issue.

**Comment by petersampsonaudacity** [comment]
Confirmed on W10 with latest alpha master build.

This is a regression on 3.1.3

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @pietro68 latest branch audacity-win-3.2.0-alpha-20220428+8747f0d-x64-msvc2022 

This now no longer hangs Audacity with this branch build

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest alpha master audacity-win-3.2.0-alpha-20220503+ba1664f-x64-msvc2022

I confirm this is fixed on Windows

**Comment by dozzzzer** [comment]
Tested on Win10 and audacity-win-3.2.0-alpha-20220502+b3c2a0d-x64
