### ISSUE TITLE
After merging two mono tracks in one stereo track and swapping channels, the name of the track is changing too

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#2862]
**Describe the bug**
After merging two mono tracks in one stereo track and swapping channels, the names of the channels are changing.

**To Reproduce**
1. Create two mono tracks
2. Name them with "L" and "R" respectively
3. Merge them into one stereo track (the name of the track is set to "L" which is okay)
4. Swap channels of this track a few times and see how the name of the track is changing

**Actual behavior**
The name of the track changes from "L" to "R" continuously when swapping channels.

**Expected behavior**
The name of the stereo track remains the same when swapping channels

**Screenshots**
If applicable, add screenshots/video to help explain your problem.

https://user-images.githubusercontent.com/70063970/165522625-d59a8a7e-e55f-4470-8a34-4ed02d5c7f8d.mp4

**Additional information (please complete the following information):**
 - OS: Windows 10
 - latest master build

**Additional context**

**Comment by Paul-Licameli** [comment]
There are certain other properties associated with stereo tracks as a whole but the implementation involves a similar unfortunate duplication of storage in channels, which I want to fix.

Besides name, you might discover similar bugs involving differences of:
- Mute
- Solo
- Gains
- Pan
- Wave track color
- choice of view type (waveform, spectrogram, or split)
- the proportions of a split wave/spectrum view
- the top-to-bottom ordering of waveform and spectrum in split views

See also https://github.com/audacity/audacity/issues/2803

**Comment by dozzzzer** [comment]
Not reproducible anymore
