### ISSUE TITLE
Safety and correctness of effect stack edits while playing back

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#2871]
- [ ] #3027

Another question to ask is whether all these things requiring pushes and pops of the undo stack are safe to do while playback is in progress.

I think we surely want that -- one hope is that you listen as you change settings of a single effect, or even change the composition of the effect list.  But now I doubt whether all is set up correctly in the audio engine for that, both to avoid dangling pointers and crashes, and to communicate changes of the sequence of effects properly inter-thread.

The limited thing that I know was anticipated by Leland's work, is the powering on and off of individual effects, which is what the suspending and resuming of states is for.

And the point of the EffectSettingsAccess class I developed is to communicate changes of settings of an individual effect correctly -- what this piece of code here will do.

But adding, deleting, and permuting effects?  Or changing the whole stack at one with undo and redo?

I must think.

_Originally posted by @Paul-Licameli in https://github.com/audacity/audacity/pull/2867#discussion_r861433554_

**Comment by dozzzzer** [comment]
Tested on MacOS 12.3.1. and Windows 10.
