### ISSUE TITLE
"Show Timeline Tooltips" and "Show Scrub Ruler" preferences ignored

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2880]
**Describe the bug**
The option to not show Timeline Tooltips does not work

**To Reproduce**
1. Hover the pointer over the Timeline and observe that a tooltip appears
2. Disable the option: "Preferences > Interface > Show Timeline Tooltips"
3. Hover the pointer over the Timeline

**Actual behavior**
The tooltip still appears in step 3

**Expected behavior**
The tooltip to be disabled.

**Screenshots**
![tooltip](https://user-images.githubusercontent.com/11681097/166149800-26ed2a83-2514-429e-a032-6c541b0f4990.png)

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version Audacity 3.1.3 / 3.2.0
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]

**Additional context**

**Comment by petersampsonaudacity** [comment]
Confirmed on W10 with latest 3.2.0 alpha master

Additionally note that the other Timeline setting "Show Scrub Ruker" has no effect when turned on in Interface preferences

**Comment by LWinterberg** [comment]
@petersampsonaudacity 1) is https://github.com/audacity/audacity/issues/2869 and different to this - it displays the tooltip of the timeline options (the triangle) if you position the cursor outside audacity. 

(also - why is the "show timeline tooltips" even an option?)

**Comment by SteveDaulton** [comment]
> also - why is the "show timeline tooltips" even an option?

Because it can be annoying to have a tooltip popping up while setting loop regions or using Timeline Quick Play from precise time positions.

Previously it was also possible to disable Timeline tooltips from the Timeline context menu, which was more convenient and easier for users to discover.

**Comment by LWinterberg** [comment]
![image](https://user-images.githubusercontent.com/87814144/167077626-661d12ee-25e8-45f0-bf62-c4897e0d0af9.png)
the scrub ruler does show once you hover over it btw

**Comment by petersampsonaudacity** [comment]
the scrub ruler does show once you hover over it btw

Yes but in 3.2 0 it now obscures part of the Clip's drag-bar and clipname - and yo get odd little ticks in it:
![image](https://user-images.githubusercontent.com/50205984/167086028-29d66a96-1046-4908-a302-cf1239dc7d2f.png)


Whereas in 3.1.3 this was not the case:
a) the Scrub ruler was displayed all the time without hovering over the region where it should be
b) it does not overlap the Clip drag-bar
c) no tick marks
![image](https://user-images.githubusercontent.com/50205984/167086471-53f29f6b-b908-4cef-a724-e9266953e0eb.png)

**Comment by SteveDaulton** [comment]
> the scrub ruler does show once you hover over it btw

On Linux, the scrubbing ruler does not appear at all.

**Comment by petersampsonaudacity** [comment]
> > the scrub ruler does show once you hover over it btw
> 
> On Linux, the scrubbing ruler does not appear at all.

Nor do I see it on my Monterey Macbook Pro with 3.2.0 alpha

**Comment by dozzzzer** [comment]
`Nor do I see it on my macOS 13.3.1 Monterey Macbook Pro with 3.2.0 alpha`
I second that
