### ISSUE TITLE
Scroll page right and Scroll page left additional buttons

### ISSUE THREAD

**Issue by Vorvule** [audacity/audacity#2881]
I'm always frustrated when I scroll the waveform horizontally (both right and left) because:
* it trembles like a leave in the wind;
* and moves slowly enough.

I'd like to propose the following solution:
(in addition to the scroll right and scroll left arrow buttons) we could add two more:
* scroll right by page
* scroll left by page
which would move the waveform right and left respectively by one width of the screen.

Thus, we would avoid trembling of the waveform while moving left and right, and speed up the very process of scrolling.
If usual scrolling icons look like angles (chevrons), the page-scrolling icons could look like double angles (double chevrons):
https://icon-icons.com/icon/chevron-double-right/138767

**Comment by LWinterberg** [comment]
Why would you want a button instead of shift+scroll?

**Comment by Vorvule** [comment]
@LWinterberg Because one can't scroll a waveform by (whole) page using just shift+scroll.
Only by a couple of seconds.

**Comment by DavidBailes** [comment]
As an alternative you can scroll left/right by a page using the page up/down keys.

**Comment by Vorvule** [comment]
Thank you, @DavidBailes! I didn't know about this option. It's great!
