### ISSUE TITLE
Transport - Stop warning box displayed if previously already stopped

### ISSUE THREAD

**Issue by manyfew** [audacity/audacity#2882]
**Steps to reproduce:**
1. Go *Edit > Preferences... > Keyboard*, find *Transport - Stop* command and assign *S* key to it, then click *OK*.
2. Record something into Audacity, then position playback cursor at beginning of recording and click *Play* button to start playback.
3. Press S (assigned at a step 1) to stop playback.

**Expected result:** Playback stops.
**Observed result:** Same as expected (no problems here, though keep reading).

4. Immediately following step 3 (i.e. playback stopped), press *S* key again.

**Expected result:**: No action, since playback state was already stopped.
**Observed result:** Warning box is displayed:

![Warning message on stop](https://forum.audacityteam.org/download/file.php?id=35371&sid=58457f60a3c74189255a250037e888bf)

**System details:**
Windows 10 Pro 64-bit v20H2 (OS Build 19042.1586)
Audacity v3.1.3

**Additional context:**
This used to work correctly (i.e. no warning box) in earlier Audacity versions. I don't know exactly when it broke. It seems to have something to do with the fact that the GUI *Stop* button is grayed out (disabled) when stopped. When stopped, if I click the Stop button, nothing happens; likewise, Audacity should quietly ignore the *Transport - Stop* if issued while stopped. This is how other software and hardware recorders (including old tape recorders) intuitively work: If already stopped, pressing/clicking the Stop button results in no change of state.

**Comment by petersampsonaudacity** [comment]
This is indeed a regression bug - my testing on W10 shows it to be a regression on Audacity 2.1.3, introduced in Audacity 2.2.0

The menu structures were changed in 2..2.0 and the "Stop" command was moved to be an Extra menus command: Extra > Transport > Stop
![image](https://user-images.githubusercontent.com/50205984/166153568-2dbdab20-200b-4575-9196-d3b1848e562a.png)


The oddity is that if you try to use Extra > Transport > Stop when Audacity is not playing or recording you will observe that the menu command is grayed out and inoperable - so via the menu you can't get the error message. It's only with the sgotscut for that command that the error message can occur.

**Comment by petersampsonaudacity** [comment]
This was originally discussed on the Forum
https://forum.audacityteam.org/viewtopic.php?f=71&t=125293&p=450417

There @feidaman added this use case

> I have an AutoHotkey script with a macro that maps a key to the following sequence: Stop, Record. The goal of this macro is to enable me to start recording immediately with a single keypress, without having to worry about whether Audacity is already playing or recording. This removes the need to even look at the screen to start a recording. The problem with using Play/Pause instead of Stop is that the playback state of the former command depends on the initial state, but my script has no way to know the initial state so the macro doesn't work 50% of the time because Audacity refuses to record if it's already playing.
>
>IMO the warning message is unnecessary since on every single hardware and software recorder ever made the Stop button stops if playing, and (rather intuitively) does nothing if already stopped. The sole purpose of a Stop button is to stop, not to stop 50% of the time :D The warning box essentially renders the Stop command useless.

**Comment by feidaman** [comment]
Thank you @petersampsonaudacity for filling in the gaps, hopefully this one is not too hard to fix.

**Comment by dozzzzer** [comment]
Confirmed on MacOS 12.3.1 on latest alpha 3.2.0 build
<img width="567" alt="image" src="https://user-images.githubusercontent.com/70063970/167161364-e07b51a2-46f5-4742-b5d7-927e24d81eee.png">

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
