### ISSUE TITLE
On/off states of effects in stacks should be persistent

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#2892]
Save a project, close it, reopen it -- expect that the "power" buttons of individual effects should remain as they were.

(Should the same apply for the per-track, master on/off switch?)

**Comment by Ryan-Miller-Audacity** [comment]
Initial testing failed as On/off states of effect are not remaining persistent when saving, closing, and reopening projects. Statuses seem to be ignored and all effects (including master switch) are set to on regardless of previously changed/saved status.

**Comment by pietro68** [comment]
Confirmed fixed in `6d6b627`

**Comment by Ryan-Miller-Audacity** [comment]
Fully tested a few additional scenarios with no bugs found.
