### ISSUE TITLE
Both horizontal and vertical scroll bars are too narrow

### ISSUE THREAD

**Issue by kpranavk** [audacity/audacity#2894]
Both the horizontal and vertical scroll bars are too narrow. It just makes it hard to snap and move the mouse fast. Please widen the scroll bar a little bit more. It makes it even worse when Zoomed In a lot. Say I hit Zoom In 5 times, the scroll bar center piece shrinks so much that it is hard to snap

<p>Too narrow</p>
<img width="527" alt="too narrow" src="https://user-images.githubusercontent.com/13447573/166617032-1fd189d6-96e2-43ec-b461-30b02a3f4c69.png">

<p>Too tiny and small</p>
<img width="541" alt="too tiny and small" src="https://user-images.githubusercontent.com/13447573/166616837-83f1911f-4789-4b94-bd7b-b7b9c731c4d4.png">

**Comment by LWinterberg** [comment]
These are the system-native scrollbars. We cannot change them. You may want to use Shift+Scroll or the Page up/Page down keys to quickly scroll horizontally instead.
