### ISSUE TITLE
Wahwah effect issues

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#2896]
@pietro68 While testing the solution #2858, several issues were discovered.

- [ ] 1: Changing sliders' position/effect parameters doesn't affect the preview playback when using the WahWah effect <img width="400" alt="image" src="https://user-images.githubusercontent.com/70063970/166976930-ea91b69d-1be7-4f53-9c91-541e8a3e93ad.png">
- [ ] 2: [Start Playback] button label doesn't change to "_Stop_ Playback" once pressed
- [ ] 3: Repeatedly clicking [Start Playback] doesn't cause the playback to stop
- [ ] 4: [Skip Backward] and [Skip Forward] buttons don't make any effect during the playback

1. OS: MacOS, Win 10
2. Version: [audacity-win-3.2.0-alpha-20220428+b93116d](https://github.com/audacity/audacity/suites/6297752451/artifacts/225722069)

**Comment by petersampsonaudacity** [comment]
Testing on W10 wit latest alpha master audacity-win-3.2.0-alpha-20220505+f1b5865-x64-msvc2022

a) I confirm with with Wahwah

b) Bass and Treble is afflicted in the same way

**Comment by dozzzzer** [comment]
The issue cannot be reproduced anymore.

**Comment by petersampsonaudacity** [comment]
Confirmed OK on W10 with latest alpha master:  audacity-win-3.2.0-alpha-20220704+679d6b6-x64-msvc2022
