### ISSUE TITLE
Please Clarify Preferences Structure

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#2902]
The current structure of Preferences can be confusing to new (and experienced users).  Specifically, the tree structure 

Tracks
  |-- Tracks Behaviors
  |-- Spectrograms

suggests there are two pages of preferences for Track Behaviors and Spectrograms.  NOT SO!

In fact there are actuall THREE pages - (the first one is hidden as "Tracks")

So in fact, we have

Tracks
  |-- Track Options
  |-- Track Behaviors
  |-- Track Spectrograms

This has caught many forum users (myself included) confused when looking for an option they thought was there, but couldn't find.

A similar situation exists for

Import/Export
  |-- Extended Import

![Fullscreen013](https://user-images.githubusercontent.com/76828213/167200181-39e0a243-e740-4ab3-8b85-fedc5c8dd8f7.png)

**Comment by LWinterberg** [comment]
incidentally, this is something I started working on last week :)

**Comment by Paul-Licameli** [comment]
> incidentally, this is something I started working on last week :)

While you are on that topic, @LWinterberg , consider how Keyboard preferences might be redesigned with sub-pages corresponding to the the different kinds of foci.

**Comment by LWinterberg** [comment]
closing this bug, I'm tracking it elsewhere. All changes made in this regard are probably going to trickle through in small bits anyway.
