### ISSUE TITLE
Unable to load a .ts file

### ISSUE THREAD

**Issue by StormProductionsMusic** [audacity/audacity#2903]
Hi there,

I'm trying to load up a .ts video file into Audacity, got ffmpeg installed, but when attempting to get the file into Audacity, the progress bar goes up to 100% and then stops, without finishing the process of loading the file. I can't neither stop nor cancel the process, and the only way to exit Audacity is by using the Task Manager.

This has happened to me in the past, but I managed to get it fixed by loading a .mp3 file, and then loading the .ts file on the second track. But now, even this doesn't work anymore. 

It's pretty difficult to reproduce the bug, as sometimes it happens, while sometimes it doesn't and the file loads up properly. 

I'm not sure if it's an Audacity bug or something's wrong with ffmpeg, but hopefully me reporting it here will get someone to look on it.

Thanks.

**Comment by LWinterberg** [comment]
which version of ffmpeg are you using?

**Comment by StormProductionsMusic** [comment]
Hi, I’ve attached a screenshot with the version of FFmpeg. Thanks.

**Comment by StormProductionsMusic** [comment]
Here's the version I'm using:
![Screenshot 2022-05-08 190058](https://user-images.githubusercontent.com/86001751/167304752-4a049e10-7acb-4312-b21c-33ebb01b80c7.png)

**Comment by StormProductionsMusic** [comment]
Audacity 3.1.3, Windows 11 21H2 (x64) build 22000.675  From: dozzzzerSent: Thursday, May 12, 2022 4:08 PMTo: audacity/audacityCc: StormProductionsMusic; MentionSubject: Re: [audacity/audacity] Unable to load a .ts file (Issue ***@***.*** Which version of Audacity? Which OS?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by dozzzzer** [comment]
@StormProductionsMusic I've got the exact same FFmpeg version but cannot reproduce the bug, all the sample .ts files opened perfectly for me multiple times. However, I tried this using Win10 x64. 
![image](https://user-images.githubusercontent.com/70063970/168277557-79581f83-ff6d-443a-a716-355f4d6319ba.png)

**Comment by StormProductionsMusic** [comment]
@dozzzzer then what should I do? Sometimes it works, but sometimes it doesn't. Restarting, for example helps. Probably there is something wrong with my system. Thanks anyway.
