### ISSUE TITLE
When the Export Multiple dialog opens on Windows, the first control is not the focus

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#2909]
**Describe the bug**
When the Export Multiple dialog opens on Windows, the first control is not the focus

**To Reproduce**
1. Open the Export Multiple dialog

**Actual behavior**
One of the controls in the Options section is the focus.

**Expected behavior**
The first control in the dialog, the Folder text box, is the focus.

**Additional information (please complete the following information):**
 - OS: Windows 10. The bug does not occur on macOS or Xubuntu
 - Version 3.1.3

**Additional context**
This bug is a regression wrt Audacity 2.4.1
The bug can be confusing for users of screen readers who may assume that the initial focus is the first control, and so not find some of the controls in this dialog.

**Comment by petersampsonaudacity** [comment]
Tested @DavidBailes  branch audacity-win-3.2.0-alpha-20220510+97a6dc2-x64-msvc2022 on W10

This looks to be fixed David's changes, with initial focus on the folder location for export.
