### ISSUE TITLE
Effect stacks: plan for click-free on/off actions

### ISSUE THREAD

**Issue by pietro68** [audacity/audacity#2914]
Clicking on/off on one of the effects in a stack, poses a problem which should be taken into account when designing the code for the effect stack.

The issue is: when a user clicks the effect off, this can not be translated into suddenly stop calling the effect's ::process function. This would likely cause an audible "click" - think for instance about a simple gain effect set at +6dB - if I stop calling the process function suddenly, then the output waveform would exhibit a sudden -6dB step down, and that means an audio click (*)

Instead, as a response to the effect being muted, its ::process function should be still called, and a fade out curve should be applied to it; after the fade out is complete, then we can effectively stop calling the effect's process function.

A similar concern applies when de-muting (i.e. pressing "on") - the framework should start calling the process function, but apply a fade-in curve to the processed.

Please take this into account: the duration of the fades could actually be larger than the process buffer, it could be that this fading phase will be spread on multiple consecutive ::process calls (in other words, do not assume that it will be enough to just apply a fade-out curve to the last processed buffer).

Please note, this problem also applies to the whole effect stack (assuming it has an "on/off" button too)

(*) the actual loudness of the click, depends also on how loud is the waveform at the end of the last processed buffer, when processing is stopped - if close to a zero-crossing point, then the click would be inaudible - this is why this could be a bit tricky to verify in QA, unless one uses a "waveform" made of DC at 0dB (i.e. an infinite step of maximum amplitude) and a simple gain effect set at -12dB; that would make a sure-fire test case.

**Comment by AnitaBats** [comment]
@Paul-Licameli to discuss with Pietro

**Comment by pietro68** [comment]
> as a response to the effect being muted, its ::process function should be still called, and a fade out curve should be applied to it; after the fade out is complete, then we can effectively stop calling the effect's process function.

Actually, a better way to do it would be to do a cross fade, i.e. to mix a fade-out of the effect-processed audio with a fade-in of the unprocessed audio. This means, upon powering off the effect, it should actually keep on processing to produce enough samples to fill the cross-fade zone - only then it can be really turned off.
