### ISSUE TITLE
Effect stacks: plan for parameters smoothing

### ISSUE THREAD

**Issue by pietro68** [audacity/audacity#2915]
Parameter smoothing is a very important thing to think about when designing realtime effects. If it is not done, turning knobs of an effect in realtime processing, can lead to clicks.

Example: a simple gain effect. If the user turns the gain knob fast enough, the gain value will change so fast across consecutive buffers, that the processed buffers will exhibit noticeable steps at the buffer junctions - producing audio clicks or at least making the audio sound "stepped" while the knob is turned.

The solution to this, is to "smooth" the parameter, i.e. to apply a speed limit to its change rate, holding some memory of the changes; usually a lowpass filter (working in the parameter domain, not the audio domain!) is enough for the purpose. Also, not all parameters of an effect need smoothing, and those who do may require different amounts of smoothing.

In principle, each effect could do its own parameter smoothing internally - i.e. receive the "raw" parameter change from the framework, and send it to a local biquad filter set as a lowpass filter to get the smoothed version of it. 

But maybe it makes sense to externalize this facility in the framework instead, to avoid code duplication. In this way, when declared, a parameter would tell the framework if it needs smoothing or not, and at which rate.

I suppose that there are classes of effects that take the liability of the smoothing, and perform it internally to them (VST, AU?) so for them we would not need this. But we might need it for our built-in effects.

Also, parameter smoothing is not a complete guarantee against audio artifacts: if we go back to our gain example, with smoothing we'd only reduce the gaps at the buffer junctions, but we do not eliminate them completely; to do so, we should also interpolate the gain factor between the previous value and the current one, and do that per-processed sample, i.e. we'd need to interpolate at each repetition of the process loop, sample-wise; that interpolation can only happen internally to the effect.

**Comment by LWinterberg** [comment]
As a slightly larger scope, you may want to apply this smoothing to the volume/pan sliders as well as start/stop playback. There exists a micro-fading option but it's somewhat broken right now (see discord)

**Comment by LWinterberg** [comment]
closing for the time being
