### ISSUE TITLE
Toolbar layout is corrupted after an upgrade from 3.1.3 to 3.2.0 (with no reset)

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2919]
Proposed action: automatically reset toolbars on upgrade

**Describe the bug**
If the user upgrades from 3.1.3 to 3.20  without making a reset as part of the update the the Toolbar layout is corrupted.
a) the new wider window size is not used (Audacity remembers and reuses the user's previous window size from 3.1.3 or earlier)
b) The Edit Toolbar incorporates a large empty space, unnecessarily more than doubling its width
c) The Tools Toolbar incorporates a small empty space unnecessarily increasing its width by 50%
d) The Play-at-Speed Toolbar remains in the top tooldock area
e) The Device Toolbar remains visible
f) as a result of all the above, the Upper tooldock area occupies 6 lines rather than the 3 one should get with 3.2.0 thereby reducing the space available for a user's tracks.

**To Reproduce**
1. Purge the audacity folder to get default OOTB factory settings
2. launch 3.1.3
3. Observe Toolbar layout - see Screenshot 1
4. Close 3.1.3
5. Launch 3.2.0
6. Observe corrupted toolbar layout as per bug description above- See screenshot 2
7. View > Toolbars > Reset Toolbars
8. Observe: Upper tooldock occupies 4 lines (window is not wide enough - see Screenshot 3
9. Observe: Lower Tooldock occupies 3 lines not 2 (as the window is not wide enough to enable the Play-at-Speed Toolbar to st alongside the Timer Toolbar
10. Observe: the Device Toolbar is disabled/hidden - expected behavior
11. Tools > Reset Configuration
12. Observe: Tooldock layout is as expected for 3.2.0 _(that which you get if you purge Audacity settings and then launch 3.2.0)_ - see screenshot 4

**Actual behavior**
Corrupted Tooldock areas

**Expected behavior**
a) As a minimum the new 3.2.0 window width size should be used
b) Probably a full  (perhaps optional) reset to get the default 3.2.0 Toolbars layout _(as this is not just a minor change)_

**Screenshots**
### 1) default 3.1.3 Toolbar layout
![image](https://user-images.githubusercontent.com/50205984/168072166-80afa726-c1ca-4389-b4ab-6d3e81d78c92.png)

### 2) 3.2.0 after upgrade from 3.1.3 with no reset
![image](https://user-images.githubusercontent.com/50205984/168072322-a892fb19-6b39-4a23-ae3c-ccf4f2defe9a.png)

### 3) 3.2.0 after Reset Toolbars
![image](https://user-images.githubusercontent.com/50205984/168072681-e282b783-13c6-45dd-b43d-8233053d2bd9.png)

### 3) 3.2.0 after Reset Toolbars
![image](https://user-images.githubusercontent.com/50205984/168072764-2948d709-6aef-445f-983c-e24023a41a63.png)

**Additional information (please complete the following information):**
 - OS:  Windows 10 - but assume all OS
 - Version: Audacity 3.2.0

**Additional context**
The simple no reset upgrade (screenshot 2) just looks messy and bad - and thus **_really_** should be fixed for 3.2.0 release.

This is effectively a regression as upgrades with previous versions did _**NOT**_ cause a corrupted messy toolbar layout.

**Comment by LWinterberg** [comment]
There was an idea earlier to include this info in a "what's new" popup (#2718), but now I'm thinking that we really should just reset the toolbars on upgrade

**Comment by petersampsonaudacity** [comment]
This gets even worse when you upgrade from 3.1.3 to the Branch 3.2.0 build with the new cogwheel toolbar
![image](https://user-images.githubusercontent.com/50205984/168806434-154cfc68-78cc-4b14-9dec-51e8e43879c4.png)

**Comment by LWinterberg** [comment]
closing in favor of #3479
