### ISSUE TITLE
A crash when trying to open up an AU plug-in.

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#2924]
I'm getting a crash when trying to open up an AU plug-in.
OS: MacOS Monterey
Version: [audacity-macOS-3.2.0-alpha-20220511+d54f67f-universal](https://github.com/audacity/audacity/suites/6466694314/artifacts/238943396)

https://user-images.githubusercontent.com/70063970/168112815-f2813f09-bd2d-49be-a8c7-272856319995.mp4

Crash Report:
[Audacity_dbgrpt-28294-20220512T173139.zip](https://github.com/audacity/audacity/files/8680557/Audacity_dbgrpt-28294-20220512T173139.zip)

AU Plugin used:
https://www.audiopluginsforfree.com/tdr-nova/

_Originally posted by @dozzzzer in https://github.com/audacity/audacity/issues/2841#issuecomment-1125141740_

**Comment by dozzzzer** [comment]
Verified on MacOS Monterey 12.3.1.
