### ISSUE TITLE
Crash when scrolling spectrogram partially off-screen

### ISSUE THREAD

**Issue by nyanpasu64** [audacity/audacity#2930]
**Describe the bug**
When I switch a clip to spectrogram view and scroll it partly off-screen, it calls memmove with an out-of-bounds source (which crashes on Flatpak Audacity, and is invalid but uncaught elsewhere).

**To Reproduce**
1. Download my sample project ([spectrogram crash.aup3.zip](https://github.com/audacity/audacity/files/8691931/spectrogram.crash.aup3.zip)). This contains a single block which can be scrolled off the left side of the screen (plus a second block off-screen on the right).
	- Fun fact: when sharing .aup3 files created after a crash (or possibly always), they are larger than expected due to holding already-deleted audio data. You have to vacuum them from the command line: `sqlite3 <FILENAME> 'vacuum;'` I'm unsure if Audacity has any method to do so from the GUI (perhaps "Backup Project"? IDK).
2. Open in Audacity 3.1.3 flatpak, or my branch with added bounds checks (https://github.com/audacity/audacity/compare/Audacity-3.1.3...nyanpasu64:fix-spectrum-3.1.3 or https://github.com/audacity/audacity/compare/master...nyanpasu64:fix-spectrum-master). You can also try defining `_FORTIFY_SOURCE` and/or `_GLIBCXX_ASSERTIONS`, building with ASAN, or running in Valgrind.
3. Scroll to the right and left (shift+mousewheel).

**Actual behavior**
Audacity crashes with an assertion error in `WaveClip::GetSpectrogram` (3.1.3) or `WaveClipSpectrumCache::GetSpectrogram` (master):

```cpp
      auto src = nBins * (copyBegin + oldX0);
      assert(src <= freq.size());
```

**Expected behavior**
Audacity does not read from out-of-bounds memory, past the end of a vector.

**Additional information (please complete the following information):**
 - OS: Arch Linux
 - Version: 3.1.3, master 2b5fa3c414d353efd21000bf687e623276cc76ab

**Additional context**
Regular Audacity performs out-of-bounds reads but doesn't crash; it's still UB and wrong.

Disassembly of function and point-of-crash in Flatpak 3.1.3: https://gist.github.com/nyanpasu64/02e2db8d9e045830a790e8e29fcb4d6d

**Comment by nyanpasu64** [comment]
This is not a distro-specific bug; it's a program bug only caught in Flatpak builds:

> Regular Audacity performs out-of-bounds reads but doesn't crash; it's still UB and wrong.

I reproduced the crash and took the state at the time of crashing:

![audacity crash state](https://user-images.githubusercontent.com/913957/168444006-57077cd5-a6cb-4650-ba78-f1aecd6d1e7d.png)

I'd have to debug further to see how the variables change at various scroll positions.

**Comment by cdbrendel** [comment]
> This is not a distro-specific bug; it's a program bug only caught in Flatpak builds:

Yes, definitely not distro-specific. I'm running Arch, no Flatpak, and I was having the same problem (a predictable crash iff I scrolled a spectrogram offscreen). [master...nyanpasu64:fix-spectrum-master](https://github.com/audacity/audacity/compare/master...nyanpasu64:fix-spectrum-master) fully solves the issue for me. I hope this gets pulled in.

Thanks for the fix, @nyanpasu64!

**Comment by nyanpasu64** [comment]
btw I think https://github.com/audacity/audacity/compare/master...nyanpasu64:fix-spectrum-master doesn't fix the bug, the patch in my above comment does. If my branch doesn't encounter the bug, I think that just means the assertion doesn't fire but the UB is still present.

**Comment by plisiecki** [comment]
I came across the same issue independently and came up with a different solution: Do the memmove before or after the Grow() call depending on the sign of oldX0. The advantage is that it allows memory to shrink. The disadvantage is duplication of the memmove code. Here is the diff: [master..plisiecki:fix-spectrum-memmove](https://github.com/audacity/audacity/compare/master...plisiecki:fix-spectrum-memmove).

**Comment by plisiecki** [comment]
Here is an alternate solution which does the grow before memmove and shrink afterwards.  Since the grow() call is much simpler, there is less duplication, and also the `if` conditions are easier to understand.  [master..plisiecki:fix-spectrum-memmove-alt](https://github.com/audacity/audacity/compare/master...plisiecki:fix-spectrum-memmove-alt).

**Comment by mrjpaxton** [comment]
I also have the same problem. I've been opening up the Flatpak version of Audacity (with networking disabled) to open up bunches of 16-bit and 24-bit FLAC files in a spectrogram to check if they are "true FLAC" files, meaning no frequency cutoffs at 15-16KHz, indicating that they were converted from lower quality sources, so this function is important to me to check my audio. Yes, I know about Spex as well, but since I use Audacity for other functions anyway, This is important for me to have working. I don't want a separate tool. Would be great if this was fixed!

**Comment by micromaomao** [comment]
I've hit this bug in Archlinux without flatpack, first with the Arch official build and now reproduced with a custom debug build. This also happens during recording, and (although I'm not sure if it's actually the same reason) I've noticed crash even when not viewing the spectrogram as well.

```gdb
(gdb) bt
#0  0x00007ffff56ac83c in  () at /usr/lib/libc.so.6
#1  0x00007ffff565c668 in raise () at /usr/lib/libc.so.6
#2  0x00007ffff56444b8 in abort () at /usr/lib/libc.so.6
#3  0x00007ffff58dd3b2 in std::__glibcxx_assert_fail(char const*, int, char const*, char const*)
    (file=file@entry=0x5555561890c8 "/usr/include/c++/13.2.1/bits/stl_vector.h", line=line@entry=1125, function=function@entry=0x5555561db6f8 "std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = float; _Alloc = std::allocator<float>; reference = float&; size_type = long unsigned int]", condition=condition@entry=0x55555614f0a5 "__n < this->size()")
    at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/debug.cc:61
#4  0x0000555555c9d21e in std::vector<float, std::allocator<float> >::operator[](unsigned long) (this=this@entry=0x555557b04d98, __n=<optimized out>) at /usr/include/c++/13.2.1/bits/stl_vector.h:1125
#5  0x0000555555fd5673 in WaveClipSpectrumCache::GetSpectrogram(WaveChannelInterval const&, float const*&, SpectrogramSettings&, sampleCount const*&, unsigned long, double, double)
    (this=0x555557bdefe0, clip=..., spectrogram=@0x7fffffffb5d0: 0x0, settings=..., where=@0x7fffffffb5d8: 0x0, numPixels=52, t0=11.552926947042408, pixelsPerSecond=154.97306034482725)
    at /home/mao/audacity-debug/audacity/src/audacity-Audacity-3.4.2/src/tracks/playabletrack/wavetrack/ui/SpectrumCache.cpp:536
#6  0x0000555555fddda0 in (anonymous namespace)::DrawClipSpectrum(TrackPanelDrawingContext&, WaveTrack const&, WaveChannelInterval const&, wxRect const&, std::shared_ptr<SpectralData> const&, bool)
    (context=..., track=..., clip=..., rect=..., mpSpectralData=std::shared_ptr<SpectralData> (use count 1, weak count 0) = {...}, selected=selected@entry=false)
    at /home/mao/audacity-debug/audacity/src/audacity-Audacity-3.4.2/src/tracks/playabletrack/wavetrack/ui/SpectrumView.cpp:429
#7  0x0000555555fdec65 in SpectrumView::DoDraw(TrackPanelDrawingContext&, unsigned long, WaveTrack const&, WaveClip const*, wxRect const&)
    (this=this@entry=0x555557d31210, context=..., channel=<optimized out>, track=..., selectedClip=0x0, rect=...)
    at /home/mao/audacity-debug/audacity/src/audacity-Audacity-3.4.2/src/tracks/playabletrack/wavetrack/ui/SpectrumView.cpp:881
#8  0x0000555555fdee7c in SpectrumView::Draw(TrackPanelDrawingContext&, wxRect const&, unsigned int) (this=0x555557d31210, context=..., rect=..., iPass=0)
    at /home/mao/audacity-debug/audacity/src/audacity-Audacity-3.4.2/src/tracks/playabletrack/wavetrack/ui/SpectrumView.cpp:907
#9  0x0000555555bd1bb6 in operator()(wxRect const&, TrackPanelNode&) const (__closure=0x5555575ced20, rect=..., node=...)
    at /home/mao/audacity-debug/audacity/src/audacity-Audacity-3.4.2/src/CellularPanel.cpp:1244
#10 0x0000555555bd1ca4 in std::__invoke_impl<void, CellularPanel::Draw(TrackPanelDrawingContext&, unsigned int)::<lambda(const wxRect&, TrackPanelNode&)>&, const wxRect&, TrackPanelNode&> (__f=<optimized out>)
    at /usr/include/c++/13.2.1/bits/invoke.h:60
#11 std::__invoke_r<void, CellularPanel::Draw(TrackPanelDrawingContext&, unsigned int)::<lambda(const wxRect&, TrackPanelNode&)>&, const wxRect&, TrackPanelNode&> (__fn=<optimized out>)
    at /usr/include/c++/13.2.1/bits/invoke.h:111
#12 std::_Function_handler<void(const wxRect&, TrackPanelNode&), CellularPanel::Draw(TrackPanelDrawingContext&, unsigned int)::<lambda(const wxRect&, TrackPanelNode&)> >::_M_invoke(const std::_Any_data &, const wxRect &, TrackPanelNode &) (__functor=<optimized out>, __args#0=<optimized out>, __args#1=<optimized out>) at /usr/include/c++/13.2.1/bits/std_function.h:290
#13 0x0000555555bd6886 in std::function<void (wxRect const&, TrackPanelNode&)>::operator()(wxRect const&, TrackPanelNode&) const (this=<optimized out>, __args#0=<optimized out>, __args#1=<optimized out>)
    at /usr/include/c++/13.2.1/bits/std_function.h:591
#14 0x0000555555bd18cb in (anonymous namespace)::Adaptor::VisitCell(wxRect const&, TrackPanelCell&) (this=<optimized out>, rect=<optimized out>, cell=<optimized out>)
    at /home/mao/audacity-debug/audacity/src/audacity-Audacity-3.4.2/src/CellularPanel.cpp:1048
#15 0x0000555555bd40c4 in CellularPanel::Visit(wxRect const&, std::shared_ptr<TrackPanelNode> const&, CellularPanel::Visitor&)
    (this=this@entry=0x555556dfbf00, rect=..., node=std::shared_ptr<TrackPanelNode> (use count 4, weak count 2) = {...}, visitor=...)
    at /home/mao/audacity-debug/audacity/src/audacity-Audacity-3.4.2/src/CellularPanel.cpp:1113
#16 0x0000555555bd4187 in CellularPanel::Visit(wxRect const&, std::shared_ptr<TrackPanelNode> const&, CellularPanel::Visitor&)
    (this=this@entry=0x555556dfbf00, rect=..., node=std::shared_ptr<TrackPanelNode> (use count 1, weak count 0) = {...}, visitor=...)
    at /home/mao/audacity-debug/audacity/src/audacity-Audacity-3.4.2/src/CellularPanel.cpp:1123
#17 0x0000555555bd4187 in CellularPanel::Visit(wxRect const&, std::shared_ptr<TrackPanelNode> const&, CellularPanel::Visitor&)
    (this=this@entry=0x555556dfbf00, rect=..., node=std::shared_ptr<TrackPanelNode> (use count 1, weak count 0) = {...}, visitor=...)
    at /home/mao/audacity-debug/audacity/src/audacity-Audacity-3.4.2/src/CellularPanel.cpp:1123
#18 0x0000555555bd4187 in CellularPanel::Visit(wxRect const&, std::shared_ptr<TrackPanelNode> const&, CellularPanel::Visitor&)
    (this=this@entry=0x555556dfbf00, rect=..., node=std::shared_ptr<TrackPanelNode> (use count 1, weak count 0) = {...}, visitor=...)
    at /home/mao/audacity-debug/audacity/src/audacity-Audacity-3.4.2/src/CellularPanel.cpp:1123
#19 0x0000555555bd4187 in CellularPanel::Visit(wxRect const&, std::shared_ptr<TrackPanelNode> const&, CellularPanel::Visitor&)
    (this=this@entry=0x555556dfbf00, rect=..., node=std::shared_ptr<TrackPanelNode> (use count 1, weak count 0) = {...}, visitor=...)
    at /home/mao/audacity-debug/audacity/src/audacity-Audacity-3.4.2/src/CellularPanel.cpp:1123
#20 0x0000555555bd4187 in CellularPanel::Visit(wxRect const&, std::shared_ptr<TrackPanelNode> const&, CellularPanel::Visitor&)
    (this=this@entry=0x555556dfbf00, rect=..., node=std::shared_ptr<TrackPanelNode> (use count 1, weak count 0) = {...}, visitor=...)
    at /home/mao/audacity-debug/audacity/src/audacity-Audacity-3.4.2/src/CellularPanel.cpp:1123
#21 0x0000555555bd4187 in CellularPanel::Visit(wxRect const&, std::shared_ptr<TrackPanelNode> const&, CellularPanel::Visitor&)
    (this=this@entry=0x555556dfbf00, rect=..., node=std::shared_ptr<TrackPanelNode> (use count 1, weak count 0) = {...}, visitor=...)
    at /home/mao/audacity-debug/audacity/src/audacity-Audacity-3.4.2/src/CellularPanel.cpp:1123
#22 0x0000555555bd4187 in CellularPanel::Visit(wxRect const&, std::shared_ptr<TrackPanelNode> const&, CellularPanel::Visitor&)
    (this=this@entry=0x555556dfbf00, rect=..., node=std::shared_ptr<TrackPanelNode> (use count 1, weak count 0) = {...}, visitor=...)
    at /home/mao/audacity-debug/audacity/src/audacity-Audacity-3.4.2/src/CellularPanel.cpp:1123
#23 0x0000555555bd4233 in CellularPanel::Visit(CellularPanel::Visitor&) (this=this@entry=0x555556dfbf00, visitor=...) at /home/mao/audacity-debug/audacity/src/audacity-Audacity-3.4.2/src/CellularPanel.cpp:1026
--Type <RET> for more, q to quit, c to continue without paging--q
Quit
(gdb) select 5
(gdb) frame
#5  0x0000555555fd5673 in WaveClipSpectrumCache::GetSpectrogram (this=0x555557bdefe0, clip=..., spectrogram=@0x7fffffffb5d0: 0x0, settings=..., where=@0x7fffffffb5d8: 0x0, numPixels=52, t0=11.552926947042408, 
    pixelsPerSecond=154.97306034482725) at /home/mao/audacity-debug/audacity/src/audacity-Audacity-3.4.2/src/tracks/playabletrack/wavetrack/ui/SpectrumCache.cpp:536
536	              &mSpecCache->freq[nBins * (copyBegin + oldX0)],
(gdb) l
531	  // possible
532	  if (copyEnd > copyBegin)
533	  {
534	     // memmove is required since dst/src overlap
535	     memmove(&mSpecCache->freq[nBins * copyBegin],
536	              &mSpecCache->freq[nBins * (copyBegin + oldX0)],
537	              nBins * (copyEnd - copyBegin) * sizeof(float));
538	  }
539	
540	  // Reassignment accumulates, so it needs a zeroed buffer
(gdb) 
```

**Comment by TheTrustedComputer** [comment]
I have a similar issue with Audacity from the Arch repos. As soon as I create at least two audio clips in a single track and have it display the spectrogram, scrolling left or right causes Audacity to crash with an IOT instruction message in the terminal.

I've also reproduced this in the Flatpak version, but the AppImage, while not working as per issue #6233, doesn't seem to be affected.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
