### ISSUE TITLE
Define and use a Settings structure for AudioUnitEffect

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#2933]
Define and use an effect settings struture for AudioUnit effects

**Comment by Ryan-Miller-Audacity** [comment]
Issues found during testing and where they are being tracked: 

Related Issues (not reproducible in previous build before changes):
1. https://github.com/audacity/audacity/issues/2993 - Importing AU presets is broken
2. https://github.com/audacity/audacity/issues/2995 - The AU Effect User presets are not being saved correctly. When a user saves a preset an entry is saved; however, the proper data doesn’t appear to be saved with it: i.e. when I select the preset later it does not load the settings from the preset as expected. 
    * I determined that saving is the problem as I observed that saving a preset from the test build and utilizing it within the current public release did not yield the correct settings; however, saving a preset from the current release and loading that preset within the test build did yield the correct result; therefore, it seems the issue lies within saving the preset metrics correctly, not loading the preset.  
3. https://github.com/audacity/audacity/issues/2997 - The AUPeakLimiter effect appears to be broken as it does not display its interface at all when opened. It just shows the popup (empty)

Unrelated issues (reproducible in previous build before changes):
1. (Previously reported) https://github.com/audacity/audacity/issues/2954 - The playback buttons included in the AU interface exhibit some issues. 
    * The play button no longer changes to stop button when playback is started. (This means that playback cannot be stopped from the interface.)
    * The fast forward/backward buttons do not work during playback and do not skip playback forward/backward. 
2. (Previously reported) https://github.com/audacity/audacity/issues/2954 - The enable checkbox no longer toggles the effect before/during playback. 
3. (Was already known and decided to be non-fix.) ~~AU Effects that display data (sound levels, frequencies, output etc) are no longer properly showing this information during playback.~~
    * ~~This includes the AUDynamicsProcessor, AUMultibandCompressor (note that I was not able to confirm this with the AUPeakLimiter effect since it is broken (see issue below), but since that effect involves monitoring playback in the interface I would say most likely it is effected here as well).~~
