### ISSUE TITLE
Manipulating Loop region during playback should not effect playback

### ISSUE THREAD

**Issue by Ryan-Miller-Audacity** [audacity/audacity#2956]
## Is your feature request related to a problem? Please describe.

Interacting with the loop region (dragging the whole region, adjusting start end time of loop region etc.) during playback can effect playback. IMO, when the loop region is being interacted with, that should "decouple" it from playback ie. until I "let go" of the loop region it should not effect playback. 

I tested this theory in Presonus Studio One and my above theory is how it is handled there. Editing the looping region during playback does not have any effect on playback until it is set (you let go of dragging it).

## Describe the solution you'd like

Editing the looping region during playback does not have any effect on playback until it is set (you let go of dragging it). In a sense, "decoupling" loop region editing from playback. 

## Describe alternatives you've considered

1. Disallow loop region editing/manipulation during playback. 
    a. This would negatively impact user's workflow by restricting them from editing their loops during playback. For example, if they selected an incorrect region or an incorrect length and want to edit this on the fly.  

## Additional context

https://user-images.githubusercontent.com/88568755/169553270-bb63f0cb-949f-4ff1-91f6-d792be66f9df.mp4

This screencast was recorded in the current public release of Audacity (3.1.3), but I also observed the behavior in the latest master release (3.2.0-alpha-20220519)

**Comment by LWinterberg** [comment]
Some testing: 

* Audition changes loop region on letting go of the mouse
* Ableton immediately updates
* Reaper immediately updates
* Bandlab does it on release
* Cakewalk does it on release
* Garageband immediately updates

Let's decide this after beats+measures exist
