### ISSUE TITLE
Can't stop real-time preview from effect UI

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2960]
**Describe the bug**
In previous versions, clicking the "Play" button in an effect with real-time preview started play, and the button would toggle to a "Stop" button. Now there is no "Stop" button.

**To Reproduce**
1. Start previewing any real-time preview effect.
2. Press "Space" to stop previewing

**Actual behavior**
Preview continues.

**Expected behavior**
Preview stops.

**Screenshots**
If applicable, add screenshots/video to help explain your problem.

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version [e.g. Audacity 2.5.1] Audacity 3.2.0 6a5645 

**Additional context**
Regression.
See also: https://github.com/audacity/audacity/issues/2954

**Comment by petersampsonaudacity** [comment]
This is already reported as step 6 in
 Changing the parameters of Reverb or other real-time enabled effects doesn't affect the sound at all during the preview playback #2954
