### ISSUE TITLE
Audacity may remain in playback mode after playback stops

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2962]
**Describe the bug**
When playback stops at the end of a selection, Audacity may remain in play mode. This blocks most other actions, including editing, effects, save and export,... until playback is manually stopped.

**To Reproduce**
1. Make a selection
2. Start playback
3. Wait for playback to stop

**Actual behavior**
"Sometimes" (usually, but not always), Audacity is still in "playback mode". The "Play" button is still in the down position, and most menu options are greyed out.

**Expected behavior**
Playback to fully stop.

**Screenshots**
Video: https://youtu.be/kWPO5dAQBMU

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version [e.g. Audacity 2.5.1] Audacity 3.2.0 6a5645
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]

**Additional context**
This is a regression that I've noticed happening _occasionally_ for a while now (with 3.2.0 alpha builds), but it is now happening most of the time, which is highly disruptive to workflow.

**Comment by petersampsonaudacity** [comment]
I seem to be able to force this to happen on w10 with latest 3.2.o alpha master: audacity-win-3.2.0-alpha-20220521+6a56459-x64-msvc2022

**Comment by dozzzzer** [comment]
Duplicates #2453

**Comment by SteveDaulton** [comment]
Why has this issue been closed?
Note that the bug report says "6a5645", which right now is the latest alpha version.
