### ISSUE TITLE
Nyquist effects unusable with resized clips

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2963]
**Describe the bug**
When Nyquist effects are applied to an audio clip where one or both ends have been dragged to make the clip shorter, overlapping clips are created

**To Reproduce**
1. Generate a 10 second chirp
2. Drag the left edge to around 3 seconds
3. Drag the right edge to around 6 seconds
4. Double click on the remaining clip to select it
5. Apply a Nyquist effect, such as "Clip Fix"

**Actual behavior**
A total mess

**Expected behavior**
The effect to be applied to the visible and selected part of the clip

**Screenshots**
If applicable, add screenshots/video to help explain your problem.
![First Track000](https://user-images.githubusercontent.com/11681097/169811353-aa90f4c1-0c3d-48a3-abd0-48d22dff04da.png)

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version [e.g. Audacity 2.5.1] Audacity 3.2.0 : 2b5fa3 

**Additional context**
Regression.

**Comment by Ryan-Miller-Audacity** [comment]
I confirmed this bug on macOS Monterey (12.3.1) in recent alpha (3.2.0-alpha-20220519).

Could not reproduce in current public Audacity release (3.1.3).

**Comment by Paul-Licameli** [comment]
Also fixed recently by https://github.com/audacity/audacity/commit/c40dad556a6dabc9a279724c3b08fce90b37df5f

**Comment by dozzzzer** [comment]
Verified on Windows 10, macOS 12.
