### ISSUE TITLE
Uninstalled Nyquist plug-in listed as "Disabled"

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2965]
**Describe the bug**
When a Nyquist plug-in is removed (deleted) from the user's Plug-Ins folder and Audacity rebooted, the plug-in still appears in the plug-in manager as "Disabled". This is potentially very confusing: If the plug-in was uninstalled a long time previously, there is no indication of why enabling the plug-in fails. Worse still, when attempting to enable the missing effect, the plug-in manager says that it is Enabled (it isn't).

**To Reproduce**
1. Install a custom Nyquist plug-in
2. Enable the plug-in
3. Close Audacity
4. Uninstall (delete) the plug-in from the user's Plug-Ins folder
5. Restart Audacity
6. Open the plug-in manager
7. Observe that the effect is listed as "Disabled"
8. Enable the plug-in
9. Observe that the effect is now listed as "Enabled"
10. Close the plug-in manager
11. Observe that the plug-in does not appear in Audacity's menus
12. Open the plug-in manager
13. Observe that the plug-in is still listed as "**Enabled**"!

**Actual behavior**
Plug-ins may be listed as Enabled or Disabled when in fact they are totally absent.

**Expected behavior**
The plug-in manager to accurately report on which plug-ins are available, and whether they are enabled or disabled.

**Screenshots**
If applicable, add screenshots/video to help explain your problem.

**Additional information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version [e.g. Audacity 2.5.1] 3.2.0 6a5645 

**Additional context**

**Comment by Ryan-Miller-Audacity** [comment]
I confirmed this bug in current public release Audacity 3.1.3 on macOS Monterey 12.3.1.

**Comment by vsverchinsky** [comment]
> I confirmed this bug in current public release Audacity 3.1.3 on macOS Monterey 12.3.1.
> 
> Note that this doesn't appear to only effect Nyquist plugins as the title/description implies and appears to be more generalized to perhaps plugins in general. I tested this as well with a Blue Cat VST effect plug in and noted the same effects.

@Ryan-Miller-Audacity I've [created](https://github.com/audacity/audacity/pull/3288) a PR which addresses that issue for each plugin type we currently support
