### ISSUE TITLE
Smart clips may expand when pasting adjacent to clip

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#2968]
**Describe the bug**
Pasting may cause "smart clips" to expand

**To Reproduce**
1. Generate a 30 second chirp
2. Select a few seconds near the middle
3. Alt + Ctrl + X (split copy)
4. Ctrl + V (paste)

**Actual behavior**
* The third clip is expanded to 30 seconds.
* The first clip is expanded below the pasted clip
* The second (pasted) clip is expanded below the third clip

**Expected behavior**
The copied clip to be pasted into the selected space.

**Screenshots**
If applicable, add screenshots/video to help explain your problem.

**Additional information (please complete the following information):**
 - OS: [e.g. Mac High Sierra, Ubuntu 18.04, Windows 10] Xubuntu 20.04
 - Version [e.g. Audacity 2.5.1] 3.2.0 6a5645

**Additional context**
Regression

**Comment by petersampsonaudacity** [comment]
Confirmed on w10 with latest alpha master audacity-win-3.2.0-alpha-20220521+6a56459-x64-msvc2022

**Comment by Ryan-Miller-Audacity** [comment]
https://user-images.githubusercontent.com/88568755/169897835-36ccf423-2065-4cc4-90b7-37f58587eff1.mp4

Screen recording for reference.

**Comment by Ryan-Miller-Audacity** [comment]
Screen recording for reference: 

Uploading smart-clips-may-expand-when-pasting-adjacent-to-clip1.mp4…

**Comment by SteveDaulton** [comment]
"P3" seems rather low to me. An editor that messes up basic edits is not fit for purpose.

**Comment by Paul-Licameli** [comment]
No longer reproducible, probably fixed by c40dad556a6dabc9a279724c3b08fce90b37df5f

**Comment by dozzzzer** [comment]
Tested and verified fixed in the latest alpha branch.

**Comment by dozzzzer** [comment]
Tested and verified fixed in the latest alpha branch.
