### ISSUE TITLE
User is told that AU and LADSPA plug-ins are "incompatible"

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#2982]
**Describe the bug**
The Apple-provided AU plug-ins appear to fail to load on Mac (the user is told they are "incompatible") - you get the message shown in the screenshot.
This message is a regression on 3.1.3 - and is likely to worry Mac users

However if you go to the Plug-in Manager you can see all the AU effects there but they are disabled:
a) they can be enabled
b) then they can successfully be used

**To Reproduce**
1. Purge the Audacity settings folder
2. Launch 3.2.0
3. Observe: AU plug-ins fail to load (see screenshot)
4. Plug-in Manger
5. Observe: AU plug-ins marked as Disabled
6. Enable AU plug-ins
7. Use AU plug-ins
8. Observe: AU plugins available for use and they work

**Actual behavior**
AU plug-ins fail to load

**Expected behavior**
AU plug-ins should load

**Screenshots**
![image](https://user-images.githubusercontent.com/50205984/170320440-9f4dab09-90dc-4ee0-98cc-33eb7ad9a1b9.png)

**Additional information (please complete the following information):**
 - OS: macOS  Monterey 12.3.1
 - Version:  audacity-macOS-3.2.0-alpha-20220525+65a2ea0-x86_64 

**Additional context**
Note that in 3.1.3 and earlier the AU effects appear in the "New" category" and not the "Disabled" category.

Update from @Paul-Licameli : I have the swh package of LADSPA plug-ins built from source on my Mac, and those plug-ins have the same problems, and I predict they will also fail on other operating systems.  I test Audacity at commit 8a7fbf5cc9b50ed973b0eff167dd9402c63a0534.

There is a common bug for these two effect protocols, which, I predict, won't affect lv2, VST2, or VST3, though other unrelated bugs might also be found with those.

**Comment by dozzzzer** [comment]
I confirm this on Mac Monterey 12.3.1

**Comment by Paul-Licameli** [comment]
@pietro68 remind us please, where are the readilyt downloaded binaries for swh plug-ins for Windows?

**Comment by Paul-Licameli** [comment]
`std::bad_function_call` is thrown in the PluginHost process, where `PluginManager::GetSettings` tries to call `sFactory`, but `PluginManager::Initialize` was not yet done.

That is because `GetConfig` is called in `AudioUnitEffect::InitializePlugin` and in `LadspaEffect::LoadUseLatency`, called from `LadspaEffect::InitializePlugin`.

**Comment by petersampsonaudacity** [comment]
Testing on macOS 12.3.1 Monterey with @Paul-Licameli 's latest branch build:  
audacity-macOS-3.2.0-alpha-20220528+9a44494-x86_64 

This now works fine in Paul's branch build AFAICT:
1) no warning dialog about AU effects being incompatible
2) the AU effects are loaded and automatically enabled (on Mac)

**Comment by Paul-Licameli** [comment]
Do you have any Ladspa plug-ins for any operating system?

**Comment by petersampsonaudacity** [comment]
> Do you have any Ladspa plug-ins for any operating system?

No, sorry I don't - nor do I ave any real intention of acquiring any as these are fundamentally legacy only effects.

The Manual has long said in the intro div on this page:
https://alphamanual.audacityteam.org/man/Effect_Menu:_LADSPA
>LADSPA has been superseded by LV2 and most if not all LADSPA plug-ins are ancient and are no longer maintained.

And the new Muse plugins page says 
https://plugins.audacityteam.org/#ladspa
>LADSPA is superseded by LV2. These plug-ins are mostly built for Linux, but some old LADSPA plugins are available via the

**Comment by petersampsonaudacity** [comment]
@Paul-Licameli would Vamp analysis plug-ins do instead for such testing?

**Comment by Paul-Licameli** [comment]
> @Paul-Licameli would Vamp analysis plug-ins do instead for such testing?
> 
> _I do have a set those (currently hidden away)._

I do not think the same known bug exists for those, but there be unknowns.  Please try it.

**Comment by petersampsonaudacity** [comment]
@Paul-Licameli   my set of VAMP plug-ins 
a) loaded just fine
b) were auto-enabled
c) worked fine

**Comment by dozzzzer** [comment]
Testing on MacOS 12.2.1 and now I'm seeing the following:

- none of the LADSPA effects are enabled upon startup (i.e. they were listed as 'incompatible' after the scan): 
<img width="500" alt="image" src="https://user-images.githubusercontent.com/70063970/179749111-6931c03e-2939-4e14-9f4e-d6b29789e594.png">

- trying to enable them individually results in 'failed to register' error message: 

<img width="304" alt="image" src="https://user-images.githubusercontent.com/70063970/179745150-a9707175-af4f-46ea-83d6-b909be15bce8.png">

- all LADSPA plugins were placed into /Library/Audio/Plug-Ins/LADSPA
- with AU plugins, though, I observed no issues

**Comment by vsverchinsky** [comment]
> Testing on MacOS 12.2.1 and now I'm seeing the following:
> 
> * none of the LADSPA effects are enabled upon startup (i.e. they were listed as 'incompatible' after the scan):
> 
> <img alt="image" width="500" src="https://user-images.githubusercontent.com/70063970/179749111-6931c03e-2939-4e14-9f4e-d6b29789e594.png">
> 
> * trying to enable them individually results in 'failed to register' error message:
> 
> <img alt="image" width="304" src="https://user-images.githubusercontent.com/70063970/179745150-a9707175-af4f-46ea-83d6-b909be15bce8.png">
> 
> * all LADSPA plugins were placed into /Library/Audio/Plug-Ins/LADSPA
> * with AU plugins, though, I observed no issues

@dozzzzer As @crsib said you were trying to load x86 plugins on arm host, they do load without an issue on a mathcing arch, so probably issue should be closed

**Comment by dozzzzer** [comment]
Verified on MacOS 12.2.1.

Now that I have a proper set of LADSPA plugins I was able to load almost all of them with no issues.
However, 4 of them were found incompatible:

`/Library/Audio/Plug-Ins/LADSPA/imp_1199.so`
`/Library/Audio/Plug-Ins/LADSPA/mbeq_1197.so`
`/Library/Audio/Plug-Ins/LADSPA/pitch_scale_1193.so`
`/Library/Audio/Plug-Ins/LADSPA/pitch_scale_1194.so`

Let's treat this as a known and a very minor issue.

No issues with AU plugins were observed.
