### ISSUE TITLE
Power buttons in stackable effects don't work yet

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#2986]
Each effect has its own button, and each track has a master button.

The on/off states of the buttons should all be independently variable, and persistent if you save a project, close, reopen it.

The Undo/Redo history should remember the last on/off states that were used when that state was current.  On/off button changes should not make new undo states.

The buttons should be safely clickable during playback and you should hear the changes at once.

The master button should disable all effects on the track regardless of their separate on/off states.

**Comment by dozzzzer** [comment]
@Paul-Licameli 
power button state isn't taken into account wheт making Undo/Redo.

STR:
1. load a clip, select a realtime effect from a sidebar
2. turn the effect OFF
3. make an action that is remembered by Undo/Redo history (e.g. trim the clip)
4. Undo the last action
5. observe the power button state

Actual: it's set back to 'ON'
Expected: it remains 'OFF', the same as it was when that state was current

https://user-images.githubusercontent.com/70063970/174307125-01789639-1c73-4943-911d-c260c56b5e72.mp4

**Comment by Paul-Licameli** [comment]
> @Paul-Licameli power button state isn't taken into account wheт making Undo/Redo.
> 
> STR:
> 
> 1. load a clip, select a realtime effect from a sidebar
> 2. turn the effect OFF
> 3. make an action that is remembered by Undo/Redo history (e.g. trim the clip)
> 4. Undo the last action
> 5. observe the power button state
> 
> Actual: it's set back to 'ON' Expected: it remains 'OFF', the same as it was when that state was current
> 
>  2022-06-17_15-22-52.mp4

As I mentioned in standup, there is an issue now in review that includes this fix.  The PR covers two issue cards, one from @LWinterberg that duplicates this.

**Comment by Paul-Licameli** [comment]
@dozzzzer Issue #3095 duplicates the report of the remaining problem

**Comment by pietro68** [comment]
> 

> The on/off states of the buttons should all be independently variable, and persistent if you save a project, close, reopen it.
> 
> The Undo/Redo history should remember the last on/off states that were used when that state was current. On/off button changes should not make new undo states.
> 
> The buttons should be safely clickable during playback and you should hear the changes at once.
> 
> The master button should disable all effects on the track regardless of their separate on/off states.

All confirmed on `6d6b627`

**Comment by Ryan-Miller-Audacity** [comment]
Testing Completed.

Platform Information:
* Operating Systems: MacOS Monterey 12.3.1 and Windows 10

Main Testing Completed:
* The following feature behaviors described above have been implemented:
   * Each effect has its own button, and each track has an indpendent master button
   * The on/off states of the buttons are all independently variable and persistent when saving and reopening projects 
   * The undo/redo history remembers the last on/off states that were used when the state was current 
      * On/off button changes do not make new undo states
   * The buttons are clickable during playback and the changes are applied immediately
   * The master button disables all effects on the track regardless of their separate on/off states
* Testing included use of Reverb/Wahwah as well as AudioUnit effects 
* Power button behaviors worked consistently on a per track/per effect basis
* Undoing/Redoing of effect additions/changes works as expected and recalls the correct state of the power button for effects/master power buttons 

Bugs
* No bugs reported.
