### ISSUE TITLE
Effect dialog accessed from main Effects menu always modal and destructive only

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#2987]
As agreed with design team:  the old user interface for accessing realtime effects -- as a project-wide not per-track list, and limited to one effect only -- will be suppressed in favor of the new sidebar.

Old behavior was that the effects dialog is modal and can only apply effects destructively (though there is also the Preview button to calculate results and let you listen first before applying) -- but with exceptions for realtime-capable effects, in which case, the dialog is non-modal and does not exclude other editing of the project.

New behavior will make all effect dialogs modal when accessed this way.

Renabling a master effects list is future enhancement.

Must make sure:
- [ ] realtime capable effects, accessed from menus, are disabled during playback like other effects

**Comment by dozzzzer** [comment]
During the playback, many plugins of different families appear to be available, though they cannot be selected of course. This looks pretty confusing and needs to be fixed.

<img width="400" alt="image" src="https://user-images.githubusercontent.com/70063970/186372015-2d70a985-c47c-4328-89c3-ff067a9129a9.png">
<img width="400" alt="image" src="https://user-images.githubusercontent.com/70063970/186372105-a5a07f3f-5b1c-4370-99bc-6f2ad4bf8ab5.png">
<img width="400" alt="image" src="https://user-images.githubusercontent.com/70063970/186372215-df9a2d23-745a-46a8-9817-d7d4a736074c.png">
