### ISSUE TITLE
missing plugin behavior spec

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#3001]
The sidebar design includes: "In circumstances when a plugin can not be found, the text ‘(missing)’ should be used after the effect name. Note that the settings button in disabled in this instance"

That is, in case a project is saved with a stack referring to an effect, which is no longer available when the project is reopened on a system without that effect installed.

**Comment by Ryan-Miller-Audacity** [comment]
There is an additional issue present related to this ticket. When loading a project with LADSPA effects included the effect stacks UI. 

When the project is loaded, the LADSPA effects will inappropriately marked as "missing" even though they are still present/enabled. 

Steps to reproduce: 
1. Start a project and add some sound
2. Add a couple of effects via the Stackable effects UI (make at least one a LADSPA plugin effect and one a native Audacity effect)
3. Save the project and close audacity
4. Open Audacity and open the project you created
5. Note that the native Audacity effect is listed properly in the Stackable effects UI
6. Note that the LADSPA Plugin effect is listed as "_effect name_ (missing)". You can double check the plug in manager and note that the LADSPA plug is present and enabled (ie not missing)

**Comment by Ryan-Miller-Audacity** [comment]
Retested this after triaging session and am no longer seeing the described issue above with LADSPA plugins. Closing and removing from team board.
