### ISSUE TITLE
AudioUnits: sliders positions are forgotten

### ISSUE THREAD

**Issue by pietro68** [audacity/audacity#3012]
**Describe the bug**
Since commit `6a5645` (on master), AudioUnit effects seem to ignore UI sliders positions, until a nudge to them is given while playing.

**To Reproduce**
0. Delete pluginsettings.cfg before you start Audacity
1. generate a mono track with noise
2. instantiate an AudioUnit AUGraphicEQ
3. select 10 bands configuration, press the button to reset all sliders to 0dB
4. bring down the 1khz slider completely
5. start playback (using the main transport toolbar)

**Actual behavior**
The output is unaffected, however as soon as you move the 1Khz slider even slightly, it starts to be affected.
When pressing stop and then play again, the output will be again unaffected, until the 1Khz slider is again nudged.

**Expected behavior**
Output should be affected by the slider position, without having to nudge it while playing.

**Additional information (please complete the following information):**
 - OS: MacOS 
 - Version: local build done on commit # in description

**Additional context**
Update from Paul: The bug happens if you start with empty PluginSettings.cfg.  But if you make a destructive application of the effect (no matter what settings), then thereafter the bug doesn't happen, and neither does it happen after a restrart.

**Comment by Ryan-Miller-Audacity** [comment]
Testing Completed.

Platform Information:
* Operating Systems: MacOS Monterey 12.3.1

Main Testing Completed:
* Bug as described above has been fixed. 
* AUGraphicEQ stil lfunctions as expected
* Slider changes properly effect playback when utilizing the main transport bar
* Other AU Effects are still working as expected as well
 
Bugs:
* No bugs reported.
