### ISSUE TITLE
Scrub ruler and play indicator not displaying correctly

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#3013]
This problem bisects to commit 5835ae5d87f195ce0e2e8b985586b2ed45c4e1ca which was a preparation for the side bar interface.

- Start program, make some sound
- View > Toolbars > Scrub Toolbar (on)
- Press the third button of the bar, the toggle that shows and hides the ruler
- Play sound; observer the green play head line; stop
- Repeat last, with toggle button up

Observe:  The bottom of the ruler changes appearance slightly, but the scrub zone is only a few pixels high, and the scrub cursor isn't available just from mouse movement over it.

Observe:  The top of the green play head line is too low

Alternative steps:  Don't show the Scrub Toolbar, but use Transport > Scrubbing sub-menu to toggle it

**Comment by Paul-Licameli** [comment]
A second screen shot on macOS, with the toggle down for the scrub ruler.  There is a subtle one or two pixel change in the height of the ruler only.  I can't position my mouse anywhere for the hit test result that changes the play head to the green double-headed scrubbing arrow.  I can do scrubbing if I use the toolbar buttons.

<img width="200" alt="Screen Shot 2022-06-06 at 9 47 06 AM" src="https://user-images.githubusercontent.com/11670369/172174006-5c56c506-8fce-4b8b-9e58-67ecf326e5ff.png">

**Comment by Paul-Licameli** [comment]
Compare with how it appears when I build commit ec5f272803ab4c524256569a37e6d8fb7c476187, one before the blamed commit.  As it also appears in 3.1.3.

<img width="270" alt="Screen Shot 2022-06-06 at 10 04 08 AM" src="https://user-images.githubusercontent.com/11670369/172176763-2d85ae94-2224-4cb0-8bf8-1aa1803b8537.png">
<img width="362" alt="Screen Shot 2022-06-06 at 10 03 55 AM" src="https://user-images.githubusercontent.com/11670369/172176759-c9d9cf44-350a-474c-a7db-60d4fd015c5b.png">

**Comment by petersampsonaudacity** [comment]
> First screen shot, on macOS, with the scrub ruler off. Observe that the green line does not extend to the top of the white area.

@Paul-Licameli  - I reported similar in a different thread some days ago.  And similar happens when recording. 

_I'll try to find that report - but it may have been on Discord_

**Comment by Paul-Licameli** [comment]
I discovered the problem incidentally when rewriting our uses of threads.

**Comment by Paul-Licameli** [comment]
> The shortened green and red cursor lines that do not reach up to to the Timeline ahould probably be listed as a new bug., do you want me to do that?
> 
> Recording looks worse than playback as the red line is ahead of the waveform being drawn.

I unite it all in one issue because the same commit caused both and that may likely be fixed with a common commit.  There is some problem with 2d screen geometry and maybe the refreshing of windows.

**Comment by DavidBailes** [comment]
@Paul-Licameli . I didn't ask to be assigned to this issue! Please unassign me.

**Comment by Paul-Licameli** [comment]
> @Paul-Licameli . I didn't ask to be assigned to this issue! I'm going to unassign myself.

The assignment was only a convenience for maintaining our projects board, and seeing easily who worked on what by the associated icons.  It implied no demand on my part that you do anything more.  But if you object I won't do this again.

Thank you for the fix!

**Comment by Paul-Licameli** [comment]
Because I expect your #2913 to be a fix for this issue also.

**Comment by DavidBailes** [comment]
> Because I expect your #2913 to be a fix for this issue also.

Alas, it won't be. My fix only changes the location of a track which Audacity provides  to any assistive technology.

**Comment by crsib** [comment]
I'll take a look

**Comment by DavidBailes** [comment]
> looks like it's wrong, but used to accidentally work before the reparenting. (No testing done to check this!)

It is and has a simple fix:
https://github.com/audacity/audacity/pull/3159

**Comment by petersampsonaudacity** [comment]
Testing on w10 with latest master:  audacity-win-3.2.0-alpha-20220704+679d6b6-x64-msvc2022

I confirm that the "gap" is now gone  (looks much better)

**Comment by dozzzzer** [comment]
I'm verifying the build from https://github.com/audacity/audacity/pull/3161 and I'm still seeing the green line not aligned vertically, i.e. 'the gap' still persists:
<img width="307" alt="image" src="https://user-images.githubusercontent.com/70063970/177298032-a0c7cadb-53ab-41ec-8716-e1fc37d6e202.png">
