### ISSUE TITLE
UI improvements to Stackable effects

### ISSUE THREAD

**Issue by AnitaBats** [audacity/audacity#3019]

**Comment by Paul-Licameli** [comment]
Is the Effects button meant to work as a toggle -- press it again, hide the side bar?

Present behavior is that it shows the side bar, then does nothing if you press it again.

**Comment by Ryan-Miller-Audacity** [comment]
Testing Completed.

Platform Information:
* Operating Systems: MacOS Monterey 12.3.1 and Windows 10

Main Testing Completed:
* Improvements noted above have been completed
* No defects/issues with the updated elements 
 
Bugs:
* No bugs reported.
