### ISSUE TITLE
Stereo tracks play too loud

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#3022]
**Describe the bug**
Stereo tracks play too loud

**To Reproduce**
1. Add a stereo track
2. Generate a tone (default settings)
3. Play
4. Observe that the tone plays so loud that it clips, and the playback meter indicates clipping.

**Actual behavior**
The tone plays so loud that it clips, and the playback meter indicates clipping.

**Expected behavior**
The tone to play at the correct level

**Screenshots**
**As expected in build deaa3f**
![3 2 0 deaa3f](https://user-images.githubusercontent.com/11681097/171842444-1cfea59e-b1ce-4c74-aae8-bb545ad21241.png)

**Bug in build 2b5fa3**
![3 2 0 2b5fa3](https://user-images.githubusercontent.com/11681097/171842543-8da4d750-7c4d-4906-9b79-faee51d578c0.png)

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version Audacity 3.2.0 alpha

**Additional context**
This bug makes Audacity virtually unusable for stereo audio.

**Comment by petersampsonaudacity** [comment]
Confirmed on W11 with latest alpha master:  audacity-win-3.2.0-alpha-20220603+ab8ed63-x64-msvc2022

### Playing default momo tone - level is as expected
![image](https://user-images.githubusercontent.com/50205984/171879717-54b23403-1e25-4fe9-bf46-2836765fb58c.png)

### Playing default stereo tone - audio clips
![image](https://user-images.githubusercontent.com/50205984/171880143-ef78d54c-765d-46da-9b87-5a80d2fd12bb.png)

**Comment by petersampsonaudacity** [comment]
Testing shows that this is a regression on 3.1.3

![image](https://user-images.githubusercontent.com/50205984/171880733-a6ef1b62-c1fb-4759-a90a-d06da7de1928.png)

**Comment by petersampsonaudacity** [comment]
This is probably the same underlying bug as:   With 3.2.0 the output signal is hotter than with 3.1.3 (distortion can occur) #2703 

But it gives a good use  case seet of steps to reproduce #2703

**Comment by Paul-Licameli** [comment]
Bisected to 8387eac9ed3c4c7a14e8d95e65c3b4c4128cd6a5

**Comment by petersampsonaudacity** [comment]
Testing on W10 with alpha master audacity-win-3.2.0-alpha-20220809+356ddd9-x64-msvc2022

I confirm his appears to work correctly on W10 - I will test on W11 tomorrow when I get to see my W11 laptop in Zurich

**Comment by petersampsonaudacity** [comment]
And tests fine in W11 with latest alpha master  -  audacity-win-3.2.0-alpha-20220809+6f6501c-x64-msvc2022
