### ISSUE TITLE
Huffman Data Overrun (v3.1.3), Redux

### ISSUE THREAD

**Issue by pavakhov** [audacity/audacity#3029]
.**Describe the bug**
Audacity refuses to open mp3 files, reporting "Import Failed", or "Huffman data overrun".  Every other player/editor tested opened/edited the files without any hint of a problem.  *Just Audacity*

This is still an issue, with v.3.1.3.  (Alpha build is old, from July 2021 v3.0.3):
 Madplay (which also uses the libmad library) reports "Huffman data overrun" on Frame0 or Frame2 of an mp3 file created from an Icecast stream using ffmpeg.  This has an impact for staff reviewing/editing of hourly airchecks recorded at a radio station.

**To Reproduce**
1. I can send a link to a problematic file.
2. Open/Import Audio mp3 file
3. Error dialog box opens, refusing to open a perfectly fine mp3 file.

**Actual behavior**
File is not opened

**Expected behavior**
Open mp3 file with or without a warning.

**Screenshots**
This is known behaviour, righteously identified as desired since libmad reports the error.  

**Additional information (please complete the following information):**
 - OS:Windows 10, Debian Bookworm, OS x 
 - Audacity V. 3.1.3 (and v2.4.2 etc...)

**Additional context**

**Comment by petersampsonaudacity** [comment]
Possibly the same as (or a close cousin of) this previously logged issue: 
Audacity doesn't recognize a mp3 file even though it's a mp3 file. #2634

**Comment by pavakhov** [comment]
Hi - thanks for the response.  I looked into this a bit more, and the following from the 'madplay' man page, I think, is relevant: 

> error: frame #: bad main_data_begin pointer
>               This  message  can occur while decoding a Layer III stream that has been cut or spliced without preserving its bit reservoir. The affected frame cannot be properly decoded,
>               but will be used to help restore the bit reservoir for following frames.
> 
Since I am creating an mp3 file from a continuous stream, the bit reservoir may be lost.  Same thing can happen with ffmpeg and the copy codec:
> ffmpeg -i in_file.mp3 -acodec copy -ss $start_time -t 1 out_file.mp3
Using 'madplay -v' on the result often results in a 'Huffman data overrun' error.

If the original file, 'in_file.mp3' is encoded without a bit reservoir:
> lame -b 128 --nores  in_file.wav nores_file.mp3
Then I never see this error when trimming an mp3 file loss-lessly as above with ffmpeg

In addition, enaming an mp3 file as mp4 seems to force Audacity to use a different decoding path, and files can be opened.

**Comment by LWinterberg** [comment]
we should really stop using mad in favor of something that breaks less and still is maintained (ie mpg123, #2236)
