### ISSUE TITLE
Developer Guide Has Typo

### ISSUE THREAD

**Issue by superelitist** [audacity/audacity#3046]
**Describe the bug**
This passage 

> (typically 14400 audio samples per second)

From the Intro section of the [Developer Guide](https://wiki.audacityteam.org/wiki/Developer_Guide) is most likely a typo. I suspect that the intended number is 44,100.

**To Reproduce**
Visit https://wiki.audacityteam.org/wiki/Developer_Guide

**Actual behavior**
The specified number is incorrect.

**Expected behavior**
The correct number.

**Comment by petersampsonaudacity** [comment]
Fixed:  https://wiki.audacityteam.org/wiki/Developer_Guide#Intro

Thanks for the report
