### ISSUE TITLE
Clicking effect name in sidebar to replace

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#3050]
Clicking name of an effect in the sidebar should bring up a menu to replace it with another.

The change should also be undo-able.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest 3.2.0 alpha master audacity-win-3.2.0-alpha-20220608+a2b9986-x64-msvc2022

Clicking name of an effect in the sidebar **_does_** bring bring up a menu - bit it does not make the replavement if to click on an alternate effect.

![image](https://user-images.githubusercontent.com/50205984/172894375-e603f79d-e6e5-4d47-a7a6-05ff8a05506b.png)

**Comment by dozzzzer** [comment]
Verified on Windows 11 and MacOS Monterey.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest alpha master:  audacity-win-3.2.0-alpha-20220704+679d6b6-x64-msvc2022

I confirm this now works on W10
