### ISSUE TITLE
Saved project duplicates the Effects Stack of stereo tracks on reopening

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#3055]
**Describe the bug**
A Saved project duplicates the Effects Stack on reopening

**To Reproduce**
1. Get some audio
2. Click the TCP Effects button
3. Add some effects to the stack - _see Screenshot 01_
4. Save the project
5. Exit Audacity
6. Relaunch Audacity
7. Click the TCP Effects button
8. Observe: the Effects Stack has duplicate copies of the effects added in Step 3 - _see Screenshot 02_

**Expected behavior**
The effect stack not to have duplicates

**Screenshots**
### 01 Project before being Saved
![image](https://user-images.githubusercontent.com/50205984/173187106-d321c372-08bd-43ab-8ed1-8c6fe5d8b6d3.png)

### 02 Project after being saved, Audacity closed and project reopened
![image](https://user-images.githubusercontent.com/50205984/173187196-d1346649-777e-420b-9c7f-e13666ac2eac.png)

**Additional information (please complete the following information):**
 - OS: Windows 10] - but assume all OS
 - Version: latest 3.2.0 alpha master audacity-win-3.2.0-alpha-20220610+ecc8de8-x64-msvc2022
 - and Paul's latest Effects Stack branch  audacity-win-3.2.0-alpha-20220610+6a52dc3-x64

**Additional context**
None

**Comment by Paul-Licameli** [comment]
I can't do exactly as in the picture when I start with clean PluginSettings.cfg.  I can choose only Reverb and Wahwah from Audacity's built-ins.

**Comment by Paul-Licameli** [comment]
Did you actually create and save the project in some earlier alpha version?

**Comment by petersampsonaudacity** [comment]
> Did you actually create and save the project in some earlier alpha version?

No:  Version: latest 3.2.0 alpha master audacity-win-3.2.0-alpha-20220610+ecc8de8-x64-msvc2022

**Comment by Paul-Licameli** [comment]
I think this happens only for stereo tracks.

**Comment by petersampsonaudacity** [comment]
Testing with latest master alpha: audacity-win-3.2.0-alpha-20220611+85e29b6-x64-msvc2022

I no longer see this problem - this is what it looks like now after steps 7-8

![image](https://user-images.githubusercontent.com/50205984/173191391-d2d05c35-7d4a-4dcf-a7a1-f45f9086d56e.png)

**Comment by Paul-Licameli** [comment]
And you just re-tested with a mono track, so you did not see the problem.  But try stereo.

There is a one line fix for this and I am making a PR.

**Comment by petersampsonaudacity** [comment]
@Paul-Licameli  - yes you're right. it still fails with a stereo track

![image](https://user-images.githubusercontent.com/50205984/173192383-d072bf31-6eb4-4b97-98a5-56f6a61d7d7e.png)

**Comment by petersampsonaudacity** [comment]
@Paul-Licameli   -  yes, testing with your latest branch V

with a stereo track project this now appears to work fine

**Comment by Ryan-Miller-Audacity** [comment]
Testing Completed.

Platform Information:
* Operating Systems: MacOS Monterey 12.3.1 and Windows 10

Main Testing Completed:
* Effects from stackable effects UI are no longer doubled when opening projects
* Saved/added effects are properly retained including their settings
* The above was confirmed for both Mono and stereo tracks 

Bugs:
* No bugs reported.
