### ISSUE TITLE
3.1.3.0 freezes on ogg-opus import on OSX running on M1

### ISSUE THREAD

**Issue by monochromec** [audacity/audacity#3057]
**Describe the bug**
After a few seconds Audacity locks up when importing an opus file on Apple Silicon.

**To Reproduce**
1. Start Audacity
2. Import an opus file 
**Actual behavior**
Audacity froze.

**Expected behavior**
Normal import

**Additional information (please complete the following information):**
 - OS: OSX 12.4 on Apple Silicon
 - Version: 3.1.3.0

Process sample at https://gist.github.com/monochromec/7f89ffb3dee1d9f52c530cbd0145baec  - happy to provide more info if required

This is an X86-64 build running on Rosetta 2.

**Comment by monochromec** [comment]
Perhaps it's time for a universal build for OSX (cf. https://github.com/audacity/audacity/issues/684 ).

**Comment by LWinterberg** [comment]
arm64 and universal mac builds are available in the current alpha (check the Actions tab). 

That said, importing opus on mac not working is a known bug (#1515), and we'll add a native import (instead of FFMPEG) eventually (#443)

**Comment by crsib** [comment]
After some examination I have to say that this is actually a different issue, not related to FFmpeg. 

Opus in OGG container (opposed to Opus container) is handled by libsndfile and looks like there is a bug there

**Comment by monochromec** [comment]
Can be closed as this has been fixed in 3.2.1.

**Comment by jadenquinn** [comment]
> Can be closed as this has been fixed in 3.2.1.

Bullarky, I had this issue yesterday and I'm not even on an M1 Sackbook.

**Comment by crsib** [comment]
@dozzzzer why you have reopened this issue?
