### ISSUE TITLE
Some effect previews stall

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#3058]
- make some sound, select all
- open a realtime-capable effect, for example Reverb, from the drop-down
- Hit the "Start Playback" button of the effect dialog
- Hit Apply

Observe:  a stall of a few seconds before playback stops and the effect applies destructively (this might vary with operating system?)
Expect: prompt stop before effect applies

**Comment by dozzzzer** [comment]
Verified on MacOS 12.3.1. and Win 10 x64.
