### ISSUE TITLE
Realtime effect plays correctly only once

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#3060]
- make some sound, like a generated rhythm track
- open sidebar and add Reverb
- play, and click either power button on and off: hear what you expect
- stop
- play again

Expect:  same sound
Observe:  variously silence or a buzzing

This is what I observed in a debug build on Mac.  Details may vary with operating system.

Undo then redo seems to clear the problem and allow one more good playback.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest alpha master:  audacity-win-3.2.0-alpha-20220614+27ad8e9-x64-msvc2022

WORKS-FOR-ME  I fail to observe this issue, works as expected.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @Paul-Licameli 's branch build - Fix inability to play the effect stack on a track more than once... Build Audacity #1584
https://github.com/audacity/audacity/actions/runs/2497463745

This now works correctly on Paul's branch

**Comment by petersampsonaudacity** [comment]
And works correctly on W10 with latest alpha master:  audacity-win-3.2.0-alpha-20220615+147cb0d-x64-msvc2022

**Comment by dozzzzer** [comment]
@Paul-Licameli 
When the effect is turned off during the playback, it leaves some "residual" tail of audio.
It can be properly observed on a DTMF tones track where signal and silence are alternating.
So the trick is to start playback having the effect turned on and then turn it of in the middle of the playback of the tone:

https://user-images.githubusercontent.com/70063970/174297861-4c81bcc0-4d38-423c-b22a-c96fb186e8c7.mp4

And then, when clicking the toggle again during the silence part, you can hear audible "tail" while there should be silence.

**Comment by Ryan-Miller-Audacity** [comment]
@Paul-Licameli / @dozzzzer If this is in the done column of the board and it appears that the issue reported during QA has been created to be tracked separately, this issue can be closed correct?
