### ISSUE TITLE
Reverb "wet only" checkbox applies to play in progress only when dialog closes

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#3061]
Update:  Actually, this is a problem very specific to just this one checkbox.  No such problem with the "dry gain" slider, for instance.

- Generate a click track, open the side bar, add Reverb
- Press play and listen
- While playing, press the gear wheel, and check WetOnly
- Press OK

Observe:  the sound really did change according to the settings, but only after OK
Expect: sound changes prompty when you check the box
Should also expect:  if you then Cancel, sound changes back to original settings

**Comment by Paul-Licameli** [comment]
I notice that I can repeat the procedure of opening the dialog, changing settings, and closing during one play-back.  That is some reassurance.  But there is the unexplained #3060

**Comment by pietro68** [comment]
I tried to reproduce the bug on a build of master, at f84dbec - by the time I press OK, an unhandled exception happens:

![image](https://user-images.githubusercontent.com/16491307/173291408-8cf201da-5b43-45ba-8c72-56d0dff2da13.png)
