### ISSUE TITLE
OSX build fails with "Multiple commands produce '/Users/...build/bin/Debug/Audacity.app/Contents/MacOS'"

### ISSUE THREAD

**Issue by monochromec** [audacity/audacity#3065]
**Describe the bug**
Build fails with above error message after following steps outlined in the build instructions for OSX.

**To Reproduce**
1. Clone the repo.
2. Run cmake and build project using XCode.

**Actual behavior**
Build fails

**Expected behavior**
Build succeeds

**Screenshots**
If applicable, add screenshots/video to help explain your problem.

**Additional information (please complete the following information):**
 - OS: OSX 12.4 running on M1 MBA 
 - Version: Audacity 3.1.3
 - Version XCode: 13.4.1 

**Additional context**
Happy to provide additional info.

**Comment by crsib** [comment]
3.1.3 can only be built using legacy build system. This issue is fixed in master though

**Comment by monochromec** [comment]
Thanks for the hint!
