### ISSUE TITLE
AudioUnits effects should monitor output

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#3069]
Example effect: AUDynamicsProcessor

PR #2940 restores output monitoring for the old non-modal effect dialog from the menus.

But when AU effects are fully working in the sidebar too, the dialog as opened from the sidebar will not update the output monitor at an acceptable rate, unless other work is done tracked by this issue.

**Comment by pietro68** [comment]
I tried `6d6b627` with AUDynamicsProcessor instantiated in the sidebar; both the plugin output meter and the audacity output meter seem to update at an acceptable rate.

**Comment by dozzzzer** [comment]
Testing MacOS build from https://github.com/audacity/audacity/pull/3129

The issue can still be reproduced: an AU plugin still doesn't monitor output signal properly.

STR:
1. load a track
2. select 'AUDynamicsProcessor' in the sidebar
3. start playback
4. click gear icon
5. observe output meter showing no value at all

Also, not sure if it's a related issue but the red pointer is moving in the bottom left area of the plugin window (please see the video):

https://user-images.githubusercontent.com/70063970/176450664-27d8e31a-4ed9-4ad1-a8b2-e057fe60861c.mp4

@Paul-Licameli please take a look into it and if the red cursor position issue isn't related, I'll log a separate ticket.

**Comment by Paul-Licameli** [comment]
@dozzzzer I think there is not really a remaining bug, except perhaps to figure out how to make the update rate of the panel better if possible (not immediate ideas).

It looks like you are using the dynamics processor on a rhythm track -- and that's simply not good input data for this kind of effect.

Try it instead with a recording of yourself counting to ten and it will look different.
