### ISSUE TITLE
Undoing Realtime effect from UI results in a crash

### ISSUE THREAD

**Issue by Ryan-Miller-Audacity** [audacity/audacity#3072]
**Describe the bug**
In testing of #2985, Undoing a realtime effect (not back to the default) and attempting to reopen the plugin's interface causes Audacity to crash. 

https://user-images.githubusercontent.com/88568755/173623910-5c99e794-0882-474b-8caf-b2e99a153fce.mp4

**To Reproduce**
1. Open Audacity
2. Generate a tone or import some audio
3. Add a realtime effect like Reverb or Wahwah via the Effects side panel
4. Click the gear icon and edit the settings then click "OK"
5. Edit the effect settings again (the crash does not appear to happen if the undo even reverts the effect back to its default settings)
6. Go to Edit -> Undo to undo your effect settings change
7. Click the gear icon to open the effect settings modal 
8. Audacity Crashes

**Actual behavior**
Audacity crashes when attempting to open the plugin interface via the Effects UI after undoing an effect change.

**Expected behavior**
User should be able to open the plugin interface via the Effects UI after undoing an effect change without crashing.

**Screenshots**
Screencast included in summary above.

**Additional information (please complete the following information):**
 - OS: Tested on MacOS Moneterey 12.3.1 and Windows 10 
 - Version: [Audacity 3.2.0-alpha-20220614 (commit id: fccf7dc)](https://github.com/audacity/audacity/actions/runs/2475100326) 
 - (if relevant) Sound Device: N/A
 - Related Pull Request: #2988 

**Additional context**
N/A

**Comment by petersampsonaudacity** [comment]
Confirmed on W10 with latest alpha master:  audacity-win-3.2.0-alpha-20220611+f84dbec-x64-msvc2022

And this is a silent crash with no crash report - and no "Phone home" error reporting/.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @Paul-Licameli 's branch build "Sidebar bugs":  https://github.com/audacity/audacity/actions/runs/2497329369

I still get the crash at Steps 7-8   -  but today though I get a crash report, it is not a "Phone Home" type one.
