### ISSUE TITLE
Editing sliders in Realtime Effects while playback is paused causes a deadlock

### ISSUE THREAD

**Issue by Ryan-Miller-Audacity** [audacity/audacity#3073]
**Describe the bug**
In testing of #2985, it was noted that attempting to edit sliders within the plugin interface while playback is paused will cause Audacity to deadlock and become unresponsive.

https://user-images.githubusercontent.com/88568755/173631959-b06b48fe-b6db-4459-85dd-b40ac247a79c.mp4

**To Reproduce**
1. Open Audacity
2. Generate a tone/add some audio
3. Add a realtime effect like Reverb or Wahwah via the Effects side panel
4. Start playback
5. Pause playback
6. Click the gear icon and attempt to edit the sliders in the interface
7. Audacity hiccups and becomes unresponsive (deadlock)
8. Note: You can edit the text values in the effect's interface without causing the crash so this appears to be directly related to the manipulation of the sliders

**Actual behavior**
Editing sliders when playback is paused results in a deadlock/unresponsive program.

**Expected behavior**
Users should be able to edit sliders in effect interfaces while playback is paused.

**Screenshots**
Screencast included in the summary above.

**Additional information (please complete the following information):**
 - OS: MacOS Monetery 12.3.1 and Windows 10
 - Version: [Audacity 3.2.0-alpha-20220614 (commit id: fccf7dc)](https://github.com/audacity/audacity/actions/runs/2475100326) 
 - (if relevant) Sound Device: N/A
 - Related Pull Request: #2988 

**Additional context**
N/A

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @Paul-Licameli 's branch build "Sidebar bugs":  https://github.com/audacity/audacity/actions/runs/2497329369

I still get the issue at Step 7 - so this is not fixed

**Comment by pietro68** [comment]
Verified it is fixed on `a3b3b53`

**Comment by petersampsonaudacity** [comment]
Tested on W10 with latest master audacity-win-3.2.0-alpha-20220623+2fd21af-x64-msvc2022

This works fine with no hiccups or unresponsiveness at steps 6-7

**Comment by dozzzzer** [comment]
Verified on Win10 and MacOS.
