### ISSUE TITLE
"Redoing" a realtime effect results in a crash

### ISSUE THREAD

**Issue by Ryan-Miller-Audacity** [audacity/audacity#3074]
**Describe the bug**
In testing of #2985, it was noted that after undoing and then redoing an effect attempting to open the effect settings in the Realtime Effect UI results in a crash.

https://user-images.githubusercontent.com/88568755/173657163-ba951b33-6083-4c35-a7a9-6598595f707a.mp4

**To Reproduce**
1. Open Audacity
2. Generate a tone/add some audio
3. Add a realtime effect like reverb or wahwah via the effects side panel
4. Click the gear icon, edit the sliders for the effect, and click OK
5. Go to Edit -> Undo
6. Click the gear icon and note the changes were undone
7. Go to Edit -> Redo
8. Click the gear icon
9. Audacity Crashes

**Actual behavior**
Audacity crashes when attempting to open realtime effect settings after "redoing" a previously undone effect

**Expected behavior**
Users should be able to open the effect settings after redoing a previously undone effect

**Screenshots**
Screencast included in the summary above.

**Additional information (please complete the following information):**
 - OS: MacOS Monetery 12.3.1 and Windows 10
 - Version: [Audacity 3.2.0-alpha-20220614 (commit id: fccf7dc)](https://github.com/audacity/audacity/actions/runs/2475100326)  
 - (if relevant) Sound Device: N/A
 - Related Pull Request: #2988 

**Additional context**
N/A

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @Paul-Licameli 's branch build "Sidebar bugs": https://github.com/audacity/audacity/actions/runs/2497329369

I still get the crash at Steps 78-9 -  I get a crash report but it is not a "Phone Home" type one.

**Comment by petersampsonaudacity** [comment]
Tested on W10 with latest master audacity-win-3.2.0-alpha-20220623+2fd21af-x64-msvc2022

This works fine with no crash

**Comment by dozzzzer** [comment]
Verified on Win10 & MacOS
