### ISSUE TITLE
Effects menu entries

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#3076]
- [x] Rename "Add/Remove Plug-Ins" to "Plugin Manager". NB: This may need to be done for the Generate/Analyze/Tools menu, too.
- [x] Add new option "Add Realtime Effects" which opens the effects panel for the currently focussed track.

**Comment by Paul-Licameli** [comment]
Note that the first task affects also the Generate, Analyze, and Tools menus too.
The second might affect only Effects, but there are also some plug-ins that are analyzers, not properly effects.  For instance: https://www.maat.digital/gon/

**Comment by Paul-Licameli** [comment]
Question @LWinterberg :  Were you assuming the new menu items should end with "..." as the old ones did?  Just changing words?  After all it is the convention meaning that a dialog will open up.

But @ksoze95 took your specification literally and left off the "..."

**Comment by LWinterberg** [comment]
Microsoft recommends: 

> This doesn't mean you should use an ellipsis whenever an action displays another window only when additional information is required to perform the action. For example, the commands About, Advanced, Help, Options, Properties, and Settings must display another window when clicked, but don't require additional information from the user. Therefore they don't need ellipses.

-- https://docs.microsoft.com/en-us/windows/win32/uxguide/cmd-menus#using-ellipses

IMHO for "Add/Remove Plug-Ins..." the ellipsis was necessary as the action requires more input from the user, but for "Plugin Manager" it is not - clicking opens the manager.

**Comment by ksoze95** [comment]
I jumped the gun and reintroduced the "..." 🤦  Will fix up my commit again.

**Comment by LWinterberg** [comment]
Fwiw, I just noticed that this is inconsistent with some other menu items (like Preferences...) - I'll bring the other entries in like with this later.

**Comment by petersampsonaudacity** [comment]
@LWinterberg for Consistency in Audacity the "plugin" should be hyphenated i.e. the menu entry should be "Plug-in Manager"

See Connie:  https://alphamanual.audacityteam.org/man/Consistency_in_wording_and_punctuation_in_Audacity

And note that "Plug-ins" is hyphenated in the Plug-in Manager dialog.   Perhaps the dialog should be re-titled to "Plug-in Manager"
![image](https://user-images.githubusercontent.com/50205984/178113186-c13c5e43-00e6-4b91-beeb-8c9c9861b28e.png)


Do you want to re-open this or should I raise a new issue for this.

**Comment by LWinterberg** [comment]
"plugin" overtook "plug-in" as the preferred spelling in 2013 https://books.google.com/ngrams/graph?content=plug-in%2Cplugin%2Cplug-ins%2Cplugins&year_start=1990&year_end=2019&corpus=26&smoothing=0&case_insensitive=true


IMHO at this point we should be updating the strings instead.

**Comment by petersampsonaudacity** [comment]
> IMHO at this point we should be updating the existing strings to "plugin" instead of reopening this issue.

@LWinterberg  Whichever spelling form you choose _(and it is your choice)_ what is important is that consistency is maintained, particularly throughout the app.  The app as it stands right now has both the un-hyphenated and hyphenated form.

If you opt for the un-hyphenated form then the trickiest thing to change could well be the **Plug-Ins** folder in the audacity settings folder, as changing this could have implications for upgraders from older versions of Audacity

![image](https://user-images.githubusercontent.com/50205984/178227967-9170d16e-587f-4458-9406-3e2cf4a2a120.png)

**Comment by petersampsonaudacity** [comment]
@LWinterberg  do we need a new issue for the plugin/plug-in inconsistencies ?

**Comment by LWinterberg** [comment]
https://github.com/audacity/audacity/pull/3208 @petersampsonaudacity :)

**Comment by dozzzzer** [comment]
@LWinterberg 
should the menu item "Add Realtime Effects" get grayed out once it has been clicked and the sidebar was opened? And the other way around, get enabled back again once the sidebar is collapsed?
<img width="834" alt="image" src="https://user-images.githubusercontent.com/70063970/178343566-178b31ef-0e1b-4d58-bc4f-4d419e33ab84.png">

**Comment by Tantacrul** [comment]
I fancy that it should also toggle / un-toggle the sidebar. I guess there's an argument that it shouldn't be called **Add** Realtime Effects... but we can change that later if we feel it is weird.

**Comment by ksoze95** [comment]
@Tantacrul Opened #3215 for menu "Add Realtime Effects" to toggle the sidebar.
