### ISSUE TITLE
Audacity crashes when a VST2 plugin exists in the realtime panel

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#3077]
**To Reproduce**
1. Install some VST2 plugins - I have ReaPlugs and GVST, you can get them from https://plugins.audacityteam.org/real-time-effects/plugin-suites :) 
2. Start Audacity
3. Make a track
4. Click the "Effects" button
5. Click the "Add Effects" button in the panel

**Actual behavior**
Audacity crashes

**Expected behavior**
Audacity shows me the plugins I just installed

**Additional information (please complete the following information):**
 - OS: Windows 11
 - Version current master as well as  90e442f (the build from #3068)

**Additional context**
Even if I disable all ReaPlugs/GVST plugins except one, it still crashes. They do not crash in OBS.

**Comment by LWinterberg** [comment]
Update: Clearing the entire configuration manually (deleting the 3 .cfg files) fixed the issue. 

@dozzzzer, @Ryan-Miller-Audacity, can you two please test some more to figure out if it was just my config (it featured lots of dead plugins in the registry as it made new entries for plugins every time I used another branch build), or if this is something that can happen generally if you switch between 3.1.3 and 3.2?

**Comment by LWinterberg** [comment]
oh, actually i did, it gave me the option to in the crash window
[Audacity_dbgrpt-42488-20220615T154123.zip](https://github.com/audacity/audacity/files/8910428/Audacity_dbgrpt-42488-20220615T154123.zip)

**Comment by dozzzzer** [comment]
Couldn't reproduce both with GVST and ReaPlugs

**Comment by dozzzzer** [comment]
Exactly. I should have also added in my comment that none of the VSTs were present in the sidebar even though they were accessible via Effect menu. Only built-ins and LADSPA were present in the Realtime effects side panel.
