### ISSUE TITLE
ffmpeg dll "avformat-55.dll" integration does not work

### ISSUE THREAD

**Issue by kosuodhmwa** [audacity/audacity#3080]
Version: Most current release version on 2022-06-15
Windows Version: Windows 10 Pro x64 most current release version on 2022-06-15

![image](https://user-images.githubusercontent.com/24782840/173869310-cd9437a7-b39a-4738-b7ab-7a519cbf8d88.png)

-> DLL ist attached as a .zip file...

[avformat-55.zip](https://github.com/audacity/audacity/files/8910970/avformat-55.zip)

Problem: Doesn't work. Always shows " ... was not found".

Why?

Thanks in advance for your feedback(s).

With kind regards from Switzerland,
Jan

**Comment by kosuodhmwa** [comment]
I can also capture a vid if you need then put it on YT...

**Comment by kosuodhmwa** [comment]
Same issue with that file...
[avformat-55.dll-62787.zip](https://github.com/audacity/audacity/files/8911033/avformat-55.dll-62787.zip)

**Comment by kosuodhmwa** [comment]
Finally got that s**t here...
-> https://master.dl.sourceforge.net/project/greenapps/Other/ffmpeg-win-2.2.2.zip?viasf=1

**Comment by LWinterberg** [comment]
for future reference, you need not just the avformat file but a complete ffmpeg installation.
