### ISSUE TITLE
Audio setup toolbar: menu items do not have access keys

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#3084]
**Describe the bug**
The items on the menu which is opened from the Audio setup toolbar do not have access keys.

**To Reproduce**
1. Open the audio setup menu on the audio setup toolbar

**Actual behavior**
The items on the menu to not have access keys

**Expected behavior**
The items on the menu have access keys

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version Audacity 3.2.0 alpha

**Comment by LWinterberg** [comment]
It works just fine if you navigate to it with the keyboard: 

1. press Ctrl+Shift+F6 to move the focus up into the toolbars
2. Tab until you get to the audio settings
![image](https://user-images.githubusercontent.com/87814144/174131918-84b079f5-40a4-457e-9181-c98debb24ba9.png)
3. press enter to open the menu
![image](https://user-images.githubusercontent.com/87814144/174132617-94a29edf-1dc7-4c1d-86de-8c8caf24bba8.png)
