### ISSUE TITLE
Change undo messages of effects panel

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#3092]
“Undo Add `effect name`”, long: “Added `effect name` to `track name`”
”Undo Remove `effect name`”, long: “Removed `effect name` from `track name`”
“Undo Change effect order”, long: “Moved `effect name` (up|down) in `track name`”
“Undo Change `effect name`”, long: "Changed `effect name` in `track name`"
“Undo Replace `old effect name`”, long: “Replaced `old effect` with `new effect`”

with the short version showing up in the Edit menu and the long version in the View > History... window

**Comment by Paul-Licameli** [comment]
@LWinterberg To be consistent with most existing strings, the long should be a part-tense (like "Replaced") and the short should be an imperative (as you specified).  I amended the top comment.

I just looked through the code and found a few existing ones that don't follow the convention.  There should be another issue to fix the inconsistencies.
