### ISSUE TITLE
retain bypass in the effect panel for undo

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#3095]
STR

1. Add a real-time effect
2. Add another real-time effect
3. bypass (turn off) both effects
4. Undo
5. Redo

**expected behavior**

4: the effect added in 2. is removed; The remaining effect is turned on
5: Both effects are turned **off**

**actual behavior**

4: the remaining effect is turned on
5: both effects are turned **on**

**Comment by Paul-Licameli** [comment]
One of my waiting PRs includes the fix for this

**Comment by pietro68** [comment]
Expected behavior was observed in `6d6b627`:

**Comment by Ryan-Miller-Audacity** [comment]
Verified in conjunction with testing of [#2986](https://github.com/audacity/audacity/issues/2986)
