### ISSUE TITLE
Make realtime effects settings non-modal

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#3102]
A user must be able to have multiple effects settings open, change the settings and jump around their project to get things just right. As such, the realtime effects settings windows cannot be modal. 

Cases to test, in which the user performs other editing actions, which should cause the dialog to close:

- track is deleted
- Effect on the track is deleted or replaced
- Undo or redo causes the track or the effect to disappear

(The first and third of these are blocked during playback, but there is not necessarily playback while the non-modal dialog is open.

The second should be safe during playback, but, test it!)

Case to test, which should cause an update of the dialog:

- undo or redo changes the effect settings

Design questions about cases where you don’t hit the apply button:

- If I drag sliders, undo, redo — should I get the same slider settings back, though there is no distinct undo history item made for this?  (Which would be similar to the treatment of the power button)
- Ditto in case of drag, redo, undo
- Ditto, if I drag sliders, do some unrelated undo-able edit, undo, redo.

Other cases to test:

- a repeated press of the cogwheel while the dialog is open should do nothing (not open a duplicate dialog)
- if we decide to disallow the dialog during recording, it must be closed when recording begins
- If we permit the dialog during recording (maybe you are overdubbing?), the undo/redo history should keep applied settings changes separate from, and previous to, the recording, even though parts of the recording happen before the hits of the apply button.  In other words, to undo the “Record” item should undo all of it, not just a late part of it.

**Comment by Paul-Licameli** [comment]
@LWinterberg @Tantacrul @Ryan-Miller-Audacity @dozzzzer I updated the description of this issue with the non obvious requirements and I don’t know if this is exhaustive yet.

I agree that non-modality and multiple simultaneous dialogs would be desirable but it will not be very simple.

The previously existing real time effect dialog is in fact non-modal but did not have all of these difficulties because it only managed a one-deep stack of effects, associated with the whole project and not with any one track, and did not require undo and redo of changes.  And even then, I’m not confident that it was ever thoroughly tested and bug free.

**Comment by LWinterberg** [comment]
Aye. Let's have it out-of-scope for this release and look at it for a later release.

**Comment by Tantacrul** [comment]
I think we need to just test the build when it is ready for user testing and then figure out if non-modal dialogs are essential or not. My guess is that they won't be absolutely essential but we may get really bad feedback that changes our mind.

**Comment by crsib** [comment]
I don't think that the dialog should handle Undo/Redo. As a user, I want Undo to work even if the dialog is closed.

**Comment by crsib** [comment]
No, I understood you correctly.

>If the undo or redo changes the settings of the effect currently shown in the panel

There is no such infrastructure right now. However, I think that this could be postponed to the patch release.

**Comment by Tantacrul** [comment]
> There is no such infrastructure right now. However, I think that this could be postponed to the patch release.

Pretty sure I agree. There are a few DAWs that still don't support undo/redo for VST controls. I can only assume it's a hornet's nest!

**Comment by crsib** [comment]
>I can only assume it's a hornet's nest!

In my recent experiments, Ableton sometimes "undoes" into some random state and Motu Performer does not support it all

**Comment by crsib** [comment]
>a repeated press of the cogwheel while the dialog is open should do nothing (not open a duplicate dialog)

This is a more complex case. We need a dialog per instance, right now everything is handled per plugin

**Comment by Paul-Licameli** [comment]
This completes a round of review of the lines of code changed, but now I need to reread the bullet points in the issue and consider whether they were all addressed.

**Comment by petersampsonaudacity** [comment]
Tested on W11 with latest alpha master audacity-win-3.2.0-alpha-20220815+c79a747-x64-msvc2022

I confirm that the realtime effects settings are now  non-modal
