### ISSUE TITLE
Consistency and cosmetic issues with Clip context menu

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#3103]
**Describe the bug**
In the Clip context menu:

a) the "**Rename clip...**" should have the "clip" capitalized to "Clip" - for consistency with "**Split Clip**" in the same context menu and with **Edit > Rename Clip...** and with **Edit > Split Clip**.

b) the **Rename Clip...** would be better alongside the **Split Clip** and moving the **Mute/Unmute Track** to below the line (thus creating a Clips group in the context menu - see screenshot 2

**To Reproduce**
1. Get some audio (single clip)
2. ensure it is not selected
3. right-click in the clip
4. **Observe:** see image 1

**Actual behavior**
See image 1

**Expected behavior**
see image 2

**Screenshots**
### 1) Existing Clip context menu
Shows the non-capitalized and inconsistent "clip"
![image](https://user-images.githubusercontent.com/50205984/174305789-2018cd98-77b5-4c12-98e0-f0cf930ab6c4.png)

### 2) Suggested revised Clip context menu
![image](https://user-images.githubusercontent.com/50205984/174305873-dc3b0496-4a71-4a00-b36a-afe6e32fcb0d.png)

### 3) Edit menu
![image](https://user-images.githubusercontent.com/50205984/174307595-7db73598-3c74-4a62-8792-81508bdb2799.png)

**Additional information (please complete the following information):**
 - OS: Windows 10 - but assume all OS
 - Version 3.2.0 alpha and 3.1.3

**Additional context**
These should be trivial fixes.

See also #3101

Flagging @Tantacrul and @LWinterberg as UX issues

**Comment by Tantacrul** [comment]
I'm strongly in favour of sentence case, so I'd argue that it should be:

- Split clip
- Rename clip

**Comment by petersampsonaudacity** [comment]
But Connie's take on this is that a "Clip" is a specific Audacity entity - and thus a capitalized proper name.

If you were to pursue sentence case you would need to attend to all the Audacity menus and dialogs such as Preferences, effects, error messages etc. - and keyboard shortcuts.

But whichever way you choose, maintaining consistency is important ...

**Comment by Tantacrul** [comment]
So, I just had a session with Leo where we looked through the current rules for capitalisation in Audacity. Although sentence case would be idea, it would clearly require a lot of work to implement, so - to completely U-turn on this - I think we should go with Peter's original request (described in the issue).

**Comment by petersampsonaudacity** [comment]
> So, I just had a session with Leo where we looked through the current rules for capitalisation in Audacity.

This is the rule that we always uses to work by:
>Use sentence capitalization, not title capitalization and not [CamelCase](https://en.wikipedia.org/wiki/CamelCase). This means only the first word is capitalized except for proper nouns and "Audacity-specific entities" such as "Device Toolbar" or "Scrubbing" or "Timeline". Generic entities common to all software such as "context menu" or "dialog" are not capitalized.

Gale Andrews (RIP) set that rule long log ago - you find it on this (Connie) page:
https://alphamanual.audacityteam.org/man/Consistency


> Although sentence case would be idea, it would clearly require a lot of work to implement

And not just a lot of work in the app - a lot of work in the documentation too.

**Comment by petersampsonaudacity** [comment]
> Also, thanks for the style guide. I've bookmarked that for later. 

@Tantacrul  Connie also has a second part for spelling:
https://alphamanual.audacityteam.org/man/Consistency_in_wording_and_punctuation_in_Audacity


>Now, I just need to keep in mind the fact my projects (MuseScore and Audacity) have different style guides 🗡️

Hmmmm ...

**Comment by petersampsonaudacity** [comment]
@LWinterberg 
Leo you have closed this for the primary cause that this issue was about (and that tests OK on latest Alpha).

BUT the secondary issue about the in-menu location of the command, one that @Tantacrul  approved has not been fixed - so can we either re-open this issue for the secondary issue - or open a new issue thread for it please?

>### 2) Suggested revised Clip context menu
![image](https://user-images.githubusercontent.com/50205984/174305873-dc3b0496-4a71-4a00-b36a-afe6e32fcb0d.png)


> > @Tantacrul @LWinterberg Are you also planning to use my other suggestion of moving the two Clip items to be together in the context menu?
> 
> Sorry, I missed that. Yes. It makes perfect sense. Thanks a lot!

**Comment by petersampsonaudacity** [comment]
>BUT the secondary issue about the in-menu location of the command, one that @Tantacrul approved has not been fixed - so I will open a new issue thread for it.

Done, see:  Clip context menu: the Rename Clip... would be better alongside the Split Clip #4235
