### ISSUE TITLE
Installer garbled in Chinese (traditional) characters

### ISSUE THREAD

**Issue by tim103117** [audacity/audacity#3105]
**Describe the bug**
Audacity's Chinese (traditional) installer is all messed up, only English is correct. But the main program itself is normal.

**To Reproduce**
1. Download Audacity installer on a traditional Chinese machine.
2. Run the installer

**Actual behavior**
All Chinese text is jumbled, unable to read and comprehend in the installer.

**Expected behavior**
Text must be readable

**Screenshots**
[Installer](https://cdn.discordapp.com/attachments/861612654447558696/987536986619408384/2022-06-18_094312.png)

**Additional information (please complete the following information):**
 - OS: [Windows 11]
 - Version [Audacity 3.13-0-64bit]

**Additional context**
Audacity doesn't support display ratio adjustment, for example, it looks blurry at 150% display ratio in Windows.

**Comment by LWinterberg** [comment]
This seems to be fixed
