### ISSUE TITLE
Audio Unit modules of some plug-ins aren't populated to the list of effects in the stackable effects UI

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3114]
Audio Unit modules of some plug-ins aren't populated to the list of effects in the stackable effects UI

Compare: 3 instances (AU, VST, VST3) of the effect when called from 'Effect...' menu:
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/70063970/170983086-f31314c8-e094-4124-ba49-3b723a820aae.png">

vs only 2 instances of the same effect when called via stackable effects UI:
<img width="412" alt="image" src="https://user-images.githubusercontent.com/70063970/170983171-e636c348-bc0f-4a3c-8fad-2c20df9e7592.png">

_Originally posted by @dozzzzer in https://github.com/audacity/audacity/issues/2845#issuecomment-1141044084_

**Comment by crsib** [comment]
Let's retest it @dozzzzer

**Comment by dozzzzer** [comment]
The original problem is still there. 
However, as for expected behavior here I'd say we only need to show a single entry of each plugin in the Realtime Effects sidebar.

**Comment by dozzzzer** [comment]
No more reproducible
