### ISSUE TITLE
Master power button state is disregarded when a new realtime effect is added to the track from the side panel

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3125]
**Describe the bug**
Even if the master power button in the stackable realtime effects panel is switched off (i.e. de-pressed), a new effect applies to the audio playback as soon as it's selected.

**To Reproduce**
1. Load/generate a clip
2. Click [Add Effects] button
3. Click the master power button to turn _all_ the stackable effects off
4. Start playback
5. In the stackable effect panel select an effect (e.g. Reverb)

**Actual behavior**
The audio changes immediately after the effect is selected:

https://user-images.githubusercontent.com/70063970/175077657-97a19762-a133-45a7-b1eb-de1a2b06757d.mp4

**Expected behavior**
The audio doesn't change unless the master power button is clicked, i.e. _all_ stackable effects are enabled at once.

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version: https://github.com/audacity/audacity/pull/3067

**Comment by Paul-Licameli** [comment]
When I checkout 85e29b659f2a83c08f6e8db2431a8d1e319a059c where power buttons were first implemented, the stated steps to reproduce don't exactly do it for me the first time.

But if I undo the addition of the effect and repeat steps from there -- then I do reproduce it.

**Comment by Paul-Licameli** [comment]
I confirm that steps to reproduce, as I modify them, still reproduce the problem at e46d7540857534f7c64d23dff8ce1fd58899107f

**Comment by pietro68** [comment]
I confirm this works as it should at `6d6b627`

**Comment by Ryan-Miller-Audacity** [comment]
Testing Completed.

Platform Information:
* Operating Systems: MacOS Monterey 12.3.1 and Windows 10

Main Testing Completed:
* Adding realtime effect during playback, paused playback, or no playback respects the current state of the master effect power button for that track
* Various power settings for different tracks do not negatively impact the behavior when adding a new effect to a separate track
* Tested the method of both Sergey's and Paul's reproduction steps and verified that I could not reproduce the original issue in the current master branch
* Per effect power buttons were not negatively impacted and work as expected under the status of the master effect power button

Bugs
* No bugs reported.
