### ISSUE TITLE
Linux: Audio Setup Toolbar issues

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#3130]
**Describe the bug**
The new "Audio Setup Toolbar" is too tall to fit into a double or single row when docked, and is truncated when floating.

**To Reproduce**
1. Reset Toolbars
2. Observe that the height of the Audio Setup Toolbar is three "units" high, reducing the space available for tracks.
3. Drag the toolbar out of the dock
4. Observe that the bottom of the toolbar is truncated (see screenshots)

**Actual behavior**
1. Excessive use of vertical space
2. Malformed when floating - Note that this problem also occurs with some other toolbars.

**Expected behavior**
1. Better use of available space
2. Floating toolbars to be properly formed. 

**Screenshots**

![docked](https://user-images.githubusercontent.com/11681097/175364480-a9880442-bfd8-461a-9b69-01e184ba031c.png)

![floating](https://user-images.githubusercontent.com/11681097/175364490-7fdd210f-91a8-4710-9a90-a816aca36e1e.png)

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version Audacity 3.2.0 e46d75

**Additional context**
**All** double height toolbars, and the new "triple" height toolbar are truncated / malformed when floating, rendering them unusable when floating. This is a regression against Audacity 2.3.3 (Audacity 3.1.3 also has this problem).

**Comment by SteveDaulton** [comment]
Not a full fix, but a big improvement achieved with a minor tweak, from:
`auto text = safenew wxStaticText(this, wxID_ANY, "Audio Setup");`
to:
`auto text = safenew wxStaticText(this, wxID_ANY, "Audio Setup", wxDefaultPosition, wxSize(-1, 20));`

Better would be to make the text a fixed size (as in "Snap To" in the Selection Toolbar), but I don't see how to do that without much bigger changes that I doubt you will want to do before 3.2.0.

**Comment by LWinterberg** [comment]
I can reproduce this with Ubuntu 22.04

**Comment by SteveDaulton** [comment]
In 3.2.4, this toolbar is  still  malformed when floating, but it is now (correctly) double height when docked.

**Comment by Ryan-Miller-Audacity** [comment]
In 3.3.2 the audio setup button looks to display fine when docked as well as when floating; however, as Leo mentions above if i switch to a scaled mode within my VM (essentially recreating a HiDPI screen) the audio setup toolbar is still malformed. However, with the closing of #503 should we be planning to keep this open? @LWinterberg What do you think?
