### ISSUE TITLE
3.2-Alpha Compressor Threshold and Noise Floor Not being loaded

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#3135]
3.2-Alpha Compressor Threshold and Noise Floor Not being loaded

Compressor not loading saved presets correctly
1) Set Params to -60, -80, 1.1:1, 0.10, 1.0
2) Manage > Factory Presets > Defaults
3) Observe param:-60, -80, 2:1, .20, 1.0
4) Set Params to -1, -20, 10:1, 5.0, 30.0
5) Manage > Factory Presets > Defaults
6) Observe param:-1, -20, 2:1, .20, 1.0

Threshold and Noise Floor Params are not being loaded from presets
This is a regression from 3.1.3

Windows 10, Audacity 3.2.0-alpha-20220624 90a440

**Comment by Ryan-Miller-Audacity** [comment]
This is a duplicate item of #2762 which includes further details in addition to the preset ailments mentioned above. Closing in favor of that item that has already been triaged.
