### ISSUE TITLE
Dragging labels in time does not snap to samples/etc.

### ISSUE THREAD

**Issue by nyanpasu64** [audacity/audacity#3141]
**Describe the bug**
When I'm dragging a label, I cannot ensure the start and stop times lie on sample boundaries (either by default, or holding a key).

**To Reproduce**
1. Open a track and select some audio.
2. Press Ctrl+B to create a label (optionally a track as well) covering that span of audio.
3. Click the label and drag horizontally.

**Actual behavior**
The label is dragged continuously and does not follow the "Snap-To" policy set in the bottom bar.

**Expected behavior**
The label snaps to samples as expected.

**Screenshots**
If applicable, add screenshots/video to help explain your problem.

![Screenshot_20220625_111133_index](https://user-images.githubusercontent.com/913957/175785557-e23f5878-291f-4385-8049-9b9b79cc8381.png)

**Additional information (please complete the following information):**
 - OS: Arch Linux
 - Version Self-built 3.1.3, with spectrogram crash fixed. (Last time I tried using a master build, applying effects was unstable and buggy.)

**Additional context**

Is it possible to drag a label vertically to reorder it, without moving in time?

**Comment by LWinterberg** [comment]
Snap-To only affects selection, not content, and labels are not quantized whereas tracks are. So all of this is working-as-intended technically.

That said, I can see how this is frustrating. Both snapping and label tracks are on our to-do to figure out a better design for (eg #2587 or #1017), so this issue will (hopefully!) get improved along with it.
