### ISSUE TITLE
Independence of settings of occurrences of one effect in effect stacks

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#3143]
No specific linked pull request.

Should be verified by QA, for each realtime capable built-in effect, and for each third party effect family (not necessarily worthwhile to re-test for every effect of each family).

If the same effect occurs more than once in effect stacks (whether on different tracks, or even on one track), then settings changes should stick for each effect stack entry, independently of all other entries.

**Comment by LWinterberg** [comment]
> Why closed 

it was in the "done" column of the board

**Comment by dozzzzer** [comment]
> why marked as "minor feature?"

Can't tell now, was probably added by mistake

**Comment by Paul-Licameli** [comment]
It's not really done until there is some verification of it for all five effect families.  And VST2 might join the party soon.

**Comment by Ryan-Miller-Audacity** [comment]
I just checked the above scenario for the following effect families and found no problems with the independence of settings per instance of effect on the same track or different tracks.

Audiounits, LV2, Ladspa, VST2,  and VST3 on windows and MacOS
