### ISSUE TITLE
Audacity crashes when an instance of a realtime effect is removed from a sidebar

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3149]
**Describe the bug**
If a built-in realtime effect (reverb/wahwah) is being removed during the playback, it causes Audacity to crash.

**To Reproduce**
1. Load a clip
2. click [Add Effects] to open side panel
3. select an effect (e.g. Reverb)
4. start playback
5. click on the effect and select 'No effect' in the dropdown menu

**Actual behavior**
Crash

**Expected behavior**
The effect is removed

**Screenshots**
<img width="599" alt="image" src="https://user-images.githubusercontent.com/70063970/175942658-ba4ae28d-0d98-4294-8c3a-a72f3c92db91.png">

**Additional information (please complete the following information):**
 - OS: MacOS 12.2.1
 - Version: latest master build

**Comment by petersampsonaudacity** [comment]
Also happens if you have several effects in the effects stack

**Comment by petersampsonaudacity** [comment]
Testing on W1l with latest alpha master  -  audacity-win-3.2.0-alpha-20220812+0761d2b-x64-msvc2022

I confirm that this now works properly and there is no crash.
