### ISSUE TITLE
"update/UpdateManager.h" include not behind flag

### ISSUE THREAD

**Issue by rhendric** [audacity/audacity#3154]
**Describe the bug**

Not a run-time bug, but when I was conducting an analysis to determine if the default build of Audacity used any network code, I discovered that this line

https://github.com/audacity/audacity/blob/7d3690189aca9880dbb3c5918326a0152876533f/src/AudacityApp.cpp#L120

is not behind an `#ifdef HAVE_UPDATES_CHECK`, unlike how many similar includes are handled throughout.

Ordinarily I'd prepare a PR for something this simple but I'm not interested in signing a CLA.

**To Reproduce**
1. Delete source files in `CMakeLists.txt` associated with the `audacity_has_updates_check` option
2. Attempt to compile Audacity without the `audacity_has_updates_check` option

**Actual behavior**
Compilation fails because `src/AudacityApp.cpp` includes `src/update/UpdateManager.h`

**Expected behavior**
Compilation succeeds.

**Comment by crsib** [comment]
I do not think one should expect successfull compilation after removing parts of the source tree to be fair. This one is quite easy to fix though.
