### ISSUE TITLE
Reverb can not work in realtime

### ISSUE THREAD

**Issue by pietro68** [audacity/audacity#3155]
The built-in reverb effect was recently converted to work in realtime mode, but I found that this conversion was not complete, and there is actually no way that it could be completed.

It was not complete because changes in the settings were not propagated to the reverb "core" i.e. what is in Reverb_libSoX.h, but most importantly, they can not be propagated there anyway - a rewrite of the reverb core would be needed.

This because in Reverb_libSoX.h provides an api which only lets clients declare how they want their reverb, but no api calls to modify its parameters, between process calls. Adding such api calls looks impossible without a rewrite of the core, because some entities are allocated with a size which depends on the pre-delay value.

I suggest that for a start we turn off realtime support for the reverb (it's a one liner: make ::SupportsRealtime return false) and then see if Reverb_libSoX can be rewritten to support parameter changes while processing - however this is a much longer task and it is also not easy to make it sound without artifacts as the parameters are changed.

@Paul-Licameli I examined Reverb_libSoX which is only 270 lines of code and depends on no other files.  I think the rewrite to allow realtime variation of parameters is achievable, though I don't know yet if artifacts would prove to be bad enough to require further effort.   Here is a checklist of subtasks that I see.

- [x] Add a function `reverb_clear` that assigns zeroes to `one_pole_t::i1` and `one_pole_t::o1`, and `filter_t::store`, and the buffer in `filter_t` from subscripts 0 to `size` -- for each of the two one-poles and the many filters.  Call it from the RealtimeSuspend override. Then demonstrate the bug like  #3112 does not happen.
- [x] Replace `reverb_create` with two functions, `reverb_allocate` and `reverb_init`.  The first simply allocates all structures, with the maximum size that could be needed for any settings -- that means as if `depth == 2` and `scale == 1.0`.  The second function fills in parameter values assuming sufficient allocation.  It also assigns the `size` members of the filters.  (The capacity of the allocated buffers, maybe larger than this, does not need to be recorded for deallocation to work correctly later.)  Note that some sizes depend on the sample rate r but of course this can be assumed constant during play.
- [x] Define `filter_resize` which moves the contents in the circular buffer in filter_t for change of size, assuming sufficient capacity.  (Only the first `size` items are occupied.  If `size` increases, add zeros for the least-recent values.  You may need to std::rotate or memcpy two ranges, and when done, have `ptr == buffer + size`)
- [x] Make sure `reverb_allocate` fills the filters with zeroes and assigs 0 to size; then `reverb_init` can use `filter_resize`, and could also be called again when there are changes of parameters.
- [x] Change `RealtimeProcessStart` to detect changes of paramters and invoke `reverb_init` again as needed.

Then, we should be able to demonstrate variation of Reverb parameters during play.

**Comment by dozzzzer** [comment]
@pietro68 One thing I observed when testing #4077 on **Windows 11** is that it crashes consistently when tweaking the **Stereo Width** slider. Sometimes you have to drag the slider all the way to the minimum and then pause, sometimes it crashes while playback is still on. MacOS build, though, works just fine.


https://user-images.githubusercontent.com/70063970/209123597-d88921a5-ef98-4f41-ae42-ed5b30440109.mp4

**Comment by dozzzzer** [comment]
Verified on macOS Ventura and Windows 11.
