### ISSUE TITLE
Crash when loading Berzerk Distortion

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3164]
### Crash when loading Berzerk Distortion 
**To Reproduce**

1. load a track
2. in the Effect menu select [Berzerk Distortion (version 12.0.0.87)](https://www.waves.com/plugins/berzerk-distortion#tab-tech-specs)
3. observe

**Actual behavior**
Crash

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version: [audacity-win-3.2.0-alpha-20220629+48b9c64-x64-msvc2022](https://github.com/audacity/audacity/suites/7135653719/artifacts/283447296)

**Comment by Ryan-Miller-Audacity** [comment]
Retested by request of triaging session, I am no longer observing a crash when utilizing the Berzerk Distortion plugin. Plugin loads as expected from both realtime and destructive panels on MacOS and Windows 10 as well.
