### ISSUE TITLE
Wahwah: when 'Wah frequency offset' is set to 100%, the sound of the playback disappears

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3169]
**To Reproduce**
1. load a track, start playback
2. add Wahwah effect from the sidebar
3. click cogwheel icon
4. set 'Wah frequency offset' parameter to 100% by either typing the value or by swiftly dragging the slider to the very right position (it might be required to swiftly drag the slider to zero and then back to 100% a few times)
5. observe

**Actual behavior**
No sound of the playback even though playback continues.

**Expected behavior**
Sound reacts correspondingly to the value

**Screenshots**
https://user-images.githubusercontent.com/70063970/176916209-51ab6208-7b0b-432e-82ec-823274fc7122.mp4

**Additional information (please complete the following information):**
 - OS: MacOS 12.2.1
 - Version: latest master build

**Comment by Ryan-Miller-Audacity** [comment]
FYI This is still reproducible in the latest public release (3.3.2).
