### ISSUE TITLE
Playback slider does not work, does not change the output volume

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#3172]
**Describe the bug**
The Playback slider _(in the Mixer toolbar, or in the new combined mixer/meter toolbar_)  does not work - it does not change the output volume.

This is a regression on 3.0.5 introduced in 3.1.0

And observe the volume that the MIDI Note track is played at is the setting made on a previous run of 3.0.5 or earlier.

**To Reproduce**
1. Import a MIDI file
2. Press Play
3. Move the Playback slider
4. Observe: this has no effect on the output volume of the Note track

**Actual behavior**
Playback slider does not work, does not change the output volume

**Expected behavior**
Playback slider should properly change the output volume

**Screenshots**
Not applicable

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version: Audacity 3.2.0 alpha and 3.1.3 (and indeed 3.1.0 onwards) - and the branch build with the combined meter/mixer  audacity-win-3.2.0-alpha-20220629+7478a55-x64

**Additional context**
If you also import an audio file and play both audio and MIDI you will observe that the volume of the audio varies with the playback slider bur the Note track volume remains constant.

**Comment by dozzzzer** [comment]
The issue duplicates https://github.com/audacity/audacity/issues/2455
