### ISSUE TITLE
error adding symbols: DSO missing from command line

### ISSUE THREAD

**Issue by ralmond** [audacity/audacity#3173]
**Describe the bug**
I'm trying to build audacity from sources (using the master branch).  I'm running under Pop_OS 22.04 (Downstream from Ubuntu 22.04).
When I get to the "make" step in the building instructions, I'm getting the following error.

```
[100%] Linking CXX executable ../bin/Debug/audacity
/usr/bin/ld: /home/ralmond/.conan/data/libid3tag/0.15.2b/audacity/stable/package/3d8adbca819867ccc062718cad27857fb790f14c/lib/liblibid3tag.a(util.c.o): undefined reference to symbol 'compress2'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/libz.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/Audacity.dir/build.make:7788: bin/Debug/audacity] Error 1
make[1]: *** [CMakeFiles/Makefile2:2380: src/CMakeFiles/Audacity.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

**To Reproduce**
1. git clone https://github.com/audacity/audacity.git
2. cd audacity
3. mkdir build
4. cd build
5.  cmake -G "Unix Makefiles" -Daudacity_use_ffmpeg=loaded ..
6. build

**Additional information (please complete the following information):**
 - OS: Pop_OS 22.04 
 - Version master:$(HEAD)
 - Pop_OS uses pipewire audio.
 - 
**Additional context**
Googling around, the DSO error can occur then the needed library appears earlier in the sequence than the library that calls it.  Looking at the file `build/src/CMakeFiles/Audacity.dir/link.txt` I noticed that the object `liblibid3tag.so` comes after `libz.so`, which could be causing the problem.

So I hacked the link.txt file (in between the cmake and the make step) to put libz at the end.
[audacity-link1.txt](https://github.com/audacity/audacity/files/9035672/audacity-link1.txt)

I then get a different, but similar error.
```
[ 60%] Linking CXX executable ../bin/Debug/audacity
/usr/bin/ld: CMakeFiles/Audacity.dir/effects/VST3/internal/x11/RunLoop.cpp.o: undefined reference to symbol 'XConnectionNumber'
/usr/bin/ld: /lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/Audacity.dir/build.make:7788: bin/Debug/audacity] Error 1
make[1]: *** [CMakeFiles/Makefile2:2380: src/CMakeFiles/Audacity.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```
So it is pretty clear that somehow the link order is not getting set properly.  The cmake system is pretty complex, so I'm not sure where to begin looking to fix this.

**Comment by crsib** [comment]
I've tried building in on my "clean" install of Pop_OS and I saw no issues with the build

**Comment by ralmond** [comment]
It might be a linker version difference.  I'm using `GNU ld (GNU Binutils for Ubuntu) 2.38`

Anyway, adding the switch `-Wl,--copy-dt-needed-entries` to `link.txt` fixed the problem for me.  Is there a way to set this in the cmake step so I don't need to manually hack the file?

**Comment by crsib** [comment]
Can you please share the whole environment?

On Pop_OS I have 

GCC 11.2.0
LD 2.38
CMake 3.22.1

We build constantly 6 different configurations on CI and I've never saw this issue before.

**Comment by ralmond** [comment]
Pop_OS 22.04
CGG 11.2.0
LD 2.38
cmake 3.22.1

So matches yours.  If I'm reading the  cmake docs correctly, I can just add 
`CMAKE_EXE_LINKER_FLAGS:STRING=-Wl,--copy-dt-needed-entries` to `CMakeCache.txt` after the first time I run, and then I should be able to build correctly.

If my problem doesn't reproduce, then I can close the issue.  Hopefully anybody who is having the same problem will find my work-around.
