### ISSUE TITLE
Add GPLv3+,AGPLv3+, for future license changes

### ISSUE THREAD

**Issue by natewrench** [audacity/audacity#3181]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by natewrench** [comment]
add MPL-2.0 for app store compatibility in case you no longer have a CLA

**Comment by LWinterberg** [comment]
VST3 does not allow for any other license except GPL3 and a proprietary license: https://github.com/steinbergmedia/vst3sdk/blob/master/LICENSE.txt#L9-L12
