### ISSUE TITLE
Assert fail when adding sidebar effect while recording

### ISSUE THREAD

**Issue by pietro68** [audacity/audacity#3186]
This can be observed with a Windows Debug build, but not with an OSX build.

Steps to trigger:

0) use a windows Debug build
1) Tracks | Add New | Mono Track
2) make sure that the recording device is set to mono
3) press record
4) try instantiating a wahwah in the sidebar

You will get an assert:

https://user-images.githubusercontent.com/16491307/176631880-9354ca3f-edb9-4e65-b2e5-de55aff10ec1.png

What happens internally is this:

When an effect is instantiated, we come to `AudioIO::AddState` and member `mpRealtimeInitialization` is used, but it is also found equal to `nullopt`. On Windows this triggers an assert (possibly due to its implementation of std::optional) but the OSX build does not seem to care and goes on apparently without problems (but maybe going into undefined behavior).

And why is `mpRealtimeInitialization` equal to `nullopt`? because the constructor of `TransportState` found `numPlaybackChannels` equal to 0 (as it should - we are recording, not playing back), therefore it will completely skip executing its body, including the initialization of `mpRealtimeInitialization`.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest alpha master:  
audacity-win-3.2.0-alpha-20220705+c71177d-x64-msvc2022

This does not happen with a master (non-debug) build.
