### ISSUE TITLE
define the instance class for VST2 effects

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#3192]
The Instance might be done before the Validator.  That is not how things progressed with built-ins.  But if you look at the dependency graphs for the source files implementing AudioUnits or LV2, you see that the validator depends on the instance, not the opposite.

So really the Instance is the more basic object, which could be extracted from existing code first, although it may also be necessary to define the Validator partially so that Instance can be defined completely.

Suggested outline of steps, by analogy with the recent LV2 transformation

- [x] 1. (As needed, perhaps not) Definine a minimal Validator class (see 72f3c002)
- [x] 2. Define minimal Instance class (8ec84fa7)
- [x] 3. Define temporary overloads of `GetSettings` in scope of the Instance (e6d6ed95)
- [x] 4. Instance doesn't inherit `StatefulPerTrackEffect::Instance`; move `ProcessInitialize`, `ProcessBlock`, `ProcessFinalize`, `GetLatency` from Effect to Instance class (ffbec4a8); and effect inherits `PerTrackEffect` and `StatefulEffectBase` but not `StatefulPerTrackEffect`
- [ ] 5. Instance doesn't inherit `StatefulEffectBase::Instance`; move other necessary overrides into Instance class; make slaves instances (76028f62); effect no longer inherits `StatefulEffectBase`
- [x] 6. (Only needed if output metering doesn't work:  Instance re-uses itself, not a slave, for group number 0 in RealtimeProcess (3447e35d))

**Comment by pietro68** [comment]
Looks like output metering already works, so I will cross out number 6.
