### ISSUE TITLE
Punch Copy/Paste

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#3194]
**Is your feature request related to a problem? Please describe.**
Audiobook producers sometimes need to paste "room tone" to cover noises (such as mouth clicks / chair squeaks / bumps / clicks) that may  be evident between words. Doing this manually is unnecessarily tricky because it is necessary to exactly match the duration being copied and the duration being pasted (and preferable to crossfade).

**Describe the solution you'd like**
A built-in ability to paste the clipboard contents such that the pasted content is automatically trimmed or looped, with optional crossfading, to exactly fit the selection that is being overwritten.

**Describe alternatives you've considered**
These plug-ins: https://forum.audacityteam.org/viewtopic.php?p=427085#p427085
which are updated versions of these plug-ins: https://forum.audacityteam.org/viewtopic.php?p=208312#p208312

**Additional context**
Many audiobook users find this feature to be indispensable. A built-in version would be more convenient, and could avoid issues that the Nyquist version has to work around (for example, the Nyquist version has to retain its own separate clipboard in RAM).

While audiobook production is the most common use for this feature, it may be used any time there is a need to trim copied audio to fit into a selection.

**Comment by LWinterberg** [comment]
overlapping clips (currently planned for 3.3) make this unnecessary

**Comment by SteveDaulton** [comment]
Steve wrote:
> such that the pasted content is automatically trimmed **or looped**, with optional **crossfading**, to exactly fit the selection that is being overwritten.

LWinterberg wrote:
> overlapping clips (currently planned for 3.3) make this unnecessary

Will overlapping clips (in 3.3) be able to automatically extend a short audio clip to fit a larger space?

**Comment by Paul-Licameli** [comment]
> Steve wrote:
> 
> > such that the pasted content is automatically trimmed **or looped**, with optional **crossfading**, to exactly fit the selection that is being overwritten.
> 
> LWinterberg wrote:
> 
> > overlapping clips (currently planned for 3.3) make this unnecessary

Planned?  Surely?  Really?  I don't agree.

> 
> Will overlapping clips (in 3.3) be able to automatically extend a short audio clip to fit a larger space?
