### ISSUE TITLE
MP3 files fail to import

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#3196]
**Describe the bug**
MP3 files fail to import, the dialog appears and  goes through the buggy motions (see #2959).

Eventually I get either an empty window, or an **Unhandled exception**

This is a regression on 3.1.3 and is a very serious rtegression issue that IMO deserves a P1, must-fix, rating

**To Reproduce**
1. Import a MP3 file (I used a 2-hour one created 3 days ago with 3.1.3)
2. Observe: a hiatus before the import progress dialog appears (also a regression on 3.1.3)
3. Observe: erroneous import progress dialog - issue #2959
4. Observe: Eventually. the import dialog finishes and you get an empty tracks window
5. Observe: there is no Undo available for the "import"

**Actual behavior**
MP3 files fail to import

**Expected behavior**
MP3 files should be imported properly

**Screenshots**
![image](https://user-images.githubusercontent.com/50205984/177786037-162efe6b-35b5-4157-be30-07e1fc02d037.png)

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version Audacity 3.2.0 alpha master

**Additional context**
I also tried with a 3 minute MP3 in case it was the length of the 2 hour one but the 3 min one failed to import too.

Does not affect other audio formats? WAV. MP4/AAC, Ogg, FLAC - all these import fine

**Comment by petersampsonaudacity** [comment]
> I wonder if this is some configuration thing.

I purged may audacity settings folder before the tests

**Comment by petersampsonaudacity** [comment]
@crsib @dozzzzer 

Too big for email (the 2 hour one) - so you should see the two MP3 files in the Audacity folder inmy Dropbox:
https://www.dropbox.com/sh/n049ws0th64kzrl/AAB4axa8M_ZcJcQPM-1UJRlWa?dl=0

**Comment by dozzzzer** [comment]
Failed to import the short one too, both on Windows and Mac

**Comment by petersampsonaudacity** [comment]
The short one (5 mins) was also recorded and edited with an earlier version of Audacity

**Comment by petersampsonaudacity** [comment]
after trying to import Clicky.mp3

![image](https://user-images.githubusercontent.com/50205984/177817251-d38dc17e-cec5-42b7-a5d7-228079ff6047.png)

**Comment by petersampsonaudacity** [comment]
And here is a link to the diagnostic data in my Dropobox:

https://www.dropbox.com/s/2podxlck2s1e46m/Audacity_dbgrpt-32652-20220707T165119.zip?dl=0

**Comment by petersampsonaudacity** [comment]
Both files import fine on 3.1.3

**Comment by crsib** [comment]
>Both files import fine on 3.1.3

And 3.1.3 fails to decode a different bunch of files :-) 

`clicky.mp3` in fact is a `wav` file. You can observe it if you open it in any text editor. The header is `RIFF WAVE`. That explains the size! 

Audacity 3.2 opens it as a wav correctly. It seems that `libmad` was capable of opening wav files, `libmpg123` is not, however the latter one handles MP3 much better. It is a generic issue with Audacity that we rely on file extension instead of the file header, but I don't think that it will be fixed in Audacity 3.2

The PR for the `Genre` issue will be there in an hour time

**Comment by dozzzzer** [comment]
Verified.
Both files now can be imported with no issues, given that the smaller file has the correct file extension.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest alpha master:  audacity-win-3.2.0-alpha-20220711+5ef9f2e-x64-msvc2022

1) my two hour MP3 now imports correctly as a full-lenght 5 minute stereo track

2) But Clicky.p3 imports but only imports as a short mono flatline

### Clicky imported with 3.2.2
![image](https://user-images.githubusercontent.com/50205984/178271393-a18f8fcb-80f5-4f14-984b-fcde81f6292d.png)

### Clicky imported with 3.2.2
![image](https://user-images.githubusercontent.com/50205984/178271528-97bbce97-4d42-45d8-a0bc-a4d1198765ec.png)

@crsib do we need a new issue for this

**Comment by crsib** [comment]
>do we need a new issue for this

As I mentioned in the issue - Clicky is not an mp3 file. Likely fixing #3206 will help as well
