### ISSUE TITLE
consistent use of ellipses in menus

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#3199]
Microsoft definition https://docs.microsoft.com/en-us/windows/win32/uxguide/cmd-menus#using-ellipses

> Proper use of ellipses is important to indicate that users can make further choices before performing the action, or even cancel the action entirely. The visual cue offered by an ellipsis allows users to explore your software without fear.

> This doesn't mean you should use an ellipsis whenever an action displays another window only when additional information is required to perform the action. For example, the commands About, Advanced, Help, Options, Properties, and Settings must display another window when clicked, but don't require additional information from the user. Therefore they don't need ellipses.

> In case of ambiguity (for example, the command label lacks a verb), decide based on the most likely user action. If simply viewing the window is a common action, don't use an ellipsis.

Apple definition https://developer.apple.com/design/human-interface-guidelines/components/menus-and-actions/menus/

> Append an ellipsis to a menu item’s label when people need to provide additional information before the action can complete. The ellipsis character (…) signals that another view will open in which people can input information or make choices.

Apple's definition is somewhat ambiguous IMHO, but at least can be interpreted in the same way as Microsoft's. 

Therefore, the following items should get un-ellipsis-d:

* **About** (no input)
* **Preferences** (example)
* **Metadata** (can be used to just view; Metadata also isn't an action on its own)
* **History, Karaoke, Mixer** (all summon additional views)
* **Makro Manager** (to become consistent with Plugin Manager)

**Comment by Paul-Licameli** [comment]
I don't understand whether you are saying "Preferences..." is the right or wrong example.

I thought the well understood convention is that a menu item ending with ellipses is one that opens a modal dialog.

On my Mac for instance it's "Preferences..." for Safari.

But it's just "Preferences" for Firefox.

Inconsistent?  No!  Safari opens a dialog, but Firefox instead opens a web page.

These two agree, for instance, in "Open File..." which opens a dialog in both.

**Comment by petersampsonaudacity** [comment]
See #6697
