### ISSUE TITLE
Audacity still creates an ~/.audacity folder even when XDG dirs are used

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#3201]
> I just tested the latest alpha (audacity-linux-3.2.0-alpha-20220708+aca9aaf-x64.AppImage) and it still creates a folder .audacity/crashreports/ directly in my home? 

> `echo $XDG_CONFIG_HOME

> /home/XXX/.config`

_Originally posted by @FranzXaver in https://github.com/audacity/audacity/issues/453#issuecomment-1178945857_

This is despite the Help → About Audacity → Build information reporting: 

```
Program build date:
Jul 8 2022
Commit Id:
aca9aa of Fri Jul 8 06:49:40 2022 -0400
Build type:
CMake Release build (debug level 1), 64 bits
Compiler:
GCC 11.1.0 (Audacity)
Installation Prefix:
/usr/local
Cache folder:
/home/xxx/.cache/audacity
Settings folder:
/home/xxx/.config/audacity
Data folder:
/home/xxx/.local/share/audacity
State folder:
/home/xxx/.local/state/audacity
```

## Expected behavior
Crash reports should be stored in $XDG_STATE_HOME (/home/xxx/.local/state/audacity) instead, and ~/.audacity should not be created at all.

**Comment by Ryan-Miller-Audacity** [comment]
Tested and verified fixed in my Linux VM. Crash reports no longer create/save within ~/.audacity, instead they are saved in /home/xxx/.local/state/audacity).
