### ISSUE TITLE
Missing "&" in Regular Interval Labels

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#3203]
**Describe the bug**
The default value of the first control in "Regular Interval Labels" should be: "Number & Interval"
(as shown in the manual: https://manual.audacityteam.org/man/regular_interval_labels.html)
but in Audacity 3.2.0 alpha it displays as (nonsensical): "Number  Interval"

This is a regression on 2.3.3

**To Reproduce**
1. Launch "Regular Interval Labels"
2. Look at the  options in "Create labels based on"

**Actual behavior**
The default value for "Create labels based on" is "Number  Interval"

**Expected behavior**
The default value for "Create labels based on" should be "Number & Interval"

**Screenshots**
### The app
![image](https://user-images.githubusercontent.com/50205984/178136630-2c603db1-3f44-4d6c-b023-646935ce4b08.png)

### The 3.1.3 manual
![image](https://user-images.githubusercontent.com/50205984/178136866-f1244dda-e782-4f0d-812f-d45bc58670f2.png)

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version Audacity 3.2.0

**Additional context**
So long as the full text is displayed, the option could be renamed as "Number and Interval".

**Comment by petersampsonaudacity** [comment]
Confirmed on W10 with latest alpha master
audacity-win-3.2.0-alpha-20220708+5d10d6f-x64-msvc2022

**Comment by petersampsonaudacity** [comment]
@SteveDaulton  against which version is this a regression?

It was certainly this way in 2/4/2 _(I haven't tested further back)_

**Comment by SteveDaulton** [comment]
Audacity  2.3.3 displays the control text correctly. I haven't tested other versions.

**Comment by petersampsonaudacity** [comment]
> Audacity 2.3.3 displays the control text correctly. I haven't tested other versions.

Yes indeed 2.3.3 is the last version in which this text string is correct it is a regression on 2.3.3 with the incorrect string introduced in 2.4.0

**Comment by petersampsonaudacity** [comment]
@LWinterberg  BUMP - surely this should not be too hard to fix ...

**Comment by LWinterberg** [comment]
I didn't find a way to preserve the `&`, but an `and` should work just as well

**Comment by petersampsonaudacity** [comment]
> I didn't find a way to preserve the `&`, but an `and` should work just as well

Sounds like a perfectly good solution to me  :-))

**Comment by SteveDaulton** [comment]
> I didn't find a way to preserve the `&`,

because Audacity is stripping it out?

Yes it would be easy to work around this bug by substituting "and" in place of "&", but that does not fix the bug.

**Comment by petersampsonaudacity** [comment]
> es it would be easy to work around this bug by substituting "and" in place of "&", but that does not fix the bug.

IMHO it's a perfectly good way if fixing this issue ...

**Comment by SteveDaulton** [comment]
As the "fix" just works around the problem, the [Nyquist documentation](https://wiki.audacityteam.org/wiki/Nyquist_Plug-ins_Widgets) needs to be updated so that users  are aware that the "&" cannot be used in multi-choice widget options.

FWIW, this is a "bug" in my opinion. The "&" character has no special significance in this context and should be treated the same way as any other ASCII character (other than "," comma, which does has special significance).
