### ISSUE TITLE
Stackable effects: all buttons should fit to the default width of the sidebar

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3209]
**Describe the bug**
When adding an effect with a long title, it doesn't fit the default minimal width of the sidebar, which, in turn, makes gear icon hide and calculates the width of the 'Add effect' button wrongly.

**To Reproduce**
1. Add an effect with a long title in the stackable effects sidebar (e.g. AUMultibandCompressor) 
2. observe 

**Actual behavior**
1. gear button isn't visble
2. effect's button as well as 'Add effect' button are partially hidden
<img width="409" alt="image" src="https://user-images.githubusercontent.com/70063970/178274142-86df23ba-dbd8-4bab-be60-324e0c8fe343.png">

**Expected behavior**
1. both effect's button and gear button fit the default width if the sidebar; if the title of the effect is too long, it should be truncated with an ellipsis
2. 'Add effect' button is fully visible too

**Comment by petersampsonaudacity** [comment]
@LWinterberg  and @Tantacrul 

How "discoverable" is it that you can click the join between the Effects Stack panel and the tracks panel to enlarge the Effects Stack panel ?

**Comment by LWinterberg** [comment]
not massively, hence why it's in https://github.com/audacity/audacity/issues/3195 as an improvement
