### ISSUE TITLE
Cannot instantiate an LV2 effect on MacOS

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3210]
**Describe the bug**
'Cannot instantiate effect' error message is observed when calling an LV2 effect on Mac M1.

**To Reproduce**
1. install an LV2 effect (e.g. [Dragonfly Reverb](https://michaelwillis.github.io/dragonfly-reverb/))
2. launch Audacity and load some audio
3. try to call the plugin either from the real-time effects sidebar or destructively

**Actual behavior**
<img width="304" alt="image" src="https://user-images.githubusercontent.com/70063970/178330328-1caa9b6f-dc08-4102-96b0-15ccd040a2c4.png">

**Expected behavior**
The effect opens up and functions properly

**Additional information (please complete the following information):**
 - OS: MacOS 12.2.1, M1 Pro chip
 - Version: latest alpha build

Note: **after** it fails to initialize destructively, playback in a normal way isn't possible: the output sound is just essentially noise.

https://user-images.githubusercontent.com/70063970/178332996-64d27427-4667-42ec-afd5-b6736e046413.mp4

**Comment by crsib** [comment]
This bug is related to an issue within plugin discovery. Turns out, that before a real instance of an effect is created LV2 does not load any shared libraries at all. `LV2Effect::MakeInstance` does not actually instantiate the effect.

(@Paul-Licameli @vsverchinsky)

**Comment by dozzzzer** [comment]
Verified
