### ISSUE TITLE
MacOS requests permission to use the microphone every time the Record button is pressed

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3212]
**Describe the bug**
MacOS requests permission to use the microphone every time the Record button is pressed

**To Reproduce**
1. click Record button
2. grant permission
3. click Record button again
4. observe

**Actual behavior**
The system repeatedly asks for permission every time the Record button is clicked
<img width="362" alt="image" src="https://user-images.githubusercontent.com/70063970/178340112-0cbb7dcf-f34e-470b-a214-f59f7f7c19d4.png">

**Expected behavior**
Permission to use the microphone is requested only once.

**Additional Information**
- MacOS 12.2.1, Macbook Pro M1 Pro

**Comment by petersampsonaudacity** [comment]
I cannot replicate this on my Macbook Pro macOS 12.4 Monterey with the latest Mac alpha master:
audacity-macOS-3.2.0-alpha-20220711+468fad9-x86_64

**Comment by dozzzzer** [comment]
@Paul-Licameli you might be missing my point: I see it every single time I press Record even while using the _exact same_ build.

**Comment by crsib** [comment]
@dozzzzer do you copy Audacity outside the image?

**Comment by crsib** [comment]
Looks like we do not codesign any builds besides the universal, this can be the issue
