### ISSUE TITLE
Stacked effects with latency de-synchronize playback with other tracks

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#3221]
UPDATED alternative steps:
- Generate rhythm track
- Put (for instance AUGraphicEQ) in the stack
- mix-and-render to new track
- apply Invert effect to the new track
- play tracks together
- expect silence

Steps to reproduce:
- Generate some silence
- At about 0.5 seconds, zoom in close and pull one sample up to +1 with the pencil tool
- Duplicate the track
- Listen
- Use the menus to apply some realtime-capable effect destructively, which has nonzero latency (I tried with AUDynamicsProcessor which has 256 sample delay, about 5 milliseconds at 44.1 kHz; also AM pitch shifter of swh ladspa plug-ins, with the size slider at maximum, which makes 2048 sample delay, 46 ms), to the first track only
- Listen: it still sounds the same
- Undo the destructive effect
- But now put the same effect with same settings into the stack of the first track
- Listen:  it's not the same:  the first track's click is later than the other track, and it's humanly detectable even at 5 ms

Comparison with the destructively applied effect proves that it is not the effect computation itself causing what you hear at the third listen.  The code for destructive effect application accounts for latency in a way that the realtime playback does not.

I haven't yet found an example of an effect with longer latency that might make the problem more obvious.  For AUDynamicsProcessor, the 256 sample latency seems to be invariant, so if the tracks instead have the lowest available sample rate of 800 Hz, then the difference is about 30 ms and the change in sound becomes more obvious.

Some ladspa effects in the swh package have latency and might be experimented with too:
am_pitchshift_1433.xml -- I tried this with the "size" parameter at maximum, which makes a 2048 sample latency

bode_shifter_1431.xml
bode_shifter_cv_1432.xml
dj_eq_1901.xml
fast_lookahead_limiter_1913.xml
gsm_1215.xml
hilbert_1440.xml
imp_1199.xml
latency_1914.xml
mbeq_1197.xml
pitch_scale_1193.xml
pitch_scale_1194.xml

**Comment by DavidBailes** [comment]
> I haven't yet found an example of an effect with longer latency that might make the problem more obvious

https://www.voxengo.com/product/latencydelay/

- with a delay of 0 entered in the interface, this will leave the delay introduced by the effect to be 10000 samples

**Comment by pietro68** [comment]
I tried to reproduce the steps (using LADSPA am pitch with largest window) and I can not hear the effect of the fix; I am also doubting that I interpret the repro steps in the right way, please could you fill the blanks:

- Generate some silence
- At about 0.5 seconds, zoom in close and pull one sample up to +1 with the pencil tool
- Duplicate the track
- Listen `I guess I should hear the two clicks in sync`
- Use the menus to apply some realtime-capable effect destructively `to both tracks?`, which has nonzero latency (I tried with AUDynamicsProcessor which has 256 sample delay, about 5 milliseconds at 44.1 kHz; also AM pitch shifter of swh ladspa plug-ins, with the size slider at maximum, which makes 2048 sample delay, 46 ms), to the first track only
- Listen: it still sounds the same `what do you mean exactly? that the two clicks are in sync?`
- Undo the destructive effect `for both tracks?`
- But now put the same effect with same settings into the stack of the first track
- Listen:  it's not the same:  the first track's click is later than the other track, and it's humanly detectable even at 5 ms

**Comment by pietro68** [comment]
I am afraid I can not even reproduce the step: "Listen: it still sounds the same" - when using LADSPA am_pitchshift with largest size - the click on the first track comes about 22000 samples later than the click on the second track.

**Comment by Paul-Licameli** [comment]
> I am afraid I can not even reproduce the step: "Listen: it still sounds the same" - when using LADSPA am_pitchshift with largest size - the click on the first track comes about 22000 samples later than the click on the second track.

Actually I think that plug in has a bug.  It mis reports it’s latency twice as large as it really is.
