### ISSUE TITLE
"Closing" an LV2 effect interface causes crash

### ISSUE THREAD

**Issue by Ryan-Miller-Audacity** [audacity/audacity#3222]
**Describe the bug**
1. Attempting to close an LV2 plugin via the "Cancel"/"Close" button for realtime/destructive effects result in a crash. 

2. Attempting to confirm an LV2 plugin via the "OK" button for realtime effects results in a crash. (This crash does not occur when clicking apply on a destructive effect panel).

The two items mentioned above create similar (if not the same) sentry crash reports which can be viewed here: https://sentry.audacityteam.org/share/issue/dfefb4f328b24978b4e69cccfb3cce3f/

Note that this issue is different than #3211 in that these include the interface properly displaying within the plugin window and appear to produce different error reports as well. 

**To Reproduce**
Steps to reproduce the behavior from Item 1:
1. Install an LV2 effect like http://x42-plugins.com/x42/x42-limiter
2. Load/generate some audio
3. Select the audio and open the LV2 plugin via the realtime panel or the effects dropdown
4. Press the gear icon on the realtime effects panel to open the interface (the dropdown will open it on its own)
5. Click the cancel/close button
6. Audacity Crashes

Steps to reproduce the behavior from Item 2: 
1. Install an LV2 effect like http://x42-plugins.com/x42/x42-limiter
2. Load/generate some audio
3. Select the audio and open the LV2 plugin via the realtime panel or the effects dropdown
4. Press the gear icon on the realtime effects panel to open the interface 
5. Click the "OK" button (changing plugin sliders itsn't necessary)
6. Audacity Crashes

**Actual behavior**
1. Audacity crashes after clicking the cancel/close button on the LV2 effect interface.
2. Audacity crashes after clicking the "OK" button on an LV2 effect loaded from the sidebar.

**Expected behavior**
1. The effect window closes without crashing.
2. The effect window closes without crashing.

**Additional information (please complete the following information):**
 - OS: MacOS Monterey 12.3.1 and Windows 10
 - Version: latest alpha 3.2.0

**Comment by crsib** [comment]
I think #3220 fixes this as well

**Comment by crsib** [comment]
I think I can no longer reproduce this issue

**Comment by Ryan-Miller-Audacity** [comment]
Testing in [most recent master](https://github.com/audacity/audacity/actions/runs/2719267121) with cleaned config files, I am still having this issue; however, it does seem to be limited to the free x42 LV2 plugins that display properly with the interface in the popup window. Other (trial/paid) x42 plugins (from the meter collection for example) that currently open their interface outside of the popup window (part 1 from #3211) do properly close without issue as well as other LV2 plugins (the MDA series of LV2 plugins for example). 

So the specific effects I am seeing this behavior with are: 
* x42 Autotune (and its variants)
* x42-comp - Dynamic Compressor Mono/Stereo
* x42-dpl - Digital Peak Limiter Mono/Stereo
* x42-eq - Parametric Equalizer Mono/Stereo

**Comment by crsib** [comment]
My bad, I saw x42 and ignored that this is about a different plugin

**Comment by Paul-Licameli** [comment]
The dangling reference fix in commit b6c534661996486ff5063222313bbd719954803b in branch Fix-lv2-block-size maybe fixes this too?

**Comment by crsib** [comment]
Unfortunately it doesn't. This appears to be an issue with this specific plugin, but I'm trying to figure it out anyway.

**Comment by Paul-Licameli** [comment]
I'm restesting this at commit fd9bd23ae79c30051e2774e8791d55d2ecbdae8d and it still crashes on macOS (as originally reported) with the given example of a plug-in.  There are mono and stereo versions of the limiter.  I used the mono, and used the sidebar dialog (which is still modal), and the cancel button.  So far, that does crash, a dangling pointer in `wxMacAutoreleasePool::~wxMacAutoreleasePool()`.

**Comment by Paul-Licameli** [comment]
@Ryan-Miller-Audacity Is this crash reproducible with the same plug-ins with versions on other operating systems?

Is it reproducible in another host program supporting LV2 on macOS?  (Which might suggest the blame is on bugs in the plug-in itself)

Or is it only the macOS build of Audacity that is to blame for crashes?

**Comment by crsib** [comment]
There is no problem in Ardour on Windows. My wild guess - we have to update LV2 SDK. This is a quite large and complicated task though, so probably we should leave it to post alpha or even to patch release

**Comment by Paul-Licameli** [comment]
I get a crash in:

```
bool wxApp::ProcessIdle()
{
    wxMacAutoreleasePool autoreleasepool;
    return wxAppBase::ProcessIdle();
}
```

While destroying the local `autoreleasepool` which suggests to me that a memory corruption happened during idle time processing.

There is no objective-C++ in our own host-side code for LV2 support.

**Comment by Paul-Licameli** [comment]
There are two `.mm` files in lib-src/lv2/suil/src where I thought I might put breaks and try to learn more, but I think these are not part of our build.

**Comment by crsib** [comment]
On Windows the crash is inside LV2 SDK. To be precise - `instance->descriptor->cleanup(instance->handle)` in `suil_instance_free`. This is why I guess that our host SDK is too old. 

I've tried to do it on Linux, as I can build against system provided LV2 - turns out that fancy UI is not always available for this plugin at all

**Comment by Paul-Licameli** [comment]
Oh no, could it be ABI incompatibility?  I thought lv2 would more careful than the ffmpeg guys were about that.

**Comment by crsib** [comment]
I guess some behavioral change. I wonder if there is a way to check, that the host version is compatible with plugin version, but I haven't studied it enough.

>ffmpeg guys were about that

They break ABI between major version changes, which is considered to be fine. Painful when you need to support range of major versions.

**Comment by crsib** [comment]
Probably (just a guess again) a new field was added, which can be done in non-ABI breaking way, but definitely requires some knowledge from the host

**Comment by Paul-Licameli** [comment]
But I thought LV2 way of doing this versioning, though, would involve capability queries from the host to the plug-in, using `lilv_instance_get_extension_data` which you can see we do in three places.

Then there are also arrays of "features" that the host supplies to the plug-in, to inform the plug-in of capabilities.

**Comment by Paul-Licameli** [comment]
The crash stack on macOS suggested something going wrong in idle time processing but that still happens even when I don't bind the idle-time event handler in `LV2Validator.cpp`

**Comment by Paul-Licameli** [comment]
Checking in the debugger, what are the required options and features this plug-in demands.  Just two:
LV2_UI__idleInterface http://lv2plug.in/ns/extensions/ui#idleInterface
and
LV2_URID_PREFIX http://lv2plug.in/ns/ext/urid#map

But when we `AddFeature` we pass null with the first -- which I think means, we promise the plug-in to look up its extension data for idle time and use it.

For the URID map, we supply the `mUriMapFeature` feature object, which could let the plug-in invoke our host code.

So suspects may be -- a bug in their idle time `idle` or `hide` functions, which we can't fix, or a bug oin our `LV2FeaturesList::uri_to_id` that corrupts memory.

Or maybe a bug in our side in one of our other Feature objects that the plug-in doesn't require but uses if available.

**Comment by Paul-Licameli** [comment]
But I thought I already eliminated idle time as a possibility.

**Comment by Paul-Licameli** [comment]
I'm out of guesses now and I feel diminishing returns in this investigation.

**Comment by crsib** [comment]
The effect in question does not implement `LV2_UI__showInterface`, only `LV2_UI__idleInterface`

**Comment by Paul-Licameli** [comment]
> FYI: @Paul-Licameli's note: This fix only works properly in MacOS currently. Not windows.

Reopen it then, updating the title, to track the known problem still on Windows, but it's less clear how to fix that case.

**Comment by Ryan-Miller-Audacity** [comment]
I did check this between MacOS, Windows, and Linux and no longer observe the crash when closing one of the effect LV2 plugins.

**Comment by crsib** [comment]
This definitely now fixed, but I dunno how. @Paul-Licameli any ideas what could've caused it?

**Comment by Ryan-Miller-Audacity** [comment]
Paul mentioned https://github.com/audacity/audacity/pull/3460#event-7276205303 when I was talking to him about it, and I quickly checked the build from there and didn't get a crash there.

**Comment by crsib** [comment]
That commit was fixing a different bug.
