### ISSUE TITLE
Handle varying latency when adjusting controls in realtime playback

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#3223]
See #3221

To handle an unchanging latency by some discard of initial playback samples is the first challenge.

Some effects can have latency that depends on slider values, such as the size parameter of am_pitchshift_1433 in the swh Ladspa plug-ins.

Handling that possibility while also keeping track playback synchronized would be another problem.

Maybe not important for 3.2, but it might become more important when we develop automation.

**Comment by saintmatthieu** [comment]
If this ever gets addressed, please then check the graph of the real-time compressor/limiter: at the time of writing it accounts for the latency reported at the start of playback, and assumes it stays constant.
