### ISSUE TITLE
3.2-Alpha's VST3s may not be ready for prime time.

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#3224]
3.2-Alpha's VST3s may not be ready for prime time.

This VST3 plugin crashed 3.2 Alpha immediately after activation (Windows 10).

In response to a suggestion by @LWinterberg here: https://forum.audacityteam.org/viewtopic.php?p=453454#p453454, I downloaded a VST3 plugin from here: https://valhalladsp.com/demos-downloads/

I downloaded "Valhalla VintageVerb Demo" Windows Demo:Version 2.2.0: Updated 11/23/2021, then ran ValhallaVintageVerbDemoWin_V2_2_0.exe from the unzipped directory. I selected *only* the VST3 version, which was installed to C:\Program Files\Common Files\VST3\ValhallaVintageVerb.vst3 (Should it have gone to AppData\Roaming\audacity\Plug-Ins?)

I then started up Audacity 3.2 Alpha: audacity-win-3.2.0-alpha-20220711+468fad9-x64, created (Generated) a chirp, then Effect > ValhallaVintageVerb..

The Valhalla splash screen came right up, but then Audacity crashed right away.

**Comment by vsverchinsky** [comment]
This is fixed by PR #3047, which is currently in review

**Comment by LWinterberg** [comment]
the non-demo versions at the bottom of the page (Freq Echo, Supermassive, Space Modulator) do work for me, which are the ones the user had trouble with.
