### ISSUE TITLE
Renaming a track is not immediately reflected in Realtime Effect UI Panel

### ISSUE THREAD

**Issue by Ryan-Miller-Audacity** [audacity/audacity#3226]
**Describe the bug**
If you rename a track with the Realtime Effect panel open, you have to close and reopen the realtime effect panel for the name change to appear in the panel.

https://user-images.githubusercontent.com/88568755/178730674-e2d80a54-b92e-4bf8-965a-caad8f6132f2.mp4

**To Reproduce**
1. Open an Audacity project and create a new track
2. Open the Realtime effects panel
3. Rename the track label
4. Note that the name is not immediately updated in the effects panel
5. Close and reopen the effects panel
6. Note that the name is now properly updated

**Actual behavior**
The track name is not updated in the realtime effect panel without closing and reopening the panel.

**Expected behavior**
The track name should be updated in the realtime effect panel without having to close and reopen the panel.

**Additional information (please complete the following information):**
 - OS: MacOS Monterey 12.3.1
 - Version: Audacity 3.2 Alpha

**Comment by petersampsonaudacity** [comment]
Confirmed on W10 with 3.2.0 alpha master:
audacity-win-3.2.0-alpha-20220712+e7c7c39-x64-msvc2022

**Comment by crsib** [comment]
This will be fixed in #3176

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @crsib Dmitry's branch:  audacity-win-3.2.0-alpha-20220722+36e9236-x64-msvc2022 

I confirm this is fixed with PR #3176

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
