### ISSUE TITLE
Error opening sound device with Apple AirPods

### ISSUE THREAD

**Issue by grmelacz** [audacity/audacity#3227]
**Describe the bug**
When I want to use AirPods (Bluetooth headphones) with Audacity, I'm unable to play anything when the device is chosen - an error is triggered.

**To Reproduce**
1. Connect AirPods to your Mac2. 
2. Select them as your output device.
3. Play the audio.

**Actual behavior**
An error is triggered:

Error opening sound device.
Try chaning the audio host, playback device and the project sample rate.

```
{
    "timestamp": 1657714094,
    "event_id": "f9c0e29ba4894c709f85dd502b2adbf9",
    "platform": "native",
    "release": "audacity@3.1.3",
    "contexts": {
        "os": {
            "type": "os",
            "name": "Macintosh",
            "version": "10.16.0"
        }
    },
    "exception": {
        "values": [
            {
                "type": "Error",
                "value": "Error opening sound device.\nTry changing the audio host, playback device and the project sample rate.",
                "mechanism": {
                    "type": "runtime_error",
                    "handled": false
                }
            }
        ]
    }
}
```

**Expected behavior**
The audio is played to the headphones.

**Screenshots**
![Screenshot 2022-07-13 at 14 17 27](https://user-images.githubusercontent.com/41264018/178731502-ed7a74ce-ce77-4484-8135-5e6ea82dc46f.png)

**Additional information (please complete the following information):**
 - OS: Mac OS 12.4 Monterrey, Apple M1, MacBook Pro 13 2020
 - Version: Audacity 3.1.3
 - Sound Device: AirPods 2 A2031, firmware version 4E71

**Additional context**
Wired headphones and internal speakers work correctly. The AirPods work correctly when used in other apps.

**Comment by dozzzzer** [comment]
Hi @grmelacz , are you facing this error consistently, i.e. every time you launch Audacity and hit Play?

**Comment by grmelacz** [comment]
Every time I hit Play. Tried restarting the app, disconnecting and reconnecting the headphones, nothing helps.

**Comment by LWinterberg** [comment]
I've added some additional troubleshooting steps to https://audacityteam.org/errors. 

In each case, a fix for this is not on the table right now
