### ISSUE TITLE
None of the generators produce any sound

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3231]
**Describe the bug**
None of the generators (Chirp, DTMF, Nois, Tone) produce any audio clip.

**To Reproduce**
1. Go to 'Generate'
2. Select Chirp/DTMF/Noise/Tone
3. Confirm by clicking [OK]
4. Observe

**Actual behavior**
The dialog is closed but no audio clip is produced

**Expected behavior**
After the dialog closes, the corresponding audio clip is generated

**Additional information (please complete the following information):**
 - OS: any OS
 - Version: latest master build, e.g. https://github.com/audacity/audacity/actions/runs/2669888749

**Additional context**
'Generate' > 'Silence' works just fine

**Comment by petersampsonaudacity** [comment]
This is a regression on 3.1.3
