### ISSUE TITLE
Crash when clicking Debug in Nyquist plug-in

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3232]
**Describe the bug**
Crash when clicking Debug in Risset Drum (or Rhythm Track) generator dialog

**To Reproduce**
1. Go to Generate > Risset Drum (or Rhythm Track)
2. Click Debug
3. Observe

**Actual behavior**
Audacity crashes: https://sentry.audacityteam.org/share/issue/4136da944009482cb59b5f51b1bec04c/

**Additional information (please complete the following information):**
 - OS: MacOS 12.2.1
 - Version: latest master build

**Comment by petersampsonaudacity** [comment]
Confirmed on W10 - regression on 3.1.3

**Comment by SteveDaulton** [comment]
The bug appears to affect **all** Nyquist plug-ins, not  just ";type generate".

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest alpha master audacity-win-3.2.0-alpha-20220721+db0b7f8-x64-msvc2022

I confirm this works OK on W10

**Comment by SteveDaulton** [comment]
Works here too (Xubuntu 20.04).

**Comment by dozzzzer** [comment]
Verified on MacOS 12.2.1
