### ISSUE TITLE
Auto Duck can be called without adding a control track prior to that

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3236]
**Describe the bug**
Auto Duck can be called without adding a control track prior to that.

**To Reproduce**
1. Add a single audio track
2. Select the track and go to Effect > Auto Duck
3. Observe the warning message:
4. <img width="350" alt="image" src="https://user-images.githubusercontent.com/70063970/179042009-cce7859e-7f6e-40ab-ac06-389ef7b89213.png">
5. click OK
6. observe

**Actual behavior**
Auto Duck dialog pops up

**Expected behavior**
Warning message closes; Auto Duck effect won't open before the control track is added

**Additional information (please complete the following information):**
 - OS: MacOS 12.2.1
 - Version: latest master

**Comment by LWinterberg** [comment]
closing in favor of #3236
