### ISSUE TITLE
Effect name capitalization

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#3239]
**Describe the bug**
All of Audacity's effects, generators and analyze effect names are in Title Case, except for:
* Spectral edit multi tool
* Spectral edit parametric EQ
* Spectral edit shelves

**To Reproduce**
1. See here in the manual: https://manual.audacityteam.org/man/index_of_effects_generators_and_analyzers.html

**Expected behavior**
Consistent naming

**Additional context**
Could be fixed by pull request #3200

**Comment by arneja-arnav** [comment]
Hey is this issue still open? It seems like it has been resolve by @LWinterberg  #3200. 
If no, I'd love to work on it

**Comment by LWinterberg** [comment]
as you just pointed out, there's a PR to fix this already, so it's pointless to work on this.

**Comment by arneja-arnav** [comment]
Noted. Thanks. I was wondering why the issue had ven opened for quite a lot of time
