### ISSUE TITLE
Adding several specific realtime plugins into a stack can cause a deadlock/crash

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3244]
**Describe the bug**
Adding 5-7 plugins in a stack can cause deadlock/crash.

**To Reproduce**
1. Generate a rhythm track, start playback
2. Start adding AU plugins one by one from the sidebar: Room, Supermassive (https://valhalladsp.com/demos-downloads/)
3. Change settings in each entry by clicking the gear icon and changing some parameters
4. Keep adding until there are 5-7 of them in the stack

**Actual behavior**
Deadlock or even crash (rarely)

**Expected behavior**
No deadlock; possibly, there should be a limitation to the number of plugins that can be added to a stack (@Tantacrul , WDYT?)

**Screenshots**
If applicable, add screenshots/video to help explain your problem.

### Deadlock when adding Room and Supermassive plugins:

https://user-images.githubusercontent.com/70063970/179249510-999478c7-5485-4b8e-85e8-e2fdd4f190ea.mp4

**Additional information (please complete the following information):**
 - OS: Mac OS 12.2.1
 - Version: today's nightly build

**Additional context**
Sentry log of the crash: https://sentry.audacityteam.org/organizations/sentry/issues/22914/?query=is%3Aunresolved&statsPeriod=1h

**Comment by Tantacrul** [comment]
I've been thinking for a while that we might want to limit it. 5 or 6 seem like OK initial numbers.

**Comment by crsib** [comment]
Does it only happen with Valhalla?

**Comment by petersampsonaudacity** [comment]
Have you tested with powerful and less powerful machines?  

 I would suspect the less powerful would crumble earlier ...

**Comment by crsib** [comment]
I'm not sure if it is purely a CPU overtload issue. CPU overload will result in dropouts, but Audacity should not hang or crash

**Comment by crsib** [comment]
I've checked on my Mac (M1) and even with dozen of plugins I do not observe any noticable CPU load. So I do not think that CPU is a problem for @dozzzzer (who uses M1 Pro based Mac)

In fact I had to add 24 AU plugins to double the CPU usage from what Audacity requires simply to play the track.

**Comment by dozzzzer** [comment]
The issue doesn't seem to be the case anymore with the latest version 3.3.2.
