### ISSUE TITLE
Cannot select a preset or perform a context menu action in some AU plugins when called from the sidebar

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3245]
**Describe the bug**

- Cannot select a preset in certain AU plugins, e.g. Valhalla Supermassive, FabFilter plugins (e.g. Pro Q3, Pro-R, Timeless 2 etc.)
- Cannot perform an action from the context menu in any FabFilter plugin

when the plugins are instantiated from the Realtime Effects sidebar.

**To Reproduce**

1. load Valhalla Supermassive (https://valhalladsp.com/shop/reverb/valhalla-supermassive/)
2. try to select a built-in preset OR
3. load FabFilter Pro-Q 
4. right-click a band and select any action from the context menu (e.g. 'Delete')

**Actual behavior**
1. a preset cannot be selected
2. a context menu action cannot be performed

**Expected behavior**
1. a preset can be selected
2. a context menu action can be performed

**Screenshots**
<img width="600" alt="image" src="https://user-images.githubusercontent.com/70063970/179250194-d3a51535-b2cb-4743-a065-6b66ab6332d3.png">
<img width="600" alt="image" src="https://user-images.githubusercontent.com/70063970/179756651-298b1f86-d615-4a1f-aee6-8ff16b6598c8.png">

**Additional information (please complete the following information):**
 - OS: MacOS 12.2.1
 - Version: latest nightly build

**Additional Context:**
None of the above relates to the application of those plugins destructively.

**Comment by crsib** [comment]
Can this be related to the demo version?

**Comment by DavidBailes** [comment]
On Fri, 15 Jul 2022 at 17:08, Dmitry Vedenko ***@***.***>
wrote:

> Can this be related to the demo version?
>
It's free.

**Comment by DavidBailes** [comment]
On Fri, 15 Jul 2022 at 17:37, David Bailes ***@***.***> wrote:

> On Fri, 15 Jul 2022 at 17:08, Dmitry Vedenko ***@***.***>
> wrote:
>
>> Can this be related to the demo version?
>>
> It's free.
>
- not a demo version.

**Comment by LWinterberg** [comment]
The VST3 version on Windows selects presets just fine.

**Comment by Ryan-Miller-Audacity** [comment]
I can reproduce this on MacOS but not windows. 

Is this related to the non-modality of the realtime plugin ui? If you open the plugin via the effects menu it allows you to select presets through the context menus without issue, it is only when opened from the realtime panel that I see this issue (note that you can use the <> to scroll presets) of not being able to select a preset via the context menu.

**Comment by dozzzzer** [comment]
Not reproducible anymore
