### ISSUE TITLE
Regular Interval Labels crashes Audacity

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#3247]
**Describe the bug**
Regular Interval Labels crashes Audacity.

This is a regression on 3.1.3

**To Reproduce**
1. Generate 2 minutes of silence
2. Tools > Regular Interval Labels
3. Use the default settings and press OK
4. Observe: Audacity crashes silently with no crash report and no "phone-home"

**Actual behavior**
Audacity crashes

**Expected behavior**
10 labels to be created fro 0-1:30

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS: Windows 10 
 - Version: Audacity 3.2.0 alpha master

**Additional context**
Flagging @SteveDaulton  - but this would not appear to be an issue with Regular Interval Labels itself but a problem with Audacity itself.  If I run RIL in 3.1.3 but choose the "3.2.0" version of RIL then the the RIL works ...

**Comment by SteveDaulton** [comment]
>  If I run RIL in 3.1.3 but choose the "3.2.0" version of RIL then the the RIL works ...

That's surprising. Regular Interval Labels (equalabel.ny) was last changed in October 2018.

**Comment by dozzzzer** [comment]
I was able to reproduce the crash on Windows 11 machine using the STRs by @petersampsonaudacity, while on MacOS it works just fine.

**Comment by SteveDaulton** [comment]
Here's the problem https://github.com/audacity/audacity/commit/96e8d0be4bf2c5a0a98c0cf7956951bd1c75f53d

**Comment by crsib** [comment]
I will take a look, @SteveDaulton. This commit is a fix for a different crash

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest alpha master audacity-win-3.2.0-alpha-20220721+db0b7f8-x64-msvc2022

I confirm this works OK on W10

**Comment by dozzzzer** [comment]
Verified on MacOS 12.2.1 and Windows 11.
