### ISSUE TITLE
No preview is generated when clicking Play button in some VST3 plugins

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3251]
**Describe the bug**
Some VST3 effects do not generate audio when clicking the Preview button.

**To Reproduce**
0. Install Valhalla Supermassive (https://valhalladsp.com/demos-downloads/)
1. Generate some audio
2. Select Supermassive  from the Effect menu
3. Click Play button at the bottom: 

![image](https://user-images.githubusercontent.com/70063970/179543961-8c2a5984-94e6-4ff9-a182-7236febcbb31.png)

**Actual behavior**
No playback

**Expected behavior**
Pre-computed audio playback preview

**Additional information (please complete the following information):**
 - OS: Windows 10/11 x64
 - Version: latest master

**Additional context**
This happens to many other plugins

**Comment by LWinterberg** [comment]
This is fixed for me
