### ISSUE TITLE
Vertical meters lose numbering - and returning to horizontal also loses numbering

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#3254]
**Describe the bug**
If you resize your meters to vertical (with click&drag) most of the numbering of the reticules is lost.

Returning the meter to horizontal orientation also results in a partial loss of numbering.

This does **_not_** appear to be a recent regression. it is this way in 3.1.3 and 2.4.2, so not a result of the recent work on merged toolbars.

But it is a regression on 2.3.3 introduced in 2.4.0

**To Reproduce**
1. Float one of the meter toolbars
2. Click and drag left on the resizer triangle to make the meter minimum horizontall size
3. Click and drag down on the resizer triangle to turn the meter into vertical orientation
4. Observe: much of the numbering is missing - see Image 1
5. Now click and drag on the resizer triangle to return the meter to horizontal location
6. Observe: some of the numbering is missing - see image 2

**Actual behavior**
Missing numbering in meters

**Expected behavior**
Full and proper numbering in meters

**Screenshots**
### 1) Vertical meter enlarged vertically
![image](https://user-images.githubusercontent.com/50205984/179724272-7f5fa6e4-3198-40bd-9481-8def2335855e.png)

### 2) After returning meter to horizontal oriemtation
![image](https://user-images.githubusercontent.com/50205984/179723705-60f38b8f-295e-4114-9868-dbf3a563350b.png)

**Additional information (please complete the following information):**
 - OS: Windows 10 - but assume all OS
 - Version 3.2.0 and earlier

**Additional context**
Workaround:  **Tools > Reset Configuration**

**Comment by petersampsonaudacity** [comment]
@LWinterberg Leo and I wrote this in:
 Volume slider moves horizontally when the metering bar orientation is set to 'Vertical' #3242 

> not for 3.2, no. I honestly see it more likely that the vertical meter function gets removed altogether at this stage, though no decision has been made. I think it'll make sense to look at it again in a context of a new mixer (#1024, #3412) and multi-track recording to see what the ultimate fate of the vertical option in the meters should be.

That sounds sensible to me.

I, personally have never used vertical meters, never seen the point. And they just don't look good.  Plus they have to be undocked which can be a pain if you move the Audacity window about or resize it.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
