### ISSUE TITLE
Change tooltip text when hovering over playback/recording toolbars

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3255]
<img width="482" alt="image" src="https://user-images.githubusercontent.com/70063970/179737610-837a5022-672d-447e-b940-f2e54c8934de.png">

The hover text for both combined toolbars is "Audacity Meter Toolbar"

It would be better if each were renamed separately as:
a) "Audacity Recording Meter Toolbar"
b) "Audacity Playback Meter Toolbar"

Or even more simply (in the light of the new combined nature of the toolbars:
c) "Audacity Recording Toolbar"
d) "Audacity Playback Toolbar"

Especially since the combined toolbar now does setting as well as metering

_Originally posted by @petersampsonaudacity in https://github.com/audacity/audacity/issues/2779#issuecomment-1184408039_

**Comment by LWinterberg** [comment]
in addition, having a tooltip while dragging would be nice. It's not as necessary as for other places as now there's a numbering in the background that represents where the slider is, but it still would be nice

**Comment by petersampsonaudacity** [comment]
@LWinterberg   testing on W10 with latest alpha master  -  audacity-win-3.2.0-alpha-20220809+6f6501c-x64-msvc2022

These tooltips now say:
a) Recordng Level
b) Playback Level

Does this mean that this issue can be regarded as "fixed" and thus closed ?

**Comment by LWinterberg** [comment]
ah wait, this is specifically for the tooltip above the grabber (not the bar themselves), which still remains as described

**Comment by petersampsonaudacity** [comment]
OIC - all the toolbars (not just the meters) have a tooltip for the grabber and that tells the user what the toolbar is, is called.  

While hovering over the elemnt(s) kf the Tollbar tells the user waht each bit does.

But this should surely be anither simple strng fix @LWinterberg  ?

**Comment by LWinterberg** [comment]
Apparently not: 
https://github.com/audacity/audacity/blob/5ef7a51b8296a78600d9c06855f5312bce5a8cef/src/toolbars/ToolBar.cpp#L368
just pulls the label from
https://github.com/audacity/audacity/blob/498b01c7cd1bed427814599465031cebae66ab52/src/toolbars/MeterToolBar.cpp#L163
which doesn't distinguish between the two types, and I'm not sure if this is trivial to fix. 

I'm tempted to give this a wontfix because of that, as the main hover area - the meters themselves - are correct.

**Comment by petersampsonaudacity** [comment]
> ... which doesn't distinguish between the two types, and I'm not sure if this is trivial to fix.

I suspect that this is down to the fact that in earlier versions of Audacity the two meters were comboned in a single toolbar.

> I'm tempted to give this a wontfix because of that, as the main hover area - the meters themselves - are correct.

That would be a simple "solution"

**Comment by LWinterberg** [comment]
yeah, considering that this won't survive into 4.x anyway and is fairly miniscule as far as impact goes, let's just not do this

**Comment by petersampsonaudacity** [comment]
Although this was closed as "not planned" a while back (four  moths ago) - this has recently been FIXED bu @abhi-kr-2100  as apart of:

 **Add tooltips for Input/Playback Metering buttons #3968** 
https://github.com/audacity/audacity/issues/3968
