### ISSUE TITLE
(Linux) Closing Audacity after enabling journal recording displays crash window

### ISSUE THREAD

**Issue by Ryan-Miller-Audacity** [audacity/audacity#3261]
**Describe the bug**
On Linux platforms, closing Audacity after enabling the journal recording a crash window is triggered.

Note: This does not appear to have any negative impact on the user as Audacity still closes properly and can be reopened with journaling enabled without any issues. 

[Sentry Report](https://sentry.audacityteam.org/organizations/sentry/issues/23080/?query=is%3Aunresolved&statsPeriod=14d)

Screencast: 
https://user-images.githubusercontent.com/88568755/179978571-7a9ab328-55b3-4a85-a144-049d17953069.mp4

**To Reproduce**
1. Open Audacity on Linux OS (I used my VM on windows for testing)
2. Go to Tools > Write Journal
3. Click OK
4. Restart Audacity to enable journal writing
6. Close Audacity
7. Crash dialog is displayed.

**Actual behavior**
Crash dialog displays when closing Audacity after enabling Journal Recording.

**Expected behavior**
Crash dialog should not display when closing Audacity after enabling Journal Recording.

**Additional information (please complete the following information):**
 - OS: Linux Ubuntu 22.04 (Ran from Windows VM)
 - Version Most recent Master branch

**Additional context**
Ref: #3014 which initially mentions the crash.

**Comment by SteveDaulton** [comment]
This still happens with [Audacity 3.2.0 Alpha 1](https://github.com/audacity/audacity/releases/tag/Audacity-3.2.0-alpha-1)

Also note that writing the journal fails, so we have an undocumented menu item that doesn't  work, that would be of no use to end users even if it did work, that causes Audacity to crash on exit. That's not a good look for a major new release, so hopefully it'll be treated with higher priority than "P4" suggests.

**Comment by LWinterberg** [comment]
Journaling is not enabled in release builds. Regular users will not see this.

**Comment by SteveDaulton** [comment]
> Journaling is not enabled in release builds. Regular users will not see this.

That's good, but perhaps the https://github.com/audacity/audacity/releases/tag/Audacity-3.2.0-alpha-1 listed in GitHub "[Releases](https://github.com/audacity/audacity/releases)" should be a "release build" (to avoid confusion).

**Comment by crsib** [comment]
It is clearly marked as pre-release, it is not visible unless you click "Releases", it has *alpha* in title. I don't really get your point.

**Comment by SteveDaulton** [comment]
> It is clearly marked as pre-release, it is not visible unless you click "Releases", it has _alpha_ in title. I don't really get your point.

Maybe it's a terminology thing. I was testing as if this was a "Release", so as to provide information about what needs doing before the actual 3.2.0 release.

I would have expected that anything that will be disabled in the release would be built only in development builds, but this is clearly a "Release Build".

Thanks for the clarification.

![Screenshot_2022-09-01_20-32-23](https://user-images.githubusercontent.com/11681097/187997785-970800a4-3d6f-4d3b-82f9-c1f009a0d707.png)

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
