### ISSUE TITLE
Many swh (Ladspa and lv2) plug-ins don't persist correctly

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#3267]
In fact, any effect with an author name containing <> characters fails to persist.

- Install swh Ladspa plug-ins
- generate some sound in a new project
- add any effect, for which the author name includes an email address in `<angle brackets>`, to the track in the sidebar
- save the project; close it; reopen it; reopen the sidebar
- Observe: the effect is disabled and the cog wheel is gray

**Comment by dozzzzer** [comment]
Verified on Windows 11.

Several plugins seem to not have any controls to adjust, so for them no dialog window can be initiated when clicking the cog wheel button.

These are:
- dc_remove_1207.xml
- declip_1195.xml
- inv_1429.xml
- matrix_st_ms_1420.xml
- split_1406.xml
- surround_encoder_1401.xml
- wave_terrain_1412.xml
- zm1_1428.xml
