### ISSUE TITLE
3.2-Alpha sometimes hangs (Not Responding) after hitting space bar.

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#3274]
OK, so I have been doing a little light testing with the 3.2 Alpha builds for the past several weeks.  I haven't said anything before because, well, this is Alpha and bugs are to be expected.

So anyway, I have a blue-tooth foot pedal which I use to start and stop playback (from earlier recordings) in Audacity. This has caused me no issues on 3.1.3.  The problem I am experiencing is on the 3.2-Alpha sometimes I will hit the pedal = space bar and I will hear nothing in my headphones - so I look at the screen, hit the pedal again and I get the Not Responding error and the blue circle.

Typically I will get this error after a few hours of running (with different .aup3 files) and light editing typically zoom-outs/ins, adding a few labels and rarely, change tempo and undo.  Today the hang started before making any edits, only after a few zoom-outs/ins.

The good news is that Audacity can be terminated by right-clicking in the Windows task bar and selecting "Close Window" AND when restarting, Audacity offers to recover my project. (I typically refuse this as I don't typically alter the audio).

All on Windows 10.
This has happened consistently on Nightly downloads throughout the past month.  It has never happened on 3.1.3.

**Comment by JohnColket** [comment]
Please note: I have not seen this issue recur for the past several days.  If it doesn't happen again for a week, I'll assume the problem has been corrected and will close this issue.

**Comment by LWinterberg** [comment]
hm, I've not noticed that at all, ever. And considering you've not seen it either in a while, I'll close this - but feel free to reopen if you see anyone talking about this issue

**Comment by JohnColket** [comment]
Yes, you are correct.  I have not seen this issue resurface in the past 5 days.

**Comment by JohnColket** [comment]
So I'm not ready to reopen this yet - but I just experienced a similar "hang".

**Comment by JohnColket** [comment]
Not responding occurred again today on audacity-win-3.2.0-alpha-20220809+6f6501c-x64.
