### ISSUE TITLE
Reevaluate need to blacklist certain AudioUnit effects

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#3277]
Nine have been blacklisted in previous versions of Audacity:  

- [x] AUAudioFilePlayer
- [x] AUScheduledSoundPlayer
- [x] AUSpeechSynthesis
- [x] AUNetReceive
- [x] AUMixer3D
- [x] AUMultiSplitter
- [x] AUMultiChannelMixer
- [x] AUMatrixMixer
- [x] AUMixer

**Comment by dozzzzer** [comment]
> AUAudioFilePlayer - 
> AUScheduledSoundPlayer
> AUSpeechSynthesis

are AU instruments and should remain blacklisted

>  AUMultiChannelMixer
>  AUMatrixMixer
>  AUMixer
> AUMixer3D
> AUMultiSplitter

cannot be instantiated and should remain blacklisted too

> AUNetReceive

the need to receive audio isn't something we need at this point too

**Comment by Paul-Licameli** [comment]
But if there are action items to re-list those effects as bad ones, then put this back into to-do.

**Comment by Paul-Licameli** [comment]
Commit d7c160a00d38003530ab9f133b3c56c79c2c2277 has restored the black list
