### ISSUE TITLE
Manual rescan is required to reveal some plugins in the Plugin Manager

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3279]
**Describe the bug**
Some plugins are shipped through a standalone app used to install, manage, and update plugins and licenses (e.g. Waves plugins are shipped through Waves Central these days). When installing plugins using this app, Audacity only sees the plugins that were installed initially and doesn't see the consequent ones unless the `pluginregistry.cfg` is removed.

**To Reproduce**
1. Install Waves Central
2. Select a plugin in it and install
3. Run Audacity and see it being enabled
4. Install one or more plugins in Waves Central
5. Re-run Audacity to see if it picks them up

**Actual behavior**
No newly added plugins are added to Plugin Manager

**Expected behavior**
After discussing with @crsib it was agreed that the best possible option here would be to add an option to manually rescan the plugins by adding the 'Rescan' button into the Plugin Manager dialog.

**Comment by dozzzzer** [comment]
The only question left is the placement of the button within Plugin Manager.
@Tantacrul what do you reckon: left or right? Or anywhere else maybe?

<img width="500" alt="image" src="https://user-images.githubusercontent.com/70063970/180471511-3c4c9815-3b47-47d9-838d-34767b3f605e.png">

**Comment by Tantacrul** [comment]
I would have thought on the left, simply due to space. You don't want to overwhelm poor 'OK' and 'Cancel' 😄

**Comment by crsib** [comment]
I think this would be a good task for Kit, but we will see how it goes

**Comment by dozzzzer** [comment]
Verified
