### ISSUE TITLE
Vamp plug-ins: some plug-ins cannot be loaded

### ISSUE THREAD

**Issue by vsverchinsky** [audacity/audacity#3286]
Vamp plug-ins could not be loaded if the name of the plug-in contains '/' symbol.
(Like "bbc-vamp-plugins:bbc-speechmusic-segmenter/Speech/Music segmenter: Detection function" from [this](https://www.vamp-plugins.org/pack.html) pack.)

1. Install plugin pack using link above
2. Run Audacity and note that some vamp plugins are reported to be incompatible (skip this step if version of Audacity is lower than 3.2)
3. Open plugin manager and try to enable one of them

**Actual behavior**
Observe: "could not load library" message

**Expected behavior**
Plugin not reported as incompatible and loads without an issue

**Comment by dozzzzer** [comment]
I've managed to reproduce this.
In addition to 'Detection function', 
`bbc-vamp-plugins:bbc-speechmusic-segmenter/Speech/Music segmenter: Segmentation`

has also failed to load.
