### ISSUE TITLE
Unusable Plain GUI mode for AU plugins

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3291]
**Describe the bug**
The plain GUI mode for AU plugins is not usable for two main reasons:

1. the control labels and their value ranges sometimes do not make any sense at all
2. the min/max value labels are not readable 

**To Reproduce**
1. Generate some audio 
2. Call an AU effect from Effect menu (e.g. Kickstart 2, TAL Reverb 2, FabFilter Micro etc.)
3. Switch to the plain GUI mode

**Actual behavior**
### 1. For some plugins, like Kickstart 2, control naming and their values just don't make any sense:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/70063970/180828689-c2e3d71d-4997-4509-bcea-035deedfcff3.png">

### 2. Some other plugins show the values which are impossible to read:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/70063970/180829196-1fd2735d-018b-45de-8889-fa6401bb0b8b.png">
<img width="801" alt="image" src="https://user-images.githubusercontent.com/70063970/180829248-0e4586f0-253b-4826-b08e-5645ddc008db.png">

### 3. Some plugins (e.g. TAL Reverb-2) have redundant controls with no title (and also have partly hidden values):
<img width="500" alt="image" src="https://user-images.githubusercontent.com/70063970/180829366-2f993954-5b74-4c1c-8c70-6d25a30bd2bc.png">

**Expected behavior**
All the issues above should be addressed: all the values should become readable, with reasonable number of decimal points, all the parameters should reflect the ones present in GUI mode.

**Comment by Ryan-Miller-Audacity** [comment]
I was able to reproduce this as described in the latest master build on MacOS 12.5 and noted the issue with plain GUI for the audiounit effects noted above as well I've seen it with a few others. Realistically we want to have the same customer experience using plain GUI that they have with using the full graphical interface so we should handle these to be better/more usable.

**Comment by crsib** [comment]
Can you please check behavior in other DAWs? I wonder how they handle the first case

**Comment by Paul-Licameli** [comment]
AudioUnits is unlike the other effect families.  The plain GUI is built for us by a call to the AU toolkit.  It is not constructed in our own code with wxWidgets.  Notice the different styles.

If a certain plug in behaves badly in plain 
UI, it may be the fault of the plug in.

We might try to build our own dialogs for AU and control their appearance better, but I don’t think it is a worthwhile effort at this point.

**Comment by Ryan-Miller-Audacity** [comment]
Retesting this in the current public release (3.3.2) I still see some of the behaviors noted above with improper display of parameters within non-GUI interfaces of AU plugins; however, given that non-GUI interfaces are a chosen option (graphical is the default (and standard)), and Paul's comment above that the AU toolkit retains control of building the plain UI (not Audacity), I feel that we can close this as not planned for the time being. Possibly could be reinvestigated post-QT migration if that opens up easier avenues for us to build out own AU plain UIs.
