### ISSUE TITLE
No I/O monitoring in real-time VSTs

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3298]
**Describe the bug**
When calling a VST plugin from the Realtime Effects panel, there's no input/output signal visualization.

**To Reproduce**
1. Call a VST plugin that is supposed to produce some visual representation of the input/output signal (e.g. FabFilter Pro-Q)
2. Start playback
3. Open the plugin by clicking the cog wheel button

**Actual behavior**
No input/output monitoring:

![image](https://user-images.githubusercontent.com/70063970/181288606-aea2192f-153c-4343-ba01-5e24575f447d.png)

**Expected behavior**
Input/output monitoring works as expected

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version: latest master

**Comment by Paul-Licameli** [comment]
Testing VST effects in the side panel is premature while the transition to statelessness is incomplete.
