### ISSUE TITLE
Realtime FX: when initializing factory defaults in a VST/VST3 plugin, it doesn't affect the sound

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3299]
**Describe the bug**
When initializing factory defaults in a VST/VST3 plugin, it doesn't affect the sound, i.e. only the visual part changes.

**To Reproduce**
1. Load some audio
2. Add a VST/VST3 effect plugin from the Realtime Effects panel
3. Start playback
4. Change the plugin's parameters to get audible changes to the sound
5. Click the hamburger menu > _Factory Presets_ > _Defaults_
6. Observe

**Actual behavior**
Graphical controls got reset to the initial position which, however, caused no audible changes to the playback sound.

https://user-images.githubusercontent.com/70063970/181290792-51a0be04-6946-4ce4-8f56-eb3cb6b7e714.mp4

**Expected behavior**
The sound changes correspondingly as if the effect was in its default state.

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version: latest master

**Comment by Ryan-Miller-Audacity** [comment]
I can reproduce the behavior above as described on MacOS in the latest master build; however, I am wondering if this is a symptom of VST3 not being fully converted to statelessness? I tested this with AUs and LV2 plugins (which have been converted to statelessness) and they seem to handle this situation appropriately.

**Comment by dozzzzer** [comment]
No more reproducible
