### ISSUE TITLE
Effect grouping preferences not reflected in realtime effects menu

### ISSUE THREAD

**Issue by Ryan-Miller-Audacity** [audacity/audacity#3311]
**Describe the bug**
Changing effect grouping/sorting in preferences is not reflected in realtime effect panel menu. Users can edit the grouping/sorting of the effects list in their preferences which is proper reflected within the destructive effects dropdown, but the realtime effects panel menu does not update to these preferences.

<img width="1074" alt="realtime-vs-destruvtive-effect-grouping" src="https://user-images.githubusercontent.com/88568755/181742816-7c733915-6875-45e1-83c4-3de9dbeecc70.png">

**To Reproduce**
1. Go to the Preferences pane->Effects and change the grouping/sorting option to default
2. Compare the destructive effects top menu to the realtime effects menu (sorting/grouping is the same)
3. Go to the preferences pane-> Effects and change the grouping/sorting option to a non-default value (grouped by type for example) 
4. Compare the destructive effects top menu to the realtime effects menu (sorting/grouping was updated in the destructive effects menu, but the realtime effects menu did not update to the new sorting/grouping)

**Actual behavior**
Realtime effects ui menu did not update grouping/sorting according to preferences settings.

**Expected behavior**
Realtime effects ui menu should update based on grouping/sorting according to preferences settings.

**Additional information (please complete the following information):**
 - OS: MacOS Monterey 12.3.1 (not OS specific issue)
 - Version: 3.2 Master

**Comment by jessjwilliamson** [comment]
It would be ideal if RT effects context menu also does the same sorting File type > Author.. etc.

**Comment by Ryan-Miller-Audacity** [comment]
Closing in favor of #3866 .
