### ISSUE TITLE
"Enable" checkbox in real-time preview is non-functional

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#3312]
**Describe the bug**
The "Enable" checkbox in real-time preview effects is disabled by default (it should be enabled by default), but the effect is enabled whether the checkbox is checked or not

**To Reproduce**
1. Start playing a real-time preview
2. Toggle the "Enabled" option on and off

**Actual behavior**
The effect is active regardless of the state of the "Enabled" option.

**Expected behavior**
When not enabled, the original (dry) audio should be heard.

**Screenshots**
![Screenshot_2022-07-29_11-25-45](https://user-images.githubusercontent.com/11681097/181744141-5826892d-4a1b-4342-85aa-a341e1afa76d.png)

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version Audacity 3.2.0 db0b7f 

**Additional context**

**Comment by crsib** [comment]
#3090 changes the UI, #2987 and 3102 change the behavior as well. @LWinterberg I think this should be closed.
