### ISSUE TITLE
Missing graphic elements in Calf plug-ins

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#3314]
**Describe the bug**
Important parts of the GUI of Calf plug-ins are not displayed. This is a regression against Audacity 3.1.3.

**Screenshots**

Audacity 3.1.3 with Calf 5 band Eq:
![313](https://user-images.githubusercontent.com/11681097/181748060-667ee091-8b27-4143-992e-0b8399322946.png)

Audacity 3.2.0  a2a06f  with Calf 5 band Eq:
![320](https://user-images.githubusercontent.com/11681097/181748497-14dfc3f4-2ed3-46c9-b85a-bdd7a3d2f1f4.png)

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version 3.2.0  a2a06f GitHub AppImage

**Comment by SteveDaulton** [comment]
> Looks like it affects preview in destructive path only. Still needs to be fixed

I see the same issue when using the effect as a non-destructive effect (when it decides to work without crashing).

**Comment by evertvorster** [comment]
Thanks for looking into this bug. 

Having the Calf plugins work correctly adds quite a bit of functionality to Audacity... for my workflow at least. The equalizer supplied by Calf is one of the very few that allows you to define the width or "Q" of the effect, and the visual feedback it used to have is really nice.

**Comment by evertvorster** [comment]
This bug is still present in current git master (2023-04-14)

**Comment by evertvorster** [comment]
This bug is also affecting the LV2 version of LSP plugins available on Linux. In version 3.1.3 of Audicaty, the LV2 version of LSP-plugins work perfectly, and any version after that the lines are spectrum analyzer is missing from the GUI.

**Comment by crsib** [comment]
And x42 as well

**Comment by Paul-Licameli** [comment]
> And x42 as well

I did put some effort into figuring out this bug and I made some progress but didn’t find a complete solution.  Other matters intervened.  I might resume the work.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
