### ISSUE TITLE
Import dialog should import filenames with numbers by number rather than alphabetically

### ISSUE THREAD

**Issue by rrthomas** [audacity/audacity#3319]
**Describe the bug**

The Gtk open file dialog, when sorting by name (the default), does not sort strictly lexically, but has some intelligence (which is quite helpful). For example, consider the following directory:

```
$ ls -1
10.mp3
1.mp3
6.mp3
```

If I open this in the Gtk file dialog, It shows the files in the order `1.mp3`, `6.mp3`, `10.mp3`. That's user-friendly!

**To Reproduce**
1. File→Import→Audio…
2. Navigate to a directory containing the above file names.
3. Click on 1.mp3, Shift-click on 10.mp3.
4. Click Open

**Actual behavior**
The files are imported in the order 10.mp3, 1.mp3, 6.mp3.

**Expected behavior**
The files should be imported in the order in which they were selected/displayed.

**Additional information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version: Audacity 3.1.3

**Comment by LWinterberg** [comment]
Are you sure this is an Audacity bug and not a Gtk bug?

**Comment by rrthomas** [comment]
@LWinterberg I'm an Audacity user, so when I have a problem with Audacity, I report it as an Audacity bug, and expect that the developers will triage it, and, if the bug is in a dependency, file an appropriate bug upstream, and link it to the Audacity issue (which, after all, is still an issue in Audacity, even if the fix ends up being in the dependency). I didn't think there was an expectation that I, a user of Audacity, would analyse the code and work out where the bug is myself? I happen to be a developer myself, and might be able to do that (though it would be time-consuming, as I'm not experienced with the Audacity or Gtk source code), but working out in which component a bug actually exists will surely be beyond the capacity of most users!

**Comment by LWinterberg** [comment]
testing with another program would've been sufficient to figure out if this was Audacity-specific or a wider gtk issue...

Anyway, having done this testing myself now, this behavior is not specific to Linux, nor is it unique to Audacity - openshot also exhibits the same behavior, as does of course `ls`. 

This issue would probably fit in well with a more general organization-related release, potentially together with project bins (#2462).

Unfortunately, our [roadmap](https://github.com/audacity/audacity/wiki/Roadmap) is currently quite full for the forseeable future, so implementing this is not on the table for quite some time. Closing for now. 

(Moving away from strict alphabetical sorting also is more of a feature request than a bug.)

**Comment by rrthomas** [comment]
> testing with another program would've been sufficient to figure out if this was Audacity-specific or a wider gtk issue...

That is not correct: if I found the same problem in another program, it could be two bugs (one in Audacity, one in the other program) or a single bug (in Gtk).

> Anyway, having done this testing myself now, this behavior is not specific to Linux, nor is it unique to Audacity - openshot also exhibits the same behavior, as does of course `ls`.

I don't understand this: `ls` does not exhibit the same behavior. The behavior in question is a difference between how files are displayed to the user and how they are treated internally. In the case of `ls`, there's only a display.

> This issue would probably fit in well with a more general organization-related release, potentially together with project bins (#2462).

Great, so why close the issue?

> Unfortunately, our [roadmap](https://github.com/audacity/audacity/wiki/Roadmap) is currently quite full for the forseeable future, so implementing this is not on the table for quite some time. Closing for now.

Does that mean the issue will be reopened in future?
 
> (Moving away from strict alphabetical sorting also is more of a feature request than a bug.)

The issue I reported is that Audacity does not import files in the order in which they are selected, not that they are sorted one way or another.

**Comment by LWinterberg** [comment]
> Does that mean the issue will be reopened in future?

Yes.

**Comment by rrthomas** [comment]
> > Does that mean the issue will be reopened in future?
> 
> Yes.

That's something! Thanks very much for your work on Audacity, @LWinterberg.
