### ISSUE TITLE
Meter sliders do not match scale with non-default options

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#3322]
**Describe the bug**
With default meter options, moving the meter sliders from 0 (default) to -6, reduces the level by -6 dB (as expected).
For non-default meter options (for example, if the meter dB  is set to -36 dB rather than the default -60 dB range), the amount of attenuation no longer matches the scale.

**To Reproduce**
1. Calibrate your system so that a known test signal produces a recorded level of exactly 0 dB.
2. Set the recording meter to "linear" scale.
3. Reduce the recording level slider to "0.5".
4. Record the test signal.

**Actual behavior**
The recording level is around -30 dB.

**Expected behavior**
The recording level to be 0.5 linear (-6.02 dB).

**Screenshots**
![meter slider](https://user-images.githubusercontent.com/11681097/181934871-85b500f6-eda3-448e-8c8c-c7b6814ea5a1.png)

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version  3.2.0 alpha

**Additional context**

**Comment by petersampsonaudacity** [comment]
@LWinterberg @dozzzzer 

is this not fixed by #3810 ??

**Comment by petersampsonaudacity** [comment]
But the slider scales have **_never_** been in dB - for example in2.4.2  they were decimal fractions:
![image](https://user-images.githubusercontent.com/50205984/200839932-b2548258-ba2d-48e3-a7ab-4ca4cae47859.png)

**Comment by petersampsonaudacity** [comment]
Even in DarkAudacity 2.3.2 where @JamesCrook  first tried incorporating the sliders with the meters and losing the mixer toolbar he had decimal fractions for the slider values.

He avoided the dB versus percentage/decimal fraction by removing the numbers and hence the dB in the meters:

![image](https://user-images.githubusercontent.com/50205984/200841808-690971f0-5f2d-440e-a3b1-c57a7fa37e66.png)

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
