### ISSUE TITLE
Audacity Flatpak does not run on Linux Mint 21 Vanessa. Appimage runs fine though

### ISSUE THREAD

**Issue by ngalerchalegocity60330** [audacity/audacity#3332]
## **Describe the bug**
On Linux Mint 21 Vanessa, the newest release of Linux Mint, what would happen was that the app would just open a dialog boxin the lines of "Audacity is starting up... is not responding", instead of Audacity itself, and when I clicked "wait" nothing would happen. However, on the bright side, the Appimage ran fine.

## **To Reproduce**
**Use Linux Mint 21 Vanessa for this.** Just download the Audacity flatpak package from the software manager then try to run it.

## **A WORKAROUND**

Thanks to @vanphong1310 for this

1. Download Flatseal.
2. Open Flatseal.
3. You should see a selection of applications on the Flatseal window. Go to the Audacity section.
4. Scroll down until you see the "File system" section, then go to the section in there that says "Other files." 
5. You should see an option that says "xdg-run/pipewire-0 ". Remove it by clicking the x on the right.

**Comment by LWinterberg** [comment]
Apparently, PopOS flatpaks have (had?) the same issue, I added your report for the maintainer there as well. 

You may want to give some more debug info, such as: 

* what does it say if you launch the flatpak version from the command line? Are there any error messages?
* What kind of system are you on? What sound devices do you use, what audio systems (pulseaudio, pipewire, plain ALSA, JACK), what language is your OS, and so on.

**Comment by JulianHeuser** [comment]
I'm having the same issue here as well. Worked on 20.3, upgraded to 21, now whenever launching the flatpak it hangs forever on the "startup" screen. System info below:

- Linux Mint 21 (x86_64)
- Kernel 5.15.0-41-generic
- DE: Cinnanon 5.4.9
- Pulseaudio

This is a fairly fresh install so everything else should be fairly normal for LM21.

I checked the gnome logs app and there wasn't really anything of note - let me know if there's other logs I should check.

**Comment by crsib** [comment]
The wild guess from the Pop_OS discussion is that this issue is related to the PulseAudio.

AppImage works, though

**Comment by ngalerchalegocity60330** [comment]
![Screenshot from 2022-08-29 00-34-54](https://user-images.githubusercontent.com/104356907/187087427-8695f6f9-b196-4871-9a64-1213022894ef.png)

**Comment by vanphong1310** [comment]
I tried to install Linux Mint 21 on virtualbox, with original state or after pipewire was updated to 0.3.59 (from ppa:pipewire-debian/pipewire-upstream), audacity didn't work at all.
The last build commit that work in original state install is b3463eb8dab1e2b2f8a5f543f2df39796709ab768f7c9aa387da70d0757c4349 (version 3.0.2), all commit after this isn't work.

**Comment by vanphong1310** [comment]
I tried to install Linux Mint 21 on virtualbox, with original state or after pipewire was updated to 0.3.59 (from ppa:pipewire-debian/pipewire-upstream), audacity didn't work at all.
The last build commit that work is
`b3463eb8dab1e2b2f8a5f543f2df39796709ab768f7c9aa387da70d0757c4349`
This is version 3.0.2, all commit after this isn't work.

**Comment by vanphong1310** [comment]
I tried to install Linux Mint 21 on virtualbox, with original state or after pipewire was updated to 0.3.59 (from ppa:pipewire-debian/pipewire-upstream), audacity didn't work at all.
The last build commit that work in is
`b3463eb8dab1e2b2f8a5f543f2df39796709ab768f7c9aa387da70d0757c4349`
This is version 3.0.2, all commit after this is broken.

**Comment by vanphong1310** [comment]
I tried to install Linux Mint 21 on virtualbox, with original state or after pipewire was updated to 0.3.59 (from ppa:pipewire-debian/pipewire-upstream), audacity didn't work at all.
The last build commit that work is
`b3463eb8dab1e2b2f8a5f543f2df39796709ab768f7c9aa387da70d0757c4349`
This is version 3.0.2, all commit after this is broken.

**Comment by vanphong1310** [comment]
I tried to install Linux Mint 21 on virtualbox, with original state or after pipewire was updated to 0.3.59 (from ppa:pipewire-debian/pipewire-upstream), audacity didn't work at all.
The last build commit that work is
b3463eb8dab1e2b2f8a5f543f2df39796709ab768f7c9aa387da70d0757c4349
This is version 3.0.2, all commit after this are broken.

**Comment by vanphong1310** [comment]
I tried to install Linux Mint 21 on virtualbox, with original state or after pipewire was updated to 0.3.59 (from ppa:pipewire-debian/pipewire-upstream), audacity didn't work at all.
The last build commit that work is
`b3463eb8dab1e2b2f8a5f543f2df39796709ab768f7c9aa387da70d0757c4349`
This is version 3.0.2, all commit after this are broken.

**Comment by vanphong1310** [comment]
You can try this workround to start it (it work for me):
Install Flatseal -> Audacity app -> Filesystem section -> Remove xdg-run/pipewire-0 row in Other files.

**Comment by ngalerchalegocity60330** [comment]
To @vanphong1310.
Yes this does work. Thank you very much. I'm using Linux Mint 21.1 Vera and now it works. Not using your workaround unfortunately still gives me the same problem. Until something is done about it, this probably is the best workaround.

**Comment by tudo75** [comment]
> You can try this workround to start it (it work for me): Install Flatseal -> Audacity app -> Filesystem section -> Remove xdg-run/pipewire-0 row in Other files.

@vanphong1310 This workaround fix th problem also for me on Linux Mint 21.1 Vera XFCE.
Thanks

**Comment by lucasgabmoreno** [comment]
> 
Thanks!

**Comment by ronny332** [comment]
Still exists. Linux Mint 21.3 with Pulse Audio. The Workaround still works.

**Comment by Uneccessary** [comment]
Issue still exist in the latest version of Linux Mint, the work around still works too.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444) which uses a different build system. This bug should no longer be applicable.
