### ISSUE TITLE
Serialization of AU effect settings doesn't work

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#3347]
- Generate a track; add an AudioUnit effect to it (for instance, AUMatrixReverb)
- Open the dialog, and note the default values.  Change settings (for instance, choose the "Cathedral" preset; "Large Density" is then at max)
- Save, close, and reopen the project
- Reopen the effect settings with the cogwheel

Expect to see the last settings; but instead observe the default settings

**Comment by pietro68** [comment]
Verified that the fix works, and posted a question about the code changes
