### ISSUE TITLE
Run Benchmark tool fails

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#3364]
- Tools > Run Benchmark (this is a little known regression test built into the program itself)
- Press Run
- Observe failure message

Problem bisects to commit

33318a421544fcadbf753271500d3bb5b238ba99

**Comment by petersampsonaudacity** [comment]
Confirmed on W11 with latest alpha master  -  audacity-win-3.2.0-alpha-20220812+fd9bd23-x64-msvc2022

This is a regression on 3.1.3

**Comment by vsverchinsky** [comment]
Turned out there are few more issues introduced by that commit:
1) Incorrect selection region after cutline expansion
2) Fixes insertion into the clip
3) Fixes issue with replacing part of wave track with generated data (and special cases with cutlines and preserving split lines)
