### ISSUE TITLE
Non-modal effect dialog does not update for change of language

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#3366]
- Add Reverb or Wahwah (or other built-in effect) to an effect stack
- open the non-modal settings dialog
- Go to Preferences, Interface, change language, close the dialog

Expect static texts and title in the dialog to update.

There are other non-modal dialogs in Audacity for which this problem was deliberately fixed before, but now the effect dialog is an omission.

To implement, see for instance `void HistoryDialog::UpdatePrefs()` for an example of a message subscription to rebuild a non-modal for changes of language.

**Comment by petersampsonaudacity** [comment]
Tested on W11 with latest alpha master audacity-win-3.2.0-alpha-20220815+c79a747-x64-msvc2022

I confirm the language m=now changes properly as expected
