### ISSUE TITLE
Non-modal effect dialog is closed unnecessarily for Undo or Redo

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#3367]
- make a track with an effect in its stack
- Make any two undo-able edits that do not delete the track
- Undo once
- Click the gear
- Either Undo or Redo

Expect the dialog to remain open.

**Comment by petersampsonaudacity** [comment]
Tested on W11 with latest alpha master audacity-win-3.2.0-alpha-20220815+c79a747-x64-msvc2022

I confirm that the dialog remains open.
