### ISSUE TITLE
DTMF reads past the dtmfSequence boundary

### ISSUE THREAD

**Issue by crsib** [audacity/audacity#3368]
`EffectDtmf::Instance::ProcessBlock` potentially reads past the `dtmfSequence` boundary. There are no checks on `curSeqPos` value and Stage seems to always send a full block to the generator.

Out of the box, corresponding assertion is only generated by Microsoft STL in debug mode. However, this is potentially can be a serious problem.

**To Reproduce**
1. Add `assert(curSeqPos < dtmfSettings.dtmfNTones)` after `curSeqPos` is incremented in `EffectDtmf::Instance::ProcessBlock`
2. Try to generate a DTMF tone on default settings

**Comment by Paul-Licameli** [comment]
A better place for the assertion would be just before `curSeqPos` is used as a subscript.
