### ISSUE TITLE
Incorrect peak level detection

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#3372]
**Describe the bug**
Peak level detection is sometimes incorrect, causing incorrect behaviour in some effects and plug-ins.

**To Reproduce**
1. Open the attached "sample project" (created in Audacity 3.2.0 alpha)
2. With the first clip selected, open the Amplify effect.

**Actual behavior**
The Amplify effect default to 1.938 dB (amount required to amplify to 0 dB)

**Expected behavior**
The actual peak level of the first clip is -22.32 dB, so the  Amplify effect should default to 22.32 dB.

**Sample Project**
https://www.dropbox.com/s/vjd7mlr93l7yxzk/amplify.aup3?dl=0

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04
 - Version 3.2.0 alpha

This is a regression against Audacity 2.4.2.

UPDATE from PRL: A problem in WaveClip::GetMinMax, not neglecting the hidden data, means the bug will also influence the Normalize effect, and the PEAK and PEAK-LEVEL properties of *SELECTION* in Nyquist.

**Comment by petersampsonaudacity** [comment]
There is something odd about that project

### When I open it with 3..2.0 or 3.13 I see

### When I open it with 3..0.0 or 3.13 I see
![image](https://user-images.githubusercontent.com/50205984/184595742-ab9d8647-ae41-4c1f-a3e5-57054b163825.png)

**Comment by petersampsonaudacity** [comment]
The other odd thing (testing on W10 with 3.2.0 alpha) 

If I make a small selection in either of the clips and apply Amplify then I get your expected calue of 22.32
![image](https://user-images.githubusercontent.com/50205984/184598131-b7e796c3-6198-456b-9ecb-24870862c0f0.png)

BUT this does not happen If I select the whole of wither of the rwo clips - or make a partial selection across the two clips
![image](https://user-images.githubusercontent.com/50205984/184598733-b793a502-ab46-4a39-b92d-ffafa1bd82e9.png)

**Comment by petersampsonaudacity** [comment]
I don't know how this accidentally got closed - Sorry mea maxima culpa / my bad ...

**Comment by dozzzzer** [comment]
I confirm this on MacOS

**Comment by Paul-Licameli** [comment]
@petersampsonaudacity I think the strange pictures in earlier Audacity are because you open a project with hidden clip data, which older versions misinterpret.

**Comment by Paul-Licameli** [comment]
A problem in WaveClip::GetMinMax, not neglecting the hidden data, means the bug will also influence the Normalize effect, and the `PEAK` and `PEAK-LEVEL` properties of `*SELECTION*` in Nyquist.

**Comment by petersampsonaudacity** [comment]
Testing on W11 qith latest alphqa master audacity-win-3.2.0-alpha-20220823+ac27c11-x64-msvc2022

This now appears to work correctly on Windows
