### ISSUE TITLE
Linux version forces to show all titlebar buttons (client side decoration issue?)

### ISSUE THREAD

**Issue by sith-on-mars** [audacity/audacity#3381]
**Describe the bug**
I turned off maximise and minimise titlebar buttons in Gnome Tweaks, so there should be only a close button on the titlebar across all apps. However, Audacity would ignore Gnome Tweaks and display all titlebar buttons. Is it because Audacity disables client side decoration?

**To Reproduce**
Open Audacity.

**Actual behavior**
Audacity display all titlebar buttons, despite the fact that I turned turned off maximise and minimise titlebar buttons in Gnome Tweaks:

![image](https://user-images.githubusercontent.com/37974764/185034538-2292ca03-5b16-491c-b012-ad1fe7c8b76a.png)

**Expected behavior**
I would expect I only see the close button on the titlebar:

![image](https://user-images.githubusercontent.com/37974764/185034310-501132ea-b240-4fb1-97fc-a131f0b660b8.png)

**Additional information (please complete the following information):**
 - OS: OpenSUSE Tumbleweed Gnome
 - Version 3.1.3-beta-20220626

**Comment by LWinterberg** [comment]
I don't think we'll get around to fixing this before porting to Qt (and it's probable that porting to Qt will solve this anyway). I'll therefore close it as a [known issue](https://github.com/audacity/audacity/wiki/Known-Issues)
