### ISSUE TITLE
Linux: Dock position indicator missing

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#3382]
### Bug description

When dragging a toolbar into the top or lower dock, there was previously a little blue triangle that indicated where the toolbar would be positioned when the left mouse button was released. The blue triangle no longer appears, though there is sometimes a black "dash" (see screenshot) that appears (perhaps a malformed version of the blue triangle?)

### Steps to reproduce

1. Grab one of the toolbar handles and drag the toolbar over the upper or lower docks.

### Expected behavior

A blue triangle to appear, indicating the toolbar placement if the left mouse button is released.

### Actual behavior

No blue indicator triangle, but sometimes a dash appears.

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

![Screenshot_2022-08-17_12-24-39](https://user-images.githubusercontent.com/11681097/185108063-70cdf58d-6ad6-4455-b5f2-ecbeb733b129.png)

**Comment by Ryan-Miller-Audacity** [comment]
Hmmmm when testing in my linux vm in the most recent alpha ([audacity-linux-3.2.0-alpha-20220818+5d32896-x64-20.04](https://github.com/audacity/audacity/suites/7870105763/artifacts/333908580)) I am still seeing the black triangle dock tracker as normal (see screencast). I double checked this on windows and mac and see the triangle properly there as well.

Perhaps there is an element to this issue that I am missing? Any additional context you can give for me to be able to reproduce? (I do text on a Linux VM on my windows machine FYI).

[linux drag interface arrow.webm](https://user-images.githubusercontent.com/88568755/185392204-1612f8e8-c16c-484e-87c7-4d713d9277f4.webm)

**Comment by SteveDaulton** [comment]
On my machine (real hardware), dragging toolbars is horrible.

Using https://github.com/audacity/audacity/suites/7870105763/artifacts/333908580 on (almost standard) Xubuntu 20.04 LTS (fully updated) on real hardware (i7, Intel Corporation HD Graphics 530).

https://youtu.be/xQhgGKOJLnM

**Comment by LWinterberg** [comment]
could not reproduce either, both the appimage and a selfcompiled build have it show up just fine for me on ubuntu 22.04. I suspect this is the same bug as #1709 which causes any "floating" graphics to be squished down into 1px black lines

**Comment by agguzman** [comment]
Tried to reproduce it in **Xubuntu** 20.04 and 22.04 on a laptop. In both of them the dock position indicator appears as half a triangle. Maybe it could be related to Xfce usage in Xubuntu where as Ubuntu uses GNOME as the default environment.
<img width="683" alt="Xubuntu 22 04 Dock Toolbar" src="https://user-images.githubusercontent.com/110631698/224323105-76319844-4bb1-4d9e-bbef-401b19b21ab6.png">
