### ISSUE TITLE
Meter clipping indicators obscured by sliders

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#3385]
### Your idea

Move the clip indicator a little further to the right so that it isn't obscured by the slider.

Current design (current development build)
![hidden](https://user-images.githubusercontent.com/11681097/185145143-a3c526a8-67d0-476b-b20a-da562041531f.png)

Clip indicator moved a little to the right so that the clip indicator is always visible.
![revealed](https://user-images.githubusercontent.com/11681097/185140560-bbea23bd-c521-420d-a986-6ff3d3dd43dd.png)

### Problem to be solved

The meter's clip indicators are mostly hidden by the slider when using default settings.

### Additional context

The meter's clip indicator is more important now that Audacity has real-time effects as real-time effects may push the track level into clipping, but the clipping is **not** displayed by "[Show Clipping](https://manual.audacityteam.org/man/view_menu.html#show_clipping_onoff)".

**Comment by Ryan-Miller-Audacity** [comment]
This definitely seems like a worthwhile enhancement to better the experience with the new meter sliders.

**Comment by crsib** [comment]
Hmm, Show Clipping problem definitely deserves a bug itself

**Comment by DavidBailes** [comment]
and the peak value indicator (blue) line can also be obscured if it coincides with the thumb of the slider.

**Comment by petersampsonaudacity** [comment]
> We're not targeting this for 3.2 or 3.3. We have a lot of significant performance issues and unmerged PRs to work through.

Thanks for the heads-up Martin

**Comment by Tantacrul** [comment]
That's not to say it's not a good point. I think we really need to soup up the mixer and make it more prominent and discoverable because, in truth, this is what I'd use in order to really keep track of my audio levels.

We'll also give thought to the metering / obscuring issue as it stands too.

**Comment by LWinterberg** [comment]
This is fixed in 4
