### ISSUE TITLE
Default Effect Menu is corrupted

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#3386]
### Bug description

Default effect menu is corrupted, organized by author and not effect type

### Steps to reproduce

1. launch latest alpha master  -  audacity-win-3.2.0-alpha-20220817+bc2ad84-x64-msvc2022
2. click in **Effect**
3. Observe incorrect menu

![image](https://user-images.githubusercontent.com/50205984/185145095-edcfe0f2-35f3-4ae5-b316-9496347b0a3a.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/50205984/185145265-d5076a1c-9335-4346-8472-aad68df5c1f0.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/50205984/185145095-edcfe0f2-35f3-4ae5-b316-9496347b0a3a.png)

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows 11 - but assume all OS

### Additional context

This is a regression against recent alpha masters - for example:  audacity-win-3.2.0-alpha-20220815+1cf0ba2-x64-msvc2022

**Comment by petersampsonaudacity** [comment]
And sometimes I see this different odd layout as the default

![image](https://user-images.githubusercontent.com/50205984/185148008-e474c809-450d-4a2d-90e6-4c5871cbf9e4.png)

**Comment by LWinterberg** [comment]
Likely caused by https://github.com/audacity/audacity/pull/3337

**Comment by petersampsonaudacity** [comment]
I note the Analyze and Tools menus on defaul have named menu entries for "Steve Daulton".

I thought we had agreed that we would not have such personally named menu items.

![image](https://user-images.githubusercontent.com/50205984/185174857-7a7d4f62-6ab3-460b-b339-1c304b10c3d9.png)


![image](https://user-images.githubusercontent.com/50205984/185175118-4ae5c7fd-9987-4de2-913e-0169d20ded58.png)

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest alpha master  -  audacity-win-3.2.0-alpha-20220825+3bc3c94-x64-msvc2022

I confirm this is fixed on W10
