### ISSUE TITLE
The effect can still be heard on the track even after undo-ing it

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3389]
### Bug description

After applying an effect destructively and canceling it via "Edit > Undo" menu, it still can be heard as if no Undo action was made.

### Steps to reproduce

1. load some audio
2. apply an effect (e.g. Reverb)
3. Undo via "Edit > undo"
4. play the audio again

### Expected behavior

The original sound (before application of the effect) is played

### Actual behavior

The sound has the effect applied to it as if it was never undone:

https://user-images.githubusercontent.com/70063970/185210309-17d50c58-80e3-4da4-9918-e2a866d8b241.mp4

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

### Additional context

Discovered while testing #3315 

I believe the regression was introduced by the PR #3349

**Comment by crsib** [comment]
STR can be simpler
* Generate chirp
* Open any RT capable effect from the Effects menu
* Close it
* Observe
