### ISSUE TITLE
Linux: Latency compensation setting has no effect until Audacity is restarted.

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#3399]
### Bug description

~~Changing the latency compensation setting in Device Preferences has no effect.~~
**Update:** Changing the latency compensation setting in Device Preferences has no effect until Audacity is restarted.

### Steps to reproduce

Run the "[Latency Test](https://manual.audacityteam.org/man/latency_test.html)" with different "Latency Compensation" settings.

### Expected behavior

Increasing the Latency Compensation (less negative) should result in the second track further to the right.
Decreasing the Latency Compensation (more negative) should result in the second track further to the left.

### Actual behavior

The Latency Compensation setting has no effect.

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

This is a serious regression as it makes it impossible to record overdubs that are synchronised to the original track.

**Comment by SteveDaulton** [comment]
Further testing seems to indicate that the setting does work, but does not take effect until Audacity has been restarted.
Changes to the latency compensation need to take effect immediately for "[Latency Test](https://manual.audacityteam.org/man/latency_test.html)".

**Comment by DavidBailes** [comment]
Tested this on Windows 10.
After opening Audacity, the first time I change the latency correction it has an immediate effect on subsequent recordings. If I change it again, it has no effect.

**Comment by Paul-Licameli** [comment]
It bisects to 712e72ab43b16ee21d101e424c04a623477c1d06

On me then.  Sigh.

**Comment by Paul-Licameli** [comment]
Thank you @SteveDaulton for vigilance
