### ISSUE TITLE
Missing translations for some elements in Realtime Effects panel

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3400]
### Steps to reproduce

1. Change app language to non-English
2. Load audio, expand Realtime Effects panel
3. Check labels of Add Effect button and Watch Video link

### Expected behavior

The button and the link are translated into the language that is being selected

### Actual behavior

No translations for those elements:
<img width="338" alt="image" src="https://user-images.githubusercontent.com/70063970/185621315-c336a058-3771-4ffa-80c3-9244fbcb512d.png">

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

**Comment by LWinterberg** [comment]
this is expected right now, a call for translations is made at string freeze.
