### ISSUE TITLE
'Silent' crash when calling Kickstart 2 plugin from Realtime Effects panel

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3401]
### Steps to reproduce

0. Install Kickstart 2 plugin (all modules): https://www.kickstart-plugin.com/
1. Launch Audacity
2. Load some audio
3. Open Realtime Effects panel
4. Select **first** item in the Kickstart 2 list
5. Hit **Play** button
6. Observe
<img width="400" alt="image" src="https://user-images.githubusercontent.com/70063970/185624358-06748db0-985f-401a-b277-3865df3eeac8.png">

### Expected behavior

Playback starts

### Actual behavior

'Silent' crash; no Sentry log available

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

**Comment by Paul-Licameli** [comment]
On my macOS build, I can observe with the debugger that the first item tries to load the AudioUnit effect, the other, VST.  But with either I get the crash as soon as I release the menu button.  No chance even to hit Play.

**Comment by Paul-Licameli** [comment]
It could be this plug-in, or at least in the free versions, is buggy and should be disabled.  But then the plug-in loader process should filter it out.

**Comment by Paul-Licameli** [comment]
What looks like a crash is not really a crash but an orderly call to `exit` -- however, with no courtesy explaining what is happening to the user.  The foreign plug-in code takes down our host process.

Our startup plug-in validation is supposed to let a different process suffer this exit so the main one does not.  The secondary process, in this case, doesn't take the loading and running of the foreign code far enough to detect this problem.

**Comment by Paul-Licameli** [comment]
```
      case audioMasterVersion:
         return (intptr_t) 2400;
```

Those lines of `VSTEffect.cpp` are visited by the foreign code of the VST version calling-back to us, before it exits.  Some clue maybe about a miniumum version it might need to work with.  Still no other hint given by the plug-in, why it doesn't like our host program.  No hint I can find in the AU case.

**Comment by DavidBailes** [comment]
> It could be this plug-in, or at least in the free versions, is buggy and should be disabled. But then the plug-in loader process should filter it out.

On Windows 10, this plugin does not cause Reaper to crash.

**Comment by Paul-Licameli** [comment]
> > It could be this plug-in, or at least in the free versions, is buggy and should be disabled. But then the plug-in loader process should filter it out.
> 
> On Windows 10, this plugin does not cause Reaper to crash.

I think the plug-in is trying to detect a certain minimum version of SDK support and shutting down the program when it does not find it.  It's not crashing:  it's exiting, but with no explanation.  Which is a rude thing to do when it might instead return error codes to the host program.

**Comment by crsib** [comment]
For vst3 we have the very fresh one, so I doubt that the reason is in the version

**Comment by crsib** [comment]
I have checked with VST supplied test host and it works well too.

**Comment by vsverchinsky** [comment]
@Paul-Licameli 
Well, this particular plugin does not like debuggers
@dozzzzer 
So the question then do you run it from XCode?

**Comment by dozzzzer** [comment]
@vsverchinsky No I don't

**Comment by dozzzzer** [comment]
can't reproduce anymore
