### ISSUE TITLE
Factory presets not properly populated in hamburger menu for VST3

### ISSUE THREAD

**Issue by Ryan-Miller-Audacity** [audacity/audacity#3414]
### Bug description

For VST3 versions of plugins, the available factory presets are not being properly populated in the hamburger menu. This does work correctly for AUs. 

For Example Auburn Sounds Couture plugin (https://www.auburnsounds.com/products/Couture.html): 

Audiounit module: 
<img width="641" alt="Screen Shot 2022-08-23 at 7 55 10 AM" src="https://user-images.githubusercontent.com/88568755/186152601-3b595a9e-597e-4ade-a776-cfe6568b0930.png">

VST3 module: 
<img width="797" alt="Screen Shot 2022-08-23 at 7 55 36 AM" src="https://user-images.githubusercontent.com/88568755/186152643-ad7be580-9aec-4bfa-8651-893aed3b6930.png">

Note: Due to #3292, you may need to disable Audiounit family in the preferences to properly instantiate the VST3 version of the plugin.

### Steps to reproduce

1. Open Audacity and grab/generate some sound
2. Select the Audiounit version of a plugin that has both a VST3 and Audiounit version and includes factory presets outside the plugin interface (Valhalla Supermassive etc. include presets within their interface)
3. Select the hamburger menu and observe the full list of available factory presets.
4. Select the VST3 Version (you may need to disable Audiounits from the effects page within preferences) of the plugin used previously
5. Select the hamburger menu and observe that there are no options (other than default) listed under the factory presets menu.

### Expected behavior

Factory presets should be properly loaded within the hamburger menu for VST3 plugins.

### Actual behavior

Factory presets are not being properly loaded within the hamburger menu for VST3 plugins.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

**Comment by Ryan-Miller-Audacity** [comment]
FYI @Paul-Licameli @vsverchinsky

**Comment by Ryan-Miller-Audacity** [comment]
Listing as a P2 as a lot of people (myself included) turn to these factory presets to make using some more complicated plugins less of a headache and this would be a great inconvenience to the end user.

**Comment by vsverchinsky** [comment]
It may be that factory presets in VST3 isn't same thing as in AU. For this specific plugin I didn't find any presets to be installed under any of expected presets locations (https://steinbergmedia.github.io/vst3_dev_portal/pages/Technical+Documentation/Locations+Format/Preset+Locations.html)
But not all of these folders are scanned and if there were presets stored in user folder Audacity still wouldn't have found them.

**Comment by LWinterberg** [comment]
lowering priority- most VST effects have some preset button in their UI and don't rely on our preset system

![image](https://user-images.githubusercontent.com/87814144/187925868-100c84fd-3918-42ba-97d2-dbae4adf1972.png)
![image](https://user-images.githubusercontent.com/87814144/187925934-eea329e5-95cb-41f0-a5c3-40bc3957d961.png)

**Comment by DavidBailes** [comment]
> lowering priority- most VST effects have some preset button in their UI and don't rely on our preset system

But the presets available in the effect's ui are not accessible for keyboard users - they obviously would be if they were available on the factory presets sub menu of the Settings & presets menu. I think that at least from a keyboard users perspective, this should be a P2 rather than a P3.

Using Reaper, the presets are available for keyboard users.

**Comment by DavidBailes** [comment]
> For this specific plugin I didn't find any presets to be installed under any of expected presets locations

Maybe many vst3 plugins use program lists for their factory presets:
https://steinbergmedia.github.io/vst3_dev_portal/pages/Technical+Documentation/Presets+Program+Lists/Index.html

**Comment by vsverchinsky** [comment]
> > For this specific plugin I didn't find any presets to be installed under any of expected presets locations
> 
> Maybe many vst3 plugins use program lists for their factory presets: https://steinbergmedia.github.io/vst3_dev_portal/pages/Technical+Documentation/Presets+Program+Lists/Index.html

True, the one mentioned in the issue does use program lists as a source of factory presets

**Comment by chinakov** [comment]
Issue is fixed, thanks!
