### ISSUE TITLE
Generators have no progress indicators

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#3418]
### Steps to reproduce

1. Generate 10 hours of white noise
2. Wait...

### Expected behavior

A progress dialog to let you interrupt the wait

### Actual behavior

No progress indication, just the cursor type changing to "Busy"

### Audacity Version

current master / alpha / nightly build

### Operating system

Other

**Comment by petersampsonaudacity** [comment]
For me on W1o with latestr alpha master

 it's worse than just "#'just the cursor type changing to "Busy""'

I see no response and when I click in the window I see this - and the spinning blue circle-of-death
![image](https://user-images.githubusercontent.com/50205984/186656011-bdf0430c-809f-4f02-afbd-68e822c2c6ed.png)


And folllowing the steps to reproduce with a 10 hour mono Noise to be generated I sit there with an apparently unresponsive Audacity for 95 seconds or so before the 10 hour Noise finally appears

**Comment by petersampsonaudacity** [comment]
@crsib @dozzzzer @LWinterberg 

Testing on W10 with latest 3.2.0 alpha  -  audacity-win-3.2.0-alpha-20220902+7c9c978-x64-msvc2022
And on macOS 12.5.1 with audacity-macOS-3.2.0-alpha-20220902+7c9c978-x86_64 

This appears to be working properly now on both W10 and macOS.

I think this could accordingly be closed
