### ISSUE TITLE
Cannot navigate by keyboard to the pinned play-head button on the timeline

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#3419]
### Steps to reproduce

Problem began at commit 5835ae5d87f195ce0e2e8b985586b2ed45c4e1ca

I noticed this while reviewing #3229 

### Audacity Version

current master / alpha / nightly build

### Operating system

all

**Comment by dozzzzer** [comment]
The issue doesn't seem to be the case anymore, pinned playhead can now be accessed by keyboard and moved with the left/right keyboard arrows.
