### ISSUE TITLE
macOS: Built-in Reverb plugin appears listed under Audio Unit subcategory in the Effect menu

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3421]
### Bug description

Built-in Reverb plugin appears listed under Audio Unit subcategory in the Effect menu

### Steps to reproduce

1. launch Audacity
2. navigate to Effect > Audio Unit
3. find "Reverb" effect on that list and bring it up

### Expected behavior

No built-in Reverb effect on that list of Audio Unit modules

### Actual behavior

It's a built-in Reverb effect:

https://user-images.githubusercontent.com/70063970/186369852-f247a182-de25-41ae-8de9-2b0a93db1f31.mp4

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

### Additional context

Purge of pluginregistry.cfg didn't help

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest alpha master  -  audacity-win-3.2.0-alpha-20220825+3bc3c94-x64-msvc2022

Not an issue on Windows

**Comment by petersampsonaudacity** [comment]
@dozzzzer 

Testing on macOS 10.15 Monterey with latest alpha master - 
audacity-macOS-3.2.0-alpha-20220825+b2c54cb-x86_64 

This now seems to be OK on Mac.
a) **Reverb** is listed in the **Delay and Reverb** section (of Audacity supplied effects
b) the only reverb type effect in the **Apple** category is **AUReverb2...**

**Comment by dozzzzer** [comment]
@petersampsonaudacity 
This issue still occurs to me.

<img width="400" alt="image" src="https://user-images.githubusercontent.com/70063970/186687991-38e8abb4-f090-4a66-8625-d0df2e3bb918.png">

 I'm pretty sure it's of the same nature as this issue: #3423 
Audacity gets confused over multiple plugins (including built-ins) with the same name.

Thus, this ticket can be closed as a duplicate.
