### ISSUE TITLE
Realtime Effects: (VST3) when loading factory defaults and playing the track, the plugin loads the last saved user preset

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3431]
### Steps to reproduce

1. Load some audio
2. In the Realtime Effects panel select a plugin (VST3) and open its settings
3. Make some changes to the effect's parameters and save it as a user preset
4. Load the effect's defaults
5. Start playback
6. Observe

### Expected behavior

The effect's parameters remain the way they were set just before the playback started = factory defaults.

### Actual behavior

The effect's parameters revert to their previous state, i.e. after the user preset was saved.

https://user-images.githubusercontent.com/70063970/186736054-e2a590c2-d55c-47c8-98e4-e3f4ce47acef.mp4

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS

### Additional context

Built-ins/LADSPA/VST aren't affected by this issue.

**Comment by Paul-Licameli** [comment]
@dozzzzer AudioUnits?

**Comment by dozzzzer** [comment]
@Paul-Licameli ...and VST3s

**Comment by Paul-Licameli** [comment]
Likely there will be separate fixes for VST3 and AU, therefore I duplicatd this issue at https://github.com/audacity/audacity/issues/3441

**Comment by AnitaBats** [comment]
@dozzzzer please re-test against mentioned PR, should not be reproducible any longer

**Comment by dozzzzer** [comment]
Verified on MacOS & Windows. Indeed all good now, closing the ticket.

**Comment by vsverchinsky** [comment]
PR isn't merged yet

**Comment by Ryan-Miller-Audacity** [comment]
This will be briefly tested in Alpha now that it has been merged as well. Unassigning @dozzzzer and assigning myself with the other merged tickets of #3475.
