### ISSUE TITLE
Applying mono VST3 to a stereo track corrupts the sound

### ISSUE THREAD

**Issue by crsib** [audacity/audacity#3434]
### Bug description

![image](https://user-images.githubusercontent.com/2660628/186774379-dbbf681f-35fb-4447-962b-7f9e423ffb0e.png)

### Steps to reproduce

1. Have a stereo track somehow
2. Add Berzerk Distortion Mono (other mono effects are affected as well it seems)
3. Press play
4. Observe that right channel clips violently

### Expected behavior

Mono effects can be applied to stereo tracks without issues

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

**Comment by Paul-Licameli** [comment]
@Ryan-Miller-Audacity this might be an example of the kind of bug I was asking you to discover

**Comment by Paul-Licameli** [comment]
Blue Cat Chorus, mono version, has similar problems and is easier to obtain for free without jumping through hoops.

I tried it and just got silence in the right channel which isn't good either.
