### ISSUE TITLE
[VST3] Blue Cat's Chorus (Stereo) crashed during the destructive application

### ISSUE THREAD

**Issue by crsib** [audacity/audacity#3437]
### Bug description

Looks like the effect is not ready to have 0 inputs

Exception thrown at 0x00007FFDBF317019 (BC Chorus 4 VST3(Stereo).vst3) in Audacity.exe: 0xC0000005: Access violation reading location 0x0000000000000030.

```
 	BC Chorus 4 VST3(Stereo).vst3!00007ffdbf317019()	Unknown
 	BC Chorus 4 VST3(Stereo).vst3!00007ffdbf32c7f2()	Unknown
 	BC Chorus 4 VST3(Stereo).vst3!00007ffdbf2dbc1a()	Unknown
 	BC Chorus 4 VST3(Stereo).vst3!00007ffdbf5ebacf()	Unknown
>	Audacity.exe!VST3Wrapper::Process(const float * const * inBlock, float * const * outBlock, unsigned __int64 blockLen) Line 553	C++
 	Audacity.exe!VST3Wrapper::FlushSettings(EffectSettings & settings) Line 466	C++
 	Audacity.exe!VST3UIValidator::ValidateUI::__l2::<lambda>(EffectSettings & settings) Line 147	C++
 	Audacity.exe!EffectSettingsAccess::ModifySettings<`VST3UIValidator::ValidateUI'::`2'::std::shared_ptr<TrackView> <lambda>(Track &)>(VST3UIValidator::ValidateUI::__l2::std::shared_ptr<TrackView> <lambda>(Track &) && function) Line 152	C++
 	Audacity.exe!VST3UIValidator::ValidateUI() Line 150	C++
 	Audacity.exe!EffectUIHost::TransferDataFromWindow() Line 276	C++
 	Audacity.exe!EffectUIHost::OnApply(wxCommandEvent & evt) Line 552	C++

```

### Steps to reproduce

1. Have a stereo track
2. Open Blue Cat's Chorus (stereo) from the Effects menu
3. Press Apply

### Expected behavior

Audacity does not crash

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

### Additional context

Other effects (from the different families) work fine, but who knows how large the scope of the problem is.

**Comment by Paul-Licameli** [comment]
Which plug-in protocol?

**Comment by crsib** [comment]
VST3, will change the title

**Comment by Paul-Licameli** [comment]
I observe it works in the AudioUnits version, but also notice that the Mono effect quietly fails when you try to apply it.
