### ISSUE TITLE
Crashes on Play of mono tracks with effects

### ISSUE THREAD

**Issue by crsib** [audacity/audacity#3443]
### Steps to reproduce

1. Generate Chirp
2. Add Dragonfly Early Reflection
3. Press Play

### Expected behavior

Audacity does not crash

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

**Comment by Paul-Licameli** [comment]
Not, as originally reported, specific to LV2;  but it does happen only with mono tracks.

**Comment by Paul-Licameli** [comment]
I'm redoing the fix, as part of fixing play of mono VST3 effects, and ask to re-verify this issue.
