### ISSUE TITLE
Auto-save does not recover effect settings changes

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#3447]
### Steps to reproduce

1. Make a track with an effect in its stack
2. Open the dialog, make changes, close the dialog
3. Force-quit Audacity
4. Restart and recover the project
5. Open the dialog again

### Expected behavior

See settings as you last left them.  But instead, settings remain as they were when the dialog first opened.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

### Additional context

I would not promise a fix in case the crash or force-quit happens while the dialog is open.

To fix the sequence as described, I thinkn a call to AutoSave when the dialog closes will be enough.

**Comment by Paul-Licameli** [comment]
@crsib

**Comment by crsib** [comment]
I am aware of this bug, it is not a blocker for alpha I think.

**Comment by Paul-Licameli** [comment]
Is there a duplicate card for it already?

**Comment by dozzzzer** [comment]
@vsverchinsky reopened: the fix doesn't seem to work for VST3s on macOS. All good with AUs though.

**Comment by dozzzzer** [comment]
Verified on macOS and Windows

**Comment by dozzzzer** [comment]
Reopened: the issue still occurs (macOS, build: https://github.com/audacity/audacity/actions/runs/3104289656)

**Comment by dozzzzer** [comment]
@Paul-Licameli LV2 effect's parameters aren't saved when re-starting Audacity after force quit.

OS: macOS
Plugin: https://x42-plugins.com/x42/mac/x42-compressor-v0.6.2.pkg
