### ISSUE TITLE
Persistency of AU effect settings in sidebar is broken again

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#3448]
### Bug description

It worked at commit 6f6501c7c28c0a5f72149ed0f89274ad45adfbd7 but has regressed since then, and the problem bisects to commit 32a863b142738b5acd1e98f786ad7d3190cd2341

### Steps to reproduce

1. Generate noise, open sidebar
2. Add an AU effect, for instance AUGraphicEQ
3. Change some settings, for instance drag 1K slider to the top
4. Close and reopen dialog, observe that in-session memory of settings is OK

Then do either (but not both) of these:

- Play -- hear WRONG results; then Stop, play again -- hear RIGHT results

or

- Save new project, close, reopen, reopen sidebar, reopen effect settings; see WRONG settings

### Expected behavior

Hear the right thing, or see the same settings as you saved

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

### Additional context

This does NOT happen for LV2 effects, so it's not general across effect families.

VST3 persistency might have bugs too, which I did not check, considering other problems with basic stickiness of settings after closing the dialog.

The bisection is rather surprising.  The commit that broke AU persistency touches no code special to AU.

**Comment by Paul-Licameli** [comment]
The button formerly called "OK" became "Apply" at commit 32a863b142738b5acd1e98f786ad7d3190cd2341 and changes behavior:  it applies the effect destructively whereas OK did not do that at the previous commit.

If you Apply and then Undo at commit 32a863b142738b5acd1e98f786ad7d3190cd2341, then save -- it "works."  But the "Close" button does not persist the effect.

**Comment by crsib** [comment]
The commit you've mentioned was written for the case when none of the buttons are present. The was the whole idea behind the PR to be fair. The omission of full scale AU testing is unfortunate, but Mac is not my main platform, so I haven't put enough testing time in it, while still checking the basics to work.
