### ISSUE TITLE
Mono effect on a Stereo track renders incorrectly

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#3456]
### Bug description

See also #3434 for the playback problem.  The fix for that is not sufficient for this too.

### Steps to reproduce

1. Make some stereo sound
2. Put, for instance, Blue Cat Chorus, VST3 mono version, on the stack
3. Mix-and-render to new track; or, export, then re-import
4. See that the right channel is silent!

### Expected behavior

Each channel should render the effect, as if a separate mono track

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

**Comment by Paul-Licameli** [comment]
@Ryan-Miller-Audacity @dozzzzer 
I'm doing my own tests to be sure that after rebasing onto #3436, the Blue Cat Chorus VST3 versions work as expected.  I do these things:

- Make a chirp
- put the effect on it, play it, hear what I expect in both channels
- mix-and-render to new track; apply Invert; play all tracks and expect to hear silence
- Delete new track; duplicate first track; remove effect from stack; apply effect destructively with same changes; apply Invert; play all; expect silence

I did all that with the Mono effect on a mono track, and with the Stereo effect on a mono track.

So far so good, and surely no crashes.

I will now test the same with the Mono effect on a stereo track, and the Stereo on stereo.

**Comment by Paul-Licameli** [comment]
And all that just checked out for me in stereo too.
@crsib

**Comment by crsib** [comment]
Yep, works good for me now as well
