### ISSUE TITLE
Crash when adding Youlean Loudness Meter 2 during playback

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3462]
### Bug description

When initializing **Youlean Loudness Meter 2** plugin from the RT panel during playback, Audacity crashes.

### Steps to reproduce

0. Download[ Youlean Loudness Meter](https://youlean.co/youlean-loudness-meter/)
1. Launch Audactiy, load some audio
2. Hit Play
3. Try adding Youlean Loudness Meter (VST or VST3, it doesn't matter) from RT panel

### Expected behavior

No crash

### Actual behavior

Audacity crashes; no Sentry report generated

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

**Comment by dozzzzer** [comment]
Verified on macOS and Windows 10.

**Comment by Ryan-Miller-Audacity** [comment]
This was properly fixed for VST3; however, this crash is now reproducible with the VST version of Youlean Loudness Meter 2 in the RT stack. Crash is triggered either when adding the plugin during playback or attempting to start playback with the plugin in the stack.

**Comment by Paul-Licameli** [comment]
I observe no problem for the AudioUnit or VST3 implementations.  I have reproduced it for VST2 even with all the latest in our branch.

**Comment by Paul-Licameli** [comment]
I observe in the debugger that the AudioUnit and VST3 versions report 2 channels in and 2 out, but the VST2 reports 10 in, 10 out and crashes in the function `VSTEffectInstance::RealtimeProcess`

**Comment by Ryan-Miller-Audacity** [comment]
In preliminary testing, this appears to be fixed (verified on Windows)  in [Build Audacity #2820](https://github.com/audacity/audacity/actions/runs/3336628616). VST version of Youlean Loudness Meter can be opened and properly meters output.
