### ISSUE TITLE
The sidebar can be dragged too far to the right, making it impossible to drag it back (and crashes debug builds)

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#3466]
### Steps to reproduce

1. open the sidepanel
2. drag it to the right

### Expected behavior

The sidepanel should have a maximum width, together with its current minimum width. 

Specifically, the maximum width should be 2/3 the window size. If the maximum width is smaller than the minimum width , the maximum width may be ignored until the window is made wider again.

### Actual behavior

Audacity crashes with the following debug message when self-compiled: 

![image](https://user-images.githubusercontent.com/87814144/187143488-a44a52ac-2722-41ae-ba9f-c91d4049fad6.png)

https://user-images.githubusercontent.com/87814144/187142843-d3727732-328a-4a6e-a7d1-bb825ae017e9.mp4

when using something that fell out of CI, it can be dragged all the way, at which point it cannot be back because the window resize kicks in instead. 

https://user-images.githubusercontent.com/87814144/187200140-365ea80a-c0f8-4bb6-b74f-7abb635f9456.mp4

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

### Additional context

testing as of commit 32a6779

**Comment by petersampsonaudacity** [comment]
This is a duplicate of:
 With 3.2.0 the track area can be dragged totally off screen #2620

**Comment by LWinterberg** [comment]
I knew I saw this filed somewhere!

**Comment by Paul-Licameli** [comment]
> I knew I saw this filed somewhere!

Please copy the detail about the debug assertion to the originsl
