### ISSUE TITLE
Unwanted beep when either the add or replace effect button is pressed using the keyboard.

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#3484]
### Bug description

In the realtime effects panel, there's an unwanted beep when either the add or replace effect button is pressed using the keyboard.

### Steps to reproduce

1. Open the realtime effects panel.
2.  Tab to the add effect button, or the replace effect button for an effect which has already been added.
3.  Press Enter to press the button.

### Expected behavior

A menu opens, without any beeps.

### Actual behavior

There is a beep sound indicating some issue with associated command, but the menu opens.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

### Additional context

Could be (very) annoying.

**Comment by dozzzzer** [comment]
I was able to reproduce it on Windows 11, it plays the system "Asterisk" sound when I press enter having the "Add Effect" button in focus.

**Comment by dozzzzer** [comment]
Verified
