### ISSUE TITLE
Crash when hitting Apply during preview of a destructive effect (LV2/VST3)

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3485]
### Steps to reproduce

1. Install an LV2/VST3 plugin (should be realtime-capable)
2. Load some audio
3. Go to Effect menu > select that effect
4. Click **Preview**
5. Click **Apply**

### Expected behavior

There's a popup with the progress bar displayed preventing the user from clicking outside. Thus, clicking Apply during preview isn't possible at all.

### Actual behavior

Crash: https://sentry.audacityteam.org/share/issue/04cf9671c1ed4368ba96f71ae7faabc4/

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

**Comment by Ryan-Miller-Audacity** [comment]
Tested on both Windows and MAC with VST3, AU, LV2 plugin families and there is no longer a crash when destructively applying an effect during preview playback.
