### ISSUE TITLE
Update the video "thumbnail"

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#3488]
- [x] Make a thumbnail (design team)
- [x] Update the thumbnail in Audacity
- [x] update the link to https://audacityteam.org/3.2.0-video

**Comment by Tantacrul** [comment]
Here's the link to the video:
https://youtu.be/DTRnDNR9LR8

Here's the thumb: https://www.dropbox.com/s/3ezilf1iav4mlkw/3.2_Thumb_V02_Small_In_Audacity.jpg?dl=0

**Comment by LWinterberg** [comment]
the in-app links https://audacityteam.org/3.2.0-video and https://audacityteam.org/realtime-video are already correct
