### ISSUE TITLE
Some links don't open on certain distros

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#3494]
### Bug description

Specifically, in the realtime effects sidebar, the "watch video" and "get more plugins" links don't work on @SteveDaulton's Xubuntu 20.04. 

### Steps to reproduce

1. click an affected link

### Expected behavior

the correct link opens

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

works on my system (Ubuntu 22.04)

**Comment by SteveDaulton** [comment]
> Specifically, in the realtime effects sidebar, the "watch video" and "get more plugins" links don't work on @SteveDaulton's Xubuntu 20.04.

This issue is (for me) specific to the AppImage.

With self-built Audacity 3.2.0 alpha,
* "watch video" opens my web browser at https://www.audacityteam.org/
* "get more plugins" opens my web browser at https://plugins.audacityteam.org/

**Comment by Ryan-Miller-Audacity** [comment]
Confirmed working and fixed in my Linux VM with the Appimage version of the most recent beta branch. @SteveDaulton is this fixed for you as well?

**Comment by SteveDaulton** [comment]
> the Appimage version of the most recent beta branch.

Which branch? https://github.com/audacity/audacity/branches

**Comment by Ryan-Miller-Audacity** [comment]
I tested against this build: https://github.com/audacity/audacity/actions/runs/3081056287

**Comment by SteveDaulton** [comment]
Thanks. Yes, the links work with that version, though somewhat unusually they open in a new browser window, even if my browser (Firefox) is already open. Other apps that open web links do so in a new tab, not a new window.
