### ISSUE TITLE
;controls in Nyquist Prompt fail

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#3500]
### Bug description

Audacity 3.2.0-alpha AppImage.

When a ";control" widget is used in the Nyquist Prompt, it always returns the default value rather than the selected value.

### Steps to reproduce

1. Make a selection, then open the Nyquist Prompt effect.
2. Enter this code into the Nyquist Prompt text window:
```
;control first "First" int "" 5 0 10
;control second "Second" float "" 5 0 10
;control third "Third" string "" "default"

(format nil "First: ~a~%Second: ~a~%Third: ~a" first second third)
```
3. Click the "Apply" button
4. Change the settings in the Nyquist Worker window.

### Expected behavior

The settings made in step 4 should be displayed.

### Actual behavior

The default values are displayed:
```
First: 5
Second: 5
Third: default
```

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

Regression against 3.1.3

**Comment by LWinterberg** [comment]
I can reproduce this in Windows 11
![image](https://user-images.githubusercontent.com/87814144/187905323-5409e9ed-2d38-4b82-b44f-c3167ba1d9ed.png)
![image](https://user-images.githubusercontent.com/87814144/187905350-a6c4f883-390e-4c71-899c-60dd580fa40e.png)

**Comment by SteveDaulton** [comment]
This bug was introduced here: https://github.com/audacity/audacity/commit/938d72c9ed132efc837960d75d5c713bc3ee7182

**Comment by Ryan-Miller-Audacity** [comment]
This has been tested and verified fixed in beta release.
