### ISSUE TITLE
File browsers are in German on mac Universal build

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#3503]
The latest [Audacity 3.2.0 Alpha 1](https://github.com/audacity/audacity/releases/tag/Audacity-3.2.0-alpha-1) posted to the releases page has the bug again where dialog box (like for open) are in german again

![Screen Shot 2022-08-31 at 11 25 22 PM](https://user-images.githubusercontent.com/2224292/187826140-632601c4-4cb8-46fd-a1d2-f82b3201b8e1.jpg)

_Originally posted by @david-macrae in https://github.com/audacity/audacity/issues/2493#issuecomment-1233694859_

**Comment by petersampsonaudacity** [comment]
Testing on macOS 12.5.1

This only affects the **Universal** build

Works properly in English for:
audacity-macOS-3.2.0-alpha-20220831+4e5525a-x86_64

**Comment by codeman38** [comment]
Oddly, it's not even consistent what wrong language shows up - for me, they show up in Russian:
<img width="799" alt="Screenshot showing file browser with folder names in Russian" src="https://user-images.githubusercontent.com/386563/188317632-959423cb-60aa-4f20-a9f5-0cc812081f8d.png">

**Comment by crsib** [comment]
Likely we will have to release x86 and arm versions separately for now
