### ISSUE TITLE
Update UI for "Audio Setup" and "Share Audio" buttons

### ISSUE THREAD

**Issue by crsib** [audacity/audacity#3516]
Desired visuals:

![Image](https://user-images.githubusercontent.com/2660628/188099254-6d9690c5-7a50-4cea-bcfb-ec9cfcc213af.png)

**Comment by dozzzzer** [comment]
Reopened: Audio Setup is OK, but the Share Audio button shouldn't have the arrow down, since it doesn't implicate a dropdown list to be shown.

![image](https://user-images.githubusercontent.com/70063970/188641226-4edc7bc0-97b6-4592-bf08-c812ff222f1e.png)

**Comment by vsverchinsky** [comment]
Fixed by https://github.com/audacity/audacity/pull/3550
