### ISSUE TITLE
Mixing a stereo track down to mono results in the amplitude being reduced

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#3519]
### Bug description
Mixing a stereo track down to mono results in the amplitude being reduced.
In contrast Mixing the track to stereo does **_NOT_** change the amplitude.

### Steps to reproduce
1. Get some stereo audio
2. Amplify it to 0dB
3. Amply again just to test that it now peaks at 0dB - see image 1
4. Tracks > Mix > Mix stereo down to Mono
5. Effect > Amplify
6. Observe the mixed mono track does not peak at 0Db  - see image 2
7. Observe:  the amplitude is reduced, visibly so, on the waveform

### Expected behavior
Unchanged amplitude on mixdown from steero to mono

### Actual behavior
The mixed mono track does not peak at 0Db - the amplitude is reduced (and visibly so too on the waveform)

### 1) Before the Mix down to mono
![image](https://user-images.githubusercontent.com/50205984/188111480-3dbf4fbf-960a-4930-8d50-a6087e293a74.png)

### 2) After the mix down to mono
![image](https://user-images.githubusercontent.com/50205984/188111722-75b3bb11-276b-45e5-97e7-5abedaf2b03c.png)

### Audacity Version
current master / alpha / nightly build

### Operating system
Windows - but suspect all OS

### Additional context
None

**Comment by Paul-Licameli** [comment]
I'm not sure this is a bug or a regression.

If the content of the two channels is identical (as in toy examples, where you generate a tone) -- I would expect this behavior.

But with real-world stereo musical recordings, small phase differences between channels can make a slight destructive interference.

I'm skeptical too of the claim that it is a regression on 2.0.6.  Did you really try it in that version and the next one after, with identical input material?

**Comment by petersampsonaudacity** [comment]
> I'm skeptical too of the claim that it is a regression on 2.0.6. Did you really try it in that version and the next one after, with identical input material?

Re-testing today with the same material (track 1 from Sgt Pepper's Lonely Hearts Club band) shows your skepticism is indeed valid - and this is not a regression on 2.0.6

**1) 2.0.6 before the mixdown**
![image](https://user-images.githubusercontent.com/50205984/188266919-f6261fde-c23e-4c8d-89dc-cb56ff3bb236.png)

### 2) 2.0.6 after the mixdown
![image](https://user-images.githubusercontent.com/50205984/188266986-b084cd90-484f-408b-8e75-9bca2081cca2.png)

**Comment by petersampsonaudacity** [comment]
@Paul-Licameli  further testing shows that we have had this issue since 1.3.0 (Nov 2005 - seventeen years ago) when the **Project >Stereo to Mono**  command was first introduced.

**Comment by Paul-Licameli** [comment]
Then I think the issue should be closed.  As I explained, some loss of amplitude in mixing-down of real world stereo recordings is to be expected because of slight phase differences.  It's just the math.

**Comment by petersampsonaudacity** [comment]
> Then I think the issue should be closed.

And my "Mystery-Shopper" agrees with you ...     ;-)

And you can't argue with the math _(or the M-S come to that)_ and I speak as an (ex)mathematician
