### ISSUE TITLE
Generate or Apply button of modal destructive effect dialog should be Default

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#3521]
### Steps to reproduce

1. Open Effect or Generator from the main
2. Hit Return

### Expected behavior

Effect or generator applies.  Instead -- nothing.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

**Comment by Paul-Licameli** [comment]
Surely I'm duplicating issues... did @DavidBailes mention this already?

We fixed Esc, now do Return.

**Comment by dozzzzer** [comment]
Tested and verified fixed in latest alpha branch.
