### ISSUE TITLE
Pan and Gain dialogs should modify play in realtime; maybe be non-modal too

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#3523]
### Your idea

Pan and Gain dialogs, which open up when you double-click the slider thumbs in the track, should be more like the settings dialogs that can be opened from the sidebar.

### Problem to be solved

Double-click one of those thumbs, after starting a concurrent playback of the track.  They give a larger scale and more precise adjustment, and a text entry box for precise values.

Vary the setting while you listen.  Expect to hear the change applied at once, but instead, it doesn't until you OK the dialog.

Open the dialog first and then try to play -- beep!  Sorry, it's modal.

**Comment by LWinterberg** [comment]
These dialogs probably won't make it over to Qt. Rather, the track headers would be accessible, with the controls being able to be swapped out with text input when requested. Prior art for this would be Cakewalk, which lets you turn a slider or knob
![image](https://user-images.githubusercontent.com/87814144/203044292-696ac92b-a76f-4053-b04e-d6e6647b8693.png)
![image](https://user-images.githubusercontent.com/87814144/203044326-2cad1c8d-b7dd-43ad-8fa0-68508469e0e7.png)
into a text field upon pressing enter:
![image](https://user-images.githubusercontent.com/87814144/203044584-35c9229f-4811-46c6-9fa7-d6397d451e38.png)
![image](https://user-images.githubusercontent.com/87814144/203044534-814a1105-4310-46cd-9970-3b95a768ac59.png)
(it probably is possible to make these things not look as daft though. Alex suggested a tooltip-like thing which can be interacted with to type things in)
