### ISSUE TITLE
Add Rescan Audio Devices option to audio setup button

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#3524]
### Your idea

Add the "Rescan Audio Devices" function to the new Audio Setup Button either by default or by adding a selection to do the rescan.

### Problem to be solved

When users connect their USB or Bluetooth device Audacity recognize it until after they restart Audacity.  They can't seem to locate (or are not aware of) the Transport > Rescan Audio Devices service.

**Comment by petersampsonaudacity** [comment]
@LWinterberg @ksoze95 @Tantacrul 

This seems like a very good idea to me.

**Comment by Tantacrul** [comment]
Yes. For sure.

We should also have a conversation about whether we can do this automatically - and if so, how long we think it might take. The ideal would be that you never need to rescan or restart ever.

We'll keep this open and highly prioritised in order to keep track of it. Thanks!

**Comment by petersampsonaudacity** [comment]
I like the idea that this may be done automagically.

If we do create an entry in the Audio Setup dropdown menu, I'm hoping that at the same time it gets removed from the Transport menu - thereby avoiding duplication.

**Comment by LWinterberg** [comment]
could this rescan be made whenever the user clicks on the "Audio setup" button? How long does this scan take anyway?

**Comment by crsib** [comment]
I'm pretty sure that it takes quite a time, especially on Linux or when ASIO is enabled

**Comment by LWinterberg** [comment]
disregard then and proceed with the initial suggestion :)

**Comment by dozzzzer** [comment]
Tested

**Comment by JohnColket** [comment]
:smile:

**Comment by petersampsonaudacity** [comment]
I have updated the manual today for this change
