### ISSUE TITLE
Noise reduction effect can crash Audacity

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#3525]
### Bug description
Noise reduction effect can crash Audacity when there is no noise profile captured and the "OK" button (which is the initial focus) is pressed.

### Steps to reproduce

1. Open Audacity
2.  Create/get some audio
3.  Select some audio
4.  Open the Noise reduction effect
5.  The OK button is the initial focus. Press it.

### Expected behavior

In step 5 the "Get Noise profile" button should be the initial focus, and the OK button should not be available, since a noise profile has not yet been got.

### Actual behavior

Crash.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

### Additional context

Regression on 3.1.3

**Comment by LWinterberg** [comment]
I can reproduce this on Win 11, both in alpha1 and 7c9c97803949a9a8bc8138032d89725b155f3c50

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest 3.2.0 alpha 

This remains an issue on the latest alpha for 3.2.0 on W10 too and on macOS 12.5,1

It crashed with phone-home error messages on both platforms which I sent on.

**Comment by petersampsonaudacity** [comment]
Testing on @Paul-Licameli 's branch build
Fix state of Apply in noise reduction so you can't crash it... Build Audacity #2408

This appears to work properly now - the "OK" button is grayed-out and inaccessible unless and until a noise profile is obtained - therefater pressing OK causes the effect to work and not crash.

-------------------------------------------------------

Aside: @ksoze95  @LWinterberg @Tantacrul @crsib 

a) shouldn't the "OK" button be an "Apply" button, shouldn't the "Cancel" and the "?" buttons be removed - all in line with the "effects beautification??  

a)And why is the Preview button grayed-out and inaccessible

![image](https://user-images.githubusercontent.com/50205984/188322574-5d78f91c-c787-4ec0-998e-e21207e5bafc.png)

Should this/these be logged a speparate bugs ?

**Comment by Paul-Licameli** [comment]
Noise Reduction remains a peculiar effect because of its unique two-phase application, and doesn't share the dialog code with the rest of the effects.

Yes, this looks like an omission, my guess is that it's not of alpha priority.  The regression of Preview, however, might be more serious for this effect in which that is especially desirable when you try to find good parameters.

**Comment by petersampsonaudacity** [comment]
> a) And why is the Preview button grayed-out and inaccessible - this is a regression on 3.1.3

Logged as new issue:
**Noise Reduction Preview button remains grayed-out for Step 2** #3533

**Comment by LWinterberg** [comment]
looks fixed to me
