### ISSUE TITLE
Using the power button on the sidebar (turning it on/off) resets RT effects

### ISSUE THREAD

**Issue by Tantacrul** [audacity/audacity#3530]
### Bug description

Using the power button on the sidebar (turning it on/off) resets the effect UI. So far, I have only tested this with:

- [Voxtengo Voxperformer](https://www.voxengo.com/product/voxformer/) (VST3)
- All MuseFX (VST3)

I'll be testing more soon. The issue occurs with all of the above.

### Steps to reproduce

To reproduce:

1. Add an RT effect and make some changes
2. Close the effect window
3. Turn off and back on the 'power' button in the sidebar
4. Open back up the effect and observe the settings have reset in the UI

Notes:
- I've so far only tested VST 3 on Windows
- It doesn't affect the sound of the effect until you change a parameter

### Expected behavior

Enabling/disabling the power button does not affect the effect settings, ever.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

**Comment by Tantacrul** [comment]
I spotted this during a session where I was testing FX on my vocals while recording audio for a new video. Obviously, I kept using the power button to check whether a particular effect was helping or not.

This is a pretty significant behaviour I would expect from anyone trying to produce anything, so it gets a P2 easily. Could even be a P1.

**Comment by Paul-Licameli** [comment]
Can our guys get the source for MuseFX?
