### ISSUE TITLE
Noise Reduction Preview button remains grayed-out for Step 2

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#3533]
### Bug description

Noise Reduction Preview button remains grayed-out for Step 2 .

It is properly grayed out for Step 1, but once you have a noise profile captures the the next invoking of Noise Reduction the NR should be ready to apply and the Preview button should be available and not grayed-out.

This is a regression on 3.1.3

The Preview is important before applying the effect so I believe this warrants at least P2 rating

### Steps to reproduce

1. get some audio
2. select a portion for Noise Profile capture - Step 1 
3. Edit > Noise Reduction
4. Observe: Preview button is grayed-out and unavailable - _expected behavior_
5. Press OK to capture the Noise profile
6. Select the whole project
7. Edit > Noise Reduction
8. Observe: Preview button remains grayed-out and unavailable

### Expected behavior

The Preview should be available once Audacity has captured a Noise Profile.

_Remember that once a Noise Profile is captured Audacity retains that until you close Audacity._

### Actual behavior

**Step 1**
![image](https://user-images.githubusercontent.com/50205984/188412387-251cff55-3678-4518-a870-f5f42a2ec327.png)

**Step 2**
![image](https://user-images.githubusercontent.com/50205984/188412729-f2a67879-8be4-42dd-be58-5e51b6060f34.png)

### Audacity Version
current master / alpha / nightly build 
audacity-win-3.2.0-alpha-20220902+7c9c978-x64-msvc2022

### Operating system
Windows - but suspect all OS

### Additional context
See:   **Noise reduction effect can crash Audacity** #3525

**Comment by Paul-Licameli** [comment]
I think the fix for #3525 fixed this too.

You did not have that fix yet, if you were given the OK button in step 1 of noise reduction.  Unknown why you didn't get a crash when you pressed it then.

**Comment by LWinterberg** [comment]
looks fixed to me

**Comment by Ryan-Miller-Audacity** [comment]
Tested and verified fixed in latest Alpha branch.
