### ISSUE TITLE
Crash when starting playback with Waves IR360 plugin in the sidebar

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3538]
### Bug description

https://www.waves.com/plugins/ir360-convolution-reverb

### Steps to reproduce

1. Select Waves IR360 plugin in the sidebar
2. Hit Play
3. Observe

### Expected behavior

Crash: https://sentry.audacityteam.org/share/issue/55a8b205aaa141fcbbe23bc3da1d9c46/

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

**Comment by crsib** [comment]
Looks like it is the same bug as #3462

I think we can now assert (oh, irony!) that Audacity will crash on multichannel plugins, regardless of family.

**Comment by crsib** [comment]
Irony continued :-)

```
// This is unexpected.  Is a bad instance demanding 3 channels out?
```
