### ISSUE TITLE
No Visible Scrollbar in Plugin Manager

### ISSUE THREAD

**Issue by hellocatfood** [audacity/audacity#3543]
### Bug description

I'm using the Audacity-3.2.0-alpha-1 appimage on Ubuntu 22.04 using the Adwaita theme with a screen resolution of 3840x2400. When I go to Effect > Plugin Manager a long list of plugins appear but there is no visible scrollbar.

![Screenshot from 2022-09-05 17-33-05](https://user-images.githubusercontent.com/151947/188490436-fb415d17-e5fb-49c3-abca-436d752767c9.png)

However, I can scroll through the plugins by dragging the small area between the plugin list and the Plugin Manager Window

https://user-images.githubusercontent.com/151947/188493557-11ede2bd-61c2-47a4-96f9-75668e0edd51.mp4

### Steps to reproduce

1. Go to Effect > Plugin Manager
2. Try scrolling the window

### Expected behavior

Being able to scroll the window using a visible scrollbar

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

**Comment by LWinterberg** [comment]
Do you have scrollbars elsewhere? because - 

* #2937 
* #2222

**Comment by hellocatfood** [comment]
> (also, for completeness: cannot repro on windows)

Just tried on a clean Ubuntu 22.04 install via a VM and still getting no scrollbars

![Screenshot from 2022-09-06 11-25-41](https://user-images.githubusercontent.com/151947/188679313-14904166-a46a-4d14-9a1b-0d950af975b2.png)

Also yes no scrollbars elsewhere either

![Screenshot from 2022-09-06 11-29-52](https://user-images.githubusercontent.com/151947/188679389-88353509-8e9f-4655-81a3-a816f91a282a.png)

In the above screenshot both bits of audio extend past the visible area

**Comment by LWinterberg** [comment]
Fixed by #3571
