### ISSUE TITLE
Audio Sharing fixes

### ISSUE THREAD

**Issue by crsib** [audacity/audacity#3554]
- [x] "Remaining" displays inadequate time 
- [x] Wrong padding between "Cancel" and "Continue"
- [x] "Cancel" and "Continue" are clipped on macOS
- [x] "Go to my file" and "Close" should be swapped
- [x] "Copy" button is not shown on macOS
- [x] Avatar is not removed from Audacity when it is removed from the profile
- [x] Successful linking should show a dialog, expect when Share Dialog is opened
- [x] Temp location is not cleaned after the abnormal Audacity termination
- [x] "Are you sure" when cancelling an active upload
- [x] #3551

**Comment by dozzzzer** [comment]
Few more findings:

1. There's some padding missing between Cancel and Continue
2. There's shadow below the buttons missing
3. No dark grey background behind the user icon (see the image)
4. The copy is truncated (macOS only)

<img width="463" alt="image" src="https://user-images.githubusercontent.com/70063970/188727081-bfcf9993-7a55-4a07-9eb5-031c461766f9.png">
<img width="463" alt="image" src="https://user-images.githubusercontent.com/70063970/188727096-64e0a2fa-18c5-4af9-b95e-c48c9f44305c.png">

**Comment by crsib** [comment]
To solve "No dark grey background behind the user icon (see the image)" new assets are needed. I doubt that it is critical. 

I'm not sure that I understand number 2.

**Comment by LWinterberg** [comment]
2 is "the buttons have an outline and the lowest pixel is getting cut off". Like, the difference between this: 

![image](https://user-images.githubusercontent.com/87814144/188839996-d9fe0c20-0cfc-43f5-8be0-50a737ba65cc.png)

and this: 

![image](https://user-images.githubusercontent.com/87814144/188840114-d4952f6a-1442-4cbd-a70b-5e42e8d9ea37.png)

(I edited the second screenshot)

It's not critical anyway

**Comment by dozzzzer** [comment]
> the lowest pixel is getting cut off
+ specifically on Mac I believe I see there's some shadow dropping
