### ISSUE TITLE
Crash when clicking Stop button during playback

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3561]
### Steps to reproduce

1. download [the project](https://www.dropbox.com/s/yznnw7ciqb64bw5/share%20audio%20issue.aup3?dl=0) and download & install [Valhalla Supermassive](https://valhalladsp.com/shop/reverb/valhalla-supermassive/)
2. launch Audacity
3. File > Open > select the project from step 1
4. Click Play button
5. Click Stop button

### Expected behavior

Playback is stopped

### Actual behavior

Crash: https://sentry.audacityteam.org/share/issue/dbd4b42548504e5cb6e1173baef8bbb2/

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

### Additional context

Reproducible in 100% cases

**Comment by LWinterberg** [comment]
cannot reproduce on windows11

**Comment by crsib** [comment]
I'm quite sure that the issue is AU related, I will check soon

**Comment by crsib** [comment]
I observe crash in finalize: `mpAccessState` is never initialized and used without checking for `nullptr` in `RealtimeEffectState::Finalize()`.
