### ISSUE TITLE
[LADSPA] GVerb crashes Mix&Render when stacked on a stereo track

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3565]
### Plugin

GVerb

### Plugin Format

LADSPA

### Steps to reproduce

1. load some stereo track
2. in the sidebar select GVerb plugin
3. click Share Audio
4. Click Continue

### Expected behavior

Upload started

### Actual behavior

Crash: https://sentry.audacityteam.org/share/issue/cd2edceef5f94944ae9c99ce5f577bc5/

### Audacity Version

current master / alpha / nightly build

### Operating system

Any

----------------

It appears, that GVerb declares a single input and two outputs. This confuses Mix&Render..

**Comment by crsib** [comment]
I appears that stereo track is required

**Comment by crsib** [comment]
And it really affects Mix&Render/Export, not the sharing feature itself. Output format is irrelevant.

**Comment by Ryan-Miller-Audacity** [comment]
Tested and verified fixed in latest alpha branch.
