### ISSUE TITLE
Typo in Audio Sharing dialog

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3568]
### Bug description

Discovered while testing #3394 

### Steps to reproduce

1. Complete Audio upload as a logged in audio.com user
2. review the copy

### Expected behavior

"Shareable link"

### Actual behavior

<img width="502" alt="image" src="https://user-images.githubusercontent.com/70063970/188933622-3f4d8062-bc15-4000-8f8a-d6eee8716f43.png">

### Audacity Version

current master / alpha / nightly build

### Operating system

Other

**Comment by LWinterberg** [comment]
Apparently it's not wrong:

![image](https://user-images.githubusercontent.com/87814144/189099025-b1c84377-8b59-4385-8862-36f4c3173616.png)
![image](https://user-images.githubusercontent.com/87814144/189099348-1e2d9a2c-d6b4-4057-89d2-0b59bf581f2c.png)
![image](https://user-images.githubusercontent.com/87814144/189099418-cbc0adae-0a97-4c94-abde-c3f4c4e5ab25.png)

**Comment by petersampsonaudacity** [comment]
And also if you don't have an account yet:

![image](https://user-images.githubusercontent.com/50205984/189112154-39258bcc-d53a-488a-84f1-75a2e0cb203a.png)

**Comment by Tantacrul** [comment]
Thanks @dozzzzer !
