### ISSUE TITLE
Xfer OTT - No UI displaying.

### ISSUE THREAD

**Issue by Tantacrul** [audacity/audacity#3570]
### Plugin

Xfer OTT (free)

### Plugin Format

VST2

### Plugin source

https://xferrecords.com/freeware/

### Bug description

On MacOS, when installed as a VST2, the OTT plugin UI does not appear. A difference in sound can be heard. VST3 version looks and sounds fine.

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/21022311/188934775-f5dac182-5bfd-400c-a79f-9e29dc98fcd6.png">

Tested on Pietro's branch: https://github.com/audacity/audacity/actions/runs/3007755230

### Steps to reproduce

Install the VST2 version and test (no UI)
Uninstall VST2
Install VST3 (UI working fine)

### Expected behavior

.

### Audacity Version

other

### Operating system

macOS

### Architecture

64 bit Intel/AMD processors

**Comment by dozzzzer** [comment]
@pietro68 @Paul-Licameli 
The issue can still be observed in the most recent release branch build: 
https://github.com/audacity/audacity/actions/runs/3414816840

**Comment by dozzzzer** [comment]
Verified on macOS Ventura and Windows 11
