### ISSUE TITLE
Normalize and Loudness normalization effect dialogs: clipped content when opened.

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#3573]
### Steps to reproduce

Open the dialogs

### Expected behavior

Dialogs open without clipped content.

### Actual behavior

Immediately after opening:
![image](https://user-images.githubusercontent.com/11887021/189096769-25726446-02d8-45d5-8767-9082a639a36f.png)

After resizing:
![image](https://user-images.githubusercontent.com/11887021/189096878-27195107-b3ed-46e5-9a0d-4add70602285.png)

Immediately after opening:
![image](https://user-images.githubusercontent.com/11887021/189097129-5abee8db-9790-44f4-ba09-59894776da9b.png)

After resizing:
![image](https://user-images.githubusercontent.com/11887021/189097216-4b2fd5af-d8e4-4484-a7e2-5b44b6c82abb.png)

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

**Comment by petersampsonaudacity** [comment]
testing on W10 with latest 3.2.0 alpha - audacity-win-3.2.0-alpha-20220907+591f227-x64-msvc2022

I do _**NOT**_ see thsi behavior

### Normalize

**Comment by DavidBailes** [comment]
> testing on W10 with latest 3.2.0 alpha - audacity-win-3.2.0-alpha-20220907+591f227-x64-msvc2022
> 
> I do _**NOT**_ see thsi behavior

Neither do I, I'll close the bug.
