### ISSUE TITLE
The rescan button re-enables user-disabled plugins

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#3576]
Testing with the alpha-3.2.0 branch, the "Rescan" button does not only rescan for plug-ins, it also automatically enables every plug-in that it finds on my computer, thus re-enabling the hundreds of plug-ins that I've previously spent time disabling.

Not only that, but after pressing "Rescan", when I see that it wants to enable hundreds of plug-ins that I don't want enabled, it then fails to honour the "Cancel" button:
1. Ensure that you have some custom effects installed on your computer.
2. Launch Audacity
3. Disable all custom effects
4. Close and restart Audacity
5. Check and see that you have only the standard set of plug-ins.
6. Launch "Manage Plugins"
7. Click the "Rescan" button
8. (optional) Curse
9. Press the "Cancel" button
10. Observe that the custom effects are NOT listed in the menus
11. Quit Audacity and relaunch
12. Observe that the custom effects ARE now listed in the menus.

Now I have to go through the effects again and disable all of those that I disabled previously.
I seriously hope that this is a bug and not the intended behaviour.

_Originally posted by @SteveDaulton in https://github.com/audacity/audacity/issues/2967#issuecomment-1240726550_

----

Expected behavior:
* Plugins which exist on-disk but were not previously in the list get enabled.
  This should also apply to Nyquist effects.
* Plugins which are in the list but are disabled don't get touched
* Plugins which are in the list but no longer exist on-disk get removed

**Comment by vsverchinsky** [comment]
@LWinterberg could you please clarify what should happen if user decides to cancel plugin scanning?

**Comment by LWinterberg** [comment]
> Right now if I cancel it I would see only those that were found so far, and when I rerun Audacity it starts scanning from where it was canceled.

this sounds correct

> Also what about "Incompatible plugin(s)" dialog?

Good question, let me think

**Comment by SteveDaulton** [comment]
Regarding cancelling things, Paul previously did a lot of work on making cancel work the same way for nearly everything. Cancel stops the current operation and winds back to the previous state (so you are back to where you were before starting the thing that was cancelled). Imo this is what most users expect "Cancel" to do. Perhaps worth having a word PRL about this.

**Comment by LWinterberg** [comment]
> Cancel stops the current operation and winds back to the previous state (so you are back to where you were before starting the thing that was cancelled). Imo this is what most users expect "Cancel" to do.

For audio and preferences operations, this makes sense. It's not really useful here though: For plugin scanning, there exists a meaningful in-between state (plugins a-m scanned, tested and usable, n-z not yet), and the ultimate state has completed the scan.  Aborting and rolling back here would just cause unnecessary double- and triple-testing.

**Comment by SteveDaulton** [comment]
> Aborting and rolling back here would just cause unnecessary double- and triple-testing.
So what should happen if:
1. You install Audacity
2. Run Audacity, then Exit (initial scan of plug-ins)
3. Add and remove some plug-ins
4. Launch Audacity, start a scan, then cancel part way through
5. Quit and restart Audacity
6. Does the scan restart automatically on restart? If it does, cancel it.
7. Quit Audacity
8. Add and remove some plug-ins. This may include removal of plug-ins that  were scanned in step  4.
9. Restart Audacity and scan plug-ins. How does Audacity know if the scan that it started is still valid?

**Comment by petersampsonaudacity** [comment]
@ksoze95 @LWinterberg @SteveDaulton @crsib 

Testing on W10 with latest 3.2.0.alpha  -  audacity-win-3.2.0-alpha-20220909+e1332b1-x64-msvc2022

This now appears to work  properly with Disabled effects (EGATS) not being re-enabled by use of the rescan button.

I tested with:
a) shipped Nyquist EGATS
b) in-built Audacity EGATS

I did
