### ISSUE TITLE
AutoDuck effect can be opened in a single track project

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#3580]
### Bug description

The AutoDuck effect requires that the project contains at least two audio tracks, and that a non-selected track exists below the selected track(s). The correct behavior, as seen in previous versions of Audacity, is that when these conditions are not met, an error dialog is displayed and the effect does not open.

In the current 3.2.0-alpha, the error dialog is displayed,  but when that message is dismissed, the effect opens as if it can be applied.

### Steps to reproduce

1. Create a project with one audio track
2. Select the audio track
3. "Effect menu > AutoDuck"
4. Observe the error message:
`Auto Duck needs a control track which must be placed below the selected track(s).`
5. Click "OK"

### Expected behavior

The error dialog to close (nothing more, nothing less).

### Actual behavior

The error dialog closes, and the AutoDuck GUI opens

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

**Comment by Ryan-Miller-Audacity** [comment]
This was tested and verified in latest Beta branch. 

PR #3589
