### ISSUE TITLE
Share Audio toolbar has 3x height

### ISSUE THREAD

**Issue by crsib** [audacity/audacity#3585]
![Image](https://user-images.githubusercontent.com/2660628/189318673-f5925b4a-4d66-4863-9dd2-19d2f7c0a9f1.png)

**Comment by GargDivanshu** [comment]
Hey, I am interested to work on your issues. Can I  work on this issue? Also, if yes, you can let me know about some impt stuff which I should take care of (if there's any)

**Comment by crsib** [comment]
This issue is fixed and waits for QA to check on it.

**Comment by DavidBailes** [comment]
I've got this issue on Windows 10 with the beta version. If the display scaling is set to 100% there isn't a problem, but on 125% there is:
![image](https://user-images.githubusercontent.com/11887021/190216201-df4567b4-6750-420f-9c14-d5f0b6c8243a.png)

**Comment by crsib** [comment]
I have checked with 125% and 150% and I am unable to reproduce the problem. @Ryan-Miller-Audacity can you please check as well?

**Comment by Ryan-Miller-Audacity** [comment]
I cannot reproduce this either at those scalings or even 175%. I checked on both my Windows 10 machine as well as Mac and did not see the share audio button at 3x height.

**Comment by DavidBailes** [comment]
> I have checked with 125% and 150% and I am unable to reproduce the problem.

This problem only occurs if the "high dpi override" is set for the Audacity.exe (properties dialog, compatibility tab, Change High DPI settings, check Override high DPI scaling behaviour", leave list box set to application.
For the 125% scaling factor, this high dpi override setting makes the text in Audacity a lot clearer and easier to read.

**Comment by Ryan-Miller-Audacity** [comment]
Hmmmm yeah @crsib I do see the 3x times height for the share audio button with that setting that @DavidBailes described on my windows machine.

**Comment by Ryan-Miller-Audacity** [comment]
Tested and confirmed that the additional case from above has been fixed.
