### ISSUE TITLE
Maintainability of EffectSettingsAccess

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#3595]
### Steps to reproduce

EffectSettingsAccess code worked well enough for Ladspa, LV2, AudioUnits, but this framework was getting stretched to work with VST and VST3, which calls for some redesign.

Ask me later for more detailed ideas

### Expected behavior

A refactor that changes nothing

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

**Comment by mckinsy** [comment]
Hello Sir! I'm interested, please provide me details and I do hope your guidance throughout
