### ISSUE TITLE
Capitalize OK button in the Link Account popup

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3612]
### Steps to reproduce

1. Link Audio.com account to Audacity

<img width="545" alt="image" src="https://user-images.githubusercontent.com/70063970/189897842-3038aca6-c08d-4fae-87c1-7d7690a30588.png">

### Expected behavior

The button's label is **OK**

### Actual behavior

The button's label is **Ok**

### Audacity Version

current master / alpha / nightly build

### Operating system

Other

**Comment by mnmason86** [comment]
@dozzzzer 

I would like to make a PR for this issue. I am new to OSS contributions, but I have signed the CLA. How do I go about pushing my change for this issue?
