### ISSUE TITLE
Incompatible plugins dialog should be shown for any failed plugins found from manual rescan

### ISSUE THREAD

**Issue by ksoze95** [audacity/audacity#3622]

**Comment by crsib** [comment]
Was this behavior confirmed by design team? As a user I would prefer a single dialog

**Comment by ksoze95** [comment]
> Was this behavior confirmed by design team? As a user I would prefer a single dialog

Yes, it was.   It was mentioned here.  https://github.com/audacity/audacity/issues/3576#issuecomment-1242125849

**Comment by dozzzzer** [comment]
### macOS: After plugin rescan is finished, 'Incompatible Plugins' dialog appears in the foreground but it cannot be dismissed.

None of the buttons highlighted on the screenshot are clickable in this case. Clicking OK button within Plugin Manager dialog is the only way to make it disappear. Which isn't too obvious.

<img width="555" alt="image" src="https://user-images.githubusercontent.com/70063970/190606732-44e505ab-6aa9-44c5-a385-f766f32ee6a4.png">

STR:

1. Go to Plugin Manager and start manual rescan
2. Wait till rescan process is finished
3. Try to dismiss the Incompatible Plugins dialog

**Comment by dozzzzer** [comment]
Verified
