### ISSUE TITLE
Audacitian Mess

### ISSUE THREAD

**Issue by Gootector** [audacity/audacity#3625]
### Your idea

1. Merge alpha-3.2.0 to release-3.2.0.
2. Delete alpha-3.2.0 after merging.

### Problem to be solved

So, Paul...
We have 3 branches:
- master
- alpha-3.2.0
- release-3.2.0
1. Alpha-3.2.0 status is: This branch is 1 commit ahead, 12 commits behind master. 1 missing commit is Update Italian translations for v3.2.0 #3621. Alpha-3.2.0 is merged into master. But - without this commit. Why?
2. Audacity 3.2.0 Beta is released. BETA.
3. Release-3.2.0 doesn't have this #3621 commit, and master too.
So... I have a question: what's is going on here?

**Comment by crsib** [comment]
Italian was merged to alpha-3.2.0 by mistake, I've asked @Paul-Licameli to fix that already. I agree, that we should remove `alpha-3.2.0` branch though and provide a new link to translators. It was my mistake that I've sent it relative to a branch, not pinned to a specific commit.

I think we will be discussing the overall localization flow after 3.2.0 is released,  to find ways to improve the current one. Your input will be much appreciated.

**Comment by Gootector** [comment]
Thanks for the answer. I think that translation platform, like Transifex or Weblate, should be solve the problem. I have accounts on Transifex and GitHub and is comfortable for me. Polish language is always up to date. At this moment, there is nothing to do on this matter, it means with Polish translation - status is gold :D. I close this issue when Paul solves problem with branches.

Greetings,
Gootector
