### ISSUE TITLE
Visual corruption on Windows when enlarging the real-time effecs stack pane

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#3641]
### Bug description
You get visual corruption on Windows when enlarging the real-time effects stack pane.

This does not occur on Mac.

### Steps to reproduce
1. get some audio
2. click the **Effects** button the the TCP
3. click on the boundary between the effects pane and the tracks pane and drag slowly rightwards to enlarge the effects pane
4. Observe: visual corruption at the top of the effects pane - see image below.

### Expected behavior
![image](https://user-images.githubusercontent.com/50205984/190897341-42e48b2c-5586-4efc-a94a-8751b3f67ccb.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/50205984/190897246-e79488a7-117a-45e8-8755-cfde98b30647.png)

### Audacity Version
current master / alpha / nightly build  -  3.2.0 Beta

### Operating system
Windows - W10

### Additional context
The visual corruption disappears if you click anywher in the Audacity window. 

Also note that if then then go on to enlarge the RT effects pane still more - then you don't get the visual corruption.

**Comment by LWinterberg** [comment]
This will be fixed in Audacity 4
