### ISSUE TITLE
Toolbar menu items alphabetic order

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#3650]
### Your idea

The "View > Toolbars" menu would be easier to navigate if the menu items were in alphabetic order, rather than seemingly random order.

### Problem to be solved

![toolbars](https://user-images.githubusercontent.com/11681097/191257953-d68b1632-2bc1-4247-893c-d61e654f5fe4.png)

**Comment by LWinterberg** [comment]
The Qt version has individually customizable buttons instead of toolbars anyway, and this is such a minor point, I don't think it's worth doing.
