### ISSUE TITLE
Data loss possible when realtime effect dialog closes

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#3663]
### Bug description

Project can save and then fail to reopen!

Updated STR:  you don't need play in progress to get the misbehavior.  Just have a sidebar dialog open when you close the project.  Needn't quit the program either.

### Steps to reproduce

1. Generate tone
2. Add an effect to its stack, e.g. Dragonfly HallReverb
(3. Play all in a loop)
4. Open effect settings (during play)
5. Ctrl+Q to quit or Ctrl+W to close
6. Say "yes" to saving the project
7. (Restart Audacity and) reopen the saved project
8. See message that project was not properly saved and was recovered from backup.  There are no tracks!

### Expected behavior

Keep the track that I saved!

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

**Comment by Paul-Licameli** [comment]
At least on a macOS debug build with the effect I named, I can reproduce this regularly.

**Comment by dozzzzer** [comment]
Verified
