### ISSUE TITLE
User isn't asked to save changes when tweaking parameters of the effect and then quitting

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3670]
### Steps to reproduce

1. open an existing project which has an RT effect added to the track
2. open the RT effect's dialog
3. tweak some parameters
4. Cmd + Q
5. observe

### Expected behavior

The user is asked to save the changes (Yes/No)

### Actual behavior

The project window is closed right away without asking the user to save the changes

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

**Comment by Ryan-Miller-Audacity** [comment]
Confirmed that users are now asked to save project when attempting to quick exit Audacity after making tweaks to effect parameters. This was tested on both MacOS and Windows 10 with all RT effect families.
