### ISSUE TITLE
Show mute/solo buttons on collapsed tracks

### ISSUE THREAD

**Issue by JC3** [audacity/audacity#3676]
### Your idea

It's pretty odd that you have to expand collapsed tracks to change their mute/solo status, or even just check it. It's especially an issue in projects with many tracks with multiple "solo" tracks enabled.

Some form of button, or at least status indication, for the mute (and solo) state of each track should still be visible when the track is collapsed.

There's a few places they could go; and also the "select" button is pretty unnecessary in general when you can just click the track details to do the same thing; or at least it doesn't reasonably need to be there when the track is collapsed.

### Problem to be solved

Inability to know which tracks are playing vs muted in under track_count * 2 clicks + multiple scrollbar interactions when tracks are collapsed. Inability to change settings without expanding the track.

### Prior art

Off the top of my head, considering other multi-track audio applications in general (not just editors):

- Pro Tools - Collapsing tracks keeps mute/solo/record buttons visible in a more compact form.
- Qtractor - Separate mixer window, and buttons stay visible in track view as well. 
- Ableton - Session view preserves mute/solo/pan/gain when mixer collapsed; timeline view always displays buttons next to tracks.
- Fruity Loops - Mixer is a separate window from tracks, always displays buttons

MixPad, unfortunately, has the same issue as Audacity here.

**Comment by petersampsonaudacity** [comment]
As an alternative one could have Mute and Solo added as commands in the Track Control Panel dropdown menu:
![image](https://user-images.githubusercontent.com/50205984/192141836-4353ec2c-151a-417e-bd1d-66b7ff8cfca9.png)

**Comment by JC3** [comment]
That would be very handy for control, but not so much for quickly
determining the mute/solo state of all tracks at a glance.

Right now the only visual indicator is that the waveform turns gray if a
track is muted, but the color change isn't really visible if the track has
no audio in the display area (considering waveform vertical zoom +
horizontal time zoom) or if it's in spectrogram view (has no color change),
and it also doesn't distinguish between a track being in solo mode vs just
being not in mute mode.

So even just a pair of led-like non-clickable "M" and "S" indicators in the
collapsed view would work, in combination with your menu item idea. Or just
change the color of the track info area maybe (typically red = mute and
yellow = solo; and the default bluish could be for neither).

Lots of options.

**Comment by LWinterberg** [comment]
![image](https://user-images.githubusercontent.com/87814144/201624188-972e1c65-9368-4806-a3fc-ec97c137f261.png)

I really liked this pattern from Serato Studio, where for small sizes the controls are hidden until you hover over the header.

**Comment by JC3** [comment]
> ![image](https://user-images.githubusercontent.com/87814144/201624188-972e1c65-9368-4806-a3fc-ec97c137f261.png)
> 
> I really liked this pattern from Serato Studio, where for small sizes the controls are hidden until you hover over the header.

I've never used Serato. Are you able to tell if a track is solo'd or muted without hovering over it?

I also like that idea though, with maybe a little colored square next to the track name to indicate the state? Or changing the track name color (it looks like maybe that's what Serato does?).

**Comment by LWinterberg** [comment]
![image](https://user-images.githubusercontent.com/87814144/201679506-e32f727c-0597-4028-8df6-7cb227942acf.png)
they change the color to grey for muted tracks and keep the controls visible. So yeah.

FWIW, there's a major redesign coming for the track header anyway

**Comment by JC3** [comment]
Here is Ableton's setup in arrangement view with the tracks collapsed (when they're expanded it's the same layout; just more spacing between tracks of course):

![Animation](https://user-images.githubusercontent.com/5651184/201680494-cc0f2ef4-eb25-4316-a823-f0c9ecf27970.gif)

The button on the left has the track name and serves as a mute button (orange = active, dark gray = muted). The S buttons are for solo mode and also change the active track buttons when solo is enabled. This setup wouldn't really need adjustments to support Audacity's "multiple solo" mode.

**Comment by JC3** [comment]
As an aside, one thing that *should* probably change if a smoother mute/solo workflow is implemented is Ableton's behavior of scrolling the top of the track into view when you interact with the track -- this is especially disruptive if one of your track heights is close to or greater than the window height. This probably shouldn't happen, or should be changed to a user preference.

**Comment by JC3** [comment]
You know, I kind of underappreciated Audacity's Mixer view. It actually handles this pretty well, as long as you don't mind having the view open, it solves the issue of checking track states at a glance.

**Comment by LWinterberg** [comment]
This is obsoleted by a new track header design which has the major controls in a single line
![image](https://github.com/audacity/audacity/assets/87814144/87f938d2-0eaf-4d4e-8afb-3a3d0ffbe8e0)
