### ISSUE TITLE
VSTs get disabled for more than Audacity

### ISSUE THREAD

**Issue by LiftPizzas** [audacity/audacity#3683]
### Bug description

After installing the latest Audacity, it "disabled" several instrument VSTs. Then after closing Audacity and trying to load up a project in Reaper, it reported that several VSTs (the above disabled ones) could not be loaded or used.

### Steps to reproduce

Install the Vital VST and create a track in Reaper that uses it, then close Reaper.
Load up Audacity and let it "disable" Vital.
Try to load the project in Reaper and use the Vital plugin.

### Expected behavior

If Audacity can't work with an instrument plugin that shouldn't be the problem of every other thing on the system that can.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by Ryan-Miller-Audacity** [comment]
I have been taking a look at this and have not been able to reproduce it so far. I am not seeing the Vital synth being unavailable in Reaper after it being disabled by Audacity. I also tried this with Studio One as well and could not reproduce it there either.

**Comment by LWinterberg** [comment]
You have a corrupted Reaper VSTPlugins64.ini. This problem is unrelated to Audacity.

You may want to look into Reaper help ressources instead: 
* https://www.reddit.com/r/Reaper/comments/tbtvgc/reaper_wont_load_plugins_randomly_after_theyve/
* https://forum.cockos.com/showthread.php?t=200407
