### ISSUE TITLE
Mainstream wxwidgets

### ISSUE THREAD

**Issue by tiziodcaio** [audacity/audacity#3684]
### Your idea

At the moment audacity is using an older version of wxwidgets for its deploys and if we want to use the sistem-wide version we have to disable conan... Can we remove this "feature" now that the default wxwidgets it's likely more supported?

### Problem to be solved

Remove conan wxwidgets dependency and add the wxwidgets 3.2.0 from apt/pacman dependency for offical aduacity

**Comment by crsib** [comment]
Audacity builds against system wxWidget 3.2.0 perfectly

**Comment by crsib** [comment]
It is not. Audacity targets other platforms as well, not only specific Linux distros, that have wxWidgets 3.2

**Comment by crsib** [comment]
You are free to use any version you think suits you best. There is an option provided exactly for it. This will not be the default nor only option. Audacity uses heavily patched version of wxWidgets. Provided that we plan to migrate to Qt - it is not feasible to port those patches to 3.2.
