### ISSUE TITLE
[Plugin issue] - VST/WaveShell1-VST 14.0.vst NOT WORKING and REALTIME EFFECTS GONE

### ISSUE THREAD

**Issue by TabethaMcNealVO** [audacity/audacity#3687]
### Plugin

WaveShell1-VST 14.0.vst

### Plugin Format

VST2

### Bug description

I recently did a rescan on Audacity 3.0, yesterday was fine doing a rescan but today it has left me on a 93:10:18 remaining time limit to find WaveShell1-VSt 14.0.vst and RealTime Effects No longer work. I've tried everything and nothing is working. 

### Steps to reproduce

<img width="1122" alt="Screen Shot 2022-09-25 at 4 15 16 PM" src="https://user-images.githubusercontent.com/111609600/192163470-1d99efac-248a-4abe-a488-025371dafe53.png">

### Expected behavior

It should've worked liked it did yesterday with no problems. I did a quick scan and everything should up. 

### Actual behavior

It scan only a few plug-ins and when it get's to WaveShell1-VST 14.0.vst it stops for hours. 

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

### Architecture

Apple Silicon (M1, M2, ...)

**Comment by crsib** [comment]
Can you please provide a list of your plugins by Waves that you have?

**Comment by TabethaMcNealVO** [comment]
Sure! I recently downloaded the Waves Central and only have StudioRack showing up for me. But it's the V14.0.0 Version. On Audacity it's showing I have the plugin but it's disabled
<img width="1117" alt="Screen Shot 2022-09-25 at 4 22 55 PM" src="https://user-images.githubusercontent.com/111609600/192164043-ee1dca11-6e2b-41af-948d-9471ac123bf1.png">
d and when I enable it, Audacity freezes.

**Comment by crsib** [comment]
Thank you a lot, we will check! Oddly Studio Rack works fine for me on Windows:-)

**Comment by TabethaMcNealVO** [comment]
Right! It was working fine yesterday. I recently did an audition and it worked. But since the rescan lol its broken.

**Comment by TabethaMcNealVO** [comment]
**UPDATE** 
I've tried reinstalling, but soon as I open Audacity it comes up with a rescan.

**Comment by dozzzzer** [comment]
@TabethaMcNealVO I've been trying to reproduce the problem over the last two days but I'm consistently seeing my StudioRack up and running. Neither I'm getting the freeze during the initial scan or when enabling the plugin. Verified on macOS 12.5.1.

**Comment by Ryan-Miller-Audacity** [comment]
I have confirmed the same findings as dozzzzer. On both windows and macos I have not been able to reproduce the behavior shown. No problems with initial scan, rescan, or enabling/using the plugin

**Comment by vsverchinsky** [comment]
@TabethaMcNealVO Could you please send what's in your log file after plugin scanning freezes (Help->Diagnostics->Show log)?
