### ISSUE TITLE
Where is the Play At Speed in Audacity 3.2.x?

### ISSUE THREAD

**Issue by brmonaghan** [audacity/audacity#3707]
### Bug description

I cannot find the play at speed anymore in Audacity 3.2.x
I tried finding it and it is not there anymore.

### Steps to reproduce

1. Start Audacity
2. Go to the top of the window
3. Not there.

### Expected behavior

I want this back if its gone, because I LOVED this feature when speeding up sound effects.

### Actual behavior

Just plain ol sound. No chipmunks, no slow mo, no more fun. 🥲

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

![image](https://user-images.githubusercontent.com/71337477/192651205-9f1d6972-81ed-462f-9bfb-bebcaebd3755.png)

**Comment by LWinterberg** [comment]
![image](https://user-images.githubusercontent.com/87814144/192688828-28a5b36a-93c7-40f0-9858-9549e903a5a2.png)

**Comment by stormsnsnow** [comment]
This issue is now back, this time with Audacity 4.0!
No where to be seen. Except in Extras where it is greyed out.
