### ISSUE TITLE
Plugin scan takes waaayyyy too long

### ISSUE THREAD

**Issue by LeoJr2015** [audacity/audacity#3708]
### Bug description

Fresh 3.20 install. First startup and anytime I rescan for plugins, it takes an exorbitant amount of time, and I have to stop it. Why is that?
![2022-09-27](https://user-images.githubusercontent.com/11169785/192663859-13883e58-033d-4462-8f84-750b6b9a94a8.png)

### Steps to reproduce

Install 3.2.
First launch it scans for plugins.
This takes too long.

### Expected behavior

Not take forever.

### Actual behavior

Taking forever.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

Windows 11 Enterprise. No special plugins yet. Stock v3.2 install

**Comment by dozzzzer** [comment]
@LeoJr2015 if you could please provide the full list of the plugins you have installed in your OS, that could give us something to start looking into.

**Comment by petersampsonaudacity** [comment]
I had this problem on W10 a week ago with long scanning for Classic Filters (that also had to be aborted) when I was testing late alphas/Betas of 3.2.0 - but this does not occur for me with the released 3.2.0.

I did raise this on the 3-2 Discord channel

**Comment by LeoJr2015** [comment]
Yes, this is a new Windows 11 Enterprise install, with K-Lite Codec Pack. https://codecguide.com/download_kl.htm

 The only additional plugin I added was the Red Rock eq302.  https://redrocksound.pro/products/eq302-pc/

Thanks.

**Comment by dozzzzer** [comment]
FWIW, I wasn't able to reproduce the issue on the freshly installed Win 11 22H2 +  K-Lite Codec Pack + Red Rock eq302.

**Comment by vsverchinsky** [comment]
@LeoJr2015 Could you please send your `audacity.cfg` and `pluginregistry.cfg` files?

**Comment by dozzzzer** [comment]
@LeoJr2015 FYI, the Classic Filters effect is now disabled so it will not cause the freeze when scanning. Also, if any other plugin freezes the scanning process for you, you'll now be able to skip this particular plugin by clicking the Skip button. These changes will be introduced in 3.2.2 release.
