### ISSUE TITLE
'Plugin Manager' tab shows up under 'Generate', 'Effect', 'Analyse' and 'Tools' tabs.

### ISSUE THREAD

**Issue by bdmax1040** [audacity/audacity#3709]
### Bug description

If you click on any of the Generate, Effect, Analyse or Tools tab at the top of the program, the plugin manager is found at the top of every single one. I assume that this should only show up under the tools tab rather than all 4.

### Steps to reproduce

1. Go to either the 'Generate', 'Effect', 'Analyse' or 'Tools' tab in the menu bar
2. Observe the repeating of the 'Plugin Manager' dropdown for each item

### Expected behavior

The 'Plugin Manager' dropdown should only show for the 'Tools' tab, rather than all 4.

### Actual behavior

The repeating of the dropdown across 4 tabs

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS

### Additional context

This is in the latest Audacity 3.2 update running on an M1 Max MacBook Pro using the ARM64 download of Audacity.

**Comment by LWinterberg** [comment]
It's always been like this (though previously called "Add/Remove Plugins...") and while I follow your argument in principle, in practice I don't think it's worth changing right now. It's not hurting in its current state and can stay where it is until a larger menus/preferences restructuring.
