### ISSUE TITLE
Gdk-CRITICAL: gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed

### ISSUE THREAD

**Issue by bdrung** [audacity/audacity#3714]
### Bug description

There are critical Gdk errors when launching audacity. The package in Debian/Ubuntu report:

```
(process:2365): Gdk-CRITICAL **: 17:23:14.820: gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed

(process:2365): Gdk-CRITICAL **: 17:23:14.820: gdk_window_get_display: assertion 'GDK_IS_WINDOW (window)' failed

(process:2365): Gdk-CRITICAL **: 17:23:14.820: gdk_cursor_new_from_pixbuf: assertion 'GDK_IS_DISPLAY (display)' failed
```

The same errors can be found in the AppImage:
```
(process:2645): Gdk-CRITICAL **: 17:24:40.758: IA__gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed

(process:2645): Gdk-CRITICAL **: 17:24:40.758: IA__gdk_drawable_get_display: assertion 'GDK_IS_DRAWABLE (drawable)' failed

(process:2645): Gdk-CRITICAL **: 17:24:40.758: IA__gdk_cursor_new_from_pixbuf: assertion 'GDK_IS_DISPLAY (display)' failed
```

Others have this too: https://github.com/audacity/audacity/issues/1726#issuecomment-1022419481

According to upstream Gtk:
> Anything that happens after a critical warning is undefined behaviour; the proper way to deal with it is actually crashing.

Tested with Audacity 3.2.0 on Debian testing and Ubuntu 22.10 (kinetic).

### Steps to reproduce

Launch audacity from the command line.

### Expected behavior

No output on stdout when launching audacity.

### Actual behavior

```
$ audacity

(process:2365): Gdk-CRITICAL **: 17:23:14.820: gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed

(process:2365): Gdk-CRITICAL **: 17:23:14.820: gdk_window_get_display: assertion 'GDK_IS_WINDOW (window)' failed

(process:2365): Gdk-CRITICAL **: 17:23:14.820: gdk_cursor_new_from_pixbuf: assertion 'GDK_IS_DISPLAY (display)' failed
```

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Linux

**Comment by LWinterberg** [comment]
This won't be fixed directly, however, Audacity is currently being ported to Qt, which will fix this along the way.
