### ISSUE TITLE
Freeze via left clicking play head bar and pushing space bar to play

### ISSUE THREAD

**Issue by Dontknowhow2code** [audacity/audacity#3716]
### Bug description

Clicking the play head area (highlighted in yellow) to play the track and pushing space to play the track at the same time causes audacity to crash.
It is easier to rapidly left click on the play head area whilst rapidly spamming the space bar.
![audacity crash](https://user-images.githubusercontent.com/81732647/192980107-1847e987-f399-46aa-aa54-7463e513abeb.png)

### Steps to reproduce

1. Open audacity
2. Open any track
3. Rapidly left click on the play head area repeatedly whilst rapidly pressing the space bar repeatedly.
4. Audacity crashes

### Expected behavior

Audacity shouldn't crash and should just play and pause over and over again.

### Actual behavior

Crash

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

Log during crash:
> 21:26:51: Audacity 3.2.0
> 21:26:51: sqlite3 message: (1) no such table: project in "SELECT 1 FROM project LIMIT 1;"
> 21:26:51: Error: Failed to load shared library 'avformat-59.dll' (error 126: The specified module could not be found.)
> 21:26:51: Error: Failed to load avformat-59.dll (error 126: The specified module could not be found.)
> 21:26:51: Error: Failed to load shared library 'avformat-58.dll' (error 126: The specified module could not be found.)
> 21:26:51: Error: Failed to load avformat-58.dll (error 126: The specified module could not be found.)
> 21:26:51: Error: Failed to load shared library 'avformat-57.dll' (error 126: The specified module could not be found.)
> 21:26:51: Error: Failed to load avformat-57.dll (error 126: The specified module could not be found.)
> 21:26:51: Error: Failed to load shared library 'avformat-55.dll' (error 126: The specified module could not be found.)
> 21:26:51: Error: Failed to load avformat-55.dll (error 126: The specified module could not be found.)

device info txt generated by audacity:
[deviceinfo.txt](https://github.com/audacity/audacity/files/9672666/deviceinfo.txt)

computer info:
Dell Inspiron 3505
CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx 2.10 GHz
8GB RAM
x64-based processor

screen recording of crash:
https://user-images.githubusercontent.com/81732647/192988667-76d3dbce-e7b0-4886-99f1-78e6cd516b87.mp4

**Comment by petersampsonaudacity** [comment]
See also:  Audacity freezes when quickly starting and stopping playback #3699

**Comment by dozzzzer** [comment]
In my case, it goes into a deadlock with no crashing. Windows 11.
Might actually be related to #3699

**Comment by petersampsonaudacity** [comment]
> In my case, it goes into a deadlock with no crashing. Windows 11.

Yes I get deadlock/freeze and not crash on W10 with 3.2.0
