### ISSUE TITLE
64-bit Audacity installer prompts to install in the (x86) folder

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3718]
### Bug description

By default, the 64-bit installer prompts to install Audacity in **C:\Program Files (x86)\Audacity** 

### Steps to reproduce

1. launch the 3.2.0-64bit installer on Windows 10 or 11
2. see the prompted installation path

### Expected behavior

C:\Program Files\Audacity

### Actual behavior

C:\Program Files (x86)\Audacity

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by crsib** [comment]
I am pretty sure that it tries to install to the **last** directory. Checking on Windows sandbox shows that the default path is correct.
![image](https://user-images.githubusercontent.com/2660628/193008208-29238e11-3839-45c4-8bd5-1431654a9291.png)

**Comment by dozzzzer** [comment]
> to the **last** directory

I'm pretty sure this couldn't be the case since I'm launching the installer for the first in the literally freshly installed OS.

**Comment by crsib** [comment]
But as you can see from the screenshot - it is not reproducible for me :-)

**Comment by petersampsonaudacity** [comment]
It default installed in c:\Program Files for me

I'm pretty sure that @crsib Dmitry is correct when he says he thinks that it offers as default the location last used for installation

**Comment by dozzzzer** [comment]
The problem seems to exist only when installing on VMs. Closing.
