### ISSUE TITLE
Crash when trying to use a deleted VST plugin before a Rescan

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#3719]
### Bug description

If you delete VST plugins while Audacity is open and then try to use them, then Audacity will crash.

Does not occur if you exit Audacity and relaunch as a Rescan is forced on startup

### Steps to reproduce

1. Install some Steinberg VST plugins (I had Voxengo Elephant, BLOCKFISH compressor, FLOORFISH de-esser & SPITFISH de-esser
2. Observe they are installed in C:\Program Files (x86)\Steinberg\VST
3. Launch Audacity 3.2.0
4. click on the Effect menu
5. Observe: the VST effects are shown at the bottom of te list
6. get some audio
7. apply one of those VST effects to the audio
8. Observe: it works
9. Delete the VST dll files from C:\Program Files (x86)\Steinberg\VST
10. click on the Effect menu
11. Observe: the VST effects are still showing
12. try applying one of those VST effects to the audio
13. Observe: Audacity crashes

_I sent the ET-phone-home crash report_

### Expected behavior

No Crash

### Actual behavior

Audacity crashes

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

If after the crash you relaunch Audacity, all is well as the launch forces a rescan and the deleted VSTs are no longer shown in the Effect menu.

The workaround is to do a Rescan after Step 9 where the VST dll files are deleted

**Comment by LWinterberg** [comment]
I can reproduce this. To me, the expected behavior would be an error message á la

> This plugin could not be loaded. It may have been deleted.

**Comment by petersampsonaudacity** [comment]
@LWinterberg  -  perhaps an error message could advise the user to do a Rescan.

**Comment by dozzzzer** [comment]
Verified on macOS and Windows
