### ISSUE TITLE
Audacity AppImage does not have "native look and feel"

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#3734]
### Bug description

According to wxWidgets documentation:
>  wxWidgets gives applications a truly native look and feel because it uses the platform's native API rather than emulating the GUI.

Prior to 3.2.0 AppImage, Audacity did indeed have "a truly native look and feel", whereas 3.2.0 AppImage (official release version) looks more like a Windows 98 app.

### Steps to reproduce

1. Launch Audacity 3.2.0 AppImage.

### Expected behavior

![313](https://user-images.githubusercontent.com/11681097/193406528-882be3e2-6117-4283-8ad5-9970e4200dc5.png)

### Actual behavior

![320](https://user-images.githubusercontent.com/11681097/193406532-297854ff-a34a-4262-8218-3a7effe30931.png)

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Linux

### Additional context

Screenshots taken with Preferences reset to default.

**Comment by LWinterberg** [comment]
it technically is native - to Gnome 2 :) 

anyway, this is due to https://github.com/audacity/audacity/pull/3571. While it sure looks ugly, it at least makes things usable. Before, 

* Icons would not appear
* Text boxes would not be white
* Dropdowns would just be text
* Checkboxes would not appear
* In menus, the ▸ icon and divider lines would not appear
* The plugin manager scrollbar would not appear

**Comment by SteveDaulton** [comment]
The repository version of Audacity for Ubuntu 20.04 is Audacity 2.3.3.
* Icons appear correctly
* Text boxes look mostly correct
* Checkboxes appear correctly
* In menus, the ▸ icon and divider lines appear correctly
* The plugin manager scrollbar appears correctly
(There is an issue with text appearing incorrectly in the Device Toolbar, but that is now hidden by default).

**Comment by LWinterberg** [comment]
2.3.3 also is not an appimage.

**Comment by wchouser3** [comment]
I just thought I'd mention - Though the new way of handing theming isn't ideal, it's a usability improvement given some themes didn't work at all, and almost none of them gave you the right drop-downs and stuff. This is one of those apps that I care more about functionality than aesthetics.

**Comment by crsib** [comment]
I don't think that there is much we can do before Audacity 4. We can try moving to wxGTK3 and ditching 18.04, this will probably improve the visuals a bit.

You can always build Audacity on Linux yourself though and you won't have the problem. Before 3.0.3 Audacity had no "official" binary distribution anyway.

**Comment by SteveDaulton** [comment]
> Before 3.0.3 Audacity had no "official" binary distribution anyway.

For that reason I've removed the "regression" label.
(I very much appreciate your work @crsib to provide an official binary release, and your efforts to help distro maintainers.)


> We can try moving to wxGTK3 and ditching 18.04, this will probably improve the visuals a bit.

[Next April ](https://endoflife.software/operating-systems/linux/ubuntu)might be a good date to do that.

**Comment by wchouser3** [comment]
yea....compiling from source is easy enough. The instructions in the build.md are well written. Compiling doesn't take all that long. I just installed it that way and now it looks great.

**Comment by LWinterberg** [comment]
this won't be fixed in the wx version and won't be an issue in the Qt version
