### ISSUE TITLE
Incorrect zh-CN translation for "Clip Fix" plugin

### ISSUE THREAD

**Issue by whc2001** [audacity/audacity#3738]
It takes me good ten minutes to find "Clip Fix". Even after switching the language to English it's still shown in Chinese since it's an external plugin instead of built-in effect. "Clip" in this context is the same as "Waveform Clipping" rather than "Audio Clip" and "Fix" is as in "Fix the television" rather than "Fixed-point Number". Personally I would prefer "削波失真修复".

https://github.com/audacity/audacity/blob/2b17feac68e31be8f35ed03a3495fbb0afd4c7fe/locale/zh_CN.po#L19921

**Comment by luzpaz** [comment]
@hlf20010508 do you mind also taking a look at this ?

**Comment by hlf20010508** [comment]
I think his translation is better than the one in zh-TW.
I've submitted.

**Comment by luzpaz** [comment]
Thanks! Ticket should be closed
