### ISSUE TITLE
Dynameter displays empty window [Plugin issue] 

### ISSUE THREAD

**Issue by vladimirkl** [audacity/audacity#3739]
### Plugin

Dynameter

### Plugin Format

Audio Unit

### Plugin source

https://www.meterplugs.com/dynameter

### Bug description

Dynameter plugin stopped working in Audacity 3.2.0 for Mac. It doesn't display UI - just empty window. Plugin worked perfectly with previous Audacity versions. 

### Steps to reproduce

1. Install Dynameter plugin and enable eiher AU or VST versions in plugin manager.
2. Open any audio track and select it
3. Choose Effect  - Dynameter...
4. See empty window with Preview and Apply buttons
5. Press Preview button or Apply buttons - they apply something but do not display Dynameter UI

### Expected behavior

1. Plugin's window should display  UI as it was in previous Audacity versions
2. Preview buttons should start analysis with realtime update of UI
3. Apply button should analyze whole selection and keep plugin's window with UI open - also as it was in previous Audacity

### Actual behavior

No UI at plugin startup and on Apply and Preview buttons

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

### Architecture

64 bit Intel/AMD processors

**Comment by Ryan-Miller-Audacity** [comment]
@vladimirkl We've done significant work to the VST framework and wanted to retest this issue to see if it persists. Could you please see if you can still reproduce this issue in our most recent release build found here: https://github.com/audacity/audacity/actions/runs/3471420722? Our team does not own dynameter and it doesn't appear they offer a free trial of the plugin either.

**Comment by vladimirkl** [comment]
@Ryan-Miller-Audacity Just tested Dynameter VST with 3.2.2 - it shows UI and working in real  time with Preview button. The only thing that still not working is Apply button. In Audacity 3.1.x it analyzed whole selection and left plugin window open with summary results in UI. Now it runs analysis but closes plugin window. You can check same behavior of Apply button with free plugins like Bitter
