### ISSUE TITLE
Maintainability of effect inter-thread communication, part two

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#3745]
### Bug description

See #3742

This issue tracks the second of two parts of clean-up of the general stackable effect framework.  But then work for particular effect families may follow:  AU, VST3, and a new VST2 statelessness built on these better foundations.

LV2, Ladspa and built-in effects might also be simplified, but they did not get as difficult as the others.

### Steps to reproduce

Nothing wrong now in the observable behavior

### Expected behavior

After merging, verify workings of Ladspa, LV2, VST3, AudioUnits effects, especially the stickiness of settings

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

**Comment by pietro68** [comment]
I verified that stickiness for vst2 works, with the first versions of the PRs. Still have to try the second versions.

**Comment by dozzzzer** [comment]
LV2 effects (at least the ones made by x42) are now capable of input metering at a good refresh rate both on macOS and Windows.

**Comment by Paul-Licameli** [comment]
> I verified that stickiness for vst2 works, with the first versions of the PRs. Still have to try the second versions.

Did you mean VST3?

Real stickiness also includes persistency when you save and reopen the project.  Did you test that?

**Comment by dozzzzer** [comment]
RT application and stickiness of the settings work fine. Verified on LADSPA, VST3, AU, LV2 plugins on macOS, the build from the PR https://github.com/audacity/audacity/pull/3765

**Comment by Ryan-Miller-Audacity** [comment]
Yes RT application, stickiness and persistence of settings as well as metering for LV2 and LADSPA plugins appear working well. Tested with Build from PR #3765 on both Windows and Linux.
