### ISSUE TITLE
Label Sounds typo ("silence" <-> "sound")

### ISSUE THREAD

**Issue by JC3** [audacity/audacity#3748]
### Bug description

This is the "label sounds" GUI:

![image](https://user-images.githubusercontent.com/5651184/193489373-16202831-bec6-4a30-acb2-6b0f418bb7e5.png)

This is the dialog that pops up if no sounds are found:

![image](https://user-images.githubusercontent.com/5651184/193489459-b5b48480-1b65-4006-bcea-a94d1ae59006.png)

One of those is not correct (there is no "minimum sound duration" setting).

### Steps to reproduce

Run "label sounds" on audio with no sounds to get the dialog.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by SteveDaulton** [comment]
Wow, this bug has been present for over 2 years without anyone noticing. I guess that running the effect on a selection with no sound  is not very common ;-) Thanks for reporting it.

The message should say:

![labelsounds](https://user-images.githubusercontent.com/11681097/193553116-a0221a71-6cfc-484d-b80b-ca1e2ee04940.png)

I'll submit a fix shortly.

**Comment by petersampsonaudacity** [comment]
@Paul-Licameli @crsib 

Any chance this can be pulled into the upcoming 3.2.1 patch release?
