### ISSUE TITLE
ImageCache.png needs updating

### ISSUE THREAD

**Issue by starinspace** [audacity/audacity#3760]
### Bug description

The _ImageCache.png_ in costum does not work as it should, I tried multiple and the same with all. Using **Audacity 3.2.0**. It needs updating with a new

![Untitled-1](https://user-images.githubusercontent.com/56514044/194045500-ee796278-dad7-4cf1-9e18-653b36170d0a.jpg)

### Steps to reproduce

Put a ImageCache.png from exempel https://wiki.audacityteam.org/wiki/Theming_HowTo in **%AppData%\audacity\Theme\custom** (windows) and change in interface in audacity.

### Expected behavior

It should work and show button where they suppose to be.

### Actual behavior

A mess.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

### Additional context

If possible, instead of "ImageCache.png", **multiple images** for **each button** so its _easier to create a theme_.

**Comment by tbmmbt** [comment]
Agreed, my custom theme I've been using for years is now messed up in the latest update with the positioning of elements all corrupted. Please consider an alternative method for custom theming as suggested as the current way is very cumbersome.

**Comment by starinspace** [comment]
> Agreed, my custom theme I've been using for years is now messed up in the latest update with the positioning of elements all corrupted. Please consider an alternative method for custom theming as suggested as the current way is very cumbersome.

I see that they have image-file for each button, I think they should have done the same instead of having a merge image with multiple buttons, Its harder also to create theme that way. I hope they will make it possible to use our own theme like this instead:

https://github.com/audacity/audacity/tree/master/libraries/lib-theme-resources/dark/Components

**Comment by LWinterberg** [comment]
I wrote a new guide explaining on how to generate a new imagecache.png as well as providing one for 3.2.x: https://github.com/audacity/audacity/wiki/Creating-custom-themes

**Comment by tbmmbt** [comment]
OK, thanks but I can't really be bothered to edit my theme every time things like this suddenly appear in a new release without warning plus the privacy concerns of Audacity anyway so I think I'll stick with OcenAudio from now on.
