### ISSUE TITLE
With the RT VST3 effect's dialog opened, the refresh rate drops

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3764]
### Steps to reproduce

1. have an audio track
2. select a VST3 effect in the sidebar
3. open its dialog
4. start playback

### Expected behavior

No refresh rate drop

### Actual behavior

Display of the visualizations becomes laggy, refresh rate drops

https://user-images.githubusercontent.com/70063970/194095615-33c7863c-3f78-4631-8696-6d0e47e612cc.mp4

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

### Additional context

On Windows it drops too, but just a tiny bit

**Comment by Paul-Licameli** [comment]
I have a suspicion how this might be fixed.

**Comment by LWinterberg** [comment]
fixed by #3767
