### ISSUE TITLE
A VST2 effect shows up in the Realtime Effects panel

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#3771]
### Bug description

iZotope Vinyl fails to load in the effects stack in 3.3 alpha although:
a) iZotope Vinyl is present in the Effect menu with 3.3 alpha
b) it loads fine in the effects stack in 3.2.1

### Steps to reproduce

1. Install iZotope Vinyl
2. launch 3.2.1
3. Get some audio
4. Effect
5. Observe iZotope Vinyl is in the effects list
6. Press the Effects button in the TCP
7. Click Add Effect
8. **Observe: iZotope Vinyl is available and can be added to the stack**
9. Exit 3.2.1
10. Launch 3.3.0 alpha
11.  Get some audio
12. Effect
13. Observe iZotope Vinyl is in the effects list
14. Press the Effects button in the TCP
15. Click Add Effect
16.  **Observe: iZotope Vinyls is not available for adding to the stack**

### Expected behavior
iZotope Vinyl to be available for the effects stack

### Actual behavior
iZotope Vinyl **_not_** available for the effects stack  -  _even though it is available in the Effect menu_

### Audacity Version
audacity-win-3.2.2-beta-20221006+df0ffd2-x64-msvc2022

### Operating system
Windows 10

### Additional context
None

**Comment by crsib** [comment]
For now, VST plugins are not supported in the effects panel, only VST3 are. VST3 Vinyl works just fine for me.

![image](https://user-images.githubusercontent.com/2660628/194383492-edd0e97d-bdaa-4775-a0b0-30a3db460d2b.png)

**Comment by dozzzzer** [comment]
Same with me, VST3 loads just fine on Windows 10 & 11.

**Comment by petersampsonaudacity** [comment]
@dozzer and @crsib 

It's all well and good just to close this - but the user experience is a little more complex than
>For now, VST plugins are not supported in the effects panel

and
>closed this as [not planned

As it looks to the user that the VST iZotope Vinyl **_is_** available in the effects stack (based on the presentation in the GUI):
![image](https://user-images.githubusercontent.com/50205984/194564075-b01352de-53b3-4c63-abfa-f304195ba5c0.png)

However when the user clicks on the iZotope Vinyl button then all that happens is that nothing happens.
In particular there is **_NO_** error or waning message to advise that the VST effect is not supported in the effects stack, lus leaving the user puzzled or bewildered ...

So either:
a) VST effeects should not ve presented at in the effects stack if they are not supported there, or
b) an error message to be popped re not supported.

With a) as the preferred option.

**Comment by crsib** [comment]
So it appears to be a different bug - VST2 is on your list of plugins that are supported. This will be fixed soon, as VST(2) will get proper support!

**Comment by petersampsonaudacity** [comment]
I get the same problem when I try to use my VST3 version of iZotope Vinyl in the RR Effects stack
![image](https://user-images.githubusercontent.com/50205984/194706542-1a5b6c7f-338f-4400-bc7b-75bbd8c2ebee.png)

**Comment by dozzzzer** [comment]
Closed as irrelevant
