### ISSUE TITLE
Audacity appimage segfaults when .config/audacity folder does not exist - Linux

### ISSUE THREAD

**Issue by texstar** [audacity/audacity#3773]
### Bug description

If .config/audacity folder does not exist, the audacity appimage will segfault when launched from KDE Plasma on Linux.

### Steps to reproduce

.

### Expected behavior

audacity appimage should launch without segfault

### Actual behavior

.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Linux

### Additional context

.

**Comment by LWinterberg** [comment]
could not reproduce; it simply creates the folder for me.

**Comment by texstar** [comment]
It has been fixed in the latest version of audacity!
