### ISSUE TITLE
Make the Changelog / Release Notes viewable from the installer before installing

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#3774]
### Your idea

The "Setup Audacity" screen in the Windows installer says:
> See the CHANGELOG.txt file for a list of changes.

![Changelog](https://user-images.githubusercontent.com/11681097/194415338-8a4ef9ef-ae8e-4fd2-a2ea-5d7ed7465eaa.png)

but there is no indication of where to find the CHANGELOG.txt file, nor does it appear to be included in the package.

Please include a link so that the file may be read before installing.

### Problem to be solved

One of, if not "the" most important purposes of a Changelog / Release Notes file is to allow the user to asses the end user impact of the update, so that they may make an informed decision whether to proceed with the update. This is only possible if the document is readily available.

### Prior art

Virtually all other reputable applications do this.

### Additional context

Even the Release Notes on the wiki fail to mention any of the known issues in the 3.2.x releases.
https://wiki.audacityteam.org/wiki/Release_Notes_3.2
https://wiki.audacityteam.org/wiki/Release_Notes_3.2.1

**Comment by petersampsonaudacity** [comment]
This sounds like a sensible idea - and an easy one to implement surely.

**Comment by LWinterberg** [comment]
Note that this screen shows *after* the install is complete. 

The flow goes 

![image](https://user-images.githubusercontent.com/87814144/201635045-87b99a72-ac22-439f-9300-151e98fba6d0.png)
![image](https://user-images.githubusercontent.com/87814144/201635127-e82865fd-de6d-480f-9558-f1723d582d0d.png)
![image](https://user-images.githubusercontent.com/87814144/201635163-db16898d-3a6d-4406-a144-3b26e5774423.png)

Given that there is a changelog in the new version notification (before you even download the thing) and also a very prominent display of the release video on first launch, there's no need for this page to be shown at all.

**Comment by SteveDaulton** [comment]
> Given that there is a changelog in the new version notification

Doesn't that assume that the person is updating from within Audacity?

Testing with Audacity 3.2.0 AppImage, there's just a very brief list of bug fixes and a link to GitHub. Unfortunately when clicking on the link to GitHub I see this (this is with Firefox NOT running):

![changelog](https://user-images.githubusercontent.com/11681097/201703435-207b41c2-714a-4f6f-9d06-14d63c1c65d0.png)

**Comment by SteveDaulton** [comment]
Just my opinion, but it still seems a bit daft to tell people to "see the CHANGELOG.txt file for a list of changes" without providing a link or any indication of where they can find the changelog file.

**Comment by LWinterberg** [comment]
agreed; this was my mistake - I didn't realize that the readme.txt from the main directory would be shown during the windows installation, especially when the win/Inno_Setup_Wizard/audacity_InnoWizard_InfoBefore.rtf.in file covers much of the same information. "see the CHANGELOG.txt" assumed you were already located in the directory in question and viewing the readme.txt directly
