### ISSUE TITLE
"MFreeFXBundle" VST3 effects are unusable

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#3775]
### Bug description

The "MFreeFXBundle" VST3 effect, recommended in Audacity's [support documentation,](https://plugins.audacityteam.org/realtime-effects/plugin-suites) are unusable.
The effect GUIs are badly malformed, and the effects may cause Audacity to crash.

### Steps to reproduce

1. Create a project with an audio track
2. Click on the "Effects" button in the panel on the left of the track
3. Click "Add Effect > Get more effects..."
4. Click on the link for "[Available for Windows -> MFreeFXBundle](https://plugins.audacityteam.org/realtime-effects/plugin-suites)"
5. Click the "Free Download" button on https://www.meldaproduction.com/MFreeFXBundle
6. When the installer has downloaded, run the installer
7. Install the "Basic" set of VST3 plug-ins by following the on-screen instructions
8. Close and relaunch Audacity
9. Create a project with an audio track
10. Click "Add Effect" and add one of the MFreeFXBundle plugins
11. Click on the name of the plugin to open its GUI

### Expected behavior

A usable VST3 plug-in.

### Actual behavior

None of the plug-ins are usable. Here are screenshots of two of them:

![MEqualizer](https://user-images.githubusercontent.com/11681097/194417459-b91aa712-10ef-4144-acd4-63b31779085f.png)

![MWaveShaper](https://user-images.githubusercontent.com/11681097/194417481-589cd44c-109c-4b50-bd85-b4115752ba1c.png)

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

I specifically chose to install plug-ins that were recommended in the documentation rather than some arbitrary VST3 effects with the expectation that they would have been tested and known to work.

**Comment by LWinterberg** [comment]
![image](https://user-images.githubusercontent.com/87814144/194517497-e0c125f6-191b-4d8f-b5ac-33c624efa676.png)

![image](https://user-images.githubusercontent.com/87814144/194517617-6d9de82c-a552-445e-b89a-ecd8773209b4.png)

could not reproduce

**Comment by crsib** [comment]
Works great for me as well 
![image](https://user-images.githubusercontent.com/2660628/194522617-6a2e8900-c667-40fb-bb17-5e3f21d1ca75.png)

**Comment by SteveDaulton** [comment]
I wonder what's different on your machines.
Are you testing on the same PC as you build on, or a "clean" Windows installation? 
The machine that I tested on is very close to a (fully updated) virgin installation of Windows 10.

**Comment by vsverchinsky** [comment]
> I wonder what's different on your machines. Are you testing on the same PC as you build on, or a "clean" Windows installation? The machine that I tested on is very close to a (fully updated) virgin installation of Windows 10.

I tried to clean install the latest Melda pack, and do not observe this issue as well. I noticed that installer also provides legacy VST versions of the plugins, is it possible that somehow legacy VST's are available in the effect stack for you?

**Comment by SteveDaulton** [comment]
> is it possible that somehow legacy VST's are available in the effect stack for you?

As per step 7 in "Steps to reproduce", I installed only the "Basic" set of VST3 plug-ins. I did not install any VST2 plug-ins as I was just wanting to try out the new "real-time" effects.

**Comment by SteveDaulton** [comment]
Closing this issue as I see the same problem with these effects in Reaper.
