### ISSUE TITLE
that "maximum reverb" effect from youtuber simusicgh3

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [audacity/audacity#3776]
### Your idea

from the video format "15 [SOUND] Sound Variations in 60 seconds" he uses commonly

### Problem to be solved

implement.

**Comment by LWinterberg** [comment]
If there's specific effects which you can't replicate with Audacity-native effects, you can use plugins instead: https://plugins.audacityteam.org/realtime-effects/delay-and-reverb
