### ISSUE TITLE
LAME "--nogap" metadata is ignored

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#3778]
### Bug description

On importing an MP3 that has been encoded with LAME's "--nogap", Audacity fails to correct for padding at the start of the file.

### Steps to reproduce

1. Generate a 30 second tone
2. Export as MP3
3. Import the MP3 back into Audacity

### Expected behavior

The imported file to be exactly 30 seconds long, without padding at the start or end.

### Actual behavior

The imported track is longer than 30 seconds, with padding at the start and end.
In my test example, the padding at the start is about 25ms, and about 7ms at the end.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Linux

**Comment by Ryan-Miller-Audacity** [comment]
I can reproduce this as described in Audacity 3.2.1.

**Comment by crsib** [comment]
@dozzzzer @chinakov can you still reproduce?

**Comment by chinakov** [comment]
@crsib - I will take a look.

**Comment by chinakov** [comment]
@crsib - reproducible on Windows, Audacity 3.3.3.
