### ISSUE TITLE
macOS: "Cannot allocate memory" error on startup

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#3779]
### Bug description

3 users have been reported running into the following error message while attempting to launch Audacity: 

`Unable to create shared memory segment. Error code=12: "Cannot allocate memory".`

![image](https://user-images.githubusercontent.com/87814144/194533622-33ff68da-6280-42cf-a8f2-02fe2cac7472.png)

### Steps to reproduce

not yet known

### Expected behavior

regular launch

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS

### Additional context

reports: 
https://discord.com/channels/873176416114585674/1027887126257356810
https://forum.audacityteam.org/viewtopic.php?f=47&t=127251&p=457009

One user reports: 

> And before install, I verified there were nothing in /Users/[ME]/Library/Application Support/

**Comment by LWinterberg** [comment]
Update: Restarting the computer worked for one user

**Comment by LWinterberg** [comment]
I haven't seen any reports about this since then. I guess it's just a strange system state causing this, I've put it into https://support.audacityteam.org/troubleshooting/error-codes anyway, but I don't think we need to work on this

**Comment by joeri00** [comment]
I have same issue with the latest version (23 jan 2023)

**Comment by LWinterberg** [comment]
well, did you restart your computer?

**Comment by joeri00** [comment]
Yes, after restarting it was solved.

Regards,

**Comment by sonicflame17** [comment]
I'm having the same issue. Running MacOS Monterey 12.4. Restarting the computer fixed it for the first run, but after I shut Audacity down and then started it again, it came back. Right now the only way I can restart Audacity is by completely rebooting my computer first.

**Comment by Javier-Lobo** [comment]
Same here.

macOS Monterey 12.6.8 (21G725)
Audacity x86_64 versions 3.2.5 to 3.3.3

<img width="420" alt="image" src="https://github.com/audacity/audacity/assets/47010069/4978fca6-1969-4874-b729-fefe2366c8e9">

**Comment by medikoo** [comment]
This issue is quite annoying, as it happens repeatedly (on my side, after single Audacity usage and quit, I no longer can open it)

As a workaround I never quit the Audacity, just close the projects. Before I was also resorting to run Audacity in Virtual Machine, but that's obviously not very efficient

**Comment by nexbridge** [comment]
I've started getting this as well, although only since I've changed laptop, in case that provides a clue.  I used to have a MacBook Pro (Intel) with Monterey, but now I have a MacBook Air (M2) with Ventura, if that helps.
