### ISSUE TITLE
scrolling left of zero can not be disabled

### ISSUE THREAD

**Issue by Sonicturtle** [audacity/audacity#3780]
### Bug description

In both 3.2.0 and 3.2.1, scrolling is permitted left of zero even if "enable scrolling left of zero" is not enabled in preferences.

### Steps to reproduce

1. record or import audio
2. click and drag the clip left of zero
3. Go into edit-preferences-tracks-tracks behavior
4. By default "enable scrolling left of zero" is not be checked, so step 2 should not have been possible
5. to verify, try checking and unchecking "enable scrolling left of zero." The track behavior will not change.

I found this in both 3.2.0 and 3.2.1

### Expected behavior

When "enable scrolling left of zero" is not checked, it should not be possible to slide a clip left of zero seconds

### Actual behavior

I am able to slide a clip left of zero seconds even when "enable scrolling left of zero" is not checked.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by LWinterberg** [comment]
Scrolling the viewport left of 0 is different from moving content left of 0. The preference affects only the former, so this all technically works as intended (and has been this way for years).

That said: This feature probably was more useful pre-3.1 to align tracks than it is now that non-destructive trimming exists.

**Comment by Paul-Licameli** [comment]
> Scrolling the viewport left of 0 is different from moving content left of 0. The preference affects only the former, so this all technically works as intended (and has been this way for years).
> 
> That said: This feature probably was more useful pre-3.1 to align tracks than it is now that non-destructive trimming exists.

But maybe it is useful too for recording latency corrections sometimes, to drag left a little bit. @SteveDaulton might comment more.
