### ISSUE TITLE
The user is asked to reset preferences even if they selected "Reset Preferences" in the install wizard

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3781]
### Steps to reproduce

1. Download the [3.2.1 installer](https://github.com/audacity/audacity/releases/tag/Audacity-3.2.1)
2. Run the installer
3. Check the checkbox "Reset Preferences"
4. Finish the installation and launch Audacity
5. Observe

### Expected behavior

No **Reset Preferences** confirmation dialog

### Actual behavior

<img width="670" alt="image" src="https://user-images.githubusercontent.com/70063970/194604223-4fd0e6fc-f18c-476c-99fe-0509d8293299.png">

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by dozzzzer** [comment]
Apparently, this confirmation dialog was added intentionally, though it seems redundant to me. 
WDYT, @Tantacrul ?

**Comment by Tantacrul** [comment]
I HATE this dialog. It utterly confused me the other day, when I came into contact with it for the first time. It is also really confusing.

I initially thought it was asking 'have you reset your preferences already?'

Agree with @dozzzzer!

**Comment by petersampsonaudacity** [comment]
I'm minded to agree with @dozzzzer amd @Tantacrul 

But I would probably opt for removing the option in the installation process - and retaining the offer on initial launch.

**Comment by dozzzzer** [comment]
Still the case in 3.4.2

**Comment by dozzzzer** [comment]
Tested
