### ISSUE TITLE
Errors in lastlog.txt

### ISSUE THREAD

**Issue by glennpc** [audacity/audacity#3782]
### Bug description

I'm seeing errors in the lastlog.txt every time I use Audacity.

### Steps to reproduce

Open Audacity, seems to run fine.
Then close it.
Check lastlog.txt

### Expected behavior

Not sure why I am getting these error messages.

### Actual behavior

Error messages.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

11:40:20: Audacity 3.2.1
11:40:20: sqlite3 message: (1) no such table: project in "SELECT 1 FROM project LIMIT 1;"
11:40:20: Error: Failed to load shared library 'avformat-59.dll' (error 126: The specified module could not be found.)
11:40:20: Error: Failed to load shared library 'avformat-58.dll' (error 126: The specified module could not be found.)
11:40:20: Error: Failed to load shared library 'avformat-57.dll' (error 126: The specified module could not be found.)
11:40:20: FFmpeg libraries loaded successfully from: C:\Program Files\Audacity\FFmpeg\avformat-55.dll
11:40:23: Using internal LAME
11:40:23: Error: Failed to load shared library 'avformat-59.dll' (error 126: The specified module could not be found.)
11:40:23: Error: Failed to load shared library 'avformat-58.dll' (error 126: The specified module could not be found.)
11:40:23: Error: Failed to load shared library 'avformat-57.dll' (error 126: The specified module could not be found.)
11:40:23: FFmpeg libraries loaded successfully from: C:\Program Files\Audacity\FFmpeg\avformat-55.dll

**Comment by glennpc** [comment]
Still getting this error with latest 64-bit version:

13:37:47: Audacity 3.3.1
13:37:47: sqlite3 message: (1) no such table: project in "SELECT 1 FROM project LIMIT 1;"
13:37:47: Error: Failed to load shared library 'avformat-60.dll' (error 126: The specified module could not be found.)
13:37:47: Error: Failed to load shared library 'avformat-59.dll' (error 126: The specified module could not be found.)
13:37:47: Error: Failed to load shared library 'avformat-58.dll' (error 126: The specified module could not be found.)
13:37:47: Error: Failed to load shared library 'avformat-57.dll' (error 126: The specified module could not be found.)
13:37:47: FFmpeg libraries loaded successfully from: C:\Program Files\Audacity\FFmpeg\avformat-55.dll

**Comment by zxf04040** [comment]
Same error suddenly happens on my Audacity with glennpc reported.
Audacity has worked previously.
Any changes were made??

**Comment by zxf04040** [comment]
Finally found, this is not something.
The severe problem is as using keyboard to input text or issue a command like Ctrl+W make Audacity hang.
So this error message is not something at the moment.
