### ISSUE TITLE
dpMeter VST3 plugin does not work

### ISSUE THREAD

**Issue by xnoreq** [audacity/audacity#3783]
### Bug description

dpMeter VST3 plugin does not work.

### Steps to reproduce

1) Install https://www.tbproaudio.de/assets/content/download/dpMeter5nogpu_Installer_WIN_522.zip
2) Start Audacity
3) Add a track
4) Add dpMeter5nogpu effect
5) Open dpMeter5nogpu effect
6) Play the track

The plugin also has a "SYNC" option that can be enabled but does not work.

### Expected behavior

1) Audio playback should not be mangled.
2) The plugin should show audio levels during playback of the track.
3) With the "SYNC" option enabled, the plugin should pause/resume monitoring whenever playback is paused/started in Audacity.

### Actual behavior

1) Audio is mangled.
2) The plugin only shows -inf (silence).
3) The "SYNC" option does nothing.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by dozzzzer** [comment]
Thanks for the report, @xnoreq !
I was able to reproduce this on Windows 11 & confirm all three issues are present.

**Comment by dozzzzer** [comment]
@vsverchinsky 

Testing on Windows 11 against PR https://github.com/audacity/audacity/pull/4119:

1. I hear no sound at all during the playback 
2. All plugin meters show silence (-INF)

**Comment by dozzzzer** [comment]
UPD: Downloading the plugin from the official site and re-installing it fixed the issue mentioned in the comment above.
