### ISSUE TITLE
Modal dialogs block all open projects

### ISSUE THREAD

**Issue by JC3** [audacity/audacity#3789]
### Bug description

When multiple unrelated projects are open and a time consuming operation is being done in one of them (e.g. resampling a track, exporting audio, compact on exit, etc.), interactions are disabled in all of the other project windows as well.

Presumably related to #3674 but who knows.

Generally speaking -- although I'm unfamiliar with Audacity's source -- it seems like most of this would be more well-behaved if each Audacity project window got its own process (on Windows, btw). I'm not really sure why they're all in the same process, I presume there is a reason (and I can only hope that the reason is better than "nobody felt like making globally unique mutex/event/shm/pipe names" or something, heh...). 

### Steps to reproduce

1. Open project A.
2. Open project B.
3. Do something time consuming in project A.
4. Try to do something in project B.

### Expected behavior

Project B's window should be unaffected by any actions being done on project A.

### Actual behavior

You can't work on project B while waiting for project A's operation to complete.

Being unable to do anything in other projects while waiting for, say, a 13-minute sample format change operation in project A to complete, or a 90 second compaction when closing project A, is kind of rough. So is being unable to start time consuming operations on multiple projects in parallel.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by hagom** [comment]
What happened with this feature? It is not going to be implemented?

**Comment by dozzzzer** [comment]
It isn't gonna be addressed in 3.6 but may still be addressed in the future.

**Comment by LWinterberg** [comment]
This is fixed in Audacity 4 ![Image](https://github.com/user-attachments/assets/d247c5a4-b407-41fd-840a-601093cf0b26)
