### ISSUE TITLE
Increase framerate of playback line

### ISSUE THREAD

**Issue by KonradHoeffner** [audacity/audacity#3791]
### Your idea

Increase the framerate of the playback line to the framerate of the monitor.

### Problem to be solved

On a Samsung G7 with 240 Hz, all movements are very smooth, except the Audacity playback line which looks like it is stuck at 60 Hz or even lower, so it looks very erratic and jumpy.

**Comment by LWinterberg** [comment]
This won't be fixed in the wxwidgets version of Audacity and won't be an issue in the Qt version
