### ISSUE TITLE
3.2.2 beta and 3.3.0 alpha fail to load Vamp plugins

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#3795]
### Bug description

3.2.2 beta fails to load the Queen Mary Vamp plugins - _see image 2_
3.3.0 alpha similarly fails

They are loaded fine and available from the Analyze menu in 3.2.1 - _see image 1_

3.2.2 beta fails to load the Vamp plugins if
a) you upgrade for 3.2.1, or
b) make a virgin install of 3.2.2 beta

### Steps to reproduce

1. Clear Audacity settings folder
2. launch 3.2.1
3. Analyze menu
4. Observe: Queen Mary Vamp plugins are available
5. Exit 3.2.1
6. launch 3.2.2 beta
7. Analyze menu
8. Observe: the QM Vamp plugins are not there
9. Analyze>Plugin Manger
10. Observe: the QM Vamp plugins are not there either 

### Expected behavior
**1) As in 3.2.1**
![image](https://user-images.githubusercontent.com/50205984/194911104-f2111fc6-64af-4217-bf70-0cd2e6927444.png)

### Actual behavior
**2)  as in 3.2.2 beta**
![image](https://user-images.githubusercontent.com/50205984/194911290-229e99e7-0008-448d-98f5-70d2882abcc9.png)

### Audacity Version
latest beta: audacity-win-3.2.2-beta-20221006+df0ffd2-x64-msvc2022
and latest alpha:  audacity-win-3.3.0-alpha-20221011+69764a4-x64-msvc2022

### Operating system
Windows 10

### Additional context
See also:   Crash editing Amplify (and some other effects) macro parameters #3769

**Comment by petersampsonaudacity** [comment]
### Additionally
why does the 3.3 menu after] an upgrade from 3.2.1 have duplicate entry for  **Beat Finder**

and an Entry "**Steve Daulton**" which duplicates **Label Sounds** and _Measure RMS_

![image](https://user-images.githubusercontent.com/50205984/194913080-12ff43fb-e839-4f65-a2c4-6a3b0a4c2d9f.png)

**Comment by Ryan-Miller-Audacity** [comment]
Hmmmmm Testing on Windows 10 with the official 3.2.1 release as well as the most recent 3.2.2 beta (https://github.com/audacity/audacity/actions/runs/3196194765) I did not see this behavior when following the steps provided. My Queen Mary VAMP plugins were still present and I did not see duplication of certain menu items like you described.

**Comment by petersampsonaudacity** [comment]
@Ryan-Miller-Audacity 

For clarity - as I said earlier, in particular in the STR, with 2.3.1 I _**DO**_  see the Queen Mary Vamp plugins.

_**BUT**_ when I launch latest 3.2.2 Beta or 3.3.0 alpha after running 3..2.1 I di _**NOT**_ see the Queen Mary Vamp plugins.

**Comment by Ryan-Miller-Audacity** [comment]
I think the beginning part of my previous comment is misleading. Following your STRs, I was unable to reproduce this behavior and properly saw the Queen Mary Vamp plugins after following the STR and opening the 3.2.2 app. 

Re the duplicates - I assumed this would be the case after following the STR as well? There's no additional steps needed to view that beyond the STR? Perhaps I misunderstood.

**Comment by petersampsonaudacity** [comment]
@Ryan-Miller-Audacity @LWinterberg @dozzzzer 

Testing on W10 with latest 3.2.2 beta:  audacity-win-3.2.2-beta-20221109+f0bb347-x64-msvc2022

This remains the case:
a) with 3.2.1 they still load fine and are available
b) with 3.2.2 beta - **_no_** Vamp plugins show in the Analyze menu

**Comment by LWinterberg** [comment]
re: duplication - that occurs when there are multiple installs of Audacity on different paths, #1381

re:this bug, I can't reproduce it either, the entire vamp plugin pack loads just fine for me
![image](https://user-images.githubusercontent.com/87814144/209131875-8aada7a4-d93f-4684-aa08-89ddfb1143e2.png)
