### ISSUE TITLE
EQ effects rename all clips

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#3796]
### Bug description
Use of either the Graphic Equalizer of the Filter Curves equalizer renames all the clips based on the track name.

### Steps to reproduce
1. generate a 30 second Chirp
2. Select from 10-20 seconds
3. Ctrl+I to split the chirp into 3 clips
4. rename the clips a, b and c
5. select the whole clip
6. Apply either of the EQ effects
7. Observe: the three clips are renamed, numerated based on the track name

### Expected behavior
**1) What it should look like after EQ**
![image](https://user-images.githubusercontent.com/50205984/195051750-11c86357-7889-46c1-8aee-4b347e082774.png)

### Actual behavior
**1) Before EQ**
![image](https://user-images.githubusercontent.com/50205984/195051021-a5b70d94-9b4f-4e16-a441-409ec3c173d0.png)

**2) After EQ**
![image](https://user-images.githubusercontent.com/50205984/195051460-0087beb4-d10b-486b-876e-e70cf45de4dd.png)

### Audacity Version
3.2.1  -  and latest 3.2.2 beta:  audacity-win-3.2.2-beta-20221006+df0ffd2-x64-msvc2022

This is **_not_** a regression - this issue has been present ever since Clip-name drag-bars were introduced in Audacity 3.1.0

### Operating system
Windows - but assume all OS

### Additional context
This is trivial in the STR use case - but for a user with a lot of named clips this would be disastrous.
And as such this should warrant a pretty high P-rating @LWinterberg @dozzzzer  - _it represents a loss of carefully placed user data._

**Comment by petersampsonaudacity** [comment]
Originally logged on the Forum's Russian section by user Ruslan
https://forum.audacityteam.org/viewtopic.php?f=10&t=127293

**Comment by dozzzzer** [comment]
I was able to reproduce this as well

**Comment by petersampsonaudacity** [comment]
@LWinterberg @crsib 

Testing on W10 with the latest 3.2.2 beta:  audacity-win-3.2.2-beta-20221109+f0bb347-x64-msvc2022

This remains the case 

I note from @Ryan-Miller-Audacity 's milestone modification from mid-October that fixing this has been put off till 3.3/3.3+
however this could result in a serious loss of carefully entered data by the user corrupting the valuable and important clip names in their project.  

Surely this should be being fixed sooner  @dozzzzer  thought it serious enough a month ago  to add a P2 status

**Comment by chuckkh** [comment]
Just a note that, with a few experiments I did, the renaming wasn't even sequential. It ended up : Bug 1 | Bug 2 | Bug if the track was named bug. Immediately before that, they were named A | Track | C, and I ran the Filter Curve EQ effect on all three clips.

**Comment by vsverchinsky** [comment]
@LWinterberg similar issue: clips created with Repeat effect get track's title in their names. Wouldn't it be better to preserve clip name instead?

**Comment by LWinterberg** [comment]
I think so, yes.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @vsverchinsky 's branch build from 5 days ago:  audacity-win-3.3.0-alpha-20230118+616d02c-x64

This now works fine on Windows, the clip names are preserved and not changed when using the EQ effects

**Comment by Ryan-Miller-Audacity** [comment]
Verified that EQ effects (Graphic EQ and Filter Curve EQ as well as a few VST3 EQs) no longer rename clips when applied to a track.

**Comment by petersampsonaudacity** [comment]
Tested on W10 with latest alpha:  audacity-win-3.3.0-alpha-20230126+d85b9bb-x64-msvc2022

I confirm that this now works fine with **Filter Curve EQ** and **Graphic EQ** in this latest 3.3.0 alpha
