### ISSUE TITLE
Add a skip option + timeout to plugin validation

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#3802]
<details>
<summary>original report</summary>
### Your idea

Make VST startup scan optional; perhaps with an entry manually added to .cfg file.

### Problem to be solved

Audacity crashes or fails to startup up due to apparently non-conforming VSTs.

### Additional context

Please read this this forum thread here: https://forum.audacityteam.org/viewtopic.php?p=456850#p456850
</details>

**Comment by LWinterberg** [comment]
The scanning process is designed so that plugins may crash without taking Audacity down in the process; the "incompatible plugins" dialog informs you about which plugins ended up crashing Audacity. If a plugin ends up crashing so hard that it also takes down the parent process somehow, it's a bug that needs fixing - not a hidden preference a user should be expected to find and manually set.

**Comment by JohnColket** [comment]
@LWinterberg, thanks for taking the time to reply.  I am afraid you totally missed the point.  You comments would be fine if the issue was crashing.  It is not.  Please see this discord issue from Steve:

https://discord.com/channels/873176416114585674/1027503779525951548/1027503779525951548

as well as these individual forum posts from 6 additional users:

from kevinwayne:
https://forum.audacityteam.org/viewtopic.php?p=457218#p457218

from JaySeb:
https://forum.audacityteam.org/viewtopic.php?p=457167#p457167

from confusionboats:
https://forum.audacityteam.org/viewtopic.php?p=456850#p456850

from _Mike:
https://forum.audacityteam.org/viewtopic.php?p=456759#p456759

from voshelley:
https://forum.audacityteam.org/viewtopic.php?p=456329#p456329

from vonshtickel:
https://forum.audacityteam.org/viewtopic.php?p=456669#p456669

**Comment by LWinterberg** [comment]
> Audacity crashes or fails to startup ...

> You comments would be fine if the issue was crashing.

?

From what I see from the threads you linked: 

* Audacity can freeze or crash when scanning plugins. This is a bug and would need fixing. 
* Some users have endless amounts of plugins on their system and would rather not use some/all of these plugins. While this is a fairly niche use case, it's true that the plugin manager is poorly equipped to manage, well, anything at scale. This may be improved in future releases

That said I'm still unsure what your point is.

**Comment by petersampsonaudacity** [comment]
And here's another one that posted just now on the Forum:
https://forum.audacityteam.org/viewtopic.php?f=47&t=127324&p=457355#p457355

**Comment by JohnColket** [comment]
@LWinterberg @Ryan-Miller-Audacity

 Thank you Leo.  My bad - as it turns out, this issue is not about crashing (which I opened this issue with).  The one user above (confusionboats) did mention crashing but later posted that 3.2.1 corrected the crashing, but it "scans forever". Jayseb gave up after a 3 hour scan. _Mike said 104 minutes and increasing. voshelly said the Time Remaining keeps increasing, and he gave up when it went over an hour. vonshtickel said over 100 hours! saintsandpoets mentions several exception reports and indicates it stalls out.

The point is several (eight and counting) regular Audacity users seem to be having serious problems with the automatic scanning and there doesn't seem to be a solution in sight for them.

I would be in favor of closing this issue in favor of a solution that addresses the problem, as you say,  "[the Audacity] plugin manager is poorly equipped to manage, well, anything at scale".

And thank you Ryan for adding this to the 3.2.2 milestones. 😄

**Comment by petersampsonaudacity** [comment]
When I first encountered the automatic scanning I too was alarmed at the long time at it took and the large number of effects I then had enabled in the effect and analyze menus.

For me the solution was simple - I merely removed the shed-load of plug-ins I had accumulated over the years in the name of QA testing, leaving only my favorite toy effect iZotope Vinyl (I just love that ol' "vinyl warmth").

But it means I feel the pain of those users who do not want all their plugins scanned and automatically enabled.

**Comment by JohnColket** [comment]
And yet another forum post, this one from wcreed51:
https://forum.audacityteam.org/viewtopic.php?p=457470#p457470

**Comment by JohnColket** [comment]
Add to the list jraoul:
https://forum.audacityteam.org/viewtopic.php?p=457734#p457734

**Comment by wpostma** [comment]
I am also able to reproduce this forever hang.  It sits on one plugin and never gives up on it.

**Comment by theirongiant82** [comment]
Adding additional impact statement: users with Universal Audio recording interfaces (e.g. the Apollo rack units) will all have the plug-ins installed on their Macs, but they may take their Mac laptops away from the studio for a while, perhaps to work on something in Audacity that doesn't require these plug-ins.  

Universal Audio interfaces are the hardware DSP powering these plug-ins, but the plug-ins themselves might be checking to see if the UA unit is plugged in at the time of testing / activation.  

Audacity 3.2.1 is hanging indefinitely at checking one such plugin, and since there is no 'skip' button I must either Stop or Cancel.

**Comment by theirongiant82** [comment]
I came back this morning after leaving it overnight.  12 hours. No progress.  I pressed "Stop" and I will be marking all of the UAD plug-ins as "Disabled" for now.

Here's a screenshot of what that list looks like in Audacity.  Note the pathnames start with !UAD/aufx/xxAU, which is not a real path.  The plug-ins in the "VST" folder are references to the real ones in the UAD collection.  Contact me if you need more detail.

<img width="1129" alt="Screen Shot 2022-11-06 at 11 15 03 AM" src="https://user-images.githubusercontent.com/91766093/200190415-4885bdc6-dce9-405b-badc-30eea1902a77.png">

**Comment by theirongiant82** [comment]
I would suggest that Audacity break out the plug-in validator into a separate process the way Logic Pro does, and monitor the child process for timing.  If it takes more than 10 seconds to validate a plugin, kill it and note the condition so the end user can decide how to handle it later.

**Comment by JohnColket** [comment]
> Adding additional impact statement: users with Universal Audio recording interfaces (e.g. the Apollo rack units) will all have the plug-ins installed on their Macs, but they may take their Mac laptops away from the studio for a while, perhaps to work on something in Audacity that doesn't require these plug-ins.

Here is another forum user, merrilyalice, reporting difficulties with Universal Audio interfaces: https://forum.audacityteam.org/viewtopic.php?p=458545#p458545

**Comment by petersampsonaudacity** [comment]
And another Forum user reporting the same:  
https://forum.audacityteam.org/viewtopic.php?f=47&t=127184&p=459034#p459034

**Comment by wpostma** [comment]
any need for logging?

**Comment by wpostma** [comment]
https://github.com/audacity/audacity/pull/3946  seems to fix. The skip feature works with at least the bad plugins on my system including LoopMix by AudioModern.

**Comment by dozzzzer** [comment]
Timeout doesn't seem to exist during scanning, MacBook M1 Pro
Build: [audacity-macOS-3.2.2-alpha-20221116+d88ba0e-universal](https://github.com/audacity/audacity/suites/9335755991/artifacts/439007215)
@vsverchinsky

**Comment by dozzzzer** [comment]
Build: https://github.com/audacity/audacity/actions/runs/3515244884
OS: macOS 13.0 (M1 Pro)

Scanning hangs on every 2nd or 3rd VST by **Soundtoys** and a bunch of others.
STR:
1. Get[ Soundtoys Trial Bundle](https://acct.soundtoys.com/demo/) and install all modules
2. Launch Audacity
3. Observe the scanning progress

Act.: the scanning starts to hand on every 3rd VST plugin by Soundtoys, i.e. the first plugin from the bundle, Crystallizer.vst, as well as the 2nd one, Decapitator.vst, pass with no issues, but the 3rd one - Devil-Loc_Deluxe.vst - hangs and throws an exception: https://sentry.audacityteam.org/share/issue/0e72537783cd446eaa4a64b2f83ce2b8/

**Comment by dozzzzer** [comment]
Build: https://github.com/audacity/audacity/actions/runs/3524759727
OS: macOS 13.0 (M1 Pro)

Scanning stops at one of the plugins (EchoBoyJr, AU version) 
STR:

1. Get[ Soundtoys Trial Bundle](https://acct.soundtoys.com/demo/) and install all modules
2. Launch Audacity
3. Wait till scanning reaches AUs
4. Observe the scanning progress

<img width="500" alt="image" src="https://user-images.githubusercontent.com/70063970/203854719-f270726f-e955-4757-bb90-e1dd32f7c1a1.png">

**Comment by theirongiant82** [comment]
> "that will close this issue" 

That remains to be seen and validated.  Has this fix been incorporated into the latest interim build ?  Or should we expect a formal 3.2.2 release?

**Comment by theirongiant82** [comment]
About a week ago, someone on the Universal Audio forum suggested that the developers of Audacity take a closer look at the code of another open-source DAW (Ardour) to understand how they solved this problem, as UAD plugins are working fine in that app.

https://uadforum.com/community/index.php?threads/audacity-3-2-x-has-real-time-non-destructive-plugin-support-it-does-not-work-with-uad-plugins-yet.59996/post-434152

*"Additionally if Audacity isn't using the official VST2 SDK (which I don't think they can and distribute the resultant binary) you might have issues surrounding that change out."*

**Comment by vsverchinsky** [comment]
> Has this fix been incorporated into the latest interim build ? Or should we expect a formal 3.2.2 release?

Would be great if you could try a build from the [PR](https://github.com/audacity/audacity/pull/3980/checks) and check if problem is solved for you, but if suggestion that the problem partly was caused by the crash report program is correct then test will not be complete since crash reporter is available only for binaries built from `release-*` and `master` branches.

**Comment by dozzzzer** [comment]
Verified on macOS and Windows 11.
