### ISSUE TITLE
Crash when calling any plugin destructively on macOS

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3806]
### Bug description

When calling an effect destructively, Audacity crashes immediately in most cases, while in other instances (e.g. with x42 Compressor) it's required to tweak a knobe to have it crash.

### Steps to reproduce

1. Call an AU/VST/VST3/LADSPA/LV2 effect from the main effect menu
2. Observe

### Expected behavior

No crash

### Actual behavior

Crash

### Audacity Version

**vsverchinsky:i3233-vst3-ui-fixes** branch
Build: https://github.com/audacity/audacity/actions/runs/3244638840

### Operating system

macOS

### Additional context

Debug report: 
[Audacity_dbgrpt-16477-20221014T113313.zip](https://github.com/audacity/audacity/files/9784556/Audacity_dbgrpt-16477-20221014T113313.zip)

Sentry log: https://sentry.audacityteam.org/share/issue/bb064ff03abc45908d7294140fb50f8c/

_Discovered while testing_ https://github.com/audacity/audacity/issues/3233

**Comment by crsib** [comment]
Hmm, this is not alpha, this is 3.2.2 targeted branch

**Comment by dozzzzer** [comment]
The bug can as well be observed in the latest release branch build: https://github.com/audacity/audacity/actions/runs/3243229534
