### ISSUE TITLE
Hovertext tooltips for recording and playback sliders no longer show the values

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#3810]
### Bug description
Now that the functionality of the Mixer toolbar has been incorporated into the Meter toolbars the hovertexts for recording and playback sliders no longer show the values as they did in the Mixer toolbar in previous versions of Audacity.

This is a regression on 3.1.3

### Steps to reproduce
1. launch 3.2.1 (or 3.3.0 alpha)
2. hover cursor over recording slider in the Recording meter
3. Observe: tooltip says "Recording Level"  -  _see image 1_
4. hover cursor over playback slider in the Playback meter
5. Observe: tooltip says "Playback Level"
6. Observe there is no indication of what the actual levels are

In contrast:
1. launch 3.1.3 or earlier
2. hover cursor over recording slider in the Recording meter
3. Observe: tooltip says "Recording Volume: x.xx"  -  _see image 2_

### Expected behavior
Recording and Playback levels to be shown in the hovertext tooltips for the recording and playback sliders in the Meter toolbars.

### Actual behavior
1) '''3.2.1'''
![image](https://user-images.githubusercontent.com/50205984/195868107-b6877437-68c0-49a9-a07d-dd878d234e43.png)

2) '''3.1.3'''
![image](https://user-images.githubusercontent.com/50205984/195867839-9a52a675-c0cd-4a5c-a286-df32f30e5ade.png)

### Audacity Version
3.2.1 and 3.3.0 alpha

### Operating system
Windows 10, but assume all OS

### Additional context
Originally reported on the Forum:
https://forum.audacityteam.org/viewtopic.php?f=70&t=127328&p=457389

Flagging @Tantacrul and @LWinterberg   as a UX issue

**Comment by vsverchinsky** [comment]
Fixed in #3696

**Comment by petersampsonaudacity** [comment]
@vsverchinsky  Vitaly, so will this make into the 3.2.2 maintenance release or will it have to wait until 3.3.0 ?

**Comment by vsverchinsky** [comment]
It's highly likely that it will make into 3.2.2 if there will be no objections, working on remaining issues from comments right now

**Comment by petersampsonaudacity** [comment]
@vsverchinsky Thanks Vitaly

**Comment by petersampsonaudacity** [comment]
@dozzzzer 

Testing on W19 with @vsverchinsky Vitaly's branch:  audacity-win-3.2.2-alpha-20221018+915aba6-x64

In this branch build@

a) the sliders on the Meter Toolbars now have the value of the current position

b) the tool-tip nicely updates when the slider is moved

![image](https://user-images.githubusercontent.com/50205984/196938888-86539936-5718-4bd5-a1d9-d55668bb69c7.png)

**Comment by petersampsonaudacity** [comment]
Testing on W10:  looks good on latest 3.2.2.beta:  audacity-win-3.2.2-beta-20221109+f0bb347-x64-msvc2022

Note that latest 3.3.0 alpha:  audacity-win-3.3.0-alpha-20221109+fe50013-x64-msvc2022
does **_not_** yet have thus merged in.
