### ISSUE TITLE
Source tarball for 3.2.1 is... weird

### ISSUE THREAD

**Issue by dvzrv** [audacity/audacity#3811]
### Bug description

The source tarball for 3.2.1 is a zip, containing a .tar.gz:

```
unzip -l Downloads/audacity-sources-3.2.1.zip
Archive:  Downloads/audacity-sources-3.2.1.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
 57115958  2022-10-05 16:56   audacity-sources-3.2.1.tar.gz
---------                     -------
 57115958                     1 file
```

I assume that was not intentional?

The previous release provided a .tar.gz tarball.

### Steps to reproduce

https://github.com/audacity/audacity/releases/download/Audacity-3.2.1/audacity-sources-3.2.1.zip

### Expected behavior

Source tarball contains files directly

### Actual behavior

Source tarball contains another tarball

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Linux

### Additional context

What is the difference between the generated .zip or .tar.gz from the auto-generated tarball that is created for the tag?

**Comment by crsib** [comment]
It was just a human error related to the specific release. This won't happen for 3.2.2
