### ISSUE TITLE
More VST effects lack UI on macOS

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#3823]
### Bug description

Commit 0097b9a3f476ca2fc33cc361cf1cd699d2699005 fixed the non-appearance of the user interface for the VST2 versions of Melda plug-ins on macOS.

But that fix caused other effects to have this problem.

### Steps to reproduce

1. In macOs, put this effect in a stack, VST 2 version:  https://dotec-audio.com/deegain.html
2. Open the dialog
3. Repeat with a Melda plug-in

### Expected behavior

Expect to see the graphical interface for both effects

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

**Comment by Ryan-Miller-Audacity** [comment]
Tested in Build from PR #3824. More VST effects are displaying properly (with UI) on MacOS including the specific one listed above. Melda plugins are still displaying properly as well. 

I also completed a brief check on windows and plugin windows look good there as well.
