### ISSUE TITLE
Disable the Edit button for macro commands that receive no parameters

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3825]
### Your idea

Some commands receive no parameters, such as Copy, Cut, etc.
For those we need to disable the **Edit** button since there's no editable parameters and having this button active makes no sense.
<img width="452" alt="image" src="https://user-images.githubusercontent.com/70063970/196698856-1b25d72f-43a6-4323-b4a6-d06ba99f368d.png">

### Problem to be solved

Some users are getting confused by the presence of this button which appears to be active.

**Comment by dozzzzer** [comment]
@petersampsonaudacity That's true, but I meant the other dialog, Macro Manager, where the button still appears to be active:

![image](https://user-images.githubusercontent.com/70063970/197522163-c489bc2d-9461-4043-919d-968cbc69a525.png)

**Comment by petersampsonaudacity** [comment]
> @petersampsonaudacity That's true, but I meant the other dialog, Macro Manager, where the button still appears to be active:

@dozzzzer indeedy - I was merely pointing out the inconsistency  ;-)
