### ISSUE TITLE
Color-coding  for Recording and Playback sliders which can be difficult to spot (in Light and Classic themes)

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#3827]
### Your idea
Now that the Recording and Playback sliders have been moved to the Recording and Playback meter toolbars, in the Light _(default)_ and Classic themes given that the sliders are gray on gray they can be difficult to spot, making them a poor visual cue.

This is less of an issue on the dark and High Contrast themes where they are light gray on dark gray or black respectively.

My suggestion is that the borders of the Recording and Playback meters be colored red and green respectively (to color-code with the Record and Play button icons:

**Meter Toolbars**
![image](https://user-images.githubusercontent.com/50205984/196735525-aa25d080-9a79-4ffd-bc1e-6b6c025dc70e.png)
Note that I also moved the sliders ever so slightly leftwards away from their hard-right default positioning in the meter toolbars, also to give them a little more visibility.

**PAS Toolbar**
Given that the Play-at_speed toolbar is also a playback toolbar then its slider icon should possibly also have the same green border for consistency:
![image](https://user-images.githubusercontent.com/50205984/196736376-e0a12d13-b7f8-4703-8a1c-c13d7359ad77.png)

### Problem to be solved
This issue surfaced on the Forum earlier this week.

Plus I ran some _(admittedly not statistically significant)_ tests,comparing older Audacity with its Mixer toolbar to the newer Audacity, with my "Mystery-Shopper" to see if she could easily spot them- she couldn't

### Prior art
Existing 3.2.x
![image](https://user-images.githubusercontent.com/50205984/196735386-aaa383a5-15c9-47c5-943a-1d054a5e4c8d.png)

### Additional context

Flagging @Tantacrul and @LWinterberg  as thus is a UX/GUI usability issue.

**Comment by Tantacrul** [comment]
Colour coding - extra especially with green and red is a little bit of a no-no for colour blindness. Are people reporting not being able to see the sliders? If so, we might do something else to make them more noticeable.

**Comment by petersampsonaudacity** [comment]
> Colour coding - extra especially with green and red is a little bit of a no-no for catering to those with colour blindness. 

An excellent point.  

But we do already color-code the Record and Play button icons and the play/record heads.

>Are people reporting not being able to see the sliders? If so, we might do something else to make them more noticeable.

Yes some are.

And note they are much easier to spot in dark theme:
![image](https://user-images.githubusercontent.com/50205984/196739089-f2f8ceea-d210-45a9-abea-8d4d774611a5.png)

**Comment by petersampsonaudacity** [comment]
Recent Forum post
https://forum.audacityteam.org/viewtopic.php?f=47&t=127380#p457652

This caused the users to revert to an earlier version of Audacity so that they could still have the more-obvious Mixer Toolbar with its sliders.

**Comment by petersampsonaudacity** [comment]
@Tantacrul 

Here's an example of a GUI with some nice clear obvios sliders that yoi May well recall Martin  ;-)

![image](https://user-images.githubusercontent.com/50205984/196747718-b55fa658-ae5d-4a24-aa66-6aa4063164c0.png)

**Comment by petersampsonaudacity** [comment]
See also this Forum thread:
**Sliders for Recording Level and Playback Level**
https://forum.audacityteam.org/viewtopic.php?f=70&t=127328

**Comment by LWinterberg** [comment]
We'll have a different solution in the Qt version
