### ISSUE TITLE
Can't maintain double-height upper tooldock when moving the Meter Toolbars adjacent to the Transport Toolbar

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#3829]
### Bug description
If you place the Meter Toolbars immediately adjacent to the right of the Transport Toolbar the the other toolbars (all double height) that were to to right of the Toolbar are placed by Audacity on a new double-height section in the upper tooldock.

It is then impossible to place any/all of these double-height toolbars to the right of the Meter Toolbars, rather Audacity only offers locations immediately to the left or right of the Transport Toolbar, disregarding the fact that there is easily sufficient space to the right of the relocated Meter toolbars,

### Steps to reproduce
1. Float both the Meter Toolbars - but do NOT resize them
2. move both the floated toolbars to the immediate right of the Transport Toolbar
3. Observe:  the double height toolbars are move to a new double-height block in the upper tooldock
4. now try locating any one of the double-height toolbars to right if the relocated Meter Toolbars
5. Observe: it can't be done

### Expected behavior
The user should be able to place their toolbars wherever they like provided there is sufficient space in the relevant tooldock.

**For example:**
![image](https://user-images.githubusercontent.com/50205984/196988895-f63b6554-7f81-4b2c-9cb5-d1b52227031b.png)

### Actual behavior
You can't move any of the double-height toolbars to the right of the single-height mete toolbar(s)
![image](https://user-images.githubusercontent.com/50205984/196981119-b1872175-b40d-4f90-81f8-f29f18995207.png)
You can, however move up the single-height Play-at-Speed Toolbar to the right  (or left)of the Meter toolbars.

### Audacity Version
3.2.1, 3.2.2 beta and 3.3.0 alpha

### Operating system
Windows 10 - but assume all OS

### Additional context
Flagging @Tantacrul and @LWinterberg as this is a UX/GUI issue

**Comment by petersampsonaudacity** [comment]
Further experimenting shows that this may be down to interaction between single-height and double-height toolbars. 

One can't place a double-height toolbar to the right of a single-height toolbar.

Also note that you can't move a single height toolbar to the left of a double-height one.  Try, for example to move meter toolbar(s) to the left of the Transport toolbar, and find you can't

**Comment by Tantacrul** [comment]
> Further experimenting shows that this may be down to interaction between single-height and double-height toolbars.

That's exactly what it is. It is annoying but we're not going to invest time in improving this UI and are instead going to conclusively solve them in the Qt UI.

**Comment by petersampsonaudacity** [comment]
> It is annoying WX widgets problem we couldn't get around. I think we shouldn't invest time in tackling this problem and should instead conclusively solve it in the Qt UI.

Fair enough - a longish wait though.  Darn WXwidgets!
