### ISSUE TITLE
The volume bar has been lost in the new build

### ISSUE THREAD

**Issue by samvoiceover** [audacity/audacity#3834]
### Your idea

I had Audacity stop playing back audio, but the sound bar was fluctuating and sound worked on other apps. It took downgrading to the older Audacity to see that somehow the sound bar had been pushed all the way to silent, which as a voice over actor I never do.  My audacity-savvy friend also noted that on the new version the sound slider is not as obvious and even he had a hard time finding it, actually I dont know if he even did find it. 

Macbook Pro M1 Monterey, Scarlett interface, Newest Audacity 3.2.1.

### Problem to be solved

Make playback volume searchable or visible.

### Additional context

I am not a tech person, I know how to use Audacity for what I do and need it for, which is why I reached out to the Audacity expert at the school I am taking voice over classes in, and the fact that even he had trouble figuring out why it was silent is testament to me that this should be made more obvious.  I almost gave up a high paying VO job because I couldn't edit my recordings without playback.

**Comment by petersampsonaudacity** [comment]
The functionality of the old Mixer Toolbar has been merged in the Recording and Playback meters.

If you examine those you will see that they now have sliders which enable you to control the amplitudes.
![image](https://user-images.githubusercontent.com/50205984/197331055-6c6f0240-e34d-4c6d-9c12-c6f4bcddbd76.png)

See this page in the manual: https://manual.audacityteam.org/man/meter_toolbar.html#recording
