### ISSUE TITLE
AppImage: Menu bar and several other UI elements remain light in dark theme

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#3837]
### Bug description

Some elements of the UI are themed according to the Desktop theme, and some by Audacity's theme selection. It is expected that when the Dark theme is selected in Audacity, and Audacity is  running on a dark theme desktop, the interface will display with a reasonable dark-theme look. Unfortunately in Audacity 3.2.1 / 3.2.2 AppImage, it is impossible for  users to achieve a reasonable dark theme look.

### Steps to reproduce

1. Enable a dark Desktop theme, such as Adwaita-dark (official Gnome dark theme), or Yaru-dark (official Ubuntu dark theme).
2. Launch Audacity and select the Dark theme  in Preferences
3. Close and restart Audacity

### Expected behavior

The appearance to look no worse than Audacity 2.4.2:

![aud242](https://user-images.githubusercontent.com/11681097/197506657-1fbe3d03-fbf5-4487-b4d8-d6870238188b.png)

### Actual behavior

The appearance looks worse than Audacity 2.4.2

![Aud322](https://user-images.githubusercontent.com/11681097/197506699-446ee6be-9ee2-4a0e-a7f4-b591e07cbdcc.png)

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Linux

**Comment by crsib** [comment]
Audacity 2.4.2 **was not an AppImage**. This simply cannot be a **regression**. 

AppImage has a certain set of limitations that are known and that have no workarounds that will work on every single possible Linux distribution.

**Comment by SteveDaulton** [comment]
I think it's a regression in the  sense that Audacity 3.2.1 AppImage is the only binary version of Audacity available for end users. While it's common for Linux distros to lag a bit behind upstream versions, most commonly used Linux distros only offer Audacity <= 2.4.2, so  the AppImage is the defacto "official" version of Audacity 3.x. Sometimes it's necessary to put yourself in the user's shoes.

**Comment by SteveDaulton** [comment]
Also, I'm not talking about "every single possible Linux distribution", I'm talking about the most commonly used Linux distributions with standard / official themes.

**Comment by crsib** [comment]
I don't think that Xubuntu is a popular Linux distribution TBH.

**Comment by SteveDaulton** [comment]
Which distro/version does the AppImage look good on?

**Comment by crsib** [comment]
3.2 AppImage is **usable** on a large set of Linux distros. There are UI different UI issues on different distro families. This is unlike the 3.0.3/3.1 AppImage, which was usable only on Ubuntu based distros. 

And contrary to what you say - there **are** other binary distributions too. For example, Flatpak and Snap.

**Comment by LWinterberg** [comment]
> most commonly used Linux distros only offer Audacity <= 2.4.2,

This is in the process of resolving itself. 

* Debian sid has 3.2.0: https://packages.debian.org/sid/audacity
* Ubuntu 22.10 has 3.2.0: https://packages.ubuntu.com/kinetic/audacity
* Fedoras are on 3.1.3: https://src.fedoraproject.org/rpms/audacity
* openSUSE Tumbleweed has 3.2.1: https://software.opensuse.org/package/audacity

**Comment by SteveDaulton** [comment]
> And contrary to what you say - there **are** other binary distributions too. For example, Flatpak and Snap.

Both of which had severe issues the last time I tried. Nevertheless, I'm testing for the benefit of the  Audacity Team, not for the benefit of Snapcraft, Flatpak, or PortableApps.

**Comment by LWinterberg** [comment]
this won't be fixed in the wx version and won't be an issue in the Qt version
