### ISSUE TITLE
Plugin scan dialog improvements

### ISSUE THREAD

**Issue by vsverchinsky** [audacity/audacity#3838]
1. Add `&Skip` button next to plugin name label
2. Convert plugin name label to ~multiline~ **elapsized** label, so that dialog does not grow horizontally and stays fixed 500px in width. 
3. Remove 'Remaining Rime'

UPD: no way to reliably wrap text (with breaks in the middle of the word) in wx

**Comment by Ryan-Miller-Audacity** [comment]
Tested via the build from PR #3850. Tested both initial scan as well as rescan.

1. Skip button is now included in plugin scan window and properly skips over plugins as clicked.
2. Plugin names are truncated properly and keeps the window display at a consistent 500px in width.
3. Remaining time counter has been removed from the dialog; elapsed time remains and works as expected.

Tested on Windows 10 and MacOS covering all plugin families.

**Comment by SteveDaulton** [comment]
> 1. Skip button is now included in plugin scan window and properly skips over plugins as clicked.


Testing with audacity-linux-3.2.2-x64.AppImage

Where is the "skip button"? Is it that line in the bottom right corner? It does not appear to be clickable.

![Screenshot_2022-12-09_16-35-34](https://user-images.githubusercontent.com/11681097/206749560-e309e7d8-9934-4f1c-915c-186bb2a62085.png)

Update: Yes it is clickable if the mouse pointer is in exactly the right place (it took a few attempts to activate it).

**Comment by DavidBailes** [comment]
> Where is the "skip button"? Is it that line in the bottom right corner? It does not appear to be clickable.

Here's dialog on Windows:
![image](https://user-images.githubusercontent.com/11887021/206751121-01248225-b4fa-45a8-8838-57726e042883.png)

(Skip button it top right)
