### ISSUE TITLE
Transport buttons don't react to touchscreen input at all

### ISSUE THREAD

**Issue by ell1e** [audacity/audacity#3841]
### Bug description

The transport buttons don't react to touchscreen input at all. This is kind of sad actually, because otherwise the UI works amazingly on small devices including my Linux phone(!!) but just because the basic play/record isn't usable at all, it just breaks the application anyway. It'd make an amazing recorder for on the run otherwise if just those buttons could be fixed to not work with only mouse clicks but also with touch taps.

### Steps to reproduce

1. Use any device with Linux and touchscreen (e.g. laptop with touchscreen)
2. Run a Wayland desktop, I tested with Phosh/Phoc but GNOME 3 Wayland session would likely also work
3. Launch Audacity and tap the transport buttons

### Expected behavior

Transport buttons (the big play/record/stop/forward/backward/... buttons) work, like any other UI element does

### Actual behavior

Transport buttons don't react

### Audacity Version

other

### Operating system

Linux

### Additional context

Audacity version: 3.2.1(FlatHub)

**Comment by LWinterberg** [comment]
Can you give some more info?

When you import a file or generate some audio, do all of these buttons and sliders work?
![image](https://user-images.githubusercontent.com/87814144/197517441-cdcd812f-853c-42fe-9e1c-34d73e58d693.png)

Additionally, can you input text into this guy?
![image](https://user-images.githubusercontent.com/87814144/197517626-36958461-4e27-4b05-a6c0-0c33ec6f0115.png)

**Comment by LWinterberg** [comment]
I'll close this, it we definitely won't fix this in the wxwidgets version. And a proper mobile version may come way down the line anyway

**Comment by ell1e** [comment]
Please don't make a separate mobile version though. Instead, make the regular version have a responsible UI with overflow menus (hamburger buttons) and such. Mobile versions have a long history of inexplicably missing half the basic functionality, lacking behind, wasting dev efforts for duplicating the entire UI, and many other bad practices.

**Comment by dozzzzer** [comment]
>  have a responsive UI with overflow menus
I still think it's a won't fix anyway for as long as there's wxWidgets. 
Once Audacity is migrated to QT, responsiveness will be addressed and it will be a whole other story then.
