### ISSUE TITLE
VST2: Effect's parameters get reset to the default values when playback starts or when re-opening the effect's window

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3842]
### Steps to reproduce

1. Open up a VST2 effect from the sidebar (e.g. BlueCat Chorus or [TAL Reverb 2](https://plugins4free.com/plugin/683/) )
2. Move one of the sliders to some value (e.g. Gain or Wet to minimum)
3. Load a preset where the slider you moved in the step above is set to a different value 
4. Start playback, or close/reopen the GUI

### Expected behavior

The effect's parameters remain unchanged

### Actual behavior

The parameters get reset to what was set at step 2. 

### Audacity Version

Win x64, macOS universal builds [from here](https://github.com/audacity/audacity/actions/runs/3312593613)

### Operating system

macOS, Windows

**Comment by dozzzzer** [comment]
@pietro68 FYI, the exact same behavior shows the destructive application of the effects: open an effect, tweak some controls, start preview, stop preview, start again - the controls get reset to the defaults.

**Comment by dozzzzer** [comment]
Also, please ignore my comment:
> When using effect's presets, the parameters stick when playing the track/re-opening the UI. The described defect can only be observed in the case of tweaking the parameters by hand.

After further investigation, it turned out that some effects (e.g. Fresh Air by Slate Digital) have their controls reset too when using presets.

**Comment by pietro68** [comment]
These are actually two separate bugs (considering repro step 4.) and they actually also happen using DeeGain. Debug print statements showed that:

a) when pressing play, VSTEffectInstance::ProcessInitialize will be called ant the passed settings will contain an outdated chunk and map of parameters

b) when hiding the gui and reopening, at some point VSTEffectInstance::RealtimeProcessStart will be called and the passed message will contain an outdated chunk and ParamsVector

**Comment by Ryan-Miller-Audacity** [comment]
Commit: https://github.com/audacity/audacity/commit/852a4b4de6cce99d549a33e974a83d38c923206a
GH job: https://github.com/audacity/audacity/actions/runs/3429017268
OS: Windows 10

Plugin: ValhallaDelay
This issue exists: No

Plugin: TAL Reverb-2
This issue exists: YES

Plugin: MCompressor by Melda Productions
This issue exists: YES

Plugin: MBandPass by Melda Productions
This issue exists: YES

Plugin: Chandler GAV19T by Plugin Alliance
This issue exists: YES

Plugin: Valhalla Supermssive
This issue exists: NO

Plugin: ValhallaPlate
This issue exists: NO

Plugin: TAL Reverb-3
This issue exists: YES
