### ISSUE TITLE
VST2: In plain UI mode, when tweaking different sliders, both the current and the previous one are moved together

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3855]
### Bug description

When in plain UI mode with the effect's power button turned off, dragging several sliders left and right one by one during playback causes the previously dragged slider to shift too.

### Steps to reproduce

1. Have some audio
2. Open a VST2 effect in the sidebar in plain UI mode
3. Turn the power button off for this effect
4. Start playback
5. Drag a slider left and right OR click within its range to make it jump to a certain value
6. Drag/click within another slider
7. Observe

### Expected behavior

Only one slider moves

### Actual behavior

Both sliders are moving: the one which you drag moves where you pointing, while the previous one jumps to an unpredicted value. If you keep dragging the same slider, everything works fine. Though, when you tweak each slider just once, you'll see the previous one jumping consistently.

https://user-images.githubusercontent.com/70063970/198054684-5593d79d-a517-49a4-b160-d859b8825344.mp4

### Audacity Version

other

### Operating system

macOS

**Comment by dozzzzer** [comment]
With PR #3900, the issue can no longer be reproduced.
Verified on macOS and Windows 10.
@Paul-Licameli @pietro68

**Comment by Ryan-Miller-Audacity** [comment]
I was able to confirm the same, sliders move independently of each other in VST Plain GUI in build from PR #3900. Tested on Windows 10.
