### ISSUE TITLE
VST2: Crash when mixing-and-rendering with an IEM plugin

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3857]
### Steps to reproduce

1. Have some audio
2. Select a VST2 [IEM plugin](https://plugins.iem.at/), like MultiEQ or MultiBndCompressor
3. Select the track
4. Mix and Render

### Expected behavior

No crash, the track has been mixed and rendered

### Actual behavior

Audacity crashes

### Audacity Version

https://github.com/audacity/audacity/actions/runs/3327725239

### Operating system

Windows

### Additional context

Debug report: [Audacity_dbgrpt-14168-20221026T172834.zip](https://github.com/audacity/audacity/files/9870977/Audacity_dbgrpt-14168-20221026T172834.zip)

**Comment by Ryan-Miller-Audacity** [comment]
@Paul-Licameli @dozzzzer @pietro68 FYI I have also reproduced this crash when mixing-and-rendering with Melda Plugins in the stack as well.

**Comment by dozzzzer** [comment]
Verified on macOS Ventura
