### ISSUE TITLE
Import / Export refactoring

### ISSUE THREAD

**Issue by AnitaBats** [audacity/audacity#3863]
Goals:
- Move generic UI out of `ExportPlugin` implementations
- Extract import/export code into `lib-import-export`, put implementations into `mod-*`
- Export should not use global state

Refactoring steps:

- [x] Preliminary work: cleanup and simplify interfaces (move `ChooseFormat` and `NewWaveTrack`, remove `ExportPlugins::mFormatInfos` etc.).
- [x] Eliminate dependency on `ProgressDialog`.
- [x] Extract `ExportFileDialog` from `GetFilename`.
- [x] Move dialogs invocation to caller side (`ExportMixerDialog`, `TagsEditorDialog` etc.)
- [x] Remove `AudacityMessageBox` from exporters and importers.
- [x] Plugin expose a list of parameter descriptions with their current values.
- [x] Do export using parameters passed as argument.
- [x] UI uses new export parameters API, eliminate `OptionsCreate`.
- [x] Extract `lib-import-export`
- [x] Run export in a dedicated thread.

**Comment by Paul-Licameli** [comment]
Can this issue have more explanation of the scope of the task?

I do not yet understand how this task relates the replatforming to Qt.  But I don't know enough about the thinking behind it.

**Comment by crsib** [comment]
Import/Export has major problems:

* UI is **extremely** tied to the processing. For example, `Import` returns `ProgressResult` which is insane. Implementations do not handle it carefully at all.
* Not only the current framework is stateful - it uses hidden **global** state with no way to access the state without the hacks. This makes any usage of the framework besides the menu items to be overcomplicated and error prone. 

In general, this task is not about helping the Qt migration, it is about making Import/Export to be manageable and usable. However, it is a must for the Qt migration.

The detailed decomposition is expected quite soon.

**Comment by ianalarina** [comment]
will be resolved in scope of #4317
