### ISSUE TITLE
VST2: Crash when playing the track with Blue Cat's Chorus (Mono)

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3864]
### Plugin

Blue Cat's Chorus (Mono)

### Plugin Format

VST2

<img width="600" alt="image" src="https://user-images.githubusercontent.com/70063970/198276905-29ee96ff-d692-43ef-9c3e-5bf421fabfab.png">

### Plugin source

https://www.bluecataudio.com/Products/Product_Chorus/#Download

### Steps to reproduce

1. Have a mono track
2. Select BC Chorus Mono in the sidebar
3. Hit the Space key

### Expected behavior

No crash

### Actual behavior

Crash with no option to send the report

### Audacity Version

https://github.com/audacity/audacity/actions/runs/3327725239

### Operating system

macOS, Windows 11

### Architecture

Apple Silicon (M1, M2, ...)

**Comment by Paul-Licameli** [comment]
Should be fixed in this build: https://github.com/audacity/audacity/actions/runs/3346486868
