### ISSUE TITLE
Add search option in Plugin Manager

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3865]
### Your idea

Adding an option to search by the plugin's name in the Plugin Manager dialog.

Adding an option to specify an additional path to scan Plugins

<img width="700" alt="image" src="https://user-images.githubusercontent.com/70063970/198307851-3cd5ab1b-98e0-4599-a7ca-55aae0db399b.png">

### Problem to be solved

Will make the navigation in the list of plugins easier, especially when having dozens or even hundreds of them.

**Comment by petersampsonaudacity** [comment]
@dozzzzer  you can already type the first letter or first few letters of the plugin you want to access in the plugin manager

**Comment by dozzzzer** [comment]
Indeed. What a discovery! Thanks for pointing out, @petersampsonaudacity

**Comment by petersampsonaudacity** [comment]
> @dozzzzer you can already type the first letter or first few letters of the plugin you want to access in the plugin manager

Hopefully one should be able to type the middle or end part of the plugin and not just be restricted to searching based on the initial characters.

**Comment by petersampsonaudacity** [comment]
I added Tip divs to the Plugin Manager and the Macro Manager pages in the alpha manual for these selection Easter-Eggs
a) https://alphamanual.audacityteam.org/man/Manage_Effects,_Generators_and_Analyzers#Enabling_and_disabling
b) https://alphamanual.audacityteam.org/man/Manage_Macros#insert

**Comment by DilsonsPickles** [comment]
> @LWinterberg @jessjwilliamson @DilsonsPickles guys, feel free to work out the UI/UX

@dozzzzer do we currently have any search bars being used in WX?

**Comment by dozzzzer** [comment]
@DilsonsPickles No, I don't think so

**Comment by DavidBailes** [comment]
> do we currently have any search bars being used in WX?

I'm not sure I fully understand the question, but in the keyboard category of preferences, there's a search box.

**Comment by DilsonsPickles** [comment]
![PluginSearch_00](https://user-images.githubusercontent.com/111350316/199263062-a38c0e75-a3c6-44f8-8cf5-51577340d594.png)
![PluginSearch_01](https://user-images.githubusercontent.com/111350316/199263158-d5d6c0f0-89df-4663-9e83-05cfce5623f3.png)
![PluginSearch_02](https://user-images.githubusercontent.com/111350316/199263183-7d257f0a-cb92-4cc2-837f-946e36575fed.png)
![PluginSearch_03](https://user-images.githubusercontent.com/111350316/199263212-ab07e975-9436-4c56-92cb-34086745f200.png)

**Comment by petersampsonaudacity** [comment]
Ooh - that looks nice

Apart from the added Search the GUI is much prettier.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @vsverchinsky 's latest branch build for this

You have a small typo Vitaly - it should say Di**s**abled

![image](https://github.com/audacity/audacity/assets/50205984/f6fad79c-d746-4d42-b242-cca9b680a901)

**Comment by LWinterberg** [comment]
If the list right underneath says "Type: Audacity", the filter for it should be "Audacity Effects" / "Audacity Commands" instead. I don't mind the path continuing to say "Built-in Effect".

**Comment by petersampsonaudacity** [comment]
And indeed the un-hyphenated "builtin" in the Type dropdown is inconsistent with the hyphedated "built-in" in the Path listings in the dialog:

![image](https://github.com/audacity/audacity/assets/50205984/1950f9e3-8d8c-402a-a57c-44d4dafdc79d)

**Comment by petersampsonaudacity** [comment]
@LWinterberg 

Hi Leo, does the "Builtin Commands" in this dialog mean that you have plans to enable/disable menu commands at some stage ?

**Comment by LWinterberg** [comment]
> Hi Leo, does the "Builtin Commands" in this dialog mean that you have plans to enable/disable menu commands at some stage ?

No, it's just there by mistake. I have no plans on making menus customizable (outside of perhaps a "favorite effects" section)

**Comment by petersampsonaudacity** [comment]
Tested on @vsverchinsky 's latest test branch for this:   audacity-win-3.5.0-alpha-20240220+8603999-x64

All looks good to me now:

![image](https://github.com/audacity/audacity/assets/50205984/6df02982-ceea-43c4-9956-cdd6498ab0b6)

![image](https://github.com/audacity/audacity/assets/50205984/c430ff2f-679c-419a-9491-02ee6ee7cb05)

_I have added a P1 to the Manual to remind me to update the page once this makes its way to master._

**Comment by petersampsonaudacity** [comment]
Note that when you press the **Rescan** button, once the scan had finished all the EGATs in the dialog window are grayed-out

![image](https://github.com/audacity/audacity/assets/50205984/640309cb-8fc4-459f-9fbd-988d90050dfb)

a) Clicking any one of them will remove the graying-out

b) scrolling shows that it is only those on-screen in the dialog during the rescan that get grayed-out

**Comment by petersampsonaudacity** [comment]
I do find myself liking the **Search** function - _I agree it's much more "discoverable"_

**Comment by DavidBailes** [comment]
@LWinterberg @vsverchinsky 
Changing from using a wxListCtrl to wxDataViewCtrl has introduced a number of accessibility issues. I'm not sure how much has been gained by this change. For mouse users it's easier to change whether a single plugin is enabled/disabled, but maybe now not as obvious how to quickly change this for a number of selected plugins. However I guess that decision has been made.

This is an initial list of issues.
Keyboard accessibility issues:
1. You can no longer use first letter navigation in the list. (I know you can now search, but first letter navigation is still useful - you can do this in shortcuts preferences, where there is also a search).
2. With the focus in the list, pressing Tab doesn't move the focus to the Rescan button, it "moves" you through the cells in the table. Similarly, pressing Shift + Tab move the focus to the Search text box.
3. Pressing left/right arrow "moves" you through the cells in the row. It would be better if these keys did nothing, as if a cell other than the Enable is the "focus", pressing spacebar does not toggle the checkbox.
4. Rescan needs an access key.

Screen reader accessibility issues:
1. Screen readers don't read the table properly. wxDataViewCtrl does in fact have a default accessible object for it - see wxWidgets code: src\generic\datavgen.cpp. However this won't be good enough as it doesn't work properly for the Narrator screen reader. Also, having the enable status read out last is far from desirable.
2. When the user presses Spacebar, I don't think any Focus or name change events are created, so screen readers won't be able to give any feedback of the changed state. I'm not familiar enough with the wxDataViewCtrl class to know whether the appropriate event creation can be added in Audacity code, or whether a patch for wxWidgets will be needed.

**Comment by petersampsonaudacity** [comment]
@LWinterberg @vsverchinsky @DavidBailes 

>You can no longer use first letter navigation in the list. (I know you can now search, but first letter navigation is still useful - you can do this in shortcuts preferences, where there is also a search).

Another oddity:
In the search box for some EGATs a single letter will suffice in the search box - for example w for Wahwah or a for Amplify

BUT for some others two letters are required - e.g; l will not scroll the loudness Normalization but lo does.  Silarlarly repair 

I have not explored the whole EGAT set for a full analysis

**Comment by petersampsonaudacity** [comment]
@LWinterberg @vsverchinsky 

@DavidBailes wrote:

>2. With the focus in the list, pressing Tab doesn't move the focus to the Rescan button, it "moves" you through the cells in the table. Similarly, pressing Shift + Tab move the focus to the Search text box.
>3. Pressing left/right arrow "moves" you through the cells in the row. It would be better if these keys did nothing, as if a cell other than the Enable is the "focus", pressing spacebar does not toggle the checkbox.

Indeed the Tab behavior seems most odd, I would expect it to move from the Table to the action buttons.

Personally, I would not want to lose the up/down arrow actions of moving you through the table.

**Comment by DavidBailes** [comment]
> Personally, I would **_NOT_** want to lose the up/down arrow actions of moving you through the table.

I was referring to left/right arrows, not up/down arrows. As an alternative to the left/right arrows doing nothing, then they could just double up with the up/down arrow actions, eg pressing either down arrow or right arrow moves to the row.

**Comment by petersampsonaudacity** [comment]
> there appears to be no segregation (searchability) by EGAT type - everything seems to be an "Effect".
> 
> There is no ability to search for Generators, Analyzers or Tools - or even identify which are which.

There could be an argument for
a) Effect > Plugin Manager - showing and managing only effects
b) Generate > Plugin Manager - showing and managing only generators
c) Analyze > Plugin Manager - showing and managing only analyzers
d) Tools > Plugin Manager - showing and managing only tools

But that would lose the ability to manage the whole EGAT set in one go - unless a separate command was provided for that purpose.

**Comment by vsverchinsky** [comment]
@DavidBailes @petersampsonaudacity Thanks for the feedback, I'll try to fix accesibility issues you've metioned. I don't know for what reason but when I first time tried keyboard navigation with `wxListCtrl`, it behave exactly same way as `wxDataViewCtrl` did for me, but now when I press TAB it indeed navigates between rows not cells...

> I also note that search is based not just in the Name filed but also the Path and even Type fields.

Yes. @LWinterberg that's how I interpret "identical to the one preferences", is that desired behavior?

> but this can either change all of them to enabled or disabled depending on something I haven't be able to figure out

Depends on the state of the current (active) item. Usually it's the one that was last clicked or navigated to via keyboard.

**Comment by DavidBailes** [comment]
> > but this can either change all of them to enabled or disabled depending on something I haven't be able to figure out
> 
> Depends on the state of the current (active) item. Usually it's the one that was last clicked or navigated to via keyboard.

@vsverchinsky . Thanks for this explanation. But I think it was simpler when the user could simply press an enable or disable button, rather than the change of state of all the selected plugins depending on the initial state of the focused plugin.

**Comment by vsverchinsky** [comment]
@DavidBailes I think I've managed to address issues you mentioned with NVDA screen reader, but not with windows build-in narrator. Didn't test it on other OS's, so other changes may follow.
@petersampsonaudacity search now filters only by name column

**Comment by petersampsonaudacity** [comment]
@LWinterberg @vsverchinsky 

**Stereo to Mono** is wrongly listed as an Audacity effect in this new Plugin Manager
![image](https://github.com/audacity/audacity/assets/50205984/52cf2e65-c595-4dec-8f6f-ddc1863a25e8)

In fact it is **_not_** an effect but rather a menu command.

Disabling it from here in the Plugin Manager removes it from the Tracks > Mix submenu
![image](https://github.com/audacity/audacity/assets/50205984/201b1507-f3a0-4ea2-9e83-77199a8bba9c)

**Comment by dozzzzer** [comment]
> does this need logging as a new bug ?

I'd say this certainly does

**Comment by dozzzzer** [comment]
@petersampsonaudacity thanks!

**Comment by DavidBailes** [comment]
> @DavidBailes I think I've managed to address issues you mentioned with NVDA screen reader, but not yet with windows build-in narrator. Didn't test it on other OS's, so other changes may follow.

@vsverchinsky . Thanks for the keyboard changes. With respect to screen readers, I forgot to mention that Jaws doesn't read the description property by default. So everything needs to be in the name, with nothing in the description. Also, I probably wasn't clear enough, but the screen reader should read the contents of all four columns, but with the 4th column read after the first column, eg "Amplify enabled Audacity Built-in Effect Amplify".
There's also a "focus" problem - to see this, select a item in the list other than the first item, press Tab, then Shift + Tab to return to the list. The screen reader does not read the selected item.
I'm going to have a look at the focus problem, and will hopefully get back to you within a day or two.

**Comment by DavidBailes** [comment]
> @vsverchinsky . Thanks for the keyboard changes. With respect to screen readers, I forgot to mention that Jaws doesn't read the description property by default. So everything needs to be in the name, with nothing in the description.

@vsverchinsky . I've since seen that you're using value rather than description for the enabled/disabled, my mistake. However, as both Jaws and Narrator are not reading this, the conclusion remains the the same - using the name for all four columns, and then having a name change event when the enable status changes.

**Comment by DavidBailes** [comment]
@vsverchinsky . Some more focus problems.

1. Do any one of the following: a) set show to disabled, b) set Type to anything apart from all or audacity effects, c) Enter some text in the Search box.
2. Tab to the list of plugins. The list becomes the " screen reader focus", not one of the items.
3. Press down arrow. The list remains the focus, so no plugin name is read out.

(It's easy to see where the screen reader focus is if you're running narrator. And just in case you don't already know, you can monitor focus events (and others) using the accevent program (on my computer it can be found at "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\accevent.exe" ) )

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @vsverchinsky 's latest branch build:   audacity-win-3.5.0-alpha-20240227+067c5e1-x64

The list of EGATS is still **NOT** in strict alphabetical order - rather it has alphabetically ordered subsections.
Please see my comments in earlier posts in this thread for more details.

a) This makes it harder to use.

b) It is not really necessary as the user can filter by Type to see the subsections.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @vsverchinsky 's latest branch build: audacity-win-3.5.0-alpha-20240227+95f0559-x64

That looks better to me now with proper alphabetic ordering.

![image](https://github.com/audacity/audacity/assets/50205984/88a7061a-f69e-4196-9105-3f20108f6211)

**Comment by vsverchinsky** [comment]
@DavidBailes 
> but with the 4th column read after the first column, eg "Amplify enabled Audacity Built-in Effect Amplify".

I guess we should skip "Path" column for those plugins that display actual path on disk, right?

**Comment by DavidBailes** [comment]
> I guess we should skip "Path" column for those plugins that display actual path on disk, right?

No, I would always include the "path" column, otherwise they won't be able to access that information. They can always press Ctrl to shut the screen reader up to stop if from reading all the path.

**Comment by DavidBailes** [comment]
@vsverchinsky . Thanks for your latest commit: [a724c8f](https://github.com/audacity/audacity/commit/a724c8fee627e346e433dbe84607626e4a66c225)

Remaining issues:
1. In the accessibility name, the name of the plugin seems to be the last section of the path, rather than the name shown in list.
For example:
![image](https://github.com/audacity/audacity/assets/11887021/1e333833-3944-4723-b156-8c8c385fc615)
In the accessibility name, the name is fil4#mono, rather than 4 Band Parametric EQ Mono.

2. In the accessibility name could you add a comma between the type and the path, otherwise it's not clear where one ends and the other starts when read by the screen reader. I did this in the accessibility name of the NumericTextCtrl to aid comprehension:
```
*name = mFieldValueStrings[field - 1] +
        wxT(" ") +
        label +
        wxT(", ") +     // comma inserts a slight pause
        mCtrl->GetString().at(mDigits[childId - 1].pos);
```

3. Minor existing issue. In void PluginRegistrationDialog::PopulateOrExchange(ShuttleGui &S), could you change the name in the constructor of the pluginsList from "Plugin List" to just "Plugin". This will stop screen readers saying plugin list list.

**Comment by vsverchinsky** [comment]
@DavidBailes Thanks! Fixed
@petersampsonaudacity @LWinterberg @DilsonsPickles added filtering by effect categories.
![изображение](https://github.com/audacity/audacity/assets/20165230/7cef5ed4-6f40-4658-9f61-fda333892dbd)

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @vsverchinsky 's latest branch build for this:  audacity-win-3.5.0-alpha-20240229+0df2b93-x64

I see we now have an additional filter for Category (type of EGAT)

The cute thing is that the default setting you get for Category depends on the way you get to the Plugin Manager, so coming for **Effect>Plugin Manager** will default to Category **Effect** and similar for the other EGAT categoiesy.

_I just hope that users are curious enough to explore the Category filter and realize that there is still an **All** category choice._

**Comment by DavidBailes** [comment]
> @DavidBailes Thanks! Fixed

@vsverchinsky . Thanks for the fixes. You probably don't want to hear this, but there is a bug in the first letter navigation. If there are no more items starting with the the letter below the current item, it should try and match starting from the top of the list. For example if there are three items in the list beginning with d, if you press d repeatedly it should cycle round all three items as long as you keep pressing the letter d. It's useful, because whatever item is the initial focus, pressing a letter will always find the items beginning with that letter.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @vsverchinsky 's latest branch:  audacity-win-3.5.0-alpha-20240306+c6c5a1c-x64

a) The cycling based on initial letter now seems good

b) if you are lower in the list that the first letter you type it will go back and find the EGATs starting with that letter

-------------------------------------------------------------------------------------------------

But I observe a small oddity with the alphabetic ordering of the list.

A couple of my VST/VST3 plugins are out of order at the bottom of the list.  This does not appear to be a VST/VST3 problem per se  as I have other VST/VST3 plugins further up the list which are in the correct alpahbetic order.

![image](https://github.com/audacity/audacity/assets/50205984/1f523594-a499-45a2-951f-4875fb860680)

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @vsverchinsky 's latest branch for this:  audacity-win-3.5.0-alpha-20240311+dcc70d2-x64

The alphabetic ordering now properly ignores case:
![image](https://github.com/audacity/audacity/assets/50205984/7d7a5ce7-43a4-432a-a832-9ca9b3701de0)

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @vsverchinsky 's latest branch build for this:  audacity-win-3.5.0-alpha-20240314+cfb3b3a-x64

The list of **Types** has had "effects" trimmed from them as per @LWinterberg 's request
And "Native Audacity" is there for Audacity supplied EGATS (thanks for that)

![image](https://github.com/audacity/audacity/assets/50205984/aa631c58-f281-4553-b4da-1d47e8dece96)

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @vsverchinsky 's latest branch build for this:  audacity-win-3.5.0-alpha-20240314+cfb3b3a-x64

In the PR thread for this @LWinterberg requested that in the Type field we should lose the term "effect" from the type listings as not all EGATs are effects.  And this is now done as reported above.

**BUT** in the EGAT lists the non-effect EGATs show as "Built-in Effects" in their path listing:

![image](https://github.com/audacity/audacity/assets/50205984/d451ca4e-29cc-4d3c-92ef-fedb5a67ca26)

**Comment by LWinterberg** [comment]
> BUT in the EGAT lists the non-effect EGATs show as "Built-in Effects" in their path listing

Possibly related to #1547 - I'd want to fix those two issues separately from this PR.

**Comment by petersampsonaudacity** [comment]
> Possibly related to #1547 - I'd want to fix those two issues separately from this PR.

@LWinterberg 

Plus one to that.

_I'm keen to see this change get into 3.5.0 - it is SO much better that the previous dialog we had for managing EGATs._

**Comment by petersampsonaudacity** [comment]
> but I can't really do that till this new dialog hits master or 3.5.0 Beta

@LWinterberg 

Actually this issue of wrongly path-naming generators and analyzers as "effects" is also present in the current version of Audacity (and earlier versions) so I will go ahead and log it.  And them trim this thread accordingly.

It's just more immediately obvious in the new version with the Type filter.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @vsverchinsky 's latest branch build for this:  audacity-win-3.5.0-alpha-20240320+4f4b2e0-x64

@LWinterberg @dozzzzer @Tantacrul @DilsonsPickles 

From a user and usability perspective all seems fine but with one small oddity/niggle - and that is the behavior of the space-bar shortcut with multiple selections (basically it acts as a toggle).

a) If you select a single EGAT in the displayed list and press the space-bar it toggles the enabled/disabled status of that selected EGAT.

b) If you make a selection of multiple EGATs in the displayed list (with Shift or Ctrl modified selection) and press the space-bar it toggles the entire selection based on the status of the **last** EGAT that you select- rather than toggling the status of each individual EGAT list based on its current status (and it is topmost not the first one you select).
Is this intended and desired behavior ?   
Is it what a user would expect ?  I would have thought that most users would expect a toggle of existing status for all selected EGATs _(my "Mystery-Shopper" thought so too when I ran this past her)_.

-----------------------------------------------------------------------

STR
1. Effect > Plugin Manager
2. set Type filter to native Audacity
3. Observe:  Classic Filters is the only disabled entry
4. Click on Classic Filters to select it
5. Ctrl+Click on Auto Duck and Bass&Treble to select those too
6. Press the space-bar: 
7. Observe all three become un-selected i.e. Classic Filters does _**not**_ toggle
