### ISSUE TITLE
Ditch macOS-specific button styles

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#3868]
The themes currently have two families of button backgrounds: The ones used on Windows and Linux, and a different one that's used on macOS. The latter ones are styled after (Probably) Mac OSX Lion's native buttons, so they don't match anymore *anyway*.

Thus, the idea is to use the windows/linux version of the buttons on macOS too, by simply updating the images in lib-theme-resources. This isn't technically ideal as there will be some duplicate images, but hopefully acceptable for the time being.

Resolves: https://github.com/audacity/audacity/issues/1783

**Comment by dozzzzer** [comment]
Tested
