### ISSUE TITLE
Toggle for sharing visibility

### ISSUE THREAD

**Issue by AnitaBats** [audacity/audacity#3884]

**Comment by DilsonsPickles** [comment]
Figma project file can be found [here](https://www.figma.com/file/L6v5zVmxOMzs4buZM6ladI/10_WX---Share-audio?node-id=30%3A761).

**Comment by DavidBailes** [comment]
> Figma project file can be found [here](https://www.figma.com/file/L6v5zVmxOMzs4buZM6ladI/10_WX---Share-audio?node-id=30%3A761).

Can this file be made viewable by anyone?

**Comment by dozzzzer** [comment]
The share audio dialog doesn't remember the previously selected option, i.e. every time a user tries to share audio, they end up seeing the "Public" option selected by default, not the option they selected when uploading last time.

<img width="349" alt="image" src="https://user-images.githubusercontent.com/70063970/206421447-64f682ad-e763-4bad-ad1f-0cc0fa1dc71d.png">

**Comment by DilsonsPickles** [comment]
It should yes, this was included in the spec document as seen below: 

![image](https://user-images.githubusercontent.com/111350316/206427842-ee4d94fe-546d-41a9-b3be-fb348666e9de.png)

**Comment by crsib** [comment]
Sorry, missed that
