### ISSUE TITLE
VST2: Change structures for settings and messages

### ISSUE THREAD

**Issue by pietro68** [audacity/audacity#3887]
Some plugins give problems when enumerating parameters by strings. Enumerate them by numerical ID instead.

Replace the current:
std::map<wxString, std::optional<std::pair<int,double> > > mParamsMap;

With two members:

- a `std::unordered_map<wxString, optional<double>>` for **saving and loading of settings**
- a  `vector<optional<double>>` for **messages**        

With the above, `CopySettingsContents` can simply be a no-op now

**Comment by Paul-Licameli** [comment]
Closing as a duplicate because the changes will be incorporated into #3900 which also fixes issues #3899 and #3855 with user-visible consequences
