### ISSUE TITLE
Plugin with latency - some playback commands don't exit playback

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#3897]
### Bug description

The commands affected are listed in the steps to reproduce.
I have only tested this using one plugin which has some latency: https://www.voxengo.com/product/latencydelay/, but I presume other plugins with latency will be affected.

### Steps to reproduce

1. Create a track with some audio.
2. Add the latency delay effect to the track: https://www.voxengo.com/product/latencydelay/, which has a latency of 10000 samples
3. Use any of the following playback commands commands:
- Transport > Playing > Play once/stop
- Extra > Transport > play one second (1), play to selection (B) , play before/after....
- Extra > Play at speed > play at speed once

### Expected behavior

Playback as expected, and audacity exits playback state.

### Actual behavior

When playback reaches the point where you would expect playback to stop, the playback cursor jumps backwards and then stops moving, and then Audacity remains in the playback state.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

### Additional context

See also: https://github.com/audacity/audacity/issues/3616

This bug has been present since 3.2.0

**Comment by ianalarina** [comment]
duplucates the issue #3651
