### ISSUE TITLE
Compressor processes wrong audio selection in second clip on second track

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#3903]
### Bug description

Forum user LeoFlash726 has reported the compressor is chopping out pieces of audio here: https://forum.audacityteam.org/viewtopic.php?p=458591#p458591 and he has supplied screeshots here: https://forum.audacityteam.org/viewtopic.php?p=458591#p458591

As the screenshots are a little tricky to follow I have tried to illustrate the issue with slightly easier steps to follow below.

### Steps to reproduce

1) Start Audacity
2) Tools > Reset Configuration
3) Transport > Recording > Record
4) Make an approximately 7-second recording of yourself reciting the counting numbers from one to as far as you get comfortably in seven seconds.
5) Track Control Panel > Split Stereo to Mono
6) "x" delete the second track.
7) Ctrl-A, Effect > Amplify and compression > Amplify the track so you can see it.
8) Tracks > Add New > Mono Track
9) On the first track, click near the one-second mark, then Edit > Audio Clips > Split (Ctrl-I)
10) Drag the second clip directly down to the second track, then roughly align the left edge of the clip with the 3-second mark.
11) Ctrl-A, Transport > Playing > Play/Stop (so you know what it sounds like: 1, silence, 2,3,4,..10 etc.).
12) Effect > Volume and Compression > Compressor > Apply
13) Ctrl-A, Transport > Playing > Play/Stop
14) Hear (1, silence, 7,8,9,10,7,8,9,10)

15) Note that the last 3 seconds of audio remains unprocessed.
16) Curiously, if you go back to step 10 and align the left edge of the clip with the 2-second mark, then the last two seconds of audio remain unprocessed.

### Expected behavior

(You should hear: 1, silence, 2,3,4,5,6,7,8,9..)

### Actual behavior

(You hear 1, silence, 7,8,9,10,7,8,9,10)

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

This seems to be a regression on 3.0.5 that somehow crept into 3.1.0 and beyond (currently 3.2.1)

This issue may be related to https://github.com/audacity/audacity/issues/1687

**Comment by JohnColket** [comment]
Thank you. I ran my most recent test on the Audacity 3.2.2-beta-20221129 nightly build to confirm the problem is still preset, and yes, the problem is still present.

Other than just recording a mono track to begin with, I wasn't sure how to simplify the steps. And the videos are confusing to say the least.  So I changed the steps slightly: instead of recording 1, 2, etc., I now recorded 1, 12, 123, 1234, etc. so the picture is more illustrative.

Here are the pictures of before and after running the compressor:
![Window011](https://user-images.githubusercontent.com/76828213/205338324-adb4b805-ddca-4772-bf2b-c87b50e3fba4.png)

![Window012](https://user-images.githubusercontent.com/76828213/205338429-09d1f253-4725-4ffc-813c-f02c22502ffb.png)

**Comment by JohnColket** [comment]
I hope this helps. :smiley:

**Comment by Ryan-Miller-Audacity** [comment]
FYI I tested this against Audacity 3.1.3 and it was reproducible there as well so this is not a new issue.

**Comment by LWinterberg** [comment]
@Ryan-Miller-Audacity please test if this is reproducible with other effects

**Comment by Ryan-Miller-Audacity** [comment]
FYI Testing with other built-ins and a few 3rd party VSTs this issue appears to be limited to the compressor only.

**Comment by GregoryAveryWeir** [comment]
We've run into this happening to an individual track when sync-lock is on and the track being compressor-ed starts at a later time than the other tracks to which it was sync-locked. All of the tracks' audio started after 0:00 (none was in pre-zero time to the left of the workspace). Turning off sync-lock before compressor-ing seems to prevent it from happening.

**Comment by dozzzzer** [comment]
Tested
