### ISSUE TITLE
VST2: Crash when hiding/showing the GUI of Fresh Air plugin

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3910]
### Plugin

Fresh Air

### Plugin Format

VST2

### Plugin source

https://slatedigital.com/fresh-air/

### Steps to reproduce

1. Have some audio
2. Select the **Fresh Air** plugin in the sidebar
3. Open its GUI
4. Close it
5. Try to open it again

### Expected behavior

The GUI of the plugin to show up

### Actual behavior

Crash: https://sentry.audacityteam.org/share/issue/a26268c8903f45c388d4413cb2dc02a1/

### Audacity Version

other: https://github.com/audacity/audacity/actions/runs/3429017268

### Operating system

macOS Ventura

### Architecture

Apple Silicon (M1, M2, ...)

**Comment by pietro68** [comment]
Can not reproduce this - it might have been fixed by other fixes (likely 08ee03f). This is what I tried:

latest release-3.2.2 (at commit 426ec9f)
built and ran it on MacOS (Intel-based)

I could open and close the Fresh Air gui multiple times, with playing on or off, without crashes.

**Comment by dozzzzer** [comment]
I confirm that the bug is no longer reproducible
