### ISSUE TITLE
Audacity 3.0.2 Incompatible with Marco + Compositing Window Manager

### ISSUE THREAD

**Issue by SirGawain99** [audacity/audacity#3925]
SW: Audacity 3.0.2 installed from official repo's via Synaptic package manager.
OS: Linux Mint 20.2 & 20.3, based on Ubuntu 20.04 (Focal).
DE: Mate Desktop.
WM: Marco + Compositing.

Procedure:
1.) Open Audacity.
2.) Close the project without saving it (File > Close), regardless of whether any audio files have been created or imported.

Result:
Audacity menu items become unselectable with a mouse. *Sometimes*, simply resizing the interface restores functionality.

Procedure (cont.):
Click the Start Menu.

Result:
The mate panels (task bar) disappear.
Ctrl-Alt-Del produces no graphical interface, although the machine does shutdown after the prescribed timeout period.

Workaround:
Using the left a Super (Windows) key to open Control Center, change the Window Manager to something other than Marco + Compositing, and back again.

Solution:
Employ an alternative window manager such as Marco + Compton.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI with all its frameworks. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
