### ISSUE TITLE
Remove 100ms minimum silence duration lower limit from Truncate Silence dialog

### ISSUE THREAD

**Issue by JC3** [audacity/audacity#3934]
### Your idea

The Truncate Silence dialog currently places a 100ms lower limit on the duration of silence to remove. There is no reason for there to be a limit on this, especially one so arbitrary and large. Worst case, to keep whatever the algorithm is from freaking out at unlucky zero-crossings in low frequency signals, a limit of N/sample_rate could just silently be placed internally, where N is some small number, like 2.

### Problem to be solved

Inability to remove silence shorter than 100ms.

**Comment by SteveDaulton** [comment]
> The Truncate Silence dialog currently places a 100ms lower limit on the duration of silence to remove.

Please say which version of  Audacity, and provide steps to reproduce.

In Audacity 3.2.1 there is no limit on the "Truncate to:" setting.
The is a 1ms limit on detection duration - there has to be a limit so as to avoid detecting thousands of zero crossings per second.

**Comment by WangleLine** [comment]
This FR can be closed - In older versions of audacity there was a minimum duration of 100ms for this effect, but in recent versions this limitation is no longer present.
