### ISSUE TITLE
VST2: Crash when applying some plugins destructively

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3935]
### Plugin

IEM Plugins, Little Radiator (Soundtoys), IHNY-2 (BabyAudio), Kickstart 2

### Plugin Format

VST2

### Plugin source

- [x] 1. https://plugins.iem.at/download/
- [ ] #3957
- [ ] #3959
- [x] #3958

### Steps to reproduce

1. select some audio
2. in the main Effect menu, select a plugin by **IEM**, (e.g. MultiEQ or MultiBandCompressor) or **Little Radiator** or **IHNY-2** or **Kickstart 2**
3. click **Apply**
5. observe

### Expected behavior

No crash

### Actual behavior

Crash: https://sentry.audacityteam.org/share/issue/5092d83086d04e8ea90be454391f2a9b/

### Audacity Version

[latest release-3.2.2 build](https://github.com/audacity/audacity/actions/runs/3461897323)

### Operating system

macOS, Windows 11

### Architecture

Apple Silicon (M1, M2, ...), amd64

### Additional Info

Comparing this build with `3.2.1`, I've noticed that all four plugins mentioned above didn't show UI when they were called from the main Effect menu. Clicking Apply did seem to process the signal properly without causing a crash.

**Comment by Ryan-Miller-Audacity** [comment]
I was able to reproduce this crash on Windows 10 testing with the IEM plugins, Kickstart, and IHNY-2 from above. I am waiting for an activation code from sound toys to test little radiator.

**Comment by Paul-Licameli** [comment]
Quite possibly, each of these has a very different cause so it's really several issues about peculiarities of individual plug-ins.

In the case of SoundToys, the plug-ins detect the presence of the program debugger and refuse to work, putting up a dialog that says so.

This will make it very difficult to proceed.  If a stack trace can be obtained by Sentry, that might give some data on which to make hypotheses about how to fix it.  But I can't promise success.

**Comment by pietro68** [comment]
About Kickstart 2: after I Installed it, I started Audacity and it froze while scanning it:

![image](https://user-images.githubusercontent.com/16491307/201959841-5f25b933-f77a-4d4b-acc7-b17557903d61.png)

No progress bar comes up, although the Elapsed Time counter will update itself. The dialog will stay stuck there (at least for 4 minutes, then I quit the app)

This happened on Windows - did any of you manage to make it work there?

**Comment by pietro68** [comment]
I tried Kickstart on Windows and it just will make the whole app exit, at this point:

![image](https://user-images.githubusercontent.com/16491307/201985644-e4ab6787-4d07-4fb1-97e1-dc9a52097dca.png)

The line is in VSTEffectWrapper::Load(). It calls a function of the vst2 sdk `vstPluginMain` where you pass in a callback function written by us (`VSTEffectWrapper::AudioMaster`); `vstPluginMain` can not be step debugged, as soon as I press the button to step into it, poof the app is gone.

I could take the last release code (3.1) and see if it happens also there - but when not, it would be hard to understand what makes the issue not happen there.

**Comment by dozzzzer** [comment]
The crash w/ Kickstart 2 is no longer reproducible in the latest release build (https://github.com/audacity/audacity/commit/932d7ae94f1535c518cbb2faa24a151806c8d60e)

**Comment by dozzzzer** [comment]
UPD: new Sentry crash log
https://sentry.audacityteam.org/share/issue/df7d12500a9240368a99d55d7ab60b75/

**Comment by Paul-Licameli** [comment]
I ticked the first box done, for IEM

**Comment by Paul-Licameli** [comment]
> Currently working at IHNY-2. It crashes in many different places: wxWidgets code, runtime c library etc. - really looks a lot like it overwrites memory when processing.
> 
> I changed the buffer size (in the options) from 8192 to **256**, and **that makes it not crash anymore**. That is definitively a good hint - will try more buffer sizes and then I can see if the fix that was done for IEM plugins in #3943 can be made to work for this case too.
> 
> EDIT: 256 and 512 cause no problems, with 1024 the crashes are triggered.

I'm not so sure.  Maybe there is a memory overwrite error and maybe you are only making bugs less probable when the size is smaller.  Maybe our code is at fault still and we don't know why.

**Comment by pietro68** [comment]
I broke this issue into 3 new issues:

#3959 (IHNY-2)
#3958 (Kickstart 2)
#3957 (Little Radiator)

Because each case manifests itself in different ways and has different causes. 
IEM is not there because it was fixed.

**Comment by dozzzzer** [comment]
Closing this ticket. See the comment above.
