### ISSUE TITLE
Audacity does not detect ffmpeg installed from pkg

### ISSUE THREAD

**Issue by TheCycoONE** [audacity/audacity#3939]
### Bug description

I downloaded the pkg for Audacity 3.2.0 and above for 64bit MacOS from https://lame.buanzo.org/#lameosx64bitdl and installed it.

It added the following files to `/Library/Application Support/audacity/libs`:

```
COPYING                     NOTICE                      libavcodec.dylib            libavformat.dylib           libavutil.dylib
LICENSE                     libavcodec.59.18.100.dylib  libavformat.59.16.100.dylib libavutil.57.17.100.dylib
LICENSE.md                  libavcodec.59.dylib         libavformat.59.dylib        libavutil.57.dylib
```

None of those files are *ffmpeg.55.64bit.dylib* and ffmpeg was not detected.

### Steps to reproduce

1. go to https://lame.buanzo.org/#lameosx64bitdl 
2. download https://lame.buanzo.org/FFmpeg_for_Audacity_3.2_on_macOS.pkg
3. install
4. open Audacity
5. attempt to import an m4a file

### Expected behavior

File should open

### Actual behavior

Dialog indicating that ffmpeg needs to be installed

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS

**Comment by TheCycoONE** [comment]
Closing, invalid. I was on an older version.

**Comment by AbsenceJam** [comment]
> Closing, invalid. I was on an older version.

I have this issue but I have the latest version (3.2.3). You didn't rename your files or anything?
