### ISSUE TITLE
Some Valhalla VST2 Plugins crash Audacity when starting playback with interface open

### ISSUE THREAD

**Issue by Ryan-Miller-Audacity** [audacity/audacity#3942]
### Bug description

This is a new issue that occurs in the most recent release build. With either ValhallaSuperMassive or ValhallaDelay (VST2) in the stack, if you open the interface and then press play, Audacity crashes. 

This does not occur with other Valhalla plugins, only the two mentioned above, and I haven't found any other examples of this issue in my plugin library so far.

This issue occurs in this build: https://github.com/audacity/audacity/actions/runs/3465950077
This issue is a regression on this build (where the issue did not occur): https://github.com/audacity/audacity/actions/runs/3461897323

This appears to only happen for ValhallaDelay on MacOS, but both ValhallaDelay and ValhallaSupermassive on Windows.

### Steps to reproduce

0. Delete pluginsettings.cfg
1. Get Valhalla Supermassive/Delay plugins from https://valhalladsp.com/plugins/
2. Open Audacity and grab some audio
3. Add Valhalla Supermassive or Valhalla Delay to the RT stack
4. Click the plugin to open its interface
5. Press the play button
6. Audacity crashes

### Expected behavior

Playback works normally; no crash

### Actual behavior

Audacity crashes

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS

**Comment by Ryan-Miller-Audacity** [comment]
FYI @pietro68 @Paul-Licameli

**Comment by Paul-Licameli** [comment]
I tried this with Supermassive (the free version) and failed to reproduce it.

**Comment by Paul-Licameli** [comment]
Aha, I can reproduce with Delay.

**Comment by Paul-Licameli** [comment]
I added a missing step 0 to reproduce the problem reliably.

**Comment by Paul-Licameli** [comment]
Commit c75bfef6b8b71c09334dc2a260e8e8056bd1472a is the bad one

**Comment by Paul-Licameli** [comment]
Actually I have seem the problem one commit previous, at ac953c12ba61eb43e4d63791c1f6c79aaa0e55f9

There seems to be some intermittency about it

**Comment by Paul-Licameli** [comment]
Try the fix! https://github.com/audacity/audacity/actions/runs/3473602583 @dozzzzer @Ryan-Miller-Audacity

**Comment by dozzzzer** [comment]
The fix works for me both on macOS and Windows, no crash observed.

**Comment by Ryan-Miller-Audacity** [comment]
Can confirm the same for me as well, no longer able to reproduce on Windows or MacOS.
