### ISSUE TITLE
VST2: IHNY-2 crashes when applying destructively

### ISSUE THREAD

**Issue by pietro68** [audacity/audacity#3959]
Plugin:  IHNY-2  https://babyaud.io/ihny-2

Format: VST2

Steps to reproduce:

### Steps to reproduce

1. select some audio
2. in the main Effect menu, select a plugin by **IHNY-2**
3. make sure that the selected user buffer size is 1024 or larger (in Options)
4. click **Apply**
5. observe

### Expected behavior

No crash

### Actual behavior

crash

What we know so far:

- running the app in Debug, we can see that all sorts of heap corruptions and memory stomps happen, and in multiple places
- the above happen as soon as the plugin's process function is run
- so far, buffersizes of 512 or 256 have been proven not to cause the crashes.
- crashes are not happening in realtime processing, because despite what the options say, the blocksize in realtime processing is 256 sample frames.

**Comment by pietro68** [comment]
This bug was incidentally fixed by the fix to another bug, happening at commit 02f0f84.
The bug is not reproducible anymore (because it is still fixed by the commit mentioned above), as of commit ca981b6 . Moving this card for ready for QA.

**Comment by Ryan-Miller-Audacity** [comment]
Note to self: Move to done if this passes QA since it was previously fixed and there is no new code to merge.

**Comment by Ryan-Miller-Audacity** [comment]
Testing in the [most recent release build](https://github.com/audacity/audacity/actions/runs/3524759727), I can no longer reproduce this crash on Windows or MacOS with the IHNY-2 VST2 plugin. Applying destructively and adding to RT stack appear to work without problem.
