### ISSUE TITLE
Information on Exporting and/or Rendering a track with an active effects stack

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#3960]
### Your idea
It would be very helpful to the more naïve users _(non-experienced DAW users like me for example)_ if the blank space in the effects stack when first launched contained some information as to how to actually **_apply_** the effects in the stack to the track.

![image](https://user-images.githubusercontent.com/50205984/202859021-d7fbac30-9396-48ac-9505-c03d3bef74d6.png)

I would suggest something similar or the same as the instructions in the Audacity Support GitBook:

![image](https://user-images.githubusercontent.com/50205984/202859226-7ee70767-47b7-42fc-94c4-c95fd150f75c.png)

Possibly additionally a link to the GitBook page would be useful@
https://support.audacityteam.org/audio-editing/using-realtime-effects

### Problem to be solved
As a reasonably experienced Audacity user I found myself yesterday totally scratching my head unable to figure out how I could actually apply the effects stack to a track and make it "stick".

In the end I posted on the Team Discord site asking how to do this - and got an excellent steer from @crsib  - thanks for that Dmitry - it's only easy when you know how.

@SteveDaulton pointed out on the same thread:
> It's normal / standard behaviour for a DAW, though I appreciate it might not be obvious for anyone that hasn't used a real-time DAW before.

I cannot be the only user of effects stack who is DAW naïve.

### Prior art
Not applicable

### Additional context
There is plenty of white space to contain this information - it may even help to make the white panel look a lot less blannk and empty:
![image](https://user-images.githubusercontent.com/50205984/202859715-ce9919a1-e0e0-4514-b106-9f9e3d6180ee.png)

Flagging @Tantacrul  @DilsonsPickles and @LWinterberg  as a UX/design issue

**Comment by LWinterberg** [comment]
I added a link to the support page on the video that's linked in there. Over the past half year, I've not seen too many people get confused by this anyway though.
