### ISSUE TITLE
The custom theme makes Audacity looks terrible!

### ISSUE THREAD

**Issue by GhostShadow0316** [audacity/audacity#3966]
### Bug description

This is the theme I put in Audacity 
![ImageCache](https://user-images.githubusercontent.com/94322065/203089746-a0f39151-93dc-47b0-bf61-f1a57b2bccdc.png)

But when I ture on Audacity, it look like this:
![image](https://user-images.githubusercontent.com/94322065/203089304-bbef4ccc-cc00-4468-b90a-5c328e6f8f12.png)

default theme works well.

### Steps to reproduce

1. put ImageCache.png into %appdata%\audacity\Theme\custom
1. restart Audacity

### Expected behavior

Audacity looks like this:

![Audacity Dark Gray Theme Preview](https://user-images.githubusercontent.com/94322065/203090564-2452c1e8-60d0-4d7b-b629-383f72c7ec77.png)

### Actual behavior

Audacity looks like this:

![image](https://user-images.githubusercontent.com/94322065/203089304-bbef4ccc-cc00-4468-b90a-5c328e6f8f12.png)

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by LWinterberg** [comment]
The imagecache is outdated and a new one needs to get generated for the theme. See https://github.com/audacity/audacity/wiki/Creating-custom-themes for steps. 

cc @visoart
