### ISSUE TITLE
Add tooltips for Input/Playback Metering buttons

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3968]
### Your idea

Currently, we're missing tooltips on hover for the Input and Playback Metering buttons. We should add the tooltips for each one of them.
![image](https://user-images.githubusercontent.com/70063970/203116741-447bce12-b006-435d-b1d2-7da884beb931.png)

### Problem to be solved

Lack of information on what these two buttons represent.

### Prior art

**Tooltip 1:** "Input Metering"
**Tooltip 2:** "Playback Metering"

**Comment by petersampsonaudacity** [comment]
The tool-tips on the reticulated grabber at the left of each meter just have the nondescript/unspecific  "**Audacity Meter Toolbar**"

They should say "**Audacity Recording Meter Toolbar**" and "**Audacity Playback Meter Toolbar**"

![image](https://user-images.githubusercontent.com/50205984/203371919-47a597dc-6af3-4362-bf38-68715a7e74cd.png)

**Comment by abhi-kr-2100** [comment]
I would like to work on this. I've successfully built and ran Audacity from source.

My plan to add the feature:

1. Find out where the mentioned GUI elements are defined in the source.
2. Add the appropriate tooltips.

**Comment by abhi-kr-2100** [comment]
@dozzzzer I've added the requested tooltips to those two buttons. See the PR above.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @abhi-kr-2100 ;s latest branch build:  audacity-win-3.3.0-alpha-20221124+a6e54d1-x64

The Tooltips say "Record Meter" and "Playback Meter" which is **_not_** what @dozzzzer from Muse spoecified in his original post in this thread.

![image](https://user-images.githubusercontent.com/50205984/203822879-17259d2e-0d1b-47ad-889c-4a01c0cc24a9.png)

![image](https://user-images.githubusercontent.com/50205984/203822944-19e93bac-4dcc-4e91-8e92-d996c75c64f2.png)

**Comment by abhi-kr-2100** [comment]
@petersampsonaudacity I used those tooltips because translations already exist for them (thanks to @vsverchinsky for pointing this out in https://github.com/audacity/audacity/pull/3977#discussion_r1031527925). If you look at [the already existing code around my changes](https://github.com/audacity/audacity/pull/3977/files#diff-cd5467523a40315d6e69e2c1ac3101945b19b5830f5efe915a51e5f20d33b2bbR236), you can see that the names of those buttons are "Record Meter" and "Playback Meter" respectively as well. Considering these, I decided to name them thus.

As to the second issue, I decided to make a small contribution first (and get all the feedback I can get) before attempting anything more, as I'm very new to open-source contributions, wxWidgets, and Audacity's source code. I plan to start work at this ASAP.

**Comment by petersampsonaudacity** [comment]
> @petersampsonaudacity I used those tooltips because translations already exist for them (thanks to @vsverchinsky for pointing this out in [#3977 (comment)](https://github.com/audacity/audacity/pull/3977#discussion_r1031527925)). If you look at [the already existing code around my changes](https://github.com/audacity/audacity/pull/3977/files#diff-cd5467523a40315d6e69e2c1ac3101945b19b5830f5efe915a51e5f20d33b2bbR236), you can see that the names of those buttons are "Record Meter" and "Playback Meter" respectively as well. Considering these, I decided to name them thus.

Actually I'm happy with either :-))

**Comment by abhi-kr-2100** [comment]
@petersampsonaudacity I've committed f3ac59734d49a4a104d037eacbbb696737a03f47, as you had suggested, to use "Audacity Recording Meter Toolbar" and "Audacity Playback Meter Toolbar" instead of the generic "Audacity Meter Toolbar". PR #3977 is awaiting approval. :)

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @abhi-kr-2100 's latest branch build:  audacity-win-3.2.2-alpha-20221125+00e4e12-x64

This now looks good to me in this branch build with the amended more specific tooltips fro the two Grabbers:

![image](https://user-images.githubusercontent.com/50205984/204086464-8e4fc8ee-086f-4565-9949-95eec16fc158.png)

![image](https://user-images.githubusercontent.com/50205984/204086491-28345e9c-096d-41de-bded-75f4185274e5.png)

**Comment by LWinterberg** [comment]
> The tool-tips on the reticulated grabber at the left of each meter just have the nondescript/unspecific "**Audacity Meter Toolbar**"
> 
> They should say "**Audacity Recording Meter Toolbar**" and "**Audacity Playback Meter Toolbar**"
> 
> ![image](https://user-images.githubusercontent.com/50205984/203371919-47a597dc-6af3-4362-bf38-68715a7e74cd.png)

shouldn't the grabbers say an action instead of what the toolbar is called? So something among the lines of "drag to rearrange".
(NB, this is unrelated to the existing PR)

**Comment by abhi-kr-2100** [comment]
@LWinterberg I think they should. How about something like: "Audacity Playback Meter Toolbar (drag to rearrange)"?

**Comment by abhi-kr-2100** [comment]
"Audacity Playback Meter Toolbar (drag to rearrange)" would look quite wordy, IMO. Maybe we should also consider removing the "Audacity" prefix from the toolbars.

**Comment by petersampsonaudacity** [comment]
> shouldn't the grabbers say an action instead of what the toolbar is called?

None of the other Grabbers have tooltips do that - they all simply state what the particular toolbar is (every single one of them).

**Comment by petersampsonaudacity** [comment]
> Maybe we should also consider removing the "Audacity" prefix from the toolbars.

That sounds quite sensible to me

**Comment by abhi-kr-2100** [comment]
@petersampsonaudacity I've made local changes that change each grabber to say "X Toolbar (drag to rearrange)". Should I push them to my existing PR?

**Comment by petersampsonaudacity** [comment]
@abhi-kr-2100 not my call any more - that's a Muse call @LWinterberg .

_I was a member of the old Audacity Team responsible for QA and documentation - but now I am an external open-source contributor acting as a "consultant" effectively._

**Comment by vsverchinsky** [comment]
@LWinterberg I guess it should be merged as is into `release-3.2.2` as such change require translation

**Comment by LWinterberg** [comment]
> None of the other Grabbers have tooltips do that - they all simply state what the particular toolbar is (every single one of them).

But *why* do they do that? The grabber is not the toolbar, why should it have a name badge of the toolbar? 

Also, looking around some more, grabbers with tooltips are very unusual anyway; what usually happens is that the cursor changes to a `grab` hand (or a 4-way `move` arrow) to indicate you can grab and move the thing. 

I don't mind having a tooltip for the action (the other side of the meters has a "click and drag to resize toolbar" tooltip anyway), but it really should be just the short "drag to rearrange" for the grabber (and "drag to resize" for the resizer)

> @LWinterberg I guess it should be merged as is into `release-3.2.2` as such change require translation
Yeah, please don't change your existing PR

**Comment by petersampsonaudacity** [comment]
> But _why_ do they do that? The grabber is not the toolbar, why should it have a name badge of the toolbar?

Aye, and now you're asking a philosophical design question (and a historical design decision at that)....

Very early Audacity 1.0 through 1.2.6 had no tooltips for the grabbers, Dominic did not provide suchlike - nor did the first of the 1.3 beta series 1.3.0 - 1.3.2 does have grabber tooltips, but they may have come with 1.3.1 (I don't have a copy of that release).  And those Grabber tooltips in 3.1.2 and subsequent Audacity versions have always just stated what the toolbar is,

**Comment by petersampsonaudacity** [comment]
> I don't mind having a tooltip for the action (the other side of the meters has a "click and drag to resize toolbar" tooltip anyway), but it really should be just the short "drag to rearrange" for the grabber (and "drag to resize" for the resizer)

That sounds sensible to me - but personally I would prefer the grabber to also retain the name of the toolbar (without the "Audacity as @abhi-kr-2100 suggests) - just to educate the user in Audacity nomenclature (handy when accessing documentation or when asking for help on the Forum or Discord).

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest 3.2.2 beta:  audacity-win-3.2.2-beta-20221129+97850a4-x64-msvc2022

Looks good to me on Windows

**Comment by LWinterberg** [comment]
closed by #3984
