### ISSUE TITLE
Macros can't access MIDI or second projects

### ISSUE THREAD

**Issue by JamesCrook** [audacity/audacity#397]
Macros (and scripting) cannot access data except in the current project, and GetInfo() and SetInfo() cannot get or set in MIDI.  

A GetInfo() command to GetInfo about all open projects, a SetProject() command and extensions to GetInfo() and SetInfo() for MIDI would address this.

An alternative is to disallow multi-projects (thereby solving multi-project wormcan) and an official stance that MIDI support is being kept limited intentionally, and that we instead intend to bridge to MIDI rather than fully implement our own MIDI editor.

**Comment by Paul-Licameli** [comment]
Closed, why?  Not disagreeing, asking.
