### ISSUE TITLE
Classic Filters is now Disabled in 3.2.2 beta and 3.3.0 alpha 

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#3972]
### Bug description
**Classic Filters** is now **Disabled** in 3.2.2 beta and 3.3.0 alpha/

a) In 3.1.3 and earlier it was not enabled but was in the now defunct "**New**" category

b) In 3.2.0 it was "**Enabled**" by default (and the manual changed accordingly) and it remained so in 3.2.1

### Steps to reproduce
1. clear the Audacity settings folder
2. Launch 3.2.2 beta or 3.3.0 alpha
3. Effect menu
4. Observe: Classic Filters is not present
5. Effect > Plugin Manager
6. Select the Disabled button
7. Observe Classic Filters is disabled

### Expected behavior
Classic Filters to be enabled by default

### Actual behavior
Classic Filters is disabled by default

### Audacity Version
3.2.2 beta and 3.3.0 alpha

### Operating system
Windows 10

### Additional context
It is possible that this is an intentional change to return Classic filters to be not enabled by default as was the case for 3.1.3 and earlier.

See also:   Classic Filters should be in the "EQ and Filters" section of the Effect menu #3932

**Comment by LWinterberg** [comment]
Peter, do you happen to know why the classic filters were shipped in the disabled (New) state prior 3.2 in general?

**Comment by petersampsonaudacity** [comment]
@LWinterberg  - Leo, I will write to you re. this tomorrow ...

**Comment by petersampsonaudacity** [comment]
Classic Filers _(originally called Scientific Filter)_ was the product of a pull request in 2013 from an open-source  contributor unknown to the Audacity Team.  At the time it was buggy and had no user documentation for what was and remains a fairly technical effect.  So it was originally added as an experimental effect and placed in the "New" category so that it was not enabled by default _(to avoid user confusion)_.

The upshot was, I suspect, that it was just momentum that carried this along as a "New" not-enabled by default effect in Audacity over many releases.

It remained in that state until Muse,worked on the "prettying-up" of the effects and the effects stack recently - when somehow (either deliberately or unintentionally) it was turned into a fully-fledged enabled by default filter effect..

It remains a fairly complex effect, used (and usable) mainly by a small population with DSP knowledge.
_I'd love to have had telemetry just to find out how much it really is used._

But as it is now a documented effect, then **_if_** it remains in Audacity it kinda makes sense for it to be enabled by default - not many folk are gonna look at the "Disabled" section in Plugin Manager now that plugins are auto-scanned and auto-enabled on launch

BUT if it does remain it really should live in the "EQ and Filters" section of the default Effect menu.
See GitHub issue #3932

**Comment by petersampsonaudacity** [comment]
The Manual is agnostic on this now.

It used to advise on the Effects page and the Classic Filters page that it was not enabled by default - but following the recent changes which enabled it by default I removed those advices.  

And it can safely remain that way in either case.

**Comment by vsverchinsky** [comment]
There were no intention to enable Classic Filters by default, that happened due to a bug

**Comment by petersampsonaudacity** [comment]
Since this is a fiercely technical/scientific effect I added a technical section to the page. This I found on the Talk page - a contribution from Federico Miyara : 
https://alphamanual.audacityteam.org/man/Classic_Filters#Detailed_background

**Comment by petersampsonaudacity** [comment]
> There was no intention to enable Classic Filters by default, that happened due to a bug

Great, in which case, I think,  this issue can be closed as NOT_A_BUG

### Residual
There does however remain a residual which will affect a small number of users.

If a user first installed Audacity when Classic filters was accidentally enabled by default and then upgrades to 3.2.2 the in 3.2.2 Classic Filters will remain enabled by default for them.

**Steps to reproduce**
1.  Clear Audacity settings folder
2. install 3.2.2
3. Effect menu
4. Observe: Classic Filters is not enabled 
5. Exit Audacity
6. Clear Audacity settings folder
7. launch 3.2.0
8. Effect menu
9. Observe: Classic Filters is enabled 
10. Exit
11. Launch 3.2.2
12. Effect Menu
13. Observe: Classic Filters _**remains**_ enabled

**Comment by Ryan-Miller-Audacity** [comment]
IMO, the residual is not a strong case to keep this open. The effect is enabled for some users that haven't reset preferences, but the effect works fine so even if a user does happen to click on it there is no negative consequence to this. 

I agree with Peter, closing as not_a_bug.
