### ISSUE TITLE
Request: update FFmpeg libraries

### ISSUE THREAD

**Issue by l00tzOMG** [audacity/audacity#398]
Please be so kind to allow the use of newer FFmpeg libraries, e.g. 4.2. The currently used version (2.2.2) has issues with e-ac3.

Thank you very much in advance,

**Comment by rogusdev** [comment]
https://forum.audacityteam.org/viewtopic.php?t=105590#p373215 seems to explain how to do it. I don't have time to prioritize this myself right now, but it sounds straightforward enough.

**Comment by Rehan-MALAK** [comment]
Yes, as said in the audacity forum, overwriting the ffmpeg lib-src/ffmpeg/{libavcodec,libavformat,libavutil}/ headers (I did it on bdcd907b5) worked for me

My local builded ffmpeg : version N-97687-gd0705ecb2b built with gcc 9 (Debian 9.3.0-11)

![auda](https://user-images.githubusercontent.com/39339802/82296432-7a663080-99b1-11ea-9a88-aa4d1d303555.png)

**Comment by l00tzOMG** [comment]
I get your point, but if it is so easy to update, why don't developers make it available for the broad audience of users, who don't wish to bother with compiling from source? Also, if you make a push request of your changes would probably speed up this process...

**Comment by pcroland** [comment]
I can't believe they still didn't update it.

**Comment by Demicro** [comment]
Why does this have no priority? I've been waiting a long time to be able to use the new ffmpeg and not the old garbage 2.2

**Comment by l00tzOMG** [comment]
> Why does this have no priority? I've been waiting a long time to be able to use the new ffmpeg and not the old garbage 2.2
> 
> It is impossible to download version 2.2 of Ffmpeg from the guide. Error 403

The sad thing is that there's already a pull request, which updates it to 4.2.3. The only effort needed from the authors is to check and merge...

**Comment by pcroland** [comment]
:-(

**Comment by AvrahamTsaban** [comment]
I am not sure how much attention do the audacity developers put into the conversation here. 
According to [this audacity forum post](https://forum.audacityteam.org/viewtopic.php?f=20&t=68196&sid=15fe1125d989d5155cfcd9b6b47c4cf7), feature request should be sent on the forum. 
Join [this forum discussion](https://forum.audacityteam.org/viewtopic.php?f=20&t=116912). Your voice will be helpful!

**Comment by pcroland** [comment]
They just don't care. All they would have to do is push the merge button.

**Comment by JamesCrook** [comment]
"All they would have to do is push the merge button."  LOL.  Try running an open source project that way and then come back and say it in all seriousness.

We have updates to FFmpeg, Portaudio and wxWidgets planned.  See #741.  That's by Leland who has commit rights.  When we are ready it will go in.

**Comment by Be-ing** [comment]
Now that #741 has been merged, I think this issue can be closed, right?

> "All they would have to do is push the merge button." LOL. Try running an open source project that way and then come back and say it in all seriousness.

To be fair, no maintainers responded to #608 until close to 9 months after it was opened. It's totally reasonable to reject or delay pull requests because the maintainers have other priorities, but it's not cool to provide no explanation for why a pull request addressing an issue that many users have raised concerns about doesn't get merged for 9 months.

**Comment by l00tzOMG** [comment]
Before closing: another important thing would be to add the `-drc_scale 0` switch upon importing (e)ac3 files, as FFmpeg applies DRC on these automatically and this should be avoided.

**Comment by JamesCrook** [comment]
@l00tzOMG - Please explain more.

Is it already covered by this: https://ffmpeg.org/pipermail/ffmpeg-devel/2015-March/170985.html ??

**Comment by l00tzOMG** [comment]
Hmmm, maybe I have missed something..., then it is already fixed :)

**Comment by JamesCrook** [comment]
Closing per:
> Now that #741 has been merged, I think this issue can be closed, right?
and:
> then it is already fixed :)

**Comment by JamesCrook** [comment]
#741 was reverted so reopening.

**Comment by ValZapod** [comment]
> Is it already covered by this: https://ffmpeg.org/pipermail/ffmpeg-devel/2015-March/170985.html ??

This was not applied and is not going to be applied. see patch more modern try to do it. https://patchwork.ffmpeg.org/project/ffmpeg/patch/20200201193443.22419-1-rcombs@rcombs.me/
