### ISSUE TITLE
Using the menu bar when audio is selected does not work seamlessly when using the keyboard

### ISSUE THREAD

**Issue by thureduehrsen** [audacity/audacity#3987]
### Bug description

Audio selection destroyed when opening menu using the mouse

### Steps to reproduce

Generate a track with audio in it
Select some audio
Click "Effect" in the menu bar
Hit the left-arrow button or the right-arrow button on the keyboard

### Expected behavior

The audio selection should be intact, and one of the adjacent menus ("Generate", "Analyze") should be open.

### Actual behavior

The selected audio is no longer selected. Using the Right arrow key causes the cursor to be at the end of the track. Then using the Left arrow key moves the cursor left as normal, albeit with the menu still visible. The originally-opened menu remains open. Hitting Esc closes it.

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

### Additional context

When using the Mousepad text editor to edit text instead of audio, this does not occur. I therefore suspect the bug to be in Audacity rather than in the window manager or the desktop environment.

This occurs on a standard 64-bit Intel system running an up-to date Debian stable, using Xfce 4.16 and the xfwm window manager.
The Audacity version is 2.4.2.

A way to work around this is to open the menu using the keyboard instead of the mouse (such as hitting "Alt+c" to open the Effect menu).

Build Information

Program build date: May 26 2021
Commit Id: No revision identifier was provided
Build type: CMake Debug build (debug level 1), 64 bits
Compiler: GCC 10.2.1
Installation Prefix: /usr

**Comment by SteveDaulton** [comment]
> Audio selection destroyed when opening menu using the mouse

I can confirm that this happens with Audacity 2.4.2, but it works correctly in the current Audacity 3.2.1.

**Comment by thureduehrsen** [comment]
> I can confirm that this happens with Audacity 2.4.2, but it works correctly in the current Audacity 3.2.1.

Fair enough, but 2.4.2 is the default Audacity version in Debian stable.
