### ISSUE TITLE
VST2: Crash when closing the dialog window of any Soundtoys plugin

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#3991]
### Plugin

Soundtoys 5 Trials

### Plugin Format

VST2

### Plugin source

https://soundtoys.com/demo

### Steps to reproduce

1. Download & install the bundle by Soundtoys
2. Launch Audacity and let it discover the plugins
3. Create an audio track
4. In the sidebar, select any VST module from the bundle
5. Open its dialog window
6. Close it by clicking the red cross icon

### Expected behavior

The plugin is closed

### Actual behavior

Crash: https://sentry.audacityteam.org/share/issue/df7d12500a9240368a99d55d7ab60b75/

### Audacity Version

latest beta: https://github.com/audacity/audacity/actions/runs/3564164007

### Operating system

macOS

### Architecture

Apple Silicon (M1, M2, ...)

**Comment by Paul-Licameli** [comment]
Call stack suggests the same problem as #3957 which is previously fixed

**Comment by Paul-Licameli** [comment]
The beta build you linked is three commits behind the fix for #3957 which is at commit 2991e0a2da50195d4960254cb5eab4f04aa5ebcf

**Comment by dozzzzer** [comment]
Verified
