### ISSUE TITLE
Audacity and "Wrapper" repeatedly ask for access to Documents or Downloads folder when loading a plugin

### ISSUE THREAD

**Issue by theirongiant82** [audacity/audacity#3995]
### Bug description

I tried loading a VST plugin on a track and Audacity asked me 20+ times for access to my Documents folder... just to draw the interface of the plugin itself.  When it did finally load, some GUI elements were corrupted or missing.

This is the 3.2.2.0 build made a couple of days ago to solve issue #3802 .  

### Steps to reproduce

1. Install a third party VST plugin.
2. Launch Audacity.
3. Create new project with a new track (or open an existing audio file).
4. Add plugin in effects rack.
5. Click button to display plugin GUI
6. Incessant privacy prompts appear.  Click OK to dismiss.  Repeat 20-30x.

### Expected behavior

I expected not to be bombarded with privacy prompts / requests when using a plugin.

### Actual behavior

MacOS prompts me repeatedly to allow Audacity or "Wrapper" to access my documents or downloads folder.

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

### Additional context

Issue #3802 .

**Comment by crsib** [comment]
This issue happens because the build you have used is not signed and notarized. Due to GitHub security limitations we cannot sign build coming from pull requests.

**Comment by theirongiant82** [comment]
Code Signing should be integreated into the development cycle because unsigned code won't run on Apple Silicon.  This is why the arm64 build won't launch on my Mac.

https://developer.apple.com/forums/thread/678816

Entitlements: https://developer.apple.com/documentation/bundleresources/entitlements
Hardened Runtime: https://developer.apple.com/documentation/security/hardened_runtime

Integrating Xcode signing into GitHub:
https://docs.github.com/en/actions/deployment/deploying-xcode-applications/installing-an-apple-certificate-on-macos-runners-for-xcode-development

**Comment by crsib** [comment]
For security reasons it is not possible to sign the builds coming from pull requests. GitHub does not shares secrets when the job is triggered with "pull_request" event, so there is no way to install the code signing certificates. After the PR is merged - the resulting build is signed. On top of that - all beta and release builds are notarized.
