### ISSUE TITLE
UI states, such as tracks height or expanded toggle, are not restored on load

### ISSUE THREAD

**Issue by eligt** [audacity/audacity#400]
**Describe the bug**
When you change tracks height or set a track to collapse rather than expanded, save the project and re-open it, the tracks' heights are all set to a default value and all tracks are expanded. These UI states used to be restored on project load on the older version of Audacity (2.2.0 I think?) but is not working in the recent version 2.3.3.

**Comment by petersampsonaudacity** [comment]
Thank you for this report - yes I can readily reproduce this on Windows 10 - so I shall be logging this on our bugtracker (I'll post back here for you with a Bugzilla link when I've done that).

It is even worse than you report as not only do you lose non-default track heights - you also lose any setting of the track view type to Waveform dB or Spectrogram.

Peter (Audacity QA)

**Comment by petersampsonaudacity** [comment]
These are two different bugs that I shall log.

1) The track size issue was present in 1.2.6 and fixed at some stage in the 1.3.x Beta Audacity series.  It was fine all the way up to  2.3.2 - so what we have with 2.3.3 (and my latest 2.4.0 alpha build) is a regression on 2.3.2 - so this will be a high priority bug.

2) The issue with the track view type seems to have been present all the way back to 1.2.6 and 1.0.0 - so not a regression but a VERY longstanding bug.

Peter.

**Comment by petersampsonaudacity** [comment]
Logged them both

1)  P1 2265
https://bugzilla.audacityteam.org/show_bug.cgi?id=2265
Track heights are reset to default on project re-opening

2) P3 2266
https://bugzilla.audacityteam.org/show_bug.cgi?id=2266
Audio track view types are reset to default on project re-opening

So is it OK if I now close this Github entry in favor of the more trackable Bugzilla entry?

**Comment by eligt** [comment]
Yup, sounds good.

**Comment by petersampsonaudacity** [comment]
OK closing this - Thanks Elia - and once again thanks for the report, much appreciated,

Peter
