### ISSUE TITLE
Crash applying PTEq-X destructively

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#4003]
### Plugin

PTEq-X by Ignite Amps

### Plugin Format

Audio Unit

### Plugin source

https://www.kvraudio.com/product/pteq-x-by-ignite-amps

### Steps to reproduce

1. generate noise, select all
2. Choose PTEq-X from the Effect menu
3. Apply
4. Bang

### Expected behavior

no go bang

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

### Additional context

See also #3936

**Comment by dozzzzer** [comment]
I wasn't able to reproduce this one against the most recent release build on my M1 Pro machine.
When I click Apply in the effect's dialog, nothing happens at all.

**Comment by Paul-Licameli** [comment]
> I wasn't able to reproduce this one against the most recent release build on my M1 Pro machine.
> When I click Apply in the effect's dialog, nothing happens at all.

Not crashing -- but not working either.  See below.

**Comment by Paul-Licameli** [comment]
Observations:  My Intel Mac reproduces this problem in 3.2.0.

In 3.1.3, the crash doesn't happen, but pressing Apply (usually) quietly fails and does nothing.  I did something, I'm not sure what, to the controls that sometimes made it do something.  I think it may have involved toggling the bypass switches, and then there would be only one success after a toggle.

Recall PR #3597 which partially fixed issue #3581 for Xfer OTT on macOS.  That fix was new in 3.2.0, and I think corrected a problem common to this plug-in, so therefore in earlier versions, this crash bug may really have been present, but latent and masked.
