### ISSUE TITLE
Selecting Audio in current 3.2.2 beta marks project as changed. Regression on 3.2.1.

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#4019]
### Bug description

Playing (selecting) audio from an existing audacity project marks the project as modified.

### Steps to reproduce

1) Start Audacity.exe from audacity-win-3.2.2-beta-20221202+05c36ac-x64
2) OK if requested
3) Tools > Reset Configuration
4) Generate > Chirp (1 minute)
5) File > Save Project > Save Project > OK
6) In Save Project Diaglog, "Chirp2" > Save
6) File > Close
7) File > Recent Files > Chirp2
8) Click near 15 second mark
9) Press space to start playing
10) Press speace to stop playing
11) File > Close
12) Note that "Save changes to Chip2?" windows appears, asking "Save project before closing?"

This is an annoyance and a regression over 3.2.1.  Note that the clicking in step 8 above seems to be what marks the project as modified. Additionally, there is no Undo information that might allow me to backtrack this supposed alteration to the project.

### Expected behavior

As the project has not been changed, (no UNDO information appears), the Audacity should simply exit without annoying the user.

### Actual behavior

A dialog asking the user if he wants to save the project.  Now I am led to believe that I have somehow unintentionally altered the project.

### Audacity Version

latest beta

### Operating system

Windows

**Comment by Paul-Licameli** [comment]
@crsib This is a consequence of the fixes that also mark the project as changed for adjustment of effect settings.

**Comment by crsib** [comment]
Well, yes, `ProjectHistory::ModifyState` now really marks project as modified, it is not longer a no-op is used to be

**Comment by crsib** [comment]
The good question is though: if we store the selection as a part of the project - why modifying it should not mark the project "dirty"? Should we remove selection info from the project or should we treat it as some meta information that can be discarded? What are the other project states we consider "minor"? Should store such information outside the project scope?

For example, the Audacity ignoring changes to looping region was quite an inconvenience for me.

**Comment by crsib** [comment]
In any case, this is very easily fixable, so I think we can fix it for 3.2.3

**Comment by JohnColket** [comment]
Wow! That was fast - I'm impressed! :smiley:

**Comment by crsib** [comment]
Well, this will be released only in the next patch release, but it will happen this year
