### ISSUE TITLE
Says a bug has happened.

### ISSUE THREAD

**Issue by noahdiamond4** [audacity/audacity#402]
Deletes files in the middle of recording
![Single Parent Families Edits (1) 12_11_2019 8_49_40 PM](https://user-images.githubusercontent.com/58823273/70733101-9e716780-1cd7-11ea-9284-9724f6307554.png)

**Comment by noahdiamond4** [comment]
Is there more detail needed?

**Comment by JamesCrook** [comment]
Which version of Audacity?
Did this appear during recording, or when you reopened the project?
Was the project on a USB key?
Had you moved the project from its original location?

**Comment by petersampsonaudacity** [comment]
This message normally appears on project opening when you have a corrupted project.  Is this when it occurred for you? 

You would be better off raising this issue on the Audacity Forum:  https://forum.audacityteam.org/index.php

**Comment by petersampsonaudacity** [comment]
I have now added a page for this in the Audacity Manual - it will be in the upcoming 2.4.0 Manual (as I cannot edit or modify released Manuals).  You can get a preview of that page here:  https://alphamanual.audacityteam.org/man/Warning_-_Missing_Audio_Data_Block_Files
