### ISSUE TITLE
Effect's parameters don't stick (AU, VST)

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4021]
### Bug description

The issue is very similar to #3993, however, there's one more important step that is necessary in order to reproduce it.

### Steps to reproduce

1. Have some audio
2. Start playback
3. Select a VST2/AU effect in the sidebar, e.g. Deegain
4. Open it
5. Tweak any parameter
6. Close it
7. Stop playback
8. Open the effect again
9. See the parameter's value

### Expected behavior

The parameter remains the same

### Actual behavior

The parameter got reset to its previous value

https://user-images.githubusercontent.com/70063970/205687169-5b84e5e5-da57-42a5-8bf4-243d829d51a9.mp4

### Audacity Version

[current master / alpha / nightly build](https://github.com/audacity/audacity/actions/runs/3620736603)

### Operating system

macOS, Windows

**Comment by Paul-Licameli** [comment]
Swapping steps 6 and 7, there is no bug in AU.

**Comment by dozzzzer** [comment]
Verified
