### ISSUE TITLE
Crash when quitting Audacity with more than one projects open

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4023]
### Bug description

Audacity crashes when a) more than one project is opened and b) at least one of them has the RT effect panel opened

### Steps to reproduce

0. Have two .aup3 project saved each containing one mono track with some audio
1. Open project A
2. Open project B 
3. Open the RT effects panel of the audio track by clicking the "Effects" button
4. Cmd + Q
5. Observe

### Expected behavior

No crash

### Actual behavior

Crash:

https://sentry.audacityteam.org/share/issue/4fa38faa4cbe41fa8f03fcc99bebeae2/

A subsequent program launch with an attempt to recover the projects shows that one project's changes were lost.

### Audacity Version

https://github.com/audacity/audacity/actions/runs/3620736603

### Operating system

macOS, Windows 

### Additional context

- It is a regression against 3.2.1
- On Windows, there's no visual clue as to the crash when quitting Audacity. However, the project recovery dialog appears when launching the program next time, which points out the program was shut down with an issue.

**Comment by Paul-Licameli** [comment]
Is the description complete?  Must there be an effect in the sidebar?  The stack trace suggests that you had one of the TAL effects loaded at the time.

**Comment by dozzzzer** [comment]
> Is the description complete?

Yes, I've reproduced this bug a number of times not having a single effect in the stack

**Comment by Paul-Licameli** [comment]
I failed to reproduce once, then added a TAL effect, then got it -- I've tried VST and AU versions of TAL so far.

I found some clues in the debugger.  It may involve @vsverchinsky 's recent changes with TipWindow.  Not confirmed yet.

**Comment by Paul-Licameli** [comment]
Now I'm having trouble repeating it.  This bug seems to fleet.  I think it involves random memory overwrites.

**Comment by Paul-Licameli** [comment]
I think a more reliable and precise STR is:

1) Open one project
2) open another project
3) Open the sidebar OF THE SECOND project
4) then ctrl+q

**Comment by Paul-Licameli** [comment]
I suspect commit 2624e1c1756d4b4c388ec1f334e7bd5b729f10e4 which lately fixed #3997 introduced this other crash, but proof is difficult with the intermittency of the crash.

**Comment by Paul-Licameli** [comment]
Maybe @dozzzzer you can confirm that this last build of the release branch before that commit is free of this bug: https://github.com/audacity/audacity/actions/runs/3585392211

**Comment by vsverchinsky** [comment]
> I suspect commit [2624e1c](https://github.com/audacity/audacity/commit/2624e1c1756d4b4c388ec1f334e7bd5b729f10e4) which lately fixed #3997 introduced this other crash, but proof is difficult with the intermittency of the crash.

Unlikely, I can reproduce a bug without this commit.

**Comment by dozzzzer** [comment]
> Maybe @dozzzzer you can confirm that this last build of the release branch before that commit is free of this bug

Yes, confirm that, [the next release build ](https://github.com/audacity/audacity/actions/runs/3593148913) already has this bug in it

**Comment by vsverchinsky** [comment]
> Unlikely, I can reproduce a bug without this commit.

Sorry, not true, I've tested it at wrong commit

**Comment by petersampsonaudacity** [comment]
I can reproduce this on W10 with @Paul-Licameli 's simplet STRs with:  audacity-win-3.2.2-beta-20221205+3d1ab64-x64-msvc2022

**Comment by petersampsonaudacity** [comment]
When I try to send the crash report I get a failure error:

![image](https://user-images.githubusercontent.com/50205984/205908998-29c1ba21-e1e1-4ae4-aece-0a492e8361ba.png)

**Comment by petersampsonaudacity** [comment]
Even simpler STRs - only one project needed for the crasj

1. Open an existing project
2. Click on Effects button in TCP
3. Ctrl+Q to quit
4. Observe crash

**Comment by dozzzzer** [comment]
Verified on macOS Ventura & Windows 11

**Comment by vsverchinsky** [comment]
@petersampsonaudacity Doesn't reproduce for me with your STR (tried both before the hot fix and after)
