### ISSUE TITLE
Speaker Mixer (Meter) behavior is inconsistent.

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#4031]
### Bug description

When I do Tools > Reset Configuration, the meters appear to be in an undefined state.

### Steps to reproduce

1) Open Audacity.
2) Set both Mixers to an arbitrary setting, eg. -30
3) Exit Audacity
4) Both Mixers appear to remain at -30.
5) Do Tools > Reset Configuration
6) Again, both Mixers appear to remain at -30.
7) Exit Audacity.
8) Restart Audacity
9) Check the meter values

### Expected behavior

At step 9 I would expect the behavior to be the same as at step 6.

### Actual behavior

Speaker Mixer appears to be 0.

### Audacity Version

latest beta

### Operating system

Windows

### Additional context

Curiously: If microphone volume is adjusted before step 7, then at step 9 the speaker mixer remains at -30

**Comment by dozzzzer** [comment]
I was able to reproduce it on macOS Ventura
