### ISSUE TITLE
Audacity hangs on Linux when there is a "lv2" directory where it's started

### ISSUE THREAD

**Issue by ycollet** [audacity/audacity#4034]
### Bug description

I've got a lv2 directory in my personal account. This directory doesn't contains any lv2 plugins.
When I start audacity in the parent directory, audacity hangs.

### Steps to reproduce

mkdir lv2
audacity

### Expected behavior

audacity starts without problems

### Actual behavior

Audacity crashs

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

**Comment by LWinterberg** [comment]
could not reproduce this, neither with the 3.2.2 appimage nor with the 2.4.2 from the repo

**Comment by ycollet** [comment]
Tested and it looks like it's fixed now.
