### ISSUE TITLE
Copied clip with envelope points starts before zero.

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#4035]
### Bug description

A forum user, Anna BRITstralian, is having a difficulty with "Envelope Tool randomly creating envelopes throughout audio", see post here: https://forum.audacityteam.org/viewtopic.php?f=70&t=127880

This bug report identifies one issue with copying clips containing envelope points that might share the underlying cause of that issue.

### Steps to reproduce

1) Tools > Reset Configuration
2) Generate Tone: Sine, 1000Hz, .8 amplitude , .01 seconds duration (short duration chosen for clarity)
3) Press F2 to activate Envelope Tool.
4) Create a single envelope point by clicking on the waveform near .002 second mark
5) Press F1 to (re-)activate Selection Tool.
6) Select Audio from near .003 to .004 second marks.
7) Ctrl+C=Copy
8) Move cursor below track, then Ctrl+V=Paste
9) Note Left-pointing arrows on newly pasted track indicate audio before time 0.

### Expected behavior

Audio should be pasted at 0.0 mark

### Actual behavior

Audio seems to be pasted prior to the 0.0 mark.

### Audacity Version

latest beta

### Operating system

Windows

### Additional context

Tested with Audacity 3.2.2-beta-20221205

Note while this behavior is repeatable, it is inconsistent.  Sometimes it will work 5 times in a row, sometimes it will fail 5 times in a row.

![Window015](https://user-images.githubusercontent.com/76828213/206213797-433e4fed-5192-4c52-ae5e-5ddd369fa351.png)

![Window016](https://user-images.githubusercontent.com/76828213/206214261-d7658e60-ebca-4b46-8f16-92c41fe754e3.png)

**Comment by DeeFeeCee** [comment]
Reproduced in the release build with larger, complex clips. For me, when it does happen, it's consistent. Copying a bugged clip always pastes a pre-0 clip. But copying a pre-0 clip results in a normal clip. & the length of both clips is reported as the same. Saving the project saves the pre-0 state.
[Bug 4035.zip](https://github.com/audacity/audacity/files/10203607/Bug.4035.zip)

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
