### ISSUE TITLE
No in-app report of new 3.2.2 release

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4037]
### Bug description

There is no report or indication in the (3.2.1) app that the new 3.2.2 release is available - and thus no offer to download and install the new version

### Steps to reproduce

1.  delete all traces of previous 3.2.2 betas and alphas - and 3.3.0 alphas
2. purge the audacity settings folder 
3. Launch 3.2.1
4. Observe: no advice re an updated version available
5. Help > Check for Updates...
6. Observe: message advises "No Updates Available"
![image](https://user-images.githubusercontent.com/50205984/206415729-af72c5a8-460c-4af8-a823-61188175ff6b.png)

### Expected behavior

Update checking to advise of the availability of the new 3.2.2 version

### Actual behavior

No update advice

### Audacity Version

stable version (from a Linux repository)

### Operating system

Windows

### Additional context
Automatic update checking is supposed to now be the **_primary means_** whereby users get notice of new releases

**Comment by crsib** [comment]
I am unable to reproduce this issue

![image](https://user-images.githubusercontent.com/2660628/206417700-3c45bc3c-fa83-49e6-a7c5-4af64bcdf23f.png)

**Comment by dozzzzer** [comment]
I'm also seeing this on startup even not having to clear the Audacity settings folder:

<img width="450" alt="image" src="https://user-images.githubusercontent.com/70063970/206425290-2cecf2af-4491-4ed6-869a-e32ed6eebdec.png">

**Comment by LWinterberg** [comment]
I get the notification as well

**Comment by petersampsonaudacity** [comment]
And I get the notification on my Macbook Pro running Monterey 12.6.1  (it's too old at a mere 5 years to upgrade to Ventura)

Her I was launching 3.2.0 as my latest version - and no purging of the audacity settings folder.

_So I'm at a loss as to understand what occurred on my W10 machine ..._
