### ISSUE TITLE
Released manual has not been updated for the 3.2.2 release (or for the 3 3.2.3 release)

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4038]
### Bug description

The released manual has not been updated from the alpha manual for the 3.2.2 release - both the online version and the downloadable version from FossHub.

Clearly seen by observing the incorrect nomenclature declaring it to be 3.3 _(this was fixed by @LWinterberg in the alpha manual for 3.2.2)._

Plus the new restructured/trimmed landing page (with its two sub-pages) is clearly not there.

### Steps to reproduce

1. Install  and launch 3.2.2 or 3.2.3
2. Help > Manual
3. Observe: the same online manual that we had for 3.2.1 - one that declares itself to be 3.3 (and does _**not**_ have  the recent updates

### Expected behavior
Updated manual displayed for 3.2.2 - with updates made for 3.2.2

### Actual behavior

Old 3.2.1 manual displayed for 3.2.2

### Audacity Version
3.2.2

### Operating system
Windows 10 - but suspect all OS

### Additional context
Flagging @LWinterberg and @gguzman

**Comment by petersampsonaudacity** [comment]
This also affects the .tar.gz zipped 3.2.2 Manual that can be downloaded from FossHub:  https://www.fosshub.com/Audacity.html

**Comment by SteveDaulton** [comment]
The current on-line version of the manual  says that it is for Audacity 3.3 whereas the current version of Audacity is 3.2.2.

![Screenshot_2022-12-14_20-38-54](https://user-images.githubusercontent.com/11681097/207709432-85afc647-8ee6-4102-9f64-8bb91bafce96.png)

**Comment by petersampsonaudacity** [comment]
@crsib @LWinterberg 

Testing on E10 with the newly released 3.2.3

When I use **Help > Manual** to access the online manual from the app, I am still seeing the same version of the manual that we had for 3.2.1 
a) it still declares itself to be q 3.3 Manual despite Leo's corrections
b) It does not have the changed, shortened, front page with its two sun-pages that a created a few weeks ago
c) it does not have the changes I made recently in the alpha Manaul to link the "View" in the menu bar in the imagemap to link directly to the "View Menu" - and similar for all the other View menu commands in the imagemap

But oddly it does have 
d) the changes I made yesterday for the Toolbars Overview page
e) the new page I added yesterday for Cut/Copy/Pasre Toolbar

**_But_** the Cut/Copy/Patre Toolbar page displays incorrectly:
![image](https://user-images.githubusercontent.com/50205984/209819323-493e8f57-ce1a-4353-9a5b-80287c4837a2.png)
In contrast this page displays properly formatted in the alpha manual

**Comment by crsib** [comment]
The procedure is quite standard and was more or less the same long before I joined. 

Magical Python script parses alphamanual, the result is pushed to a very special repo and is later grabbed by a script on manual.audacityteam.org. I haven't changed the Python script, I have no controll over the script that that updates the manual.

I have no idea what is wrong or how to fix it.

**Comment by petersampsonaudacity** [comment]
@crsib  maybe you need to ask @JamesCrook  for his advice on haw to fix this, my understanding was tht it was he who createted the Magical Python script to pull the Manual to be the released manual from the alpha manual as part of the release process.

It is most odd that other changes have percolated through (View Menu changes and Cut.Copy Paste Toolbar addition) - but the front page (perhaps the most important page of all remains unchanged).

I certainly can offer no insight into how the Magical Python script is supposed to work, sorry ...

**Comment by crsib** [comment]
I can see significant amount of changes in `index.html`: https://github.com/audacity/audacity-manual/commit/77d05c0b119d3d30631141cc058200c4da43ab2d

I cannot verify if they are correct or no

**Comment by crsib** [comment]
Speaking of the wrong layout - CSS file for cut copy paste evaluates to a wrong location. Probably the script can't handle that many forward slashes in the page path

**Comment by LWinterberg** [comment]
The page title handling is the problem. cut/copy/paste_toolbar.html tries to load [../../m/skins/monobook/main.css/303.css](https://manual.audacityteam.org/man/m/skins/monobook/main.css/303.css), which 404s. It should have ../../../ instead to go to [/m/skins/monobook/main.css/303.css](https://manual.audacityteam.org/m/skins/monobook/main.css/303.css)

(or, better yet, an absolute path for the stylesheet instead of a relative one)

A workaround would be to move the page to Cut Copy Paste toolbar and DISPLAYTITLE it

**Comment by crsib** [comment]
Absolute path won't work, as the generated manual is generally expected for the offline use

**Comment by crsib** [comment]
Yeah, the script doesn't handle that level of nested directories

https://github.com/audacity/audacity-manual/blob/master/scripts/mw2html_audacity/mw2html.py#L311

**Comment by crsib** [comment]
I have quicly compared the main page and I don't observe any significant differences between the pages on `manual` and `alphamanual`

**Comment by petersampsonaudacity** [comment]
> A workaround would be to move the page to Cut Copy Paste toolbar and DISPLAYTITLE it

Can do  _(I did wonder yesterday when I created that page - but the alpha manual seemed happy, so I went ahead)_

**Comment by crsib** [comment]
We will edit the link to CSS in cut/copy/paste manually this time. 

As for the index page - I think something is wrong with the browser cache, because I can see no meaningful difference between manunl and alphamanual on my side.

**Comment by petersampsonaudacity** [comment]
> > A workaround would be to move the page to Cut Copy Paste toolbar and DISPLAYTITLE it
> 
> Can do

Done - and changed the links in the three pages that link to it:
https://alphamanual.audacityteam.org/man/Cut_Copy_Paste_Toolbar

**Comment by petersampsonaudacity** [comment]
> We will edit the link to CSS in cut/copy/paste manually this time.

Thanks for that much appreciated 

 
> As for the index page - I think something is wrong with the browser cache, because I can see no meaningful difference between manual and alphamanual on my side.

Yepper, it must be my cache on Firefox, as when I search for the Manual on Chrome or MS Edge - all is fine 3.2 Manual with all my front page changes

What is odd was that I thought I had cleared the Firefox cache ...

So @LWinterberg I think this issue can be closed
