### ISSUE TITLE
Scrollbars in dark mode

### ISSUE THREAD

**Issue by locness3** [audacity/audacity#404]
**Is your feature request related to a problem? Please describe.**
Scrollbars in dark interface themes aren't dark colored an stay in the system colors.

**Describe the solution you'd like**
I'd like the scrollbars to be themed with the rest of the interface.

**Additional context**
macOS :
![Capture d’écran 2019-12-20 à 15 20 57](https://user-images.githubusercontent.com/37651007/71260931-60f68500-233c-11ea-9efe-0f03a7323e30.png)

**Comment by JamesCrook** [comment]
Thanks for creating an issue.  Yes, we would like this too.  At the moment it looks like we would need to draw the scrollbars ourselves to get the desired result.

**Comment by locness3** [comment]
Yeah, I understand.
