### ISSUE TITLE
Screenshot of Track Panel shows Ruler instead

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#4040]
### Bug description

On Screen Capture Frame in Tools > Screenshot,

Track Panel and Ruler buttons seemed to have swapped functionality.

This is a regression on 3.1.3

### Steps to reproduce

1) Tools > Screenshot
2) Click "Track Panel" button (3rd row from bottom)

### Expected behavior

Saved C:\...\Tracks....png

### Actual behavior

Saved C:\...\Ruler....png

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

Tracks Panel and Ruler button seem to be reversed.

**Comment by Paul-Licameli** [comment]
I think commit 988bcc209dcef0669685802425b72a3366ba8900 is to blame, and the fix will be a simple one liner

**Comment by petersampsonaudacity** [comment]
Testing shows that all the buttons in the **Capture part of a project window** are screwed up and incorrect after the Transport button.

It looks as though they are transposed by one button position.

Might this have something to do with the **Mixer** button being there but Audacity no longer having a Mixer toolbar?

And just what is the **Meter** button doing there?
_**Update:**_  OIC - it gives you both meters - so the button would be better as "Meters" for clarity of purpose

**Comment by JohnColket** [comment]
Thank you, Paul. :smiley:

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @Paul-Licameli 's branch build:  audacity-win-3.3.0-alpha-20221208+b4ba7ec-x64

This looks to be properly fixed in Paul's branch build
