### ISSUE TITLE
ReaPlugs plugins in two different categories in the Effect menu and in the Effects stack

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4042]
### Bug description

The ReaPlugs plugins show up in two different categories in the Effect menu and in the Effects stack:  2 in **Cockos** and 6 in **Unknown**

### Steps to reproduce

1. Download the ReaPlugs VST FX Suite fro Reaper's site:  https://www.reaper.fm/reaplugs/
2. Install to the default folder suggested by installer:    C:\ProgramFiles\Steinberg\VSTPlugins\Reaplugs
3. Launch 3.2.2
4. get some audio and make it selected
5. Effect > Cockos
6. Observe 2 ReaPlugs plugins
7. Effect > Unknown
8. Observe: a further 6 ReaPlugs plugins

Similar behavior obtains in the Effects Stack

### Expected behavior

All the ReaPlugs plugins to be in the same category

No plugins in the **Unknown** category

### Actual behavior

ReaPlugs plugins in two different categories in the Effect menu and in the Effects stack

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context
![image](https://user-images.githubusercontent.com/50205984/206537288-021274c0-8b5e-4d21-8765-54558550ed6e.png)

![image](https://user-images.githubusercontent.com/50205984/206537404-c92b1896-ed89-4f88-9928-44102d75e225.png)

![image](https://user-images.githubusercontent.com/50205984/206537630-59a847c5-d86a-45c5-9293-48f25b7cd3ce.png)

**Comment by crsib** [comment]
It's not a bug in Audacity, this issue is with ReaPlugins - they do not report vendor

**Comment by petersampsonaudacity** [comment]
@crsib  I somehow thought you were gonna say that Dmitry  ;-))

**Comment by Ryan-Miller-Audacity** [comment]
If the bug is not on our side, we can likely go ahead and close. Let me know if there is disagreement.

**Comment by petersampsonaudacity** [comment]
@Ryan-Miller-Audacity    even if the bug is on our side - we should try to ensure that Audacity fails gracefully (with an informative error message) and does not crash.

_This applies to any other plug-in that might crash Audacity as crashes are never good, they reflect badly on Audacity even if the fault lies with the plug-in provider._

**Comment by crsib** [comment]
Audacity does not crash because of different categories
