### ISSUE TITLE
plugin scan dialog malformed on linux

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#4048]
> 1. Skip button is now included in plugin scan window and properly skips over plugins as clicked.

Testing with audacity-linux-3.2.2-x64.AppImage

Where is the "skip button"? Is it that line in the bottom right corner? It does not appear to be clickable.

![Screenshot_2022-12-09_16-35-34](https://user-images.githubusercontent.com/11681097/206749560-e309e7d8-9934-4f1c-915c-186bb2a62085.png)

Update: Yes it is clickable if the mouse pointer is in exactly the right place (it took a few attempts to activate it).

_Originally posted by @SteveDaulton in https://github.com/audacity/audacity/issues/3838#issuecomment-1344522455_

**Comment by LWinterberg** [comment]
I can reproduce this somewhat: 

Using Ubuntu (gnome) 22.04, the cancel button is simply cut off at 100% scaling. 

At hiDPI, the "elapsed time" also is cut off. 

The hitbox for the skip button works as expected at 100%.

**Comment by sirius-c** [comment]
Same issue on Xubuntu 22.04 LTS, Audacity compiled from source. Plugin scan window looks as shown above.

**Comment by dozzzzer** [comment]
No issues on Ubuntu 20.04 compiled from source

<img width="525" alt="image" src="https://user-images.githubusercontent.com/70063970/207063125-29ff9e1f-12e7-4e06-83f5-5ccccac0f967.png">

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
