### ISSUE TITLE
Recording audio with Audacity, BlackHole and multi output device

### ISSUE THREAD

**Issue by klopfdreh** [audacity/audacity#405]
**Describe the bug**
When I try to record audio with BlackHole audio mapping it is not working properly. QuickTime however is recording everything correctly, so the internal audio mapping is working correctly.

**To Reproduce**
1. Install BlackHole like explained here: https://github.com/ExistentialAudio/BlackHole
2. Created a multi output device within the Audio-Midi-Setup with the primary device being set to the internal speakers - drift correction applied to BlackHole 16ch
3. Started the system preferences for audio and set the input to BlachHole 16ch
4. Started Audacity and set the recording device to BlackHole 16ch and the output to the multi output device

**Expected behavior**
The audio should be recorded like with QuickTime

**Additional information (please complete the following information):**
- macOS 10.15.2
- Audacity 2.3.3
- BlackHole v0.2.5

**Additional context**
- Related bug issue: https://github.com/ExistentialAudio/BlackHole/issues/39
- Audacity setup with BlackHole: https://github.com/ExistentialAudio/BlackHole/wiki/Audacity
- Micro access has been granted to Audacity

**Comment by JamesCrook** [comment]
Thanks.  For now we are treating this as the same as the 'not supporting Catalina' bug.  So am closing (as a duplicate).  If when we do support Catalina, expected with 2.4.0, and if it still does not work, then may be time to revisit it.

**Comment by klopfdreh** [comment]
Okay - I am going to check it and report back here when 2.4.0 is released. Thanks for the reply.
