### ISSUE TITLE
Preference "Use dialog for the name of new label" also acts on editing Clip-names

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4055]
### Bug description

The **Tracks Behaviors** preference setting for "**Use dialog for the name of new label**" also acts on the editing of editing Clip-names.

This will be a surprise to the user as:
a) it is an undocumented Easter-Egg
b) There is nothing in the labeling of the pref to indicate that it also acts on clip-name editing

### Steps to reproduce

1. Ensure **Use dialog for the name of new label** is off in **Tracks Behaviors** prefs
2. get some audio
3. Edit the clip-name (**double click**, shortcut **Ctrl+F2** or **Edit > Rename Clip**)
4. Observe the clip can be edited in situ in the Clip-handle drag-bar (subject to bug #3704)
5. In **Tracks Behaviors** prefs tun **on** the pref **Use dialog for the name of new label**
6. Edit the clip name
7. Observe this time a dialog appears for the editing

![image](https://user-images.githubusercontent.com/50205984/207037159-5351ed7b-c3d8-46b6-804c-ee210f2c66f4.png)

### Expected behavior

Either of:

a) re-title that preference to **Use dialog for the name of new label or for editing clip names**

b) add a new pref in **Tracks Behaviors**  for **Use dialog for editing clip names**

The former is a lot more clunky - but does avoid prefs-bloat.
The latter has greater clarity of purpose (and thus simplifies documenting in the manual)
Personally, I prefer the latter, the new preference.

### Actual behavior

**Tracks Behaviors** preference setting for **Use dialog for the name of new label** unexpectedly also acts on the editing of clip names

### Audacity Version
3.2.2 - but this is _**not**_ believed to be a regression

### Operating system
Windows 10 - but suspect all OS

### Additional context
Originally detected with the research into Bug 
 **Can't rename clips #3704**

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
