### ISSUE TITLE
Multiple "Usage: Audacity [/b <num]..." message box popups on Windows

### ISSUE THREAD

**Issue by ksoze95** [audacity/audacity#4058]
### Bug description

Under Windows, when Audacity starts up and scans for plugins, it pop up multiple "Usage: Audacity ...." message boxes.
It takes a while for each message box to appear.  It seems happen after it attempts to verify each plugin, which times out, before the the message is displayed.

This happens on the latest master branch.  Git bisect shows that commit f78f01241374720450f1da82c13ed09a2cf30e81 is the first commit which had this bug.

![plugin_scanning_issue](https://user-images.githubusercontent.com/101076697/207076779-3740ad55-74bc-48a2-bb9e-8778957f1460.png)

### Steps to reproduce

1.  Start up the Windows Audacity application build from the latest master branch.

### Expected behavior

1. Does not take a long time to do the plugin scanning.
2. No "Usage: Audacity ..." message box popups.

### Actual behavior

1. Long time to complete the plugin scanning.
2. Multiple "Usage: Audacity..." message boxes.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

**Comment by dozzzzer** [comment]
Verified on Windows 11.
