### ISSUE TITLE
BassTreble, Phaser, Reverb, WahWah should be available in sidebar

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#4063]
These four should be among the built-in realtime capable effects, and available for testing soon.

Should also arrange that when switching from 3.3 (or later) to an earlier Audacity, then back again -- the effects are in the sidebar only when you run 3.3 + .

There are known problems with Reverb not responding to adjustment of controls, to be fixed later.

It is not expected that the other threee have similar problems, but if such are discovered, then open other issues.

**Comment by petersampsonaudacity** [comment]
I tested this on w10 with @Paul-Licameli 's branch build:  https://github.com/audacity/audacity/actions/runs/3685700498.

The four Audacity RT effects seem to action in the Effects Stack 

As Paul requested in his pull request I tested subsequently launching 3.2.2 and 3.2.1 and there I observe that the four Audacity RT effects are _**not**_ available in the Effects Stack.
