### ISSUE TITLE
Get selection time via pipe / NyquistPrompt command

### ISSUE THREAD

**Issue by buggymcbugfix** [audacity/audacity#407]
I'm trying to get the start and end times of the current selection for scripting purposes but I have only managed to _set_ the time via `SelectTime:`.

I am looking for some command `GetTime:` which returns the information that is displayed in the audio position toolbar:
<img width="694" alt="Screenshot 2020-01-03 at 02 12 35" src="https://user-images.githubusercontent.com/17603372/71703795-8ec4da80-2dce-11ea-918b-8764bb2a9d61.png">

**Comment by buggymcbugfix** [comment]
I am aware that Nyquist can get this information, but I have not managed to funnel this information out of Audacity via the pipe.

**Comment by SteveDaulton** [comment]
I don't think it's possible to get the selection times "down the pipe", but
also, I've not yet seen a case where that is really needed.
I'd suggest that you write into the Audacity forum and describe what you
are trying to do - the forum is the main Audacity help channel.
https://forum.audacityteam.org/viewforum.php?f=69

Steve
