### ISSUE TITLE
Eset reports a threat when trying to download audacity

### ISSUE THREAD

**Issue by orbennatan** [audacity/audacity#4079]
### Bug description

Just tried to download exe for all platforms

### Steps to reproduce

Go to https://audacite.org/?gclid=CjwKCAiA7vWcBhBUEiwAXieItj3J_YxIYGXGuuVxEGgsZ8CwthiZ5wMDrACpM956vqvqxtbimcUzixoCoswQAvD_BwE
Click on Download audacity
If Eset is installed you will get the following message
![ThreatOnAudacity](https://user-images.githubusercontent.com/9202352/208252592-0f82a79f-c327-4f30-bb83-67fc2d508202.png)

### Expected behavior

Download without any security report from Eset

### Actual behavior

There is a threat report from Eset
![ThreatOnAudacity](https://user-images.githubusercontent.com/9202352/208252654-015126dc-c6ee-4c0b-b1e6-89b5b557718c.png)

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by crsib** [comment]
Unfortunately you have downloaded Audacity from a skam website. This site has been reported already by our team, but still operates 

Please download Audacity from the official website 
https://www.audacityteam.org/download/
