### ISSUE TITLE
Yellow Vertical Snap Lines are NOT behaving.

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#4082]
### Bug description

I ran into this difficulty while trying to document another possibly unrelated issue.

The Yellow Vertical Snap Lines that we all use to line up audio on different tracks is not behaving.

### Steps to reproduce

1) Tools > Reset Configuration
2) Generate 20 seconds of sine tone
3) Near 10 second mark, Ctrl+I = Split
4) Tracks > Add New > Mono Track
5) Grab first clip on clip name bar near 8 second mark and attempt to drag clip straight down.
6) While dragging clip....

### Expected behavior

A yellow guide lines appears and the clip can be dropped exactly in place, so it located exactly at the same place in time, yet on the second track.

### Actual behavior

Any of several different conditions occur randomly, including (while dragging):

1) The yellow guide line does not appear, and yet the clip "appears" to have been dropped in the correct location.  However, we may not know this without zooming into the sample level.
![ClipCenter](https://user-images.githubusercontent.com/76828213/208264010-6b96ff4f-d134-49e1-b9c6-c6b6f4611cc6.png)

2) The yellow guide line does appear and simultaneously left-pointing arrows appear at the beginning of the clip.  You would think this would be an impossibility, yet it happens:
![ClipLeftArros](https://user-images.githubusercontent.com/76828213/208264024-d5ff671d-31a3-44dd-b895-2e5dd8708ed3.png)

3) The yellow guide line does appear but not until the clip is shifted slightly to the right, clearly in the wrong place:
![ClipRight](https://user-images.githubusercontent.com/76828213/208264041-ac4d7741-d570-47fe-993a-4006a28e2945.png)

4) The yellow guide line does appear but not until the clip is shifted slightly to the left, with arrows noting that the audio will be started before time 0.
![ClipLeft](https://user-images.githubusercontent.com/76828213/208264046-948f9c19-c964-4051-8e7a-95685098632d.png)

### Audacity Version

stable version (from a Linux repository)

### Operating system

Windows

### Additional context

See also #3680

**Comment by JohnColket** [comment]
Additional information:
The yellow line seems to want to be in the approximate location the clip first appeared in the lower track while dragging. Specifically, if I drag the clip one second to the left prior to dropping it down, it is likely the clip will be to the left when the yellow line appears, and if I push the clip what might be one second to the right while dragging, the yellow line appears when the clip is lined up with this position.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with 3.2.2

I can reproduce this at times but not reliably or repeatably.

But I do not that if one of the clips is selected before the line-up adjustment the the yellow clip lines appear to work properly.

**Comment by dozzzzer** [comment]
I could never reproduce items 3 & 4 from **Actual Behavior**, so, given that, I think P3 would be a fairer tag for it.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
