### ISSUE TITLE
No (easy) way to re-order effects in an Effects Stack

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4093]
### Bug description

Try to re-arrange the effects in a track's Effects Stack _(similar to the way a user can re-arrange tracks)_ by:
a) click&drag
b) a menu item from an effect in the stack

There is no facility for this all you can do is delete effects and replace them in the order you want in the stack
a) this is tricky
b) it's prone to error
c) you lose the settings

### Steps to reproduce

1. get some audio
2. click on the **Effects** button in the TCP
3. add some effects to the stack
4. try to re-arrange the order of the stack (without deleting and re-adding effects)
5. Observe:  you can't

### Expected behavior

The user should be able to arrange the effects order in a similar manner as to how they are able to re-arrange the track order

1) with click&drag on the effect in the stack

2) from the effects drop-down menu - similar the the TCP dropdown menu
![image](https://user-images.githubusercontent.com/50205984/208906588-0daef485-84b6-4ae9-8d6b-765b125e139f.png)

### Actual behavior

No ability to re-arrange the order of effects in an Effects Stack - except by deleting and re-adding - and note that this loses the user's careful effect settings.

### Audacity Version
3.2.2, 3.2.3 Beta and 3.3.0 alpha

### Operating system
Windows 10 - but assume all OS

### Additional context
Tagging @LWinterberg @DilsonsPickles  and @Tantacrul

**Comment by LWinterberg** [comment]
https://user-images.githubusercontent.com/87814144/208911040-24184630-1de7-47ed-b2c9-6f9f03e6958d.mp4

**Comment by Tantacrul** [comment]
> Audacity_tZgsQaqPq1.mp4

Exactly. I'm completely puzzled by this issue.

**Comment by petersampsonaudacity** [comment]
The fact that I didn't "find" it (and logged this issue)shows that is is nor readily "discoverable"  _<sighs deeply>_

_But "it's easy when you know how" as me ol' mum used to say ..._

**Comment by Tantacrul** [comment]
I was worried the function was broken or something. Anyway:

1. The grips will be more discoverable in the Qt version, for sure
2. I think a context menu option to move an effects up/down makes sense
3. We've also added shortcuts (alt+up/down)

**Comment by DavidBailes** [comment]
> 3\. We've also added shortcuts (alt+up/down)

which unfortunately are neither discoverable or documented. See https://github.com/audacity/audacity/issues/3504

**Comment by petersampsonaudacity** [comment]
The "**grips**" and their use are also not documented in the GitBook documentation:

https://support.audacityteam.org/audio-editing/using-realtime-effects



> 2. I think a context menu option to move an effects up/down makes sense

That makes eminent sense to me as that is where I tried to find suchlike by clicking on the LDPT (liitle black downward pointing triangle)

**Comment by petersampsonaudacity** [comment]
I got my "Mystery-Shopper" to test drive this.

1.  first she tried to click&drag on the effect names (as did i)
2.  then she tried the LDPBT, looking for a context menu
3. next she tried clicking on the blue switch - she quickly realized the on/off-ness
4. finally she eventually spotted the grips
