### ISSUE TITLE
Compressor - Upward/Downward compression modes

### ISSUE THREAD

**Issue by emtiu** [audacity/audacity#4098]
### Your idea

The Compressor setting **"Compress based on Peaks"** should be renamed and made more prominent.

It's the single most important setting to the Compressor, but it's hidden away at the bottom of the dialog, and its name completely uninformative and unintuitive.

The manual describes its function quite well (https://github.com/audacity/audacity-manual/blob/47f3a7e784d0801bc9beb3eb196d1fecbdceae68/manual/man/compressor.html#L54-L56), but this information is unnecessarily hidden:

> **Compress based on Peaks**: Base the threshold and gain adjustment on peak values of the [waveform](https://manual.audacityteam.org/man/audacity_waveform.html) rather than the average (RMS) value used when in default (unchecked) state. 
> * When using RMS, the compressor uses "downward" compression, making louder sounds above the threshold quieter while leaving quieter ones below it untouched.
> * When using peak values, "upwards" compression is applied which makes the audio louder, but amplifies the louder sounds above the threshold progressively less than those below it. Where the original (input) level is 0 dB there is no amplification.

Currently, the dialog looks like this:
![Screenshot_20221222_131559](https://user-images.githubusercontent.com/2159933/209133709-3a887007-c6a1-4857-b946-8e14c9b6ff07.png)
Note that this most important setting **Compress based on Peaks** is hidden away at the bottom.

I suggest to make it a radio button setting named after the much more intuitive descriptions in the manual: **"Upward compression"** and **"Downward compression"**. The "Make-up gain …" setting would only be available for Downward compression, because AFAIK it has no effect on Upward compression:

![Screenshot_20221222_131559_](https://user-images.githubusercontent.com/2159933/209136304-4162eb80-cdf0-4d41-87b6-41da18a2572d.png)

### Problem to be solved

Users have a hard time understanding what the Compressor does, and how to achieve the desired effect.

**Comment by LWinterberg** [comment]
> I thought that it had been agreed earlier that the action buttons in the Effects, Generators, Analyzers and Tools (EGATs) would be returned to the more conventional position at the bottom of the dialogs.

yes, see https://github.com/audacity/audacity/issues/3615

**Comment by SteveDaulton** [comment]
> The manual describes its function quite well


As the documentation is obviously useful, maybe built-in effects could have context sensitive help so that users can find that documentation easily.

**Comment by SteveDaulton** [comment]
> I suggest to make it a radio button setting named after the much more intuitive descriptions in the manual: **"Upward compression"** and **"Downward compression"**.

but that hides the extremely important distinction that one uses RMS levels and the other uses peak  levels.

**Comment by emtiu** [comment]
> but that hides the extremely important distinction that one uses RMS levels and the other uses peak levels.

Then just add those words, and make it: **"Upward compression (by peak levels)"** and **"Downward compression (by RMS levels)"**.

Still better than to hide the information on whether the applied action will actually make things louder or quieter.

**Comment by SteveDaulton** [comment]
Maybe better to write a new compressor from scratch. Audacity's compressor is both limited and quirky.

**Comment by petersampsonaudacity** [comment]
> Maybe better to write a new compressor from scratch. Audacity's compressor is both limited and quirky.

See:   Create a Chris-like compressor for Audacity #2397

**Comment by emtiu** [comment]
A big rewrite notwithstanding, the suggested UI change will still make the workings of the current Compressor much more understandable.

**Comment by LWinterberg** [comment]
We're replacing this compressor with a new one. Regarding the manual quote, either the manual is wrong or the current compressor is extremely weird - Peak vs RMS should just be deciding whether to detect peak or RMS as the threshold value. In each case, this compressor won't be updated anymore.

**Comment by emtiu** [comment]
> We're replacing this compressor with a new one.

Is there an Issue or PR to follow that development?

**Comment by SteveDaulton** [comment]
> Is there an Issue or PR to follow that development?

This looks like it: https://github.com/audacity/audacity/issues/6305

**Comment by petersampsonaudacity** [comment]
As Steve says - and this pill request:

https://github.com/audacity/audacity/pull/6306
