### ISSUE TITLE
Reverb: let users hear processed sounds while they tweak some of the parameters

### ISSUE THREAD

**Issue by pietro68** [audacity/audacity#4107]
At the moment, each time any of the reverb parameters is tweaked, users will not hear the reverb wet sound for as long as they keep moving any slider. This is because some parameters, when tweaked, require a full reinit of some components.

But some of the parameters do not actually require a full reinit in principle - these are:

- Reverberance
- HF Damping
- Tone Low
- Tone High
- Wet Gain

The goal here is to make the reverb keep making sound when one of the above parameter is tweaked.

**Comment by dozzzzer** [comment]
Verified
