### ISSUE TITLE
Macro/Scripting Method "Export2:" shows a dialog on windows 10 instead of being silent

### ISSUE THREAD

**Issue by krupper** [audacity/audacity#411]
**Bug Description**
The "Export2:" Method from the macro / scripting section opens an export dialog.

**To Reproduce**
1. Go to 'Tools'
2. Go to 'Macros'
3. Click on 'New'
4. Enter a name
5. Add a new Step
6. Select "Export2"
7. Apply macro on Project
8. See export dialog

The bug also ocours if you trigger the method via scripting (through the pipe).

**Expected behavior**
The export should be done in the background without promting a dialog.
The method is documented here: [https://manual.audacityteam.org/man/scripting_reference.html](https://manual.audacityteam.org/man/scripting_reference.html)

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version: Audacity 2.3.3

Thank you guys for your work! :-)

**Comment by SteveDaulton** [comment]
Thanks for the report, but I'm not able to reproduce this issue (testing with the latest Audacity 2.4.0 alpha source code). Please note that Export2: requires that "Filename" needs to be a fully qualified file name (including the full path and file extension). If you still have problems with this, please come and discus it with us on the Audacity forum and I think we should be able to get it working for you. https://forum.audacityteam.org/viewforum.php?f=69

**Comment by finn64** [comment]
Did you ever enable debug output? I sometimes found that the same function will continue to output debug info even when deselected

**Comment by JamesCrook** [comment]
Closed could not reproduce.  (also request to move to forum)
