### ISSUE TITLE
Cloud upload does not take panning into account when evaluating the number of channels

### ISSUE THREAD

**Issue by crsib** [audacity/audacity#4114]
### Steps to reproduce

[test_audio.aup3.zip](https://github.com/audacity/audacity/files/10303294/test_audio.aup3.zip)
1. Try to upload the attached file
2. Observe, that the result is mono

### Expected behavior

Stereo file should be uploaded

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows, macOS, Linux

### Additional context

Workaround for now is to add an empty stereo track to the AUP3

**Comment by dozzzzer** [comment]
Tested
