### ISSUE TITLE
Fix RT effect drag'n'drop

### ISSUE THREAD

**Issue by vsverchinsky** [audacity/audacity#4121]
- Effects in RT panel cannot be rearranged with drag'n'drop on Linux (Ubuntu)
- Effects drag start area should be limited to drag handle area (all platforms)

**Comment by petersampsonaudacity** [comment]
>     * Effects in RT panel cannot be rearranged with drag'n'drop when drag starts over a button element (all platforms)

Do you mean the on/off button and/or the context mevu button

My understanding is the Click&Drag in the Effects Stack only works with the drag buttom
![image](https://user-images.githubusercontent.com/50205984/209704059-00cfbb2a-0606-400e-b393-b286bc05bd6e.png)
And that works fine for me on W10 with 3,2,2, 3.2.3 Beta and 3.3.0 alpha

**Comment by vsverchinsky** [comment]
> Do you mean the on/off button and/or the context mevu button

Turns out that the design document specifies that reordering should be possible only with grab handle. I'll update task description

**Comment by LWinterberg** [comment]
closing as it won't be fixed before the Qt transition, and Qt will have its own set of drag'n'drop problems
