### ISSUE TITLE
Scroll down the effects menu

### ISSUE THREAD

**Issue by Voyager-III** [audacity/audacity#4124]
### Your idea

Would it be possible to make the mouse scroll wheel to scroll up and down the effects menu instead of having to click on the up and down buttons it would be alot quicker to select the effect you need, Thank you

### Problem to be solved

Quick access to the different effects on the effects menu

**Comment by LWinterberg** [comment]
Audacity 3.2 alleviates this problem somewhat by introducing a new grouping option, and those weird up/down scroll buttons won't make it over to Qt anyway
