### ISSUE TITLE
[Bug] Mac save file window fail to use Command+V ect' properly

### ISSUE THREAD

**Issue by zxzzz8** [audacity/audacity#413]
MacOS High-Sierra 10.13.6, audacity version 2.3.3.

in the saving-project-as window....
when i try to use all the keyboard commands, like copy, paste or Command+a [mark all], it fail or screw things up:
when i try to paste something into the text, it instead reset it and paste my thing INSTEAD of what was in the box already, for example if i wrote ''some file name from today'' and i mark only the ''today'' or the spot after the word, in either case when i try to paste something like ''2020-01-12'' it instead erasing everything up and putting just the ''2020-01-12'' over,
like so:
some file name from today .aup
turn to
2020-01-12.aup
instead of 
some file name from today 2020-01-12.aup
or
some file name from 2020-01-12 .aup

as for all the other stuff like copy and mark all, they just make some system sound and fail....
right click and choosing the options like copy and paste from the menu work fine btw.

its been really bugging me for a while now, giving me so much hell, and also so many times i forgot audacity do it, writing some long name and then pasting something in the end only to get all what i wrote beforehand deleted, and i can't undo ect' coz the undo also fail like copy and mark-all and just do the system sound, and undo don't even exist in the rightclick menu....

i tried to update right now from 2.3.2 to 2.3.3 in hopes you fixed it, but sense you didn't then you might not be aware about this bug....

so please fix? its driving me like crazy, thanks for reading.

**Comment by petersampsonaudacity** [comment]
This now works on my Macbook Pro with macOS 11.2.3 Big Sur on 3.0.2 and the latest alpha test build I have for the upcoming 3.0.3

Cmd+V to paste a filename works for
a) Save Project
b) Save Project AS
c) Backup Project.

IIRC I think we fixed this for the 3.0.0 release.
