### ISSUE TITLE
Add a Delete button to the Cut/Copy/Paste toolbar

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4131]
### Your idea

The new Cut/Copy/Paste toolbar toolbar has been implemented with an empty bottom right cell.

This is not following the original Figma design spec, by designer @DilsonsPickles 
>Here's the Figma link to the design specification: https://www.figma.com/file/uYdHVW7Hhkha51ZGGfC3RF/09_WX---Tools?node-id=328%3A4323
>
>Or [click here](https://www.figma.com/file/uYdHVW7Hhkha51ZGGfC3RF/09_WX---Tools?node-id=328%3A4323)

It also looks a tad ugly and unfinished with the empty cell.

It may have been removed die to a belief that **Cut** and **Delete** do the same thing making the Delete superfluous.  This is _**not**_ the case as Cut replaces the contents of the clipboard whereas Delete does not - and the user may want the carefully placed prior contents of the clipboard to be retained there.

### Problem to be solved

**As implemented in 3.2.3**
![image](https://user-images.githubusercontent.com/50205984/209966212-ddc0fb9f-b1e9-4d34-a39f-f6b76b311957.png)

**As specified by @DilsonsPickles in the Figma design** 
![image](https://user-images.githubusercontent.com/50205984/209966571-5e6aa167-3aaf-4324-bcbe-fb5b89903a3b.png)

### Prior art

**Paint3D**
Here's an example from Microsoft's Paint3D which has a similar toolbar - and that does have a Delete button in addition to Cut, Copy and Paste.

![image](https://user-images.githubusercontent.com/50205984/209966037-5b337206-9ee6-4404-ba7a-a9ec14808dd8.png)

### Additional context

See also:   Restore the Cut, Copy and Paste buttons as a new (hidden by default) toolbar #3693

**Comment by abhi-kr-2100** [comment]
Is there a reason why one needs to request before viewing the design specification at https://www.figma.com/file/uYdHVW7Hhkha51ZGGfC3RF/09_WX---Tools?node-id=328%3A4323?
![image](https://user-images.githubusercontent.com/66527624/210158021-e7dcb0d7-65fd-47e2-a014-ec269c9ebfe3.png)

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @abhi-kr-2100 's   branch build:  audacity-win-3.3.0-alpha-20230101+c23548e-x64-msvc2022

This looks good to me in this branch build:

a) The Delete button does indeed delete the selection - and properly does _**not**_ replace the clipboard contents

b) the Cut button deletes the selection - and properly **_does_** replace the clipboard contents

![image](https://user-images.githubusercontent.com/50205984/210173342-298fb047-d905-48e5-9441-7d6e54a9fc61.png)

**Comment by DilsonsPickles** [comment]
Hi @abhi-kr-2100 - I've granted you access to the project file.

**Comment by abhi-kr-2100** [comment]
Thank you, @DilsonsPickles.

**Comment by Ryan-Miller-Audacity** [comment]
Verified the addition and behavior of the delete button within the cut/copy/paste toolbar as well as retention of previous cut/copy/paste toolbar behaviors on both Windows and MacOS.

**Comment by petersampsonaudacity** [comment]
I have updated the Reference Manual for this:
https://alphamanual.audacityteam.org/man/Cut_Copy_Paste_Toolbar
and
https://alphamanual.audacityteam.org/man/Toolbars_Overview

**Comment by petersampsonaudacity** [comment]
And my thanks too to @abhi-kr-2100  - and to the Muse guys for pulling this fix through into 3.3.0 alpha

**Comment by abhi-kr-2100** [comment]
Thank you, you too @petersampsonaudacity for pointing out the issue and updating the reference manual.
