### ISSUE TITLE
Use of the right/left arrows is laggy/jumpy with full screen (or wider than default window size)

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4132]
### Bug description

On Windows at default Audacity widow size (or narrower)  use of the right/left arrows to move the cursor position is relatively smooth

_**BUT**_  if you expand the Audacity to full-screen (or wider than default) the cursor movement is noticeably laggy/jumpy with full screen (or wider than default window size).

Testing shows that this is a regression on 2.3.3, introduced in 2.4.0

_I have not yest tested on Mac, I cannot test on Linux._

### Steps to reproduce
1. clear audacity settings folder _(to obtain default settings)_
2. get a 3 minute song
3. place cursor at T=0
4.  hold down the right-arrow key
5. Observe : cursor moves steadily across the waveform
6. Set the Audacity window to full-screen
7. place cursor at T=0
4.  hold down the right-arrow key
5. Observe : cursor moves laggily/jumpily across the waveform

### Expected behavior
Smooth cursor movement at all window widths

### Actual behavior
Jumpy/laggy cursor movement at full-screen

This appears to be independent of the zoom level

### Audacity Version
3.2.3 and 3.3.0 alpha  _(and all versions 2.4.0 onwards)_

### Operating system
Windows 10

### Additional context
17 inch HP Envy laptop running Windows 10

Originally notice when testing following a Forum post where the user was claiming cursor movements of one Pixel per second on M1 Mac:
https://forum.audacityteam.org/viewtopic.php?f=70&t=122203&p=461608

**Comment by petersampsonaudacity** [comment]
Testing with 3.2.3 on macOS 12.6.2

The situation is _**MUCH**_ on Mac

1) the cursor does not  visually move until the arrow key is released

2) the "cursor" in the Timeline does move, bit it crawls extremely slowly across the top of the waveform waveform

3) when the arrow key is released then the cursor is repainted on the waveform at the same position as the "cursor" in the Timeline.

This concurs with the findings of the poster in the Forum - and makes the use of the left/right arrows to move the cursor effectively absolutely unusable.

**Comment by crsib** [comment]
macOS is slowest platform UI wise right now, so no surprise for me here, unfortuantely.

**Comment by crsib** [comment]
Just some random info - if you use Alpha builds - there is a dialog that measures the time needed to draw TCP in Help->Diagnostics->Frame Statistics. 

I've checked on my M1 13'' MacBook Pro - it takes 36 ms when upadting the top ruller and 46+ ms when updating the track itself.

On top of that - performance is really sensitive to the width of the window.

**Comment by petersampsonaudacity** [comment]
Testing on Mac shows that _(unlike on Windows where this is a regression on 2.3.3)_ this is present on all 64-bit versions of Audacity on Mac i.e. 2.3.1 onwards.  

I cannot test earlier on Mac as prior to 2.3.1 Audacity on Mac was only 32-bit and my Macbook is 64-bit an Apple do not allow 32-bit apps to run on 64-bit Macs.

**Comment by SteveDaulton** [comment]
On my Linux laptop, it's  a bit jumpy / laggy, but not critically bad.

**Comment by crsib** [comment]
Linux is the fastest one, yes. Windows sits somwhere in between, but it is critically affected by the window width.

**Comment by LWinterberg** [comment]
I'm going to close this for the same reason as other performance bugs - it's not going to be fixed in wx, and in qt there'll be an entirely new situation
