### ISSUE TITLE
copypasting a smart clip also pastes zero-length clip adjacent

### ISSUE THREAD

**Issue by billw58** [audacity/audacity#4134]
### Bug description

In some cases when pasting a clip it appears that a "phantom clip" is created at the right edge of the pasted clip. This prevents expanding the pasted clip and interferes with dragging the pasted clip (or any other clip in the track).

### Steps to reproduce

1) New project
2) Generate Chirp
3) Click somewhere and Split
4) Double-click left clip and Copy
5) New Audio Track
6) Paste
7) Try to expand the pasted clip to the right
- it will probably work, but might not; if it works …
8) Double-click the clip in the second track and delete it
9) Click somewhere inside the left clip and Split
10) Double-click left clip and Copy
11) Click in the second audio track and Paste
12) Try to expand the pasted clip to the right
- it will probably not work, but if it does …
13) Repeat steps 8 through 12 until you get a pasted clip that can’t be expanded
14) Try to move the clip to the right
- if you drag the pointer far enough the clip will snap to be under the pointer
- note that there is a black line (phantom clip?) at the position of the right edge of the clip pasted in step 11
- if you drag the clip to the right of the phantom clip then it can be expanded to the right

### Expected behavior

The pasted clip should be expandable to the right if there was audio to the right of the clip when it was copied

### Actual behavior

Sometimes the pasted clip cannot be expanded to the right. There appears to be a "phantom clip" to the right of the pasted clip that interferes with expanding and dragging.

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

**Comment by petersampsonaudacity** [comment]
Also try this>

1. generate 30 second chirp
2. split it at 15 secs
3. move the second clip 15 seconds to the right
4. Select the first clip and Copy
5. New traclk
6. Paste
7. Observe you can expand it to the right - _**BUT**_ the 15 second gap is missing and the two clips run from 0 to 30 wecs

![image](https://user-images.githubusercontent.com/50205984/210179906-a7022425-7556-4c0a-84b4-25166647bfc1.png)

---------------------------------------------------------

Th underlying behaviors here are leaving me totally foxed and puzzled ...

I thought that if you made a selection from part of a clip and then used copy that just the full **_clip_** would be forming the new "smart clip".

But instead it looks like the whole **_track_** forms the copied "mart clip" - AND with blank space ignored.

**Comment by petersampsonaudacity** [comment]
See also this Discussion thread:  Is Split intended to make "smart clips" containing all the audio #4137

**Comment by SteveDaulton** [comment]
Also occurs with Audacity 3.3.0-alpha 5f511d (AppImage) on Linux.

**Comment by LWinterberg** [comment]
NB:

* this also happens when you click on the clip handle instead of double-clicking inside the clip
* The "phantom clip" is 0 samples long and its visuals stop rendering properly when zooming in
* I haven't had any luck reproducing it in 3.2.3; this might be a regression

**Comment by billw58** [comment]
For me this happens reliably (more than half the time!) in 3.1.0 through 3.2.3. I didn't go back any further.

In step 6 (or 11) it is worth clicking in the second track somewhere other than 0 sec - sometimes the phantom clip is on the left of the pasted clip.

**Comment by SteveDaulton** [comment]
Considering that this issue is about "phantom" clip boundaries appearing intermittently, I'm wondering if it's related to https://github.com/audacity/audacity/issues/4146

**Comment by LWinterberg** [comment]
found a report on 2.3.3: https://forum.audacityteam.org/viewtopic.php?t=111075

**Comment by SteveDaulton** [comment]
I think this should still be considered a "regression". Yes there have been _similar_ issues in the past, but not caused as easily as splitting a clip (which is what is happening now). In my opinion it is extremely likely that this is a different issue to the one mentioned in that forum post, despite sharing a common symptom.

**Comment by dozzzzer** [comment]
Verified
