### ISSUE TITLE
Updating to 3.2.3 Gets Stuck on Verifying Audacity.app for older Macbooks (OSx 10.13.6 / Intel Chip)

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#4139]
### Bug Description
Users on older MacOS systems (High Sierra / Intel chips) have reported that the app gets stuck when updating to 3.2.3 on the "verifying" step when opening the newly updated app. I was not able to reproduce this on my newer Mac (M1 Macbook Air on MacOS 12.3.1), but was able to reproduce on my older Mac (Intel 2011 Macbook Air on MacOS 10.13.6).

### Steps to Reproduce
1. On a older MacOS system (High Sierra / Intel Chip) open Audacity 3.2.2 and check for updates
2. Select install on the update to 3.2.3 prompt
3. Close the previous audacity window and select replace on the multiple copies prompt
4. Open the newly updated Audacity app
5. Note that the app gets stuck on "verifying" and doesn't open

### Expected Behavior
The app finishes verifying and opens without issue.

### Actual Behavior
The app gets stuck on verifying and does not open.

### Audacity Version
3.2.3

### Operating System
Older versions of MacOS

### Additional Context

Two forum users cannot seem to get 3.2.3 to get past system verification while 3.2.2 and prior seem to have no problems.

See: https://forum.audacityteam.org/viewtopic.php?f=47&t=128517

**Comment by Ryan-Miller-Audacity** [comment]
Testing on both a new Macbook Air (M1 Chip) running MacOS Monterey 12.3.1 as well as an old Macbook Air (2011/Intel Chip) running MacOS 10.13.6, I did not experience any freezing during the installation process of 3.2.3 on the verifying portion or otherwise. I was able to successfully run the installer and get past the system verification for all three MacOS options (Universal, ARM, and x86_64). 

FYI /cc @dozzzzer

**Comment by Ryan-Miller-Audacity** [comment]
After further investigation, I can reproduce this issue specifically when *updating* the app from to 3.2.3; however, fresh installs downloaded from audacityteam.org work perfectly fine.

**Comment by voluum2** [comment]
Having this issue also. Reported on Audacity forums. MACOS 10.14.6, Fresh install

**Comment by typonaut** [comment]
Also experiencing this problem MacBook 7,1 (Intel Core 2 Duo 2.4GHz, 16GB ram, 1TB SSD - approx 240GB free space) MacOS 10.13.6. This is a new installation, not an update - ie no previous version of Audacity (found this file in MacPorts "patch-audacity-portmixer.diff").

**Comment by wjrl** [comment]
Hi. I am also experiencing this problem trying to install 3.2.3 on my Late 2014 Mac Mini (2.6 GHz Intel Core i5; 8 GB) running macOS 10.13.6 (17G66) (High Sierra). My system has never has Audacity on it; this is a fresh install. The verification process appears to launch the XProtectService, which appears to slowly grow and grow. As the attached figure show, the Verify stall is accompanied by slowing increasing memory pressure, and my machine eventually starts to thrash and needs to be rebooted.
![Audacity-Verify-1](https://user-images.githubusercontent.com/4065595/211188100-a52ba479-c8dc-41d9-b806-07b10d3448d1.png)
![Audacity-Verify-2](https://user-images.githubusercontent.com/4065595/211188109-84795150-59c2-4971-a9c1-abd58cba0c49.png)

The state of the XProtect service might be relevant for this problem. Here is the version and the date of the malware definitions:

```
userName$ defaults read /System/Library/CoreServices/XProtect.bundle/Contents/Resources/XProtect.meta.plist Version
2099

userName$ ls -l /System/Library/CoreServices/XProtect.bundle/Contents/Resources/XProtect.plist
-rw-r--r--  1 root  wheel  113976 Mar  8  2018 /System/Library/CoreServices/XProtect.bundle/Contents/Resources/XProtect.plist
```

**Comment by jessewchu** [comment]
This problem still exists in 3.2.4. The solution above does work for me, though: installing from the audacity-macOS-3.2.4-x86_64.dmg works, but using the universal image, my 2015 Macbook Pro running 10.14.6 Mojave stalls at "Verifying" when first starting Audacity.

**Comment by Ryan-Miller-Audacity** [comment]
Given the small subset of users effected and workarounds present (github assets page, intel x86 packages etc.) this is not something that we intend to pursue fixing. We will also update the compatibility list as suggested on the forum.

**Comment by Mowgliart** [comment]
I just went through the process explained here and managed to install Audacity on my Mac. Now Macros don't work. I'm trying to convert some files to mono .wav and nothing happens. Trying to access the Audacity forum results in: This site can’t be reached forum.audacityteam.org refused to connect...
Any solutions?

**Comment by JohnColket** [comment]
> Trying to access the Audacity forum results in: This site can’t be reached forum.audacityteam.org refused to connect...

The forum is under maintenance at the moment as the database is being migrated. It should be back in a few days.

**Comment by dozzzzer** [comment]
> Trying to access the Audacity forum results in: This site can’t be reached forum.audacityteam.org refused to connect...

UPD: The new forum is live now.
