### ISSUE TITLE
add more decimal numbers in change speed to correct sync audio with video

### ISSUE THREAD

**Issue by kedaitinh12** [audacity/audacity#4140]
### Your idea

I think need more decimal numbers in change speed of audio

### Problem to be solved

I try change my dub audio from bad quality video 23.976 fps to correct original audio from good quality video 25 fps. When i change speed multiplier is 1.042 but the result don't sync with good quality video. I findout my correct speed multiplier is 25000/23976=1.0427 but i can't add more decimal number and i try with speed multiplier is 1.043 but audio still don't correct too. You think 1.0427 very small number but it's will don't sync if audio very long than 1 hr 20 mn

### Prior art

I try with megui and successful cause they have option to correct fps exactly. I think you can add this function one to Audacity in the future

![image](https://user-images.githubusercontent.com/66716952/210338632-8e9c1e85-732e-48a8-a0cd-efa2c5929ab9.png)

**Comment by LWinterberg** [comment]
Removing the good first issue tag; it's not entirely clear to me how to exactly add the these options in a way that's comprehensive while also not clashing with the vinyl tags. 

FWIW: If you know the target length in frames, you can type in the frames directly by switching the time input to frames.
![image](https://user-images.githubusercontent.com/87814144/210589409-e63dcb47-213d-46d7-b02e-e49ed2d6f1df.png)

**Comment by kedaitinh12** [comment]
I try with edit hh:mm:ss length but ouput outdio still don't corect my setting. Example i type from 1:28:32 to 1:28:18 but the result is 1:28:15

**Comment by SteveDaulton** [comment]
> I think need more decimal numbers in change speed of audio

I disagree.
The Change Speed effect _should_ be sample accurate, but to achieve sample accuracy for long or high sample rate tracks would require a lot of decimal places. This would be overkill and distracting clutter for the majority of users.



> I try with edit hh:mm:ss length but ouput outdio still don't corect my setting.

That's a bug that needs fixing. https://github.com/audacity/audacity/issues/3688

**Comment by kedaitinh12** [comment]
Ok, wait for that fix but i still think need more decimal numbers in change speed of audio

**Comment by SteveDaulton** [comment]
> Ok, wait for that fix but i still think need more decimal numbers in change speed of audio

but if you want sample accuracy with just a 2 hour track @ 44100 Hz sample rate, you would need about 10 decimal places.
Imo it's much better to use the time controls, which are designed to handle sample level precision.

**Comment by kedaitinh12** [comment]
Ok, i don't think it's need very many more decimal numbers. In my example just add one more number to correct 25000/23976=1.0427

**Comment by kedaitinh12** [comment]
Ok, when i need change speed, say goodbye with Audacity, Megui is better. Bye
