### ISSUE TITLE
Erroneous behaviors in the Cut/Copy/Paste toolbar and Edit menu

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4148]
### Bug description

When audio is present in an Audacity project but no selection is made in the audio the the buttons and commands for **Cut, Copy and Delete** are erroneously black and active.  

Using them is this state causes an error message to be displayed as they are basically non-functional in this state.

The **Copy** button appears to be always active/black - but its counterpart **Edit>Copy** command is grayed-out and inactive.

**1) At Step 4**
![image](https://user-images.githubusercontent.com/50205984/210755771-4dd9eb00-e032-400a-aea4-327c5c7d1c95.png)

**2) at Step 8**
![image](https://user-images.githubusercontent.com/50205984/210752636-5e564323-f3d7-4e67-90ea-4aadcb4066f2.png)

a) The Cut/Copy erroneous behavior is a regression on 2.2.0
b) the Paste behavior is a regression on 2.1.2
c) The Delete button is new to 3.3.0 alpha (see #4131 )- but is also erroneous in its behavior

### Steps to reproduce

1. launch 3.3.0 alpha **(3.2.3 does the same, but has no Delete button)**
2. Observe: Cut, Copy and Delete buttons are grayed out and Paste button is black/active
3. Edit command
4. Observe: Cut, Copy and Delete commands are grayed out and Paste command is black/active  _-  see image 1_
5. Get some audio (or even a blank audio track with add new track) - make _**no**_ selection
6. Observe: Cut, Copy, Delete and Paste buttons are black/active
7. Edit command
8. Observe: Cut, Copy, Delete and Paste commands (and Duplicate)  are erroneously black/active (as there is nothing to act on)   _-  see image 2_

_Note that this does _**not**_  happen if at step 5 you add an empty label track to the empty project_

### Expected behavior

Buttons in the Cut/Copy/Paste toolbar and their associated commands in the Edit menu should be grayed-out and inactive where there is nothing to act  on or work with.

_@crsib Dmitry assures me that the buttons shadow and take their state from their associated Edit commands._

### Actual behavior
See above

### Audacity Version
3.3.0 latest alpha and 3.2.3

### Operating system
Windows 10 - but suspect all OS

### Additional context
@Tantacrul   -  this, I think, explains the differences in behavior you and I were observing with these buttons when testing the new Delete button.

Having these buttons and commands properly grayed-out and inactive would remove a lot of unnecessary error messages being shown to users ((the messages have to stay as the shortcut commands are **always** "available"):
![image](https://user-images.githubusercontent.com/50205984/210759239-b1bcf920-8c0b-4d22-a271-21700bf0a322.png)

See also:  Add a Delete button to the Cut/Copy/Paste toolbar #4131

**Comment by DavidBailes** [comment]
Just to point out that this behaviour is part of a much larger issue.
In Audacity 2.2.0:
1. The default setting of "select all audio in project if none selected" (or other variations of this wording) was changed from enabled to disabled.
2. When this option was disabled, then the behaviour of the commands with acted on selected tracks or selected audio when none was selected was changed. Instead of the commands being unavailable, they were made available, but when executed an error message resulted, telling the user of the lack of selection. 
Lots of commands were affected by this change, eg copy, duplicate, effects, the align track commands in the tracks menu.

**Comment by petersampsonaudacity** [comment]
@DavidBailes  bit the fundamental issue with your number 2 is that 
**IF** no selection is available 
**THEN** commands & buttons that act on selection should be grayed out and unavailable 

This should in **_no_** way depend on whether auto-select-all is either on or off surely - _this is just one (automatic) way of having a "selection" always effectively present if you turn that on._

**Comment by DavidBailes** [comment]
> @DavidBailes but the fundamental issue with your number 2 is that
> **IF** no selection is available
> **THEN** commands & buttons that act on selection should be grayed out and unavailable

I was just providing the wider context and  history of the current behaviour, not commenting on what I think should be the behaviour.

**Comment by petersampsonaudacity** [comment]
> I was just providing the wider context and history of the current behaviour, not commenting on what I think should be the behaviour.

Hahaha David - I was just trying to make sure we didn't replace one of the bear-traps that we carefully removed a while back  ;-))

**Comment by Ryan-Miller-Audacity** [comment]
Ensuring that the cut/copy/paste/delete buttons show accurate active/inactive states can, as Peter, mentioned clear up a lot of unnecessary error messages from appearing and also increase the new user experience with the functions.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
