### ISSUE TITLE
Turning an effect on and off doesn't make the project dirty

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4151]
### Steps to reproduce

1. add an effect in the sidebar
2. save the project 
3. turn the effect on/off by clicking the blue power button
4. ctrl + w

### Expected behavior

The prompt to save the changes in the project pops up

### Actual behavior

The project is closed with no warning

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS

**Comment by Paul-Licameli** [comment]
#4153 is an easy fix for the problem as stated -- but if you press a power button twice for no net change, then the prompt to save when closing will also appear, though unnecessarily.

Should extra work be done to correct that?

**Comment by dozzzzer** [comment]
> Should extra work be done to correct that?

I'd say it's not necessary

**Comment by dozzzzer** [comment]
@Paul-Licameli 
the fix looks good to me, however, in the case when turning an effect on/off by opening its UI first, and then clicking the blue power button, it doesn't make the project dirty. We also need to fix that.

**Comment by dozzzzer** [comment]
Tested
