### ISSUE TITLE
Waveform View and Multitrack View

### ISSUE THREAD

**Issue by izzyreal** [audacity/audacity#417]
**Problem**
I have literally never used Audacity's multi track capabilities. Cool Edit Pro/Audition has a way to switch between Waveform View and Multitrack View. In Waveform View life is very simple. You don't need a project sample rate, you don't see 32 bit after importing a 16 bit file, and everything just makes sense -- within the context of editing a single audio file that is.

Does Audacity have such a feature? If not, would it like to? I think it would be wonderful if Audacity would by default profile itself as an ordinary wave editor. I've tried recommending Audacity to various friends and family, but the current UI doesn't lend itself for any kind of entry-level use. Also ordinary destructive wave editing, like a quick trim, adding silence, resampling, could become more straightforward.

If I'm missing some of the rationale behind all this, please point me to the place to read up on this.

**Solution**
If a feature of this kind is desirable, I'd be happy to help define it in more detail. It's been a while I compiled Audacity from source, but essentially I'm willing to help with/do the implementation.

**Comment by LWinterberg** [comment]
We are not looking to emulate Audition in the regard that you need a special mode to interact with the waveform and another mode to interact with clips. Instead, you should be able to do both in one mode. The recent 3.1 update was a first step in that direction. 

That said, we are looking to introduce workspaces (#1022) which would allow for these kinds of simplifications. One obvious difference between workspaces would be the presence of bars and beats which would be very useful for musicians but very useless for podcasters, and I definitely also want to have a "I just want to do a quick single track recording" mode which allows you to do just a recording and maybe set a simple trim afterwards (the exact details are still in the far future). 

Anyhow, closing this for now. You can follow #1022 to stay updated regarding workspaces.

**Comment by izzyreal** [comment]
Sounds a bit like a missed opportunity to me. Then again, I realise my use case is probably very specific, and tailoring Audacity to it one way or another would be a lot of work, at the cost of not making sense to most existing users.

I'll keep an eye out on https://github.com/audacity/audacity/issues/1022.
