### ISSUE TITLE
Macro Manager and Apply Macro have swapped places in the Tools menu

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4172]
### Bug description
Macro Manager and Apply Macro have swapped places in the Tools menu - and note that there is no longer a divider between Plugin Manager and the Macro commands.

Update from @Paul-Licameli : there will be a fix, and the before and after executables should be tested after deleting audacity.cfg if you switch among them.  (Else the fixed version may contaminate the retesting of the buggy version and mask the bug in it, making it incorrectly appear not reproducible.)

This is regression on 3.2.3   -  and also on recent alpha  audacity-win-3.3.0-alpha-20230111+3840d65-x64-msvc2022

**3.2.3**
![image](https://user-images.githubusercontent.com/50205984/211885806-e0093b2e-599e-426b-8496-5cc7eb5dfabb.png)

**3.3.0 alpha**
![image](https://user-images.githubusercontent.com/50205984/211886417-188f3b7e-3520-4006-af59-a630c9501ec0.png)

### Steps to reproduce
1. launch 3.2.3
2. Tools menu
3. Observe menu
4. close 3.2.3
5. launch 3.3.0 alpha
6. Tools menu
7. Observe: Macro Manager and Apply Macro have swapped places

### Expected behavior
Macro commands ordered the way they are in all previous Audacity releases that have Macro capability - and ordered the way they are shown in the Reference Manual:
![image](https://user-images.githubusercontent.com/50205984/211888395-54d05c3e-5bbc-496e-a045-96f0326bddae.png)

### Actual behavior
Macro Manager and Apply Macro have swapped places in the Tools menu

### Audacity Version
3.3.0 alpha - audacity-win-3.3.0-alpha-20230111+0e209c6-x64-msvc2022 (2)

### Operating system
Windows 10, but assume all OS

### Additional context
Maybe trivial - but conflicts the muscle-memory of those of us who use Macros a lot

**Comment by Paul-Licameli** [comment]
It may be of small importance, but it is an unintended change caused by recent work, that escaped the rest of us.  I mean to fix it in 3.3.  Thank you @petersampsonaudacity

**Comment by Paul-Licameli** [comment]
The draft PR that I linked may not yet solve the issue, but it will not be considered complete and review ready until it does.

**Comment by petersampsonaudacity** [comment]
@Paul-Licameli  I have checked all the other menus and sub-menus (with the exception of the Extra menus as I recall you already said you had ordering problems there with the recent changes).

**_All_** are correct, apart from the two Macro commands already noted in this bug thread.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with  @Paul-Licameli 's branch build:  audacity-win-3.3.0-alpha-20230202+5ac1890-x64

This now has the former correct order in the Tools menu in Paul's branch build
![image](https://user-images.githubusercontent.com/50205984/216626705-f2189c50-ac22-4d50-800f-5cba4e51b301.png)

**Comment by dozzzzer** [comment]
Verified

**Comment by petersampsonaudacity** [comment]
Tested this on W10 with latest alpha master:  audacity-win-3.3.0-alpha-20230206+0c901f9-x64-msvc2022

Confirm this has now properly reverted the Tools menu to its former state.

_Thanks for fixing this @Paul-Licameli_
