### ISSUE TITLE
Trim Audio command deserves a better menu position for "discoverability"

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4174]
### Bug description
The **Trim Audio** command is currently in the **Edit** submenu **Remove Special**   this is somewhat odd as
a) it is sufficiently important to warrant having a button for it in the Edit toolbar in the upper tooldock
b) In #4165 @Tantacrul wrote:
>Ah, my mistake. I thought it was a special, niche function, since it was in a menu called 'Remove special'

This makes this useful command somewhat "undiscoverable".

It would be more appropriate and more "discoverable" if **Trim Audio** was moved to a position in the top-level **Edit** menu.

### Steps to reproduce
1. Edit Menu > Remove Special
2. Observe:  menu structure

### Expected behavior
**Trim Audio** moved to top-level **Edit** menu
![image](https://user-images.githubusercontent.com/50205984/212049307-4a61f3db-6756-4f17-8e81-3e96abbe253e.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/50205984/212048653-bf6dcd21-d0fa-479b-9aee-41720e4c12a9.png)

### Audacity Version
3.2.3 and 3.3.0 alpha (and earlier Audacity versions)

### Operating system
Windows 10 - but suspect all OS

### Additional context
One _might_ consider the Same argument for the **Silence Audio** command.

It too is deemed important enough to have a button in the Edit Toolbar

**Comment by petersampsonaudacity** [comment]
But as @SteveDaulton  pointed out in #4165 yesterday that button in the GUI is far from prominent he wrote:
>I'd also add that the trim option is ridiculously buried - to the point where it's tough to believe anyone would ever find it.

And I am minded to agree with him.

Note that currently **_all_** buttons in the GUI have a command associated with them (and not a command in the, normally hidden, scripting Extras menu).

So I believe that Trim should definitely  remain in the Edit menu/submenu - not least because that aids discoverability.

**Comment by SteveDaulton** [comment]
> But as @SteveDaulton pointed out in #4165 yesterday that button in the GUI is far from prominent - he wrote:

That was @Tantacrul not  me. Personally I think the trim command is adequately "discoverable" as it has a dedicated button in addition to the sub-menu item and keyboard shortcut.

**Comment by LWinterberg** [comment]
I'm doing some menu redesigns, so it'll likely end up in a better place than "Remove Special" eventually anyway
