### ISSUE TITLE
Transport>Cursor to submenu and Keyboard pref  lack shortcuts displayed for:  Selection Start and Selection End

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4175]
### Bug description

In the **Cursor to** submenu of the **Transport** menu there are no displayed shortcuts for **Selection Start** and **Selection End**, even though shortcuts for them exist, **Left** keyboard arrow and **Right** keyboard arrow.

These have always been more than somewhat of an easter-egg being:
a) undocumented in the Audacity Manual
b) not show in the menus (as discussed here)
c) not shown in the app in Keyboard preferences

These are slightly dangerous/iffy shortcuts as:
i) they remove the selection
ii) the selection cannot be restored with the Undo command

### Steps to reproduce

1. Get some audio and make a selection
2. Transport>Cursor to
3. Observe: no shortcuts for Selection Start and Selection End
4. Edit > Preferences
5. select keyboard
6. Search on "selection"
7. scroll down a bit to the Transport Menus section
8. Observe: no shortcuts for Selection Start and Selection End

### Expected behavior

Shortcuts to be shown in the app in the menu and in preferences

### Actual behavior

**1) Menu** - no shortcuts for Selection Start and Selection End
![image](https://user-images.githubusercontent.com/50205984/212053394-65c30ef9-6823-404a-a429-37c4c1dfe299.png)

**2) Preferences** - no shortcuts for Selection Start and Selection End
![image](https://user-images.githubusercontent.com/50205984/212060362-5e956afa-9063-4824-855c-d1fdffb76825.png)

### Audacity Version
3.2.3 and 3.3.0 alpha (and earlier Audacity versions)

### Operating system
Windows 10 - but assume all OS

### Additional context
Having spotted Bills ednote about this today in the Manual from long ago I decided to fix the Manual today:
https://alphamanual.audacityteam.org/man/Transport_Menu:_Cursor_to
![image](https://user-images.githubusercontent.com/50205984/212059516-0a7e44ad-c632-4d69-b397-1204882e7836.png)

And I updated the Selection page:
https://alphamanual.audacityteam.org/man/Audacity_Selection

![image](https://user-images.githubusercontent.com/50205984/212060024-2ea8e319-aa5d-4dce-a75d-c555074d5412.png)

**Comment by DavidBailes** [comment]
> In the **Cursor to** submenu of the **Transport** menu there are no displayed shortcuts for **Selection Start** and **Selection End**, even though shortcuts for them exist, **Left** keyboard arrow and **Right** keyboard arrow.

There are no default shortcuts for these two commands.
The cursor left and cursor right commands have default shortcuts left and right arrow.
When there's a time selection and you press left or right arrow, commands cursor left or cursor right are executed, and the cursor it moved to the start or end of the selection. This is in keeping with Audacity's time selection, which is similar to the selection of characters in a line of text.
So when there's a time selection, to move the cursor to the start or end of the selection, a user can either use the cursor to start or end of selection commands, or the cursor left or right commands.
When there's no time selection the effects of these two pairs of commands are different.

**Comment by LWinterberg** [comment]
given they're separate commands, there's no fix for this.
