### ISSUE TITLE
F11 / can't exit from full screen

### ISSUE THREAD

**Issue by csgerg** [audacity/audacity#418]
Audacity 2.3.3-alpha-Nov 22 2019
Manjaro 18.1.5 Xfce
Hi, I tired the full screen mode, it works fine but you cant exit with F11.
You can leave the full screen mode with change workspace.

**Comment by petersampsonaudacity** [comment]
Works fine on Windows 10

**Comment by SteveDaulton** [comment]
Works fine in Xubuntu 18.04.

Steve

**Comment by JamesCrook** [comment]
We support Ubuntu linux builds, and not every flavour of Linux, so closing this since it works on Ubuntu.
