### ISSUE TITLE
Label text is positioned too close to bottom of label box, obscuring descenders 

### ISSUE THREAD

**Issue by virgilON** [audacity/audacity#4181]
### Bug description

Some standard ASCII characters are partially obscured by the lower border of the label textbox.  While most of these remain legible, the underscore ( _ ) disappears entirely and becomes indistinguishable from a space.  Since an underscore is frequently used in file names, being unable to distinguish the difference becomes a nuisance, or worse.  Although it is rendered useless within the Audacity context, an underscore (vs. a space) still matters when labels are exported, for example.

### Steps to reproduce

1. In a Label Track, create a Label by typing typing (or Copy/Pasting) characters such as : ( ) _ y p [ ] g j { } | 
2. Note that all are at least partially obscured by, and merge with, the outline of the textbox, making them more difficult to read. The underscore character disappears completely and is indistinguishable from a space.
3. The problem becomes more acute when attempting to use extended UTF-8 characters, as descenders are even more common (and more critical): e.g.:  § ¡ µ ¸ ¿ Ç ý þ ÿ Ą ą  (sampling just the first hundred or so).

### Expected behavior

Since there is ample white space above the characters, there would seem to be no reason why all characters should not be visible. Raising the line on which they rest by a couple pixels could resolve this.  Recognizing that this may be getting into some low-level programing, a simpler alternative may be to get rid of the textbox border altogether, as it seems to have no functional purpose beyond aesthetics (of doubtful value IMO, adding clutter to an already busy environment).  However, this would still leave the full-depth descenders touching the bottom of the textbox, so perhaps a combination of both approaches would be the best solution.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

I am using a 4K monitor, so it is possible others may see things differently.  However, the problem seems to occur on other machines, such as a laptop, so I assume it occurs on most or all (Windows, at least) displays.

**Comment by LWinterberg** [comment]
![image](https://user-images.githubusercontent.com/87814144/212651259-07983f4e-88be-4aea-89e8-4d06bfe7dfb1.png)
yeah, this seems like a hidpi issue (#503). It won't be tackled in wxWidgets and shouldn't be an issue in Qt
