### ISSUE TITLE
Audacity erroneously plays selected audio that is in negative time

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4185]
### Bug description
If you have audio in negative time and then use Ctrl+A to select all then the audio starts playing from the beginning of the selected audio in negative time and not from T=0.

And note that there is no indication on the Time toolbar that the audio being played is in negative time - the counter only kicks in when the playhead finally reaches T=0 - nor is there any indication in the Selection Toolbar that a selection exists in negative time (I will log these later as separate issues).

![image](https://user-images.githubusercontent.com/50205984/212664528-a5cc4c0d-6ad7-470f-87c4-7cfb60e7a8e2.png)

This is a regression on 3.0.5, introduced in 3.1.0 

### Steps to reproduce
1. get a 3 minute song
2. use the clip-handle drag-bar to drag half of it into negative time
3. Observe: only the second half of the audio is visible (default settings don't show audio in negative time)
4. Ctrl+A to select all
5. press Play
6. Observe: audio starts playing from the beginning of the three minute song
7. Observe: Time toolbar does not operate until the audio reaches the visible part at T=0

### Expected behavior
Audio in negative time should not be played.

This was true in 3.0.5 and earlier even if the user had turned on **Enable scrolling left of zero** in **Tracks Behaviors** preferences and the audio in negative time was displayed on-screen

### Actual behavior
Selected audio in negative time is played - and with no indication in the Time toolbar

### Audacity Version
3.2.3 - but present since 3.1.0

### Operating system
Windows 10, but assume all OS

### Additional context
Originally reported by Forum user NOOBtools:
https://forum.audacityteam.org/viewtopic.php?f=46&t=128756&p=462464

**Comment by petersampsonaudacity** [comment]
@LWinterberg @dozz

Testing on W10 with latest 3.5.- master alpha for 3.5.0

shows that this is _**NOT**_ fixed for 3.5.0

STRs
1. Record this sentence: "This is the beginning of the audio"
2. Time shift it so that half of the track is before zero
3. Ctrl+A to select all.
4. Press Play
5. Observe; the whole recording is played, including the before zero part

**Comment by petersampsonaudacity** [comment]
See also #4187

**Comment by petersampsonaudacity** [comment]
And see also

 **The Selection and Time Toolbars do not show a selection that is in negative time #4186**

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
