### ISSUE TITLE
The Selection  and Time Toolbars do not show a selection that is in negative time

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4186]
### Bug description

The Selection Toolbar  and the Time Toolbar have no indication that a selection that is in negative time:
![image](https://user-images.githubusercontent.com/50205984/212670366-118e0161-2206-4d58-8507-13606ce7aebd.png)
a) the red rectangles show no indication in the toolbars that a selection exists in negative time
b) the green ellipses are the somewhat weak visual cue that audio exists in negative time
c) the orange rectangle at the left of the Timeline, before T=0 is the **_only_** indication that a selection exists in negative time, _not exactly a strong visual cue._

### Steps to reproduce

1. get a 2 minute song
2. use the Clip-handle drag-bar to drag half of it into negative time
3. Ctrl+A
4. Observe: no indication in Selection  and Time Toolbars that the selection starts in negative time,

### Expected behavior
**1) Fix the toolbar indicators**
Since selections can exist in negative time the Selection  and Time Toolbars should indicate the negative start time of the selection

_**OR**_

**2) No selections in negative time**
Selections should not be allowed in negative time (and maybe you should not be allowed to timeshift audio into negative time.

_**OR EVEN**_

**3) No negative time**
The concept of negative time should be done away with entirely in Audacity.

### Actual behavior
Even true if you turn on **Enable Scrolling left oz zero** and display the negative time start audio:
![image](https://user-images.githubusercontent.com/50205984/212673111-bdbf661f-00a9-482a-9775-deac902b45a0.png)

### Audacity Version
3.2.3 - but all Audacity versions (i.e. this is _**not**_ a regression at all

### Operating system
Windows 10 - but assume all OS

### Additional context
See also:   Audacity erroneously plays selected audio that is in negative time #4185

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
