### ISSUE TITLE
Effects are applied to non-visible audio in negative time

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4187]
### Bug description
Effects are applied to non-visible selected audio in negative time - as are Analyzers, Generators and Tools

As there are no good visual cues for audio selected in negative time this may well come as a nasty unexpected surprise for the user later.  See:   The Selection and Time Toolbars do not show a selection that is in negative time #4186 

### Steps to reproduce
1. get a 2 minute song
2. use the Clip-handle drag-bar to drag half of it into negative time
3. Ctrl+A to select all
4. Apply any effect (e.g. much reduced amplification)
5. Drag all the audio back into positive time
6. Observe: the effect has been applied to the whole clip including the first half which was previously in negative time.

### Expected behavior
Effects (and other EGATs) should only be applied to audio which is potentially visible to the user.

_A good example of this in practice is applying an effect to a  shrunken smart clip with hidden audio_

### Actual behavior
Effects (and all EGATs) are applied to non-visible audio in negative time

### Audacity Version
3.2.3 - but all Audacity versions

### Operating system
Windows 10 - but assume all OS

### Additional context
See also:   The Selection and Time Toolbars do not show a selection that is in negative time #4186

**Comment by petersampsonaudacity** [comment]
See also:

 Audacity erroneously plays selected audio that is in negative time #4185

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
