### ISSUE TITLE
Cutline expansion erases cutlines to the right

### ISSUE THREAD

**Issue by vsverchinsky** [audacity/audacity#4189]
STR:
- Make sure cutlines option is enabled
- Generate audio clip
- Make two cutlines (Ctrl+X)
- Expand the leftmost cutline

Observe: second cutline disappear

**Comment by Ryan-Miller-Audacity** [comment]
Verified that cutlines no longer disappear when expanding other cutlines. Including when expanding the leftmost cutline, the second cutline properly maintains.
