### ISSUE TITLE
Artist is missing in the metadata after exporting multiple files

### ISSUE THREAD

**Issue by BaumGuard** [audacity/audacity#419]
One of my major purposes of using Audacity is to digitize vinyl records. Every track on the record is being exported as a separate file. When I export a part of the recorded audio and fill in the tag-form, the artist is only written to the metadata of the first file. The tags of the following files all don't contain the artist. Except the artist every information standing in the form is written to every file.
To mention a further detail: I always use MP3 to export the audios. I don't know whether that's the reason for the issue.

Steps to reproduce:
1. Select a part of the audio
2. Export the selected part as MP3
3. Fill in the tag-form with the information
4. After exporting this part, select another part of the audio and export it as MP3 as well.

Now you will see that the first file has the artist in its metadata, but not the second one, even though the artist had been displayed in the tag-form.

As you can imagine, I always have to write the artist in to the metadata of the files manually.

**Comment by petersampsonaudacity** [comment]
I'll have a look into this

**Comment by BaumGuard** [comment]
For some reason this doesn't occur every time, but sometimes.

**Comment by petersampsonaudacity** [comment]
I have tested this thoroughly today and I cannot reproduce this.  All seven of the standard metadata tags appear to get passed through:
a) to the next use of the export dialog
b) to the file.

1) Examining the exported files with Windows explorer shows the first six present and carried through, including "artist".  WE does not show the "comments" metadata

2) I f I import the files into iTunes I see all seven standard metadata tags  carried through

**Comment by BaumGuard** [comment]
I'm using Audacity on my linux system. I've tried it again and now the artist doesn't appear in any track when I open them with Kid3.

**Comment by SteveDaulton** [comment]
On Thu, 13 Feb 2020 at 16:18, BaumGuard <notifications@github.com> wrote:

> I'm using Audacity on my linux system. I've tried it again and now the
> artist doesn't appear in any track when I open them with Kid3.
>

Is the file definitely MP3 (and not, for example "WAV")?

Steve

**Comment by BaumGuard** [comment]
Yes.

**Comment by JamesCrook** [comment]
Closed.  Could not reproduce.
