### ISSUE TITLE
Cutlines disappear when duplicating track with selection

### ISSUE THREAD

**Issue by vsverchinsky** [audacity/audacity#4190]
STR:
- Make sure cutlines option is enabled in preferences
- Generate audio clip
- Create cutline in the middle
- Select short region around the cutline
- Duplicate track (Ctrl+D)

Observe: duplicated track does not contain cutline (or it can be displaced)

![image](https://user-images.githubusercontent.com/20165230/212687841-ee8ec064-6bb3-4811-8ccb-4b49759532d4.png)

**Comment by Ryan-Miller-Audacity** [comment]
Verified cutlines no longer disappear/displace when a track with cutlines is duplicated.
