### ISSUE TITLE
Effects stack is restricted to a single track

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4195]
### Bug description

An Effects stack can only be applied to a single track, it cannot be applied to a selected group of tracks or the whole project.

This sits in stark contrast with the functionality that we had in earlier Audacity versions with the Real-time enabled destructive effects.

and there is no facility for copying/replicating effects stacks, so applying a preferred stack to a whole project can be hard work:
 **There is no facility to Copy or Export/Import an effects stack #4194** 

### Steps to reproduce

1. get several audio tracks
2. set up and effects stack for the top one
3. Try to apply that stack to the entire project (or selected group of tracks)
4. Observe: you can't

### Expected behavior

There should be some facility to enable users to duplicate and re-use an effects stack with its settings.

### Actual behavior

No such facility

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

### Additional context

Triggered by this recent Forum post:  https://forum.audacityteam.org/viewtopic.php?f=70&t=128710&p=462465

**Comment by LWinterberg** [comment]
This is not something we're looking to implement. Copypasting/import-exporting stacks between tracks, yes (this is for your other bug), but the particular problem of applying effects to multiple tracks at once will be solved with a master track and - depending on how far into the weeds the journey goes - auxes, sends, returns, busses, groups, and so on
