### ISSUE TITLE
Port vocoder to SuperCollider

### ISSUE THREAD

**Issue by bramtayl** [audacity/audacity#420]
Hello! I was wanting a better vocoder in SuperCollider so I ported your implementation. See the [PR](https://github.com/supercollider/sc3-plugins/pull/273). I wanted to ask your permission first. If anyone is inclined, you might look over the code I wrote in SuperCollider to check whether I ported the implementation correctly.

**Comment by SteveDaulton** [comment]
The vocoder effect in Audacity is not a "traditional" vocoder. It's a quirky kind of "vocoder-like" effect. As such, I doubt that it would be a suitable replacement for SuperCollider's vocoder, though they may accept is as an addition.
As with the main Audacity application, the effect is licensed under the terms of GPL v2.

**Comment by bramtayl** [comment]
Sorry are you waiting for a response from me? What's the question? See the discussion on the PR

**Comment by SteveDaulton** [comment]
I think this "issue" is resolved at our end. As far as I'm aware, if your code is licensed as (verbatim) "GPL v2 or later", then that protects the full rights of our GPL v2 license, and allows it to be used in GPL v3 or later. The important phrase in GPLv2 with respect to this is in section 6 of the GPL v2 license:
"You may not impose any further restrictions on the recipients' exercise of the rights granted herein."

As joshpar wrote in the PR, I would suggest including (in the file) a comment that describes where you got it, links to any sources you referenced, and  the name of the original author. I don't think that is legally required, but is generally considered to be courteous and good practice.

**Comment by bramtayl** [comment]
Ok I did that
