### ISSUE TITLE
In Noise Reduction effect, a Sensitivity setting of 0 disables the effect

### ISSUE THREAD

**Issue by billw58** [audacity/audacity#4201]
### Bug description

Since a sensitivity setting of 0 disables the effect, it should not be offered as an option.

### Steps to reproduce

1) Import audio appropriate for testing the NR effect (I used an acoustic guitar chord fading out into the vinyl noise)
2) Duplicate the track (for later comparison)
3) Select a noise-only region and Get Noise Profile
4) Select all of second track and apply Noise Reduction with settings;   Reduction: 12, Threshold: 0, Smoothing: 0
5) Select the noise region selected in step three and set that as the loop region
6) Solo each track back and forth while looping the noise region
Note that noise reduction is not applied
7) To confirm, select the noise region in each track and do Effect > Amplify and look at the amplification amount

### Expected behavior

Noise reduction should be applied.

### Actual behavior

Sensitivity = 0, no NR
Sensitivity = 1, 3 dB NR, audible artifacts
Sensitivity = 2, 8 dB NR, audible artifacts
Sensitivity = 3, 12 dB NR, almost no audible artifacts
Sensitivity =3, Smoothing = 3,  12 dB NR, no audible artifacts

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS

**Comment by LWinterberg** [comment]
Hm. there's a handful of effects which can be configured as a no-op: Amplify by 0dB, change pitch/speed/tempo by 0, EQ/basstreble, delay, maybe more. Though I guess it's a bit more opaque that this effect would be a no-op than in most other effects which also have this

**Comment by SteveDaulton** [comment]
Setting "Sensitivity" to 0 also disables the effect.

Personally I don't find that "Threshold = 0 dB = no noise reduction" is particularly surprising. It seems logical to me in the same way that "Amplify by 0dB, change pitch/speed/tempo by 0, EQ/basstreble, delay" are no-ops, but setting "Sensitivity" to minimum being a no-op seems both surprising and totally pointless.

**Comment by billw58** [comment]
Sorry, throughout this discussion I should have said "Sensitivity" instead of "Threshold". I was thinking about what the setting apparently did, which was raise the threshold (the border between noise and signal). I'll try to edit the title

**Comment by Sririram** [comment]
is the issue solved?

**Comment by Crazycoder122** [comment]
I would like to contribute in this issue. 

Also found the file (https://github.com/audacity/audacity/blob/master/src/effects/NoiseReduction.cpp)

If you could kindly guide me in finding the actual place in the file cz I am very much nervous seeing the file as a whole so that I can contribute.

Thank You so much :)

**Comment by SteveDaulton** [comment]
Probably something like this:

```
--- a/src/effects/NoiseReduction.cpp
+++ b/src/effects/NoiseReduction.cpp
@@ -1278,7 +1278,7 @@ const ControlInfo *controlInfo() {
          0.0, 48.0, 48, wxT("%d"), true,
          XXO("&Noise reduction (dB):"), XO("Noise reduction")),
          ControlInfo(&EffectNoiseReduction::Settings::mNewSensitivity,
-         0.0, 24.0, 48, wxT("%.2f"), false,
+         1.0, 24.0, 48, wxT("%.2f"), false,
          XXO("&Sensitivity:"), XO("Sensitivity")),
 #ifdef ATTACK_AND_RELEASE
          ControlInfo(&EffectNoiseReduction::Settings::mAttackTime,

```

**Comment by vedantiitkgp** [comment]
@LWinterberg is this issue solved ?

**Comment by dozzzzer** [comment]
Tested
