### ISSUE TITLE
Cancel button is missing from EGAT dialogs

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4205]
### Bug description
The dialogs for Effects, Generators, Analyzers and Tools (EGATs) no longer have a **Cancel** button to abort the dialog.  

Such a button was present in all versions of Audacity from 1.0.0 onwards and only removed recently in the EGAT "beautification" mini-project - so technically this is a regression.
![image](https://user-images.githubusercontent.com/50205984/213199224-e1e8395e-b81a-400d-9932-656c0ed8bb22.png)

### Steps to reproduce
1. get some audio
2. select it
3. launch any EGAT
4. Observe: there is no **Cancel** button

### Expected behavior
A **Cancel** button to be displayed with the action buttons at bottom of the EGAT dialogs

### Actual behavior
No **Cancel** button in EGAT dialogs

### Audacity Version
3.2.3 and 3.3.0 alpha

### Operating system
Windows 10 - but assume all OS

### Additional context
Spun off from:  

Location of buttons is wrong #3615

**Comment by DilsonsPickles** [comment]
Can we include adding a cancel button to the upload to audio.com progress dialog in this ticket?

<img width="276" alt="image" src="https://user-images.githubusercontent.com/111350316/218428245-5d4cde00-996d-4275-b9c4-7883e033a136.png">

**Comment by petersampsonaudacity** [comment]
For 3.2.4 the **red circle** cancel button has been removed (as the cancel there did nothing, the copy continued merrily to completion).

@Tantacrul wrote in this thread:  Performance and file size issues when copying and pasting a small portion of a very large clip #3820 

>Also, if / when we do create a 'Cancel' button, it should be a **properly labelled button**, not a 'close' button.

**Comment by DilsonsPickles** [comment]
Sorry, I think that image lead to confusion. What I mean to say is, can we implement the below design as part of this ticket. Or, does this need to be its own task?

<img width="276" alt="image" src="https://user-images.githubusercontent.com/111350316/218432613-dcddd282-1c42-44b8-9861-afec74e04657.png">

**Comment by Tantacrul** [comment]
I'd just treat these individually because the issues are more challenging technically (or not, depending on what it is you are cancelling 😄 )

So, I'd keep the cancel button for uploads, exporting, etc. separate.

**Comment by vsverchinsky** [comment]
> So, I suspect it's best to keep the cancel button tasks for uploads, exporting, etc. separate.

I agree with that

**Comment by DilsonsPickles** [comment]
Fresh off the press for you all to enjoy!

![AdditionalCancelButton_02](https://user-images.githubusercontent.com/111350316/221587897-50501b5d-8471-4ef1-a95e-a1600764d286.png)
![AdditionalCancelButton_03](https://user-images.githubusercontent.com/111350316/221587903-bf751b28-511e-4be1-a078-f1838fea6e3c.png)
![AdditionalCancelButton_04](https://user-images.githubusercontent.com/111350316/221587905-9a4f2c04-9197-4228-9d0a-96d1f651c412.png)
![AdditionalCancelButton_05](https://user-images.githubusercontent.com/111350316/221587908-5691c176-8c53-4442-b055-56996031a2a8.png)

**Comment by Tantacrul** [comment]
T'is a fine thing.

**Comment by petersampsonaudacity** [comment]
These work for me.

**Comment by petersampsonaudacity** [comment]
@DavidBailes 

@LWinterberg  wrote in #3615 
>> I would much prefer the Presets & Settings to be located bottom left rather than top left
>
>This is in preparation of #2417 which definitely will sit at the top - it'd much too wide to go in line of preview/cancel/OK of the thinner dialogs

**Comment by DavidBailes** [comment]
> @DavidBailes
> 
> @LWinterberg wrote in #3615 in response to my similar request at the time:

My comment is about the position of the preview button, not the presets and settings button. See also: https://github.com/audacity/audacity/issues/3615#issuecomment-1386800719

**Comment by petersampsonaudacity** [comment]
> My comment is about the position of the preview button, not the presets and settings button. See also: [#3615 (comment)](https://github.com/audacity/audacity/issues/3615#issuecomment-1386800719)

Oh yes, I really should learn to read more thoroughly <blushes deeply>

And I think I see what you mean David, the **Preview** can be regarded an action button, a precursor to pressing **Apply** - but it could also be regarded as a test the preset or settings and thus live up top with the **Presets & Settings** button.  I can see a good argument for it being in either place.

@LWinterberg  and @DilsonsPickles   if we had the **Preview** button at the bottom would that not make more room available for any longish preset name to be displayed #2417 ?

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @vsverchinsky 's latest branch for this:  audacity-win-3.5.0-alpha-20240213+848d528-x64

I observe in Vitaly's branch that the for all EGATs The **Apply/Generate** button has been moved to the bottom of the EGAT dialog window and a **Cancel** button has been added (back) also in the footer.

![image](https://github.com/audacity/audacity/assets/50205984/dda6e539-e9d1-4d06-8099-858182c9a822)

_This is a much more "conventional" position for action buttons in a dialog._

**Comment by petersampsonaudacity** [comment]
@DavidBailes  wrote earlier in this thread:

>I think that a more natural place for the preview button would be at the bottom, as in previous sketches: https://github.com/audacity/audacity/issues/3615#issuecomment-1385705419
>
>A user reads down the parameters, maybe changes some on the way and then presses the preview button at the bottom.

@LWinterberg @DilsonsPickles @Tantacrul 

I am minded to agree with David as the **Preview** can also be regarded as an action button.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @vsverchinsky 's subsequent branch for this:   audacity-win-3.5.0-alpha-20240214+3a68083-x64

The EGATs' footers in Vitaly's latest branch now have buttons for **Preview**, **Cancel** and **Apply**
![image](https://github.com/audacity/audacity/assets/50205984/45ddbe5d-b0d1-41bc-bf3e-f34ea1c73e02)

Looks good to me.

**Comment by DavidBailes** [comment]
@vsverchinsky . The presets & settings button is in an unexpected position in the Tab order.

**Comment by LWinterberg** [comment]
Given that we ship with way less factory presets than we could, I think the current tab order is probably appropriate.

**Comment by DavidBailes** [comment]
> Given that we ship with way less factory presets than we could, I think the current tab order is probably appropriate.

@LWinterberg @vsverchinsky . I should have been clearer about what I meant by "unexpected position" in the Tab order.
I'm not suggesting that the presets & settings button should be the initial focus.
However, I am suggesting, that immediately after the dialog opens, a user would expect that if they pressed Shift+Tab, the presets & settings button would become the focus, as this is the previous control in the reading order of the controls. In fact the Apply button becomes the focus.  Pressing Shift + Tab to move to the presets & settings button, as well as being expected given the layout, would also be very useful, given that the presets & settings button does not have an access key. Example dialog:
![image](https://github.com/audacity/audacity/assets/11887021/1c225fb5-f6d4-466c-a116-28002e00fb54)

Also, when an effect such as Bass and Treble is used as a real time effect, in that dialog, immediately after it is opened, pressing Shift + Tab does make the Presets & settings button the focus, as one would expect. 
![image](https://github.com/audacity/audacity/assets/11887021/4e5ab511-1a6d-4d2a-9589-1a110c527cb8)

**Comment by LWinterberg** [comment]
Ah, I didn't know ordering and initial position could go independently. In which case David's request looks good to me @vsverchinsky

**Comment by vsverchinsky** [comment]
@DavidBailes I've updated the PR, all elements in the top bar including "Presets..." button are now placed before plugin parameters in tab ordering, could you please tell if it's good now?

**Comment by DavidBailes** [comment]
> I've updated the PR, all elements in the top bar including "Presets..." button are now placed before plugin parameters in tab ordering, could you please tell if it's good now?

@vsverchinsky . Thanks, it's now OK.
