### ISSUE TITLE
No longer any help (or replacement hovertext information) in EGATs

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4206]
### Bug description
The dialogs for Effects, Generators, Analyzers and Tools (EGATs) no longer have a **?** Help button to link the user to the relevant page in the Manual.

A suitable replacement would be hovertext help information in the EGATs when hovering over the settable parameters in the EGATs.  This would be useful to users as some (not all, but definitely some) of the EGATS have somewhat fiercely complex and subtle parameters that can be set (and we know that many users do not bother to RTFM)

Such a button was present in earlier versions of Audacity and only removed recently in the EGAT "beautification" mini-project - so technically this is a regression.

### Steps to reproduce
1. get some audio
2. select it
3. launch any EGAT
4. Observe: there is no **?l** Help button
5. Hover your cursor over any settable parameter in the EGAT dialog
6. Observe: there is no hovertext help

### Expected behavior
In all EGATs when the user hovers their cursor over any settable parameter hovertext help should appear.

Note carefully that no text needs to be invented/written for this, it's all there in the manual already on the EGAT pages- it just needs pasting as hover-help in the EGAT dialogs.

### Actual behavior

No user help in EGAT dialogs - and some are fiercely complex/subtle

### Audacity Version
3.2.3 and 3.3.0 alpha

### Operating system
Windows 10 - but assume all OS

### Additional context
Spun off from:

Location of buttons is wrong #3615

**Comment by petersampsonaudacity** [comment]
Here's a good example of a complex Effect with tricksy/subtle settings - the Audacity Compressor:
![image](https://user-images.githubusercontent.com/50205984/213204615-bd5f3f89-ea65-4044-86ac-4e35b0a7eeba.png)

**Comment by Ryan-Miller-Audacity** [comment]
I believe these were removed in the edits made in Audacity 3.2. I'll let design team comment on this though since it seems to have been removed by them when we redesigned the EGAT windows. 

@LWinterberg @DilsonsPickles

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
