### ISSUE TITLE
[enhancement request] - adding Trevor Wishart Composers Desktop Project Plugins to Audacity by Default

### ISSUE THREAD

**Issue by tiagomoraismorgado2022** [audacity/audacity#4214]
### Your idea

adding Trevor Wishart Composers Desktop Project Plugins to Audacity by Default

### Problem to be solved

adding in a whole set of plugins for spectral processing and fft processing to audacity, which are already free and opensource, were coded by a leading persona in the electroacoustic music scene, and can be of great advantage to audacity

### Prior art

the free and opensource release of Trevor Wishart CDP

### Additional context

by providing this implementation, not only there will be a great counterpart to tools like audacity paulstretch, as well as the database of plugins available in audacity will literally explode

**Comment by LWinterberg** [comment]
I don't think CDP is a good fit for Audacity right now: 

From a technical point, they exist as standalone command line tools, which are limited to 32-bit on Windows. To be part of Audacity, they need to be a 64-bit library though. 

From a design point, "exploding" the number of effects is not desirable, especially not with 400-500 effects which have a very narrow scope each. Paulstretch shares this problem with them, and when time comes to look more closely at all the effects we have, I'd propose to merge it into the change tempo effect (eg with an "enable extreme stretching" checkbox)
