### ISSUE TITLE
Audacity detects custom metadata as `TXXX` and not actual name

### ISSUE THREAD

**Issue by hasezoey** [audacity/audacity#4218]
### Bug description

Currently audacity detects all custom metadata as the `TXXX` tag and also writing it like this in the final file, even though the input had proper names.

I am not completely sure, but i think a earlier version of audacity worked (did not confirm)

### Steps to reproduce

1. have a file with custom metadata
2. open in audacity
3. confirm that the metadata got recognized as `TXXX` in `Edit -> Metadata`
4. try to export the file
5. confirm that the export also contains `TXXX` instead of all custom tags

### Expected behavior

To use the proper tag names

### Actual behavior

Uses `TXXX` for all custom tag names

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

### Additional context

test file with custom metadata: [silence.zip](https://github.com/audacity/audacity/files/10471719/silence.zip)

ffprobe output on input file:
```sh
$ ffprobe silence.mp3 
[mp3 @ 0x5645fc085c40] Format mp3 detected only with low score of 1, misdetection possible!
Input #0, mp3, from 'silence.mp3':
  Metadata:
    artist          : test-artist
    title           : test-title
    date            : 2022
    description     : test description
    purl            : SomeUrl
    comment         : SomeComment
    encoder         : Lavf59.27.100
  Duration: 00:00:00.05, start: 0.023021, bitrate: 129 kb/s
  Stream #0:0: Audio: mp3, 48000 Hz, mono, fltp, 64 kb/s
```

audacity metadata screenshot:
![audacity](https://user-images.githubusercontent.com/10911626/213849117-3dbd395e-1c1c-4e07-8784-3004d638563d.png)

ffprobe output on output file:
```sh
$ ffprobe audacity_out.mp3 
[mp3 @ 0x55b2eb5e5c40] Format mp3 detected only with low score of 25, misdetection possible!
Input #0, mp3, from 'audacity_out.mp3':
  Metadata:
    artist          : test-artist
    title           : test-title
    TXXX            : SomeComment
    date            : 2023
  Duration: 00:00:00.07, start: 0.023021, bitrate: 130 kb/s
  Stream #0:0: Audio: mp3, 48000 Hz, mono, fltp, 117 kb/s
    Metadata:
      encoder         : LAME3.100
```

**Comment by petersampsonaudacity** [comment]
There are a raft of issues logged regarding metadata (which is not very well handled in Audacity, including custom metadata).

See:  https://github.com/audacity/audacity/labels/Metadata

**Comment by hasezoey** [comment]
Duplicate of #3733
