### ISSUE TITLE
Cannot open file when Long file name + path 

### ISSUE THREAD

**Issue by smallstepforman** [audacity/audacity#4219]
Probably reported over 1000 times, but if you have a deep file path / hierarchy and a long file name, Audacity fails to open a file.  Tested under Windows 11.

**Comment by petersampsonaudacity** [comment]
You need to provide some explicit Steps To Reproduce:
a) what length of filename,
b) what depth of path?

**Comment by smallstepforman** [comment]
D:\Development\1234\Audio\abcdefgh\ANCIENT_EGYPT_SLOT_GAME_SOUND_EFFECTS_LIBRARY-Royalty_Free_Egyptian_Slots_Music_and_Sounds-Fusehive.com\Fusehive - ANCIENT EGYPT SLOTS [SD WAV]/ANCIENT EGYPT SPECIAL REEL STOP - Achievement Notification World Music Instrument Tune 01    [002181].wav

Moving the file to a higher directory and it works.
