### ISSUE TITLE
Reverb Crashes Audacity

### ISSUE THREAD

**Issue by DocWicked** [audacity/audacity#4225]
### Bug description

Whenever I apply a reverb effect I get a crash

### Steps to reproduce

Create any audio
Apply a reverb effect (any settings)
You might get crashed

### Expected behavior

I expect the reverb effect to apply without crashing

### Actual behavior

Once I apply a reverb effect my Audacity crashes with a list of code
Exception code 0xc0000005

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by petersampsonaudacity** [comment]
Testing on W10 with 3,2,3 and the latest alpha test build I have for the upcoming 3.3.0

I cannot replicate this - works for me.

I have tested with
a) long 2 hour show
b) short tracks
c) short selections
d) stereo
e) mono

@DocWicked can you provide some explicit short Steps To Reproduce please?

**Comment by Ryan-Miller-Audacity** [comment]
Testing this on Windows 10 in Audacity 3.2.4 I cannot reproduce this behavior either. I tried with a variety of parameters and clips and never got a crash.

**Comment by SnoweyLumi** [comment]
Had the same problem. My thought it's because a few settings inside of the reverb are contradicting each other or ending up at a non-valid number.
Restoring the settings to factory settings, or changing the settings manually should fix this.
