### ISSUE TITLE
fatal error C1091: string exceeds 65535 bytes in length

### ISSUE THREAD

**Issue by nathan-osman** [audacity/audacity#4230]
### Bug description

I attempted to build from `master` with MSVC++ 2019. I got about a third of the way through before encountering this compiler error:

<pre>[ 60%] Building CXX object src/CMakeFiles/Audacity.dir/AboutDialogGPLv3Text.cpp.obj
AboutDialogGPLv3Text.cpp
F:\audacity-source\src\AboutDialogGPLv3Text.cpp(4): fatal error C1091: compiler limit: string exceeds 65535 bytes in length
NMAKE : fatal error U1077: '"C:\Program Files\CMake\bin\cmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.</pre>

### Steps to reproduce

1. Clone the repository
2. Open the x64 Native Tools Command Prompt
3. Create a `build` directory and `cd` into it
4. Run `cmake -G"NMake Makefiles" ..`
5. Wait for completion and run `nmake`

### Expected behavior

The application should finish compiling.

### Actual behavior

It stops partway through with the above-mentioned error.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

### Additional context

I know you are making the switch to Qt, but I tried switching to that branch and the error occurs on that file as well.

**Comment by crsib** [comment]
This is really weird. Audacity is built on CI using MSVC2019 several times a day without any issues.

**Comment by nathan-osman** [comment]
I will try a fresh build with VC++ project files instead of nmake to see if it makes any difference later tonight.
