### ISSUE TITLE
Uploaded audio exceeds file size limit

### ISSUE THREAD

**Issue by DilsonsPickles** [audacity/audacity#4234]
Audio.com has a new 2GB file size limit. As such, Users attempting to upload audio that exceeds this limit must be notified via an error message.

**Comment by DilsonsPickles** [comment]
Proposed design solution is to present the User with an error dialog once they press "Share audio" when their selected audio data exceeds the 2GB file size limit. 

@crsib do we know the size of the upload at this point in time, or do we need to present the dialog at a later stage in the upload process?

![AudioExceedsFileSizeLimit_02](https://user-images.githubusercontent.com/111350316/214620763-c7987f86-6b3c-48b5-9dec-edc49d5bac51.png)

**Comment by DilsonsPickles** [comment]
Wouldn't this mean that a User could potentially waste a chunk of time attempting to upload 4GB of audio data, only to find out that it's too large right at the last stage in the process?

**Comment by crsib** [comment]
Releasing Audacity is not the fastest process. I have a strong opinion, that we should not hard code such limitations.

**Comment by crsib** [comment]
BTW the good question is how to measure the size :-) It appears that what audio.com guys want is to limit the size of the WAV file with some encoding options they choose. This can change on the server side we. 

For the reference, we do not upload WAV files, we upload WavPack encoded data.

**Comment by shoogle** [comment]
>> I think we can pass uncompressed size to the server somehow and let it to decide.
>
> Wouldn't this mean that a User could potentially waste a chunk of time attempting to upload 4GB of audio data, only to find out that it's too large right at the last stage in the process?

No. It means Audacity sends the file's ***size*** (i.e. a number) and then the server responds to say whether the number is too big. Alternatively, Audacity could ask the server to send back the maximum size. Either way, if the current file's size is too large then no audio data is transmitted.

But this only works if the size limit applies to unrendered audio (basically, to the Audacity project file rather than to an exported WAV). As it turns out...

> It appears that what audio.com guys want is to limit the size of the WAV file with some encoding options __they choose__. This can change on the server side

Since the file size limit applies to *rendered* audio, the project has to be rendered before the file's size can be known. Also, since the rendering happens on the server, the audio has to be uploaded before it can be rendered.

So the options are:

1. Audio.com decides to limit the size of _unrendered_ audio instead of _rendered_ audio, or;
2. Audacity uses some fancy heuristic to quickly guess the size of rendered audio without actually rendering it all, or;
3. The user has to sit through the entire upload, and also wait for the rendering to complete on the server, before they get to know whether it was successful.

> BTW the good question is how to measure the size :-)

It sounds like @crsib wants to use option 2, but I can't tell whether he was being serious😄

**Comment by crsib** [comment]
We can send the duration and the number of channels beforehand so the server can decide if the file is to large. Or samples count and sampling frequency.

As I understand audio.com wants to limit the size of the wav file, which has constant bitrate so they will be able to calculate the storage requirements easily.

**Comment by shoogle** [comment]
I guess it would be sample count, frequency, and number of channels in case Audio.com wants to mix the channels down to stereo, which would make for a smaller file size overall.

**Comment by DilsonsPickles** [comment]
Ok, @shoogle @crsib at which point in the upload to audio.com process does Audacity communicate the file size? We have 3 interactions at present:
1. Pressing share audio
2. Confirming the audio's public visibility
3. The upload progress dialog

**Comment by crsib** [comment]
>  Audio.com wants to mix the channels down to stereo

Audio.com is a very simple service right now, it only allows uploading mono and stereo audio files, so Audacity always downmixes the project first. I am not aware of any plans to support multitrack audio.

@DilsonsPickles as far as I understand, audio.com wants to limit the upload based on the uncompressed file size. We never communicate this size and I am not aware of any APIs that would allow doing so. We send the size of WavPack compressed data, this size is only known after WavPack compression is complete. It is technically impossible to know this size before the file is exported and compressed.

**Comment by DilsonsPickles** [comment]
Hi all, 

Given the above, I've drafted up two options. Both wait for the audio to be compressed and communicated to audio.com before displaying.

As we'll want to re-use this flow for other errors/messages, I think **option 1** is more versatile but that'll depend on whether it's possible to completely abort the upload process. 

LMK what you think. 

Cheers

### 1. Standalone error dialog
![AudioExceedsFileSizeLimit_04](https://user-images.githubusercontent.com/111350316/216014682-806dc8bc-9b04-48a6-8248-4d07eadfa224.png)
![AudioExceedsFileSizeLimit_05](https://user-images.githubusercontent.com/111350316/216014694-3694476e-c8db-491c-a3a7-6b15faf730a3.png)
![AudioExceedsFileSizeLimit_06](https://user-images.githubusercontent.com/111350316/216014700-173d9e6f-6d0f-404f-b656-8facabe7457f.png)

### 2. Inline error message
![AudioExceedsFileSizeLimit_09](https://user-images.githubusercontent.com/111350316/216015205-b788c4fb-0336-4597-b22a-735a16da0eb7.png)
![AudioExceedsFileSizeLimit_08](https://user-images.githubusercontent.com/111350316/216015200-a567bb8b-aea4-413d-a865-2807438d11f0.png)

**Comment by crsib** [comment]
@agilov FYI

**Comment by DilsonsPickles** [comment]
Looks like option 1 (Standalone error dialog) is the winner.

**Comment by Ryan-Miller-Audacity** [comment]
Tested and confirmed. Message popup content does not exactly match spec; however this is controlled on Audio.com side.
