### ISSUE TITLE
Distortion in DTMF generation

### ISSUE THREAD

**Issue by ngregorich** [audacity/audacity#424]
I have been using Audacity's DTMF Tone generation capabilities and noticed certain samples are distorted, as confirmed in the spectrogram. I have been generating samples with tone durations as low as 20 ms and silence of 5 ms, so I think this issue may only manifest itself in shorter durations. 

**To Reproduce**
1. Go to _Generate_
2. Scroll down to _DTMF Tones_
3. Set _DTMF sequence to_ 0000000000 (ten 0s, value not critical)
4. Set _Amplitude_ to 0.5
5. Set _Duration_ to 1 s
6. Set _Tone/Silence ratio Duty cycle_ to 80% (value not critical)
7. Push _OK_ to generate audio
8. Listen to resulting audio, first 6 or so tones will be distorted compared to following 4
9. Go to _Audio Track_
10. Scroll down to _Spectrogram_
11. Observe differences in spectral content of first 6 vs following 4 tones

**Expected behavior**
I expected all 10 tones to sound identical. When I zoom in, it looks like the first 6 tones do not have an envelope applied to ensure the waveform amplitude is at / near 0 at the end of the tone duration. Later tones appear to have a proper envelope applied, as expected.

**Screenshots**
Overview of spectrogram generated from the _To Reproduce_ steps
<img width="592" alt="distorted_vs_clean_overview" src="https://user-images.githubusercontent.com/44035038/74767984-a819cd00-523c-11ea-9f2b-4455fc3cacac.png">

Comparison of distorted and clean tones in time domain
<img width="1897" alt="distorted_vs_clean_zoom_time" src="https://user-images.githubusercontent.com/44035038/74768091-d0a1c700-523c-11ea-9c0f-377b97f43b38.png">

Comparison of distorted and clean tones in frequency domain
<img width="1897" alt="distorted_vs_clean_zoom_freq" src="https://user-images.githubusercontent.com/44035038/74768132-e7481e00-523c-11ea-9668-e4e1aa32f57f.png">

**Additional information:**
 - OS: macOS Mojave 10.14.6
 - Version: Audacity 2.3.3
 - OS: Linux Mint 19.3
 - Version: Audacity 2.2.1
 - Note: issue does not appear identically on both systems / versions

**Additional context**
 - I have been able to work around this issue by generating a longer sequence than required
 - I have just started building Audacity from source and will see if I can aid in debugging

**Comment by ngregorich** [comment]
I was able to build and find that the issue is related to the extra sample padding in _DtmfGen.cpp_ as seen below:

```// the statement takes care of extracting one sample from the diff bin and```
```// adding it into the current block until depletion```
```numRemaining += (diff-- > 0 ? 1 : 0);```

I have forked the repo and will try and get on the mailing list to discuss a pull request for this fix. [Here](https://github.com/audacity/audacity/compare/master...ngregorich:Distortion-in-DTMF) is the comparison with master.

**Comment by SteveDaulton** [comment]
Thanks for the bug report.
To fix it, why not just change:
   // generate a fade-out of duration 1/250th of second
   if (last == total - len) {
to:
   // generate a fade-out of duration 1/250th of second
   if (last >= total - len) {

**Comment by ngregorich** [comment]
That is about where I started, but after logging _last_, _total_, and _len_ in _MakeDtmfTone_ I found that _last_ was always 0 and that _total_ and _len_ were always equal or differed by 1 with my test cases.

I see now that longer tone durations require the phase preservation provided by _last_, which would be the cases where you wouldn’t want a fade in / out envelope applied to the buffered tone.

I will double check tomorrow to see if your proposed inequality will safely cover both shorter and longer tone durations. 

Thank you

**Comment by SteveDaulton** [comment]
I've committed the "simple" fix, so you can now test it from the current GitHub code.
I also replaced that "protect against negative offset" hack, so that even stupidly short tones now fade out correctly.
Thanks for your help with this. It looks like this bug had been present for years (but never reported until now).

**Comment by ngregorich** [comment]
I dug pretty deep into this, I’ll post an update late next week.

**Comment by JamesCrook** [comment]
Fix committed, and issue now closed.
