### ISSUE TITLE
Memory leaks while recording on Wayland

### ISSUE THREAD

**Issue by kuba-orlik** [audacity/audacity#4247]
### Bug description

When recording in Audacity in Gnome on Wayland, while the waveform is zoomed in to a scale where around 10s of recording fit horizontally on the screen, the memory usage goes drastically up. Zooming out the waveform or minimizing the Audacity window stops the growth of memory usage, but the already used up memory is released only after closing Audacity. The same issue does not occur if audacity is ran as `env GDK_BACKEND=x11 audacity` under the same kernel and Audacity version.

### Steps to reproduce

1. Open Audacity in Wayland and your preferred resource usage monitor (like gnome-monitor or `watch free -h`
2. Start recording audio
3. Wait around 10 minutes and observe memory usage

### Expected behavior

Memory usage should remain more or less constant

### Actual behavior

The memory usage of Audacity is ramping up. Eventually I ran out of RAM and the PC froze. The growth pauses when Audacity is minimized or when the timeline view is zoomed out.

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

### Additional context

The drop of RAM usage after closing audacity that's been leaking memory:

![image](https://user-images.githubusercontent.com/2697916/215258590-123e82e0-c429-473b-93ba-b5d887a27b47.png)
![image](https://user-images.githubusercontent.com/2697916/215258599-1705a731-439d-408d-9cea-7d9d8be59ae2.png)

The buff/cache metric is the one that keeps growing. The facts that minimizing the window pauses the memory usage growth and that running it in xorg fixes the issue seem to point to the GUI as the culprit

**Comment by dvzrv** [comment]
Hi! This has been broken for months apparently. There is a downstream ticket with Arch Linux as well at https://bugs.archlinux.org/task/77335

It would be really great if this could be addressed. Is this still a problem with 3.3.1?
If so, can the env please be added to the XDG desktop integration file until you have this figured out? Thanks! :)

**Comment by crsib** [comment]
Wayland is not an option for wx based Audacity anyway. Attempt to fix that resulted in 25k lines, so I don't think that we will fix any issues in Audacity 3.x timeline.

**Comment by dvzrv** [comment]
> Wayland is not an option for wx based Audacity anyway.

Okay. Can you please disable it in the XDG desktop integration then as suggested in the original ticket? That would help managing expectations and lead to fewer bug reports I think.

**Comment by crsib** [comment]
I'm not quite sure what you mean

**Comment by dvzrv** [comment]
Well, if you do not support running natively on Wayland, please make sure that the X11 backend (i.e. XWayland) is used.
It can be achieved by using `GDK_BACKEND=x11` in the XDG desktop file.

**Comment by chinakov** [comment]
Tested, no issues after a recording for 20 minutes. Thanks, no memory leaks observed.
