### ISSUE TITLE
clang does not have -latomic

### ISSUE THREAD

**Issue by xxjack12xx** [audacity/audacity#425]
Reading around, it looks like only cmake 3.8+ supports latomic. Need to properly check for it before using.

[https://github.com/fish-shell/fish-shell/commit/45633f4a54f9d04d33406e97e48613066c072d81](https://github.com/fish-shell/fish-shell/commit/45633f4a54f9d04d33406e97e48613066c072d81)
FreeBSD 12 amd64 audacity 2.3.3 has cmake 3.16.4 and llvm 9.0.1 which requires removing -latomic to configure

There's probably a better way to check for this in the previous URL.

```
--- configure.ac.orig   2019-02-24 08:28:05 UTC
+++ configure.ac
@@ -200,14 +200,6 @@ if test x$enable_universal_binary = xyes; then
    esac
 fi
 
-dnl Check if $CXX is clang by evaluating the version string because
-dnl $ax_cv_cxx_compiler_vendor seems not to work (it is either "gnu" or just empty).
-dnl If $CXX is clang (string is found), grep returns 0 and the if is executed.
-dnl Use /dev/null to suppress grep output to shell.
-if ($CXX --version | grep 'clang version' > /dev/null); then
-    LDFLAGS="${LDFLAGS} -latomic"
-fi
-
 if test x$enable_sse = xyes; then

    if test "${ax_cv_cxx_compiler_vendor}" = "gnu"; then

```

**Comment by rrrapha** [comment]
This is related to #344

**Comment by lllucius** [comment]
We will be switching to CMake builds shortly and I have added a check for libatomic.  Do you want to give it a try?

**Comment by xxjack12xx** [comment]
Sure. Is it part of head or a patch?

**Comment by lllucius** [comment]
Yes, it's part of HEAD.  I have some stuff in there already for FreeBSD, but I'm by no means an expert on FreeBSD (like I've installed it once ;-)), feel free to make suggestions to the CMake build.  I'll be able to incorporate those now, but I won't be able to incorporate source code changes as we're looking to release 2.4.0 shortly.

**Comment by xxjack12xx** [comment]
I'm working on testing out 5a2eaf9, if it doesn't crash, would be good
enough for 2.4.4.

I just installed the current HEAD version and the time interface is warped
(screenshot attached). 2.3.3 was not warped. The rest of the interface is
still the same with everything going outside the boundaries from wxgtk
being built with gtk3 instead of 2.

**Comment by lllucius** [comment]
Wow, you got it working that quickly?!?!  Excellent work.  Would LOVE to see your screenshot.  Did I miss it or did you not attach it?

**Comment by xxjack12xx** [comment]
Not sure about if I forgot to attach but here it is again just in case ;)

**Comment by xxjack12xx** [comment]
Also during make install, got this:

 /bin/mkdir -p '/usr/obj/usr/ports/audio/audacity-devel/work/stage/usr/local/share/audacity/nyquist'
install  -m 0644  nyquist/aud-do-support.lsp nyquist/dspprims.lsp
nyquist/envelopes.lsp nyquist/equalizer.lsp nyquist/
evalenv.lsp nyquist/fileio.lsp nyquist/init.lsp nyquist/misc.lsp
nyquist/nyinit-dbg.lsp nyquist/nyinit.lsp nyquist/nyqm
isc.lsp nyquist/nyquist-plot.txt
'/usr/obj/usr/ports/audio/audacity-devel/work/stage/usr/local/share/audacity/nyquist'
find: lib-src/lv2/build: No such file or directory

Looks like maybe these are causing it?
audacity-5a2eaf9/Makefile.in:suillib_DATA = $(shell find
lib-src/lv2/build -name \*.so)
audacity-5a2eaf9/Makefile.am:suillib_DATA = $(shell find
lib-src/lv2/build -name \*.so)

**Comment by lllucius** [comment]
Let me look into this.  It's probably something I recently added to the existing build to provide the suil UI wrappers.

**Comment by lllucius** [comment]
Interesting.  In your build directory do you not have a lib-src/lv2/suil/build directory?  It should have:
```
[build]$ dir lib-src/lv2/build
total 32
drwxr-xr-x. 8 yam 4096 Feb 24 15:55 .
drwxr-xr-x. 9 yam 4096 Feb 24 15:55 ..
drwxr-xr-x. 2 yam 4096 Feb 24 15:55 bin
drwxr-xr-x. 3 yam 4096 Feb 24 15:55 etc
drwxr-xr-x. 8 yam 4096 Feb 24 15:55 include
drwxr-xr-x. 5 yam 4096 Feb 24 15:55 lib
drwxr-xr-x. 3 yam 4096 Feb 24 15:55 lib64
drwxr-xr-x. 4 yam 4096 Feb 24 15:55 share
```

Here’s where the suil libs should be:

```
[build]$ dir lib-src/lv2/build/lib/suil-0
total 256
drwxr-xr-x. 2 yam  4096 Feb 24 15:55 .
drwxr-xr-x. 5 yam  4096 Feb 24 15:55 ..
-rwxr-xr-x. 1 yam 18296 Feb 24 15:55 libsuil_gtk2_in_qt4.so
-rwxr-xr-x. 1 yam 23696 Feb 24 15:55 libsuil_gtk2_in_qt5.so
-rwxr-xr-x. 1 yam 19160 Feb 24 15:55 libsuil_qt4_in_gtk2.so
-rwxr-xr-x. 1 yam 24344 Feb 24 15:55 libsuil_qt5_in_gtk2.so
-rwxr-xr-x. 1 yam 24368 Feb 24 15:55 libsuil_qt5_in_gtk3.so
-rwxr-xr-x. 1 yam 16304 Feb 24 15:55 libsuil_x11.so
-rwxr-xr-x. 1 yam 28184 Feb 24 15:55 libsuil_x11_in_gtk2.so
-rwxr-xr-x. 1 yam 28360 Feb 24 15:55 libsuil_x11_in_gtk3.so
-rwxr-xr-x. 1 yam 31080 Feb 24 15:55 libsuil_x11_in_qt4.so
-rwxr-xr-x. 1 yam 31360 Feb 24 15:55 libsuil_x11_in_qt5.so
```

Ah wait…just guessing here, but I bet when suil got configured it didn’t find any Qt, Gtk, or X11 devel files.  Reconfigure and look for these lines.  I’d wager that all of your “Support for” lines say “no”.  I’m going to try and simulate there here, but it’d be good if you could confirm.

```
Setting top to                                : /home/yam/audacity/b/lib-src/lv2/suil
Setting out to                                : /home/yam/audacity/b/lib-src/lv2/suil/build
Checking for 'gcc' (C compiler)               : /usr/bin/gcc
Checking for 'g++' (C++ compiler)             : /usr/bin/g++
Checking for flag '-std=c99'                  : yes
Checking for link flags -Wl,-z,-nodelete      : yes
Checking for program 'pkg-config'             : /usr/bin/pkg-config
Checking for 'lv2 >= 1.16.0'                  : yes
Checking for 'x11'                            : yes
Checking for 'gtk+-2.0 >= 2.18.0'             : yes
Checking for 'gtk+-x11-2.0'                   : yes
Checking for 'gtk+-quartz-2.0'                : not found
Checking for 'gtk+-3.0 >= 3.14.0'             : yes
Checking for 'gtk+-x11-3.0 >= 3.14.0'         : yes
Checking for 'QtGui >= 4.4.0'                 : yes
Checking for 'Qt5Widgets >= 5.1.0'            : yes
Checking for header QMacCocoaViewContainer    : not found
Checking for library dl                       : yes
Install prefix                                : /home/yam/audacity/b/lib-src/lv2/build
C Flags                                       : -I/home/yam/audacity/b/lib-src/lv2/suil -DNDEBUG -fshow-column -std=c99
C++ Flags                                     : -I/home/yam/audacity/b/lib-src/lv2/suil -DNDEBUG -fshow-column
Debuggable                                    : no
Build documentation                           : no
Static library                                : yes
Shared library                                : no
Gtk2 Library Name                             : "libgtk-x11-2.0.so.0"
Gtk3 Library Name                             : "libgtk-x11-3.0.so.0"
Support for cocoa in gtk2                     : no
Support for gtk2 in qt4                       : yes
Support for gtk2 in qt5                       : yes
Support for qt4 in gtk2                       : yes
Support for qt5 in gtk2                       : yes
Support for win in gtk2                       : no
Support for x11 in gtk2                       : yes
Support for x11 in gtk3                       : yes
Support for qt5 in gtk3                       : yes
Support for x11 in qt4                        : yes
Support for x11 in qt5                        : yes
Support for cocoa in qt5                      : no
'configure' finished successfully (0.294s)
```

**Comment by xxjack12xx** [comment]
jack@b2:~ % fetch "
https://codeload.github.com/audacity/audacity/tar.gz/5a2eaf9?

 dummy=/audacity-audacity-5a2eaf9_GH0.tar.gz"
fetch:
https://codeload.github.com/audacity/audacity/tar.gz/5a2eaf9?dummy=/audac

         ity-audacity-5a2eaf9_GH0.tar.gz: size of remote file is not known
audacity-audacity-5a2eaf9_GH0.tar.gz                    60 MB  809 kBps
01m16s
jack@b2:~ % tar -xf audacity-audacity-5a2eaf9_GH0.tar.gz
jack@b2:~ % ls audacity-5a2eaf9/lib-src/lv2/build
ls: audacity-5a2eaf9/lib-src/lv2/build: No such file or directory
jack@b2:~ % ls -1 audacity-5a2eaf9/lib-src/lv2/build/lib/suil-0
ls: audacity-5a2eaf9/lib-src/lv2/build/lib/suil-0: No such file or directory
jack@b2:~ % ls -1 audacity-5a2eaf9/lib-src/lv2
Makefile
configure
lilv
lv2
serd
sord
sratom
suil
unpack-waf
windows
jack@b2:~ % ls -1 audacity-5a2eaf9/lib-src/
FileDialog
Makefile.am
Makefile.in
audacity-patches.txt
dist-libsoxr.mk
dist-libvamp.mk
dist-portaudio.mk
expat
ffmpeg
header-substitutes
lame
lib-widget-extra
libflac
libid3tag
libmad
libmp3lame
libnyquist
libogg
libscorealign
libsndfile
libsoxr
libvamp
libvorbis
lv2
mod-null
mod-nyq-bench
mod-script-pipe
mod-track-panel
mpglib
portaudio-v19
portburn
portmidi
portmixer
portsmf
sbsms
soundtouch
twolame

**Comment by lllucius** [comment]
Thanks, but I was looking for what your build directory contained after you run configure and make.  And the output from configure when it does suil.

**Comment by xxjack12xx** [comment]
My log is getting rejected for being too large. I've uploaded the log to my
server with the find cmd after the build.

https://www4.punkrockdemo.com/audacity.txt

Let me know when you've got it so I can delete it.

**Comment by lllucius** [comment]
I've got a copy.  And I do see the problem.  I made a bit of an assumption that the distro maintainers would be using the in-tree LV2 libs when it came to the installation step.

I've committed a fix.

But, keep in mind, that if we do release Audacity 2.4.0 using the CMake build, we will not be maintaining the Makefile build process any longer.

**Comment by xxjack12xx** [comment]
ok will test that out and let you know, thanks!

**Comment by xxjack12xx** [comment]
Looks like the fix worked. Thanks.

**Comment by JamesCrook** [comment]
Closing:
>Looks like the fix worked. Thanks.
