### ISSUE TITLE
Paste shifts Envelope Points elsewhere in track

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#4250]
### Bug description

Doing what should be a totally harmless paste, radically shifts envelope points located elsewhere in the track.

### Steps to reproduce

1. Generate 40-second chirp
2. F2 = Envelope Tool
3. Create three envelope points @ 20, 25, and 30, with a marked dip at 25. See screenshot
4. F1 = Selection Tool
5. Ctrl+D = Duplicate track
6. On duplicate track, select 1 second of audio between 5 and 6 seconds.
7. Cut and Paste this selected audio in place: Ctrl+X -> Ctrl+V
![Window018](https://user-images.githubusercontent.com/76828213/215351228-ffa0515e-f6c8-4c9d-9a54-3509cfeb3753.png)

### Expected behavior

I would expect to see no visible change

### Actual behavior

Envelope Points have shifted left by about 5 seconds

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

All OSs

### Additional context

This issue was originally reported by forum user ranlevi who has reported the issue here: https://forum.audacityteam.org/viewtopic.php?p=462723#p462723 and provided steps to reproduce here: https://forum.audacityteam.org/viewtopic.php?p=463181#p463181

Note that ranlevi also encountered a situation where envelope points could no longer be created.

**Comment by Ryan-Miller-Audacity** [comment]
I was able to reproduce this issue as described. Assigning P3.

**Comment by Ryan-Miller-Audacity** [comment]
Testing this against the current public release (3.3.2) I can confirm that this is still reproducible as described above.

**Comment by dozzzzer** [comment]
Fixed by #5043

**Comment by JohnColket** [comment]
Hurray! Unable to duplicate original complaint on nightly build: audacity-win-3.4.0-alpha-20231006+618d61e-x64-msvc2022.  Thank you @saintmatthieu. @LWinterberg.
