### ISSUE TITLE
[Plugin issue] - Calf Equalizer "Presets and Settings" button does nothing

### ISSUE THREAD

**Issue by evertvorster** [audacity/audacity#4252]
### Plugin

Calf Equalizer 12 Band

### Plugin Format

VST2

### Plugin source

Official Arch Repos

### Bug description

This effect used to have a way of storing various presets. Now when I click on the Presets & Settings button, nothing happens

### Steps to reproduce

Select audio
Select Calf Equalizer effect
Click on "Presets & Settings"

### Expected behavior

A menu should pop up where you can save and restore presets

### Actual behavior

Nothing happens

### Audacity Version

other

### Operating system

Linux

### Architecture

64 bit Intel/AMD processors

### Additional context

This is the qt branch of audacity, but it seems to be pretty close to master. Checked out with git on 30 January 2023

**Comment by evertvorster** [comment]
Ah, the latest release does not have this issue, currently rebuilding qt branch and checking again...

**Comment by crsib** [comment]
Qt branch is in a **very** early development stage. The default build will be just behind the master branch

**Comment by evertvorster** [comment]
Yeah, I noticed it is pretty close to master still. 

Is there any way that I can put bug reports against just a branch, rather than the whole code base?

I have no expectations of it magically working straight after the coding effort has begun, so no pressure there. 
However, I do run qt, and am quite willing to run testing of features and/branches, and then revert back to stable branches for my day to day work... :)

**Comment by evertvorster** [comment]
This bug is also present on latest master branch. 30 January 2023

**Comment by crsib** [comment]
> Yeah, I noticed it is pretty close to master still.

It's in much earlier state. I don't expect that this branch will be testable in the following months. The default build from that branch will just build Audacity master.

So yeah, this bug is definitely in master.

**Comment by evertvorster** [comment]
So, now this menu works as well, under latest release and git master. 
Whatever it was must have been a transient issue. I'll close this ticket now. Sorry for the bother.
