### ISSUE TITLE
Add support for "seconds + milliseconds".

### ISSUE THREAD

**Issue by JC3** [audacity/audacity#4258]
### Your idea

Add support for fractional seconds to time format widget.

### Problem to be solved

Lack of ability to go to 123.456 seconds in a project without doing mental hh:mm:ss.zzz conversion math. It's a bit absurd that this format is missing.

### Prior art

Generally solved by allowing fractional second inputs.

![image](https://user-images.githubusercontent.com/50205984/216412103-8cf6122e-9fbf-490b-a3e0-abc2d925f15e.png)

### Additional context

PR forthcoming.

**Comment by JC3** [comment]
See https://github.com/audacity/audacity/pull/4259.

**Comment by JC3** [comment]
See PR https://github.com/audacity/audacity/pull/4260.

Ignore PR #4259.

**Comment by petersampsonaudacity** [comment]
@LWinterberg @crsib 

This looks like a sensible addition to the time formats to me.

Plus @JC3 (Jason) has already done the work and issued a Pull Request for this - his branch build is pending approval, so at the moment I can't test this.

**Comment by petersampsonaudacity** [comment]
Just tested this on W10 with @JC3  Jason's branch:  audacity-win-3.2.4-alpha-20230203+0baa1bf-x64

This works fine for me in 
a) **Selection** toolbar
b) **Time** toolbar


![image](https://user-images.githubusercontent.com/50205984/216606231-66ba43f7-ad74-4193-ad5f-0e82ad40ab32.png)

**Comment by dozzzzer** [comment]
Verified

**Comment by petersampsonaudacity** [comment]
Tests OK on W10 with latest 3.3.0 alpha:  audacity-win-3.3.0-alpha-20230220+7ed07a8-x64-msvc2022

![image](https://user-images.githubusercontent.com/50205984/220101590-18cf3b59-e537-436e-ac0b-0bd9ea390c04.png)

**Comment by petersampsonaudacity** [comment]
I have updated the alpha Manual:

https://alphamanual.audacityteam.org/man/Selection_Toolbar#Selection_Formats
