### ISSUE TITLE
Add support for Windows Dark Theme mode

### ISSUE THREAD

**Issue by Giermann** [audacity/audacity#4262]
### Your idea

Audacity has multiple themes, including Light and Dark.
The Dark theme would look far better, if it addionally would support the Windows Dark theme for Apps.
It seems that wxWidgets supports this and there are applications (i.e. Notepad++) that already use this successfully.
(Maybe some patches were needed, have a look at the [source code](https://github.com/notepad-plus-plus/notepad-plus-plus/tree/master/PowerEditor/src/DarkMode).)

I would wish to have an additional "app theme" setting to set it to Light, Dark or "use system setting".

### Problem to be solved

Running Audacity with Dark Theme looks mixed between Light and Dark:
![grafik](https://user-images.githubusercontent.com/4408398/216556800-bfae1ab2-5fde-466f-97db-56b6ef7adbbe.png)

### Prior art

In Notepadd++, also the menu and dialog widgets look dark:
![grafik](https://user-images.githubusercontent.com/4408398/216557779-79bfb3bd-d314-439a-979d-76b5eb652cc3.png)

**Comment by LWinterberg** [comment]
Audacity is currently being ported to Qt, which will have a much more thorough dark mode. For a preview of how this might look like, you can check Musescore 4 - Audacity will be using its UI library. 

For wxwidgets, this isn't planned.
