### ISSUE TITLE
We have a problem,

### ISSUE THREAD

**Issue by FrostKnight** [audacity/audacity#4271]
### Bug description

sup Muse, I just wanted to thank you all, for your efforts to truly boost the moralle of audacity projects, by listening to your gut and not letting things like facts, rules and what people actually want get in the way of you guys accomplishing great things.

My main bug is that there aren't enough bugs!

Btw, make sure you dismount when you get off your horse before you get much closer to the top of that mountain your on, otherwise, you will fall to your doom. :)

Seriously though, wonderful job, the open source world couldn't have done better if microsoft and google got together and used that good ol integrity they had to show how much they actually care about open source or free software.

I mean its not like there was something called Embrace Extend Extinguish that was used by microsoft and google in order to close competitive projects that they wanted to kill, right?

So to conclude, just keep doing what your doing and don't worry about that iceberg ahead, the titantic survived it, so shall you!

:)

### Steps to reproduce

Open Audacity 
Press ALT F4 
The program closes for no reason!

### Expected behavior

I should be able to make a million dollars when I press ALT F4 after opening audacity program

### Actual behavior

The program just closes every time I try!

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

### Additional context

Windows 3.0

**Comment by Tantacrul** [comment]
Closing as not planned :)
