### ISSUE TITLE
Scripting documentation: "Time Shift" commands are not in Scripting Reference.

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#4278]
### Bug description

The new "Time Shift Left" / "Time Shift Right" commands have not been added to the [Scripting Reference](https://manual.audacityteam.org/man/scripting_reference.html) documentation.

### Steps to reproduce

1. Look up either the "Time Shift Left" or "Time Shift Right" commands in the  [Scripting Reference](https://manual.audacityteam.org/man/scripting_reference.html) documentation.

### Expected behavior

To find a brief description of the commands, parameters, and what they do.

### Actual behavior

The commands are not listed.

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

This issue was originally reported on the forum as:

> I am trying to create a macro that uses Time Shift Right command, but this feature is not allowing any parameters to be passed, and as a result does not perform the needed task.

Had the commands been documented in the Scripting Reference, the user would have been able to look them up.
The commands are documented in the "[Extra menu > Edit](https://alphamanual.audacityteam.org/man/Extra_Menu:_Edit#time_shift_left)" section, but that is hard to find unless you already know that it's there. The reference section needs to be complete and up to date.

**Comment by petersampsonaudacity** [comment]
Fixed in the alpha Manual for the upcoming 3.3.0 release

https://alphamanual.audacityteam.org/man/Scripting_Reference#Extra:_Edit

**Comment by petersampsonaudacity** [comment]
I made several other updates to the Scripting Reference page.
https://alphamanual.audacityteam.org/man/Scripting_Reference

I left a P1 for the two **Scrub** commands in the **Extra>Transport** menu 

I have no idea what they are supposed to do - and when I try to use them they seem to have no effect.  
@Paul-Licameli can you cast any light on these two commands?

**Comment by DavidBailes** [comment]
> I left a P1 for the two **Scrub** commands in the **Extra>Transport** menu
> 
> I have no idea what they are supposed to do - and when I try to use them they seem to have no effect.

https://alphamanual.audacityteam.org/man/Scrubbing_and_Seeking#Scrubbing_using_the_keyboard

**Comment by petersampsonaudacity** [comment]
@DavidBailes  yes holding down the U and I shortcuts invoke forwards and backwards scrubbing.

But I get nothing when I use **Extra > Transport > Scrub Backwards/Forwards**  - so I remain confused ...

**Comment by DavidBailes** [comment]
"After pressing one of the two keys playback continues until the key is released."
- you have to hold down one of the two keys.

**Comment by petersampsonaudacity** [comment]
So how do you use **Extra > Transport > Scrub Backwards/Forwards ** - there's nothing to "hold down" ???

**Comment by DavidBailes** [comment]
> So how do you use **Extra > Transport > Scrub Backwards/Forward**s - there's nothing to "hold down" ???

Those commands are there primarily so that users can know what their default shortcut keys are, and so they can change them in keyboard preferences if they want to.

**Comment by petersampsonaudacity** [comment]
OK so I have updated:

a)  https://alphamanual.audacityteam.org/man/Extra_Menu:_Transport#Scrubbing_commands

and

b) https://alphamanual.audacityteam.org/man/Scripting_Reference#Extra:_Transport

@LWinterberg  - subject to review I think this issue can be CLOSED as FIXED
