### ISSUE TITLE
Year needs to be updated in the About dialog

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4279]
### Bug description

<img width="610" alt="image" src="https://user-images.githubusercontent.com/70063970/216966143-4f94a0c9-fdbd-4702-8e3c-0456633396d6.png">

### Steps to reproduce

1. navigate to About dialog
2. check the year

### Expected behavior

1999 - 2023

### Actual behavior

1999 - 2021

### Audacity Version

latest beta

### Operating system

Other

**Comment by boomboss200** [comment]
I would like to work on this issue
