### ISSUE TITLE
'pop' appears at the start of the recorded file when this is exported by "export audio" with file type wav and alaw codec. It happens in windows version but does not in Linux versions.

### ISSUE THREAD

**Issue by ggcallejo** [audacity/audacity#4298]
### Bug description

Every time i export any kind of project to wav/alaw, a "pop" appears just at the beggining of the track. And, as this file/codec type can only be obtained by exporting audio (i mean, there is no "save" command for this) it is useless to remove the pop, as it will appear again when the file is exported.

I have found out this never happened with Linux version of Audacity, bu Windows (10 in my case). The bug is consistent across different PCs (at least 2).

### Steps to reproduce

1.- Start Audacity in Windows
2.- Create/open any kind of audio file
3.- Set project frecuency to 8000Hz (bottom left box)
4.- Edit as needed
5.- Go to File->Export Audio->Select filetype "Wav Microsoft" and "aLaw" as codec and clic on Save
6.- Close file and/or Audacity
7.- Start Audacity
8.- Go to File-> Import -> Raw Data -> Select File -> Codec: aLaw, ByeOrder: Default Endianness, Channels: 1 mono. Offset 0, Amount to import: 100%, sample frecuency: 8000 Hz and clic import
9.-> Play the file. You will hear (and see) the starting 'pop'

### Expected behavior

Get the aLaw file with expected sound, with no pops

### Actual behavior

starting 'pop'

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

Last checked with version 3.2.1. But traditionally happening with older versions also. And, for some reason, it never happens when using Linux versions.

**Comment by LWinterberg** [comment]
Well, yes. If you export as WAV, you export it as WAV. A WAV has a RIFF header. 

![image](https://user-images.githubusercontent.com/87814144/218065029-927c742b-259a-4ae7-bd9d-d09b8e5d42d4.png)

![image](https://user-images.githubusercontent.com/87814144/218065298-cc00f244-7c4b-401b-9229-0a3934414678.png)

If you want to export raw data, use

> Type: Other uncompressed files
> Header: RAW (header-less)
> Encoding: (whatever you want, in your example A-Law)

**Comment by ggcallejo** [comment]
You're right.

Obviously i missed the exporting parameters. Sorry for bothering.

And thank you for quick reply and help.

Gonzalo García
