### ISSUE TITLE
sound device is not released any more

### ISSUE THREAD

**Issue by ossilator** [audacity/audacity#4300]
### Bug description

the audio device is now kept open after the initial probing, so i can't unload the driver anymore without quitting audacity first.

### Steps to reproduce

just start it.

### Expected behavior

device is closed until it is actually used.

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

### Additional context

i'm using audacity mostly just as an elaborate wave viewer, and i basically want it to stay away from any actual audio devices, as that interferes with the low-level work i do.

so minimally, you can spin off a feature request to make it possible to select no audio devices. this would (obviously) disable all playback and recording functions.

also, it would probably make sense to limit the device probing to the actually selected device until the audio setup is opened.

**Comment by LWinterberg** [comment]
FWIW: not closing the device has been a long-standing request (#711). I don't know whether that particular thing is fixed by whatever recent changes happened though. 

Your particular use case is much rarer than the typical user, and I don't think we want to support it. I recommend either grabbing an [older version](https://www.fosshub.com/Audacity-old.html) (up to 3.0.3 exists as an appimage, before that you'll have to compile yourself), or an actual wave viewer (kst, gwave, gtkwave, etc).

**Comment by crsib** [comment]
> I don't know whether that particular thing is fixed by whatever recent changes happened though.

Nope, current versions of Audacity only open the devices when doing playback and/or recording. Otherwise, device stays closed

**Comment by ossilator** [comment]
keeping the server connection open does sound like a good idea, but that doesn't mean that direct device access should do the same. but of course the abstraction through libalsa makes it hard to discriminate. i suppose one could make it an explicit option, though one might consider that too technical for "regular" users.

therefore, i'd like you to concentrate on the last two paragraphs from the request. do you want to re-purpose the issue, or should i create a new one?

i tried various wave viewers. the audio-oriented ones suck (sonic-visualizer comes closest, but is bugged), while the scientific ones require data conversion in advance, which complicates and slows down matters.
