### ISSUE TITLE
sound device setup got way too "smart"

### ISSUE THREAD

**Issue by ossilator** [audacity/audacity#4301]
### Bug description

the recording device selection appears rather broken: it seems to find a mixer device on one of the cards, assumes that it can use that for the actual source selection (no!), and then goes on to multiplex the apparently available sources over other soundcards that have absolutely nothing to do with that mixer (!?!).

### Steps to reproduce

open the recording device dropdown in either location.

### Expected behavior

there should be an option to not touch the mixer at all.
i'm not sure how to integrate that into the UI, as it would be ideally a per-card option.

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

### Additional context

the card in question is an E-MU 0404 (emu10k1 driver), and the mixer allows configuring each output and recording channel separately. this clearly doesn't fit the model audacity assumes.

as secondary cards i have on-board HDA and the graphics card's HDMI output.

**Comment by LWinterberg** [comment]
Audacity doesn't make any assumptions about the capabilities of devices, it simply lists all your devices (for ALSA, this would be `arecord -L` and `aplay -L`). You may be able to screw around in some system configs to reduce this list. It won't get fixed here anyway.

**Comment by ossilator** [comment]
> Audacity doesn't make any assumptions about the capabilities of devices

that is obviously counter-factual.

> You may be able to screw around in some system configs to reduce this list.

yes. i could remove the sound card (or its driver) that is confusing audacity. do you seriously consider that an adequate solution?

and even if we ignore everything else, there is still the bogus correlation of mixers and pcms that live on different cards.
