### ISSUE TITLE
No preview progress dialog for some of the built-in effects

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4307]
### Steps to reproduce

1. Have some audio
2. Select it
3. Effect > Distortion (or Phaser, Bass & Treble, Wah Wah, Reverb)
4. Click 'Preview'
5. Observe

### Expected behavior

Preview progress dialog appears:

<img width="194" alt="image" src="https://user-images.githubusercontent.com/70063970/218543576-5dd974e9-c003-48c9-9c77-0dfe29de574a.png">

### Actual behavior

No preview progress dialog

### Audacity Version

current master / alpha / nightly build

### Operating system

All

### Additional context

Bisects to: https://github.com/audacity/audacity/commit/c3d6e37b2d0ddec9f1b4643f2451c31a6b060a1b

**Comment by petersampsonaudacity** [comment]
@dozzzzer 

This affects **_all_** the built-in effects that have been real-time enabled for use in the effests stack

1. Phaser
2. Wahwah
3. Reverb
4. Bass and Treble
5. Distortion

The "Preview" no longer plays a short preview but plays the whole selection

An easter-egg advantage is that in the Preview for these effects when invoked in destructive mode from the Effect menu the controls can be adjusted in real-time in the preview before being applied destructively.

**Comment by dozzzzer** [comment]
closing as a duplicate of #4323
