### ISSUE TITLE
Remote interface/command for integration to other software

### ISSUE THREAD

**Issue by Amitkapadi** [audacity/audacity#431]
My suggestion is to set up a remote interface/command (Like VLC) so we can use Audacity with other software integration, for example, Audacity with Unity, when you play the animation in unity at that time audacity plays current audio.

Using this type of interface Artist can make music or SFX for their requirement/and test it quickly

**Comment by JamesCrook** [comment]
Does scripting https://alphamanual.audacityteam.org/man/Scripting do what you need already?

**Comment by JamesCrook** [comment]
This kind of automation is being done with python scripting to interoperate between blender and Audacity.
