### ISSUE TITLE
Error message in the Normalize effect dialog doesn't fit 

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4310]
### Steps to reproduce

1. Bring up the Normalize effect
2. Enter a positive value
3. Observe

### Expected behavior

The dialog is wide enough to fit the error message in brackets
![image](https://user-images.githubusercontent.com/50205984/219004783-38355a53-3365-4e85-8abd-96d03f336e40.png)

### Actual behavior

The error message in brackets - "Maximum 0 dB" - doesn't fit the window and becomes hidden:

![2023-02-14_17-35-10 (1)](https://user-images.githubusercontent.com/70063970/218800432-9f052b2f-9c20-4677-86fb-3c6e24820882.gif)

### Audacity Version

current master / alpha / nightly build

### Operating system

Other

**Comment by Ritikkhulbe** [comment]
hey @dozzzzer , i would like to work on this issue and possibly i'll fix it.

**Comment by dozzzzer** [comment]
> i would like to work on this issue and possibly i'll fix it.

Great! Feel free to create a PR once you figure it out and we'll review it.

**Comment by Ritikkhulbe** [comment]
hey @dozzzzer , i'm having some issue about Cmake GUI not being able to detect VS code while configuring and hence im unable to run the software, if you can help me then pls contact me on my discord at Mello#1426 , else i'm looking for a solution to the problem

**Comment by vsverchinsky** [comment]
> hey @dozzzzer , i'm having some issue about Cmake GUI not being able to detect VS code while configuring and hence im unable to run the software, if you can help me then pls contact me on my discord at Mello#1426 , else i'm looking for a solution to the problem

hey @Ritikkhulbe did you use the official instruction to configure and build Audacity? https://github.com/audacity/audacity/blob/master/BUILDING.md

**Comment by Ritikkhulbe** [comment]
hey @vsverchinsky , thanks a lot, I went through it but didn't read it properly earlier
this is my first contribution, and I hope to do many more

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @Ritikkhulbe 's branch build: audacity-win-3.3.0-alpha-20230218+0ee4c00-x64

This looks better as the dialog is full-size from the get-go
![image](https://user-images.githubusercontent.com/50205984/219864613-30b6c036-5b73-4a94-9e54-3ccbff33626e.png)


But it is a little cramped on the right, would look better with a little space on the right of the closing bracket:
![image](https://user-images.githubusercontent.com/50205984/219864714-681e9a08-027b-4ecd-819d-6dc9987df582.png)

**Comment by petersampsonaudacity** [comment]
testing with @Ritikkhulbe 's latest branch build:  audacity-win-3.3.0-alpha-20230218+50ee0f0-x64

This now looks better to me (thanks for that) :
![image](https://user-images.githubusercontent.com/50205984/219879945-f1c800b0-61f1-4772-8868-232e0c278e32.png)


BTW I am not a decision-maker, I'm not a Muse bod, _I used to do QA on the old Audacity Team before Audacity bought the project a couple of years ago_, so the final yeah/nay will need to come from Muse anyway.

**Comment by player-29** [comment]
Hello  Dozzer,I would like to contribute in this issue. Can you please assign me this issue?

**Comment by dozzzzer** [comment]
Hello, @player-29 

The ticket already has a PR which has not been merged yet

**Comment by kshitiz-goel07** [comment]
Hello , @dozzzzer 
I can resolve this bug.
Just let me know , About current PR

**Comment by sunny2508** [comment]
I am new to contributing to opensource and I want to contribute to this project but I am not able to find where this issue is located. I searched for normalize dialog in normalize.cpp file but I am not finding where this issue is located. Can anyone help me in this

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
