### ISSUE TITLE
Automatic update or update notification for FFmpeg

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4319]
### Your idea

Audacity now has a very nice mechanism for informing users that a newer stable released version of Audacity is available.

**_BUT_** the user appears to have no similar mechanism for warning them (as in my case) that their FFmpeg is out of date and should be updated.

Is there any chance that we could have such a mechanism for FFmpeg:
a) a test at installation (or better on launch) time if the user already has an old FFmpeg installed and install it for them? 
b) Or possibly a "check for updates" in the Libraries prefs dialog?

### Problem to be solved

Users can unknowingly be running with a very out of date (but still vaguely functional)  version of FFmpeg.
_I was when testing #4309 - until @crsib kindly advised me to upgrade._

There is no mechanism or test to advise users that a better, newerm version of FFmpeg may be available

### Prior art

Not applicable

### Additional context

None

**Comment by crsib** [comment]
It's a complicated topic. We hardly ever build FFmpeg ourselves or ask Arturo to update the FFmpeg on his site. We cannot host it ourselves as the legality of this action is not entirely clear.

The reason we have updated FFmpeg this time is quite simple - we have introduced AppleSilicon support so we had to build ARM version of FFmpeg as well. We have no plans to provide updated FFmpeg libraries in the future.
