### ISSUE TITLE
An effect's preview progress dialog may be covered by the effect's dialog itself

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4323]
In some cases, when using effects like Amplify, the preview progress dialog won't show up because it gets overlapped by the effect's dialog itself. It doesn't happen 10/10 times but it's still somewhat easy to reproduce.

STR:
1. Have some audio and make a selection a few seconds long
2. Bring up the Amplify effect
3. Click in a random spot of the amplification slider to set a new amplification value
4. Click the Preview button
5. Repeat steps 3 & 4 until the Preview progress dialog won't show up

![2023-02-16_14-50-56 (1)](https://user-images.githubusercontent.com/70063970/219384162-800638db-a8b2-42fb-8c59-3ad2601cf857.gif)

OS: macOS
The issue bisects to https://github.com/audacity/audacity/commit/95b7997ebb56e914d185cc3ed07e2dc55b7d5699

_Originally posted by @dozzzzer in https://github.com/audacity/audacity/issues/4257#issuecomment-1433126368_

**Comment by petersampsonaudacity** [comment]
I can't reproduce this on W10  with 3.24 or 3.3.0 alpha with longer selections.

With very short sub 0.25 secs the the preview plays too quickly for the progress dialog to show.

**Comment by dozzzzer** [comment]
> I can't reproduce this on W10

My bad, forgot to put a macOS tag on it, I don't see it on Windows either

**Comment by dozzzzer** [comment]
Some other effects, including Normalize and Echo, are also affected by this

<img width="499" alt="image" src="https://user-images.githubusercontent.com/70063970/220125461-5afa5490-c056-4a51-aafb-f546f76f3a3d.png">

**Comment by dozzzzer** [comment]
Testing PR #4588 
The issue remains to be the case 
![image](https://user-images.githubusercontent.com/70063970/234430723-a5a9628d-0a88-4ab5-9295-46cd89dc9ffc.png)
