### ISSUE TITLE
3.2.4 crashes when trying to build a macro

### ISSUE THREAD

**Issue by twj815** [audacity/audacity#4330]
### Bug description

Ver. 3.2.4 64 bit on Win10

When I try to create a new macro, Audacity crashes as soon as I press Insert. The individual effects that I want to put into the macro work but I can't get that far before the program crashes. Audacity then creates a crash report but it fails to send. 

### Steps to reproduce

1. In Audacity 3.2.4 64 bit, click Tools then Macro Manager.
2. In the left pane, either select an existing macro or click New to create a new macro.
3. In the Right pane, click Insert.
4. Audacity crashes and creates a crash report that fails to send.

### Expected behavior

After clicking Insert, I expect to be able to add an effect to the right pane but Audacity crashes before I get that opportunity.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by petersampsonaudacity** [comment]
Testing on W10 I acnnot reproduce this with 3.2.4 or with the latest 3.3.0 alpha that I have  audacity-win-3.3.0-alpha-20230217+58a44f3-x64-msvc2022

**Comment by twj815** [comment]
So, how do we proceed since it happens to me every time I try it? Would you like to see a video of it happening? Can I attach a copy of the crash report here since it fails when I try to "Send" it?

**Comment by JohnColket** [comment]
You can try Tools > Reset Configuration

If that yields no change, try deleting (or renaming) the C:\Users\<your name.\AppData\Roaming\audacity folder.  Note that your existing macros may be stored in this folder.

**Comment by twj815** [comment]
If I reset the configuration in 3.2.4 64 bit will that also affect the configuration of version 3.1.3 32 bit which I am currently using until I can make the new version useable? If so, I will not be able to do that for some time since I am in the middle of a rather large project in 3.1.3 32 bit and I don't want to risk losing working macros right now.

**Comment by JohnColket** [comment]
> If I reset the configuration in 3.2.4 64 bit will that also affect the configuration of version 3.1.3 32 bit which I am currently using

Yes it will.  That is the reason for renaming the old directory. :smiley:

Note that Audacity provides a way for you to keep your Preference settings with the application, rather than in a global place for user settings.  See: https://manual.audacityteam.org/man/portable_audacity.html

**Comment by dozzzzer** [comment]
Cannot reproduce on Windows 11 and version 3.2.4.
