### ISSUE TITLE
German spelling error in v3.2.4

### ISSUE THREAD

**Issue by mathpoli** [audacity/audacity#4333]
### Bug description

In Audacity version 3.2.4 for German macOS 10.15.7, I found two spelling errors in the menus.

Instead of "Audioclips" it says "Audi%oclips", see images.

### Steps to reproduce

Open menues and look at them. 
:-)

### Expected behavior

No misspellings.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS

**Comment by petersampsonaudacity** [comment]
Confirmed, testing on W10 with 3,2,4
![image](https://user-images.githubusercontent.com/50205984/219963436-e97797c8-7a7c-405a-8d31-74653a514050.png)

and
![image](https://user-images.githubusercontent.com/50205984/219963487-b16e7529-bbfd-4f55-8d4e-13784ad5d424.png)

**Comment by LWinterberg** [comment]
This is already fixed in https://github.com/audacity/audacity/commit/698fe11c77604c9581c409e21ff5de649a56f71b

**Comment by mathpoli** [comment]
It's still there in v3.2.5.0.

I don't understand what [LWinterberg](https://github.com/LWinterberg) meant by writing "(the & converts to an accelerator key, ie the underline when you tap Alt)". 

When I press the "alt" key on my keyboard, nothing changes. Maybe I am too dumb for that. Sorry to bother!

**Comment by mathpoli** [comment]
Thanks,but this behaviour is not working with macOS 10.15.7 on two of my iMacs.

What OS are you working with?
