### ISSUE TITLE
Crashing when Exporting to Apple Lossless Audio

### ISSUE THREAD

**Issue by jadenquinn** [audacity/audacity#4339]
### Bug description

I use Audacity to capture audio from games, and then I export as an Apple Core Audio File, as a Lossless Apple Codec, and it fails right at the end. I remember the first few times this happened, the file WAS actually usable and playable fully, but now for some reason that is not the case.
Video: https://youtu.be/-hrTXa3ZqTc

### Steps to reproduce

1. Buy an Intel Mac.
2. Open Audacity and record.
3. Export as an Apple Core Audio File as a Lossless Apple Codec.
4. Watch it break.

### Expected behavior

It should work.

### Actual behavior

It not working.
Video: https://youtu.be/-hrTXa3ZqTc

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS

### Additional context

I'm on an Intel MacBook Pro 16-inch (2019).

**Comment by dozzzzer** [comment]
Could not reproduce on Macbook M1

**Comment by Ryan-Miller-Audacity** [comment]
Testing this on my 2011 Intel Macbook I have been unable to reproduce this as well using the details provided above. I observed a brief hang/pause at the end of the export process; however, I was never able to achieve a full crash.

@jadenquinn do you receive the crash as well if you do not open the intermediary program and such as seen in the video? Just going through export, meta tags, process, done.

**Comment by jadenquinn** [comment]
I can't for the life of me remember why I was exporting to Apple Lossless. I use WAV now, please disregard.
