### ISSUE TITLE
Performance Increase

### ISSUE THREAD

**Issue by jadenquinn** [audacity/audacity#4340]
### Your idea

I would like the editor to not be extremely laggy when scrolling, I work very very quick and this slowdown doesn't seem to be there for any good reason, it's like 6fps at most..

### Problem to be solved

Lag.

**Comment by Legosi13** [comment]
You and me both. I don't have the best machine in the world, but 16GB with a 3ghz CPU shouldn't at all warrant such absurd lag. Literally Audition, which is essentially 20x more complex than Audacity fairs better, even with a taxing task.

**Comment by LWinterberg** [comment]
Audacity's waveform rendering indeed is much slower than expected, but it should get better in the Qt port that's currently being worked on. This will take a while. As a workaround, you can improve FPS somewhat by making the window less wide. 

I'll close this particular issue as the corresponding programming task will be more among the lines of "implement waveforms in qt" than this.
