### ISSUE TITLE
Tracks Behaviors prefefences dialog window is not long enough

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4341]
### Bug description
The new preferences introduced in 3.3.0 for controlling the behaviors on copying clips to new projects overflow the size of the window for Tracks Behaviors preferences,  The window needs to be a little longer

### Steps to reproduce
1. launch 3.3.0 alpha
2. Edit > Preferences > Tracks Behaviors
3. Observe: text at the bottom of the parameters pane is trimmed and obscured

### Expected behavior
**Sufficient room to show the full set of parameters**
![image](https://user-images.githubusercontent.com/50205984/220298904-8fb3e45e-68ab-4171-93a3-374d1a72a918.png)

### Actual behavior
**Insufficient room to show the full set of parameters**
![image](https://user-images.githubusercontent.com/50205984/220300188-9cbcc5a5-340b-4948-9d75-560635ada2b7.png)

**Worse on Mac - a whole parameter is missing/obscured**
![image](https://user-images.githubusercontent.com/50205984/220304143-9055112a-eee7-48d1-a063-2e4041f5a742.png)

### Audacity Version
3.3.0 alpha:  audacity-win-3.3.0-alpha-20230220+55584ef-x64-msvc2022(2)

### Operating system
Windows 10  and macOS 12.6.3 Monterey - but assume all OS

### Additional context
See also:   
**Clip copy dialog #4033** 
**Add prompt dialog when copying clips between projects #4004**
**Performance and file size issues when copying and pasting a small portion of a very large clip #3820**

**Comment by LWinterberg** [comment]
> Worse on Mac - a whole parameter is missing/obscured

But it's not missing - there is a scrollbar. People understand what scrollbars are.

**Comment by petersampsonaudacity** [comment]
> > Worse on Mac - a whole parameter is missing/obscured
> 
> But it's not missing - there is a scrollbar. People understand what scrollbars are.

Some of them do, but not all.

Is there a problem with making the dialog a  little longer in height?
