### ISSUE TITLE
Clip Copy dialog: the "Audio data" figure is misleading

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4344]
### Bug description

In the Clip Copy dialog introduced for 3.3.0 when copying a selection from one project to another a calculated figure is shown:
**Audio data is xx.x MB. Larger sizes will take longer to paste.**

This figure remains the same if the user changes from the default option of **copy to full clip** to just **copy the selection** (which is normally a _**lot**_ smaller.

### Steps to reproduce

1. Generate a 1 hour chirp
2. select a 5 minute chunk of audio
3. Ctrl+C to copy the "selection" to the clipboard
4. Ctrl+N to open a new project
5. Ctrl+V to paste into the new project
6. Observe: in the Clip Copy dialog the data size is reported as 605.6 MB with the default **Smart clip** setting
7. Select the **Selected audio only** radio button
8. Observe: the data size remains reported as 605.6 MB

### Expected behavior
Proper size for the data occupancy of only the selection to be reported when **copy the selection**  is active.

**Smart Clip**   -  605.5 MB is the expected size for a full 30 minute chirp
![image](https://user-images.githubusercontent.com/50205984/220390014-72faeb9b-281b-4c5c-adff-7abb0172fd37.png)

**Selection only**  -  50.5 MB is the expected size for a five minute selection
![image](https://user-images.githubusercontent.com/50205984/220392311-5a436845-2732-4bf0-8015-5848c68b6c88.png)

### Actual behavior
Misleading data size reported for the selection to be copied when **copy the selection**  is active.

**Smart Clip**   -  605.5 MB is the expected size for a full 30 minute chirp
![image](https://user-images.githubusercontent.com/50205984/220390036-d3d4c5a4-a1b5-4324-a9a3-c1966c38c75d.png)

**Selection only**  -  still showing as 605.5 MB and **_not_** the reduced 50.5 MB, the expected size for a five minute selection
![image](https://user-images.githubusercontent.com/50205984/220390527-5f7b940f-8e93-441c-88a9-9a994a814e0a.png)

### Audacity Version
3.3.0  audacity-win-3.3.0-alpha-20230220+55584ef-x64-msvc2022(2)

### Operating system
Windows 10 - but assume all OS

### Additional context
See:  Add prompt dialog when copying clips between projects #4004 
and:  Performance and file size issues when copying and pasting a small portion of a very large clip #3820

**Comment by petersampsonaudacity** [comment]
I have updated the Tracks Behaviors preferences page in the Manual with an advice dive about this issue:
![image](https://user-images.githubusercontent.com/50205984/220398888-64c0e130-b3e0-4242-8442-32eaf9d24063.png)

**Comment by dozzzzer** [comment]
This isn't a bug really, although I agree it would be a nice-to-have improvement to the existing implementation.

**Comment by petersampsonaudacity** [comment]
@dozzzzer 
> This isn't a bug really, although I agree it would be a nice-to-have improvement to the existing implementation.

Maybe technically not a "bug" - a "feature" since it was designed this way.

And certainly misleading - if  this can't or won't be fixed than maybe the text could be revised for clarity to say:

**The entire source clip is xx.x MB. Larger sizes will take longer to paste.**

**Comment by LWinterberg** [comment]
This is just a small string update, is it not? 
"The full smart clip is..."

**Comment by petersampsonaudacity** [comment]
> This is just a small string update, is it not? "The full smart clip is..."

That would certainly be a "fix".

It would be useful to to show the user the size of the selection too for comparison. perhaps alongside/below the Smart Clip(s) size (rather than be triggered by the radio button selection made by the user as I suggested previously).

**Comment by petersampsonaudacity** [comment]
@LWinterberg   -  this issue is likely to become apparent to real-life users once 3.3.0 is released shortly.

Up to now it's only QA (and devs) who have seen and experienced the ability to just copy the selected data in the alpha/beta builds.  With the release of 3.3.0 all users will get to see this.

**Comment by petersampsonaudacity** [comment]
BUMP - @LWinterberg  might this get actioned for 3.4.0
