### ISSUE TITLE
[audio.com] With an expired refresh token Audacity spams auth endpoint

### ISSUE THREAD

**Issue by crsib** [audacity/audacity#4373]
### Bug description

With an expired refresh token Audacity spams auth endpoint

### Steps to reproduce

Audacity spams endpoint

### Expected behavior

Audacity should not spam endpoint

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows, macOS, Linux

**Comment by dozzzzer** [comment]
Verified on macOS and Windows
