### ISSUE TITLE
Stereo Tool/Perfect Declipper VST3 Plugin always crashes Audacity on second use

### ISSUE THREAD

**Issue by mutaunt** [audacity/audacity#4382]
If you open Audacity, open an audio file, open the Stereo Tool VST3 plugin, it works OK.  But if you open Stereo Tool a second time  Audacity crashes.  This happens even if:

- you open Stereo Tool, immediately close it, then open it again
- you open Stereo Tool, use/close it, use another plugin, then open Stereo Tool a second time
- use Stereo Tool on one file, open another file, open Stereo Tool again

Happens for me on 3.2.3, 3.2.4, 3.2.5.  Don't know about earlier versions.
Using Stereo Tool v9.92 (latest)

I've attached the crash report.  Exception code 0xc0000005

This may be a bug in the plugin, but Audacity shouldn't crash.

[Stereo Tool Audacity crash report.txt](https://github.com/audacity/audacity/files/10878214/Stereo.Tool.Audacity.crash.report.txt)

**Comment by dozzzzer** [comment]
I've tried to reproduce it using all three scenarios @mutaunt posted, but none of those led to the crash. 
Audacity: 3.2.5
Plugin: [Thimeo Stereo Tool 9.92 ](https://www.thimeo.com/stereo-tool/download/)

**Comment by mutaunt** [comment]
That's interesting @dozzzzer.  So what's the difference?  I'm using:

- an old AMD Phenom 8 core CPU, 16GB RAM, lots of free space on C drive (SSD)
- Audacity 64bit installed in default C:\Program Files\Audacity
- Stereo Tool (licensed) in C:\Program Files\Common Files\VST3
- OS is Windows 10

If you have any suggestions for things I could change they'd be welcome.  Since posting I've tried without success:

- remove plugin, rescan plugins in Audacity, reinstall plugin, rescan plugins
- Audacity reset configuration

Nothing stops the crash on second opening of the plugin.

**Comment by dozzzzer** [comment]
@mutaunt could you please re-check if the problem exists in the latest version 3.3.2?

**Comment by mutaunt** [comment]
Yes, still happens 3.3.2.

Crash report attached.

[Stereo Tool Audacity crash report 2023-05-13.txt](https://github.com/audacity/audacity/files/11468322/Stereo.Tool.Audacity.crash.report.2023-05-13.txt)

**Comment by mutaunt** [comment]
Still happened 3.3.3.

But does NOT happen with new Thimeo Stereo Tool 10.10 recently released.

So some odd interaction with the previous version of the plugin and my PC???  Guess we'll never know root cause now.
