### ISSUE TITLE
linux compile

### ISSUE THREAD

**Issue by ohquait** [audacity/audacity#4391]
### Bug description

compilation breaks jst at this point, 
all deps are installed and on as actual versions

i am not a coder, just a packager

### Steps to reproduce

cmake .....
cmake_build

### Expected behavior

build braek

### Actual behavior

not knowing

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Linux

### Additional context

/usr/include/c++/12.2.1/bits/hashtable_policy.h: In instantiation of ‘std::__detail::_Hash_code_base<_Key, _Value, _ExtractKey, _Hash, _RangeHash, _Unused, __cache_hash_code>::__hash_code std::__detail::_Hash_code_base<_Key, _Value, _ExtractKey, _Hash, _RangeHash, _Unused, __cache_hash_code>::_M_hash_code(const _Key&) const [with _Key = wxString; _Value = std::pair<const wxString, TranslatableString>; _ExtractKey = std::__detail::_Select1st; _Hash = std::hash<wxString>; _RangeHash = std::__detail::_Mod_range_hashing; _Unused = std::__detail::_Default_ranged_hash; bool __cache_hash_code = true; __hash_code = long unsigned int]’:
/usr/include/c++/12.2.1/bits/hashtable_policy.h:773:45:   required from ‘std::__detail::_Map_base<_Key, std::pair<const _Key, _Val>, _Alloc, std::__detail::_Select1st, _Equal, _Hash, _RangeHash, _Unused, _RehashPolicy, _Traits, true>::mapped_type& std::__detail::_Map_base<_Key, std::pair<const _Key, _Val>, _Alloc, std::__detail::_Select1st, _Equal, _Hash, _RangeHash, _Unused, _RehashPolicy, _Traits, true>::operator[](const key_type&) [with _Key = wxString; _Val = TranslatableString; _Alloc = std::allocator<std::pair<const wxString, TranslatableString> >; _Equal = std::equal_to<wxString>; _Hash = std::hash<wxString>; _RangeHash = std::__detail::_Mod_range_hashing; _Unused = std::__detail::_Default_ranged_hash; _RehashPolicy = std::__detail::_Prime_rehash_policy; _Traits = std::__detail::_Hashtable_traits<true, false, true>; mapped_type = TranslatableString; key_type = wxString]’
/usr/include/c++/12.2.1/bits/unordered_map.h:980:20:   required from ‘std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::mapped_type& std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::operator[](const key_type&) [with _Key = wxString; _Tp = TranslatableString; _Hash = std::hash<wxString>; _Pred = std::equal_to<wxString>; _Alloc = std::allocator<std::pair<const wxString, TranslatableString> >; mapped_type = TranslatableString; key_type = wxString]’
/home/quait/src/rpm/BUILD/audacity-sources-3.2.5/libraries/lib-strings/Languages.cpp:216:32:   required from here
/usr/include/c++/12.2.1/bits/hashtable_policy.h:1268:23: error: static assertion failed: hash function must be invocable with an argument of key type
 1268 |         static_assert(__is_invocable<const _Hash&, const _Key&>{},
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/12.2.1/bits/hashtable_policy.h:1268:23: note: ‘std::__is_invocable<const std::hash<wxString>&, const wxString&>()’ evaluates to false
/usr/include/c++/12.2.1/bits/hashtable_policy.h:1270:25: error: no match for call to ‘(const std::hash<wxString>) (const wxString&)’
 1270 |         return _M_hash()(__k);
      |                ~~~~~~~~~^~~~~
make[2]: *** [libraries/lib-strings/CMakeFiles/lib-strings.dir/build.make:121: libraries/lib-strings/CMakeFiles/lib-strings.dir/Languages.cpp.o] Error 1
make[2]: Leaving directory '/home/quait/src/rpm/BUILD/audacity-sources-3.2.5/build'
make[1]: *** [CMakeFiles/Makefile2:966: libraries/lib-strings/CMakeFiles/lib-strings.dir/all] Error 2
make: *** [Makefile:159: all] Error 2
error: Bad exit status from /home/quait/src/tmp/rpm-tmp.JPvket (%build)

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444) which uses a different build system. This bug should no longer be applicable.
