### ISSUE TITLE
ERA 6 plugin not working as macro [Plugin issue] 

### ISSUE THREAD

**Issue by ihubgit** [audacity/audacity#4397]
### Plugin

Accusonus ERA6

### Plugin Format

VST3

### Plugin source

https://accusonus.com/

### Bug description

wrote a macro for the free ERA6 bundle as following :
_Era6VoiceAutoeq:Use_Preset="<Current Settings>"
Era6VoiceLeveler:Use_Preset="User Preset:breath+emphasis"
Era6VoiceDeepener:Use_Preset="<Current Settings>"
Era6NoiseRemoverPro:Use_Preset="User Preset:DETAILED DENOISE LOW"
ExportWav:_
When running the macro, it stops.
I tried to manually apply just one ERA6 effect in the editor window and this doesn't work neither.

### Steps to reproduce

1. go to macro manager
2. copy-paste the settings above
3. from the manage macros windows select 'apply macro to' files
4. select the desired files
5. let the macro run

### Expected behavior

the macro ought to apply the VST effects to the batch of the selected files.

### Actual behavior

I see a dialog window with a progress bar for a split second, but there's no macro output (and yes, i created a dedicated forlder in audacity settings - directory - for that on forehand)

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS

### Architecture

Apple Silicon (M1, M2, ...)

**Comment by dozzzzer** [comment]
@ihubgit given the official Accusonus website seems to be down for a long time, as well as there're no other sources to grab ERA 6 from, there's no way we can even try to reproduce it.
