### ISSUE TITLE
Export should default be to the same folder as where it opens

### ISSUE THREAD

**Issue by a-einstein** [audacity/audacity#4398]
### Your idea

Obviously I probably want to write an edited file back to the same directory as where I read it.

In my case e.g. after cropping off silence.

### Problem to be solved

Unnecessarily need to browse TWICE to the same folder.

**Comment by dozzzzer** [comment]
@a-einstein 
Currently, Audacity remembers directories used for each operation separately, i.e. Import/Export, Save/Open
Meaning that if you import some audio from directory A and try to export it, it defaults to the directory B used previously for _export_ operation (if there were any), not the one used for import

Generally, I think this is a highly disputable question of whether or not it should always navigate to the same folder used for both open/save and import/export operations.

**Comment by dozzzzer** [comment]
Plus, if you go to **Preferences > Directories**, you can actually specify the directories you always want to go to for each operation which gives you the ability to customize it in a desirable way:

<img width="450" alt="image" src="https://user-images.githubusercontent.com/70063970/224754363-0be27c5a-ff64-49b5-9271-5a973a2f7614.png">

With that being said, I don't think there's any solid reasoning for changing this to the solution proposed by @a-einstein
