### ISSUE TITLE
Clicking during playback after update to 3.2.5

### ISSUE THREAD

**Issue by WMRG1057** [audacity/audacity#4404]
### Bug description

Random clicks during playback 
Loaded up 5 copies of the "same" track. an AIF, 2 processed WAVs and 2 MP3s
to compare and switch while listening to.

### Steps to reproduce

started playback and heard random clicks. Not in the same location each time.
While trying to use the Solo and Mute button there were clicks and dropouts.

running an i5-4460 at 3.2G with 16 GB memory win 10 latest patches
max CPU was less than 25% 
files are a half hour. 

Just upgraded to 3.2.5

plan to down grad to 3.2.0 and see if it still happens later. or on different machines

### Expected behavior

no clicks during playback or while switching between track using the solo or mute button.

### Actual behavior

Random clicks

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

external sound Alesis IO Hub
No problem with files when play with other software

**Comment by petersampsonaudacity** [comment]
I cannot reproduce this on W11 with 3.2.5 (or the latest alpha test build I have for the upcoming 3.3.0)

**Comment by WMRG1057** [comment]
Planning on running some more test later this week. It's not consistently
in the same locations but quite noticeable.
Will update.

**Comment by dozzzzer** [comment]
I cannot reproduce this on Windows 11 and Audacity 3.2.5
