### ISSUE TITLE
The new Linear (dB) would be a better default view - and be consistent with the meters

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4406]
### Your idea
I have been working on updating the Manual for the new **Linear (db)** view , the linear waveform with decibel calibration (this provided by GSoC22 participant @micpap25 ).

In doing the testing and image capture for this I have come to _**strongly**_ think that this newly availble view for 3.3.0 would make a **_much_** better default view than the old long-standing **Linear** view (now **Linear (amp)**).

a) this would make the default calibration of the **Vertical Scale** and the **Meters** consistent by default - _and "consistency" has long been an Audacity design goal_.

b) to me the new view just looks better somehow.

c) it may make users less inclined to max out their recordings and edits _(which happens far too often, as can be observed in postings on the Forum)_

d) and perhaps (most importantly) it would make this nice new fearure "discoverable" rather than hiding it away in a hard to find mechanisms _(right-click in VS and obscure prefs)_.

![image](https://user-images.githubusercontent.com/50205984/224548652-3e2a0fbc-9e65-44e0-a720-a444763cd74f.png)

### Problem to be solved
Meters and Vertical Scale calibrations are inconsistent

### Prior art
Virtually all  audio editors use dB labelling - it's "industry standard".

### Additional context
I would also suggest that the listing in the Tracks preferences for Default Waveform Sacle be re-ordered with this new proposed default at the top of the list, giving:

- **Linear (dB)**
- **Linear (amp)**
- **Logarithmic (dB)**

**Existing layout:**
![image](https://user-images.githubusercontent.com/50205984/224548924-a88f41cd-1430-4c2d-abb8-d3de2e2566a4.png)

**Comment by petersampsonaudacity** [comment]
And many thanks to Michael @micpap25  for his work on this/

**Comment by LWinterberg** [comment]
We should really fix this for audacity 4
