### ISSUE TITLE
Default time format in Selection toolbar (and Generators) changed to hh:mm:ss + hundredths

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4408]
### Bug description
In 3.2.5 the default time format for the selection toolbar was changed to **hh:mm:ss + hundredths** from **hh:mm:ss + milliseconds**.

This also affects the default time format for Generators.

**hh:mm:ss + milliseconds** has been the default since Audacity 1.3.0 through 3.2.4 - and is what is documented throughout in the manual as the default.

### Steps to reproduce
1. clear auddacity settings folder
2. run 3.2.4 or any earlier
3. Observe time format in the selection toolbar is **hh:mm:ss + milliseconds**
4. Generate > Chirp
5. Observe defaulttime format is **hh:mm:ss + milliseconds**
6. close Audacity
7. Clear the audacity settings folder
8. run 3.2.5 (or 3.3.0 alpha)
9. Observe time format in the selection toolbar is **hh:mm:ss + hundredths**
10. Generate > Chirp
11. Observe defaukt time format is **hh:mm:ss + hundredths**

### Expected behavior
I see no reason for the default format to have chanfed - and I see no indication of this in the Release Notes

### Actual behavior
Default Time format in the Selection Toolbar and Generators has changed in 3.2.5

### Audacity Version
3.2.5 and latest 3.3.0 alpha

### Operating system
Windows, macOS

### Additional context
Initially surfaced in testing against this Forum post:

https://forum.audacityteam.org/t/audacity-3-2-5-generate-behaviour-has-changed/71034

**Comment by petersampsonaudacity** [comment]
Testing on W11 with @Kirktopode 's branch build:  audacity-win-3.3.0-alpha-20230315+3deb3e7-x64

This branch build fixes the issue with the default time formats for the Selection and the Generators restored to **hh:mm:ss + milliseconds**

**Comment by petersampsonaudacity** [comment]
This persists on the latest branch alpha by @crsib audacity-win-3.3.0-alpha-20230317+745c285-x64

![image](https://user-images.githubusercontent.com/50205984/226166306-df6aea46-a562-4031-8808-a4b5abb48906.png)

**Comment by dozzzzer** [comment]
Tested
