### ISSUE TITLE
Beats & bars ruler: zoom level inaccuracies

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4412]
### Bug description

There're some inaccuracies related to the display of the beats & bars ruler.

### Steps to reproduce

1. Enable Beats & Measures ruler by right-clicking the Timeline
2. Compare different zoom levels with the specification

### Expected behavior

 The actual implementation matching the specsmatches

### Actual behavior

Compare the actual implementation (above) to the specs (below):

**Zoom Normal (0)** view - 4.2.2 rendered vs 4.2.1 expected
<img width="500" alt="image" src="https://user-images.githubusercontent.com/70063970/225036651-5f74fe18-b69f-4ea2-9b08-8be474c23e5b.png">

**Zoom Normal + 1** view - 2.3.3 rendered vs 2.4.1 expected
<img width="500" alt="image" src="https://user-images.githubusercontent.com/70063970/225051174-e9347e0d-bab4-4c86-b843-0a307381d57a.png">

**Zoom Normal + 2** view looks OK

**Zoom Normal + 3** view is off by one notch:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/70063970/225059154-7c3e4ed8-6218-4c98-9186-3145f20a6212.png">

**Zoom Normal + 4** view lacks secondary notches, i.e. there should be twice as many:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/70063970/225060779-3997ea27-8b08-4c66-a9b5-f8a63ec2e28b.png">

**Zoom Normal - 1** view - 7.3.1 rendered vs 7.1.3 expected:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/70063970/225065010-7e5d834a-f9b1-463e-9f10-9455b694a170.png">

**Zoom Normal - 2** view: 14.2 vs 13.4 expected

**Zoom Normal - 3** view: 27.3 vs 26.4 expected

**Zoom Normal - 4** view: 54.1 vs 52.3 expected

**Zoom Normal - 5** view - the increment equals 6 while it's supposed to be 8:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/70063970/225080415-6cb23794-3011-4d17-a67b-dab052c24ec9.png">

**Zoom Normal - 6** view - the increment equals 10 while it's supposed to be 16; also, at this zoom level it fits more than 213 bars while the expected number is around 207:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/70063970/225082172-c724e66e-362c-419a-baac-2bf08bd080be.png">

### Audacity Version

other: https://github.com/audacity/audacity/actions/runs/4408319383

### Operating system

macOS

Update
Michael interprets this as three problems:
- [x] Lack of 128th notes fixed in #4437
- [ ] To do -- numbering interval of bars should be power of 2 (commit 96ea01b2e9b336aa1fb937b7b463e43f027831f3)
- [ ] Discrepancy in design mockup drawings (non-issue to fix it)

**Comment by petersampsonaudacity** [comment]
There is also an issue wit a stray "**1**" marker in negative time when using **Beats and Bars** view in the Timeline.

This always appears to be consistently 2.5 cm  _(on my machine)_  to the left of zero, independent of the zoom level.

![image](https://user-images.githubusercontent.com/50205984/225243073-2bd1bd2c-f720-48ab-b258-efa1714e8735.png)

**Comment by micpap25** [comment]
Hi @petersampsonaudacity I am not sure how to display negative time, how did you do that?

**Comment by petersampsonaudacity** [comment]
> Hi @petersampsonaudacity I am not sure how to display negative time, how did you do that?

@micpap25  Michael,  you need to go to **Tracks Behaviors** preferences and tun on **Enable scrolling left of zero** _(and this is off by default)_

Then you can use the horizontal scrollbar yo scroll left of zero and into negative time.

I doe sbeg tha big question of just why we have negative time in Audacity - _but that's another can o' worms entirely_:
**Why do we have negative time in Audacity - do we need it?** #4188
