### ISSUE TITLE
Validation for BPM and upper time signature values

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4418]
### Your idea

Add validation for values entered in the BPM and upper time signature text boxes:

- allow only 2 decimal places for BPM value
- allow natural numbers only for upper time signature values

<img width="246" alt="image" src="https://user-images.githubusercontent.com/70063970/225603643-7d91e10e-a15d-4092-a83e-df1becfafd7a.png">

### Problem to be solved

Lack of validation

**Comment by crsib** [comment]
Hmm, where is this UI is located?

**Comment by dozzzzer** [comment]
@crsib in Preferences > Interface

**Comment by crsib** [comment]
I think it should be removed from there, ain't it @LWinterberg?

**Comment by LWinterberg** [comment]
yes, the stuff in Preferences should go away

**Comment by LWinterberg** [comment]
this is implemented
