### ISSUE TITLE
Upon restart, previously selected "beats and bars" ruler mode gets reset

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4423]
### Steps to reproduce

1. Launch Audacity
2. Right-click the timeline
3. Select "Beats and Bars" mode
4. Restart Audacity
5. Check the current ruler mode

### Expected behavior

Beats and Bars

### Actual behavior

Ruler mode got changed to "Minutes and Seconds"

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS

**Comment by Paul-Licameli** [comment]
Commit a905581669df490bb308bdc799373158d7f85775
