### ISSUE TITLE
Reset Configuration does not use the proper time format for the Time toolbar

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4426]
### Bug description
Using **Tools > Reset Configuration** does not use the proper time **hh:mm:ss** format for the Time toolbar - instead it changes it to **xxx,xxx.xxx seconds**

This is s regression on 3.2.4

### Steps to reproduce

1. clear audacity settings folder
2. launch @crsib  latest branch build:  audacity-win-3.3.0-alpha-20230317+745c285-x64
3. Observe: time format of **Time** toolbar is **hh:mm:ss**  -   _(the expected long-standing default format)_
4. Tools > Reset Configuration
5. Observe: time format of **Time** toolbar has changed to **xxx,xxx.xxx seconds**

**At Step 3**
![image](https://user-images.githubusercontent.com/50205984/226166606-9ece4e19-c0e2-4349-9ebf-42f7d329a8b0.png)

**At Step 5**
![image](https://user-images.githubusercontent.com/50205984/226166643-f22f7a76-499d-4436-bf43-1be7a67ca8b2.png)

### Expected behavior
Reset Configuration should reset the Time toolbar to **hh:mm:ss**

### Actual behavior
Reset Configuration resets the Time toolbar format to **xxx,xxx.xxx seconds**

### Audacity Version
3.2.5  and

Latest branch build @crsib audacity-win-3.3.0-alpha-20230317+745c285-x64
The build for the new updated lower tooldock, updated for bars and beats

### Operating system
Windows 10

### Additional context
Might this be related to the issue 
 **Default time format in Selection toolbar (and Generators) changed to hh:mm:ss + hundredths** #4408   
I.e. introduced as a result of the new **seconds + milliseconds** time format (that was supposed to be in 3.3.0, but inadvertently crept into 3.2.5)

See also:   Upon restart, previously selected "beats and bars" ruler mode gets reset #4423

**Comment by Ryan-Miller-Audacity** [comment]
Confirmed I can reproduce this as described. Tested this against the fix for #4408 (PR #4413) and that PR did not fix this issue as well, so this will have to be fixed separately.

**Comment by petersampsonaudacity** [comment]
This now looks to be fixed on W10 with the latest alpha:  audacity-win-3.3.0-alpha-20230322+10a5735-x64-msvc2022

Possibly fixed by the fix for:
 **Default time format in Selection toolbar (and Generators) changed to hh:mm:ss + hundredths** #4408

**Comment by petersampsonaudacity** [comment]
Testing on W10 with audacity-win-3.3.0-alpha-20230404+d0f0852-x64-msvc2022

@LWinterberg This now appears to be fixed

_I believe it got fixed as part of the work that @crsib did on the new updated bottom tooldock._

**Comment by petersampsonaudacity** [comment]
And testing on W10 with 3.3.0 Beta:  audacity-win-3.3.0-beta-20230405+caeb58e-x64-msvc2022

This appears to be properly fixed in the lates Beta for 3.3.0

@LWinterberg  I think this can be closed

**Comment by Ryan-Miller-Audacity** [comment]
I can no longer reproduce this in the Beta for 3.3 as well. Closing down. I believe this was fixed in the Bottom UI Improvements in PR #4491.
