### ISSUE TITLE
Audacity marks IEM Plugins (LV2) as incompatible

### ISSUE THREAD

**Issue by candideu** [audacity/audacity#4428]
Hello! I'm using Audacity 3.2.5 on Windows 10.

I wanted to try the IEM Plugin Suite, which is [featured in the docs](https://plugins.audacityteam.org/realtime-effects/plugin-suites#muse-fx), but ran into some issues. After I downloaded v1.14.1 (14th February 2023), I was unable to get either the LV2s or VSTs working after moving the folders to `C:\Program Files\Common Files`

I got an alert saying that the plugins were incompatible:
![image](https://user-images.githubusercontent.com/55474996/226081546-daf39074-7cd9-4e4a-ab5c-b304d3b2488c.png)

Enabling the Plugins in the Plugin Manager didn't help, because they were automatically disabled once I rescanned them.

**Comment by candideu** [comment]
> So you'd probably want to move those to the path specified by the developer instead. Hope that helps @candideu

This solved the issue! Thanks @dozzzzer. The plugins were enabled instantly when rescanned from the new location.

**Comment by RaphaelBeguin** [comment]
hello i had the same issue, and you review helped me, but i 'm a bit lost i downloaded this [version](https://git.iem.at/audioplugins/IEMPluginSuite/-/releases/v1.13.0) of plugin and extracted them into C:\Program Files (x86)\Common Files\Steinberg\VstPlugins 
![2023-10-02 17 16 12](https://github.com/audacity/audacity/assets/36958850/0f7dc649-223d-44e3-974e-c6fc4daa1104)
and when i expected seeing IEM plugins trought RE effects list
![2023-10-02 17 03 21](https://github.com/audacity/audacity/assets/36958850/4db7ce96-b29f-4cf1-b179-2f0c7dabc295)
what i did wrong?

**Comment by LWinterberg** [comment]
Two things: 

* If Audacity was running during the installation of the plugins, try rescanning plugins in Effects > Plugin Manager,
* If you install to  Program Files (x86), you're indicating 32-bit plugins. Audacity comes in both 32 and 64 bit versions and only sees plugins which are of the same kind as itself. AFAICT, the IEM plugin suite is always 64-bit and should not be put in that folder.

**Comment by RaphaelBeguin** [comment]
HI, it was close
ok i got it i downloaded the wrong version, i've downloaded this one https://users.iem.at/holzmueller/IEM-Audioplugins/IEMPluginSuite/v1.13.0/IEMPluginSuite_v1.13.0_x64.zip  abd put into C:\Program Files\Common Files\VST3 foldder and it works !
![2023-10-03 19 43 35](https://github.com/audacity/audacity/assets/36958850/c00749fa-babc-4be2-95b8-9aeb0370fa9a)
