### ISSUE TITLE
[Accessibility]  If Mouse Cursor size is boosted in Windows 11, Sliders become hard to read

### ISSUE THREAD

**Issue by thygrrr** [audacity/audacity#4429]
### Your idea

Move the origin of the "while pressed" tool tips to be above or entirely below the mouse cursor, or anchored right-justified.

### Problem to be solved

When pressing on some controls, for example the gain slider on a channel, a new tooltip shows up. This is difficult to read because the mouse cursor can overlap it, especially if the mouse cursor size is boosted by the OS.

Slider pressed tooltip:
![image](https://user-images.githubusercontent.com/8904620/226281500-bee78f2b-f708-4182-9b25-278f0dd60df7.png)

Normal Tooltip:
![image](https://user-images.githubusercontent.com/8904620/226283753-b5c6b2de-d128-47ea-8944-fea399762841.png)

### Prior art

![image](https://user-images.githubusercontent.com/8904620/226282741-072597d2-3cc8-4e07-bcc6-52093b3f8bad.png)
Chrome shows it left justified at the bottom right of the cursor like this: (it's difficult to screencap these, screen capture software reduces cursor size, but the positioning is accurate)

They also keep the tooltip sticky instead of moving it with the cursor, meaning you can slide the cursor out of the way.

![image](https://user-images.githubusercontent.com/8904620/226284533-778e0de6-4edf-4f98-b5db-18d82b764774.png)
Microsoft Windows usually shows it above the cursor. The tooltip also stays pinned to the place where it showed up, so it doesn't move when the mouse moves.

### Additional context

![image](https://user-images.githubusercontent.com/8904620/226281772-8eab50ab-2ab7-4a5f-a092-8824a1122232.png)
In Windows 11, this slider (search for "Mouse Pointer Size" in start menu) is what will trigger the overlap issue.

**Comment by bkunde** [comment]
Hi I'm working on a project for one of my university classes and would like to try and implement this feature. Where could I find the file that stores the tooltip information?

**Comment by LWinterberg** [comment]
The tooltip can be covered even by normal cursor sizes depending on the y-position of the cursor. However, the slider still works regarding how far up or down you have it, so you can just move your cursor out of the way to reveal it.

https://github.com/audacity/audacity/assets/87814144/bec21467-a5f3-4a06-9ebc-07fe5dd878ce
