### ISSUE TITLE
Audacity fails to enable some plugin bundles

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4430]
### Bug description

Upon startup, Audacity fails to enable some plugins shipped in bundles by Melda, NI and Waves. Enabling them manually from the Plugin Manager also gives no result, although they get marked as "Enabled" and no error is shown.

### Steps to reproduce

1. Download & install Melda free FX Bundle or some Waves plugins or NI plugins (such as Kontakt)
2. Run Audacity
3. Let the plugin scan finish
4. Observe: some plugins **were recognized as incompatible**
5. In the Plugin Manager, enable all these plugins and click OK
6. Observe: no errors are shown
7. Check if the plugins become available in either the Effect menu or in the sidebar

### Expected behavior

The plugins were recognized as valid and got enabled by default

### Actual behavior

The plugins were recognized as incompatible and weren't enabled manually

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

### Architecture

64 bit Intel/AMD processors

### Additional context

Seems to be a regression from 3.2.5

**Comment by Ryan-Miller-Audacity** [comment]
Testing this with Waves, Melda, Native Insturments etc and this seems to be working appropriately now and plugins are registered as expected. The waves plugins that I observed not registering properly were a mix of VSTi and surround sound pllugins.
