### ISSUE TITLE
Constantly-increasing audio delay introduced by Audacity 3.2.5 on Linux Mint 21

### ISSUE THREAD

**Issue by alexmcwi** [audacity/audacity#4433]
### Bug description

Linux Mint 21. AMD Ryzen 5 5500. 32GB RAM. AMD Radeon 5700 XT. Soundblaster Audigy RX PCIe.

After running Audacity audio starts lagging and the lag keeps increasing, even after closing audacity, until the computer is rebooted.

I never had this issue with my old computer (Mint 19, built-in audio).

I tested this with the version from the repositories (2.4.something), as well as with the most recent appimage and both require a reboot in order to get rid of this issue.

I’m using this video to test: https://www.youtube.com/watch?v=TjAa0wOe5k4 (an mp4 version of this file can be downloaded from http://twitch-event-engineering-public.s3.amazonaws.com/sync-footage/Sync-Footage-V1-H264.mp4 ).

When I open a recording in audacity (audio only), and the lag is present, sound occurs AFTER the cursor shows it playing. For example, if I have an audio file with beeps (like the video above) and I play it with audacity, the beeps are heard AFTER the cursor shows that they should be heard, and the delay keeps growing.

If I kill pulseaudio, the lag seems to reset to zero, but that doesn't keep it from growing, and after about 10 minutes, the audio is AGAIN about .5 seconds behind the video (and growing).

Pulseaudio Volume Control (pavucontrol) lets me switch output from Soundblaster to HDMI (via video card). HDMI audio does NOT lag, so it's something that's going on between audacity, pulseaudio, and the sound card.

Needless to say, this is incredibly aggravating.

I imagine that maybe 1% (or less) of all users rely on external sound card, let alone the same as mine and I don't expect a lot of people to be able to reproduce this issue, so if anyone could provide some guidance regarding what I should be checking, I'll be happy to provide whatever additional information might be needed to fix this bug.

Thanks!!!!

### Steps to reproduce

1. Start audacity and open an audio file.
2. Close audacity.
3. Wait about 10 minutes.
4. Open any youtube video such as https://www.youtube.com/watch?v=TjAa0wOe5k4 which will make it easy to tell there's a lag between video and audio (audio is delayed relative to video).

### Expected behavior

NO LAG between video and audio.

### Actual behavior

Audio lags behind video and lag keeps increasing.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Linux

### Additional context

- OS: Linux Mint 21.
- CPU: AMD Ryzen 5 5500. 
- RAM: 32GB RAM. 
- Video Card: AMD Radeon 5700 XT. 
- Sound Card: Soundblaster Audigy RX PCIe.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
