### ISSUE TITLE
Add wavelet waveform analysis view.

### ISSUE THREAD

**Issue by Ygarr** [audacity/audacity#444]
**Is your feature request related to a problem? Please describe.**
Choosing "Open menu" for audio file. There are "Waveform","Waveform(db)","Spectrogram". But no Wavelet view for better details.

**Describe the solution you'd like**
Just option in menu

**Describe alternatives you've considered**
Such feature in "Nero" audio editor in attach
![feature_wavelet_Screenshot_2020-01-23_11-19-53](https://user-images.githubusercontent.com/14309871/75926997-2d73c300-5e74-11ea-996a-73d01e08a922.png)

**Comment by Ygarr** [comment]
May be this old link for windows version plugin for short audios make some help http://stevehanov.ca/wavelet/

**Comment by LWinterberg** [comment]
I see that wavelets may be very useful for compression and stuff, but it's unclear to me how they would improve Audacity's spectrogram display. Nero is (probably?) showing the wavelet of the raw MP3, but Audacity always works with uncompressed data. 

If you just want to see more detail in the spectrogram, you can change the scale of it instead; with 3.1 we switched the default from Linear to Mel. 
![image](https://user-images.githubusercontent.com/87814144/156561621-203dd136-2827-46b5-94a6-bdae524c6f81.png)
