### ISSUE TITLE
An issue with a stray "1" marker in negative time when using Beats and Bars view in the Timeline and "0.0" when using Minutes and Seconds view

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#4440]
There is also an issue with a stray "**1**" marker in negative time when using **Beats and Bars** view in the Timeline.

This always appears to be consistently 2.5 cm  _(on my machine)_  to the left of zero, independent of the zoom level.

![image](https://user-images.githubusercontent.com/50205984/225243073-2bd1bd2c-f720-48ab-b258-efa1714e8735.png)

_Originally posted by @petersampsonaudacity in https://github.com/audacity/audacity/issues/4412#issuecomment-1469518574_

### UPDATE
You can also observe this when using Play with Pinned playhead.

**Comment by petersampsonaudacity** [comment]
You get a similar stray marker when you use the default Minutes and Seconds format for the Timeline - but with this you get a stray "0.0" marker c. 2.5 cm to the left of T=0  (and that distance seems to be independent of the zoom level.

![image](https://user-images.githubusercontent.com/50205984/227228228-a5f5c453-7515-4bb5-8aef-08d648778e46.png)

**Comment by petersampsonaudacity** [comment]
This is still the case in the latest alpha:  audacity-win-3.3.0-alpha-20230329+8715a71-x64-msvc2022

**Comment by petersampsonaudacity** [comment]
This remains the case in the latest 3.3.0 Beta and 3.4.0 alpha

**Comment by petersampsonaudacity** [comment]
And remains the case on W10 today with the latest Beta, the one which inhibits the numbers display in negative time.
