### ISSUE TITLE
Audacity silently changes the project rate on importing the first audio file to match its rate.

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4448]
### Bug description
Audacity silently changes the project rate on importing the first audio file to match its rate.

With 3.3.0 Lower Tooldock changes with the **Project Rate** removed (it used to be in the old **Selection Toolbar**) there is _**NO**_ visual indication, no visual cue, to alert the user that the project rate has changed.

Fundamentally I believe anyway that Audacity should not be changing the project user that the user already has  _**without**_ asking the user.

I am marking this as a regression as with all previous Audacity versions 3.2.5 and earlier we had a visible Project Rate at the bottom left of the Audacity window,

### Steps to reproduce
1. Clear the audacity settings folder - _for default settings_
2. Launch 3.3.0
3. Preferences>Audio Settings  0r  Audio Setup>Audio Settings
4. Observe: Project rate is 44100 Hz
5. Import a 11025 Hz audio file
6. Preferences>Audio Settings  0r  Audio Setup>Audio Settings
8. Observe: Project rate is now changed to 11025 Hz
9. Import a regular 44100 Hz audio file (a CD track say - or a recording made with default Audacity)
10. Export the project as WAV
11. Observe:  The exported WAV file has only 25% of the samples that the file at step 8 had

Now consider that most users will **_not_** bother to do steps 5 and 6 to observe the project rates, so when they make the export they may well not (almost certainly will not) realize that the file is of lower quality than the expected 44100/

Consider too that this problem is compounded if the user:
a) throws way the original file in favor of the newly exported one
b) overwrites the existing step 9 file at step 10
There is no way back from either of these scenarios.

### Expected behavior
1.  At the very least Audacity should advise the user with a dialog that it wants to change the project rate based on the imported file - and in tat dialog the user should have the option to reject that.

2. Perhaps Audacity should never change the project rate based on an imported file.

3. If Audacity is to offer to change the rate then it should do so with every subsequently imported file and _**not**_ just use the first import

### Actual behavior
Audacity silently changes the project rate on importing the first audio file to match its rate, with no immediate visual cue (or confirmatory dialog)

### Audacity Version
3.3.0 Beta

### Operating system
Windows 10 - but assume all OS

### Additional context
Flagging @Tantacrul @DilsonsPickles and @LWinterberg   as a design/UX issue.

-----------------------------------------------------------------

I can see a use case for Audacity changing the rate based on imported file:

1. Import a  11025 Hz file 
2. Edit it
3. Export it

In this case the user probably rightly expects to end up with a 11025 Hz file - there is no point in up-sampling (the file just takes up more space).  But I still think they should be warned on importing.

**Comment by petersampsonaudacity** [comment]
> Keeping the sample rate default is the safer option, so I'd opt to no longer automatically setting the project rate to other rates when importing anything.

@LWinterberg  @crsib 
This has not been addressed for 3.3.0 (and no chance of that now) - any chance this can be fixed for the next release please?

**Comment by petersampsonaudacity** [comment]
The Use Case that I listed in the initial post is likely to be negated by the new Export dialog(s) which gives the the user full control of the sample rate of the exported audio file

**Comment by petersampsonaudacity** [comment]
@LWinterberg   @crsib 

Testing on W10 with @vsverchinsky 's latest branch build for new Export: audacity-win-3.4.0-alpha-20230707+796e0db-x64
(and latest 3.4..0 alpha).

This issue is still the case.

It is particularly egregious as the change of project sample rate is now done silently and opaquely to the user as we no longer show the project rate on the main Audacity window - and there is no warning message regarding the rate change.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @vsverchinsky 's branch build for this fix:  audacity-win-3.4.0-alpha-20230823+888f9ac-x64

This appears to properly fix this issue.

**Comment by dozzzzer** [comment]
Tested

**Comment by Obscure2020** [comment]
We have a new problem now. My Audacity default project settings are set to 48000 Hz. However, I also do a lot of work with 44100 Hz files. If I tell Windows to open 44100 Hz file using Audacity, the file opens as a new project at 48000 Hz instead of the sample rate of the file.

**Comment by petersampsonaudacity** [comment]
> We have a new problem now. My Audacity default project settings are set to 48000 Hz. However, I also do a lot of work with 44100 Hz files. If I tell Windows to open 44100 Hz file using Audacity, the file opens as a new project at 48000 Hz instead of the sample rate of the file.

I cannot reproduce this on W10 with 3.4.0/

If I set my project rate to 48000 and then import a know 44100 16-bit PCM stereo WAV file - in it's Track Control Panel the imported track shows properly as 44100 Hz.

![image](https://github.com/audacity/audacity/assets/50205984/b750b8ab-3550-4845-aff7-40f3bfc83017)

**Comment by Obscure2020** [comment]
No, you literally _**did**_ reproduce the issue in your screenshot. When you imported your 44100 Hz clip, Audacity should have brought up a popup to ask if you'd like to change the project sample rate to 44100 Hz or leave it at the default of 48000 Hz. No such popup occurred, did it? Your screenshot proves that the Project Sample Rate did not change to 44100 Hz, even though it _should_ have, or at least it should have _asked_ you.

**Comment by LWinterberg** [comment]
No, it should not have asked you to set the project sample rate. Rather, when exporting, it should have set the default in the export window to the highest sample rate found in the tracks, and not use the project sample rate.

**Comment by petersampsonaudacity** [comment]
Sorry @Obscure2020  - but I'm pretty sure that what I am seeing is the correct Audacity behavior and one that has been so for time immemorial in the app.

**When you import an audio file it imports at the rate the file is at - the is **_NO_** up-sampling or down-sampling to match the project rate.**

Project rate is used for recording and rendering (and used to be used for the export rate, but since 3.4.0 that is now done explicitly, and thus with more clarity, in the new Export dialog)

This logged (and fixed issue) addresses the fact that Audacity used to silently change the project rate to match the rate of any first incoming file that you import - thereby catching many users out - mot realizing that their project rate had _"helpfully"_ been changed for them and silently so.

Peter

**Comment by Obscure2020** [comment]
When you import an audio file, it imports it at the rate the file is at. This is correct behavior, and it what is displayed.

HOWEVER. Project rate is used for rendering. Under the current system (now that #5075 has been merged), if you do not _**manually change**_ the Project Sample Rate (either in the Audio Settings or in the Export dialog), blindly hitting the Export button would upsample the 44100 Hz clip to 48000 Hz _**at the time of export.**_

> At the very least Audacity should advise the user with a dialog that it wants to change the project rate based on the imported file

This expectation remains unfulfilled.

What I used to be able to do is open a 44100 Hz file, Audacity would automatically open it as a 44100 Hz project, I'd perform some small trimming and filtering, and then I'd export, and the export would stay at 44100 Hz.

What happens _now_ is if I open a 44100 Hz file, Audacity will open it as a 48000 Hz project, and it would _export_ at 48000 Hz _too_ unless I _**manually**_ change it to 44100 Hz, either in the Audio Settings or the Export menu.

What _**should**_ happen, as suggested by @petersampsonaudacity, is that _**a popup should appear at the time of first file import**_ to ask if the user would like to change the Project Sample Rate to match the rate of the imported clip, or if the user would instead like to keep the Project Sample Rate at the default.

**Comment by Njsmooth** [comment]
I mess around with files that have vastly different sample rates, but usually only do basic edits, and then resave with the same sample rate. This was easy previously, because I would import my file and the project rate would be matched with that file. But now, I have to individually save each file with the correct sample rate in the export dialog, which gets pretty tedious (and I forget most of the time). Can't we just have settings for track import or for project rate, that allow us to choose what works best for our workflow?

**Comment by Njsmooth** [comment]
If you don't want to add more options, then a popup upon importing a track asking whether to use the track or default sample rate as the project rate would be much appreciated

**Comment by Njsmooth** [comment]
> when exporting, it should have set the default in the export window to the highest sample rate found in the tracks, and not use the project sample rate.

completely overlooked this idea, which I would totally be down with

**Comment by Obscure2020** [comment]
>> it should have set the default in the export window to the highest sample rate found in the tracks, and not use the project sample rate.

> this idea... I would totally be down with

Agreed!

**Comment by Obscure2020** [comment]
Issue #5032 seems to have brought up the same issue and proposed the same solution. Now that it's closed and the fix has been released, Audacity appears to be behaving in a more sensible manner now.
