### ISSUE TITLE
Extra>Selection menu has incorrect entries for the new 3.3.0 snapping

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4450]
### Bug description
**Extra>Selection** menu has incorrect entries for the new 3.3.0 snapping

For 3.3.0 a new Snapping toolbar has been spun-off from the old selection.  As part of that:
a) **Snap-To** now simply becomes **Snap**
b) the option of snapping to "prior" has gone, Snap bow always snaps to nearest.

While this has been changed in the Snapping Toolbar in the lower tooldock the Extra>Selection menu still has the old behavior.

_I'm guessing that this just got overlooked when the design for the new lower tooldock was being worked on. Easily done (I only stumbled on this not through testing but from editing the Manual looking for instances of **Snap-To**)._

### Steps to reproduce
1. Run @crsib Dmitry's latest branch build:  audacity-win-3.3.0-alpha-20230327+8484c1a-x64
2. turn on the Extra menus
3. Extra > Selection
4.  Observe: entries for  **Snap-To Off**, **Snap-To Nearest**, **Snap-To Prior**   _(see image below)_

### Expected behavior
**Extra>Selection** menu should correspond to snapping behaviors in the new Snapping toolbar:

a) **Snap-To On** to become **Snap On**
b) no entries for **Snap-To Nearest** or **Snap-To Prior** 
c) and additional entry for **Snap Off**

### Actual behavior
![image](https://user-images.githubusercontent.com/50205984/227987856-099f9a83-7809-4770-9f7d-8bded45be721.png)

### Audacity Version
@crsib Dmitry's latest branch build:  audacity-win-3.3.0-alpha-20230327+8484c1a-x64

### Operating system
Windows 10 - but assume all OS

### Additional context
I have set P1s in the manual for if/when this gets fixed

**Comment by petersampsonaudacity** [comment]
@LWinterberg @Tantacrul @DilsonsPickles 

This really is a design issue.

Surely the snapping commands in the **Extra>Selection** menu should correspond to the new 3.3.0 functionality in the **Snapping** toolbar?

**Comment by LWinterberg** [comment]
The extra menu featuring extra options (ie more options than can be found in the rest of the UI) kinda is what the extra menu *is*. So I don't really mind things staying this way.

**Comment by petersampsonaudacity** [comment]
OK - I can buy the argument Leo.  ;-)

I'll remove the P1s in the Manual for this - and this I think this issue can be CLOSED
