### ISSUE TITLE
New Tempo and Upper Time Signature values can only be set by moving focus out of the text box

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4456]
### Bug description

When typing a new Tempo or Upper Time Signature value into the text box and pressing the Enter key, the value isn't set. It only gets entered when moving focus out of the field by either clicking somewhere outside of it (macOS) or by clicking within an audio track (Windows).

### Steps to reproduce

1. in the [latest bottom bar UI build](https://github.com/audacity/audacity/actions/runs/4532690177), enable the Beats and Measures mode in the context menu of the timeline
2. type a new value into either **Tempo** or **Upper Time Signature** text box in the Time Signature toolbar and hit **Enter**

### Expected behavior

The ruler denotations are changed correspondingly.

### Actual behavior

No changes to the ruler;
The entered values of the tempo and the upper time signature will only change when clicking anywhere outside the time signature toolbar (macOS) and precisely on an audio track (Windows).

### Audacity Version

other

### Operating system

Windows, macOS

**Comment by crsib** [comment]
Should be fixed by #4414

**Comment by DavidBailes** [comment]
> Should be fixed by #4414

When you press Enter, the next control becomes the focus. This is non-standard behaviour (at least on Windows), which is probably not helpful for users.

**Comment by crsib** [comment]
I'm not sure what is the standard Windows behavior and where can I experience it.  This is something I expect when filling out multiple text edits (that's it - forms). In any case, this behavior can be easily changed.

**Comment by DavidBailes** [comment]
> I'm not sure what is the standard Windows behavior and where can I experience it. This is something I expect when filling out multiple text edits (that's it - forms). In any case, this behavior can be easily changed.

On place is the app winui 3 gallery: https://apps.microsoft.com/store/detail/winui-3-gallery/9P3JFPWWDZRC
- search for NumberBox.
I'm not sure it's a form. I guess it depends on how often the user is going to want to change the time signature after changing the tempo.

**Comment by crsib** [comment]
Great app, but I sincerely hope that I wont see this anywhere else

![image](https://user-images.githubusercontent.com/2660628/229116245-730aa020-52a8-4451-9983-c1844156de2e.png)

> I guess it depends on how often the user is going to want to change the time signature after changing the tempo.

Hmm, that a really good point

**Comment by crsib** [comment]
(I mean I understand that it is probably for the Touch Screens, but come on...)

I've changed the Enter key behavior.

**Comment by Ryan-Miller-Audacity** [comment]
Confirmed fixed via PR #4414 on both Windows and MacOS.

**Comment by Ryan-Miller-Audacity** [comment]
PR #4414 was merged previously. This ticket wasn't officially attached to it and was not auto closed.
