### ISSUE TITLE
Time signature toolbar can be unreadable (Windows)

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#4461]
### Steps to reproduce

On Windows:
1. Set the Windows display scaling set to 125%
2. So that the text in Audacity is clear, set Audacity to override hi DPI scaling on the compatibility tab of the executable's property dialog.
3. Open Audacity, leave the tempo at 120.

### Expected behavior

All the text in the time signature toolbar is visible and so readable.

### Actual behavior

![image](https://user-images.githubusercontent.com/11887021/228487174-ffb74ece-5c55-4521-97e1-5808058ed89c.png)

### Audacity Version

other

### Operating system

Windows

**Comment by LWinterberg** [comment]
HiDPI is not supported at the moment, and won't be during 3.x
