### ISSUE TITLE
Inconsistency: Time Toolbar's time format setting is reset by Reset Toolbars

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4462]
### Bug description
Unlike all other toolbars the Time Toolbar's time format setting is reset by Reset Toolbars to its default (**hh:mm:ss**).

This is an inconsistency and the Manual clearly states:

>**Reset Toolbars**
>Using View > Reset Toolbars positions all toolbars in default location and size as they were when Audacity was first installed.

It does _**NOT**_ state that any toolbar has its settings reset. 
https://alphamanual.audacityteam.org/man/View_Menu:_Toolbars#reset

This does _**not**_ appear to be a regression - testing shows that this is the case all the way back to 2.4.2 _(I did not test further back - I can't remember the version where James sprung off the Time toolbar from the Selection toolbar.)_

Note that a full reset of toolbars (position and settings) is readily achieved with **Tools > Reset Configuration**

### Steps to reproduce
1. launch audacity
2. change the settings in various toolbars, particularly Time Toolbar
3. View > Toolbars > Reset Toolbars
4. Observe: only the Time toolbar is reset to default

### Expected behavior
Time format in Time toolbar should _**NOT**_ be changed by **View > Toolbars > Reset Toolbars**

It should _**only**_ be reset by **Tools > Reset Configuration**

### Actual behavior
Time format in Time toolbar is inconsistently changed by **View > Toolbars > Reset Toolbars**

### Audacity Version
3.2.5 and latest alpha master and at least all the way back to 2.4.2

### Operating system
Windows 10 - but assume all OS

### Additional context
I will update the Manual to clarify the Reset Toolbars does _**NOT**_ reset the settings but only the positions and size.

I will also add a temporary advice div to point out the Time toolbar anomaly (with an ednote to remove that if/when thsi bug gets fixed)

**Comment by petersampsonaudacity** [comment]
I have updated the manual:

![image](https://user-images.githubusercontent.com/50205984/228495946-f8ae8b10-1ba3-42f4-abeb-966f5ac44af4.png)

**Comment by petersampsonaudacity** [comment]
Now that with 3.3.0 Beta using Reset Configuration changes the Time format of the Time Ruler to **mm:ss** - in my revised opinion it makes _**eminent sense**_ for the Time Toolbar to be reset to **hh:mm:ss**.

Therefore I would like to withdraw this issue from the log.

@LWinterberg  can we please just close this as "good, required, behaviour" ?

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
