### ISSUE TITLE
"Normalize" effect still clips audio

### ISSUE THREAD

**Issue by ChrisX4Ever** [audacity/audacity#4469]
### Bug description

After normalizing to 0.0 db, some audio sections get clipped.

### Steps to reproduce

1. Check the "Show audio clipping" option
2. Select the audio
3. Go to "effects" and then to "normalize"
4. Make sure it will normalize at 0.0 db
5. Normalize the audio

### Expected behavior

It should have no clipping

### Actual behavior

The audio is clipping

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by LWinterberg** [comment]
![image](https://user-images.githubusercontent.com/87814144/228673602-6b781d52-337c-4e50-9013-b26f01f87a8d.png)
Well, yes. If you normalize to 0dB, you by definition want to place samples right to the extremes. This will get detected as clipping, as any clipped values are - again, by definition - clipped to the extreme values, but no actual clipping (overshooting 0db) has occurred from the normalize effect.
