### ISSUE TITLE
Reset Configuration won't reset the Timeline ruler mode to "Minutes and Seconds"

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4474]
### Bug description

Tools > Reset Configuration doesn't reset the ruler mode to the default state i.e. "Minutes and Seconds"

### Steps to reproduce

1. Launch Audacity
2. Right-click the ruler
3. Select "Beats and Measures" mode
4. Tools > Reset Configuration

### Expected behavior

The ruler mode has been changed to "Minutes and Seconds"

### Actual behavior

The ruler mode is "Beats and Measures"

### Audacity Version

other https://github.com/audacity/audacity/actions/runs/4563459070?pr=4473

### Operating system

Windows, macOS

**Comment by LWinterberg** [comment]
Why? It's got two easy workarounds, one in deleting the cfg, one in just setting it back by right-clicking the ruler

**Comment by petersampsonaudacity** [comment]
> This is a one line fix, so probably we should implement it

Yes please Dmitry.

**Comment by petersampsonaudacity** [comment]
I have added a note to the Manual in case this does not get fixed
![image](https://user-images.githubusercontent.com/50205984/229766087-ea01ede7-e0d6-4711-aa35-a443020235af.png)

**Comment by petersampsonaudacity** [comment]
Testing on W10 with the latest Beta 3.3.0:  audacity-win-3.3.0-beta-20230405+caeb58e-x64-msvc2022

This is still the case in the latest Beta

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @crsib 's branch build:  audacity-win-3.3.0-alpha-20230410+09bdf32-x64

This issue appears to be properly fixed in Dmitry's branch

**Comment by petersampsonaudacity** [comment]
Testing on W10 with the latest 3.3.0 Beta 

This issue looks to be properly fixed
