### ISSUE TITLE
Missing Error Message

### ISSUE THREAD

**Issue by FuzzyDriver** [audacity/audacity#4475]
### Your idea

The colon is an invalid character in Graphic Equalizer user preset names. If you type a colon in the name, no error message is generated. The preset is actually saved (in pluginsettings.cfg), but the name is corrupted and will not show up in the Graphic Equalizer user preset list - so you can not load or delete it. 

Additionally, I found that if you escape the colon by editing pluginsettings.cfg then the preset will appear in the list (with the colon). But if you select it, the settings will not be loaded. Removing the escaped colon enables you to both select it and load it.

Requested Fix:
Generate an error message when user types an invalid preset name and don’t save the preset.

Note: I am a Senior Software Engineer (retired) and would like to help with QA testing.

### Problem to be solved

(1) Users will be assured that the Graphic Equalizer presets they save will be available for future loading.
(2) Audacity will not save Graphic Equalizer presets that can neither be loaded, nor deleted.

**Comment by Ryan-Miller-Audacity** [comment]
I was able to reproduce this in Audacity 3.2.5. The preset naming properly handles several other symbols but when a : is used it breaks the loading/display of the preset in the menu. We should be able to handle this case either by allowing colons to work properly in naming presets or as @FuzzyDriver suggests, giving a warning for invalid characters. I did a quick look through of several special characters and : appears to be the only one that shows this behavior.

**Comment by FuzzyDriver** [comment]
Ryan,
I found another anomaly with Graphics Equalizer preset naming (by accident - honest, I wasn't looking for more!) 
If your preset name includes an ampersand, the ampersand serves to underscore the next character, even if it's a space.
"Booger & Goober" becomes "Booger _Goober" 
IIRC, this is how you set the <Alt> shortcut key in a menu, but we shouldn't be doing that during runtime.  The preset (with the boogered name) is loadable.  Interestingly, if you go to delete the preset the name shows up correctly in the challenge confirmation.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
