### ISSUE TITLE
Selection toolbar: numeric controls are not adjacent in tab order

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#4478]
### Bug description

It's convenient for keyboard users for the two numeric controls to be adjacent.

### Steps to reproduce

Tab through the controls of the selection toolbar

### Expected behavior

The tab order is the setup button, the first numeric control, the second numeric control.

### Actual behavior

The tab order is the first numeric control, the setup button, the second numeric control.

### Audacity Version

other
https://github.com/audacity/audacity/actions/runs/4574907547

### Operating system

Windows

**Comment by DavidBailes** [comment]
@LWinterberg @crsib I've submitted a PR for this, please can this be included in 3.3.0?

**Comment by Ryan-Miller-Audacity** [comment]
Tested and confirmed implementation of updated tab order for the audio selection elements.

**Comment by Ryan-Miller-Audacity** [comment]
This has been merged into Release 3.3.
