### ISSUE TITLE
Time Display Formats of (mm:ss + milliseconds) and/or (mm:ss + samples)

### ISSUE THREAD

**Issue by literaldehyde** [audacity/audacity#4479]
### Your idea

Add (mm:ss + milliseconds) and/or (mm:ss + samples) as time display formats options, or add a customization feature.

### Problem to be solved

I noticed that I never use hours and I love the precision of milliseconds/samples. I could use seconds + milliseconds but vastly prefer minutes as the highest unit over seconds.  

Either of these suggestions would be great universal time display formats that I don't think I'd ever need to to change, plus they'd also help keep the toolbar compact. 

A customization feature would be ideal but sounds much more complex to code. 

Thanks for your guys' hard work!

**Comment by dozzzzer** [comment]
@literaldehyde why wouldn't you want to use **hh:mm:ss + milliseconds** (samples) instead?

**Comment by literaldehyde** [comment]
> @literaldehyde why wouldn't you want to use **hh:mm:ss + milliseconds** (samples) instead?

As mentioned above, I've literally never needed the hours units even once in my hundreds of hours of editing in Audacity. It would help keep the toolbar compact.

**Comment by LWinterberg** [comment]
mm:ss, hh:mm:ss and dd:hh:mm:ss probably should all be one option which then dynamically adjusts the size of the widget as needed by the content. I've noted that down for sometime in the future. I don't think it's worth adding mm:ss+ms in addition to hh:mm:ss+ms in the current system.
