### ISSUE TITLE
phasevocoder.c: Variable is used without being initialized

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#4482]
The problem of using an uninitialized variable is only detected in debug builds. It looks like the problem was introduced by this commit:

Author:		Steve Daulton <SteveDaulton@users.noreply.github.com>
Date:		2 years ago (29/09/2021 11:51:00)
Committer:	GitHub <noreply@github.com>
Commit hash:	72d72d120d29360c35d0b57af3dbd708696cd663
Child:		6750576b
Parent:		1fe4d70d

Issue 1642 Fix by rdb (#1672)

Apply upstream update to Nyquist library.

Fixes special case where the time warp function maps positive output times

to negative input times (negative input times are now handled by filling

with zeros).

Fixes improper handling of Nyquist's logical stop times and terminate times

which have to get mapped through the time warp function to the output.

_Originally posted by @DavidBailes in https://github.com/audacity/audacity/issues/4416#issuecomment-1493873481_

**Comment by rbdannenberg** [comment]
On further study, it looks like g is computed until the mapping function (g) terminates. After that, there's no more mapping, so the output (or maybe input to the phase vocoder) is just zeros, and g0 is not used, so the value of g doesn't matter. I think the best fix is this:

    } else { /* g has terminated, so we just fill input with zeros */
             /* hopsize does not matter, so we'll set it to fftsize/8 */
        memset(samples, 0, pvs->fftsize * sizeof(*samples));
        hop = pvs->fftsize / 8;
        g = 0;
        /* printf("filled samples with 0, hop %d\n", hop); */
    }

(new code is "g = 0;", around line 355). I think in Xcode, where I usually test, there's no check for uninitialized variables. Would you be able to insert the change and test where you already have a test case? If that fixes it, let me know and I'll make the change "upstream". -Roger

**Comment by LWinterberg** [comment]
The error no longer appears with your fix, looks all good @rbdannenberg

**Comment by rbdannenberg** [comment]
Thanks @LWinterberg. I've updated my Nyquist sources. Maybe you can get this into Audacity if it's not in already.

**Comment by SteveDaulton** [comment]
Will someone be committing this fix?
