### ISSUE TITLE
Tracks > Align Tracks ignores Snapping setting

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4490]
### Bug description

When aligning several tracks together using Tracks > Align Tracks command with snapping turned ON, they get aligned ignoring the selected snapping option

### Steps to reproduce

1. Enable beats & measures timeline ruler
2. Have two audio tracks with some audio clips misaligned to each other
3. Ctrl + A
4. Tracks > Align Tracks > End to End or Align Together

### Expected behavior

The tracks get aligned according to the currently selected snapping option

### Actual behavior

The tracks are aligned but totally off beat.
Compare the results with snapping to fourth turned on:
Before
<img width="600" alt="image" src="https://user-images.githubusercontent.com/70063970/229854700-64fa29b4-a899-4782-b69b-599886bb3676.png">

After
<img width="600" alt="image" src="https://user-images.githubusercontent.com/70063970/229854744-46d198bd-74a1-4390-a57f-f4e5f2fe4281.png">

### Audacity Version

other https://github.com/audacity/audacity/actions/runs/4599859841

### Operating system

Other

**Comment by petersampsonaudacity** [comment]
Is this a bug - is this a desired behavior?

If aligning tracks observes snapping you will end up with gaps between tracks surely?

**Comment by dozzzzer** [comment]
@LWinterberg 
please see the expected behavior and either confirm this is valid or close the issue otherwise.

**Comment by LWinterberg** [comment]
this is intended
