### ISSUE TITLE
Tempo Improvements - Beat Detection

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#4495]
### Your idea

We need the ability for Audacity to automatically estimate the tempo of its audio clips.

This should be an asynchronous task, eventually returning a tempo optional that can be associated to the clip.

### Problem to be solved

We want to auto-strech audio clips so that their tempo fits the project tempo.
Would also be the engine behind a "tap-your-tempo" feature.

### Additional context

We can probably assume constant tempo through the clip. That's what Ableton seems to do, and Reaper seems to _require_ manual work to create tempo maps, at least for [high-precision tasks](https://www.youtube.com/watch?v=2SB73rGeIXQ)

**Comment by saintmatthieu** [comment]
Could be broken down in several smaller tasks / PRs :
1. Are audio clips objects ? Do they have metadata ? Does this metadata already have a tempo value ? If not, add it.
2. Is there already a base class for that kind of asynchronous analyses ? Try to find examples.

**Comment by saintmatthieu** [comment]
There is a Beat Finder effect in the Analyze menu. Evaluate this.

**Comment by SteveDaulton** [comment]
> There is a Beat Finder effect in the Analyze menu. Evaluate this.

The "Beat Finder" effect is very primitive. You would definitely need better beat detection than that. I'd suggest looking at how [Mixxx](https://github.com/mixxxdj/mixxx), and/or some of the [Vamp plugins](https://www.vamp-plugins.org/download.html).

**Comment by saintmatthieu** [comment]
1st task in this ticket: put together a benchmarking test app to evaluate accuracy of candidate solutions against a large set of files. (At least some of Muse Hub have tempo information in their names, could be used as ground truths.)

**Comment by saintmatthieu** [comment]
@LWinterberg

**Comment by saintmatthieu** [comment]
Priorities were set straight for 3.4 : time-stretching is a must, but tempo detection can wait. Closing for now. Above-mentioned benchmarking test app can be used again when resuming work on this.
