### ISSUE TITLE
Cogwheel in Selection toolbar malformed in High Contrast theme

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4504]
### Bug description
The Cogwheel in Selection toolbar malformed in High Contrast theme - it has an orange line above it and a green line below.  The other themes do **_not_** seem to be similarly affected.

This happens on latest 3.3.0 Beta and @crsib 's latest branch with the smaller cogwheel,

Image scaled 200% for clarity:
![image](https://user-images.githubusercontent.com/50205984/230441706-ede3faac-da84-4770-9336-62fe9330f6cf.png)

### Steps to reproduce
1. Launch 3.3.0 Beta
2. Edit > Preferences > Interface
3. Select High Contrast theme
4. Observe: Malformed cogwheel icon

### Expected behavior
no extraneous colored lines on the cogwheel icon when using High Contrast theme

### Actual behavior
See image above

### Audacity Version
latest beta: audacity-win-3.3.0-beta-20230406+0184816-x64-msvc2022
and @crsib 's latest smaller Mr Coggy branch: audacity-win-3.3.0-alpha-20230406+dfed530-x64

### Operating system
Windows - but assume all OS

### Additional context
**Update:**
From looking at Dark theme in earlier versions I see that the green underline is present on many/most button icons so this is probably intended - _**but not so**_ the orange line above on the cogwheel icon

**Comment by petersampsonaudacity** [comment]
Share Audio Toolbar ison also has an upper orange bar:
![image](https://user-images.githubusercontent.com/50205984/230443162-b6e8f14d-a72d-4f7c-ae63-dc4c41b7daa8.png)

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @aniruddhJo 's branch build:  audacity-win-3.4.0-alpha-20230416+a69204c-x64

@crsib this seems to fix the cosmetic issue of the extraneous orange line at the top of the cogwheel 

![image](https://user-images.githubusercontent.com/50205984/232328474-9ed15a80-8232-4cba-8020-26143fbe4c24.png)

**Comment by petersampsonaudacity** [comment]
But note the Share Audio butto still has the extrabeous orange line above the cogwheel icon:
![image](https://user-images.githubusercontent.com/50205984/232328848-e1839860-6450-46da-8ad6-61334321b907.png)

**Comment by aniruddhJo** [comment]
@petersampsonaudacity, I am unable to see share audio button in my windows 11 and there is no option in View->Toolbars for any such button
Is it a glitch

**Comment by LWinterberg** [comment]
If you're compiling yourself, you need to set the relevant flags in cmake (I think `audacity_has_networking` and `audacity_has_audiocom_upload`) to make it show up. Alternatively you can get the build that falls out of CI on your PR to test it.

**Comment by petersampsonaudacity** [comment]
@crsib @LWinterberg  this looks to be fixed in the latest master I have - so this can probably be closed.

![image](https://github.com/audacity/audacity/assets/50205984/4593ea03-dbce-4a63-aa0d-4aa143273fb1)

**Comment by petersampsonaudacity** [comment]
@dozzzzer  sorry for any noise (if you saw it) I was mistakenly testing on the Dark theme and NOT the High Contrast - so mistakenly thought this was fixed and added notes on that basis (now removed)

**Comment by LWinterberg** [comment]
This is caused by EffectOn.png being a pixel off in height

**Comment by dozzzzer** [comment]
Tested

**Comment by petersampsonaudacity** [comment]
@dozzzzer @LWinterberg 

Testing on W10 with the latest 3.6.0 alpha build:  audacity-win-3.6.0-alpha-20240430+8715c77-x64-msvc2022

This appears to show an improvement in that the upper extraneous line on the cogwheel is now gone, there still remains an extraneous green line underneath the two cogwheels.

Also note that the Play icon in the Transcription toolbar also has an extraneous green line beneath it:

![image](https://github.com/audacity/audacity/assets/50205984/0de7b576-eeec-4d66-b4f8-f477795372e6)

**Comment by petersampsonaudacity** [comment]
But maybe these green bottom lines are intentional, as I notevarious other buttons (outined in orange) have them too?
![image](https://github.com/audacity/audacity/assets/50205984/73e467e6-65ba-46e6-a994-6b84849f2fc1)

**Comment by LWinterberg** [comment]
Orange lines are separating buttons in the imagecache.png, so an orange line showing is a mistake. The green lines are part of the actual button. I don't know why they're there, but I don't mind them either.
