### ISSUE TITLE
Crash when opening "Preferences > Application" from the Check Updates dialog

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4506]
### Bug description

Crash when opening "Preferences > Application" from "Help > Check for Updates" menu.

### Steps to reproduce

1. Launch Audacity
2. Help > Check for Updates
3. In the dialog, click "Preferences > Application" link
4. Observe

### Expected behavior

Preferences > Application is opened.

### Actual behavior

Crash:
[Audacity_dbgrpt-11712-20230406T223048.zip](https://github.com/audacity/audacity/files/11174247/Audacity_dbgrpt-11712-20230406T223048.zip)

### Audacity Version

other https://github.com/audacity/audacity/actions/runs/4619421588

### Operating system

Windows, macOS

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest Beta audacity-win-3.3.0-beta-20230406+0184816-x64-msvc2022

I confirm this crash - and note that is is a "silent" crash with no error dialog and no phone-home error reporting.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @crsib 's branch build:  audacity-win-3.3.0-alpha-20230407+f4ef424-x64

This issue appears to be properly fixed:
a) there is no crash
b) clicking the link in the **Check for update**s dialog takes the user properly to **Application Preferences**

**Comment by petersampsonaudacity** [comment]
Testing on the latest 3.3.0 Beta

This issue looks to be properly fixed
