### ISSUE TITLE
Crash using Nyquist Prompt effect

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#4517]
### Bug description

When applying the Noise Gate code via the Nyquist Prompt, Audacity crashes.

### Steps to reproduce

1. Generate a tone and apply a couple of fades (this provides a suitable signal for the effect to be clearly seen).
2. Apply Noise Gate (via the Effect menu) with Gate Threshold set to around -12 dB (other settings at default).
3. Observe that the effect works correctly.
4. Undo the Noise Gate effect.
5. Copy the code from noisegate.ny and paste into the Nyquist Prompt effect.
6. Apply with the same settings as used in step 2

### Expected behavior

The Noise Gate effect to be applied.

### Actual behavior

Audacity crashes.

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

Possibly related to https://github.com/audacity/audacity/issues/4498 though in this case the Debug window is not involved.

Regression against Audacity 3.2.4.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @Paul-Licameli 's branch:  audacity-win-3.3.0-alpha-20230410+5721047-x64

This now works properly with Paul's branch build, at step 6 the effect is properly applied.

**Comment by Ryan-Miller-Audacity** [comment]
Tested and confirmed in Paul's branch.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest 3.3.0 Bet

This now works properly with the latest beta  -   at step 6 the effect is properly applied.
