### ISSUE TITLE
Random crashes when opening files with File Explorer (Windows)

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [audacity/audacity#4522]
### Steps to reproduce

1. open a bunch of files to audacity in file explorer
2. random crash

### Expected behavior

Doesn't crash

### Actual behavior

Crash

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by LWinterberg** [comment]
these steps are not sufficient to reproduce this bug. Please update it with information such as: 

* How many files are you trying to open at once?
* How are you trying to open them? Drag'n'drop, File > Open, File > Import, something else?
* Is it freezing (becoming unresponsive) or crashing (instantly closing)?
* How big are the files you're trying to open?

**Comment by H-A-M-G-E-R** [comment]
clicking files in file explorer with audacity as default app
