### ISSUE TITLE
Change Pitch and Change Tempo effects crash with High Quality checkbox on

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#4526]
### Steps to reproduce

1. Generate sound
2. Open Change pitch or Change Tempo
3. Check the box at bottom of the dialog
4. Apply

### Expected behavior

Apply the effect

### Actual behavior

Crash!

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

### Additional context

See #4517 -- these are related

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @Paul-Licameli 's branch:  audacity-win-3.3.0-alpha-20230410+5721047-x64

This now works properly with Paul's branch build, at step $ the effect is proper;y applied.  I tested with both Change Pitch and Change Tempo

**Comment by Ryan-Miller-Audacity** [comment]
Tested and confirmed in Paul's branch.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest 3.3.0 Beta

This now works properly in the latest beta - at step 4 the effect is properly applied.  

I tested with both Change Pitch and Change Tempo
