### ISSUE TITLE
Linear dB ruler loses ticks when getting scrolled off screen

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#4541]
### Steps to reproduce

1. create a number of tracks such that a vertical scrollbar appears
2. scroll down

### Expected behavior

The ticks stay where they are

### Actual behavior

https://user-images.githubusercontent.com/87814144/231985328-a3a8918b-85f1-466e-8331-ad7671d5986a.mp4

### Audacity Version

latest beta

### Operating system

Windows

**Comment by LWinterberg** [comment]
FAO @micpap25

**Comment by micpap25** [comment]
I see, sorry that this was not caught in testing. This is caused by one of my more recent commits which "simplifies" the ruler drawing by only drawing the bottom ticks if the top ticks are drawn. I will check if reverting this change fixes the issue

**Comment by saintmatthieu** [comment]
For me it's much more straightforward  : the bottom track is a copy of the top track. Given my track height in pixels (seems to play a role) the lowest tick I can get is -12dB, which is largely insufficient.
![image](https://user-images.githubusercontent.com/22740106/234875669-70a46b83-80ae-4581-b4db-0458dd2ad2ef.png)

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
