### ISSUE TITLE
Numeric inputs in third-party plugins don't interact correctly in 3.2.x

### ISSUE THREAD

**Issue by khanfluence** [audacity/audacity#4550]
### Bug description

In Audacity 3.2.x, Cockos ReaPlugs no longer behave properly when typing numeric values. The cursor resets to the leftmost position on each keystroke, and minimum / maximum default values are enforced on each keystroke. Neither of these problems occur with Audacity 3.1.x.

### Steps to reproduce

1. Create an audio track so the effect can be opened.
2. Add, e.g., ReaEQ as an Audacity plugin.
3. Open the plugin's GUI via the menu: Effect > Unknown > reaeq-standalone.
4. Focus the Frequency numeric input, selecting its entire value for replacing.
5. Type a digit.

### Expected behavior

The digit is input, and the cursor moves to the right to allow continued typing.

### Actual behavior

The digit is overwritten with what seems to be a default minimum value of 20. Also, the cursor jumps to the leftmost position.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

This screen recording is an example of inputting the digit "3" twice.

https://user-images.githubusercontent.com/10392584/232253985-14c7630e-dbe2-4fed-bbc5-32215d5b2e7c.mp4

**Comment by petersampsonaudacity** [comment]
Testing on W10 with 3.2.5

I confirm this - but I _suspect_ that it is an issue with the Rea plugin rather than Audacity

**Comment by dozzzzer** [comment]
I can reproduce this, however, it does seem that the issue isn't on the host's side but it's rather because of the faulty Rea plugins.
