### ISSUE TITLE
Copy-paste fails with multiple segments targeted after a 40-min continuous segment in new window

### ISSUE THREAD

**Issue by rr-audacity** [audacity/audacity#4553]
### Bug description

trying to copy selected 4 segment in source window to blank area at end on 40 min long continuous segment in second window.  Audacity hangs. fails on all appimages 3.1.3 -> 3.2.5 did not try earlier regressions. Ubuntu 22.04

### Steps to reproduce

1: select several adjacent segment starting in middle of segment one and extending through middle of segment 4
2: ctrl-c
3: place cursor in second window in empty area after 40 minute unsegmented content
4: ctrl-v
5:no response. no copy, audacity hangs

### Expected behavior

copied selection should appear in second window as segments 2-5

### Actual behavior

no copy, no response

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Linux

**Comment by LWinterberg** [comment]
Does this also happen in the 3.3 beta? https://github.com/audacity/audacity/releases/tag/Audacity-3.3.0-beta-1

**Comment by Ryan-Miller-Audacity** [comment]
I have not been able to reproduce this in previous releases (3.2.5) or the current 3.3.3 alpha on windows or my linux variants.
