### ISSUE TITLE
VST plugins fail to work on 3.3.0 Beta

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4558]
### Bug description
VST plugins that I have (Steinbergs rea plugin suit and the  VST version of iZotope Vinyl) fail to work on the latest 3.3.0 beta.  They are visible _(and apparently available for use as they are not grayed-out)_ in the menu but clicking on them yields now plugin effect dialog window.

Also on launch you do not see the rea plugins or iZotope Vinyl VST version being loaded.

This worked fine on 3.2.5 and earlier - and curiously still works on the latest 4.4.0 alpha

This does _**NOT**_ appear to affect VST3 plugins - I also have the VST3 version of iZotope Vinyl and that works fine.

### Steps to reproduce
1. Download rea VST plugins from Steinberg 
2. clear the audacity settings folder
3. launch latest 3.3.0 Beta  (I was using the Japanese Translation build of 17Apr23)
4. get some audio and select it
5. Effect
6. Observe the rea plugins are present in the menu
7. click on one of them
8. Observe: nothing happens

### Expected behavior
These rea commands are available in the menu - they should work
![image](https://user-images.githubusercontent.com/50205984/232468532-2422bcc8-6f95-4482-acce-c6770f07cd1b.png)

### Actual behavior

Clicking on them does nothing:
a) no action
b) no error or warning message

### Audacity Version
latest 3.3.0 beta - Japanes translation update 17Apr23

### Operating system
Windows 10

### Additional context
Found while testing #4550

**Comment by petersampsonaudacity** [comment]
I also note that it's somewhat odd that two of the rea plugins appear under Cockos in the default effect menu - but the other six are un-categorized and are strung out on the default top-level effect menu, needlessly over-lengthening it.

**Comment by crsib** [comment]
> but the other six are un-categorized

This is a bug in the plugins - they do not report the vendor

**Comment by petersampsonaudacity** [comment]
> > but the other six are un-categorized
> 
> This is a bug in the plugins - they do not report the vendor

But in 3.2.5 we had an "Unknown" category in the top-level default effect menu which helped keep the top-level menu usefully a bit shorter:
![image](https://user-images.githubusercontent.com/50205984/232474320-95fd8c53-45b7-43e3-829a-d9f1b38533fc.png)

**Comment by petersampsonaudacity** [comment]
### UPDATE
@crsib   -  When I just retested this the rea plugins and the VST version of iZotope vinyl totally failed to load at all and sre not present in the 3.3.0 Beta menu:
![image](https://user-images.githubusercontent.com/50205984/232477062-84cb4091-038d-4305-b7d6-c08e61a1d97c.png)

**Comment by DavidBailes** [comment]
On Windows 11, using commit: https://github.com/audacity/audacity/commit/c9e5ae7fa19c1e3ed03acc1448e0863a6cbd8052,
I can't reproduce this bug.

**Comment by crsib** [comment]
Nor do I :-)

**Comment by LWinterberg** [comment]
did you accidentally download a 32 bit build or something?

**Comment by petersampsonaudacity** [comment]
> did you accidentally download a 32 bit build or something?

@LWinterberg  -  I don't think so Leo - I've downloaded several successive betas and I'm pretty sure they were 64-bit - and all failed

But I'll be downloading another soon when the current in progress builds complete, so I'll check again then.

**Comment by petersampsonaudacity** [comment]
But that made me look at the build info - and yes that is the case with the current beta build I have:
![image](https://user-images.githubusercontent.com/50205984/232845995-1d386c6c-e342-4362-a581-78fcc86541e7.png)

**Comment by petersampsonaudacity** [comment]
BINGO - give that man, Leo, a cigar !

When I install the latest available build as a 64-bit version - of course the rea plugins work.

I've been so used to pulling the 64-bit zips off the bottom of the list that I was then blindly pulling off the bottom exe link - and that was 32-bit and **NOT** 64-bit   **<at this point Peter blushes very deeply>**

@LWinterberg I think this can be closed ...
