### ISSUE TITLE
NumericTextCtrl does not shows more that 999 bars

### ISSUE THREAD

**Issue by crsib** [audacity/audacity#4560]
### Steps to reproduce

1. Generate enough audio (more than 2000 seconds for 4/4 120BPM)
2. Select all audio
4. Change the time format to bars:beats
4. Observe selection-end shows the wrong value

![image](https://user-images.githubusercontent.com/2660628/232545592-c6206b4f-b83b-48b0-bbba-0bc5f6d2d1ba.png)

### Expected behavior

NumericTextCtrl  support longer audio selection

### Audacity Version

latest beta

### Operating system

Windows, macOS, Linux, Other

### Additional context

The same problem applies to other formats, such as `seconds`, but triggering the bug is much harder, as it requires over 999,999 seconds (almost 278 hours)

**Comment by LWinterberg** [comment]
downgrading priority, In practice, this problem occurs somewhat rarely in music, and when it does occur, the timeline ruler shows the correct number anyway

As for the bug, It currently shows the first 3 digits of the number off by one by the looks of it, so after 999 you have 10 bars of 099, then 10 bars of 100, then 10 bars of 101. A sufficient fix may be to just show the last 3 digits instead, so the bar after 999 is 000 again. PAL frames seems to behave this way.

**Comment by crsib** [comment]
Additional problem is that when you try to increment past 999.3.3 (or past 999999 secs) using the keyboard - the value will reset to zero. 

This behavior is not something new, but it is much easier to reproduce now.

**Comment by DavidBailes** [comment]
In addition:
1. If the playback position goes past 999, then the position in the time toolbar is not correct, and the number of beats does not change during playback - it gets stuck on 4
2. If a selection goes from before the 999 problem to after it, then if you try to adjust selection end in the selection toolbar, then the selection collapses and the cursor ends up in totally the wrong place.

**Comment by DavidBailes** [comment]
> downgrading priority, In practice, this problem occurs somewhat rarely in music, and when it does occur, the timeline ruler shows the correct number anyway

The timeline ruler showing the correct number is of no help to users of screen readers.
