### ISSUE TITLE
Duration in generators cannot be set using one of the bar formats

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#4569]
### Bug description
The Duration in generators cannot be set using one of the bar formats.

### Steps to reproduce
1. Open the chirp generator
2. Try to set the format of the duration to bar.beat or bar.beat.tick

### Expected behavior
You can.

### Actual behavior
You can't
![image](https://user-images.githubusercontent.com/50205984/232722713-326df6be-d56e-4be7-b639-8e96467548e4.png)

### Audacity Version
latest 3.3.0 beta

### Operating system
Windows

**Comment by dozzzzer** [comment]
Postponed until the refactoring of Effects.

**Comment by LWinterberg** [comment]
this is in audacity 4, with https://github.com/audacity/audacity/issues/7928 atm
