### ISSUE TITLE
Cursor sample-position display wraps around 1000

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#4570]
### Bug description

Looks like the displayed cursor position, at least when set to samples (as opposed to e.g. seconds), undergoes a modulo 1000 operation, e.g., if the cursor is at 1234 samples, 234 is displayed. Observe the Selection toolbar at the bottom of [this video](https://user-images.githubusercontent.com/22740106/232713090-4dcc3e42-2aed-49ab-bb52-88712a96107e.mp4) as the cursor is scrolled forward.
Tried with Audacity 3.2.5, but there the display is even worse, can't read the value :  ![3 2 5](https://user-images.githubusercontent.com/22740106/232713469-2a0bb24d-8dd8-4a60-b615-f5bf6a754219.png)

### Steps to reproduce

1. make sure the Project Sample Rate is set to 44.1 kHz
2. make sure the Selection toolbar unit is set to "samples"
3. Ctrl + Q
4. Ctrl + N
5. import a WAV file with a sample rate of 48 kHz
6. click around

### Expected behavior

The correct sample position should be displayed.

### Actual behavior

Looks like the displayed sample position undergoes a modulo 1000 operation, e.g., if the cursor is at 1234 samples, 234 is displayed.

### Audacity Version

latest beta

### Operating system

Windows

### Additional context

Doesn't seem to happen if I generate audio in an empty project.

**Comment by DavidBailes** [comment]
This is a regression wrt Audacity 3.2.5

**Comment by crsib** [comment]
To trigger this issue the sample rate needs to be changed after the sample based format is selected. Dragging wav to Audacity triggers this bug is the file has a different sample rate.

**Comment by dozzzzer** [comment]
Tested
