### ISSUE TITLE
Layout of Welcome dialog is broken in CJK multibyte character languages

### ISSUE THREAD

**Issue by SakiPapa** [audacity/audacity#4576]
### Bug description

When the language setting of Audacity is set to multibyte characters such as Japanese or Simplified Chinese etc, the layout of the Welcome panel and About panel is corrupted. The baseline of multibyte characters and Roman characters are displayed out of alignment.

This issue occurs on both macOS and Windows.

I think the same issue existed in the days of Audacity version 2.

### Steps to reproduce

1. Open Audacity's preferences.
2. Set the language to Japanese in the interface settings.
3. Click OK.
4. Open "About Audacity" from the menu bar. The text layout is aligned wrong
5. Restart Audacity and display the Welcome panel. The text layout is aligned wrong.

### Expected behavior

The baseline of CJK characters should be aligned on the same line as the Roman characters.

### Actual behavior

<img width="1025" alt="welcome_panel" src="https://user-images.githubusercontent.com/106289731/233011894-dae3aedb-3474-4884-ac54-4dff29bdc293.png">
<img width="1163" alt="about_panel" src="https://user-images.githubusercontent.com/106289731/233011949-f4157b48-2cda-45e0-9706-1ef12712407a.png">

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS

**Comment by SakiPapa** [comment]
(1) Windows version of Audacity 3.3.0 seems to fix this issue. (macOS version doesn't)

(2) Update Panel has same problem also.
![UpdatePanel](https://user-images.githubusercontent.com/106289731/235188404-1267e5ae-23d4-4c82-83d2-46dc53243d8c.jpg)

**Comment by Ryan-Miller-Audacity** [comment]
I was able to confirm this behavior on MacOS with Japanese translation selected. As previously mentioned the text appears to display/align properly on Windows now.
