### ISSUE TITLE
Work-disrupting vertical line suddently appeared with no way of removing

### ISSUE THREAD

**Issue by vmsh0** [audacity/audacity#4582]
### Your idea

During my workflow, a vertical line appeared in the middle of one of the tracks:

![image](https://user-images.githubusercontent.com/1955497/233302841-a7d142f3-23ce-45b9-b311-0171821710ae.png)

### Problem to be solved

I don't know what the line is, nor how to remove it. Selecting it is very challenging as its mouse click region is only one pixel wide, and once selected there is seemingly no way of deleting it. The status bar doesn't give any helpful information.

I cannot drag audio clips across this line. The only way I was able to continue working was completely discarding my existing work and starting from scratch in a fresh instance of the program.

**Comment by dozzzzer** [comment]
@vmsh0 without more details it's gonna be virtually impossible to reproduce the issue

**Comment by vmsh0** [comment]
> @vmsh0 without more details it's gonna be virtually impossible to reproduce the issue

What kind of detail should I provide? From my point of view, the line literally appeared out of thin air. I've most likely pressed some keyboard or mouse button inadvertently.

**Comment by vmsh0** [comment]
> What do you see there with extreme close magnification (resolving single samples)?

It would have been a great idea to investigate that, but unfortunately the instance of Audacity (that I was keeping open to provide additional details here if necessary) has crashed a few minutes ago when my Bluetooth headphones went out of range... :vampire:

**Comment by vmsh0** [comment]
I... have reproduced the issue. Here are the steps, which do not work every time:

- Copy a clip
- Paste the clip onto itself (not sure if this is necessary, but it's nonetheless what I do by mistake very often)
- Paste the clip at a later time in the track in a spot where there's not enough space available (not sure if this is necessary)
- Paste the clip at a later time in the track

This is literally all I just did, and it spawned a vertical line.

When zooming it, at a certain point the line becomes invisible. That's _before_ you zoom in enough to resolve individual samples. However, if you swipe the mouse horizontally in the area where the line is supposed to be, you can still highlight it in yellow, suggesting it's definitely still there:

![image](https://user-images.githubusercontent.com/1955497/233309066-f069d3a4-46dd-44ed-aa3d-ad554e1c0c08.png)
![image](https://user-images.githubusercontent.com/1955497/233309093-cc05f18c-50b7-46ac-9592-66d2f78cea51.png)

**Comment by petersampsonaudacity** [comment]
It is quite likely to be a very small clip with only a few samples (Which is why @Paul-Licameli asked what you saw when you zoomed in).

Because it is so thin, when zoomed out it would just show as a thin black line.

**Comment by vmsh0** [comment]
Ok, that information might help me address the problem should it happen again.

But please do note that this was happening when selecting clips by double-clicking on their title bar, so something is definitely going wrong (i.e. I'm not mis-selecting clips before a copy operation - these few-samples clips are really coming out of nowhere).

Can I help with any additional details?

**Comment by LWinterberg** [comment]
This is a very short clip, you can just select the area around it and delete to make it go away. We'll add a more obvious clip selection state in a later release.
