### ISSUE TITLE
Snapping: keyboard commands with default shortcuts left and right arrows etc don't always work.

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#4583]
### Steps to reproduce

1. Generate a 30min chirp. (The chirp will fit the width of the Audacity window. Don't change the zoom factor.) 
2. Set snapping on, and snap to any of: milliseconds, centiseconds, deciseconds, or possibly seconds, depending on the resolution of your monitor and the width of the Audacity window.
4. Click somewhere in the chirp.
5. Press right arrow a few times

### Expected behavior

The position of the cursor as shown visibly and by the value of selection start in the selection bar should change after each press of the right arrow key.

### Actual behavior

The position of the cursor doesn't change after each press of the right arrow key.

### Audacity Version

latest beta

### Operating system

Windows

### Additional context

This is a regression.

**Comment by petersampsonaudacity** [comment]
It appears to be the zoom level that is causinf this.

a) if you generate a 3 minute chirp with the full chirp on display it seems to work properly

b) BUT if you generate a 30 minute chirp with the full chirp on display it wiil move forwar 1 second (my set snapping frmat) and back one second again - but then move no more than that on further clicks.  BUT if you zoom out on this chirp a few times then it will move the cursor properly with the right and left arrows.

_I have not experimented to finf the cut-off size where it stops working af default window size._

**Comment by petersampsonaudacity** [comment]
Also note that the Shift and Ctrl+Shift modified left and right arrow shortcuts don not work on the 30 minute Chirp at full chirp in default window size.  But as above, zoom out a few times and they then do work. 

Zoom the 30 minute chirp to fit the window again and once again they don't work.

Also note that if you generate a 30 second chirp the arrows and modified arrow keys work - but if you zoom out several times then they stop working.

**Comment by dozzzzer** [comment]
Tested

**Comment by DavidBailes** [comment]
@crsib Thanks for the very fast fix.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with the latest 3.3.0 Beta

@crsib @DavidBailes 

With my snapping on and set to seconds format and with a 30 minute chirp I am finding that a single press of the arrow keys will sometimes move the cursor just the one second nut also it can sometimes move it 2 seconds or 3 seconds with a single press.

**Comment by LWinterberg** [comment]
that is expected - arrow keys move the cursor by 1px, and with the fix *at least* to the next snapping distance.

**Comment by DavidBailes** [comment]
> With my snapping on and set to seconds format and with a 30 minute chirp I am finding that a single press of the arrow keys will sometimes move the cursor just the one second nut also it can sometimes move it 2 seconds or 3 seconds with a single press.

With the above set up, if you temporarily turn snapping off and use the left/right arrow keys, you'll probably find that the step size is around 2 seconds, but it won't be an exact number of seconds. So when snapping is on, the position is "snapped" which results in things being rounded up or down - hence the variation.
