### ISSUE TITLE
Snapping checkbox doesn't get checked when clicking the label

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4586]
### Steps to reproduce

1. click the label "Snap" in the snapping toolbar
2. check if the label is aligned with the checkbox itself

### Expected behavior

1. clicking the label also checks the checkbox
2. the label is aligned horizontally with the checkbox itself

### Actual behavior

1. clicking the label does not check the checkbox
2. the label is misaligned horizontally with the checkbox itself (macOS only)

![image](https://user-images.githubusercontent.com/70063970/233642471-1162b01b-77a7-49b4-ace3-e2385df520a6.png)

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @crsib 's branch build:  audacity-win-3.3.1-alpha-20230426+89b40ab-x64

clicking on the "**Snap**" label now toggles the snapping state in this branch build

**Comment by dozzzzer** [comment]
Tested.
The misalignment of the label issue cannot be easily fixed due to the limitations of the wxwidgets.
