### ISSUE TITLE
Inconsistent tooltip for "Preview" button

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#4587]
### Bug description

A very minor thing I'm sure, but I notice it now as an oversight in the changes for the destructive effect dialog, where we meant to remove all the special treatment of realtime capable effects

### Steps to reproduce

1. Generate sound
2. open Amplify
3. Hover the mouse over "Preview" and read the tooltip
4. Dismiss dialog
5. Repeat instead for one of the built-in realtime capable effects

### Expected behavior

Same text

### Actual behavior

First says "PreviewEffect" but the second says "Start and stop preview"

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

**Comment by petersampsonaudacity** [comment]
It's a bit more complicated that that ...

With the non real-time built-in effects, clicking the Preview button pops up a little dialog window annd Audacity plays a six second preview:
![image](https://user-images.githubusercontent.com/50205984/233779043-e8a65485-f2a4-4332-866d-4375d893354b.png)

But with a real-time enabled built-in effect the behavior is quite different - on clicking the Preview button:
a) the is no additional preview dialog
b) the Preview button changes to Stop Preview
c) the preview playback, plays the whole selection as a preview (not the short six second preview)
![image](https://user-images.githubusercontent.com/50205984/233779292-0d1556d9-2419-48d5-98a6-80d6e4e5b12b.png)


So maybe we don't want or need to change the tooltip as the button behavior is different for re-time enabled and non-real-time enabled effects - and thus the two different tooltips are appropriate.

**Comment by dozzzzer** [comment]
Tested

**Comment by petersampsonaudacity** [comment]
@LWinterberg  this looks to be fixed in the recently released 3.1.1
