### ISSUE TITLE
Recording Level slider stuck on initial install.

### ISSUE THREAD

**Issue by WJPARRY** [audacity/audacity#4597]
### Bug description

I updated to 3.3.0 and was trying first recoding project and could not get the Recording level slider to move at all.  I tried with and without monitoring being enabled. Playback slider working fine.

### Steps to reproduce

from opening AUDACITY
click on Recording Level Slider and try to move while holding.

### Expected behavior

 it will move under cursor control.

### Actual behavior

 slider does not move. 

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

Severe error: cannot proceed with recoding.

![image](https://user-images.githubusercontent.com/131711646/234101859-13eac58a-7034-49c1-a6bf-cd1e89827f4a.png)

**Comment by LWinterberg** [comment]
What happens if you change your host (from MME to WASAPI or vice versa, for example)?

**Comment by LWinterberg** [comment]
ah, I found the forum thread - https://forum.audacityteam.org/t/stuck-recording-level/74321

that indeed was the cause
