### ISSUE TITLE
«Cut» command consumes unfairly huge amount of time and disk space

### ISSUE THREAD

**Issue by stdword** [audacity/audacity#4600]
### Steps to reproduce

1. Generate 1 hour chirp
2. Save the project to disk and exit audacity
3. Note the size of the project file (654.4 MB for me)
4. Open project
5. Make 15 cuts (command name «Cut») of length 0.5-1 min at random places:
    <img width="600px" src="https://user-images.githubusercontent.com/1984175/234148498-2f6942e3-e076-4537-879c-ad37eacf8d49.png"/>
7. Save the project to disk and exit audacity
8. Note the size of the project file: it changes drastically (1.81 Gb for me)

### Expected behavior

File size don't increases too much. Every cut takes very short time.

### Actual behavior

File size increases too much. Every next cut takes exorbitantly huge amount of time. At some point in real projects it leads to «Automatic database backup failed» errors. Very similarly to [this](https://forum.audacityteam.org/t/automatic-database-backup-failed/62449) topic.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Additional context

MacOS Monterey, v12.6
Audacity v3.3.0

**Comment by crsib** [comment]
Can you please clarify what is Cut? I cannot reproduce the described behavior using Cut (Cmd-X) or Split (Cmd-I).

However, it is known that "destructive" **editing** can contribute a lot to the file size.

**Comment by dozzzzer** [comment]
Cannot reproduce this on macOS Ventura and Audacity 3.3.0
The project's size changes slightly in my case (643 Mb -> 678 Mb)

**Comment by stdword** [comment]
@dozzzzer @crsib

1) «Cut» command is the one that has name «Cut» in `Preferences` → `Keyboard`:
    <img width="400px" src="https://user-images.githubusercontent.com/1984175/234229217-f27dd72d-b78f-492e-a482-8860838b5939.png"/>
2) It is completely reproducible for me. Get into this every time I've used «Cut».
3) Note, that when I use «Delete» instead of «Cut» — things behaves like for you: file size changes slightly.
4) The issues doesn't related for v3.3.0 — it was there before I've updated Audacity.
5) I guess some setting can make an impact. «Enable cut lines»? So here is my `Preferences` → `Tracks Behaviors`:
    <img width="400px" src="https://user-images.githubusercontent.com/1984175/234230310-06034b73-05c2-4d16-99fd-69d186474019.png"/>

What else can I do to provide more details?

**Comment by stdword** [comment]
Additional:
- MacOS v12.6 — Monterey, not Ventura
- `Preferences` → `Libraries`:
  <img width="400px" src="https://user-images.githubusercontent.com/1984175/234232251-2a8d35eb-f6a3-4eec-a21d-1998443c2f1b.png"/>

**Comment by petersampsonaudacity** [comment]
Testing on W10 woth 3.3.0 / 3.0.0 / 2.4.2

I confirm @stdword 's findings

### 3.3.0
Step 3  -  628,288KB
Step 7 -  1,200,128 KB 
i.e. twice as much size occupanve


**3.0.0**
Step 3  -  6288,288 KB
Step 7  -  679,168 KB
i.e. ~ same at both steps


**2.4.2**
Step 3  -  644,964 KB
Step 7  -  645, 066 KB


So 2.4.2 with the old AUP "pile-of-files" project format and 3.00 the initial implementation of the unitary SQLite database project format are roughly equivalent.

3.3.0 with it's double the size at step 7 indicates that changes between 3.0.0 and 3.3.0 are causing this.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @vsverchinsky 's branch build audacity-win-3.3.1-alpha-20230426+634928e-x64

1) at step 3 size is 628,288  kb  -  at step 7 size is only slightly larger at 691,456 kb

2) I experience no slow editing with the 15th and subsequent Cuts

Looks like a good improvement to me

**Comment by dozzzzer** [comment]
Tested. The file size now changes from 643.4 Mb to 708 Mb in my case.
