### ISSUE TITLE
OSX Cata FFMPEG Fail

### ISSUE THREAD

**Issue by juanpc2018** [audacity/audacity#4602]
### Bug description

OSX Cata
Audacity works https://www.audacityteam.org/download/mac/
FFMpeg .pkg installed ok.
https://support.audacityteam.org/basics/installing-ffmpeg
https://lame.buanzo.org/ffmpeg.php
https://lame.buanzo.org/FFmpeg_5.0.0_for_Audacity_on_macOS.pkg
Fail to Detect.
i dont know where the ffmpeg.pkg installs.

<img width="445" alt="image" src="https://user-images.githubusercontent.com/33388902/234169018-31673af0-1666-4f06-82d8-e2c241bb5ca0.png">

<img width="812" alt="image" src="https://user-images.githubusercontent.com/33388902/234168951-f77d1990-53a7-45ee-a9c6-cad6588103ad.png">
<img width="544" alt="image" src="https://user-images.githubusercontent.com/33388902/234168993-4196966c-5fcf-418a-9085-d25f33d1e587.png">

### Steps to reproduce

install
feil

### Expected behavior

Detect

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS

**Comment by juanpc2018** [comment]
will try brew method:

> brew install curl
> brew install ffmpeg

**Comment by LWinterberg** [comment]
did you install audacity and ffmpeg with matching architecture (either x86_64 or arm64 for both)?

**Comment by crsib** [comment]
> did you install audacity and ffmpeg with matching architecture (either x86_64 or arm64 for both)?

The package on Buanzo's website is universal

@juanpc2018 can you please send the logs? (Help -> Diagnostics -> Show Log)

**Comment by juanpc2018** [comment]
brew install curl ffmpeg
worked
but takes 10 hours in a 2-core MacMini 2014
<img width="831" alt="image" src="https://user-images.githubusercontent.com/33388902/234336565-a93a26ec-edfe-4a7d-9f22-6bf49e3e8d85.png">
