### ISSUE TITLE
custom project rate stays greyed out

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#4612]
When choosing "other" in the sample rate dropdowns, in the current version a text box right next to it should enable. This is not the case for the project rate, only for the default rate.
![image](https://user-images.githubusercontent.com/87814144/234560691-983c7310-5da0-46a6-be89-d5af9a3ebc9a.png)

**Comment by LWinterberg** [comment]
![image](https://user-images.githubusercontent.com/87814144/234563799-9380ae86-cae0-4d16-94d9-323a96e8a918.png)
A workaround exists via Extra > Scriptables I > Set Project

**Comment by dozzzzer** [comment]
Tested
