### ISSUE TITLE
Add brush to tool toolbar

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#4622]
### Your idea

The brush tool is useful ! It's a convenient way of reducing clicks that a user may find.
I suggest adding it to the tool toolbar, rather than having it hidden behind pencil + Alt.

### Problem to be solved

Making users aware of the availability of this useful functionality.

**Comment by Paul-Licameli** [comment]
I believe the cursor changes to a spray paint can on Linux

**Comment by petersampsonaudacity** [comment]
Yes the Manual say brush normally - but spray-can on Linux:
![image](https://user-images.githubusercontent.com/50205984/234868731-58073638-43da-42e8-8bc5-205611925961.png)

**Comment by petersampsonaudacity** [comment]
>I suggest adding it to the tool toolbar, rather than having it hidden behind pencil + Alt.

It was certainly a learning for me to discover the "brush" _(as a long-term user of Audacity and one who used the pencil many many times when I was repairing the clicks on my LP transcriptions before I discovered the ClickRepair app)_

I can see that it might be advantageous to make the brush more "discoverable" - but I thought that Muse's long-term design plan was to do away the the Tools toolbar with the functionality achieved in different ways and with selection being always "on", always available.

**Comment by LWinterberg** [comment]
We generally want to go mode-less as much as possible, so it won't be added to the tools toolbar. 

Having a click repair available interactively that's not as hidden as this would be very useful indeed though.
