### ISSUE TITLE
copy & pasting Label Track to another project, when "Selected audio only" behaviour is on, shifts the entire track

### ISSUE THREAD

**Issue by doom-hamster** [audacity/audacity#4626]
### Bug description

When the setting:
**Edit > Preferences > Tracks Behaviors > Pasted audio**
is set to **"Selected audio only."**

and you try to copy&paste label track (that doesn't have a label at 0 seconds) to another project - audacity shifts the entire track so that the first label is now sits at the beginning of the project.

Windows 10, Audacity 3.3.0 release build x64

### Steps to reproduce

1. Enable setting: **Edit > Preferences > Tracks Behaviors > Pasted audio:** **"Selected audio only."**
2. On blank project, create Label Track, place labels anywhere but the beginning - at 7 seconds, 20 seconds, etc.
3. Press Ctrl-A or select the whole track. Copy & Paste to new project.

### Expected behavior

The position of labels on timeline is preserved between projects.

### Actual behavior

After pasting, the labels are shifted to the beginning of the project.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows, macOS

**Comment by virgilON** [comment]
This bug affects all labels having a leading dead space being copied from one project to another, not only into a blank project.  In other words, if a block of audio and associated label tracks (or just a label track(s)) is copied from one project to another, any label tracks that do not include a label beginning before--or align exactly with--the selection will cause the labels within those selected tracks to be shifted to the beginning of the selection.  Fortunately, existing labels in the target project are not affected.
This unexpected behavior can quickly corrupt a project and may do so without being noticed where the offsets are small.  For some users, it may make the long-awaited "Selected audio only" option more problematic than the problem (bloated files) it solved.  I would urge the team to give this bug top priority--it cannot wait for version 3.4!

**Comment by DavidBailes** [comment]
In EditMenus.cpp,
comparing the lines in DuplicateDiscardTrimmed():
```
auto trackCopy = track->Copy(track->GetStartTime(), track->GetEndTime(), false);
trackCopy->Init(*track);
trackCopy->SetOffset(track->GetOffset());
```
to what look like the equivalent lines inn OnDuplicate():
```
auto dest = n->Copy(selectedRegion.t0(),
              selectedRegion.t1(), false);
dest->Init(*n);
dest->SetOffset(wxMax(selectedRegion.t0(), n->GetOffset()));
```
If in DuplicateDiscardTrimmed() there is this change:
`trackCopy->SetOffset(wxMax(track-GetStartTime(), track->GetOffset()));`
then this "appears" to fix this issue.
However, I don't understand exactly what this wxMax stuff is doing.

**Comment by DavidBailes** [comment]
I've submitted a PR for this wrt 3.3.2. If it isn't wanted for that release, just let me know, and I'll change it to wrt master.

**Comment by dozzzzer** [comment]
Tested
