### ISSUE TITLE
Set Track crashes Audacity when applied to a label track

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#4628]
### Steps to reproduce

1. Just downloaded Audacity 3.3.0 (Win 10 home 64bit), 
2. created an new label track (Tracks->Add New->Label Track), 
3. selected Extra->Scriptables II->Set Track..., 
4. pushed OK-button (even after selecting nothing) 
5. and Audacity crashed after giving a bug report. 

### Expected behavior

No crash

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

This doesn't happened with Audacity 3.2.4 or 3.2.0.

Via https://forum.audacityteam.org/t/audacity-3-3-0-is-out/74344/20

**Comment by Ryan-Miller-Audacity** [comment]
@Paul-Licameli Link to Sentry crash report: https://sentry.audacityteam.org/share/issue/0076e68ae3c34d8dbbaaa588726ff2b1/

**Comment by Paul-Licameli** [comment]
I failed to reproduce it at 796603d8644b8c0440f1fd44a60bbf3dbc317925 in 3.4 alpha

**Comment by petersampsonaudacity** [comment]
Testing on W10

1) with 3.3.3 the STRs still produce a crash

2) with latest alpha test build for 3.4.0:  audacity-win-3.4.0-alpha-20230711+51febec-x64-msvc2022
**NO** crash is caused at Step 4
