### ISSUE TITLE
Request: Make File Explorer not use dropdown path mode

### ISSUE THREAD

**Issue by joshcamas** [audacity/audacity#463]
When saving / loading a file, this is the file selection dialog that appears:
![Screenshot_122](https://user-images.githubusercontent.com/26180637/77352307-3a116b80-6cfc-11ea-9ef8-ac5c7fdddc87.png)

This mode (I do not know the word for it) is incredibly frustrating to use. It doesn't have a list of "bookmarks", you can't copy/paste the path, and more. It makes saving files in multiple directories (which I do all the time) a huge pain.

A fix would be to use this form of file dialog:
![Screenshot_123](https://user-images.githubusercontent.com/26180637/77352310-3aaa0200-6cfc-11ea-86b1-27f15e393682.png)

I assume this would be an easy fix, although I lack knowledge on windows explorer API's, so I could be wrong. 

If users like the original dialog style for some reason, could it at least be in a setting?

Thank you!

**Comment by joshcamas** [comment]
After looking into it a bit, it looks like the reason the dialog looks like this is due to the OFN_ENABLEHOOK hook being used. This seems to be a wonderful windows issue. It looks like the solution would be to instead use the IFileDialogCustomize interface instead of the hook, although naturally I have no idea whether the interface would allow for whatever modifications Audacity applies using the hook.

**Comment by lllucius** [comment]
I definitely want to convert over to the IFileDialog... interfaces and I'll probably do it during our conversion to wxWidgets 3.1.3/3.2.0.  So, we'll leave this open as a reminder to get it done.  :-)

**Comment by joshcamas** [comment]
Any idea when this conversion will be started and finished? No rush, just interested :)

**Comment by lllucius** [comment]
No idea really.  But, it should be fairly soon since many Linux distros are starting to bundle 3.1.1+ and we need to be ready.

**Comment by joshcamas** [comment]
Any updates on this? Has the conversion to 3.1.3/3.2.0 begun? :)

**Comment by Robert-J-H** [comment]
It also came up on the Audacity4Blind mailing list. The lack of the tree navigation is definitely  a minus point.
Lucius is being occupied with implementing unified projects (getting rid of the additional data folder). So, I guess it has to wait until Audacity 3.0 is out.

**Comment by LWinterberg** [comment]
This has been superseded by #1002. For exporting specifically, a fix is nearing completion via #4668
