### ISSUE TITLE
Export of playhead position

### ISSUE THREAD

**Issue by evertvorster** [audacity/audacity#4638]
### Your idea

When recording audio narration for a video, it's nice to see where you are in the video while talking. 

It would be totally awesome if audacity exported it's playhead position so that another program can read that position and  play a corresponding part of a video clip.

### Problem to be solved

It is hard to synchronize between two applications that both have a timeline. The only information that need to be shared is the timeline position, and one application would be the controller, and another would read that informaiton and follow along.

Audacity is really good at recording, and editing audio recordings. There are some video editors that can also record, but the controls are clunky and basic, and a lot of features are simply missing. I would rather that each application do what they do best, and work together in some situations.

This is also a fairly easy thing to implement, I believe, as the playhead position is known. Of course if you have any other ideas on how to implement this sort of thing, I am all ears. 

### Prior art

I have not found anything that does this. There are applications that do this within their own application, but nowhere do I see applications cooperating. 

### Additional context

I use kdenlive extensively, and plan to ask them to make an interface where the timeline playhead position could be locked to an external source, much like using a paddle wheel for the playhead position.

With these two applications working together, I would easily be able to make a narration track for video clips.

**Comment by LWinterberg** [comment]
Actual video tracks are planed, which avoid this fragile construct of keeping two separate programs in sync and compatible throughout various program updates. The solution you're proposing works sort of on Audacity's end in that Audacity receive commands via a pipe: https://manual.audacityteam.org/man/scripting.html

**Comment by evertvorster** [comment]
Hi there, and thank you for taking the time to respond. 

How difficult would it be to export the playhead position? Would exporting the playhead position really affect the stability of Audacity?

Of course I don't know how it would even be possible to export a value from one program to the next, but I do know that different programs in the Unix/Linux world pass messages to each other all the time, so it is possible. Whether that would be cross-platform I don't know either. 

Really, all the information I am after is this: 
![image](https://user-images.githubusercontent.com/12045269/235378656-33d13d3e-2455-47e4-830b-7aeb7df2034d.png)

I might even set up a screen capture and OCR to get the value that is displayed here and use it as input for the playhead position in kdenlive.... it just seems a waste of CPU cycles for what really should be just a text string.
