### ISSUE TITLE
Add "Project Sample Rate" as a menu item in the Audio Setup Toolbar/button menu

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4642]
### Your idea

Now that for 3.3.1 "Project Rate" has been removed from the main Audacity Window _(it was always part of the old Selection Toolbar)_  many users, as witnessed on the Forum and FaceBook user group postings, are:
a) struggling to find where to change the **Project Sample Rate** (which is now 2 clicks down in the **Audio Settings Dialog** from the **Audio Setup** toolbar/button)
b) complaining that it takes more clicks to change (or view) the rate

I suggest the a new entry be added to the **Audio Setup** toolbar/button menu for **Project Sample Rate**

### Problem to be solved

**Existing:**
![image](https://user-images.githubusercontent.com/50205984/235642251-02266b64-ae4f-4269-9520-17a6104b18a5.png)

**Suggested:**
![image](https://user-images.githubusercontent.com/50205984/235644292-75bd1294-3208-4e56-a419-21d4e115ec35.png)

### Prior art
None

### Additional context
This may help to make the relocated Project rate to be more "discoverable" and more obviously accessible

**Comment by LWinterberg** [comment]
#4317 makes this unnecessary. The vast majority of feedback I've seen about this is related to setting the sample rates for exporting.

The other problems I've seen people solve with a different sample rate: 

1. I want to preview how low I can go with the sample rate before the nyquist frequency becomes a problem and then export with that rate. 
2. I have low storage space so for longer recordings I like to lower the recording sample rate
3. I use different interfaces which support different sample rates

A highly visible sample rate doesn't really benefit any of these cases, as better solutions would be: 

1. A sample rate reduction VST plugin
2. Given how affordable storage space is, buying more 
3. Detecting a device's default sample rate and just following that solves that without needing additional user input
