### ISSUE TITLE
Crash in DefaultFormatRegistrator

### ISSUE THREAD

**Issue by zb3** [audacity/audacity#4656]
### Bug description

I understand this might not be the appropriate place to report this as I'm using the `audacity-freeworld-3.3.0-1.fc38.x86_64` package which might not correspond to the latest version, however the bug seems pretty interesting.

I've tried to debug this using GDB and it appears that the `NumericConverterType` passed to `DefaultFormatRegistrator` is empty (this is called in https://github.com/audacity/audacity/blob/master/libraries/lib-numeric-formats/formatters/ParsedNumericConverterFormatter.cpp), thus the assertion is triggered which prevents registering multiple defaults for the same type.

Why does that happen? It it related to some compiler switch?

### Steps to reproduce

1. Install the `audacity-freeworld-3.3.0-1.fc38.x86_64` package from RPM Fusion on Fedora 38
2. Launch "audacity" in the terminal

### Expected behavior

The program starts :)

### Actual behavior

The program doesn't, this is shown:
```
audacity: /builddir/build/BUILD/audacity-Audacity-3.3.0/libraries/lib-numeric-formats/NumericConverterFormats.cpp:40: NumericConverterFormats::DefaultFormatRegistrator::DefaultFormatRegistrator(const NumericConverterType&, const NumericFormatSymbol&): Assertion `false' failed.
Aborted (core dumped)
```

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

**Comment by crsib** [comment]
This would be fixed by https://github.com/audacity/audacity/pull/4644

It is odd that Fedora builds packages with assertions enabled though

**Comment by zb3** [comment]
@crsib Thanks! The weirdest part for me is that the package which doesn't start at all is in the stable fedora release while a newer package is in testing, seems that either they didn't test it at all, or assumed that LTO can't possibly break any package. Either way, it's the first time I see this happening :)

**Comment by leigh123linux** [comment]
#4644  Fixes the issue

https://pkgs.rpmfusion.org/cgit/free/audacity-freeworld.git/commit/?id=958ac096a08f7f78fff59d4bdab09e9aa943d143
