### ISSUE TITLE
Destructive effects: most of them don't have preview buttons

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#4665]
### Steps to reproduce

1. From the Effects menu, open one of Audacity's built-in effects which can't be added from the realtime effect panel. That is any effect apart from: Bass and Treble, Distortion, Phaser, Reverb and Wahwah
2. Look for a preview button.

### Expected behavior

There is a preview button

### Actual behavior

There isn't

### Audacity Version

latest beta

### Operating system

Windows

### Additional context

May have be caused by https://github.com/audacity/audacity/pull/4664 ?

**Comment by petersampsonaudacity** [comment]
Confirmed on W11 - this is a regression on 3.3.1

**Comment by petersampsonaudacity** [comment]
Testing on W11 with @crsib 's branch build:  audacity-win-3.3.2-alpha-20230505+99439e5-x64

This branch build fixes the problem - the effects have their preview buttons restored when invoked from the Effect menu.

**Comment by dozzzzer** [comment]
Tested
