### ISSUE TITLE
Can't build against the Conan wxWidgets because headerfiles are not found

### ISSUE THREAD

**Issue by RJVB** [audacity/audacity#4673]
### Bug description

I have spent a few hours yesterday trying to get Audacity to build using the Conan wxWidgets package. These attempts all failed because apparently only the resulting libraries are exposed to the actual Audacity build process, but not the corresponding headers. The 1st error that holds the build process is because `<wx/string.h>` is not found.

It does not matter if I allow prebuilt Conan packages or force a build from sources.

The current bug report is about building master/HEAD on Linux but I ran into the same issue on Mac a few months back:
https://forum.audacityteam.org/t/building-against-the-conan-wxwidgets-build/66819

### Steps to reproduce

1. mkdir audacity-git/build && cd audacity-git/build
2. ../../cmake-audacity.sh .. # (see "Additional context")
3. ninja

### Expected behavior

Success

### Actual behavior

Build failure as described above.

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

I did not try this with a vanilla `cmake` invocation for lack of time & resources: my intended configuration is obtained with this `cmake-audacity.sh` script:

```
#!/bin/sh

export CCACHE_SLOPPINESS=pch_defines,time_macros
export AR=/usr/bin/gcc-ar-8
export NM=/usr/bin/gcc-nm-8
export RANLIB=/usr/bin/gcc-ranlib-8
export CC="gcc-8"
export CXX="g++-8"
export CFLAGS="-O3 -ftracer -march=native -g -DUSE_AQUA_THEME"
export CXXFLAGS="-O3 -ftracer -march=native -g -Wno-inconsistent-missing-override -Wno-overloaded-virtual -DUSE_AQUA_THEME"
export OBJCFLAGS="-O3 -ftracer -march=native -g -DUSE_AQUA_THEME"
export OBJCXXFLAGS="-O3 -ftracer -march=native -g -Wno-inconsistent-missing-override -Wno-overloaded-virtual -DUSE_AQUA_THEME"
export LDFLAGS="-L/usr/local/lib -Wl,--enable-new-dtags -Wl,-rpath,/usr/local/lib -Wl,-rpath,/usr/local/lib/audacity"

cmake  -G "Ninja" -DCMAKE_BUILD_TYPE=MacPorts -DCMAKE_INSTALL_PREFIX="/usr/local" -DCMAKE_INSTALL_NAME_DIR="/usr/local/lib" \
    -DCMAKE_SYSTEM_PREFIX_PATH="/usr/local;/usr" -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
    -DCMAKE_OBJC_COMPILER_LAUNCHER=ccache -DCMAKE_OBJCXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER="$CC" -DCMAKE_CXX_COMPILER="$CXX" \
    -DCMAKE_OBJC_COMPILER="$CC" -DCMAKE_OBJCXX_COMPILER="$CXX" -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_POLICY_DEFAULT_CMP0060=NEW \
    -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_COLOR_MAKEFILE=ON -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
    -DCMAKE_MAKE_PROGRAM=ninja -DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=ON -DCMAKE_INSTALL_RPATH="/usr/local/lib;/usr/local/lib/audacity" \
    -Wno-dev -Daudacity_lib_preference=system -Daudacity_has_tests=off -Daudacity_has_sentry_reporting=off -Daudacity_has_crashreports=off \
    -Daudacity_has_updates_check=off -Daudacity_conan_allow_prebuilt_binaries=off -Daudacity_use_audio_units=off \
    -Daudacity_use_ffmpeg=loaded -Daudacity_use_soxr=system -Daudacity_use_vamp=local -Daudacity_use_lv2=local \
    -Daudacity_use_suil_qt5=ON -Daudacity_use_sbsms=local -Daudacity_use_soundtouch=system -Daudacity_use_twolame=system \
    -Daudacity_use_midi=system -Daudacity_has_vst3=off -Daudacity_use_sqlite=system -Daudacity_use_pch=OFF \
    -DCMAKE_DISABLE_FIND_PACKAGE_JACK=On -Daudacity_use_wxwidgets=local \
    -DCMAKE_AR="${AR}" -DCMAKE_NM="${NM}" -DCMAKE_RANLIB="${RANLIB}" -DCMAKE_CXX_STANDARD=14 "$@"
```

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444) which uses a different build system. This bug should no longer be applicable.
