### ISSUE TITLE
Can't disable GUI mode for VST2 plugins

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4677]
### Steps to reproduce

1. open up a VST2 plugin's dialog
2. in the Options menu, uncheck the checkbox "Enable graphical interface" and confirm
3. re-open the plugin's dialog 

### Expected behavior

Generic (non-GUI) mode is enabled

### Actual behavior

GUI mode persists regardless

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows, macOS

**Comment by petersampsonaudacity** [comment]
Testing on W11 with 3.3.2

This also happens with my VST3 iZotope Vinyl ( and my VST version of the same plug-in)
