### ISSUE TITLE
Audio starts before 0 seconds

### ISSUE THREAD

**Issue by JustSomeRandomGuy3** [audacity/audacity#4682]
### Bug description

When opening a project (or a media file), if you double click at the 0 seconds mark, it goes back 9 seconds and then back to normal.

### Steps to reproduce

1. Grab yourself a media file (or an Audacity project)
2. Import it
3. Double-click at the 0,0s mark
Done.

### Expected behavior

It begins at the beginning. (0,0s mark)

### Actual behavior

It goes back 9 seconds. (from 0,0s mark)

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

Demonstration:
https://github.com/audacity/audacity/assets/102457568/8c7abdd8-9d1b-4342-b6f0-2cb2bab6ae77

Also, did anybody else notice this? I have no idea if this issue has been posted.

**Comment by crsib** [comment]
Judging by your video - you have "Pinned Play Head" enabled. https://manual.audacityteam.org/man/timeline.html#pinned

**Comment by JustSomeRandomGuy3** [comment]
I turned it off, now it works. But it feels weird that I have to turn it on again every single time I want to check my project.
Solution: Click once.
