### ISSUE TITLE
Track resampling is not working

### ISSUE THREAD

**Issue by thexmarat** [audacity/audacity#4685]
### Bug description

Can't resample wav, and mp3 files.
Tried resample, 48000Hz wav to 8000Hz or to other sample rates. After exporting as Wav encoded to "Signed 16-bit PCM" changes not applied.  Export to mp3 the same.
![изображение](https://github.com/audacity/audacity/assets/56560794/b1ade956-9370-4f94-8dc6-250dd4794575)
![изображение](https://github.com/audacity/audacity/assets/56560794/9cb39ec6-76a5-42a2-9b93-607e09f147c0)
![изображение](https://github.com/audacity/audacity/assets/56560794/de909555-6230-4394-8dbd-59c8b4a7c981)
versions Audacity 3.3.0 and 3.3.2 contain this bug

### Steps to reproduce

1. Open wav file in Audacity 3.3.0 or 3.3.2
1.1. Select Tracks - Resample (change rate to other)
1.2. Seleсt File - Export - Export as Wav.
1.3. Change Encoding to "Signed 16-bit PCM" and save

2. Open mp3 file in Audacity 3.3.0 or 3.3.2
2.1. Select Tracks - Resample (change rate to other)
2.2. Seleсt File - Export - Export as mp3
2.3. Settings don't matter, just click Save

### Expected behavior

After resampling and exporting will create second file with changed sample rate

### Actual behavior

Now after saving the file nothing was changed.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by dozzzzer** [comment]
Not a bug. See the comment above.
