### ISSUE TITLE
Improve the way audacity divides meter marks on the screen

### ISSUE THREAD

**Issue by Charlie-Ramirez-Animation-Studios-de-MX** [audacity/audacity#4692]
### Your idea

Audacity allows you to choose different sizes (Scales) for the Decibel Meter. ranging from -36 to -145dB.
The problem:
While the meter are adjustable in size with a simple drag and drop. **There is a severe problem with the way audacity distributes and divides the scale values according to the (Physical) size of the meter and is largely influenced by the resolution of the monitor used.  and the user has no way to change this behavior of the program other than choosing a lower range meter or forcing higher resolutions by degrading the image**

-The division is done in such an unhelpful way that **audacity usually uses the same division of steps of 3 by 3 (or more) decibels per point for the scales in their smallest size as in their maximum despite the fact that the numbering and the points could fit perfectly on the screen** 

[Examples of this are 1360x768 aka 720p HD ready screen] common in laptops, TV screens, and input line equipment.
Where It's practically impossible to use any meter size greater than -48dB without audacity truncating it to the same division. (see image, taking weight the lack of sense that the same division is used in a minimum size meter and one in full screen).
At the time I posted this problem on the linux audacity forum _[I use it on both windows and linux]_ without any useful answers or ways to improve it.

At the same time, another user also experiences the problem with 2k screens (despite the fact that his monitor is large enough, audacity also continues to truncate the scales in more agressive way jumping to 1 by 1 to 6 by 6)
https://forum.audacityteam.org/t/is-it-possible-to-change-the-scale-on-the-vu-meter/64447

P.S. I see that there is an open survey about the meters, I think it is a good time for this request https://forms.gle/GaZL5kWSNSePPQq49

### Problem to be solved

-dB Meter scale Marks division: scales should not be truncated so drastically if they can still fit on the screen or be user selectable if you want a compact but full form of scaling, or the "clean" but truncated form that has been used up to today [or the number of jumps between marks that must have] the splitting method is impractical, since a meter at its minimum size still uses the same splitting of a full screen even at gigantic resolutions

### Prior art

An example of a 60dB half screen size scale has the same division on a full screen scale (although it could be shown complete in 1 by 1 jumps) on a 1360x768 screen on Windows
![image](https://github.com/audacity/audacity/assets/64709446/4f293af1-ff97-41e0-9fe0-0ff3d42cda75)

### Additional context

Previosly posted on Audacity forum https://forum.audacityteam.org/t/is-it-possible-to-change-the-scale-on-the-vu-meter/64447/3

1360x768 like screens are the second most common desktop resolution, so it is a good test point and consideration for the performance of the meter division
https://gs.statcounter.com/screen-resolution-stats/desktop/worldwide

**Comment by LWinterberg** [comment]
This won't be changed in Audacity 3.x, and for Audacity 4 the meters will be significantly different anyway.
