### ISSUE TITLE
Audacity 3.3.2 causes visual glitches while it starts on Gnome desktop environment

### ISSUE THREAD

**Issue by glaubersm** [audacity/audacity#4696]
### Bug description

Hi
Visual glitches affect the "Volume levels" popup in the Sound module of Gnome DE settings
every time I open Audacity 3.3.2. Visual glitches also affect the icons in Gnome Shell top bar.
This bug was reported in Gnome bug tracker, but apparently it is an Audacity issue.

Bug report in Gnome bug tracker:
https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/2485

I'm using Arch Linux with Gnome 44.1.

### Steps to reproduce

1. install Audacity on a Linux distribution with Gnome desktop environment
2. open Gnome Settings, go to Sound module and click on "Volume levels"
3. open Audacity and observe the icons in the top bar of Gnome Shell and "Volume levels" popup while Audacity starts

### Expected behavior

Audacity should not cause any visual glitch while starting

### Actual behavior

Visual glitches in the Gnome Shell top bar and Sound module of Gnome Settings seen in the attached screen recording.

[sound.webm](https://github.com/audacity/audacity/assets/15967631/4d6d4fa6-8a53-4c99-8827-86bc20a76163)

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

**Comment by LWinterberg** [comment]
It's definitely not just a visual glitch, it probably is some sort of probing of device capabilities. It creates a number of somewhat quiet but still audible clicks on my machine while it does that.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
