### ISSUE TITLE
USB mic not working in Audacity 2.3.3

### ISSUE THREAD

**Issue by CodeFunction** [audacity/audacity#470]
**Describe the bug**
Open Audacity. Cannot get the latest version of Audacity to record from mic using Focusrite Scarlett Solo USB.

I originally thought it was PulseAudio since they've broken audio badly about 5 months or so and are having way too much trouble fixing those problems (as in, so far they managed to break it more).

But, using "$ parecord ..." does contain audio from the mic. Fedora control panel > sound > also shows the mic working once working around the current PulseAudio bugs.

So, currently, I'm not sure what is going on.

I can build from source an older version of Audacity (distro doesn't have older version available) and check it that way. Of if there's some other way to look into this?

**### Edit**: It used to work but I haven't used Audacity since 5-8 months ago maybe. It looks like I would have had Fedora 30 at that time and Audacity 2.3.2-1.

I might as well start work on building from source...

**To Reproduce**
1. Start latest version of Audacity
2. Never any sound coming in from the mic, visual indicator is dead.

**Expected behavior**
Visual indicator should show something when its enabled, recording should get audio from the mic.

**Additional information (please complete the following information):**
 - OS: Fedora 31
 - Version Audacity 2.3.3
 - Focusrite Scarlett Solo USB

**Comment by CodeFunction** [comment]
Indeed, built 2.3.2, clicking monitoring of input shows sound activity and recording also has audio from the mic.

The latest version of Audacity did break the mic here ;-(

**Comment by SteveDaulton** [comment]
Have you tried building Audacity 2.3.3, or 2.4.0 alpha from source?

**Comment by CodeFunction** [comment]
Apparently building and running 2.4.0 alpha also works.

Distro package problem or 2.3.3? I probably don't need to build 2.3.3 if 2.4.0 works.

**Comment by JamesCrook** [comment]
Closing

> Apparently building and running 2.4.0 alpha also works.
> Distro package problem or 2.3.3?
