### ISSUE TITLE
Half muted resulting track when mixing-and-rendering two muted mono tracks

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#4702]
### Bug description

Forum user jaja714 reports: "With all tracks muted, after performing a “Mix and render to new track”, the left channel appears muted (in grey) while the right channel appears not muted (in blue). When listening to the track, both channels are truly muted. Why then, is the right channel appearing as if it is not muted? This did not happen before Audacity 3.2."

See: https://forum.audacityteam.org/t/half-muted-track/75885

### Steps to reproduce

1. Generate Chirp
2. Mute and Pan Left
3. Click in empty space
4. Generate DTMF
5. Mute and Pan Right
6. Ctrl-A
7. Tracks > Mix And Render to New Track

### Expected behavior

The resulting stereo track is not muted.

### Actual behavior

The new stereo track is muted, but the track only appears to be only partially muted.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

![Trackpanel015](https://github.com/audacity/audacity/assets/76828213/7a5916b5-1a16-4e85-ba45-f4ebcbf2ba89)

**Comment by dozzzzer** [comment]
I can confirm this on macOS as well. I believe the expected behavior here would be indeed the visual representation of both channels muted, not just the right one.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with 3.3.2

I confirm this.

### Top track only muted
Also note that if you mute just the top track the after Mix&Render both tracks are muted
![image](https://github.com/audacity/audacity/assets/50205984/b68f57e2-28ff-4676-bfbc-408b3929882f)

###Bottom track only muted
But if you mute just the bottom track the result is more logical
![image](https://github.com/audacity/audacity/assets/50205984/86ecbbae-3c20-41cc-b3cb-04b39dbab29c)

**Comment by petersampsonaudacity** [comment]
Further testing shows that this is a regression on 3.1.3

**Comment by dozzzzer** [comment]
The original issue is no longer reproducible in 3.4.2: currently, when mixing and rendering two muted mono tracks, it creates a fully muted stereo track, which, I believe, is the expected behavior and thus, this issue can be closed. @LWinterberg agree?

**Comment by LWinterberg** [comment]
aye
