### ISSUE TITLE
Envelope tool unstable

### ISSUE THREAD

**Issue by Djard** [audacity/audacity#4703]
### Bug description

In a multi-track project, I generate 1 sec of silence at the start of each track then use the Amplify tool to edit sections of the waveform, after which I add reverb and compression. Occasionally, I use the Envelope tool. At some point during editing with the Amplify tool and/or compressor, the Envelope tool becomes unstable--i.e. if I place a control point at, say, the middle of the track, it will appear at the start of the track.

If envelope points were successfully placed, say in the middle of the track, and I attempt to use the Envelope tool near the end of the track, the control points appear not at the start of the track but just before the previous one.

I tried to replicate the problem but find the issue to be random. Perhaps the problem is triggered after a number of edits by the Amplify tool.

Exporting the problematic track then importing it again fixes the  issue, allowing use of the Envelope tool again, anywhere in the waveform.

### Steps to reproduce

1. Generate some silence at start of a track.
2. Add reverb and compression.
3. Edit sections with Amplify tool and Sliding Stretch.
4. Use Envelope tool in more then one section.

### Expected behavior

The control points should continue to appear where the mouse was clicked.

### Actual behavior

The control points appear at the start of the track, or shortly before a previous section, where an Envelope was created.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

Exporting the problematic track and re-importing it solves the problem, allowing an envelope to be created where previously it became impossible.

**Comment by Djard** [comment]
I apologize for the tardy response. The problem of the Envelope tool's control points being lost after use of the Amplify tool appears to be a random occurrence: I was unable to replicate the issue. Saving the corrupted track then re-importing it restores the ability to place the Envelope control points anywhere in the waveform, without them jumping to an earlier point.

If an envelope is not created earlier in the track and the issue occurs at a later time, the control points jump to the very beginning of the waveform. Next time it happens, I will take a screenshot.

**Comment by dozzzzer** [comment]
I once again failed to reproduce it after many attempts.

**Comment by Djard** [comment]
"Undo" in step 5 above undoes/cancels step 2 ("Cut a few milliseconds of silence near the beginning....).

I can consistently replicate the problem initially described by cutting a section of a waveform and pasting it later in the track. Cutting out a section alone does not cause the control point to jump to an earlier point in the track. But pasting a section into the track no longer permits use of the Envelope tool. Other tracks are not affected... not until something is pasted into them.

**Comment by dozzzzer** [comment]
@Djard it would be of much help if you could share a screen recording of replication of your issue, including all the steps you mentioned above. Thank you.
