### ISSUE TITLE
Opus export crashes Audacity

### ISSUE THREAD

**Issue by mrbumpy409** [audacity/audacity#4709]
### Bug description

When I try to export audio in Opus format, Audacity crashes and leaves a 0 KB .opus file. This happens in two versions of Audacity I have tried on my Linux system: 3.3.1 compiled from source and the 3.3.2 AppImage. If it matters, the codec settings I am using are:

* Bit Rate: **128 kbps**
* Compression: **10**
* Frame Duration: **20 ms**
* Vbr Mode: **On**
* Application: **Audio**
* Cutoff: **disabled**

### Steps to reproduce

1. Open/record some audio.
2. Export Audio
3. Choose "Opus (OggOpus) Files (FFmepeg)" from the dropdown menu. I'm not sure if it's necessary to match my codec settings above.
4. Click Save and dismiss the tagging window, if necessary.

### Expected behavior

Audacity should render the Opus file.

### Actual behavior

Audacity crashes, and a 0 KB .opus file is created.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Linux

### Additional context

OS's tested: KDE neon 5.27 and Xubuntu 22.04, both based on Ubuntu 22.04.
[Audacity_dbgrpt-19251-20230518T090058.zip](https://github.com/audacity/audacity/files/11508602/Audacity_dbgrpt-19251-20230518T090058.zip)

**Comment by petersampsonaudacity** [comment]
Testing on W10 with 3.3.2

@mrbumpy409  This works fine for me on Windows (using your settings)

**Comment by Ryan-Miller-Audacity** [comment]
I can't seem to reproduce this issue within my Xubuntu VM. I see the export process finish without hiccup and also have the excepted .opus file which can be played back via rhythmbox or imported into Audacity without issue. Tested on 3.3.2 AppImage.

**Comment by mrbumpy409** [comment]
How bizarre. I get the crash in VirtualBox using Xubuntu 22.04 and Ubuntu Studio 23.04. I haven't tried other distros yet.

**Comment by mrbumpy409** [comment]
All of my Linux installs include the "ubuntu-restricted-extras" package or distro equivalent (e.g., "kubuntu-restricted-extras"). Could this be a factor, since ffmpeg is involved?

**Comment by mrbumpy409** [comment]
After further testing on my two Linux PCs (desktop and laptop) both running the same version of KDE neon, I can ascertain the following:

* Desktop PC
  * The crash happens in KDE neon, native install.
  * The crash happens in Linux VirtualBox machines (Xubuntu 22.04, Ubuntu Studio 23.04) with KDE neon as the host OS.
  * The crash does not happen in Windows 7 or 10, native install.
  * Converting to Opus with FFmpeg via the SoundKonverter app works fine (Linux).
* Laptop
  * The crash _does not happen_ in KDE neon, native install.
  * The crash _does not happen_ in Linux VirtualBox machines (Xubuntu 22.04) with KDE neon as the host OS.

Could there be something unique to my desktop PC that Audacity doesn't like, perhaps my CPU's lack of AVX instructions? Here are the two systems tested:

### Desktop PC

* **OS:** KDE Neon 5.27 User Edition (Plasma Desktop 5.27.5, KDE Frameworks 5.106.0, Qt 5.15.9)
* **Linux Kernel:** 5.19.0-1024-lowlatency (64-bit)
* **Motherboard:** ASRock X58 Extreme3 (Intel X58 chipset)
* **CPU:** Intel Core i7-990x Gulftown (3.46 GHz hexa-core, Socket 1366) @ 4.15 GHz
* **RAM:** 24GB (6x G.Skill 4GB DDR3 PC3-10666 1333 MHz) @ 1430 MHz
* **Video:** EVGA NVIDIA GeForce GTX 980 Ti SC GAMING ACX 2.0+ w/ 6GB RAM
* **NVIDIA video driver:** 525.105.17
* **Display Server:** X11

### Laptop

* **OS:** KDE Neon 5.27 User Edition (Plasma Desktop 5.27.5, KDE Frameworks 5.106.0, Qt 5.15.9)
* **Linux Kernel:** 5.19.0-1024-lowlatency (64-bit)
* **PC:** HP Pavilion m6-1035dx
* **CPU/GPU:** AMD A10-4600M 2.3 GHz quad-core APU with Trinity \[Radeon HD 7660G\] Graphics (using xorg radeon driver)
* **Display Server:** X11

**Comment by Ryan-Miller-Audacity** [comment]
> All of my Linux installs include the "ubuntu-restricted-extras" package or distro equivalent (e.g., "kubuntu-restricted-extras"). Could this be a factor, since ffmpeg is involved?

I installed the ubuntu-restricted-extras packet into my Xubuntu VM and it did not change the behavior for me. 



> After further testing on my two Linux PCs (desktop and laptop) both running the same version of KDE neon, I can ascertain the following:
> 
> * Desktop PC
>   
>   * The crash happens in KDE neon, native install.
>   * The crash happens in Linux VirtualBox machines (Xubuntu 22.04, Ubuntu Studio 23.04) with KDE neon as the host OS.
>   * The crash does not happen in Windows 7 or 10, native install.
>   * Converting to Opus with FFmpeg via the SoundKonverter app works fine (Linux).
> * Laptop
>   
>   * The crash _does not happen_ in KDE neon, native install.
>   * The crash _does not happen_ in Linux VirtualBox machines (Xubuntu 22.04) with KDE neon as the host OS.
> 
> Could there be something unique to my desktop PC that Audacity doesn't like, perhaps my CPU's lack of AVX instructions? Here are the two systems tested:
> 
> ### Desktop PC
> * **OS:** KDE Neon 5.27 User Edition (Plasma Desktop 5.27.5, KDE Frameworks 5.106.0, Qt 5.15.9)
> * **Linux Kernel:** 5.19.0-1024-lowlatency (64-bit)
> * **Motherboard:** ASRock X58 Extreme3 (Intel X58 chipset)
> * **CPU:** Intel Core i7-990x Gulftown (3.46 GHz hexa-core, Socket 1366) @ 4.15 GHz
> * **RAM:** 24GB (6x G.Skill 4GB DDR3 PC3-10666 1333 MHz) @ 1430 MHz
> * **Video:** EVGA NVIDIA GeForce GTX 980 Ti SC GAMING ACX 2.0+ w/ 6GB RAM
> * **NVIDIA video driver:** 525.105.17
> * **Display Server:** X11
> 
> ### Laptop
> * **OS:** KDE Neon 5.27 User Edition (Plasma Desktop 5.27.5, KDE Frameworks 5.106.0, Qt 5.15.9)
> * **Linux Kernel:** 5.19.0-1024-lowlatency (64-bit)
> * **PC:** HP Pavilion m6-1035dx
> * **CPU/GPU:** AMD A10-4600M 2.3 GHz quad-core APU with Trinity [Radeon HD 7660G] Graphics (using xorg radeon driver)
> * **Display Server:** X11

It certainly seems that there could be an issue to do with your Desktop machine since the crash does not occur on your laptop. What it could be, however, I'm not sure that is a little above my knowledge base. 

Perhaps @crsib could take a look over the details and provide some insight?

**Comment by petersampsonaudacity** [comment]
Testing On W10 with @crsib 's latest branch build for this:  Sgt. Pepper's Lonely Hearts Club Band

The Opus export works properly, with no crash.

**Comment by dozzzzer** [comment]
I can no longer reproduce this one on Ubuntu 22.04
Please confirm @mrbumpy409
