### ISSUE TITLE
Playback cursor not moving on wayland

### ISSUE THREAD

**Issue by rodrigoaguilera** [audacity/audacity#471]
**Description**
The cursor over the wave doesn't appear when playing

1. Record something
2. Play it
3. Click on the wave to see the cursor appear for a few milliseconds

**Expected behavior**
Vertical line cursor moving

**Additional information (please complete the following information):**
 - OS: debian testing
 - Version 2.3.2
 - Window compositor: wayland (this bug does not appear on GNOME under Xorg)

**Additional context**
Reported already in other trackers:
https://forum.audacityteam.org/viewtopic.php?f=48&t=109707
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=950150

**Comment by reesmichael1** [comment]
I've also had this issue (which I think is the same as #459) for a while. I built the current master branch from source, and it seems to be fixed there.

**Comment by DSpeckhals** [comment]
I can reproduce this consistently with the Sway window manager (wlroots-based Wayland compositor) on Arch Linux. However, if I pin the playback, it seems to show the track position normally.

Another difference I see between X11 and Wayland is the refresh rate of the tracking indicator when recording. With X, it's very smooth (maybe every 5 milliseconds); yet with Wayland it lags (it refreshes about every 250 milliseconds).

A workaround I have for now is to run Audacity in XWayland: `GDK_BACKEND=x11 audacity`. To run in native Wayland (which has the track position that doesn't play), I use `GDK_BACKEND=wayland audacity`.

Here's some applicable package information that's in the Audacity package for Arch Linux:
- wxgtk3-3.0.4-2
- audacity-2.3.3-2

**Comment by rodrigoaguilera** [comment]
Closing this in favor of #459
