### ISSUE TITLE
Sync lock errors in stereo tracks

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#4713]
### Bug description

Sync lock sometimes affects only the left channel of a track

### Steps to reproduce

1. New project
2. Add Mono track
3. Generate 30s chirp in it
4. Add Stereo track
5. Generate 30s chirp in it
7. Turn on Sync Lock (Tracks Menu)
8. Drag-select from 10s to 15s in the Mono track only
9. Apply
 - Change Tempo, to 110%, with High Quality stretching off, OR 
 - The same but with High Quality stetching on, OR
 - Sliding stretch with defaults (0 and 100%), OR
 - Sliding stretch with initial 100% and final 100%, OR
 - PaulStretch

(Note, ChangeSpeed has no problem)

### Expected behavior

After step 8, both channels of the stereo track are shortened to maintain sync with the stereo track

### Actual behavior

Either no change in the stereo track, or (worse!) only the left channel shortens

Note:  you can also repeat all of the above with settings that lengthen the selection rather than shortening it.  Expect result would be insertion of silence in both channels.  But observed is insertion in only the left channel, or in neither.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

### Additional context

Sync lock affects many other things.  Are there similar errors in Sync Lock involving other features?  Maybe for non-application of sync lock at all, but I believe not for the other problem, because of the examination of code that led me to file this.

The problem ,of applying to one channel only, exists only where there is iteration over "leader" tracks, type-switching for Wave tracks, but falling-through to default sync lock adjustment when the track is not selected.

**Comment by petersampsonaudacity** [comment]
> Sync lock affects many other things. Are there similar errors in Sync Lock involving other features?

Hi @Paul-Licameli  -  IIRC Paulstretch (different Paul!) also does not play nicely with sync-lock.

**Comment by Paul-Licameli** [comment]
> > Sync lock affects many other things. Are there similar errors in Sync Lock involving other features?
> 
> Hi @Paul-Licameli - IIRC Paulstretch (different Paul!) also does not play nicely with sync-lock.

True, it's a time-stretcher that contains no code to invoke sync lock adjustment.  I can add that to the description.

But what concerns me more right now is sync lock done inconsistently between channels -- that's worse than not doing it at all.

**Comment by dozzzzer** [comment]
Tested

**Comment by dozzzzer** [comment]
Reopening; the issue can be reproduced in PR #4650
