### ISSUE TITLE
Redefine how Paste replicates the last copied wave track

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#4714]
### Your idea

Design should respecify the case of pasting a smaller number of wave tracks into a larger number of tracks.

### Problem to be solved

Audacity was written to replicate "the last" (maybe only) copied wave track when pasting into a greater number of selected tracks.

Certain existing edge case behavior of Paste may copy data from a stereo track right channel (only) into mono or stereo tracks, or paste a mono track into stereo tracks.

This behavior needs to be precisely re-specified for the present project to restructure wave clips as "wide."

Update: The first "yes" in this comment implies the answer to the question this issue raises https://github.com/audacity/audacity/issues/4720#issuecomment-1560194675

### Additional context

Observe present behavior of Audacity:

Case A:

1. Select (whole time range of) a stereo track with distinct left and right channel data
2. Copy (or cut)
3. Open new project
4. Add three empty mono tracks, then one stereo track; select all (Ctrl+A); paste
5. Observe error "Copying stereo audio into a mono track is not allowed" -- as it should be
6. Click drop-down of first track and "Make Stereo Track"; select all; paste
7. Observe pasting into the first stereo track, but also replication of the right channel into the mono track and each channel of the second stereo track (probably not wanted)

What would be correct?  I suggest:  don't paste anything into the mono, but replicate stereo into stereo

Case B:
1. Select (whole range of) a mono track
2.-4. as in case A
5. Observe the mono channel replicated in all five mono and stereo channels
6. Acceptable?  Or, should mono paste only into mono?

**Comment by Paul-Licameli** [comment]
Assigning myself the implementation work, a necessary edge case fix in all the restructuring now happening.  Who wants to be assigned the design specification? @Tantacrul @LWinterberg @DilsonsPickles

**Comment by Tantacrul** [comment]
I think @LWinterberg and @DilsonsPickles will tackle the question and we'll discuss it in our next meeting and then make a proposal to the team. Happy to hear suggestions too, obviously.

**Comment by Ryan-Miller-Audacity** [comment]
Tested. This will wait for merge until the issue descrbied in the PR is discussed. Details can be found here: https://github.com/audacity/audacity/pull/4730#issuecomment-1579008868
