### ISSUE TITLE
Specify whether pasting mono into stereo is permitted

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#4718]
### Your idea

Pasting mono track data into a stereo track is now permitted, replicating it in both channels.

Do we wish to conserve this behavior?

See also #4714

### Problem to be solved

The legacy behavior of pasting from a mono wave track into another should be reexamined and respecified so that wide clip restructuring can proceed.

### Additional context

Present Audacity behavior:

1. Cut or copy from at least one wave track (possibly other tracks of other types too)
2. Paste into an equal number other selected tracks (maybe of anothe project), without correspondence of number of channels

In case a stereo track of the copy corresponds to a mono track in the attempted paste -- the operation fails with an error message, probably correctly so.

In case a mono track of the copy corresponds to a stereo track -- paste proceeds, replicating the mono data in each stereo track.

Is this legacy behavior to be preserved?  Or would it be preferable to disallow this too?

**Comment by Ryan-Miller-Audacity** [comment]
Tested. This will wait for merge until the issue descrbied in the PR is discussed. Details can be found here: https://github.com/audacity/audacity/pull/4730#issuecomment-1579008868
