### ISSUE TITLE
Applying a macro to several hundred files yields "Cannot open this type of file"

### ISSUE THREAD

**Issue by user135711** [audacity/audacity#472]
**Describe the bug**
Applying a macro which first normalizes and then exports as mp3 to about 600 mp4's yields the cryptic message: "x is an Advanced audio coding file. Audacity cannot open this type of file. You need to convert it to a supported audio format, such as WAV or AIFF." Reducing the number of files to about 100 the macro runs fine. A more meaningful error such as "too many files" should be given.
**To Reproduce**
See description
**Expected behavior**
The macro runs
**Screenshots**
<img width="639" alt="aud err" src="https://user-images.githubusercontent.com/31940582/77594799-1c3f3480-6ebd-11ea-8a40-177ae7fce657.png">

**Additional information (please complete the following information):**
 - OS: win 10 
 - Version 2.3.0

**Comment by Pokechu22** [comment]
Does that file process successfully if you use your macro on *only* that file?  I see some garbled-looking things in the file name, so perhaps it is an issue with the number of files you're opening, but it also might be something with that file specifically.

From my research, advanced audio coding (AAC) is an audio codec that's often used with MP4 files.  It looks like audacity uses that message if it fails to find a plugin that can import the file:

https://github.com/audacity/audacity/blob/c96fd0d2be8ec3a5d4ab84ec76ffffe5e9b0579d/src/import/Import.cpp#L725-L731

(the message was changed (731c056e7ec4f94499fd4a35a65ef4a2a337c6d8) in Audacity 2.3.2 to mention that FFMpeg can allow importing them, but I don't know if anything changed with the import logic in that time)

**Comment by user135711** [comment]
Yes, it imports fine with only that file. The garbled looking things are mandarin symbols that did not interfere with smaller numbers of files. I'm currently investigating how many is too many. I will run out of files or have an approximate number in an hour.

**Comment by user135711** [comment]
whelp, as many as 266 process fine, but 600 definitely not. I tried about 5 times.

**Comment by Pokechu22** [comment]
Can you check Audacity 2.3.3 as well?  It's probably still an issue, but it'd be good to know for sure.

**Comment by user135711** [comment]
yes, I definitely still get the error in 2.3.3. I also tried remaking the macro. same

**Comment by user135711** [comment]
As many as 510 will run, 650 and 651 no, I can keep binary searching for the limit but I can't at the moment.

**Comment by SteveDaulton** [comment]
This is a known limitation that is mentioned in the manual (https://alphamanual.audacityteam.org/man/Apply_Macro):
"It is recommended not to process more than 500 files at a time. "

**Comment by user135711** [comment]
Well it should return a sensible error then whenever 500 or more are requested.

**Comment by JamesCrook** [comment]
Marking this as a bug, as Audacity could/should tell you what is going on.

**Comment by petersampsonaudacity** [comment]
Maybe Audacity ought the enforce the 500 files maximum for processing with a Macro as we recommend in the Manual - and error out if tha number is exceeded.

**Comment by petersampsonaudacity** [comment]
@user135711 do you still get this issue with the latest Audacity release 3.0.2 ?

**Comment by petersampsonaudacity** [comment]
Logged on our Bugzilla bugtracker as P2 Bug #2785
https://bugzilla.audacityteam.org/show_bug.cgi?id=2785

Accordingly I shall close the GitHub Issue in favour of the tracked Bugzilla entry

**Comment by Leterel** [comment]
Hello,

at the moment I get the same error when I am approximately over 3,000 files.
3,000 files work. Everything beyond that is unknown territory.

**Comment by petersampsonaudacity** [comment]
It quite clearly states in the Manual in a highlighted yellow tip div:

>It is recommended not to process more than **500** files at a time.

It has been a well known oddity/restriction for a long time

**Comment by petersampsonaudacity** [comment]
To make  this recommendation clearer I have updated the alpha manual fir the upcoming 3.4.0 to have this tip div at the top of each of the three macros pages in the manual in their intro divs

>{{tip|When applying a macro to files it is recommended not to process more than '''500''' files at a time. }}

See:
a) https://alphamanual.audacityteam.org/man/Macros
b) https://alphamanual.audacityteam.org/man/Manage_Macros
c) https://alphamanual.audacityteam.org/man/Apply_Macro

**Comment by petersampsonaudacity** [comment]
> 'm a simple end-user, but why is it 500 or 3,000?
> Why is it, not 99, 999, or 9,999 then?

@Leterel  -  _A long time ago in a galaxy far, far away...._ - it was  simple "wet finger in the air" job.

We (the old Audacity Team that is) knew that if failed with large numbers of files so we settled on a conservatively low number that we knew always seemed to work.

So not  a lot of science in that ...

**Comment by Leterel** [comment]
Is it OK if I suggest this for a future update?
I don't care if it gets ignored.
I just feel like this might be relevant for more people.
Because let's say SWIM is ripping the SFX samples
from a modern game, then you're easily reaching 100k, or more, numbers.

**Comment by dozzzzer** [comment]
The original issue doesn't seem to be the case anymore.
3.4.2 runs normalize & export macro on a 600 mp4 files batch just fine.

<img width="500" alt="image" src="https://github.com/audacity/audacity/assets/70063970/9cf5588a-2ad9-4a42-900b-6f0cff98e3da">

**Comment by chrisjphelps** [comment]
Still breaks if you do lots of files. Better to be honest and say, there is a known bug where large number of files fails.
Recommended implies it might be fine with more.
