### ISSUE TITLE
Short and simple specification of how copy-paste "fits" the clipboard into the selected tracks

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#4720]
### Your idea

When some tracks have been cut or copied, and are then pasted (not pasting label or title text), and the set of selected tracks is not empty, succeed if and only if there is a "good fit" of ALL copied tracks into the selected tracks.

If successful, and sync lock is enabled, then in all cases, any track sync-locked with a changed track must be adjusted.

If not successful, fail with just one error message "Pasting one type of track into another is not allowed."

And this is a bit of pseudocode to define "Good fit" -- in short, it means, find a sub-sequence of selected tracks with types like those in the clipboard, or else fail.

A special rule will be applied:  when exactly one track is selected, consider `selected tracks` to include that track and all following ones. 

```
Correspondence := empty
ToCopy := clipboard
ToPaste := selected tracks
while ToCopy is not empty
   while ToPaste is not empty AND front(ToPaste) does not "fit into" front(ToCopy)
      pop_front ToPaste
   if ToPaste is empty
      fail
   push_back Correspondence, { front(ToCopy), front(ToPaste) }
   pop_front ToCopy
   pop_front ToPaste
```
And “fits into” means “of the same type" recognizing four distinct types (Mono, Stereo, Label, MIDI)

Or, it might instead be an asymmetrical relation, allowing mono to “fit into” stereo, replicating the sample data.

### Problem to be solved

Resolution of this question is needed to unblock refactoring for wide clips.  I want to refactor the present confused paste logic into something sensible before I go on.

### Prior art

As paste behaves now, the major decision tree is:

1. If there is a focused label or clip name, do pasting of text, not track data.
2. Otherwise if there is no selection, then paste all copied tracks into new tracks.
3. Otherwise... it's hard to describe all the cases simply.  The sequence of copied tracks may have types not corresponding to selected tracks, and some of those may be skipped. Sometimes paste fails with a message that "Pasting one type of track into another is not allowed." or that "Copying stereo audio into a mono track is not allowed."  Sometimes a copied track is multiply pasted while other copied tracks are not pasted at all!  (Examples will be added below)

See related issues #4714, #4718; also there may be sync-lock adjustment of unselected tracks.  

### Additional context

Documenting some strange cases in present behavior:

Case 1:
Two wave tracks, then a label track with one label "A" at about 0.5s.  Sync-lock on.  Press "Select" of the second track, than Ctrl+C.  Press Select of the first track, then left arrow key, then Ctrl+V.
Result:  Paste into the first track, and sync-lock adjustment of the label track, but the second track fails to make sync-lock adjustment.

Case 2:
As in Case 1, plus a duplicated label track with label changed to "B".  Select tracks A and B and copy.  Select one or two wave tracks and no others, and paste. 
Result: Error "Pasting one type of track into another is not allowed."

Case 3:  As in Case 2, but Ctrl+A, left arrow before paste.
Result:  "A" pasted into both label tracks but "B" not pasted at all (weird!) and the wave tracks do not adjust for sync lock.

Case 4: Undo from Case 3, Ctrl+A, Ctrl+C to copy all; left arrow, and ctrl+Click on "Select" of track "B" to deselect just that one.  Paste.
Result:  Pasting into the wave tracks and "A", and sync lock adjustment of "B".  But the copy of "B" in the clipboard is not re-pasted anywhere.  (Shouldn't the complete clipboard always be pasted somewhere?  Should a new label track be made in this case?)

**Comment by petersampsonaudacity** [comment]
@Paul - I have no persona; skin in this particular game ...

But it looks like it has been that way since 1.3.2 with the mono selection being copied to both left and right channels of the stero track - so we've had this behavior for a very long time.

In earlier versions the mono selection was copied to the left channel with flat-line silence added in the right channel.

**Comment by Paul-Licameli** [comment]
@petersampsonaudacity the very old legacy behavior may never have been well documented.  The code as it is now is rather confusing.  What was the original intent?  I think that was never well articulated by anybody to cover all the cases.

I'm not satisfied with the issue I just wrote.  I will update it.  Wait for it...

**Comment by petersampsonaudacity** [comment]
> the very old legacy behavior may never have been well documented.

@Paul-Licameli I don't think it was documented at all - it's a bit of an Easter-egg  ;-)

**Comment by LWinterberg** [comment]
Okay, so, how about this: 

1. If mono is pasted into stereo, the audio content is quietly duplicated
2. If stereo is pasted into mono, we ask if we should mixdown:  
    > Your stereo data will be mixed down to mono when pasting here.  
    >  [x] don't ask again &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;       [OK] [Cancel]
3. If a number of tracks has been copied and an explicit and matching selection has been made for pasting, paste in the selection. Example: Copying from tracks 1+2 and selecting tracks 3+5 would paste into 3+5
4. If a number of tracks has been copied, and only one track is selected for pasting, paste into the following consecutive tracks if there is room. Example: Copying from tracks 1+2 and then selecting only track 3 would paste into 3+4
5. If there is no room in the following consecutive tracks (eg because it's a different type of track, or a clip is present at the paste location), create new tracks underneath the selected track until the entire paste fits.
6. If an insufficient and more complex selection has been made for pasting, show an error. Example: Copying from 1+2+3 and attempting to paste into 4+8 would error out. 
    > You are attempting to paste data from `n` audio tracks, `m` label tracks and `o` note tracks into `n'` audio tracks, `m'` label tracks and `o'` note tracks, which mismatches. Please select a matching number of tracks before pasting. [OK]  

Did I miss anything?

**Comment by Paul-Licameli** [comment]
1., 2. So we can fit a mono track into stereo by replication, and oppositely with mix-down.  There are old comments in paste about the mix down idea but it was never done yet.

I might add the mix down as a later enhancement after I get the important refactoring done.

**Comment by Paul-Licameli** [comment]
3. If I understand you are assuming sameness of types of corresponding tracks, then my proposal covers that special case, in which none of the selected tracks need to be skipped.

**Comment by Paul-Licameli** [comment]
4., 5., 6. Why these complications?

**Comment by Paul-Licameli** [comment]
Finally do you have an opinion about replicating the last wave track in excess selected tracks?

**Comment by LWinterberg** [comment]
The goal here is to ensure two things: 

* All content that is copied gets pasted to where it _probably_ was intended to go
* Tracks and paste stay coherent

Point 3 is the user explicitly requesting something from us; we can be pretty sure they have something very specific in mind. Point 6 covers the case where they have something specific in mind but mess up; I can't make a good assumption here over where they likely wanted to have things pasted to, and silently just not pasting the last track is unexpected.

Point 4 and 5 is for a more vague idea of "I want my paste to *start* here", maybe similar to pasting an image onto a canvas. We know the start track and position and can make some reasonable assumption what the user was intending to do. Keeping the paste in a group together is the most likely expected result here, and if not, you at least know where all the stuff you pasted went as it sticks together. 5 specifically is about avoiding a paste getting interleaved with the existing content (like this: 
![image](https://github.com/audacity/audacity/assets/87814144/8e1f1598-2b2a-4c9a-9cde-feefb3647746)
), which are annoying to resolve by hand currently, though that may be revisited once we have multi-clip selection and overlapping clips. 

> Finally do you have an opinion about replicating the last wave track in excess selected tracks?

Starting from the top. If you run out of tracks before running out of targets, the remaining ones at the bottom can stay empty.

**Comment by Paul-Licameli** [comment]
Is it agreed at least, that the existing cases of present behavior, mentioned at top, are undesirable?  Excepting no. 2 perhaps

**Comment by Paul-Licameli** [comment]
> The goal here is to ensure two things:
> 
> * All content that is copied gets pasted to where it _probably_ was intended to go

Can I interpret this as:  every copied track is pasted exactly once, or else paste fails.  (No copied track is pasted multiply.  No copied track is left un-pasted somewhere.)

> * Tracks and paste stay coherent

What does "coherent" mean?

> 
> Point 3 is the user explicitly requesting something from us; we can be pretty sure they have something very specific in mind. Point 6 covers the case where they have something specific in mind but mess up; I can't make a good assumption here over where they likely wanted to have things pasted to, and silently just not pasting the last track is unexpected.

No argument I think about what case 3 does in successful cases.

You imply some complicated logic to make the error message that explains the failure of case 6.  For immediate purposes of unblocking the refactoring, I would rather keep one simple error message as now.

But do you understand my proposal:  possibly skip over some selected tracks of wrong types, if there are enough later selected tracks of the right types to accept them all.

For example, I might copy two wave tracks, then another project has two wave tracks but alternating with label tracks.  In the other I just select all with an easy Ctrl+A.  I expect paste just works without complaint.  This needs the skipping of some selected tracks to find the correspondence.

If you agree with that, then maybe your error message for case 6 would apply in fewer cases.

> 
> Point 4 and 5 is for a more vague idea of "I want my paste to _start_ here", maybe similar to pasting an image onto a canvas. 

Point 4 needs more precision.  The tracks immediately following the sole selected one might be of wrong types to receive the pasted track. What then?

Is this a possible precise statement for this case:  When exactly one track is selected, treat as if the range of that and all later tracks is selected, and then apply the "fitting" algorithm (my pseudocode), reducing this cases like 1 or 6.

But then if you want as in 5 to insert new tracks instead, sometimes, again I'm pressing for more precision.

So maybe I could say:

Treat the single track and all later as the selected range.  Follow the pseudocode until "fail".  If you reach "fail", keep the partial correspondence so far determined, and don't fail the paste.  Instead, insert tracks as needed after the last existing track in the correspondence.

> We know the start track and position and can make some reasonable assumption what the user was intending to do. Keeping the paste in a group together is the most likely expected result here,

Are you sure that's always true?  What about my example with wave and label tracks?  Where I think it is reasonable to paste what were consecutive tracks into non-consecutive ones separated by labels.

> and if not, you at least know where all the stuff you pasted went as it sticks together. 5 specifically is about avoiding a paste getting interleaved with the existing content (like this: ![image](https://user-images.githubusercontent.com/87814144/240268640-8e1f1598-2b2a-4c9a-9cde-feefb3647746.png) ),

I don't understand what you mean to illustrate with an image of just one track.  My entire issue is about pasting material covering one unbroken interval of time.  The debate here is about the discrete "vertical" axis of multiple tracks.

> which are annoying to resolve by hand currently, though that may be revisited once we have multi-clip selection and overlapping clips.
> 
> > Finally do you have an opinion about replicating the last wave track in excess selected tracks?
> 
> Starting from the top. If you run out of tracks before running out of targets, the remaining ones at the bottom can stay empty, but keeping same-type tracks.

"Empty?"  Rather you mean "unchanged?"  Pasting into a wave track may replace content of the selected time interval, but also shift in time whatever is right of that interval.

**Comment by LWinterberg** [comment]
> Can I interpret this as: every copied track is pasted exactly once, or else paste fails

yes

> But do you understand my proposal: possibly skip over some selected tracks of wrong types, if there are enough later selected tracks of the right types to accept them all.

> For example, I might copy two wave tracks, then another project has two wave tracks but alternating with label tracks. In the other I just select all with an easy Ctrl+A. I expect paste just works without complaint. This needs the skipping of some selected tracks to find the correspondence.

yes

> Point 4 needs more precision. The tracks immediately following the sole selected one might be of wrong types to receive the pasted track. What then?

> Is this a possible precise statement for this case: When exactly one track is selected, treat as if the range of that and all later tracks is selected, and then apply the "fitting" algorithm (my pseudocode), reducing this cases like 1 or 6.

While it's not exactly what I had in mind, it's suitable nonetheless. Go ahead with that interpretation, and discard point 5. 

>> We know the start track and position and can make some reasonable assumption what the user was intending to do. Keeping the paste in a group together is the most likely expected result here,

> Are you sure that's always true? What about my example with wave and label tracks? Where I think it is reasonable to paste what were consecutive tracks into non-consecutive ones separated by labels.

An assumption is never going to be always true. A single label track inbetween two audio tracks likely may be the intended effect, but if there is tons of clip-populated tracks following the single paste, you may have one part of your track end up in track 3 and the other in track 12, which may not be in view anymore. This is what I wanted to avoid here, but which has a solution coming down the road in overlapping clips. So whatever we choose here is going to be imperfect, but acceptable for the time being. 

> I don't understand what you mean to illustrate with an image of just one track. My entire issue is about pasting material covering one unbroken interval of time. The debate here is about the discrete "vertical" axis of multiple tracks.

I wasn't sure if you wanted to do "does it fit" checks based on clips or on the entire copied selection duration, the example I've shown can only be a result of pasting if you were doing fit-checks based on clip positions and durations. 

It appears you are taking the entire copied duration as your basis, which avoids this issue anyway.

> "Empty?" Rather you mean "unchanged?"

Unchanged is correct.

**Comment by Paul-Licameli** [comment]
I think we have reached agreement, and there is now a linked pull request implementing the ideas, except that mix-down of stereo into mono tracks is not implemented.

Note that I replaced the two possible error messages for failed paste with new message, which you may want to review and amend, @LWinterberg 

"There are not enough tracks after the selected track for the copied tracks." in the special case of one selected track

"There are not enough selected tracks for the copied tracks." in the general case

**Comment by Ryan-Miller-Audacity** [comment]
Tested. This will wait for merge until the issue descrbied in the PR is discussed. Details can be found here: https://github.com/audacity/audacity/pull/4730#issuecomment-1579008868
