### ISSUE TITLE
Hovering over "Effects" button doesn't feature hotkey tooltips

### ISSUE THREAD

**Issue by Ryan-Miller-Audacity** [audacity/audacity#4726]
### Bug description

As a helpful tool to users we include the name and hotkey information in a tooltip as well as in the bottom of the Audacity window pane. You can see this by hovering over items such as the "record", "mute", and "solo" buttons among others. 

![hotkey-vs-no-hotkey](https://github.com/audacity/audacity/assets/88568755/2ca289a5-c879-4784-8a03-43e90544f951)

We should add the hotkey information to these locations for ease of use. "e" is currently the hotkey to display/hide the Real-time FX panel.

### Steps to reproduce

1. Open Audacity and create a track
2. Hover over some of the examples listed above (record, mute, or solo buttons etc.)
3. Note the tooltip that includes the hotkey information for that item as well as the text in the bottom of the window pane
4. Hover over the "effects" button 
5. Note the name is displayed on hover within the tooltip and the bottom of the window pane but no hotkey information

### Expected behavior

Hotkey information should be included within tooltips and bottom window pane for "effects" button.

### Actual behavior

Hotkey information is not included within tooltips and bottom window pane for "effects" button.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

**Comment by sksDonni** [comment]
@dozzzzer , @Ryan-Miller-Audacity  would like to take up this issue

**Comment by sksDonni** [comment]
@dozzzzer, @Ryan-Miller-Audacity, I tried debugging the code to figure out the issue, It appears that we may not have keybindings for the effects button, as its not mentioned in the [track menu file where shortcuts to other buttons are specified](https://github.com/audacity/audacity/blob/master/src/menus/TrackMenus.cpp)

**Comment by dozzzzer** [comment]
> @dozzzzer , @Ryan-Miller-Audacity would like to take up this issue

Please feel free to do so! Simply assign it to yourself and, once ready, prepare a PR.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
