### ISSUE TITLE
CFG file with settings for all Users

### ISSUE THREAD

**Issue by GNDMNL** [audacity/audacity#4728]
### Your idea

for every user a configuration file is created and it can be found in the user profile. so far so good. but so every user has to make it's personal settings. if possible i want a default configuration file with default settings which is used as default settings configuration when a user starts the program for the first time. after that every user can make his/her own changes. of the default settings in the default configuration file too.

### Problem to be solved

i want to create a configuration file for all users with default settings (ex. the splashscreen at the first start should be disabled, the default update check disabled, etc.). this file should be copied from the installation path of audacity into the user profile folder. if a user changes a default setting (ex. enable default update check) then so be it, but it doesn't affect other users in the computer.

**Comment by LWinterberg** [comment]
A comprehensive enterprise solution (with things like group policies, MSI installers and such) may come in the far future, but until then, this won't get changed

**Comment by LWinterberg** [comment]
NB, if you self-compile Audacity, you can turn off some features at that stage for your users, too. Update checking and error reporting is disabled by default, for example.
