### ISSUE TITLE
"Set Loop to Selection" should also enable looping if it is not currently enabled

### ISSUE THREAD

**Issue by Ryan-Miller-Audacity** [audacity/audacity#4731]
### Bug description

When you have made a selection within a track you can right click within the horizontal ruler and choose "Set loop to selection" in order to set the looping region to your selection within the track. 

Once you select this option; however, looping is not enabled as part of this action. It would be a nice QOL feature to enable looping as part of this action. Generally speaking, if a user is going to use this option their next intention is going to be to playback the looped selection. This would save them the additional hassle of playing their track without realizing that looping is not enabled or otherwise having to turn the option on manually.

https://github.com/audacity/audacity/assets/88568755/2c3a0dbf-479c-426b-bcef-596e85b21fb9

### Steps to reproduce

1. Open Audacity and grab some sound
2. Make a selection within a track
3. Right click in the horizontal ruler
4. Select the "Set loop to Selection" option in the context menu
5. Note that the looping region is properly set to the selection, but looping is not enabled.

### Expected behavior

It would be convenient for the Set loop to selection option to enable looping for you (if it's disabled) when selected as the next natural step after this action is to playback that (now looped) section. 

### Actual behavior

Using the set loop to selection option properly sets the looping region to the selection, but doesn't enable looping; so, if I got to play my (now looped) selection, looping will not initially work because it is disabled and I will have to go enable looping manually.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

**Comment by dozzzzer** [comment]
Tested
