### ISSUE TITLE
When dragging the sidebar past its minimum width, it fully collapses

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4733]
### Bug description

https://github.com/audacity/audacity/assets/70063970/439ff4ce-2092-4641-9b0f-c76650e9b1c1

### Steps to reproduce

1. Have some audio
2. Open the sidebar either by clicking **Effects** or by pressing **E**
3. Hover over the edge of the sidebar
4. Start dragging all the way until the sidebar reaches its max width
5. Without releasing the LMB, keep dragging past its minimum width all the way to the left edge of the window
6. Release the LMB

### Expected behavior

The sidebar stays at its minimum width

### Actual behavior

The sidebar collapses

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows, macOS

**Comment by petersampsonaudacity** [comment]
I'd observed this previously while testing the effects stack.

I always assumed this was a designed-in "feature" rather than a bug.

**Comment by LWinterberg** [comment]
I don't think we designed for this, but it working like this is great IMHO :)
