### ISSUE TITLE
Create new tracks on paste instead of throwing a "can't paste" error

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#4734]
In playing around with this build, it felt sensible overall, though the error messages ended up more annoying than I had anticipated. Can we make it so that in cases where the error pops up currently, it instead creates a new track? In the case of multiple selected tracks, any "overflowing" pasted contents would go immediately after the last selected track, in case of a single selected track, it would go at the end of the project.

_Originally posted by @LWinterberg in https://github.com/audacity/audacity/issues/4730#issuecomment-1564128905_

**Comment by Paul-Licameli** [comment]
So again, special treatment of the case of selection of a single track.

This would leave the rewritten paste with no need for any error messages about track type mismatches.  It will always succeed one or another way with extra tracks as needed.

**Comment by LWinterberg** [comment]
this has a spec in 4
