### ISSUE TITLE
Plus and minus buttons in the Time Signature toolbar are blank 

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4736]
### Steps to reproduce

1. Build from master branch
2. Launch Audacity
3. Enable the Time Signature toolbar
4. Observe

### Expected behavior

Up/Down (Plus/Minus) buttons have +/- signs on them

### Actual behavior

The buttons are blank

![image](https://github.com/audacity/audacity/assets/70063970/c5bcea20-cb13-4331-83a5-1af768b0eea8)

### Audacity Version

current master / alpha / nightly build

### Operating system

Ubuntu 22.04

**Comment by petersampsonaudacity** [comment]
Testing on W10 with 3.3.2 and latest 3.4.0 alpha

These look fine on Windows:
![image](https://github.com/audacity/audacity/assets/50205984/832e587d-576a-46a9-bf7f-3612523b194e)
