### ISSUE TITLE
Audacity hangs indefinitely with pipewire 1:0.3.71 if another application is also using sound.

### ISSUE THREAD

**Issue by evertvorster** [audacity/audacity#4740]
### Bug description

There is a bug report in the pipewire bug tracker, since a verison change in pipewire brought on this bug. However, it's jut Audacity hanging with this version update, and we can't hold back the version of pipewire forever, so maybe it's worth it for someone that knows the Audacity code to take a look at it as well. 

https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3246#note_1929407

### Steps to reproduce

1. Run an application that uses pipewire, in my case Kdenlive.
2. Launch Audacity

### Expected behavior

Audacity to produce a UI

### Actual behavior

Audacity hangs, not starting up. Once the application that was using pipewire is closed down, Audacity starts up. 

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

This is not an issue with pipewire 1:0.3.70, but it became apparent with 1:0.3.71.

In my case, I have the audio driver set to ALSA.

**Comment by Ryan-Miller-Audacity** [comment]
Testing this in my Fedora VM with Pipewire 1:0.3.71 and 1:0.3.67 I found that with pipewire 0.3.71 installed I was unable to open Audacity (it would hang and then upon a retry give the error reporter window). I found that with pipewire 0.3.67 (the previous version that was installed already in my VM) Audacity launched and ran without issue. 

Here is a link to the crash report in Sentry: https://sentry.audacityteam.org/share/issue/ae70d5a166a44a1fbaaf536c3ec6ca03/

**Comment by dozzzzer** [comment]
While we're using PortAudio, fixing this problem isn't achievable.
