### ISSUE TITLE
Audio Sharing: Cancelling the upload midway will result in uploading audio anyway

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4747]
### Bug description

The issue occurs only on Windows: while uploading a file and clicking the Cancel button, the upload process will finish anyway, and even if going back to Audacity and confirming, the uploaded file will not get retracted.

### Steps to reproduce

1. Download and launch the build [from here](https://github.com/audacity/audacity/actions/runs/5113577455?pr=4743)
2. Have some audio
3. Click **Share Audio** button
4. Click **Continue**
5. While upload is in progress, click **Cancel** and do not confirm
6. Observe: the upload progress reaches the end and the just uploaded file opens in the browser
7. Go back to Audacity and confirm cancel operation by clicking **Yes**
8. Go back to the browser and check if the file still exists

### Expected behavior

At step 5, clicking **Cancel** should pause upload progress until either Yes or No button is clicked.

### Actual behavior

The upload process isn't terminated despite clicking **Cancel** and finishes successfully:

https://github.com/audacity/audacity/assets/70063970/2db5cf9a-3ac9-4482-9733-59d3bebf714e

### Audacity Version

other

### Operating system

Windows

**Comment by crsib** [comment]
I'm not sure why and even if this is possible before we implement resumable uploads
