### ISSUE TITLE
Audacity Crashes when Selecting a new Portion of Track and Previewing an Effect

### ISSUE THREAD

**Issue by protodrew** [audacity/audacity#4753]
### Steps to reproduce

1. select a portion of a track and open the graphic EQ plugin (may happen with other plugins)
2. select a different potion and select preview

### Expected behavior

preview using new selection should play

### Actual behavior

audacity crashes

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

using wayland if that is relevant

**Comment by Ryan-Miller-Audacity** [comment]
Testing on both Windows 10 and Fedora in my Linux VM in Audacity 3.3.2, I am experiencing the same as @petersampsonaudacity mentions above. Once the graphic EQ plugin is opened from the destructive effects menu (it is not currently available in the Realtime FX) you can no longer interact with the Audacity window behind the plugin window.

I tested just utilizing the graphic eq plugin, closing, selection different range, using graphic eq etc., but never experienced any adverse sideffects (crashes). 

@protodrew Is there any additional context you could provide to assist us in replicating this issue? Perhaps a video of you reproducing it or more specific reproduction steps? Seems like there may be something missing here.
