### ISSUE TITLE
“Split Stereo” and “Split Stereo to Mono” now indistinguishable 

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#4756]
### Steps to reproduce

1. Generate a stereo track
2. Choose “Split Stereo Track” from track’s drop down 
3. Observe pan sliders
4. Undo
5. Choose “split stere to mono”
6. Observe pan sliders

### Expected behavior

Difference

### Actual behavior

Since only May 24 in alpha builds — no difference, both give you center panned results

(my fault for this regression)

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

### Additional context

So let’s decide:  the distinction mattered, and I should restore it, or it didn’t, and instead we just have one command

**Comment by LWinterberg** [comment]
initial community feedback indicates that both are needed too, so go ahead

**Comment by saintmatthieu** [comment]
I imagined that the implementation of splitting a stereo track would strive to preserve left-right balance, but in current live (and what Paul's PR currently intends to restore) it is not the case, left/right panning of a stereo track gets lost. For the use case you described, @LWinterberg, where one wants to make corrections to either channel separately, that'd be a nuisance.

If it were trivial, I'd suggest using this PR to change to this "lossless" behaviour, but there'd be the need to map pan values to gain values back and forth, which doesn't exist in the code yet AFAICS. Shouldn't be too hard to implement either, though.
