### ISSUE TITLE
Plugin scanning: it takes too long before a plugin can be automatically skipped

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4758]
### Bug description

Currently, when scanning plugins either during start-up or when initialized manually, it takes about 2.5 min before a plugin that for some reason causes the progress to hang can be skipped.

### Steps to reproduce

1. Have some VSTi2/VSTi3 plugins installed in your system
2. Initialize plugin scanning either manually (e.g. Effect > Plugin Manager > Rescan) or by launching Audacity with clean pluginregistry.cfg
3. See the progress

### Expected behavior

After 30 seconds of checking the plugin, the plugin gets automatically skipped and the process should move on to the next one

### Actual behavior

The plugin is being scanned for 2m 30s before it moves on to the next one

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows 10

### Additional context

This can be reliably reproduced using Arturia's VSTi, such as Pigments, V-Collection etc.

**Comment by crsib** [comment]
I wasn't aware that we do autoskip at all :-)

**Comment by LWinterberg** [comment]
Relevant: 
* #4157

**Comment by dozzzzer** [comment]
The issue can no longer be reproduced.
