### ISSUE TITLE
.CAF Files Are Not Included in FFmpeg File Name Filter.

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#4768]
### Bug description

See: https://forum.audacityteam.org/t/cannot-import-a-caf-file-into-audacity-i-installed-ffmpeg-but-when-i-try-to-import-a-caf-file-it-doesnt-find-it/77211 reported by forum user Mcijoh.

### Steps to reproduce

File > Import > Audio > Files of type: FFmpeg-compatible files

### Expected behavior

.caf files should be listed

### Actual behavior

.caf files are not listed

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

Note that .caf files are listed (and can be imported) if "All files" or "All compatible files" is specified.

**Comment by JohnColket** [comment]
Good First Issue

**Comment by sksDonni** [comment]
@JohnColket , would like to take up this issue

**Comment by JohnColket** [comment]
> @JohnColket , would like to take up this issue

Excellent. You will need @LWinterberg 's or other's approval.

**Comment by crsib** [comment]
We are redoing import/export framework right now.

> .caf files should be listed

Provided that any build of FFmpeg can be used, we cannot guarantee support for any file format at all. So I'm not quite sure, that "caf" should be hardcoded in the list.

**Comment by LWinterberg** [comment]
That's a good point - looking into caf more, it seems like "supported" isn't as simple as looking at the .caf extension, as inside of it can be quite literally any codec. The uncompressed varieties of which can be opened always by Audacity/libsndfile while others can only be opened by specific ffmpeg builds which contain the correct decoder for the thing. 

FFmpeg supports these variations:

<details><summary>show list</summary>

```c
 /**
  * Known codec tags for CAF
  */
 const AVCodecTag ff_codec_caf_tags[] = {
     { AV_CODEC_ID_AAC,             MKTAG('a','a','c',' ') },
     { AV_CODEC_ID_AAC,             MKTAG('a','a','c','l') },
     { AV_CODEC_ID_AC3,             MKTAG('a','c','-','3') },
     { AV_CODEC_ID_ADPCM_IMA_QT,    MKTAG('i','m','a','4') },
     { AV_CODEC_ID_ADPCM_IMA_WAV,   MKTAG('m','s', 0, 17 ) },
     { AV_CODEC_ID_ADPCM_MS,        MKTAG('m','s', 0,  2 ) },
     { AV_CODEC_ID_ALAC,            MKTAG('a','l','a','c') },
     { AV_CODEC_ID_AMR_NB,          MKTAG('s','a','m','r') },
   /* FIXME: use DV demuxer, as done in MOV */
   /*{ AV_CODEC_ID_DVAUDIO,         MKTAG('v','d','v','a') },*/
   /*{ AV_CODEC_ID_DVAUDIO,         MKTAG('d','v','c','a') },*/
     { AV_CODEC_ID_GSM,             MKTAG('a','g','s','m') },
     { AV_CODEC_ID_GSM_MS,          MKTAG('m','s', 0, '1') },
     { AV_CODEC_ID_ILBC,            MKTAG('i','l','b','c') },
     { AV_CODEC_ID_FLAC,            MKTAG('f','l','a','c') },
     { AV_CODEC_ID_MACE3,           MKTAG('M','A','C','3') },
     { AV_CODEC_ID_MACE6,           MKTAG('M','A','C','6') },
     { AV_CODEC_ID_MP1,             MKTAG('.','m','p','1') },
     { AV_CODEC_ID_MP2,             MKTAG('.','m','p','2') },
     { AV_CODEC_ID_MP3,             MKTAG('.','m','p','3') },
     { AV_CODEC_ID_MP3,             MKTAG('m','s', 0 ,'U') },
     { AV_CODEC_ID_OPUS,            MKTAG('o','p','u','s') },
     { AV_CODEC_ID_PCM_ALAW,        MKTAG('a','l','a','w') },
     { AV_CODEC_ID_PCM_MULAW,       MKTAG('u','l','a','w') },
     { AV_CODEC_ID_QCELP,           MKTAG('Q','c','l','p') },
     { AV_CODEC_ID_QDM2,            MKTAG('Q','D','M','2') },
     { AV_CODEC_ID_QDMC,            MKTAG('Q','D','M','C') },
   /* currently unsupported codecs */
   /*{ AC-3 over S/PDIF          MKTAG('c','a','c','3') },*/
   /*{ MPEG4CELP                 MKTAG('c','e','l','p') },*/
   /*{ MPEG4HVXC                 MKTAG('h','v','x','c') },*/
   /*{ MPEG4TwinVQ               MKTAG('t','w','v','q') },*/
  
     { AV_CODEC_ID_PCM_S8,       MKTAG('l','p','c','m') },
     { AV_CODEC_ID_PCM_S16LE,    MKTAG('l','p','c','m') },
     { AV_CODEC_ID_PCM_S16BE,    MKTAG('l','p','c','m') },
     { AV_CODEC_ID_PCM_S24LE,    MKTAG('l','p','c','m') },
     { AV_CODEC_ID_PCM_S24BE,    MKTAG('l','p','c','m') },
     { AV_CODEC_ID_PCM_S32LE,    MKTAG('l','p','c','m') },
     { AV_CODEC_ID_PCM_S32BE,    MKTAG('l','p','c','m') },
     { AV_CODEC_ID_PCM_F32LE,    MKTAG('l','p','c','m') },
     { AV_CODEC_ID_PCM_F32BE,    MKTAG('l','p','c','m') },
     { AV_CODEC_ID_PCM_F64LE,    MKTAG('l','p','c','m') },
     { AV_CODEC_ID_PCM_F64BE,    MKTAG('l','p','c','m') },
     { AV_CODEC_ID_NONE,            0 },
 };
```

via [caf.c](https://ffmpeg.org/doxygen/trunk/caf_8c_source.html)

</details>

In the current implementation it *probably* would be fine to hard-code caf as being always-available because, chances are, one of the codecs it supports is included in whatever ffmpeg build you have, but at the same time, I'm curious if the new importer (#4316) can have a smarter solution than that.

**Comment by dozzzzer** [comment]
Isn't reproducible anymore.
