### ISSUE TITLE
Crash when pasting stereo data into project with Mono track preceding stereo track with all tracks selected

### ISSUE THREAD

**Issue by Ryan-Miller-Audacity** [audacity/audacity#4769]
### Bug description

When pasting stereo data into a project with a leading mono track before a stereo track, if the user selects all (rather than specifically selecting the stereo track) Audacity will crash when you attempt to paste.

https://github.com/audacity/audacity/assets/88568755/4c2843fa-c20f-4dd4-ac34-49cc9139fa62

### Steps to reproduce

1) Open Audacity and generate some audio in a stereo track
2) Copy the stereo track data (Ctrl+A, Ctrl+C)
3) Ctrl + N
4) and create a mono track and a stereo track
5) Ctrl+A to select all tracks
6) Ctrl+V to paste

### Expected behavior

Audacity does not crash and with the copy/paste changes in PR #4730 the data would be correctly pasted into the stereo track (skipping the mono track when all tracks are selected)

### Actual behavior

Audacity crashes 

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

### Additional context

There is a rather obvious workaround for this which is to select the track that you are intending to paste into rather than using Ctrl+A to select all. 

This was discovered while testing the paste updates in PR #4730, but was not introduced as part of those changes. I tracked it back to being introduced in Audacity 3.3.0. Versions previous to that give an error of "Coping stereo audio into a mono track is not allowed." when attempting these steps. Versions 3.3.0 or later produce the crash.

Sentry Report: https://sentry.audacityteam.org/share/issue/a0a69ecaca714f8a8fee9505ef37f41b/

**Comment by saintmatthieu** [comment]
Still happens on current master. Call stack:
```
Audacity.exe!std::vector<std::shared_ptr<WaveClip const>,std::allocator<std::shared_ptr<WaveClip const>>>::_Unchecked_begin() Line 1914 (c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\vector:1914)
Audacity.exe!``anonymous namespace'::EstimateCopiedBlocks'::`2'::<lambda_1>::operator()(const WaveTrack & waveTrack) Line 173 (c:\Users\saint\git\github\saintmatthieu\audacity2\src\menus\EditMenus.cpp:173)
Audacity.exe!std::invoke<``anonymous namespace'::EstimateCopiedBlocks'::`2'::<lambda_1> &,WaveTrack const &>(`anonymous-namespace'::EstimateCopiedBlocks::__l2::<lambda_1> & _Obj, const WaveTrack & _Arg1) Line 1589 (c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\type_traits:1589)
Audacity.exe!std::_Invoker_ret<void>::_Call<``anonymous namespace'::EstimateCopiedBlocks'::`2'::<lambda_1> &,WaveTrack const &>(`anonymous-namespace'::EstimateCopiedBlocks::__l2::<lambda_1> & _Func, const WaveTrack & <_Vals_0>) Line 674 (c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\functional:674)
Audacity.exe!std::_Func_impl_no_alloc<``anonymous namespace'::EstimateCopiedBlocks'::`2'::<lambda_1>,void,WaveTrack const &>::_Do_call(const WaveTrack & <_Args_0>) Line 834 (c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\functional:834)
Audacity.exe!std::_Func_class<void,WaveTrack const &>::operator()(const WaveTrack & <_Args_0>) Line 875 (c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\functional:875)
Audacity.exe!`anonymous namespace'::ForEachCopiedWaveTrack(const TrackList & src, const TrackList & dst, const std::function<void __cdecl(WaveTrack const &)> & f) Line 134 (c:\Users\saint\git\github\saintmatthieu\audacity2\src\menus\EditMenus.cpp:134)
Audacity.exe!`anonymous namespace'::EstimateCopiedBlocks(const TrackList & src, const TrackList & dst) Line 172 (c:\Users\saint\git\github\saintmatthieu\audacity2\src\menus\EditMenus.cpp:172)
Audacity.exe!`anonymous namespace'::NotificationScope(const CommandContext & context, const TrackList & srcTracks) Line 568 (c:\Users\saint\git\github\saintmatthieu\audacity2\src\menus\EditMenus.cpp:568)
Audacity.exe!`anonymous namespace'::OnPaste(const CommandContext & context) Line 648 (c:\Users\saint\git\github\saintmatthieu\audacity2\src\menus\EditMenus.cpp:648)
Audacity.exe!CommandManager::HandleCommandEntry(AudacityProject & project, const CommandListEntry * entry, std::bitset<64> flags, bool alwaysEnabled, const wxEvent * evt, const CommandContext * pGivenContext) Line 1284 (c:\Users\saint\git\github\saintmatthieu\audacity2\src\commands\CommandManager.cpp:1284)
Audacity.exe!CommandManager::FilterKeyEvent(AudacityProject * project, const wxKeyEvent & evt, bool permit) Line 1200 (c:\Users\saint\git\github\saintmatthieu\audacity2\src\commands\CommandManager.cpp:1200)
Audacity.exe!<lambda_4>::operator()(wxKeyEvent & key) Line 1733 (c:\Users\saint\git\github\saintmatthieu\audacity2\src\commands\CommandManager.cpp:1733)
Audacity.exe!std::invoke<<lambda_4> &,wxKeyEvent &>(<lambda_4> & _Obj, wxKeyEvent & _Arg1) Line 1589 (c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\type_traits:1589)
Audacity.exe!std::_Invoker_ret<bool>::_Call<<lambda_4> &,wxKeyEvent &>(<lambda_4> & _Func, wxKeyEvent & <_Vals_0>) Line 674 (c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\functional:674)
Audacity.exe!std::_Func_impl_no_alloc<<lambda_4>,bool,wxKeyEvent &>::_Do_call(wxKeyEvent & <_Args_0>) Line 834 (c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\functional:834)
Audacity.exe!std::_Func_class<bool,wxKeyEvent &>::operator()(wxKeyEvent & <_Args_0>) Line 875 (c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\functional:875)
Audacity.exe!GlobalHook<KeyboardCapture::PostFilter,bool __cdecl(wxKeyEvent &),0>::Call<wxKeyEvent &>(wxKeyEvent & <arguments_0>) Line 173 (c:\Users\saint\git\github\saintmatthieu\audacity2\libraries\lib-utility\GlobalVariable.h:173)
Audacity.exe!`EventMonitor::FilterEvent'::`2'::<lambda_1>::operator()() Line 216 (c:\Users\saint\git\github\saintmatthieu\audacity2\src\KeyboardCapture.cpp:216)
Audacity.exe!GuardedCall<int,`EventMonitor::FilterEvent'::`2'::<lambda_1>,`EventMonitor::FilterEvent'::`2'::<lambda_2>,`EventMonitor::FilterEvent'::`2'::<lambda_3>>(const EventMonitor::FilterEvent::__l2::<lambda_1> & body, const EventMonitor::FilterEvent::__l2::<lambda_2> & handler, EventMonitor::FilterEvent::__l2::<lambda_3> delayedHandler) Line 219 (c:\Users\saint\git\github\saintmatthieu\audacity2\libraries\lib-exceptions\AudacityException.h:219)
```
Last non-std stack level: 
![image](https://github.com/audacity/audacity/assets/22740106/622a7a24-a08d-46b0-83cc-7b9295ee5e30)

**Comment by Paul-Licameli** [comment]
> ### Bug description
> 
> When pasting stereo data into a project with a leading mono track before a stereo track, if the user selects all (rather than specifically selecting the stereo track) Audacity will crash when you attempt to paste.
> paste.stereo.data.with.leading.mono.track.crash.mp4
> ### Steps to reproduce
> 
>     1. Open Audacity and generate some audio in a stereo track
> 
>     2. Copy the stereo track data (Ctrl+A, Ctrl+C)
> 
>     3. Ctrl + N
> 
>     4. and create a mono track and a stereo track (Paul: or make two stereo tracks(
> 
>     5. Ctrl+A to select all tracks
> 
>     6. Ctrl+V to paste
> 
> 
> ### Expected behavior
> 
> Audacity does not crash and with the copy/paste changes in PR #4730 the data would be correctly pasted into the stereo track (skipping the mono track when all tracks are selected)
> ### Actual behavior
> 
> Audacity crashes
> ### Audacity Version
> 
> current master / alpha / nightly build
> ### Operating system
> 
> Windows, macOS, Linux
> ### Additional context
> 
> There is a rather obvious workaround for this which is to select the track that you are intending to paste into rather than using Ctrl+A to select all.
> 
> This was discovered while testing the paste updates in PR #4730, but was not introduced as part of those changes. I tracked it back to being introduced in Audacity 3.3.0. Versions previous to that give an error of "Coping stereo audio into a mono track is not allowed." when attempting these steps. Versions 3.3.0 or later produce the crash.
> 
> Sentry Report: https://sentry.audacityteam.org/share/issue/a0a69ecaca714f8a8fee9505ef37f41b/

**Comment by dozzzzer** [comment]
Tested
