### ISSUE TITLE
Clip Handles / Time Shift Tool Toggle

### ISSUE THREAD

**Issue by kpcenti** [audacity/audacity#4777]
### Your idea

I would like a toggle between the new Clip Handles feature and the old Time Shift Move Tool.

### Problem to be solved

The new clip handles are too small to grab, the old time shift move tool has a bigger area to click on to move tracks.

**Comment by petersampsonaudacity** [comment]
Note that one you have clicked in the Clip-handle drag bar and keep the left mouse button down the drag-hand is not restricted to the drag-bar it can move across the track -or even the whole Audacity window until you release the left mouse button.

_In fact the closed hand drag-cursor can even operate outside the Audacity window._
