### ISSUE TITLE
Portaudio: bug in OSVERSIONINFO initialization

### ISSUE THREAD

**Issue by carlo-bramini** [audacity/audacity#478]
I would like to report that there is a bug into the source code of local copy of Portaudio, which prevents the correct compilation when compiling for Windows with GNU C.
I have signaled the bug to Portaudio team and the patch has been committed to their master.
So, in my opinion it would be worth to sync local copy of Portaudio with their master, by importing that small fix.

https://app.assembla.com/spaces/portaudio/git/commits/799a6834a58592eadc5712cba73b35956dc51579

**Comment by lllucius** [comment]
Upstream fix applied...
