### ISSUE TITLE
32 bits float recording doesn't work on Windows 10

### ISSUE THREAD

**Issue by Sky3RN** [audacity/audacity#4784]
### Bug description

Hi, 

I have the brand new soundcard Zoom UAC-232 which is a very special soundcard that records in 32 bits float. 
On Audacity for Linux (Ubuntu 20.04) it works fine, I can record with a high amount of input gain and reduce it in post and the sound is clear. 
On Windows (10 Pro) it's a struggle.. If I record the same way, I can't have a clear sound, all saturated. 

### Steps to reproduce

1) Get a Zoom UAC-232 
2) Increase the volume until you have saturation 
3) Record on Audacity 
4) Normalize the volume 

### Expected behavior

Clear sound, with no saturation. 

### Actual behavior

Saturation and distorded waveform. 

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by LWinterberg** [comment]
And you have set your mic to 32-bit in the windows settings as well? The dialog looks something like this: 

![image](https://github.com/audacity/audacity/assets/87814144/7fd2c0e4-c6cc-4a5a-9744-207a2b5c47b5)

**Comment by Sky3RN** [comment]
Last time I checked in this window there was no settings for for 32 bits float. 

I'll check it out afterwork when I'm home just to be sure and let you know.

**Comment by Sky3RN** [comment]
Here it is, I simply can not select anything in this window. 

![Zoom UAC-232 Github Audacity](https://github.com/audacity/audacity/assets/129675027/efa193b6-8820-486e-b105-e77a46a91c6e)

**Comment by LWinterberg** [comment]
that's very strange! But it would explain why Audacity seems to run into trouble on Windows for you: Windows simply doesn't see any other options than 24 bit 48k. You may be able to fix this by installing drivers or maybe something else, but that's out of scope for this bug tracker and if anything, zoom support would know why this is.

**Comment by Sky3RN** [comment]
But everything is installed correctly, I'm not the only one experiencing this issue.

**Comment by DavidBailes** [comment]
> But everything is installed correctly, I'm not the only one experiencing this issue.

https://zoomcorp.com/media/documents/UAC-232_32bit-float_applications_2023JAN_E.pdf

**Comment by Sky3RN** [comment]
> > But everything is installed correctly, I'm not the only one experiencing this issue.
> 
> https://zoomcorp.com/media/documents/UAC-232_32bit-float_applications_2023JAN_E.pdf

I already know this file, I work with Zoom France. :) (Not for but with.) 

And for the moment no one knows how to solve this issue. 

That's why I'm here, posting, hoping for a solution. It works fine on Linux so.. Does it come from the compilation of Audacity ? Or does it come from Microsoft itself ?

**Comment by crsib** [comment]
Audacity has different ways to work with audio devices. You can change the setting with "Audio Setup" -> "Host".

Probably WASAPI allows 32-bit float sample formats. However, you probably need ASIO support. For legal reasons, we are unable to distribute Audacity binaries with ASIO enabled, but you can build it from the source. 

https://github.com/audacity/audacity/blob/master/BUILDING.md#building-with-asio-support-on-windows

**Comment by DavidBailes** [comment]
I don't know too much about this stuff, but...
Portaudio documentation says:
The floating point representation (paFloat32) uses +1.0 and -1.0 as the maximum and minimum respectively.
In bool AudioIO::StartPortAudioStream(), in the call to Pa_OpenStream(), PaStreamFlags does not include paClipOff, which disables default clipping of out of range samples.

**Comment by Sky3RN** [comment]
> Audacity has different ways to work with audio devices. You can change the setting with "Audio Setup" -> "Host".
> 
> Probably WASAPI allows 32-bit float sample formats. However, you probably need ASIO support. For legal reasons, we are unable to distribute Audacity binaries with ASIO enabled, but you can build it from the source.

I tried with WASAPI and it didn't work. 

> https://github.com/audacity/audacity/blob/master/BUILDING.md#building-with-asio-support-on-windows

I'm trying to compile it but it's a real struggle. 
As far as I've succeed to compile it, I don't understand how to open Audacity then. I can't find any .exe file in my folder. 
I've tried to click on Debug > Run with, or without debug, but it get stuck on the splash screen. 

I'm not familiar with Visual Studio, it's the first time I'm using it. 

![VS Debug](https://github.com/audacity/audacity/assets/129675027/3a8e89dc-d516-41cf-88f8-ba66ed44d896)

**Comment by Sky3RN** [comment]
> Audacity has different ways to work with audio devices. You can change the setting with "Audio Setup" -> "Host".
> 
> Probably WASAPI allows 32-bit float sample formats. However, you probably need ASIO support. For legal reasons, we are unable to distribute Audacity binaries with ASIO enabled, but you can build it from the source.

I tried with WASAPI and it didn't work. 

> https://github.com/audacity/audacity/blob/master/BUILDING.md#building-with-asio-support-on-windows

I'm trying to compile it but it's a real struggle. 
As far as I've succeed to compile it, I don't understand how to open Audacity then. I can't find any .exe file in my folder. 
I've tried to click on Debug > Run with, or without debug, but it get stuck on the splash screen. 

I'm not familiar with Visual Studio, it's the first time I'm using it. 

![VS Debug](https://github.com/audacity/audacity/assets/129675027/335a4404-c614-44cc-850e-7b8dec1c2c91)

I'm trying this script : https://gist.github.com/SteveALee/da24c2be633340b8791066dd98eb5d0b 
Everything seems to be installed correctly and, same thing when Audacity opens : Stuck on the splash screen.

**Comment by Sky3RN** [comment]
It looks like the file _portaudio_x64.dll_ is blocking the starting of Audacity. But if I read well, it's THE important file for ASIO ?

**Comment by crsib** [comment]
ASIO scanning can be very slow. 

> it's THE important file for ASIO

Pretty much the only one, yes.

**Comment by Sky3RN** [comment]
@crsib I understand but I waited for 30 minutes before I gave up. 
I've tried on my desktop computer and my laptop. I don't understand why it blocks on the splash screen ?
