### ISSUE TITLE
Add option to skip effect property pop-ups for certain effects

### ISSUE THREAD

**Issue by WangleLine** [audacity/audacity#4785]
### Your idea

Allow the user to tell audacity to always skip the property pop-up window for certain effects and use a set of defined parameters.

I'm thinking this could be a per-effect/per-action setting to improve workflow when using certain effects hundreds of times.

### Problem to be solved

I often find myself normalizing small sections of audio in long sessions, and it's quite bothersome that this requires me to always click through the property pop-up window.

Currently: Select region -> Press Normalize hotkey -> Press enter to close/accept property pop-up window -> done

How I think it should optionally work: Select region -> Press Normalize hotkey -> done

### Additional context

In Izotope RX, the normalize effect/process only requires one button press, instead of two, like in audacity.

**Comment by LWinterberg** [comment]
You can use macros for that, available via Tools > Macro Manager
