### ISSUE TITLE
Horizontal scroll with mouse wheel updates the scroll bar, but not the waveform/track.

### ISSUE THREAD

**Issue by Alexia** [audacity/audacity#4786]
### Bug description

Reproducing this requires a horizontal scroll wheel on the mouse.

### Steps to reproduce

1.) Have any project open.
2.) Scroll with the **horizontal scroll wheel** on the mouse.

### Expected behavior

The waveform should scroll horizontally(left and right).

### Actual behavior

The scroll bar slide moves, but the waveform does not move.

However, manually clicking on the scroll bar slider where it moved to fires a mouse event which causes the waveform position to update.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

Video demonstration:

https://github.com/audacity/audacity/assets/248632/97950ef5-8f67-4371-89cc-779c771b4c3c

**Comment by LWinterberg** [comment]
I can reproduce this with a logitech mx master but not a logitech mx ergo (which doesn't have a side wheel, but a tilting "normal" scroll wheel). 

On the mx master, moving the side wheel sometimes *does* work, sometimes it works for a single tick and then exhibit's OP's behavior, and sometimes it only exhibits OP's behavior. Focussing on and scrolling in another window and then going back to Audacity seems to reroll the dice. 

A workaround is available in Shift+vertical scroll.

**Comment by KoenT-SS** [comment]
I also ran into this bug and wished it worked as expected, as horizontal scrolling is an essential action one uses all the time in an audio editor (or any editor with a timeline for that matter).
Personally, I also wouldn't say this is a very high priority bug, but it does surely cripple the UX each time I have to work in Audacity, so I would consider it as normal priority.

I can see this on Windows 10 in Audacity 3.3.3 using a Logitech MX Master 3 mouse (which has a thumbwheel for horizontal scrolling).

It's especially strange that the horizontal scroll event is obviously received (as the scroll bar handle does move as expected), but the audio display is not being updated. I would check how a mouse drag event on the scrollbar is hooked up to the redrawing of the display, and check what's different from receiving a horizontal scroll event. It might just be a missing "update / redraw" call.

**Comment by Alexia** [comment]
> It might just be a missing "update / redraw" call.

I would agree that is a most likely scenario.  I looked through the code and tried to figure it out, but the GUI handling code is confusing to me.

**Comment by LWinterberg** [comment]
This is fixed in the first alpha versions of Audacity 4.
