### ISSUE TITLE
High DPI support

### ISSUE THREAD

**Issue by JinZhuXing** [audacity/audacity#4788]
### Your idea

I think current audacity program (for windows) does not support High DPI.
I am using 4K monitor, and using 200% scale.
But the audacity does not support high DPI.
Please make it possible.
Thank you.

### Problem to be solved

I think it will be possible.
I have no idea for it, but I think it will be possible.

**Comment by dozzzzer** [comment]
We're currently switching the UI framework from wxwidgets to Qt and aren't looking to improve wx' HiDPI support as it'll be obsoleted soon anyway.
