### ISSUE TITLE
[Plugin issue] FFMPEG support is broken

### ISSUE THREAD

**Issue by jadenquinn** [audacity/audacity#4796]
### Plugin

FFMPEG

### Plugin Format

Other

### Plugin source

https://lame.buanzo.org/ffmpeg.php

### Bug description

Before I updated Audacity to 3.3.1 or whatever the latest is (just checked it's 3.3.3), ffmpeg support was not broken, but ever since I updated Audacity, ffmpeg support is as if it doesn't exist, not being able to import AAC and other formats, and not being able to export with formats too, even after installing the updated ffmpeg thingy for Audacity, the 5.0.0 version on the site Audacity links me to. It simply doesn't work, on ANY Mac I own.

### Steps to reproduce

Install Audacity, get the Audacity version of ffmpeg from site, and then not be able to do what you have to do because this thing that is supposed to work just doesn't.

### Expected behavior

It.. working.

### Actual behavior

It... doesn't work.. idk what else to put here, it just doesn't link up.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS

### Architecture

64 bit Intel/AMD processors, Apple Silicon (M1, M2, ...)

### Additional context

It just doesn't think I have FFMPEG for Audacity installed at all, even when I manually browse for the plugin/library thing and point Audacity to use it, it doesn't do anything.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with 3.3.3 and latest alpha test build for 3.4.0

I cannot reproduce this.

FFmpeg works fine for me for both import and export.

This is the FFmpeg version I have installed:
![image](https://github.com/audacity/audacity/assets/50205984/45229069-7a64-4cbc-80fd-40d1cebb32de)

**Comment by dozzzzer** [comment]
Cannot reproduce. M1 Pro, Audacity 3.3.3

What I did was the following:
1. Uninstalled all existing ffmpeg packages from the system
2. Downloaded macOS package from the website [using this link](https://lame.buanzo.org/FFmpeg_5.0.0_for_Audacity_on_macOS.pkg)
3. Launched Audacity 3.3.3
4. Checked ffmpeg installation in Preferences > Libraries

Act. result: 

![image](https://github.com/audacity/audacity/assets/70063970/5ae64408-e0f3-458a-909d-f8f3c7f86f95)

**Comment by jadenquinn** [comment]
I just tried this on a brand new install of MacOS High Sierra, brand new Audacity download, brand new FFmpeg download, it doesn't work. It simply doesn't "detect" it, even when I point it directly to the avformat thing that it says it wants.

**Comment by LWinterberg** [comment]
The "stuck in verification" thing happens on that one version with the universal binary; if you use the x86_64 audacity installer instead it works.

**Comment by jadenquinn** [comment]
This is still a problem, reproduced on more than 10 machines.
