### ISSUE TITLE
Icon for .aup files in Gnu/Linux

### ISSUE THREAD

**Issue by RafaMartorell** [audacity/audacity#480]
It is very simple, in linux audacity files do not have a custom icon.
This should be easy to fix, this is my icon proposal, if you like I can pass the gimp files and even make in svg with inkscape.
![audacity_project](https://user-images.githubusercontent.com/47257587/78500622-cfc6e500-7757-11ea-97bf-f7177dbeeda0.png)

**Comment by Fatih20** [comment]
IMHO this is not a good icon. It shouldn't have writings on it, mainly because of the writings. The icons will be displayed in small sizes, as such, it will make the writings unreadable and be perceived as just a jumbled mess by users, especially by users who use low ppi monitor, and I don't think you need gimp files for icon. SVG is always preferable for icon due to its scalability compared to raster image.
I could make a better icon if the developers would like to.

**Comment by RafaMartorell** [comment]
1. Do it, I would like to see your proposal
2. Of course it would be in .svg if I was asked to do so, although png is not a bad format for icons if you know how to do it well and it is compatible with all sizes without rasterizing.
3. The text is a simple ornament, they do not have to read it, but I see that at normal size it even reads well.
![icon](https://user-images.githubusercontent.com/47257587/78657331-e93b6e80-78c8-11ea-91eb-03c135183d8c.png)
P.S. Saying that you would do better without your showing it is considered demagoguery.

**Comment by Fatih20** [comment]
Here's my idea.
![Audacity File](https://user-images.githubusercontent.com/51940383/78660832-fa4fa400-78f7-11ea-961d-a88311113d1e.png)

**Comment by RafaMartorell** [comment]
Very good idea. Much more adapted to the current style used today on desks, I think it's great. Let's see if the developers give us a pleasant surprise and we can quickly locate the audacity files visually in Linux, without being confused with text files. :-)

**Comment by Fatih20** [comment]
Thanks! Yeah, it'd be nice.

**Comment by SteveDaulton** [comment]
The official Audacity icon can be found here: https://github.com/audacity/audacity/blob/master/images/Audacity_Logo_large.svg

**Comment by RafaMartorell** [comment]
Thanks @SteveDaulton. The problem is that in Gnu/Linux when installing Audacity® it does not put any icon for its project files. And these adopt the default icon, as if it were just another text file.

**Comment by SteveDaulton** [comment]
We do not make binaries for Linux, and we have no control over how an Audacity Project file is represented on any particular Linux distro or Desktop. An Audacity Project file is an XML (format) file, with the file extension ".aup". How such files are represented may vary from one distro to another, one Desktop Manager to another, and one Desktop theme to another. If you wish to pursue your feature request, then you would need to take the matter to the package maintainer for your Linux distribution.

**Comment by RafaMartorell** [comment]
Thank you very much for the clarification.
I simply made an association in my system of the .aup files so that they can be seen with an icon, to locate them quickly. I also don't think the theme of the .aup file icon is important to users.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Surely, because of the response that is available at http://github.com/audacity/audacity/issues/480#issuecomment-610448884, this issue should be closed?

**Comment by LWinterberg** [comment]
@BEEDELLROKEJULIANLOCKHART since that comment, we actually have started to provide binaries (AppImages) for Linux. I'm not familiar enough with the matter to know whether that means that we now could make nicer looking file icons.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
I would prefer Audacity to not provide its own file-logonography, but I realise that this issue is closed, so I shall state no more.

**Comment by ppw0** [comment]
> Here's my idea. ![Audacity File](https://user-images.githubusercontent.com/51940383/78660832-fa4fa400-78f7-11ea-961d-a88311113d1e.png)

This is nice. Do you have an SVG version?
