### ISSUE TITLE
Paulstretch effect update

### ISSUE THREAD

**Issue by havocfire** [audacity/audacity#4806]
### Your idea

Would it be possible to update Paulstretch effect with PaulXstretch's new parameters and features https://github.com/essej/paulxstretch

### Problem to be solved

It would add new features and possibilities in Paulstretch.

**Comment by LWinterberg** [comment]
FWIW: The thing comes with a VST3 version, so you probably already can load this into Audacity. 

That said, i wonder whether Paulstretch should be included or enabled in the default Audacity install in the first place. Between the unusual name and the extreme transformations of the audio, it feels like a very different beast to all the other included effects.

**Comment by petersampsonaudacity** [comment]
> i wonder whether Paulstretch should be included or enabled in the default Audacity install in the first place. Between the unusual name and the extreme transformations of the audio, it feels like a very different beast to all the other included effects.

@LWinterberg I've often wondered the same too ...

**Comment by LWinterberg** [comment]
I haven't made up my mind about the ultimate fate of paulstretch, but what is pretty clear at this point is that bringing feature parity with paulxstretch is not planned
