### ISSUE TITLE
New Export:  the Export dialog fails to honor the setting for last-used directory

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4809]
### Bug description

Testing new Exporter #4317 on W10 with @vsverchinsky 's branch build:  audacity-win-3.4.0-alpha-20230606+2e235de-x64

The Export dialog fails to honor the setting for last-used directory, instead it always defaults to@
C:\users\username\Documents\Audacity 

This is a regression on 3.3.3 and earlier Audacity versions

### Steps to reproduce

1. get some Audio
2. Export to a chosen directory - NOT the default C:\users\username\Documents\Audacity 
3. Export again
4. Observe: directory offered is the default:  C:\users\username\Documents\Audacity 

### Expected behavior

Audacity should remember and re-use the users last used directory  for export (or their chosen directory in Direcories preferences - if a setting has been made there).

### Actual behavior

C:\users\username\Documents\Audacity  is always the offered location on reinvoking Export

### Audacity Version
@vsverchinsky 's branch build:  audacity-win-3.4.0-alpha-20230606+2e235de-x64

### Operating system
Windows - but assume all OS

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @vsverchinsky 's latest branch build:  audacity-win-3.4.0-alpha-20230707+796e0db-x64

This appears to be properly fixed on Windows

**Comment by chinakov** [comment]
Tested, this is fixed on @vsverchinsky 's branch build: audacity-win-3.4.0-alpha-20230725+a480c52-x64

Thank you!
