### ISSUE TITLE
Can't build 008d8d8c branch with CMAKE

### ISSUE THREAD

**Issue by screwt** [audacity/audacity#481]
**Describe the bug**
Cmake is stuck on the generation step.

**To Reproduce**
```
git checkout -b 008d8d8c
git pull origin 008d8d8c
git status
On branch 008d8d8c
nothing to commit, working tree clean
```

**Expected behavior**
Solution file is generated by cmake without errors

**Additional information (please complete the following information):**
 - OS: windows 7
 - Audacity branch 008d8d8c
 - cmake version 3.17
 - cmake "visual studio 2017 | x64" target

**Additional context**
 error:

```
CMake Error at src/CMakeLists.txt:487 (add_executable):
  Cannot find source file:

    tracks/labeltrack/ui/LabelTrackUI.cpp
```

**Comment by lllucius** [comment]
At that commit the CMake build was only in the preparation stage.  It was incomplete and not being maintained.  You'll need to use the Visual Studio solution in "audacity/win".

However, if you want to try out the v2.4.0 (still being developed), the CMake build process is in good shape.

**Comment by screwt** [comment]
Ok.
In deed i want to build a plugin.
I would allow users to easily share the work.
That s why i'm targetting the last release.

**Comment by screwt** [comment]
@lllucius how can i checkout v2.4.0.
I tried master, but it seems broken right now :


```
Error	C2248	'TranslatableString::Request': cannot access private enum declared in class 'TranslatableString'	Audacity	audacity\src\Internat.cpp	305	
Error	C2248	'TranslatableString::NullContextName': cannot access private member declared in class 'TranslatableString'	Audacity	\audacity\src\Internat.cpp	306	
Error	C2248	'TranslatableString::Request': cannot access private enum declared in class 'TranslatableString'	Audacity	audacity\src\Internat.cpp	307	
Error	C2248	'TranslatableString::Request': cannot access private enum declared in class 'TranslatableString'	Audacity audacity\src\Internat.cpp	308	
```
