### ISSUE TITLE
New Export: The Edit Metadata dialog still has a checkbox for "Don't show this when exporting audio"

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4813]
### Bug description

Testing new Exporter https://github.com/audacity/audacity/issues/4317 on W10 with @vsverchinsky 's branch build: audacity-win-3.4.0-alpha-20230606+2e235de-x64

The new Export multiple, the Edit Metadata dialog still has a checkbox for "Don't show this when exporting audio"

This box is surely now redundant _(given the changed behavior whereby access to metadata editing is from the new Export Audio dialog)_ and should be removed now that metadata editing access is controlled from the Export Audio dialog.

And note that if you check this "on" then the Edit Metadata button in the Export Audio dialog becomes useless and does nothing.

### Steps to reproduce

1. get some audio
2. File > Export Audio
3. Click on the Edit Metadata button
4. Observe: the checkbox for "Don't show this when exporting audio"

### Expected behavior

No field for "Don't show this when exporting audio" to be in the Export Audio dialog

### Actual behavior

![image](https://github.com/audacity/audacity/assets/50205984/990adf11-beb1-4e83-885b-43aeeea4bf13)

### Audacity Version

@vsverchinsky 's branch build: audacity-win-3.4.0-alpha-20230606+2e235de-x64

### Operating system

Windows - but assume all OS

**Comment by petersampsonaudacity** [comment]
Note too that there still remains the prefs option for this in Import/Export preferences  which can also make the Metadata button inthe Export Aidio dialog non-functional (though that top section is intended to be removed according to the Figma design doc for the Export changes): 
![image](https://github.com/audacity/audacity/assets/50205984/91253c26-3372-4f72-9b9f-2ef0bcbc47f2)

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @vsverchinsky 's latest branch build:  audacity-win-3.4.0-alpha-20230707+796e0db-x64

The **Edit Metadata Tags** appears to be properly fixed on Windows

**Comment by chinakov** [comment]
Tested on audacity-win-3.4.0-alpha-20230725+a480c52, it is indeed fixed. 

Thank you!
