### ISSUE TITLE
New Export:  Opus Export fails

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4814]
### Bug description

Testing new Exporter https://github.com/audacity/audacity/issues/4317 on W10 with @vsverchinsky 's branch build: audacity-win-3.4.0-alpha-20230606+2e235de-x64

With the new Export Audio export to Opus format fails with an FFmpeg error

This is a regression on 3.3.3 and earlier

### Steps to reproduce

1. get some audio
2. File > Export Audio
3. Select Opus as the format
4. Export
5. Observe FFmpeg error message

### Expected behavior

The Opus file should be exported

### Actual behavior

![image](https://github.com/audacity/audacity/assets/50205984/8e4071e2-efb5-4b5a-b7cb-96ef305669df)

### Audacity Version
@vsverchinsky 's branch build: audacity-win-3.4.0-alpha-20230606+2e235de-x64

### Operating system

Windows - but assume all OS

### Additional context

This may (or may not) be down to the default settings - but I am no Opus expert

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @vsverchinsky 's latest branch build:  audacity-win-3.4.0-alpha-20230707+796e0db-x64

This appears to be properly fixed on Windows

**Comment by chinakov** [comment]
Tested on audacity-win-3.4.0-alpha-20230725+a480c52, it is indeed fixed. 

Thank you!
