### ISSUE TITLE
New Export: Configure button should only be available when "Custom mapping" is selected

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4818]
### Bug description

Testing new Exporter https://github.com/audacity/audacity/issues/4317 on W10 with @vsverchinsky 's branch build: audacity-win-3.4.0-alpha-20230606+2e235de-x64

In the new Export dialog there is a **Configure**.  This button only has relevance when the user chooses **Custom mapping** as the **Channels** option.

Thus when the user has chosen **Mono** of the default **Stereo** for Channels the **Configure** button should be grayed-out and unavailable

### Steps to reproduce

1. get some audio
2. File > Export Audio
3. Select  **Channels** option to  be  **Stereo** _(default)_ or **Mono**
4. Observe: **Configure** button is NOT grayed-out
5. Click on the **Configure** button
6. Observe: **Advanced Mixing Options** dialog appears

### Expected behavior

Configure button _**only**_ to be available when the user selects **Custom mapping** - otherwise (for stereo and mono) it should be grayed-out

### Actual behavior

![image](https://github.com/audacity/audacity/assets/50205984/0b4f1825-626b-4584-8abc-b940c1e8a0a1)

### Audacity Version

@vsverchinsky 's branch build: audacity-win-3.4.0-alpha-20230606+2e235de-x64

### Operating system

Windows - but assume all OS

### Additional context

@DavidBailes  referred to this as part of his accessibility review of New Export  as no. 3 in this thread:
https://github.com/audacity/audacity/issues/4317#issuecomment-1571712895

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @vsverchinsky 's latest branch build:  audacity-win-3.4.0-alpha-20230707+796e0db-x64

This appears to be properly fixed on Windows

**Comment by chinakov** [comment]
Tested on audacity-win-3.4.0-alpha-20230725+a480c52, it is indeed fixed. 

Thank you!
