### ISSUE TITLE
New Export: Timer Record is still using the old Export Audio dialog

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4819]
### Bug description
Testing new Exporter #4317 on W10 with @vsverchinsky 's branch build:  audacity-win-3.4.0-alpha-20230606+2e235de-x64

With the New Export, **Timer Record** is still using the old Export Audio dialog and NOT the new one

### Steps to reproduce
1. open a new project
2.  Transport > Recording > Timer Record
3. Click the checkbox **Enable Automatic Export**
4. Press its **Select button**
5. Observe old (3.3.3 and earlier) Export dialog appears

### Expected behavior
Timer Record should be using the new Export Audio dialog

### Actual behavior
![image](https://github.com/audacity/audacity/assets/50205984/f1f2bdc9-ec35-4587-abba-cbb6c04396b1)

### Audacity Version
@vsverchinsky 's branch build:  audacity-win-3.4.0-alpha-20230606+2e235de-x64

### Operating system
Windows - but assuma all OS

### Additional context
I know that @vsverchinsky has this in hand but is waiting for @crsib  to first complete the review of export refactoring before proceeding with this - see:
 New export UI #4668 

So this is logged just to enable us to track this

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @vsverchinsky 's latest branch build:  audacity-win-3.4.0-alpha-20230707+796e0db-x64

This now causes audacity to **CRASH** when following the Steps To Reproduce

**Comment by petersampsonaudacity** [comment]
@vsverchinsky 

Testing on W10 with Vitaly's latest branch build:  audacity-win-3.4.0-alpha-20230713+e7f58dd-x64

This issue is properly fixed in this branch build:
a) the new dialog appears
b) there is NO crash when accessing the Export dialog(s) for the automated export
c) The Timer record works and exports properly

**Comment by chinakov** [comment]
Thank you!
