### ISSUE TITLE
i3 window manager issue / wxgtk3

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#482]
Background windows fail to update correctly if Audacity is built with wxgtk3.

Run Audacity 2.3.3 from Arch community repository on Arch Linux with i3 gaps windows manager.

![DeepinScreenshot_20200406133344](https://user-images.githubusercontent.com/11681097/78792643-4c043700-79a9-11ea-89e5-dcb623244358.png)

Logged on Audacity bugzilla: https://bugzilla.audacityteam.org/show_bug.cgi?id=2385

**Additional information (please complete the following information):**
 - OS:  Arch Linux with i3 gaps windows manager,
 - Version: 2.3.3 from Arch community repository

**Comment by wlhlm** [comment]
I can confirm similar issues on Arch running i3 as well. Both the main track area as well as the meters for playback and record volume do not draw correctly. This happens with *and* without compositor (picom aka compton in my case).

**Comment by wlhlm** [comment]
Here is audacity recording system audio. You can see the contents of the previous workspace from which I've switched to audacity (it had a terminal open in this case) instead of the main track area. Again, this happens with and without compositor.

![Screenshot-2020-04-11-202754](https://user-images.githubusercontent.com/1928113/79051918-3013c600-7c33-11ea-81bf-94d4c4a2634a.png)

**Comment by mauricioph** [comment]
I had the same problem on Debian 10 (Buster) using i3wm on X11 and Sway on Wayland.
I have attached the strace log.
[audacity-strace.log](https://github.com/audacity/audacity/files/4576360/audacity-strace.log)

**Comment by obayit** [comment]
Can confirm this for `Ubuntu 20.04` and i3wm `4.18.3-258-g806104cf (2020-10-20, branch "gaps-next")`, I have to reload i3 every time with `ctrl` + `shift` + `r`

**Comment by dosy4ev** [comment]
I use `Arch` and `i3wm` and have similar visual glitch. `Audacity` main track area does not draw correctly.
But it depends on `GTK_IM_MODULE` env variable.
When i run `Audacity` with `GTK_IM_MODULE= audactity` everything works as expected. (My default is `GTK_IM_MODULE=xim`).

**Comment by Penikov** [comment]
While `GTK_IM_MODULE= audactity` works fine, there is no sense to keeping this issue open.
