### ISSUE TITLE
New Export: redundant entries in Import/Export preferences need to be removed

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4820]
### Bug description
Testing new Exporter #4317 on W10 with @vsverchinsky 's branch build:  audacity-win-3.4.0-alpha-20230606+2e235de-x64

With New Export, options that were formerly in Import/Export preferences are now handled in the new Export Audio dialg and thus need to be removed from Import/Export preferences (the top section).

### Steps to reproduce
1. Edit > Prefefences
2. Choose Import / Export
3. Observe the now redundant top section

### Expected behavior
![image](https://github.com/audacity/audacity/assets/50205984/611e8a7e-c00e-4d79-b344-95a2c1cd9509)

### Actual behavior
![image](https://github.com/audacity/audacity/assets/50205984/7b85db91-a63e-440b-9618-e07107e026b2)

### Audacity Version
@vsverchinsky 's branch build:  audacity-win-3.4.0-alpha-20230606+2e235de-x64

### Operating system
Windows - but assume all OS

### Additional context
I know that @vsverchinsky has this in hand but is waiting for @crs to first complete the review of export refactoring before proceeding with this - as Timer Record is still using the old Export Audio dialog.  See #4819

So this is logged just to enable us to track this

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @vsverchinsky 's latest branch build:  audacity-win-3.4.0-alpha-20230707+796e0db-x64

This appears to be properly fixed on Windows:

![image](https://github.com/audacity/audacity/assets/50205984/38369639-6e76-45ff-88f7-da5d55b69b3f)

**Comment by chinakov** [comment]
Tested on audacity-win-3.4.0-alpha-20230725+a480c52, and macOS, it is indeed fixed. 

Thank you!
