### ISSUE TITLE
New Export: If all tracks are muted there is no longer an error message blocking the export

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4822]
### Bug description
Testing new Exporter #4317 on W10 with @vsverchinsky 's branch build:  audacity-win-3.4.0-alpha-20230606+2e235de-x64

If all tracks are muted there is no longer an error message blocking the export.  Instead what happens with this branch build is that a silent audio file is exported.

This was not the case in 3.3.3 and earlier and is thus a regression on 3.3.3

### Steps to reproduce
1. get two audio tracks
2. Mute both of them
3. File > Export Audio (whole project or selection)
4. Observe: export takes place with no error message
5. Import the file
6. Observe: flat-line silent audio of the expected length

### Expected behavior
Audacity 3.3.3 and earlier
![image](https://github.com/audacity/audacity/assets/50205984/03e45101-24f3-48a2-a633-32971f8f388d)

### Actual behavior
No error message, instead a silent audio file is exported.

### Audacity Version
 @vsverchinsky 's branch build:  audacity-win-3.4.0-alpha-20230606+2e235de-x64

### Operating system
Windows, but assume all OS

### Additional context
The manual documents that there  is (should be) an error message in this situation.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @vsverchinsky 's latest branch build:  audacity-win-3.4.0-alpha-20230707+796e0db-x64

This appears to be properly fixed on Windows

![image](https://github.com/audacity/audacity/assets/50205984/75d76e16-c213-40f5-a55f-2ee0660868cd)

**Comment by chinakov** [comment]
Hi! Just tested on audacity-macOS-3.4.0-alpha-20230724+d3d98a4-universal branch build, and the warning message is also shown on macOS. 

I am closing this task, thank you!

**Comment by petersampsonaudacity** [comment]
@chinakov 

Surely this and the other "fixed" new export issues cannot be closed yet as @vsverchinsky 's work has not been pulled into master yet and remains subject to code review ?

**Comment by LWinterberg** [comment]
I mean, these bugs don't exist in master either as they're related to the new exporter :) 

I think for the new exporter bugs it's fair to close them as they're fixed in the branch
