### ISSUE TITLE
sample browser like Resonic player

### ISSUE THREAD

**Issue by XtremeSounds** [audacity/audacity#4824]
### Your idea

This would be highly useful to have something like Resonic right within Audacity.  

### Problem to be solved

I wouldnt need Resonic  - only one app needed. better integration for editing files.

**Comment by LWinterberg** [comment]
By sample browser, do you mean a file browser that has an audio preview?

**Comment by XtremeSounds** [comment]
Sure

 

Have you seen resonic player? It has more features but essentially that is what it is

**Comment by LWinterberg** [comment]
Right. There are no plans to add this any time soon, so I'll close this issue for the time being. It is in my feature request spreadsheet so it won't get lost though.
