### ISSUE TITLE
(macOS) Saving a project to a FAT32-formatted drive is allowed

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4828]
### Bug description

When saving a project to a FAT/FAT32 drive, Audacity doesn't raise any errors and allows users to save and potentially lose their data once their project size exceeds 4GB.

https://alphamanual.audacityteam.org/man/Error:_Unsuitable_drive

### Steps to reproduce

1. Cmd + N
2. Cmd + S
3. Select a FAT/FAT32-formatted flash drive
4. Enter a project name and try to save

### Expected behavior

Saving isn't allowed and the error message pops up:

<img width="411" alt="Screenshot 2023-06-22 at 22 18 27" src="https://github.com/audacity/audacity/assets/70063970/d8d1c040-3160-45b0-b128-3fcfeebf302a">

### Actual behavior

The project has been saved with no errors

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS

**Comment by Paul-Licameli** [comment]
Why isn't it a regression?

Did the ban on using FAT from macOS in fact never really work?

@petersampsonaudacity @dozzzzer

**Comment by dozzzzer** [comment]
> Why isn't it a regression?
> 
> Did the ban on using FAT from macOS in fact never really work?

It doesn't seem it has ever worked properly on macOS: I've looked all the way back to 2.4.1 release and none of the builds I've tested had blocked me from saving to a FAT32 drive with a proper error message.

**Comment by Paul-Licameli** [comment]
> > : I've looked all the way back to 2.4.1 release
> 
> FYI, I believe the ban started around 3.0.0, but others know better than I.

Correct, only since 3.0.0 was this ban intended.  Before that you should find it didn't apply in Windows either.

**Comment by petersampsonaudacity** [comment]
@Paul-Licameli 

I seem to recall that I'm pretty sure that I tested this at the outset on both Widows and macOS and that it failed _(expected behavior)_ with the error message on both.

I can try and test later (possibly over the weekend as I am off to a gig soon) - but note that my testing on macOS is now limited to 64-bit versions of Audacity as 32-bitters no longer run on my Mac.

**Comment by dozzzzer** [comment]
@petersampsonaudacity thank you, that would be great

**Comment by petersampsonaudacity** [comment]
Testing on my MacbookPro macOS 12.6.3

3.3.3 and 3.4.0 alpha both block saving projects to FAT and FAT32 formatted clip dives - so this WORKSFORME

**Comment by petersampsonaudacity** [comment]
Tested on macOS 12.6.7 with 3.3.3 and the very latest 3/4/0 alpha

FAT and FAT32 are properly blocked as targets for saving a project on both 3.3.3 and 3.4.0

**Comment by chinakov** [comment]
Thankfully, I also got the correct message with 3.3.3 on macOS 14.0 (MBP M2 15") when saving to a USB drive formatted as FAT32. 
![Screenshot 2023-07-18 at 21 50 26](https://github.com/audacity/audacity/assets/139755141/828d65fb-22d1-4ad5-b648-e02d35e47707)
