### ISSUE TITLE
Add Keywords to .desktop file

### ISSUE THREAD

**Issue by scootergrisen** [audacity/audacity#483]
https://github.com/audacity/audacity/blob/master/src/audacity.desktop.in currently have no keywords.

Other software sometimes have keywords so users can find the software if they search for "audio" or "edit" etc.

Example:

    Keywords=audio;editing;recorder;[...];

It would be best to add the strings from the following .desktop lines into the po files so they can be translated there:

    Comment
    GenericName
    Keywords

**Comment by dcsmith1212** [comment]
I've added the relevant fields from the .desktop file to the .pot file generation script, and the three new entries are marked as fuzzy in the resulting .po files. Should I try copying over the translations for Comment and GenericName from the existing .desktop file to their respective .po files or should I just check in the automagically generated translations and let the human translators re-do them all?

**Comment by scootergrisen** [comment]
Maybe the best for a translator would be to copy the strings from .desktop to po and mark them as fuzzy.
But it is not important if you do it or not.
It's fine if they are untranslated.

**Comment by priynshuchouhn** [comment]
hey I am new to this community and want to contribute in this project can you please help me with the process

**Comment by LWinterberg** [comment]
https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html is the spec for .desktop files, an example for what kind of line to add is in the initial comment. If you have questions, feel free to ask on audacityteam.org/devserver @priynshuchouhn

**Comment by pree-T** [comment]
May I work on this? Can someone help me?

**Comment by LWinterberg** [comment]
All I can tell you is that [this](https://github.com/audacity/audacity/blob/master/src/audacity.desktop.in) is the file and [this](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html) is the spec and [this](https://audacityteam.org/devserver) is our discord server where you can get help.

**Comment by pree-T** [comment]
I have joined the discord server and asked for help. @LWinterberg

**Comment by Ayush-Raghuwanshi** [comment]
Hey, I want to work on this issue, I studied about .desktop file and still a little confused. 
so I just want to confirm?
Keywords="Audio"
Keywords[en]="Audio Editor"

is this the right format to add keywords? @LWinterberg

**Comment by Ayush-singla27** [comment]
Has this issue been solved ? i am new to open source contributions. Can i try working on it?

**Comment by LWinterberg** [comment]
@Ayush-singla27 there's a pull request #2440 by @Dhriti03 but they've not done anything in 2 weeks to it. So I'd say go for it considering it's a quick change.

**Comment by Dhriti03** [comment]
> @Ayush-singla27 there's a pull request #2440 by @Dhriti03 but they've not done anything in 2 weeks to it. So I'd say go for it considering it's a quick change.

Pardon me for the delay , but is the work done or can I still work on it ?

**Comment by Ayush-singla27** [comment]
> > @Ayush-singla27 there's a pull request #2440 by @Dhriti03 but they've not done anything in 2 weeks to it. So I'd say go for it considering it's a quick change.
> 
> Pardon me for the delay , but is the work done or can I still work on it ?

yeah sure, got for it. not sure what i am doing. i guess i will go with reading documentation properly first.
