### ISSUE TITLE
Crash on MacOS Sonoma 14.0 beta

### ISSUE THREAD

**Issue by ChrisSW58** [audacity/audacity#4836]
### Bug description

Crash on opening Audacity when it tries to auto check for an update, and same when performing manual update.

### Steps to reproduce

1. Start Audacity with an auto check for update enabled OR
2. Click Help > Check for updates

### Expected behavior

No crash

### Actual behavior

Crash - Sentry log sent in each time; Immediately restarting the program and it works

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS 14.0

**Comment by LWinterberg** [comment]
@dozzzzer can you repro this?

**Comment by ChrisSW58** [comment]
Happens every time on open (once per day) and thereafter if I check for an update, so yes. If I restart immediately after the crash, as the check has already been done, Audacity opens as normal.

**Comment by dozzzzer** [comment]
> @dozzzzer can you repro this?

No. I haven't yet tried out macOS 14 developer beta. As soon as the public beta is available, I'm gonna install it and try to reproduce the issue.

**Comment by chinakov** [comment]
I have macOS 14.0 Beta 3 build on a MacBook Pro 15" (M2), and I have reproduced the same crash. 
@dozzzzer - you can already get the latest public beta already by registering at https://beta.apple.com/

**Comment by chinakov** [comment]
Seems like the issues with macOS 14.0 are not over just yet. 
Upon installing the latest [Master Branch build](https://github.com/audacity/audacity/actions/runs/5587828832), Audacity outright does not launch. No splash screen is observed, the application just does not launch. It is also **not** shown in Activity Monitor at any moment. 
@dozzzzer has not reproduced this on a non-14.0 macOS version.

Hardware: MacBook Pro M2
Software: macOS 14.0, Audacity 3.4.0 Alpha

**Comment by crsib** [comment]
Only final builds are notarized, likely you need to run `xattr -cr` to be able to launch even the signed builds.

**Comment by chinakov** [comment]
@crsib - you are correct. It seems that I missed the warning message that didn't allow it to launch. I approved it, and it works now. Thanks!

**Comment by chinakov** [comment]
Here is the stack trace of the crash. 
[stacktrace_macos14.txt](https://github.com/audacity/audacity/files/12127298/stacktrace_macos14.txt)

**Comment by jadenquinn** [comment]
I sent the crash report thing to wherever it sends it to when I click the send button. If Audacity cannot collect such reports by clicking send in the Audacity reporter, maybe that shouldn't be a feature since it's not helpful.

Every subsequent time I open Audacity, it works. No idea why, but here's a video showing this after I had already opened it once and it crashed, this is the time after when it didn't: https://www.youtube.com/watch?v=lMpx5qsp3Mo

**Comment by ChrisSW58** [comment]
> It works like this. It crashes if, in Preferences, under Application, you have Check for Updates checked. If checked, when you start Audacity, it will crash. However, because it has already tried to check for an update, it will not do it on subsequent opens, thankfully! (It probably checks once a day when run.) If you turn this off, and try a manual Check for Updates from the Help menu, then it will crash again. Either turn off the automatic check for now, or put up with starting the program a second time. Both will allow you to use the program.

**Comment by crsib** [comment]
It seems that the issue was fixed during the migration to Conan 2 (libcurl was updated in the process indeed)

**Comment by dozzzzer** [comment]
Unfortunately, it wasn't. I'm getting a crash on macOS 14.0 following the STRs above.

**Comment by crsib** [comment]
Do you use the latest master? I cannot repro the crash on latest macOS RC with the master, but 3.3 crashes for me as in str

**Comment by chinakov** [comment]
@dozzzzer - I will check it on my Mac with Sonoma as well.

**Comment by dozzzzer** [comment]
The issue indeed appears to be gone now, please disregard my previous comment.

**Comment by jwaldrip16** [comment]
Please see new ticket for the same issue for ticket # 5249.

**Comment by EricGoodrich** [comment]
I'm having the same trouble with Audacity 3.3.3 crashing at startup. Launching the second time works fine until you ask for a manual check for updates. I am sunning MacOS 14.0 Sanoma (23A344) on a Mac Studio M2 Ultra 128GB. Easily reproduced.

**Comment by LWinterberg** [comment]
This issue is fixed in the 3.4 alpha.

**Comment by MikHulk** [comment]
> This issue is fixed in the 3.4 alpha.

Any idea when 3.4 will be available ?

I would rather not have to build it from source.

Great software anyway 😄 .

**Comment by LWinterberg** [comment]
You can download the latest alpha on audacityteam.org/nightly. We also will put up a beta very soon.
