### ISSUE TITLE
File > Close should not close the whole window like File > Exit

### ISSUE THREAD

**Issue by Germs2004** [audacity/audacity#4839]
### Your idea

If I have two Audacity projects open at once, they are shown in two windows.  On the second window, if I click "File > Close", I expect it to close that second project, leaving the second window open and ready to open another project.  In other words, File>Close should have the same behavior whether one or two windows are open, but it works differently currently when only one window is open.  File>Close should not be a redundant button with File>Exit.

### Problem to be solved

Do not close an Audacity window when clicking File > Close.  Closing the whole window is the purpose of File > Exit.

**Comment by LWinterberg** [comment]
Exit (in other programs known as Quit) exits Audacity, closing *all* projects in the process, while Close only closes the current project. Audacity doesn't have a home screen to fall back to when no project is opened (not yet anyway), hence why closing a project when only one window is open throws you to the de-facto home screen - an empty project. 

The logic is different to what you may be expecting but IMHO the logic that exists typically doesn't get in the way.

**Comment by Germs2004** [comment]
It's ok if you choose not to implement this, but I want to make sure my request was understood.  I'm requesting that clicking Close should have the same behavior whether you have one window or two windows open - that is, clicking Close on a second window should return that second window to the "de-facto home screen - an empty project" rather than closing the whole window.  If the user wants to close that second window, they can already click Exit instead.  In effect, you currently have two menuitems that both do the same thing when you have two windows open, rather than having unique purposes like they do when only one window is open.

REASON:
This would be more intuitive, and it helps the user keep a second window open, which is important because opening a second window is currently difficult while the first window is recording (the "New" menuitem is grayed out and running audacity.exe a second time just brings the first instance to focus instead of opening a second window).

If you don't want to give the option of closing only the project in a second window, you may as well remove the "Close" menuitem altogether since it's redundant with Exit.

Thank you for your consideration.
