### ISSUE TITLE
"Snap" field has unexpected UX behavior

### ISSUE THREAD

**Issue by WangleLine** [audacity/audacity#4843]
### Bug description

This is about the "Snap" UI field in the bottom left of the main Audacity screen.

### Steps to reproduce

1. Launch Audacity
2. Enable Snap
3. Click in the field

Notice how a blinking text cursor appears, and you can select text in the field, but you cannot actually type anything in there.
[chrome_DG2pT8jeJO.webm](https://github.com/audacity/audacity/assets/34343336/eb529274-e6dd-444a-b100-37fe8434ea3d)

Additionally,
4. Disable Snap

Notice how the text cursor is still visible and blinking.
[chrome_dVlCOW4IV0.webm](https://github.com/audacity/audacity/assets/34343336/6da0886c-edcd-4d57-84e9-8e3bcebdb7ea)

### Expected behavior

I think it feels wrong for a text cursor appear in a dropdown field that does not allow you to enter any text.

Additionally, the ability to select text also feels out-of-place here, but I can see how that could be useful in extremely niche scenarios.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by petersampsonaudacity** [comment]
Confirmed on W10 with 3.3.3 and the latest 3.4.0 alpha test build.

Fundamentally 
IF no text can be input 
THEN there should be no text editing cursor in that field.

_**Ideally**: it would be good if clicking in the text field had the same effect ans clicking on the down-arrow to the right and invoked the dropdown list of available snaps._

**Comment by crsib** [comment]
There are accessibility issues otherwise, at least on Windows. This was a 'lesser evil' kind of compromise. There are no plans to try to address this issue before Audacity 4.

**Comment by WangleLine** [comment]
Wait, why was this closed instead of moved to a backlog?

**Comment by crsib** [comment]
This won't be fixed in Audacity 3. Audacity 4 will have the UI, written from scratch
