### ISSUE TITLE
right click audio file convert to mp3

### ISSUE THREAD

**Issue by XtremeSounds** [audacity/audacity#4845]
### Your idea

This would be a great feature to have right in the windows environment

### Problem to be solved

saves time. sharing wav files that are too large doesnt work

**Comment by petersampsonaudacity** [comment]
You can do it in Audacity with a simple macro.

In fact the simple MP3 Conversion Macro that we ship with Audacity doe that (with a little Normalization added)
![image](https://github.com/audacity/audacity/assets/50205984/5512ceed-2820-4a48-b34b-af2c6a7e4af9)

**Comment by LWinterberg** [comment]
I don't think this would be a great fit for Audacity. In a majority of conversion cases, Audacity acts as a front-end to things like ffmpeg. It makes sense to have easy conversion capability within Audacity as it lets you do these actions from within the familiar interface, but once you move outside of a context of Audacity and instead operate in the context of the file manager, having Audacity is just a hindrance at this point. 

Using plain FFmpeg, all you need is `ffmpeg -i %1 %1.mp3` and roughly 3 commands to put it into the context menu as outlined [in this superuser answer](https://superuser.com/a/1484841). Using Audacity, this becomes a *lot* more complicated.
