### ISSUE TITLE
Keyboard scrubbing: bug if you reverse direction

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#4846]
### Bug description

If you are holding down one of the keyboard scrubbing keys, U and I, you can change the direction of scrubbing, without stopping the scrubbing, by also holding down the other key and sometime after that releasing the original key.
However this no longer works correctly, the wrong audio is scrubbed.

### Steps to reproduce

Create a recording off yourself counting to five.
1. Hold down the I key to start scrubbing forwards.
2. Immediately after you have passed "three", also hold the U key.

### Expected behavior

The playback changes direction, and the audio corresponds to the playback position.

### Actual behavior

The playback changes direction, but the audio doesn't correspond to the playback position. 

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

### Additional context

This is a regression with respect to Audacity 3.3.2

Tested with commit: https://github.com/audacity/audacity/commit/35a0869c240631d235f05c0063f340ba3d1feee8

**Comment by saintmatthieu** [comment]
Thanks a lot for your report, @DavidBailes , looking into this.

**Comment by DavidBailes** [comment]
> looking into this.

Thanks!
Just in case it's any help, change in direction for keyboard scrubbing is handled by this function: void Mixer::SetSpeedForKeyboardScrubbing(), and if there's a change of direction, there ends up being a call to void MixerSource::MakeResamplers().

**Comment by saintmatthieu** [comment]
Bisecting points to a somewhat older merge. @DavidBailes would you be so kind to verify that the bug isn't present [here](https://github.com/audacity/audacity/actions/runs/5326010351) but that it is [there](https://github.com/audacity/audacity/actions/runs/5338487745) ?

**Comment by DavidBailes** [comment]
> Bisecting points to a somewhat older merge. @DavidBailes would you be so kind to verify that the bug isn't present [here](https://github.com/audacity/audacity/actions/runs/5326010351) but that it is [there](https://github.com/audacity/audacity/actions/runs/5338487745) ?

I can confirm that the bug isn't present in the first commit but is present in the second ("there").

**Comment by saintmatthieu** [comment]
Thanks. Assigning to @Paul-Licameli.

**Comment by DavidBailes** [comment]
The bug appears to have been introduced by this commit:
Author: Paul Licameli <paul.licameli@audacityteam.org>
Author date: 29/05/2023 15:07:59
Commit date: 21/06/2023 17:56:08
Commit hash: e0acd57e1cfa1254fd8d3aea64c95b0e67e5fe99

Lower loops over channels into MixSameRate, MixVariableRates...

... Make the assumption that channels have the same rate; maintain just one
sample position, for both channels.

Also lift the definition of the end position out of the loops -- ignoring
differences of channel lengths.  (This will simply fetch zeroes from WaveTrack
if the right channel happens to be shorter.)

**Comment by DavidBailes** [comment]
@Paul-Licameli  In commit https://github.com/audacity/audacity/commit/e0acd57e1cfa1254fd8d3aea64c95b0e67e5fe99 , there is the following change:

void MixerSource::Reposition(double time, bool skipping)
 {
-   for (size_t j = 0; j < mnChannels; ++j) {
-      mSamplePos[j] = GetChannel(j)->TimeToLongSamples(time);
-      mQueueStart[j] = 0;
-      mQueueLen[j] = 0;
-   }
+   mSamplePos = GetChannel(0)->TimeToLongSamples(time);

If after the mSamplePos assignment, I add the lines:
   mQueueLen = 0;
   mQueueStart = 0;
then this appears to fix the bug (in fact even just the line mQueueLen = 0; seems to be a fix).

Does this look like a good fix to you?

**Comment by Paul-Licameli** [comment]
> @Paul-Licameli In commit [e0acd57](https://github.com/audacity/audacity/commit/e0acd57e1cfa1254fd8d3aea64c95b0e67e5fe99) , there is the following change:
> 
> ```
> void MixerSource::Reposition(double time, bool skipping)
>  {
> -   for (size_t j = 0; j < mnChannels; ++j) {
> -      mSamplePos[j] = GetChannel(j)->TimeToLongSamples(time);
> -      mQueueStart[j] = 0;
> -      mQueueLen[j] = 0;
> -   }
> +   mSamplePos = GetChannel(0)->TimeToLongSamples(time);
> ```
> 
> If after the mSamplePos assignment, I add the lines:
> 
> ```
>    mQueueLen = 0;
>    mQueueStart = 0;
> ```
> 
> then this appears to fix the bug (in fact even just the line mQueueLen = 0; seems to be a fix, but might be safer just to set both to zero).
> 
> Does this look like a good fix to you?

Yes, thank you

**Comment by dozzzzer** [comment]
Tested
