### ISSUE TITLE
Audacity wrongly complaining about stereo track with different sample rates

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#4848]
### Steps to reproduce

1. create two mono empty tracks
2. pan one track hard left, the other hard right
3. mix and render to a new track
4. save, close and re-open project

### Expected behavior

the project re-opens

### Actual behavior

An error modal pops up, stating that "This project cannot be opened because it contains a stereo track with different sample rates."

### Audacity Version

other

### Operating system

Windows

### Additional context

The issue first appears in [this build](https://github.com/audacity/audacity/actions/runs/5379916314).

**Comment by saintmatthieu** [comment]
I have a similar problem opening [this project](https://1drv.ms/u/s!ArATSZ9esLBGxizp6yeMBa1CAB26?e=HN2oWh), which was created just by duplicating a mono track. It may be related.

**Comment by dozzzzer** [comment]
Tested
