### ISSUE TITLE
Have clips know project tempo

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#4849]
The stretching of clips depends also on project tempo and project tempo changes. Clips (and tracks) must know project tempo at all times, which they currently don't.

**Comment by dozzzzer** [comment]
Tested:

- For non-audio tracks changing the project tempo results in the track's horizontal scaling staying in sync with the beats-and-measure ruler
- Audio tracks still stay in sync with the time ruler
- Changing project tempo for all track types making sure it is correct
- Copy/paste between the projects
- Undo/Redo
- Save, close and reopen projects
