### ISSUE TITLE
Flatpak very slow to start compared with snap/AppImage (Ubuntu 22)

### ISSUE THREAD

**Issue by IgnacioJPickering** [audacity/audacity#4857]
### Bug description

I'm running Ubuntu 22.04 with GNOME and the Audacity flatpak (from flathub) is very slow to start (around x5 times slower than the corresponding snap or AppImage). I'm not completely sure if the flatpak is officially supported though, feel free to close this if that is the case. 

### Steps to reproduce

Install and run the audacity flatpak with:
```
flatpak install flathub org.audacityteam.Audacity
flatpak run org.audacityteam.Audacity
```

### Expected behavior

Startup should be roughly as fast as ``snap`` or ``AppImage``

### Actual behavior

Startup time is 5x slower

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Linux

**Comment by LWinterberg** [comment]
https://github.com/flathub/org.audacityteam.Audacity/issues is the flathub tracker

**Comment by IgnacioJPickering** [comment]
Ok, I'll post there then!
