### ISSUE TITLE
When changing rate of a stereo track with non-zero start times of L/R channels, start times get zeroed 

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4858]
### Steps to reproduce

1. Have two mono channels with clips on them starting at t>0
2. Track menu > Make stereo track
3. (observe the correct start times on each channel)
4. Right-click on the TCP > Rate > select a new value from the list

### Expected behavior

The track's channels remain at non-zero positions, proportionally moving left/right depending on the selected sample rate value (greater/smaller)

### Actual behavior

Both channels get zeroed, i.e. their start times get aligned with zero time mark.

https://github.com/audacity/audacity/assets/70063970/bda126ee-ae37-42b4-bbf3-e7fa1683e7d8

### Audacity Version

current master / alpha / nightly build

### Operating system

Other

### Additional context

The regression introduced by https://github.com/audacity/audacity/commit/0ec7ab2908f2acb5759323e1f5b5f345698e3d1b

**Comment by Paul-Licameli** [comment]
I failed to reproduce this at 796603d8644b8c0440f1fd44a60bbf3dbc317925

**Comment by Paul-Licameli** [comment]
It appears this bug was fixed with the reimplementation of join of mono tracks to stereo.  No new PR needed.

**Comment by dozzzzer** [comment]
The bug indeed is no longer reproducible.
