### ISSUE TITLE
macOS external headphones problems

### ISSUE THREAD

**Issue by alfs** [audacity/audacity#486]
**Describe the bug**
3,5 mm headset must be plugged in when Audacity starts. If removed during audacity execution they are not found and audacity must be restarted for the headset to be recognized.

Same if headset is plugged in after Audacity is started.

**To Reproduce**
1. Plug in 3,5 mm headset
2. Start audacity, open file, enjoy the audio
3. * Have a co-worker call you. 
4. Stop the audio and unplug the headset
5. * Plug the headset in your phone and carry out business
6. Replug headset in computer
7. Press play in Audacity
8. "Error opening sound device"
9. Change to internal speakers - OK, but audio disturbes co-coworkers
10. Change to external speakers (=headset)
11. Same error as in (9.)
12. Quit audacity
13. Goto (2.)

* (not actually required ;) )

**Expected behavior**
I expect that unplugging and replugging headsets would work seamlessly, or inserting headset after application is started.

**Screenshots**

<img width="838" alt="Screenshot 2020-04-11 at 00 24 21" src="https://user-images.githubusercontent.com/1869479/79027051-14ed7b80-7b8b-11ea-8428-ca7b7ae1a48a.png">

**Additional information (please complete the following information):**
 - OS: macOS Catalina 10.15.4
 - Audacity 2.3.2

**Comment by SteveDaulton** [comment]
Audacity scans for audio devices on launch, and again when explicitly requested with "Transport menu > Rescan Audio Devices". If you attach or disconnect an external device while Audacity is open, use Transport > Rescan Audio Devices to update the device lists before playing or recording. 

This is documented in multiple places in the manual, for example: https://manual.audacityteam.org/man/device_toolbar.html

Thank you for your interest in Audacity. If you require further help, we have a support forum here: https://forum.audacityteam.org

**Comment by alfs** [comment]
This worked, thanks. Sorry for not being observant and reading the manual. Just a last comment (which I think belongs to this report rather than the support forum)


Would it be possible to do a single automatic rescan of audio devices is there is an error opening the sound device, or could this cause some problem? 

Not sure what happens underneath in macos, but the user exceptation of simply replugging 3,5 mm headsets would not be that the audio device would need rescanning.

Or at least in the error message, prompt the user to do a transport->rescan devices (to complement the other suggestions?

Thanks,
  Stefan
