### ISSUE TITLE
Error when pressing Record for the second time with WASAPI set as a host

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4860]
### Steps to reproduce

1. select Host: WASAPI
2. Press Record
3. Stop recording
4. Press Record again
5. Observe

### Expected behavior

No errors, recording continues

### Actual behavior

![image](https://github.com/audacity/audacity/assets/70063970/6d3e4530-5d18-4230-8881-ca1fcda4b5e9)

### Audacity Version

current master / alpha / nightly build

### Operating system

Other

### Additional context

A regression introduced by https://github.com/audacity/audacity/commit/35a0869c240631d235f05c0063f340ba3d1feee8

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest 3.4.0 alpha:  audacity-win-3.4.0-alpha-20230627+86de8e9-x64-msvc2022

I cannot reproduce this.

I tested with all 3 Recording devices offered to me with WASAPI as the host:
![image](https://github.com/audacity/audacity/assets/50205984/4ee88ad5-7b54-41e9-8ff8-9cd499bac7fa)

**Comment by saintmatthieu** [comment]
@petersampsonaudacity it could be due to not having overdub enabled. I found this played a role while debugging the issue.

**Comment by petersampsonaudacity** [comment]
@saintmatthieu  interesting, I can't test now as my pc is packed away and I'm off to Egypt very shortly.

I would have had overdub on, as it is on by default.

Personally I have never understood why that is so. I campaigned some years ago to have it turned off by default, but I was outvoted.  I still think it should be off by default as clearly not evevery users wants or needs overdub (in 20 years of Audacity use I have never used it, except for QA testing).

**Comment by saintmatthieu** [comment]
If not overdub ... then it could be that your recording and playout devices have equal sample rate. You could also try changing one of these if you wish. But if I were in Egypt I'd rather go visit the pyramids :D

**Comment by crsib** [comment]
I think Gonzalo has made an almost-finished PR to address this issue https://github.com/audacity/audacity/pull/4353

**Comment by saintmatthieu** [comment]
Solved with https://github.com/audacity/audacity/pull/4861

**Comment by petersampsonaudacity** [comment]
> But if I were in Egypt I'd rather go visit the pyramids :D

A nice idea, BUT...  Hurghada on the Red Sea coast is a long way from Cairo - and a dive boat on the Red sea makes the trip even harder.

But I have seen the pyramids twice in my life already - and mighty impressive they are  :-))
