### ISSUE TITLE
Flatpak audacity cli interprets files with spaces as separate files

### ISSUE THREAD

**Issue by hasezoey** [audacity/audacity#4862]
### Bug description

Audacity installed through flatpak (`flatpak install flathub org.audacityteam.Audacity`, 3.3.3) cannot open files that have spaces in them and interprets them as separate files, native build (manjaro) and appimage work fine though.

opening the same file via a already started audacity "File -> Open", it opens the file correctly
(other applications installed through flatpak, like kdenlive in my case, can open files from cli with spaces just fine)

### Steps to reproduce

1. install audacity via flatpak
2. have a file with a space in the name (for this example `test file.mp3`)
3. try to run `org.audacityteam.Audacity ./test\ file.mp3` (or `"./test file.mp3"`)
4. observe error "cannot find file ./test" and "cannot find file ./file.mp3"

### Expected behavior

Files with spaces in the name to be properly opened like in the native version and in the appimage

### Actual behavior

interpreting files with spaces as separate files

### Audacity Version

other

### Operating system

Linux

### Additional context

Flatpak version: 3.3.3
Native version (manjaro): 3.3.2-1
AppImage: [3.3.3](https://github.com/audacity/audacity/releases/download/Audacity-3.3.3/audacity-linux-3.3.3-x64.AppImage)

**Comment by crsib** [comment]
Please log the issue with https://github.com/flathub/org.audacityteam.Audacity/issues

We do not support or maintain flatpak.

**Comment by hasezoey** [comment]
> We do not support or maintain flatpak.

didnt notice that, opened https://github.com/flathub/org.audacityteam.Audacity/issues/126
