### ISSUE TITLE
Playback stops when adding an effect during playback

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4864]
### Steps to reproduce

1. play a track with some audio in it
2. add an effect in the realtime effects panel
3. observe

### Expected behavior

Playback continues; the newly added effect changes the sound correspondingly

### Actual behavior

As soon as the new effect is added, playback stops

### Audacity Version

other

### Operating system

Other

### Additional context

A regression introduced by #4861

**Comment by saintmatthieu** [comment]
Solved with https://github.com/audacity/audacity/pull/4861
