### ISSUE TITLE
Set project tempo on clip when added to track

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#4869]
A small PR, following up on #4867. Clips have to know the project tempo as soon as they become visible in the UI, which is consistent with when a clip is added to a track's clip list. This is what we implement here.

**Comment by dozzzzer** [comment]
Tested:

- Creating clips on a track in random places should not break
- Reordering them by means of copy-paste
- Export and mix-and-rendering after the previous two steps
