### ISSUE TITLE
(Windows) Mic volume increase bug

### ISSUE THREAD

**Issue by TechySC23** [audacity/audacity#4871]
### Bug description

When I try to increase the mic volume while on host Windows WASAPI, the volume doesn't increase. I'm on Windows 8 BTW. Audacity version 3.3.2

### Steps to reproduce

Open Audacity.
Click Audio Setup toolbar.
Click Host.
Switch from MMS to Windows WASAPI (or Windows DirectSound)
Then try to drag Recording Meter toolbar's handle.

### Expected behavior

It should move the handle so that we can adjust the microphone volume.

### Actual behavior

It's not moving the handle!

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by JohnColket** [comment]
> It should move the handle so that we can adjust the microphone volume.
Which microphone ?

**Comment by LWinterberg** [comment]
works for me in https://github.com/audacity/audacity/commit/796e0db2d688b0f6830dc9f1cccf61cb48332289


https://github.com/audacity/audacity/assets/87814144/1e0f797e-9c9e-4897-ad6c-0a16635b0832
