### ISSUE TITLE
Shifting clip to left of 0 mark breaks spectrum display

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#4882]
### Steps to reproduce

1. Have a track with audio.
2. Switch to spectrum display.
3. Move clip left to the zero mark.

### Expected behavior

Spectrum display works.

### Actual behavior

Spectrum display turns black.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

### Additional context

Was introduced by recent caching-refactoring PR https://github.com/audacity/audacity/pull/4771

**Comment by dozzzzer** [comment]
Tested
