### ISSUE TITLE
Spectrogram default window size labelled incorrectly.

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#4889]
### Bug description

"Preferences > Tracks > Spectrograms" has a default window size of 2048, but the dropdown list shows "1024 (default)".

### Steps to reproduce

Look at the list of options for the default window  size for track spectrogram view.

### Expected behavior

The stated "default" value to be the actual default value.

### Actual behavior

The stated default value is 1024, while the actual default value is 2048.

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

**Peter:**  and W10

**Comment by petersampsonaudacity** [comment]
Confirmed on W10 with latest master for 3.4.0 alpha

**Comment by petersampsonaudacity** [comment]
In most (all other?) prefs we do not label the "default" setting in dropdown lists.

I suggest that we **just** remove the (incorrect) "default" labeling from the 1024 entry in the dropdown - and _**NOT**_ place it alongside the 2048.

_Traditionally the Manual has been used to show what the defaults are._

**Comment by SteveDaulton** [comment]
> Traditionally the Manual has been used to show what the defaults are

_Traditionally_ it was very easy to look up the relevant page in the included user manual - just click on the "?" button. Rather less easy now that there is no "?" button and no included user manual.

**Comment by LWinterberg** [comment]
Plot Spectrum has a very similar FFT size dropdown which comes without any such markings. I don't see too much value in pointing out what the default values for individual settings are, rather, I'd like to have a "reset to default" button nearby  which does these things for me.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @LWinterberg 's latest branch build:   audacity-win-3.4.0-alpha-20230710+0db5d81-x64

This fix works fine on Leo's latest branch:
![image](https://github.com/audacity/audacity/assets/50205984/e78f7d48-335b-4b13-9d3f-d05b4de2de0a)
