### ISSUE TITLE
Undo/redo clip trims separately

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4892]
### Description

Currently, when Undoing/Redoing several clip trim operations, Audacity only cares about whether from the left or from the right edge of the clip trim has been made. So, if several clips are trimmed from the same side one by one, Audacity would undo the whole sequence of trim operations at once:

https://github.com/audacity/audacity/assets/70063970/b5ab9da0-dc0a-45fd-b906-decc892f5c13

### STR

1. Have a few clips on the same audio track
2. Trim every one of them by dragging the right edge to the left
3. Edit > Undo or Ctrl (Cmd) + Z
4. Observe

### Actual Behavior

All clips are reversed to their previous (untrimmed) state

### Expected Behavior

Only the last trim action gets undone; 
Undo/Redo trim clip is performed for each individual clip separately.

**Comment by LWinterberg** [comment]
this sounds more like a bug, rather than a feature request

**Comment by dozzzzer** [comment]
Tested
