### ISSUE TITLE
Some Labeled Audio commands don't work as expected

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4903]
### Bug description

The following Labeled Audio operations don't work as expected:

macOS:
- Cut 
- Split Cut
- Copy
- Join

Windows:
- Join

### Steps to reproduce

macOS: 

1. Have some audio
2. Have a few region-type labels on the label track under the audio track
3. Edit > Labeled Audio > Cut
4. Edit > Labeled Audio > Split Cut
5. Edit > Labeled Audio > Copy
6. Edit > Labeled Audio > Join

Windows:

1. Have some audio
2. Have a few region-type labels on the label track under the audio track
3. Edit > Labeled Audio > Join

### Expected behavior

macOS:

3. The selected labeled audio data is removed and put on the Audacity clipboard
4. The selected labeled audio data is removed and put on the Audacity clipboard, but none of the audio data to the right of the selected labeled audio regions is shifted
5. The selected labeled audio is copied to the Audacity clipboard
6. Clips within the selected labeled audio regions are joined into one clip by removing the split lines

Windows:

3. Clips within the selected labeled audio regions are joined into one clip by removing the split lines

### Actual behavior

macOS:

3. _"There is not enough room available to paste the selection"_ error message
4. _"There is not enough room available to paste the selection"_ error message
5. _"There is not enough room available to paste the selection"_ error message
6. Clips within the selected labeled audio regions are **NOT** joined into one clip by removing the split lines

Windows:

3. Clips within the selected labeled audio regions are **NOT** joined into one clip by removing the split lines

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows, macOS

### Additional Context

macOS: not a regression since at least 3.0.0
Windows: not a regression since at least 3.1.0

**Comment by LWinterberg** [comment]
potential duplicate of #3679 or #2278

**Comment by dozzzzer** [comment]
It's indeed a duplicate of #3679. Closing in favor of the older issue
