### ISSUE TITLE
No warning when saving empty project

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4904]
### Steps to reproduce

1. In **Preferences > Warnings**, enable "Saving empty projects"
2. Ctrl + S
3. Observe

### Expected behavior

A warning for saving an empty project

### Actual behavior

No warning

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Other

**Comment by sdev23** [comment]
i didn't know amending the message would spam references like that. my bad. anyhow, does [this](https://github.com/sdev23/audacity/commit/933a1656d985f2032bdfbabfd9f8d818bf738e0b) look like a solution? it seems to work for me, at least.

**Comment by petersampsonaudacity** [comment]
A prime example of the above is when opening a new project for a Timer Record session when wanting to use the "Current project" option for the automated Save.

**Comment by LWinterberg** [comment]
According to https://bugzilla.audacityteam.org/show_bug.cgi?id=1368#c10, the reason this setting exists is: 

> 1. User imports MP3 (or something). MP3 appears as track.
> 2. User edits project and saves it.
> 3. User "closes project" by clicking the [X] on the track button.
> 4. User quits Audacity and is asked whether he wants to save changes.
> 5. User is a bit confused (because he already saved the project) but thinks "yes, why not?" and clicks "yes"
> 6. Later on, user starts Audacity loads the project and finds that it is empty. 

The case of nothing having been present ever doesn't need a warning as it can't lose any data, so this is WAI. 

The design fix for this would be to take the ambiguous X (close) button on the track and move it into the TCP menu, right next to the rename option. Then calling it "delete track" removes any ambiguity and will make this warning obsolete.
