### ISSUE TITLE
With Sync-Lock on, MIDI tracks aren't in sync with audio tracks

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4909]
### Bug description

When Sync-Lock is turned on, and the project has some audio and MIDI tracks, copying-and-pasting audio track data doesn't cause MIDI tracks to shift rightwards.

### Steps to reproduce

1. Have some audio
2. Import a MIDI file
3. Add a label track underneath both tracks
4. Enable Sync-Lock
5. Copy some portion of the audio and paste it onto the same track somewhere within the length of the MIDI clip
6. Observe

### Expected behavior

Silence (blank space) is added to the MIDI clip:

https://github.com/audacity/audacity/assets/70063970/990a046b-4054-441d-856a-780d431f67d7

### Actual behavior

No changes to the MIDI clip:

https://github.com/audacity/audacity/assets/70063970/2329baeb-d0df-4ed8-a6ad-51a90bfe9987

### Audacity Version

current master / alpha / nightly build

### Operating system

Other

### Additional context

Regression introduced by https://github.com/audacity/audacity/commit/ff0226138cd7031b87a993405f15b1ce2ef768b8

**Comment by Paul-Licameli** [comment]
Actually the bug isn't special to MIDI tracks.  It happens whenever the pasted-into track is not the last of the group.

**Comment by dozzzzer** [comment]
Tested
