### ISSUE TITLE
Loud, high-pitched tone at Audacity startup

### ISSUE THREAD

**Issue by Mr-Personality** [audacity/audacity#4924]
### Bug description

I launched Audacity and immediately there was a dangerously loud high pitched tone around 10k. It was much, much louder than simply generating a tone in Audacity at full volume.

The sound persisted even after lowering/muting the system volume. The only way to stop the sound was to physically pull out the speaker cable going into the audio out port on the back of my PC. When I plugged the cable back in again, the sound was gone.

This has only happened to me a couple of times and I cannot replicate it.

I understand that no one else has ever reported anything like this and it may be a problem with my own hardware/motherboard. But the fact that it happened when I launched Audacity made me think it was worth mentioning it here.

### Steps to reproduce

See above

### Expected behavior

See above

### Audacity Version

other

### Operating system

Windows

### Additional context

My motherboard: ASUS P7P55D, LGA 1156_Socket H, Intel
No sound card
Audacity version: 2.4.2 (I haven't updated for a while, sorry)

**Comment by dozzzzer** [comment]
@Mr-Personality This one will be extremely hard (if possible) to reproduce, given the fact that such an issue has never been reported and there is no clear set of steps to be taken in order to at least somewhat consistently make this happen.

**Comment by Mr-Personality** [comment]
Rather than reproducing the problem, might it be possible to theorize the circumstances which caused it?

**Comment by luzpaz** [comment]
Is this still relevant ?
