### ISSUE TITLE
Crash on moving Audio Clips to new Tracks with Sync Lock Track Enabled

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#4930]
### Bug description

If a User decides to grab an Audio Clip and drag it into another track, Audacity crashes. This happens on Stereo tracks, either created previously or newly created after the audio clip has been added to Audacity.
However, if the User cuts or copy/pastes the clips, no issues are observed. 

### Steps to reproduce

1. Open Audacity
2. Enable Sync Lock Tracks
3. Import an Audio Clip (Stereo)
4. Create a new Stereo Track
5. Drag and Drop the imported Audio Clip into the newly created Stereo Track or drag it across the original track.
6. Observe Result

### Expected behavior

The User should be able to freely move Audio Clips to different Audio Tracks. 

### Actual behavior

Audacity crashes. 

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS

### Additional context

https://github.com/audacity/audacity/assets/139755141/a8bb3fe6-fbba-4299-85f4-ae560bb9fd4a

**Comment by chinakov** [comment]
Here is the commit that lead to this regression: #[9e72efa](https://github.com/audacity/audacity/commit/9e72efa24f2e84c37fe48cc8ecf3790dcfab35f6)

**Comment by Paul-Licameli** [comment]
> Here is the commit that lead to this regression: [#9e72efa](https://github.com/audacity/audacity/commit/9e72efa24f2e84c37fe48cc8ecf3790dcfab35f6)

I think your bisection is mistaken and the bug has been present since 981d465

**Comment by chinakov** [comment]
> > Here is the commit that lead to this regression: [#9e72efa](https://github.com/audacity/audacity/commit/9e72efa24f2e84c37fe48cc8ecf3790dcfab35f6)
> 
> I think your bisection is mistaken and the bug has been present since [981d465](https://github.com/audacity/audacity/commit/981d46562ad68c52e4128c240d14a8bef884ef33)

Thank you! I've just spoken with @dozzzzer on how to do it correctly.

**Comment by dozzzzer** [comment]
Tested

**Comment by chinakov** [comment]
The issue is no longer present for tracks if the Sync Lock feature is disabled. 

However, it seems like the issue is still present if the Sync Lock feature is enabled. 

Sentry log: https://sentry.audacityteam.org/organizations/sentry/issues/26340/?query=is%3Aunresolved
