### ISSUE TITLE
Beats & Measures Gridlines

### ISSUE THREAD

**Issue by crsib** [audacity/audacity#4931]
### Gridlines for Beats & Measures
Even though Users are able to snap clips and selection to the new beats & measures timeline format, the alignment process can still be a bit finicky.

Our new gridlines design seeks to do two things:
- Extend the ruler hatch marks to the entirety of the track canvas to improve visibility of the ruler.
- Act as a visual cue to help Users differentiate between Minutes & seconds and Beats & meaures.

![Image](https://github.com/audacity/designtasks/assets/111350316/f777474d-0932-46ca-84d9-69c46fb82c57)

As the User zooms in and out of Audacity, the timeline ruler adjusts accordingly. As the gridlines are essentially an extension of the timeline ruler hatch-marks, they will also respond to zoom levels. Gridline formats have been specified for typical zoom-levels in the spec provided below.

[Link to specification -> ](https://zpl.io/YYQegye)

**Comment by chinakov** [comment]
Tested, thank you!

**Comment by chinakov** [comment]
#5039

**Comment by chinakov** [comment]
Seems like this issue is also reproduced on Master, which means that this branch is also affected. I am closing this task, please merge, and fix will be merged after.
