### ISSUE TITLE
Applying Sliding Stretch effect on a track of a sync-locked group won't cause other tracks to shift

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4939]
### Bug description

Applying the built-in Sliding Stretch effect, along with Change Speed, Change Tempo and Paulstretch, should be causing time shift/adding silence into other tracks when in a sync-locked track group.

### Steps to reproduce

1. Have a clip on a mono track
2. Have a clip on a stereo track
3. Have a label track with a label past the zero time mark
4. Enabel Tracks > Sync Lock tracks
5. Select a portion of the stereo clip and apply Sliding Stretch to it with the values like i.e. -50/-50 (see the screenshot)
6. Observe
<img width="336" alt="Screenshot 2023-07-20 at 16 13 27" src="https://github.com/audacity/audacity/assets/70063970/744913c2-e4d5-484e-b8c2-58f038516b01">

### Expected behavior

- Inserted silence in the mono track, so that the overall length of the clip matches the one of the stereo track
- The label on the label track is shifted to the right by the same value

### Actual behavior

Only the stereo track's clip has been stretched; no changes made to either mono or label track:

<img width="483" alt="Screenshot 2023-07-20 at 16 14 17" src="https://github.com/audacity/audacity/assets/70063970/0440ddc9-2d85-4841-8958-1ca88bebc165">

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Other

### Additional context

Doesn't seem to be a regression; the issue has been present since at least 2.4.2.

**Comment by petersampsonaudacity** [comment]
@dozzzzer 

See also:   Paulstretch and Set Rate do not affect Sync-Locked tracks #1606 

This may be basically the same issue

**Comment by dozzzzer** [comment]
Indeed, that seems like the same bug, thanks @petersampsonaudacity
