### ISSUE TITLE
Use FLAC compression for the `Save a lossless copy` feature

### ISSUE THREAD

**Issue by spacehobo** [audacity/audacity#494]
**Is your feature request related to a problem? Please describe.**
Lossless copies of projects are nearly the same size as the originals.

**Describe the solution you'd like**
The track audio files in the `*_data /`directory should be losslessly-compressed FLAC (or ogg FLAC) copies of the data.

**Describe alternatives you've considered**
The `save a compressed copy` menu option is fine for some purposes, but lossy compression introduces error that makes it unsuitable for repeated infrequent updates of a re-archived audio project.

**Additional context**
I am aware of the role of the "save a X copy" feature, and do not expect it to be a working tree.  I would just like to save space on my archives of historic projects without losing fidelity.

**Comment by LWinterberg** [comment]
FLAC currently doesn't have a 32-bit encoder (although the format does support it), so it's unsuitable for this. 
That said, #1470 is adding wavpack which would support 32-bit audio and is a candidate for lossless compression of project files. 

I'll close this issue, but you can follow along the progress regarding the project format in https://github.com/audacity/audacity/projects/7
