### ISSUE TITLE
Misbehavior of selection with label tracks

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#4941]
### Bug description

A bad behavior I have discovered and expect to change incidental to refactoring work.

### Steps to reproduce

1. In a new project make one label track
2. make two region labels starting later than time 0
3. Ctrl + A to select all

### Expected behavior

At 3., compare what happens if instead there is a note track starting later than 0, or a wave track with at least one clip and the first of them later than 0.

Expect then that selected time goes from the earliest label start to the latest label end.

### Actual behavior

Selection goes from 0 to the latest label end.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

**Comment by petersampsonaudacity** [comment]
>Selection goes from 0 to the latest label end.

'Twas ever thus - it's done that ever since 1.3.0 _(also 1.2.6 - but no range labels in 1.2.6)_

I've always thought that was the way it was supposed to be - nut I do agree that it would probably be better if "selected time goes from the earliest label start to the latest label end".

**Comment by Paul-Licameli** [comment]
> > Selection goes from 0 to the latest label end.
> 
> 'Twas ever thus - it's done that ever since 1.3.0 _(also 1.2.6 and even 1.0.0 - but there were no range labels in those early versions, only point labels)_
> 
> I've always thought that was the way it was supposed to be - but I do agree that it would probably be better if "selected time goes from the earliest label start to the latest label end".

I'm clearing up some very ancient stuff that has gone long unquestioned.  See the other issue about the alignment commands really messing up with label tracks.

The code makes a distinction between "offset" versus "start time" of a label track but never explains why.  I just want to get rid of that complication.

This minor bit of behavior that was always so is probably not a thing anything really cares to defend, so I hope.

**Comment by petersampsonaudacity** [comment]
> This minor bit of behavior that was always so is probably not a thing anything really cares to defend, so I hope.

I suspect that its another one of those things that if I asked Dominic about it he would likely reply@
>Ooh, I never thought of that use case ...

**Comment by petersampsonaudacity** [comment]
BTW if the user wanted to retain the label track selection always starting at T=0 all they would need to do is create a point label at T=0

**Comment by Paul-Licameli** [comment]
> BTW if the user wanted to retain the label track selection always starting at T=0 all they would need to do is create a point label at T=0

Shift+J could do it as now implemented too, but I may change what Shift+J does, to make label and wave track behavior consistent.

Using the selection toolbar is an option too.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest 3.4.0 alpha with @Paul-Licameli 's fix for this:  audacity-win-3.4.0-alpha-20230804+48a1e8d-x64-msvc2022

I note that the behavior is different depending on whether sync-lock is off or on - @Paul-Licameli is this intentional ?

In both cases I make the selection by clicking un the Select button in the label track.

### 1. Sync-lock off
![image](https://github.com/audacity/audacity/assets/50205984/f1aee065-61eb-4d5b-9892-9e2b5eb488fd)

### 2, Sync-lock on
![image](https://github.com/audacity/audacity/assets/50205984/8274feb7-399a-4a8f-bc22-de589ca4c21e)

**Comment by Paul-Licameli** [comment]
I didn't notice that difference.  Is the behavior unchanged from previous master?
