### ISSUE TITLE
Timer Record can fail to Export

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4952]
### Bug description

Using defaults in Timer Record and choosing Automatic Export
![image](https://github.com/audacity/audacity/assets/50205984/888b9ed8-9ca0-475c-a6ce-02d2e505ffb2)

 The Export on completion fails:
![image](https://github.com/audacity/audacity/assets/50205984/ed5bd996-0490-47ae-84d2-86566981efc1)

_I assume that it is because although the folder location is set there is no default filename set (see STRs below)_

### Steps to reproduce

1. clear Audacity settings folder
2. Launch Audacity (Vitaly's branch build for new Export)
3. Transport > Recording > Timer Record
4. set the timer for 5 seconds recording (immediate)
5. Check "on"  the **Automatic Export**
6. Observe:  A default location is now provided for the export   _(not the case in earlier Audacity versions)_
7. Press OK in the Timer Record dialog
8. Observe: 5 seconds recorded
9. Observe: The Export fails (see above)

If instead at step 5 you 
5.1 press the Select button by the Automatic Export
5.2 Observe: folder location and filename untitled.wav are populated
5.3 make no changes just press the OK button
Then the Export (of untitled.wav) proceeds correctly

### Expected behavior
Either the TR should not be allowed to be activated if the file location is not set

or

a default filename of untitled .wav should be used

### Actual behavior
Export fails

### Audacity Version
@vsverchinsky 's latest brabch build for new Export

### Operating system
Windows 10 - but assume all OS

### Additional context
None

**Comment by petersampsonaudacity** [comment]
This is a regression on 3.3.3 as with that version (and earlier) if you leave the Export filed unmodified the Timed Recording is blocked when you press the OK button in the TR dialog:
![image](https://github.com/audacity/audacity/assets/50205984/1ee3f2e9-8765-4478-97a4-c09a46451e2f)

**Comment by petersampsonaudacity** [comment]
@LWinterberg @dozzzzer @crsib 

Testing on W10 with @DavidBailes ' branch:  audacity-win-3.5.0-alpha-20231219+2e17667-x64

As Suggested by David in PR #5911  This issue also appears to be fixed in David's branch

**Comment by dozzzzer** [comment]
Tested
