### ISSUE TITLE
The Detach at Silences command may incorrectly make splits where only the left channel is silent

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#4954]
### Bug description

This bug will exist after #4937 is merged

### Coding tasks
- [x] In `WaveTask::Disjoin` use the width of the track `NChannels()`
- [x] Rewrite the loop over clips as over `Intervals()` instead, adding member functions to `WaveTrack::Interval` as needed
- [x] Where samples are fetched from the clip, use `WaveChannelInterval::GetSamples` instead, in a loop over the `Channels()` of the `WaveTrack::Interval`

### Steps to reproduce

1. Make stereo track with rhythm track in the left but tone in the right
2. Select all
3. Edit > Audio Clips > Detach at Silences

### Expected behavior

No splitting of the track

### Actual behavior

The track is split at silences of the left channel, ignoring the right

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

**Comment by dozzzzer** [comment]
Tested
