### ISSUE TITLE
Windows: New export dialog: initial focus is not the first control

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#4960]
### Steps to reproduce

using the commit: https://github.com/audacity/audacity/commit/d3d98a434a0cf9511526842b70799234c0cdbba4

1. Open the Export audio dialog
2. Which control is the initial focus?

### Expected behavior

The first control is the initial focus (unless there are very good reasons otherwise), which is the file name text box.

### Actual behavior

One of the channels radio buttons is the initial focus.
For users of screen readers, and probably others, this is not at all helpful.

### Audacity Version
New Export branch build

### Operating system

Windows

**Comment by chinakov** [comment]
Just a note: It works as expected on macOS builds of Audacity: the initial focus there is in the file name text box. 
<img width="2152" alt="Screenshot 2023-07-27 at 18 49 44" src="https://github.com/audacity/audacity/assets/139755141/e032abaa-ecac-4d02-a19f-b69821576b93">

**Comment by DavidBailes** [comment]
> Just a note: It works as expected on macOS builds of Audacity: the initial focus there is in the file name text box.

and also works as expected on XUbuntu 22.04:
![image](https://github.com/audacity/audacity/assets/11887021/f8291e0e-4c1a-495e-81c6-88ea145d2fb7)

**Comment by petersampsonaudacity** [comment]
@DavidBailes @chinakov 
Testing on macOS 12.6.7 Monterey with @vsverchinsky 's latest branch build

This works properly on Mac with the initial focus on the **File Name** field

**BUT** I can't figure out how to change the Channels setting
and **WORSE** tabbing gets stuck circling round inin the Channels section

**Comment by petersampsonaudacity** [comment]
Testing on W10 (and Mac macOS 12.6.7) with @DavidBailes 's latest branch build:  audacity-win-3.4.0-alpha-20230803+43a29d1-x64

1) this now works properly on Windows with this branch build with the initial dialog entry **Filename** having the focus on calling up the Export Audio dialog.

2) On Mac **Filename** remains the initial focus so remains working properly _(as was that case in earlier 3.4.0 alphas)_

**Comment by chinakov** [comment]
@DavidBailes - it seems that the focus issues has been fixed. However, @petersampsonaudacity is correct - macOS now has unwanted behaviour - tabbing no longer works properly. 

On Windows a User can tab through every single element in the Export Audio dialog window. 
On macOS, a User can only tab through the File Name and Folder fields, nothing else. 

Could you try to fix this in-branch?

**Comment by DavidBailes** [comment]
> @DavidBailes - it seems that the focus issues has been fixed. However, @petersampsonaudacity is correct - macOS now has unwanted behaviour - tabbing no longer works properly.
> 
> On Windows a User can tab through every single element in the Export Audio dialog window. On macOS, a User can only tab through the File Name and Folder fields, nothing else.
> 
> Could you try to fix this in-branch?

@chinakov . I work on a Windows computer, so can't help with problem with the tabbing behaviour on MacOS.
I suggest the tabbing problem is logged as a separate issue.

**Comment by DavidBailes** [comment]
@petersampsonaudacity . Could you please log the tabbing issue on MacOS as a separate issue? I don't think it's at all helpful that it seems to have got combined with a separate issue on a different platform.

**Comment by DavidBailes** [comment]
> > @petersampsonaudacity . Could you please log the tabbing issue on MacOS as a separate issue?
> 
> Yes, I can do that at some stage over the weekend

@petersampsonaudacity . Thanks!

**Comment by chinakov** [comment]
Yes, this is fixed, and ready to merge. Thank you!
