### ISSUE TITLE
Wrong link on the Edit Menu: Labeled Audio manual page

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#4967]
### Bug description

The last paragraph of the Labeled Audio Submenu section has a wrong link to the examples.

<img width="1115" alt="Screenshot 2023-07-28 at 12 24 31" src="https://github.com/audacity/audacity/assets/70063970/0be59351-e81d-4431-9a8f-176f0d954c21">

### Steps to reproduce

1. Navigate to https://manual.audacityteam.org/man/edit_menu_labeled_audio.html
2. Scroll down to the Labeled Audio Submenu section
3. Click the link "examples" in the last paragraph

### Expected behavior

It takes you to a section (page) with examples _of the difference between selecting in the label track only versus selecting in the label track and one or more audio tracks._

### Actual behavior

Takes you to the "Type to Create a Label (on/off)" section instead

### Audacity Version

other

### Operating system

Other

**Comment by petersampsonaudacity** [comment]
@dozzzzer 

Fixed in the alpha Manual for the upcoming 3.4.0
https://alphamanual.audacityteam.org/man/Edit_Menu:_Labeled_Audio

**Comment by dozzzzer** [comment]
Thank you, Peter
