### ISSUE TITLE
New Export: Project Sample Rate affects the length of generated tone

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#4969]
### Bug description

If a User chooses to change the sample rate of his project, creates a new track with the new sample rate, the tone generator no longer works correctly, creating a longer/shorter Right channel.

### Steps to reproduce

1. Launch Audacity
2. Go to Preferences and make sure the project is in 44100 kHz sample rate
3. Create a stereo track
4. Generate a tone (1m30s)
5. Both channels have equal-length tones
6. Go to Preferences 
7. Change the Project Sample Rate and Default Sample Rate to 192000 kHz
8. Create a new stereo track
9. Observe '192000Hz' as the sample rate for the newly created stereo track
10. Generate the same tone (1m30s)
11. Observe Result

### Expected behavior

Both tones generated in each channel after changing the Project Sample Rate and Default Sample Rate should be equal length (1m30s).

### Actual behavior

The Right channel is 4 minutes longer than the Left. 
![Screenshot 2023-07-28 at 14 54 24](https://github.com/audacity/audacity/assets/139755141/ab9a1059-2886-48f5-b427-4ede8788a6d5)

### Audacity Version

other

### Operating system

Windows, macOS

### Additional context

**This is only reproducible on the 'new-export-ui' branch by @vsverchinsky.**

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @vsverchinsky 's latest branch build:  audacity-win-3.4.0-alpha-20230731+e132f93-x64

This now works properly following the rebase onto the latest master.

**Comment by crsib** [comment]
This was fixed in #4962
