### ISSUE TITLE
AUDACITY_PATH env variable doesn't work

### ISSUE THREAD

**Issue by Godnyx** [audacity/audacity#497]
**Describe the bug**
I'm setting the AUDACITY_PATH env variable but when I open audacity it still generates a new config directory in ~ and doesn't reads the env variable.

I tried both:
export AUDACITY_PATH="$HOME/.config"
export AUDACITY_PATH="$HOME/.config/.audacity-data"

**To Reproduce**
1. Set AUDACITY_PATH env variable
2. Open Audacity

**Expected behavior**
To not generate new config files and read the path I'm setting up.

**Screenshots**
I think you don't need a screenshot in this case...

**Additional information (please complete the following information):**
 - OS: Manjaro Linux
 - Version: v2.3.3
 - (if relevant) Sound Device: (Probably) ALSA

**Additional context**

**Comment by SteveDaulton** [comment]
As far as I'm aware, the AUDACITY_PATH environmental variable has not been used in many years.
It is still included in Audacity's search path, as can be seen from the Nyquist command:
(print (get '*system-dir* 'plug-in))
but as far as I'm aware, it is no longer used.

**Comment by Godnyx** [comment]
Oh ok! Thanks a lot for your answer!
