### ISSUE TITLE
 problem When importing and changing the khz and it becomes faster and the audio file is smaller and also the khz

### ISSUE THREAD

**Issue by Nonman2** [audacity/audacity#4970]
### Bug description

**hello I'm new, and I wanted to do my first report so let's go, first problem I want to complain about the audacity program it's good but it has its flaws and I'm going to comment on some bugs and I don't know and I'm not sure if they are bugs, one thing what leaves me in agony is when you are going to import the audio And when you are going to see it, it stays at 48000hz if you put a random number of 490000hz an example: since it could be automatic, but ok, only then the second thing: when you change the hz to 384000hz the audio is so fast and sounding like a mouse's voice that when you look for the function and want to know why this is happening the audio is at 1.00x and you didn't understand why then another thing that I was also wanting to complain about.**

### Steps to reproduce

1- use ffmpeg
2- import audio from a program recorder
3- imported the audio try to change the hz
4- The audio simply had a smaller audio file and a mouse voice

### Expected behavior

when it matters but when it's recording it's normal.

### Actual behavior

only audio problems when you import.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

### Additional context

 the problem is what I mentioned in the bug description, because it doesn't apply the automatic hz settings, and also when importing the audio is fast and sounds like a mouse's voice  the playback speed is at 1.00x when it is at a higher khz.

**Comment by LeoWattenberg** [comment]
If you change the sample rate via the drop down in the track header, this is the expected behaviour. If you go to Tracks > Resample, it does what you expect it to do.

**Comment by dozzzzer** [comment]
Not a bug
