### ISSUE TITLE
Welcome dialog links are broken in Swedish

### ISSUE THREAD

**Issue by hikari-no-yume** [audacity/audacity#4972]
### Bug description

When Audacity starts, you get a dialog with a title along the lines of "Welcome to Audacity!". For Swedish specifically, its content is:

> Audacity 3.3.3
> Hur man får hjälp
> Dessa är våra sätt att ge support:
> * Snabbhjälp
> * Manual
> * Handledningar & Hur-göra
> * Forum - ställ din fråga direkt på Internet.

The first two links are broken:

* "Snabbhjälp" (Swedish for "quick help") links to https://manual.audacityteam.org/man/snabbhj%c3%a4lp.html which does not exist
* "Manual" links to some internal page within the software that also seems to not exist (only the text "hjälp:Huvudsida" shows up)

### Steps to reproduce

Install Audacity and select svenska (Swedish) as the language. Open Audacity and look at the welcome dialog.

### Expected behavior

Links should not be broken.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

I think I can see what went wrong here: the Swedish translation has not only translated the titles of the links, but also the destinations, which might not be what's expected. That's a common issue with badly designed localisation strings, so if that's the issue here, I expect Audacity has the same problems in some other languages too.

**Comment by petersampsonaudacity** [comment]
See also:
 Logging bugs information on the Audacity website fails to mention raising an issue on GitHub 
https://github.com/audacity/audacity-support/issues/40
