### ISSUE TITLE
Linux: Selection Toolbar loses second time control when dragged out of dock

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#4982]
### Bug description

When the Selection Toolbar is dragged out of it's docked position, the second time control disappears.

### Steps to reproduce

Drag the Selection Toolbar out of the dock.

### Expected behavior

![Expected](https://github.com/audacity/audacity/assets/11681097/93cdc2f2-aa51-4f85-b013-f754c68a1a20)

### Actual behavior

![Actual](https://github.com/audacity/audacity/assets/11681097/ef6668af-dfc4-4fbe-8d95-e89e5ad0434f)

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

**Comment by petersampsonaudacity** [comment]
Works fine on W10 and macOS12.6.7 Monterey with 3.3.3

**Comment by SteveDaulton** [comment]
> @SteveDaulton works fine for me on Ubuntu 22.04 with the most recent master

Are you using the AppImage release?

[This video shows a recent AppImage build on Ubuntu 22.04 ](https://youtu.be/pcaKW-sgPx4)

**Comment by dozzzzer** [comment]
> Are you using the AppImage release?

yes, sir!

https://github.com/audacity/audacity/assets/70063970/4dde2af5-d218-4a13-83ec-d993dc64909e
