### ISSUE TITLE
Linux: sudo needed to "Record on a New Track" While "Overdubbing"

### ISSUE THREAD

**Issue by SykkNyzz** [audacity/audacity#499]
The issue is the same as title (using a USB Mic)
sudo audacity fixes the issue where it shows my options to record

but...

**To Reproduce**
1. Go to 'Preferences'
2. Click on 'Record New Track and Overdub.'
3. Hit Record '....'
4. See error that just stops

**Expected behavior**
Recording to work on a new track while playing song

**Terminal Use**
Running these same steps with "audacity" results in:

```
ALSA lib pcm.c:8526:(snd_pcm_recover) underrun occurred
Expression 'err' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 3355
Expression 'ContinuePoll( self, StreamDirection_In, &pollTimeout, &pollCapture )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 3896
Expression 'PaAlsaStream_WaitForFrames( stream, &framesAvail, &xrun )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 4274
```

Every time I hit record with same setup. but as mentioned earlier, entering "sudo audacity" in terminal has none of this error.

**Comment by LWinterberg** [comment]
I can reproduce this in the 3.1.3 appimage

**Comment by SteveDaulton** [comment]
The issue does not occur for me with audacity-linux-3.1.3-x86_64.AppImage on Xubuntu 20.04

**Comment by LWinterberg** [comment]
I can no longer reproduce this on 22.04, so this probably resolved itself through something Ubuntu did
