### ISSUE TITLE
Audacity does not work on Debian Linux (error code=38: "function not implemented")

### ISSUE THREAD

**Issue by hansm629** [audacity/audacity#4993]
### Bug description

![스크린샷_2023-08-04_09-25-28](https://github.com/audacity/audacity/assets/101167173/23331056-c096-4f56-bd27-bed393ae90e0)

I installed Audacity on the Termux-X11 PRoot-Distro Debian
```
OS: Debian GNU/Linux trixie/sid aarch64
Host: samsung SM-S918N
DE : Xfce 4.18
Memory : 12GB
GPU : virgl
``` 
There are issues that are not running.

The error pop-up below will be generated.

```
**Audacity Startup Failure**           
Unable to create shared memory segment
error code=38 : "Function not implemented".
``` 

Termux-X11 PRoot-Distro Ubuntu 22.04 LTS
It runs well without the above symptoms.

But I want to solve the problem because I use Debian as the main.

The version is **audacity_3.3.3+dfsg-1_arm64.deb**.

### Steps to reproduce

1. sudo apt install audacity
2. run audacity
3. error code=38

### Expected behavior

The program must run.

It runs well on the Termux-X11 PRoot-Distro Ubuntu 22.04 LTS.

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

**Comment by LWinterberg** [comment]
Does the Appimage work?

**Comment by crsib** [comment]
> Does the Appimage work?

I'd be surprised. It seems that ARM Debian misses a kernel call we use for single instance checker.

**Comment by hansm629** [comment]
> Does the Appimage work?

No, the title image is not created and an error pop-up is generated immediately T_T

**Comment by LWinterberg** [comment]
It may be worth reporting this bug to the debian maintainers as well, https://www.debian.org/Bugs/Reporting

**Comment by isrgish** [comment]
I'm experiencing the same error
I'm running Ubuntu 23.10 on chroot with Linux Deploy on an android 13 device.

It used to work with the same setup on previous versions of Ubuntu, but then I was using an Android 10 device.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444) which uses a different build system. This bug should no longer be applicable.
