### ISSUE TITLE
Windows: Record crashes latest 3.4.0 alphas

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#4996]
### Bug description
Using Record as the initial action in the latest 3/4/0 alphas causes Audacity to crash.

_And note that the offer to send the error report fails to work._

Curiously if I import a stereo file first and then press Record the recording takes place normally

This is a regression 0m 3.3.3 and on earlier 3.4.0 alpha test builds

### Steps to reproduce
1. Launch latest 3.4.0 alpha
2. Press Record
3. Observe: Audacity crashes

Update from @Paul-Licameli : consider 2 x 2 x 2 = 8 possibilities to test
- Tracks already exist, or not
- Append-record (R) or record to a new track
- Stereo or Mono recording

Besides all that, try punch and roll too

### Expected behavior
Pressing Record as your initial command after launch should initiate recording

### Actual behavior
Pressing Record as your initial command after launch crashes Audacity

### Audacity Version
a) Pressing Record as your initial command after launch
b) audacity-win-3.4.0-alpha-20230804+48a1e8d-x64-msvc2022

### Operating system
Windows 10

### Additional context
Crashes with the two recent 3.4.0 alphas
a) Pressing Record as your initial command after launch
b) audacity-win-3.4.0-alpha-20230804+48a1e8d-x64-msvc2022

Works fine on previous alpha
c) audacity-win-3.4.0-alpha-20230802+f5851cd-x64-msvc2022

and works fine on 3.3.3

**Comment by petersampsonaudacity** [comment]
Tested on macOS 12.6.7  with latest alpha:  
audacity-macOS-3.4.0-alpha-20230804+ca2098e-x86_64 

Works fine on Mac - so assume Windows-only

**Comment by LWinterberg** [comment]
<details><summary>stack trace</summary>

```
>	lib-track.dll!std::list<std::shared_ptr<Track>,std::allocator<std::shared_ptr<Track>>>::begin() Zeile 1087	C++
 	lib-track.dll!TrackList::getBegin() Zeile 1370	C++
 	lib-track.dll!TrackList::MakeTrackIterator<Track>(std::pair<std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<Track>>>>,std::list<std::shared_ptr<Track>,std::allocator<std::shared_ptr<Track>>> *> iter) Zeile 1348	C++
 	lib-track.dll!TrackList::Find<Track>(Track * pTrack) Zeile 1068	C++
 	lib-track.dll!TrackList::FindLeader(Track * pTrack) Zeile 544	C++
 	lib-wave-track.dll!TrackList::Channels<WaveTrack>(WaveTrack * pTrack) Zeile 1207	C++
 	lib-wave-track.dll!WaveTrack::MoveTo(double origin) Zeile 332	C++
 	Audacity.exe!ProjectAudioManager::DoRecord(AudacityProject & project, const TransportSequences & sequences, double t0, double t1, bool altAppearance, const AudioIOStartStreamOptions & options) Zeile 909	C++
 	Audacity.exe!ProjectAudioManager::OnRecord(bool altAppearance) Zeile 754	C++
 	Audacity.exe!ControlToolBar::OnRecord(wxCommandEvent & evt) Zeile 565	C++
 	[Externer Code]	
 	Audacity.exe!AButton::Click() Zeile 603	C++
 	Audacity.exe!AButton::OnMouseEvent(wxMouseEvent & event) Zeile 438	C++
 	[Externer Code]	
 	Audacity.exe!AudacityApp::OnRun() Zeile 1740	C++
 	[Externer Code]	
 	Audacity.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Zeile 930	C++
 	[Externer Code]	

```

</details>

**Comment by petersampsonaudacity** [comment]
Also happens with Timer Record

**Comment by petersampsonaudacity** [comment]
Since no priority has been assigned to this I am going to assign P1

Audacity should just NOT crash when all you do is ask it to record - 3.4.0 surely cannot be released with such a basic crash bug, for me it really is a MUST-FIX.

_Apart from any other consideration I keep falling fould of this when testing aother issues in the alpha builds._

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @Paul-Licameli 's latest branch fix for this:  audacity-win-3.4.0-alpha-20230811+2294b4e-x64

First I get this:
![image](https://github.com/audacity/audacity/assets/50205984/1bb0af08-f410-4e41-b7f1-0c707551aafd)

Then after pressing the OK button I get:
![image](https://github.com/audacity/audacity/assets/50205984/750ea32a-1462-4a8f-909e-a84fa71d5971)

Then after pressing the OK or Cancel buttons Audacity crashes

**Comment by petersampsonaudacity** [comment]
Curiously if I add a step 

1.1 Tracks >Add New > Stereo Track

and the press Record in Step 2 - it records fine.

**Comment by Paul-Licameli** [comment]
> Curiously if I add a step
> 
> 1.1 Tracks >Add New > Stereo Track
> 
> and the press Record in Step 2 - it records fine.

Variables include:  existing track or not; R key or Shift+R; mono or stereo recording.

**Comment by petersampsonaudacity** [comment]
1. works with an existing track 
2. I was testing with the Record button in transport toolbar - not the command
3. Shift+Record also fails/crashes
4. Stereo and mono both fail/crash

**Comment by petersampsonaudacity** [comment]
Testing with @Paul-Licameli 's latest branch build:  audacity-win-3.4.0-alpha-20230812+6ad372f-x64

This now appears to work fine on W10 with Paul's branch build.

I tested:
1. stereo and mono
2. Play button
3. R shortcut key
4. Transport > Recording Record command
5. Shift modified recording
6. Timer Record

All work fine

**Comment by chinakov** [comment]
@petersampsonaudacity - thank you for your work. 
It seems good from my side as well - please merge this!
