### ISSUE TITLE
Import of audio file now (significantly?) slower

### ISSUE THREAD

**Issue by deus-e-x** [audacity/audacity#4999]
### Bug description

Hello dear Audacity team,

this is actually not a bug report but a heads-up to check whether a regression has crept in (i.e. a "just-in-case" report of sorts).

This is a comparison of the below-listed nightly builds:
audacity-win-3.4.0-alpha-20230804+ca2098e-x64-msvc2022
audacity-win-3.4.0-alpha-20230731+c8fda52-x64-msvc2022

Importing a FLAC audio file, 248 MB in size, takes about one second longer with the latest nightly build from 2023-08-04 compared to the nightly build from 2023-07-31 and earlier nightlies.

On the contrary, the export of mentioned 248 MB FLAC file is about half a second faster with the new audio export dialog in the current nightly from 2023-08-04.

Thank you for your ongoing support and further development of Audacity, guys.

### Steps to reproduce

1. Import a FLAC audio file of reasonable file size (e.g. my example is 248 MB) using the open dialog (Ctrl+O).
2. Measure the time it takes to import once you clicked/pressed the open button to execute the loading process. 
3. Repeat several times for reproducible results.

### Expected behavior

The time it takes to import the above-mentioned audio file (FLAC, 248 MB) would be at the same speed as in previous builds if that is possible with regards to the current restructuring of certain processes of Audacity.

### Actual behavior

As described above importing an example audio file (FLAC, 248 MB) takes ~1 second longer compared to older recent nightly builds.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS

**Comment by SteveDaulton** [comment]
I don't see a significant difference when testing with a 100 MB FLAC file (both versions take about 3 seconds), but with a large (75 MB) MP3 file, the latest alpha version is about 38% slower than Audacity 3.1. (Tested on Xubuntu  22.04, i7 + SSD)

**Comment by dozzzzer** [comment]
In my case (M1 Pro, macOS 13.0) the import of a 2h MP3 file is **significantly** slower: ~7.5s in 3.3.3 against ~17.7s in the latest `master`.

**Comment by DavidBailes** [comment]
> In my case (M1 Pro, macOS 13.0) the import of a 2h MP3 file is **significantly** slower: ~7.5s in 3.3.3 against ~17.7s in the latest `master`.

Windows 11, importing a 2h mp3 is roughly twice as slow in latest master vs 3.3.3 (roughly 14s vs 7s)
This isn't going to get fixed for 3.4?

**Comment by crsib** [comment]
There is a lot going on with Track interfaces right now. We want to have them stable before we assess the performance. 

Judging by what I see now only MP3 is affected (I might be wrong), there was a change in MP3 importer for gapless import.

**Comment by deus-e-x** [comment]
Importing of FLAC, as I stated in my first post, is affected as well.

**Comment by Paul-Licameli** [comment]
Remember that overlapping computation and i/o with more threads is a possibility that might make it faster than in old versions.

**Comment by DavidBailes** [comment]
> There is a lot going on with Track interfaces right now. We want to have them stable before we assess the performance.
> 
> Judging by what I see now only MP3 is affected (I might be wrong), there was a change in MP3 importer for gapless import.

I was concerned by @dozzzzer 's comment that this was to be checked after 3.4 is released, rather than before.
MP3 is a common format, and users may not appreciate imports taking twice as long, especially those with older hardware.
I did a check of removing the gapless flag, and it doesn't seem to make any difference to the import time.

**Comment by DavidBailes** [comment]
Time to import 2hr M4A and ogg vorbis have also roughly doubled.

**Comment by dozzzzer** [comment]
I did a quick test with the import of a 2-hour file:

|File Format| Avg time to import, 3.3.3 | Avg time to import, 3.4.2 |
|--------|--------|--------|
| MP3 | 7.951 | 19.112 |
| WAV | 3.707 |4.057 |
| FLAC | 11.731 | 12.234 |
| AIFF | 3.208 | 3.638 |
| M4A | 13.605 |  26.436 |

**Comment by petersampsonaudacity** [comment]
@dozzzzer 

I just tested on W10 with 3.4.2 versus @vsverchinsky 's branch build for this:  audacity-win-3.5.0-alpha-20240306+52fb883-x64

I imported a 2 hour stereo MP3 266MB

It took slightly longer on the new branch build than on 3.4.2 - 1m20 versus 1m06

**Comment by Paul-Licameli** [comment]
The PR has not yet passed code review.

I am recommending some simplification of it.

**Comment by Paul-Licameli** [comment]
Performance should also be tested in the wave-clip-refactoring branch after #6094 is completed.

**Comment by dozzzzer** [comment]
Testing PR #6129 gives the following results:

| File Format | Avg time to import |
|--------|--------|
| MP3 | 9.37 |
| WAV | 3.1 |
| FLAC | 13.31 |
| AIFF | 2.99 |
| M4A | 13.16 |

**Comment by petersampsonaudacity** [comment]
@Paul-Licameli @dozzzzer 

Testing on W10 with the latest 3.5.0 master:  audacity-win-3.5.0-alpha-20240316+3c07b93-x64-msvc2022

Initial testing shows that import of a large MP3 file is now even worse - taking twice as long as with 3.4.2

2 hour stereo MP3 size 259MB

a) on 3.4.2 import took 46 seconds
b) on 3.5.0 master import too 1minute 25 seconds

I can probably find some time next week to do some more extensive testing with differing file types.

**Comment by petersampsonaudacity** [comment]
@Paul-Licameli @dozzzzer @LWinterberg 

OK so I found some time to resurrect one of my old time testing macros (one for import testing)

I only ran a single import of a one-hour stereo file in various formats - the results are nowhere near as concusive as yesterday's stark result.

![image](https://github.com/audacity/audacity/assets/50205984/1bc93dbf-2719-40f7-8ef3-c1909d0e9d04)
orange cells = worst times
green cells = best times

I have an extended version of the Macro which allows me to run the import for each file type multiple times - I was thinking 5 or 7 to get a fair average.  I can probably find some time tomorrow to run this test

**Comment by deus-e-x** [comment]
@petersampsonaudacity 

Thank you for retesting. It confirms my findings that import timings for FLAC audio files got worse since the v3.4.2 release, and even the early v3.5.0 (20240111+621db51) build.

For me a 40 min FLAC file (~260 MB)now  takes about 1 to 1.5 seconds longer to import with the lastest build 3.5.0-alpha-20240316%2B3c07b93-x64-20.04.

Here's hoping the audacity team can further improve the timings of the audio import. 👍

**Comment by petersampsonaudacity** [comment]
So I spent some time yesterday evening running a set of tests on 3.3.3, 3.4.2 and 3.5.0 latest master build.

My macro had 5 sets of imports of a one-hour stereo file in the various formats

![image](https://github.com/audacity/audacity/assets/50205984/da2b6805-79f4-4025-9ee0-c5af1ee3e569)

This appears to show that the latest 3.5.0 master is deed an improvement in this regard on 3.4.2 and 3.3.3

@deus-e-x 
note that from these tests of mine it shows that 3.5.0 master offers a good improvement for FLAC

**Comment by LWinterberg** [comment]
Given that we're reproducibly within margin of error to 3.3.3 again, I'd say there's nothing more that needs to be done here.

**Comment by petersampsonaudacity** [comment]
@LWinterberg 

I had thought that @Paul-Licameli Paul was hoping for improvement in speed rather than just matching 3.3.3 (bug-fixing 3.4.2)

**Comment by LWinterberg** [comment]
That's the wave-clip-refactoring branch, which is massive and won't make it into 3.5.

**Comment by deus-e-x** [comment]
I did some more testing here after petersampsonaudacity posted his new results. Many thanks to Peter for your efforts and dedication, going strong as always! 😊👍

Previously, I always measured the import timings including Audacity's application start. For me, older versions of Audacity load slightly faster, which may be due to the older versions of Audacity having a lesser amount of additional libraries in Audacity's program folder.

This time I measured import timings with Audacity already running. The audio import of 20240316+3c07b93 appears to be nearly the same compared to the earlier release 20240111+621db51.

So agreed, there's probably not that much to be gained here anymore. But don't let that stop you, should you have any further ideas and tricks in your sleeves worth trying. 

Many thanks to the Audacity team, you guys rock. 👏👍

**Comment by petersampsonaudacity** [comment]
@deus-e-x 

Here is a trimmed version of my Macro which would enable you to run import test timing of FLAC imports using the inbuilt logging with Macro Trace.

You would,of course. have to change your filenames (import FLAC file and the outputted report) and pathing to your own rather than mine.

![image](https://github.com/audacity/audacity/assets/50205984/6b47bfde-b812-4a1b-8fb4-d5485dbe84ba)

See this page in the manual:  https://manual.audacityteam.org/man/performance_testing_using_macro_trace.html

**Comment by deus-e-x** [comment]
@petersampsonaudacity

Thank you for sharing, much appreciated.
