### ISSUE TITLE
Repair (some) destructive effects

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#5003]
[The PR introducing stretching of audio clips](https://github.com/audacity/audacity/pull/4881), when merged, will break the destructive effects if stretching is used (either by changing project tempo or by stretching individual clips).

This ticket is the first of a series (possibly of length 1, if we're lucky) whose aim is to repair some or all of the destructive effects. Detail: Work will begin on so-called `PerTrackEffect`s, which is the base class for a number of effects. The exact list of effects that this will repair is unknown at the time of writing.

**Comment by Paul-Licameli** [comment]
You are very likely to conflict with my work and maybe you have incompatible ideas.

i intend one more PR that will disturb PerTrackEffect again.  I will limit scope of that PR and open it today.  You should base any work into it.
