### ISSUE TITLE
Export no longer has a warning message for invalid extension

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#5005]
### Bug description
On Export there is no longer a warning message displayed when the user specifies an invalid file extension - either garbage or the wrong file-type.

This is a long-standing regression - a regression on 2.1.1

### Steps to reproduce
1. launch audacity
2. generate  a 30 second chirp
3. Go to the File Export/Export Audio dialog 
4. leave the file type as default WAV
5. specify the file name as test.garbage (or test.mp3)
6. Observe: the file is exported with the specified file extension (.garbage or .mp3) - but with **_NO_** warning message
7. Examine the file with Windows Explorer _(or similar on Mac/Linux)_
8. Observe: the exported file is indeed a WAV file but with a false extension

### Expected behavior
![image](https://github.com/audacity/audacity/assets/50205984/4f04b622-0181-4f06-a25f-95409f9e1d05)

### Actual behavior
No warning message

### Audacity Version
3.4.0 latest alpha and 3.3.0-2.1.2

### Operating system
Windows 10 - but assume all OS

### Additional context
The Manual specifies, on this page, that there should be such a warning :  https://alphamanual.audacityteam.org/man/File_Export_Dialog

![image](https://github.com/audacity/audacity/assets/50205984/3f054e41-1c08-4061-91db-f32976848f4e)

Many thanks to @vsverchinsky  for helping to catch this.

**Comment by LWinterberg** [comment]
As laid out in #5007, I much prefer being sure that we always have a valid extension, making this case impossible to reach.
