### ISSUE TITLE
New Export: if no extension is specified, export no longer supplies the appropriate extension

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#5007]
### Bug description
With the new Export, if no extension is specified, export no longer supplies the appropriate extension.

This is a regression on 3.3.3 and earlier

### Steps to reproduce
1. launch 3.4.0 latest alpha
2. generate a 30 second chirp
3. File > Export Audio
4. specify a filename without and extension,  **test** say
5.  Observe the file is exported without a file extension

### Expected behavior
Appropriate file extension to be added for the exported file type

### Actual behavior
No extension added on export - and no warning message

### Audacity Version
3.4.0 alpha

### Operating system
Windows 10 - but assume all OS

### Additional context
See also #5005

**Comment by petersampsonaudacity** [comment]
The Manual specifies that this should indeed be the case:
![image](https://github.com/audacity/audacity/assets/50205984/4a6448f0-8f2d-4f96-a879-2197f5837b96)

**Comment by LWinterberg** [comment]
We probably have 3 option to handle this: 

1. Just let the user do their thing; if they didn't say .wav, they didn't say .wav. 
2. Warn the user before export if they messed up  (#5005)
3. Always auto-complete to the appropriate file type as soon as the user goes into another field or clicks export. 

Out of these options, option 3 probably is the only one worth going for, given that Windows just can't do anything with the files otherwise. It fixes #5005 automatically as there just never *can* be wrong extension. 

The other options feel weaker to me. If we go for option 2, album numberings like "4.Blossom" would show a "your wav has a `.Blossom` extension, do you want to go back and fix that?", which feels more annoying. And option 1 just would produce "broken" files for most users.

**Comment by lededev** [comment]
I need extenstion automatic completion back, when in v3.3.3, the export dialog, I have a filename `out`, if type is WAV (Microsft), it will export `out.wav`, but on v3.4-alpha, it export `out` file no extension.

**Comment by petersampsonaudacity** [comment]
@LWinterberg  of your options Leo, I am minded to favour option 3:
**Always auto-complete to the appropriate file type as soon as the user goes into another field or clicks export.**

**Comment by dozzzzer** [comment]
Related https://github.com/audacity/audacity/issues/5416

**Comment by petersampsonaudacity** [comment]
@LWinterberg @dozzzzer 

See this recent Forum thread:  https://forum.audacityteam.org/t/can-not-export-as-mp3-with-new-update/88893

**Comment by dozzzzer** [comment]
@LWinterberg I wonder if we also should auto-complete with a proper extension when "Custom FFmpeg Export" is selected and the **Format** and the **Codec** are selected? In its current state, #5482 doesn't allow for this.

**Comment by crsib** [comment]
According to the comment from @vsverchinsky - ffmpeg doesn't return such information

**Comment by petersampsonaudacity** [comment]
> @LWinterberg I wonder if we also should auto-complete with a proper extension when "Custom FFmpeg Export" is selected and the **Format** and the **Codec** are specified?

I think thatbyou also need to auto-complete dor all File tyes when the user specifies a filename with no extension

See these STRs that I wrote in the recent forum thread complaining about this:

>Try these steps:
1. import a WAV file or record some audio
2. **File > Export Audio**
3. Change the export  Format to be **MP3 Files**
4. Observe:  offered File Name is:   <project name>.mp3 - with the .mp3 extension
5. Export button to export it
6. Observe you have a proper MP3 file
7. File > Export Audio
8. Observe:  Format remains as MP3 Files and offered File Name remais as before
9. change the File Name - but do NOT add the extension
10. Export button to export the audio
11. Observe: a file is exported but it is not identified as and MP£ file and it carries no extension.
>
>The simple workaound is:
a) add the .mp3 extension manually, or
b) click the Format dropdown and re-select MP3 files
>
>BTW this affects not just MP3 but all the other export formats in the same way.

**Comment by LWinterberg** [comment]
With the exceptions of custom ffmpeg export and external program, it should autocomplete the file name as soon as you click off the text field. Is that not the case in the build?

**Comment by petersampsonaudacity** [comment]
Doesn't work for me in the STRs is listed above!

**Comment by LWinterberg** [comment]
ah, I see the distinction: When clicking "export" _directly_ after the name, the extension is not appended.

**Comment by dozzzzer** [comment]
@petersampsonaudacity Peter, chances are you're looking at the wrong build: I've just re-checked that particular use case you mentioned in [the PR linked to this issue](https://github.com/audacity/audacity/actions/runs/6744245692/job/18333697994?pr=5482) and it works perfectly for me.

**Comment by petersampsonaudacity** [comment]
@dozzzzer 

Sergey, testing on W10 with the latest 3.4.1 Beta test build:  audacity-win-3.4.1-beta-20231106+3897888-x64-msvc2022

Following my steps above O still get the same prob;em at steps 9-11

Though as Leo points out if I add Steps 
9.1 change the Folder location
9.2: Observe: the file extension is then added to the name.

And of course all is fine after that.

**Comment by petersampsonaudacity** [comment]
Ah, but branch build testing

Testing on W10 with @vsverchinsky 's branch build for this fix:  audacity-win-3.4.1-alpha-20231103+b08b1c7-x64

This now appears to work fine on Vitaly's branch

If the user has a Filename without an appropriate extension and then presses the Export button
a) the appropriate file extension is added in the dialog
b) a file of the identifiably correct format is exported

@crsib @LWinterberg @dozzzzer :  perhaps the fix PR #5482 could be pulled into the 3.4.1 Beta?

**Comment by dozzzzer** [comment]
> perhaps the fix PR https://github.com/audacity/audacity/pull/5482 could be pulled into the 3.4.1 Beta?

yes, we plan to include it in 3.4.1
