### ISSUE TITLE
Resizeable clip pointer is difficult to distinguish from Selection pointer.

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#5009]
### Bug description

When the mouse pointer is over the clip resizing hot zone, it should change to a pointer that indicates that the clip can be resized. In Audacity 3.3 the pointer changed to a double headed arrow <->

### Steps to reproduce

1. Try resizing an audio clip

### Expected behavior

When the mouse pointer is over the top half  of either left or right edges, the pointer changes to indicate that the clip may be resized.

### Actual behavior

The pointer does not change, though it does change to indicate that the selected area  may be resized.
Update: It does actually change, but the change is so small that I failed to see that it had changed.

![resize_clip](https://github.com/audacity/audacity/assets/11681097/e0221fa4-7a31-4855-bbe5-9a407d30a383)

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

**Comment by petersampsonaudacity** [comment]
You now (with latest 3.4.0 alpha) get the square brackets icon for resizing - but it only works at the clip-handle drag-bar.

I Have no ide if that is intentionsl, by design, or a bug.

**Comment by SteveDaulton** [comment]
Oh yes, it does change from I to [ but that's not so easy to see with less than perfect eyesight and a very small pointer icon. It is somewhat easier to see if I reduce the DPI but who wants to change their monitor DPI just to use one app?

**Comment by LWinterberg** [comment]
![image](https://github.com/audacity/audacity/assets/87814144/ebcab6f3-6dad-47ab-8f93-8f9a127a936c)

I fixed it by angling the Ibeam a bit

**Comment by petersampsonaudacity** [comment]
@LWinterberg  - wow Leo, that's the first time the I-bream cursor has ever changed in the whole of Audacity's history all the way from 1.0.0 through to 3.3.3

**Comment by petersampsonaudacity** [comment]
@LWinterberg  - note that the Selection tool in the tools toolbar though still has the old traditional flat-topped/flat-bottomed I-beam.
