### ISSUE TITLE
"Beep on completion of longer activities" is non-functional

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#5018]
### Bug description

The "Beep on completion of longer activities" option is non-functional.

### Steps to reproduce

1. Enable the "Beep on completion of longer activities" option in Preferences > Interface
2. Perform an action that takes more than a minute. I used "Paulstretch" on a long track.

### Expected behavior

Audacity to play a beep when activities lasting longer than a minute are completed.

### Actual behavior

No beep.

### Audacity Version

current master / alpha / nightly build

### Operating system

All

### Additional context

https://manual.audacityteam.org/man/interface_preferences.html

**Comment by daksh-code** [comment]
can I work on this?
