### ISSUE TITLE
Undoing anything clears the realtime FX stacks

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#5020]
### Steps to reproduce

1. Create track and add one or more real-time effects.
2. Do and undo anything.

### Expected behavior

Real-time FX stack is unaffected.

### Actual behavior

Real-time FX stack is cleared.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

### Additional context

Video from @Tantacrul on our private Discord channel : https://discord.com/channels/822396597085667338/1009022077166170122/1139185856851214396

This is a regression on 3.3.3

**Comment by Paul-Licameli** [comment]
bisected to 640275ef394617e6802131c3840250c41d862134

**Comment by Paul-Licameli** [comment]
Bisected to 640275ef394617e6802131c3840250c41d862134

**Comment by chinakov** [comment]
Tested, and fixed! Thank you!

**Comment by petersampsonaudacity** [comment]
Tests fine on W1- with latest 3.4.0 alpha:  audacity-win-3.4.0-alpha-20230814+8bf108e-x64-msvc2022
