### ISSUE TITLE
Importing audio files fail on local builds with macOS M1

### ISSUE THREAD

**Issue by nwang92** [audacity/audacity#5025]
### Bug description

On commit dfc4854b64933a494af0ad0f0d396bcfa373eb83, it seems like the import file functionality is broken on macOS M1. I've tried a few different formats (FLAC, WAV, MP3) and they all seem to result in the error dialog saying "Audacity did not recognize the type of the file".

I can run the latest release of Audacity just fine, it seems to be a problem with local builds. Not sure if this is isolated to arm64 either but it's happening there for me.

Some other symptoms:
* Preferences dialog is missing the "Libraries" menu completely so I can't check whether or not ffmpeg was detected
* About dialog says ffmpeg support is enabled

### Steps to reproduce

1. Check out commit dfc4854b64933a494af0ad0f0d396bcfa373eb83
2. Build using instructions in BUILDING.md https://github.com/audacity/audacity/blob/master/BUILDING.md#macos-1 
3. Run the local build through Xcode and try importing a file into Audacity (drag-and-drop or via menu or programmatically)

### Expected behavior

File import works

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

**Comment by crsib** [comment]
Most likely that means that you have built only Audacity, not the ALL target.

**Comment by nwang92** [comment]
Adding some more artifacts.

Here's the full output of my `cmake -GXcode ../audacity`: [build.log](https://github.com/audacity/audacity/files/12325270/build.log)

Screenshot of what I see when drag-and-dropping a file:
<img width="473" alt="Screenshot 2023-08-11 at 2 34 34 PM" src="https://github.com/audacity/audacity/assets/6201822/ff26d801-1e83-4f75-9ae9-6b4ca8c91229">

Missing preferences:
<img width="184" alt="Screenshot 2023-08-11 at 2 36 28 PM" src="https://github.com/audacity/audacity/assets/6201822/7e21778a-9b56-4605-a266-4aebe0eb6f36">

**Comment by nwang92** [comment]
> Most likely that means that you have built only Audacity, not the ALL target.

Is there a build option I need to supply to `cmake -GXcode ../audacity` to build that target? For what it's worth, I went back to commit dd68c485685f7caf188d30ba02a1349f055e4f7a and a local build from there works as expected.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444) which uses a different build system. This bug should no longer be applicable.
