### ISSUE TITLE
Implementation/Moving to WinUI 3

### ISSUE THREAD

**Issue by meierac** [audacity/audacity#5026]
### Your idea

Would be nice to move the UI to WinUI 3 to get some fresh look into this program. I know the UI is the same on all operating systems, but maybe it’s time to either split them up or find a modern/good looking solution to work for all OS. 

### Problem to be solved

Splitting up GUI per OS. Implementing WinUI 3

### Additional context

Of course low priority but it will come the day some one else does publish a better looking software with the same functionality and which is free as well.

**Comment by LWinterberg** [comment]
We're currently porting Audacity to Qt which solves this. You can see some of the initial Qt builds [here](https://github.com/audacity/audacity/actions/workflows/build_qt.yml), which don't yet have usable levels of functionality but do showcase some of the button/layout choices we've made.
