### ISSUE TITLE
HiDPI issues

### ISSUE THREAD

**Issue by prokoudine** [audacity/audacity#503]
There is a number of UI/UX issues quite visible when using Audacity on a HiDPI display (Linux, wxGTK3):

- pixelated text in custom widgets
- low-resolution icons
- text not fitting respective parts of UI
- combo boxes get cut off

![image](https://user-images.githubusercontent.com/57467/80292188-3e96cd00-875d-11ea-94f3-fadfa7b96e40.png)

Hopefully, you could address some of that in the future.

**Comment by lllucius** [comment]
Absolutely!  It drive me crazy as well.  It won't be in the upcoming release (out soonish), but this will be one of my main chores for the next one.

**Comment by Marat-Tanalin** [comment]
Under Windows, Audacity is not DPI-aware at&nbsp;all, so GUI (including the latest Audacity&nbsp;3.0) is entirely blurry (W7) or&nbsp;pixelated (W10 at&nbsp;integer OS-level zooms like 2.0=200%) by&nbsp;default.

Enabling enhanced DPI scaling (DPI virtualization) via the executable properties (“System (Enhanced)” mode) somewhat helps under Windows&nbsp;10:

“Properties”&nbsp;→ “Compatibility”&nbsp;→ “Settings”&nbsp;→ “Change high DPI settings”&nbsp;→ “High DPI scaling override”&nbsp;→ “Override high DPI scaling behavior. Scaling performed by”&nbsp;→ “System (Enhanced)”.

That, compared with regular (non-enhanced) “System” DPI mode used by default for non-DPI-aware apps, at&nbsp;least makes some GDI-rendered texts rendered in&nbsp;full resolution. Though icons and some non-GDI texts are of&nbsp;course still pixelated.

<details>
<summary>Screenshot</summary>

![w10-system-enhanced](https://user-images.githubusercontent.com/1833563/111547754-b06b7100-878a-11eb-8be7-f136ddb4a19a.png)
</details>

**Comment by eszlari** [comment]
Under Linux with:
```
GDK_DPI_SCALE=0.5
GDK_SCALE=2
```
wxWidgets `3.1`:

![audacity_gtk_scale_2x](https://user-images.githubusercontent.com/15569934/111690001-fa0c9800-882c-11eb-84bb-2a66878ceea1.png)

wxWidgets `3.0`:

![audacity_wx3 0_gtk_scale_2x](https://user-images.githubusercontent.com/15569934/111690512-9171eb00-882d-11eb-95b6-a5127efb6154.png)

Now with Audacity 3.0 you have forced the use of wxWidgets 3.1 at compile time. Please fix the HiDPI issues or allow compiling with wxWidgets 3.0 again.

**Comment by DasJott** [comment]
Audacity currently not usable at all.
![image](https://user-images.githubusercontent.com/6298761/125603453-45299bae-508e-43ef-ab40-95354ba5afb6.png)

**Comment by DasJott** [comment]
In V3.0.2 it is different, but still unusable and far from good looking:
![image](https://user-images.githubusercontent.com/6298761/125608290-00dc37a7-8bcd-4aa0-9ad7-d4b72e0ad199.png)

Installed this by flatpak on Solus OS.

**Comment by MarkJeronimus** [comment]
For Linux users, you can use https://github.com/kaueraal/run_scaled/ to work around it.

**Comment by rrthomas** [comment]
@MarkJeronimus I tried this, but unfortunately while almost everything worked, the view of the audio (the waveforms) are only drawn once, and then never redrawn when I zoom/pan etc.

**Comment by LunaGNUisance** [comment]
GNOME, 200% DPI, compiled it via the AUR with conan. But these issues are present on the (broken) AppImages as well.

GDK_SCALE seems to fail on startup. It looks the same whether it's 100% or 200% scaled on GNOME.

```
(process:31817): Gdk-CRITICAL **: 17:03:55.196: IA__gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed

(process:31817): Gdk-CRITICAL **: 17:03:55.197: _gdk_pixmap_new: assertion '(drawable != NULL) || (depth != -1)' failed
/home/luna/.conan/data/wxwidgets/3.1.3.1-audacity/_/_/build/130288072304580eba516027ffe9f26f82ad6965/source_subfolder/src/gtk/bitmap.cpp(827): assert ""IsOk()"" failed in ConvertToImage(): invalid bitmap
/home/luna/.conan/data/wxwidgets/3.1.3.1-audacity/_/_/build/130288072304580eba516027ffe9f26f82ad6965/source_subfolder/src/common/image.cpp(2172): assert ""IsOk()"" failed in SetMaskColour(): invalid image
/home/luna/.conan/data/wxwidgets/3.1.3.1-audacity/_/_/build/130288072304580eba516027ffe9f26f82ad6965/source_subfolder/src/common/image.cpp(2223): assert ""IsOk()"" failed in SetMask(): invalid image
/home/luna/.conan/data/wxwidgets/3.1.3.1-audacity/_/_/build/130288072304580eba516027ffe9f26f82ad6965/source_subfolder/src/common/image.cpp(1853): assert ""IsOk()"" failed in GetWidth(): invalid image
/home/luna/.conan/data/wxwidgets/3.1.3.1-audacity/_/_/build/130288072304580eba516027ffe9f26f82ad6965/source_subfolder/src/common/image.cpp(1860): assert ""IsOk()"" failed in GetHeight(): invalid image
/home/luna/.conan/data/wxwidgets/3.1.3.1-audacity/_/_/build/130288072304580eba516027ffe9f26f82ad6965/source_subfolder/src/common/image.cpp(2112): assert ""IsOk()"" failed in GetAlpha(): invalid image
/home/luna/.conan/data/wxwidgets/3.1.3.1-audacity/_/_/build/130288072304580eba516027ffe9f26f82ad6965/source_subfolder/src/common/image.cpp(2232): assert ""IsOk()"" failed in HasMask(): invalid image
/home/luna/.conan/data/wxwidgets/3.1.3.1-audacity/_/_/build/130288072304580eba516027ffe9f26f82ad6965/source_subfolder/src/common/image.cpp(1986): assert ""IsOk()"" failed in GetData(): invalid image

(process:31817): GdkPixbuf-CRITICAL **: 17:03:55.197: gdk_pixbuf_new_from_data: assertion 'data != NULL' failed

(process:31817): Gdk-CRITICAL **: 17:03:55.197: IA__gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed

(process:31817): Gdk-CRITICAL **: 17:03:55.197: IA__gdk_drawable_get_display: assertion 'GDK_IS_DRAWABLE (drawable)' failed

(process:31817): Gdk-CRITICAL **: 17:03:55.197: IA__gdk_cursor_new_from_pixbuf: assertion 'GDK_IS_DISPLAY (display)' failed

(process:31817): GLib-GObject-CRITICAL **: 17:03:55.197: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```
![audacity-hidpi-problems](https://user-images.githubusercontent.com/78894455/150287936-13878418-f75e-4026-81c7-8b1621504448.png)

**Comment by realh** [comment]
Also, if you try to drag one of the toolbars it jumps to the top left of the window, and a small black triangle gets superimposed and jiggles randomly between pointing down and left when you move the mouse.

How much of this is unique to Audacity and how much is down to wxWidgets/wxgtk3?

**Comment by Kwadz** [comment]
@LWinterberg, it is closed in favour of which issue please? I'd like to subscribe to the good one.

**Comment by LWinterberg** [comment]
no issue, but Audacity 4.0 won't be using wxWidgets at all.

**Comment by realh** [comment]
Cool. Are you switching to Qt?

**Comment by LWinterberg** [comment]
yep

**Comment by batteredhedgehog** [comment]
I am still experiencing dpi issues on ubuntu 22.04 with audacity-linux-3.5.1-x64.AppImage
I have tried setting the various QT scaling environment variables with no effect.
Is there some way to fix this that I am missing?

**Comment by emilrueh** [comment]
what is the state of high dpi support for audacity? any fix if not official? am on 4k Arch linux and the ui is very small.
