### ISSUE TITLE
Behavior disparity for Selection icon and Clip Shrink/Expand icon

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#5030]
### Bug description
The I-beam selection icon only operates when in the actual waveform.

In contrast once the Clip shrink/expand icon is activated it continues to operate outside the waveform - and not only when remaining in the Audacity Window - it also operates outside the Audacity window

### Steps to reproduce
1. Generate a 30 second chirp
2. zoom out 1 level and shift the clip to mid-screen
3. left-click in the waveform and hold button down (to initiate click&drag selection)
4. Still holding the left mouse button down, move the mouse left or right within the waveform
5. Observe: selection is made
6. Still holding the left mouse button down, move the I-beam cursor down out of the waveform into the gray of the Audacity window - and move cursor left or right
7. Observe: the cursor remains as the I-beam but has no effect on the selection.
8. Release left mouse button
9. Hover the I-beam over the upper third left edge of the clip so that the cursor changes to the Clip Shrink/Expand icon
10. Left click and hold left button down
11. Still holding the left mouse button down, move the mouse right within the waveform
12. Observe: Clip is shrunk from the left
13. Still holding the left mouse button down, move the I-beam cursor down out of the waveform into the gray of the Audacity window or even out of the Audacity Window - and move cursor right
14. Observe: the clip continues to shrink from the left

### Expected behavior
The Clip Shrink/Expand cursor should act like the Selection cursor and only operate when it is within the waveform.

It should certainly **not** operate outside the Audacity window

### Actual behavior
The Clip Shrink/Expand cursor continues to operate outside the waveform and even outside the Audacity window

### Audacity Version
3.3.3 and latest 3.4.0 master  - _so independent of recent icon change for the Clip Shrink/Expand cursor_

### Operating system
Windows 10 ad macOS 12.6.7 Monterey - so assume all OS

### Additional context
None

**Comment by petersampsonaudacity** [comment]
Note that the sliders in:
a)  meter toolbars
b) Play-at-Speed
c) Pan & Gain in the TCP
all only operate when the cursor (arrow cursor) remains within the slider.

**Comment by petersampsonaudacity** [comment]
But the slider for the Sound Activated Recording level in recording preferences also operate out side the slider and outside the Audacity window like the Clip Shrink/Expand cursor

**Comment by LWinterberg** [comment]
PAS/meter/Pain & Gain sliders in the track header follow the Windows _scrollbar_ standard, where when you move too far away from the thing it snaps back to where you started. Effects sliders going all the way also is consistent with the Windows slider standard.

Selection not moving as soon as it moves outside a track seems like a technical consequence of it being able to do multi-track selections, so when there's no track, the selection doesn't update while within the Audacity window. Once you move with the selection outside the window to the left or right, it starts moving the selection and the viewport.

**Comment by petersampsonaudacity** [comment]
> Selection not moving as soon as it moves outside a track seems like a technical consequence of it being able to do multi-track selections, so when there's no track, the selection doesn't update while within the Audacity window. Once you move with the selection outside the window to the left or right, it starts moving the selection and the viewport.

Exactly - and I expect that behavior for selection.

But I also expect that the shrink/expand for a clip should similarly only work when the cursor is within the bounds of the clip or the waveform

**Comment by petersampsonaudacity** [comment]
> PAS/meter/Pain & Gain sliders in the track header follow the Windows _scrollbar_ standard, where when you move too far away from the thing it snaps back to where you started. Effects sliders going all the way also is consistent with the Windows slider standard.

@LWinterberg  BTW this appears not to be true for the sliders in the latest Qt build:
audacity-win-3.4.0-alpha-20230814+7b893ab-x64

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
