### ISSUE TITLE
Use highest sample rate in a track to determine export default

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#5032]
The default export rate offered in the export dialog should have the following properties: 

1. When the export dialog is summoned for the first time in a project, the sample rate of the highest sample rate track in the project is chosen (or the next best)
2. After an export is made, the selected sample rate setting is remembered for this project's future export

<details> <summary>original report</summary>

### Your idea

To make it less cumbersome to choose an appropriate sample rate when exporting.

### Problem to be solved

1. Open an old Audacity  project that has a lot of tracks.
4. "File menu > Export Audio".
5. Notice that a sample  rate for the exported audio is set to whatever sample rate was used last.

* If the selected sample rate is too low, then high frequency content will be lost.
* If the selected sample rate is too high, then the exported file will  be unnecessarily bloated.
* For the exported file to sound the same as the project, the sample rate of the exported file must be the same or higher than the Project rate.
* To avoid data loss, the exported sample  rate must be at least as high as the highest track sample  rate.

6. Notice that although you can see the sample rate that will be used for the exported file, you can't see what the Project rate is, and you can only see the track  sample rates for tracks that fit into the tracks  window, and only if the tracks are sufficiently expanded (vertically) to see their sample rates.
7. Close the Audio Export window.
8. Check the Project rate and/or track sample rates as necessary.
9. Reopen the Audio Export dialog and set the sample rate as required.

Even when you know that the sample  rate in the export dialog  may not be appropriate, it is still cumbersome to have to manually check the Project rate from "Audio Setup > Audio Settings" before exporting, just to be sure that the exported file will sound the same as the project.

### Prior art

In older versions of Audacity, the Project Rate was visible in the main screen, and the exported file sample rate was automatically selected to have the same audio bandwidth as the project.

### Additional context

Using the "last used" sample rate is not very useful. Maybe better to default to the Project rate, or to the highest track sample rate, or the higher of these two sample rates. This feature request is not intended to prescribe an optimal solution, but rather to raise the issue as something that would benefit from improvement.

</details>

**Comment by LWinterberg** [comment]
Checking the project rate prior to exporting is probably unhelpful, eg. if you previously had exported 8k and changed the project rate for it. 

Defaulting to the highest track sample rate sounds very sensible though.

**Comment by petersampsonaudacity** [comment]
> Defaulting to the highest track sample rate sounds very sensible though.

Yes, but that conflicts with "last-used" which a lot of folk seem to want  - for example, this Forum poster from yesterday: 
https://forum.audacityteam.org/t/permanent-settings-for-format-options/82046

**Comment by crsib** [comment]
I agree with @petersampsonaudacity, I think this issue needs more work from the design team. Probably we should find a way to show a "preferred" sample rate for exporting

**Comment by LWinterberg** [comment]
I'll do a better spec for this, but not this patch

**Comment by SteveDaulton** [comment]
I think this proposal needs some modification now that Audacity has a sample rate option in the Export Dialog that has been decoupled from the Project Rate,

I still think that the default  case should be the minimum sample rate that avoids data loss, but now that the export sample rate has an independent control in the export dialog, (decoupled from the Project Rate), users should have additional ways to override the default export rate.

I've not yet fully thought through the details, but my inclination right now is for the Export dialog to support "presets". Audacity could provide a few common case factory presets, plus user presets.

If a preset Export profile is selected, then that would override automatically defaulting as described in the original proposal.

Example Factory Presets:

- **CD audio: Rate**=44.1kHz, Channels=stereo, Format=WAV 16-bit
- **Podcast audio:** Rate=44.1kHz, Channels=mono, Format=MP3 Constant 128kbps
- **MP3 [high quality]:** Rate=44.1kHz, Channels=Auto, Format=MP3 Preset Extreme
- **Last used:** Retain the last used settings
- **Last used format [Auto]:** Retain last used format, with Rate and channels auto-selected to match the project.

("Last used format [Auto]" may be a good out-of-the-box default).
