### ISSUE TITLE
Snap Increments are not Even with Musical Gridlines

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#5039]
### Bug description

If the User chooses to work with Bars and Beats gridlines, and then selects 'Bar' as the Snap step, and tries to move around the project, the movements won't follow the 'Bar' size at a certain point. 

This happens to any 'Snap' value - the increments are uneven. At some point, the increments align themselves correctly once again, but it depends on the value of the snap increment. 

### Steps to reproduce

1 . Launch Audacity, add a mono track
2. Select 'Beats and Measure' via the Ruler
3. Define Tempo (88BPM) in (View -> Toolbars -> Time Signature Toolbars (Beta)
4. Switch to 'Bar:Beat:Tick' in Time Toolbar 
5. Enable 'Snap' > select "Bar" as an interval
6. Align the cursor at the beginning of the project (**001bar01beat01**)
7. Press 'Right Arrow Key' 
8. Observe **002bar01beat01** as the value of the Time Toolbar (**which is correct**)
9. Press 'Right Arrow Key' until you get to **027bar01beat01**
10. Press 'Right Arrow Key' once again - you get **027bar04beat04**, but you should be getting **028bar01beat01**

### Expected behavior

User can scroll with Snap throughout the entire project in the increment of 1 bar, , or any other increment. 

### Actual behavior

User can't scroll with snap throughout the entire project in the increment of 1 bar, or any other increment. 

### Audacity Version

other

### Operating system

macOS

### Additional context

This is only reproduced on the crsib:4931_musical_gridlines branch.

**Comment by LWinterberg** [comment]
This is not exclusive to Dmitry's build, here's an example of it in current master.

![image](https://github.com/audacity/audacity/assets/87814144/3de7af66-ea74-4608-9851-b0f166a101be)

NB: This is dependent on the tempo, it happens at 119, 117 bpm; at 95 bpm it even goes to 39.04.3

![image](https://github.com/audacity/audacity/assets/87814144/65366636-ddfe-4f54-ad07-7e32a1b86e5f)

**Comment by petersampsonaudacity** [comment]
Testing on W10 with 3.3.3 and the latest alpha for 3.4.0

I cannot reproduce this on Windows
![image](https://github.com/audacity/audacity/assets/50205984/c3886304-32f2-4b38-a2b7-1fca08f8f970)

**Comment by petersampsonaudacity** [comment]
I cannot reproduce this on W10 with @crsib Dmitry's latest build for Musical Gridlines either:  audacity-win-3.4.0-alpha-20230810+db4e2f6-x64

**Comment by LWinterberg** [comment]
@petersampsonaudacity at 120 bpm, this only starts happening past 999 bars (which also breaks the control in a different way, #4560)

**Comment by petersampsonaudacity** [comment]
@LWinterberg   silly me for using the default 120 4/4 setting ...

**Comment by dozzzzer** [comment]
The bug remains unfixed in PR #5190

Observe the value in the Time toolbar closely as the cursor is moving forward with a snap increment of 1 bar across the project:


https://github.com/audacity/audacity/assets/70063970/51e85743-44eb-468e-8516-a844c65a51a6

**Comment by crsib** [comment]
Please share the tempo and time signature you used

**Comment by crsib** [comment]
Please check other snap mode too

**Comment by dozzzzer** [comment]
Tested
