### ISSUE TITLE
Audacity on MS Store

### ISSUE THREAD

**Issue by Saijin-Naib** [audacity/audacity#505]
**Is your feature request related to a problem? Please describe.**
Not really, though the MS Store version does alleviate some potential pain-points (auto-update, non-admin, vetted/tested distribution source).

**Describe the solution you'd like**
A possible paid repackage of the Audacity Windows distribution through the MS Store, with the ability to use FFMPEG and other plugins.

**Describe alternatives you've considered**
Using the currently-provided binary distributions in both install and portable variants.

**Additional context**
I like to think of this as a way for you to get donations, and for users to get the convenience of store-distributed apps. For instance, I make use of Paint.NET and LibreOffice Vanilla in this way. I would certainly make use of Audacity this way.

**Comment by MichaelGrigoryan25** [comment]
In a way, I agree with you. I think it'll have many shortcomings by uploading it as an app to MS Store. Speaking of donations, it'll be a good idea to open an [OpenCollective](https://opencollective.com/) or [Patreon](https://patreon.com) account to engage users to donate in some way, not to force them.

**Comment by Saijin-Naib** [comment]
What possible shortcomings have you concerned?

Store distribution has come a long way since W8/early W10...

**Comment by MichaelGrigoryan25** [comment]
I know that it has come a long way.
Here is a shortlist
-Most of the time windows store apps need some kind of troubleshooting
-They generate too much cache just from being an app
-At any time(and believe me that time will come) there can be a major error in specific user app
-Updating/installing of the apps takes too long(I have an i5-8250U, 8GB RAM, 50Mbp/s internet)

**Comment by Saijin-Naib** [comment]
Most of those are honestly not platform issues due to the Store, but rather sound like issues with your setup.

For reference, I work for a major international retailer's tech support and I've encountered a few of those problems occasionally, but there was always an underlying issue to cause them unrelated to the Store/App itself.


> -Most of the time windows store apps need some kind of troubleshooting

I've never experienced this and I make heavy use of Store provided apps, from LibreOffice, Paint.NET, the entire Affinity Suite, Arduino, Slack, Python, to full Linux Distros. It just isn't a common problem 🤷‍♂️

> -They generate too much cache just from being an app

I'm not sure what you mean by this, but with MSIX, you can take a mostly unmodified MSI installer and repackage it for the Store. It doesn't "cache" any differently.

> -Apps remain in your app library without any possibility to remove it (a serious issue for me because of many bloatware was installed on my computer and I can't get rid of it from my account )

You've been able to hide them for a few years now. If you contact Support, the can remove licenses, though they don't like to.

> -At any time(and believe me that time will come) there can be a major error in specific user app

Never had an issue, even on my personal machine that has been on Insider Fast Windows builds for the past 4.5 years 🤷‍♂️ That isn't a platform issue.

> -Updating/installing of the apps takes too long or doesn't complete at all(I have Windows 10 Home, i5-8250U, 8GB RAM, Nvidia GeForce MX150, 50Mbp/s internet)

Intermittent issue, sometimes caused by Service issues on MS' end, but most often an underlying issue with BITS or the WU service. Again, not a platform issue/limitation.
![image](https://user-images.githubusercontent.com/19295950/80916853-50faa300-8d29-11ea-9788-2f7c52286856.png)
If you want downloads to speed up, make use of Delivery Optimization. Makes a HUGE difference, especially if you have more than one machine on your local network.

**Comment by MichaelGrigoryan25** [comment]
In any way we **should count** the **minority** too, because maybe I'm not the only person who has this problem.

**Comment by Saijin-Naib** [comment]
> In any way we should count the minority too, because maybe I'm not the only person who has this problem.

Then continue to use the non-Store builds provided as MSI/EXE and Zip, no? This is an additional option for those who would prefer it through the Store, as well as a way to make a donation, as well.

**Comment by SteveDaulton** [comment]
The latest release version of Audacity is always available, free of charge, via the Audacity website: https://www.audacityteam.org/download/
For notification of new releases, follow us on facebook (https://www.facebook.com/AudacityTeamOfficial/) or twitter (https://twitter.com/getaudacity), or click "Help menu > Check for updates" in the Audacity app.

Donations are gratefully accepted through the "Donations" page of the website. Currently we can only accept donations via PayPal. A donation is NOT required to use the software, but donations help us to cover costs.

Audacity probably will eventually be available at minimal charge via the MS Store, but please note that at the present time there is no authorised distribution other than the downloads from FossHub (the download links on the Audacity website).

We strongly recommend NOT obtaining Audacity from unauthorised sites as we cannot guarantee that they are unmodified, genuine versions. There is at least one website that we know of (a ".de" domain) that offers Audacity for free download, and also distributes malware. For more information about safely downloading Audacity, see: https://www.audacityteam.org/download/online-safety-when-downloading/

Audacity will probably never be available via Apple Store due to Apple Store being incompatible with our GPL open source license.

**Comment by MichaelGrigoryan25** [comment]
So you are telling to force people to donate, not to give them a good reason to donate!?

**Comment by SteveDaulton** [comment]
No-one is "forced" to donate. Donations are purely voluntary. We intend to keep Audacity available for free download regardless of whether we eventually put it into MS store.

Please do not use GitHub for trolling or flaming. Save that for your social media.

I am closing this issue as my previous post covers Audacity's current position.

**Comment by MichaelGrigoryan25** [comment]
> 
> 
> No-one is "forced" to donate. Donations are purely voluntary. We intend to keep Audacity available for free download regardless of whether we eventually put it into MS store.
> 
> Please do not use GitHub for trolling or flaming. Save that for your social media.
> 
> I am closing this issue as my previous post covers Audacity's current position.

Agree :)

**Comment by Saijin-Naib** [comment]
> Audacity probably will eventually be available at minimal charge via the MS Store, but please note that at the present time there is no authorised distribution other than the downloads from FossHub (the download links on the Audacity website).

Look forward to seeing it there, and recommending it to family, friends, and clients when this is so. Thanks for all you and your team have done over the years.

**Comment by Jaiganeshkumaran** [comment]
It doesn't need to be in the Microsoft Store, but at least consider using an MSIX installer rather an MSI one which reduces the change of machine rot.

**Comment by Rexogamer** [comment]
Update: It seems that as per [this commit](https://github.com/audacity/audacity-support/commit/7ba0e6bb8bc2e657ea9d36a821c4b187da5acfee) Audacity is now available via the MS Store
