### ISSUE TITLE
AutoDuck Effect applies unevenly to Stereo Tracks.

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#5054]
### Bug description

If the User uses AutoDuck effect in current Master, the left channel is processed correctly (the parameters set by the User in AutoDuck effect window are honoured), but the right channel is processed incorrectly (the parameters set by the User in AutoDuck effect window are not honoured).

### Steps to reproduce

1. Open Audacity
2. Import or Generate Audio in a Stereo Track
3. Create another track with some noise, for example
4. Apply AutoDuck effect to the first track created
5. Observe Left and Right channels.

### Expected behavior

Here is how the effect is applied in Audacity 3.3.3:
<img width="1617" alt="Screenshot 2023-08-18 at 14 20 59" src="https://github.com/audacity/audacity/assets/139755141/94e7561f-cd74-4bc0-9660-2427d1ad3e5b">

### Actual behavior

Here is what the effect does on Master (same project used):
<img width="1617" alt="Screenshot 2023-08-18 at 14 25 52" src="https://github.com/audacity/audacity/assets/139755141/a175f9e4-ca21-42df-89b3-a5e359438c3a">

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

**Comment by petersampsonaudacity** [comment]
This is possible the same or related to:

 **Most (nearly all) effects overwrite right channel data with left channel data #5055**

**Comment by chinakov** [comment]
@petersampsonaudacity - yes, this is not reproduced on Mono tracks, as shown in your example above. 

However, this is how it looks on Stereo on Paul's branch build: 
**Before:**
![image (1)](https://github.com/audacity/audacity/assets/139755141/d0df32b8-1943-40d5-8947-3921e988fac0)

**After:**
![image](https://github.com/audacity/audacity/assets/139755141/3be33128-9040-4d49-90c2-8869a3423b57)

Pay close attention to left and right channels here.

**Comment by petersampsonaudacity** [comment]
> Pay close attention to left and right channels here.

@chinakov   -  I see that you have quieter ducks in the right channel

Hoever when I run a similar project on Paul's branchmine looks OK:
![image](https://github.com/audacity/audacity/assets/50205984/53f938b9-f81f-450b-9cc0-504d010ae93a)

**Comment by Paul-Licameli** [comment]
> @chinakov @Paul-Licameli
> 
> This is possible the same or related to:
> 
> **Most (nearly all) effects overwrite right channel data with left channel data #5055**

Indeed it is related.

Matthieu recommended a change to my proposed fix and I agreed.  So I will ask you to test again when it rebuilds.

**Comment by dozzzzer** [comment]
Tested
