### ISSUE TITLE
Vocal Reduction and Isolation (and Vocoder) causes Audacity to crash 

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#5057]
### Bug description
Using **Vocal Reduction and Isolation** and **Vocoder** crashes 3.4.0 alpha

This is a regression on 3.3.3 and earlier Audacity versions

### Steps to reproduce
1. get a stereo track
2. select it
3. apply Nyquist effect **Vocal Reduction and Isolation** or **Vocoder**

And once again the phone-home error report fails to send -see #4154 _(which has been closed)_

### Expected behavior
**Vocal Reduction and Isolation** and **Vocoder** should work on the selected audio

### Actual behavior
**Vocal Reduction and Isolation**  and **Vocoder** crash Audacity 3.4.0

### Audacity Version
3.4.0 alpha audacity-win-3.4.0-alpha-20230817+b2626a1-x64-msvc2022

### Operating system
Windows 10/11; no such issue on macOS

### Additional context
The issue is introduced by PR https://github.com/audacity/audacity/pull/4987

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @Paul-Licameli 's latest branch build:  audacity-win-3.4.0-alpha-20230820+9d21d5c-x64

This issue is **_NOT_** fixed in Paul's branch build

**Comment by petersampsonaudacity** [comment]
@dozzzzer @chinakov @Paul-Licameli 

Testing on W10 with latest 3.4.0 master (with Paul's fix for #5055 ):  audacity-win-3.4.0-alpha-20230822+48154ef-x64-msvc2022

This no longer crashes Audacity on Windows

**Comment by dozzzzer** [comment]
Confirm this is no longer reproducible in the latest `master`
