### ISSUE TITLE
ASIO now seems to be GPL-compatible!

### ISSUE THREAD

**Issue by ChrisEt** [audacity/audacity#507]
Hi guys,

I think the Steinberg license now allows to include the ASIO support in GPL projects! I also found other projects (e.g. https://github.com/monocasual/giada) already doing that!

If you look at the license agreement contained in https://www.steinberg.net/asiosdk, there is no section anymore that prohibits the inclusion of ASIO SDK code in GPL projects!

All that would be required is that someone from Audacity signs the agreement and sends it back to info [at] steinberg.de.

What do you guys think?

**Comment by SteveDaulton** [comment]
I'm not convinced.
Section 2.3 from https://www.steinberg.net/asiosdk :

"The Licensee will not sell, license, give-away and/or distribute the
Licensed Software
Developer Kit or parts of it for the use as software developer kit in any
way, for
example, integrated in any framework application, on any medium, including
the
Internet, to any other person, including sub-licensors of the Licensee or
companies
where the Licensee has any involvement."

Steve

**Comment by ChrisEt** [comment]
"for the use as software developer kit" and "integrated in any framework application" - this could be interpreted both ways.

I volunteer to correspond with Steinberg to get a written statement, if you guys agree?

**Comment by JamesCrook** [comment]
Closed.  Request involves packaging license incompatible software.

**Comment by gilgongo** [comment]
> I'm not convinced. Section 2.3 from https://www.steinberg.net/asiosdk : "The Licensee will not sell, license, give-away and/or distribute the Licensed Software Developer Kit or parts of it for the use as software developer kit in any way, 

While it's true their licence doesn't explicitly mention source code (or F/LOSS), we interpreted it as [not being in conflict with the GPL](https://github.com/jamulussoftware/jamulus/issues/2417#issuecomment-1054752634), and signed the Steinberg agreement based on that conclusion.

(Sorry, but forums won't let me register - was going to post this there)

**Comment by crsib** [comment]
> Sorry, but forums won't let me register - was going to post this there

I think GitHub is a much better place for such discussions. The forum is mostly about the user support.

Generally I agree that there is no need to amend the source code license. However, we distribute binaries under GPLv3 and we need to do so to comply with another Steinberg product license - VST3 SDK.

To be fair, I am not quite sure that distributing and re-distributing Audacity violates the license per se, I think license only forbids Audacity forks to distribute the binaries under the different name. This is a complex topic, so it should be run through the lawyer first anyway.

**Comment by gilgongo** [comment]
Not sure I follow. Steinberg's licence for the VST3 SDK appears to be the same as that of ASIO, but Audacity sees ASIO as license incompatible software. Apologies if I've misunderstood this issue.

**Comment by crsib** [comment]
VST3 SDK has a GPL3 option.

**Comment by juped** [comment]
As of just a couple days ago, the ASIO SDK license now reads
> This Software Development Kit is licensed under the terms of the Steinberg ASIO License,
or alternatively under the terms of the General Public License (GPL) Version 3.
You may use the Software Development Kit according to either of these licenses as it is
most appropriate for your project on a case-by-case basis (commercial or not).

**Comment by DavidBailes** [comment]
Press release for this change:
https://www.steinberg.net/press/2025/obs-collaboration/

**Comment by RavuAlHemio** [comment]
And there's already a pull request to enable it in regular builds, #9727. 🙂
