### ISSUE TITLE
Crash when discarding an auto recovery file

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#5070]
### Steps to reproduce

1. Start Audacity
2. Open a previously saved project
3. Make Audacity crash (such "Help > Diagnositcs > Test segfault Report" which is only in Alpha builds)
4. Restart Audacity
5. Choose "Discard Selected" in the recovery dialog
6. Start Audacity again; the backup has been correctly discarded

### Expected behavior

No crash

### Actual behavior

Crash at step 5 (but not at step 6)

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

### Additional context

I didn't test on other operating systems.  It may be only on macOS

**Comment by dozzzzer** [comment]
Tested
