### ISSUE TITLE
Default quality  setting for M4A/AAC stereo export is ridiculously low at 98 kbps

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#5079]
### Bug description
The default setting for M4A/AAC stereo export is ridiculously low at 98 kbps, this is a very poor setting for music and a not very good setting for voice.  _(BTW it was 100 kbps when I last updated the image for AAC export in the Manual)_

This is a regression as in 3.3.3 and earlier it was 160 kbps - introduced in @vsverchinsky 's work on new Export for 3.4.0

256 kbps would be a much better default as that is the quality the Apple sells its AAC files at in iTunes/Music- and most folk who are exporting to AAC are likely to be exporting music for use in an iTunes/Music library.

### Steps to reproduce
1. Clear audacity settings folder
2. launch 3.4.0 alpha
3. get some stereo audio
4. File > export Audio
5. select AAC/M4A
6. Observe offered (default) quality is 98 kbps 

### Expected behavior
256 kbps would be a much better default setting 

This is the quality at which Apple now sells music files in iTunes/Music.

### Actual behavior
![image](https://github.com/audacity/audacity/assets/50205984/08e57b7d-55b0-451c-a6b0-0842334e3d9e)

### Audacity Version
3.4.0 alpha (with new Export)

### Operating system
Windows and macOS 12.6.8 Monterey - so assume all OS

### Additional context
See also:   
**M4A(AAC) Export does not honor the user's quality settings for bit rates below 196kbps in the export dialog #4309** 

which indicates that with this default setting the user is likely to be getting 196/198 kbps as a minimum quality that we get from the AAC exporter we currently use.

And see also:
 **Native AAC support: Windows #3861 
 Native AAC support: macOS #3862**

**Comment by petersampsonaudacity** [comment]
But if you use the default 160 0 you actually get 197-198

See my post from yesterday when I retested:
 **M4A(AAC) Export does not honor the user's quality settings for bit rates below 196kbps in the export dialog** #4309

I have re-run the tests today on W10 and macOS 12.6.8 Monterey with the latest 3.4.0 alpha,

The results have improved somewhat for Windows meaning that both give reasonably close results with stereo for setting of 196kbps and above:

### Actual behavior with stereo exports
**using the latest FFmpeg that @crsib recommended_**

**Windows 10**
Set rate  /  actual rate   - stereo
98 - 197  -  lowest setting
128 - 197
160 - 197
192 - 197
196 - 197
198 - 199
200 - 201
224 - 225
235 - 236
256 - 256
320 - 256

**Mac - macOS 12.6.8 Monterey**
Set rate  /  actual rate   - stereo
98 - 198
128 - 198
144 - 198
160 - 198 
196 - 198
198 - 200
200 - 202
224 - 226
256 - 257
320 - 316

**Comment by LWinterberg** [comment]
on second thought, the value for mono gets clamped at 160 anyway, and the stereo value is lowest-clamped to 98*2 anyway still. Let's just do 256 as standard.

**Comment by petersampsonaudacity** [comment]
>Let's just do 256 as standard.

Great  -  the smaller sizes held sway when disks and SD cards were smaller and more expensive.

I started out with my first small iPod using 192 (after some careful listening tests) - but switched to 256 as soon as I got a 160GB iPod (the SD card in my Android phone is even bigger).   But even at mostly 256 my 160GB ipod is still only 2/3 full and it contains my entire record an tape collection made over a 60-year-plus period.

**Comment by petersampsonaudacity** [comment]
Testing om W10 with @LWinterberg 's branch:  audacity-win-3.4.0-alpha-20230825+3264d5b-x64

This now looks fine to me Leo - many thanks for that.
![image](https://github.com/audacity/audacity/assets/50205984/3e987570-0a02-4255-b495-62654cd6b5b4)

**Comment by dozzzzer** [comment]
Tested
