### ISSUE TITLE
When uploading to audio.com, track title cannot be submitted by pressing the Enter key

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5081]
### Steps to reproduce

1. Navigate to the Share Audio/Save to the Cloud dialog
2. type something into the Track/Project Title text box
3. press Enter

### Expected behavior

Track Title is submitted and file uploading starts as if the Continue button was clicked.

### Actual behavior

Nothing happens

### Audacity Version

current master / alpha / nightly build

### Operating system

Any

**Comment by dozzzzer** [comment]
Fixed for project cloud upload; not fixed for uploading audio via Share Audio dialog.

**Comment by crsib** [comment]
Those are different dialogs, although they look very similar now :-)

**Comment by crsib** [comment]
Not now :-) But we surely should!
