### ISSUE TITLE
"Bouncing ball delay with panning" nyquist plugin does not work

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#5086]
### Steps to reproduce

Install the bouncing ball delay with panning plugin from: https://plugins.audacityteam.org/nyquist-plugins/effect-plugins/delay-and-reverb#bouncing-ball-delay-with-panning

1. Select some audio in a stereo (or mono) audio track.
2. Try and preview or apply the effect

### Expected behavior

The effect is previewed or the effect is applied.

### Actual behavior

There is no preview, and no effect is applied.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

Issue also exists using Audacity 2.4.2.
Reported on Audacity4Blind list.

Debug output:
error: In CUE, argument must be a sound or multichannel sound, got 0.25, a FLONUM
Function: #<Subr-ERROR: #000001D0A30D23E8>
Arguments:
  "In CUE, argument must be a sound or multichannel sound, got 0.25, a FLONUM"
Function: #<FSubr-LET: #000001D0A30CD9D8>
Arguments:
  ((TYPES-STRING (NY:TYPE-LIST-AS-STRING (FIRST TYP) MULTI)))
  (ERROR (STRCAT "In " SRC "," (INDEX-TO-STRING INDEX) " argument" (IF (SECOND TYP) (STRCAT " (" (SECOND TYP) ")") "") (IF (EQ (CHAR TYPES-STRING 0) #\i) " must be an " " must be a ") TYPES-STRING ", got " (PARAM-TO-STRING VAL) (IF SECOND-VAL (STRCAT ", and" (PARAM-TO-STRING VAL2)) "")))
Function: #<Closure-NY:ERROR: #000001D0A2E4FDD8>
Arguments:
  "CUE"
  0
  ((SOUND) NIL)
  0.25
  T
Function: #<FSubr-IF: #000001D0A30D1C50>
Arguments:
  (NOT (OR (SOUNDP SOUND) (MULTICHANNEL-SOUNDP SOUND)))
  (NY:ERROR "CUE" 0 (QUOTE ((SOUND) NIL)) SOUND T)
Function: #<Closure-CUE: #000001D0A2ECCBD0>
Arguments:
  0.25
Function: #<FSubr-IF: #000001D0A30D4C20>
Arguments:
  (= COUNT 0)
  (CUE S)
  (SIM (CUE S) (AT (MULT DELAY COUNT) (LOUD DECAY (PANBOUNCES (STEREO-PAN (MULT 2 S) (NEXT-POSITION COUNT)) (- COUNT 1)))))
Function: #<Closure-PANBOUNCES: #000001D0A30C5B28>
Arguments:
  0.25
  15
Function: #<FSubr-PROGV: #000001D0A30D5958>
Arguments:
  (QUOTE (*WARP*))
  (LET ((STR 1)) (NY:TYPECHECK (NOT (NUMBERP STR)) (ERROR "1st argument of STRETCH-ABS (or 2nd argument of SAL's ~~ operator) should be a number (stretch factor)" STR)) (LIST (LIST (LOCAL-TO-GLOBAL 0) STR NIL)))
  (NY:TYPECHECK (MINUSP (WARP-STRETCH *WARP*)) (ERROR "In STRETCH-ABS (or SAL's ~~ operator), negative stretch factor is not allowed" (WARP-STRETCH *WARP*)))
  (PANBOUNCES S COUNT)
1>

**Comment by SteveDaulton** [comment]
A basic "fix" would be to add a "1" to the second line to give:
`;version 1`

That will allow the plug-in to run, though I still don't think that panning works as David Sky originally intended.
I see in the code comments that I previously patched up this effect 11 years ago:
```
;; Bug Fix by Steve Daulton 5th Dec 2012
;; This plug-in is still quite buggy, but it basically works.

```

**Comment by SteveDaulton** [comment]
I've just  tried downloading the plug-in from the link in the first post, and it downloaded as:
spaces_klCVENFte0GRy5IqVz0W_uploads_git-blob-8404fcffb69e6c69ee978e26eedf04936e6471e2_Bbdelay.ny

**Comment by DavidBailes** [comment]
> I've just tried downloading the plug-in from the link in the first post, and it downloaded as:
> spaces_klCVENFte0GRy5IqVz0W_uploads_git-blob-8404fcffb69e6c69ee978e26eedf04936e6471e2_Bbdelay.ny

I can confirm this problem.
I submitted a fix for the lack of version number, which was merged by @LWinterberg : https://github.com/audacity/audacity-support/pull/41
I don't know why this has caused this problem with the file name.

**Comment by LWinterberg** [comment]
I've contacted gitbook about it. Outside of the weird rename, I believe the PR fixes it though.
