### ISSUE TITLE
UI: When pressing the record button it will slide the scroll down to the bottm in a multi track project

### ISSUE THREAD

**Issue by ovidiucs** [audacity/audacity#509]
**Describe the bug**
When pressing the record button (or hitting R) on a multi track project the vertical scrollbar will go to the last track, at the bottom of the window.

**To Reproduce**
1. Make any project such that there are more tracks than the height of the window. Do not rearrange tracks.
2. Scroll up and select a track from the first ones created (let's say track 2).
3. Click on "Record".
4. You will notice that this action starts recording and takes you to the last track at the bottom of the screen.

**Expected behavior**
If a track is selected it should keep focus while recording on that track. 
If there is a 50 track project then, every time a user is recording something he will be taken to the bottom of the window. I could not find any option which deals with this behavior in order to disable it.

**Screenshots**
Please see this [video](https://www.reddit.com/link/fwovla/video/zfchlrj2nfr41/player?utm_source=reddit&utm_medium=usertext&utm_name=audacity&utm_content=t3_fwpyru) of the issue taken form a reddit topic, but which shows this odd behavior.

**Additional information (please complete the following information):**
 - OS: I'm on Arch. The video shown above looks to be on Windows. So I will assume ANY os.
 - Version 2.3.3.

**Additional context**
Playback maintains the vertical scrollbar's position in place. It is only when recording that the vertical scrollbar position is placed at the bottom. According to this [reddit](https://www.reddit.com/r/audacity/comments/fwpyru/how_to_get_audacity_to_stop_auto_sliding_to_bottom/) post this seems to be expected behavior, however when doing 50 tracks it does not do well as you constantly have to go.

**Comment by SteveDaulton** [comment]
Thank you for reporting this issue. I agree that this is a bug and shall transfer it to our bug tracker.

**Comment by SteveDaulton** [comment]
This issue has now been closed "resolved - fixed" on the Audacity bug tracker.
https://bugzilla.audacityteam.org/show_bug.cgi?id=2422
