### ISSUE TITLE
Timeline menu: Nomenclature for dragging selection with looping region is misleading and could be clarified

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#5092]
### Bug description

The nomenclature for dragging a selection with the looping region is misleading in Timeline context menu, where "**Enable dragging  selection**"  as it affects not the "**selection**" but rather it drags the selection in sympathy as the looping region is expanded or contracted by dragging with the cursor in the Timeline.  

_Selection dragging is totally different and independent of looping region dragging - selection dragging is controlled from Tracks Behaviors preferences._

**The current Timeline context menu entry had me totally baffled as I was trying to use it to control selection dragging  - and I'm sure I'll not be the only user to be confused by this.**

### Steps to reproduce

1. get some audio
2.  make a looping region in the Timeline
3. make a selection that is different from the looping region
4. right click in the Timeline to get the context menu
5. turn on "Enable dragging selection"
6. try dragging the selection edges 
7. Observe:  you can't

### Expected behavior

The entry in the Timeline context menu for:  **Enable dragging selection**

should be changed to  **Drag Selection with Loop**
![image](https://github.com/audacity/audacity/assets/50205984/807cefcc-c7fb-4d40-aa6f-7eaea4b0f463)
You don't need the "**Enable**" as the function is either "on" or "off"

**Note:** there is a totally different command for dragging an entire loop:  
![image](https://github.com/audacity/audacity/assets/50205984/67c914ba-2bbe-4b2b-8dd2-f1beb42e83e2)

### Actual behavior

**Timeline context menu**
![image](https://github.com/audacity/audacity/assets/50205984/26d9afe7-78ff-4fed-a6c8-036aac5eeb04)

### Audacity Version
All versions from 3.1.0 onwards (when new Looping was introduced)

### Operating system
Windows 10 but assume all OS

### Additional context
I came to this because for some user testing for the Forum I turned off selection edge dragging in Tracks Behaviors prefs at some stage this week.

I was surprised/confused when I found that "Enable dragging selection" when turned on from the Timeline context menu did NOT enable me to expand/contract the selection by edge-dragging.

**Comment by petersampsonaudacity** [comment]
I have updated the manual such that **"looping region"** is used throughout.

There were a smattering of "loop region" entries _(one even on the looping page itself)_ but I changed all those.

**Comment by petersampsonaudacity** [comment]
With that change I note that the app itself  seems to be using "loop region" rather than "looping region"
![image](https://github.com/audacity/audacity/assets/50205984/fec0e713-94dd-46e2-b8bf-b27059e64884)

@LWinterberg  can you please advise if you either:
a) wish to change the nomenclatre in this menu in the app
b) change the nomenclature in the manual
c) just leave the app and the manual divergent in this regard?

**Comment by LWinterberg** [comment]
> in Timeline context menu, where "Enable dragging selection" is misleading as it affects not the "selection" but rather the "Loop" or "Loop edges"

This is incorrect, "enable dragging selection" makes it such that whenever you set a new loop region, a selection is drawn with it. The loop region itself is always moveable in the timeline. 

https://github.com/audacity/audacity/assets/87814144/f93a1073-060f-45fe-8ec8-0c641ecd8011

Regarding the preference in track behaviors - can that be removed maybe?

**Comment by petersampsonaudacity** [comment]
> This is incorrect, "enable dragging selection" makes it such that whenever you set a new loop region, a selection is drawn with it. The loop region itself is always moveable in the timeline.

Yes I know that - but the selection can then be changed independently (and dragged independently) of the looping region - that is precisely why I have Step 3 in my STRs:

![image](https://github.com/audacity/audacity/assets/50205984/68cb2724-51e6-48e1-87de-2eb046b9b2c5)

**Comment by petersampsonaudacity** [comment]
I came to this because for some user testing for the Forum I turned off selection edge dragging in Tracks Behaviors prefs at some stage this week.

I was surprised/confused when I found that "Enable dragging selection" when turned on from the Timeline context menu did NOT enable me to expand/contract the selection by edge-dragging.

**Comment by petersampsonaudacity** [comment]
OIC - I've just had a careful read of the manual (always helps) - and there it is made clear

![image](https://github.com/audacity/audacity/assets/50205984/18e6f466-419d-4270-a758-0a2d7fa1b097)

BUT we do know that very few people RTFM and even fewer do so carefully - so I still argue that the nomenclature in this context menu command is confusing and its actual action is not readily "discoverable" from "what it says on the tin"

**Comment by petersampsonaudacity** [comment]
Maybe that contxet menu entry could (as a clearer indication of waht it does) say

**Drag Selection with Loop**

You don't need the "**Enable**" as the function is either "on" or "off"

**Comment by petersampsonaudacity** [comment]
@LWinterberg 

Now that I understand this better I will rework this replacing my original suggestion with my latest one (probably later on today)

In the course of that I will purge all the unnecessary dross from this thread.

**Comment by dozzzzer** [comment]
Fixed by #5174
