### ISSUE TITLE
Suggestion to simplify the Mac build a tiny bit

### ISSUE THREAD

**Issue by RJVB** [audacity/audacity#5093]
You're currently using a wrapper/launcher with the single purpose of un-setting `DYLD_LIBRARY_PATH`:

https://github.com/audacity/audacity/blob/c8c17426f6723781a9adc88eb1e1b5b3c2fc1b96/mac/Wrapper.c#L49

IMHO that complexifies things needlessly (plus you get a process called "Wrapper" in your `ps` output).

You can achieve the same thing in the "real" `main` in `AudacityApp.cpp` where it can be done in 6 lines only (at the very start of the main function and in my experience it's not required to use `execve()`):

```
if (getenv("DYLD_LIBRARY_PATH") && !getenv("AUDACITY_PRESERVE_LIBRARY_PATH")) {
    unsetenv(DYLD_LIBRARY_PATH);
    execvp(argv[0],argv);
    perror("Launch failed");
    exit(-1);
}
```

_Maybe_ one could just fall through and continue execution if `execvp()` failed but I've never tried that. 

---------

I do question the justification for unsetting `DYD_LIBRARY_PATH`: if that variable is set it is because the user wants it to be and has a reason for it. Hence the check if `AUDACITY_PRESERVE_LIBRARY_PATH` is set in the suggestion above.

**Comment by RJVB** [comment]
FWIW, I'm using that exact same trick in a simple `dlsym` wrapper around `dlopen()` and `dlsym()` I wrote for testing shared libraries:

```
int main( int argc, char *argv[] )
{ int i, r= 1;
  void *lib;
#if defined(__MACH__) || defined(__APPLE_CC__) || defined(__USE_GNU)
  Dl_info info;
#endif
        char *v;
        if( (v = getenv("DLSYM_VERBOSE")) ){
                putenv("DYLD_PRINT_LIBRARIES_POST_LAUNCH=1");
                putenv("DYLD_BIND_AT_LAUNCH=1");
                putenv("LD_BIND_NOW=1");
                if (atoi(v) > 1 ) {
                        putenv("DYLD_PRINT_INITIALIZERS=1");
                        putenv("DYLD_PRINT_APIS=1");
                        putenv("DYLD_PRINT_RPATHS=1");
                        putenv("LD_DEBUG=files");
                }
                unsetenv("DLSYM_VERBOSE");
                fprintf(stderr, "relaunching %s\n", argv[0]);
                execvp(argv[0], argv);
                perror("oops");
                exit(-1);
        }
        if( argc> 1 ){
<snip>
 ```

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444) which uses a different build system. This bug should no longer be applicable.

**Comment by RJVB** [comment]
On Tuesday October 15 2024 06:38:34 Leo Wattenberg wrote:
>uses a different build system.

Thankfully not exactly, just a redesigned CMake-based build system ^^
