### ISSUE TITLE
Crash/deadlock when recording in the Waveform, and then switching to the Spectrogram view

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5094]
### Bug description

When initially recording on an empty mono/stereo track in the Waveform view and then, after switching the view to the Spectrogram, resuming recording, it causes Audacity to crash (on Windows) or freeze (macOS).

### Steps to reproduce

1. add an empty mono track
2. set recording channels to 1
3. click Record
4. wait a few sec
5. click Stop
6. switch to Spectrogram
7. click Record again (might require to stop and then hit Record one more time)

### Expected behavior

No crash or freeze

### Actual behavior

Crash/freeze:

https://github.com/audacity/audacity/assets/70063970/c1588d80-6af8-4267-8275-590c31eca762

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS

**Comment by petersampsonaudacity** [comment]
@dozzzzer 

Testing on W10 with the latest 3.4.0 alpha master.

I crash out much earlier, at Step 3 !

**Comment by petersampsonaudacity** [comment]
If I omit Step 1 and proceed with the rest of the steps I get no crash after switching to Spectrogram and the continuing with recording on the track.

**Comment by dozzzzer** [comment]
@petersampsonaudacity I believe PR #5082 should fix that crash you're dealing with, I should've mentioned that in the description. It's already merged. Once the [build job](https://github.com/audacity/audacity/actions/runs/5999200317) is finished, feel free to re-test.

**Comment by petersampsonaudacity** [comment]
Yepper @dozzzzer  the latest apha master :  audacity-win-3.4.0-alpha-20230828+a53fd35-x64-msvc2022

causes no crash at step 3 (with either mono or stereo)  - phew that saves logging a bug

**Comment by petersampsonaudacity** [comment]
@dozzzzer and testing on w10 with latest alpha 3,4,0 master:  audacity-win-3.4.0-alpha-20230828+a53fd35-x64-msvc2022

a) following your STRs I get no crash at Step 7

b) I can even toggle the view from waveform to spectrogram and back again while actually recording.

**Comment by Paul-Licameli** [comment]
Maybe we can merge the known fix and open an issue for the residual.

I reproduced a crash but intermittently.  This symptom is different.

It may be the switch between view types is not necessary -- that it could happen simply using spectrogram always.

Anything you can do to identify conditions to reproduce it would be helpful.

**Comment by dozzzzer** [comment]
As for the residual, it's now logged as https://github.com/audacity/audacity/issues/5108
