### ISSUE TITLE
Left and right channels get misaligned when recording

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5098]
### Bug description

When importing an audio file with a sample rate different than the default one and starting recording, the left and right channels get out of sync and misaligned, as if each had its own sample rate.

<img width="500" alt="Screenshot 2023-08-28 at 18 36 04" src="https://github.com/audacity/audacity/assets/70063970/bda1e9b1-2072-451f-a582-b184de734bb0">

### Steps to reproduce

1. Have the default sample rate set to 44.1 kHz
2. Import a .wav stereo audio file with a sample rate of 48 kHz
3. Double-check in Audio settings that the project's sample rate is also 48 kHz now
4. Check that Recording Channels is set to "2"
5. Place the cursor after the imported clip and hit Record

### Expected behavior

Left and Right channels are aligned

### Actual behavior

The left and right channels are misaligned, and the longer the recording takes, the larger the offset between the channels is:

https://github.com/audacity/audacity/assets/70063970/07e45c7b-7e02-4aac-81be-5567d82d85e0

### Audacity Version

current master / alpha / nightly build

### Operating system

Other

### Additional context

A possible workaround: one may change the track's Sample Rate to 44.1 kHz and then the recording will have both channels aligned.

**Comment by petersampsonaudacity** [comment]
@dozzzzer 
Note that the project rate won't change at steps 2-3 once @vsverchinsky rececnt fix for the following Issue is pulled into Master:
 **Audacity silently changes the project rate on importing the first audio file to match its rate. #4448** 

and the Pull Request
 Importing into empty project does not change project sample rate #5075

**Comment by Paul-Licameli** [comment]
Awful.  P1 please.

**Comment by dozzzzer** [comment]
Bisects to https://github.com/audacity/audacity/commit/c8fda52656a303b19c3bf8464790eebb0390fd0d

**Comment by Paul-Licameli** [comment]
> Bisects to [c8fda52](https://github.com/audacity/audacity/commit/c8fda52656a303b19c3bf8464790eebb0390fd0d)

Thank you sir may I have another

**Comment by vsverchinsky** [comment]
Bisected it to this line:
https://github.com/audacity/audacity/commit/1002423084216925a92c7e824c7e879468537d1e#diff-6c07ddf13b454ffd9eb07045294c3efd274d3cff6e9ca9921bdd926241c560fbL1069-R1069

**Comment by petersampsonaudacity** [comment]
> @dozzzzer
> Note that the project rate won't change at steps 2-3 once @vsverchinsky rececnt fix for the following Issue is pulled into Master:
> **Audacity silently changes the project rate on importing the first audio file to match its rate. #4448**

This is now the case in master for 3.4.0 alpha

**Comment by Paul-Licameli** [comment]
> @Paul-Licameli Bisected it to this line: [1002423#diff-6c07ddf13b454ffd9eb07045294c3efd274d3cff6e9ca9921bdd926241c560fbL1069-R1069](https://github.com/audacity/audacity/commit/1002423084216925a92c7e824c7e879468537d1e#diff-6c07ddf13b454ffd9eb07045294c3efd274d3cff6e9ca9921bdd926241c560fbL1069-R1069)

Really to the LINE and not just to the commit?

**Comment by vsverchinsky** [comment]
> Really to the LINE and not just to the commit?

I mean exactly this line change in the commit introduced the issue )
