### ISSUE TITLE
Crash when joining an audio track and an empty audio track

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#5102]
### Bug description

"Join tracks to stereo" crashes Audacity when upper track is empty

### Steps to reproduce

1. Add a new mono track
2. Add another mono track
3. Generate some audio into the second track
4. From the upper track dropdown menu, select "Make Stereo Track"

### Expected behavior

A stereo  track with audio in the right (lower) channel.

### Actual behavior

Crash

### Audacity Version

current master / alpha / nightly build

### Operating system

All OSs

### Additional context

Tested with [audacity-linux-3.4.0-alpha-20230828+a53fd35-x64-20.04](https://nightly.link/audacity/audacity/workflows/build/master/audacity-linux-3.4.0-alpha-20230828%2Ba53fd35-x64-20.04) on Xubuntu 22.04.

On restarting Audacity, attempting to recover the project will crash immediately. Because of this it is an **_extremely serious bug_** because if it happened in an existing project it would permanently destroy the project with no means of recovery.

**Comment by Paul-Licameli** [comment]
The feature of joining of mono to stereo is in a state of flux while I'm doing a massive transformation of how stereo data is managed.

I'll figure out how not to have a crash (probably not hard) but then don't expect the resulting track always to behave as you expect in alpha.

Having tracks with clips that don't align is a feature, or misfeature, that Audacity 3.4 will retract.  I'm rewriting many other places first to use the assumption that misaligned tracks don't exist, so different right hand channel data is ignored.  Only later, I will rewrite the piece that joins mono tracks into stereo, and it will correct clip misalignment in the result.

**Comment by Paul-Licameli** [comment]
I have opened a PR to fix the crash.  If you repeat the steps, the resulting stereo track will not draw the clip in the right hand channel.

Please do not include this misbehavior in the scope of this issue.  I will only fix the crash.  As I said, do not otherwise expect reasonable behavior yet when joining mono tracks with misaligned stereo clips.  That is a large task I'm planning for later in developing this release.

**Comment by petersampsonaudacity** [comment]
Worse still it crashes when you attempt the offered Recovery on relaunch

**Comment by Paul-Licameli** [comment]
> Worse still it crashes when you attempt the offered Recovery on relaunch

Are you referring to alpha or the branch with my proposed fix?

**Comment by petersampsonaudacity** [comment]
> Are you referring to alpha or the branch with my proposed fix?

alpha master

**Comment by Paul-Licameli** [comment]
> and it crashes if you try to open an old project that has non-aligned clips in a stereo tracks.

So don’t do that :-)

seriously these cases are not expected to work now as the program is undergoing a huge transformation.  I expect to address this but it is later in my plan.

**Comment by Paul-Licameli** [comment]
Watch the checkboxes in #4681

**Comment by Paul-Licameli** [comment]
Whatever the Make Stereo command will do in future to correct misaligned clips — it should also be applied to projects from 3.3 and earlier that contain such.

**Comment by Paul-Licameli** [comment]
But meanwhile I have told our full time QA not to spend time testing these cases.

**Comment by SteveDaulton** [comment]
Will there be a "beta" version before the next release?

**Comment by Paul-Licameli** [comment]
See issues #5200, #5202, #5203
