### ISSUE TITLE
Misleading error message when attempting to paste stereo into mono tracks

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#5105]
### Bug description

Attempting  to paste stereo into a pair of mono tracks says:

> There are not enough tracks selected to accommodate your copied content. Select additional tracks and try again.

This implies that pasting stereo into two mono tracks "should" work, yet no matter how many tracks are selected, the same error occurs.

### Steps to reproduce

1. Create a project containing one stereo track with audio, and two empty mono tracks.
2. Copy part of the stereo track
3. Select the two empty mono tracks
4. Paste

### Expected behavior

Either:

The left channel to be pasted into the first selected mono track, and the right channel pasted to the second selected mono track.

Or:

A sensible message to say that the action is not supported,

### Actual behavior

A message telling the user to select more tracks.

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

**Comment by petersampsonaudacity** [comment]
I get a more sensible message on W10 when I do this:
![image](https://github.com/audacity/audacity/assets/50205984/f53dea18-cd3f-46d3-9f01-54e85fb14c20)

**Comment by petersampsonaudacity** [comment]
In contrast I do note that one can paste from a mono track into a stereo track and the mono is pasted to both stereo :tracks:
![image](https://github.com/audacity/audacity/assets/50205984/1d0f3f5f-6a1c-4dc0-a2bd-29b98e448f02)

**Comment by SteveDaulton** [comment]
> I get a more sensible message on W10 when I do this:

Are you using a recent alpha version?

**Comment by petersampsonaudacity** [comment]
> Are you using a recent alpha version?

Yepper, you;re tight - the good message comes fom 3.3.3


With latest 3.4.0 alpha I too getL
![image](https://github.com/audacity/audacity/assets/50205984/34fd8902-23b1-4122-b667-348a2b9df5ee)

**Comment by LWinterberg** [comment]
this probably will be fixed with https://github.com/audacity/audacity/issues/4734

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
