### ISSUE TITLE
Massive clicks when overdubbing in a project containing muted tracks

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#5106]
### Bug description

When overdubbing in a project that contains muted tracks, random clicks that are almost full-scale amplitude may occur.
This does not always happen, but on my machine it occurs sufficiently often to make the current alpha version unusable for multi-track recording.

When it does occur, it may be a single isolated click, or dozens of clicks in rapid succession.

This issue  does not occur in Audacity 3.2.4 or 3.3.

### Steps to reproduce

These steps may not all be necessary, but on my machine they will produce clicks within a few seconds of overdub recording about 90% of the time:

1. Launch Audacity with default settings
2. Import a stereo audio track
3. Play a few seconds, then stop
4. Move cursor position to start ("<<" button)
5. Mute the track
6. Shift + R

### Expected behavior

Overdub recording in a new stereo track

### Actual behavior

Overdub recording with intermittent massive clicks.

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

**Comment by SteveDaulton** [comment]
This still happens with Audacity 3.4 beta:

![Trackpanel000](https://github.com/audacity/audacity/assets/11681097/acc2cccc-8475-48ba-a1d3-8eef329a3e91)

**Comment by chinakov** [comment]
Cannot be reproduced on Windows 11, but I will take a look on Linux as well.

**Comment by LWinterberg** [comment]
Here's a user who can reproduce it: https://forum.audacityteam.org/t/audacity-3-4-is-out-now/88434/8

PC Dell XPS15
Win11 64
Audacity 3.4.0 English
Headset Logitech Pro X wired version (USB connection) with Logitech G HUB version 2023.9

**Comment by crsib** [comment]
I still cannot reproduce it. When using WASAPI I have clicks sometimes when the playback starts (and not affecting the recording). However, in previous version of Audacity overdubbing simply doesn't work in a similar configuration.

**Comment by HaydenHildreth** [comment]
This is happening on my machine (Windows 11 Insider Build)

**Comment by dozzzzer** [comment]
I can reproduce this in 3.4.0-appimage, Ubuntu 22.04

It's worth mentioning that recording to a new track (Shift + R) behaves intermittently: in some cases, it would initiate recording, create a new track and then stop immediately, or after recording a tiny cliplet (see https://github.com/audacity/audacity/issues/4863)

 Every time it performs as anticipated though, it generates massive clicks for me.

The simplified STRs are:

1. generate chirp
2. mute it
3. Shift-click the Record button

**Comment by dozzzzer** [comment]
Tested
