### ISSUE TITLE
[Windows 8]: Error when opening "Check for updates"

### ISSUE THREAD

**Issue by TechySC23** [audacity/audacity#5107]
### Bug description

So, the bug is that whenever I open the Check for Updates button, it pops up with a error message saying:
"Update Data was corrupted." The Problem Details:
{
    "timestamp": 1693326781,
    "event_id": "d80bf6a0107bf34e8aa28ffde8630ba7",
    "platform": "native",
    "release": "audacity@3.3.2",
    "contexts": {
        "os": {
            "type": "os",
            "name": "Windows",
            "version": "6.2.9200"
        }
    },
    "exception": {
        "values": [
            {
                "type": "Error_checking_for_update",
                "value": "Update data was corrupted.",
                "mechanism": {
                    "type": "runtime_error",
                    "handled": false
                }
            }
        ]
    }
}

### Steps to reproduce

1. Click on Help Menu.
2. Click Check for Updates

### Expected behavior

Audacity should show the current version and also check if I am in the latest version or not.

### Actual behavior

An error message showing:
(Alert symbol) Update data was corrupted.

More information about this error may be available here (https://audacityteam.org/errors)
Would you like to send a report to help us fix the issue?
All the reports are anonymous. See our Privacy Policy for more info. (https://www.audacityteam.org/about/desktop-privacy-notice/)
The problem details:
{
    "timestamp": 1693327009,
    "event_id": "8f906bb39ebcfb4282a2cc31c4b35ce9",
    "platform": "native",
    "release": "audacity@3.3.2",
    "contexts": {
        "os": {
            "type": "os",
            "name": "Windows",
            "version": "6.2.9200"
        }
    },
    "exception": {
        "values": [
            {
                "type": "Error_checking_for_update",
                "value": "Update data was corrupted.",
                "mechanism": {
                    "type": "runtime_error",
                    "handled": false
                }
            }
        ]
    }
}

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows 8

### Additional context

I am on Audacity version 3.3.2. On Windows 8.

**Comment by petersampsonaudacity** [comment]
Works fine on W10 with 3.3.3 and 3.4.0 alpha test build

**Comment by TechySC23** [comment]
> Works fine on W10 with 3.3.3 and 3.4.0 alpha test build

Are you online?

**Comment by TechySC23** [comment]
Try it on a VM. May reproduce?

**Comment by petersampsonaudacity** [comment]
> > Works fine on W10 with 3.3.3 and 3.4.0 alpha test build
> 
> Are you online?

Of course - I need to be online to post here ...

**Comment by LWinterberg** [comment]
This should be fixed now
