### ISSUE TITLE
Set clip colors per clip; make color selection clearer

### ISSUE THREAD

**Issue by lordlouckster** [audacity/audacity#511]
Subtasks:

- [ ] Move coloring from track menu into a clip context menu
- [x] #2713
- [ ] Improve color palette of clip colors

<details>
<summary>original report </summary>
This request has been out for a while as different variants.
If you want to change colors, too bad. There are only four colors available, and you can't change the background color.

There should be all colors available; preset colors and ability to choose your own colors and set them to different track clips. There should also be an ability to change background colors for different clips as well.

My approach is something like this:
![Näyttökuva (24)](https://user-images.githubusercontent.com/57062013/81389909-45d9b580-9123-11ea-9ee7-953ee2842b42.png)
It would be nice if you were finally able to add it.

</details>

**Comment by LWinterberg** [comment]
This is fixed in Audacity 4.
