### ISSUE TITLE
Wrong display of time when punch and roll recording on an expanded clip

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5113]
### Steps to reproduce

1. Generate a 10-second chirp
2. Expand it to 30 seconds
3. Place the cursor somewhere at the very end of the clip (see the screen recording)
4. Transport > Recording > Punch and roll record
5. Observe

### Expected behavior

The time display of the recorded clip has no stretch factor applied to it.

### Actual behavior

Wrong display of time on the recorded clip. 
The time of the recorded audio goes appr. 3 times faster; the playhead doesn't catch up and the gap become larger as the recording continues:

https://github.com/audacity/audacity/assets/70063970/44cec9c2-80fb-4ccd-bcf2-8085b025ccc1

### Audacity Version

[Latest master](https://github.com/audacity/audacity/actions/runs/6050706064)

### Operating system

Windows, macOS

**Comment by saintmatthieu** [comment]
Strangely the bug wasn't always reproducible - here's the reason why:
In [this video](https://github.com/audacity/audacity/assets/22740106/732f8228-1d68-4bc2-bf79-9a248d3d0a0e),
1. I first place the cursor to the left sample and start the recording. In that case, a new clip is created.
2. Then, I place the cursor closer to the right sample, and no new clip is created.

This is the behaviour on current release, without stretching involved. I'm not sure what the default behaviour should be - probably appending if possible, as in 2.

With stretching, a new clip should be created if the existing clip is stretched.
