### ISSUE TITLE
Presets & Settings button does not pop up a window

### ISSUE THREAD

**Issue by evertvorster** [audacity/audacity#5114]
### Bug description

When clicking on the "Presets & Settings" button on all effects, including built-in effects, the window controlling the presets does not pop up. 

### Steps to reproduce

1. Open an audio file in Audacity.
2. Select any effect
3. Click on the Presets & Settings button

### Expected behavior

A window should pop up, controlling presets.

### Actual behavior

No window pops up.

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

Audacity is built from source on this Linux system, using local dependencies as far as possible.

About the system:
```
Operating System: Arch Linux 
KDE Plasma Version: 5.27.7
KDE Frameworks Version: 5.109.0
Qt Version: 5.15.10
Kernel Version: 6.4.12-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 32 × 13th Gen Intel® Core™ i9-13900HX
Memory: 62.5 GiB of RAM
Graphics Processor: Mesa Intel® Graphics
Manufacturer: Notebook
Product Name: PD5x_7xSNC_SND_SNE
System Version: Not Applicable
```

**Comment by LWinterberg** [comment]
FWIW: It's not supposed to open a window, but a menu

![image](https://github.com/audacity/audacity/assets/87814144/d630a1ba-7703-4585-9ea5-da7c138a2c17)

Does this also happen if you run Audacity in x11?

**Comment by evertvorster** [comment]
Hi there!

Ah, I never even thought to check, but yes, on X11 the pop up "menu" does pop up. 
Also, now that I have restarted my machine, it works under Wayland as well. Maybe it was a transient thing on an update?

In any case, thanks for looking at this report. I'll close it now, since it's all working now.
