### ISSUE TITLE
No playback when using Punch&Roll Recording (WITH OVERDUB)

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#5115]
### Bug description

With 3.4.0 alpha there is no playback of the run-in when using Punch&Roll Recording.

This is a regression on 3.3.3

### Steps to reproduce
1. Launch 3.3.3
2. get some audio
3. use Punch&Roll
4. Observe: the run-in audio is audibly played
5. launch 3.4.0 alpha
6. use Punch&Roll
7. Observe: the run=in is visually "played" but there is no sound

**Note that switching back to 3.3.3 and using P&R the run-in sound is again audibly played - so this implies 3.4.0 is NOT interfering at all with settings.**

### Expected behavior
Punch&Roll run-in to be audibly played

### Actual behavior
The Punch&Roll run-in is _**NOT**_ audibly played

### Audacity Version
current master / alpha / nightly build3.4.0 alpha 

### Operating system
Windows 10 - but assume all OS

### Additional context
None

**Comment by petersampsonaudacity** [comment]
Tagging @Paul-Licameli as Punch&Roll is his baby.

**Comment by Paul-Licameli** [comment]
> Tagging @Paul-Licameli as Punch&Roll is his baby.

Thanks for your diligence.  This is bad and surely must be fixed for beta.  I would give it P1.

“Pre-roll” rather than “run-in” is the term I would use.

**Comment by petersampsonaudacity** [comment]
Added a P1 Label as per @Paul-Licameli 's suggestion

**Comment by petersampsonaudacity** [comment]
> The bug only occurs when overdub is enabled.

Good catch @DavidBailes 

I almost always test with a purged audacity settings folder so I get default factory settings (unless the particular test requires otherwise).  

And for some **_strange_** reason that I, personally, have never understood Overdub is "on" by default - I've _**always**_ thought it should be off by default.

_AFAIK that was done so that those users who used overdubbing didn't have to bother to turn it on - nut in contrast many users, like me, who mainly used Audacity for vinyl/tape trranscription normally  want over dub off and we have to turn Software Playthrough "on".  So it always seemed to me that we were pandering to one set of users at the expense of the other (s)._

**Comment by LWinterberg** [comment]
> And for some strange reason that I, personally, have never understood Overdub is "on" by default - I've always thought it should be off by default.

good call, I'll look into that. Turning it off eliminates a class of portaudio errors anyway.

**Comment by Paul-Licameli** [comment]
> The bug only occurs when overdub is enabled. In void OnPunchAndRoll(const CommandContext &context), the setting up of the the playback stuff in TransportSequences is handled depending on overdub/duplex:
> 
> ```
> TransportSequences transportTracks;
> const auto duplex = ProjectAudioManager::UseDuplex();
> if (duplex)
>    // play all
>    transportTracks = MakeTransportTracks(
>       TrackList::Get( project ), false, true);
> else
>    // play recording tracks only
>    for (auto &pTrack : tracks)
>       if (pTrack->IsLeader())
>          transportTracks.playbackSequences.push_back(pTrack);
> ```
> 
> MakeTransportTracks() adds `shared_ptr<StretchingSequence>`s to TransportSequences.playbackSequences. Because of this, in bool ProjectAudioManager::DoRecord():, prerollTrack is computed to be false:
> 
> ```
> // If the track was chosen for recording and playback both,
> // remember the original in preroll tracks, before making the
> // pending replacement.
> const auto shared = wt->SharedPointer<WaveTrack>();
> // playbackSequences contains only leaders; prerollSequences should
> // be a subset of it.  Non-leader might not be found, but that is
> // all right.
> bool prerollTrack =
>    make_iterator_range(transportSequences.playbackSequences)
>       .contains(shared);
> ```

Thanks a lot for the exploration.  I will propose a fix.

Note that if you did P&R with overdub, then it may play tracks other than the one you are recording, if you have such, and it should continue to play those after the crossover point.

**Comment by petersampsonaudacity** [comment]
> Note that if you did P&R with overdub, then it may play tracks other than the one you are recording, if you have such, and it should continue to play those after the crossover point.

@LWinterberg  this is a very good reason as to why Overdub should really be "off" by default, I'm thinking.

**Comment by petersampsonaudacity** [comment]
Testing on W10  with @Paul-Licameli 's branch build for this:  audacity-win-3.4.0-alpha-20230908+a06ae83-x64

This looks to be fixed in your branch Paul - bit I do note your recent ancillary issue #5173

**Comment by dozzzzer** [comment]
tested

**Comment by petersampsonaudacity** [comment]
Looks good to me on W10 with latest 3.4.0 alpha test vuild
