### ISSUE TITLE
De-duplication of channel data: color and origin

### ISSUE THREAD

**Issue by vsverchinsky** [audacity/audacity#5116]
More elimination of duplicated track members that would need to be kept consistent across channels.

QA:
- [x] Shift a stereo track in time, delete the clip, then record more into the track
- [x] Changing WaveTrack color using the context menu; then recording a new clip which gets correct color
- [x] Persistency of wave track color choice in mono and stereo tracks (test it by making a new clip after reopening)
- [x] Mix-and-render (to new or to replacement track) keeps the color choice (again, make a new clip)
- [x] Swapping channels and splitting stereo preserve the color choice

**Comment by chinakov** [comment]
Tested, thank you!
