### ISSUE TITLE
Plot Spectrum fails on a stretched clip

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5119]
### Steps to reproduce

1. Stretch a 6-second stereo clip to, say, 20 seconds
2. Analyze > Plot Spectrum
3. Observe

@Paul-Licameli Also test:
- [ ] Make a good selection and open then dialog; but then make a bad selection of a stretched clip and Replot

### Expected behavior

A corresponding spectrum image in the Frequency Analysis dialog

### Actual behavior

It doesn't plot the spectrum, i.e., it shows the blank image. 

<img width="450" alt="Screenshot 2023-09-08 at 09 57 40" src="https://github.com/audacity/audacity/assets/70063970/861f1793-9abb-4f50-884c-91df69c9e7e2">

### Audacity Version

master

**Comment by Paul-Licameli** [comment]
I think the issue title needs an update.  In master now, it won’t freeze, but it will fail to plot anything.

**Comment by dozzzzer** [comment]
The bug has been updated

**Comment by saintmatthieu** [comment]
Currently on master: generate a 1kHz sine wave, change project tempo, plot spectrum.
Expected:
![image](https://github.com/audacity/audacity/assets/22740106/8fd442b0-c016-4a8e-9025-71c581e8c926)
Actual:
![image](https://github.com/audacity/audacity/assets/22740106/eebb4a7b-6035-44ef-9e1e-e58ac446583c)

I don't know why this shape. Maybe that's the spectrum of uninitialized data.

**Comment by Paul-Licameli** [comment]
> Currently on master: generate a 1kHz sine wave, change project tempo, plot spectrum. Expected: ![image](https://user-images.githubusercontent.com/22740106/266586094-8fd442b0-c016-4a8e-9025-71c581e8c926.png) Actual: ![image](https://user-images.githubusercontent.com/22740106/266586260-eebb4a7b-6035-44ef-9e1e-e58ac446583c.png)
> 
> I don't know why this shape. Maybe that's the spectrum of uninitialized data.

Yes, likely it's uninitialized data:  `GetFloats` returns false when there is any stretch on the track, but in master there is no check on the return value.

Notice the junk data makes very high positive dB values!

A small change in `WaveTrack::GetOne` to zero-fill the buffer when it fails would fix this and maybe other unchecked uses of `GetFloats` to behave at least with more determinism.

**Comment by saintmatthieu** [comment]
Then the spectrum would be blank, which would be a better indicator that there was an error, but that still wouldn't repair the feature.

**Comment by Tantacrul** [comment]
I know this is blasphemy... but if this fix is going to delay the release a lot, I would suggest we bump it for a patch release. Happy to hear arguments to the contrary.

This is just another example of how the major changes we introduce clash with legacy things.

**Comment by saintmatthieu** [comment]
Decision taken during stand-up: error message mentioning time-stretched clips as a know reason why this would happen. That's easy to implement.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @saintmatthieu 's branch build for this:  audacity-win-3.4.0-alpha-20230908+519eafe-x64

When I now try to run Plot Spectrum on a stretched clip I get this error message.
![image](https://github.com/audacity/audacity/assets/50205984/18720a47-7305-4bc4-bd5f-192ff8277689)

I find that message very opaque and unhelpful to the user.  Now I figured out that if I rendered the stretched track then I would be able to plot the spectrum - but that's _**only**_ as a result of the discussions I had with Matthieu on Thursday.  

Maybe the error message could suggest that the user renders the track and then retries.

**Comment by petersampsonaudacity** [comment]
BTW testing other shipped analyzers with a stretched clip shows that there are also issues with **Beat Finder** and **Label Sounds**

Should these be similarly blocked for use on stretched clips?

@LWinterberg @saintmatthieu 
should I log separate issues for these two.

**Comment by Paul-Licameli** [comment]
> BTW testing other shipped analyzers with a stretched clip shows that there are also issues with a) **Beat Finder** b) **Label Sounds**
> 
> Should these be similarly blocked for use on stretched clips?
> 
> @LWinterberg @saintmatthieu should I log separate issues for these two.

Did you try Find Clipping?

**Comment by Tantacrul** [comment]
@petersampsonaudacity - I agree. What do you think of this text instead?

_This audio could not be analysed.

If it has been time-stretched, then return it back to 100% speed and try again._

**Comment by petersampsonaudacity** [comment]
@Tantacrul 
it's humanly impossible to set it back to 100% size/speed once it's been stretched.  Apart from the fact that there is no visual cue indicator for the stretch facto (something I discussed with @saintmatthieu  on Thursday) the manual drags are not that precise it seems to me.

@LWinterberg  suggested in the Pull Request
>"Audio could not be analyzed. This may be due to a stretched clip. Try resetting any stretched clips, or mixing and rendering the tracks before analyzing." might be better

**Comment by petersampsonaudacity** [comment]
> Did you try Find Clipping?

@Paul-Licameli   -  yes and it seemed to work fine, nut the audio track I had has no clipping anyway.  I'll test further sometime.

**Comment by Paul-Licameli** [comment]
> > Did you try Find Clipping?
> 
> @Paul-Licameli - yes and it seemed to work fine, nut the audio track I had has no clipping anyway. I'll test further sometime.

I opened #5176 so add comments there

**Comment by Tantacrul** [comment]
@petersampsonaudacity it will be possible soon. There's one little bit of the design missing, which allows you to set a specific % and also to see precisely how much it has been stretched too.

@LWinterberg @saintmatthieu FYI
