### ISSUE TITLE
Reassign Clip name, color, start time without TrackList::Channels

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#5121]
Should depend on
- #5031

See also issue #5076 

Subtasks
- `WaveTrack::Interval` has member functions to set name, color, and start time in one or two `WaveClip`s
- `SetClipCommand` rewritten as a `SetTrackBase` using interval iteration
- Remove class `SetChannelsBase`
- `EffectRepeat` sets clip names using interval iteration
- `ProjectFileManager::AddImportedTracks` can loop over leader tracks only, and intervals, to set clip names

QA:
- [x] "Set Clip" macro command to change clip names, color, start time in mono and stereo
- [x] Use Repeat effect to replicate a clip in a track; observe clip names; swap channels or split the clip; undo/redo
- [x] Import tracks, observe clip names, swap, split, undo/redo
- [x] A clip (mono or stereo) can be dragged into a track of another color and keeps its different color; swap, split, undo/redo

**Comment by dozzzzer** [comment]
Tested

**Comment by Paul-Licameli** [comment]
It's done, but didn't auto-close because of a bit of confusion in the merging of PRs.
