### ISSUE TITLE
Trims aren't saved correctly on an audio clip of a different sample rate

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5125]
### Bug description

When trimming an audio clip of a different sample rate than the project, its trim regions aren't preserved correctly when the project is saved and re-opened.

### Steps to reproduce

1. Generate a 30-second chirp
2. Export it with the sample rate of 48 kHz
3. Reset config 
4. File > Open > Select the 48 kHz chirp from step 2
5. Trim it down to 5 seconds
6. Ctrl + S and give the project a name
7. Ctrl + W
8. Ctrl + O and select the project from step 6
9. Check the length of the chirp

### Expected behavior

5 seconds

### Actual behavior

~7 seconds

### Audacity Version

current master / alpha / nightly build

### Operating system

Other

### Additional context

Regression introduced by https://github.com/audacity/audacity/commit/e2f650c9562a050dfad30bb3b0040aa597afdf9f

**Comment by saintmatthieu** [comment]
So in your description, @vsverchinsky , we save a project of sample rate 44.1kHz which has a 48kHz track, and when re-opening it again, there the trim value isn't correct anymore, did I understand correctly ? In that case, it looks indeed like this will also fix https://github.com/audacity/audacity/issues/5171.

**Comment by dozzzzer** [comment]
Tested

**Comment by Paul-Licameli** [comment]
> Tested

Please also test #5171 which is addressed by the same PR
