### ISSUE TITLE
When swapping (or splitting) channels of a stereo track, the effects should not be removed from the (second) stack

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5127]
### Steps to reproduce

1. Have a stereo track
2. Add some effect(s) to the stack
3. Swap channels OR split the stereo track

### Expected behavior

The effects remain in the stack, or in both stacks.

### Actual behavior

The effects get removed from the stack (swapping) or from the second track's stack (splitting). When swapping channels
one more time, they re-appear.

### Audacity Version

current master / alpha / nightly build

### Operating system

Other

### Additional context

A regression against 3.3.3

**Comment by dozzzzer** [comment]
Bisects to https://github.com/audacity/audacity/commit/e5bc5d5818eef068b064d3a1f240f251834e26f0

**Comment by Paul-Licameli** [comment]
Bisects more exactly to 640275ef394617e6802131c3840250c41d862134 inside that PR

**Comment by petersampsonaudacity** [comment]
@dozzer @Paul-Licameli 

Note too that if you have two mono tracks and only the lower one has effects in its effects stack 
if you make a stereo track from those two tracks the the resultant stereo track has no effects in the effects stack (and playing the audio confirms that the right channel plays without added effects).

BUT if then then split the stereo track you observe (and hear) the the lower track (right channel) still has its effects in its effects stack.

**Comment by petersampsonaudacity** [comment]
I also confirm the Swap Stereo Channels behavior that @dozzzzer reports.

Bit also note that if you swap the channels back again, then the effects stack is restored.

**Comment by dozzzzer** [comment]
The bug is still reproducible in PR #5128:

https://github.com/audacity/audacity/assets/70063970/6743b292-a812-403f-adb9-540741251d8c

**Comment by dozzzzer** [comment]
Fixed in PR #5130

**Comment by petersampsonaudacity** [comment]
Testing on W10 latest alpha master:  audacity-win-3.4.0-alpha-20230907+5f43627-x64-msvc2022

This issue as logged tests OK on the latest 3.4.0 master.

But there is an associated residual when making a stereo track from tracks with different effects stacks - I will log this separately
