### ISSUE TITLE
Rewrite change of rate

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#5131]
A pretty easy task in the checklist for restructuring.  Note that `WaveTrack::SetRate` must also update rate in every `WaveClip`.

- [x] The loop over channels in `RateMenuTable::SetRate` is lowered into the `WaveTrack` member function
- [x] Change `wxASSERT` to `assert`
- [x] The call to `SetRate` in `WaveTrack::Resample` must be lifted out of the loop
- [x] Examine other uses of `SetRate` and convince yourself they are always done on leaders or tracks with no clips, so need no change

QA:
- [x] Change rates on tracks using the track's context menu (this is NOT resampling but just reassignment of rate, which changes pitch)
- [x] Then observe that swapping channels or splitting stereo keeps the correct rates
- [x] Also test resampling (in the main Track pull-down menu)

**Comment by chinakov** [comment]
This is tested, thank you!
