### ISSUE TITLE
Opus import crashes 3.4.0 alpha

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#5132]
### Bug description
Attempting to import an Opus file with 3.4.0 alpha causes Audacity to crash when ujsing the File>Import command
or to hang when using drag&drop to effect the import

This is a regression on 3.3.3

I cannot send the phone-home error log as that fails to work

_Export of an Opus audio file works fine with 3.4.0_

### Steps to reproduce
1. launch 3.3.3
2. import an Opus file
3. Observe: it imports OK
4. launch 3.4.0 alpha
5. Import the same Opus file
6. Observe:  Audacity crashes

### Expected behavior
Opus files should be properly imported

### Actual behavior
Audacity crashes when you try to import an Opus audio file

### Audacity Version
3.4.- alpha

### Operating system
Windows 10 - but assume all OS

### Additional context
See also this Discussion thread (which prompted this testing)
**Cannot import opus #4288**

**Comment by petersampsonaudacity** [comment]
I tested all the other supported imports and they all work fine with 3.4.0
![image](https://github.com/audacity/audacity/assets/50205984/c80c694d-7555-47c0-9d1a-93a55f5b7247)

**Comment by crsib** [comment]
The crash affects all FFmpeg imports with non trivial stream start time.

**Comment by dozzzzer** [comment]
It still crashes on Windows in the[ latest master build](https://github.com/audacity/audacity/actions/runs/6317682945)

**Comment by crsib** [comment]
@vsverchinsky FYI

**Comment by dozzzzer** [comment]
The issue only seems to occur on my Windows VM and not on my Win10 laptop.
