### ISSUE TITLE
Change temp/pitch/speed effect + trimming or non-destructive tempo end of clip reveals spurious clip

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#5135]
### Steps to reproduce

1. Generate a chirp
2. Open change tempo effect and change speed by 10%
3. trim end of clip or change tempo by dragging end of clip

### Expected behavior

After step 3:
![image](https://github.com/audacity/audacity/assets/11887021/5eec1ff8-2253-4d9b-b646-a98de6fccfe2)

or
![image](https://github.com/audacity/audacity/assets/11887021/3339f1ed-f419-4370-b83d-b1893159b80b)

respectively

### Actual behavior

After step 3:
![image](https://github.com/audacity/audacity/assets/11887021/bf2f7fa4-effb-43ee-b537-a27f0f2a8d13)

or

![image](https://github.com/audacity/audacity/assets/11887021/59c40df6-fd0e-4ac9-818d-ad69fdb65679)

respectively

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

**Comment by saintmatthieu** [comment]
Thanks for the report, @DavidBailes !
It looks like one of my currently being reviewed PRs fixes this, but I don't know how yet, so at least there'll be a need for investigation.

**Comment by dozzzzer** [comment]
Fixed by #5138
