### ISSUE TITLE
Audacity hangs on start in Ubuntu 20.04 due to missing libgail-gnome.so

### ISSUE THREAD

**Issue by fat-tire** [audacity/audacity#514]
Started Audacity 2.3.3 in Ubuntu 20.04 (and before that in 19.04),and it it hangs.

Why is this?  it took me FOREVER to figure out.  The message `(Audacity:202976): Gnome-WARNING **: 00:29:28.351: Accessibility: failed to find module 'libgail-gnome' which is needed to make this application accessible` was a clue something was wrong here.  

Then, in strace:

```
...
access("/usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libgail-gnome.so", F_OK) = -1 ENOENT (No such file or directory)
access("/usr/lib/x86_64-linux-gnu/../gtk-2.0/modules/libgail-gnome.so", F_OK) = -1 ENOENT (No such file or directory)
access("/usr/lib/x86_64-linux-gnu/libgail-gnome.so", F_OK) = -1 ENOENT (No such file or directory)
access("/usr/lib/x86_64-linux-gnu/../libgail-gnome.so", F_OK) = -1 ENOENT (No such file or directory)
ioctl(2, TCGETS, {B38400 opost isig icanon echo ...}) = 0
...
```
Eventually several lines down was a `futex(0x7fc2973e8f38, FUTEX_WAIT_PRIVATE, 339, NULL)` and Audacity just hung/froze.

`libgail-gnome` is not a package that is available for ubuntu any more, although `libgail-common` is, and I do have it installed.  But that wasn't enough to make Audacity happy.

Searching for this issue lead me to [this very old thread](https://forum.audacityteam.org/viewtopic.php?f=48&t=90537&start=10), which discussed the problem:

> monnerat wrote:
> I found the solution:
> Gnome2 accessibility is enabled and this requires libgail-gnome which is not available anymore :(
> This occurs even if audacity is compiled with wxGTK3.
> 
> To disable gnome2 accessibility, use the command:
> 
> gconftool-2 --set /desktop/gnome/interface/accessibility --type bool false
>
> After that, audacity starts properly again

For what it's worth, I do have the package `libgail-common` installed, which provides these in `/usr/lib`:
```
i386-linux-gnu/libgailutil.so.18.0.1
i386-linux-gnu/libgailutil.so.18
i386-linux-gnu/gtk-2.0/modules/libgail.so
x86_64-linux-gnu/libgailutil.so.18.0.1
x86_64-linux-gnu/libgailutil.so.18
x86_64-linux-gnu/gtk-2.0/modules/libgail.so
x86_64-linux-gnu/libgailutil-3.so.0
x86_64-linux-gnu/libgailutil-3.so.0.0.0
```
Maybe I could have symlinked them to one of the files Audacity was looking for, but no need, that `gconftool-2` command fixed the issue immediately.

The solution is probably to check for the `libgailutil.so` or `libgail.so`version (assuming they work) or fail more gracefully if `libgail-gnome.so` can't be found and is actually needed.

Thanks!  Love audacity- been using it forever.

ft

**Comment by fat-tire** [comment]
(BTW this may not be an Audacity issue per se but wanted to put it here JIC)

**Comment by JamesCrook** [comment]
Closing:

> (BTW this may not be an Audacity issue per se but wanted to put it here JIC)
