### ISSUE TITLE
Loop region is not tied to project tempo

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#5142]
https://github.com/audacity/audacity/assets/87814144/859ebf49-7488-4b0a-b9a7-6408a3369214

Instead, it stays "glued" to the original time.

Desired behavior: the loop region should be moving with the project tempo and be "glued" to the corresponding beats and measures.

**Comment by crsib** [comment]
I think this one is fixed. @dozzzzer @chinakov

**Comment by dozzzzer** [comment]
It's fixed indeed.
