### ISSUE TITLE
Synced label track (and label) does not sync when the audio is stretched

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#5143]
### Bug description
When you have audio in a sync-locked track group (defined by the label track below it) and stretch the audio to either expand or contract then the label track is not synced with the stretch of the audio

In contrast if the clip is moved left or right then the sync-locking of the label track works - see STR step 6

### Steps to reproduce
1. turn sync locking on
2. generate a 30 second chirp
3. label the whole chirp with region label (Ctrl+B)
4. Zoom out one level
5. drag the clip rightwards so that it starts at 15 seconds
6. Observe: the label track moves in sync - _expected behavior_
7. negative stretch the clip from the right so that it become 15 seconds long
8. Observe: the label track is **_NOT_** synced with the audio

### Expected behavior
The label track and especially the label for the audio should be stretched in sync with the audio stretching.  

### Actual behavior
![image](https://github.com/audacity/audacity/assets/50205984/c552af90-85ee-49b9-ada3-6fbadffdd71d)

### Audacity Version
latest 3.4.0 alpha

### Operating system
Windows 10 but assume all OS

### Additional context
Similar happens when you use smart clip to reduce the size of the clip down to 15 seconds - but in this case I do not expect the label to sync as there is actually a "hidden" 15 seconds of audio.

Tagging @saintmatthieu @LWinterberg  @crsib 
This is the underlying problem with labels rather than on-track markers - with labels the audio has no idea that the label "belongs" to it.   Thus this may be a design quirk that we just have to live with - you certainly don't want labels to the right of such a label to move in sync as that are likely to be labeling audio that properly does **not** move when the audio clip is stretched in either direction.

**Comment by saintmatthieu** [comment]
Thanks @petersampsonaudacity !
This behaviour can already be observed on current release 3.3.3, when trimming is used in place of stretching.
This report is similar to #5090, only in the one, size change is expected on the label track, and in the other, on other clips of other tracks.
What would be the use of the expected behaviour, @petersampsonaudacity and @dozzzzer (reporter of #5090) ? Implementation-wise I reckon this to be sticky: what do you do with colliding clips ? What do you do with clips reduced to zero ? Should the "slave clips", in the case of stretching, be stretched proportionally or not ?

**Comment by petersampsonaudacity** [comment]
See also:   **In a sync-locked track group, time-stretching or trimming a clip doesn't cause other tracks of the group to shift #5090** 

which looks to be a close cousin of this one.

**Comment by LWinterberg** [comment]
> This is the underlying problem with labels rather than on-track markers - with labels the audio has no idea that the label "belongs" to it. Thus this may be a design quirk that we just have to live with 

exactly that.
