### ISSUE TITLE
Appending buffers to alternate channels, with exception safety and preservation of clip alignment

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#5156]
Task breakdown:
- [x] Weaken the stated invariant on `WaveClip::mSequences`: the vector of sequences have non-increasing lengths (right channel is not longer than left, assuming two channels)
   - [x] change `CheckInvariants` to match that
   - [x] remove comment in `GetNumSamples`
- [x] Do not assume equal append buffer lengths either
   - [x] So rewrite `WaveClip::GetAppendBufferLen` and functions that use it
   - [x] And  `WaveClipWaveformCache::GetWaveDisplay` needs the maximum length to paint both channels correctly 

QA:
- [x] Drawing of stereo tracks (wave or spectrogram) during recording always shows channels as having same length
- [x] Recording to stereo tracks, including tests of exception handling when external drive runs out of storage
- [x] One of these: Change Speed, Paulstretch, Compressor, Mix Stereo To Mono, Change Tempo, Sliding Stretch, EQ, Noise Reduction
- [x] Tone, Chirp, or Noise
- [x] A Nyquist effect
- [x] Import, any file format

**Comment by chinakov** [comment]
@Paul-Licameli - quick clarification, I see that the task breakdown checklist items are not checked. Does this not block the QA progress? Just making sure.

**Comment by Paul-Licameli** [comment]
> @Paul-Licameli - quick clarification, I see that the task breakdown checklist items are not checked. Does this not block the QA progress? Just making sure.

Those were notes to myself months ago and for possible delgation to another developer.  You can ignore them.

**Comment by chinakov** [comment]
@Paul-Licameli - thank you!
