### ISSUE TITLE
Can't enter hash sign (#) into a track label on macOS Ventura using Swiss German Keyboard layout.

### ISSUE THREAD

**Issue by bwagner** [audacity/audacity#5163]
### Bug description

When attempting to enter a hash sign (#) into a label on macOS Ventura using Swiss German Keyboard layout (Option-3), there's a beep and the character is not added to the label. This behaviour was already present at least on macOS Mojave and Audacity 3.2.4.
I have checked Preferences>Keyboard and Option-3 is not assigned to anything.
When Switching to "US International - PC" keyboard, the hash sign is entered using Shift-3 and works as expected when editing a track label.
Workaround: Copy the hash sign into the clipboard and paste it into the track label.
E.g. In the Terminal enter `echo -n \#|pbcopy` which copies the hash sign into the clipboard, then paste it into Audacity's track label. @DavidBailes has a [better workaround](https://github.com/audacity/audacity/issues/5163#issuecomment-1710019865)

### Steps to reproduce

1. Switch your Keyboard to Swiss-German Layout in System Settings>Keyboard Layout
2. Start Audacity
3. Press Cmd+B to create a label
4. Press Option+3 to create the # character

### Expected behavior

The # character is added to the label.

### Actual behavior

Beep and # character not added.

### Audacity Version

latest stable version (from audacityteam.org/download) 3.3.3

### Operating system

macOS Ventura 13.5.1

### Workaround
Copy the hash sign into the clipboard (e.g. use Audacity's Rename Track Dialog to enter the character, copy it into the clipboard, then Cancel) and paste it into the track label.
Or: In the Terminal enter `echo -n \#|pbcopy` which copies the hash sign into the clipboard, then paste it into Audacity's track label. @DavidBailes has a [better workaround](https://github.com/audacity/audacity/issues/5163#issuecomment-1710019865)

**Comment by dozzzzer** [comment]
I could reproduce this on macOS 13.0 in recent `master`

**Comment by DavidBailes** [comment]
I use Windows rather than MacOS, but I'm pretty sure that another workaround would be to set the following option: In preferences, on the Tracks Behaviors page, set the "Use dialog for the name of a new label" check box.

**Comment by mcdurdin** [comment]
This also impacts Keyman users; see keymanapp/keyman#523. We have had multiple reports of this; here are two of them:
* https://community.software.sil.org/t/mac-m2-computers-not-working-with-keyman/8554/3
* https://community.software.sil.org/t/keyman-win10-no-longer-recognized-by-newer-audacity-versions/536

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.

**Comment by bwagner** [comment]
For the record, just realized the same issue with another character: @.
