### ISSUE TITLE
Unable to build Audacity with local libjpeg-turbo

### ISSUE THREAD

**Issue by evertvorster** [audacity/audacity#5168]
### Bug description

Arch recently updated libtiff to depend on a newer libturbo-jpeg. 
Unfortunately, the libturbo-jpeg that is provided by Conan is not compatible with the system's libtiff, as it is expecting the system's libjpeg-turbo.

This is referenced in #5157, but that bug is misleading, as I was not fully aware of the issues at play.

I did a little deeper digging and I got to this conclusion. 

One of the things I have tried is to make Conan use the system's libjpeg-turbo, but there does not seem to be a switch for it in the Makefile.

### Steps to reproduce

Try to build Audacity with local libraries provided by Conan on a fully up to date Arch system.

### Expected behavior

A compile without any errors. 

### Actual behavior

Build fails with this error:
```
[ 31%] Generating ../Release/nyquist/xm.lsp
/usr/bin/ld: /usr/lib/libtiff.so.6: undefined reference to `jpeg12_write_raw_data@LIBJPEG_8.0'
/usr/bin/ld: /usr/lib/libtiff.so.6: undefined reference to `jpeg12_read_scanlines@LIBJPEG_8.0'
```

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

I am thinking that we should rather have Conan provide less and less libraries and prefer to use up to date packages from the host system as a way forward to get away from requiring really old libraries to build Audacity. 

There is precious little information on the lifjpeg-turbo in the build instructions, it is not even listed as a dependency, but Conan pulls in a pre-built version of it in any case.

**Comment by crsib** [comment]
So the bug is that on your system the default Audacity configuration peeks system libtiff instead of Conan provided one. I will surely take a look and fix that :-)

> I am thinking that we should rather have Conan provide less and less libraries and prefer to use up to date packages from the host system as a way forward to get away from requiring really old libraries to build Audacity.

This would be only possible on Linux, but even on Linux, for most cases, we would have to rely on much older versions of the libraries than we do when using Conan. There are different Linux distributions, that have different policies on updating packages.

On top of that, let me remind you that Audacity can be built using only system-provided libraries, so I don't understand your point about Conan. You can just disable it. This will break fancy UI with Calf, but it is half-broken right now anyway.

**Comment by evertvorster** [comment]
Hi there!

If you can fix building with Conan on recent Arch that would be absolutely great!

I use the fancy UI on Calf and LSP plugins, so that I can see what I am doing when cleaning up audio for my videos. 

Not having it work is quite the deal breaker for me, and that's why I spend some time maintaining the Arch Aur package audacity-local-git whose sole purpose it is to build Audacity from source with the packages from Conan.

This is just a stopgap measure until Audacity supports having the fancy UI and being built with a completely up to date WxWidgets, or WxWidgets is replaced with something else that provides those some fancy UI's. I know it's a mammoth task to fix that, but depending on a singular version of a package is slow suicide for a project. It's like a cancer that pulls in and freezes more and more supporting libraries until it's completely unbuildable.

While you have a look at why the system's libtiff is being peeked, I'll hold back the version of libtiff on my system for as long as I can, until it starts causing issues elsewhere.

**Comment by evertvorster** [comment]
I just checked today, and the configuration is still peeking the system libtiff instead of the provided one. 

Does this require a huge effort to fix?

**Comment by evertvorster** [comment]
From the names of the commits that are going in now, it looks like you might be getting ready for a new release?

I checked again today, and with libtiff 4.6.0 installed, audacity does not build with conan supplied dependencies:
```
[ 31%] Generating ../Release/locale/sv/LC_MESSAGES/audacity.mo
[ 31%] Building CXX object libraries/lib-components/CMakeFiles/lib-components.dir/ComponentInterface.cpp.o
[ 31%] Building CXX object lib-src/libnyquist/CMakeFiles/libnyquist.dir/nyquist/nyqstk/src/ADSR.cpp.o
[ 31%] Generating ../Release/locale/ta/LC_MESSAGES/audacity.mo
[ 31%] Generating ../Release/locale/tg/LC_MESSAGES/audacity.mo
[ 31%] Built target lib-uuid
/usr/bin/ld: /usr/lib/libtiff.so.6: undefined reference to `jpeg12_write_raw_data@LIBJPEG_8.0'
/usr/bin/ld: /usr/lib/libtiff.so.6: undefined reference to `jpeg12_read_scanlines@LIBJPEG_8.0'
[ 31%] Building CXX object lib-src/libnyquist/CMakeFiles/libnyquist.dir/nyquist/nyqstk/src/BandedWG.cpp.o
[ 31%] Building CXX object libraries/lib-ipc/CMakeFiles/lib-ipc.dir/IPCServer.cpp.o
/usr/bin/ld: /usr/lib/libtiff.so.6: undefined reference to `jpeg12_write_scanlines@LIBJPEG_8.0'
/usr/bin/ld: /usr/lib/libtiff.so.6: undefined reference to `jpeg12_read_raw_data@LIBJPEG_8.0'
[ 32%] Building CXX object libraries/lib-basic-ui/CMakeFiles/lib-basic-ui.dir/BasicUI.cpp.o
[ 32%] Generating ../Release/locale/tr/LC_MESSAGES/audacity.mo
collect2: error: ld returned 1 exit status
make[2]: *** [libraries/lib-string-utils/tests/CMakeFiles/lib-string-utils-test.dir/build.make:116: tests/lib-string-utils-test] Error 1
[ 32%] Generating ../Release/locale/uk/LC_MESSAGES/audacity.mo
make[1]: *** [CMakeFiles/Makefile2:2249: libraries/lib-string-utils/tests/CMakeFiles/lib-string-utils-test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Is there any chance of showing this one some love before the release?
This may be a golden opportunity to try and lessen Audacity's reliance on really old libraries?

**Comment by crsib** [comment]
I will look at it again, probably after the beta release, but it is pretty complicated TBH. 

> This may be a golden opportunity to try and lessen Audacity's reliance on really old libraries?

We have other Linux distros where Audacity builds and runs besides Arch. There is a chance to break them up, as it already happened with SBSMS library. It is easy to upgrade the libjpeg, but there are no guarantees about API or ABI compatibility because there was a major version bump for libjpeg-turbo. BTW the new version of the library got out just over 3 months ago, so calling the version before it "really old" isn't exactly fair.

Audacity doesn't even need TIFF (or modern libjpeg-turbo for that matter).

**Comment by crsib** [comment]
And as far as I remember the main reason for you to build Audacity from source is to make Calf work, which happens because Audacity targets a dinosaur-level-ancient GTK2 by default

**Comment by evertvorster** [comment]
Well, it's a little more than just Calf, actually. It's all plugins that put up a nice graphical display for whatever filter is needed. 

Currently I am using LSP plugins to give me a graphical equalizer so that I can see what I am doing and adjust Q values in a visual sort of way. It's really neat, and the main reason I use Audacity. 

I, for one would be really happy if we could have the graphical parts of VST plugins display without having to use the very specific wxWidgets libraries and all the old libraries that it needs. 

By the way, I was not calling tiff library really old, I just thought it might be an option to use system libtiff completely, rather than a conan one.  Ultimately, I suppose, there would be no special libraries needed for Audacity to build and be useful for graphical plugins. I do see a LOT of work going into Audacity's code base. A really impressive amount actually, and I am assuming that major parts of the codebase is being rewritten to be less dependent on specific libraries...

**Comment by crsib** [comment]
> to use system libtiff completely

But that is the problem - the system version of tiff is picked up, which was built against libjpeg-turbo 2 :-) And Audacity doesn't even need tiff :-)

**Comment by evertvorster** [comment]
The sad part is that there is no quick fix for this issue. A monumental amount of work is required no matter which way is chosen to get out of this situation.

Thanks so much for putting in your time and taking the trouble to fix this.

**Comment by crsib** [comment]
I think you can unblock your workflow by doing a clean configure with `-Daudacity_use_jpeg=system`.

This worked for me now:

```
> cmake -GNinja -B build/system-jpeg -S projects/audacity -Daudacity_use_jpeg=system
> cmake --build build/system-jpeg/ --parallel
``` 

I dunno why it failed for me 3 weeks ago.

This is by no means a final solution, this workaround shouldn't be needed at all.

**Comment by evertvorster** [comment]
It builds, but then fails on the linker:
```
[ 99%] Linking CXX executable ../Release/bin/audacity
/usr/bin/ld: /usr/lib/libtiff.so.6: undefined reference to `jpeg12_read_raw_data@LIBJPEG_8.0'
/usr/bin/ld: /usr/lib/libtiff.so.6: undefined reference to `jpeg12_write_raw_data@LIBJPEG_8.0'
/usr/bin/ld: /usr/lib/libtiff.so.6: undefined reference to `jpeg12_read_scanlines@LIBJPEG_8.0'
/usr/bin/ld: /usr/lib/libtiff.so.6: undefined reference to `jpeg12_write_scanlines@LIBJPEG_8.0'
```

Anyways, I tried changing tack and building with only the bare minimum of libraries provided by Conan, with the same result as above.

**Comment by evertvorster** [comment]
It was a real adventure to figure out that portmidi is configured with the -Saudacity_use_midi=local. 

Unfortunately, this still fails to link, with the same error as above. 
This tells me that most likely the conan provided wxWidgets has a hidden link against system libtiff that it never told anyone about.

**Comment by crsib** [comment]
Hmm, that's much later already. 

Do you have Conan installed on your system? Have you deleted your build folder before reconfiguring?

>  libtiff

There is a transitive dependency, but when you build with `audacity_use_jpeg=system`, there should be no link to the local libjpeg-turbo.

My guess is that you had old generators folder, and by the search rules of `find_package` you got the local jpeg, not a system one.

Can you please try something like this?

```bash
> rm -rf build
> mkdir -p build/conan/env
> cmake -GNinja -B build -S audacity -Daudacity_use_jpeg=system
> cmake --build build/system-jpeg --parallel
```

This should force the build system to create a completely isolated environment.

**Comment by crsib** [comment]
FWIW this is how the dependencies tree looks like when you build with the options above

```
dvedenko@crsib-desktop ~/p/audacity (master)> lddtree ../../build/system-jpeg/Debug/bin/audacity 
../../build/system-jpeg/Debug/bin/audacity (interpreter => /lib64/ld-linux-x86-64.so.2)
    lib-theme-resources.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-theme-resources.so
    lib-graphics.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-graphics.so
    lib-project-file-io.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-project-file-io.so
    lib-wx-init.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-wx-init.so
    lib-time-track.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-time-track.so
    lib-snapping.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-snapping.so
    lib-audio-io.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-audio-io.so
    lib-import-export.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-import-export.so
    lib-export-ui.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-export-ui.so
    lib-file-formats.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-file-formats.so
    lib-vst.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-vst.so
    lib-lv2.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-lv2.so
    lib-ladspa.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-ladspa.so
    lib-vst3.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-vst3.so
    libatomic.so.1 => /usr/lib/libatomic.so.1
    lib-tags.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-tags.so
    lib-shuttlegui.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-shuttlegui.so
    lib-theme.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-theme.so
    lib-wx-wrappers.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-wx-wrappers.so
    libgtk-x11-2.0.so.0 => /usr/lib/libgtk-x11-2.0.so.0
        libgmodule-2.0.so.0 => /usr/lib/libgmodule-2.0.so.0
        libXfixes.so.3 => /usr/lib/libXfixes.so.3
    libgdk-x11-2.0.so.0 => /usr/lib/libgdk-x11-2.0.so.0
        libXrender.so.1 => /usr/lib/libXrender.so.1
        libXinerama.so.1 => /usr/lib/libXinerama.so.1
        libXi.so.6 => /usr/lib/libXi.so.6
        libXrandr.so.2 => /usr/lib/libXrandr.so.2
        libXcursor.so.1 => /usr/lib/libXcursor.so.1
        libXcomposite.so.1 => /usr/lib/libXcomposite.so.1
        libXdamage.so.1 => /usr/lib/libXdamage.so.1
        libXext.so.6 => /usr/lib/libXext.so.6
    libpangocairo-1.0.so.0 => /usr/lib/libpangocairo-1.0.so.0
    libatk-1.0.so.0 => /usr/lib/libatk-1.0.so.0
    libcairo.so.2 => /usr/lib/libcairo.so.2
        libpng16.so.16 => /usr/lib/libpng16.so.16
        libxcb.so.1 => /usr/lib/libxcb.so.1
            libXau.so.6 => /usr/lib/libXau.so.6
            libXdmcp.so.6 => /usr/lib/libXdmcp.so.6
        libxcb-render.so.0 => /usr/lib/libxcb-render.so.0
        libxcb-shm.so.0 => /usr/lib/libxcb-shm.so.0
        libpixman-1.so.0 => /usr/lib/libpixman-1.so.0
    libgdk_pixbuf-2.0.so.0 => /usr/lib/libgdk_pixbuf-2.0.so.0
        libjpeg.so.8 => /usr/lib/libjpeg.so.8
        libtiff.so.6 => /usr/lib/libtiff.so.6
            libzstd.so.1 => /usr/lib/libzstd.so.1
            liblzma.so.5 => /usr/lib/liblzma.so.5
            libjbig.so.2.1 => /usr/lib/libjbig.so.2.1
    libgio-2.0.so.0 => /usr/lib/libgio-2.0.so.0
        libmount.so.1 => /usr/lib/libmount.so.1
            libblkid.so.1 => /usr/lib/libblkid.so.1
    libpangoft2-1.0.so.0 => /usr/lib/libpangoft2-1.0.so.0
    libpango-1.0.so.0 => /usr/lib/libpango-1.0.so.0
        libfribidi.so.0 => /usr/lib/libfribidi.so.0
        libthai.so.0 => /usr/lib/libthai.so.0
            libdatrie.so.1 => /usr/lib/libdatrie.so.1
    libgobject-2.0.so.0 => /usr/lib/libgobject-2.0.so.0
        libffi.so.8 => /usr/lib/libffi.so.8
    libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0
        libgraphite2.so.3 => /usr/lib/libgraphite2.so.3
    libfontconfig.so.1 => /usr/lib/libfontconfig.so.1
    libfreetype.so.6 => /usr/lib/libfreetype.so.6
        libbz2.so.1.0 => /usr/lib/libbz2.so.1.0
        libbrotlidec.so.1 => /usr/lib/libbrotlidec.so.1
            libbrotlicommon.so.1 => /usr/lib/libbrotlicommon.so.1
    libwx_gtk2u_xrc-3.1.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/libwx_gtk2u_xrc-3.1.so
        libICE.so.6 => /usr/lib/libICE.so.6
        libgthread-2.0.so.0 => /usr/lib/libgthread-2.0.so.0
        libpangoxft-1.0.so.0 => /usr/lib/libpangoxft-1.0.so.0
            libXft.so.2 => /usr/lib/libXft.so.2
        libXtst.so.6 => /usr/lib/libXtst.so.6
    libwx_gtk2u_qa-3.1.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/libwx_gtk2u_qa-3.1.so
    libwx_gtk2u_aui-3.1.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/libwx_gtk2u_aui-3.1.so
    libwx_gtk2u_html-3.1.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/libwx_gtk2u_html-3.1.so
    libwx_baseu_xml-3.1.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/libwx_baseu_xml-3.1.so
    libexpat.so.1 => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/libexpat.so.1
    libwx_baseu_net-3.1.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/libwx_baseu_net-3.1.so
    libwx_gtk2u_adv-3.1.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/libwx_gtk2u_adv-3.1.so
    libwx_gtk2u_core-3.1.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/libwx_gtk2u_core-3.1.so
    libpng16d.so.16 => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/libpng16d.so.16
    lib-effects.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-effects.so
    lib-wave-track.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-wave-track.so
    lib-stretching-sequence.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-stretching-sequence.so
    lib-time-and-pitch.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-time-and-pitch.so
    lib-sample-track.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-sample-track.so
    lib-mixer.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-mixer.so
    lib-audio-graph.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-audio-graph.so
    lib-playable-track.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-playable-track.so
    lib-track-selection.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-track-selection.so
    lib-track.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-track.so
    lib-time-frequency-selection.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-time-frequency-selection.so
    lib-screen-geometry.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-screen-geometry.so
    lib-command-parameters.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-command-parameters.so
    lib-numeric-formats.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-numeric-formats.so
    lib-project-rate.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-project-rate.so
    lib-audio-devices.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-audio-devices.so
    libasound.so.2 => /usr/lib/libasound.so.2
    lib-realtime-effects.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-realtime-effects.so
    lib-project-history.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-project-history.so
    lib-project.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-project.so
    lib-transactions.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-transactions.so
    lib-math.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-math.so
    lib-channel.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-channel.so
    lib-registries.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-registries.so
    lib-module-manager.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-module-manager.so
    lib-xml.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-xml.so
    lib-string-utils.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-string-utils.so
    lib-files.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-files.so
    lib-preferences.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-preferences.so
    lib-components.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-components.so
    lib-exceptions.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-exceptions.so
    lib-basic-ui.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-basic-ui.so
    lib-strings.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-strings.so
    libwx_baseu-3.1.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/libwx_baseu-3.1.so
    libz.so.1 => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/libz.so.1
    libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0
        libpcre2-8.so.0 => /usr/lib/libpcre2-8.so.0
    libX11.so.6 => /usr/lib/libX11.so.6
    libSM.so.6 => /usr/lib/libSM.so.6
    libuuid.so.1 => /usr/lib/libuuid.so.1
    lib-ipc.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-ipc.so
    lib-utility.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/lib-utility.so
    libportmidi.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/libportmidi.so
    libportmidi_s.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/libportmidi_s.so
    libsndfile.so.1 => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/libsndfile.so.1
    libvorbisenc.so.2.0.12 => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/libvorbisenc.so.2.0.12
    libvorbis.so.0.4.9 => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/libvorbis.so.0.4.9
    libFLAC++.so.10 => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/libFLAC++.so.10
    libFLAC.so.12 => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/libFLAC.so.12
    libogg.so.0 => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/libogg.so.0
    libopus.so.0 => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/libopus.so.0
    libm.so.6 => /usr/lib/libm.so.6
    libportaudio.so => /home/dvedenko/build/system-jpeg/Debug/lib/audacity/libportaudio.so
        libjack.so.0 => /usr/lib/libjack.so.0
            libpipewire-0.3.so.0 => /usr/lib/libpipewire-0.3.so.0
    libstdc++.so.6 => /usr/lib/libstdc++.so.6
    libgcc_s.so.1 => /usr/lib/libgcc_s.so.1
    libc.so.6 => /usr/lib/libc.so.6
```

**Comment by evertvorster** [comment]
*Success!*

So, I blew off my local .conan2 cache, and then also the /src directory that of course included the build directory. 

I then built with (In the build dir):
```
  cmake -G "Unix Makefiles" ../audacity \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DAUDACITY_BUILD_LEVEL=2 \
        -Daudacity_has_vst3=off \
        -Daudacity_use_jpeg=system \
        -Daudacity_has_networking=off \
        -Daudacity_lib_preference=system \
        -Daudacity_use_expat=system \
        -Daudacity_use_ffmpeg=loaded \
        -Daudacity_use_zlib=system \
        -Daudacity_use_curl=system \
        -Daudacity_use_midi=local \
        -Daudacity_use_wxwidgets=local 
```

I checked that the graphical components work, and I have not had any other errors, but then I don't know the extent of Audacity's midi integration and whether the system provided library is good enough. 

So, literally the only libraries required from Conan is wxWidgets and PortMidi.
