### ISSUE TITLE
Incorrect audio clip boundaries when opening project

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#5171]
### Steps to reproduce

1. Set default project rate to 48kHz in preferences,
2. create new project,
3. drag and drop 44.1kHz wav file
4. move the clip so that it starts at 1 second,
5. save the project,
6. re-open the project.

### Expected behavior

The clip still begins at second 1.

### Actual behavior

It begins later.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

### Additional context

I did some debugging:
When re-opening the project,
1. an empty track is created, with rate 48kHz,
2. the clip is added to the track, and gets 48kHz assigned,
3. the correct track rate is read from the project file, i.e. 44.1kHz, and is reassigned to the track and then the clips.

Step 3, here, calls `WaveClip::SetRate`, which remaps clip boundaries, including trim and envelope points, to the new sample rate.

A solution would be to ensure that the `WaveTrack` rate is read from the project file before the clips, but I'm not sure how to do this or if it's the best solution.

**Comment by dozzzzer** [comment]
Tested
