### ISSUE TITLE
Find Clipping doesn't work with stretched clips

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#5176]
### Steps to reproduce

1. Delete PluginSettings.cfg to get default effect settings
2. Generate Chirp with default settings
3. Amplify by 3 dB with Allow Clipping
4. View -> Show Clipping on
6. (apply a stretch to the clip, or not)
7. Analyze > Find Clipping

### Expected behavior

Expect to see labels corresponding with the clipping, as here when there is no stretch (and zoomed in closely):

<img width="1232" alt="image" src="https://github.com/audacity/audacity/assets/11670369/31f9f10a-12bb-406c-8552-8ce5f6be8ecf">

### Actual behavior

I saw no labels when I compressed the 30s chirp to 15s nor when I stretched it to 60.  But there may be non-determinism on other systems because of usage of uninitialized data, similar to the present master's (9aea997dfb9db401e3affbe153823d062eca7c6a) misbehavior in Plot Spectrum, so there might be random labels.

If the shrunk or stretched clip is mixed-and-rendered, you do see red clipping and the analyzer will find the clipping on the new track

### Audacity Version

latest beta

### Operating system

Windows, macOS, Linux

### Additional context

Consider these incidental problems, and maybe break them out into other issues.

- [ ] #5188
- [ ] An easy fix for this would label where clipping WOULD BE in the rendered track, but that may not match the waveform.  As we know, the shape of waveforms may change a lot with stretching because of different phase shifts of frequency components, making higher peaks even if not much changing RMS.
- [ ] #5187
- [ ] Neither the red paint nor the labels will account for non-destructive effects  also on the stack, or for pan, gain, or envelope.

**Comment by petersampsonaudacity** [comment]
@Paul-Licameli 

When I tested on W10 I got this - where it doesn't properly find the clipping and only appears to put clipping indicators dor the original length of the audio.  AND it took an inordinate amount of time.
![image](https://github.com/audacity/audacity/assets/50205984/7bcfff9a-4c6a-4762-9449-33dfab975cd0)
