### ISSUE TITLE
Frequency snapping in spectral selection fails with stretched clips

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#5179]
### Bug description

Making note of another known consequence of recent code changes, and the failure of `GetFloats` applied to stretched clips.

The purpose of the frequency snapping feature was to make it easy to adjust spectral selection to a local peak, then invoke one of the Nyquist spectral editing effects (which you bind to keystrokes if you want to use them often) to reduce or remove an unwanted background sound.  This is easier than using Notch Filter but figuring out the correct numbers to enter.  See these old videos demonstrating the feature when it was in prototype. https://www.youtube.com/@paullicameli9855

If work on the experimental enhanced spectral selection (the GSOC 2021 project) resumes, enabling this for irregularly shaped selections, then there will likely be trouble there too with stretched clips.

### Steps to reproduce

Useful preparations in Preferences:

1. In Keyboard, find "Next Higher Peak Frequency" and assign it a convenient keystroke like Alt+H; likewise for "Next Lower Peak Frequency"
2. In Tracks, make Spectrogram or Split your default view
3. In the View > Toolbars menu, enable the Spectral Selection bar, which appears at bottom and shows frequencies

To reproduce the problem:
1. Get some sound with interesting harmonic frequency content. (Generate a Square, No Alias wave, or record some speech, or use some instrumental music)
2. Zoom on some time with an interesting sustained note (ripply pattern of overtones) and drag a selection box.
4. Clicks and drags on the (un-dashed) horizontal centerline of the box, with and without Shift key down at click time
5. Use the keystrokes to move the box up and down
6. Repeat all after stretching or shrinking the clip

### Expected behavior

For stretched, as for unstretched clips, detection of peaks of the spectrum and snapping of the centerline to them

### Actual behavior

Peak detection and snapping fails for stretched clips

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

**Comment by saintmatthieu** [comment]
There isn't the 3.4 Milestone tag to this ticket, is this deliberate?

**Comment by Paul-Licameli** [comment]
Let it be triaged.  I think it can be a known issue unlikely to affect many.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
