### ISSUE TITLE
Help Wanted: Simple build for local development

### ISSUE THREAD

**Issue by oliveirafilipe** [audacity/audacity#518]
Hi Folks!

Maybe this is not the best place for this question,  but any tips can help me to contribute.

I want to code a really simple feature, that I think will improve the UX.

I set up a Dockerfile, just for local development, in order to build the application without installing all the dependencies into my host.

I followed [this guideline](https://wiki.audacityteam.org/wiki/Building_On_Linux#Detailed_Instructions), for build in linux (`debian:buster` to be more precise).

This is my first interaction in a big project written in C++, so I got a little bit surprised with the build time. I thinking is taking too long, more than 15 minutes.

Is there any build tricks, or special/correct params to be used in `configure` and make executables in order to have a simple build, not release version, to accelerate the cycle "code, build, test, fail"?

I can improve this question if I did not make myself clear. 

Thank you all.

**Comment by SteveDaulton** [comment]
As of Audacity 2.4.0, the old autotools build chain has been replaced by cmake. The wiki has yet to be updated, but there are brief notes in the source code: https://github.com/audacity/audacity/blob/master/linux/build.txt
Building with cmake is likely to be a lot quicker.

**Comment by oliveirafilipe** [comment]
Thank you @SteveDaulton I will give it a try

**Comment by oliveirafilipe** [comment]
@SteveDaulton I think it built. 

It took 17 minutes, is that an acceptable time?

**Comment by SteveDaulton** [comment]
Build times can vary tremendously, depending largely on the machine, the build options, and which libraries have to be built. When I first built Audacity I was using a Pentium II which took over 2 hours to complete.

**Comment by oliveirafilipe** [comment]
I'm using a i7, but I didn't any improve in docker to get the best of host's hardware.

You said that the build time may also depends on  "the build options, and which libraries have to be built".

I'm using the following commands:
```
cmake -DCMAKE_BUILD_TYPE=Release ..
cmake --build .
make .
```

am I using the best parameters for a build that doesn't need to be for final release?

**Comment by SteveDaulton** [comment]
Please come and chat to us on the Help forum. We have a forum board specifically for discussing compile/build issues: https://forum.audacityteam.org/viewforum.php?f=19

**Comment by oliveirafilipe** [comment]
Oh that's great! Thank You! Closing the issue
