### ISSUE TITLE
Show Clipping paints red only where clipping is in the waveform before processing

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5187]
### Steps to reproduce

1. Delete PluginSettings.cfg to get default effect settings
2. Import [this file](https://www.dropbox.com/scl/fi/tzpv158pq21ev68agkf9x/072-01.wav?rlkey=ckl73b6sv34otmukp1aebys30&dl=0)
3. View > Show Clipping on
4. Observe: no clipping
5. Stretch the imported clip up to 7 seconds
6. Observe

### Expected behavior

Clipping is displayed with the red paint immediately after stretching.

### Actual behavior

No clipping is indicated with red paint.
Clipping only becomes visible after mixing and rendering the track.

### Audacity Version

current master / alpha / nightly build

### Operating system

Other

### Additional context

From #5176

**Comment by LWinterberg** [comment]
This is not a bug, it's a consequence of non-destructive editing. Adding a VST amplification and boosting the track by +999dB also won't show up as clipping in the waveform. I don't think we can - or should - fix that in the waveform in a static manner, like show clipping does right now. 

That said, there may be an opportunity to have a waveform during playback which shows the actually rendered audio during that particular playback. This would either live in the mixer (FL Studio has it) or perhaps be overlaid onto the track as a ghost. Or perhaps another solution.
