### ISSUE TITLE
Right-click clip header pops up clip menu

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#5195]
### Your idea

First step towards [that design](https://www.figma.com/file/3vAMBYovsJuTrbet34ruaZ/08_WX---Clips?type=design&node-id=1104-27663&mode=design&t=iXpPrnx6bJ9SWhWt-0). See #5192 for an overview.

### Problem to be solved

First step towards [that design](https://www.figma.com/file/3vAMBYovsJuTrbet34ruaZ/08_WX---Clips?type=design&node-id=1104-27663&mode=design&t=iXpPrnx6bJ9SWhWt-0). See #5192 for an overview.

**Comment by dozzzzer** [comment]
Tested
