### ISSUE TITLE
Speed dialog: interactive clip speed textbox

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#5196]
### Your idea

As in [this design](https://www.figma.com/file/3vAMBYovsJuTrbet34ruaZ/08_WX---Clips?type=design&node-id=1104-27663&mode=design&t=iXpPrnx6bJ9SWhWt-0), add a "Change Speed..." entry to the clip menu, which pops-up a "Clip Speed" window. As first step this window only has the "Clip Speed" textbox that allows textual setting of the speed.

This should stretch by changing the position of the clip's right edge.

If a clip is slowed down and collides with other following clips, trimming should occur.

### Problem to be solved

Allow users to stretch to precise percentages using a textbox.

**Comment by chinakov** [comment]
> If a clip is slowed down and collides with other following clips, trimming should occur.

<img width="1501" alt="Screenshot 2023-09-26 at 13 20 50" src="https://github.com/audacity/audacity/assets/139755141/c43ae855-e523-4c1d-99b9-531edf1e1673">

Currently, if a User stretches a clip so that it collides with other following clips, no trimming occurs - User is shown an error message shown in the screenshot.

**Comment by crsib** [comment]
> If a clip is slowed down and collides with other following clips, trimming should occur.

@LWinterberg was it something agreed on? This is not in spec and probably the weirdest behavior I can imagine :-)

**Comment by saintmatthieu** [comment]
Sorry, I forgot about that requirement and haven't synced properly with Design.
This was the result of a discussion with @Tantacrul and I. Don't know what to do with it now, I suppose it's to be negotiated between @crsib and Design 🤷‍♂️

**Comment by DavidBailes** [comment]
> Sorry, I forgot about that requirement and haven't synced properly with Design. This was the result of a discussion with @Tantacrul and I. Don't know what to do with it now, I suppose it's to be negotiated between @crsib and Design 🤷‍♂️

I don't think that trimming is very user friendly.
1. It could occur off-screen, and not be obvious visually when the user looked at the end of the clip that had been trimmed.
2. If a user reduced the speed of a clip which resulted in trimming, if they then increased the speed, there would be no adjustment to the amount of trimming - and again this could be all off-screen.
3. Keyboard users still can't un-trim a clip, so it's not at all helpful for these users.

**Comment by chinakov** [comment]
I would also agree with trimming not being very user friendly, and it basically constitutes as a destructive action with no warnings. 

A warning about not enough space to 'stretch' is much more User friendly. 

Please let me know when you've agreed on the wanted behaviour, I will close/re-open the ticket accordingly.

**Comment by crsib** [comment]
We may also want to do ripple editing when ripple editing is enabled

**Comment by saintmatthieu** [comment]
All right, there are worthy counter-arguments to that. I think we can safely leave it at that, then, and let any resentment for later discussion.

**Comment by chinakov** [comment]
@saintmatthieu  - thanks, moving to Ready to Merge.
