### ISSUE TITLE
Can't run 3.4.0 alpha on macOS 14.0

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5199]
### Steps to reproduce

1. Install macOS 14.0 Beta
2. Download a universal binary from `master`, e.g. [this one](https://github.com/audacity/audacity/actions/runs/6161055139)
3. Launch it

### Expected behavior

The splash screen Audacity is shown, followed by the main program window

### Actual behavior

1. "Wrapper would like to access the microphone" dialog appears, blocking the program from launching
2. Clicking either of the two buttons won't cause the dialog to go away, instead, the exact same dialog pops up again, over and over

<img width=350 src=https://github.com/audacity/audacity/assets/70063970/727b3b95-4c81-4f2a-bc53-22ec36f27b2f>

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

**Comment by dozzzzer** [comment]
Doesn't seem to be the case anymore

**Comment by chinakov** [comment]
Indeed, not reproduced. Closing.

**Comment by crsib** [comment]
Welcome to the world of macOS testing xD
