### ISSUE TITLE
python2 is not a build requirement for lv2

### ISSUE THREAD

**Issue by dvzrv** [audacity/audacity#520]
**Describe the bug**
The wiki currently states, that [python2 is required for building lv2 integration](https://wiki.audacityteam.org/wiki/Building_On_Linux), which is further assumed by the cmake setup. However, the waf setup of lv2, suil, sord, serd, sratom or lilv all do not require python2. In fact, python2 should be discouraged wherever  possible, as [it is now legacy](https://pythonclock.org/).

**To Reproduce**
```
cmake -L -B build -S .
```
For output see #519 

**Expected behavior**
Python3 is used all across.

**Screenshots**
-

**Additional information (please complete the following information):**
 - OS: Arch Linux
 - Version: Audacity 2.4.0

**Additional context**
All lv2 related waf setups support python3.

**Comment by SteveDaulton** [comment]
I have updated the wiki so that it now says:
"In addition to the listed dependencies and standard build environment, Audacity also requires Python 2 to be installed."
This is correct at time of writing and will be updated to say Python3 when all of Audacity's Python scripts have been updated to Python 3.

**Comment by dvzrv** [comment]
@SteveDaulton thanks for the clarification!
Could you be more specific as to what exact pieces of code actually require python2?

I could not find [any reference in the code base](https://github.com/audacity/audacity/search?p=1&q=python2&unscoped_q=python2) that would warrant hard coding python2 to be required.

**Comment by SteveDaulton** [comment]
"mw2html.py" is one.
