### ISSUE TITLE
If Audacity 3.4 opens a legacy project containing misaligned clips, un-merge them as split to mono

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#5202]
This needs an info box showing up upon opening a project saying: 

> "This project contained stereo tracks with non-aligned content. This feature is not supported in Audacity versions past 3.3.3. These stereo tracks have been split into mono tracks. As a result, some realtime effects may be missing. Please verify that everything works as intended before saving."

QA:
 - [x] Verify opening of a properly saved project that contains misalligned clips:
   - [x] Shows warning dialog with message above
   - [x] Stereo wave tracks that has misalligned clips is split into two mono tracks
   - [x] These tracks have empty effects stack
   - [x] Splited tracks have same rate and sample format
   - [x] Other tracks are not affected (mono wave tracks, label tracks etc.)
   - [x] Not automatically saved (so it's still possible to open it using Audacity version that was used to create project, and there are **NO** changes in channel linking or effects)
   - [x] Fixed re-saved legacy project should open up in older versions of Audacity without an issue
 - [x] Verify opening of a project that was once saved properly but has unsaved changes/was never saved at all (make changes to a project and force-quit/crash the application)
   - [x] Recovery dialog appears as usual
   - [x] Check that all items from previous list are fullfiled when auto save is discarded.
   - [x] Check that all items from previous list are fullfiled when recover option is choosen. 
 - [x] Projects saved in 3.0.x (before there were smart clips) with well aligned clips open in 3.4 without warnings

**Comment by dozzzzer** [comment]
Tested
