### ISSUE TITLE
lame not detected by cmake setup

### ISSUE THREAD

**Issue by dvzrv** [audacity/audacity#521]
**Describe the bug**
The cmake setup for 2.4.0 does not detect a system version of lame.
On Arch Linux we currently offer 3.100, but it is not detected.

**To Reproduce**
```
cmake -L -B build -S .
```

[audacity-2.4.0-cmake.log](https://github.com/audacity/audacity/files/4640339/audacity-2.4.0-cmake.log)

**Expected behavior**
A system version of lame is detected and used.

**Screenshots**
-

**Additional information (please complete the following information):**
 - OS: Arch Linux
 - Version Audacity 2.4.0

**Additional context**
The detection of the lame library works in the autotools setup (based on the header file).

**Comment by ainola** [comment]
@lllucius Could this be looked into, please? We are still stuck on 2.4.1 on Arch Linux because of no recourse.

**Comment by tcanabrava** [comment]
ping?

**Comment by crsib** [comment]
Fixed in #1030
