### ISSUE TITLE
Reverse effect produces inconsistent results when applied on multiple tracks with stretched clips

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5210]
### Bug description

When selecting a region involving two stretched clips on two different tracks and applying Reverse to them several times while only changing the stretch ratio of one of them, it would also produce different results each time for the other clip too.

### Steps to reproduce

1. Generate a chirp with a square wave
2. Duplicate (Ctrl + D) it
3. Stretch/shrink the upper clip
4. Stretch/shrink the lower one by a different amount
5. Select a region inside both clips
6. Effect > Reverse
7. Select the newly created clip and copy and paste it into the new project
8. Ctrl + Z
9. Repeat steps 4 – 7
10. In the second project, Effect > Invert on one of these two clips
11. Ctrl + A > Mix and Render

### Expected behavior

Silence clip

### Actual behavior

Not a silent clip, i.e. the clips produced by the Reverse effect are different despite out of those two clips only the lower one was stretched.

https://github.com/audacity/audacity/assets/70063970/e475c7e7-24a8-47b7-82ed-d6a9f2f6a44c

### Audacity Version

[PR #5138 ](https://github.com/audacity/audacity/pull/5138)

**Comment by saintmatthieu** [comment]
As @Paul-Licameli demonstrated at stand-up, mix-and-rendering of the same track several times produces each time a slightly different result. The different results are likely identical perceptually, still this surprising behaviour should at least be understood.

**Comment by dozzzzer** [comment]
Fixed by #5233
