### ISSUE TITLE
Import AUP edge cases

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#5211]
### Bug description

One loophole that may still allow the creation of projects in 3.4 with misaligned clips is the "Import AUP" feature, which opens projects saved in Audacity 2.4.2 and earlier.

### Steps to reproduce

1. Start Audacity 2.4.2
2. Generate a mono track of noise; time-shift it right some
3. Generate another mono track of noise; time-shift it farther right
4. Use "Make Stereo Track"
5. Drag the channel separator so the channels have unequal heights
6. Save Audacity project; also try "Save Lossless Copy" and "Save Compressed Copy"
8. Close and reopen projects in 2.4.2; observe (Lossless and Compressed didn't restore clip boundaries or channel heights)
9. Quit Audacity 2.4.2; start Audacity 3.4
10. Reopen the files

### Expected behavior

3.4 should not make misaligned clips

### Actual behavior

The normal project file (only; not the compressed or lossless) still has misalignment.

This results from a different code path not in the scope of issue #5202 .

Also observe that unlike in 2.4.2, the difference of channel height is not preserved.  But I recommend allowing this regression, very unlikely anyway to be seen in practice.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

**Comment by chinakov** [comment]
Tested.
