### ISSUE TITLE
Clip name is discarded when mixing and rendering the track

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5216]
### Steps to reproduce

1. generate some audio
2. observe: the clip's name is "Audio 1"
3. give the clip a new name
4. Tracks > Mix > Mix and Render

### Expected behavior

The clip retains the given name.

### Actual behavior

The clip's name is reverted to "Audio 1".

### Audacity Version

current master / alpha / nightly build

### Operating system

Other

**Comment by Paul-Licameli** [comment]
Clip names -- sorry.

But notice the preservation of track name of a single track.  We should not have unintended regression of that behavior.

**Comment by LWinterberg** [comment]
> But notice the preservation of track name of a single track. We should not have unintended regression of that behavior.

That hasn't regressed though :)

**Comment by Paul-Licameli** [comment]
> > But notice the preservation of track name of a single track. We should not have unintended regression of that behavior.
> 
> That hasn't regressed though :)

Right, and be sure it doesn’t after my continued violence to the source tree.
