### ISSUE TITLE
Context menu option to join clips

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#5221]
### Your idea

Following up on #2330, which only removed the click-to-merge behaviour. Quoting that other ticket:

> The context menu option should function in the following way:
> * If a range of audio is selected, Right-Click > Join Clips joins all selected clips (same as Edit > Clip Boundaries > Join)
> * If no audio is selected and the cursor is on top of a Clip boundary, Right-Click > Join Clips joins the two adjacent clips (same thing as what clicking the line would do)

### Problem to be solved

Accessibility improvement to join clips. Currently, this is done via the menu: `Edit >Audio Clips > Join`, which is a bit lengthy.

**Comment by petersampsonaudacity** [comment]
Sounds like an excellent improvement to me

**Comment by Paul-Licameli** [comment]
> Sounds like an excellent improvement to me

Accidental left clicks joining clips was deemed an annoyance and will be removed, but there will be something almost as easy to do when you really want that.

**Comment by petersampsonaudacity** [comment]
> Accidental left clicks joining clips was deemed an annoyance and will be removed

Yes, I've already tested @saintmatthieu 's branch build with that particular fix _(and I like it)_.

**Comment by petersampsonaudacity** [comment]
This appear to be duplicated by #5242 

I think this can be closed in favor of 5242 as that is carrying greater and later discussion.
