### ISSUE TITLE
More than 2 decimal places back in Play At Speed.

### ISSUE THREAD

**Issue by MichaelKazmierski** [audacity/audacity#5222]
### Your idea

In older versions of Audacity, numbers with 3 or more decimal places could be entered for precise speeds. Unfortunately Audacity version 3.3.3 only allows 2, and that is not precise enough. I would love to see the option for 3 or more decimal places back.

### Problem to be solved

More precise speeds for Play At Speed, such as 3 octaves lower.

**Comment by petersampsonaudacity** [comment]
originally noted on the Forum in this thread:
https://forum.audacityteam.org/t/play-at-speed-not-enough-decimal-places/84931

**Comment by SyntaxTsundere** [comment]
I must admit, while i'm not some full-time audiophile or anything, I really do just find this annoying...

**Comment by chinakov** [comment]
Tested, thanks!
