### ISSUE TITLE
Extend clip rendering by the length of one sample

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5226]
### Your idea

As a follow-up to our agreement as to what the visual length of the sample is, we need to extend the rendered length of the clip by one sample length;

### Problem to be solved

Until now, there was no agreement on how to interpret what sample length is in terms of visuals. Thus, it may be confusing in some cases, for instance, when pasting a clip next to another clip with less than one sample offset, e.g.:

<img width=350 src=https://github.com/audacity/audacity/assets/70063970/31fd0775-c45c-4ea2-899d-3e64a5d7d76e>

In this particular case, the clips will be merged but it may not be too apparent for the User, given that the clip visually ends exactly on the sample, and is not extended till the next one, in which case the paste would rather be into the clip.

Also, with the rendered length of the clip extended by the length of one sample, the selection would match the clip's length when selecting the whole track, which is far more adequate and sensible than the current behaviour of selection stretching one sample beyond the rightmost clip edge:

<img width=350 src=https://github.com/audacity/audacity/assets/70063970/3ba9b75a-71fc-43aa-88d9-d93a9d25b507>

### Prior art

<img width=350 src=https://github.com/audacity/audacity/assets/70063970/6ed8ae79-2b55-4a65-9803-243d3ab5d046>

**Comment by saintmatthieu** [comment]
While working on the waveform display with time stretching, at some stage I had Audacity in the state suggested here. It didn't look great, keeping some space between clips the way Audacity 3.3 looks better. If we still want to extend the clip right boundary to cover that last sample period, we may want to modify the painting at that place somehow.

**Comment by LWinterberg** [comment]
clip rendering is being reworked
