### ISSUE TITLE
Can't access Preferences after unplugging an external display [macOS]

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5227]
### Bug description

In macOS, when using Audacity with an external display connected and then disconnecting it, Preferences cannot be accessed.

### Steps to reproduce

1. connect your Macbook to an external display
2. launch Audacity on the built-in display of your Macbook
3. unplug the external display
4. try to access Preferences menu by `Cmd + ,` or via `Audacity > Preferences`

### Expected behavior

Preferences menu opens up.

### Actual behavior

The beep sound; the Audacity window becomes out of focus and unresponsive until the `Esc` key is pressed.

Re-starting Audacity also doesn't help. A system reboot is required.

<img width="460" alt="Screenshot 2023-09-21 at 18 35 44" src="https://github.com/audacity/audacity/assets/70063970/3a473324-fadd-487b-a975-b63fbe963480">

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

### Additional context

This issue isn't in any way a macos-14-related one. This has also happened to me in previous versions of the OS.
After yet another occurrence of this issue, an attempt to open the latest stable version [resulted in a crash](https://sentry.audacityteam.org/share/issue/0e72537783cd446eaa4a64b2f83ce2b8/)

(The subsequent launch was successful, though)

**Comment by LWinterberg** [comment]
I see that the Metadata Editor has a failsafe for that:

https://github.com/audacity/audacity/blob/871ad32ec943c4e81a2a653e25d6625cadffb901/src/TagsEditor.cpp#L260-L264

with the validity check function being a bit further down:

https://github.com/audacity/audacity/blob/871ad32ec943c4e81a2a653e25d6625cadffb901/src/TagsEditor.cpp#L979-L995

It probably is worth pulling that validity checker into a more general helper class and chucking it onto every dialog which retains position. 

actually, @dozzzzer, it also might be worth checking that this issue *doesn't* happen with the metadata editor

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
