### ISSUE TITLE
Incorrect syntax in audacity.dox

### ISSUE THREAD

**Issue by albert-github** [audacity/audacity#523]
**Describe the bug**
In the file audacity.dox we see he lines:
```
PREDEFINED             = AUDACITY_DLL_API \
                         = \
```
this is an incorrect syntax, most likely:
```
PREDEFINED             = AUDACITY_DLL_API= \
```
is intended.

**To Reproduce**
1. run `doxygen audacity.dox`
2. see the console output:
    ```
    error: Illegal PREDEFINED format '=', no define name specified
    ```
    at least with the current doxygen version

**Expected behavior**
No warning regarding PREDEFINED in configuration

**Additional information (please complete the following information):**
 - OS: independent
 - Version 2.4.0 (audacity-minsrc-2.4.0.tar.xz)

**Comment by JamesCrook** [comment]
Thanks.  Fixed with https://github.com/audacity/audacity/commit/8a88881e43ca7e01983c4ffee50cca98735ac7c1
