### ISSUE TITLE
Error message when dragging the pencil/brush tool rightwards off the screen

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5231]
### Bug description

When using the Pencil or Brush tool dragging the cursor off the right edge the window while holding LMB, it throws an error message:

<img width="332" alt="Screenshot 2023-09-22 at 13 06 58" src="https://github.com/audacity/audacity/assets/70063970/f224f2ff-d6ef-47a0-b09d-c920cdea1da0">

### Steps to reproduce

1. Grab some audio
2. Zoom in until you see individual samples
3. With the pencil/brush tool selected, hold LMB and start dragging it all the way to the right

### Expected behavior

No such error message when reaching the rightmost edge of the window.

### Actual behavior

The last draw action gets discarded. An error message is displayed:

https://github.com/audacity/audacity/assets/70063970/3c73ee39-60ae-4d42-8d1b-b7fcd3498037

### Audacity Version

https://github.com/audacity/audacity/pull/5042

### Operating system

Windows, macOS

**Comment by saintmatthieu** [comment]
There are some imperfections with drawing since stretching. This is one of them. There is also a new use case: samples are visible in the one clip, but not in the next clip because it was shrunk. What should happen then? 
![image](https://github.com/audacity/audacity/assets/22740106/e0afe1e3-923e-47e3-b95f-914e3ce4e6e0)
@LWinterberg

**Comment by saintmatthieu** [comment]
Also the brush tool in that situation, when used near the end of the left clip, modifies the samples in the right clip. What should be the correct behaviour? @LWinterberg

**Comment by petersampsonaudacity** [comment]
Testing on W11 with latest 3.4.0 master alpha

I cannot reproduce this.

**Comment by dozzzzer** [comment]
> I cannot reproduce this.

This isn't in the master branch yet. It was introduced by PR https://github.com/audacity/audacity/pull/5042
