### ISSUE TITLE
Number of digits in the Selection Start should match the one of the Selection End when bars and beats is selected

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5232]
### Bug description

In the Selection toolbar, when bar:beat:tick or bar:beat format is selected, the number of digits displayed for Selection Start is always three, despite in the lower part of the Selection toolbar, Selection End, it may exceed 999 bars, adding the 4th digit in the line.

### Steps to reproduce

1. Generate 1h of audio with the tempo of 120.0 bpm
2. Ctrl + A
3. Switch the Selection toolbar format to bar:beat:tick or bar:beat
4. Observe

### Expected behavior

The number of digits of the Selection Start perfectly matches the one of the Selection End

### Actual behavior

The Selection Start is one digit less shorter than the Selection End, which makes the top and the bottom misaligned:

![image](https://github.com/audacity/audacity/assets/70063970/524dc66b-fb5b-48ab-a0b5-a13ec46d46e8)

### Audacity Version

current master / alpha / nightly build

### Operating system

Other

**Comment by rohitmit98** [comment]
Hello! That's an interesting observation. Please confirm I'm correctly identifying and reproducing this issue:
![image](https://github.com/audacity/audacity/assets/51212933/9bdeb434-2195-4154-8d12-d5338be327a5)

From my understanding, it seems after '999' bars, the value wraps incorrectly. 

I'm going to try and work on this issue.

**Comment by dozzzzer** [comment]
> it seems after '999' bars, the value wraps incorrectly

There's indeed an issue with the display of more than 999 bars, and it has been fixed already, although PR #5190 fixing it hasn't been merged yet.

**Comment by dozzzzer** [comment]
Tested
