### ISSUE TITLE
Wrong tempo

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#5235]
### Bug description

The project tempo value seems to be ignored and 60bpm used instead until tempo is manually changed.

### Steps to reproduce

1. Open Audacity, set the time ruler to minutes and seconds, and the tempo to 120bpm.
2. Close Audacity, and reopen.
3. Generate a 1s tone. The length correctly shows 1s: 
![image](https://github.com/audacity/audacity/assets/22740106/7e850bea-e050-4672-921a-2fe0847141e0)
4. Switch to beats-and-measure view.

### Expected behavior

The generated tone spans 2 beats.

### Actual behavior

It only spans 1, as though the project tempo were 60bpm:
![image](https://github.com/audacity/audacity/assets/22740106/afa3cb43-4558-45f2-8388-980e6b2b57d3)
Changing the project tempo corrects this.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

### Additional context

This has for more noticeable consequence that it breaks snapping to beats-and-measures units.

**Comment by rohitmit98** [comment]
Hello, I'd like to work on this issue. 

In your reproduction steps, how are you changing the tempo of a project before generating a track? Audacity has 'change tempo' grayed out for me until I have a track to select.

**Comment by saintmatthieu** [comment]
Hi @rohitmit98 , absolutely :)

If you want the project tempo to be e.g. 120 before adding a track, what you can do is add the track, change project tempo to 120, close the project without saving. Next time you open Audacity, the project tempo should still be 120.

**Comment by saintmatthieu** [comment]
@rohitmit98 this is a blocker for our upcoming release and must be addressed asap. I'll get on with it now, sorry I'm taking this away from you. If you're interested in contributing to something else I'd be interested to hear if you have particular interests.

**Comment by chinakov** [comment]
Fixed, thank you!
