### ISSUE TITLE
Clip stretching with an asynchronous stero track is faulty - the right channel behaves oddly

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#5237]
### Bug description
Clip stretching with an asynchronous stero track is faulty

With a left channel clip to the right of the right channel clip 
a) stretching to the right has no impact on the right channel clip
b) stretching to the left has no impact on the right clannel clip until you start to overlap with the stretched left channel clip and the the behavior looks odd

With the left channel clip to the left of the right channle clip you get a mirro image behavior.

_Note that using the clip-handle drag-bar to move the left channel (top) clip does properly move both the left and right clips in sync - expected (and documented) beahvior._

### Steps to reproduce
1. create a 30 second chirp
2. on a new track vreate a 30 second DTMF
3. Zoom out a coupl of times
4. Move the chirp so that it starts at 1min
5. move the DTMF so that it starts at 15 secs _(i.e. there is no overlap)_
6. Make an asynchronous stereo track from the pair
7. Use the Alt modifer at the right boundary of the drag-bar to time stretch rightwards
8. OBSERVE: the DTMF'right boundary snaps to the right boundary of the chirp and stretches with it from there
9. Undo the time shift
10. Use the Alt modifer at the left boundary of the drag-bar to time stretch leftwards so that it just passes the right DTMF boundary
11. OBSERVE: The DTMF gets shrunk
12. continue to timestretch the clip leftwards
13. OBSERVE: the left borders of the chirp and DTMF reamin in sync
14. Now use the left edge of the drag bar to drag rifgtwards befonf the DTMF
15. OBSERVE: the DTMF is shunk to a mininal clip

### Expected behavior
I'm not entirely sure - but I think that maybe teh two clips should time-stretch by the same amount so that as one grwos or shrinks the other does likewise.

This use case has clips of the same leght - I'munsure what should happen with aysync clips of different length.

_And note I have not expored behaviors for overlapping async clips_

### Actual behavior
**Step 8**
![image](https://github.com/audacity/audacity/assets/50205984/f16e278d-dc5a-49ea-b48e-74c8d89b9315)

**Step 11**
![image](https://github.com/audacity/audacity/assets/50205984/57fedc34-c87b-4ccd-9af6-28ff1348a973)

**Step 13**
![image](https://github.com/audacity/audacity/assets/50205984/8a472382-8343-4e92-8eb3-891d4b75c5ad)

**Step 15**
![image](https://github.com/audacity/audacity/assets/50205984/adee0af6-83a6-4d96-81c7-d78678bf3b0f)

### Audacity Version
Latest 3.4.0 master audacity-win-3.4.0-alpha-20230925+feec9d9-x64-msvc2022

### Operating system
W11 - but assume all OS

### Additional context
Tagging @saintmatthieu

**Comment by Paul-Licameli** [comment]
After #5200 is merged, tracks like these will be impossible to make.  Clips will always align.

**Comment by petersampsonaudacity** [comment]
> After #5200 is merged, tracks like these will be impossible to make. Clips will always align.

@Paul-Licameli 
But what if the user wants asynchronous clips in their stero track - I'm confused _(easily done these days)_

Will the non-overlap than be true silence filled in the future to ensure synchronicity?

This finds me recalling the tero tracks made from mono tracks that you had earlier Paul, where both channels had a drag bar (and that ws deemed to be a bug, or at least undesirable behavior.
