### ISSUE TITLE
Join Clips command in the Clip-handle and waveform RMB  context menu

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#5242]
### Bug description

It would be very useful to add a command for **Join Clips** in the RMB context menu(s) for the Clip-handle and waveform..

Beacuse:

a) the **Edit > Audio Clips > Join**  is not that easy to "discover"

b) a context menu is more "discoverable" and simpler/quicker to use

c) and **_in particular_** because the **LMB click** to join a pair of adjacent clips has recently been removed as part of @saintmatthieu 's work)

### Steps to reproduce
1. get some audio
2. RMB click on the clip handle
3. Observe: in the context menu there is no **Join Clips**

### Expected behavior
The functionality for Join Clips already exists in Audacit as executed by use of the **Edit > Audio Clips > Join** menu command. The propose context menu command should execute the same functionality.

Note that the **Edit > Audio Clips > Join** command joins not just a pair of adjacent clips, but several clips on the same track that are contained in the current selection.  It even works across a selection in multiple tracks - but, of course, on a per-track basis.

### Actual behavior
![image](https://github.com/audacity/audacity/assets/50205984/af8c3778-518e-4040-8015-72ad7d9e41be)

### Audacity Version
Latest 3.4.0 master - and @crsib 's latest branch for the extended RMB context meny (the image above is from this branch build\0

### Operating system
Windows 11, but assume all OS

### Additional context
None

**Comment by vsverchinsky** [comment]
@LWinterberg @petersampsonaudacity 
What happens now when I click area between waveforms:
![изображение](https://github.com/audacity/audacity/assets/20165230/8bd95029-1776-4296-9d8a-619e2509c5ce)
When click happens between clip handles:
![изображение](https://github.com/audacity/audacity/assets/20165230/21e4ff65-c5f2-4047-8d64-2c0ddda23998)
I wonder if it supposed to be like this?
RMB click exactly over clip handle moves selection and that makes **Join** useless when only one track is selected, but still available.

**Comment by LWinterberg** [comment]
Please place the Join command in the area between waveforms as well.

**Comment by petersampsonaudacity** [comment]
@LWinterberg @crsib @vsverchinsky 

The purpose of the command would be much clearer if it were **Join Clips** rather than the simple **Join**

**Comment by dozzzzer** [comment]
@vsverchinsky moving 

- Let's rename "Join" to "Join Clips"
- Let's remove the error message issued when no audio is selected... 
<img width=400 src="https://github.com/audacity/audacity/assets/70063970/6c3b46ff-5485-496f-8251-3647d19953e2>
...and in such cases (when no audio is selected) disable **Join** command instead. Both in the context menu and in the `Edit > Audio Clips` menu.
- as for your concern about 

> RMB click exactly over clip handle moves selection and that makes Join useless when only one track is selected, but menu entry is still available.

let's leave it as is for now.

**Comment by crsib** [comment]
I think the correct predicate for this option should be "more than one interval intersects the selection"

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest @vsverchinsky 's latest branch build:  audacity-win-3.4.0-alpha-20230928+2d34c5c-x64

The RMB context menu from the track does now have **Join Clips**
![image](https://github.com/audacity/audacity/assets/50205984/a4a1a232-911d-4b31-842f-4524b540edff)


But I note that there is no RMB context menu available from the Clip-handle.  That functionality was added to the Clip-handle recently and can be observed in the latest master build.

Personally I don't think that we really need a context menu from the clip-handle.

**Comment by petersampsonaudacity** [comment]
This is a duplicate of #5221 

I think 5221 can be closed in favor of this _(which has more discussion)_

**Comment by vsverchinsky** [comment]
> But I note that there is no RMB context menu available from the Clip-handle. That functionality was added to the Clip-handle recently and can be observed in the latest master build.

@petersampsonaudacity Not sure that I understand that corretly. Context menu does appear for me when I do RMB click over clip handle in this branch:
![изображение](https://github.com/audacity/audacity/assets/20165230/2349b6c6-9b9b-404e-82c1-2667658751d3)

**Comment by petersampsonaudacity** [comment]
> Context menu does appear for me when I do RMB click over clip handle in this branch:
@vsverchinsky 
Just tested again RMB click in the Clip handle causes the current selection to be discarded and the clip then becomes the new selection.

**Comment by petersampsonaudacity** [comment]
@LWinterberg @crsib @vsverchinsky 

It could be better in the context menu if the **Change Speed** were changed to **Change Clip Speed**

That would give greater clarity of purpose i.e _"does what it says on the tin"_

**Comment by chinakov** [comment]
The `Edit > Audio Clips` menu still says 'Join' instead of 'Join Clips'. 
Is this fine? @LWinterberg 
<img width="503" alt="Screenshot 2023-10-02 at 13 33 49" src="https://github.com/audacity/audacity/assets/139755141/ed4c92a6-dc70-4a52-b1f3-2770b10dcee5">

Apart from this, everything seems to be in order. Please advise if we should address this.

**Comment by LWinterberg** [comment]
it's fine, we can address that later

**Comment by chinakov** [comment]
@LWinterberg - thanks, then it's ready to merge.

**Comment by petersampsonaudacity** [comment]
@LWinterberg @chinakov 

I too wondered about that - but decided that it was probable better as it is, more compact and succinct.

It's Ok, I think, because the sub-menu comes from the Edit menu **Audio Clips** - so it's explicitly about clips

But if you are going to change it at some stage then you should probably also change **Change Speed** to be **Change Clip Speed**  for greater clarity of purpose _(and so the user doesn't get to think they are changing the Track speed)_

**Comment by petersampsonaudacity** [comment]
The solution is either
a) remove the context menu for the clip-handle area, or
b) make it so that right-clicking the clip-handle does NOT change the selection

**Comment by LWinterberg** [comment]
As we currently don't have a concept of clip selection that's separate from the time selection, this is necessary to make the "rename clip", "change speed" and "render clip stretching" options available when right-clicking the clip headers. It's not ideal, definitely, but also not something that will be fixed right now - in each case not in scope of this issue.

**Comment by vsverchinsky** [comment]
> And note that unlike the Join Clips command in the context menu which is then grayed-out, the Split Clip command is NOT grayed-out but invoking it of course does nothing.

They are greyed-out in [this](https://github.com/audacity/audacity/pull/5277) PR
