### ISSUE TITLE
Plot Spectrum fails when multiple tracks selected

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#5244]
### Bug description

When multiple tracks are selected, Plot Spectrum ignores all tracks except the last track.

### Steps to reproduce

1. Generate a 1000 Hz tone
2. In a new track, generate a 2000 Hz tone
3. Select both tracks and view Plot Spectrum

### Expected behavior

![expected](https://github.com/audacity/audacity/assets/11681097/4cb14c98-c742-4f31-937b-3264cc2db37e)

### Actual behavior

![actual](https://github.com/audacity/audacity/assets/11681097/fc0c86c3-740e-4de4-a14e-c0b59d6ea747)

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

This can be very misleading, and not necessarily obvious when working with multi-track audio projects.

**Comment by Paul-Licameli** [comment]
Did you try to bisect it?

**Comment by Paul-Licameli** [comment]
Bisects to 6ce46f11a582cd7a1c70199ac3f4d7d364ebda1a

**Comment by chinakov** [comment]
![image](https://github.com/audacity/audacity/assets/139755141/dc6f3e17-2af8-403b-9fa3-a890cc873b2e)

Yep, looks good! 

Thanks.
