### ISSUE TITLE
Joining Stretched and Un-stretched Audio Clips ignores Stretching

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#5246]
### Bug description

If a User has a stretched and un-stretched audio clips in one track, and the User uses 'Join Audio' command - the stretched clip will be returned to it's un-stretched state, and then will join the audio clips in the track.

<img width="1608" alt="Screenshot 2023-09-26 at 14 30 02" src="https://github.com/audacity/audacity/assets/139755141/2ca6f3c5-7a5c-4bab-b9ab-75a423cde3f8">

### Steps to reproduce

1. Open Audacity
2. Add or generate 2 audio clips within one single audio track
3. Stretch one of the audio clips, but do not render
4. Select both clips
5. Go to 'Audio Clips -> Join'
6. Observe Result 

### Expected behavior

The stretched clip should persist if the User joins both audio clips via 'Audio Clips -> Join'.

### Actual behavior

The stretched clip doesn't persist if the User joins both audio clips via 'Audio Clips -> Join'.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @saintmatthieu 's 4 of 6 latest branch build:  audacity-win-3.4.0-alpha-20231005+7737b4b-x64
Flagging @chinakov as the originator of this issue ticket

This now appears to work properly in Matthieu's 4 of 6 branch.

Both of these clips started out as 30 seconds, only the left one was stretched:
![image](https://github.com/audacity/audacity/assets/50205984/6f2e0b36-3661-41af-bacd-e1bff6c46b23)
