### ISSUE TITLE
Changing instrument one waveform color

### ISSUE THREAD

**Issue by Reaper10** [audacity/audacity#525]
Changing the default instrument one color from the current blue to a darker blue or a bluish purple. This is the best way there is a difference between the instrument one color and the other GUI elements like sliders in the rest of the program.  For when you change theme in audacity the instrument one color changes with with it.  The other instrument color does not change with the theme.  Instrument one color should be just like the rest of the instrument colors they stay the same no matter what theme you have picked. This isn't the way it is right now.

dark mode
![dark mode](https://user-images.githubusercontent.com/8137561/82271398-44876480-993d-11ea-9301-bbe350abdede.jpg)

light mode
<img width="842" alt="light mode" src="https://user-images.githubusercontent.com/8137561/82271437-6385f680-993d-11ea-92cd-6cfaa47c7051.PNG">

blue wave light
![blue wave light](https://user-images.githubusercontent.com/8137561/82271524-9e882a00-993d-11ea-92ab-4f34bee7a0cc.png)

blue wave dark
![blue wave dark](https://user-images.githubusercontent.com/8137561/82271570-be1f5280-993d-11ea-9d0b-2c73df56778d.jpg)

blue wave light
![blue wave light](https://user-images.githubusercontent.com/8137561/82271632-f7f05900-993d-11ea-9eb0-4c1ca89258d0.png)

red wave light
![red wave light](https://user-images.githubusercontent.com/8137561/82271730-37b74080-993e-11ea-95ed-74c255a9a231.jpg)

red wave dark
![red wave dark](https://user-images.githubusercontent.com/8137561/82271792-66351b80-993e-11ea-93e5-0c7f2b92f2e2.jpg)

**Comment by SteveDaulton** [comment]
Thank you for your suggestion.
