### ISSUE TITLE
Mix and Render fails to reset Pan slider

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#5253]
### Bug description

Rendering a track should not change what it sounds like.

When rendering a  panned track, the panning is rendered into the track, so the Pan slider needs to be reset to sound the same as the original.

### Steps to reproduce

1. Generate a full scale tone.
2. Pan 50% Left
3. Play and observe the output level meter. Observe that the Left channel is 0dB and the right channel is approximately -6dB.
4. Mix and Render.
5. Play and observe that: (i) the right channel is much quieter than it  was, (ii) The Pan slider is still 50% Left. (iii) The playback meter shows the Left channel is 0dB but the right channel is now approximately -12dB.

### Expected behavior

The Pan slider to be reset to 0 (centre).

### Actual behavior

The panning becomes exaggerated because it is in effect being applied twice.

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

Regression.

**Comment by vsverchinsky** [comment]
May be fixed by #5303

**Comment by dozzzzer** [comment]
Tested

**Comment by SteveDaulton** [comment]
> Tested

Did you test the Track Gain slider as well?
