### ISSUE TITLE
New "What's new" thumbnail in welcome screen

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#5262]
- [x] Create the 3.4 thumbnail @LWinterberg 

![Image](https://github.com/audacity/audacity/assets/87814144/1e7d061c-0a48-4db0-9878-2180e40ca1c7)

Audacity: 
- [x] Add the thumbnail in the what's new dialog (weird WhatsNewBtn.jpeg.h file)
- [x] Link the thumbnail to https://audacityteam.org/3.4.0-video (ie: Set the WhatsNewURL to `"https://audacityteam.org/3.4.0-video"`)
- [x] Add a new text section below the thumbnail (see string below)
- [x] Reset the preference to hide the welcome to audacity screen upon upgrading again

New string: 

```c
"In this release we added Beats & Measures, Time Stretching and more. 
Watch the release video or read the changelog to learn more!"
```
with "release video" linking to WhatsNewURL and "changelog" linking to https://support.audacityteam.org/additional-resources/changelog

Web: 
- [x] audacityteam.org: Set up a redirect on the current website for /3.4.0-video to https://youtube.com/@audacity - we'll change it once the video is ready
- [x] mirror that change to the new website as well @LWinterberg

**Comment by dozzzzer** [comment]
Tested
