### ISSUE TITLE
It's hard to put a clip in between other clips when dragging it across the tracks

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5264]
### Bug description

It's hard to fit a clip in the position in between other clips by dragging and dropping.

### Steps to reproduce

1. have a blank audio track
2. have another audio track with three identical clips going one after another: 
<img width=300 src=https://github.com/audacity/audacity/assets/70063970/f6edb4c3-0dbb-46df-a4cc-88ae1387dc5e>

3. try to move the middle clip up and down and back into its original position

### Expected behavior

A clip can be easily fitted into its original position

### Actual behavior

A clip cannot be fitted into a position easily:

https://github.com/audacity/audacity/assets/70063970/d3f1cbe9-f66f-47bb-959c-81085c1ba193

### Audacity Version

current master / alpha / nightly build

### Operating system

Other

**Comment by DavidBailes** [comment]
Here are some alternative steps:
0. Open audacity.
1. Generate a tone lasting 50 samples.
2. Select a region within is and run split, to create 3 adjacent clips.
3. Create a new mono track.
4. Drag the middle clip to the new track.
5. Try to drag the clip back to its original position. I can't.

This works fine on 3.3.3.

**Comment by SteveDaulton** [comment]
> try to move the middle clip up and down and back into its original position

You should be able to do that by holding down the Ctrl key (to constrain dragging to one dimension).

**Comment by saintmatthieu** [comment]
I also find this difficulty on current 3.3.3. I think I remember someone's comment that it got worse on master?

**Comment by SteveDaulton** [comment]
> I also find this difficulty on current 3.3.3.

Did you try:
1. have a blank audio track
2. have another audio track with three identical clips going one after another:
3. Hold down the Ctrl key and try to move the middle clip up and down and back into its original position.

That works for me in Audacity 3.3.3, 3.4.0 alpha, and older versions of Audacity. I don't know if this "Ctrl + drag" behaviour is still in the official documentation, but it clearly should be.

**Comment by saintmatthieu** [comment]
Yes, sorry I didn't respond to your earlier comment. That was interesting to experience, and yes, it still works on master.

**Comment by dozzzzer** [comment]
Fixed in #5307. However, two things are to be noted here:
- Keep in mind that in order for a clip to be easily dragged in the area in between other clips one should be doing this across the Y axis, since any deviation to the left or right would not let the clip go in that space. Like, say, if the clip's affordance is grabbed right in the middle, one would need to follow the green arrow.

<img width="450" alt="Screenshot 2023-10-05 at 16 13 36" src="https://github.com/audacity/audacity/assets/70063970/af3f396a-4239-4be9-9494-0dc88e0a40ea">

- As @DavidBailes pointed out in the comment above, it becomes much easier to achieve this when holding down  Ctrl (Cmd) key, in this case the direction is locked to Y axis.
