### ISSUE TITLE
Clips Join if Pasted In-Between Clips

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#5265]
### Bug description

If a User decides to paste an audio clip in-between 2 clips, the most right-most clip will be joined together with the pasted clip.

### Steps to reproduce

1. Launch Audacity
2. Add Stereo Track
3. Generate Audio or add a track
4. Place the newly generated/placed clip into the copy/paste buffer (via 'CTRL + C')
5. Paste the clip a couple of times into the Stereo Track
6. Use snapping and arrow keys to get in-between the clips
7. Press Paste ('CTRL + V')
8. Observe Clips joining together

### Expected behavior

Clips should not be joined if they are pasted in-between other clips.

<img width="1797" alt="Screenshot 2023-09-27 at 17 08 26" src="https://github.com/audacity/audacity/assets/139755141/e9fb2cec-c76f-43d6-8cd7-74179774d76f">

### Actual behavior

Clips are joined if they are pasted in-between other clips.

<img width="1797" alt="Screenshot 2023-09-27 at 17 07 22" src="https://github.com/audacity/audacity/assets/139755141/f2105189-18a7-454a-8020-9004533a076d">

### Audacity Version

latest stable version (from audacityteam.org/download)

also reproduced on latest Master

### Operating system

Windows, macOS, Linux

**Comment by chinakov** [comment]
@saintmatthieu - no, I should have specified that it's reproducible on both mono and stereo, apologies.

**Comment by chinakov** [comment]
<img width="566" alt="Screenshot 2023-09-29 at 15 58 43" src="https://github.com/audacity/audacity/assets/139755141/42ffe6b4-cd1e-4486-979b-972d2b0a60f9">

I presume that this warning message is correct? @saintmatthieu

**Comment by saintmatthieu** [comment]
Can you try that? 
![image](https://github.com/audacity/audacity/assets/22740106/2741a10b-874b-4931-9a5b-b88d74122b5b)

**Comment by saintmatthieu** [comment]
That's if the preference "track behaviors > editing a clip can move other clips" is not checked. If it is, then you should never see this message.

**Comment by chinakov** [comment]
@saintmatthieu - yes, everything seems to be correct now, thank you!

**Comment by petersampsonaudacity** [comment]
Testing on @saintmatthieu 's latest 4 of 6 branch build:  audacity-win-3.4.0-alpha-20231005+7737b4b-x64

This appears to be working correctly in the branch build
