### ISSUE TITLE
Preferences: Modules is not showing drop down list 

### ISSUE THREAD

**Issue by RyanMetcalfeInt8** [audacity/audacity#5266]
### Bug description

On latest master branch, Preferences: Modules shows 'No Modules':
![image](https://github.com/audacity/audacity/assets/107415876/f6c036cf-bfcb-4b4e-a8bc-8f627abd47ab)

I'm on Windows 11, Visual Studio 2019.

### Steps to reproduce

1. Build Audacity with mod-script-pipe support.
2. Double check that mod-script-pipe.dll is in Release/modules folder.
3. Launch Audacity and go to Edit->Preferences->Modules

### Expected behavior

I would expect to see module drop down list, like this (From Audacity 3.2.5):
![image](https://github.com/audacity/audacity/assets/107415876/40db2647-ef29-4e30-b214-577527b11354)

### Actual behavior

This:
![image](https://github.com/audacity/audacity/assets/107415876/f6c036cf-bfcb-4b4e-a8bc-8f627abd47ab)

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

### Additional context

I'm on commit 0a852da:

commit 0a852da746de945d162dd04077b5031edee0264f (HEAD -> master, origin/master, origin/HEAD)
Author: Matthieu Hodgkinson <saintmatthieu@gmail.com>
Date:   Tue Sep 26 13:26:09 2023 +0200

    Round FFT size to closest pow-of-two with 44.1kHz mapping exactly to 4096.

**Comment by vsverchinsky** [comment]
Feels like modules were not build at all. Did you use f7 command to build all targets?

**Comment by RyanMetcalfeInt8** [comment]
The modules are built, I can see the DLL's sitting in 'modules' under Release:
![image](https://github.com/audacity/audacity/assets/107415876/bded19e0-16a2-4458-a8ab-f869813f9698)

**Comment by petersampsonaudacity** [comment]
In 3.3.3 I get this - with several modules including mod-script-pipe
![image](https://github.com/audacity/audacity/assets/50205984/773d4aa9-3772-427d-8601-68b9dcd88ad9)


In latest 3.4.0 alpha test build I get this - with no modules
![image](https://github.com/audacity/audacity/assets/50205984/3cd6a8e0-0e99-4327-9c53-d13b8ad48ba6)

So this looks like a regression to me

**Comment by crsib** [comment]
And probably quite a recent one too. I was talking with @chinakov not so long ago about disabling modules for the testing purposes of the new Export

**Comment by chinakov** [comment]
Yes, I vividly remember them working as well.

**Comment by chinakov** [comment]
I've managed to trace the commit that breaks the modules page in Preferences. 

https://github.com/audacity/audacity/commit/41d9441d8066cc2d8014ec29d849f031ac16a903

**Comment by chinakov** [comment]
This is fixed, thanks!
