### ISSUE TITLE
Crash when opening up Mixer

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5268]
### Steps to reproduce

1. Download [the project](https://www.dropbox.com/scl/fi/amkwq2zyy3k81kpzmti80/Everything_App_Project.aup3?rlkey=vwnx186uusch34c8xwkp964rp&dl=0)
2. Open the project in Audacity and dismiss the missing plugins warning
3. Click Play
4. Open up Mixer (View > Mixer)
5. Wait a few moments until the play head hits bar 33

### Expected behavior

No crash

### Actual behavior

A crash

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS, Windows

**Comment by dozzzzer** [comment]
Bisects to https://github.com/audacity/audacity/commit/a49762fdc1179f05d4b12ca4db428dd563a2fe64

**Comment by vsverchinsky** [comment]
There are at least 2 zero-length clips in this project. First is exactly at bar 33, second is at bar 182, second beat.
There is a quire simple hotfix for that crash, but it obviously will not fix zero-length clips issue

**Comment by dozzzzer** [comment]
Tested
