### ISSUE TITLE
Time controls with bars: keyboard interactions can produce completely wrong results

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#5270]
### Bug description

There are problems with keyboard interactions which cause the number of digits used for the bar number to change.

In the case of using up/down arrows, in general this should not cause which digit is the focus to change. However if the number of digits reduces and the focus was on the digit that is removed, then the focus has to change - to the next digit, I guess would be sensible.

Observation: If the current number of digits for the bar number is 3 then setting a 4 digit bar number using the keyboard is a bit of a fiddle.

### Steps to reproduce

All these cases are using the selection start control, with the format set to bar:beat

Case A:
1. Set the bar number to 999.
2. Set the focus to the last digit of 999.
3. Press up arrow twice.

Case B:
1. Set the bar number to 1000.
2. Set the focus to the last digit of 1000.
3. Press down arrow twice.

Case C:
1. Set the bar number to 1000.
2. Set the focus to the first digit of 1000.
3. Type the digits 0,9,6,1.

### Expected behavior

Case A:
The bar number changes to 1001.

Case B:
The bar number changes to 998.

Case C:
The bar number changes to 961

### Actual behavior

Case A:
The bar number changes to 2000. (After the first up arrow the focus is moved to the first of the now 4 digits.)

Case B:
The bar number changes to 899. (After the first up arrow, the focus is moved to the first of the now 3 digits.)

Case C:
The bar number changes to 124, and the beat number to 2. (After typing the 0, the focus is moved to the first digit of the beats.)

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

### Additional context

Introduced by this commit: https://github.com/audacity/audacity/pull/5190, which allows more than 3 digits for bar numbers.

**Comment by crsib** [comment]
Expected results in case B are not in line with what Audacity would do now, I've made the behavior to match the current one

**Comment by DavidBailes** [comment]
> Expected results in case B are not in line with what Audacity would do now, I've made the behavior to match the current one

@crsib Thanks for having a look at this. However I'm not sure what you mean by this. I think that if the focus is on the last digit of bar 1000, and the user presses down arrow twice, then the user would expect the bar number to change to 998? Are you suggesting this shouldn't be the case?

**Comment by crsib** [comment]
Oh, shoot, the last digit. Sorry, @DavidBailes. Then it is fixed as well.

**Comment by dozzzzer** [comment]
Tested
