### ISSUE TITLE
When joining clips with different stretch ratios, all clips should be rendered

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5273]
### Bug description

Currently, when multiple clips with different stretch ratios are joined together, the resulting clip has the stretch ratio (=speed) of the leftmost clip.

### Steps to reproduce

1. Have two clips with different stretch ratios put on the same track
2. `Edit > Audio Clips > Join`
3. Observe the speed value of the resulting clip
4. Observe what previously was the leftmost clip

### Expected behavior

The resulting clip has a speed of 100% and, thus, it's not displayed.
The leftmost clip is also rendered.

### Actual behavior

The resulting clip has the speed value of the leftmost clip
The leftmost clip wasn't rendered when joining other clip(s)

### Audacity Version

current master / alpha / nightly build

### Operating system

Other

### Additional context

Discovered while testing https://github.com/audacity/audacity/pull/5043

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @saintmatthieu 's 4 of 6 latest branch build:  audacity-win-3.4.0-alpha-20231005+7737b4b-x64

The resulting clip appears to be rendered correctly - BUT i get a could of glitches at the old clip boundaries

**Use Case 1**
I had top 30 second chirps separated with space in-between them
![image](https://github.com/audacity/audacity/assets/50205984/621fb4ab-a558-4c58-84bd-4ecab04233d3)

**Comment by petersampsonaudacity** [comment]
And look at the glitches I get with a stretched DTMF tone
![image](https://github.com/audacity/audacity/assets/50205984/b72d9ff5-aa32-428c-a8ce-322965007e75)

**Comment by saintmatthieu** [comment]
Thanks for this report, @petersampsonaudacity .

I just looked into this. My experiment: Track 2 is the result of joining clips of track 1. Track 3 is that or rendering them separately by RMB. Track 4 is the mix of track 2 and inverted track 3. They are bit-exact.
![image](https://github.com/audacity/audacity/assets/22740106/1cde9259-b5a6-40b5-8576-cfffc3f41b71)

It looks like the waveform display accentuates the abrupt transition to zero, forming those "horns".

Does this analysis convince you or did I miss something from your findings ?

I see two improvements that could be discussed: improving the waveform display and cross-fading. Only I think these two things mostly apply to synthetic tones, and not really for musical content stretched for the purpose of looping. In any case not in the scope of #5043.

**Comment by dozzzzer** [comment]
Fixed by https://github.com/audacity/audacity/pull/5043

As for the "horns" problem, it's now logged as https://github.com/audacity/audacity/issues/5319
