### ISSUE TITLE
Crash applying effect to overlapping zero-width clip

### ISSUE THREAD

**Issue by joeessayvoice** [audacity/audacity#5279]
### Bug description

I have about a  piece of audio that I'm working with, and all of a sudden whenever I try to normalize sections of it, it completely crashes. This is out of nowhere.  I've been using audacity for years!  Paul Licameli , any thoughts?

### Steps to reproduce

1. Load the file in Audacity: https://www.dropbox.com/scl/fi/19sdon2c40gzp1zo3lz4y/Joe-Essay-Audacity-Failure.aup3?rlkey=5pmwhd0to43cw5r224rfz7c10&dl=0
2. Make a selection of audio
3. Attempt to normalize it

### Expected behavior

It should normalize the audio appropriately

### Actual behavior

Crash

### Audacity Version

Audacity Version 3.2.4

### Operating system

macOS

**Comment by LWinterberg** [comment]
I can reproduce the crash in 3.3.3 on linux when selecting the entire track

**Comment by LWinterberg** [comment]
![image](https://github.com/audacity/audacity/assets/87814144/889836e5-29c3-4164-a899-58d6a0d4f2ed)

There is an overlapping zero-width clip at 3s470ms (the small black line that does not have a line in the timeline ruler above it). Dragging the second clip to the right, deleting the zero-width clip and then dragging it to the left again to match it up with the previous clip has things working again.

**Comment by LWinterberg** [comment]
The bug you encountered here is actually 3 bugs: 

1. Zero-width clips should never happen; clips should be at least 1 sample long
2. Clips should never overlap
3. Applying an effect should not crash. 

Fixing this crash in particular is a lower priority as you already are in a state which should not occur, having an overlapping zero-width clip in your project. It'd be very helpful to know how you got your project in this state

**Comment by joeessayvoice** [comment]
To get this audio in this state, I was simply going through a segment of
clips, and pasting the over the gaps of the clips with a copied segment of
a certain length in order to even out the silent portions of the file.
