### ISSUE TITLE
Add Nyquist "power" function (generalise s-sqrt to arbitrary powers)

### ISSUE THREAD

**Issue by dlh-0492** [audacity/audacity#528]
So I see that _s-sqrt_ takes the square root of each positive sample and maps all negative samples to zero. Could this be generalised to something like _s-pow_ that raises every sample to a certain power? More precisely, something like this: 

(s-pow \*track\* p)

equivalent to

s => {s^p, if s is non-negative | -(-s)^p, if s is negative}

Therefore, (s-sqrt \*track\*) would be equivalent to:

s => {sqrt(s), if s is non-negative | -sqrt(-s), if s is negative}

And it would be great if support for fractions could be added, so cube roots would go like (s-pow \*track\* (/ 1 3)) or something (you know, raising to the power of 1/3). Divide-by-zero exception handling would be a must as well.

Or maybe this could be added as an effect in Distortion?

**Comment by SteveDaulton** [comment]
For positive integer powers, you can simply use MULT.
For roots, you can create your own function. For example:
```
(defun root (sig n)
  (let* ((delta (/ (power 2 31)))
         (pos (s-max sig delta))
         (neg (mult -1 (s-min sig (- delta)))))
    (sim
      (s-exp (mult (s-log pos) n))
      (mult -1 (s-exp (mult (s-log neg) n))))))
```

**Comment by SteveDaulton** [comment]
If you have further questions about Nyquist in Audacity, we provide a forum here: https://forum.audacityteam.org/viewforum.php?f=39

**Comment by SteveDaulton** [comment]
If you are interested in deforming waves (waveshaping), take a look at the [SHAPE](https://www.cs.cmu.edu/~rbd/doc/nyquist/part8.html#index452) function.

**Comment by dlh-0492** [comment]
Thanks so much!

**Comment by dlh-0492** [comment]
> For positive integer powers, you can simply use MULT.
> For roots, you can create your own function. For example:
> 
> ```
> (defun root (sig n)
>   (let* ((delta (/ (power 2 31)))
>          (pos (s-max sig delta))
>          (neg (mult -1 (s-min sig (- delta)))))
>     (sim
>       (s-exp (mult (s-log pos) n))
>       (mult -1 (s-exp (mult (s-log neg) n))))))
> ```

Thanks so much!
