### ISSUE TITLE
Add a feature: formula calculation

### ISSUE THREAD

**Issue by qq1010903229** [audacity/audacity#5281]
### Your idea

Add a feature: formula calculation
In GoldWave, there is a feature that using a formula to generate waves.
But in Audacity, there is not.
I suggest add formula calculation feature to generate waves.

### Problem to be solved

To make more complex sounds or effects

**Comment by LWinterberg** [comment]
You can do that using Tools > Nyquist Prompt. 

You can use the [generator nyquist plugins](https://plugins.audacityteam.org/nyquist-plugins/generator-plugins) as a basis to see how it works; just open the .ny files in a text editor like Notepad++ or VSCode.

**Comment by qq1010903229** [comment]
I can't write Nyquist plugins, also, GoldWave's formula calculation feature is not in plugins.
So, you can add formula calculation feature to Audacity now

**Comment by LWinterberg** [comment]
The nyquist prompt isn't a plugin either! If you type in `(sine 100 1)`, it generates a 1s sine wave at 100 hz, for example.

**Comment by qq1010903229** [comment]
But, GoldWave's formula calculation feature can use waves for input

**Comment by qq1010903229** [comment]
such as wave(n) will output the source wave itself

**Comment by qq1010903229** [comment]
GoldWave's formula calculation can make complex effect to input wave sounds

**Comment by LWinterberg** [comment]
All of these things are true for the nyquist prompt too.
