### ISSUE TITLE
Importing a 5.1/7.1 audio file creates one stereo and other mono tracks

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5282]
### Steps to reproduce

1. Download [LPCM 7.1.wav ](https://drive.google.com/file/d/1vdFvs7Fobyqw0EyNYxXDq__cez2fA6k7/view?usp=drive_link)or [FLAC 5.1.flac](https://drive.google.com/file/d/1DZCKsFocqSG5YkWNFH_lBdQ9QKf3Du_O/view?usp=drive_link) file
2. File > Import

### Expected behavior

Creates 8 (for 7.1) or 6 (for 5.1) individual mono tracks.

### Actual behavior

Creates a stereo track and the rest are mono tracks:

<img width="500" alt="Screenshot 2023-09-29 at 14 07 41" src="https://github.com/audacity/audacity/assets/70063970/30aee608-ea77-44ab-83e8-bf22cccac4dc">

### Audacity Version

current master / alpha / nightly build

### Operating system

Other

### Additional context

May be related to https://github.com/audacity/audacity/issues/5255

It's a regression against 3.3.3

**Comment by Paul-Licameli** [comment]
This bisects to 4d67c0e7a8ac2b91448ef132bd938b57eb721417 and is not the same bug as #5255

**Comment by Paul-Licameli** [comment]
Yes now I think #5255 will also be fixed with it, although that bug bisects to a later point.

**Comment by chinakov** [comment]
Tested.
