### ISSUE TITLE
Merging two mono tracks into stereo results in 100% panned left track

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5284]
### Steps to reproduce

1. generate chirp
2. generate one more
3. select "Make Stereo Track" in TCP
4. observe panning in the resulting track

### Expected behavior

A panned center stereo track

### Actual behavior

A 100% panned left stereo track.

### Audacity Version

current master / alpha / nightly build

### Operating system

Other

**Comment by chinakov** [comment]
Tested, fixed.
