### ISSUE TITLE
Error while building with ASIO

### ISSUE THREAD

**Issue by Patafikss** [audacity/audacity#5287]
### Bug description

CMake Configuration step not proceeding when building with audacity_has_asio_support flag.
Checksum does not match.

-> cannot build with asio support

### Steps to reproduce

Following https://github.com/audacity/audacity/blob/master/BUILDING.md#building-with-asio-support-on-windows
1. `mkdir build_audacity`
2. `git clone https://github.com/audacity/audacity/`
3. `cd build_audacity`
4. `cmake -Daudacity_has_asio_support=On -G "Visual Studio 17 2022" -A x64 ..\audacity\`
5. get error

### Expected behavior

I suppose the configure step should finish properly.

### Actual behavior

Checksum invalid. I suppose it could be bypassed, but I have no knowledge of conan.
full log: https://pastebin.com/9iPAk0q3
relevant bit:
```
portaudio/19.7.0@audacity/stable: Calling generate()
portaudio/19.7.0@audacity/stable: Generators folder: C:\Users\Administrator\Documents\Projects\build_audacity\conan\home\p\b\porta5df76628a3fc3\b\build\generators
ASIO requires that Steinberg ASIO SDK Licensing Agreement Version 2.0.1 is signed
ERROR: portaudio/19.7.0@audacity/stable: Error in generate() method, line 90
        get(self,
        ConanException: sha256 signature failed for 'asiosdk_2.3.3_2019-06-14.zip' file.
 Provided signature: 80F5BF2703563F6047ACEC2EDD468D0838C9F61ECED9F7CDCE9629B04E9710AC
 Computed signature: bc425d9b98701af74b43639798566c48bc005af7328a2251cff722c1885076b2
```

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

### Additional context

Note: The page  https://manual.audacityteam.org/man/asio_audio_interface.html is outdated, as https://github.com/audacity/audacity/discussions/1809 pointed out.

**Comment by crsib** [comment]
This is now fixed; you may need to run `conan remove portaudio` in order to get the updated recipe.

Thank you for the report!

**Comment by Patafikss** [comment]
Can confirm, the problem described has been fixed.
My build still doesn't work but that's another story :)
