### ISSUE TITLE
When trying to paste clips, an error is thrown if there are tiny clips in the copied selection

### ISSUE THREAD

**Issue by Tantacrul** [audacity/audacity#5292]
### Bug description

See video.

(Update) I now realise that this is due to some tiny clips in my project that were included in the selection I copied. pasting works if I find and remove them. However, pasting should still work even if tiny cliplets are present.

https://github.com/audacity/audacity/assets/21022311/a74f970c-9f25-42eb-b419-5e294a76a24a

### Steps to reproduce

1. Turn on snapping and set it to 'bar'
2. Select audio across multiple clips
3. Try to paste the audio next to an existing clip

### Expected behavior

Pasting should work in this circumstance

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

**Comment by petersampsonaudacity** [comment]
@Tantacrul 

Isn't part of the problem that it is almost impossible to spot such "tiny cliplets" ?

**Comment by Tantacrul** [comment]
@petersampsonaudacity 

Yes, although in my video, I'm copying a region that has an exact number of beats and pasting it into an area that is the same number of beats, so the cliplets shouldn't be causing an issue.

It would be desirable (obviously) to figure out why my project has so many... but that's a separate problem. This one feels more fundamental.

Eventually, we'll be able to make this a much nicer experience by allowing for overlapping clps

**Comment by petersampsonaudacity** [comment]
> It would be desirable (obviously) to figure out why my project has so many...

@Tantacrul if you find out just why Martin, I'd be intrigued to know.

I always thought such cliplets were maybe an edge-case, but I recall that we had a recent poster on the Forum who was being similarly blocked by an "invisible" cliplet.

**Comment by DavidBailes** [comment]
> Isn't part of the problem that it is almost impossible to spot such "tiny cliplets" ?

Using one of the next/previous clip commands (eg Tab/Shift + Tab), you should be able to spot them. And if you temporarily turn on Narrator (Ctrl + Windows key + Enter), then narrator will read the position of the clip within the clips in the track, eg 3 of 5, which probably makes the presence of "invisible clips" even more obvious.

**Comment by saintmatthieu** [comment]
Assigned @vsverchinsky - likely this is indeed due to the presence of zero-length clips.
Once he has found out how to make their creation impossible, and preventing projects from reading or writing them, it should fix this problem, as well as #5279 and #5268.
