### ISSUE TITLE
Unnecessary warning message when merging two identical stretched (or trimmed) mono tracks to stereo

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5297]
### Steps to reproduce

1. Generate chirp
2. Stretch (shrink) it
3. Ctrl + D
4. Select "Make Stereo Track" in TCP

### Expected behavior

A stereo track combining two mono tracks

### Actual behavior

A warning dialog "Combine Mono to Stereo":

<img width=450 src=https://github.com/audacity/audacity/assets/70063970/c99368f9-f56f-4ef2-8894-799ff453d4a4>

### Audacity Version

current master / alpha / nightly build

### Operating system

All

### Additional context

Clicking "Yes" in the dialog will merge them anyway.

**Comment by dozzzzer** [comment]
Bisects to https://github.com/audacity/audacity/commit/410a0515c7b612a2497f4783737c7b298f9a5c35

**Comment by petersampsonaudacity** [comment]
Same happens if you trim the Clip (making a smart clip) with unmodified click&drag  at Step 2

And indeed also happens of at Step 2 you select a chunk in the middle if the chirp and use the **Trim** button in the **Edit** toolbar - or use **Edit > Remove Special > Trim**

**Comment by petersampsonaudacity** [comment]
As reported by @SteveDaulton  on Discord

The same happens with an unstretched mono track if you add a clip line

1.Generate a chirp 
2. Add a split line
3. Duplicate the entire track
4. Select "Make Stereo Track" in the upper track's context  menu
5. Observe the message (even though both tracks are identical)

**Comment by LWinterberg** [comment]
This is probably not a regression. In 3.3.3, if you follow the STR, or even just

1. Have a stereo track
2. Split stereo
3. Merge stereo

it creates asynchronous stereo clips. The only difference in https://github.com/audacity/audacity/commit/410a0515c7b612a2497f4783737c7b298f9a5c35 would be that the asynchronous clip now creates the message, while the async clips could be more easily overlooked

**Comment by SteveDaulton** [comment]
Testing on Linux with 3.3.0
1.Generate a chirp
2. Add a split line
3. Duplicate the entire track
4. Select "Make Stereo Track" in the upper track's context menu
5. Observe that the tracks  become joined, albeit not a normal stereo track. The split from step 2 is preserved.

With Audacity 3.2 and 3.1: Same behaviour as 3.3.0

With Audacity 2.4.2:
1.Generate a chirp
2. Add a split line
3. Duplicate the entire track
4. Select "Make Stereo Track" in the upper track's context menu
5. Observe that the tracks  become joined into a normal stereo track. The split from step 2 is preserved.

Audacity 3.4.0 commit 8b226a 
1.Generate a chirp
2. Add a split line
3. Duplicate the entire track
4. Select "Make Stereo Track" in the upper track's context menu
5. Observe the warning message is displayed.
6. On clicking "Yes", the tracks are rendered to a normal stereo track, **removing all split lines** and rendering envelopes and effects.

**Comment by chinakov** [comment]
Tested.
