### ISSUE TITLE
AUP import ignores sample format and rate

### ISSUE THREAD

**Issue by vsverchinsky** [audacity/audacity#5304]
### Bug description

Attempt to import AUP project that has wave track with non-default sample rate or sample format results in both being set to default.

### Steps to reproduce

1. Create AUP project in Audacity 2.x
2. Add wave track to the project
3. Change sample rate of a track
5. Change sample format of a track
6. Save project
7. Attempt to import AUP project

### Expected behavior

Wave track sample rate and format didn't change on import

### Actual behavior

Sample rate and format are reset to the project default

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

**Comment by chinakov** [comment]
Tested. Per-track rates and formats are retained when opened in this branch. Thanks!
