### ISSUE TITLE
Making selection over the waveform lags behind the cursor position

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5309]
### Steps to reproduce

1. grab some audio
2. in Selection tool mode, hold LMB and start moving the cursor swiftly left and right making a selection OR
3. start moving the cursor really slow
4. observe the selected area painted over the waveform

### Expected behavior

The selection is painted over the waveform precisely following the cursor position.

### Actual behavior

The selection lags behind the cursor, sometimes by a lot:

https://github.com/audacity/audacity/assets/70063970/7a7287cb-0837-4fb0-9ce9-ced18d77979a

https://github.com/audacity/audacity/assets/70063970/cfd31c30-e957-4e91-8c59-4d9e5894543c

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Other

**Comment by LWinterberg** [comment]
is this limited to macOS 14?

**Comment by chinakov** [comment]
@LWinterberg - yeah, seems to be that way. Couldn't reproduce on 12.4 Monterey, but did also reproduce it on 14.0 Sonoma.

**Comment by M-D-M** [comment]
Looks like my new bug is a clone of this one.  https://github.com/audacity/audacity/issues/5343

**Comment by crsib** [comment]
Video in #5343 gives somewhat better STR. Moving the cursor real slow is the easiest way to reproduce it

**Comment by dozzzzer** [comment]
Tested
