### ISSUE TITLE
Changing sample rates don't have any effects after export for output file

### ISSUE THREAD

**Issue by bugsquantii** [audacity/audacity#5311]
### Bug description

In the past, I changed the sample rate of many .wav files, for example, from 4.8k to 4.1k, and saved them as .wav files. They used to be at the new rate of 4.1k after saving. I'm not sure if this is a real problem (bug) or if there's been a change in the software that requires a different way to set the sample rate now.

When I check the sample rate in Linux using "file output.wav," it tells me it's 48000 Hz, even though I set it to 44100Hz in Audacity.

### Steps to reproduce

1. Import any .wav file to audacity
2. Set sample rate to any other sample rate
3. Go to File -> Export -> Export as WAV & save

### Expected behavior

The exported .wav file should be exported with the new changed sample rates. 

### Actual behavior

Sample rates of .wav files stays like before (The changes from audacity seems don't have any effects)

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, Linux

**Comment by LWinterberg** [comment]
This is fixed in the 3.4 alpha. 

In older versions, this is because the project sample rate is used, not the track sample rate. You need to change it in Audio Setup -> Audio Settings before exporting.

The 3.4 alpha has a sample rate dropdown in the Export Audio dialog.
