### ISSUE TITLE
Render Clip Stretching produces incorrect result

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5313]
### Steps to reproduce

1. download and open [this project](https://www.dropbox.com/scl/fi/8q5nxf98biy4pjonneai9/Render-Stretching-Bug.aup3?rlkey=o9arietc3qccdu7nyzeqwfagz&dl=0)
2. right-click either of the two clips' affordances and select "Render Clip Stretching"
3. observe
4. undo
5. mix and render the track
6. compare the result with the one in step 3

### Expected behavior

The results are identical;
In step 3, the result produced by the "Render Clip Stretching" doesn't create any additional envelope points on the clip

### Actual behavior

The results in steps 3 and 6 are different;
In step 3, "Render Clip Stretching" produces a wrong clip with unwanted envelopes:

https://github.com/audacity/audacity/assets/70063970/7646f17e-f901-4f5c-9510-771258faca83

### Audacity Version

current master

### Operating system

Windows, macOS

### Additional Info

Introduced by #5239

**Comment by saintmatthieu** [comment]
Simple steps to reproduce: generate something, change speed, add envelope points near the left and trim them away. When rendering the stretching, the points creep back in the visible part of the clip. Same applies to cutlines.
This relates to the recent optimization whereby the hidden part of clips was not stretch-rendered but cleared.

**Comment by saintmatthieu** [comment]
I can confirm, though, that this doesn't have to be fixed in the context of 4-of-6. I reckon we will want to have this fixed in 4-of-6, though, but this can be decided in triaging.
