### ISSUE TITLE
Partial borrowing of GTK Theme

### ISSUE THREAD

**Issue by kaiyga** [audacity/audacity#5316]
### Bug description

I'm install Audacity from Pop-Repo and saw that they use my GTK Theme but Audacity have own theme and this mix looks sooo strange?

- PopOS 22.04
- APT???
- Gnome Schell 42.5
- Dark Theme 

### Steps to reproduce

0. Install Audacity
```
sudo apt install audacity
```
1.Go to GNOME Settings
2. Appearance 
3. Switch to Dark Theme
4. _Crying with blood:3_

### Expected behavior

![image](https://github.com/audacity/audacity/assets/92279086/6e88468e-cca5-4df7-8ebe-eef85e901021)

![image](https://github.com/audacity/audacity/assets/92279086/d511bbad-667d-4c84-a515-0b963c9ab5e1)

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

**Comment by LWinterberg** [comment]
Preferences > Interface has a dark theme option in Audacity you can use.
