### ISSUE TITLE
(macOS) ffmpeg not linking up with library

### ISSUE THREAD

**Issue by jadenquinn** [audacity/audacity#5318]
### Bug description

I recently wiped this MacBook, I put 10.13 on it, and started installing my apps back on it, however Audacity is refusing to link up with its ffmpeg library that I installed for it. I followed the instructions exactly, it just won't see it. It still doesn't see it even after I located it for Audacity.

I had this issue before, but I think that one was closed, but it's clearly still an issue. Please fix it.

### Steps to reproduce

1. Get a 2015 MacBook.
2. Install MacOS 10.13.6 high sierra.
3. Get Audacity.
4. Get its ffmpeg library installer.
5. Install both.
6. B*tch on Github about it not linking.

### Expected behavior

I expect it to link up, and show the version that it linked with.

### Actual behavior

I see "FFmpeg library not found".

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS

### Additional context

I can't find the related bug, but I know I did make one or two.. or three. I really can't remember. It's been a bit.

**Comment by chinakov** [comment]
Yeah, this is also reproducible on my side:
- macOS 10.13.6

**Comment by chinakov** [comment]
@jadenquinn - could you please try to install the 64-bit version of ffmpeg via https://lame.buanzo.org/ffmpeg_64bit_osx.pkg, as this fixed the issue for me.

**Comment by jadenquinn** [comment]
> @jadenquinn - could you please try to install the 64-bit version of ffmpeg via https://lame.buanzo.org/ffmpeg_64bit_osx.pkg, as this fixed the issue for me.

That... makes no sense. The only version available IS the 64-bit one, therefore it's already downloaded and installed.

**Comment by crsib** [comment]
There are two versions of ffmpeg available on lame.buanzo.org. An old one, called ffmpeg_64bit_osx.pkg, and a new one: FFmpeg_5.0.0_for_Audacity_on_macOS.pkg. The later one supports both Intel and ARM Macs, but it doesn't support macOS 10.13. For this reason Audacity cannot load it when run on macOS 10.13.

**Comment by jadenquinn** [comment]
> There are two versions of ffmpeg available on lame.buanzo.org. An old one, called ffmpeg_64bit_osx.pkg, and a new one: FFmpeg_5.0.0_for_Audacity_on_macOS.pkg. The later one supports both Intel and ARM Macs, but it doesn't support macOS 10.13. For this reason Audacity cannot load it when run on macOS 10.13.

I will test this later today.

**Comment by jadenquinn** [comment]
This wasn't actually tested at the time, however I still encounter this bug on 10.13, I've encountered it twice since then and both times I made SURE to download the x86_64 version of Audacity, so that didn't seem to help.

**Comment by jadenquinn** [comment]
This is still a problem.
