### ISSUE TITLE
Fix display of rendered waveform resulting from stretched clips joined together

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5319]
### Your idea

Joining the clips (`Edit > Audio Clips > Join`) having different stretch ratios would render the two clips in a single clip.
Also, joining the clips having the same stretch ratio and then rendering them (`Tracks > Mix > Mix and Render`) would also render the clips and set the stretch ratio to 1.
In both cases, when zoomed out, the waveform of the resulting clip shows narrow prominent peaks.  This can be fixed.

### Problem to be solved

There's a horn-like peak appearing after two adjacent clips of different stretch ratios are joined together:

### Before Join

<img width=450 src=https://github.com/audacity/audacity/assets/70063970/32627dcb-1fc5-4d3f-9df4-e97d9fddd093>

#### Zoomed in

<img width="450" alt="Screenshot 2023-10-06 at 11 08 17" src="https://github.com/audacity/audacity/assets/70063970/12eb6394-e12f-47a6-9715-349869df2f5d">

#### Zoomed out

<img width="450" alt="Screenshot 2023-10-06 at 11 08 28" src="https://github.com/audacity/audacity/assets/70063970/df997a10-3a40-4e25-8ee9-d109d75f1acf">

**Comment by petersampsonaudacity** [comment]
@dozzzzer 

It's not just **_display_** - when I tested similar I got audible clicks from the point where the clips were joined, the "horns".

**Comment by saintmatthieu** [comment]
I was wrong, the display is right. There is a slight swell at the edges of the rendered sine that I hadn't noticed. Zooming in an out, with appropriate vertical scaling, shows that the peak values are equal whether zoomed in or out.

**Comment by LWinterberg** [comment]
This appears to be the same symptoms as #5588 and probably has the same cause.
