### ISSUE TITLE
Remove libpixman-1.so.0 from Appimage

### ISSUE THREAD

**Issue by izzylaif** [audacity/audacity#5327]
### Steps to reproduce

Launch 3.3.3 appimage on any Linux distribution with September/October 2023 updates

### Expected behavior

Audacity opens

### Actual behavior

It doesn't

`/tmp/.mount_audaciABfngW/bin/audacity: symbol lookup error: /usr/lib/libcairo.so.2: undefined symbol: pixman_image_set_dither`

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Linux

### Additional context

Removing outdated /lib/libpixman-1.so.0 from appimage resolves the issue

**Comment by dozzzzer** [comment]
Tested

**Comment by omega3** [comment]
Can you release new appimage, please. I still can't use Audacity on Linux because of this bug and https://github.com/audacity/audacity/issues/3714.

Any chances for QT version anytime soon (a few months)?

**Comment by LWinterberg** [comment]
an appimage with above fix is here: https://github.com/audacity/audacity/suites/17277553573/artifacts/987191774

#3714 doesn't prevent Audacity from launching, it's just stuff that litters the console and has done so for a while now.

Qt version is a mere shell at the moment and I don't think "few months" is a timeframe in which it'll be ready.

**Comment by omega3** [comment]
It doesn't start for me. I can only see logo and nothing after that.
Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.11
Kernel Version: 6.5.5-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Pentium® CPU G4560 @ 3.50GHz
Memory: 7.7 GiB of RAM
