### ISSUE TITLE
plugin folders are not recognized Audacity 2.4.x / Linux [Solved]

### ISSUE THREAD

**Issue by ronsens** [audacity/audacity#533]
Hi,
using the latest version 2.4.0 / 2.41 on Linux (Arch)

With this version the given per-user plugin folders (for linux) aren't recognized:
~/.audacity-files/plug-ins

but also the plugins in the  system-wide folders will not be shown in the "Add Effects"-window:
/usr/share/audacity/plug-ins
/usr/local/share/audacity/plug-ins

Latest version showing the effects is 2.3.3

**Comment by SteveDaulton** [comment]
This looks like it could be a documentation error. Where does it say that the per-user plug-in folder is
~/.audacity-files/plug-ins
(It should say: "~/.audacity-data/plug-ins")

**Comment by SteveDaulton** [comment]
The location for system-wide plug-ins depends on where Audacity is installed.
Most distributions install Audacity to `/usr/share/audacity/` but the default for "self built" Audacity is
`/usr/local/share/audacity/`

**Comment by davidhealey** [comment]
I'm experiencing the same issue. I have plugins in /home/user/.audacity-data/Plug-Ins. They show up in Audacity's list of plugins but it won't let me enable them.

**Comment by davidhealey** [comment]
I just realised that the Nyquist Plug-in Installer isn't in the tools menu, something strange is happening...

**Comment by davidhealey** [comment]
Ok seems like a packaging issue. The solution here works - https://forum.audacityteam.org/viewtopic.php?f=48&t=110960&hilit=nyquist+there&start=10

**Comment by ronsens** [comment]
Solved with the latest update in Arch. (Version is 2.4.1.2)
