### ISSUE TITLE
shortcuts do not work with num lock number keys

### ISSUE THREAD

**Issue by tapsala** [audacity/audacity#5330]
### Bug description

Audacity has shortcuts Ctrl +1, Ctrl +2 and Ctrl +3. They are related to track view magnification, reduction, and normal view mode. Shortcuts work with the numeric keys on your keyboard, but they don't work with the actual numeric key used with NumLock. 

### Steps to reproduce

1. Open application
2. Klick the track
3. Keyboard.
4. Ctrl +1 or Ctrl + 2 or Ctrl +3. Use num lock number keys

### Expected behavior

The track view should appear normal or zoomed in or zoomed out.

### Actual behavior

Shortcuts have no effect

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

**Comment by DavidBailes** [comment]
By default, the zoom in, normal and out commands have the shortcuts Ctrl + 1, Ctrl + 2, and Ctrl + 3 respectively.
On the Keyboard page of the preferences dialog, you can change these shortcuts to Ctrl + Numpad1, Ctrl + Numpad2, and Ctrl + Numpad3 respectively if that's more convenient for you.
Currently Audacity has no  mechanism for a user to assign more than one shortcut to a command.

**Comment by LWinterberg** [comment]
yeah, the solution here is to allow multiple shortcut per function, not to equate keys to certain other keys. Incidentally, Numpad+, Numpad- and Numpad= would probably be good candidates as default shortcuts, instead of numpad123
