### ISSUE TITLE
Selection Graphics on MacOS 14 (M1 Mac) with Audacity 3.3.3 is Slow to Update

### ISSUE THREAD

**Issue by M-D-M** [audacity/audacity#5343]
### Bug description

When selecting audio on Audacity 3.3.3 on MacOS 14, the selection graphics are "jittery".  This started happening when I upgraded to MacOS 14.  

Selecting audio is difficult to do precisely, since the graphic that shows what audio is being selected is slow to update.  You can sometimes "force" it to update by shaking the cursor (weird).  Please see attached video file.

### Steps to reproduce

Open Audacity 3.3.3 on MacOS 14.  Open an audio file.  Try to select audio.

### Expected behavior

Graphic that shows selection should update.

### Actual behavior

Graphic that shows selection is slow to update.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS

### Additional context

https://github.com/audacity/audacity/assets/5725775/50b024bf-7816-4781-8a83-5ce6680cb2ad

**Comment by dozzzzer** [comment]
Duplicates #5309
