### ISSUE TITLE
Time control with bar format: when number of digits for bar increases, screen readers read incorrectly.

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#5344]
### Steps to reproduce

On Windows, using a screen reader, eg NVDA or Narrator
1. In the selection toolbar set the format for selection start to bar:beat.
2. Set the bar number to 998.
3. Set the the last digit of 998, ie the 8, to be the focus.
4. Press up arrow. The bar number changes to 999, and the screen reader reads 999 as expected.
5. Press up arrow again.

### Expected behavior

The bar number changes to 1000, and the screen reader reads 1000.

### Actual behavior

The bar number changes to 1000, and the screen reader reads 0.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

### Additional context

This bug has occurred since the number of digits for bars was allowed to increase. Last of the commits for this was: https://github.com/audacity/audacity/pull/5310

I'll commit a fix for this after https://github.com/audacity/audacity/pull/5338 is merged (to avoid the fix having merge conflicts).

**Comment by dozzzzer** [comment]
Tested!
