### ISSUE TITLE
The label track 

### ISSUE THREAD

**Issue by Reaper10** [audacity/audacity#535]
The label track wouldn't let me type anything.
![Annotation 2020-05-23 123647](https://user-images.githubusercontent.com/8137561/82736939-e7036700-9cf2-11ea-9905-2677c2d5e9da.jpg)

**Comment by SteveDaulton** [comment]
If you want to type directly into a label track (without creating a label first), you have to enable that in Preferences. See "Type to create a label:" in https://manual.audacityteam.org/man/tracks_behaviors_preferences.html

For user support, please post to: https://forum.audacityteam.org
