### ISSUE TITLE
Right-clicking in the Clip-handle not only invokes the clip context menu it also wrongly selects the clip

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#5354]
### Bug description
For 3.4.0 the clip context menu was made available via an additional right-click in the Clip-handle drag-bar.

for 3.3.3 and earlier there was no right-click available in the clip-handle, rather right-clicking in a Clip's waveform will invoke the clip context menu (and that's all it did).

In 3.4.0 alpha that remains the case, but right-clicking in the clip-handle not only invokes the clip context menu but also changes the user's carefully made previous selection to be the whole Clip.

This is poor UX, because:
a) traditionally in apps it is left-click gestures that are used for selection,
b) right-clicking in apps is normally reserved for invoking context menus.

Accordingly,  using the right click in the clip-handle should only invoke the context menu and **_aNOT_** change the user's carefully made selection that they want to apply the context menu to, thereby making some commands in that Clip-handle context menu **_totally_** useless i.e. **Join Clips** and **Split Clip**.

### Steps to reproduce
1. generate a 30 second chirp
2. select from 10-20 seconds
3. right-click in the waveform
4. Observe: the clip context menu
5. select Split Clip
6. Observe the clip is split
7. Select from 5-25 seconds
8. right-click in the clip-handle of the middle clip
9. Observe: the clip context menu appears - BUT the selection has changed to 10-20 seconds i.e. the middle clip)
10.  Try to use Split Clip
11. Observe: it does nothing (as the selection has changed) - but also note it is NOT grayed-out
12. Try to use Join Clips (observe it is grayed out)
13. Observe: you can't

### Expected behavior
Either, right-clicking in the clip-handle should _**ONLY**_ invoke the clip context menu.

Or, there should be no right-click available in the clip-handle drag-bar - _the context menu is well-covered by right-clicking in the waveform_

### Actual behavior
Right-clicking in the clip-handle not only invokes the clip context menu, it _**also**_ changes the selection to the clip:
![image](https://github.com/audacity/audacity/assets/50205984/c6221f16-7df2-4c86-84cf-f6bd6c0e056d)

In contrast right-clicking in the waveform does NOT change the user's selection:
![image](https://github.com/audacity/audacity/assets/50205984/3c01c4f0-2039-4a65-8537-20fd408cee8d)
 

### Audacity Version
3.4.0 latest master

### Operating system
Windows 10 - but assume all OS

### Additional context
Flagging @LWinterberg and @Tantacrul  as a UX issue

**Comment by LWinterberg** [comment]
This is intentional for this release, otherwise you can't right-click a clip header to rename/change speed/render stretching

**Comment by petersampsonaudacity** [comment]
In which case you really should have the Split Clip command grayed-out as is is meaningless when the whole clip is selected.

Are you saying when you say "intentional for this release" that in a future release it may not be necessary for a whole clip to be selected to "rename/change speed/render stretching"?   And just a right-click in an un-selected clip or clip-header would be enough for all those operations on a clip?

See:   A clip needs to be selected for the context menu to enable "Rename Clip" #3101 

If so that would be really good.
