### ISSUE TITLE
When generating a clip using a certain musical interval, its ending point isn't aligned with the grid

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5361]
### Steps to reproduce

1. enable the Beats & Measures mode of the timeline
2. add a mono track
3. turn on snapping and set it to **1/32**
4. select **1/32nd** in the track
5. Generate > Tone
6. double-click the generated clip to select it and press `Ctrl + C`
7. press the right arrow key on the keyboard
8. zoom in as much as possible
9. observe

### Expected behavior

TBD; We need to define whether the cursor in this case should be placed at the very end of the clip or rather at the next snapping point (which in this particular case would be the nearest 1/32nd) @LWinterberg @Tantacrul your input here would be appreciated.

My suggestion for the desired behavior is:
- When snapping is ON, put the cursor right at the start of the next snapping interval
- When snapping is OFF, put the cursor at the very end of the clip

### Actual behavior

The current cursor position doesn't reach the nearest tick. 
Although the gap, in this case, is minuscule, with longer clips and when pasting clips further down the track it will only get larger, causing a situation when the supposedly snapped-to-the-grid clips may in fact get misaligned with the grid line but, unless zoomed in, it may not be too obvious why.

https://github.com/audacity/audacity/assets/70063970/5109674a-0a03-49c7-8ecd-9cb47db23900

### Audacity Version

current master / alpha / nightly build

### Operating system

Other

**Comment by LWinterberg** [comment]
We're again running into the issue that our samples have "width", which is not represented by the clip edges. I think this is another consequence arising out of https://github.com/audacity/audacity/issues/5226

**Comment by saintmatthieu** [comment]
> We're again running into the issue that our samples have "width", which is not represented by the clip edges. I think this is another consequence arising out of #5226

I don't think so, the fact that the clip boundary stops right after the last lollypop, not extending to the whole last sample period, really only comes from the clip painting code.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
