### ISSUE TITLE
Export Dialog: Variable Bitrate abbreviation should be uppercase

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5364]
<img width="384" alt="Screenshot 2023-10-11 at 17 12 59" src="https://github.com/audacity/audacity/assets/70063970/a81668d5-0a1c-4e3d-9d79-dbb406f992dc">

Change "Vbr Mode" to "VBR Mode" in the Export dialog when Opus is selected as an output file format.

**Comment by crsib** [comment]
This will be fixed with the new Opus exporter (fixed already, but the exporter doesn't work ... yet)

**Comment by petersampsonaudacity** [comment]
Testing On W10 with @crsib 's latest branch build for this:  Sgt. Pepper's Lonely Hearts Club Band

The Opus export works properly

And the "VBR" is properly capitalized.

**Comment by dozzzzer** [comment]
Tested
