### ISSUE TITLE
How to add same effect to rest or another audio? Is there a "format painter" to clone formatting/effect?

### ISSUE THREAD

**Issue by nazar2sfive** [audacity/audacity#537]
i spent my 30 minutes to create a cool audio "1".
now i don't remember where i went and what settings i changed in that period.
i again record second audio.
how can i apply the same settings to the new recorded audio "2"?

![image](https://user-images.githubusercontent.com/12841320/82778560-79ca1000-9e71-11ea-91d5-261fea5d0ad2.png)

**Comment by JamesCrook** [comment]
For advice and assistance in using Audacity, please ask for help on the forum.
