### ISSUE TITLE
Preview progress bar should not be placed on top of effect

### ISSUE THREAD

**Issue by evertvorster** [audacity/audacity#5381]
### Bug description

Some effects have information shown in them while the preview is in action. The dialog that pops up obscures this information. It's really annoying to keep having to move this dialog that does not tell you anything you already know out of the way so that you can see the things you want to see.  

https://github.com/audacity/audacity/assets/12045269/68cf80bc-e892-4321-ae69-71aaf9f9ef9f

### Steps to reproduce

1. Open an effect that has a spectrum analyser
2. Hit preview

### Expected behavior

One of the following. 
1. No dialog at all, maybe the "Preview" Button changes color and a stop button appears next to it?
2. The dialog remembers the last position and pops up over there
3. The dialog tries it's best not to pop up over the gui of the effect.

### Actual behavior

The dialog pops up exactly in the middle of the effect, obscuring the information that I am interested in, while adding no extra information of its own.

Preview time is also limited for some reason? Why not let it play until the end?

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

I've been noticing this for a while, In fact, ever since the preview buttons changed, but thought that maybe someone else would bring this to the attention of the kind folk over here. 
The old style of preview was much better in my opinion, as it did not obscure the UI of the effect, and also allowed looping and quite long playbacks of the effect.

System information:
```
Operating System: Arch Linux 
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.11
Kernel Version: 6.5.7-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 32 × 13th Gen Intel® Core™ i9-13900HX
Memory: 62.5 GiB of RAM
Graphics Processor: Mesa Intel® Graphics
Manufacturer: TUXEDO
Product Name: PD5x_7xSNC_SND_SNE
System Version: Not Applicable
```

**Comment by evertvorster** [comment]
Come to think of it, why can't the normal play buttons be used to preview what the effect would sound & look like?

**Comment by evertvorster** [comment]
Thinking about this even more... 
The concept of toggling playback with play/pause buttons is quite well known, so why not turn the preview button into a stop button when its pressed?

The user will already know the preview is happening due to the sound being produced, and if so equipped the UI of the effect coming alive. 

This approach means you don't have to assign more space for a stop button on the effect window, and you only display what is necessary... and the stop button is right where its needed just in case the user wants to stop playback of the effect straight away.

**Comment by LWinterberg** [comment]
If you click the effects button in the track, you can use the effect in realtime mode, in which case it will just be active during playback and not have any need for previewing. See also https://support.audacityteam.org/audio-editing/using-realtime-effects

**Comment by evertvorster** [comment]
Thanks for the tip!

It does exactly what I need, with the realtime effect I can select however long a piece of audio that I need and fine-tune the equalizer without that annoying popup. 
Then, I can save the settings on the equalizer and apply it to the track later. I have never played with this part of Audacity and it's quite the revelation. 

Somehow I _still_ feel that this is a workaround, and that popup dialog on the preview is superfluous.

**Comment by petersampsonaudacity** [comment]
Very early versions of Audacity had no progress dialog at all for the effect previews, they just played the preview.

The progress dialog was inroduced early in the 1.3 Beta series in 1.3.3 - and here the progress dialog is not shown over the effect dialog:
![image](https://github.com/audacity/audacity/assets/50205984/4ff1cbfd-7d38-45ae-8053-a4848794bff0)

**Comment by petersampsonaudacity** [comment]
Though I do note that it is possible for the user to set a much longer preview time in Playback preferences:
![image](https://github.com/audacity/audacity/assets/50205984/0f0cc549-6de3-4d31-8b55-5efe28a4dce8)
The six second preview is the Audacity default setting.

**Comment by petersampsonaudacity** [comment]
> If you click the effects button in the track, you can use the effect in realtime mode, in which case it will just be active during playback and not have any need for previewing.

@LWinterberg  -  yes but many/most Audacity effects are still not available for realtime use in the effects stack.

**Comment by LWinterberg** [comment]
The Qt version won't have this blocking dialog, and I don't think it's necessary to change this before that.
