### ISSUE TITLE
Player vertical time indicator in timeline is not shown

### ISSUE THREAD

**Issue by mokazemi** [audacity/audacity#5382]
### Bug description

When you play an audio, the timeline indicator is not shown. This issue is only for Wayland. There's no issue when I run audacity like this: `GDK_BACKEND=x11 audacity`

### Steps to reproduce

1. Use Wayland session
2. Record an audio or open a file
3. Play it

### Expected behavior

There should be a vertical indicator in timeline moving when the audio is playing

### Actual behavior

You don't see any vertical line in timeline to indicate the time of playing

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

### Additional context

**Version:** Audacity 3.3.3 (ArchLinux)

**Logs (Maybe related):**

```
12:07:13: Audacity 3.3.3
12:07:13: sqlite3 message: (1) no such table: project in "SELECT 1 FROM project LIMIT 1;"
12:07:13: FFmpeg libraries loaded successfully from: /usr/lib/libavformat.so.60.3.100
12:07:25: File name is ~/Downloads/voice_fa_voice_route_calculate.ogg
12:07:25: Mime type is *
12:07:25: Opening with liboggvorbis
12:07:25: Open(~/voice_fa_voice_route_calculate.ogg) succeeded
12:07:25: Operation 'Importing Ogg Vorbis files' took 0.000000 seconds. Poll was called 0 times and took 0.000000 seconds. Yield was called 0 times and took 0.000000 seconds.

```

** Screenshots:**

Wayland:
![image](https://github.com/audacity/audacity/assets/18334056/85fcf7d2-345d-4d21-b2f8-620ae78df872)

X11:
![image](https://github.com/audacity/audacity/assets/18334056/80277e93-a163-4794-b165-02eed1ff1ae4)

**Comment by crsib** [comment]
This is a known issue, there are no plans to fix before the migration to Qt is complete.

In any case, X11 is a preferred way because Wayland doesn't play well with external plugin formats, such as LV2 and VST/VST3.
