### ISSUE TITLE
Transporting Audio Clips to Other Stereo Tracks Splits Tracks to Mono

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#5389]
@Paul-Licameli  UPDATE: please verify this bug remains fixed in the branch #5389

### Bug description

If the User has multiple tracks within a project, and then drags one of the clips within another track, it will sporadically split the tracks to mono, with no panning being applied.

#### Scenario 1 (apparently, easier to reproduce, thx @petersampsonaudacity )

1. launch 3.4.0
2. get some stereo audio
3. select a section and split the clip
4. add two stereo tracks
5. drag the middle clip down to the lower stereo track

#### Scenario 2

1. Open Audacity
2. Create new Project
3. Create Stereo Track 1 
4. Import or Generate Audio within Stereo Track 1 
5. Create Stereo Track 2
6. Import or Generate Audio within Stereo Track 2
7. Grab the audio clip within Stereo Track 2 and 'drag and drop' it into Stereo Track 1 
8. Do it a bunch of times, and observe different results	

### Expected behavior

No stereo tracks are split when clips are re-arranged from different tracks.	

#### Scenario 1

The originating track and the middle stereo track (empty one) get split to mono

<img width=600 src=https://github.com/audacity/audacity/assets/70063970/2ca98a18-332c-406d-9ad0-02314b155595>

#### Scenario 2

The tracks are split sporadically if the User re-arranges clips to different Stereo tracks. 

https://github.com/audacity/audacity/assets/139755141/be1f9500-892f-4543-a73c-52317737bbe5

### Audacity Version

latest beta

### Operating system

Windows

**Comment by Paul-Licameli** [comment]
Bisects to 5fe2ce1f8e141d18805db8e194fa07441a115e26

**Comment by dozzzzer** [comment]
Tested

**Comment by petersampsonaudacity** [comment]
@Paul-Licameli @crsib 

I note that the build for this fix for 3.4.1 has partially failed.  
https://github.com/audacity/audacity/actions/runs/6783530050

**Comment by JohnColket** [comment]
Forum user Davidcalder64 reports this issue is still present in 3.4.1: https://forum.audacityteam.org/t/3-4-bug-why-is-audacity-splitting-stereo-tracks-into-separate-tracks-for-each-channel-when-i-move-other-files-in-other-tracks/88714/6

**Comment by petersampsonaudacity** [comment]
Yes my understanding is that the fix is coming in the impending 3.4.2 maintenance release.

Peter.

**Comment by DavidBailes** [comment]
> my understanding is that the fix is coming in the impending 3.4.2 maintenance release.

There was a fix in 3.4.1:
https://support.audacityteam.org/additional-resources/changelog/audacity-3.4.1

**Comment by CheeseTurtle** [comment]
> > my understanding is that the fix is coming in the impending 3.4.2 maintenance release.
> 
> There was a fix in 3.4.1: https://support.audacityteam.org/additional-resources/changelog/audacity-3.4.1

Evidently not, because I'm using 3.4.1 and it's happening very consistently.

**Comment by ChandigarIT** [comment]
Problem still there in 3.4.2

![image](https://github.com/audacity/audacity/assets/108827431/0c0adbca-f9d6-4522-96af-3f71bbc407ca)

**Comment by dozzzzer** [comment]
The issue is still reproducible.
Feel free to download and open [this project](https://www.dropbox.com/scl/fi/hann9ty8sdcvrvfifbsuc/breaky-loop.aup3?rlkey=musa195frgg63btiwc5ghttlt&dl=0), add a new stereo track, and simply drag the clip to that track. It causes the upper stereo track to split.

**Comment by ChandigarIT** [comment]
How do I upgrade to 3.5 in Linux? apt update is not finding the new version.  Thanks.

**Comment by dozzzzer** [comment]
3.5 has not yet been released

**Comment by Paul-Licameli** [comment]
> The issue is still reproducible in the recent master. Feel free to download and open [this project](https://www.dropbox.com/scl/fi/hann9ty8sdcvrvfifbsuc/breaky-loop.aup3?rlkey=musa195frgg63btiwc5ghttlt&dl=0), add a new stereo track, and simply drag the clip to that track. It causes the upper stereo track to split.

I observe that this happens only the first time that I try it.  If I undo the change and try again, behavior is correct.

This suggests the problem is in the persistent data.

**Comment by Paul-Licameli** [comment]
This is easily reproduced in 3.5 alpha:  Make a stereo track, save it, close window, reopen the project.  Make a new stereo track, then drag the clip across tracks, see the first track split.

But undo and repeat, and this does not happen.  Or make a stereo clip in a new, unsaved project, then make another stereo track, and drag the clip -- the bug doesn't happen.

**Comment by dozzzzer** [comment]
Tested

**Comment by petersampsonaudacity** [comment]
This is a regression on 3.3.3

**Comment by Paul-Licameli** [comment]
> This is a regression on 3.3.3

See update at the top.  The fix in alpha caused another bug.  This and the other must be tested again on the new PR #5389

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @Paul-Licameli 's branch build:  audacity-win-3.5.0-alpha-20240103+c17e14b-x64

This now appears to work properly with _**NO**_  unwanted stereo splitting with both of the use case STRs.

**Comment by dozzzzer** [comment]
Tested
