### ISSUE TITLE
High Quality Change Tempo and Change Pitch effects are broken

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5397]
### Steps to reproduce

1. Have an audio clip
2. Apply Change Tempo (high quality) effect
3. Apply Change Pitch (high quality) effect
4. Observe

### Expected behavior

The effects are applied correspondingly to the clip.

### Actual behavior

The audio clip remains the same. No changes were applied.

### Audacity Version

current master / alpha / nightly build

### Operating system

All

### Regression
This is a regression on 3.3.3

**Comment by petersampsonaudacity** [comment]
I not also that if I use change Pitch on a selection with a clip/track the at the end of the selection I get a short silent gap.  This si NOT a regression same thing happens in 3.3.3

![image](https://github.com/audacity/audacity/assets/50205984/9027a9bb-eac5-45a0-928d-576c203a4278)

Does this need logging as a separate bug @dozzzzer @crsib  ?

**Comment by dozzzzer** [comment]
Bisects to https://github.com/audacity/audacity/commit/97f10ed0badca020f9825a16aba7953941ef8cd6
@saintmatthieu

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest 3.4.0 Beta:  audacity-win-3.4.0-beta-20231020+0ec0d02-x64-msvc2022

Both Change Pitch and Change Tempo now work properly in High Quality mode.

@LWinterberg @dozzzzer 
This testing has shown me that the High Quality produces **_much better_** results. Accordingly I would suggest that it would be better to have High Quality set "on" by default for both these effects (then those who are desperate to save a liitle time can turn it "off" and put up with poorer results.

_The Silence issue I reported above is still extant in this latest build, I will log a fresh ticket for this,_
