### ISSUE TITLE
Audacity throws error when "hand" cursor is present on cut lines.

### ISSUE THREAD

**Issue by joeessayvoice** [audacity/audacity#5399]
### Bug description

I've been cutting and pasting areas of silence into my audio line, and it ends up throwing errors when I attempt to apply My effects chain.  I noticed specifically some of my cut lines have a "hand" cursor on them instead of the "pointer" cursor.  This seems to be the tell that it's going to fail.
![image](https://github.com/audacity/audacity/assets/146398802/8e9b5792-8046-47b4-9a02-edb92bfd54d6)

![image](https://github.com/audacity/audacity/assets/146398802/c5d5d201-6792-4234-b4ca-867b3eb5d638)

Zoomed in extremely close looks odd:
![image](https://github.com/audacity/audacity/assets/146398802/7f95c62b-4efb-4062-a2b2-2f2a0f689636)

Here's the .aup3: https://www.dropbox.com/scl/fi/f54kmh4rumd05m11q31xw/Fail-example.aup3?rlkey=cye1fdzg1z1tp14c9tju4d7hw&dl=0

### Steps to reproduce

1. Load aup3
2. Attempt to Normalize, or compress, or some other effect

### Expected behavior

No Error should occur.

### Actual behavior

Error state occurs.

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

**Comment by LWinterberg** [comment]
These lines got removed in 3.4
