### ISSUE TITLE
Custom "Snap" length

### ISSUE THREAD

**Issue by QuartzSTQ** [audacity/audacity#5405]
### Your idea

Being able to use a custom length for the snap feature.

### Problem to be solved

Working around this by setting up a specific tempo and snapping to it.

### Additional context

This would mainly be useful for splitting a lossy stream by setting it to codec frame lengths in samples. Ideally, the software I'm using to split the audio would have this natively, but it doesn't.

**Comment by LWinterberg** [comment]
There is an argument to have direct MP3 editing at some point in the far future. For this particular use case, snapping to frames wouldn't help you; things would still be decoded and re-encoded with all the generational loss that incurs.

Use [mp3DirectCut](https://mpesch3.de/) instead.

**Comment by LWinterberg** [comment]
mp3directcut can also cut frame by frame.

**Comment by QuartzSTQ** [comment]
I think I was actually trying to cut AC-3, albeit the usefulness of cutting audio which is likely supposed to be combined with video is debatable. mp3DirectCut also isn't open-source. Anyway though, complaining isn't going to achieve anything, albeit I'd still like this to be implemented, if not specifically for cutting lossy streams then for something else. Maybe it would clutter up the interface too much, I dunno.
