### ISSUE TITLE
Audacity options do not work

### ISSUE THREAD

**Issue by hueychen27** [audacity/audacity#5407]
### Bug description

Using options with Audacity 3.3.3 in Kali Linux and probably other distributions of Linux do not work.

### Steps to reproduce

1. Run `audacity -version` or `audacity -help` in a Linux terminal

### Expected behavior

The output should be the version of Audacity.

### Actual behavior

Audacity returns:
```
(process:507074): Gdk-CRITICAL **: 17:04:28.948: gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed

(process:507074): Gdk-CRITICAL **: 17:04:28.948: gdk_window_get_display: assertion 'GDK_IS_WINDOW (window)' failed

(process:507074): Gdk-CRITICAL **: 17:04:28.948: gdk_cursor_new_from_pixbuf: assertion 'GDK_IS_DISPLAY (display)' failed
```

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

### Additional context

I tried the commands `audacity -version` and `audacity -help` in a Debian virtual machine, but it still returns the same thing:
```
(process:507074): Gdk-CRITICAL **: 17:04:28.948: gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed

(process:507074): Gdk-CRITICAL **: 17:04:28.948: gdk_window_get_display: assertion 'GDK_IS_WINDOW (window)' failed

(process:507074): Gdk-CRITICAL **: 17:04:28.948: gdk_cursor_new_from_pixbuf: assertion 'GDK_IS_DISPLAY (display)' failed
```

**Comment by LWinterberg** [comment]
those are simply the wrong arguments, it's either `-h` or `--help`.

That said, --version indeed appears broken for me. Given that Audacity currently is not really useful in a command line anyway, I'm not sure these arguments are necessary at all, or whether they should just be removed.

**Comment by hueychen27** [comment]
The manual found with `man audacity` says that the options are `-version` and `-help`

**Comment by hueychen27** [comment]
For some reason, and option (even options that don't exist) just return the same thing for me.

**Comment by hueychen27** [comment]
I found this: `This man page documents audacity version 1.3.5`

**Comment by hueychen27** [comment]
Now audacity just aborts when you try to include any option with it.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.

**Comment by hueychen27** [comment]
Oh nice!
