### ISSUE TITLE
Crash after trying to open Preferences after unsuccessful external program export

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5417]
### Steps to reproduce

1. grab some audio
2. Cmd + Shift + E
3. select format: (external program)
4. in the **Command** input box, type some gibberish e.g. `qqq - "%f"`
5. click **OK** to dismiss the error message dialog
6. click **Cancel**
7. press `Cmd + ,` to access Preferences

### Expected behavior

Preferences dialog opens up.

### Actual behavior

A crash

https://github.com/audacity/audacity/assets/70063970/3edc730c-5313-4ed2-bfd8-47891388452a

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

### Additional context

Sentry: https://sentry.audacityteam.org/share/issue/63371df213534042b0cfae68e7a15b53/

**Comment by petersampsonaudacity** [comment]
Testing on W10 with 3.4.0 Beta-1

I cannot reproduce this on Windows

**Comment by dozzzzer** [comment]
Tested
