### ISSUE TITLE
Looping region is ignored when enabling looping during playback

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5422]
### Steps to reproduce

1. generate chirp
2. select a few-second region on the timeline
3. observe: looping enabled automatically
4. put the cursor at the beginning of that region
5. hit Play
6. click Enable Looping button to disable looping
7. click Enable Looping once again as the play head approaches the end of the looping region
8. observe

### Expected behavior

Once the play head reaches the end of the region, it jumps back to the beginning.

### Actual behavior

Once the play head reaches the end of the looping region, it keeps going further as if looping was turned off.

https://github.com/audacity/audacity/assets/70063970/642a4781-7251-49b8-aeff-1c4c9c5c9286

### Audacity Version

current master / alpha / nightly build

### Operating system

win11, macOS 14

**Comment by chinakov** [comment]
Tested, works now! Thanks!
