### ISSUE TITLE
Minor typo ("capabailities" instead of "capabilities")

### ISSUE THREAD

**Issue by zeritonius** [audacity/audacity#5423]
### Bug description

AUD-DO is a function that extends Nyquist's capabailities. 
The word "capabilities" is spelled "capabailities".

### Steps to reproduce

Go to:
https://manual.audacityteam.org/man/nyquist_macros.html

Find the text AUD-DO is a function that extends Nyquist's capabailities.
(it's on top 25% of the page)
![capabailities](https://github.com/audacity/audacity/assets/89370810/00c3b182-fc1c-4b29-8baa-e6a898723e05)

### Expected behavior

The word "capabilities" to be spelled "capabilities".

### Actual behavior

The word "capabilities" is spelled "capabailities".

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

**Comment by petersampsonaudacity** [comment]
Thanks for the report @zeritonius 

I will be fixing this for the manual for the soon to be upcoming 3.4.0 release.

**Comment by petersampsonaudacity** [comment]
@zeritonius 

Done:
![image](https://github.com/audacity/audacity/assets/50205984/466c6d72-1d88-4ab9-b1a3-caaa2338d7a2)

https://alphamanual.audacityteam.org/man/Nyquist-Macros
