### ISSUE TITLE
The Audacity logo is missing from the 3.4.0 alpha Manual (soon to be the new released Manual)

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#5428]
### Bug description
The Audacity logo is missing from the 3.4.0 alpha Manual.

This will soon to be the new released Manual so the need to fix this is **_urgent_**,

I suspect that this may be a result of the new expanded Audacity logo that was implemented for 3.4.0

### Steps to reproduce
1. Launch 3.4.0 latest Beta
2. Help > Manual
3. Observe: _**NO**_ Audacity logo at top left of the page (all pages)
4. Launch 3.3.3
5. Help > Manual
6. Observe: Audacity logo displays at top left (on all pages)

### Expected behavior
![image](https://github.com/audacity/audacity/assets/50205984/1a7f6e8d-431f-4a1e-91a5-60e676bba893)

### Actual behavior
![image](https://github.com/audacity/audacity/assets/50205984/e5c55d04-4246-40cb-b269-3ad9c01e4a45)

### Audacity Version
latest beta 3.4.0

### Operating system
Windows 10 - but assume all OS

### Additional context
Flagging @LWinterberg amd @crsib 

**_Even as the main editor of the manual I have no idea at all how that Audacity logo is placed as part of every page in the manual ..._**

**Comment by LWinterberg** [comment]
The thing tries to load `https://www.audacityteam.org/wp-content/uploads/2016/01/NEW_AudacityTransMediaWiki_sans_serif.png`, which of course no longer exists as the wordpress install is no more. I pinged sysadmin to make it point to a file local to the alphamanual instead.

see https://www.mediawiki.org/wiki/Manual:FAQ#How_do_I_change_the_logo? for details
