### ISSUE TITLE
Drag and drop of (previously exported) label files

### ISSUE THREAD

**Issue by KoenT-SS** [audacity/audacity#5433]
### Your idea

When using label tracks to annotate audio files in Audacity, you can export your labels and then re-import them by using File → Import → Labels…
It would be super useful if you could simply drag and drop a label file onto Audacity, as you can do for audio tracks.

### Problem to be solved

If you're using Audacity for annotating sets of audio files using label tracks, you need to switch a lot between different files.
Typically, each audio file (say "recording001.wav") has a corresponding label file ("recording001.txt").
And each time you switch to a new pair of audio/label files, you currently need to do this:
1. remove all tracks (or start a new Audacity instance)
2. drag and drop the audio file on Audacity (or go through the File menu)
3. go to: File -> Import -> Labels (3 clicks) and then browse for and select the label file to import

It would be nice if you could also drag and drop a previously exported label file onto an open Audacity project.
Then you could simply select both the audio and label file in Windows Explorer / macOS Finder / ... and drag and drop them both on Audacity instead of having to go through the menu each time.

The drag and drop handling could check the file extension (.txt), and then add the labels as a new label track in the project.
Since .txt is a not-so-specific and rather common extension, the drop event handling could do some quick contents check first (like checking the first line and see if it is pure text with 3 tab-separated columns).

Also, if you drag and drop _set_ of audio files and label files, they would all be added as audio tracks and label tracks.

### Additional context

Was originally discussed here on the Audacity forum some time ago: https://forum.audacityteam.org/t/drag-and-drop-of-previously-exported-label-files-fr/65174/1

**Comment by petersampsonaudacity** [comment]
This sounds like a very sensible enhancement request to me.

**Comment by Tillomar** [comment]
If the label file was previously exported, and now needs to be reimported, then I wonder why the user didn't simply save the audio file as an audacity project, complete with the labels?
That said, the idea has indeed some merits – I often create label file from scratch or calculate them by spreadsheet, so importing them by d'n'd would be easier then going through import.
### Extension of this idea
But I would like allow the d'n'd to address not only the whole project, but one track specifically if you drop the label file on it – that way the labels would adjust to the beginning of that specific track, w/o need to adjust the label track manually.

**Comment by LWinterberg** [comment]
We've had this before in #680, and after some re-consideration I think it still doesn't quite pan out: Text files you might want to drag'n'drop into a project include

* Labels
* Effect preset
* Sample data
* Subtitles
* Spectrum plots
* Project notes
* Macros
* Plugins/scripts

(Not all of these features exist right now, but they have chances at being a thing one day)

The majority of these are headerless, so just they just get going with data.
---

> If you're using Audacity for annotating sets of audio files using label tracks, you need to switch a lot between different files.
Typically, each audio file (say "recording001.wav") has a corresponding label file ("recording001.txt").

I think this particular use case would be better served with markers anyway. Markers are stored within the audio file itself and surprisingly widely supported.
