### ISSUE TITLE
Lisp code wrongfully identified as SAL due to 2 extra spaces

### ISSUE THREAD

**Issue by zeritonius** [audacity/audacity#5439]
### Bug description

I tried the example here:
https://alphamanual.audacityteam.org/man/Creating_Nyquist_Plug-ins

I copied and pasted the code directly into the Nyquist prompt from Audacity.
I got the error from the first picture, and I was being suggested that that's SAL code, not Lisp.
![1](https://github.com/audacity/audacity/assets/89370810/6f6fe46b-c6f6-4ddb-8c75-29c4d0ed0f4b)

I tried to put the code in a xy.ny file, and Audacity complained about it, as seen in the second picture.
![2](https://github.com/audacity/audacity/assets/89370810/460c39f3-a343-4326-a992-442f438dc831)

![3](https://github.com/audacity/audacity/assets/89370810/d0dc6c9b-8304-4bd1-80c8-039e6bd1231b)
Then I noticed in the third picture that on the page above each line has 2 extra spaces. I removed them from each line, and all the errors disappeared. Without those 2 extra spaces, the code works fine both in the Nyquist prompt, and as a file.

On the same link, there is this:
"Any line that does not begin with a semicolon (;) or a dollar sign ($) are assumed to contain Nyquist code and will be executed. "
It seems that double spaces at the beginning of a line changes the behavior. Speaking of the line above, I couldn't find an explanation of the difference between ; and $ and when to use each. To me, it's confusing that a line starting with a ; is considered a comment, and ignored, in some cases, while in other cases a line starting with ; contains control code that has effect.

### Steps to reproduce

I explained above.

### Expected behavior

I expected an error like "You have 2 extra spaces at the beginning at each line"

### Actual behavior

Lisp code wrongfully identified as SAL due to 2 extra spaces

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

**Comment by SteveDaulton** [comment]
> I couldn't find an explanation of the difference between ; and $ and when to use each.

Here: https://web.archive.org/web/20230405064412/https://wiki.audacityteam.org/wiki/Nyquist_Plug-ins_Reference#Plug-in_Translations

**Comment by zeritonius** [comment]
@SteveDaulton , thank you very much for that link. Now it's crystal clear to me.

**Comment by LWinterberg** [comment]
I changed it

(fwiw @petersampsonaudacity - nyquist codeblocks generally want to live inside of `<pre>` which does code formatting and has an implicit `<nowiki>` going on)

**Comment by SteveDaulton** [comment]
I see this has been closed as completed.
Where will I find the fix?
(I assume that it has been fixed, as you only need to strip leading spaces from lines before checking if it LISP  or SAL)

**Comment by LWinterberg** [comment]
fix will go into the manual with the next regeneration

**Comment by SteveDaulton** [comment]
So you're not going to fix the Nyquist Prompt?

**Comment by petersampsonaudacity** [comment]
> (fwiw @petersampsonaudacity - nyquist codeblocks generally want to live inside of `<pre>` which does code formatting and has an implicit `<nowiki>` going on)

@LWinterberg  - not me. I didn't write and don't edit that page.  _I have no idea about Nyqist, Lisp, Python, scripting etc._
