### ISSUE TITLE
Multiple track can be "solo"

### ISSUE THREAD

**Issue by ElijahHamilton** [audacity/audacity#5441]
### Bug description

You can set more than one track to be solo, causing them both to play.

### Steps to reproduce

1. open audacity 3.4.0
2. create two tracks
3. click solo and both tracks

### Expected behavior

One track should only be allowed to be solo.

### Actual behavior

Multiple tracks can be solo, causing all "solo" tracks to play.

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

**Comment by LWinterberg** [comment]
Allowing multiple solo tracks is the new default for 3.4. You can either shift-click onto solo to get to the old behavior, or change Preferences > Track Behaviors > Solo Button to simple.
