### ISSUE TITLE
Break dependencies on toolbars

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#5444]
Fix some old confusions in the flow of notifications, which resulted in undesirable dependencies of non-UI code on UI.

SetProjectCommand, ImportAUP, ProjectFileManager, ProjectManager,
and ProjectSelectionManager no longer depend on toolbars;
and the last also no longer depends on TrackPanel or ProjectWindow. Instead, all those windows use Observer to
update for changes of selection formats or snapping choices.

Fewer places depend on ProjectSelectionManager. That class now exists mostly to update persistent preferences
and the time selection in response to project format changes.

**Comment by dozzzzer** [comment]
Tested
