### ISSUE TITLE
Toolkit neutral TrackFocus

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#5448]
The logic for getting and setting the focused track is lowered to libraries.

TrackPanelAx is now used only by TrackPanel and together they inject the extra toolkit-dependent interaction with screen readers.

The other places that used to use TrackPanel.h, use only TrackFocus.h now.

**Comment by chinakov** [comment]
Tested! Thank you, Paul - the issue present in this branch has been fixed.
