### ISSUE TITLE
Crashes on startup, “cannot set locale“

### ISSUE THREAD

**Issue by Rasmis** [audacity/audacity#5453]
### Bug description

When I start Audacity it crashes. It gives this error message:
`Cannot set locale to language "English (Denmark)"`

If I start it again, just after quitting, it runs without issue, but “recovers” a blank project.

I’ve been living with this for some time, but yesterday I had been doing many projects in Audacity, and had not quit the app. After I’d been away from the computer, Audacity had crashed again, with the same error.

![Screenshot 2023-10-31 at 17 47 00](https://github.com/audacity/audacity/assets/1069447/1144cd15-73a8-4c40-9ace-1bfc2dbb9874)

### Steps to reproduce

I’m not 100 % sure, because the crash only happens, when Audacity has been closed for an unknown amount of time. And apparently when it’s been running in the background for some time.

But I assume it can be recreated on MacOS, using setting `System Preferences` → `Language & Region` to language: `English (UK) - Primary`, and region: `Denmark`.

![Screenshot 2023-10-31 at 17 59 05](https://github.com/audacity/audacity/assets/1069447/2f635fff-3fe7-4b8d-aa00-32a66e9df844)

### Expected behavior

Audacity should open without crashing, and should not crash when running.

### Actual behavior

It crashes when opening (after not having been used for some time), and has once crashed while being open in the background.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS

### Additional context

I have tried both the `Universal` for MacOS and the `Arm 64` for Apple Silicon (I am on an M1 Max chip).

The problem existed with `macOS Ventura`, and still exist with `macOS Sonoma`.

In the Audacity preferences, I’ve chosen “language: English”. I cannot find an option to choose a different locale.

![Screenshot 2023-10-31 at 18 04 40](https://github.com/audacity/audacity/assets/1069447/80886dfd-53d0-4240-b264-9ccf2054a240)

**Comment by crsib** [comment]
The crash from your screenshot is fixed, new release with this fix is expected in a few days
