### ISSUE TITLE
appimage wont start on debian 12 sid

### ISSUE THREAD

**Issue by enorrmann** [audacity/audacity#5455]
### Bug description

console says 

/tmp/.mount_audaciHYxL3X/bin/audacity: symbol lookup error: /lib/x86_64-linux-gnu/libcairo.so.2: undefined symbol: pixman_image_set_dither

### Steps to reproduce

donwload latest appimage

### Expected behavior

app working

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Linux

**Comment by LWinterberg** [comment]
seems fixed now
