### ISSUE TITLE
Silence audio deletes the clip

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#5456]
### Steps to reproduce

1. Create an audio track
2. Select some of the the audio
3. Edit>  Remove special > Silence audio

### Expected behavior

Selected audio is silence

### Actual behavior

All clips which intersect the time selection are deleted.

### Audacity Version

latest beta

### Operating system

Windows

### Additional context

Regression on 3.3.3

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @saintmatthieu 's branch build for 3.4.0 Beta:  audacity-win-3.4.0-alpha-20231101+1b8cac1-x64

This appear to properly fix this issue.

**Comment by saintmatthieu** [comment]
Thanks @petersampsonaudacity !

**Comment by chinakov** [comment]
Tested!
