### ISSUE TITLE
Applying destructive effect to  part or all of a time stretched clip results in clip with no name 

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#5461]
### Steps to reproduce

1. Create an audio track which contains a clip.
2. Time stretch the clip.
3. Select either all or part of the clip
4. Apply a destructive effect, eg silence audio.

### Expected behavior

If all of the clip was selected, the clip retains its name.
If part of the clip was selected, then then newly created clip has a name.

### Actual behavior

If all of the clip was selected, the name of the clip is empty.
If part of the clip was selected, the name of the newly created clip is empty.

### Audacity Version

latest beta

### Operating system

All

### Additional context

I am making the assumption that the current behaviour is a bug. Or is it by design?

**Comment by LWinterberg** [comment]
I ran into this myself when silencing audio and thought "oh yeah this seems vaguely logical". But it applies to *any* destructive effect, which is kinda bad.

**Comment by petersampsonaudacity** [comment]
@DavidBailes   What this also shows is that the behavior is fundamentally different for unstretched and stretched clips

a) If you apply a destructive effect to a selection within an **un-stretched** clip
then the clip remains as a single clip.

b) If you apply a destructive effect to a selection within an **stretched** clip
then you end up with 3 clips.

I.e. the act of applying a destructive effect to a selection within a clip causes Audacity to make a de facto **Edit>Audio Clips>Split**

@saintmatthieu @LWinterberg   is there a good and necessary design reason for this behaior with stretched clips?

**Comment by crsib** [comment]
> If you apply a destructive effect to a selection within an stretched clip
then you end up with 3 clips.

This is by design. Otherwise we will have to render the stretching for the whole clip

**Comment by petersampsonaudacity** [comment]
Note that this does **_NOT_** happen with the destructive **Edit > Remove Special > Silence Audio** when applied to a stretched clip

**Comment by petersampsonaudacity** [comment]
Note that this also happens when applying the destructive menu command **Edit > Remove Special > Silence Audio** to a stretched clip

**Comment by petersampsonaudacity** [comment]
> This is by design. Otherwise we will have to render the stretching for the whole clip

@crsib   does this mean that the selected section is the rendered and no-longer stretched?

One can't tell at the moment as there is no label for the selection ...

**Comment by LWinterberg** [comment]
let's have that discussion somewhere else and not in this bug

**Comment by Paul-Licameli** [comment]
Now what about preserving clip colors?

I see the fix for clip name and I think we really need the `EmptyCopy` equivalent for `WaveClip` as for `WaveTrack` to copy, name, color, and whatever other et ceteras we might associate with clips in future.

**Comment by LWinterberg** [comment]
that sounds like an excellent utility to add for the future :)

**Comment by dozzzzer** [comment]
Tested

**Comment by petersampsonaudacity** [comment]
Tested on W10 with @saintmatthieu 's latest branch build:  audacity-win-3.4.0-alpha-20231102+8464170-x64

This now label the auto-created selected clip correctly when an effect is applied:
![image](https://github.com/audacity/audacity/assets/50205984/b221d294-75ce-48ab-ae16-d7c7934fa1ea)

**Comment by Paul-Licameli** [comment]
> Tested on W10 with @saintmatthieu 's latest branch build: audacity-win-3.4.0-alpha-20231102+8464170-x64
> 
> This now label the auto-created selected clip correctly when an effect is applied: ![image](https://user-images.githubusercontent.com/50205984/279959341-30d04729-968c-4efc-b1f3-69e4e3946268.png)

Did you test clip colors?
