### ISSUE TITLE
Applying destructive effect  to part or all of a time stretched clip results in waveform color reverting to default

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#5465]
### Bug description
Applying destructive effect  to part or all of a time stretched clip results in clip color reverting to default blue waveform.

Generators do not change the waveform color back to default.

### Steps to reproduce
1. Create an audio track which contains a clip.
2. Time stretch the clip.
3. Change the Wave Color from the TCP context menu
4. Select either all or part of the clip
5. Apply a destructive effect, e.g. Amplify
6. Observe: the selection reverts to default blue waveform

### Expected behavior
The selection should retain the waveform color set at Step 3

### Actual behavior
the selection reverts to default blue waveform

### Audacity Version
3.4.0

### Operating system
Windows

### Additional context
Change Pitch/Tempo effects do _**NOT**_ exhibit this color change

**Comment by petersampsonaudacity** [comment]
In related bug #5461 

@Paul-Licameli wrote:
>Now what about preserving clip colors?
>
>I see the fix for clip name and I think we really need the `EmptyCopy` equivalent for `WaveClip` as for `WaveTrack` to copy, name, color, and whatever other et ceteras we might associate with clips in future.

To which @LWinterberg replied:
>that sounds like an excellent utility to add for the future :)

**Comment by petersampsonaudacity** [comment]
@dozzzzer @LWinterberg 

Testing on W10 with 3.5.1 and the latest alpha master rest build for 3.6.0

I can no longer reproduce this.

I think this bug/issue can ve closed.

**Comment by dozzzzer** [comment]
I can still reproduce this on Windows and macOS in the latest master build.

**Comment by dozzzzer** [comment]
The issue can no longer be reproduced.

**Comment by petersampsonaudacity** [comment]
@dozzzzer 

Sadly this still happens for me on W10 with 3.6.4 and the latest 3.7.0 alpha test build

**Comment by petersampsonaudacity** [comment]
Might this be related to the issue I logged yesterday:

 **Joining clips in non-default wave color changes the wave color to default** #7459

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
