### ISSUE TITLE
Recording 24 bit is broken

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#5467]
### Bug description
MME, Directsound: 
![image](https://github.com/audacity/audacity/assets/87814144/ce5ece89-ab95-44ad-b302-7d877836067e)

WASAPI: 
![image](https://github.com/audacity/audacity/assets/87814144/6b02399e-a224-4aef-8dd8-534c32415311)
(note it's producing a flat waveform despite the meter going full bore)

### Steps to reproduce

1. Go to audio settings > audio setup
2. change default sample format to 24 bits
3. record

### Expected behavior

normal recording

### Actual behavior

completely broken 

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows, macOS

### Additional context

also reported on https://twitter.com/AlisterCado/status/1720174813887520825/photo/1
16-bit appears fine

**Comment by dozzzzer** [comment]
Tested

**Comment by petersampsonaudacity** [comment]
Tests Ok on W10 with 3.4.1 Beta: audacity-win-3.4.1-beta-20231103+9b8acdb-x64-msvc2022
