### ISSUE TITLE
Ask for confirmation to install programmes from the Muse Hub

### ISSUE THREAD

**Issue by vivadavid** [audacity/audacity#5469]
### Your idea

Hi,

Today I've tried Muse Hub for the first time. I'm just an Audacity user and, when I clicked on the MuseScore icon by mistake, this programme got installed without my permission. I wish I had been asked for confirmation.

### Problem to be solved

A confirmation to install a programme would solve the problem of having a programme installed by mistake.

**Comment by vivadavid** [comment]
I wish there was, in general, a way to cancel any downlods, not only for programmes.

**Comment by LWinterberg** [comment]
Heya! I'll forward this to the team. If you'd like to send further suggestions about musehub, please do so via https://musehub.zendesk.com/hc/en-gb

**Comment by vivadavid** [comment]
> Heya! I'll forward this to the team. If you'd like to send further suggestions about musehub, please do so via https://musehub.zendesk.com/hc/en-gb

Thank you: to be honest, I wasn't sure if this was the place to add suggestions about MuseHub, but I didn't know where else to go. I've created another thread with a different issue, but next time I'll use the link you've provided.
