### ISSUE TITLE
"Enable Community Acceleration" should be OFF by default

### ISSUE THREAD

**Issue by vivadavid** [audacity/audacity#5470]
### Your idea

Using my Internet connection to accelerate downloads without my permission isn't acceptable. This feature should be off by default.

### Problem to be solved

Having this feature enabled by default raises privacy concerns.

**Comment by LWinterberg** [comment]
Same as your other bug. For anyone else stumbling across this: Please send your suggestions regarding musehub via https://musehub.zendesk.com/hc/en-gb and not this bug tracker

**Comment by vivadavid** [comment]
> Same as your other bug. For anyone else stumbling across this: Please send your suggestions regarding musehub via https://musehub.zendesk.com/hc/en-gb and not this bug tracker

I will next time: sorry about that.
