### ISSUE TITLE
'Crossfade Clips' does not seem to work as of Audacity 3.4.0

### ISSUE THREAD

**Issue by jroyvde** [audacity/audacity#5471]
### Bug description

In Audacity 3.4.0 on Windows 11, attempting to use the 'Crossfade Clips' effect seems to do nothing at all, and doesn't even leave an entry in the undo history. After downgrading to Audacity 3.3.3, the effect works as intended.

### Steps to reproduce

Select part of two adjacent stereo clips and try to use the Crossfade Clips effect as normal.

### Expected behavior

The clips should join together with a crossfade effect.

### Actual behavior

Nothing happens.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows, macOS

**Comment by saintmatthieu** [comment]
Thanks @jroyvde for the report, looking into this.
Without stretching, the bug occurs with stereo clips only.
With stretching,, an error wrongly pops up about more than two clips being selected.

**Comment by petersampsonaudacity** [comment]
@saintmatthieu @LWinterberg @dozzzzer 

Have _**all**_ EGATs been tested yet with stretched clips (mono and stereo)?  

Or is this X-fade just a one-off issue?

**Comment by chinakov** [comment]
Seems that the issue has been fixed for Mono Tracks, but Stereo Tracks still do not get the effect applied to them. @saintmatthieu

**Comment by chinakov** [comment]
Added test case for Regression.

**Comment by DavidBailes** [comment]
> With stretching,, an error wrongly pops up about more than two clips being selected.

This can still happen, although normally it doesn't.

**Comment by saintmatthieu** [comment]
@DavidBailes yes, the PR attached to this bug does not intend to fix the stretched-clip case. #5483 has a follow-up PR that's supposed to (QA in progress).

**Comment by DavidBailes** [comment]
> @DavidBailes yes, the PR attached to this bug does not intend to fix the stretched-clip case. #5483 has a follow-up PR that's supposed to (QA in progress).

@saintmatthieu .Thanks. Just to clarify, that will fix Crossfade Clips as well as Crossfade tracks?

**Comment by saintmatthieu** [comment]
Yes, that follow-up PR intends to fix all problems you reported.
