### ISSUE TITLE
Exporting multiple files doesn't honor sample rate

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#5473]
### Bug description

When exporting multiple files, the sample rate is always set to 44.1k regardless of any user setting

### Steps to reproduce

1. have some audio
2. make some labels
3. go to the exporter
4. set a different sample rate (eg 16k, 96k), wav, multiple files, split by labels

### Expected behavior

exported files follow the exporter sample rate

### Actual behavior

Exported files have 44.1k sample rates

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

### Additional context

Originally reported in https://forum.audacityteam.org/t/audacity-3-4-is-out-now/88434/17?u=lwinterberg

**Comment by dozzzzer** [comment]
Tested

**Comment by petersampsonaudacity** [comment]
Tests Ok on W10 with 3.4.1 Beta: audacity-win-3.4.1-beta-20231103+9b8acdb-x64-msvc2022
