### ISSUE TITLE
We desperately need a way to see exact values for the Time Track and Envelope Tool

### ISSUE THREAD

**Issue by awrog** [audacity/audacity#5478]
### Your idea

We desperately need a way to see exact value for the Time Track (and the Envelope Tool)

We can now only place a coordinate 'by eye', hoping that it is at the exact right moment, and has exactly the right value (e.g. 100% at 1.0 sec, 75% at 1.5 sec and again 100% at 2.0 sec)
It would already help if X-Y coordinates are shown in the lower right corner of the screen when the mouse moves over a **Time Track** or when the **Envelope Tool** is active?

### Problem to be solved

Inaccuracy.

**Comment by LWinterberg** [comment]
I'll close this in favor of #1000 - We need to do automation lanes anyway. Current designs just put a tooltip near your mouse to show the value of the line you'll be editing.
