### ISSUE TITLE
Selecting (external program) in export dialog crashes the program

### ISSUE THREAD

**Issue by vsverchinsky** [audacity/audacity#5480]
### Bug description

Selecting (external program) in export dialog crashes the program

### Steps to reproduce

1. Create audio track
2. Go to export dialog
3. Choose `(external program)` in format dropdown list

### Expected behavior

No crash

### Actual behavior

Crash

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

**Comment by dozzzzer** [comment]
I couldn't reproduce this on both macOS 14 and Windows 11.

**Comment by crsib** [comment]
I can though

**Comment by chinakov** [comment]
Doesn't crash for me either - are there any additional steps to reproduce? I tried with empty tracks, added audio, LAME and ffmpeg...

**Comment by petersampsonaudacity** [comment]
Doesn't crash for me on W10 with 3.4.0 either

**Comment by SteveDaulton** [comment]
Maybe related to https://github.com/audacity/audacity/issues/5417

**Comment by mdyan** [comment]
It doesn't crash for me, but it does seem to set my audacity.cfg file to blank.

**Comment by dozzzzer** [comment]
Tested
