### ISSUE TITLE
v3.4.0 Metadata set default not working on audio export

### ISSUE THREAD

**Issue by aschiefe** [audacity/audacity#5494]
### Bug description
In the previous versions you could set the metadata to default on exports and it would persist across projects, the current version this is not working

### Steps to reproduce
1. Export an audio and update the metadata
2. Set the metadata as the default
3. Export the audio from a different project and there will be no metadata

### Expected behavior
The metadata should be default across all projects

### Actual behavior
The metadata remains blank after setting it as the default

### Audacity Version
latest stable version (from audacityteam.org/download)

### Operating system
Windows

### Additional context
I had upgraded from the previous version, do I require a full reinstall?

**Comment by JohnColket** [comment]
@aschiefe - Also, take a look at this forum post: https://forum.audacityteam.org/t/metadata-for-multiple-tracks-not-working-as-before/88607

**Comment by LWinterberg** [comment]
The core trouble here appears to be that before, the first metadata editor popping up would save its content to the file but also the project, and then the next one would load things in from the project. With the new pagination, they all get loaded at once, so the only way to pre-populate them would be by **first setting the project metadata in Edit > Metadata Editor and only then exporting**. This would be the workaround for the time being.

As a fix for this, it probably needs some sort of "use values for all exported files" button in here (only in the exporter version of the project)
![image](https://github.com/audacity/audacity/assets/87814144/42814fb5-5c51-429d-a433-3a594e7782b6)

Exact wording TBD

**Comment by JohnColket** [comment]
Also see report from forum user "JayDPiii" here: https://forum.audacityteam.org/t/another-problem-with-export-of-mp3-in-audacity-3-4-0/89315

**Comment by JohnColket** [comment]
Also see report from forum user "Geoffsvinyl" here: https://forum.audacityteam.org/t/v3-4-1-doesnt-export-multiples-with-all-metadata/89702

**Comment by ddubovoy** [comment]
The latest Audacity doesn't save extra metadata tags as default for new projects

Reproduce
1. Open Edit Metadata Tags
2. Add a new empty tag
3. Click on Set Default
4. Click Ok
5. Save project
6. Open new project
7. Open Edit Metadata Tags
8. The new added tag is not there

Tags are also not saved between projects if tag is imported from the template and then set as default. Then open new project and new tag will not be there.

**Comment by petersampsonaudacity** [comment]
Testing shows that this is a regression on 3.3.3 and earlier

**Comment by krutarth-vaishnav** [comment]
Can anyone please update when this issue will solve as I use this feature mainly across all of my projects. Otherwise, I'll need to downgrade audacity.

**Comment by Mrodent** [comment]
There is a solution to this. It's hideously irritating that Audacity's designers mess around so much. This is a mature project, things should be much more stable.
[This (closed) thread](https://forum.audacityteam.org/t/metadata-for-multiple-tracks-not-working-as-before/88607/5) gives some clues what you have to do now... but unfortunately the people there didn't have the rudimentary intelligence to explain the WHOLE procedure.
- 1. on entering the Export Audio dialog, set the Export Range to "Entire Project" (even though later we'll be doing multiple...)
- 2. click "Edit Metadata" and set items which must apply to all the tracks
- 3. click OK to return to the Export Audio dialog
- 4. at this point only, set the radio button to "Multiple Files"
- 5. click "Edit Metadata" again: you should (hopefully) find that the common fields have all been set up and only the ones which vary from track to track are different.

**Comment by petersampsonaudacity** [comment]
> There is a solution to this. It's hideously irritating that Audacity's designers mess around so much. This is a mature project, things should be much more stable.

@Mrodent:  you are not compelled to update to later versions of Audacity.  I,myself (and I know Steve Daulton does too) find 2.4.2 to be a particularly good and stable version (provided one is aware of the of "pile-of-files" project structure.  I like 2.4.2 for recording as it gives me good control over the levels with the old Nicer toolbar separate from the meters.


> [This (closed) thread](https://forum.audacityteam.org/t/metadata-for-multiple-tracks-not-working-as-before/88607/5) gives some clues what you have to do now... but unfortunately the people there didn't have the rudimentary intelligence to explain the WHOLE procedure.

If I get some time this week I will try to test your workaround here.  And if it works OK I'll update the 3,5.0 alpha Manual with it.

Peter.

**Comment by petersampsonaudacity** [comment]
@LWinterberg @dozzzzer @crsib 

Testing On W10 with @dg-no-9 's branch build for this audacity-win-3.5.0-alpha-20240217+b31a7b5-x64

The default setting for Metadata tags is with this test branch properly stored, remembered and recalled.

### Basic test:
1. launch the branch build
2. Edit > Metadata Editor
3. populate the fields 
4. Press the **Set Default** button
5. Press **OK** button to confirm and exit the dialog
6. Exit Audacity
7. launch the branch build
8. Edit > Metadata Editor
9. Observe: all metadata tags are as set at steps 3-5

![image](https://github.com/audacity/audacity/assets/50205984/c24bbc97-6d9d-4726-8980-59fcb30b5014)

------------------------------------------------------------------------------------------------------------------

### Export test
1. After running the basic test
2. Generate 30 second chirp
3. File > Export Audio
4. choose **Entire Project**
5. do _**NOT**_ use the Metadata button
6. Click the **Export button**
7. Observe: The metadata is passed through to the exported audio file

![image](https://github.com/audacity/audacity/assets/50205984/e6513e95-6491-4e17-9caf-b6304744efaf)

-----------------------------------------------------------------------------------------------------------------

### multiple export test (using the default metadata settings)
This mostly works but there are some wrinkles
1. After running the basic export test
2. create three labels in the Chirp A, B & C
3. File > Export Audio
4. Choose **Multiple Files**
5. do _**NOT**_ use the Metadata button
6. Click the **Export button**
7. Observe: most metadata is carried through from the default metadata **BUT** the **Year** is missing

----------------------------------------------------------------------------------------------------------------

1) For the Export multiple missing "Year" I will not log this or explore it further until the default metadata fix makes it to master for 3.5.0

2) I cannot comment on whether or not the "Comments" field gets carried through to either the simple whole project export or the multiple export as Windows Explorer fails to show such a field.

3) although the metadata shows Widows Explorer - when I import the audio files from these tests into iTunes the metadata does **NOT** show up in the imported iTunes files.  I do _**not**_ think this is an Audacity problem - _but I guess it may be_

**Comment by petersampsonaudacity** [comment]
Further testing with Export Multiple shows another issue - one which may be reported/logged elsewhere.
Basically if in multiple export you use the metadata button and edit the metadata then that metadata set only passes through to the first file exported - the succeeding files all get their metadata from th default metadata set

### D) Further multiple export test
1. After running the previous three tests
2. TBP

**Comment by dozzzzer** [comment]
Tested
