### ISSUE TITLE
Ctr+left-click to join clips

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#5497]
### Your idea
I suggest that we introduce a **Ctrl+left-click** (Cmd+left-click on Mac) to join adjacent clips when on (or close to) the clip junction.

### Problem to be solved
In 3.4.0 the simple left-click to join adjacent clips was removed (see #2330 ).  It is clear from several reports on the Forum that many users are really missing this simple action (and regard making a selection first and then using a menu command or context menu command as requiring too much clipping).

### Prior art
Remove the "Click to merge clips" line #2330   -  now closed as completed

### Additional context
None

**Comment by LWinterberg** [comment]
by the time you're pressing ctrl on your keyboard you might as well press ctrl+j. For joining multiple clips, this is actually faster as well: Merging 6 clips via "the line" requires 5 clicks, doing it via shortcuts requires click+drag, ctrl+j, so 2-4 actions depending on how you want to count. In case of a single track project that you want to keep a continuous waveform in, holding `ctrl` and pressing `a j` would be pretty fast as well. I'll add the shortcut in #5498

**Comment by petersampsonaudacity** [comment]
> I'll add the shortcut in #5498

Thanks @LWinterberg
