### ISSUE TITLE
Crashing when using effects (Amplify in this case)

### ISSUE THREAD

**Issue by james0r** [audacity/audacity#550]
Here is crash report:

http://dpaste.com/2H3QNHV

**Comment by JamesCrook** [comment]
Hi James.

I see you are running Audacity 2.3.3.
Is the problem 100% reproducible or does it only happen sometimes?

Could you also try our latest released Audacity, 2.4.1, and see if it happens with that too?  We don't get this crash with either 2.3.3 or 2.4.1.

**Comment by james0r** [comment]
don't have time to investigate. i'll try again with newest version soon.
