### ISSUE TITLE
Extract lib-viewport

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#5508]
Break many dependencies on `TrackPanel` and `ProjectWindow`.

Gather in one class the logic for scrolling and zooming the TrackPanel, fitting the view to tracks, expanding and collapsing tracks, scrolling to make a given track or time point visible, and keeping scrollbars thumb sizes and positions consistent.

Maybe also, repainting the view or just a portion of it displaying a given track.

Define a toolkit-neutral facade for updating the scrollbars and repainting the view, with `ProjectWindow` supplying the callbacks.

If all goes well, then with `lib-menus` extracted too, `ViewMenus` may then be extractable as a module.

**Comment by chinakov** [comment]
There's only one issue - the unmodified scroll wheel does not let the User scroll through the tracks vertically.
