### ISSUE TITLE
Open the Export Audio dialog in center of screen

### ISSUE THREAD

**Issue by GermanKiwi** [audacity/audacity#5515]
### Your idea

On Windows, the new Export Audio dialog, introduced in 3.4.0, always opens near the top-left corner of the screen.

If you move it to another location, then close it and reopen it, it opens again near the top-left corner.

This is annoying when you're using a very large screen (eg. 32").

### Problem to be solved

Please either:

A) Have this dialog always open in the center of the screen, just as the Preferences dialog does;

or

B) Have this dialog remember its last location, so it always reopens wherever the user last positioned it.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with 3.4.0 and the latest Beta build I have for the upcoming 3.4.1

I cannot reproduces this - the export dialog opens over my Audacity window:
![image](https://github.com/audacity/audacity/assets/50205984/701438d2-9ab2-4da1-9ca8-054a9b9daf63)

**Comment by dozzzzer** [comment]
Tested
