### ISSUE TITLE
Paste Into Label via 'Ctrl + V' Fails

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#5518]
### Bug description

Ctrl+V to paste into a label fails.

### Steps to reproduce

1. Open Notepad.  Type in "xyz" and select, copy w/Ctrl+C
2. Open Audacity.  Generate Chirp.
3. Create a point or region label w/Ctrl+B
4. Paste the "xyz" text into the new label w/Ctrl+V

### Expected behavior

"xyz" text gets pasted onto the label.

### Actual behavior

Nothing happens

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

Reported on Forum: https://forum.audacityteam.org/t/ctrl-v-doesnt-work-no-more/88848

**Comment by dozzzzer** [comment]
>Looks like a duplicate 

Not a duplicate, this one describes the issue of pasting via Ctrl + V, while #2854 is about copying from the label via Ctrl + C

**Comment by dozzzzer** [comment]
Bisects to https://github.com/audacity/audacity/commit/4f5f9dac96fccbe26d976284e4ee61ab08ab3499
@vsverchinsky

**Comment by crsib** [comment]
I think we should fix this in 3.4.2, looks quite bad to me

@LWinterberg

**Comment by dozzzzer** [comment]
Tested
