### ISSUE TITLE
wxGTK is underlinked

### ISSUE THREAD

**Issue by mikhailnov** [audacity/audacity#552]
Building with `-Wl,--no-undefined`:

```
/usr/bin/ld.default: CMakeFiles/mod-script-pipe.dir/ScripterCallback.cpp.o: in function `__static_initialization_and_destruction_0':
/usr/src/RPM/BUILD/audacity-src-2.4.1/modules/mod-script-pipe/ScripterCallback.cpp:114: undefined reference to `wxArrayString::~wxArrayString()'
/usr/bin/ld.default: CMakeFiles/mod-script-pipe.dir/ScripterCallback.cpp.o:(.data.rel.ro._ZTI20wxThreadHelperThread[_ZTI20wxThreadHelperThread]+0x10): undefined reference to `typeinfo for wxThread'
<...>
```

Probably `wx-config --libs` have to be used.

**Comment by mikhailnov** [comment]
CMAKE_EXE_LINKER_FLAGS and CMAKE_MODULE_LINKER_FLAGS seem to be ignored

**Comment by mikhailnov** [comment]
As the resulting binary cannot be underlinked, maybe here there is no sense in try to avoid underlinking

**Comment by JamesCrook** [comment]
Please explain more clearly.
What do you mean by 'underlinked'?

Is your point about mod-script-pipe (only)?  
Is it that mod-script-pipe requires wxWidgets libs?

**Comment by mikhailnov** [comment]
when Audacity is being build with `-Wl,--no-undefined`, some middle stages of compilation fail because some wx libs are not linked

**Comment by lllucius** [comment]
> 
> 
> when Audacity is being build with `-Wl,--no-undefined`, some middle stages of compilation fail because some wx libs are not linked

Interesting...I do not see that here and we actually NEED --no-undefined so that the symbols are resolved at runtime, rather than build time.

How are you building?

**Comment by mikhailnov** [comment]
--no-undefined is not needed, but it would be nice to be able to build correctly with it
I actually realized that it is not obligatory to be able to be buildable with --no-undefined a bit after reporting this issue

**Comment by JamesCrook** [comment]
Closing.
Bug report is unclear.  Also:

>I actually realized that it is not obligatory to be able to be buildable with --no-undefined a bit after reporting this issue
