### ISSUE TITLE
Create preference for paste-as-clip vs paste-into-clip

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#5521]
Located in: Preferences > Track Behaviors > Behaviors

Option name: "Always paste audio as new clips"

Option either restores pre-3.4 behavior or keeps 3.4 behavior. The old behavior is the default

**Comment by petersampsonaudacity** [comment]
From reading posts on the Forum and on Facebook this is likely to be popular with users.

**Comment by LWinterberg** [comment]
yeah, this was a blunder on our part. Having the 3.4.0 behavior makes a lot of sense when overlapping clips exist (ie: you paste where you want your correction and then can make changes to the timing non-destructively), so we thought this would be some preparatory work - but as it turns out, it just gets in the way with very little benefit otherwise without overlapping clips.

**Comment by dozzzzer** [comment]
Tested
