### ISSUE TITLE
Unsquish audacity logo in installer

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#5522]
![image](https://github.com/audacity/audacity/assets/87814144/3056f646-ca5e-4015-8488-fc88a57ef1e9)

File in question is "\win\Inno_Setup_Wizard\audacity_InnoWizardImage.bmp". I'll fix it another time

_Originally posted by @LWinterberg in https://github.com/audacity/audacity/issues/5291#issuecomment-1799021886_

**Comment by dozzzzer** [comment]
tested
