### ISSUE TITLE
Pasting Over Clips can create blank space

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#5523]
### Bug description

When "Editing a clip can move other clips" is set, and pasting over an identical sized clip, white space is created.

### Steps to reproduce

1. Set Edit > Preferences > Tracks > Tracks Behaviors > "Editing a clip can move other clips".
2. Generate 10 second chirp.\
3. Select 1st one second of audio, then Ctrl+C
4. At 9 second mark, Ctrl+V
5. At 5 second mark, Ctrl+V
6. Again, at 5 second mark, Ctrl+V

### Expected behavior

No change.

### Actual behavior

One second of white space inserted at the 10 second mark.
![image](https://github.com/audacity/audacity/assets/76828213/273c391b-6496-4f0e-9e1f-f6fcb796cceb)

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

Reported by Forum users "robinjohnson" and "Bear1" here: https://forum.audacityteam.org/t/bug-with-pasting-over-clips-in-3-4-0/89013

Also, a similar behavior reported  by Forum user "tiberius" during Noise Reduction here: https://forum.audacityteam.org/t/noise-reduction-shifting-track/88649/6

**Comment by DavidBailes** [comment]
I can confirm that when Tracks Behaviors > "Editing a clip can move other clips" is enabled, there are significant problems with pasting. Tested using 3.4.1.
Here's a more straightforward example:
Create a chirp and divide it into 3:
![image](https://github.com/audacity/audacity/assets/11887021/dcffb54d-6736-4acb-b02a-8257c748ad75)

Then select the third clip and copy, select the first clip and paste. Result:
![image](https://github.com/audacity/audacity/assets/11887021/90d831e0-b3d0-4735-962a-7a9618770ad1)

Alternatively, select the third clip and copy, make a small selection in the second clip:
![image](https://github.com/audacity/audacity/assets/11887021/f5ed49f6-4c84-4c5e-8fe6-23b7823c88c0)

Then paste:
![image](https://github.com/audacity/audacity/assets/11887021/a9fd8923-c14d-4645-be9a-bb61a6569d20)

Had a quick test using https://github.com/audacity/audacity/pull/5524
Looks OK with the new option being false, but same issues if it's true.

**Comment by DavidBailes** [comment]
@LWinterberg . Given that this significant bug occurs in https://github.com/audacity/audacity/pull/5524 if "Always paste audio as new clips" is checked, could this bug be fixed for 3.4.2? (or else the old behaviour restored, and the new option removed)

**Comment by dozzzzer** [comment]
> could this bug be fixed for 3.4.2?

yes

**Comment by chinakov** [comment]
All three cases mentioned in this bug report are fixed by the underlying MR, thank you!
