### ISSUE TITLE
Tracks don't Solo at all

### ISSUE THREAD

**Issue by gadielisawesome** [audacity/audacity#5527]
### Bug description

Clicking Solo does not mute any tracks, and the Mute button can stay pressed at the same time. This occurs in new and old project types.

![image](https://github.com/audacity/audacity/assets/51249136/a9524c9c-21f5-40aa-9038-30d35b85476f)

### Steps to reproduce

1. Create a new audacity project / Open an audacity project
2. Add two or more tracks containing audio data
3. Click Solo on any track.

### Expected behavior

All other tracks should mute, and the current one should unmute if neededd.

### Actual behavior

The current track stays the current mute state and does nothing else.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

The timeline will occasionally render nothing. Haven't been able to get a screenshot of it, so just leaving it here for now.

**Comment by JohnColket** [comment]
Yes; in 3.4.0 when you do Tools > Reset Configuration, or do this during installation, the default Solo button behavior was changed from "Simple" to "Multi-track".  You can find this at Edit > Preferences > Tracks Behaviors > Solo Button.

**Comment by gadielisawesome** [comment]
Still does the same action, even after reinstallation.

**Comment by JohnColket** [comment]
> Still does the same action, even after reinstallation.

Sorry if I was not clear.  You will need to change this at:  Edit > Preferences > Tracks Behaviors > Solo Button.

**Comment by gadielisawesome** [comment]
I did. This still occurs even after saving.

**Comment by JohnColket** [comment]
> I did. This still occurs even after saving.

What did you set it to ?

**Comment by gadielisawesome** [comment]
![image](https://github.com/audacity/audacity/assets/51249136/d151cbad-3841-4992-983a-801d956fa9ae)

**Comment by JohnColket** [comment]
Simple would be what you are looking for.  Based on your clip in your original report, it looks as though your shift key may be stuck.

**Comment by gadielisawesome** [comment]
Shift key isn't stuck, I'm typing normally.

**Comment by JohnColket** [comment]
> Shift key wasn't stuck, bug occurred even after restart.

Then I have absolutely no idea what is going on.  Good Luck!

**Comment by amarraff** [comment]
> Yes; in 3.4.0 when you do Tools > Reset Configuration, or do this during installation, the default Solo button behavior was changed from "Simple" to "Multi-track". You can find this at Edit > Preferences > Tracks Behaviors > Solo Button.

Thank you, I was unaware of this change, and I was confused. Got it working how I prefer now.
