### ISSUE TITLE
"select all audio if selection required" doesn't work on Copy anymore

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#5529]
### Bug description

Reported by Forum User "mitch_park" here: https://forum.audacityteam.org/t/pasting-behavior-has-changed-in-3-4/88581/24

The behavior for Ctrl+C with no selection has changed from 3.3.3

### Steps to reproduce

1. Open Audacity
2. Make a 1 second recording.
3. Ctrl+C

### Expected behavior

1) If Preferences > Track Behavior "Select all audio, if selection is required", All audio is copied to the clipboard.

2) If not selected, an error message, as in 3.3.3 would be appropriate:
![image](https://github.com/audacity/audacity/assets/76828213/7ec09079-6415-4052-bdee-3240f2cd3768)

### Actual behavior

Nothing happens; nothing is copied to the clipboard, regardless of the Track Behavior setting.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows, macOS

**Comment by LWinterberg** [comment]
this is intentional; the goal was to make it behave like copying text. If you're copying nothing... you're copying nothing. No need to pop up a big warning every time.

**Comment by LWinterberg** [comment]
ah sorry, you're talking about the  specific case when that one preference is on
