### ISSUE TITLE
Allow configuring Audiocom endpoints in audacity.cfg

### ISSUE THREAD

**Issue by crsib** [audacity/audacity#5531]
Allow changing the configuration for Audio.com without rebuilding Audacity:

The following settings are needed to satisfy the QA purposes:

* Endpoint
* OAuth parameters
* Login page
* URL templates

Additionally, configuring a proxy server is very useful.

**Comment by dozzzzer** [comment]
Link Account is broken: clicking the button opens a blank page instead of https://audio.com/auth/sign-in

**Comment by crsib** [comment]
Please clarify

**Comment by dozzzzer** [comment]
Tested
