### ISSUE TITLE
Export still can export without extension

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#5533]
STR: 

1. Type in a new name (without extension)
2. Press ENTER

I see the field populate briefly before the window closes, but apparently it happens after the exported file's name already got locked in.

Hey, at least it's harder to get into this state.

Reported in https://forum.audacityteam.org/t/exporting-as-a-document-bug-in-3-4/89330

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @crsib 's branch build:  audacity-win-3.4.2-alpha-20231109+b783cdc-x64

This looks to fix this residual issue.

Testing with various selected format and a filename with no extension when pressing Enter - the outputted file has the appropriate extension added.

And as @LWinterberg points out, if you look carefully on pressing the Enter the extension is briefly added on-screen.

**Comment by dozzzzer** [comment]
Tested
