### ISSUE TITLE
Break dependency cycle of CommonTrackControls, TrackButtonHandles, TrackInfo

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#5534]
#5508 will not strictly depend on this, but it will worsen one of the other existing dependency cycles without this.

Better to avoid the cycle, or correct it after merging it.

The other dependency cycle is this one: 

<img width="266" alt="image" src="https://github.com/audacity/audacity/assets/11670369/96c5e59d-21d1-4803-ab12-7a9201d8ab42">

Later, at least `SelectUtilities` and `TransportUtilities` should be freed from that one so they can move to toolkit neutral menus.

Fixing this issue will avoid complicating that other future work

**Comment by chinakov** [comment]
Tested! Thank you!
