### ISSUE TITLE
Builds 3.4.1 - Looks like portable builds x86 and x64 are flipped (32bit zip contains 64bit build and vice versa).

### ISSUE THREAD

**Issue by RonnyTNL** [audacity/audacity#5537]
### Bug description

32bit zip for build 3.4.1 contains 64bit build.
64bit zip for build 3.4.1. contains 32bit build.

### Steps to reproduce

1. download 32bit zip
2. extract and run it's the x64 binary

3. download 64bit zip
4. extract and run it's the x86 binary

### Expected behavior

32bit zip should contain 32bit version.
64bit zip should contain 64bit version.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

**Comment by crsib** [comment]
Thank you for noticing, that is fixed now!
