### ISSUE TITLE
Missing bitrate options for MP2 in the new export UI

### ISSUE THREAD

**Issue by Logan589XP** [audacity/audacity#5539]
### Bug description

In the new versions of Audacity (3.4.0/3.4.1) with the new export UI when selecting MP2 for export the bitrate maxes out at 256 kbps even though in the old export UI (3.3.3 and earlier) it went up to 384 kbps, which is MP2's max bitrate.

### Steps to reproduce

1. Select Export Audio
2. Select MP2 as the Format
3. Make sure the Version is set to MPEG1
4. Select the Bitrate dropdown and scroll down to the bottom of the list.

### Expected behavior

It's supposed to max out at 384 kbps.

### Actual behavior

You'll see that the bitrate only goes up to 256 kbps

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by dozzzzer** [comment]
Tested
