### ISSUE TITLE
Preferences option to disable the crashpad process from starting.

### ISSUE THREAD

**Issue by RonnyTNL** [audacity/audacity#5542]
### Your idea

I would like to have control over the crashpad being started and/or allowed to be used.
Can't find anything in preferences.

### Problem to be solved

Sending of crashreports should be under user control and with the option to disable the feature.

**Comment by crsib** [comment]
The crash report is sent only when you press send, so it is totally under your control. In any case, you can just delete `crashreporter` from your installation.

**Comment by RonnyTNL** [comment]
Sorry only partially agree, that's not clear to the user, I prefer to not having the potential process running at all.
Why would it be an issue to give the user an option to disable crash reporting?

Renaming the files results in an error message.

![image](https://github.com/audacity/audacity/assets/19427356/8171cc86-8fb5-41bf-a18f-5ed3d408fa23)
