### ISSUE TITLE
Audio file header search for loop metadata

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#5546]
Provide utility that extracts loop metadata from audio (wav only?) file.
In particular, look for the presence of an ACID chunk.
Useful links:
* https://exiftool.org/TagNames/RIFF.html#Acidizer
* https://forums.cockos.com/showthread.php?t=227118

The information we are particularly interested in and which should be available is:
* "one-shot" (negation of "is loop?")
* "tempo" (in beats or quarter-notes per minute ?)
* "meter" (time signature)

If possible also extract the rest of the information specified by the ACID standard:
* "root note" (key ?)
* "beats" (number of beats (or quarter notes?))
* ...

If no metadata is present, an attempt at parsing the file name would follow (other ticket).

The MuseHub team plans a release of their server where sounds will be stored and downloaded as WAV (no Opus step anymore). David Hearn said he'd add to "the list" the burning of such metadata in their audio file headers according to the ACID standard.

**Comment by saintmatthieu** [comment]
Interesting, thank you!

**Comment by LWinterberg** [comment]
https://www.abyssmedia.com/tunexplorer/bpm-key-metadata.shtml has more still: 

> In Xiph comment tags, the BPM is conventionally stored in a field with the key 'BPM'.
> In APE metadata tags, the BPM is stored in an atom named 'BPM'.
> In MP4 tags, the tempo is stored in a 'tmpo' atom. This is part of the MP4 standard.
> In ASF tags, the tempo is conventionally stored in a field 'WM/BeatsPerMinute'.

the WAV and ID3 tags probably are going to be the most interesting ones anyway

**Comment by chinakov** [comment]
If a User creates a flagged .wav file via riff-test-util with these parameters: `.\riff-test-util.exe 2.wav 15.0 MuseHub 150` - Audacity fails to read the BPM tag, and no tempo adjustment is made. 

Note: Exif-Tool returns correct data.
![image](https://github.com/audacity/audacity/assets/139755141/a0ee82dc-f96b-4e26-bcdb-5f05f86c0c75)

Expected outcome: BPM is adjusted to 150.
