### ISSUE TITLE
Crash with LegacyMacroOutputFolder.ny plug-in

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#5547]
### Bug description

Audacity 3.4.1 crashes when running [LegacyMacroOutputFolder.ny](https://forum.audacityteam.org/uploads/short-url/Aj4j1nMq6dxRhsUV7I0Znp2EBH3.ny)

This plug-in works in previous versions, including 3.4.0, so it's a regression in 3.4.1.

### Steps to reproduce

1. Run the LegacyMacroOutputFolder.ny plug-in.
2. Observe that Audacity crashes.

### Expected behavior

The macro-output folder is set to the same directory as the most recent imported file.

### Actual behavior

Audacity crashes.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Linux

### Additional context

This issue was initially reported on Windows: https://forum.audacityteam.org/t/legacy-macro-output-folder/62096/41
Confirmed on Linux.

**Comment by dozzzzer** [comment]
Tested
