### ISSUE TITLE
Mixing and Rendering doesn't reset the track's Gain value

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5549]
### Steps to reproduce

1. have a non-zero Gain value on a track
2. mix and render the track
3. check the Gain value

### Expected behavior

The Gain value is reset to 0.0 dB.

### Actual behavior

The Gain value remains the same after mixing-and-rendering.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS

### Additional context

A regression against 3.3.3

**Comment by dozzzzer** [comment]
Bisects to https://github.com/audacity/audacity/commit/e34dd1fa1d31c4d3479ca2431c6864af1901bab6

**Comment by chinakov** [comment]
Tested! Thanks
