### ISSUE TITLE
Failed to enable install and load Effect Plugins -Ubuntu 20.04 PPA Version.

### ISSUE THREAD

**Issue by Charlie-Ramirez-Animation-Studios-de-MX** [audacity/audacity#555]
It is impossible to activate and install Effects Plugins. Both at startup and with an open project.
The Add / Remove dialog box. It does not save the enabled / disabled state of the plugins, it only shows the default plugins. When changing to activated and closing them they are unchecked again.

**To Reproduce**
Download the PPA Version, via terminal (sudo apt install audacity) in Ubuntu 20.04.
[error after updating version possibly]

- open (a ghost icon will blink disappearing in the gnome bar) -Splash Screen is not shown [another bug?]
-Audacity will open. Try to Install or enable a plugin in the Add option (Effects)
-Enable and then check in the effects list (the plugin is not there, when you return to the add list, you will see that it is disabled) [See Image]

-Go to the tools tab.
-The tool to install Plugins automatically is not shown and has been replaced by another button that redirects to the  "adding remove plugins" from the effects function.
Folder usr/share/Audacity/Plug-ins (doesn't Exist). [cannot be created, could be...manually with root permissions

Disabled plugins should be enabled when changing Add / Remove Plugins.
-The tool to import (install, new plugins should appear)
In some Tabs the Text exceeds the limits or is not centered (I'm not sure if it will be an audacity bug or if it is a secondary consequence of the system escalation)

**Screenshots**
![Captura de pantalla de 2020-05-30 20-18-34](https://user-images.githubusercontent.com/64709446/83342420-eea7aa80-a2b4-11ea-847e-f8e7aaad4e20.png)
![Captura de pantalla de 2020-05-30 20-56-53](https://user-images.githubusercontent.com/64709446/83342706-28c67b80-a2b8-11ea-8469-93a53b5eec9c.png)

[tools tab does not allow taking screenshots when active]

**Additional information**
 - OS: Ubuntu 20.04 x64
 - Version Audacity 2.4.1 [Via PPA.]
Fecha de compilación:
Jan 29 2016
Commit Id:
No hay ningún identificador de revisión
Tipo de compilación:
Debug build (debug level 0), 64 bits
Compilador:
GCC 9.3.0
Prefijo de instalación:
/usr
Carpeta de configuración:
/home/charlie/.audacity-data

**Additional context**
LOG:
20:17:07: Audacity 2.4.1
20:17:07: Warning: Critical Nyquist files could not be found. Nyquist effects will not work.
20:17:19: Retrieving FFmpeg library version numbers:
20:17:19:    AVCodec version 0x3a3664 - 58.54.100 (built against 0x3a3664 - 58.54.100)
20:17:19:    AVFormat version 0x3a1d64 - 58.29.100 (built against 0x3a1d64 - 58.29.100)
20:17:19:    AVUtil version 0x381f64 - 56.31.100 (built against 0x381f64 - 56.31.100)
20:18:26: Error: .so: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio
20:35:24: Error: .so: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio
20:39:01: Error: .so: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio

-Assist Report Data Genered:
[Audacity_dbgrpt-23899-20200530T203956.zip](https://github.com/audacity/audacity/files/4706953/Audacity_dbgrpt-23899-20200530T203956.zip)

**Comment by JamesCrook** [comment]
Fecha de compilación:
Jan 29 2016
Commit Id:
No hay ningún identificador de revisión
Tipo de compilación:
Debug build (debug level 0), 64 bits

The source was created in 2020, so a compilation date of 2016 is way out of date.
Distros should be building with a revision ident.  This ppa does not.
Compilations should be release builds, not debug.

Please correct the 'additional information'.  If it is already correct, you have a bad ppa.  Ask whoever supplied it to fix it.

**Comment by JamesCrook** [comment]
Closing.  Bad ppa.  Not ours.
