### ISSUE TITLE
Investigate Windows on ARM64 build

### ISSUE THREAD

**Issue by i-lina** [audacity/audacity#5557]
### Your idea

Run Audacity natively on Windows on ARM64 platforms like Project Volterra, Thinkpads, Surface Pros etc. 

### Problem to be solved

Currently Audacity runs an x64 emulated binary on a ARM64 platform. Windows emulation of x64 binary  has known performance issues on ARM64. Running natively on Windows will help avoid these performance bottlenecks and ensure compatibility with libraries on the platform.

**Comment by crsib** [comment]
QA note: nothing to test here (yet)

**Comment by crsib** [comment]
Thank you a lot for your contribution!
