### ISSUE TITLE
3.4.1 Crashes trying to open 3.3.3 .aup3 project

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#5568]
### Bug description

Reported by forum user "jakste".  This problem occurred on a larger file reported here: https://forum.audacityteam.org/t/i-cant-open-old-audacity-projects-since-new-update/89172/7

jakste reproduced the problem on a smaller .aup3 project. Which I was able to reproduce as well.

Now sometimes it works and sometimes it crashes.

### Steps to reproduce

1. Open Audacity 3.4.1.
2. File > Open > ...Helion.aup3

### Expected behavior

![image](https://github.com/audacity/audacity/assets/76828213/ae736ab0-267d-4d0b-b8b3-3d1cf97f336a)

### Actual behavior

![image](https://github.com/audacity/audacity/assets/76828213/1bb962f5-579c-4b14-bb75-ef488e05332a)

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

I can send link to .aup3 project file privately.

Intermittent

**Comment by crsib** [comment]
Please share a link with me

**Comment by JohnColket** [comment]
https://drive.google.com/file/d/10JD90SL_RVPPjhN_gP5NMgYtT09vQ5Ea/view

**Comment by JohnColket** [comment]
I'll need a private email

**Comment by crsib** [comment]
I got the file, no worries :-)

**Comment by crsib** [comment]
I can reproduce the crash 100% when scrolling vertically

**Comment by dozzzzer** [comment]
Tested
