### ISSUE TITLE
Installing nyquist plugin crashes Audacity

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#5569]
### Steps to reproduce

1. Down load the DeEsser plugin from here: https://forum.audacityteam.org/t/updated-de-clicker-and-new-de-esser-for-speech/34283
2. Try to install it using the Nyquist plugin installer on the Tools menu. 

### Expected behavior

Audacity doesn't crash

### Actual behavior

Audacity crashes. Tried to send a crash report but that failed.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

Reported on forum: https://forum.audacityteam.org/t/lost-data-from-crash-after-saving-multiple-times/89504

This is a regression wrt 3.3.3

**Comment by DavidBailes** [comment]
I've just tried installing the nyquist ramp panning plugin: https://plugins.audacityteam.org/nyquist-plugins/effect-plugins/amplify-mix-and-pan-effects#ramp-panning

That also causes Audacity to crash, so this could affect many (all?) installations of nyquist plugins. Not good.
Will update title.

**Comment by crsib** [comment]
@dozzzzer @chinakov please check

**Comment by chinakov** [comment]
Reproduced on DeEsser.ny, Enhancer.ny, buzz.ny, dtmfrand.ny.

It seems that, most probably, installing any nyquist plugin crashes audacity. 

Here's a crashlog: [crashlog.txt](https://github.com/audacity/audacity/files/13319693/crashlog.txt)

**Comment by saintmatthieu** [comment]
@DavidBailes @chinakov could you re-test on latest `release-3.4.2` ? As far as my debugging goes, https://github.com/audacity/audacity/issues/5547 would have fixed it.

**Comment by saintmatthieu** [comment]
> latest `release-3.4.2`

https://github.com/audacity/audacity/actions/runs/6824022146

**Comment by chinakov** [comment]
@saintmatthieu - yes, the build you've posted has no issues when installing a Nyquist Plugin/Generator. Thanks!
