### ISSUE TITLE
3.4 Noise Reduction (and other Effects) Reportedly Shifting Track to the Right

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#5571]
### Steps to reproduce

1. Generate 30s tone.
2. Select about last 20s of tone
3. Duplicate.
4. Select some audio in the first or second track, open the noise reduction effect, and press get noise profile.
5. Select the clip on the second track.
6. Apply the noise reduction effect.

### Expected behavior

Operation completed successfully

### Actual behavior

Tracks shifting to the right

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows, macOS

### Additional Info

<details><summary>Several Forum users have made similar reports:</summary>

tiberius: https://forum.audacityteam.org/t/noise-reduction-shifting-track/88649
Robosquid: https://forum.audacityteam.org/t/new-bug-feature-with-3-4-noise-reduction/88981
dante1st: https://forum.audacityteam.org/t/new-bug-feature-with-3-4-noise-reduction/88981/4
robni7: https://forum.audacityteam.org/t/new-bug-feature-with-3-4-noise-reduction/88981/7
GerryVienneau: https://forum.audacityteam.org/t/new-bug-feature-with-3-4-noise-reduction/88981/8

</details>

**Comment by JohnColket** [comment]
Possibly related to these issues:

https://github.com/audacity/audacity/issues/5523
https://github.com/audacity/audacity/issues/5573

**Comment by DavidBailes** [comment]
Some steps to reproduce (tested with 3.4.1):
1. Generate 30s tone.
2. Select about last 20s of tone
3. Duplicate.
4. Select some audio in the first of second track, open the noise reduction effect, and press get noise profile.
5. Select the clip on the second track.
6. Apply the noise reduction effect.

After step 3:
![image](https://github.com/audacity/audacity/assets/11887021/de36a5e4-f702-4a5f-95cd-650702833dbc)

After step 6:
![image](https://github.com/audacity/audacity/assets/11887021/9c27e3e9-e5f7-47e8-b9d0-03130a2507cb)

**Comment by JohnColket** [comment]
> Some steps to reproduce

Thanks you David. :smiley:

**Comment by dozzzzer** [comment]
> Some steps to reproduce

Thanks David! Following these, I was able to reproduce the issue.

**Comment by DavidBailes** [comment]
@dozzzzer . Please could this be added to 3.4.2? P3 seems low given it involves loss of data.

**Comment by dozzzzer** [comment]
@DavidBailes yes, on track for 3.4.2!

**Comment by Paul-Licameli** [comment]
Bisects to 09280962c0bbddeb653594dda965e2efac71421d

**Comment by dozzzzer** [comment]
Tested
