### ISSUE TITLE
Incorrect clip positioning when applying Nyquist effects

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#5573]
### Bug description

When a Nyquist effect is applied to a clip that starts after time=0, the returned audio is shifted to the right.

### Steps to reproduce

See video attached to this forum post: https://forum.audacityteam.org/t/3-4-1-trying-to-run-macros-shifts-all-the-tracks-over-randomly/89560

### Expected behavior

Nyquist effects to work correctly.

### Actual behavior

See video attached to this forum post: https://forum.audacityteam.org/t/3-4-1-trying-to-run-macros-shifts-all-the-tracks-over-randomly/89560

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

I've seen multiple reports of this bug, and it is severely impacting users.

**Comment by DavidBailes** [comment]
This is clearly a serious bug, but we need some clear steps to reproduce.
I haven't been able to reproduce this yet.

**Comment by SteveDaulton** [comment]
> we need some clear steps to reproduce.

1. Launch Audacity 2.4.1
2. Generate a 30 second chirp (any sound will do)
3. Select from around 20 seconds to the end of the track
4. "Ctrl + D" (duplicate)
5. "Ctrl + A" (Select all)
6. Apply "High Pass Filter" (just about any Nyquist effect will do)
7. Observe that the start of the clip in the second track has been padded with about 20 seconds of silence.

**Comment by SteveDaulton** [comment]
In step 6 you can use this code in the Nyquist Prompt:
```
() *track*
```
That should just return the selected audio to the tracks without any modification.
(In Audacity 2.4.2, the selected white space in track 2 would be rendered as silence, with a split line at the start of the duplicated clip - this was an expected limitation of how Nyquist handles white space.)

This bug also occurs in Audacity 3.4.0.

**Comment by DavidBailes** [comment]
> > we need some clear steps to reproduce.
> 
> 1. Launch Audacity 2.4.1
> 2. Generate a 30 second chirp (any sound will do)
> 3. Select from around 20 seconds to the end of the track
> 4. "Ctrl + D" (duplicate)
> 5. "Ctrl + A" (Select all)
> 6. Apply "High Pass Filter" (just about any Nyquist effect will do)
> 7. Observe that the start of the clip in the second track has been padded with about 20 seconds of silence.

That's a great help. These steps also result in the same problem in the lastest commit for 3.4.2: https://github.com/audacity/audacity/commit/30cc55bdf73d3cba3544696e866d5e8dc3d1f50f

**Comment by crsib** [comment]
So this bug was introduced 2.4.1? You you mean 3.4.1 @SteveDaulton?

**Comment by DavidBailes** [comment]
Results of steps to reproduce using 3.3.3:
![image](https://github.com/audacity/audacity/assets/11887021/f2846e15-e8ee-4328-bc72-4e7f84f69afa)

Results of steps to reproduce using 3.4.1/2:
![image](https://github.com/audacity/audacity/assets/11887021/db0b2aaa-c50e-46bc-836d-eced2c7c1dbe)

So this is a regression

**Comment by SteveDaulton** [comment]
> So this bug was introduced 2.4.1?

No, that was a typo. Now corrected.
I can reproduce the bug in 3.4.0 and 3.4.1.

I don't have a copy of 3.3.3 handy, but it does not occur in 3.3.2

**Comment by SteveDaulton** [comment]
> Results of steps to reproduce using 3.3.3:

That's consistent with previous versions of Audacity.

**Comment by DavidBailes** [comment]
@dozzzzer . Please can this be added to 3.4.2, as it results in the project getting messed up.

**Comment by DavidBailes** [comment]
This appears to bisect to the same commit causing the bug with noise reduction: https://github.com/audacity/audacity/issues/5571#issuecomment-1808240999

Results of steps to reproduce with commit: 0928096
![image](https://github.com/audacity/audacity/assets/11887021/55473c5d-e62b-4d9b-92f3-7be21be91205)

Results of steps to reproduce with the previous commit: 4ed5543

![image](https://github.com/audacity/audacity/assets/11887021/94725ab0-effd-4848-ba26-254e52021a9c)

**Comment by dozzzzer** [comment]
Tested

**Comment by Paul-Licameli** [comment]
And MERGED!!!

BOO-YAH!!!!
