### ISSUE TITLE
audacity 3.4.1 consistently core-dumps on launch taking more than usual time for window to appear

### ISSUE THREAD

**Issue by koshikas** [audacity/audacity#5579]
### Bug description

ever since upgrading to audacity 3.4.1, it core dumps on launch. seems to functional normally though i haven been able to test extensively.

core dump is as follows;
Process 7814 (audacity) of user 1000 dumped core.                                                              
Stack trace of thread 7814:
#0  0x00007f5855c3a83c n/a (libc.so.6 + 0x8e83c)
#1  0x00007f5855bea668 raise (libc.so.6 + 0x3e668)
#2  0x00007f5855bd24b8 abort (libc.so.6 + 0x264b8)
#3  0x00007f5855bd3390 n/a (libc.so.6 + 0x27390)
#4  0x00007f5855c447b7 n/a (libc.so.6 + 0x987b7)
#5  0x00007f5855c4683c n/a (libc.so.6 + 0x9a83c)
#6  0x00007f5855c46b29 n/a (libc.so.6 + 0x9ab29)
#7  0x00007f5855c49353 free (libc.so.6 + 0x9d353)
#8  0x000055cc975d569d _ZN18AudacityFileConfigD1Ev (audacity + 0x4d169d)
#9  0x000055cc975d5717 n/a (audacity + 0x4d1717)
#10 0x000055cc975ce089 n/a (audacity + 0x4ca089)
#11 0x00007f5855beccc6 n/a (libc.so.6 + 0x40cc6)
#12 0x00007f5855bece10 exit (libc.so.6 + 0x40e10)
#13 0x00007f5855bd3cd7 n/a (libc.so.6 + 0x27cd7)
#14 0x00007f5855bd3d8a __libc_start_main (libc.so.6 + 0x27d8a)
#15 0x000055cc975aa0d5 _start (audacity + 0x4a60d5)

Stack trace of thread 7816:
#0  0x00007f5855caef6f __poll (libc.so.6 + 0x102f6f)
#1  0x00007f58561d3276 n/a (libglib-2.0.so.0 + 0xb8276)
#2  0x00007f5856173162 g_main_context_iteration (libglib-2.0.so.0 + 0x58162)
#3  0x00007f58561731b2 n/a (libglib-2.0.so.0 + 0x581b2)
#4  0x00007f58561a69f5 n/a (libglib-2.0.so.0 + 0x8b9f5)
#5  0x00007f5855c389eb n/a (libc.so.6 + 0x8c9eb)
#6  0x00007f5855cbc7cc n/a (libc.so.6 + 0x1107cc)

Stack trace of thread 7815:
#0  0x00007f5855cba73d syscall (libc.so.6 + 0x10e73d)
#1  0x00007f58561ce2b7 g_cond_wait (libglib-2.0.so.0 + 0xb32b7)
#2  0x00007f58561401b4 n/a (libglib-2.0.so.0 + 0x251b4)
#3  0x00007f58561a8a7e n/a (libglib-2.0.so.0 + 0x8da7e)
#4  0x00007f58561a69f5 n/a (libglib-2.0.so.0 + 0x8b9f5)
#5  0x00007f5855c389eb n/a (libc.so.6 + 0x8c9eb)
#6  0x00007f5855cbc7cc n/a (libc.so.6 + 0x1107cc)

Stack trace of thread 8257:
#0  0x00007f5855caef6f __poll (libc.so.6 + 0x102f6f)
#1  0x00007f584caf38c7 n/a (libpulse.so.0 + 0x338c7)
#2  0x00007f584cadd46c pa_mainloop_poll (libpulse.so.0 + 0x1d46c)
#3  0x00007f584cae742c pa_mainloop_iterate (libpulse.so.0 + 0x2742c)
#4  0x00007f584cae74e1 pa_mainloop_run (libpulse.so.0 + 0x274e1)
#5  0x00007f584caf7c02 n/a (libpulse.so.0 + 0x37c02)
#6  0x00007f584ca94c67 n/a (libpulsecommon-16.1.so + 0x5bc67)
#7  0x00007f5855c389eb n/a (libc.so.6 + 0x8c9eb)
#8  0x00007f5855cbc7cc n/a (libc.so.6 + 0x1107cc)

Stack trace of thread 7817:
#0  0x00007f5855caef6f __poll (libc.so.6 + 0x102f6f)
#1  0x00007f58561d3276 n/a (libglib-2.0.so.0 + 0xb8276)
#2  0x00007f5856175b97 g_main_loop_run (libglib-2.0.so.0 + 0x5ab97)
#3  0x00007f585591d14c n/a (libgio-2.0.so.0 + 0x11214c)
#4  0x00007f58561a69f5 n/a (libglib-2.0.so.0 + 0x8b9f5)
#5  0x00007f5855c389eb n/a (libc.so.6 + 0x8c9eb)
#6  0x00007f5855cbc7cc n/a (libc.so.6 + 0x1107cc)
ELF object binary architecture: AMD x86-64

### Steps to reproduce

launch audacity

### Expected behavior

audacity application launches after loading all plugins. etc.

### Actual behavior

application takes a significantly longer time to launch, and coredumps in the process

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

### Additional context

kernel: Linux-5.15.138-1-MANJARO-x86_64
glibc 2.38
glib2 2.78.1
gcc v: 13.2.1
Desktop: KDE Plasma v: 5.27.9 tk: Qt v: 5.15.11 wm: kwin_x11 dm: SDDM
Distro: Manjaro Linux base: Arch Linux

Audio:
  Device-1: Intel 7 Series/C216 Family High Definition Audio vendor: Dell 7
    driver: snd_hda_intel v: kernel bus-ID: 00:1b.0 chip-ID: 8086:1e20
    class-ID: 0403
  API: ALSA v: k5.15.138-1-MANJARO status: kernel-api with: aoss
    type: oss-emulator tools: alsactl,alsamixer,amixer
  Server-1: PipeWire v: 0.3.84 status: active with: 1: pipewire-pulse
    status: active 2: wireplumber status: active 3: pipewire-alsa type: plugin
    4: pw-jack type: plugin tools: pactl,pw-cat,pw-cli,wpctl

**Comment by glaubersm** [comment]
On my Arch Linux with Gnome and Audacity 3.4.1 a coredump occurs when Audacity is clsoed.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444) which uses a different build system. This bug should no longer be applicable.
