### ISSUE TITLE
Timer Record automatic export defaults to mono when project is set to record in stereo

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#5580]
### Bug description
Timer Record automatic export defaults to mono when project even if the user has their project set to record in stereo, which is the Audacity default setting.

This is a regression on 3.3.3 introduced in 3.4.0

### Steps to reproduce
1. in Audio Setup ensure Audacity is set to stereo
2. Transport > Recording > Timer record
3. click in the **Enable Automatic Export** box
4. click on the Automatic Export **Select** button
5. Observe:  the export is set to default to mono

### Expected behavior
When the project is set to 2-channel stereo then the default Automatic Export in Timer Record should be stereo

When the project is set to 1-channel mono then the default Automatic Export in Timer Record should be mono

### Actual behavior
![image](https://github.com/audacity/audacity/assets/50205984/3d8af594-6bf8-461e-b7c4-a0e03b81234b)

### Audacity Version
3.4.1 and 3.4.2 latest Beta

### Operating system
Windows 10 - but assume all OS

### Additional context
Originally reported on the Forum:  
https://forum.audacityteam.org/t/save-to-mp3-defaults-monoral/89484

**Comment by petersampsonaudacity** [comment]
Fortunately the workaround is simple.

_**BUT**_ it does require the user to be observant and take action ELSE they may lose valuable stereo data if they mistakenly export the file as mono and then delete the project.

**Comment by fory-horio** [comment]
FYI, I just exported to mp3 this morning thinking that it was "stereo", but was not. I had to redo all of the work, wasted all most 2 hours.

**Comment by petersampsonaudacity** [comment]
@LWinterberg  @dozzzzer 

note that this is particularly egregious if you just accept the default folder offered in the automatic export dilalog and just press **OK** to effect the setting up of the export.
![image](https://github.com/audacity/audacity/assets/50205984/7ca318d6-d5e6-438b-881a-5ffa484db33d)


It is **ONLY** if you press the **Select** button that you get the dialog showing that the export will be mono
![image](https://github.com/audacity/audacity/assets/50205984/7757b7ce-6a7d-4904-818d-0f60b82299c1)

_On that basis I believe that this deserves a higher rating than P4_

**Comment by DavidBailes** [comment]
@petersampsonaudacity . I've submitted a fix for this: https://github.com/audacity/audacity/pull/5802

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @DavidBailes ' branch for this:  audacity-win-3.5.0-alpha-20231219+2e17667-x64

This now works properly in David's branch, exporting with the correct number of channels the user has set to record to before setting up the Timer Recording.

Works properly either if the user examines the deeper dialog:
![image](https://github.com/audacity/audacity/assets/50205984/260f01a3-cb71-4b84-bac1-a5551626d19a)

Or just uses the **OK** button without drilling down with the **Select**
![image](https://github.com/audacity/audacity/assets/50205984/323d3faa-049d-4367-9653-8b0d83919d2d)

Thanks for that Fix @DavidBailes

**Comment by fory-horio** [comment]
Does the "Export Audio" => "Browse" button work? It does not show a file listing on my Macbook pro.

**Comment by petersampsonaudacity** [comment]
> Does the "Export Audio" => "Browse" button work? It does not show a file listing on my Macbook pro.

The Browse button is no intended to show files - just folders (the location for the file to be exported to)

**Comment by petersampsonaudacity** [comment]
testing on W10 with 3.4.2

Works fine on Windows
![image](https://github.com/audacity/audacity/assets/50205984/ebce3c3f-0f86-4350-a64c-68babd6de09b)
=>
![image](https://github.com/audacity/audacity/assets/50205984/679fc2ca-df52-4409-a71f-a9d386dd92c6)

**Comment by dozzzzer** [comment]
Tested
