### ISSUE TITLE
Audacity recorded audio is slightly shorter than real life

### ISSUE THREAD

**Issue by VandalPaulius** [audacity/audacity#559]
**Describe the bug**
Audacity recorded audio is slightly shorter than real life, noticable only when trying to sync audio with other record sources such as external camera footage (+ audio)

**To Reproduce**
1. Record audio (10+ minute clip to increase effect) with Audacity (and possibly via USB audio interface)
2. Record same audio with OBS Studio or any other recording software or hardware (can be external camera, phone, etc)
3. Export Audacity record to `wav` or `mp3` format
4. Align audio from Audacity and other source in any software (in my case it was Davinci Resolve 16.2)
5. Zoom in different locations in and notice what Audacity record is slightly shorter. This is especially noticable if you're trying to sync audio with Resolves "Auto sync" feature

**Expected behavior**
Audio to be it's real length

**Additional information (please complete the following information):**
 - OS: Windows 10 Pro
 - Version: Audacity 2.4.1
 - Recording device: USB audio interface - Behringer U-Phoria UMC2020HD 192kHz

**Additional context**
I have tried different records with camera and OBS Studio, tried different sampling and bitrates in Audacity and same behaviour persists.

**Comment by SteveDaulton** [comment]
There are many possible reasons why this could be happening. Please post to our support forum and we will be happy to try and help. The support forum is here: https://forum.audacityteam.org

**Comment by VandalPaulius** [comment]
I didn't realise it might be configuration issue.
Will ask help on the forum. Thank you

**Comment by JamesCrook** [comment]
Support issue moved to forum.
