### ISSUE TITLE
VST plugin (GSnap) isn't found by Audacity Flatpak

### ISSUE THREAD

**Issue by rcsilva83** [audacity/audacity#5590]
### Bug description

I copied `GSnap.so` file to `~/.vst` folder but the Plugin Manager don't add it to the list.

### Steps to reproduce

1. Downloaded the 64 bits Linux plugin from https://www.gvst.co.uk/gsnap.htm?pageview=selectos
2. Unzipped and copied the `GSnap.so` file to the `~/.vst` folder
3. Opened Plugin Manager on Audacity Flatpak
4. Click "Rescan"
5. Gsnap doesn't show up

### Expected behavior

Gsnap should show up on Plugin Manager list

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

**Comment by crsib** [comment]
Flatpak is community-managed, we do not build it or provide it to flathub

**Comment by crsib** [comment]
I have verified an GSnap works correctly with AppImage

**Comment by xmready** [comment]
> Flatpak is community-managed, we do not build it or provide it to flathub

@crsib Why wouldn't Audacity verify themselves on flathub and provide an officially maintained flatpak?
