### ISSUE TITLE
Simple Copy Paste to Track Below Fails

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#5593]
### Bug description

Forum user "mafg1953" reported a failure in Copy- Paste operation here: https://forum.audacityteam.org/t/copying-audio-from-one-track-to-the-track-below/89742

### Steps to reproduce

0) Tools > Reset Configuration
1) Generate > DTMF
2) Tracks > Add Mono
3) Select region in center of track 1 (DTMF)
4) Ctrl+I (Split)
5) Click on center clip's grab handle
6) Ctrl+C (Copy)
7) Shift-Down Arrow to 2nd track
8) Ctrl+P (Paste)

### Expected behavior

Clip in question should be copied to 2nd track,

### Actual behavior

Nothing happens. (Clips is NOT copied)

![image](https://github.com/audacity/audacity/assets/76828213/586f9567-5edf-45c2-a8c0-8a7b8ef74f70)

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

Also tested on 3.4.2 Beta: Commit Id:30cc55 of Fri Nov 10 17:51:46 2023 +0100

Regression on 3.3.3

**Comment by LWinterberg** [comment]
Same as #5594 - the first track is selected so the content is pasted into the first track first.
