### ISSUE TITLE
3.4.1 Paste Into Multiple Tracks Fails

### ISSUE THREAD

**Issue by JohnColket** [audacity/audacity#5594]
### Bug description

Forum user "Paul357" reports that he is unable to Pasting clips to multiple tracks at the same time: https://forum.audacityteam.org/t/pasting-clips-to-multiple-tracks-at-the-same-time/89747

### Steps to reproduce

0) Tools > Reset Configuration
1) Generate > Chirp
2) Tracks > Add Mono
3) Tracks > Add Mono
4) Select Track 1
5) Ctrl+C (Copy)
6) Click anywhere in Track 2
7) Shift-Downarrow to extend the selection point to track 3
8) Ctrl+V (Paste)

### Expected behavior

Track 1 gets copied to selection point in both Track 2 and Track 3.

### Actual behavior

![image](https://github.com/audacity/audacity/assets/76828213/e12bfb57-50cd-4375-b386-d39ef45dc212)

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

Regression on 3.3.3

See also related issue: https://github.com/audacity/audacity/issues/5593

**Comment by LWinterberg** [comment]
Copying and pasting has been simplified for this release. When you copy something, a "stack" is created and when pasting, this stack is inserted into the selected tracks. When the stack runs out of content, any additional selected tracks are kept blank. In this case, the clip is pasted into Audio 2 (overwriting the content the selection in that track).

**Comment by Paul50-blip** [comment]
Ok, but what If I want to paste the clip from Audio 1 into Audio 2 and 3 simultaneously? I frequently do this to keep the tracks synced when inserting new clips.
