### ISSUE TITLE
Intermittent bug with Filter Curve EQ, Graphic EQ, and Nyquist effects applied to clip

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#5599]
### Bug description

When  applying Filter Curve EQ, Graphic EQ, or Nyquist effects to a clip with adjacent clips, the effect may fail with error:
"There is not enough room available to paste the selection"

Bug observed in Audacity 3.4.1 on Linux.

### Steps to reproduce

1. Download the small project "bug.aup3" from https://www.dropbox.com/scl/fi/ci3fncgys5tmgrr6ht2nk/bug.aup3?rlkey=5m4c94s133sfybmk0hae7mnuk&dl=0
2. Launch Audacity 3.4.1
3. Open the "bug.aup3" project
4. Apply "Filter Curve EQ" to the selection

### Expected behavior

Filter Curve EQ to be applied.

### Actual behavior

Error message: "There is not enough room available to paste the selection"

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

This may be the cause of some of the many reported failures with macros.

**Comment by SteveDaulton** [comment]
Also occurs in 3.4.0 Commit ID:#1cbb43

**Comment by SteveDaulton** [comment]
Also occurs in Audacity 3.5.0-alpha-20231113 commit id: #b236fe

**Comment by dozzzzer** [comment]
@SteveDaulton PR #5555 (not merged yet) fixes that for me
