### ISSUE TITLE
EQ in a macro fails when applied to files

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#5604]
### Bug description
When either EQ effect is used in a macro fails with an error message when applied to files - it works fine if you apply it to audio in a project.

This is a regression on 3.3.3 where the simple macro runs on files with no error message.

### Steps to reproduce
1. create a simple Macro with **Filter Curve EQ** in it (or **Graphic EQ**)
2. Apply it to files
3. Observe error message

_I tested further and added an **Export to WAV** command and no files or macro-output folder were created._

### Expected behavior
This macro should work with no error message

### Actual behavior
**Step 1**
![image](https://github.com/audacity/audacity/assets/50205984/a621533e-b5b1-4ab2-94e7-6b4f213515f9)

**Step 3**
![image](https://github.com/audacity/audacity/assets/50205984/1de460c3-169e-422e-8ab7-0f5efa7020bb)

### Audacity Version
3.4.1 and 3.4.2 latest Beta (in fact all 3.4.x)

### Operating system
Windows 10 - but assume all OS

### Additional context
Originally reported by a Forum user:
New bug in 3.4.1. Had to revert to 3.4.0
https://forum.audacityteam.org/t/new-bug-in-3-4-1-had-to-revert-to-3-4-0/89756

**Comment by dozzzzer** [comment]
Bisects to https://github.com/audacity/audacity/commit/618d61e50ce21f57e7046e943908d786385d4d36

**Comment by chinakov** [comment]
Tested. Thank you!
