### ISSUE TITLE
Presence checks for built-in modules

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#5609]
With modules being optional, it currently is possible to fuck up your install, especially when manually copypasting the files into a directory instead of using the installer. With modules being optional, this can result in you trying to export and seeing this:

![image](https://github.com/audacity/audacity/assets/87814144/18d9e65d-6eae-4b37-ada8-c5cdc84a9d97)

2 users have reported running into this in the forum: https://forum.audacityteam.org/t/format-option-missing/89780

As a solution, we may want to do something similar to FFmpeg being not found: When a module was previously used but can no longer be found, we show a message saying that the module(s) in question used to be there but no longer are, and that functionality may be impeded because of it. However, unlike FFmpeg we'd start out with the assumption that the module in question can be found initially.

**Comment by crsib** [comment]
Well, by missing some files, you can break Audacity into not launching at all :-)

The good question is if the modules were really missing, or do we have issues with module discovery

**Comment by LWinterberg** [comment]
> Well, by missing some files, you can break Audacity into not launching at all :-)

The main cause of that would be launching Audacity.exe directly from within a ZIP, which I'm sure happens often - but in that case you get an error that stuff is missing and no Audacity, and you figure out quite quickly that you need to unzip first. Modules are trickier because you can do ~everything without error, but then suddenly import/export appears non-functional.

I'll probe users into sharing their install before reinstalling (which has fixed it for people so far) to see if it was a discovery problem or an install problem

**Comment by LWinterberg** [comment]
closing in favor of #6448
