### ISSUE TITLE
plugin GUI not appearing in window for LSP plugins with latest wxWidgets

### ISSUE THREAD

**Issue by evertvorster** [audacity/audacity#5611]
### Bug description

I'm a little excited to see that Audacity is getting to be more compatible with the latest versions of wxWidgets. 

I was able to get a GUI from LSP plugins when compiling audacity and linking to the latest wxWidgets. So that is a massive step forward!

Unfortunately, the GUI is not bound to and does not appear within the window that pops up for the effect. 

Here is a screenshot:
![image](https://github.com/audacity/audacity/assets/12045269/14f7be79-247c-4618-b790-b71222dbffb4)

### Steps to reproduce

Build Audacity on Arch linux, but link to the latest system version of wxWidgets rather than the Conan version. 

Install LSP plugins. 

Record some audio, and apply one of the LSP effects on it. 

The window that pops up is empty, and the GUI for the effect pops up on its own somewhere else.

### Expected behavior

The gui for effects to be in the window. 

### Actual behavior

The Gui for the effect is not bound to, and does not appear inside the window for it. 

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

About my system:
```
Operating System: Arch Linux 
KDE Plasma Version: 5.27.9
KDE Frameworks Version: 5.112.0
Qt Version: 5.15.11
Kernel Version: 6.6.1-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 32 × 13th Gen Intel® Core™ i9-13900HX
Memory: 62.5 GiB of RAM
Graphics Processor: Mesa Intel® Graphics
Manufacturer: TUXEDO
Product Name: PD5x_7xSNC_SND_SNE
System Version: Not Applicable
```

**Comment by crsib** [comment]
Well, that's how Wayland works, and Audacity doesn't work well with Wayland anyway. Running with `GDK_BACKEND=x11 audacity` will fix that for you. I don't see us fixing Wayland support before we get to Qt, sorry. There are some massive (literally massive) changes that are needed to how Audacity paints itself to get decent Wayland support.

LSP uses OpenGL for UI, so it is not affected by how the wxWidgets build. I think, only Calf does, as it uses GTK2.

**Comment by evertvorster** [comment]
Fair enough, but on a side note it works really well with the Conan version of wxWidgets. Thanks for looking into it!

**Comment by evertvorster** [comment]
> Well, that's how Wayland works, and Audacity doesn't work well with Wayland anyway. Running with `GDK_BACKEND=x11 audacity` will fix that for you. I don't see us fixing Wayland support before we get to Qt, sorry. There are some massive (literally massive) changes that are needed to how Audacity paints itself to get decent Wayland support.
> 
> LSP uses OpenGL for UI, so it is not affected by how the wxWidgets build. I think, only Calf does, as it uses GTK2.

Calf has had it's latest release in 2019, a full four years ago. In the git repo, six commits have been made since then, so it's safe to assume that it's a stagnant project. 

For me, all I require is an equalizer that has a graphical user interface and supports setting the width of a filter, which I get with an Audacity + LSP plugins at the moment. 

Wayland has been my daily driver for a few months now, and for the most part it works really well. 

With the Conan version of wxWidgets and portmidi, Audacity + LSP plugins work flawlessly under pure Wayland, so saying that Audacity does not work well under Wayland is not agreeing with my experience. 

Saying all that, I do keep an eye on the development of Audacity, and I too look forward to the day where we don't have to pull in ancient copies of libraries that I have in the system already just to have one application work properly. 

But, as you say, it's an immense amount of work to fix, and since its based on a library that you are planning to move away from, I can see that it does not make much sense to waste the effort on fixing that part now.

However, Wayland is here to stay, so I'll keep providing feedback on Wayland issues as they pop up.

**Comment by crsib** [comment]
> Audacity + LSP plugins work flawlessly under pure Wayland

I know for sure that the cursor doesn't move

**Comment by evertvorster** [comment]
On my pure Wayland system the cursor moves without issue:

https://github.com/audacity/audacity/assets/12045269/4488b5a2-a3b8-4aac-abbb-40bde4d7acfc

**Comment by crsib** [comment]
Hmm, that's ... new

**Comment by evertvorster** [comment]
In this version, the only packages I have installed from Conan is wxWidgets and portmidi, as I need Conan for the wxWidgets, and then Conan does not detect the system version of portmidi.
Apart from those small issues, it runs really great.
