### ISSUE TITLE
GetInfo yields each row of the JSON in a separate dialog

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5615]
### Steps to reproduce

1. Have a track
2. Extra > GetInfo: Tracks
3. Observe

### Expected behavior

The entire JSON is printed in a single dialog:

<img width="450" alt="Screenshot 2023-11-14 at 15 07 58" src="https://github.com/audacity/audacity/assets/70063970/b3d17a12-0e51-4ed5-9ace-4745b58f104e">

### Actual behavior

Each row of the output JSON is printed in a separate dialog:

https://github.com/audacity/audacity/assets/70063970/16eddad5-3288-4595-b52d-910773b1d8b2

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

**Comment by Paul-Licameli** [comment]
I think the problem will not be unique to Track information.

If I delete these lines:
```
static CommandContext::TargetFactory::SubstituteInUnique<
   InteractiveOutputTargets
> scope;
```

from `wxCommandTargets.cpp` then the problem reproduces on a macOS build.

**Comment by Paul-Licameli** [comment]
I am guessing the Microsoft compiler erroneously optimizes away the construction of the static object.

Other uses of `SubstituteInUnique` exist to inject UI handling logic for the realtime effect families, but none of them are known to have the same problem.

The difference in those cases is that the `static` object is not also (redundantly) inside an anonymous namespace, as in this case.

**Comment by dozzzzer** [comment]
The issue remains unfixed. @Paul-Licameli

**Comment by crsib** [comment]
I guess I will have to take a look then

**Comment by Paul-Licameli** [comment]
> I guess I will have to take a look then

Should the issue be reassigned to you?

**Comment by crsib** [comment]
Yes

**Comment by Paul-Licameli** [comment]
> Yes

It's weird, isn't it.  `SubstituteInUnique` is used elsewhere with no problem.

Maybe for some ridiculous reason, it works only when the `scope` object is the last definition in the file.  Who knows.

**Comment by crsib** [comment]
But it seems that the problem is different, as your fix has not worked.

**Comment by Paul-Licameli** [comment]
Oh, here's the problem:

```
   struct Factory : DefaultedGlobalHook<Factory,
      Callable::SharedPtrFactory<CommandManager, AudacityProject &>::Function
   >{};
```

That should be MENUS_API

**Comment by dozzzzer** [comment]
Tested
