### ISSUE TITLE
After installing FFmpeg, restart is needed in order to export some file formats

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5625]
### Steps to reproduce

1. Uninstall previous FFmpeg installations (if any)
2. Launch Audacity
3. Make sure FFmpeg version isn't detected in Audacity in _Preferences > Library_
4. `sudo apt install ffmpeg lame` 
5. In Audacity, make sure FFmpeg is detected correctly in _Preferences > Library_
6. Grab some audio
7. File > Export Audio
8. Select M4A format and click Export

### Expected behavior

Success

### Actual behavior

"Unable to export" error; 
Audacity needs to be restarted in order to export.

![image](https://github.com/audacity/audacity/assets/70063970/7f63e84f-f2dc-4643-939a-283057e71d3c)

### Audacity Version

current release-3.4.2 branch

### Operating system

Ubuntu 22.04

**Comment by LWinterberg** [comment]
I added a line for this in the error page. Given that a restart fixes it, I don't think any further action is required
