### ISSUE TITLE
Split lines causes gap in audio

### ISSUE THREAD

**Issue by joeessayvoice** [audacity/audacity#5630]
### Bug description

When splitting a line in audacity, it puts a small portion of empty audio between the two tracks, and you cannot get them to butt up 100% next to each other. This appears to be causing unwanted artifacts as you listen to the audio. (Clicks/pops etc...)

### Steps to reproduce

1. Create a track with audio on it
2. Use the command+I in order to split the track
3. Zoom in and observe

### Expected behavior

The tracks should be split, but perfectly next to each other.

### Actual behavior

The Tracks are split, but separated by an area of no waveform, and you cannot move them closer to eachother.

https://github.com/audacity/audacity/assets/146398802/344792d1-f00f-4b68-90d2-742dd0c9ced6

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

**Comment by LWinterberg** [comment]
This is just the way clip rendering works right now. As you can see, the samples are as close as they are within both clips.
