### ISSUE TITLE
Clicking Share Audio button after project recovery won't open up the dialog

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5634]
### Steps to reproduce

1. grab some audio
2. crash or force quit Audacity
3. launch Audacity
4. in the project recovery dialog, click "recover selected"
5. click Share Audio button

### Expected behavior

Share Audio dialog pops up

### Actual behavior

Nothing

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS

### Additional context

Bisects to https://github.com/audacity/audacity/commit/b23c56cd35aa9a51742fd7f30f35c4f72e146a11

**Comment by petersampsonaudacity** [comment]
@dozzzzer   Works for me on W10 with 3.4.2 beta

**Comment by dozzzzer** [comment]
> @dozzzzer Works for me on W10 with 3.4.2 beta

The issue's present in the master branch only.

**Comment by Paul-Licameli** [comment]
My first attempt to reproduce this on macOS at 86a6b6df892751a908280c054ac59afdb8425f62 -- I could not.

**Comment by dozzzzer** [comment]
Tested
