### ISSUE TITLE
Update/changelog window may exceed screen bounds and then be impossible to dismiss

### ISSUE THREAD

**Issue by jamshark70** [audacity/audacity#5637]
### Bug description

Note in the screenshot that the bottom of the updates window (where the buttons are) is offscreen.

![audacity-bad-update-window](https://github.com/audacity/audacity/assets/318301/8a1460f7-f8fe-4cb7-8e4e-e16d7530332e)

At this point, tab-selection of buttons seems inoperative (I tried tab-space, tab-space a few times, and was unsuccessful in dismissing the window). Also the changelog window does not allow resizing (?). Had I been able to resize it, then I wouldn't have had to log an issue -- just resize, "OK" and done. Buuuuut... no dice.

I had no choice but to force-kill Audacity and use other software in this class session.

### Steps to reproduce

Launch the software when updates are pending. (However the problem doesn't reproduce unless the changelog is rather long, and your screen resolution settings aren't very deep, e.g. 900 pixels high.)

### Expected behavior

Windows opened by the software should always be navigable: completely visible onscreen, or if too large, at least possible to resize and bring onscreen.

### Actual behavior

Un-dismissable and un-resizable modal window covering Audacity's workspace, rendering the software unusable until updating.

### Audacity Version

other

### Operating system

Linux

### Additional context

Audacity 3.3.3. I *will* update soon but didn't have time to do that when in the middle of a classroom demo.

**Comment by dozzzzer** [comment]
I was able to reproduce the issue on Fedora 39.
