### ISSUE TITLE
Custom FFmpeg export utilises wrong codec

### ISSUE THREAD

**Issue by jadasse** [audacity/audacity#5638]
### Bug description

Whenever I export audio with Custom FFmpeg export, it ignores my format options and exports into 192 kbps AC-3 instead.

### Steps to reproduce

1. Go to File
2. Click on Export Audio
3. Choose Custom FFmpeg Export
4. It automatically exports to a 192 kbps AC-3 audio file if it doesn't give an error message.

### Expected behavior

It should export to what I requested in the format options like in pre-3.4.0 Audacity.

### Actual behavior

It exports to 192 kbps AC-3 instead.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by dozzzzer** [comment]
It seems that the problem concerns many other formats. For instance, when exporting to DTS, the output file's codec is Vorbis:
<img width="400" alt="Screenshot 2023-11-17 at 12 41 53" src="https://github.com/audacity/audacity/assets/70063970/b81d02d9-0447-4fab-a08d-9c773a1c98ea">

<img width="400" alt="Screenshot 2023-11-17 at 12 40 42" src="https://github.com/audacity/audacity/assets/70063970/f66c046c-9ac3-4184-a4ec-37ae131ffcd2">

Moreover, the output file is much shorter in length than it should be (~3 seconds vs 30 seconds) and has unwanted clicks at the beginning: https://www.dropbox.com/scl/fi/s2mkmmu9ckoh5jdbd7dgu/untitled.dts?rlkey=ba5b5dwl52dpriewqrb3zua0o&dl=0
