### ISSUE TITLE
DSP-based global tempo detection

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#5640]
Extend Music-Information-Retrieval capabilities introduced by #5548 with DSP inspection of the signal.

This is planned to be used as fallback attempt if no music information is present in the imported audio title or file header.

Scope is only to expose a global tempo detection, if any, for use during file import. Onset and beat detection may be addressed in a follow-up ticket if not already a side product of the global tempo estimation.

**Comment by dozzzzer** [comment]
tested
