### ISSUE TITLE
Remove WaveTrack::SetWaveColorIndex

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#5652]
Rather than rewriting this one as interval-major, better to remove completely from lib-wave-track, any mention of extraneous display related things.

Some surprisingly roundabout solutions are needed with attached objects on WaveTrack and WaveClip, but they may prove useful in future to attach other extra information to tracks and clips non-intrusively.

**Comment by chinakov** [comment]
There is one last issue persistent in this MR, putting the task back to 'In Progress'. 

Thanks! 
![image](https://github.com/audacity/audacity/assets/139755141/4a1b28f7-17a5-402f-bff0-4db7b4054e44)
