### ISSUE TITLE
Auto Expand device name based on name length

### ISSUE THREAD

**Issue by Arryboom** [audacity/audacity#5657]
### Your idea

![image](https://github.com/audacity/audacity/assets/28295452/75c71ace-2b67-4b09-b9c5-70284ef66280)

as you can see in the picture when the playback/recording device got a long name,it will not auto expand,sometimes makes the device hard to recognize

### Problem to be solved

Auto expand device name when needed

**Comment by petersampsonaudacity** [comment]
Testing on W10 with 3.4.2

I cannot replicate this on Windows - expands nicely for me:
![image](https://github.com/audacity/audacity/assets/50205984/e9fad397-0666-433d-ae27-e2900be6f081)

**Comment by LWinterberg** [comment]
When using MME, the device length is limited to 31 characters. That's just the nature of an API from the Windows 3.x days. 

On an unrelated note, the media coverage of MME being introduced is absolutely beautiful: https://books.google.com/books?id=2j0EAAAAMBAJ&lpg=PA1&pg=PA90#v=onepage&q&f=false

**Comment by Arryboom** [comment]
Thanks,change MME to WASAPI sovled the problem for sure
