### ISSUE TITLE
Track name is replaced by random text on drag & drop (and sometimes on audio insert)

### ISSUE THREAD

**Issue by HilaManor** [audacity/audacity#5667]
### Bug description

Dragging and dropping audio tracks beyond the first drag and dropped track removes the name and replaces it with XXYYYY~Z
where XX is the first 2 letters of the original track, then there are 4 random letters Y and Z is a random number (usually 1 it seems).
The behavior sometimes is also the same when using "Insert tracks" (Ctrl Shift I), but sometimes it leaves the original track name.

![image](https://github.com/audacity/audacity/assets/53814901/15b3e2ae-b852-4317-bc1c-5039b6917e37)

### Steps to reproduce

1. Open audacity
2. Drag and drop a file
3. drag and drop multiple files 

### Expected behavior

Before upgrading versions it would leave the original name 

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

**Comment by dozzzzer** [comment]
I can't reproduce it in 3.4.2 on my machines: macOS 14 / Windows 11

**Comment by HilaManor** [comment]
It sometimes doesn't happen; I can't seem to catch how to reproduce it all the time.
In any case, I'm using 3.4.2 on Windows 10 (version 22H2)

**Comment by chinakov** [comment]
I also can't reproduce this.

**Comment by Paul-Licameli** [comment]
Does this depend on the type of file system of the drive?

**Comment by HilaManor** [comment]
It's just a .wav file saved on a normal SSD NTFS drive :/
