### ISSUE TITLE
Compressor produces corrupted audio when blank space is selected ahead of the audio

### ISSUE THREAD

**Issue by JamzTyson** [audacity/audacity#5670]
### Bug description

The output from Audacity's compressor effect may be weirdly wrong.Tested on Linux.

### Steps to reproduce

1. Download this small project: https://www.dropbox.com/scl/fi/0otz4p63lemw3ugxp5fgh/compressor-bug.aup3?rlkey=5e9f32z5xvq8jui6rp233vepc&dl=0
2. Launch Audacity 3.4.2 and open the project
3. Apply Audacity's compressor effect with default settings.

### Simple steps to reproduce
1. generate a 30 second tone starting at 15 seconds
2. silence it from 7 to 30 seconds
3. select from 5 seconds to the end of the clip
4. Effect >Compressor
5. Observe:  the result is corrupt.

**Step 3**
<img width=450 src=https://github.com/audacity/audacity/assets/50205984/fec917b9-fb44-4823-b121-2f03da08c9b2>

**Step 5**
<img width=450 src=https://github.com/audacity/audacity/assets/50205984/b3f2c338-7ce5-4993-9293-3d04f55c275c>

### Expected behavior

<img width="450" alt="Screenshot 2023-11-23 at 13 03 00" src="https://github.com/audacity/audacity/assets/70063970/bba0e6b6-f36f-46b3-b808-38613ac45025">

### Actual behavior

<img width=450 src=https://github.com/audacity/audacity/assets/151654652/54bb3b3f-6669-471a-8593-9bda4a022b74>

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Linux, Windows

**Comment by petersampsonaudacity** [comment]
Testing on W10 with 3.4.2

I cannot replicate this with a very similar looking project.  What I get after applying Compressor with default settings is:

![image](https://github.com/audacity/audacity/assets/50205984/fe178546-e4a6-4762-8657-3d5095359622)

I have not tested yet with  @JamzTyson 's project - but the inference is that there ,may be something odd about that project.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with 3.4.2

Using @JamzTyson 's project I not that unlike mine above the audio starts at c.14 seconds and the selection includes not just the audio but also blank space from c. 2-14 seconds.
![image](https://github.com/audacity/audacity/assets/50205984/011a22c4-eeb8-4b1d-83de-1edddfe03e52)

When I apply Compressot that that selection ten I get the same  result as @JamzTyson 
![image](https://github.com/audacity/audacity/assets/50205984/4abeaf1e-9407-41f0-9b65-feb1fb08bd07)


HOWEVER,, if I Undo and then select just the audio clip and then apply the compressor I get the properly expected result:
![image](https://github.com/audacity/audacity/assets/50205984/0a32f478-c04d-4701-834d-cd8b1c3d7125)

**Comment by petersampsonaudacity** [comment]
Further testing shows that if I use my simple project above but with the audio starting at 14 seconds

a) If I select blank space **before** the audio as well as the audio - then the Compressor result is **corrupt**

a) If I select blank space **after** the audio as well as the audio - then the Compressor result is **correct**

**Comment by DavidBailes** [comment]
https://github.com/audacity/audacity/issues/3903 looks like it could be the same or related bug, but with different steps to reproduce.

**Comment by petersampsonaudacity** [comment]
This is a regression on 2.4.2 further testing shows

**Comment by DavidBailes** [comment]
I've submitted a PR to fix this. There is an existing problem that if part of the selected audio in the track is before time zero, then the result is incorrect, and this fix does not address that problem. This fix improves the behaviour of the compressor, but I'm sure there's a better fix which addresses all the problems.

**Comment by dozzzzer** [comment]
Tested
