### ISSUE TITLE
(Linux) CALF plugin suite GUI missing

### ISSUE THREAD

**Issue by algreen702021** [audacity/audacity#5682]
### Plugin

Calf suite

### Plugin Format

LV2

### Plugin source

https://calf-studio-gear.org/#install

### Ubuntu 22, Audacity 3.41 installed recent Calf plugins 
_original GUI_ missing, DAW displaying grey style graphics.
Any clue please?
regards
Al

![Schermata del 2023-11-22 07-33-40](https://github.com/audacity/audacity/assets/82070251/8f58317c-1ed4-42b4-a9eb-9acf6f40e460)

### Steps to reproduce

Menu: **effects/realtime effects/add effects/Calf studio gear/**        selecting any effects get same visual results

### Expected behavior

original Calf GUI 
![96cee1c895bd58091be7ee1290a0406eda51574d](https://github.com/audacity/audacity/assets/82070251/a9918a32-8d9a-4cee-90b3-904e7a61d6b0)

### Actual behavior

Grey panel instead of genuine GUI.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Linux

### Architecture

64 bit Intel/AMD processors

### Additional context

**Downloaded from:** 
[](git clone https://github.com/calf-studio-gear/calf.git)
 
**install procedure:** 

`cd calf
./autogen.sh
make -j2
make install`

**Comment by dozzzzer** [comment]
@algreen702021 Please make sure that the Graphical Interface is enabled for this particular plugin: _Presets & Settings > Options > Enable graphical interface:_

<img width="668" alt="Screenshot 2023-11-27 at 10 22 37" src="https://github.com/audacity/audacity/assets/70063970/f6c1cd2f-3037-422f-9e7d-95170966cdf7">

**Comment by crsib** [comment]
If you use Audacity from `apt` - Calf GUI won't work. Calf uses GTK2, `apt` Audacity uses GTK3. It is impossible to mix GTK2 and GTK3 in the same process.

**Comment by dozzzzer** [comment]
Closing the issue due to the incompatibility of the GTK version used in Audacity and the CALF plugins.
