### ISSUE TITLE
Scrub Ruler Widget is now white not green - and tooltip fails to appear

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#5683]
### Bug description
The Scrub Ruler Widget is now white and not green - the green color-coding is designed to indicate a playback mode.
See image from the Manual below

The Tooltip fails to appear until you click on the widget.

Both are regressions on 3.0.5 - but note that in 3.1.0 to 3.1.2 the widget did not appear at all 

### Steps to reproduce
1. Transport > Scrubbing > Scrub Ruler  -  to enable the Scrub Ruler
2. get some audio
3. Hover your cursor in the Scrub Ruler
4. Observe: the Scrub widget is white and not green
5. Continue to hover over the widget
6. Observe: NO tooltip appears
7. Click ob the widget
8. Observe> now the tooltip does appear

### Expected behavior
![image](https://github.com/audacity/audacity/assets/50205984/1bd81d79-8a6a-4c94-a6fd-da40271be594)

### Actual behavior
![image](https://github.com/audacity/audacity/assets/50205984/3be34938-1201-4fa6-b648-8196d80fc8eb)

### Audacity Version
3.4.2

### Operating system
Windows 10 - but assume all OS

### Additional context
None

**Comment by petersampsonaudacity** [comment]
This also affects scrubbing without the Scrub Ruler being displayed _(either from the Transport>Scrubbing menu or the Scrub toolbar)_  - the scrub widget in the Timeline in this case is also white and not green.

![image](https://github.com/audacity/audacity/assets/50205984/580f9a83-c41d-4d6a-8687-cd2ed87b6613)

Note that the white of the widget is inconsistent with the green icon in the Scrub toolbar.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
