### ISSUE TITLE
Win32 build has unresolved external __std_init_once_link_alternate_names_and_abort@0

### ISSUE THREAD

**Issue by RockySong** [audacity/audacity#5686]
### Bug description

Unresolved external 
**__std_init_once_link_alternate_names_and_abort@0,** 
which is referred by 
public: __thiscall std::_Init_once_completer::~_Init_once_completer(void) (??1_Init_once_completer@std@@QAE@XZ)

### Steps to reproduce

Just follow "BUILDING.md" without changing any options, selecting WIN32, CMake version was 3.27.8

### Expected behavior

Successful build.

### Actual behavior

Build failure

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by RockySong** [comment]
It happens when building base.lib(fdebug.obj)

**Comment by crsib** [comment]
You are likely dealing with the bug in MSVC 17.2: https://developercommunity.visualstudio.com/t/__imp___std_init_once_complete-unresolve/1684365

We cannot reproduce this issue locally or on CI

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444) which uses a different build system. This bug should no longer be applicable.
