### ISSUE TITLE
Track Control Panel misbehaves on hover

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5688]
### Steps to reproduce

1. Add a track
2. Deselect the track
3. Hover over the Select button
4. Move the cursor away

### Expected behavior

When on hover, the Select button gets highlighted, when the cursor is moved away – it doesn't.

### Actual behavior

When on hover, both the Select and the TCP header get highlighted, when the cursor is moved away – both remain highlighted.

https://github.com/audacity/audacity/assets/70063970/cbe5d9c6-240f-4843-b043-a57e7f8596a2

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS

**Comment by dozzzzer** [comment]
Possibly related https://github.com/audacity/audacity/issues/5689

**Comment by chinakov** [comment]
This is 'fixed' by the removal of the 'Select' button in TCP - https://github.com/audacity/audacity/pull/6308
