### ISSUE TITLE
Easy channel iteration rewrites, part 1

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#5691]
An arbitrary-looking subset of the subtasks in #5065, which for various reasons are unblocked now without sequential dependencies on other tasks.

Certain of the other "easy" ones may need to wait on "hard" ones first.

This list might easily grow or shrink or be subdivided if that aids faster review and testing.

  - MoveTo
  - GetSequenceSamplesCount
  - CountBlocks
  - ConvertToSampleFormat
  - Silence
  - Flush (no outer loop, it applies only to one Interval)
  - CloseLock
  - WidestEffectiveFormat
  - RemoveCutLine
  - Resample

**Comment by chinakov** [comment]
Tested, thank you Paul!
