### ISSUE TITLE
View Toolbars does not facilitate multiple settings

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#5694]
### Bug description
View Toolbars does not facilitate multiple settings - it's a one-shot command, the dialog disappears as soon as the user makes just one change so multiple changes cannot be effected in one go.

### Steps to reproduce
1. View >Toolbars
2. make one change
3. Observe: the dialog disappears immediately

### Expected behavior
In response to View > Toolbars the following (or similar) dialog apperas allowing the user to make more than one change and then press the **OK** button.
![image](https://github.com/audacity/audacity/assets/50205984/ea6f030a-136f-4ffd-b8cf-2704a0e91816)

### Actual behavior
![image](https://github.com/audacity/audacity/assets/50205984/b16937f1-0a8f-4181-833f-1dba1e6fa992)

Only one change to the toolbars can be made at a time - once the user makes a change the dialog immediately disapperas, forcing the user to make multiple uses of **View > Toolbars** to make multiple changes

### Audacity Version
3.4.2 and 3.5.0 alpha - in fact all previous Audacity versions

### Operating system
Windows 10 - but assume all Os

### Additional context
This ENH was prompted by this recent thread on the Forum:
**Quicky way to hide all toobars?**
https://forum.audacityteam.org/t/quicky-way-to-hide-all-toobars/91155

Tagging @LWinterberg and @Tantacrul  as a UX/Design issue

**Comment by SteveDaulton** [comment]
On Linux it is possible to set / unset multiple options by using spacebar to tick / un-tick rather than a mouse click.
I've not tested on other platforms.

**Comment by LWinterberg** [comment]
This is already fixed in Qt.

https://github.com/audacity/audacity/assets/87814144/eac81dd7-64c7-495f-af3e-d8512bd45ba9
