### ISSUE TITLE
Playback/Recording meter scales are absent

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5699]
### Steps to reproduce

1. Launch Audacity
2. Look at the Playback/Recording meters

### Expected behavior

Playback/Recording meters as usual.

### Actual behavior

<img width="400" alt="Screenshot 2023-11-27 at 16 30 16" src="https://github.com/audacity/audacity/assets/70063970/b17b66e6-4bdd-459f-9027-74ab7567803c">

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS 14.2

### Additional context

 Not a regression, since older releases also have such a problem.

**Comment by chinakov** [comment]
We should check this prior to 3.5 release.

**Comment by dozzzzer** [comment]
Please check in the macOS 14.3 Beta 1 @chinakov

**Comment by chinakov** [comment]
@dozzzzer - Cannot reproduce this issue on macOS 14.3 Beta (23D5051b). Seems like Apple have fixed it.

**Comment by LWinterberg** [comment]
Alrighty, this doesn't need any action on our side then. 

For anyone else stumbling upon this bug: This bug only affects macOS 14.2, so running either 
* macOS 14.1 and earlier 
*  \- or - 
* 14.3 or later 

fixes it
