### ISSUE TITLE
Easy channel iteration rewrites, Part 2

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#5708]
Depends on
- #5691

Will rewrite
- HasHiddenData
- DiscardTrimmed
- VisitBlocks
- smartClipsExtension
- stretchedClipsExtension

QA: Test with mono and stereo tracks:
- [x] Again, cross-document copy-paste with hidden clip data; be sure to try the "Discard" option
- [x] Observe space usage estimates in View > History non-modal dialog don't change when repeating same edits in branch and in master; including examples with large data hidden in cutlines
- [x] A project saved with any smart clips is still not openable in Audacity versions before 3.1
- [x] A project saved with any stretched clips is still not openable in Audacity versions before 3.4

**Comment by chinakov** [comment]
New issue found - if a User tries to perform these 2 operations, observed in the checklist:

- A project saved with any smart clips is still not openable in Audacity versions before 3.1
The User will be presented with an incorrect 'Audacity failed to read from a file in C:.' File Error message. 
![easy channel rewrites](https://github.com/audacity/audacity/assets/139755141/cf495068-1a0b-4da8-b60f-648727669bb4)

Here's how it looks on 3.4.2 for the same scenario:
![3 4 2](https://github.com/audacity/audacity/assets/139755141/6c028367-32d2-4ad7-b537-8f063eb7f5a8)

- A project saved with any stretched clips is still not openable in Audacity versions before 3.4
The User will be presented with an incorrect 'Audacity failed to read from a file in C:.' File Error message.
![easy channel rewrites (2)](https://github.com/audacity/audacity/assets/139755141/5123fde9-a978-49f0-bcc1-97cc872a2c71)

Here's how it looks on 3.4.2 for the same scenario:
![3 4 2 (2)](https://github.com/audacity/audacity/assets/139755141/56cc3304-dd18-4233-89c3-ca7481fc117b)

**Comment by Paul-Licameli** [comment]
I have force-pushed a rebase onto the updated base branch, which required only a little conflict resolution.

I tried to reproduce the problem.  So far, I made a project with one mono track and some hidden data on the left end.  I saved, exited, and started 3.0.5.  I opened the project and got the correct error message.

**Comment by Paul-Licameli** [comment]
I repeated but with a stereo track, and now I do see the changed behavior you described.
