### ISSUE TITLE
A couple improvements to the Effects workflow

### ISSUE THREAD

**Issue by alexandervrs** [audacity/audacity#571]
When applying an audio Effect it always frustrates me to:

**1.** Have to manually Ctrl+A to select the entire audio if I want to apply an effect to the entire audio duration, but I have nothing selected at the moment
**2.** Apply and then Close the dialog, 2 clicks for no reason, sometimes you might click the wrong button and have to reopen the dialog to do them again

Audacity should:

**1.** Be smart enough to realize that I need the effect applied to the entire audio track/file if I have nothing selected prior
**2.** The Effect dialogs should have an **Apply & Close** button as well to avoid the extra click every time. Might not look as much but the work adds up when you have to bulk edit lots of sounds

**Comment by SteveDaulton** [comment]
Audacity has an option in Preferences: "Select all audio, if selection required:"
See: https://manual.audacityteam.org/man/tracks_behaviors_preferences.html

**Comment by alexandervrs** [comment]
This solves the selection issue, thanks. I added a separate issue for the OK/Apply button
