### ISSUE TITLE
Cleanup tasks

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#5710]
Small tasks which aim to a) simplify the app, b) simplify the code and c) simplify some messaging.

## removals 

- [x] https://github.com/audacity/audacity/pull/5676
- [x] #5711
- [x] #5712
- [x] #5718
- [ ] Remove those grabbers on the sides of multi-tool
- [x] #5713
- [x] Remove scrub toolbar
- [ ] Introduce small mod-script-pipe timer record plugin
    - [ ] then Remove built-in timer record 
- [x] #5714
- [x] #5761
- [ ] Remove supporting code for local manual
- [x] https://github.com/audacity/audacity/issues/3868
- [ ] Snap-to-prior (vs nearest)

## other cleanup

- [x] https://github.com/audacity/audacity/issues/5522
- [x] #5720
- [ ] https://github.com/audacity/audacity/issues/4420
- [ ] Cursors for spectral selection
- [x] #5801
- [x] #5715
- [x] https://github.com/audacity/audacity/issues/4144
- [ ] #3922
- [x] #6434
- [x] #6644
- [x] #6785

## dejankification

- [ ] Clean up normalize UI and #2408
- [ ] #4452
- [x] #4731
- [ ] #4732
- [ ] #5377
- [x] #5581
- [ ] Automatically trim clips when moved before zero (as opposed to letting them actually move there)

**Comment by petersampsonaudacity** [comment]
I have added P1s to the Manual for when these changes eventually arrive in master for 3.5.0

**Comment by LWinterberg** [comment]
this is essentially done now
