### ISSUE TITLE
Remove EQ XML to TXT converter

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#5711]

**Comment by LWinterberg** [comment]
It's been ported to https://plugins.audacityteam.org/additional-resources/eq-curves/eq-xml-to-txt-converter

Nyquist file is at https://github.com/audacity/audacity-support/blob/plugins/.gitbook/assets/EQ%20xml%20to%20txt.ny

**Comment by chinakov** [comment]
Tested, thanks!
