### ISSUE TITLE
Apply & Close buttons for the Effect dialogs

### ISSUE THREAD

**Issue by ghost** [audacity/audacity#572]
When applying an audio Effect it always frustrates me to apply and then Close the dialog, 2 clicks for no reason, sometimes you might click the wrong button and have to reopen the dialog to do them again.

The Effect dialogs should have an **Apply & Close** button as well to avoid the extra click every time. Might not look as much but the work adds up when you have to bulk edit lots of sounds

**Comment by SteveDaulton** [comment]
Please post feature requests to the "Adding Features" board on the Audacity forum: https://forum.audacityteam.org/viewforum.php?f=20
Feature requests posted to the forum frequently gain the support of other users, which we then log for the attention of developers.

**Comment by LWinterberg** [comment]
With stackable real-time effects being the main feature of this release, you'll be able to use effects non-destructively and continue working, making it less necessary to destructively apply an effect. I'm closing this issue for now, but I'll take a very close look at feedback when we hit beta as well as post-launch.
