### ISSUE TITLE
Restore the "Click to join adjacent clips" as an "off" by default option/preference

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#5722]
### Bug description

The left-mouse-button click gesture on the shared boundary of adjacent clips to join the clips was removed in 3.4.0.

There have been many complaints about this on the Forum and on the various Facebook pages for Audacity

### Steps to reproduce

1. get some audio
2. make a selection in the middle
3. Ctrl+I to make 3 clips
4. left click on either of the shared clip boundaries
5. Observe:  nothing happened

### Expected behavior

Provided the user sets an as-yet non-existent preference than at stps 4-5 the two clips should be joined

### Actual behavior

Clips are no longer joined with LMB gesture

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

See also further on in this issue thread:
 Consistent behaviour when joining a selected clip to adjacent clips #5509 

And for example this Forum thread:
https://forum.audacityteam.org/t/after-update-3-4-0-clicking-to-join-clips-not-working/88465
**After update 3.4.0: Clicking to join clips not working**

**Comment by LWinterberg** [comment]
I'm rejecting this, for two reasons: 

1. Off-by-default _features_ just aren't helpful. I've brought up Cut lines before as another example before - it's an *incredibly* useful feature, especially in a pre-3.1 world, but with it being off virtually nobody uses it! I could only find one or two dozen posts about it in the forum (2007-now), and I could not find any YouTube tutorial mentioning it! On top of that comes added complexity which QA suffers from, and which ultimately users suffer from as well as these off-by-default features rarely get tested in depth. 
2. Joining clips now isn't actually slower. For each individual line, sure, but if you let just a handful of clips accumulate, Selecting -> Right-click -> join clips or, in simple projects, Ctrl+A Ctrl+J is actually faster than clicking each line away one-by-one.

**Comment by kmote** [comment]
I just want to say I am quite frustrated by  your decision to reject this request. Did you even read the forum thread that was linked above? You are ignoring the voices of a significant number of disgruntled users who clearly expressed their frustration over the removal of this feature. So now all of us have to give up a much-loved and much-used feature simply because you're concerned that it will clutter the Preferences dialog? Yes, in the case when batch-joining all the clips at once is acceptable, that is easier than clicking one at time. But, in my case at least, that's NOT acceptable because I have to edit each split one at a time anyway. 
I'd like to respectfully ask you to please reconsider this decision.

**Comment by joe-op** [comment]
I would like this to return as on by default, and let anyone with the issue in https://github.com/audacity/audacity/issues/1815 address it by disabling the feature.

I frequently want to join clips together until the result reaches a certain length.  With click-to-join, a triple click merges the clips and shows the length so far.  Without it, it is slower to find out the length.

As someone alluded to in [this Audacity forum thread](https://forum.audacityteam.org/t/after-update-3-4-0-clicking-to-join-clips-not-working/88465), the functionality requested in https://github.com/audacity/audacity/issues/1815 seems like a rare edge case compared to joining adjacent clips.

**Comment by LWinterberg** [comment]
The above reasons only address Peter's request for an off-by-default setting. The reason why it's not on-by-default anymore is this:

Clip edges are increasingly meaningful. Back when the feature was introduced, there was hardly a difference between a track and a clip, but now, clips carry information such as speed changes, pitch changes, temporarily hidden data, color and names. And this list is only going to expand. Other clip properties which may come down the road would be things like gain, fade, clip source, takes, repeats, snap points and probably more. 

Having a one-click destructive operation in this environment is highly unexpected, and also relatively dangerous, especially as the controls for some of these clip properties are on the clip edge as well. The benefit of fast clip merges does not outweigh the downside of an accidental clip merge which loses a bunch of data.

**Comment by petersampsonaudacity** [comment]
> The above reasons only address Peter's request for an off-by-default setting.

@LWinterberg   -  actually not **_"my"_** request, I was merely the scribe logging the complaints of many Forum users.

_In the past in fact I was always a strong advocate of removing the left-click to join a pair of clips as it mad it impossible to set the cursor on a clip boundary.  And I remain of that view (hence the "off" by default option in this issue)._

Personally I have never used clips (except in QA testing and documenting) - but if I did I would be perfectly happy to use the new method of selecting over a clip, or a range of clips, and using the join clips command in the Track/Clip context menu.
In fact the ability to join several clips at once would seem to be a big advantage over the old method of left-clicking a single clip.

----------------------------------------------------------------------------------------------

One thing that would improve the usability of the new method would be to allow clip merging when the selection just touches the clip edge.

Consider this use case, where the middle clip is selected but cannot be joined to its two adjacent clips with the Clip context menu.
![image](https://github.com/audacity/audacity/assets/50205984/3fa96ed1-6d59-4457-8272-73fdf85709a1)

**Comment by petersampsonaudacity** [comment]
> Clip edges are increasingly meaningful. Back when the feature was introduced, there was hardly a difference between a track and a clip, but now, clips carry information such as speed changes, pitch changes, temporarily hidden data, color and names. And this list is only going to expand. Other clip properties which may come down the road would be things like gain, fade, clip source, takes, repeats, snap points and probably more.
> 
> Having a one-click destructive operation in this environment is highly unexpected, and also relatively dangerous,

@LWinterberg - Hi Leo, this raises an interesting question ...

When two (or more) clips are merged with the Clip context menu, where each of the clips has different characteristics, what are the characteristics of the merged clip:
a) does one clip dominate and override the others,
b) does clip rendering take place?

**Comment by LWinterberg** [comment]
> Should we be logging this as a usability enhancement?

Feel free to. When a single clip is selected, the "Join clips" command really needs to read "Join with adjacent clips" or something, because otherwise selecting a single clip and having "join clips" enabled is super weird. 

> When two (or more) clips are merged with the Clip context menu, 
Clip merges always get rendered, yes.

**Comment by petersampsonaudacity** [comment]
> > Should we be logging this as a usability enhancement?
> 
> Feel free to.

I later realized that we already have one:
** Consistent behaviour when joining a selected clip to adjacent clips #5509 **

**Comment by joe-op** [comment]
> Having a one-click destructive operation in this environment is highly unexpected, and also relatively dangerous

That makes sense, but also seems to apply to a subset of users who have data in the clip to destroy, but won't realize they've destroyed it.  I wish it could be handled more like the track mix down warning.  For users like myself who don't use this feature, this is just a loss of functionality.

In my view this isn't really a linear change in usage, it's a change from joining clips being "ridiculously easy" to "something you can do."  Certainly not just one extra step.

In any case, overall I appreciate Audacity a lot.  I think I'll stick to an earlier version for now.
