### ISSUE TITLE
Tempo Detection: handle multiple-file import

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#5726]
#5548 introduced the user-interaction flow wrt to tempo detection.
Currently, though, if more than one file are imported at a time, no attempt is made at tempo detection and the behaviour is as in 3.4.
There is a need for UX thinking. Indeed, if ,about project reconfiguration upon music file import,
* the user has chosen "Do nothing", project is not re-configured but if the view is B&M, files with music content should probably be auto-stretched,
* the user has chosen "Reconfigure", the only change should now be the switch to B&M (the project tempo should probably not change)

Also, the preference setting may well need re-wording, as well as the dialog.

**Comment by saintmatthieu** [comment]
@LWinterberg

**Comment by LWinterberg** [comment]
* If the metadata parser sees *all* of the files self-reporting as, say, 90 bpm, the project tempo would be set to 90 bpm.  So the same logic is used here like just one file was imported.
* If the files have different tempi (for example, 90, 100, 120, 138), simply pick one of them and offer to stretch to it (depending on preferences)
* If some of the files don't have any discernable tempo, don't stretch the files without tempo. If they are bundled with files which do have tempo (eg 90, 100, null, null), use the files which do have tempo to determine the new project tempo as above and stretch them accordingly.  

Does that sound reasonable?

**Comment by saintmatthieu** [comment]
> If the metadata parser sees all of the files self-reporting as, say, 90 bpm, the project tempo would be set to 90 bpm. So the same logic is used here like just one file was imported.

I don't have a strong opinion on that, but I'm not sure this is worthwhile. This check would be easy to add, but that'd be another test case for QA. Do you have a use case in mind?

> If the files have different tempi (for example, 90, 100, 120, 138), simply pick one of them and offer to stretch to it (depending on preferences)

What makes you prefer that over preserving the project tempo? I'm thinking, especially in the mixture-import scenario, that non-musical clips then wouldn't be auto-stretched.

**Comment by LWinterberg** [comment]
> I don't have a strong opinion on that, but I'm not sure this is worthwhile. This check would be easy to add, but that'd be another test case for QA. Do you have a use case in mind?

Importing stem-like groups of files. I found these in my sample library:

* Floating 90bpm hihat.wav
* Floating 90bpm kick.wav
* Floating 90bpm snare.wav
* Floating 90bpm sidestick.wav

And similarly, the Musehub also has sets which really want to be imported in groups to create the base beat for something. 

> What makes you prefer that over preserving the project tempo? I'm thinking, especially in the mixture-import scenario, that non-musical clips then wouldn't be auto-stretched.

Picking a bpm from the imported files has a chance of being the correct one the person wanted, while the default bpm is less likely to have that. Non-musical clips wouldn't be auto-stretched in either case.

**Comment by saintmatthieu** [comment]
> Non-musical clips wouldn't be auto-stretched in either case.

Right, I thought wrong.

Sounds good.

**Comment by dozzzzer** [comment]
Tested
