### ISSUE TITLE
Right-click "Change Speed" should be "Change Tempo"

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#5727]
### Bug description

The right-click "Change Speed" menu item changes the "tempo", as is reflected in the "Tempo" setting in the Time Signature Toolbar.

### Steps to reproduce

1. Right click on a selected track.
2. Look at the menu items

### Expected behavior

Consistent terminology.

### Actual behavior

The "Change Speed" command changes the Tempo rather than the Speed.

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

Discrepant naming conventions hinder understanding and overall usability.
https://github.com/audacity/audacity/issues/5645

**Comment by LWinterberg** [comment]
Since there are no tempo (bpm) controls inside that option, it does not make sense to rename it to change tempo, no.
