### ISSUE TITLE
Availability of right-click "Change Speed" determined by mysterious logic

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#5728]
### Bug description

The "Change Speed" option in an audio track's right click menu may be unexpectedly available / unavailable (greyed out /not greyed out).

### Steps to reproduce

1. Launch Audacity
2. Generate a 30 second tone
3. Click on an empty part of the tracks window
4. Generate a 10 second tone (creates a new, selected track)
5. Right click on the 10 second track
6. Observe that "Change Speed" is greyed out
7. Right click again on the track (the menu closes and the selection remains)
8. Right click again on the track
9. Observe that "Change Speed" is now available
10. Right click again on the track to close the menu
11. Right click on the 30 second track
12. Observe that "Change Speed" is available (not greyed out)
13. Select "Change Speed"
14. Observe that the menu closes without opening the Change Speed dialog window

### Expected behavior

Step 6: "Change Speed" available.
Step 12: "Change Speed" greyed out

### Actual behavior

Step 6: "Change Speed" greyed out.
Step 12: "Change Speed" available

### Audacity Version

3.4.2

### Operating system

All OSs

**Comment by petersampsonaudacity** [comment]
Hmmm...

I notice that the image I have in the manual gas it grayed-out even though a selection is present:
![image](https://github.com/audacity/audacity/assets/50205984/f157132c-edb1-4c9f-b18a-54511bb2f299)

**Comment by petersampsonaudacity** [comment]
> While we're at it, #3101 goes in the same vein - when a clip is right-clicked, it the relevant options for the clip could be accessible even if it's not selected

**Big** +1 from me

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
