### ISSUE TITLE
Exporting mono track makes a stereo file panned all the way left

### ISSUE THREAD

**Issue by JapanYoshi** [audacity/audacity#5731]
### Bug description

Before 3.4, I could export a mono audio file from a project that has only mono tracks.

Now, when I export audio from a project that has only mono tracks, I get a stereo audio file with a silent right track.

### Steps to reproduce

1. Create a project
2. Add mono audio
3. Export audio
4. Open that exported audio back in Audacity

### Expected behavior

The exported audio should be monaural.

### Actual behavior

The exported audio is stereo with a completely silent right track.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by petersampsonaudacity** [comment]
Testing on W10 with 3.4.2 and the latest alpha test buld I have for the upciming 3.5.0

I cannot reproduce this.

1) I I export a mono track as mono and then re-import, it comes in as a mono track

2) If I force export of that mono track to be a stereo - then when I re-import I get a stereo track which is center-panned

**Comment by dozzzzer** [comment]
Cannot reproduce this either (macOS 14.2 / Windows 11)
