### ISSUE TITLE
When editing a label you can no longer tab to the next label for editing

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#5737]
### Bug description
When the user is editing a label they can no longer tab to the next (or previous) label text box to continue editing.
Instead tabbing from the label's text box takes the user to that label's drag-bar - and the next tab takes the user to the next label's drag-bar.

This is a regression on 3.0.5, introduced in 3.1.0 when the label drag-bars came into use.

### Steps to reproduce
1. generate a 30 second chirp
2. create a range label from 5-10 secs
3. create a range label from 20-25 secs
4. Click in the first label's text box (to initiate editing)
5. Edit the label text
6. press Tab
7. Observe: the focus shifts to the first label's drag-bar and NOT the next label text box ready for editing
8. press Tab
9.  Observe: the focus shifts to the second label's drag-bar

### Expected behavior
While in label editing mode tabbing should move the user to the next label text box ready for editing

### Actual behavior
When editing a label text, pressing tab shifts the focus to the label's drag-bar

### Audacity Version
3.4.2 and 3.5.0 alpha - all versions 3.1.0 and onwards

### Operating system
Windows 10 - but assume all OS

## Additional context
This issue arose from a forum thread where the user was expecting to still be able to tab to the next label's text box to continue editing.

See this related issue:
https://github.com/audacity/audacity/issues/2737

**Comment by dozzzzer** [comment]
Please bisect @chinakov

**Comment by DavidBailes** [comment]
> This is a regression on 3.0.5, introduced in 3.1.0 when the label drag-bars came into use.

See:
https://github.com/audacity/audacity/issues/1251

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
