### ISSUE TITLE
Rewrite WaveTrack::Clear, ClearAndAddCutline, SplitDelete

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#5742]
Interval-major rewrites of the functions named in this issue.

QA: test for mono and stereo tracks:
- [x] Making cutlines, expanding and deleting them
- [x] Change Speed, Change Tempo, Sliding stretch, where the selected time includes gaps between clips (high and low quality)
- [x] Edit > Remove Special > Split Delete (Ctrl + Alt + K)
- [x] Edit > Remove Special > Split Cut (Ctrl + Alt + X)
- [x] Edit > Remove Special > Trim (Ctrl + T)
- [x] Edit > Clips > Split New (Ctrl + Alt + I)
- [x] Edit > Clips > Disjoin (Ctrl + Alt + J)
- [x] Apply Equalization, Truncate Silence, Noise Reduction
- [x] Generating inserted Silence of zero duration
- [x] Tracks > Stereo to Mono
- [x] Shortening of a sync-locked wave track
- [x] Include time selections that completely surround a clip
- [x] Include time selections that overlap a clip partly at the left or right end, or are inside a clip; both for split-delete and for simple deletion
- [x] With "Always paste audio as new clips" off, paste into a clip, verify no splits are made 
- [x] With "Always paste audio as new clips" on, paste into a clip, verify splits are made, and also if you delete the middle clip, the left and right clips retain hidden data
- [x] Repeat the last, in the case of two clips with a gap between them, and the selection is from inside one clip to inside the other, surrounding the gap

**Comment by dozzzzer** [comment]
@Paul-Licameli 
- with "Always paste audio as new clips" ON, attempting to paste audio from one stereo track to another always causes a crash, regardless of the "Editing a clip can move other clips" setting:

https://github.com/audacity/audacity/assets/70063970/97183f40-4a67-4172-bc22-5b3f2cdc56a1

**Comment by dozzzzer** [comment]
@Paul-Licameli an unintended change of behavior is introduced by this PR:
- with "Always paste audio as new clips" ON and "Editing clips can move other clips" OFF, copy a selection from one audio track and paste it to the other. Currently, the selection is pasted as a separate clip. Previously, it would yield "not enough room" error message.

#### Current master

https://github.com/audacity/audacity/assets/70063970/172f5e6f-2db2-4665-a585-5cbc573c6625


#### This PR


https://github.com/audacity/audacity/assets/70063970/d14c5541-7540-46b8-bd02-43d99698823a

**Comment by Paul-Licameli** [comment]
> @Paul-Licameli an unintended change of behavior is introduced by this PR:
> 
>     * with "Always paste audio as new clips" ON and "Editing clips can move other clips" OFF, copy a selection from one audio track (mono or stereo) and paste it to the other. Currently, the selection is pasted as a separate clip. Previously, it would yield "not enough room" error message.
> 
> 
> #### Current master
> Screen.Recording.2023-12-07.at.16.48.16.mov
> #### This PR
> Screen.Recording.2023-12-07.at.16.49.35.mov

Debug build crashes when you do that, because of an assertion violation.
