### ISSUE TITLE
MuseFX for Linux

### ISSUE THREAD

**Issue by mmeyn** [audacity/audacity#5745]
### Your idea

Add MuseFX to the Linux version of Muse Hub, or have a place where you can download the effects.

### Problem to be solved

MuseFX cannot be used on Linux because they cannot be found.

**Comment by LWinterberg** [comment]
the musefx are not compatible with Linux at the moment, unfortunately. You can send this feature request to https://musehub.zendesk.com/hc/en-gb and ask the musefx team to port them over though.
