### ISSUE TITLE
Plugin directory in user’s home directory

### ISSUE THREAD

**Issue by mmeyn** [audacity/audacity#5746]
### Your idea

I’d like to have a plugin directory that a non-admin user can access.

### Problem to be solved

I’d like to use things like auto-tune in music classes but it was a huge struggle (eight months of e-mails) to get our IT guys to installing Audacity on my computer so I would rather not try this again for plugins.

### Prior art

MuseScore has /home/MYNAME/Documents/MuseScore4/Plugins on Linux and a similar location on Windows.

**Comment by LWinterberg** [comment]
You can install plugins into ` ~/.local/share/audacity/Plug-Ins`  (or `~/.audacity-data` on older Audacity versions).

**Comment by mmeyn** [comment]
This is not documented, is it? At least I can’t find this info at https://support.audacityteam.org/basics/customizing-audacity/installing-plugins

**Comment by mmeyn** [comment]
I tried copying the MuseFX .vst3 files from `Program Files\Common Files\VST3` on another Windows computer to `%appdata%\audacity\Plug-Ins` on my work computer. Audacity doesn’t seem to find them there. Shouldn’t this work? If this is expected behaviour, this issue should be re-opened. If this is unexpected, what might I have done wrong?

**Comment by LWinterberg** [comment]
If you are trying to use the same project in both computers, this is expected. The ID of a VST3 plugin contains the install path.
