### ISSUE TITLE
Links in Help menu take to the old Alpha Manual

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5749]
1. Select `Help > Quick help`

Actual: https://alphamanual.audacityteam.org/man/Quick_Help
Expected: https://manual.audacityteam.org/quick_help.html

1. Select `Help >  Manual`

Actual: https://alphamanual.audacityteam.org/man/Main_Page
Expected: https://manual.audacityteam.org/index.html

**Comment by LWinterberg** [comment]
This is expected of alpha/beta builds, but is different in release builds. That said, given that we're gating the alphamanual now, we probably should just always link to the live manual.

**Comment by dozzzzer** [comment]
Tested
