### ISSUE TITLE
Mono/Stereo Option is Ignored When Using Export Audio > Multiple

### ISSUE THREAD

**Issue by Enverex** [audacity/audacity#5750]
### Bug description

As per the title, the Mono/Stereo option seems to be ignored when doing a “Multiple Files” export. Even if I select Mono on this page, it’ll still export the files as Stereo.

Version 3.4.2.

### Steps to reproduce

Have multiple stereo tracks in the project. Go to Export Audio. Select Mono. Export.
![image](https://github.com/audacity/audacity/assets/958670/f79a47be-aeb1-40c0-8820-011a83379977)

### Expected behavior

For the audio tracks to be downmixed to mono on export.

### Actual behavior

Stereo tracks are exported as stereo regardless of the selected "Mono" option in the Export dialog. 

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows, macOS

**Comment by Rowsinator** [comment]
I am also having this issue. My tracks are considered to be mono, but the exports are stereo (my mic only records on the left channel). Playback in the program is properly Mono, even though the export is Stereo.

I'd like to add that I've tested this for the following formats:  .mp3, .wav, and .ogg. This is a problem that likely affects all formats.

**Comment by mlevac-demeter** [comment]
Regression?
This problem was already present on version 3.2.4, under Debian 12 (Bookworm)!
Purely mono project always exporting WAV as stereo.

**Comment by dozzzzer** [comment]
> This problem was already present in version 3.2.4

FWIW I can't reproduce the issue in 3.2.4, either on Windows or Mac, both when exporting as WAV or multiple files.

**Comment by Rowsinator** [comment]
> > This problem was already present in version 3.2.4
> 
> FWIW I can't reproduce the issue in 3.2.4, either on Windows or Mac, both when exporting as WAV or multiple files.

Try this, this is my setup for recording:

I have an audio interface that records the left and right sides of a single track separately (Voice left, Instrument right). When I only want to do voice work I set the track type to MONO. This makes my left side voice hear-able on both sides of the track when in the program. I then record to different tracks for each specific thing I want to record. From there, I export as multiple files. What I hear from Audacity is what I expect the output to be when I export the file, and it does sound correct when I only export one track at a time that I manually export by hand.

What I get instead is files that only have "Left only" as if I had not selected a mono track. This issue does not seem related to the file type as exporting as any format that supports stereo sound will export multiple as stereo.

My guess is that whatever checks for the track type in "Export multiple" does not correctly assign what the current track type is before exporting.

**Comment by vsverchinsky** [comment]
@LWinterberg Could you please clarify the expected behavior when channels option is set to stereo but there are mono tracks present? I see that now (and in older versions of Audacity) the number of channels in each individual exported file dependend on whether the track source had two channels, or non-zero panning. Should we keep that behavior when stereo option is selected or forcibly expand to stereo even if there is only one channel in the track and no panning applied?

**Comment by LWinterberg** [comment]
When stereo is selected, all exported files should be stereo, and mono channels expanded to stereo.
