### ISSUE TITLE
Rewrite ClearAndPaste

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#5751]
Rewrite WaveTrack::ClearAndPaste as interval-major

QA:  for mono and stereo, point selections and interval selections:
- [x] Test the "Crossfade Clips" Nyquist effect, selecting around the split of two butting clips:  the split should remain, no new splits
- [x] With "Always paste audio as new clips" checked or unchecked, verify that new splits are or are not made as appropriate
- [x] With "Always paste audio as new clips" off, paste into a clip, verify no splits are made
- [x] Also do that cross-project, with difference of tempo; verify the pasted part stretches for new tempo
- [x] With "Always paste audio as new clips" on, paste into a clip, verify splits are made, and also if you delete the middle clip, the left and right clips retain hidden data
- [x] Repeat the last, in the case of two clips with a gap between them, and the selection is from inside one clip to inside the other, surrounding the gap
- [x] Transforming a selection containing cutlines with Eq preserves the cutlines; try with more than one cutline
- [x] Same, with all the built-in time stretching effects, preserves cutlines and remaps them in time
- [x] Preservation of copied clip names when you do or don't paste "as new clips"
- [x] Preservation of hidden data on the edge of the pasted-INTO clip, when you don't paste "as new clips", and the selected interval crosses that clip boundary; test both left and right
- [x] As above, but where you select an interval that only touches the clip's left or right edge
- [ ] ...

Also for good measure, reproducing the checklist of #5585:

- [x] Pasted-into track becomes selected
- [x] Cross-project paste, with and without project tempo differences
- [x] Paste with and without stretch ratio differences
- [x] With and without the new merging preference
- [x] Pasting into a clip, within one sample interval of time 0
- [x] With and without the "Edit clips can move" preference; test the prohibition
- [x] Moving of multiple other clips rightward to make room for the paste
- [x] New clips get correct names, and also when splitting to mono after the paste

**Comment by Paul-Licameli** [comment]
Rewrite WaveTrack::ClearAndPaste as interval-major

**Comment by dozzzzer** [comment]
@Paul-Licameli 

<img width="400" alt="Screenshot 2023-12-12 at 14 18 50" src="https://github.com/audacity/audacity/assets/70063970/1b05442f-729c-4155-8d54-102cc2050ee7">

- when copying a selection of two clips with a gap between them (see above) and then pasting it onto the same selection, the result is incorrect.

This PR:

<img width="450" alt="Screenshot 2023-12-12 at 14 21 30" src="https://github.com/audacity/audacity/assets/70063970/e2d7f1d6-a6cd-4d47-bb2c-a1b09da90205">

Current master:

<img width="450" alt="Screenshot 2023-12-12 at 14 23 43" src="https://github.com/audacity/audacity/assets/70063970/836710de-0785-4ae7-a25b-63001f62bc09">

Also, when copying the selection to a new track, this is what the pasted audio looks like:

<img width="350" alt="Screenshot 2023-12-12 at 14 24 44" src="https://github.com/audacity/audacity/assets/70063970/3d2ae92b-f5b3-4da1-8c04-c997fe6b0702">

**Comment by Paul-Licameli** [comment]
> @Paul-Licameli
> <img alt="Screenshot 2023-12-12 at 14 18 50" width="400" src="https://private-user-images.githubusercontent.com/70063970/289871560-1b05442f-729c-4155-8d54-102cc2050ee7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxOTkzNTksIm5iZiI6MTcwNDE5OTA1OSwicGF0aCI6Ii83MDA2Mzk3MC8yODk4NzE1NjAtMWIwNTQ0MmYtNzI5Yy00MTU1LThkNTQtMTAyY2MyMDUwZWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDEyMzczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1N2MyMDBjNGNlYTllMjk4ZThmNzY2NDFlYzE5OWY2M2RkNTlmNTBmYWRhYmVhOGVmZTQ0ZDQ2OTQ0ZTIwNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DdsN4wOY8cMpq17Qrl8gqdAJ3lBHbyokg8y2l1gMbzc">
> 
>     * when copying a selection of two clips with a gap between them (see above) and then pasting it onto the same selection, the result is incorrect.
> 
> 
> This PR:
> <img alt="Screenshot 2023-12-12 at 14 21 30" width="450" src="https://private-user-images.githubusercontent.com/70063970/289871727-e2d7f1d6-a6cd-4d47-bb2c-a1b09da90205.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxOTkzNTksIm5iZiI6MTcwNDE5OTA1OSwicGF0aCI6Ii83MDA2Mzk3MC8yODk4NzE3MjctZTJkN2YxZDYtYTZjZC00ZDQ3LWJiMmMtYTFiMDlkYTkwMjA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDEyMzczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NDdhNzU3YTM3NWY4YWYzYTI4NzcxYzdmMzdkODA3YzYxNmI5ZDdjNjdhNmJiYTNiZTMyZjFmYTcwMThkMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._sRo8N_5-NVvbibDvNGmICx86WKnDln508dLY2Tb2uU">
> 
> Current master:
> <img alt="Screenshot 2023-12-12 at 14 23 43" width="450" src="https://private-user-images.githubusercontent.com/70063970/289872296-836710de-0785-4ae7-a25b-63001f62bc09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxOTkzNTksIm5iZiI6MTcwNDE5OTA1OSwicGF0aCI6Ii83MDA2Mzk3MC8yODk4NzIyOTYtODM2NzEwZGUtMDc4NS00YWU3LWEyNWItNjMwMDFmNjJiYzA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDEyMzczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMmNjNmNmNDFlYmQ2YjQ0MjFjY2MxYzExY2RjM2NhOWFjMzUyNDM0ZDMxODgyMTNiZDU0MzY4YTE5MWYwNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._4cXc9of09hE-rXDwayA0u-qBvW7CiZkGaAZUT0OnJ0">
> 
> Also, when copying the selection to a new track, this is what the pasted audio looks like:
> <img alt="Screenshot 2023-12-12 at 14 24 44" width="350" src="https://private-user-images.githubusercontent.com/70063970/289872709-3d2ae92b-f5b3-4da1-8c04-c997fe6b0702.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxOTkzNTksIm5iZiI6MTcwNDE5OTA1OSwicGF0aCI6Ii83MDA2Mzk3MC8yODk4NzI3MDktM2QyYWU5MmItZjViMy00ZGExLThjMDQtYzk5N2ZlNmIwNzAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDEyMzczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5MDc1OGUwN2RiMWFiZjNmZDMyNzY1MzhlYjgzZDU4YzI3YTI3Mzg3NzdmYjk0Zjc1MzNmZGRmYjYyZTExY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LiX-i7Lv5qXA6tqbvVPLYlxv31xmcB_1ovbth6OVro0">

Is the problem in the last screenshot already existent in audacity/wave-clip-refactoring?

**Comment by Paul-Licameli** [comment]
In fact, yes.  There is more than one problem here, and one is not new in this branch, but escaped earlier testing.

**Comment by dozzzzer** [comment]
Tested
