### ISSUE TITLE
Set default snapping unit to 8th-note

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#5756]
The default snapping unit is seconds. This is seldom useful, more useful is snapping to a musical unit. The 8th-note is probably a good default unit.
I'd also have enabled snapping by default when switching to B&M (e.g. when tempo is detected in an imported file) but @LWinterberg warned me that the behavioral change may be unexpected and upsetting.

**Comment by LWinterberg** [comment]
Snapping to seconds seems highly rare, so snapping to eights is as good a default as any. I wouldn't want to turn on snap by default though; in a world where we can assume that people are working MIDI and pre-made loops it probably is a good default, but right now we probably can expect people to start out with their own recordings and other non-conformed content.

**Comment by crsib** [comment]
> own recordings and other non-conformed content

That's my point exactly; snapping to 8th for most users ATM will mean snapping to 0.25 seconds, but expressed in a weird `120 BMP 4/4` way.

**Comment by LWinterberg** [comment]
Aye. It's just, you rarely need to snap to any grid in the context of non-rhythmic content in the first place. So it'll be mostly music people using this option, and for them, 1/8 is the more useful default.
