### ISSUE TITLE
Music import dialog: When it opens, it's not automatically read by some screen readers.

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#5757]
### Bug description

At least on my computer, this bug occurs when using Narrator or NVDA, but not when using Jaws.

### Steps to reproduce

On Windows, open either the Narrator or NVDA screen reader.
1. Open audacity.
2. Import a track with xxxbpm in the filename. A music import dialog opens.

### Expected behavior

The screen reader automatically reads the music import dialog.

### Actual behavior

The screen reader reads the name of the track - the screen reader thinks the track is the focus.
Here's a screen shot when using the narrator screen reader - the blue outline around the track shows where the screen reader thinks the focus is:
![image](https://github.com/audacity/audacity/assets/11887021/a7034671-3635-47f1-aaf3-1a80ad10fe4b)

After the dialog opens, if you then press any standard navigation keystrokes then when a new control in the dialog becomes the focus, the screen reader then reads that control correctly.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

**Comment by DavidBailes** [comment]
@LWinterberg . I've submitted a PR for this, please can this issue be added to the 3.5 milestone.

**Comment by saintmatthieu** [comment]
@DavidBailes, @ianalarina assigned me, but I think it makes more sense for you to be the assignee, what do you think?

**Comment by DavidBailes** [comment]
> @DavidBailes, @ianalarina assigned me, but I think it makes more sense for you to be the assignee, what do you think?

I've already submitted a PR to fix this.

**Comment by dozzzzer** [comment]
Tested
