### ISSUE TITLE
Export as FLAC (in the Extra>Export menu) should be grayed-out and unavailable when there is no Audio

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#5758]
### Bug description
When there is no audio present, in the **Extra > Export** submenu the **Export as FLAC** is not grayed-out and unavailable.  Whereas the exports for MP3, WAV and OGG are properly grayed-out.

Clicking on the **Export as FLAC** yields an error message "All audio is muted" - BUT there is no audio.

### Steps to reproduce
1. View > Enable Extra Menus
2. Extra > Export
3. **Observe: Export as FLAC is not grayed-out**
4. Click on it
5. Observe: inappropriate error message

### Expected behavior
Export as FLAC should be grayed-out and unavailable when there is no audio

### Actual behavior
![image](https://github.com/audacity/audacity/assets/50205984/65561d7b-e1c2-48b2-a7f6-4b80bc0a6648)

![image](https://github.com/audacity/audacity/assets/50205984/d935e952-f764-4672-99a3-a62a4484ab54)

### Audacity Version
3.4.2 and 3.5.0 alpha

### Operating system
Windows 10 - but assume all OS

### Additional context
Will become more visible to more users once **Export Selection** is added to the **Extra > Export** submenu.

This does _**not**_ appear to be a regression, it has been this way since the Export entry was added to the Extra menu for 3.4.0

**Comment by dozzzzer** [comment]
I confirm the bug remains unfixed

**Comment by LWinterberg** [comment]
ah, I see: There's actually 2 FLAC exports, one in HiddenFileMenu (only accessible via macros), one in the extra menu. Given that export is now in the extra menu, do we really need that HiddenFileMenu entry anymore?

**Comment by petersampsonaudacity** [comment]
I can't really answer that question - but I assume the the HiddenFileMenu may be important/useful for scripting as well as Macros.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @LWinterberg 's latest branch for this fix:  audacity-win-3.5.0-alpha-20231211+43d0cba-x64

This now works fine:
![image](https://github.com/audacity/audacity/assets/50205984/3576bd31-18dd-4e51-8c85-20ef05bcea9a)

**Comment by dozzzzer** [comment]
Tested

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest master alpha for 3.5.0:  audacity-win-3.5.0-alpha-20231213+0956bcc-x64-msvc2022

This now works properly with the FLAC export in the Extra>Export menu grayed-out and inaccessible when there is no audio.
