### ISSUE TITLE
Selected clip edges should stroke across stereo channels

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#5767]
### Bug description

A subtle problem in drawing, more evident in non-default, Dark theme

### Steps to reproduce

1. choose Dark or High Contrast theme to make the problem more obvious
2. generate a stereo clip
3. Try the next in each of Spectrogram, Waveform, or Split views
4. Click and drag the clip; observe the left and right edges

### Expected behavior

Narrow white vertical lines, one pixel wide, are drawn about the moving clip, but these span only the left channel

### Actual behavior

The intention was probably to draw lines around both channels.  Now that misaligned clips are impossible, this should be easier to code

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows, macOS, Linux

### Additional context

Problem is older in fact than "latest stable version"

**Comment by chinakov** [comment]
Tested, thank you!
