### ISSUE TITLE
SuSE: Audacity 2.4.1 crashes when built with gtk2 widgets.

### ISSUE THREAD

**Issue by plater** [audacity/audacity#577]
Audacity's configure or cmake when it's ready, should reject wxWidgets built with gtk2 it also needs wxWidgets greater than 3.1 to build.

**Comment by SteveDaulton** [comment]
I'm using Audacity 2.4.1 and 2.4.2 alpha, both built with wx3.1 and gtk2, on Xubuntu 18.04 LTS and xorg session.
Both are very stable.

What platform are you building on?

**Comment by plater** [comment]
Sorry Ieft out built with STL so I have to make a special wxWidgets package for audacity. wxWidgets are version 3.1.3 Gtk is 3.24.20. Gtk2's version is 2.24.32+67
It segfaults at gobject, Audacity's build at:
https://build.opensuse.org/package/live_build_log/home:plater/audacity/Factory/x86_64
I can change my home wxWidgets-nostl package back to gtk2 and post a backtrace but audacity works fine with gtk3.

**Comment by lllucius** [comment]
I little off-topic, but you say your GTK3 build works fine.  Can you try a little thing for me?  Can you resize the device toolbar to see if the controls resize along with the toolbar or if they just slide to the left and get truncated on the left hand side of each one.

Thanks.

**Comment by lllucius** [comment]
Okay, okay, I guess I'll have to build myself an OpenSUSE VM.  :-)  I'll take a look at the crash and the device toolbar.  Will have to be later today though.

**Comment by plater** [comment]
> I little off-topic, but you say your GTK3 build works fine. Can you try a little thing for me? Can you resize the device toolbar to see if the controls resize along with the toolbar or if they just slide to the left and get truncated on the left hand side of each one.

Can't find a resize point on the play etc controls but the sliders resize in proportion. Take note that this is on Leap:15.1 so although the wxWidgets are the same gtk3 is older 3.22.30.
I tried wxWidgets with gtk3 with about audacity 2.1.0 and the result was terrible. It was refreshing to see everything in place with the latest. I think wxWidgets-3.1x plays nicely with gtk3 now.

**Comment by lllucius** [comment]
I just built using:

    cmake -Daudacity_use_wxwidgets=local .. && make -j16 && bin/audacity

This pulled down the Audacity version of wxWidgets 3.1.3 and built it using GTK2.  And it started up just fine.

I'm using Tumbleweed in case it makes a diff.

**Comment by plater** [comment]
I tried cmake, the %cmake macro which adds our standard set of build flags and it failed. It's possibly a bad reaction to -flto= or -o2 that causes the crash. Have to use system libraries where possible.
cmake does this with system lame:
ckages/BUILD/audacity-Audacity-2.4.1/lib-src/libmp3lame/lame.c
In file included from /data/packages/BUILD/audacity-Audacity-2.4.1/lib-src/libmp3lame/lame.c:43:0:
/data/packages/BUILD/audacity-Audacity-2.4.1/lib-src/libmp3lame/set_get.h:24:10: fatal error: lame.h: No such file or directory
 #include <lame.h>
