### ISSUE TITLE
Remove distinction between `GetTrack` and `ReallyGetTrack` in `WaveChannel`

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#5772]
Depends on
- #5806

QA: Mono and stereo...
- [x] Recording
- [x] Mix-and-render
- [x] Import (any file format)
- [x] A generator (any)
- [x] A destructive effect (any)
- [x] Run benchmark tool
- [x] Mix Stereo to Mono
- [x] Low quality change pitch, change tempo effects
- [x] Correct refresh of waveform and spectrum display after track resampling, Tracks > Align commands, dragging clips from track to track
- [x] Dark blue and light blue waveform areas are computed the same
- [x] Save project in 3.3 or earlier with a stereo track with misaligned clips and non-default sample rate; open it in this branch and verify the correct split and correct rates in the tracks and clips
- [x] Loudness effect on stereo tracks really processes both channels
- [x] Cut, copy, paste, select all (Ctrl+A) of text in focused clip name

**Comment by crsib** [comment]
There is one case in PR that should be fixed, but I don't expect that the fix would change the behavior of the program. I would say it is save to start testing.

**Comment by Paul-Licameli** [comment]
> @Paul-Licameli
> 
>     * Generating onto a stereo track using any Nyquist generator causes a crash

That bug already exists in the refactoring branch.  It escaped our detection earlier.

But I have figured out the fix and will add it to this branch.

**Comment by Paul-Licameli** [comment]
In fact that crash bisects to commit 09ca4cdec66eded3dadd297dd0449f218f08a397 in #5692

**Comment by Paul-Licameli** [comment]
I made this issue now dependent on another new issue, to fix the preexisting crash bug in Nyquist generators.

**Comment by dozzzzer** [comment]
Tested
