### ISSUE TITLE
Move some inessential functions from class `WaveTrack` to namespace `WaveChannelUtilities`

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#5774]
Depends on
- #5772

QA: mono and stereo:
- [x] For tasks involving multiple clips, prepare a project where a track is split into many clips, and then these have been "shuffled" by dragging into another track to change their permutation 
- [x] #5767 retested
- [x] Again, verify correct dark blue/pale blue painting
- [x] Pencil editing tool
- [x]  paintbrush (Pencil mode with ALT key), including "spray" across a clip boundary, and with stretch differences
- [x] Amplify computes the same default control value
- [x] Contrast computes the same
- [x] Loudness by RMS computes the same
- [x] Normalize of Peak Amplitude computes the same
- [x] Envelope editing
- [x] Select > Audio Clips menu items
- [x] Transport > Cursor > Previous/Next clip boundary
- [x] Extra menu > Edit > Time shift Left/Right

**Comment by dozzzzer** [comment]
Tested
