### ISSUE TITLE
export cannot recursively create new folders

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#5782]
> I’ve noticed that since the 3.4 update (I believe), the export audio dialogue box now doesn’t allow me to create a new folder in the “Folder” path if the path seems to be more than 1 folder deeper than the current folder.

> For example, if the path is set to C:\export
> I can create C:\export\export
> But I cannot create C:\export\export\a

> In this case, Audacity has the error of “Unable to create destination folder”

Original report from https://forum.audacityteam.org/t/bug-or-error-when-trying-to-make-new-folder-when-exporting-audio/92959/ 

The workaround here is to use the browse dialog instead to create the folders.

**Comment by dozzzzer** [comment]
Tested
