### ISSUE TITLE
Solo button on Track not switch off other

### ISSUE THREAD

**Issue by CASTEL-SBO** [audacity/audacity#5785]
### Bug description

Solo button on Track, when click on one track, the other track is not muted if other is solo enabled

### Steps to reproduce

* Add 2 tracks in project
* Click on solo button on track_1 -> The track_2 is deactivate and track_1 stay activate.
* Click on solo button on track_2 -> The track_2 is activate, but the track_1 is NOT deactivate and button stay on.

### Expected behavior

The Solo button switch all other to desactivate and activate track of solo button

### Actual behavior

The track_2 is activate, but the track_1 is NOT deactivate and button stay on.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by petersampsonaudacity** [comment]
Muse recently changed the default setting for the Solo button behavior to be "**Multi-track**" to make it more like a mixer-board behavior.

Just got to Tracks Behaviors preferences and chnge it back to "**Simple**"
![image](https://github.com/audacity/audacity/assets/50205984/6a6cd0f9-1c8b-4039-b783-e269eb17b2e2)


See this page in the Audacity Manual: 
https://manual.audacityteam.org/man/tracks_behaviors_preferences.html
