### ISSUE TITLE
Better Scrolling  Better Shortcuts

### ISSUE THREAD

**Issue by stephanhhhh** [audacity/audacity#579]
When selecting an audio track, it would be nice to use the mouse wheel to scroll left/right.

When editing/cutting the audio, it would be nice to have 1 key to play/pause/continue the audio, instead of doing play then pause/stop then cutting then select place to play audio  then play audio.
After cutting, it should not automatically revert to stop.

**Comment by SteveDaulton** [comment]
The mouse wheel scrolls projects up / down (when you have multiple tracks)
Shift + Mouse wheel scrolls left / right.
You  can preview what cutting a selection will sound like with the "C" key.
The full list of keyboard shortcuts can be found in the manual: https://manual.audacityteam.org/man/keyboard_shortcut_reference.html

For help using Audacity, and sharing tips, we have a help forum here: https://forum.audacityteam.org
