### ISSUE TITLE
Tempo detection speed improvement

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#5794]
The analysis takes time. The feature would be less irritating if it were much faster.
Currently, it looks like the vast majority of the time is spent on the time-frequency analysis. The time-frequency precision used is that of a Phase Vocoder, but for our purpose something much more rough is probably sufficient.
Ideas:
1. Downsample the signal before analysis. With a bit of luck this could make the detection twice as fast with no or negligible loss of quality.
2. Use a filter bank instead of an STFT to have control over the frequency resolution. Currently, the STFT settings are such that the frequency resolution is of 40Hz. For our purpose this is probably far too much.
3. Find approximations for the log and sqrt methods maybe would help ?

**Comment by dozzzzer** [comment]
Tested. Importing a ~1-minute music loop has gone significantly faster.
For some audio files, the time to perform Music Information Retrieval has decreased by a whopping 450%:
<img width="442" alt="Screenshot 2024-01-24 at 13 26 45" src="https://github.com/audacity/audacity/assets/70063970/330a18b7-1ed4-429a-9d77-40d33a85c0ce">
