### ISSUE TITLE
Please add "Label after filename prefix" in export multiple dialog 

### ISSUE THREAD

**Issue by vspinu** [audacity/audacity#58]
Hi,

I have loads of audio that I have to manually segment. Unfortunately "file+label" option is not present in "export multiple dialog". So I have to recur to workarounds, like manually creating a folder from the same export dialog.  Note taht, a less useful IMO, "file+number" option is there:

![audacity](https://cloud.githubusercontent.com/assets/1363467/8552243/252b176a-24dc-11e5-9a67-0dab8e7a4363.png)

I wonder if it would be more meaningful to remove the last option and have "file prefix" check box instead. Then users can have access to all 3 alternatives: "file+label", "file+number" and "file+number+label".

Thanks for the awesome package!

**Comment by JamesCrook** [comment]
Aren't there five valid combinations we would want?

File-number
File-label
File-number-label
label
number-label

So better is a box for the file (possibly empty) a check box for number, a check box for label/track.  Show an example filename OR a message saying 'more details required' (if e.g. no checkbox checked).  What do you think?

**Comment by vspinu** [comment]
Indeed. All of the above are meaningful.  I like the checkboxes UI. 

You can also have a dropdown list with all the above combinations instead of the checkboxes.  When options with file are selected, the file name prefix text box becomes active. 

Thanks for looking into it.

**Comment by LWinterberg** [comment]
closing this issue in favor of #2615
