### ISSUE TITLE
Horizontal scrolling not working with horizontal scroll wheel

### ISSUE THREAD

**Issue by Mrxx99** [audacity/audacity#581]
**Describe the bug**
I have a mouse that has a horizontal scroll wheel (Logitech MX master 3). Scrolling horizontally with it works fine in other applications. In Audacity however it only moves the (horizontal) scroll bar but it does not actually scroll.

**To Reproduce**
Scroll horizontally with a horizontal scroll wheel.
I guess it is only reproducible with such a mouse... 

**Expected behavior**
The tracks should scroll horizontally together with the scroll bar. Like it is when using shift + normal scroll wheel

**Screenshots**
See here how the scroll bar moves but the tracks don't:
![audacity_scroll](https://user-images.githubusercontent.com/33566379/85157436-c5e35700-b25b-11ea-950e-8a7751b57946.gif)

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version Audacity 2.4.1
 - Mouse: Logitech MX Master 3

**Comment by ahmadalli** [comment]
try uninstalling Logitech Options and see if that fixes it.

**Comment by petersampsonaudacity** [comment]
Horizontal scrolling works fine on my Big Sur Macbook Pro when using left/right gestures on my Magic-Mouse.

I can't test on W10 as my mouse there only has a vertical sroll-wheel

**Comment by petersampsonaudacity** [comment]
@ahmadalli is this still the case with the latest Audacity version ?

**Comment by Mrxx99** [comment]
Tested again with 3.02 on Windows.
Still same behavior, the srcrollbar moves but the tack does not.

**Comment by petersampsonaudacity** [comment]
I logged this on our Bugzilla bugtracker as P3 Bug #2795
https://bugzilla.audacityteam.org/show_bug.cgi?id=2795
Bug 2795 - Windows: horizontal scrolling with mouse with horizontal scroll wheel fails to scroll

Accordingly I will close this GitHub Issue in favor of the tracked Bugzilla entry.

Thanks for the update re 3.0.2 @Mrxx99
