### ISSUE TITLE
Update window goes off screen

### ISSUE THREAD

**Issue by Mementh** [audacity/audacity#5815]
### Bug description

the update window for the current version goes off screen and does not limit itself to userspace

### Steps to reproduce

open app... check for updates see its 
![Clipboard01-](https://github.com/audacity/audacity/assets/13825617/e9c99e8e-fb0b-48d2-9787-7e2ca55a2950)

### Expected behavior

window should limit itself to what the user has

### Actual behavior

![Clipboard01-](https://github.com/audacity/audacity/assets/13825617/5457bd9b-f401-43bb-a217-40b57bb8a32f)

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by crsib** [comment]
Duplicates #5637
