### ISSUE TITLE
Wrong Russian translation of the "Export" menu wording 

### ISSUE THREAD

**Issue by inovikov78** [audacity/audacity#5817]
### Bug description

Audacity 3.4.2
In Russian version, in a  "File" menu ("Файл" in Russian) should be "Экспорт" menu (mean "Export").
But now it looks like "Аудиоданных..." ("Audiodata...")
![Monosnap Screen_Recording_20231225_150924_Audacity](https://github.com/audacity/audacity/assets/20823783/134d1d6b-9ce8-4af2-89b7-e9062ce1c05d)

### Steps to reproduce

1.  Open the app with Russian translated interface
2. Open the "Файл" menu 
3. Try to find ""Экспорт" in the dropdown

### Expected behavior

1.  Open the app with Russian translated interface
2. Open the "Файл" menu 
3. Open the "Экспорт" menu to export current file into different audio formats

### Actual behavior

Menu "File" -> "Экспорт" has wrong translation

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by inovikov78** [comment]
Screenshot - https://disk.yandex.ru/i/SqMuj1yJ_P7vCw

**Comment by dozzzzer** [comment]
Not reproducible anymore:

<img width="615" alt="image" src="https://github.com/audacity/audacity/assets/70063970/fda86d91-4b2a-4548-957c-07b364e2dd32">
