### ISSUE TITLE
Link Consistency Fail dialog when opening a project with a stereo and mono tracks

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5819]
### Steps to reproduce

1. generate chirp
2. import a stereo clip
3. save and close the project
4. open the project

### Expected behavior

No Link Consistency Fail dialog

### Actual behavior

<img width="450" alt="image" src="https://github.com/audacity/audacity/assets/70063970/3993bc2e-e66f-467b-ac65-88d69ac73950">

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS

**Comment by petersampsonaudacity** [comment]
Confirmed on W10 with latest 3.5.0 alpha

It also fails if you make the STRs prpject (steps 1-3) in 3.4.2 and then at Step 4 open it in 3.5.0 alpha

This is not just a regression on 3.4.2 - it's a regression on all Audacity versions back to 1.0

**Comment by Paul-Licameli** [comment]
I reproduced this; but, curiously, if the chirp you make in step 1 is in a stereo track, the bug does not happen.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @Paul-Licameli 's branch build:  audacity-win-3.5.0-alpha-20240103+c17e14b-x64

This now appears to work properly _(in Paul's branch)_  with _**NO**_  unwanted Consitency fail dialog message.
