### ISSUE TITLE
Issue with Mac OS 14.2.1 with audacity issue with audio level toolbar

### ISSUE THREAD

**Issue by jwaldrip16** [audacity/audacity#5821]
### Bug description

Issues with record and playback meter toolbar

### Steps to reproduce

Please see 

https://www.youtube.com/watch?v=LnvJ37_2EZ0

### Expected behavior

https://www.youtube.com/watch?v=LnvJ37_2EZ0

### Actual behavior

https://www.youtube.com/watch?v=LnvJ37_2EZ0

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS

**Comment by dozzzzer** [comment]
Duplicate of https://github.com/audacity/audacity/issues/5699
