### ISSUE TITLE
Everything after the first dot in the name of the exported audio file is cut off

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5823]
### Steps to reproduce

1. Grab some audio
2. Ctrl + Shift + E
3. Leave the Format as is (WAV, for instance)
4. In the File Name text box, put down smth like "Artist – Track (feat. Artist)"
5. Click the Export button
6. Review the exported file's name

### Expected behavior

`"Artist – Track (feat. Artist).wav"`

### Actual behavior

`"Artist – Track (feat.wav"`

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows, macOS

**Comment by metoxys** [comment]
Confirming on 3.4.2 on Windows  
Interesting tidbit: Have a dot in there, export the file, then export again under the same name.  
Audacity will ask you if you are okay with overwriting the file - and it displays the correct name there, but the actual file name is cut off.

**Comment by petersampsonaudacity** [comment]
@dozzzzer 

Testing on W10 with @vsverchinsky 's latest branch build for this:  audacity-win-3.5.0-alpha-20240219+ab76a81-x64

Unless the text after the final period is a valid audio file extension then the text after the last period is stripped and replaced with the appropriate file extension.

STRs
1. get some audio
2. File > Export Audio
3. in the File Name filed type:  a.b.c.d
4. press the Export button
5. Observe: file is exported as a.b.c.wav

**Comment by petersampsonaudacity** [comment]
I note you can also export a filename which is all periods.

For example if you set the File Name to be four periods:   **....** 

the resulting exported file is three periods with a wav extension:   **...wav**  

Is this sensible?  Is this intended/desired behavior?

**Comment by petersampsonaudacity** [comment]
BTW a similar issue occurs when you try to save a project with periods and without an aup3 extension

1. launch Audacity (3.4.2 or this test branch)
2. File save Project
3. set the project name to be **a.b.c**
4. Observe: project is saved as **a.b.aup3**

**Comment by vsverchinsky** [comment]
> Unless the text after the final period is a valid audio file extension then the text after the last period is stripped and replaced with the appropriate file extension.

Yes, I think there was a ticket requesting such behavior. 

> I note you can also export a filename which is all periods.

That would still be a valid file name.

In other words the main goal is to make sure that the extension of the exported file matches the exported file type and. e.g. in Sergey's bug export dialog detects ". Artist)" part of a string to be an extension (but it's not) of the exported file that doesn't match the currently selected format, so it gets repleced.

**Comment by metoxys** [comment]
> > Unless the text after the final period is a valid audio file extension then the text after the last period is stripped and replaced with the appropriate file extension.
> 
> Yes, I think there was a ticket requesting such behavior.
> 
> > I note you can also export a filename which is all periods.
> 
> That would still be a valid file name.
> 
> In other words the main goal is to make sure that the extension of the exported file matches the exported file type. e.g. in Sergey's bug export dialog detects ". Artist)" part of a string to be an extension (but it's not) of the exported file that doesn't match the currently selected format, so it gets repleced.

This issue could be solved by changing "replace" to "append"  
Consider this example of input text versus output file name for someone exporting to .ogg:
![image](https://github.com/audacity/audacity/assets/6764458/2a45bd83-f447-464b-a500-5dfd26faaf4f)

Just always replacing user input without their consent is clearly undesirable behavior in this case

**Comment by dozzzzer** [comment]
Tested
