### ISSUE TITLE
Audacity Crashes on MacOS 14.2.1 when using AUMultibandCompressor

### ISSUE THREAD

**Issue by gshankar** [audacity/audacity#5829]
### Steps to reproduce

1. Open an Audacity project
2. Select track and choose Effect > AUMultibandCompressor
3. Audacity crashes with 

### Expected behavior

Can use the compressor

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

### Additional context

Stacktrace:

Operating system: Mac OS X
                  10.16.0 23C71
CPU: arm64
     10 CPUs

GPU: UNKNOWN

Crash reason:  EXC_BAD_ACCESS / KERN_INVALID_ADDRESS
Crash address: 0x0
Process uptime: 17 seconds

**Comment by crsib** [comment]
Duplicates #5799
