### ISSUE TITLE
Record and Playback levels not functioning on Sonoma 14.2.1.

### ISSUE THREAD

**Issue by jeffschwartz** [audacity/audacity#5832]
### Bug description

Level are not visible.

### Steps to reproduce

Open app.

### Expected behavior

See levels.

### Actual behavior

Levels are not visible.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS

**Comment by jeffschwartz** [comment]
<img width="1909" alt="Untitled" src="https://github.com/audacity/audacity/assets/271288/4e9a73e4-cb95-4698-b484-d653eb844a4d">

**Comment by LWinterberg** [comment]
Duplicate of https://github.com/audacity/audacity/issues/5699
