### ISSUE TITLE
[Bug/MacOS] EXTREMELY HIGH usage of ONE CPU Core

### ISSUE THREAD

**Issue by jadenquinn** [audacity/audacity#5833]
This is beginning to be a problem for me, because on my laptop, Audacity is screwing the hell out of the first core, and not using any other cores, making this one core 100C most of the time, and that is just unkind. There's 6 idle cores on the same chip!! Use them!! ![image](https://github.com/audacity/audacity/assets/13245331/47e0f056-6352-4b57-aba7-a305cf9ae5a2)

Note: This is while Audacity is recording. Either minimized or on screen.

Also note: I'm on my phone, so Issue Templates... don't work because somehow the GitHub devs are incompetent, so that's why this issue has basically no info. It doesn't need any anyway! It's using 100% of one core maxing out its temp for as long as it's recording, that's horrible! No details needed!

Note 3: If you guys need actual proof that this is really running this hot for this long, I'm logging it for about 6min or so using Intel Power Gadget (rip).
![image](https://github.com/audacity/audacity/assets/13245331/b4732bf6-52bc-473a-a047-5a53e0e7a04d)

**Comment by LWinterberg** [comment]
Audacity predates the advent of multi-core processors on consumer desktops by 5 years or so, hence why most operations are single-core. There are plans to improve things one aspect at a time; this particular request is too broad to be actionable though.

**Comment by jadenquinn** [comment]
> Audacity predates the advent of multi-core processors on consumer desktops by 5 years or so, hence why most operations are single-core. There are plans to improve things one aspect at a time; this particular request is too broad to be actionable though.

How about making the app not laggy? It's... incredibly laggy. Maybe the whole thing should be rewritten, actually.
