### ISSUE TITLE
Paste bug in wave-clip-refactoring branch

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#5834]
<img width="400" alt="Screenshot 2023-12-12 at 14 18 50" src="https://github.com/audacity/audacity/assets/70063970/1b05442f-729c-4155-8d54-102cc2050ee7">

- when copying a selection of two clips with a gap between them (see above) and then pasting it onto a new track, the result is incorrect.

<img width="350" alt="Screenshot 2023-12-12 at 14 24 44" src="https://github.com/audacity/audacity/assets/70063970/3d2ae92b-f5b3-4da1-8c04-c997fe6b0702">

_Originally posted by @dozzzzer in https://github.com/audacity/audacity/issues/5751#issuecomment-1852284901_

**Comment by dozzzzer** [comment]
@Paul-Licameli 

Grab some audio (stereo or mono), copy the whole clip or a region of the clip, and try to paste it further onto the same track. The copied audio cannot be pasted. Selection is made instead.

https://github.com/audacity/audacity/assets/70063970/c33db934-491d-494d-b78b-fb52084f2162
