### ISSUE TITLE
Compatibility with Retina display (HiDPI)

### ISSUE THREAD

**Issue by Kwadz** [audacity/audacity#584]
With a MacBook Pro Retnia display, a lot of areas are pixelated. That makes the final rendering of the GUI a bit ugly. Here is a screenshot with some areas highlighted where there is the issue.

<img width="935" alt="pixelated" src="https://user-images.githubusercontent.com/1472599/85200136-7f463900-b2fd-11ea-84f1-c03e9726ca4b.png">

What has to be done to fix this?

**Comment by SteveDaulton** [comment]
You seem to be missing the elephant in the room.
![distortion](https://user-images.githubusercontent.com/11681097/85202762-b10ccf00-b300-11ea-850a-061b94ff6aa1.png)
Development is largely a matter of priorities. Yes it would be nice if the GUI was prettier, but with a small number of volunteers developing Audacity and only 24 hours in a day, it is necessary to prioritise those parts that are most important for the intended task. 
Personally I believe that sound quality is much higher priority that whether the graphics look a bit pixilated when using a very large display.

**Comment by Kwadz** [comment]
Hahaha, yes that's the first mp3 that I found, didn't even look at it.

Anyway, I've asked the steps to implement that to check if I'd be able to do it.
So, feel free to give some guidance if you have an overview in mind.

**Comment by cybear** [comment]
I'm also interested in learning where to begin looking in order to try and fix this. 
For instance, is this a missing feature for the wxWidget library?

**Comment by JamesCrook** [comment]
Supporting HiDPI has shot up the agenda recently.  It's actively being discussed about how to and what can be done easily.

@cybear We need to change how we use wxWidgets (we use some default scaling), but we currently believe wxWidgets is weak in this area.  Fulling fixing may only happen after a change of toolkit.  We're planning on creating component png images at 2x resolution and scaling down for Lo DPI, and using HiDPI aware scaling in the text that we draw ourselves (text that is part of standard controls that we don't draw is believed OK).

**Comment by JamesCrook** [comment]
See also issue #503

**Comment by verhovsky** [comment]
On Audacity 3.7.3 on my M1 Macbook Air 2021, macOS 15.3.2 with a Studio Display (5120x2880), everything except for text in the outer UI is noticeably blurry. Everything in the waveform is blurry, all the icons are noticeably low resolution, the "h/m/s" in the bottom are noticeably blurrier than the numbers.

<img width="317" alt="Image" src="https://github.com/user-attachments/assets/2baed8f9-3e5f-4d84-9565-75bbeb92e529" />
