### ISSUE TITLE
Crash when opening a project

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5842]
### Steps to reproduce

1. Download [the project](https://github.com/audacity/audacity/files/8192886/Sliding.Stretch.Bug.zip)
2. Try to open it in 3.4.2/recent master build

### Expected behavior

No crash

### Actual behavior

A crash. Any subsequent launch of Audaicity will result in a crash too (even if the project is discarded in the Project Recovery dialog) unless audacity.cfg is purged.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS

**Comment by petersampsonaudacity** [comment]
@dozzzzer 

So what is special about "the project" - how was it created ?

**Comment by dozzzzer** [comment]
@petersampsonaudacity no idea how exactly it was created, but it was taken from this issue: https://github.com/audacity/audacity/issues/2637

**Comment by petersampsonaudacity** [comment]
@dozzzzer 

Testing on W10 with 3,4,2 and latest 3.2.5 I cannot reproduce this.

"the project" opens fine in both versions.

**Comment by dozzzzer** [comment]
@petersampsonaudacity Cannot reproduce it myself anymore.
