### ISSUE TITLE
When importing a music file, Audacity looks for the tempo value in the entire file path, not the file name

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5851]
### Steps to reproduce

1. have a directory with the tempo value in its title, e.g. "140 bpm project"
2. Place the loop of the tempo that is different from 140 bpm in this folder
3. Try to import that file into Audacity
4. Observe

### Expected behavior

The file tempo is detected correctly.

### Actual behavior

The file tempo has been mistakenly detected as 140 bpm; Apparently, the entire file path is parsed upon import, not only the file name part.

### Audacity Version

current master / alpha / nightly build

### Operating system

Other

### Additional context

Related https://github.com/audacity/audacity/pull/5570

**Comment by LWinterberg** [comment]
FWIW: My library has some resources which are structured this way. 

![image](https://github.com/audacity/audacity/assets/87814144/3a8983da-14fa-4f42-86ca-dd23083fcfda)

In my case the files themselves also have BPM information in the title, but I wouldn't put it past someone to include information common to all items in the folder (eg key and bpm) and naming the actual files themselves "version 1", "version 2", ...

**Comment by saintmatthieu** [comment]
So what should we do? Look for the latest BPM occurrence in the complete path and use it?

**Comment by saintmatthieu** [comment]
Well done @dozzzzer for spotting this.

**Comment by LWinterberg** [comment]
> So what should we do? Look for the latest BPM occurrence in the complete path and use it?

Just went through that idea with @DilsonsPickles and it seems like a pretty safe option to proceed with.

**Comment by saintmatthieu** [comment]
> ### Steps to reproduce
> 1. have a directory with the tempo value in its title, e.g. "140 bpm project"
> 2. Place the loop of the tempo that is different from 140 bpm in this folder
> 3. Try to import that file into Audacity
> 4. Observe
> 
> ### Expected behavior
> The file tempo is detected correctly.
> 
> ### Actual behavior
> The file tempo has been mistakenly detected as 140 bpm; Apparently, the entire file path is parsed upon import, not only the file name part.
> 
> ### Audacity Version
> current master / alpha / nightly build
> 
> ### Operating system
> Other
> 
> ### Additional context
> Related #5570

Agreement during triaging was reached that the actual behaviour is also the expected behaviour.
@LWinterberg in case there are conflicting BPM values in path and title, e.g. "./140bpm collection/130bpm loop.wav", it is already so that the last occurrence is used.
