### ISSUE TITLE
Crash upon closing realtime Reverb effect on Windows

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5860]
### Steps to reproduce

1. generate mono chirp
2. hit Play
3. add Reverb effect to the stack
4. open its UI
5. tweak some parameters (e.g. Room Size, Pre-delay etc.)
6. close by clicking the Cross icon in the upper right corner
7. open up the UI again
8. close again by clicking the Cross icon

### Expected behavior

No crash

### Actual behavior

A crash

https://github.com/audacity/audacity/assets/70063970/d0c8d2ee-7270-4571-9e94-607e40f552cc

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

### Additional context

Not reproducible on macOS

**Comment by petersampsonaudacity** [comment]
This appears to be a regression on 3.4.2

**Comment by petersampsonaudacity** [comment]
Does **_NOT_** affect the other real-time enabled Audacity effects

**Comment by dozzzzer** [comment]
This issue appears not to be a regression. It has existed since Reverb was made available for realtime use, i.e., since 3.3.0.

**Comment by JoeS209** [comment]
The root cause appears to be that the &data shared pointer reference is bad in the call to EnsureIndex() (ClientData.h line 526 in Audacity 3.4.2).  I don't yet know why.

**Comment by JoeS209** [comment]
I've debugged a bit further and it seems that the root cause here is that the mpProject pointer inside the mEffectUIHost->GetEditor()->Subscribe callback lambda inside RealtimeEffectStateUI.cpp!RealtimeEffectStateUI::Show is NULL.  If I add a NULL check inside the callback code such that it looks like this, it seems to fix the problem.  This is at RealtimeEffectStateUI.cpp line 117:

`
   mParameterChangedSubscription = mEffectUIHost->GetEditor()->Subscribe(
      [this](auto) { /* assert(mpProject); */
                     if (mpProject) {  // Add this check here
                        UndoManager::Get(*mpProject).MarkUnsaved();
                     }
                   });
`

**Comment by Paul-Licameli** [comment]
> I've debugged a bit further and it seems that the root cause here is that the mpProject pointer inside the mEffectUIHost->GetEditor()->Subscribe callback lambda inside RealtimeEffectStateUI.cpp!RealtimeEffectStateUI::Show is NULL. If I add a NULL check inside the callback code such that it looks like this, it seems to fix the problem. This is at RealtimeEffectStateUI.cpp line 117:
> 
> ```
>    mParameterChangedSubscription = mEffectUIHost->GetEditor()->Subscribe(
>       [this](auto) { /* assert(mpProject); */
>                      if (mpProject) {  // Add this check here
>                         UndoManager::Get(*mpProject).MarkUnsaved();
>                      }
>                    });
> ```

Excellent!  Please make a pull request from this fix.

**Comment by JoeS209** [comment]
Great.  I'll try to get that put together today.

**Comment by dozzzzer** [comment]
Tested
