### ISSUE TITLE
Changing clip speed during playback possible with "change speed" menu

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#5863]
### Bug description

Changing the amount of time stretching of clips during playback is not supported and is supposed to be disabled. However, one can still do this with the change-speed menu

### Steps to reproduce

1. Create a clip
2. Start playback
3. Right-click the clip
4. select the "change speed" option

### Expected behavior

Changing the clip's speed should be disabled.

### Actual behavior

It is possible. The clip is visually stretched, but the audio continues as though it weren't.

### Audacity Version

other

### Operating system

Windows

### Additional context

Discovered on alpha, but it most likely is present in 3.4.2 already.

**Comment by saintmatthieu** [comment]
@LWinterberg I suppose the "Change speed" menu item should be grayed out then ?

**Comment by petersampsonaudacity** [comment]
> I suppose the "Change speed" menu item should be grayed out then ?

Certainly makes sense to me to gray it out during playback.

**Comment by LWinterberg** [comment]
Definitely.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @saintmatthieu 's latest branch for this:  audacity-win-3.5.0-alpha-20240202+81dc5f9-x64-msvc2022

Pitch and Speed  changing appears to work while Audacity is playing - but there are some issues of note:

1) when Audacity is playing and you hover the cursor over the Clip-handle drag bar the cursor icon that you get is a **white no-entry**  icon - to me this implies that no action is available but clicking on it still brings up the drag-bar context menu, including the **Pitch and Speed** command.
This is **_not_** introduced as part of this change - the same occurs in 3.4.2

2) when Audacity is playing the **Clip Speed %** in the **Pitch and Speed** dialog is grayed-out and unavailable.  
This is _**not**_ the case when the command is invoked while Audacity is not playing.
![image](https://github.com/audacity/audacity/assets/50205984/8383c245-1445-45e4-b5cf-474e9d6cbb54)

3) The **Pitch and Speed** context menu :command has a much reduced UI compared to the **Effect > Pitch and Tempo > Change Speed and Pitch** menu command:
![image](https://github.com/audacity/audacity/assets/50205984/b633326e-093c-4d2e-865e-81a65800f672)

4) I was really expecting the **Change Speed and Pitch** effect to be a further Audacity command that would now be available in the Real-time effects stack - and not just a clip-handle context menu.

5) In the clip-handle context menu command dialog for **Pitch and Speed** - you appear to be able to change pitch and speed independently.  
This appears to contrast with what happens with the **Effect > Pitch and Tempo > Change Speed and Pitch** menu command.
