### ISSUE TITLE
[Plugin issue] Nyquist effect “Vocal Reduction and Isolation” outputs NaN samples at silent parts and sometimes at random

### ISSUE THREAD

**Issue by Openstreetmapler** [audacity/audacity#5864]
### Plugin

Vocal Reduction and Isolation

### Plugin Format

Nyquist

### Plugin source

Shipped with Audacity 3.4.2

### Bug description

The _Vocal Reduction and Isolation_ effect (v3.0.1-2) that comes with Audacity 3.4.2 has some problems that causes it to output `NaN` samples†:
- Weird, but not too bad: The effect outputs `NaN` samples where both stereo channels of the input are perfectly silent (float value `0.0`).
- **Quite annoying, makes the effect unreliable:** The effect sometimes randomly outputs `NaN` samples in a short section of audio (completely wiping the original samples), which causes unexpected silences on playback.

† I know that they’re `NaN` thanks to _Sample Data Export_.

### Steps to reproduce

1. Set your default sample format to **32-bit float** if it isn’t already.
2. Import this audio file: https://github.com/audacity/audacity/assets/9383930/d1d46535-7547-4317-93cb-7c4c31004220
3. Select the whole track.
4. Open the Nyquist effect _Vocal Reduction and Isolation_.
5. In the effect, choose any action except the “to mono” and “analysis” options, then apply.
    - The other parameters have no influence on the bug’s occurrence.

### Expected behavior

- The effect is being applied as it’s supposed to.
- Sections where both stereo channels of the input audio are perfectly silent (float value `0.0`) should still be float value `0.0` after applying the effect.

### Actual behavior

Sections where both stereo channels of the input audio are perfectly silent (float value `0.0`) will be output as `NaN`. This does not happen with the “to mono” effect actions.
<img width="1617" alt="Audacity screenshot: testing different configurations of the Vocal Reduction and Isolation effect" src="https://github.com/audacity/audacity/assets/9383930/c98791c9-2ed5-4716-afee-a8aff24ceda2">
Look at the beginning of the tracks: `NaN` samples are rendered in a weird and inconsistent way (you will notice that when zooming in).

Sometimes and only with specific files, random sections of audio will turn into `NaN` samples, too. With the uploaded audio file, this happens once: around 2:38.5 – but **only** with the actions _Remove Mid_, _Isolate Mid_, _Isolate Mid and Invert_.
<img width="1617" alt="Bildschirmfoto 2024-01-13 um 17 54 00" src="https://github.com/audacity/audacity/assets/9383930/a7ed6a0b-bd7e-40de-919d-93c3da4f757c">
Roughly 8225 samples (which are selected in the screenshot) are affected. As with the previous screenshot, `NaN` samples render weirdly and inconsistently. With the same input audio, these `NaN` samples always occur in the same spot.

The bug only occurs with the **32-bit float** sample format; **24-bit PCM** is not affected. However, it is tedious to normalize (to prevent clipping) and convert an audio track to 24-bit PCM just for this effect to work properly.

### Audacity Version

3.4.2 (updated from an older version using Muse Hub)

### Operating system

macOS

### Architecture

Apple Silicon (M1, M2, ...)

### Additional context

Audacity version 3.4.2 with commit ID: 9dd60f

**Comment by LWinterberg** [comment]
I didn't know you could even write NaN into Audacity projects

**Comment by getCursorsExe** [comment]
Unable to reproduce on Windows 11. I think this is macOS-exclusive bug

**Comment by SteveDaulton** [comment]
If found to be reproducible, this bug  should be higher that P1. The presence of even a single NaN can cause massive problems in a project, including substantial data loss.
I've not been able to reproduce the problem on Linux.

**Comment by saintmatthieu** [comment]
Could someone from QA bisect this ? As reported, it's already present in ` 9dd60f`, but in fact the issue seems to have been introduced earlier. That would help, because Nyquist + MacOS makes it particularly tedious for me to pinpoint.

**Comment by saintmatthieu** [comment]
I suspect the bug to be inside the `vocalrediso.ny` script. Looking into this file's history to see suspicious changes.

**Comment by saintmatthieu** [comment]
I take back what I said: the bug was introduced by 3.4 and that nyquist file didn't undergo any change since 3.3.

**Comment by saintmatthieu** [comment]
@dozzzzer managed to reproduce this on versions older than 3.3.3. The ticket was accordingly de-prioritized.

**Comment by SteveDaulton** [comment]
> The ticket was accordingly de-prioritized.

Just ensuring that you know that NaN's are very bad news for Audacity projects that can destroy user's work.

**Comment by LWinterberg** [comment]
Between the factors of
* This issue has been a thing for a long time (ie isn't a recent regression)
* The effect being written in lisp/nyquist, which none of the team is proficient in
* The effect is only very situationally useful
* There is a replacement coming in form of the openVINO source separation

I'd say that it's time to relegate this effect to the plugin site. The question is: Do we do it for 3.5 or 3.6? Earlier today I thought 3.6 was more appropriate as we'd likely have a more robust installer or openVINO ready by then, but now I think the more disruptive option of removing it now and adding openVINO later is the better way - especially as people could still install the effect as a plugin if they really wanted to.

**Comment by saintmatthieu** [comment]
@SteveDaulton as far as I could debug, my primary suspect is the nyquist script itself (which indeed hasn't been modified since 3.3.3) rather than its integration, since such NaN problem isn't known for other scripts, and even for this one, it depends on which option you choose and hence which branch of the script gets executed. I suspect an unseen division by zero. In case you'd like to give fixing it a try ?

**Comment by SteveDaulton** [comment]
I'm not able to reproduce the issue (on Linux). Is it only reproducible on macOS with Apple Silicon? Is it easily reproducible, or moon-phase?

The options in Vocal Reduction and Isolation in which the bug  appears are those that use FFT in Nyquist. It may be worth asking Roger Dannenberg about this as the issue may be in Nyquist's implementation of FFT / IFFT (which is written in C ).

Has it been established when this bug first appeared? If it was 3 years ago, it may be worth taking a look here: https://github.com/audacity/audacity/tree/master/lib-src/libnyquist/nyquist/ffts

**Comment by SteveDaulton** [comment]
> I didn't know you could even write NaN into Audacity projects

Perhaps it would be possible to make that the case? For example, writing NaN samples as 0 (zero) may not always be "correct", but it would be far less damaging.

**Comment by SteveDaulton** [comment]
> @dozzzzer managed to reproduce this on versions older than 3.3.3. The ticket was accordingly de-prioritized.

Was that on a Silicon "M" chip?

The effect appears to be perfectly safe on Windows and Linux, and Peter tells me that he is not able to reproduce the bug on his Mac. Considering that the  OpenVINO plug-in is only available for Windows, it would be very helpful for Intel Mac users to know if it is safe to use this plug-in.

**Comment by Openstreetmapler** [comment]
> ### Architecture
> 
> Apple Silicon (M1, M2, ...)

As I stated in the original post, this occurs on the Apple Silicon (M1) architecture.

**Comment by SteveDaulton** [comment]
Thanks @Openstreetmapler, but I'm wanting to know if the bug is _only_ on Apple Silicon. If it is, then the red warning on https://plugins.audacityteam.org/nyquist-plugins/effect-plugins/filters-and-eq#vocal-reduction-and-isolation should say that, so that Intel Mac users know that it is still OK to use the plug-in.

I think this is important since the replacement for this effect (the OpenVINO plug-in) is only available for Windows. Audacity users on other platforms have to find an alternative.

**Comment by Openstreetmapler** [comment]
> Thanks @Openstreetmapler, but I'm wanting to know if the bug is _only_ on Apple Silicon. If it is, then the red warning on https://plugins.audacityteam.org/nyquist-plugins/effect-plugins/filters-and-eq#vocal-reduction-and-isolation should say that, so that Intel Mac users know that it is still OK to use the plug-in.
> 
> I think this is important since the replacement for this effect (the OpenVINO plug-in) is only available for Windows. Audacity users on other platforms have to find an alternative.

@SteveDaulton I don’t know for sure. I _could_ do some testing on that old 2011 iMac, but it would be really tedious for me to do that (I don’t have patience for such stuff).

For the time being, until more precise info about the behavior on Intel macOS is available, I suggest rewriting the warning to something like the following:
> Warning: This effect causes data loss on the Apple Silicon version of macOS, and _maybe_ Intel macOS too. See [#5864](https://github.com/audacity/audacity/issues/5864) for details.

**Comment by Openstreetmapler** [comment]
By the way, as a replacement for both OpenVINO and _Vocal Reduction and Isolation_, I currently use [Phantom Center by Bertom Audio](https://www.bertomaudio.com/phantom-center.html) – this VST3/AU plugin is compatible with both Intel and Apple Silicon (arm64) macOS. The developer relies on the pay-what-you-want model, allowing you to get the software for free, e. g. if you have neither a credit card nor PayPal (like me).

Just like vocalrediso.ny, the plugin has low-/high-pass settings and with the Mix slider, you can choose anything between “Remove center” (left) and “Isolate center” (right).

**Comment by JamzTyson** [comment]
>I currently use [Phantom Center by Bertom Audio](https://www.bertomaudio.com/phantom-center.html)

Do you know if that uses DFT to determine correlation, or just the simple "invert and add" method? ("Vocal Reduction and Isolation" has both, and it is only the DFT algorithm that has the problem).

**Comment by Openstreetmapler** [comment]
> > I currently use [Phantom Center by Bertom Audio](https://www.bertomaudio.com/phantom-center.html)
> 
> Do you know if that uses DFT to determine correlation, or just the simple "invert and add" method? ("Vocal Reduction and Isolation" has both, and it is only the DFT algorithm that has the problem).

Being named “Phantom Center”, this plugin has to use DFT which preserves the stereo image and allows extraction of the perceived stereo center in the first place.

With the simple “invert and add” method, you can only get the stereo side in mono (not stereo) and you cannot extract the perceived stereo center at all.

**Comment by kryksyh** [comment]
@SteveDaulton @LWinterberg I can confirm that the same Audacity universal-binary build produces different results on M-chip depending on Rosetta2 was used or not. 
I highly doubt that the issue with the plugin itself, and other plugins might be affected as well.

If we are to support nyquist in AU4 this issue has to be investigated further.
