### ISSUE TITLE
Tempo and upper time signature: using German or Norwegian keyboard, can't enter digits 8 or 9

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#5868]
### Steps to reproduce

Using a German keyboard layout:
1. Set the tempo control to be the focus
2. Type 8 or 9

### Expected behavior

The digit 8 or 9 is entered.

### Actual behavior

If there are no tracks in the project, nothing happens.
If there are tracks, then the Set left selection boundary or Set right selection boundary dialog opens

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

See similar issue when there was a control for the project rate in the main window: https://github.com/audacity/audacity/issues/1548

There may be other keyboard layouts which are affected.

**Comment by dozzzzer** [comment]
Tested
