### ISSUE TITLE
Failed to open the scripting pipe file on Windows 10

### ISSUE THREAD

**Issue by MAbjadpour** [audacity/audacity#587]
**Test environment**
- Python 3.6
- Windows 10 Version 1803 (OS Build 17134.1550)
- Audacity Version 2.3.2 build information: 
-- Date: May 4 2019
-- Commit Id: bd2956 of Sat May 4 11:38:57 2019 +0100
-- Build type: Release build
-- Compiler: MSVC 19.16.27027.01

Apparently, checking for the existence of Audacity temporary files for reading from and writing into ([here ](https://github.com/audacity/audacity/blob/16d52f63a4183bba77ef7305d14622958dc0d1d5/scripts/piped-work/recording_test.py#L71)and [here](https://github.com/audacity/audacity/blob/16d52f63a4183bba77ef7305d14622958dc0d1d5/scripts/piped-work/recording_test.py#L77)), causes those files to be removed somehow. 

Both `if` statements turn out to be `True`, however, the following error raises as we try to `open()` the files:
`OSError: [Errno 22] Invalid argument: '\\\\.\\pipe\\ToSrvPipe'`

----

**Fix**

Removing both `if` statements causes both `TOFILE = open(TONAME, 'w')` and `FROMFILE = open(FROMNAME, 'rt')` to be executed successfully.

**Comment by SteveDaulton** [comment]
Please include the exact version number of the Audacity build that you are using.
If you are using a pre-release version of Audacity, please include the Git commit number.

**Comment by MAbjadpour** [comment]
I just edited the issue.

**Comment by SteveDaulton** [comment]
Audacity 2.3.2 is an old version. 
recordingtest.py was updated and tested to work with Audacity 2.4.1 / 2.4.2.
