### ISSUE TITLE
Git master source does not build on Arch Linux.

### ISSUE THREAD

**Issue by evertvorster** [audacity/audacity#5877]
### Bug description

It seems that the recent acidizer tags commits broke compilation on Linux. 
I believe that this is the line in the build log that points this out, but I will attach a full build log for completeness:
```
[ 62%] Built target lib-vst
In file included from /mnt/int/system/aur/audacity-local-git/src/audacity/libraries/lib-import-export/GetAcidizerTags.cpp:14:
/usr/include/sndfile.h:359:33: error: conflicting declaration ‘typedef struct sf_private_tag SNDFILE’
  359 | typedef struct sf_private_tag   SNDFILE ;
      |                                 ^~~~~~~
```

### Steps to reproduce

Build Audacity on Linux from source pulled from git master according to the build instructions listed in Github.

### Expected behavior

A clean build.

### Actual behavior

It fails to build the program. 

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

[2024-01-20_Audacity_Build_Failure.txt](https://github.com/audacity/audacity/files/13999252/2024-01-20_Audacity_Build_Failure.txt)

This is the same build script that is used to build Audacity for the longest time, and it's only after the recent changes in Git Master that it started failing to build. 

About my system:
```
Operating System: Arch Linux 
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.114.0
Qt Version: 5.15.12
Kernel Version: 6.6.10-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 32 × 13th Gen Intel® Core™ i9-13900HX
Memory: 62.5 GiB of RAM
Graphics Processor: Mesa Intel® Graphics
Manufacturer: TUXEDO
Product Name: PD5x_7xSNC_SND_SNE
System Version: Not Applicable
```

**Comment by crsib** [comment]
I would still say that using `master` is very much not advisable :-)

**Comment by evertvorster** [comment]
Can confirm that this is fixed now. 
Who's going to find all bugs if no one is running master?

My bug reports are not THAT bad?

**Comment by crsib** [comment]
> My bug reports are not THAT bad?

It's not what I mean :-) But sometimes evil stuff gets into master, that can ruin your workflows :-)
