### ISSUE TITLE
Horizontally duplicating tempo-estimated clip sometimes merges

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#5878]
### Bug description

After music file import, duplicating clip horizontally sometimes merges the clip.

### Steps to reproduce

1. Import [this file](https://drive.google.com/file/d/19s9gSyxzz1jXyWVw1DpZbM4XXUX7m8e7/view?usp=drive_link) ; say yes to music-file-import prompt
2. Make sure that snap is enabled to some musical duration, e.g. 1/16
3. Select all
4. Copy
5. Press right key to position the cursor at Bar 4,
6. Paste
7. Press right key again
8. Paste

### Expected behavior

You now have three clips

### Actual behavior

You only have two: clips 2 and 3 got merged

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

**Comment by dozzzzer** [comment]
@saintmatthieu on macOS, the original issue persists:

<img width="450" alt="image" src="https://github.com/audacity/audacity/assets/70063970/44b925ed-c195-4b50-8ad8-7c9f1d8de1f5">

**Comment by dozzzzer** [comment]
Tested
