### ISSUE TITLE
No hovertext tooltip for the Clip-handle drag-bar

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#5882]
### Bug description
There is no hovertext tooltip for the Clip-handle drag-bar.

This leads to many users not "discovering" it (as evidenced by many posts on the Forum - many of which complain the the Time-Shift tool is missing from the Tools toolbar)

### Steps to reproduce
1. get some audio
2. hover over the Clip-handle drag-bar
3. Observe: cursor changes to open gloved hand (which is good)
4. Observe: there is no hovertext tooltip 

### Expected behavior
A hovertext tooltip would be extremely useful

### Actual behavior
There is no hovertext tooltip for the Clip-handle drag-bar.

### Audacity Version
3.4.2 and latest 3.5.0 alpha (in fact all Audacity versions that have Clip-handle drag-bars).

Th open gloved hand correctly changes to a closed gloved hand when the user clicks on the drag-bar - this indicates that dragging is possible _(necessary, but not sufficient)_.

### Operating system
Windows 10 - but assume all OS

### Additional context
None

**Comment by LWinterberg** [comment]
A tooltip is not a solution here. 

This situation occurs when someone with a strong mental model of Audacity pre-3.1 uses modern Audacity for the first time. They are *expecting* the timeshift tool in the top and then get confused it's not there, and there also isn't anything else with an <--> -identity anywhere else in the app. 

The clip headers also are fairly muted in appearance to the point they may fade into invisibility, as opposed to something front-and-center like the waveform-blue or the track-name overlay. 

Between those factors, it's extremely unlikely the users upgrading from old versions will hover their mouse over the clip handles not understanding what they are - and much more likely that they don't notice them in the first place.

Or to put it in another way, if it was an issue with the inherent discoverability of the feature, we'd be getting a steady stream of posts from new users asking how to move clips. But we're not, we're getting a steady stream of posts asking on where the timeshift tool has gone to.

If update checking had been available for longer, this wouldn't be an issue. 

There's a slight argument to be made that the clip handles should be a different color to be even easier recognizable. I might get to that next time I feel inclined to do UI stuff.
