### ISSUE TITLE
After importing a non-looped clip, subsequent loop import won't trigger auto tempo detection

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5890]
### Steps to reproduce

1. Make sure automatic tempo detection is set to "Ask me each time" in Preferences
2. File > Import
3. Select a one-shot audio clip (e.g. a hi-hat sound)
4. File > Import
5. Select a music loop audio file under 1 minute
6. Observe

### Expected behavior

Music Import dialog pops up:

<img width=450 src=https://github.com/audacity/audacity/assets/70063970/2eb36d76-a73d-41ea-b162-33edc2ffff1b>

### Actual behavior

Music Import dialog isn't there; all subsequent loops are imported as regular audio files with no tempo detection mechanism triggered.

### Audacity Version

current master / alpha / nightly build

### Operating system

Other

**Comment by saintmatthieu** [comment]
@dozzzzer this is intended behaviour. See https://github.com/audacity/audacity/pull/5570, "importing on a non-empty project, if the view is in minutes and seconds, nothing happens".
