### ISSUE TITLE
Timeline options button improvements

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#5894]
in scope for 3.5:

- [x] The timeline options button currently assumes the appearance of the playhead and has 4 states. It really only needs 1. 
- [x] The timeline options button is hard to recognize as an options button and needs a different icon.
- [x] The "pin" metaphor for the pinned playhead is not terribly helpful. Let's remove it.
- [x] Some options inside the timeline options button are hard to understand ("update display while playing"), so some strings can be clarified

nice-to-haves eventually: 
- (code: There seems to be a large amount of scaffolding to allow for multiple buttons in there, which is unused. This may be something which can be cleaned up)

**Comment by petersampsonaudacity** [comment]
Note that the Timeline options can also be accessed from the context menu you get from right-clicking anywhere in the Timeline (including right-clicking on the Options button) .

And this is the same menu, so maybe the options button isn't need at all and the user can just rely on context menu right-click - a gesture that is available in many other places in Audacity (and other apps) so users should be fairly used to that.

**Comment by petersampsonaudacity** [comment]
I seem to recall that in much older versions of Audacity that green button in the Time was _**just**_ used to pin/unpin the playhead (which is why it looks like a playhead icon)

**Comment by petersampsonaudacity** [comment]
I have added P1s in the manual to track this in the documentation

**Comment by petersampsonaudacity** [comment]
I have updated the Manual for this change  - with the exception of one page that I'll tackle over the weekend
