### ISSUE TITLE
Improve delay compensation of pitch shifting

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#5905]
### Your idea

https://github.com/audacity/audacity/issues/5206 improved the delay estimation when using time stretching. The problem is back with pitch shifting. Something seemingly was omitted.

### Problem to be solved

Time-alignment of clips is important for synchronization and also to reduce the risk of discontinuities when looping a pitch-shifted clip.

**Comment by dozzzzer** [comment]
tested!

**Comment by dozzzzer** [comment]
Tested
