### ISSUE TITLE
Occasional crash in tempo estimation

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#5906]
### Bug description

Importing that audio file sometimes crashes Audacity: [AudacitySpectral.zip](https://github.com/audacity/audacity/files/14126902/AudacitySpectral.zip)

### Steps to reproduce

1. On empty project, import that file

### Expected behavior

File opens

### Actual behavior

Audacity crashes

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

### Additional context

Crash occurs in PFFFT, when used by the recently introduced tempo-estimation algorithm.
Seems intermittent (??)

**Comment by dozzzzer** [comment]
Tested

**Comment by saintmatthieu** [comment]
Here too, @Paul-Licameli you may merge.
