### ISSUE TITLE
Loop tempo metadata persists through imports

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#5914]
### Bug description

The tempo metadata of an imported loop, when present, remains in memory. Upon any subsequent file import, whether music or not, that metadata will be interpreted as being that of those new files, too.

### Steps to reproduce

1. Extract these files: 
[persistent-metadata-bug.zip](https://github.com/audacity/audacity/files/14167477/persistent-metadata-bug.zip)
2. Import `square.wav`. Tempo isn't detected.
3. Delete the track. Import `tagged-70.wav`. 70BPM is detected.
4. Remove the track.
5. Change project tempo to something other than 70.
6. Import again `square.wav`.

### Expected behavior

Tempo isn't detected.

### Actual behavior

 It gets detected as 70BPM.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS

**Comment by dozzzzer** [comment]
Tested
