### ISSUE TITLE
[MacOS] Performance is HORRID on systems with HDPI displays

### ISSUE THREAD

**Issue by jadenquinn** [audacity/audacity#5922]
### Bug description

Audacity runs fine on most systems, but on any Mac with scaling (like any MacBook Pro made after 2012, and now ALL Macs as of 2020) Audacity runs so sluggishly that, because it's a single core application, will make it almost unusably laggy. I'm talking like if I press a button, like zoom for example, it can take a second or two. This doesn't really limit Audacity's functionality, but it just seems like such a fixable problem that doesn't need to exist. Keep in mind: Audacity does not need to be in view on the screen for it to have these problems, as it uses the same amount of CPU power when offscreen as onscreen, so this problem is 2-fold. It's causing the system to overheat and the application is lagging. Audacity is trying to do too much on one core. I turned this Mac's scaling off (i9 MacBook Pro) and this problem mostly went away, however if I turn the resolution to 1080p, this is still a problem, however it uses about half the power, but it's still a crap ton. The Audacity display seems to not like running at high resolutions, 1080p+, or it will... ok it is always a little laggy no matter what, but anything above 1440p is just awful. Please fix the lag.

### Steps to reproduce

1. Get a Mac with a Retina display.
2. Download Audacity.
3. Start recording.
4. Widen your eyes as you see how laggy the UI is.

### Expected behavior

I expect Audacity to not lag this much on an i3, let alone an i9.

### Actual behavior

Extreme lag.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS

### Additional context

HDPI is what MacOS people call the scaling that Apple uses with Retina displays and such, however one can use this HDPI scaling function with any 4K display I believe.

I have also made it function under low power mode, which on Intel MacBook Pros basically disables some background operations, but also turns off Intel Turbo Boost, which when Audacity is recording, will make one core boost at ALL TIMES to 4.8-5GHz, effectively keeping it at 100C/212F which is not good for any machine, keep in mind this is with the fans manually at full blast, so when I turn on low power mode, it turns turbo boost off, and instead of that one single core using 40W, it now uses like 5 or 6W, but this makes Audacity 3x LAGGIER... of course, but at least it's not trying to start a fire anymore.

**Comment by dozzzzer** [comment]
On MacBook M1 Pro, I don't experience such an issue either with the built-in or with an external display. With non-scaled resolutions, recording into Audacity loads the CPU at about 38-41% and the interface is perfectly usable.

**Comment by crsib** [comment]
This is a known issue, I don't expect it to be fixed in Audacity 3 timeline.

It is related to how Audacity draws the interface. When the interface scrolls it easily overloads the Intel Macs.

**Comment by jadenquinn** [comment]
> On MacBook M1 Pro, I don't experience such an issue either with the built-in or with an external display. With non-scaled resolutions, recording into Audacity loads the CPU at about 38-41% and the interface is perfectly usable.
> 
> 
> 
> 

Ah, alright. This might not be a problem on the Apple Silicon builds then? Not too sure. I can't say I've had the same issue on my M2 Pro Mac mini on my 4K display either really, however if Audacity is using 40% of your CPU just drawing the interface... that's horrible and there still seems like there's something wrong.

**Comment by jadenquinn** [comment]
> This is a known issue, I don't expect it to be fixed in Audacity 3 timeline.
> 
> 
> 
> It is related to how Audacity draws the interface. When the interface scrolls it easily overloads the Intel Macs.

Awesome! Are there builds of this 3.0 timeline or whatever that I can just nab real quick, or do I have to build myself from source or something?

**Comment by crsib** [comment]
This won't be fixed for the 3.x builds.

**Comment by jadenquinn** [comment]
> This won't be fixed for the 3.x builds.

Then when will it be fixed?

**Comment by LWinterberg** [comment]
We're redoing the entire UI in a new framework for 4.0

**Comment by jadenquinn** [comment]
> We're redoing the entire UI in a new framework for 4.0

Oooh, nice! Will this version be compatible with MacOS 10.13?

**Comment by jadenquinn** [comment]
> We're redoing the entire UI in a new framework for 4.0

Would be really nice to know!

**Comment by LWinterberg** [comment]
> Will this version be compatible with MacOS 10.13?

I don't believe Qt6 supports that version, no.

**Comment by kryksyh** [comment]
> I don't believe Qt6 supports that version, no.

Unfortunately, yes, the oldest supported version is 10.14
