### ISSUE TITLE
Labels: Export as subtitle formats

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#5924]
### Your idea

Labels should be exportable as subtitle formats, such as VTT or subrip (SRT)

### Problem to be solved

The current label export format looks like this: 

```
105.000000	106.200000	 text1
106.200000	109.160000	 text2
```

This is a perfectly fine format, but it isn't supported by anything else. This means that if you're using the transcription plugin, or otherwise used Audacity to subtitle things, you can't easily use it elsewhere. 

YouTube supports a wide range of subtitle formats, the easiest ones probably being [WebVTT](https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API): 

```
0:01:45.000 --> 0:01:46.200
text1

0:01:46.200 --> 0:01:49.160
text2
```

The conversion between those two formats isn't entirely trivial to the end user (especially the sss.µµµµµµ to hh:mm:ss.ttt conversion) so being able to export in this format would make things a lot more viable and fit well into subtitle workflows. 

### Prior art

This has an ancient PR in https://github.com/audacity/audacity/pull/394

**Comment by leodom** [comment]
Hello, thanks for the work on this labels export !

I am using version 3.4.2, how can I install/use the export label plugin ?

**Comment by LWinterberg** [comment]
It's not a plugin, it's part of the upcoming 3.5 release which will release later this month.
