### ISSUE TITLE
Extra menu: duplicate access key.

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#5928]
### Steps to reproduce

1. Open the Extra menu using the keyboard
2. Press the access key for Timeline, T

### Expected behavior

Timeline sub menu opens

### Actual behavior

Timeline is selected but sub menu does not open, because Track also has the access key T.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

**Comment by LWinterberg** [comment]
I suppose Timeline can go on m instead

**Comment by DavidBailes** [comment]
> I suppose Timeline can go on m instead

Yes, I've submitted a PR for this. Please can it be added to 3.5?
