### ISSUE TITLE
Move the Timeline sub menu from the Extra menu to the View sub menu

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#5932]
### Your idea

As in title. See discussion: https://github.com/audacity/audacity/discussions/5931

### Problem to be solved

So the the Timeline menu is easier to Find

**Comment by DavidBailes** [comment]
@LWinterberg . Please could this be added to the 3.5 release.

**Comment by petersampsonaudacity** [comment]
Tested on W10 with @DavidBailes  latest branch build for this  audacity-win-3.5.0-alpha-20240212+3f4bc06-x64

All seems good:

![image](https://github.com/audacity/audacity/assets/50205984/88497273-ee2b-40ac-9a9e-2d4b494cf791)

![image](https://github.com/audacity/audacity/assets/50205984/4e5645d4-8024-4d67-9162-017d8a0857e2)

**Comment by dozzzzer** [comment]
Tested

**Comment by petersampsonaudacity** [comment]
I've updated the 3.5.0 alpha manual for this - a LOT of menu images (Extra menu commands) had to be changed.
