### ISSUE TITLE
Create keybindings for vertical zoom commands

### ISSUE THREAD

**Issue by henrik-jensen** [audacity/audacity#5938]
### Your idea

~~Expose~~ Create keybindings for Vertical Zoom (optionally defaulting to **ctrl+shift+1/2/3**), mirroring the normal zooms keybindings **ctrl+1/2/3**, (**ctrl+2** _Zoom Normal_ mirrored by **shift+ctrl+2** _Zoom Reset_)+ adding some Vertical Center up/down keybindings to mirror the functionality available to the mouse for setting the Vertical Center for the zoom.
Mirror the normal zooms interaction with the mouse-wheel, **ctrl+mouse-wheel** for zooming in/out, with **shift+ctrl+mouse-wheel** for vertical zooming in/out as suggested by @petersampsonaudacity. 

Bonus would be keybindings for the other ~~"dB area"~~ _Vertical Scales_ popup menu items which likewise is only accessible with the mouse. (caveat: some of the menu items disappeared in 3.5.0 alpha. See @petersampsonaudacity's [post](#issuecomment-1937535703).

![image](https://github.com/audacity/audacity/assets/9413242/b07f1d04-54b7-428b-9898-07fd078612d0)
_Vertical Scale_ outlined in red in the screenshot

### Problem to be solved

Main problem is accessibility.
You can't vertical zoom without the mouse as this functionality is dependent on the mouse cursor hovering over the Vertical Scale. And it is not possible to navigate to this area in other ways than with the mouse which exclude or at least complicates help from external automation/accessibility tools.

### Additional context
I've brought this up in the Audacity Help Forum post [Controlling Vertical Zoom without mouse](https://forum.audacityteam.org/t/controlling-vertical-zoom-without-mouse/98227), where [steve](https://forum.audacityteam.org/t/controlling-vertical-zoom-without-mouse/98227/6) points out some of the ambiguated problems that arises with Vertical Zoom opposed to normal Horizontal Zoom.
I don't find the problems Steve points out a big hindrance to give access to Vertical Zoom from the keyboard. There are already some problems present with the current implementation when using the mouse interface. Yes you can decide where to start your zoom, top, bottom, middle, but the precision is so very low with the mouse, that you have to retry again and again to hit the spot you aim for. Using the keyboard for this would be much more in your control, adding some Vertical Center up/down keybindings. (This said with the assumption that there are no technical debt in the source code that makes such functionality impossible.)

#### Edits:
* **Additional context** section: 
   - Rephrased and fixed a badly phrased and incorrect statement "The problems Steve points out are already present for the current implementation...".
 * **Your idea** section:
   - Copied the need for some Vertical Center up/down keybindings to mitigate some of the problems [steve pointed out](https://forum.audacityteam.org/t/controlling-vertical-zoom-without-mouse/98227/6) from the **Additional context** section.
   - Using the correct terminology (thx @petersampsonaudacity)
   - Added @petersampsonaudacity's suggestions.
   - Caveat with 3.5.0 alpha.

**Comment by petersampsonaudacity** [comment]
Just a quick heads-up:

Vertical zooming is changing a little for the upcoming 3.5.0 - and thus so is the Vertical Scale context menu:
![image](https://github.com/audacity/audacity/assets/50205984/2ab93792-1d06-4318-ad46-26c3d256cb9f)

**Comment by petersampsonaudacity** [comment]
To extend this idea:

**Shift modified Ctrl+mousewheel** could be used for vertical scaling in and out

**Comment by henrik-jensen** [comment]
> To extend this idea further:
> 
> **Shift + Ctrl + mousewheel** could be used to effect vertical scaling in and out

How could I have missed that? 👍 

I added "... adding some Vertical Center up/down keybindings to mirror the functionality available to the mouse for setting the Vertical Center for the zoom..." to the **Your idea** section, to mitigate some of the problems pointed out by steve [on the forum](https://forum.audacityteam.org/t/controlling-vertical-zoom-without-mouse/98227/6). Feel like I'm moving the goalpost by editing the Enhancement Request. Hope you still can support it.
(Maybe I should keep additions down in the comment. On the vscode repo the admins monitor the thumps-up count to determine the priority of a proposal. I don't know what the audacity admins/mods/devs policies are but I do feel a bit dishonest changing the Enhancement Request if audacity has a similar policy)

Re: the upcoming 3.5.0
Couldn't find it described in the [roadmap](https://github.com/audacity/audacity/wiki/Roadmap).
Could you point me to where to find the details of this upcoming release?

**Comment by petersampsonaudacity** [comment]
> Re: the upcoming 3.5.0
> Couldn't find it described in the [roadmap](https://github.com/audacity/audacity/wiki/Roadmap) or in the github branches.
> Could you point me to where to find the details of this upcoming release?

I find out what's going on by following the GitHuB Actions: https://github.com/audacity/audacity/actions

and the GitHub Pull Requests:  https://github.com/audacity/audacity/pulls

The Projects>Main section:  https://github.com/orgs/audacity/projects/9

(filtered for 3.5.0) gives an indication of what Muse are planning for the vext release - but I suspect that it may not be a complete list:
https://github.com/orgs/audacity/projects/9/views/1?filterQuery=milestone%3A%22Audacity+3.5%22

**Comment by SteveDaulton** [comment]
There are a couple of plug-ins available [HERE](https://audionyq.com/binding-keys-to-vertically-zoom-tracks/) for zooming in/out on the track that has focus. When installed and enabled you will be able to create keyboard shortcuts of your choice (I'm using the "+" and "-" keys on the numpad).

**Comment by henrik-jensen** [comment]
@petersampsonaudacity
Thanks for the links.  👍 
Good opportunity to into github Actions and Project.

@SteveDaulton 
Thanks for the [script](https://audionyq.com/binding-keys-to-vertically-zoom-tracks/) and for introducing me to the audacity-focussed nyquist website [audionyq.com](https://audionyq.com/). 👍

**Comment by petersampsonaudacity** [comment]
@LWinterberg  is this something that you would consider adding to Audacity ?

It sounds like a good idea to me.

**Comment by LWinterberg** [comment]
Yes

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
