### ISSUE TITLE
Please make the toolbars move strips hidable

### ISSUE THREAD

**Issue by jadenquinn** [audacity/audacity#5939]
### Your idea

Make the little "toolbar" strips on the top panel of items appear with a toggle in the options/settings of Audacity.

### Problem to be solved

Ok so basically I keep clicking on the "toolbar" strip thing next to each menu item on the top, and even time I do, I end up moving whatever is there and after that item to somewhere below this menu area, and that's really annoying, as now I then have to move it all back up again. This has happened more than 20 times, and I have no idea why this wasn't already a toggle that is disabled upon application start.

### Prior art

I've never had this issue with any other programs.

### Additional context

I'm not sure why Audacity left UI configuration strips in plain view where people can frequently misclick them and mess up their UI. Sure, it's a misclick, but when you are forced to use a program like Audacity for long enough, it starts to get so annoying you wish you could just hide the toolbar move strips.

**Comment by jadenquinn** [comment]
I tried to figure out how to add another tag to this but idk how. I was gonna add the UX one.

**Comment by petersampsonaudacity** [comment]
> Ok so basically I keep clicking on the "toolbar" strip thing next to each menu item on the top, and even time I do, I end up moving whatever is there and after that item to somewhere below this menu area, and that's really annoying, as now I then have to move it all back up again.

Rather than "moving it back you can either:

a) use **Edit > Undo** or its shortcut Ctrl+Z  - after you've accidentally moved it

b) Press **Escape** while you are still moving it (with the left cursor button still held down)

----------------------------------------------------------------

_BTW the "little toolbar strips" are called **Clip-handles** and are referred to as **drag-bars**_

**Comment by LWinterberg** [comment]
![image](https://github.com/audacity/audacity/assets/87814144/2be78e92-9701-4ef5-bdfc-02d3a5ad77e4)

Are you talking about toolbar grabbers (red rectangles here) or clip handles (red oval)?

**Comment by petersampsonaudacity** [comment]
Movable and undockable toolbras using the toolbar grabbers has been a feature of Audacity ever since the initial release 1.0.0 (and in fact in the un-released 0.98b prior to 1.0.0).

This is valuable functionality for many users (me included) so I suspect that it's unlikely to be removed or hiiden (or made hideable).  

As far as I can recall this  is the first complaint we have ever had about this in well over 20 years of Audacity since its launch.

**Comment by petersampsonaudacity** [comment]
> Funnily enough, I never had such a problem

Strangely, me neither @dozzzzer ...

**Comment by LWinterberg** [comment]
After some more consideration - 

* I don't think we should make a preference for this. 
* We may want to change the cursor on hover to something else (either hand, or 4-direction-arrows) to give a bit more indication what it is you're about to click
* We'll likely have a better solution for Qt, where you can rearrange/enable/disable buttons individually in a settings menu, so for the buttons in the top row, it'd be much harder to accidentally do it.

**Comment by petersampsonaudacity** [comment]
> * I don't think we should make a preference for this.

Plus 1 to this

> * We may want to change the cursor on hover to something else (either hand, or 4-direction-arrows) to give a bit more indication what it is you're about to click

That sounds like a good idea @LWinterberg 

Hand would be consistent with Clip-handle drag-bars _(and consistent with both Microsoft and Apple design guidelines)_

**Comment by jadenquinn** [comment]
> ![image](https://private-user-images.githubusercontent.com/87814144/303932760-2be78e92-9701-4ef5-bdfc-02d3a5ad77e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNDQyOTksIm5iZiI6MTcwOTM0Mzk5OSwicGF0aCI6Ii84NzgxNDE0NC8zMDM5MzI3NjAtMmJlNzhlOTItOTcwMS00ZWY1LWJkZmMtMDJkM2E1YWQ3N2U0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDAxNDYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NjMyMTk3MmU1MTQ2OTUyOTkzYjg3ZmE0ZmI0Yzg0MTRlN2VkN2IwY2I1Y2JiNjVkM2M0MjI4ZDI2OGZmZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c_JE0E32KVlQCCsuqrFamlB4fAkta7TisGT3Gxaa4lk)
> 
> Are you talking about toolbar grabbers (red rectangles here) or clip handles (red oval)?

Red rectangles.

**Comment by jadenquinn** [comment]
> After some more consideration -
> 
>     * I don't think we should make a preference for this.
> 
>     * We may want to change the cursor on hover to something else (either hand, or 4-direction-arrows) to give a bit more indication what it is you're about to click
> 
>     * We'll likely have a better solution for Qt, where you can rearrange/enable/disable buttons individually in a settings menu, so for the buttons in the top row, it'd be much harder to accidentally do it.

Excellent
