### ISSUE TITLE
SuSE: Audacity 2.4.2 doesn't build for 32 bit intel

### ISSUE THREAD

**Issue by plater** [audacity/audacity#594]
Audacity 2.4.2 doesn't build for 32 bit intel (i586)
Build fails with:
[  161s] In file included from /home/abuild/rpmbuild/BUILD/audacity-Audacity-2.4.2/lib-src/sbsms/src/sse.h:9,
[  161s]                  from /home/abuild/rpmbuild/BUILD/audacity-Audacity-2.4.2/lib-src/sbsms/src/fft.h:10,
[  161s]                  from /home/abuild/rpmbuild/BUILD/audacity-Audacity-2.4.2/lib-src/sbsms/src/fft.cpp:1:
[  161s] /home/abuild/rpmbuild/BUILD/audacity-Audacity-2.4.2/lib-src/sbsms/src/fft.h: In function '_sbsms_::SSETwiddle<128, 1>::twiddle2(int, int, float (*) [2], float (*) [2], float __vector(4) const&, float __vector(4) const&)':
[  161s] /usr/lib/gcc/i586-suse-linux/10/include/xmmintrin.h:778:1: error: inlining failed in call to 'always_inline' '_mm_storeh_pi(int __vector(2)*, float __vector(4))': target specific option mismatch
[  161s]   778 | _mm_storeh_pi (__m64 *__P, __m128 __A)
[  161s]       | ^~~~~~~~~~~~~
[  161s] In file included from /home/abuild/rpmbuild/BUILD/audacity-Audacity-2.4.2/lib-src/sbsms/src/fft.h:10,
[  161s]                  from /home/abuild/rpmbuild/BUILD/audacity-Audacity-2.4.2/lib-src/sbsms/src/fft.cpp:1:
[  161s] /home/abuild/rpmbuild/BUILD/audacity-Audacity-2.4.2/lib-src/sbsms/src/sse.h:21:34: note: called from here
[  161s]    21 | #define STOREH(v,p) _mm_storeh_pi((__m64 *)(p), v)
[  161s]       |                     ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
[  161s] In file included from /home/abuild/rpmbuild/BUILD/audacity-Audacity-2.4.2/lib-src/sbsms/src/sse.h:9,
[  161s]                  from /home/abuild/rpmbuild/BUILD/audacity-Audacity-2.4.2/lib-src/sbsms/src/fft.h:10,
[  161s]                  from /home/abuild/rpmbuild/BUILD/audacity-Audacity-2.4.2/lib-src/sbsms/src/fft.cpp:1:
[  161s] /usr/lib/gcc/i586-suse-linux/10/include/xmmintrin.h:807:1: error: inlining failed in call to 'always_inline' '_mm_storel_pi(int __vector(2)*, float __vector(4))': target specific option mismatch
[  161s]   807 | _mm_storel_pi (__m64 *__P, __m128 __A)
[  161s]       | ^~~~~~~~~~~~~

I've disabled i586 build in the package so long, don't know if anyone uses i586 audacity even raspberry pi's are 64bit nowadays.

**Comment by JamesCrook** [comment]
I'm marked this as bug-distros as it looks like a special build for SuSE.

**Comment by plater** [comment]
So can I assume that audacity builds for 32 bit intel on other distributions or it doesn't build -m32 anymore? I haven't had any user complaints about the nonexistence of a 32 bit package but I'm intrigued as to why this is openSUSE specific.
