### ISSUE TITLE
Waveform does some really goofy shish within Audacity, but not in exported file

### ISSUE THREAD

**Issue by jadenquinn** [audacity/audacity#5940]
### Bug description

I have no idea how to even describe this issue, all I can say is Audacity seems to play these samples back incorrectly, completely blowing out the audio, I've only seen this like 3 times.

### Steps to reproduce

1. Download this file: https://archive.org/download/fdmusic/aaliensmap04_blowout.aup3
2. Open it in Audacity
3. Press Play and listen

### Expected behavior

I expected Audacity to play the samples like this file: https://archive.org/download/fdmusic/aaliensmap04_blowout.wav
Exported files somehow don't have this waveform bug or whatever.

### Actual behavior

The waveform delflects upward in Audacity and as a result the audio is completely FuuFed up.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS

**Comment by LWinterberg** [comment]
The waveform of the wav is badly clipping at over +6dB and off-center regardless of editor:
![image](https://github.com/audacity/audacity/assets/87814144/821bebee-afb0-465e-8517-1c131c176237)

Note that as these are 32 bit float wav files, the clipping isn't a problem per se - if you lower the volume of the track or the playback volume in Audacity, it'll sound fine again. Similarly, if you turn up the volume of your browser or media player, it'll begin clipping there too. 

If you're looking to achieve a mildly clipped effect, use Audacity's limiter in soft/hard clipping mode. Do not let the file itself blow out.

**Comment by jadenquinn** [comment]
> The waveform of the wav is badly clipping at over +6dB and off-center regardless of editor: ![image](https://private-user-images.githubusercontent.com/87814144/304006846-821bebee-afb0-465e-8517-1c131c176237.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNDQyMTMsIm5iZiI6MTcwOTM0MzkxMywicGF0aCI6Ii84NzgxNDE0NC8zMDQwMDY4NDYtODIxYmViZWUtYWZiMC00NjVlLTg1MTctMWMxMzFjMTc2MjM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDAxNDUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2MGJmNDc0YTljOGI1M2MwNzYyNTg3Yzk0OTZmZGZkMDIzNGE0MGE0M2Y1NDJmM2E2YjliYTQ3ZmVkMzMzNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sGXzATr75beqbFf4coqdvO6w4mm1--Cm00YOl99i8DM)
> 
> Note that as these are 32 bit float wav files, the clipping isn't a problem per se - if you lower the volume of the track or the playback volume in Audacity, it'll sound fine again. Similarly, if you turn up the volume of your browser or media player, it'll begin clipping there too.
> 
> If you're looking to achieve a mildly clipped effect, use Audacity's limiter in soft/hard clipping mode. Do not let the file itself blow out.

Huh.. interesting. Thanks. Not sure why this happens, however I know that it doesn't do this or sound like it does in Audacity when I export the videos I use these for, or within Resolve or Premiere before that.
