### ISSUE TITLE
Solo & Mute can both be enabled simultaneously

### ISSUE THREAD

**Issue by JappaWakka** [audacity/audacity#5942]
### Bug description

You can press both the solo button and the mute button on a track and both will be enabled instead of only one of them

### Steps to reproduce

1. Create a track
2. Press the solo button on the track
3. Press the mute button on the track

### Expected behavior

They shouldn't be allowed to both be enabled

### Actual behavior

Both can be enabled at the same time

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

![image](https://github.com/audacity/audacity/assets/31563291/08cec5af-d8f3-412f-a9b1-6191dc06b21a)

**Comment by LWinterberg** [comment]
This is intentional and the standard across DAWs. You can enable the old behavior via Preferences > Track Behaviors > Solo button: Simple
