### ISSUE TITLE
Cancelling the Pitch & Speed dialog by ESC doesn't restore the previous pitch value and submits the entered value instead

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5944]
### Steps to reproduce

1. Have a clip
2. Navigate to the Pitch and Speed dialog
3. Enter some value in the Clip Pitch and/or Cents text box
4. Press ESC on the keyboard
5. Observe

### Expected behavior

The value entered in step 3 has not been submitted

### Actual behavior

The value entered in step 3 has been submitted

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

**Comment by saintmatthieu** [comment]
The fix may be as simple as calling `ProjectHistory::Get(project).RollbackState();` - thanks @Paul-Licameli !

**Comment by saintmatthieu** [comment]
> The fix may be as simple as calling `ProjectHistory::Get(project).RollbackState();` - thanks @Paul-Licameli !

Unfortunately not: `RollbackState()` must not be called during playback, as it replaces the track objects, assumed constant by the playback thread ...

**Comment by chinakov** [comment]
This is fixed within the scope of https://github.com/audacity/audacity/issues/5981, closing.
