### ISSUE TITLE
No information and no timeline on deprecation of autotools setup

### ISSUE THREAD

**Issue by dvzrv** [audacity/audacity#595]
**Describe the bug**
In c42d188e7 the autotools setup has been removed, although the new cmake setup still has fundamental issues in reaching feature parity (#519, #521, #522). This change was neither mentioned in the ChangeLog (see #593) nor in the [release notes in the wiki](https://wiki.audacityteam.org/wiki/Category:Release_Notes).

**To Reproduce**
1. Download 2.4.2
2. Extract and try to use autotools to build
3. Try to find information about autotools setup deprecation anywhere

**Expected behavior**
A fundamental change with _how_ a project is being built is announced in a ChangeLog. If a deprecation is planned it would be very helpful to pro-actively announce this (for a large scale project such as Audacity) and make sure that at least feature parity with the previous build system is reached before making it the default.

**Screenshots**
n/a

**Additional information (please complete the following information):**
 - OS: Arch Linux
 - Version Audacity 2.4.2

**Additional context**

A possible approach to pro-actively announcing these types of changes instead of pushing this downstream (without announcement) has been made in  https://github.com/audacity/audacity/issues/538#issuecomment-633678357 and I have opened #593 for a more straight forward and helpful use of the ChangeLog.
I don't quite understand what kept the project from simply announcing when and how their build system will change fundamentally. For me this is considered common courtesy (especially after bringing this up before).

**Comment by nckx** [comment]
> Audacity 2.4 **.2** is a quick release […]. We also fixed over 30 bugs, and added one small new feature, a 'Reset Configuration' menu item.

I honestly feel trolled.

**Comment by ainola** [comment]
@lllucius, please consider either reverting the removal or addressing these issues in the replacement build system. I see that Debian is also having to [carry patches](https://sources.debian.org/patches/audacity/2.4.2~dfsg0-3/) due to these changes.
