### ISSUE TITLE
Define waveform colorways per theme

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#5954]
### Your idea

Currently, colorways are defined per theme for Instrument 1 (Sample, Rms in the theme's colors.txt), but all other colorways are hardcoded in TrackArtist.cpp:105. Instead, all colorways should be defined in the theme's colors.txt.

### Problem to be solved

Colorways other than the default are currently unthemed. This means for the high contrast theme for example that there's 2 green waveforms and a decidedly low-contrast black-on-black instrument4 colorway:

![image](https://github.com/audacity/audacity/assets/87814144/089402ae-b16d-4d4e-bacc-8e595b9e5385)

**Comment by petersampsonaudacity** [comment]
Anoother issue with this is that in High Contrast Instrument 4 the full waveform is not visible only the RMS part _(unless the track is selected)_  As the other part of the wavegorm is the sme color as the black nackground

### Selected
![image](https://github.com/audacity/audacity/assets/50205984/bee64559-fb22-4def-9598-5b183aca0e5c)

### Not selected
![image](https://github.com/audacity/audacity/assets/50205984/f3e9839f-977c-4d4f-825f-a12ada7e617d)

**Comment by dozzzzer** [comment]
Tested
