### ISSUE TITLE
Internal portaudio error

### ISSUE THREAD

**Issue by EphraimB** [audacity/audacity#596]
**Describe the bug**
Internal portaudio error

**To Reproduce**
Open Audacity

**Expected behavior**
Recording and playback to just work

**Screenshots**
<img width="551" alt="screenshot41" src="https://user-images.githubusercontent.com/10489639/86178202-f47fee00-baf5-11ea-8fb8-3728ad463594.png">
<img width="1920" alt="screenshot42" src="https://user-images.githubusercontent.com/10489639/86178203-f47fee00-baf5-11ea-9b5c-d12cefa2be30.png">

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version: Audacity 2.4.2
 - (if relevant) Sound Device: All

**Additional context**
Works perfectly in Audacity 2.3 but won't work in any 2.4 versions

**Comment by petersampsonaudacity** [comment]
@EphraimB   can you please provide more information?

a) the latest release is now 3.0.2 - is this still happening for you on 3.0.2?

b) Please provide more detailed steps, in particularly what if any external input/output devices do you have plugged in ?

c) In Windows Sound control - are any of your devices visible to Windows - and are they enabled?  If Windows can't see them then certainly Audacity won't see them.

**Comment by petersampsonaudacity** [comment]
Due to lack of response from the OP (after our request for updated information) -  and as the original issue was logged a year ago on an older version of Audacity I shall close this issue.
