### ISSUE TITLE
Make Cancel/OK buttons order uniform across the dialogs

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5963]
### Your idea

Currently, on Windows, the Cancel/OK buttons order is inconsistent: some dialogs (e.g. Preferences, Audio Settings, Plugin Manager) have OK on the left, and Cancel on the right. The rest have it the other way around. It has now become even more annoying than ever given that all EGATs now have Cancel button too.

On macOS, though, there's no such a problem: all dialogs have OK on the left, and Cancel on the right.

This should be made uniform.

<img width="450" alt="image" src="https://github.com/audacity/audacity/assets/70063970/bb2dc2cb-c5f4-460e-a860-ad59e2addf18">

### Problem to be solved

Put an end to the mess with the OK/Cancel buttons order and make it consistent.

**Comment by LWinterberg** [comment]
It is infinitely to be regretted that this divergent decision made by Apple and Microsoft in the 80s now is my problem.

**Comment by petersampsonaudacity** [comment]
> It is infinitely to be regretted that this divergent decision made by Apple and Microsoft in the 80s now is my problem.

And my problem too - as it will involve a **LOT** of images in the manual   ;-)

**Comment by petersampsonaudacity** [comment]
So is this likely to be holding up:

 **Move OK/Cancel/Preview down in EGATs #3615** 

_which, apart from this new curve-ball, looks ready to go_

**Comment by petersampsonaudacity** [comment]
Since by far the dominant user vase for Audacity is Windows perhaps it makes eminent sense to use Microsoft's standards rather than Apple's.

**Comment by LWinterberg** [comment]
this one definitely isn't going into 3.5.

**Comment by LWinterberg** [comment]
All dialogs reimplemented in Audacity 4 should have this
