### ISSUE TITLE
Reset Config moves Share Audio toolbar to the next row

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5966]
### Steps to reproduce

1. Launch Audacity
2. Tools > Reset config
3. Observe

### Expected behavior

Share Audio toolbar remains next to the Audio Setup toolbar

### Actual behavior

Share Audio toolbar has been moved to the next row:

<img width="450" alt="image" src="https://github.com/audacity/audacity/assets/70063970/dac759b6-4358-421d-ae32-d3059cbb823a">

### Audacity Version

[other](https://nightly.link/crsib/audacity/workflows/build/au_project_sync)

### Operating system

Windows, macOS

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest 3.5.0 alpha test build I cannot replicate this

**Comment by crsib** [comment]
Bugs with Cloud label are not present in master or any opened PR so far. And fingers crossed - the all will be fixed before that :-)

**Comment by petersampsonaudacity** [comment]
> Bugs with Cloud label

But there is no Cloud label for this bug ...

**Comment by dozzzzer** [comment]
Now there is!

**Comment by petersampsonaudacity** [comment]
Testing on w10 with the latest Beta test build:  audacity-win-3.5.0-beta-20240301+ed81a44-x64-msvc2022

This looks to be fixed for the 3.5.0 Beta

**Comment by chinakov** [comment]
This is done, thank you!
