### ISSUE TITLE
Hotkey for Import RAW Data

### ISSUE THREAD

**Issue by rayman3003** [audacity/audacity#597]
As the title said: A Hotkey for Import RAW Data. 

Bcuz so many times I import raw data sounds & it would save me a lot of time to have a hotkey for it.

**Comment by Pokechu22** [comment]
It's already possible to set custom hotkeys; see [Keyboard Preferences](https://alphamanual.audacityteam.org/man/Keyboard_Preferences).

**Comment by rayman3003** [comment]
> 
> 
> It's already possible to set custom hotkeys; see [Keyboard Preferences](https://alphamanual.audacityteam.org/man/Keyboard_Preferences).

Oh, I didn't know it has key bindings. Thank u.

Please close this Issue.
