### ISSUE TITLE
Clicking Cancel in the "save to audio.com" doesn't cause sync process to stop

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5972]
### Steps to reproduce

1. Initiate cloud upload
2. In the "Save to audio.com" dialog with "Export..." progress bar, click the Cancel button
3. Observe: the dialog says you've canceled the upload
4. Observe: sync is still in progress

### Expected behavior

Save to the cloud is aborted as soon as you click Cancel.

### Actual behavior

Sync remains active until the very end, yielding the success message once the upload is complete.

https://github.com/audacity/audacity/assets/70063970/57f074fa-cea5-41b2-86af-e332b2044ee0

### Audacity Version

[other](https://nightly.link/crsib/audacity/workflows/build/au_project_sync)

### Operating system

Windows, macOS

**Comment by crsib** [comment]
Surprisingly, this is pretty much exactly how it is specified in the spec

**Comment by LWinterberg** [comment]
What you're cancelling is the MP3 generation and upload, not the project save. So yes, this is intentional.

**Comment by dozzzzer** [comment]
@LWinterberg Shall we at least make it clearer for the end user what exactly it is to be canceled?

**Comment by LWinterberg** [comment]
If it says "Generating mixdown..." instead of "Exporting...", this probably would be clear enough.

**Comment by dozzzzer** [comment]
I think we should also remove the subsequent "You have canceled this upload" dialog because it makes no sense since the actual upload continues.

**Comment by LWinterberg** [comment]
Let's remove that dialog too then.

**Comment by dozzzzer** [comment]
Tested
