### ISSUE TITLE
Opening a project from the cloud cannot be aborted

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5974]
### Steps to reproduce

1. File > Open from Cloud
2. Select a project that doesn't exist on the file system
3. Observe: "Synchronizing project" progress dialog
4. Click "Cancel"
5. Observe

### Expected behavior

Sync is aborted

### Actual behavior

The sync progress dialog freezes and cannot be dismissed, causing Audacity to freeze too.

https://github.com/audacity/audacity/assets/70063970/ebc0d06c-8fcb-483c-875a-083f4a91c90b

### Audacity Version

[other](https://nightly.link/crsib/audacity/workflows/build/au_project_sync)

### Operating system

Windows, macOS

**Comment by crsib** [comment]
I cannot reproduce this issue.

**Comment by dozzzzer** [comment]
Cannot reproduce this either
