### ISSUE TITLE
Error when opening a project that isn't in the temp directory

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#5975]
### Steps to reproduce

1. Have a project that has been successfully uploaded to the cloud but isn't in the temp directory
2. File > Open from cloud
3. Select that project and click Open
4. Observe: sync progress dialog pops up
5. Wait for the operation to finish

### Expected behavior

The project is loaded into Audacity

### Actual behavior

Windows:

![image](https://github.com/audacity/audacity/assets/70063970/c973e362-fac9-40b4-be5c-216d1124bb13)

macOS:

<img width="450" alt="image" src="https://github.com/audacity/audacity/assets/70063970/12dae3e4-5675-45c6-a0d2-d60282d52aaf">

### Audacity Version

[other](https://nightly.link/crsib/audacity/workflows/build/au_project_sync)

### Operating system

Windows, macOS

**Comment by crsib** [comment]
This is actually a fascinating bug. Right now, Audacity moves the project to the cloud directory; this way, we save (?) disk space for the user, but this is not necessarily needed. @LWinterberg, what do you think? Should we just clean up recent? Should we have both files? Should we save the file in place?

**Comment by crsib** [comment]
I cannot reproduce this issue by the latest steps @dozzzzer 

I have tried
1. Starting from a clean cloud env
2. Deleting a single project while Audacity is running.

I wonder if this bug had the same root cause as #5996

**Comment by dozzzzer** [comment]
Indeed. Following the original STRs, the actual error message is different now:

<img width="500" alt="image" src="https://github.com/audacity/audacity/assets/70063970/bea7918e-58dd-40a5-9eeb-843bdc13a300">

However, it still fails to clarify what exactly went wrong in this case. 
Is this acceptable though? @LWinterberg

**Comment by crsib** [comment]
For me the project just opens

**Comment by LWinterberg** [comment]
@dozzzzer If a file exists in the cloud but not locally, it definitely should be loaded. Given that the server tells you 404, maybe you're trying to load a project from the cloud that also is deleted on the cloud, and only exists in your cache?
