### ISSUE TITLE
Non-modal pitch-and-speed dialog

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#5981]
### Your idea

Pitch and speed dialog isn't modal anymore, meaning having it open doesn't block interaction with the rest of the UI.

### Problem to be solved

Changing speed isn't allowed (yet) during playback. So if one wants to change speed, that person has to close the dialog, press stop, and then open it again.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @saintmatthieu 's branch build for this.

This looks properly non-modal to me.

II can invoke the speed&pitch dialog from the Clip-handle and then still press Play or other buttons in the app.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @saintmatthieu 's latest branch build for this:  audacity-win-3.5.0-alpha-20240315+de007d8-x64

The arrow and the clock in the Clip-handle bow mirror the setting in the change Pitch&Speed dialog
![image](https://github.com/audacity/audacity/assets/50205984/deffe0da-fcd5-4344-8237-64ae5606fba1)

I also note that nicely in this non-modal dialog
1. when you are not playing the speed change is not grayed-out and can be used
2. Press Play and observe the Change Speed is grayed-out and inoperable
3. Press Pause and it remains grayed-out
4. Press Stop and observe that it becomes non-grayed out and usable again

**Comment by chinakov** [comment]
Tested, and ready for merge! Thanks.
