### ISSUE TITLE
MAC 14.3.1 (23D60):  Audacity Silicon is constantly crashing due to QSharedMemory::create: out of resources"; Only 2.4.2 works 

### ISSUE THREAD

**Issue by vigilant4u** [audacity/audacity#5983]
### Bug description

MAC 14.3.1 (23D60):  Audacity Silicon is constantly crashing due to QSharedMemory::create: out of resources";
Alle version from SILICON / Intel are crashing only the good old:  Only the version 2.4.2 works fine on newest Mac Sonoma.

The output from Terminal when starting any newer version is:

"SingleApplication: Unable to create block.
SingleApplication: 7 "QSharedMemory::create: out of resources"

==> AND NO: REBOOTING DOES NOT FIX THE ISSUE! It returns constantly.

The only hint i found, but is is catalina and not Sonoma and i have a fresh and new Sonoma machine right from the start is the following link:

https://forums.developer.apple.com/forums/thread/669625

Please fix the bug the quickest possible for all Mac user using SONOMA. Thx.

### Steps to reproduce

Terminal:

./BitBox.app/Contents/MacOS/Audacity

### Expected behavior

App should start but instead:

"SingleApplication: Unable to create block.
SingleApplication: 7 "QSharedMemory::create: out of resources"

### Actual behavior

A crashing audacity app from the newest version back to version 2.4.2: This is the only one running properly on Sonoma 14.3.1

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS

### Additional context

SONOMA 14.3.1 MAC 14.3.1 (23D60): 

The output from Terminal when starting any newer version is:

"SingleApplication: Unable to create block.
SingleApplication: 7 "QSharedMemory::create: out of resources"

==> AND NO: REBOOTING DOES NOT FIX THE ISSUE! It returns constantly.

The only hint i found, but is is catalina and not Sonoma and i have a fresh and new Sonoma machine right from the start is the following link:

https://forums.developer.apple.com/forums/thread/669625

Please fix the bug the quickest possible for all Mac user using SONOMA. Thx.

**Comment by dozzzzer** [comment]
> Steps to reproduce
> Terminal:
> 
> ./BitBox.app/Contents/MacOS/Audacity

What is BitBox anyway? @vigilant4u

**Comment by LWinterberg** [comment]
@dozzzzer a crypto wallet thingy which also has the same issue: https://github.com/digitalbitbox/bitbox-wallet-app/issues/2562

@vigilant4u I'm strongly suspecting you have some program running on your system which is eating up all shared memory segments. Audacity requires just a single one to start, and if something else has eaten up all shared memory segments, it can't. Given that a restart doesn't fix it for you, it'll be a program that's automatically loading on startup for you.

**Comment by vigilant4u** [comment]
> > Steps to reproduce
> > Terminal:
> > ./BitBox.app/Contents/MacOS/Audacity
> 
> What is BitBox anyway? @vigilant4u

Bitbox is another app with the same issue: They are already working on a fix, see here:

https://github.com/digitalbitbox/bitbox-wallet-app/issues/2562

![Uploading Standardwert 2024-02-19 um 13.59.22.png…]()

**Comment by vigilant4u** [comment]
> @dozzzzer a crypto wallet thingy which also has the same issue: [digitalbitbox/bitbox-wallet-app#2562](https://github.com/digitalbitbox/bitbox-wallet-app/issues/2562)
> 
> @vigilant4u I'm strongly suspecting you have some program running on your system which is eating up all shared memory segments. Audacity requires just a single one to start, and if something else has eaten up all shared memory segments, it can't. Given that a restart doesn't fix it for you, it'll be a program that's automatically loading on startup for you.

definitely not! 
![Standardwert 2024-02-19 um 14 01 49](https://github.com/audacity/audacity/assets/76205694/516c3dfb-aae2-4bf4-8a5d-49994062d207)

**Comment by LWinterberg** [comment]
Shared memory is a separate concept to RAM. I believe the terminal command to list shared memory segments is `ipcs -m`, with the `nattch` column listing how many segments are attached to a shmid, and `ipcs -m -p` to show which creator process has made the segment, and `ipcs -m -l` listing the limits the system has. I believe macOS comes with a 32 segment limit by default, which is extremely easy to fill up by misbehaving programs which need to share large amounts of data between processes.

**Comment by vigilant4u** [comment]
**The Only way i got Audacity 3.4.2 Silicon app to run properly on Mac OS Sonoma 14.3.1 was writing an executable apple script to be executed on Login Items during the startup process** as followed:

As there is definitely a shared memory bug on Sonoma 14.3.1 preventing to let your app start when the default values influencing the default shared memory settings

kern.sysv.shmmax
kern.sysv.shmall and
kern.sysv.shmseg

would stay as defined by apple, the only workaround is as followed:

open ScripEditor:

tell application "Terminal"
	
	if not (exists window 1) then reopen
	do script "sudo  sysctl  -w  kern.sysv.shmmax=104857600" in front window
	delay 0.5 --pause for half a second
	do script "roae3o7snapokatMZ" in front window
	
	if not (exists window 1) then reopen
	do script "sudo  sysctl  -w  kern.sysv.shmall=25600" in front window
	delay 0.5 --pause for half a second
	
	if not (exists window 1) then reopen
	do script "sudo  sysctl  -w  kern.sysv.shmseg=4096" in front window
	delay 0.5 --pause for half a second
	
	if not (exists window 1) then reopen
	do script "sysctl -n machdep.cpu.brand_string" in front window
	delay 2 --pause for two seconds
	
	if not (exists window 1) then reopen
	do script "sysctl -a | grep shm" in front window
	delay 8 --pause for eight seconds
	
	quit
end tell


Hope this also works others.

PS: 
I have no clue why it works on your side guys as i have used a fresh preinstalled Macbook Pro M3 with Sonoma.
I only installed the latest security update 14.3.1 from end of Jan 2024.

**Comment by mikewaters** [comment]
@vigilant4u what is this:
`do script "roae3o7snapokatMZ" in front window`

Strange script name?
