### ISSUE TITLE
Audacity 3.4.2 Silicon problem Mac OS Sonoma 14.3.1 shared memory problem

### ISSUE THREAD

**Issue by vigilant4u** [audacity/audacity#5990]
**The Only way i got Audacity 3.4.2 Silicon app to run properly on Mac OS Sonoma 14.3.1 was writing an executable apple script to be executed on Login Items during the startup process** as followed:

As there is definitely a shared memory bug on Sonoma 14.3.1 preventing to let your app start when the default values influencing the default shared memory settings

kern.sysv.shmmax
kern.sysv.shmall and
kern.sysv.shmseg

would stay as defined by apple, the only workaround is as followed:

open ScripEditor:

tell application "Terminal"
	
	if not (exists window 1) then reopen
	do script "sudo  sysctl  -w  kern.sysv.shmmax=104857600" in front window
	delay 0.5 --pause for half a second
	do script "roae3o7snapokatMZ" in front window
	
	if not (exists window 1) then reopen
	do script "sudo  sysctl  -w  kern.sysv.shmall=25600" in front window
	delay 0.5 --pause for half a second
	
	if not (exists window 1) then reopen
	do script "sudo  sysctl  -w  kern.sysv.shmseg=4096" in front window
	delay 0.5 --pause for half a second
	
	if not (exists window 1) then reopen
	do script "sysctl -n machdep.cpu.brand_string" in front window
	delay 2 --pause for two seconds
	
	if not (exists window 1) then reopen
	do script "sysctl -a | grep shm" in front window
	delay 8 --pause for eight seconds
	
	quit
end tell

Hope this also works others.

PS: 
I have no clue why it works on your side guys as i have used a fresh preinstalled Macbook Pro M3 with Sonoma.
I only installed the latest security update 14.3.1 from end of Jan 2024.

_Originally posted by @vigilant4u in https://github.com/audacity/audacity/issues/5983#issuecomment-1954253824_

**Comment by LWinterberg** [comment]
> I only installed the latest security update 14.3.1 from end of Jan 2024.
You have definitely installed some other programs and apps, one of which I'm fairly sure is causing this bug. The root cause here definitely is that macOS still has an extremely low limit for shared memory. In each case, this is not something fixable on our end.
