### ISSUE TITLE
Formant preservation

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#6001]
### Your idea

Use a formant preservation technique to improve the pitch shift quality, targeting vocals. Which one and where to integrate it is open.

### Problem to be solved

Currently, pitch shifting a human voice by only a few semitones makes it sound unrealistic.
This is because the resonances of the vocal cavity are also pitched up and down, virtually reducing or enlarging the vocal cavity dimensions and making for unrealistic characters (chipmunk or Darth Vador).
Some commercial pitch shift products offer formant preservation, e.g. Ableton's clip transposition, when using the "Warp" option and the "Pro" algorithm, yields currently a convincing result.
![image](https://github.com/audacity/audacity/assets/22740106/255bec0d-a0cb-4411-8819-584459167dc5)

**Comment by dozzzzer** [comment]
Tested
