### ISSUE TITLE
Reset Config doesn't reset some of the Cloud preferences

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#6002]
### Steps to reproduce

1. Launch Audacity clean
2. Link audio.com account
3. Change Preferences > Cloud > Generate Mixdown to e.g. "Never"
4. Reset config
5. Navigate to Preferences > Cloud

### Expected behavior

1. The audio.com account has been unlinked
2. Generate Mixdown has been reset to "every 5 saves"

### Actual behavior

1. The previously linked audio.com account remains linked
2. Generate Mixdown has not been reset to "every 5 saves"

### Audacity Version

[other](https://github.com/crsib/audacity/actions/runs/7987371529)

### Operating system

Windows, macOS

**Comment by chinakov** [comment]
This is done, thanks!
