### ISSUE TITLE
Right click options greyed out in newly created clips

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#6005]
### Bug description

When a new clip is created by splitting a selected region, some right-click options are greyed out until the clip is de-selected and reselected.

### Steps to reproduce

1. Generate  a 10 second tone
2. Select a few seconds 
3. Right click on the selection
4. "Split Clip"
5. Right click (again)

### Expected behavior

All relevant options to be available

### Actual behavior

"Rename Clip" and "Pitch and Speed" are disabled (greyed out)

<img width="450" alt="image" src="https://github.com/audacity/audacity/assets/70063970/b7a5d8b1-88ac-4122-8f4b-e882bbd93eb2">

### Audacity Version

current master / alpha / nightly build

### Operating system

All

### Additional context

The options may be enabled by de-selecting, then re-selecting the clip.

**Comment by petersampsonaudacity** [comment]
testing on W10 with 3.4.2 and latest 3.5.0 alpha test build

I cannot reproduce this on Windows:
![image](https://github.com/audacity/audacity/assets/50205984/4cc1e90d-ee32-4a34-9c34-5fb5a77b3ea3)

**Comment by saintmatthieu** [comment]
We might also want to change the behavior slightly, namely the clip doesn't need to be fully selected for these options not to be greyed out. @LWinterberg
