### ISSUE TITLE
"Make Stereo Track" does not do what it says in the manual.

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#6007]
### Bug description

According to the [manual](https://manual.audacityteam.org/man/splitting_and_joining_stereo_tracks.html):

>[Envelopes](https://manual.audacityteam.org/man/envelope_tool.html) will be retained for the left and right channels of the new stereo track,

### Steps to reproduce

1. Have two mono tracks with different envelope points
2. Make a stereo track out of these two
3. See if the envelope points in the resulting stereo track are retained

### Expected behavior

The behaviour of Audacity to be the same as described in the manual.

### Actual behavior

Envelopes are no longer retained when "joining" mono tracks to stereo. The tracks are now rendered to stereo, destroying any envelope control points (and clips / splits) in the process.

### Audacity Version

current master / alpha / nightly build

### Operating system

All

### Additional context

"Make Stereo Track" appears to be undocumented on the [support](https://support.audacityteam.org/) site.

**Comment by LWinterberg** [comment]
Updated the manual to mention current behavior.
