### ISSUE TITLE
When saving to cloud, without being signed in to audio.com, change 'Anonymous' to 'Account not linked'

### ISSUE THREAD

**Issue by Tantacrul** [audacity/audacity#6008]
### Your idea

See image below. The word 'anonymous' would be better placed by a more informative statement: 'Account not linked'. When I first encountered this dialog, I found it quite confusing because I didn't quite understand why the save button was disabled.

<img width="453" alt="image" src="https://github.com/audacity/audacity/assets/21022311/9c035c6c-0c38-4115-a09c-f3a01c567c39">

### Problem to be solved

.

**Comment by crsib** [comment]
This will affect the Share Audio as well. Does it works for you?

**Comment by Tantacrul** [comment]
Yeah, that'd improve both dialogs, since 'anonymous' is no longer a thing. Thanks!

**Comment by NathanGithub2013** [comment]
and the profile picture, i think changing it to something else shall emphasis the ACCOUNT NOT LINKED
