### ISSUE TITLE
When "Generate Mixdown" dialog is dismissed, the preference should be set to "Never"

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#6015]
### Steps to reproduce

1. Launch Audacity clean
2. Initiate the cloud upload
3. Observe: the "Generate Mixdown" dialog pops up
4. Dismiss the dialog by clicking the "X" button
5. Navigate to Preferences > Cloud
6. Review the "Generate Mixdown" option

### Expected behavior

It has been set to "Never"

### Actual behavior

It remains the default, i.e. "Every 5 saves"

### Audacity Version

other

### Operating system

Windows, macOS

**Comment by crsib** [comment]
We are killing this dialog, so this task is no longer relevant.
