### ISSUE TITLE
"Run Benchmark" fails

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#6019]
### Bug description

Run Benchmark fails.

### Steps to reproduce

1. Launch Audacity 3.5.0 alpha
2. "Tools > Run Benchmark"
3. Run

### Expected behavior

The benchmark utility to run.

### Actual behavior

Using 63310 chunks of 265 samples each, for a total of 32.0 MB.
Preparing...
Performing 100 edits...
Trial 0
Failed on Paste.
TEST FAILED!!!
Benchmark completed successfully.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

**Comment by Paul-Licameli** [comment]
There is a fix in the audacity/wave-clip-refactoring branch which could be cherry picked to master.

**Comment by petersampsonaudacity** [comment]
This is a regression on 3.3.3 introduced in 3.4.0

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @Paul-Licameli 's branch build for this fix:  audacity-win-3.5.0-alpha-20240222+f24e454-x64

Works a treat again in Paul's branch on Windows

**Comment by dozzzzer** [comment]
Tested
