### ISSUE TITLE
Add description in "Project Details" dialog

### ISSUE THREAD

**Issue by ianalarina** [audacity/audacity#6024]
### Bug description

Add text "Sharing projects to the Cloud requires free audio.com account linked to Audacity. Press "Link account" above to proceed" at the bottom of Project Details dialog, similar to what we have for sharing audio functionality.

![image](https://github.com/audacity/audacity/assets/128831621/1f062d10-12eb-40af-9d27-a3777129fb9d)

![image](https://github.com/audacity/audacity/assets/128831621/2fe7d186-7b91-4711-a069-86756873f4ab)

**Comment by dozzzzer** [comment]
<img width="450" alt="image" src="https://github.com/audacity/audacity/assets/70063970/a1938a0b-608e-40be-9b95-42728e0e8788">

@LWinterberg this is what is displayed in the Cloud upload dialog, which in my opinion is irrelevant. So please suggest the string change

**Comment by LWinterberg** [comment]
"Cloud saving requires..."
