### ISSUE TITLE
Capitalize all "Cloud" mentions across Audacity

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#6026]
#### File > Save to cloud
<img width="300" alt="image" src="https://github.com/audacity/audacity/assets/70063970/e0ed9dc5-ff28-4781-887a-9569d92d627e">

#### Success dialog:
<img width="300" alt="image" src="https://github.com/audacity/audacity/assets/70063970/30f641e1-796d-4573-ac37-51ec8e023e7b">

#### "How would you like to save?" dialog: 
<img width="300" alt="image" src="https://github.com/audacity/audacity/assets/70063970/02665d3c-b80e-41f4-9fe7-fd19e979fec9">

#### Open from cloud dialog title bar
<img width="300" alt="image" src="https://github.com/audacity/audacity/assets/70063970/49810cac-e176-405f-9c59-0b4afdfda5b1">

#### An error message when Internet cuts out:
<img width="300" alt="image" src="https://github.com/audacity/audacity/assets/70063970/37526937-00e2-45c8-8adc-62d0bfc4cf62">

#### Generic "Failed to save" dialog:
<img width="300" alt="image" src="https://github.com/audacity/audacity/assets/70063970/8529df7c-7754-4118-9a09-c83089c52353">

**Comment by petersampsonaudacity** [comment]
And Connie in the manual now agrees too, where on the Wording page it says:

>**Cloud**, should be capitalized when referring to the Muse cloud
