### ISSUE TITLE
Stereo to Mono command is wrongly listed as a built-in effect in the Plugin Manager

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#6031]
### Bug description
**Stereo to Mono** is a **Tracks > Mix** submenu command and is _wrongly_ listed in the Plugin Manager as Built-in effect - it should **_NOT_** be listed as an effect in the Plugin Manager.

The upshot of this is that if you disable this in the Plugin Manager then the **Mix Stereo Down to Mono** command is removed from the Tracks > Mix submenu:
![image](https://github.com/audacity/audacity/assets/50205984/385b1e86-5bb9-4efe-90ea-a573b75e9915)

### Steps to reproduce
1. Tracks > Mix
2. Observe the command **Mix Stereo Down to Mono**
3. Effect > Plugin Manager
4. scroll down to the S section and locate Stereo to Mono
5. Observe: this is wrongly listed here as an Audacity built-in effecyt
6. disable it
7. Tracks > Mix
8. Observe: the **Mix Stereo Down to Mono** sub-command is missing (hidden)

### Expected behavior
Stereo to Mono is a Tracks > Mix submenu command and not a Built-in effect - it should NOT be listed as an effect in the Plugin Manager.

It should not be possible to turn off or hide menu commands from the plugin manager

### Actual behavior
![image](https://github.com/audacity/audacity/assets/50205984/68f6ff60-d4d5-4a72-a726-f4f6f855d017)

### Audacity Version
3.4.2 and the latest 3.5.0 alpha test build - and even in @vsverchinsky 's latest branch build for the new Plugin Manager dialog.

### Operating system
Windows 10 - but assume all OS

### Additional context
This is the case in 3.4.2 and the latest 3.5.0 alpha test build - and even in @vsverchinsky 's latest branch build for the new Plugin Manager dialog.

This is **NOT** a regression - testing shows this to be the case in all Audacity versions from 2.1.1 onwards, when the plugin manager dialog was first introduced.

**Comment by dozzzzer** [comment]
Great catch, Peter!

**Comment by petersampsonaudacity** [comment]
We've had this since July 2015 - I'm amazed that this has nor been spotted before in the eight and half elapsed years.

**Comment by dozzzzer** [comment]
Tested
