### ISSUE TITLE
Cancelable uploads without quitting Audacity

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#6042]
### Your idea

Implement another way to access the "Project is syncing" dialog which would allow you to cancel the upload midway without having to quit Audacity.

The exact way to reach that dialog is yet TBD (@LWinterberg @Tantacrul @DilsonsPickles your input is much needed here)

### Problem to be solved

Currently, there's no way to cancel the upload other than by quitting Audacity. And there would be a need for a User to terminate their upload midway for a variety of reasons.

### Prior art

<img width=450 src=https://github.com/audacity/audacity/assets/70063970/695a1633-a321-4091-a09d-52b7c9ee7af0>

**Comment by crsib** [comment]
I have a strong opinion that the "cancellable" uploads should have a very different design. Pressing "stop" in this dialog doesn't mean the snapshot is discarded.

**Comment by DilsonsPickles** [comment]
@dozzzzer for clarification, do you mean allowing the User to cancel a generic cloud save? I.e. when the User sees this: 
![image](https://github.com/audacity/audacity/assets/111350316/ede51ddd-9488-4dd7-b368-35ae93edf98b)
in the bottom right corner of their screen?

**Comment by dozzzzer** [comment]
@DilsonsPickles yes sir

**Comment by Tantacrul** [comment]
I'm not sure we should allow people to stop syncing / uploading. If they've set the project as a cloud project, then syncing should just happen automatically.

**Comment by dozzzzer** [comment]
In this case, the ticket can be closed? 
@Tantacrul

**Comment by Tantacrul** [comment]
Yeah, I think so.

**Comment by LWinterberg** [comment]
The best use case I can come up with is that you're taking your laptop away from home, edit and suddenly realize Audacity is burning through your mobile data you've tethered to, in which case a "Pause" button may be useful. 

This feels very edge casey though - I personally wouldn't dare using cloud anything if I'm out and about.

**Comment by Tantacrul** [comment]
@LWinterberg the edge case is legit. I'd suggest that we solve it under the hood though. Audacity recognises there's no internet connection so allows the user to save locally in the temp file. When it detects a connection, it resumes syncing. I think that's basically what it does now.

For the moment, I'd not try and tackle this edge case. Let's see how things shape up once we get the beta out.
