### ISSUE TITLE
New File Menu has inconsistencies in the cloud sections

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#6047]
### Bug description
The new File Menu has inconsistencies in the cloud sections:
![image](https://github.com/audacity/audacity/assets/50205984/2ab10085-2e4a-4917-875f-529d2f7aa8d4)

1. two of the uses of Cloud are capitalized, one is not

2. The open and save are inconsistent:
a) Open From has a capitalized "F"
b) **Save to** has a lower case "t"

### Steps to reproduce
1. Launch cloudy Audacity
2. click on **File** menu command
3. Observe: menu inconsistencies

### Expected behavior
1. Consistency within the menu
2. Consistency with other menus in the app

### Actual behavior
Inconsistencies in the File menu

### Audacity Version
3.5.0 Beta (with added cloud stuff)

### Operating system
Windows 10 - but assume all OS

### Additional context
None

**Comment by LWinterberg** [comment]
Here's a new file menu:

![image](https://github.com/audacity/audacity/assets/87814144/27a3050e-f076-4313-a4c2-ffe95ebadb9f)

**Comment by crsib** [comment]
I have fixed what @petersampsonaudacity commented already. 

I have some concerns about the new menu layout for the cases when the cloud is not enabled though

**Comment by LWinterberg** [comment]
> I have some concerns about the new menu layout for the cases when the cloud is not enabled though

We do have a tendency to create way too many one-item sections, that's true. Worst offender is the effects menu which starts out with 3 of them, and the tracks menu isn't much better. I'm keeping this in mind for a menu reshuffling, it's probably out of scope for 3.5 and definitely out of scope for the beta.

**Comment by crsib** [comment]
Anyway, I've adopted your structure, the build is ready to test now
