### ISSUE TITLE
White Text on White BG in welcome dialog 

### ISSUE THREAD

**Issue by ligi** [audacity/audacity#605]
with a dark theme activated it looks like this:

![Selection_074](https://user-images.githubusercontent.com/111600/86780640-3f9d8200-c05d-11ea-9d03-598bcc9b76b7.png)

**Comment by petersampsonaudacity** [comment]
For me with 2.4.2 on W10 it looks kike this with dark text on white at the bottom of the dialog window.
![image](https://user-images.githubusercontent.com/50205984/87290527-61d04d80-c4fe-11ea-95c6-98138d1a4b3e.png)

**Comment by JamesCrook** [comment]
Closing, NOT-A-BUG
The OP is expecting system theming dark + Dark theme to theme everything.  It doesn't.

OP will get results closer to what they want/expect if they disable blending of system and audacity theme in preferences.

https://alphamanual.audacityteam.org/man/Interface_Preferences
