### ISSUE TITLE
Change the title of the dialog that comes up after mixdown is complete (aborted)

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#6051]
### Steps to reproduce

1. Initiate Cloud upload
2. Observe: "Generating Mixdown" dialog pops up
3. Cancel it OR wait until generating mixdown is finished
4. Observe

### Expected behavior

The dialog saying that the upload continues in the background and is titled accordingly

### Actual behavior

The dialog titled "Mixdown complete!":

<img width="450" alt="image" src="https://github.com/audacity/audacity/assets/70063970/7866dff6-f54f-44a2-880d-b22bed26dc74">

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS

**Comment by dozzzzer** [comment]
@LWinterberg please provide the title for that dialog ^

**Comment by LWinterberg** [comment]
ah sorry I had updated it in figma, but forgot to send the message. 

In both the mixdown success and mixdown cancel cases it can just show this. 

![image](https://github.com/audacity/audacity/assets/87814144/35b1efce-fab9-4b82-abc1-7d17dba0468a)
