### ISSUE TITLE
Add New > Time Track should be greyed out when a time track already exists. 

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#6052]
Currently, it's possible to attempt to add two time tracks, which yields this error message:

![image](https://github.com/audacity/audacity/assets/87814144/ab8a6c43-d3e9-435c-89bd-9e2a9756b2db)

Instead, the menu entry should just be greyed out when a time track is present.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @nalin243 's branch build for this:  audacity-win-3.6.0-alpha-20240709+ba19532-x64

Having already added a Time track to the project the next visit to Tracks > Add New shows that the **Time Track** menu option is properly grayed-out and unavailable in this branch build.
![image](https://github.com/audacity/audacity/assets/50205984/0ccbeefc-1643-4c18-b392-7708faf5aef6)

**Comment by dozzzzer** [comment]
tested

**Comment by petersampsonaudacity** [comment]
Testing this on W10 with the latest 3.6.0 Beta

This now works as expressed in this logged issue.

@LWinterberg 
BUT, I find myself preferring the old error message-based approach as it carefully informs the user that only one Time track is (I would lose the "This version of " from the front of the message though.

I can just see Forum postings of the future:
> Why is Time Track grayed out in the Tracks > Add New menu?
