### ISSUE TITLE
Prompt the user to restore a version of the project that failed to upload its last snapshot

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#6057]
If the last project snapshot upload failed (e.g. due to loss of connection) and a user on another computer tries to open the project in Audacity, they should be given the last uploaded snapshot. In addition, the user should be prompted to go to audio.com and choose which version of the project to make the current one by clicking 'Restore' for an appropriate version.

If the snapshot that failed to upload is also the first snapshot, the user should receive an error message.

**Comment by dozzzzer** [comment]
In the first case (i.e. when the file is available but its last version failed to upload), an attempt to retrieve such a project from another machine causes this:

<image width=450 src=https://github.com/audacity/audacity/assets/70063970/ccfcde50-3725-428e-a3c2-d7c0238b717d>


```
{
    "timestamp": 1709144370,
    "event_id": "471badc4f43eff4396a69190cb6e81a8",
    "platform": "native",
    "release": "audacity@3.5.0",
    "contexts": {
        "os": {
            "type": "os",
            "name": "Windows",
            "version": "10.0.19041"
        }
    },
    "exception": {
        "values": [
            {
                "type": "File_Error",
                "value": "Audacity failed to read from a file in <path>.",
                "mechanism": {
                    "type": "runtime_error",
                    "handled": false,
                    "data": {
                        "sqlite3.rc": "101",
                        "sqlite3.context": "SqliteSampleBlock::Load::step"
                    }
                }
            }
        ]
    }
}
```

**Comment by crsib** [comment]
I think this is a bug on backend side. I will recheck quickly

**Comment by crsib** [comment]
I cannot reproduce this issue. I receive the expected dialog "No version of this project..."
