### ISSUE TITLE
Cloud status in status bar is not read by screen readers.

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#6065]
### Steps to reproduce

1. Open the NVDA screen reader.
2. Open audacity, and do something which causes there to be some text next to the cloud symbol in the status line.
3. Press Insert + End to read the status line.

### Expected behavior

The text next to the cloud symbol is read

### Actual behavior

The text isn't read.

### Audacity Version

latest beta

### Operating system

Windows

**Comment by crsib** [comment]
Accessibility is not yet covered, it will be addressed in the following days.

**Comment by DavidBailes** [comment]
> Accessibility is not yet covered, it will be addressed in the following days.

So do you want me to wait until accessibility has been addressed before creating any more accessibility issues?

**Comment by crsib** [comment]
> So do you want me to wait until accessibility has been addressed before creating any more accessibility issues?

I would prefer to implement them first

**Comment by DavidBailes** [comment]
I can still reproduce this issue using the steps to reproduce.
For example, if the status line looks something like the status line in this image:
![image](https://github.com/audacity/audacity/assets/11887021/8fb5d21b-e456-430c-abf9-5a986ed541e5)

Then if NVDA is asked to read the status line, it just reads stopped.

Incidentally, I noticed that the selection of the status bar for the cloud status is focusable, but I'm not sure what the motivation for this is.

**Comment by crsib** [comment]
Under Accessibility Insights I see that the correct name is set

**Comment by DavidBailes** [comment]
@crsib I'm having a look at this. Think I've got a fix, though just trying to understand what's going on a little more...

**Comment by DavidBailes** [comment]
@crib. This is as far as I've got with the issue of trying to get Jaws to read the cloud status in the status line. It looks like it only reads the text that was put in the status line using wxStatusBarBase::SetStatusText(), and which is visible.
The current code creates children of the status bar  such that when there is cloud status present, the 5th and 6th children have the same location, and of these only the 6th child is visible.
I tried hacking some text into the the 5th child:
![image](https://github.com/audacity/audacity/assets/11887021/ec5b6634-2a13-4f52-b178-bcecc26ccaaf)

"fred" is read by NVDA, but still isn't read by Jaws.

In Filezilla, where there are icons on the status line, the text "Queque: empty" is read by Jaws.

![image](https://github.com/audacity/audacity/assets/11887021/0d8d7bf9-c578-489c-857f-1e6ce73f79c7)


![image](https://github.com/audacity/audacity/assets/11887021/dbe528bc-c7b4-4625-add9-d580d148f8ee)

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
