### ISSUE TITLE
"Wide" `Track` functions, transitionally modified to return or accept `TrackLists`, again simply use `Track`

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#6070]

**Comment by chinakov** [comment]
@Paul-Licameli - this is ready for merge. A huge commit with no issues noticed, and thanks for the expansive QA list. Thank you!

**Comment by Paul-Licameli** [comment]
> @Paul-Licameli - this is ready for merge. A huge commit with no issues noticed, and thanks for the expansive QA list. Thank you!

🎉
