### ISSUE TITLE
When trying to load the last synced version, Audacity yields an error message

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#6073]
### Steps to reproduce

1. On machine A, Generate > anything
2. Save the project to the cloud
3. Observe: on audio.com, the version is created
4. In Audacity, make some changes to the project impacting the project size (e.g. import a song)
5. Ctrl + S to sync changes
6. Cut out the internet midway through
7. On machine B, log in to the same audio.com account
8. File > Open from Cloud on machine B
9. Observe: the project is on the list
10. Select the project and click Open
11. Observe: "Cloud Project Incomplete"
12. Click "Load latest"
13. Observe

### Expected behavior

The first version (aka the last uploaded snapshot) is loaded into Audacity.

### Actual behavior

![image](https://github.com/audacity/audacity/assets/70063970/c370d326-9c8f-4c9f-a39d-894ba111fc86)

### Audacity Version

latest beta

### Operating system

Windows

### Additional context

The issue isn't 100% reproducible

**Comment by crsib** [comment]
I am not sure that I understand this bug. In all cases, I rely on the information I received from the audio.com

**Comment by dozzzzer** [comment]
Can no longer reproduce it
