### ISSUE TITLE
Mixdown option dialog does not get displayed again, even if resetting configuration

### ISSUE THREAD

**Issue by Tantacrul** [audacity/audacity#6078]
### Bug description

When testing the beta build (reseting configuration first), I did not get asked a question about how often I'd like to generate a mixdown of my projects.

I had to locate the options in preferences, which are still set to my original choice
<img width="274" alt="image" src="https://github.com/audacity/audacity/assets/21022311/cfdee809-1da2-40b2-81f4-088f586c0f27">

### Steps to reproduce

.

### Expected behavior

Resetting configuration should cause the Mixdown dialog to reappear when saving a project

### Audacity Version

latest beta

### Operating system

macOS

**Comment by chinakov** [comment]
This is done, thank you!
