### ISSUE TITLE
The Timeline does not have the new gear-wheel in the 3.5.0 Beta build

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#6079]
### Bug description

In the latest 3.5.0 Beta build by @crsib :  audacity-win-3.5.0-beta-20240229+a2a7f8c-x64-msvc2022

The Timeline does not have the new gear-wheel (even though the 3.5.0 changelog says that is the case)
![image](https://github.com/audacity/audacity/assets/50205984/2272c4ac-5f92-44e3-803c-f8ffe44c3119)

![image](https://github.com/audacity/audacity/assets/50205984/400de691-96df-4fff-8b0c-5fbab3523308)

Other 3.5.0 alpha builds that I have previously tested DO have the gear-wheel
![image](https://github.com/audacity/audacity/assets/50205984/f8f73c34-b31b-4c64-a0b8-68abe2434a23)

### Steps to reproduce

1. clear the audacity settings folder
2. load latest 3.5.0 Beta
3. Observe:  The gear-wheel is not in the Timeline

### Expected behavior

![image](https://github.com/audacity/audacity/assets/50205984/f8f73c34-b31b-4c64-a0b8-68abe2434a23)

### Actual behavior

![image](https://github.com/audacity/audacity/assets/50205984/400de691-96df-4fff-8b0c-5fbab3523308)

### Audacity Version

latest beta

### Operating system

Windows

### Additional context

@LWinterberg  wrote:

>ah shoot, that one only is in master then, not the beta branch. It'll definitely get in there for the full release.

**Comment by crsib** [comment]
Well, this is a new type of bug - bug in the changelog :-)

**Comment by petersampsonaudacity** [comment]
> Well, this is a new type of bug - bug in the changelog :-)

Sadly not only there - also in the 5.5.0 manual !
![image](https://github.com/audacity/audacity/assets/50205984/2dd8b7e3-4c79-43f4-81d9-d3254dada8b0)

**Comment by crsib** [comment]
This feature will be present in 3.5.0. The Beta is largely made for Cloud purposes

**Comment by petersampsonaudacity** [comment]
And fixed in the alpha 3.5. manual
