### ISSUE TITLE
Question: beta-3.5.0

### ISSUE THREAD

**Issue by Gootector** [audacity/audacity#6084]
Should I do PRs with the latest updated translation files (de, pl) for beta-3.5.0 branch? Will this branch be merged into the master or renamed release-3.5.0? What is going on here?
Thank you in advance for any reply.

Greetings,
Gootector

**Comment by LWinterberg** [comment]
This beta is a bit different from what we usually do - we've neither hit code freeze nor string freeze yet. There will be a separate release-3.5.0 branch with all changes from both this beta branch and master.

**Comment by Gootector** [comment]
OK. Thanks for the info.
