### ISSUE TITLE
Accessing the Clip context menu selects the whole clip

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#6091]
### Bug description
Accessing the Clip context menu selects the whole clip, thus _destroying_ any active selection that user may have carefully made.  

True for both methods of access:
a) right-click (RMB) in the Clip-handle drag-bar
b) left-click (LMB) on the three-dot overflow menu icon

Curiously right-click on the three-dot overflow menu icon dose _**NOT**_ change the selection

And in particular this means that the **Split Clip** and **Join Clips** in the context menu fail to work.

### Steps to reproduce
1. generate a 30 second chirp
2. select from 10-15 seconds
3. right click in the Clip-handle
4. Observe: context menu - and the whole clip is now selected
5. select from 10-15 seconds
6. left click on the three-dot overflow menu icon
7. Observe:  context menu - and the whole clip is now selected
8. select from 10-15 seconds
9. right click on the three-dot overflow menu icon
10. Observe: context menu (restricted menu items) - **BUT** the 10-15 seconds selection remains 

### Expected behavior
I don't expect the selection to change because I access the Clip context menu

I certainly don't expect different behavior for LMB and RMB cllick on the three-dot overflow menu icon

### Actual behavior
Accessing the Clip context menu selects the whole clip

### Audacity Version
3.4.2, 3.5.0 latest alpha master and the released 3.5.0 Beta

_Note that 3.4.2 does not have the three-dot overflow menu icon - so STRs 5 onwards do not apply here_

### Operating system
Windows 10 - but assume all OS

### Additional context
This has been the case ever since the clip context menu was introduced in 3.4.0

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
