### ISSUE TITLE
Ask if the User wants to export to the Cloud

### ISSUE THREAD

**Issue by crsib** [audacity/audacity#6106]
[ ] Add Share Audio to File/Export
[ ] Ask user for the export location
![Image](https://github.com/audacity/audacity/assets/2660628/cb60596e-cfd2-46d2-9927-c33dd4b0c50e)
[ ] Update the preferences to allow changing the behavior
![Image](https://github.com/audacity/audacity/assets/2660628/9aae8723-4240-40cf-8744-094d0e27f096)

**Comment by petersampsonaudacity** [comment]
@crsib 
 I'm assuming that the "Location" at the bottom is a Cloud location only (in fact on-computer temp files), correct?
 _We already have normal on-computer Save location controlled in Directories prefs._ 

In the old version of this dialog the bottom section was labelled "Temporary Cloud files directory"  which gave a clear indication of its purpose ("does what it says on the tin...").  And anyway you have here twp sections both labelled the same as "Save behavior".

**Previous dialog**
![image](https://github.com/audacity/audacity/assets/50205984/6ab63039-754c-4146-afe8-83340d5e4bca)

**Comment by petersampsonaudacity** [comment]
@LWinterberg @Tantacrul @crsib 
There could be an argument for moving the "Temporary Cloud files directory" to the Directories preferences.

But, on balance, I think I prefer to see all the Cloudy stuff together in one place.

**Comment by petersampsonaudacity** [comment]
Is "Always ask" intended to be the default setting in this dialog for both Export and Save ?

**Comment by Tantacrul** [comment]
> Is "Always ask" intended to be the default setting in this dialog for both Export and Save ?

The popup will appear each time unless you tell it not to. There are slightly different behaviours in each case. 

With Saving and Export, the vast majority of users will select 'don't show me this again' and pick the local option. We know this from having implemented the same flow for MuseScore last year.

However, with Saving, the user can opt to always save to cloud by default. We're not going to offer the same for exporting because I think it's less likely a user would always want that option. Therefore, showing 'don't show me this again' for exporting basically means 'Don't mention cloud saving again'.

**Comment by petersampsonaudacity** [comment]
@Tantacrul 

@LWinterberg @Tantacrul @crsib 
There could be an argument for moving the "Temporary Cloud files directory" to the Directories preferences.

But, on balance, I _think_ I prefer to see all the Cloudy stuff together in one place.

-------------------------------------------------------------------------

Might it be clearer to the user if the two sections were labeled:
a) **Audio files export behavior**
b) **Project save behavior**
to claify the difference between the two?

**Comment by petersampsonaudacity** [comment]
@Tantacrul 

while I have your attention here, is the Cloud prefs supposed to be at the bottom of the prefs list or sandwiched between Shortcuts and modules - see #6104

**Comment by Tantacrul** [comment]
> @Tantacrul
> 
> while I have your attention here, is the Cloud prefs supposed to be at the bottom of the prefs list or sandwiched between Shortcuts and modules?
> 
> See #6104

Well, it's not meant to be both, as you seem to have guessed 😄 

I don't have a strong opinion here. We could raise it up in the list if we think it deserves a higher priority.

**Comment by petersampsonaudacity** [comment]
I don't have a strong opinion here either - BUT I would like to see consistency   :-)

**Comment by crsib** [comment]
@petersampsonaudacity 

Cloud page availability is determined in the runtime. Due to how the Preferences (and many other places, like Menus) are built in Audacity, the position of such items may change in some circumstances. The best I can do now is to keep the Cloud last.

**Comment by petersampsonaudacity** [comment]
@crsib 

keeping it last would be fine by me.

It has the advantage that being last it looks more obvious as a new item at the bottom of the list for regular users of prefs.

_Plus it saves me a lot of work as that is how I have it in the manual right now_ 😄

**Comment by petersampsonaudacity** [comment]
Testing on W10 with the latest 3.5.0 Beta

@Tantacrul @LWinterberg @crsib 

Might it not be better (and more logical) if the **Export behavior** section were moved to Import/Export preferences?
![image](https://github.com/audacity/audacity/assets/50205984/ac80d7cf-ca46-4c81-90f9-d827be0b61b6)

This would also have the advantage of enabling the Cloud preferences dialog to fit within the vertical height of the default prefs dialog size.

**Comment by crsib** [comment]
> Might it not be better (and more logical) if the Export behavior section were moved to Import/Export preferences?

Moving them to a different section is much more challenging. Cloud support is implemented as a runtime module.

**Comment by petersampsonaudacity** [comment]
@crsib    Fair enough - I can live with it

As @Tantacrul observed yesterday, most users will encounter the dialog on first use of Export and are likely to make their choice there and the click the "Do not show this again" checkbox.  

So this will be a fairly obscure prefs setting anyway.

**Comment by petersampsonaudacity** [comment]
@Tantacrul @LWinterberg @crsib 

Note that the new Cloud preferences in the **only** pref that does not have a "?" help link to link to the relevant page in the manual.

**Comment by petersampsonaudacity** [comment]
@Tantacrul  wrote yesterday in this thread
>With Saving and Export, the vast majority of users will select 'don't show me this again' and pick the local option. We know this from having implemented the same flow for MuseScore last year.

However I note the the default in the following dialog is "Cloud", which from Tantacrul's observation is the least likely choice for most users to make.
![image](https://github.com/audacity/audacity/assets/50205984/de3ab846-6433-46b1-94b0-acf391fd2399)

-------------------------------------------------------------------------------------
@crsib 
I also note that on the Cloudy side it says
>Uploads uncompressed audio ...

Is it really the case that **only** uncompressed audio can be exported to audio.com? 
Or can MP3, AAC etc also be uploaded

**Comment by crsib** [comment]
We always upload WavPack from Audacity, audio.com handles the conversion internally.

**Comment by petersampsonaudacity** [comment]
@Tantacrul @LWinterberg @crsib 

I note that while the user can both save and open projects from Muse's Clod - this is **not** similarly the case for audio files.

I.e. the user can opt export an uncompressed audio file to audio.co - but they then cannot import it into any project.

**Comment by crsib** [comment]
Exactly!

**Comment by chinakov** [comment]
Tested, thanks!
