### ISSUE TITLE
German translation of "signed" file formats inappropriate

### ISSUE THREAD

**Issue by Kadabash** [audacity/audacity#611]
**Describe the bug**
The German version of Audacity translates "signed" as "signiert" in the names of file formats.
For example, "Signed 8 bit PCM" is translated as "Signiertes 8-bit PCM".

The problem is that "signiert" usually means something like "including a signature" or, in the context of files, "signed using a certificate". As a native German speaker, I have never heard the word "signiert" used to mean "contains (mathematical) sign information" for integers.

**To Reproduce**
1. Open Audacity, record some audio
2. Click "File", "Export", "Export audio" (German: "Datei", "Exportieren", "Audio exportieren")
3. In the dialogue for saving the file, the inappropriate translations appear in the file type selection combo box

**Expected behavior**
Although I'm not an audio expert, I would probably translate "signed" as something like "vorzeichenbehaftet" (literally meaning "sign-marked" as in "marked with a sign").
"Signed 8 bit PCM" would then be "Vorzeichenbehaftetes 8-bit PCM".
Could someone from the audio community please voice their opinion?

*EDIT*: It appears that the Ardour DAW, for example, does not translate "signed" at all, see its [translation file](https://github.com/Ardour/ardour/blob/master/libs/ardour/po/de.po#L3571).

**Additional information (please complete the following information):**
 - OS: Debian 10
 - Version: Audacity 2.2.2, although judging from `locale/de.po` in `master`, the translations have not been changed yet.

**Comment by Robert-J-H** [comment]
Yes, I agree. It's drawn out in German and that's why the English term is preferred in most places.
I would suggest either the adjective version or the one with preposition and noun:

8-bit integer (signed)
-> 8 Bit Ganzzahl (vorzeichenbehaftet)
-> 8 Bit Ganzzahl (mit Vorzeichen)

8-bit (unsigned)
-> 8 Bit Ganzzahl (vorzeichenlos)
-> 8 Bit Ganzzahl (ohne Vorzeichen)

https://de.pons.com/%C3%BCbersetzung/deutsch-englisch/signed+integer?bidir=1

**Comment by petersampsonaudacity** [comment]
My "Mystery-Shopper" who is a native German speaker and has a Masters in Linguistics agrees with Robert - and prefers

8-bit integer (signed)
-> 8 Bit Ganzzahl (mit Vorzeichen)

8-bit (unsigned)
-> 8 Bit Ganzzahl (ohne Vorzeichen)

Based on the fact that this is more elegant linguistically (not based on computer literacy auf Deutsch)

**Comment by Robert-J-H** [comment]
Oops can't remember what it is right now, perhaps
8 Bit Ganzzahl (vorzeichenbehaftet)?
That would of course not really work for the second case.
8 Bit Ganzzahl (vorzeichenunbehaftet)
Anyway, fine as suggested and glad that your M-S agrees with me.
Cheers
Robert

**Comment by petersampsonaudacity** [comment]
I logged this on Bugzilla as new P3 Bug #2779
https://bugzilla.audacityteam.org/show_bug.cgi?id=2779
Bug 2779 - German translation of "signed" file formats inappropriate

Accordingly I shall close this GitHub Issue in favour of the Bugzilla log

**Comment by Robert-J-H** [comment]
If only all bugs were as simple to fix...
Robert
