### ISSUE TITLE
[MacOS] FFMPEG 5.0.0 for Audacity doesn't work on MacOS 10.13

### ISSUE THREAD

**Issue by jadenquinn** [audacity/audacity#6119]
### Bug description

FFMPEG with Audacity has never worked on MacOS 10.13, and it still doesn't. This is a new issue on Github, because every time I make an issue for this bug, it always gets marked as completed, and the bug never gets fixed. This is STILL a bug. YEARS later. Please fix it already.

### Steps to reproduce

1. Have a MacBook with MacOS 10.13.
2. Download Audacity.
3. Download & Install the FFMPEG import/export library for Audacity, either the old version, or the new 5.0.0 version.
4. Be pissed off at how Audacity WILL NOT use it, even if you point it directly to the file it says it needs to point to manually.

### Expected behavior

I expect Audacity to pick up on the fact that FFMPEG has been installed, JUST FOR IT, but instead this does not happen.

### Actual behavior

Audacity does not pick up on the fact that I have installed FFMPEG for Audacity.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS

### Additional context

This happens on ALL MACHINES with MacOS 10.13, of which 5 of my MacBooks are, and I use a lot of them for audio-related purposes, like recording a Volt 4 (audio interface), so this is EXTREMELY annoying to still be an issue, as I brought this up YEARS ago and it still isn't fixed, probably because it keeps being marked as completed, when it CLEARLY has not been!

I've tried both the Universal DMG and the x86_64 one, and both versions of the FFMPEG for Audacity thing, both the slightly older one and the new 5.0.0 version, neither of them work.
<img width="1185" alt="2" src="https://github.com/audacity/audacity/assets/13245331/0feb2c29-a5ba-4e9c-a8bc-d67b33d4e9f9">

**Comment by jadenquinn** [comment]
Update: NO THIS IS NOT FIXED - But I just screwed around with the avformat file it says it needs, and I just got it to.. "work". Audacity still doesn't say the library is found or anything, but it at least lets me import and possibly export ogg/opus files, which it didn't before I did this screwing, so obviously something is working.

**Comment by dozzzzer** [comment]
As was already mentioned in #5318, 

> There are two versions of ffmpeg available on lame.buanzo.org. An old one, called ffmpeg_64bit_osx.pkg, and a new one: FFmpeg_5.0.0_for_Audacity_on_macOS.pkg. The later one supports both Intel and ARM Macs, but it doesn't support macOS 10.13. For this reason Audacity cannot load it when run on macOS 10.13.

**Comment by jadenquinn** [comment]
This is still a problem.
