### ISSUE TITLE
Save Project becomes cloud save after backing out of cloud save

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#6123]
### Steps to reproduce

1. Make some noise
2. Go to File -> Save to Cloud
3. Abort the operation
4. Go to File -> Save Project -> Save Project (Ctrl+S)

### Expected behavior

The "how would you like to save" dialog is shown

### Actual behavior

Only the "save to cloud" path is shown

### Audacity Version

latest beta

### Operating system

Windows

**Comment by crsib** [comment]
I think that was fixed as a part of removing the mixdowns

**Comment by dozzzzer** [comment]
No longer reproducible
