### ISSUE TITLE
Once the synced project file on Audio.com is manually deleted, Audacity refuses to open the local .aup3 file of said project

### ISSUE THREAD

**Issue by yasurok** [audacity/audacity#6124]
### Bug description

Once the project file on Audio.com is deleted, Audacity refuses to open the local .aup3 file of the previously-synced-with-Audio.com project, thereby rending it impossible for you to continue working on the locally-saved project file.

### Steps to reproduce

1. From within Audacity, sync your project to Audio.com, and close the app.
2. Delete the project file on Audio.com.
3. Try to open the locally-saved project file in Audacity.

### Expected behavior

Audacity reports that it cannot find the synced projected on Audio.com, but happily opens the locally-saved project file none the less, so you can resume your work, albeit just locally.

### Actual behavior

Audacity does report that it cannot find the synced projected on Audio.com, but nothing further happens when you acknowledge the notice.

### Audacity Version

latest beta

### Operating system

Windows

### Additional context

I know I should give this the label "Cloud" but I could not figure out how. Sorry.

**Comment by LWinterberg** [comment]
I'd say the CloudProjects folder being only used as a cloud projects cache is fine. You can move the project anywhere else to "convert" it to an offline project you can continue working on.

**Comment by yasurok** [comment]
Hi, @LWinterberg!

> I'd say the CloudProjects folder being only used as a cloud projects cache is fine. You can move the project anywhere else to "convert" it to an offline project you can continue working on.

I do not know anything about how the cloud project feature is implemented, but "the CloudProjects folder" sounds like a _local_ cache folder. If I am right, would you tell me where it is located? I could not figure it out by a quick Google search.

Thanks!

**Comment by LWinterberg** [comment]
it's in your Audacity settings folder - %appdata%\audacity. You can see and set its location in Preferences -> Cloud.
