### ISSUE TITLE
Audio tracks and background do not draw updates as scrolling and zooming occurs

### ISSUE THREAD

**Issue by Nightfirecat** [audacity/audacity#6128]
### Bug description

Additionally, the audio tracks and background area seems to not draw an initial grey background, instead drawing a copy of whatever desktop or windows were visible below the application.

### Steps to reproduce

1. Launch Audacity
2. Select, pan, or zoom on active tracks
3. See result

### Expected behavior

Visuals update accordingly with user input and interaction

### Actual behavior

The ruler for the track changes, however the background and track area itself does not change at all.

(note, the below audio is slightly longer than 3 minutes long, not 3 and a half hours like the track would indicate)
![Screenshot_20240312_161201](https://github.com/audacity/audacity/assets/2199511/6a9df778-09d4-474a-8a3f-db7813a1bd15)

https://github.com/audacity/audacity/assets/2199511/9e1cc3e5-452a-4d98-a771-a9253c40e856

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

### Additional context

This occurs in both version 3.4.2 (installed via Flatpak), and version 3.2.4 (installed from the Debian stable package).

I'm running Debian 12 with KDE Plasma 5.27.5 on X11.

**Comment by Nightfirecat** [comment]
Apologies, I think I used some poor terminology here. I didn't mean panning as in adjusting the levels of stereo/multi-channel audio, I meant scrolling as in clicking and dragging a selection beyond the left or right edges of the visible track, or scrolling left and right to view different parts of the track.

**Comment by petersampsonaudacity** [comment]
> I meant scrolling as in clicking and dragging a selection beyond the left or right edges of the visible track, or scrolling left and right to view different parts of the track.

In which case on W10 I have no problems with those actions- they work well and properly update the waveform image.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
