### ISSUE TITLE
After resetting the configuration, the audio.com account appears to remain linked

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#6135]
### Steps to reproduce

1. Link audio.com account with Audacity
2. Tools > Reset Configuration
3. Observe: it says "Account not linked" in Preferences: Cloud
4. File > Open from Cloud
5. Observe: The project list is loaded as if the user were signed in
6. Load any project and try to sync changes
7. Observe: changes are synced with no issues as if the user were signed in

### Expected behavior

Any Cloud-related operation, including reading the project list from the Cloud or syncing changes, must require the User to be signed in and should yield a prompt to sign in.

<img width="420" alt="image" src="https://github.com/audacity/audacity/assets/70063970/cb0a41b9-e3d4-4637-8cdc-ee00b782ebcf">

### Actual behavior

All cloud-related actions can be performed as if the user were logged in, as long as the user doesn't restart Audacity.

### Audacity Version

latest beta

### Operating system

Windows, macOS

**Comment by crsib** [comment]
I cannot reproduce this issues

**Comment by chinakov** [comment]
Also can't reproduce on Windows.
