### ISSUE TITLE
Link Account button needs to be clicked twice to perform account linking

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#6136]
### Bug description

https://github.com/audacity/audacity/assets/70063970/dde2395c-5a93-482a-b1bd-c564a524c4f5

### Steps to reproduce

1. Preferences > Cloud
2. Click "Link account" button
3. Observe: nothing
4. Click once again
5. Observe: the linking process initiated

### Expected behavior

The linking initiates as soon as you click "Link account" for the first time

### Actual behavior

The button needs to be clicked twice to begin the account linking procedure.

### Audacity Version

latest beta

### Operating system

Windows, macOS

**Comment by chinakov** [comment]
Issue fixed, thanks!
