### ISSUE TITLE
"You're not signed in" when the Cloud upload is initiated

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#6137]
### Bug description

https://github.com/audacity/audacity/assets/70063970/c3f4747a-452b-4170-8dc7-6e715b727ed7

### Steps to reproduce

1. Reset Config
2. Preferences > Cloud 
3. Link audio.com account > OK
4. Grab some audio
5. Initiate Cloud upload
6. Observe: "Syncing your project" dialog comes up
7. Click Continue
8. Observe

### Expected behavior

The dialog is dismissed by clicking Continue, then "Success!" dialog comes up.

### Actual behavior

The dialog is dismissed, after which the "You're not signed in" dialog comes up. Canceling the dialog causes the error message "Failed" to appear in the status bar. The project has the "Syncing" status on audio.com.

### Audacity Version

latest beta

### Operating system

Windows, macOS

### Additional context

Charles session file exposing the issue: 
[6137.zip](https://github.com/audacity/audacity/files/14722970/6137.zip)

**Comment by crsib** [comment]
I cannot reproduce this issue

**Comment by dozzzzer** [comment]
I cannot reproduce this in the latest build on Windows either; on macOS, I can't verify at the moment because of #6151

**Comment by crsib** [comment]
Cannot reproduce this bug
