### ISSUE TITLE
Store temporary files in RAM to preserve SSD longetivity

### ISSUE THREAD

**Issue by HerrBert233** [audacity/audacity#614]
**Is your feature request related to a problem? Please describe.**
I often use Audacity to just look into audio files. e.g. find out what's the dynamic range, and other small things
Audacity creates temporary files always, even if the audio is very short. But the temp file are uncompressed and always quite large. (several 100 MB). They would easily fit into my RAM (16 GB) but Audacity nevertheless creates temp files for them.
Nowadays, computers come with SSDs as the main (and sometimes the only) drive. SSDs have limited write operations before they go broke.

**Describe the solution you'd like**
Do not create temp files if the RAM is large enough.
Actually, you could let the operating system handle this for you.
On Windows, with a very simple change (just change file attributes) you can avoid that the file is written to disk:
Files created with both FILE_ATTRIBUTE_TEMPORARY and FILE_FLAG_DELETE_ON_CLOSE are held in memory and only written to disk if the system experiences high memory pressure. [[1]](https://docs.microsoft.com/de-de/windows/win32/api/fileapi/nf-fileapi-createfilea?redirectedfrom=MSDN#caching_behavior)
On Linux use tmpfs.

These are very simple changes, if someone points me to the code writing files to disk, I could give it a try. 

Best,
Herbert

**Comment by LWinterberg** [comment]
this used to be an option but got removed. 

We're looking to make Audacity real-time capable in this release, so things like the undo history should get significantly smaller.
