### ISSUE TITLE
When a clip has a non-zero cents value, the pitch indicator is not displayed

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#6140]
### Steps to reproduce

1. Grab some audio clip
2. Right-click > Pitch and speed or Ctrl + Shift + P
3. Enter a non-zero "cents" value
4. Click OK to close the dialog
5. Review the clip's title bar

### Expected behavior

The pitch indicator is in the title bar.

### Actual behavior

The pitch indicator is displayed only when the cents value is zero.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS

**Comment by LWinterberg** [comment]
have you seen https://github.com/audacity/audacity/issues/6062 and https://github.com/audacity/audacity/issues/6092 btw?

**Comment by saintmatthieu** [comment]
#6062 and this issues are duplicates, closing one of the two at random.
