### ISSUE TITLE
An attempt to pitch shift the clip down by 12 semitones with the formant preservation enabled shifts one semitone up (macOS)

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#6157]
### Bug description

https://github.com/audacity/audacity/assets/70063970/8abbb0c2-c22c-4149-95f6-6c68a79a36ea

### Steps to reproduce

1. Play a clip
2. Right-click > Pitch and Speed
3. In the Semitones, type "-12"
4. Click "Optimize for Voice"
5. Observe

### Expected behavior

The "Optimize for Voice" option is enabled as soon as it's clicked for the first time; the semitones value remains consistent at -12.

### Actual behavior

Upon the first click in the "Optimize for Voice" checkbox, Semitones value changes to -11, the second click actually enables the "Optimize for Voice" option.

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

**Comment by chinakov** [comment]
Tested, issue no longer reproduced.
