### ISSUE TITLE
'Sync Failed' when trying to open project from Audio.com

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#6160]
### Bug description

If the User presses 'Open' button on a project uploaded via Audio.com while the project is opened, the User will recieve a 'Sync failed' warning message. 

### Steps to reproduce

1. Create a new project
2. Upload it to the Cloud
3. Make some changes, re-save and re-upload the project
4. Go to Audio.com and press 'Open' on the first version of the project
5. Observe Result

### Expected behavior

The project should open as a new project (in the preview capacity)

### Actual behavior

'Sync failed' message is shown.
![image](https://github.com/audacity/audacity/assets/139755141/41e5f763-1917-477f-837f-728d2eec6e9f)

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

**Comment by crsib** [comment]
This is definitely not a bug with error message. This is an indication of a problem with Audacity itself.

**Comment by crsib** [comment]
Can you please clarify `Make some changes, re-save and re-upload the project` @chinakov ?

**Comment by chinakov** [comment]
@crsib I meant that you have to create a second version of the project used.

**Comment by crsib** [comment]
Cannot reproduce

**Comment by chinakov** [comment]
I can no longer reproduce this.
