### ISSUE TITLE
Closing a project without saving makes changes to the aup3-file after modifying the tempo

### ISSUE THREAD

**Issue by LinkeHand** [audacity/audacity#6166]
### Bug description

Closing a project without saving changes the aup3-file after modifying the tempo.
After reloading the aup3-file the label track is out of sync and resized.

### Steps to reproduce

1.	Create a news project with audio
2.	Add a label track with some labels
3.	Save the project
4.	Open the project
5.	Modify the tempo with the time signature toolbar
6.	Close the project without saving
7.	Reopen the project

Situation after step 3:
 
![image](https://github.com/audacity/audacity/assets/104369709/6e4fd1b4-b369-48b5-9aae-19f57729cb9d)

Situation after step 7:
![After Reload_69BPM](https://github.com/audacity/audacity/assets/104369709/ae43ed56-d210-4ef8-8436-470655058c47)

 

### Expected behavior

Closing without saving doesn’t write any changes to the aup3-file.

### Actual behavior

Audacity writes tempo changes to the aup3-file when closing the project without saving.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, Linux

### Additional context

If you export the xml-Data of the aup3-file, you see that the parameter “time_signature_tempo=“ is altered after closing the project without saving.
I use audacity for learning an instrument and therefore I reduce the tempo for training and looping short passages.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with 3.4.2

I confirm this
![image](https://github.com/audacity/audacity/assets/50205984/7c291e6a-dac4-4a4d-aaf5-0b656f7e2232)
**At Step 7**

a) for audio I generated a 30 second DTMF tone
b) I used Label sounds to label the sounds (and deleted the first label
c) at OP's Step 4 my project reopened coirrectly
d) At Step 5 I changed the Tempo from 120 to 240
e)  the DTMF tone accordingly shrank to 15 seconds - with the labels appropriately moved, still labelling the sounds
f) at step 7 the unsaved project opened with the audio incorrectly at 15 seconds (I had not saved that change at Step 6)
g) the labels however still correctly span the proper 30 seconds.

**Comment by petersampsonaudacity** [comment]
Ahhh - the root cause of this would appear to be that the BPM is _**NOT**_ stoored as part of the project.

Instead it is store as a global setting in the audacity.cfg file

This is my audacity.cfg after Step 7

![image](https://github.com/audacity/audacity/assets/50205984/551a58e2-39df-4dce-a04b-68eab00561b1)

**Comment by crsib** [comment]
BPM and signature are stored in the project. BPM in config just remembers the last value for the empty porjects
