### ISSUE TITLE
Pitch and Speed dialog stays hidden when accessed via overflow button

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#6168]
### Bug description

Pitch and Speed dialog stays behind main window when accessed via overflow button if it has already been opened and is in the background.

### Steps to reproduce

1. Invoke the dialog
2. Click somewhere else - the dialog is now hidden
3. Invoke the dialog using the overflow button

### Expected behavior

The dialog is brought to the fore.

### Actual behavior

The dialog stays hidden.

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

**Comment by DavidBailes** [comment]
@saintmatthieu . If the History dialog doesn't have the same problem, then my PR for including the Pitch and speed dialog in the Alt + F6 cycle may be relevant.

**Comment by saintmatthieu** [comment]
You fix keeps the dialog in the foreground also when it is not focused, which is also an improvement, but using the overflow button doesn't restore the focus, so there's yet a need for something else.
