### ISSUE TITLE
Pitch and speed dialog: when open it should be reachable from the main window by pressing Alt + F6

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#6170]
### Bug description

With the full default shortcuts enabled, pressing Alt + F6 or Shift Alt + F6 cycles you round the main window and any open modeless dialogs. However, the Pitch and speed dialog is not included in this cycle.

### Steps to reproduce

With the full default shortcuts enabled:
1. Select a clip
2. Open the Pitch and speed dialog.
3. Press Alt + F6. The main window becomes the focus.
4. Press Alt + F6.

### Expected behavior

The Pitch and speed dialog becomes the focus.

### Actual behavior

The main window remains the focus.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

**Comment by saintmatthieu** [comment]
Will be addressed with https://github.com/audacity/audacity/issues/6168 and corresponding PR - thanks @DavidBailes !
