### ISSUE TITLE
An empty project opens in the new window when you try to open the restored version of the project in Audacity

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#6177]
### Bug description

When opening the restored version in Audacity while having the newer version already opened, an empty project is opened in the new Audacity window instead.

### Steps to reproduce

1. Generate some audio
2. Save the project to the cloud
3. Change the project in Audacity
4. Save again
5. Go to audio.com (not having closed Audacity yet)
6. restore the first version
7. click "open in Audacity" on the first version
8. In the "Cloud project conflict" dialog, click "Open new version"
9. Observe

### Expected behavior

The first (original) version of the project opens in the new Audacity window.

### Actual behavior

An empty project named e.g. "New Project xxxx-xx-xx xx-xx-xx N-2" opens in the new Audacity window. 

### Audacity Version

[other](https://github.com/audacity/audacity/actions/runs/8433683091)

### Operating system

Windows, macOS

**Comment by crsib** [comment]
I have tried a lot and I cannot reproduce this issue not on Windows nor on Mac. I think @chinakov can't reproduce it either
