### ISSUE TITLE
Unwarranted 'Syncing your Project' window upon locally saving a Project

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#6180]
### Bug description

If a User saves an Audacity project locally, he will recieve an unwarranted 'Syncing your Project' window, as this project should not be synced.

### Steps to reproduce

1. Launch Audacity
2. Reset Configuration
3. Link your Audio.com account to Audacity
4. Import or generate some audio into a new project
5. Press 'Ctrl + S'
6. Press 'Save to Computer'
7. Observe result

### Expected behavior

No 'Syncing your Project' window is shown to the User when saving locally.

### Actual behavior

The window is shown to the User when saving locally.

### Audacity Version

latest beta

### Operating system

Windows, macOS

**Comment by dozzzzer** [comment]
Tested
