### ISSUE TITLE
"Load latest" when trying to retrieve a not fully synced project causes a blank project to open in Audacity

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#6183]
### Bug description

https://github.com/audacity/audacity/assets/70063970/54e9cc90-4ad9-4d3d-8739-349e90e12a61

### Steps to reproduce

1. Upload a project to the Cloud
2. Make some changes to it
3. Ctrl + S and then quit Audacity immediately to abort the syncing of the snapshot
4. Remove the project file locally
5. Launch Audacity
6. Try to load the project via File > Open from Cloud
7. Observe: "Cloud project incomplete"
8. Click "Load latest"
9. Observe

### Expected behavior

The latest available (i.e. the first) version of the project is loaded.

### Actual behavior

A blank project opens in Audacity.

### Audacity Version

other

### Operating system

Windows, macOS

**Comment by dozzzzer** [comment]
Following the STRs I'm getting this:

<img width="600" alt="image" src="https://github.com/audacity/audacity/assets/70063970/bbc3a5a1-6be7-42f5-b25d-24b4c8bbee58">

**Comment by crsib** [comment]
I would say that this is correct behavior.
