### ISSUE TITLE
Open from cloud dialog: focus problems

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#6190]
### Steps to reproduce

Case A:
1. Open the Open from cloud dialog, and assume that there are some projects in the list. The Search box is the initial focus.
2. Press Tab, and then press Tab again.

Case B:
1. Open the Open from cloud dialog, and assume that there are some projects in the list. The Search box is the initial focus.
2. Type in some rubbish so that no projects are selected.
3. Press Tab. The empty list becomes the focus.
4. Press Tab again.

### Expected behavior

Case A:
After the first tab, the first project is the focus
after the second tab, one of the buttons below the list is the focus.

Case B:
One of the buttons after the list is the focus.

### Actual behavior

Case A:
After the first tab, the first project is the focus - though something isn't quite right, as NVDA just reads "table".
After the second tab, the focus doesn't appear to change - though NVDA now reads the first line of the list.

Case B:
The focus does not change - it's stuck, pressing Tab or Shift + Tab does not change the focus.

### Audacity Version

latest beta

### Operating system

Windows

**Comment by chinakov** [comment]
Tested, thanks!
