### ISSUE TITLE
Appstream file fail to validate

### ISSUE THREAD

**Issue by hfiguiere** [audacity/audacity#6192]
### Bug description

In 3.5.0 beta 3 (git tag)

The file `help/audacity.appdata.xml` fail to validate:

`<a>` are not allowed in the release description. There is the `url` tag to send to release, ideally it should be inline.

### Steps to reproduce

`appstreamcli validate help/audacity.appdata.xml`

### Expected behavior

No error.

### Actual behavior

Errors.

### Audacity Version

latest beta

### Operating system

Linux

**Comment by LWinterberg** [comment]
ah, I assumed the thing just ate HTML. I'll update it with the final release changelog

**Comment by hfiguiere** [comment]
It doesn't. There is a whole spec.
