### ISSUE TITLE
Adjust spectral selection frequency range by draging high&low boundary on spectrogram.

### ISSUE THREAD

**Issue by svjx18** [audacity/audacity#6195]
### Your idea

In audacity, the only way to adjust the frequency range of spectral selection in spectrogram is to drag the center frequency and the low or high boundary. It's not easy to adjust only the high or low frequency boundary individually.

### Problem to be solved

Enable user to adjust only the high or low frequency boundary in the spectrogram.
For example, user can drag boundary to change frequency range from:
![image](https://github.com/audacity/audacity/assets/41556600/fb340608-1d46-4b34-b734-6d59148f59f3)
to :
![image](https://github.com/audacity/audacity/assets/41556600/c0b1c2f8-32ba-4b72-a502-5425388e995c)

**Comment by LWinterberg** [comment]
You can adjust only one boundary by Ctrl+Dragging
