### ISSUE TITLE
Multi-view not selectable as a default view in settings

### ISSUE THREAD

**Issue by Gibbz** [audacity/audacity#621]
**Describe the bug**
In the preferences-> track -> Default view mode are the options for the tracks default display mode. The multi-view option is missing from the list

**Expected behavior**
An option for multi-view to be default.

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version 2.4.2

**Comment by Gibbz** [comment]
Also it would be nice to be able to specify the default split ratio between the views. Eg, 1 wavform : 3 spectogram

**Comment by SteveDaulton** [comment]
Thanks for the suggestion. 
It's already logged on our bug tracker here: https://bugzilla.audacityteam.org/show_bug.cgi?id=2460
Previous mailing list discussions ruled out an option for "the default split" as unnecessary "preference bloat".
