### ISSUE TITLE
Android Version

### ISSUE THREAD

**Issue by m1karii** [audacity/audacity#6213]
### Your idea

Hardware of mobile phones is getting beefier and beefier with each year. If you wanted to be a photographer or filmmaker a few years back you would need to invest at least a few hundreds possibly even few thousand euros on professional equipment. Nowadays each phone comes with at least 3 cameras including at least one with 4K resolution. With this and few lights small and medium size photography/filmmaking is a reality. Heck you can even do some minor lightroom-style edits to the photos right on the phone. And why wouldnt you? It can handle that. In the audio/podcast space this hardware evolution hasnt been however ~~fully~~ at all taken advantage of. Practically every ROM ships a "recorder" app yet unless you were to use a proprietary alternative you would still need to drag your notebook with you to places even though a phone with mic should be enough because "recorder" app only lets you record and replay audio which some people might deem deeply insufficient and there are no open source alternatives to proprietary apps for android. Audacity is the most powerful (and known) open source audio editor and is currently under massive code restructuring in preparation for version 4. I believe this could and should be taken advantage of in the form of an android app.

### Problem to be solved

Lack of open source audio editors on android.

**Comment by LWinterberg** [comment]
It certainly is on our radar, but as a feature request it's not really actionable at the moment: We do not have the resources to develop an android app just yet, and even making Audacity 4 happen will take quite some time.
