### ISSUE TITLE
Add an option to show/hide RMS in waveform

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#6219]
### Your idea

Audacity currently always shows peak + RMS values in its waveform. The RMS should be made optional.

### Problem to be solved

While RMS is extremely useful in some applications, it can be distracting in others, making Audacity appear more complex than it actually is. 

### Prior art

most music applications (both DAWs and things like soundcloud/audio.com) don't show the RMS

### Additional context

It's worth pointing out that RMS isn't the only thing which could be useful on a waveform. Especially in DJing, I've seen colored waveforms (where red = low pitch, blue = high pitch) and 3-band waveforms too (where you effectively overlay separate low/mid/high waveforms on top of each other). Here's some examples on how that works in CDJ: 

https://www.deejayplaza.com/en/articles/color-waveform-rekordbox

**Comment by dozzzzer** [comment]
Tested

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @vsverchinsky 's branch build for this:  audacity-win-3.6.0-alpha-20240701+a0197a1-x64

This seems to work as intended with the user able to turn off the RMS display from the View menu
![image](https://github.com/audacity/audacity/assets/50205984/5bdfd7ff-974f-4f59-b5ef-689f8cd2c223)

--------------------------------------------------------------------------------------

Curiously when Dominic Mazzoni originally launched Audacity there was no RMS display.  This is Audacity 1.0
![image](https://github.com/audacity/audacity/assets/50205984/56cc9eef-24fe-4987-b314-4d41544a51de)
 But by 1.2.6 the next oldest version I have still, the RMS in the waveform is present

**Comment by petersampsonaudacity** [comment]
I have updated the 3.6 alpha manual for this
