### ISSUE TITLE
LSP effects (OR built-in Reverb) only applied to one channel, and the other channel is muted (or too quiet)

### ISSUE THREAD

**Issue by evertvorster** [audacity/audacity#6226]
### Bug description

When using the LSP Parametric Equalizer x16 Stereo effect, the second channel is muted. 
This bug is also apparent on the GOTT Compressor Stereo effect. 

### Steps to reproduce

1. Open a stereo sound file. In my case, a mp4 screen recording that has stereo sound.
2. Apply the LSP Parametric Equalizer x 16 stereo effect.

### Expected behavior

The effect to be applied to both channels.

### Actual behavior

Effect applied to first channel, and the second channel is muted.

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

These effects were working properly on Audacity built from sources on April the 4th, so whatever broke this was introduced in the last 24 hours.

The effects in question are VST plugins, namely lsp-plugins-vst on Arch Linux. 
About my system:
```
Operating System: Arch Linux 
KDE Plasma Version: 6.0.3
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.3
Kernel Version: 6.8.2-arch2-1 (64-bit)
Graphics Platform: Wayland
Processors: 32 × 13th Gen Intel® Core™ i9-13900HX
Memory: 62.5 GiB of RAM
Graphics Processor: Mesa Intel® Graphics
Manufacturer: TUXEDO
Product Name: PD5x_7xSNC_SND_SNE
```

**Comment by evertvorster** [comment]
This issue is still present on git master from 7 April 2024

**Comment by evertvorster** [comment]
This is still present in the latest git master as of 12 April 2024.

The LSP plugins are available at:
https://github.com/lsp-plugins/lsp-plugins

**Comment by evertvorster** [comment]
Hi there!
I did some digging, and this same issue is present on the LV2 version of LSP Plugins. 

Unfortunately, the LV2 plugins also does not display and Graphics, so it is back to the VST versions for me. 

Also, I will be using the 4th April version of Audacity for my day to day work, because that is still working properly with these plugins, but will be compiling the latest master of Audacity in the hopes that something fixes this rather serious issue.

**Comment by LWinterberg** [comment]
Is this a regression?

**Comment by evertvorster** [comment]
Hi there!
I have been using Audacity for a while, and have never had the experience that one of my channels would be muted just by applying an effect from a plugin. 

So, I cannot for sure say that this is a regression. 
What I can say is that with Audacity compiled from sources pulled from git master branch on 4th of April and before, effects apply to both channels of a stereo project, and then from the 5th of April onwards the effect is applied to the first channel only, and the second channel is zeroed out or muted.

**Comment by crsib** [comment]
Hmm, @Paul-Licameli can this be a problem with wide wave tracks?

**Comment by chinakov** [comment]
Yes, this issue is confirmed. I have managed to reproduce this issue on Ubuntu 22.04, with the  LSP Parametric Equalizer x16 stereo effect. 
I have tried some other LV2 and VST plugins from different developers, same issue was observed.

**Comment by Paul-Licameli** [comment]
> Hmm, @Paul-Licameli can this be a problem with wide wave tracks?

Possibly.

Who wants to do bisection in the wave-clip-refactoring branch?

**Comment by Paul-Licameli** [comment]
I have no guess why anything I did would affect only Linux.

Is there a reproducible case also for Windows or Mac?

**Comment by chinakov** [comment]
@Paul-Licameli - I will take a look, thanks. 

I couldn't reproduce the issue on Windows so far.

**Comment by Paul-Licameli** [comment]
Bisection among my prior PRs into the wave-clip-refactoring branch -- can you do that tedious business, @chinakov ?

**Comment by evertvorster** [comment]
As of 23 April 2024, this issue is still present on the master branch of git.

**Comment by chinakov** [comment]
I've narrowed it down to https://github.com/audacity/audacity/actions/runs/8157350610, this is where the issue has been introduced.

**Comment by chinakov** [comment]
I've looked through most commits in [audacity/audacity/actions/runs/8157350610](https://github.com/audacity/audacity/actions/runs/8157350610), and here are my findings for the last commits of this MR:
- e3a1e19 - crash upon adding a stereo track in a new project
- 421d7d - crash upon adding a stereo track in a new project
- 18145e3 - crash upon applying LSP effect, asserion 'nchannels <=sequence.NChannels()
- 1ada855 - crash upon applying LSP effect, asserion 'nchannels <=sequence.NChannels()

So, it should have been https://github.com/audacity/audacity/pull/5965/commits/18145e370544c251b295cc177df57309e1c5d297

**Comment by Paul-Licameli** [comment]
> I've looked through most commits in [audacity/audacity/actions/runs/8157350610](https://github.com/audacity/audacity/actions/runs/8157350610), and here are my findings for the last commits of this MR:
> 
>     * [e3a1e19](https://github.com/audacity/audacity/commit/e3a1e193e554582a3ca016957360f5111f5304be) - crash upon adding a stereo track in a new project
> 
>     * 421d7d - crash upon adding a stereo track in a new project
> 
>     * [18145e3](https://github.com/audacity/audacity/commit/18145e370544c251b295cc177df57309e1c5d297) - crash upon applying LSP effect, asserion 'nchannels <=sequence.NChannels()
> 
>     * [1ada855](https://github.com/audacity/audacity/commit/1ada85597e633cdad494dc67c58d35c9f5f6206b) - crash upon applying LSP effect, asserion 'nchannels <=sequence.NChannels()
> 
> 
> So, it should have been [18145e3](https://github.com/audacity/audacity/commit/18145e370544c251b295cc177df57309e1c5d297)

Can you find a call stack for the assertion violation?

**Comment by chinakov** [comment]
@Paul-Licameli here it is!
[stack_trace.txt](https://github.com/audacity/audacity/files/15096882/stack_trace.txt)

**Comment by Paul-Licameli** [comment]
I have discovered:  Audacity's own build-in Reverb effect, with default settings, applied destructively to a stereo track, violates the same assertion in a debug build.  In a release build, the right channel results are not silent as in the original report, but much softer than they should be and not computed as in release 3.4.2.

**Comment by chinakov** [comment]
Great success, @Paul-Licameli! The issue is fixed. 

@evertvorster - could you please try it on your side, if you'd like?

**Comment by evertvorster** [comment]
I'll give it a go when that pull request is merged. 
In the meantime, thank you all for the hard work that was put in!

**Comment by Paul-Licameli** [comment]
I verified it only for reverb built in.

**Comment by evertvorster** [comment]
Fix confirmed. 
Thanks so much for all the effort that you guys put in!
