### ISSUE TITLE
Can't open audacity (appimage)

### ISSUE THREAD

**Issue by Samueru-sama** [audacity/audacity#6233]
### Bug description

```
./audacity-linux-3.4.2-x64.AppImage                   
/usr/lib/libatk-1.0.so.0
/usr/lib/libatk-bridge-2.0.so.0
/usr/lib/libcairo-gobject.so.2
/usr/lib/libcairo.so.2
/usr/lib/libgio-2.0.so.0
/usr/lib/libglib-2.0.so.0
/usr/lib/libgmodule-2.0.so.0
/usr/lib/libgobject-2.0.so.0
/usr/lib/libgthread-2.0.so.0
/usr/lib/libjack.so.0
/usr/lib/libpixman-1.so.0
/usr/lib/libportaudio.so
/tmp/.mount_audaciF8sZQp/bin/audacity: /tmp/.mount_audaciF8sZQp/lib/libmount.so.1: version `MOUNT_2_40' not found (required by /usr/lib/libgio-2.0.so.0)
```

### Steps to reproduce

Just opening that appimage results in that error. 

### Expected behavior

It should open.

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

This is on Archlinux with kernel 6.8.2-arch2-1 (fuse2 is installed just in case)

**Comment by bariscodefxy** [comment]
same

**Comment by bariscodefxy** [comment]
> same

installing audacity via package manager (pacman) solved my problem

**Comment by zavorra** [comment]
+1 on this one. 
I am on Fedora 40, trying to run audacity 3.5 I get this:

`giorgio@Ulmo:~/Downloads$ ./audacity-linux-3.5.0-x64.AppImage 
/lib64/libatk-1.0.so.0
/lib64/libatk-bridge-2.0.so.0
/lib64/libcairo-gobject.so.2
/lib64/libcairo.so.2
/lib64/libgio-2.0.so.0
/lib64/libglib-2.0.so.0
/lib64/libgmodule-2.0.so.0
/lib64/libgobject-2.0.so.0
/lib64/libgthread-2.0.so.0
/usr/lib64/pipewire-0.3/jack/libjack.so.0
/lib64/libpixman-1.so.0
findlib: libportaudio.so: cannot open shared object file: No such file or directory
/home/giorgio/Downloads/audacity-linux-3.5.0-x64.AppImage: Using fallback for library 'libportaudio.so'
/tmp/.mount_audaciIuvk6Q/bin/audacity: /tmp/.mount_audaciIuvk6Q/lib/libselinux.so.1: no version information available (required by /lib64/libgio-2.0.so.0)
/tmp/.mount_audaciIuvk6Q/bin/audacity: /tmp/.mount_audaciIuvk6Q/lib/libmount.so.1: version `MOUNT_2_40' not found (required by /lib64/libgio-2.0.so.0)
`

**Comment by bariscodefxy** [comment]
> +1 on this one. I am on Fedora 40, trying to run audacity 3.5 I get this:
> 
> ```
> giorgio@Ulmo:~/Downloads$ ./audacity-linux-3.5.0-x64.AppImage 
> /lib64/libatk-1.0.so.0
> /lib64/libatk-bridge-2.0.so.0
> /lib64/libcairo-gobject.so.2
> /lib64/libcairo.so.2
> /lib64/libgio-2.0.so.0
> /lib64/libglib-2.0.so.0
> /lib64/libgmodule-2.0.so.0
> /lib64/libgobject-2.0.so.0
> /lib64/libgthread-2.0.so.0
> /usr/lib64/pipewire-0.3/jack/libjack.so.0
> /lib64/libpixman-1.so.0
> findlib: libportaudio.so: cannot open shared object file: No such file or directory
> /home/giorgio/Downloads/audacity-linux-3.5.0-x64.AppImage: Using fallback for library 'libportaudio.so'
> /tmp/.mount_audaciIuvk6Q/bin/audacity: /tmp/.mount_audaciIuvk6Q/lib/libselinux.so.1: no version information available (required by /lib64/libgio-2.0.so.0)
> /tmp/.mount_audaciIuvk6Q/bin/audacity: /tmp/.mount_audaciIuvk6Q/lib/libmount.so.1: version `MOUNT_2_40' not found (required by /lib64/libgio-2.0.so.0)
> ```
> 
> And I don't think that "use your package manager" can be considered a solution, not even a workaround, since it is distribution dependent. Maybe "build your own" could work better \s

Yes, you're right. Using package manager is not a solution. If it is, why "AppImage" is exists? I said that because you can use that way until this problem be fixed.

**Comment by izzylaif** [comment]
remove libmount.so.1 from inside appimage (in lib folder) and it will run

**Comment by Samueru-sama** [comment]
> remove libmount.so.1 from inside appimage (in lib folder) and it will run

That works, great!

This single command does it all btw: `./audacity*AppImage --appimage-extract && rm ./squashfs-root/lib/libmount.so.1 && appimagetool ./squashfs-root`

**Comment by bharathpofficial** [comment]
> > remove libmount.so.1 from inside appimage (in lib folder) and it will run
> 
> That works, great!
> 
> This single command does it all btw: `./audacity*AppImage --appimage-extract && rm ./squashfs-root/lib/libmount.so.1 && appimagetool ./squashfs-root`

THIS WORKED FOR ME. but, why deleting that module fixes the issue ? why it is given in first place ? just curious.

btw: dowload the `appimagetool` from (this github repo)[https://github.com/AppImage/appimagetool/releases]

**Comment by mmBesar** [comment]
> That works, great!
> 
> This single command does it all btw: `./audacity*AppImage --appimage-extract && rm ./squashfs-root/lib/libmount.so.1 && appimagetool ./squashfs-root`

Thank you.

**Comment by Samueru-sama** [comment]
> btw: dowload the `appimagetool` from (this github repo)[https://github.com/AppImage/appimagetool/releases]

Btw something good of that appimagetool is that it pulls the static runtime by default, meaning that the produced appimage no longer depends on libfuse2 as well.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444) which uses a different build system. This bug should no longer be applicable.

**Comment by nazdridoy** [comment]
### Workaround: Preload the System's libmount (without modifying the AppImage)
Force Audacity to use the system version of `libmount.so` instead of the one in its AppImage. You can try launching it with the following command:
```bash
LD_PRELOAD=/usr/lib/libmount.so.1 ./audacity-linux-3.4.2-x64.AppImage  
```
