### ISSUE TITLE
Save to audio.com: sync failed - audacity encountered an unknown error.

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#6238]
### Steps to reproduce

1. Generate 30 mins of audio.
2. Save project to cloud.

### Expected behavior

Project is saved

### Actual behavior

After a small percentage of syncing to audio.com, I get a sync failed error. (percentage varies). Eg:
![image](https://github.com/audacity/audacity/assets/11887021/2f03d731-2331-47df-9538-a031506b8121)

### Audacity Version

latest beta

### Operating system

Windows

### Additional context

version: https://github.com/audacity/audacity/commit/5cb057520198aa99555c0aac5ce5e9aec62032c6

The upload speed of my internet connection is about 1.2 Mb/s

I presume, that others aren't getting this error.

**Comment by DavidBailes** [comment]
> Can you please share your logs?

Which logs?

**Comment by crsib** [comment]
Just the regular Audacity logs :-)

**Comment by DavidBailes** [comment]
> I do test emulating bad connections a lot, it works just fine for me

I don't think that I've got a bad connection. I can do uploads using other software without any problems. Using Routerstats, I don't see any problems.

**Comment by crsib** [comment]
> I don't think that I've got a bad connection. I can do uploads using other software without any problems. Using Routerstats, I don't see any problems.

I've tried to say that I test in extreme cases too, so the upload speed should not be a problem

**Comment by dozzzzer** [comment]
@DavidBailes is that something you're still experiencing with the most recent version of Audacity?
