### ISSUE TITLE
Import raw offset broken above 2147483648 bytes

### ISSUE THREAD

**Issue by namazso** [audacity/audacity#6253]
### Bug description

When importing raw data, attempting to set a byte offset over 2147483648 bytes will import with no offset applied

### Steps to reproduce

1. File > Import > Raw Data...
2. Select a big enough file
3. Enter a "Start offset:" of at least 2147483648

### Expected behavior

Import happens from the 2147483648th byte

### Actual behavior

Import happens from the beginning

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

The window resizing is also broken, so bigger offsets cannot be seen:

![image](https://github.com/audacity/audacity/assets/8676443/ef03fcf4-f77c-412f-9f71-541ccd833329)

**Comment by chinakov** [comment]
Tested, thanks
