### ISSUE TITLE
Make track header wider

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#6265]
Currently, the track header (TCP) is uncomfortably narrow, to the point where View > Show track names as overlay needed to be made a thing because the thing isn't wide enough to show the entire track name. 

A wider track header decreases the need for that as more info can be shown at once.

**Comment by petersampsonaudacity** [comment]
I tested this on W10 with @LWinterberg 's branch for this.

The TCP is indeed a little wider.

----------------------------------------------------------------------------------------------

What would be really nice would be if the user could expand/contract the TCP by clicking&dragging on its right border.

_I seem to recall user request for this in the past, in the old Forum._
