### ISSUE TITLE
File menu: 5 items not translated

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#6271]
### Steps to reproduce

1. On the interface page of preferences, set the language to netherlands
2. Open the Bestand (file) menu.

### Expected behavior

All the menu items are translated

### Actual behavior

5 of them are not.

### Audacity Version

other

### Operating system

Windows

### Additional context

version release-3.5.0

This was caused by commit: 30383047

**Comment by LWinterberg** [comment]
What'd be the easiest way to get this fixed? I was thinking to go into the PO files in question and manually add the accelerators for the translations.

cc @Gootector

**Comment by Gootector** [comment]
I'll fix it tonight.
