### ISSUE TITLE
Share Audio toolbar is in wrong position when resetting configuration

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#6276]
### Steps to reproduce

View > Toolbars > Reset

### Expected behavior

Share Audio is in the proper place as in release 3.5

### Actual behavior

Share Audio toolbar is alone in a new row of toolbars

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

### Additional context

The error was in b730d50b6d0aeaa50941f433c951e296592d34fa

**Comment by dozzzzer** [comment]
The bug is no longer reproducible

**Comment by dozzzzer** [comment]
Disregard my previous comment. The issue does exist in master which #6277 fixes.
