### ISSUE TITLE
Disable all "are you sure" questions

### ISSUE THREAD

**Issue by S-S-X** [audacity/audacity#6278]
### Your idea

Allow disabling every "are you sure?" question through configuration.
When disabled always assume that I don't want to do anything I didn't already do and just carry on with request (like closing unsaved project).

### Problem to be solved

Don't have to kill audacity process to close it.
Alternatively I could technically answer crazy amount of "are you sure?" questions which in turn would take anything from half a minute to five minutes which is why I've been resorting to kill -9 audacity and relaunching it after.

### Prior art

Yes, generally this is solved by simply having "never ask (you might lose data)"-checkbox in settings.

**Comment by LWinterberg** [comment]
I'd be interested to see what your use case it, and if using [batch processing](https://manual.audacityteam.org/man/macros.html) on the files directly would be helpful for you. 

I'm generally reluctant to add this option in the form you're suggesting. I understand it's useful when doing small edits on individual files in bulk, but if you were to switch context and start editing a podcast or a similarly complex project, I wouldn't want that you'd easily lose data in that context.

**Comment by S-S-X** [comment]
> I'd be interested to see what your use case it, and if using [batch processing](https://manual.audacityteam.org/man/macros.html) on the files directly would be helpful for you.

Last use case was going over some unknown audio files. Previous use cases _(where I had to use external software to forcibly kill audacity)_ mostly involved many small files most without any edits.

I do use batch processing and no, it wont help. It is only for well know situations where you go through exact process, it is not for situations where you're going over a lot of unknown stuff.

Generally questions where you know for sure you'll always use same selection are just extremely annoying, while killing audacity by force isn't that complicated it is still multiple clicks/letters.

> if you were to switch context and start editing a podcast or a similarly complex project, I wouldn't want that you'd easily lose data in that context.

I guess those users probably know not to change that option. You know, users should probably be regarded adults who are responsible of their very own actions?

**Comment by S-S-X** [comment]
To solve this at least for closing unsaved files, which is most annoying case, maybe it could be solved by having configuration to disable project altogether.

Another option could be a command line flag like `audacity --disable-all-questions` or `audacity --disable-projects`, it should make it clear even for those people who really need someone to watch over their actions.

**Comment by petersampsonaudacity** [comment]
There have been _**many**_ discussions and arguments about this over the years - in particular some (a few) folk object to this one when exiting without having saved the project:
![image](https://github.com/audacity/audacity/assets/50205984/e2789a47-c012-4227-93f4-c0e97270a939)

The old Audacity Team decided that it was better and safer to retain this message and **NOT**  provide a preference or other mechanism to have it turned off. 

This decision was made in the interests of safety, to try to avoid the chances of users losing important project data when they exit.  This is @LWinterberg 's point above - and I **_strongly_** agree with him.

Microsoft has similar safety messages on exiting from Excel and Word - and I,for one, have been extremely grateful in the past when this has saved me from accidentally discarding important data.  _Note that if you open an Excel spreadsheet and all that you do is  just select some data from a cell, with no other changes, then you will still get the "do you want to save" message from the app,_

**Comment by LWinterberg** [comment]
A preference is definitely not something I'm looking to add. A "you might lose data!" thing makes Audacity seem more scary than it actually is, and "Audacity is scary" definitely isn't a message I want to convey. 

That said, I think it's possible to cater to user intent a bit better:

* If you import a single track without making any edits (ie, use Audacity as a viewer), you are probably using Audacity as a waveform viewer and don't need to save it to a project.
* If you import a single track, make some edits, and then overwrite the original via a future #762, making no changes after the export, you are probably using Audacity as a wave editor and don't need to save it as a project. 
* If you delete all tracks, you probably were done with the project you had open, and don't need to save it as a project.

These cases can be handled individually, without any need for a preference.

**Comment by S-S-X** [comment]
One thing to still consider, would it be fine if "Exit" macro function could allow closing without saving?

That way you could define macro that closes Audacity without saving anything and override normal exit shortcut which is already possible.

**Comment by LWinterberg** [comment]
I don't mind a force-quit macro.
