### ISSUE TITLE
Wrong encoding (probably) of Languages/it/audacity.mo

### ISSUE THREAD

**Issue by mlocati** [audacity/audacity#6279]
### Bug description

I've downloaded audacity-win-3.5.0-beta-3-64bit.exe from https://www.audacityteam.org/beta/ and I see "wrong" strings for non US-ASCII characters.

For example, the main menu is displayed like this:

![immagine](https://github.com/audacity/audacity/assets/928116/7f5409b8-a6ea-445d-8041-db8e6b71538e)

As you can see, there's the `AttivitÃ` whereas it should be `Attività`, but it's not the only place where I see such strange characters.

In the "Quality" section of the preferences, for example, I see:

![immagine](https://github.com/audacity/audacity/assets/928116/efb51c2e-8bf8-42f3-a287-ed7ad9a06a23)

There we have `QualitÃ` instead of `Qualità` and `piÃ¹` instead of `più`.

In order to fix it:
1. I downloaded the file https://github.com/audacity/audacity/blob/release-3.5.0/locale/it.po
2. I compiled it to .mo format with `msgfmt -o audacity.mo it.po`
3. I moved the generated `audacity.mo` file to the `C:\Program Files\Audacity\Languages\it` folder

And everything seems ok now.

So, I thing there's something wrong in the way the `audacity.mo` is generated when creating the Audacity setup file.

### Steps to reproduce

1. download audacity 3.5 beta
2. select the Italian language
3. see the wrong characters

### Expected behavior

The non US-ASCII letters (eg `à`, `ù`) should be displayed correctly.

### Actual behavior

The non US-ASCII letters aren't displayed correctly (eg `à` becomes `Ã`, `ù` becomes `Ã¹`).

### Audacity Version

latest beta

### Operating system

Windows

**Comment by LWinterberg** [comment]
I can reproduce this when compiling locally on windows. I don't understands where it comes from, because locale/CMakeLists.txt does the same steps you do for the fix as well. 

This only appears to occur on the italian translation; french, spanish, german and danish look fine to me. The it.po file itself also looks fine to me.

**Comment by LWinterberg** [comment]
This is the same as https://github.com/audacity/audacity/issues/3691, so it's relatively long-standing.

**Comment by Jessetw** [comment]
I also have an issue showing zh-tw, I am not sure if it is the same issue or not.

![image](https://github.com/audacity/audacity/assets/16289549/f44c951a-d5c3-4ee7-8418-ebd9324eb697)

**Comment by LWinterberg** [comment]
On Linux, compiling it and then running `msgunfmt` on the mo to get the translation back, everything still seems fine.

**Comment by mlocati** [comment]
How do the `.mo` files that get installed are generated?

**Comment by crsib** [comment]
It does read the encoding metadata: https://github.com/audacity/audacity/blob/16df49d02783b96a2151752091cd096028c36126/locale/msgfmt.py#L157

**Comment by mlocati** [comment]
I think I found the issue: `locale/msgfmt.py` doesn't place in the `.mo` files the strings that are marked as "fuzzy".

The problem is that the header of .po files is usually marked as fuzzy:

```po
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: audacity 3.5.0\n"
"Report-Msgid-Bugs-To: audacity-translation@lists.sourceforge.net\n"
"POT-Creation-Date: 2024-04-04 21:13+0300\n"
"PO-Revision-Date: 2024-04-06 16:47+0000\n"
"Last-Translator: Michele Locati <michele@locati.it>, 2024\n"
"Language-Team: Italian (https://app.transifex.com/klyok/teams/690/it/)\n"
"Language: it\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=n == 1 ? 0 : n != 0 && n % 1000000 == 0 ? 1 : 2;\n"
```

So, `locale/msgfmt.py` doesn't write the header to the .mo files, thus when it's read, the encoding used is the default one (which I guess is something like latin1 or iso-8859) instead of utf-8.

**Comment by crsib** [comment]
Interestingly, I don't have this problem, at least with portable beta 3

![image](https://github.com/audacity/audacity/assets/2660628/86a46678-752e-4d76-ab42-78149c2b9e49)

**Comment by mlocati** [comment]
@crsib does your `Languages/it/audacity.mo` file contain the string `Content-Transfer-Encoding`?

**Comment by crsib** [comment]
It does not

**Comment by mlocati** [comment]
Maybe your environment is configured to use utf-8 as the default gettext charset... I checked installing audacity 3.5 beta on a Windows Sandbox, and the bug is there

**Comment by mlocati** [comment]
#6284 should fix this issue

**Comment by crsib** [comment]
Whoa, that was really quick! Thank you!

**Comment by crsib** [comment]
Can you please rebase onto `release-3.5.0` and force push @mlocati ?

**Comment by mlocati** [comment]
> Can you please rebase onto `release-3.5.0` and force push @mlocati ?

@crsib done.

**Comment by crsib** [comment]
I've moved the issue into the QA state
