### ISSUE TITLE
Preference: 4 items cannot localize on 3.5.0 beta

### ISSUE THREAD

**Issue by SakiPapa** [audacity/audacity#6291]
### Bug description

Following 4 items of Preference Panel cannot localize.
Preference / Interface / Option
    □Show 'What's new' dialog at launch
Preference / Cloud / export behavior
    □Show 'How would you like to export?' dialog
Preference / Cloud / save behavior
    ○Alwavs save to cloud
    ○Always save to the computer

### Steps to reproduce

1. Download audacity.pot file from https://github.com/audacity/audacity/tree/release-3.5.0/locale
2. Open audacity.pot with Poedit and create new translation (example: Japanese)
3. Translate the following items of ID581, 584, 585, 3392
4. Save the translated po file (example ja.po),and also mo file (example ja.mo).
5. Rename mo file (example ja.mo) to "audacity.mo"
6. Replace Audacity version 3.5.0 beta3's localize file(audacity.mo). (example:  Windows: C:\Program Files (x86)\Audacity\Languages\ja\, macOS: Applications/Audacity.app/Contents/Resources/ja.lproj/)
7. Run Audacity and open Preference.

### Expected behavior

Whole Preference Panel's words should be localized.

### Actual behavior

Following 4 items are English (not translated).

Preference / Interface / Option
    □Show 'What's new' dialog at launch
<img width="1064" alt="pref_interface" src="https://github.com/audacity/audacity/assets/106289731/234780f8-d0b2-4ac5-b482-327f8c17f6ca">
Preference / Cloud / export behavior
    □Show 'How would you like to export?' dialog
Preference / Cloud / save behavior
    ○Alwavs save to cloud
    ○Always save to the computer
<img width="1064" alt="pref_cloud" src="https://github.com/audacity/audacity/assets/106289731/75668fd2-8d43-4b90-b103-f622b204be00">

### Audacity Version

3.5.0 beta 3

### Operating system

Windows
macOS

### Additional context

Words of audacity.pot file's ID 3392 should not
"Show 'How to Get &Help' at launch"
but
"'What's new' dialog at launch" ?

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
