### ISSUE TITLE
Ctrl + Q/Ctrl + W causes the project not fully synced to the Cloud to vanish

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#6292]
### Steps to reproduce

1. Import a song/generate 5 min of anything
2. Initiate Cloud upload
3. Cut out the internet midway through
4. Ctrl + W or Ctrl + Q
5. Observe

### Expected behavior

The "Do you want to save?" dialog pops up since the project was never saved.

### Actual behavior

No "Do you want to save?" dialog; Audacity closes the project without warning (Ctrl + W) or quits (Ctrl + Q). The project is gone and cannot be restored upon the next launch.

### Audacity Version

current master / alpha / nightly build

### Operating system

Other

**Comment by crsib** [comment]
I don't quite agree that this is a bug. I probably don't quite understand what actual behavior means here. After the snapshot was created successfully, and this is clearly the case here, Audacity fully saves the project to the local cache. It marks the project as not fully synced, so the sync could be finished the next time the user opens the project. 

The recovery dialog is not expected in this case, the project IS fully saved.

**Comment by dozzzzer** [comment]
Now that I give it a second look I cannot reproduce the original issue (previously, no snapshot was created in CloudProjects directory).

**Comment by DavidBailes** [comment]
> It marks the project as not fully synced, so the sync could be finished the next time the user opens the project.

As long as the user opens it before it is automatically deleted after X days.

**Comment by crsib** [comment]
Only fully synced projects are cleaned up
