### ISSUE TITLE
Add binary release files to github

### ISSUE THREAD

**Issue by martinlindhe** [audacity/audacity#63]
Greetings all!

Would it be possible to attach the binaries you released at http://www.fosshub.com/Audacity.html/audacity-macosx-ub-<version>.dmg to the "2.1.1" release on github? See bottom of link [1] for details.

The reason I'm asking is that the new host fosshub.com don't seem to allow any stable download links to be used in scripts, in my case particular homebrew-cask [2].

1: https://github.com/blog/1547-release-your-software
2: https://github.com/caskroom/homebrew-cask

**Comment by JamesCrook** [comment]
Hi Martin,

We don't want to put binary files in the Git repo itself for obvious reasons.  Attaching as a release object isn't something I was aware of before, so thanks for the info.  We're generally trying to keep our use of GitHub to 'pure git' use, and not use extras such as even this issue tracking system.  I therefore think it's unlikely we will use GitHub releases for binary releases.    If you'd like to argue the case for doing so with more people, explain more about why and lobby for it, the audacity-devel mailing list is a better place.  Nothing stops you hosting your own binary releases on your own GitHub fork of Audacity, provided you comply with Audacity GPL licensing terms, and you could then ensure that the binaries/downloads work correctly with your homebrew-cask.

--James.

**Comment by JamesCrook** [comment]
Meant to close the issue with previous comment.

**Comment by martinlindhe** [comment]
Thanks. I don't care enough for this issue to host my own binaries for your project, it was merely a suggestion to help your users, since your current host fosshub.com don't allow direct downloads (their page is riddled with javascript to prevent hot-linking)

**Comment by JamesCrook** [comment]
Thanks for the feedback Martin.

**Comment by karbassi** [comment]
@JamesCrook since some time has passed, any thoughts on this in 2019/2020? Thank you for all the hard work on an amazing project.

**Comment by JamesCrook** [comment]
Thanks @karbassi . We're still happy with hosting our binaries at FossHub.
