### ISSUE TITLE
Remove "Select" button from track headers

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#6307]
Audacity currently has a "select" button in the track headers which users can click to select the entire track. However, users also can click *anywhere* into the track header to select the entire track. 

Clicking onto an item to select it is a well-understood pattern that's been around in file browsers and similar since the dawn of UI. Similarly, clicking on headers to select the item its connected to is something we already use in Audacity for clips. 

The button therefore is not necessary and adds a bunch of visual noise, especially in dense multi-track environments. It should get removed.

**Comment by LWinterberg** [comment]
Yes, the current track headers are indeed not communicating that they are selectable items themselves. That is something I will change via a new theme.

**Comment by dozzzzer** [comment]
Tested
