### ISSUE TITLE
macOs intel build fail

### ISSUE THREAD

**Issue by xtuyaowu** [audacity/audacity#6313]
### Bug description

build fail  release-3.5.0

### Steps to reproduce

(base) mac@localhost build % gcc --version
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: x86_64-apple-darwin21.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
(base) mac@localhost build % g++ --version

Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: x86_64-apple-darwin21.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
(base) mac@localhost build % cmake --version
cmake version 3.24.0-rc1

CMake suite maintained and supported by Kitware (kitware.com/cmake).

build fail：

[40/513] Building CXX object libraries/lib-effects/CMakeFiles/lib-effects.dir/PerTrackEffect.cpp.o
FAILED: libraries/lib-effects/CMakeFiles/lib-effects.dir/PerTrackEffect.cpp.o 

### Expected behavior

build and run success

### Audacity Version

stable version (from a Linux repository)

### Operating system

macOS

**Comment by LWinterberg** [comment]
macOS builds on CI just fine several times a day. Please post the full log and the actual steps you're taking to reproduce it (ie, build commands).

**Comment by xtuyaowu** [comment]
@LWinterberg thanks ,flowing is the full cmake output thanks:

====================[ Build | Audacity | Debug ]================================
"/Users/mac/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/221.5787.29/CLion.app/Contents/bin/cmake/mac/bin/cmake" --build /Users/mac/Documents/study/workspace/audacity/cmake-build-debug --target Audacity -j 9
[3/513] Building CXX object libraries/lib-wave-track/CMakeFiles/lib-wave-track.dir/SampleBlock.cpp.o
In file included from /Users/mac/Documents/study/workspace/audacity/libraries/lib-wave-track/SampleBlock.cpp:11:
In file included from /Users/mac/Documents/study/workspace/audacity/libraries/lib-wave-track/SampleBlock.h:12:
/Users/mac/Documents/study/workspace/audacity/libraries/lib-utility/GlobalVariable.h:46:7: warning: expression result unused [-Wunused-value]
      &GlobalVariable::Assign;
      ^~~~~~~~~~~~~~~~~~~~~~~
/Users/mac/Documents/study/workspace/audacity/libraries/lib-wave-track/SampleBlock.cpp:18:29: note: in instantiation of member function 'GlobalVariable<SampleBlockFactory::Factory, const std::function<std::shared_ptr<SampleBlockFactory> (AudacityProject &)>, nullptr, true>::Get' requested here
   auto &factory = Factory::Get();
                            ^
1 warning generated.
[15/513] Building CXX object libraries/lib-project-history/CMakeFiles/lib-project-history.dir/ProjectHistory.cpp.o
In file included from /Users/mac/Documents/study/workspace/audacity/libraries/lib-project-history/ProjectHistory.cpp:11:
In file included from /Users/mac/Documents/study/workspace/audacity/libraries/lib-project-history/ProjectHistory.h:15:
/Users/mac/Documents/study/workspace/audacity/libraries/lib-utility/GlobalVariable.h:46:7: warning: expression result unused [-Wunused-value]
      &GlobalVariable::Assign;
      ^~~~~~~~~~~~~~~~~~~~~~~
/Users/mac/Documents/study/workspace/audacity/libraries/lib-utility/GlobalVariable.h:171:30: note: in instantiation of member function 'GlobalVariable<ProjectHistory::AutoSave, const std::function<void (AudacityProject &)>, nullptr, true>::Get' requested here
      auto &fn = GlobalHook::Get();
                             ^
/Users/mac/Documents/study/workspace/audacity/libraries/lib-project-history/ProjectHistory.cpp:76:17: note: in instantiation of function template specialization 'GlobalHook<ProjectHistory::AutoSave, void (AudacityProject &), nullptr>::Call<AudacityProject &>' requested here
      AutoSave::Call(project);
                ^
1 warning generated.
[20/513] Building CXX object libraries/lib-realtime-effects/CMakeFiles/lib-realtime-effects.dir/RealtimeEffectState.cpp.o
In file included from /Users/mac/Documents/study/workspace/audacity/libraries/lib-realtime-effects/RealtimeEffectState.cpp:11:
In file included from /Users/mac/Documents/study/workspace/audacity/libraries/lib-realtime-effects/RealtimeEffectState.h:21:
/Users/mac/Documents/study/workspace/audacity/libraries/lib-utility/GlobalVariable.h:46:7: warning: expression result unused [-Wunused-value]
      &GlobalVariable::Assign;
      ^~~~~~~~~~~~~~~~~~~~~~~
/Users/mac/Documents/study/workspace/audacity/libraries/lib-utility/GlobalVariable.h:171:30: note: in instantiation of member function 'GlobalVariable<RealtimeEffectState::EffectFactory, const std::function<const EffectInstanceFactory *(const wxString &)>, nullptr, true>::Get' requested here
      auto &fn = GlobalHook::Get();
                             ^
/Users/mac/Documents/study/workspace/audacity/libraries/lib-realtime-effects/RealtimeEffectState.cpp:347:32: note: in instantiation of function template specialization 'GlobalHook<RealtimeEffectState::EffectFactory, const EffectInstanceFactory *(const wxString &), nullptr>::Call<wxString &>' requested here
      mPlugin = EffectFactory::Call(mID);
                               ^
1 warning generated.
[29/513] Building CXX object libraries/lib-module-manager/CMakeFiles/lib-module-manager.dir/PluginHost.cpp.o
In file included from /Users/mac/Documents/study/workspace/audacity/libraries/lib-module-manager/PluginHost.cpp:13:
In file included from /Users/mac/Documents/study/workspace/audacity/libraries/lib-module-manager/PluginHost.h:16:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/memory:682:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__memory/shared_ptr.h:25:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__memory/unique_ptr.h:57:5: warning: delete called on 'PluginProvider::Validator' that is abstract but has non-virtual destructor [-Wdelete-abstract-non-virtual-dtor]
    delete __ptr;
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__memory/unique_ptr.h:318:7: note: in instantiation of member function 'std::default_delete<PluginProvider::Validator>::operator()' requested here
      __ptr_.second()(__tmp);
      ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__memory/unique_ptr.h:272:19: note: in instantiation of member function 'std::unique_ptr<PluginProvider::Validator>::reset' requested here
  ~unique_ptr() { reset(); }
                  ^
/Users/mac/Documents/study/workspace/audacity/libraries/lib-module-manager/PluginHost.cpp:38:40: note: in instantiation of member function 'std::unique_ptr<PluginProvider::Validator>::~unique_ptr' requested here
            auto validator = provider->MakeValidator();
                                       ^
In file included from /Users/mac/Documents/study/workspace/audacity/libraries/lib-module-manager/PluginHost.cpp:22:
In file included from /Users/mac/Documents/study/workspace/audacity/libraries/lib-files/FileNames.h:16:
In file included from /Users/mac/Documents/study/workspace/audacity/libraries/lib-preferences/Prefs.h:49:
/Users/mac/Documents/study/workspace/audacity/libraries/lib-utility/GlobalVariable.h:46:7: warning: expression result unused [-Wunused-value]
      &GlobalVariable::Assign;
      ^~~~~~~~~~~~~~~~~~~~~~~
/Users/mac/Documents/study/workspace/audacity/libraries/lib-utility/GlobalVariable.h:171:30: note: in instantiation of member function 'GlobalVariable<audacity::ApplicationSettings, const std::function<std::unique_ptr<audacity::BasicSettings> ()>, nullptr, true>::Get' requested here
      auto &fn = GlobalHook::Get();
                             ^
/Users/mac/Documents/study/workspace/audacity/libraries/lib-module-manager/PluginHost.cpp:80:51: note: in instantiation of function template specialization 'GlobalHook<audacity::ApplicationSettings, std::unique_ptr<audacity::BasicSettings> (), nullptr>::Call<>' requested here
   InitPreferences(audacity::ApplicationSettings::Call());
                                                  ^
2 warnings generated.
[40/513] Building CXX object libraries/lib-effects/CMakeFiles/lib-effects.dir/PerTrackEffect.cpp.o
FAILED: libraries/lib-effects/CMakeFiles/lib-effects.dir/PerTrackEffect.cpp.o 
/usr/local/bin/ccache /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DAUDIO_DEVICES_API="" -DAUDIO_GRAPH_API="" -DBASIC_UI_API="" -DCHANNEL_API="" -DCOMMAND_PARAMETERS_API="" -DCOMPONENTS_API="" -DEFFECTS_API="" -DEXCEPTIONS_API="" -DEXPERIMENTAL_CRASH_REPORT -DEXPERIMENTAL_DRAGGABLE_PLAY_HEAD -DEXPERIMENTAL_FULL_WASAPI -DEXPERIMENTAL_HALF_WAVE -DEXPERIMENTAL_KEY_VIEW -DEXPERIMENTAL_MIDI_OUT -DEXPERIMENTAL_MODULE_PREFS -DEXPERIMENTAL_NOISE_REDUCTION -DEXPERIMENTAL_NOTETRACK_OVERLAY -DEXPERIMENTAL_NYQUIST_SPLIT_CONTROL -DEXPERIMENTAL_PUNCH_AND_ROLL -DEXPERIMENTAL_SCIENCE_FILTERS -DEXPERIMENTAL_SCRUBBING_SCROLL_WHEEL -DEXPERIMENTAL_SCRUBBING_SUPPORT -DEXPERIMENTAL_SPECTRAL_EDITING -DEXPERIMENTAL_SUBRIP_LABEL_FORMATS -DEXPERIMENTAL_THEMING -DEXPERIMENTAL_ZOOM_TOGGLE_BUTTON -DFILES_API="" -DIPC_API="" -DMATH_API="" -DMIXER_API="" -DMODULE_MANAGER_API="" -DNUMERIC_FORMATS_API="" -DPLAYABLE_TRACK_API="" -DPREFERENCES_API="" -DPROJECT_API="" -DPROJECT_HISTORY_API="" -DPROJECT_RATE_API="" -DREALTIME_EFFECTS_API="" -DREGISTRIES_API="" -DSAMPLE_TRACK_API="" -DSCREEN_GEOMETRY_API="" -DSNAPPING_API="" -DSTRETCHING_SEQUENCE_API="" -DSTRINGS_API="" -DSTRING_UTILS_API="" -DTIME_AND_PITCH_API="" -DTIME_FREQUENCY_SELECTION_API="" -DTRACK_API="" -DTRACK_SELECTION_API="" -DTRANSACTIONS_API="" -DUNCAUGHT_EXCEPTIONS_UNAVAILABLE -DUSE_PORTMIXER=1 -DUTILITY_API="" -DWAVE_TRACK_API="" -DWXUSINGDLL -DXML_API="" -D_WX_APP_H_BASE_ -D_WX_BRUSH_H_BASE_ -D_WX_COLOUR_H_BASE_ -D_WX_EVTLOOP_H_ -D_WX_IMAGE_H -D_WX_PEN_H_BASE_ -D__WXDEBUG__ -D__WXMAC__ -D__WXOSX_COCOA__ -D__WXOSX__ -Dlib_effects_EXPORTS -DwxUSE_GUI=0 -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-effects -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-command-parameters -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-preferences -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-basic-ui -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-strings -I/Users/mac/Documents/study/workspace/audacity/cmake-build-debug/generators/../conan/home/p/wxwida84c2b1f1091c/p/include -I/Users/mac/Documents/study/workspace/audacity/cmake-build-debug/generators/../conan/home/p/wxwida84c2b1f1091c/p/include/wx-3.1 -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-components -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-utility -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-numeric-formats -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-math -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-project-rate -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-project -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-registries -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-exceptions -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-xml -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-files -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-string-utils -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-audio-devices -I/Users/mac/Documents/study/workspace/audacity/lib-src/portmixer/include -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-realtime-effects -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-channel -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-module-manager -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-ipc -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-project-history -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-transactions -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-stretching-sequence -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-time-and-pitch -I/Users/mac/Documents/study/workspace/audacity/lib-src/pffft -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-mixer -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-audio-graph -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-wave-track -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-sample-track -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-playable-track -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-track -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-track-selection -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-time-frequency-selection -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-snapping -I/Users/mac/Documents/study/workspace/audacity/libraries/lib-screen-geometry -isystem /Users/mac/Documents/study/workspace/audacity/cmake-build-debug/generators/../conan/home/p/zlibbbb5a233a0365/p/include -isystem /Users/mac/Documents/study/workspace/audacity/cmake-build-debug/generators/../conan/home/p/porta522c269e394ab/p/include -stdlib=libc++ -g -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=10.9 -fPIC -include /Users/mac/Documents/study/workspace/audacity/cmake-build-debug/src/private/configmac.h -DAUDACITY_VERSION=3 -DAUDACITY_RELEASE=5 -DAUDACITY_REVISION=0 -DAUDACITY_MODLEVEL=0 -DAUDACITY_VERSION_STRING=L\"3.5.0-alpha-20240420\" -DAUDACITY_FILE_VERSION=L\"3,5,0,0\" -Dsafenew=new -Wno-underaligned-exception-object -Werror=return-type -Werror=dangling-else -Werror=return-stack-address -Werror=defaulted-function-deleted -DWXINTL_NO_GETTEXT_MACRO -D_DEBUG=1 -DUSE_AQUA_THEME -DIS_ALPHA -std=gnu++17 -MD -MT libraries/lib-effects/CMakeFiles/lib-effects.dir/PerTrackEffect.cpp.o -MF libraries/lib-effects/CMakeFiles/lib-effects.dir/PerTrackEffect.cpp.o.d -o libraries/lib-effects/CMakeFiles/lib-effects.dir/PerTrackEffect.cpp.o -c /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp
In file included from /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:27:
In file included from /Users/mac/Documents/study/workspace/audacity/libraries/lib-track-selection/SyncLock.h:15:
In file included from /Users/mac/Documents/study/workspace/audacity/libraries/lib-track/Track.h:28:
/Users/mac/Documents/study/workspace/audacity/libraries/lib-utility/TypeSwitch.h:207:59: error: no member named 'SetUsed' in 'std::integral_constant<bool, true>'
      return std::integral_constant<unsigned, (Executors::SetUsed | ...)>{};
                                                          ^
/Users/mac/Documents/study/workspace/audacity/libraries/lib-utility/TypeSwitch.h:236:19: note: in instantiation of member function 'TypeSwitch::detail::UsedCases<TypeSwitch::detail::Executor<void, TypeList::List<Track, AudioTrack, PlayableTrack, SampleTrack, WritableSampleTrack, WaveTrack>, TypeList::List<const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:317:7) &, const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:311:7) &>>::Combine<TypeList::List<const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:317:7) &, const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:311:7) &>, TypeSwitch::detail::Executor<void, TypeList::List<Track, AudioTrack, PlayableTrack, SampleTrack, WritableSampleTrack, WaveTrack>, TypeList::List<const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:317:7) &, const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:311:7) &>>::Combine<TypeList::List<const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:311:7) &>, TypeSwitch::detail::Executor<void, TypeList::List<Track, AudioTrack, PlayableTrack, SampleTrack, WritableSampleTrack, WaveTrack>, TypeList::List<const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:317:7) &, const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:311:7) &>>::NoOp>>::Transparent::type, TypeSwitch::detail::Executor<void, TypeList::List<AudioTrack, PlayableTrack, SampleTrack, WritableSampleTrack, WaveTrack>, TypeList::List<const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:317:7) &, const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:311:7) &>>::Combine<TypeList::List<const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:317:7) &, const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:311:7) &>, TypeSwitch::detail::Executor<void, TypeList::List<AudioTrack, PlayableTrack, SampleTrack, WritableSampleTrack, WaveTrack>, TypeList::List<const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:317:7) &, const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:311:7) &>>::Combine<TypeList::List<const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:311:7) &>, TypeSwitch::detail::Executor<void, TypeList::List<AudioTrack, PlayableTrack, SampleTrack, WritableSampleTrack, WaveTrack>, TypeList::List<const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:317:7) &, const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:311:7) &>>::NoOp>>::Transparent::type, TypeSwitch::detail::Executor<void, TypeList::List<PlayableTrack, SampleTrack, WritableSampleTrack, WaveTrack>, TypeList::List<const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:317:7) &, const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:311:7) &>>::Combine<TypeList::List<const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:317:7) &, const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:311:7) &>, TypeSwitch::detail::Executor<void, TypeList::List<PlayableTrack, SampleTrack, WritableSampleTrack, WaveTrack>, TypeList::List<const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:317:7) &, const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:311:7) &>>::Combine<TypeList::List<const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:311:7) &>, TypeSwitch::detail::Executor<void, TypeList::List<PlayableTrack, SampleTrack, WritableSampleTrack, WaveTrack>, TypeList::List<const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:317:7) &, const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:311:7) &>>::NoOp>>::Transparent::type, TypeSwitch::detail::Executor<void, TypeList::List<SampleTrack, WritableSampleTrack, WaveTrack>, TypeList::List<const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:317:7) &, const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:311:7) &>>::Combine<TypeList::List<const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:317:7) &, const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:311:7) &>, TypeSwitch::detail::Executor<void, TypeList::List<SampleTrack, WritableSampleTrack, WaveTrack>, TypeList::List<const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:317:7) &, const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:311:7) &>>::Combine<TypeList::List<const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:311:7) &>, TypeSwitch::detail::Executor<void, TypeList::List<SampleTrack, WritableSampleTrack, WaveTrack>, TypeList::List<const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:317:7) &, const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:311:7) &>>::NoOp>>::Transparent::type, TypeSwitch::detail::Executor<void, TypeList::List<WritableSampleTrack, WaveTrack>, TypeList::List<const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:317:7) &, const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:311:7) &>>::Combine<TypeList::List<const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:317:7) &, const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:311:7) &>, TypeSwitch::detail::Executor<void, TypeList::List<WritableSampleTrack, WaveTrack>, TypeList::List<const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:317:7) &, const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:311:7) &>>::Combine<TypeList::List<const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:311:7) &>, TypeSwitch::detail::Executor<void, TypeList::List<WritableSampleTrack, WaveTrack>, TypeList::List<const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:317:7) &, const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:311:7) &>>::NoOp>>::Transparent::type, std::integral_constant<bool, true>>::operator()' requested here
         decltype(Apply_t<UsedCases, Executors>{}())
                  ^
/Users/mac/Documents/study/workspace/audacity/libraries/lib-utility/TypeSwitch.h:318:11: note: in instantiation of template class 'TypeSwitch::detail::TypeSwitcher<void, TypeList::List<Track, AudioTrack, PlayableTrack, SampleTrack, WritableSampleTrack, WaveTrack>, TypeList::List<const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:317:7) &, const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:311:7) &>>' requested here
   return detail::TypeSwitcher<R, Types, Bind_t<TupleLike>, Args...>{}(
          ^
/Users/mac/Documents/study/workspace/audacity/libraries/lib-utility/TypeSwitch.h:333:11: note: in instantiation of function template specialization 'TypeSwitch::Dispatch<void, TypeList::List<Track, AudioTrack, PlayableTrack, SampleTrack, WritableSampleTrack, WaveTrack>, std::tuple<const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:317:7) &, const (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:311:7) &>>' requested here
   return Dispatch<R, Types>(object, std::forward_as_tuple(functions...));
          ^
/Users/mac/Documents/study/workspace/audacity/libraries/lib-track/Track.h:936:17: note: in instantiation of function template specialization 'Track::TypeSwitch<void, (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:317:7), (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:311:7)>' requested here
         track->TypeSwitch(functions...);
                ^
/Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:316:18: note: in instantiation of function template specialization 'TrackIterRange<Track>::VisitWhile<bool, (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:317:7), (lambda at /Users/mac/Documents/study/workspace/audacity/libraries/lib-effects/PerTrackEffect.cpp:311:7)>' requested here
   outputs.Any().VisitWhile(bGoodResult,
                 ^
1 error generated.
[44/513] Building CXX object libraries/lib-import-export/CMakeFiles/lib-import-export.dir/LibsndfileTagger.cpp.o
/Users/mac/Documents/study/workspace/audacity/libraries/lib-import-export/LibsndfileTagger.cpp:17:43: warning: 'tmpnam' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of tmpnam(3), it is highly recommended that you use mkstemp(3) instead. [-Wdeprecated-declarations]
    : mFilename { filename.empty() ? std::tmpnam(nullptr) : filename }
                                          ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/stdio.h:186:1: note: 'tmpnam' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of tmpnam(3), it is highly recommended that you use mkstemp(3) instead.")
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/sys/cdefs.h:208:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
1 warning generated.
[46/513] Building CXX object libraries/lib-import-export/CMakeFiles/lib-import-export.dir/ExportUtils.cpp.o
In file included from /Users/mac/Documents/study/workspace/audacity/libraries/lib-import-export/ExportUtils.cpp:18:
/Users/mac/Documents/study/workspace/audacity/libraries/lib-track/Track.h:875:38: warning: 'not1<std::__mem_fn<bool (WaveTrack::*)() const>>' is deprecated [-Wdeprecated-declarations]
      return this->operator + ( std::not1( std::mem_fn( pmf ) ) );
                                     ^
/Users/mac/Documents/study/workspace/audacity/libraries/lib-import-export/ExportUtils.cpp:29:7: note: in instantiation of function template specialization 'TrackIterRange<const WaveTrack>::operator-<bool, WaveTrack>' requested here
      - (anySolo ? &WaveTrack::GetNotSolo : &WaveTrack::GetMute);
      ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__functional/unary_negate.h:39:1: note: 'not1<std::__mem_fn<bool (WaveTrack::*)() const>>' has been explicitly marked deprecated here
_LIBCPP_DEPRECATED_IN_CXX17 inline _LIBCPP_CONSTEXPR_AFTER_CXX11 _LIBCPP_INLINE_VISIBILITY
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__config:1066:39: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX17'
#  define _LIBCPP_DEPRECATED_IN_CXX17 _LIBCPP_DEPRECATED
                                      ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__config:1043:48: note: expanded from macro '_LIBCPP_DEPRECATED'
#    define _LIBCPP_DEPRECATED __attribute__ ((deprecated))
                                               ^
1 warning generated.
[48/513] Building CXX object libraries/lib-import-export/CMakeFiles/lib-import-export.dir/Import.cpp.o
ninja: build stopped: subcommand failed.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444) which uses a different build system. This bug should no longer be applicable.
