### ISSUE TITLE
Relegate legacy compressor and limiter

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#6319]
Not to overwhelm the user with a range of implementations, after https://github.com/audacity/audacity/issues/6305 (and follow-up tickets) is merged, the legacy compressor and limiter should be removed from the default menu.
The compressor was a Nyquist script ported to C++. Can it be uncovered and added to the plugin page?
Double-check that the limiter.ny found in https://plugins.audacityteam.org/nyquist-plugins/effect-plugins/dynamics-processing is the one currently to be found in Audacity, and there'd be nothing to do for that effect.

**Comment by saintmatthieu** [comment]
@SteveDaulton [the limiter script on our website](https://plugins.audacityteam.org/nyquist-plugins/effect-plugins/dynamics-processing#limiter) differs quite a lot from the nyquist file that's currently checked in the repo. Is there one which is outdated?

**Comment by SteveDaulton** [comment]
> @SteveDaulton [the limiter script on our website](https://plugins.audacityteam.org/nyquist-plugins/effect-plugins/dynamics-processing#limiter) differs quite a lot from the nyquist file that's currently checked in the repo. Is there one which is outdated?

The limiter.ny at https://2455084635-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FklCVENFte0GRy5IqVz0W%2Fuploads%2Fl7wqsRgm2AH6H8flJwVe%2FLimiter.ny is much older than the limiter.ny at https://github.com/audacity/audacity/blob/master/plug-ins/limiter.ny

**Comment by LWinterberg** [comment]
I'll put the one found in Audacity at the moment there as well in a bit
