### ISSUE TITLE
"Progress" window stuck after applying macro to files

### ISSUE THREAD

**Issue by stefantalpalaru** [audacity/audacity#6321]
### Bug description

![audacity](https://github.com/audacity/audacity/assets/495550/45ddaa0f-e6a2-46b3-b3cc-80d417fc3684)

### Steps to reproduce

Tools -> Macro Manager
Apply Macro to: Files...

Select some files. The macro is applied properly and all the expected output is produced, but then it gets stuck on that black "Progress" window that cannot be closed. Nor can the "Manage Macros" window behind it.

There is no console output.

### Expected behavior

See above. This did not happen with 3.4.2, so it's something introduced by 3.5.0.

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

**Comment by LWinterberg** [comment]
Actually, I can reproduce it on Windows now. Instead of a progress window, the result textbox flashes a couple of times, disappears, and then Audacity doesn't respond to any input.

**Comment by saintmatthieu** [comment]
@stefantalpalaru would you be so kind to re-test with this build once it's done? https://github.com/saintmatthieu/audacity/actions/runs/8801396388
This does fix something in that realm but I hardly can give proof that this is the very problem you are having.

**Comment by stefantalpalaru** [comment]
Yes, your commit fixes my problem, @saintmatthieu.

**Comment by saintmatthieu** [comment]
> Yes, your commit fixes my problem, @saintmatthieu.

Thanks for your report and support, @stefantalpalaru !

**Comment by dozzzzer** [comment]
Tested
