### ISSUE TITLE
3.5.0 crash on Catalina at launch

### ISSUE THREAD

**Issue by jpmelko** [audacity/audacity#6322]
### Steps to reproduce

Launch Audacity

### Expected behavior

Opening a window

### Actual behavior

Crash

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

**Comment by LWinterberg** [comment]
Try downloading the x86_64 version from https://www.audacityteam.org/download/mac/ - does that work?

**Comment by LWinterberg** [comment]
Thank you. 

I imagine you accidentally closed the issue?

**Comment by jpmelko** [comment]
No change
------------------------------
Jean-Pierre Melkonian
***@***.***

**Comment by jpmelko** [comment]
Yes, probably joining the crash
------------------------------
Jean-Pierre Melkonian
***@***.***
