### ISSUE TITLE
Unable to load the 'mod-openvino' module on Audacity 3.5.0

### ISSUE THREAD

**Issue by vivadavid** [audacity/audacity#6323]
### Bug description

After updating to the 3.5.0 version, I got this message when I ran the programme:

![Unable to load the mod-openvino module](https://github.com/audacity/audacity/assets/9334287/61f7b5f8-777a-4015-9fa1-523f2b841ee1)

I've extracted again the contents of the file _Audacity-OpenVINO-Module-3.4.2-R1.zip_, but it didn't work.

### Steps to reproduce

1. I updated Audacity to the 3.5.0 version.
2. I ran Audacity.
3. I got an error message: "Unable to load the 'mod-openvinol' module".

### Expected behavior

Openvino should be recognized and loaded.

### Actual behavior

I can't use Openvino because it keeps getting disabled. If I enable it manually in _Preferences_ > _Modules_, I get the error message again.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by LWinterberg** [comment]
openvino will get updated to 3.5 later today.

**Comment by vivadavid** [comment]
> openvino will get updated to 3.5 later today.

Thank you for your quick reply: will the models be updated too or just the module?

**Comment by vivadavid** [comment]
I've updated OpenVino and it works now. Thanks!
