### ISSUE TITLE
Alpha channel is used for update checks

### ISSUE THREAD

**Issue by crsib** [audacity/audacity#6324]
### Steps to reproduce

1. Install 3.5.0 release
2. Configure proxy
3. Observe, that alpha.xml is requested on updates check

### Expected behavior

latest.xml is used

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows, macOS, Linux

**Comment by crsib** [comment]
I am trying to figure out how to test it. I think, default builds from the release branch would go for beta.xml, but PR builds will go for Alpha anyway. I think we need to run a build in `release` mode manually

**Comment by chinakov** [comment]
Tested, thanks!
