### ISSUE TITLE
OpenVino plugins show as Native Audacity Built-in EGATs in Plugin Manager

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#6334]
### Bug description

OpenVino plugins show as Native Audacity built-in EGATS, when in fact they are additional optional plugins.

### Steps to reproduce

1. Install 3.5.0
2. Install the OpenVino for 3.5
3. launch 3.5.0
4. launch the Plugin Manager
5. set the **Type** filter to be **Native** Audacity
6. Observe: OpenVino EGATs show as **Built-in**

### Expected behavior

OpenVino effects to be in their own "**Type**"

### Actual behavior

![image](https://github.com/audacity/audacity/assets/50205984/78d52ee3-0d91-4b5c-95c5-d50f97ff1564)

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

Flagging @RyanMetcalfeInt8

**Comment by LWinterberg** [comment]
This is correct: Modules are in principle native effects which utilize native Audacity functions. 

The "built-in" is a bit misleading either way, as by the same token, the nyquist plugins bundled with audacity are "build-in" as well but show up as plugins.
