### ISSUE TITLE
xHE-AAC codec request to add

### ISSUE THREAD

**Issue by RossBogdanov** [audacity/audacity#6336]
### Your idea

Please add the _libxaac_ library of the _xHE-AAC_ codec.

https://github.com/ittiam-systems/libxaac

### Problem to be solved

Extended HE-AAC, the latest innovation member of the MPEG AAC codec family, is ideally suited for adaptive bit rate streaming and digital radio applications. Extended HE-AAC bridges the gap between speech and audio coding and ensures consistent high-quality audio for all signal types, including speech, music, and mixed material. It is the required audio codec for DRM (Digital Radio Mondiale). When it comes to coding, the codec is incredibly effective, generating high-quality audio for music and speech at bitrates as low as 6 kbit/s for mono and 12 kbit/s for stereo services. By switching to extremely low bitrate streams, Extended HE-AAC streaming apps and streaming radio players can provide uninterrupted playback even during very congested network conditions.

As the Extended High Efficiency AAC Profile is a logical evolution of the MPEG Audio's popular AAC Family profiles, the codec supports AAC-LC, HE-AACv1 (AAC+) and HE-AACv2 (eAAC+) audio object type encoding. The bitrate that was saved with AAC family tools can be used to enhance video quality. Extended HE-AAC is a well-liked option for a number of applications since it is a strong and effective audio codec that provides high-quality audio at low bitrates.

**Comment by LWinterberg** [comment]
AAC is encumbered with 3077 patents last time I checked. Mercifully they're all together in a patent pool, but at a fee of around 1 USD per Audacity download, they're about 1 USD per download too expensive for us to include in a free download. 

If anything, it'll get added via FFmpeg - https://trac.ffmpeg.org/ticket/8411. The library you listed is licensed Apache, while FFmpeg is LGPL2.1/GPL2, which I believe are incompatible.
