### ISSUE TITLE
Help page for new compressor and limiter

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#6339]
Effects introduced by https://github.com/audacity/audacity/issues/6305 and follow-up tickets should have a help page.

**Comment by saintmatthieu** [comment]
@petersampsonaudacity I know you usually are the one adding these pages, but for my awareness I would like this once to do it myself, if you don't mind?

**Comment by petersampsonaudacity** [comment]
@saintmatthieu 

You're very welcome - the technicalities of the usage of this I;m sure are way above my "pay grade"  👍 

The other tricky thing to manage will be the alphabetic list of EGAT's on this page (released manual):
https://manual.audacityteam.org/man/index_of_effects_generators_and_analyzers.html

_This used to be managed by a tool on the old Wiki, but is not extant in the Manual._

**Comment by petersampsonaudacity** [comment]
@saintmatthieu 

Hi Matthieu,

I have been doing some playing with your recent builds for Realtime Limiter and Relatime Compressor:

1) I note that with the Real Time Limiter just after you move the sliders there come a short set of staccato noises before it settles down with the new setting.  This dose not appear to be the case with Realtime Compressor.

2)  I see that both Realtime Limiter and Relatime Compressor run as normal effects from the Effect menu as well as in the realtime stack.  Does that mean that the intention is to replace the existing effects Limiter and Compressor with the new realtime variants, or will those be retained as well?

**Comment by LWinterberg** [comment]
The existing limiter and compressor will be replaced by the new versions. The limiter, thanks to being a nyquist effect, will remain available though (for whatever that's worth - there already are 4 other nyquist limiters in https://plugins.audacityteam.org/nyquist-plugins/effect-plugins/dynamics-processing )

**Comment by saintmatthieu** [comment]
@petersampsonaudacity thank you so much for trying these out and giving your feedback.
About the stacato noises, that sounds like a bug, except if the slider you've been moving is the look-ahead slider. This parameter modifies the algorithmic delay, and at the moment no measure is taken to smooth this out. It'd be worth considering, though, for our users' comfort.

**Comment by petersampsonaudacity** [comment]
@saintmatthieu 

> About the stacato noises, that sounds like a bug, except if the slider you've been moving is the look-ahead slider.

No it's all the cliders.  I just downloaded your latest build and I still get the same.

I'm using a 30 second mono chirp for the test.

Do you want me to log this as a GitHub issue, or do you want to do that?  _I won't be able to get to do that till tomorrow as I have to go out shortly._



> The existing limiter and compressor will be replaced by the new versions.

@LWinterberg  
thanks for that.   But will the new ones retain the "Realtime" in their menu entries or will they just become **Limiter** and **Compressor** ?

If they use the old names then that does not disturb the alphbetic listing in the EGATs page in the Manual.

Also note that the pre-exiting real-time enabled effects (Bass&Treble, Distortion, Phaser, Reverb and Wahwah) do _**NOT**_ have a "Realtime" added in front of them.

**Comment by petersampsonaudacity** [comment]
> The existing limiter and compressor will be replaced by the new versions.

@LWinterberg  
thanks for that.   But will the new ones retain the "Realtime" in their menu entries or will they just become **Limiter** and **Compressor** ?

If they use the old names then that does not disturb the alphbetic listing in the EGATs page in the Manual (and we have lost the tool for managing taht as it was only in the now-deprecated Wiki).

Also note that the pre-exiting real-time enabled effects (Bass&Treble, Distortion, Phaser, Reverb and Wahwah) do _**NOT**_ have a "Realtime" added in front of them.

**Comment by LWinterberg** [comment]
>  But will the new ones retain the "Realtime" in their menu entries or will they just become Limiter and Compressor?

They will be just Limiter and Compressor.

**Comment by saintmatthieu** [comment]
@petersampsonaudacity I see. There is no smoothing when changing the parameters, and for steady noises, it can be audible indeed.
It's not nice, but so long as we don't have parameter automations, this can't be considered a bug IMO. If you could file an enhancement request though that'd be helpful.

**Comment by saintmatthieu** [comment]
I just pushed a commit that dismisses the legacy compressor and limiter. The new ones now are simply called "Compressor" and "Limiter", as one would expect :D

**Comment by petersampsonaudacity** [comment]
> I just pushed a commit that dismisses the legacy compressor and limiter. The new ones now are simply called "Compressor" and "Limiter"

Hi @saintmatthieu 

Yes that now is fine. 👍 

Testing shows that with both the new effects the **Presets and Settings fail to work**  
a) the **Factory Presets/Default** fails to restore the default settings
b) whilst the user can ser a user preset, these also fail to apply when invoked

Do you want me to raise this as a GitHub issue?

**Comment by petersampsonaudacity** [comment]
> Would you please comment this on #6395? 
Done.

**Comment by petersampsonaudacity** [comment]
@saintmatthieu 

Hi Matthieu,  I note from a comment elsewhere from @LWinterberg that your new Limiter and Compressor may make it into 3.6.0 and that may be as early as next week.

Are you still planning to write the documentation for this in the manual, as you requested earlier in this thread - as otherwise the Compressor an Limiter pages will be out of date and refer/relate to the old replace effects.

If you don't have time I can make a start on this providing graphics and a shell structure (I would still need help from you on the explanation of how the settings work though).

Even if it is unsure whether they make it into 3.6.0 we can still make draft versions on the Talk pages ready for swift implementation if required.

**Comment by petersampsonaudacity** [comment]
@saintmatthieu 

I've prepared a couple of draft pages in my user-space in the Manual:
https://alphamanual.audacityteam.org/man/User:PeterSampson/Compressor
https://alphamanual.audacityteam.org/man/User:PeterSampson/Limiter

There are a couple of TBPs where I have no knowledge at all, for some parameters I have provided drafts based on what was on the old effects' pages - so some editing will be required.

**Comment by saintmatthieu** [comment]
Thanks a million for preparing this, Peter, I'll look into this as soon as the coding side gets a bit more relaxed, hopefully by the end of the week.

**Comment by LWinterberg** [comment]
Note that there's also a history graph when viewed in realtime mode.

**Comment by petersampsonaudacity** [comment]
@LWinterberg @saintmatthieu 

If these are definitely gonna be in 3.6.0 I'll move these across straight away - please advise.

And thanks, Leo, for the reminder about the history graph _(whatever that is and does)_

**Comment by LWinterberg** [comment]
it just got merged, and yes, it'll be shipped.

**Comment by LWinterberg** [comment]
![image](https://github.com/audacity/audacity/assets/87814144/c8fe4332-a85f-4c72-b461-1032e09c29dc)

You may find this image helpful for the understanding of Lookahead vs Attack

**Comment by petersampsonaudacity** [comment]
@LWinterberg @saintmatthieu 

I note that in the Realtime stack the optional history graph is labelled as **Beta**

Should this be the case in a released version?

![image](https://github.com/audacity/audacity/assets/50205984/e203dd06-f48b-4f74-9115-abf560a8be8c)

**Comment by LWinterberg** [comment]
yes. It's in a weird state where it's a little wonky but already a lot more powerful than what came before as it allows you to see what the compressor actually is doing and how it's responding to things.

**Comment by petersampsonaudacity** [comment]
> it just got merged, and yes, it'll be shipped.

OlKso I've moved to draft pages to their correct place in the Manual:
https://alphamanual.audacityteam.org/man/Compressor
https://alphamanual.audacityteam.org/man/Limiter

_I should be able to find some time tomorrow to add draft sections for the RT History graphs_

**Comment by petersampsonaudacity** [comment]
@LWinterberg 

I wasn't querying whether it was "weird" or "wonky" - I was actually querying as to whether it should be labelled "beta" in a released piec eof software _(even if it is in a beta state)_

**Comment by LWinterberg** [comment]
yes, it should.

**Comment by petersampsonaudacity** [comment]
So I have added some material to both pages about realtime use and the graph,

And thanks Leo for your additional material and changes.

**Comment by saintmatthieu** [comment]
Some material to help understand the effect of the smoothing parameters.
* No smoothing: the compression gain is applied instantly. The actual compression (green line) completely overlaps the target compression (blue line). For an infinite ratio, this is equivalent to hard clipping. ![L0_A0_R0](https://github.com/audacity/audacity/assets/22740106/faeec2c6-c588-4e0a-8c2d-aea211eaaa02) 
![L0_A0_R0_in-out](https://github.com/audacity/audacity/assets/22740106/351d9693-31b2-4e9c-8bf1-0170bf3ece1a)
* Look-ahead: allows the compression gain to converge towards the target in anticipation of a peak. The attack is better preserved, at the cost of ramping down the preceding audio. The delay needed for this to be possible is compensated for by Audacity's effect framework. (The graph is not delay-compensated: this is not intentional and should be addressed soon.)
![L200_A0_R0](https://github.com/audacity/audacity/assets/22740106/2ab85623-2444-4d3a-8190-009c3a82de08)
![L200_A0_R0_in-out](https://github.com/audacity/audacity/assets/22740106/07690a76-32ca-4609-8d4e-03283fed52eb)
* Attack: the compression gain converges towards the target _a posteriori._ Reduces the distortion when the input is above the threshold, at the cost of an overshoot of the input, the actual compression always lagging behind the target. 
![L0_A0 1_R0](https://github.com/audacity/audacity/assets/22740106/082e66ad-c173-4565-935e-06e4c257e10f)
![L0_A0 1_R0_in-out](https://github.com/audacity/audacity/assets/22740106/07caec77-b359-4980-8834-477250ba980f)
* Release: when the target becomes less than the current gain, the latter converges towards the target rather than following it exactly. Preserves the decaying parts of the envelope, at the cost of reducing more and longer than strictly needed. 
![L0_A0_R200](https://github.com/audacity/audacity/assets/22740106/135e6535-eb50-4d7f-ac70-a8cc892e6914)
![L0_A0_R200_in-out](https://github.com/audacity/audacity/assets/22740106/53513666-a91f-4417-98db-ac9225a67b75)
