### ISSUE TITLE
Audacity crashed when closing a project and then failed to send the crash report

### ISSUE THREAD

**Issue by kurtekat** [audacity/audacity#6341]
### Bug description

When I closed a project via the menu, the application crashed. When I clicked the option to send the crash report, a pop-up message said it failed to send the report.

### Steps to reproduce

When I originally posted this, I didn't know how to reproduce the issue. The following steps were consistent enough for me, but I had to try several times. There seems to be a similar issue in the history that couldn't be reproduced.

1. Open a project that contains tracks
2. Remove a track
3. Close the project and answer the save prompt as you wish

### Expected behavior

N/A

### Actual behavior

In one case, a read access violation occurs at the vtable when the window calls a method.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

![Capture](https://github.com/audacity/audacity/assets/142125482/087e798a-f8d5-4dd5-88c0-fe6fa1848a75)

[Problem details.zip](https://github.com/audacity/audacity/files/15103182/Problem.details.zip)

**Comment by LWinterberg** [comment]
I could not reproduce this on my win11 machine.

**Comment by kurtekat** [comment]
i'm gonna leave one more note, in case someone is able to reproduce the exception(s).

i added some code to `GetVerticalThumbPosition` in `ProjectWindow.cpp` for testing. when the issue happens, a breakpoint hits at the `return` statement.

```
if (mwWindow->IsBeingDeleted())
   return 0;
```

calling `window->DestroyChildren` (see line 566) after `WaveTrackFactory::Destroy` in `ProjectManager.cpp` seems to make the issue go away.
