### ISSUE TITLE
i686 building error: pffft inlining failed in call to 'always_inline'

### ISSUE THREAD

**Issue by iFoundSilentHouse** [audacity/audacity#6352]
### Bug description

[9/1193] Building C object cmake-proxies/pffft/CMakeFiles/pffft.dir/__/__/lib-src/pffft/pffft.c.o
FAILED: cmake-proxies/pffft/CMakeFiles/pffft.dir/__/__/lib-src/pffft/pffft.c.o
/usr/bin/ccache /usr/bin/cc -DEXPERIMENTAL_CRASH_REPORT -DEXPERIMENTAL_DRAGGABLE_PLAY_HEAD -DEXPERIMENTAL_FULL_WASAPI -DEXPERIMENTAL_HALF_WAVE -DEXPERIMENTAL_KEY_VIEW -DEXPERIMENTAL_MIDI_OUT -DEXPERIMENTAL_MODULE_PREFS -DEXPERIMENTAL_NOISE_REDUCTION -DEXPERIMENTAL_NOTETRACK_OVERLAY -DEXPERIMENTAL_NYQUIST_SPLIT_CONTROL -DEXPERIMENTAL_PUNCH_AND_ROLL -DEXPERIMENTAL_SCIENCE_FILTERS -DEXPERIMENTAL_SCRUBBING_SCROLL_WHEEL -DEXPERIMENTAL_SCRUBBING_SUPPORT -DEXPERIMENTAL_SPECTRAL_EDITING -DEXPERIMENTAL_SUBRIP_LABEL_FORMATS -DEXPERIMENTAL_THEMING -DEXPERIMENTAL_ZOOM_TOGGLE_BUTTON -I/builddir/audacity-3.5.1/lib-src/pffft -DNDEBUG -fstack-clash-protection -D_FORTIFY_SOURCE=2
-mtune=i686 -O2    -ffile-prefix-map=/builddir/audacity-3.5.1/build=. -fPIC -MD -MT
cmake-proxies/pffft/CMakeFiles/pffft.dir/__/__/lib-src/pffft/pffft.c.o -MF cmake-proxies/pffft/CMakeFiles/pffft.dir/__/__/lib-src/pffft/pffft.c.o.d -o cmake-proxies/pffft/CMakeFiles/pffft.dir/__/__/lib-src/pffft/pffft.c.o -c /builddir/audacity-3.5.1/lib-src/pffft/pffft.c
In file included from ../lib-src/pffft/pffft.c:116:
../lib-src/pffft/pfsimd_macros.h: In function 'Vvalidate_simd':
../lib-src/pffft/pfsimd_macros.h:205:23: warning: SSE vector return without SSE enabled changes the ABI [-Wpsabi]
  205 |   t = a0; u = a1; t.v = VZERO();
      |                       ^
In file included from ../lib-src/pffft/pfsimd_macros.h:99:
/usr/lib/gcc/i686-pc-linux-gnu/13.2/include/xmmintrin.h: In function 'passf2_ps':
/usr/lib/gcc/i686-pc-linux-gnu/13.2/include/xmmintrin.h:196:1: error: inlining failed in call to 'always_inline' '_mm_sub_ps': target specific option mismatch
  196 | _mm_sub_ps (__m128 __A, __m128 __B)
      | ^~~~~~~~~~
../lib-src/pffft/pfsimd_macros.h:113:21: note: called from here
  113 | #  define VSUB(a,b) _mm_sub_ps(a,b)
      |                     ^~~~~~~~~~~~~~~
../lib-src/pffft/pffft.c:149:23: note: in expansion of macro 'VSUB'
  149 |       ch[l1ido + 1] = VSUB(cc[1], cc[ido+1]);
      |                       ^~~~
/usr/lib/gcc/i686-pc-linux-gnu/13.2/include/xmmintrin.h:190:1: error: inlining failed in call to 'always_inline' '_mm_add_ps': target specific option mismatch
  190 | _mm_add_ps (__m128 __A, __m128 __B)
      | ^~~~~~~~~~
../lib-src/pffft/pfsimd_macros.h:111:21: note: called from here
  111 | #  define VADD(a,b) _mm_add_ps(a,b)
      |                     ^~~~~~~~~~~~~~~
../lib-src/pffft/pffft.c:148:23: note: in expansion of macro 'VADD'
  148 |       ch[1]         = VADD(cc[1], cc[ido+1]);
      |                       ^~~~
/usr/lib/gcc/i686-pc-linux-gnu/13.2/include/xmmintrin.h:196:1: error: inlining failed in call to 'always_inline' '_mm_sub_ps': target specific option mismatch
  196 | _mm_sub_ps (__m128 __A, __m128 __B)
      | ^~~~~~~~~~
../lib-src/pffft/pfsimd_macros.h:113:21: note: called from here
  113 | #  define VSUB(a,b) _mm_sub_ps(a,b)
      |                     ^~~~~~~~~~~~~~~
../lib-src/pffft/pffft.c:147:23: note: in expansion of macro 'VSUB'
  147 |       ch[l1ido]     = VSUB(cc[0], cc[ido+0]);
      |                       ^~~~
/usr/lib/gcc/i686-pc-linux-gnu/13.2/include/xmmintrin.h:190:1: error: inlining failed in call to 'always_inline' '_mm_add_ps': target specific option mismatch
  190 | _mm_add_ps (__m128 __A, __m128 __B)
      | ^~~~~~~~~~
../lib-src/pffft/pfsimd_macros.h:111:21: note: called from here
  111 | #  define VADD(a,b) _mm_add_ps(a,b)
      |                     ^~~~~~~~~~~~~~~
../lib-src/pffft/pffft.c:146:23: note: in expansion of macro 'VADD'
  146 |       ch[0]         = VADD(cc[0], cc[ido+0]);
      |                       ^~~~
/usr/lib/gcc/i686-pc-linux-gnu/13.2/include/xmmintrin.h:190:1: error: inlining failed in call to 'always_inline' '_mm_add_ps': target specific option mismatch
  190 | _mm_add_ps (__m128 __A, __m128 __B)
      | ^~~~~~~~~~
../lib-src/pffft/pfsimd_macros.h:111:21: note: called from here
  111 | #  define VADD(a,b) _mm_add_ps(a,b)
      |                     ^~~~~~~~~~~~~~~
../lib-src/pffft/pfsimd_macros.h:180:120: note: in expansion of macro 'VADD'
  180 | #define VCPLXMUL(ar,ai,br,bi) { v4sf tmp; tmp=VMUL(ar,bi); ar=VMUL(ar,br); ar=VSUB(ar,VMUL(ai,bi)); ai=VMUL(ai,br); ai=VADD(ai,tmp); }
      |
                                           ^~~~
../lib-src/pffft/pffft.c:159:9: note: in expansion of macro 'VCPLXMUL'
  159 |         VCPLXMUL(tr2, ti2, wr, wi);
      |         ^~~~~~~~
/usr/lib/gcc/i686-pc-linux-gnu/13.2/include/xmmintrin.h:202:1: error: inlining failed in call to 'always_inline' '_mm_mul_ps': target specific option mismatch
  202 | _mm_mul_ps (__m128 __A, __m128 __B)
      | ^~~~~~~~~~
../lib-src/pffft/pfsimd_macros.h:110:21: note: called from here
  110 | #  define VMUL(a,b) _mm_mul_ps(a,b)
      |                     ^~~~~~~~~~~~~~~
../lib-src/pffft/pfsimd_macros.h:180:104: note: in expansion of macro 'VMUL'
  180 | #define VCPLXMUL(ar,ai,br,bi) { v4sf tmp; tmp=VMUL(ar,bi); ar=VMUL(ar,br); ar=VSUB(ar,VMUL(ai,bi)); ai=VMUL(ai,br); ai=VADD(ai,tmp); }
      |
                           ^~~~
../lib-src/pffft/pffft.c:159:9: note: in expansion of macro 'VCPLXMUL'
  159 |         VCPLXMUL(tr2, ti2, wr, wi);
      |         ^~~~~~~~
/usr/lib/gcc/i686-pc-linux-gnu/13.2/include/xmmintrin.h:196:1: error: inlining failed in call to 'always_inline' '_mm_sub_ps': target specific option mismatch
  196 | _mm_sub_ps (__m128 __A, __m128 __B)
      | ^~~~~~~~~~
../lib-src/pffft/pfsimd_macros.h:113:21: note: called from here
  113 | #  define VSUB(a,b) _mm_sub_ps(a,b)
      |                     ^~~~~~~~~~~~~~~
../lib-src/pffft/pfsimd_macros.h:180:79: note: in expansion of macro 'VSUB'
  180 | #define VCPLXMUL(ar,ai,br,bi) { v4sf tmp; tmp=VMUL(ar,bi); ar=VMUL(ar,br); ar=VSUB(ar,VMUL(ai,bi)); ai=VMUL(ai,br); ai=VADD(ai,tmp); }
      |
  ^~~~
../lib-src/pffft/pffft.c:159:9: note: in expansion of macro 'VCPLXMUL'
  159 |         VCPLXMUL(tr2, ti2, wr, wi);
      |         ^~~~~~~~
/usr/lib/gcc/i686-pc-linux-gnu/13.2/include/xmmintrin.h:202:1: error: inlining failed in call to 'always_inline' '_mm_mul_ps': target specific option mismatch
  202 | _mm_mul_ps (__m128 __A, __m128 __B)
      | ^~~~~~~~~~
../lib-src/pffft/pfsimd_macros.h:113:21: note: called from here
  113 | #  define VSUB(a,b) _mm_sub_ps(a,b)
      |                     ^~~~~~~~~~~~~~~
../lib-src/pffft/pfsimd_macros.h:180:79: note: in expansion of macro 'VSUB'
  180 | #define VCPLXMUL(ar,ai,br,bi) { v4sf tmp; tmp=VMUL(ar,bi); ar=VMUL(ar,br); ar=VSUB(ar,VMUL(ai,bi)); ai=VMUL(ai,br); ai=VADD(ai,tmp); }
      |
  ^~~~
../lib-src/pffft/pffft.c:159:9: note: in expansion of macro 'VCPLXMUL'
  159 |         VCPLXMUL(tr2, ti2, wr, wi);
      |         ^~~~~~~~
/usr/lib/gcc/i686-pc-linux-gnu/13.2/include/xmmintrin.h:202:1: error: inlining failed in call to 'always_inline' '_mm_mul_ps': target specific option mismatch
  202 | _mm_mul_ps (__m128 __A, __m128 __B)
      | ^~~~~~~~~~
../lib-src/pffft/pfsimd_macros.h:110:21: note: called from here
  110 | #  define VMUL(a,b) _mm_mul_ps(a,b)
      |                     ^~~~~~~~~~~~~~~
../lib-src/pffft/pfsimd_macros.h:180:63: note: in expansion of macro 'VMUL'
  180 | #define VCPLXMUL(ar,ai,br,bi) { v4sf tmp; tmp=VMUL(ar,bi); ar=VMUL(ar,br); ar=VSUB(ar,VMUL(ai,bi)); ai=VMUL(ai,br); ai=VADD(ai,tmp); }
      |                                                               ^~~~
../lib-src/pffft/pffft.c:159:9: note: in expansion of macro 'VCPLXMUL'
  159 |         VCPLXMUL(tr2, ti2, wr, wi);
      |         ^~~~~~~~
/usr/lib/gcc/i686-pc-linux-gnu/13.2/include/xmmintrin.h:202:1: error: inlining failed in call to 'always_inline' '_mm_mul_ps': target specific option mismatch
  202 | _mm_mul_ps (__m128 __A, __m128 __B)
      | ^~~~~~~~~~
../lib-src/pffft/pfsimd_macros.h:110:21: note: called from here
  110 | #  define VMUL(a,b) _mm_mul_ps(a,b)
      |                     ^~~~~~~~~~~~~~~
../lib-src/pffft/pfsimd_macros.h:180:47: note: in expansion of macro 'VMUL'
  180 | #define VCPLXMUL(ar,ai,br,bi) { v4sf tmp; tmp=VMUL(ar,bi); ar=VMUL(ar,br); ar=VSUB(ar,VMUL(ai,bi)); ai=VMUL(ai,br); ai=VADD(ai,tmp); }
      |                                               ^~~~
../lib-src/pffft/pffft.c:159:9: note: in expansion of macro 'VCPLXMUL'
  159 |         VCPLXMUL(tr2, ti2, wr, wi);
      |         ^~~~~~~~
/usr/lib/gcc/i686-pc-linux-gnu/13.2/include/xmmintrin.h:190:1: error: inlining failed in call to 'always_inline' '_mm_add_ps': target specific option mismatch
  190 | _mm_add_ps (__m128 __A, __m128 __B)
      | ^~~~~~~~~~
../lib-src/pffft/pfsimd_macros.h:111:21: note: called from here
  111 | #  define VADD(a,b) _mm_add_ps(a,b)
      |                     ^~~~~~~~~~~~~~~
../lib-src/pffft/pffft.c:158:19: note: in expansion of macro 'VADD'
  158 |         ch[i+1] = VADD(cc[i+1], cc[i+ido+1]);
      |                   ^~~~
/usr/lib/gcc/i686-pc-linux-gnu/13.2/include/xmmintrin.h:190:1: error: inlining failed in call to 'always_inline' '_mm_add_ps': target specific option mismatch
  190 | _mm_add_ps (__m128 __A, __m128 __B)
      | ^~~~~~~~~~
../lib-src/pffft/pfsimd_macros.h:111:21: note: called from here
  111 | #  define VADD(a,b) _mm_add_ps(a,b)
      |                     ^~~~~~~~~~~~~~~
../lib-src/pffft/pffft.c:157:19: note: in expansion of macro 'VADD'
  157 |         ch[i]   = VADD(cc[i+0], cc[i+ido+0]);
      |                   ^~~~
/usr/lib/gcc/i686-pc-linux-gnu/13.2/include/xmmintrin.h:202:1: error: inlining failed in call to 'always_inline' '_mm_mul_ps': target specific option mismatch
  202 | _mm_mul_ps (__m128 __A, __m128 __B)
      | ^~~~~~~~~~
../lib-src/pffft/pfsimd_macros.h:110:21: note: called from here
  110 | #  define VMUL(a,b) _mm_mul_ps(a,b)
      |                     ^~~~~~~~~~~~~~~
../lib-src/pffft/pfsimd_macros.h:180:47: note: in expansion of macro 'VMUL'
  180 | #define VCPLXMUL(ar,ai,br,bi) { v4sf tmp; tmp=VMUL(ar,bi); ar=VMUL(ar,br); ar=VSUB(ar,VMUL(ai,bi)); ai=VMUL(ai,br); ai=VADD(ai,tmp); }
      |                                               ^~~~
../lib-src/pffft/pffft.c:159:9: note: in expansion of macro 'VCPLXMUL'
  159 |         VCPLXMUL(tr2, ti2, wr, wi);
      |         ^~~~~~~~
/usr/lib/gcc/i686-pc-linux-gnu/13.2/include/xmmintrin.h:190:1: error: inlining failed in call to 'always_inline' '_mm_add_ps': target specific option mismatch
  190 | _mm_add_ps (__m128 __A, __m128 __B)
      | ^~~~~~~~~~
../lib-src/pffft/pfsimd_macros.h:111:21: note: called from here
  111 | #  define VADD(a,b) _mm_add_ps(a,b)
      |                     ^~~~~~~~~~~~~~~
../lib-src/pffft/pffft.c:158:19: note: in expansion of macro 'VADD'
  158 |         ch[i+1] = VADD(cc[i+1], cc[i+ido+1]);
      |                   ^~~~
/usr/lib/gcc/i686-pc-linux-gnu/13.2/include/xmmintrin.h:190:1: error: inlining failed in call to 'always_inline' '_mm_add_ps': target specific option mismatch
  190 | _mm_add_ps (__m128 __A, __m128 __B)
      | ^~~~~~~~~~
../lib-src/pffft/pfsimd_macros.h:111:21: note: called from here
  111 | #  define VADD(a,b) _mm_add_ps(a,b)
      |                     ^~~~~~~~~~~~~~~
../lib-src/pffft/pffft.c:157:19: note: in expansion of macro 'VADD'
  157 |         ch[i]   = VADD(cc[i+0], cc[i+ido+0]);
      |                   ^~~~
/usr/lib/gcc/i686-pc-linux-gnu/13.2/include/xmmintrin.h:202:1: error: inlining failed in call to 'always_inline' '_mm_mul_ps': target specific option mismatch
  202 | _mm_mul_ps (__m128 __A, __m128 __B)
      | ^~~~~~~~~~
../lib-src/pffft/pfsimd_macros.h:110:21: note: called from here
  110 | #  define VMUL(a,b) _mm_mul_ps(a,b)
      |                     ^~~~~~~~~~~~~~~
../lib-src/pffft/pffft.c:156:40: note: in expansion of macro 'VMUL'
  156 |         v4sf wr = LD_PS1(wa1[i]), wi = VMUL(LD_PS1(fsign), LD_PS1(wa1[i+1]));
      |                                        ^~~~
/usr/lib/gcc/i686-pc-linux-gnu/13.2/include/xmmintrin.h:898:1: error: inlining failed in call to 'always_inline' '_mm_set1_ps': target specific option mismatch
  898 | _mm_set1_ps (float __F)
      | ^~~~~~~~~~~
../lib-src/pffft/pfsimd_macros.h:110:21: note: called from here
  110 | #  define VMUL(a,b) _mm_mul_ps(a,b)
      |                     ^~~~~~~~~~~~~~~
../lib-src/pffft/pffft.c:156:40: note: in expansion of macro 'VMUL'
  156 |         v4sf wr = LD_PS1(wa1[i]), wi = VMUL(LD_PS1(fsign), LD_PS1(wa1[i+1]));
      |                                        ^~~~
/usr/lib/gcc/i686-pc-linux-gnu/13.2/include/xmmintrin.h:898:1: error: inlining failed in call to 'always_inline' '_mm_set1_ps': target specific option mismatch
  898 | _mm_set1_ps (float __F)
      | ^~~~~~~~~~~
../lib-src/pffft/pfsimd_macros.h:110:21: note: called from here
  110 | #  define VMUL(a,b) _mm_mul_ps(a,b)
      |                     ^~~~~~~~~~~~~~~
../lib-src/pffft/pffft.c:156:40: note: in expansion of macro 'VMUL'
  156 |         v4sf wr = LD_PS1(wa1[i]), wi = VMUL(LD_PS1(fsign), LD_PS1(wa1[i+1]));
      |                                        ^~~~
/usr/lib/gcc/i686-pc-linux-gnu/13.2/include/xmmintrin.h:898:1: error: inlining failed in call to 'always_inline' '_mm_set1_ps': target specific option mismatch
  898 | _mm_set1_ps (float __F)
      | ^~~~~~~~~~~
../lib-src/pffft/pfsimd_macros.h:114:21: note: called from here
  114 | #  define LD_PS1(p) _mm_set1_ps(p)
      |                     ^~~~~~~~~~~~~~
../lib-src/pffft/pffft.c:156:19: note: in expansion of macro 'LD_PS1'
  156 |         v4sf wr = LD_PS1(wa1[i]), wi = VMUL(LD_PS1(fsign), LD_PS1(wa1[i+1]));
      |                   ^~~~~~
/usr/lib/gcc/i686-pc-linux-gnu/13.2/include/xmmintrin.h:196:1: error: inlining failed in call to 'always_inline' '_mm_sub_ps': target specific option mismatch
  196 | _mm_sub_ps (__m128 __A, __m128 __B)
      | ^~~~~~~~~~
../lib-src/pffft/pfsimd_macros.h:113:21: note: called from here
  113 | #  define VSUB(a,b) _mm_sub_ps(a,b)
      |                     ^~~~~~~~~~~~~~~
../lib-src/pffft/pffft.c:155:20: note: in expansion of macro 'VSUB'
  155 |         v4sf ti2 = VSUB(cc[i+1], cc[i+ido+1]);
      |                    ^~~~
/usr/lib/gcc/i686-pc-linux-gnu/13.2/include/xmmintrin.h:196:1: error: inlining failed in call to 'always_inline' '_mm_sub_ps': target specific option mismatch
  196 | _mm_sub_ps (__m128 __A, __m128 __B)
      | ^~~~~~~~~~
../lib-src/pffft/pfsimd_macros.h:113:21: note: called from here
  113 | #  define VSUB(a,b) _mm_sub_ps(a,b)
../lib-src/pffft/pffft.c:154:20: note: in expansion of macro 'VSUB'
  154 |         v4sf tr2 = VSUB(cc[i+0], cc[i+ido+0]);
      |                    ^~~~

### Steps to reproduce

building on i686 for i686 with flags: -mtune=i686 -O2

### Expected behavior

to build

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Linux

**Comment by crsib** [comment]
Audacity requires SSE2 support to build on x86

**Comment by iFoundSilentHouse** [comment]
> SSE2

3.4.2 was built just fine

**Comment by iFoundSilentHouse** [comment]
Now it should be built with `-msse2` flag?

**Comment by iFoundSilentHouse** [comment]
Works with `export CFLAGS='-msse2'`
