### ISSUE TITLE
Audacity immediately crashes when using Filter Curve effect

### ISSUE THREAD

**Issue by craigstern** [audacity/audacity#6362]
### Bug description

I have a simple two-stereo-track project in Audacity 3.0.2 that's a little less than 10.5 seconds long. Each track has a volume envelope applied. When I apply a Filter Curve Effect to the top track, it works fine; but when I apply it to both tracks at once (or to the second track on its own), Audacity experiences a fatal error and crashes.
![Screenshot 2024-04-29 090956](https://github.com/audacity/audacity/assets/24302200/4cd5deaf-4378-43e1-8e4f-ee91201f4927)

### Steps to reproduce

Open the aup3 file; select either both tracks or the second track; select Effects > Filter Curve; apply the filter curve and watch the program immediately crash.

### Expected behavior

Audacity should apply the filter curve without crashing.

### Actual behavior

![Screenshot 2024-04-29 090956](https://github.com/audacity/audacity/assets/24302200/bf0403c3-7674-40e0-a686-d9f59723e160)

### Audacity Version

other

### Operating system

Windows

### Additional context

[log.txt](https://github.com/audacity/audacity/files/15150269/log.txt)
[log.txt](https://github.com/audacity/audacity/files/15150276/log.txt)
[log.txt](https://github.com/audacity/audacity/files/15150278/log.txt)

**Comment by craigstern** [comment]
Is there a way to attach an aup3 file to these? I think there's something specific to the files used that produces the crash.

**Comment by dozzzzer** [comment]
> Is there a way to attach an aup3 file to these?

Yes, you can compress your project file first and attach the .zip after

**Comment by craigstern** [comment]
[Crowd Booing.zip](https://github.com/audacity/audacity/files/15163751/Crowd.Booing.zip)

Here you go!

**Comment by dozzzzer** [comment]
No worries! Glad that it helped ;)
