### ISSUE TITLE
ffmpeg library not found, and user path not used

### ISSUE THREAD

**Issue by jor63** [audacity/audacity#6371]
### Bug description

Providing a user path to ffmpeg libraries seems to have no effect

### Steps to reproduce

1. Install audacity 3.5.1 (via homebrew)
2. Successfully open Audacity.app (after accepting the warning that this is not on the apple store...)
3. Go in Preferences : Libraries, and see "FFmpeg library not found"
4. Click on "Locate" button, and see the default path "/usr/local/Cellar/ffmpeg/2.5.2/lib" which indeed does not exist
5. Enter the correct path, e.g. /opt/homebrew/lib , and click OK

### Expected behavior

Audacity should identify the existing libraries

### Actual behavior

No change: still get "FFmpeg library not found"
Logs show that the provided path was recorded, but in fact not used in the search:

**10:50:12: User-specified path = '/opt/homebrew/lib/'**
10:50:12: Error: dlopen(libavformat.60.dylib, 0x0002): tried: 'libavformat.60.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibavformat.60.dylib' (no such file), '/usr/lib/libavformat.60.dylib' (no such file, not in dyld cache), 'libavformat.60.dylib' (no such file)
10:50:12: Error: dlopen(ffmpeg.60.64bit.dylib, 0x0002): tried: 'ffmpeg.60.64bit.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSffmpeg.60.64bit.dylib' (no such file), '/usr/lib/ffmpeg.60.64bit.dylib' (no such file, not in dyld cache), 'ffmpeg.60.64bit.dylib' (no such file)
10:50:12: Error: dlopen(libavformat.59.dylib, 0x0002): tried: 'libavformat.59.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibavformat.59.dylib' (no such file), '/usr/lib/libavformat.59.dylib' (no such file, not in dyld cache), 'libavformat.59.dylib' (no such file)
10:50:12: Error: dlopen(ffmpeg.59.64bit.dylib, 0x0002): tried: 'ffmpeg.59.64bit.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSffmpeg.59.64bit.dylib' (no such file), '/usr/lib/ffmpeg.59.64bit.dylib' (no such file, not in dyld cache), 'ffmpeg.59.64bit.dylib' (no such file)
10:50:12: Error: dlopen(libavformat.58.dylib, 0x0002): tried: 'libavformat.58.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibavformat.58.dylib' (no such file), '/usr/lib/libavformat.58.dylib' (no such file, not in dyld cache), 'libavformat.58.dylib' (no such file)
10:50:12: Error: dlopen(ffmpeg.58.64bit.dylib, 0x0002): tried: 'ffmpeg.58.64bit.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSffmpeg.58.64bit.dylib' (no such file), '/usr/lib/ffmpeg.58.64bit.dylib' (no such file, not in dyld cache), 'ffmpeg.58.64bit.dylib' (no such file)
10:50:12: Error: dlopen(libavformat.57.dylib, 0x0002): tried: 'libavformat.57.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibavformat.57.dylib' (no such file), '/usr/lib/libavformat.57.dylib' (no such file, not in dyld cache), 'libavformat.57.dylib' (no such file)
10:50:12: Error: dlopen(ffmpeg.57.64bit.dylib, 0x0002): tried: 'ffmpeg.57.64bit.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSffmpeg.57.64bit.dylib' (no such file), '/usr/lib/ffmpeg.57.64bit.dylib' (no such file, not in dyld cache), 'ffmpeg.57.64bit.dylib' (no such file)
10:50:12: Error: dlopen(libavformat.55.dylib, 0x0002): tried: 'libavformat.55.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibavformat.55.dylib' (no such file), '/usr/lib/libavformat.55.dylib' (no such file, not in dyld cache), 'libavformat.55.dylib' (no such file)
10:50:12: Error: dlopen(ffmpeg.55.64bit.dylib, 0x0002): tried: 'ffmpeg.55.64bit.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSffmpeg.55.64bit.dylib' (no such file), '/usr/lib/ffmpeg.55.64bit.dylib' (no such file, not in dyld cache), 'ffmpeg.55.64bit.dylib' (no such file)
**10:50:12: Error: User-specified path does not contain FFmpeg libraries.**

Furthermore, the provided path is NOT recorded, and trying again starts again from the default path "/usr/local/Cellar/ffmpeg/2.5.2/lib"

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS

**Comment by LWinterberg** [comment]
FFmpeg 2.5.2 is not supported by Audacity. Please get a different version. `brew install ffmpeg@6` should work.

**Comment by jor63** [comment]
Sorry, @LWinterberg but please read more carefully... 
I DO have ffmpeg@6 installed in the given directory (/opt/homebrew/lib). The problem is that this directory is NOT searched, or kept for the next search.

/usr/local/Cellar/ffmpeg/2.5.2/lib is the path hardcoded by defaut, which I don't have installed. 
I may add it does not seem to be searched either. Only /urs/lib (which is normal) and /System/Volumes/Preboot/Cryptexes/, which is more curious...
There definitely is a problem in the management of the library search path list...

From looking at a particular search try in the log:
  _'/System/Volumes/Preboot/Cryptexes/OSlibavformat.60.dylib' (no such file), '/usr/lib/libavformat.60.dylib' (no such file, not in dyld cache), 'libavformat.60.dylib' (no such file)_
I deduce that the path list is something like 
     /System/Volumes/Preboot/Cryptexes/OS:/usr/lib/:""
The first: should probably disappear in an non-development version?
The second /usr/lib is quite normal
The last "" (empty, or current directory) is dangerous: what is it in the end, when you don't launch from the command line?

**Comment by LWinterberg** [comment]
I have no idea why the homebrew install does that. Maybe @krehel knows

**Comment by jor63** [comment]
Hi, @LWinterberg. AFAIU this has nothing to do with homebrew (Casks just download the the binary from the audacity site). I did check that I have exactly the same issue with the downloaded version from https://github.com/audacity/audacity/releases/download/Audacity-3.5.1/audacity-macOS-3.5.1-universal.dmg

As I said, I believe this is a pb in the list management, maybe complicated by the sandbox policy of OSX? I don't know... but I didn't have that in the previous version, and I didn't change OS (Ventura 13.6.3) in the meantime...

**Comment by LWinterberg** [comment]
I believe this works in a regular Audacity install, at least it I've seen reports from other users that it does. @dozzzzer please check

> I did check that I have exactly the same issue with the downloaded version from...

Did you clear the audacity.cfg inbetween?


> I deduce that the path list is something like
/System/Volumes/Preboot/Cryptexes/OS:/usr/lib/:""

the search paths used are here: https://github.com/audacity/audacity/blob/f62eb1a02e74c528f27111e4380f6b1b0cad6ae4/modules/import-export/mod-ffmpeg/lib-ffmpeg-support/FFmpegFunctions.cpp#L330-L337
