### ISSUE TITLE
Support clipboard promise when importing through copy/paste

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#6376]
Follow-up on #6280

When copying a file from the Muse Hub, it may copy something that wasn't downloaded yet. The hub writes to the clipboard the place where the file will be once download is complete, but in the meantime the user might paste and there'll be nothing yet to be imported.

**Comment by DavidBailes** [comment]
@saintmatthieu . Are you referring to copying one of the sounds from the Muse Hub. If so, how do you copy it? Is it possible to do this using the keyboard?

**Comment by saintmatthieu** [comment]
Hi David,
I cannot say how the Muse Hub (or the newer version that'll soon be rolled out) can be keyboard-navigated, but this is Hub-specific. Do you have a concern?

**Comment by DavidBailes** [comment]
> Hi David, I cannot say how the Muse Hub (or the newer version that'll soon be rolled out) can be keyboard-navigated, but this is Hub-specific. Do you have a concern?

Using the current version of the Muse Hub, the only way that I know of importing one of the sounds into Audacity is using drag and drop. Users of screen readers can't drag and drop items between different windows, and I don't think there is the ability to copy a sound to the clipboard.

So in the description above which mentions copying a file from the muse hub, I thought that there may be a way of copying a file in Muse hub to the clipboard using the keyboard, which then could be pasted into Audacity using the new functionality that you have provided. This would allow a way that users of screen readers could use to get sounds from the hub into Audacity, which I don't think is currently possible.

**Comment by saintmatthieu** [comment]
Using ctrl-c to copy a file from the Muse Hub is going to be part of their upcoming roll-out. From what I read it is indeed meant as an accessibility improvement.

**Comment by DavidBailes** [comment]
> Using ctrl-c to copy a file from the Muse Hub is going to be part of their upcoming roll-out. From what I read it is indeed meant as an accessibility improvement.

Thanks - that's good news.

**Comment by dozzzzer** [comment]
Reopened: the dialog's title should be changed from "Audacity" to "Importing..." @grliszas14 @LWinterberg 

<img width="441" alt="image" src="https://github.com/audacity/audacity/assets/70063970/d5f68e84-65c0-412f-871c-5534091621a2">

**Comment by chinakov** [comment]
I am putting this to Ready to Merge, as I am still unable to rectify one issue that I assume is only on my side. The issue is only connected to files that are not available locally, but available in iCloud.
