### ISSUE TITLE
[Bug] The text in the drop-down menu is mostly obscured on KDE

### ISSUE THREAD

**Issue by WhiredPlanck** [audacity/audacity#638]
**Describe the bug**
The text of the drop-down menu used to select the device will be mostly obscured on KDE.

**To Reproduce**
Just open the application.

**Expected behavior**

The text of the drop-down menu should be clearly shown.

**Screenshots**

![Screenshot.png](https://i.loli.net/2020/08/04/tyOkfXW4aGB6RrF.png)

**Additional information:**
 - OS: Arch Linux, KDE Plasma 5.19.4
 - Version 2.4.1, distribution package.

**Additional context**
DPI: 120
Global Zoom: 100%

**Comment by SteveDaulton** [comment]
Has Audacity been built with GTK2 or GTK3?

**Comment by whriedplanck** [comment]
> Has Audacity been built with GTK2 or GTK3?

It has been built with GTK3.

**Comment by whriedplanck** [comment]
I switched to MATE desktop environment, and found that it‘s a bit more normal than on KDE. Look like this:

![图片.png](https://i.loli.net/2020/08/05/FeyIaSMuwZ45UVz.png)

But just two fields, the text in the fields marked with red is totally invisible.

**Comment by SteveDaulton** [comment]
Audacity should "mostly" work with either GTK2 or GTK3 but there are some issues (such as this) with GTK3 that still need to be resolved.

**Comment by whriedplanck** [comment]
> Audacity should "mostly" work with either GTK2 or GTK3 but there are some issues (such as this) with GTK3 that still need to be resolved.

Oh, that sounds not good.....
