### ISSUE TITLE
When selecting over waveform, the peak part of the waveform is coloured wrongly

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#6394]
### Steps to reproduce

1. Have some audio
2. Make a selection on a clip
3. Change the color of the track to anything but the default one

### Expected behavior

<img width="450" alt="image" src="https://github.com/audacity/audacity/assets/70063970/0109200a-d9ba-402b-87bf-0b1736f49b8a">

### Actual behavior

<img width="450" alt="image" src="https://github.com/audacity/audacity/assets/70063970/277c25e6-3362-43bf-b7ee-9cb5fe5ba46c">

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

### Additional context

Bisects to https://github.com/audacity/audacity/commit/3de5915b00e22aa5b6f5d7cbafd91c9493cd10cb

**Comment by petersampsonaudacity** [comment]
Testing on W11 shows this is a regression on 3.5.1

**Comment by chinakov** [comment]
This is fixed, thanks!
