### ISSUE TITLE
Organizing label track content strictly based on time order

### ISSUE THREAD

**Issue by The3IC** [audacity/audacity#6397]
### Your idea

Setting for label track to force an alternate way of displaying labels. In this alternative way, labels should be shown in strict chronological order + vertical scroll bar to enable scrolling. So showing all labels (perhaps even left aligned with some small tick mark to identify placement) stacked in time order. In order to reach labels not fitting into the track space, a scroll bar on the right would be needed.

### Problem to be solved

This is mainly an issue because the nice new support for generating transcripts as labels by the Openvino project. There is a small usability issue in the the label track seems to try to optimize label placement to fill the track so "later" labels can appear in any free spot in the track window, not necessarily adjacent to next/previous. This makes reading/checking/editing the transcript unnecessarily hard as the next/previous text can be "anywhere" and next/previous context is quite relevant for editing. 

Zooming in on the audio track helps to some degree, the main usability issue is that with a center-wheel mouse, the wheel typically controls a vertical scroll bar so this is an easier way to scroll through the content rather than zoom+horizontal scroll bar in audio window.  Also the zoom scroll bar context (audio) is different from the edit context (label) so needs some additional mouse movement.

### Prior art

?

### Additional context

Could be implemented as a setting in the track menu.

**Comment by LWinterberg** [comment]
Use the label editor for this (edit > labels > label editor). Or export the labels as a subtitle file so you can view the subtitles alongside the video itself.
