### ISSUE TITLE
Crash when move parts audio to another track

### ISSUE THREAD

**Issue by microcoder** [audacity/audacity#6398]
### Bug description

Crash when move parts audio to another track on last build from git master branch

### Steps to reproduce

1. Open editor and import an audio 
2. Split the audio track in any place 
3. Create new track from menu Tracks -> Add New -> Stereo Track
4. Mouse move any part of splitted audio from track 1 to track 2
5. Crash

### Expected behavior

*

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

[Audacity_dbgrpt-151841-20240507T163134.zip](https://github.com/audacity/audacity/files/15236332/Audacity_dbgrpt-151841-20240507T163134.zip)

**Comment by petersampsonaudacity** [comment]
Testing on W11 with 3.5.1 and latest master alpha test build for 3.6.0

I cannot reproduce this on Windows, the audio clips move to track 2 correctly and there is no crash.

**Comment by microcoder** [comment]
> I cannot reproduce this on Windows

My Operating system - Manjaro Linux

**Comment by microcoder** [comment]
https://github.com/audacity/audacity/assets/2853555/8776f37c-65e2-45df-948f-ffb607aa41b8

**Comment by dozzzzer** [comment]
I didn't manage to reproduce this on Ubuntu 22.04 as well as Fedora 39

**Comment by j4nn3r** [comment]
Sim sim, encontrei o semelhante erro ao abrir mais de cinco arquivos e tentar colocar-los em uma só pista, ele simplesmente trava e desliga, usando aqui **Ubuntu 24.04 LTS instalado via flatpak,** se houver alguma solução, por gentileza postem aqui. Grato.

**Comment by dozzzzer** [comment]
@j4nn3r feel free to provide your project that exhibits such behavior. Otherwise, there's not much we can do in order to help you with that issue.

**Comment by CoffeeTheProto** [comment]
Just ran into this same issue, imported wav audio, split the clip into two parts and moved one to a new track, causes audacity to hang and crash. Running Windows 10, just updated to latest (3.6.1). I thought it was an issue with the clip being too long, but I tried splitting it into smaller segments with no results.

**Comment by dozzzzer** [comment]
@CoffeeTheProto is your WAV file mono or stereo? What sample rate/bit depth does it have?

**Comment by CoffeeTheProto** [comment]
Stereo, and it looks like the sample rate was 48khz and the bit depth was apparently 32? I'll try changing it to 24 but it's very slow.

**Comment by dozzzzer** [comment]
Could not reproduce it with either 32-bit float or PCM on Windows 10/Audacity 3.6.1:

https://github.com/user-attachments/assets/b3d27ce4-d41f-4e33-883e-52f2c14bab72

@CoffeeTheProto
