### ISSUE TITLE
export to raw is wrong

### ISSUE THREAD

**Issue by iddq** [audacity/audacity#640]
reproduce:

record
split stereo to mono
delete track 2
tracks/resample to 8000Hz
export as uncompressed raw, signed 16 bit
file/new/import/raw: signed 16 bit, little endian (?), 1 channel mono, sample rate 8000Hz

I think the exported file's sample rate is 44100 instead of 8000.

**Comment by SteveDaulton** [comment]
Use the "Project Rate" (lower left corner of the main Audacity window) to set the sample rate of exported files.
See also: https://manual.audacityteam.org/man/selection_toolbar.html#rate

If you require more help, please ask on the Audacity help forum: https://forum.audacityteam.org

**Comment by iddq** [comment]
thank you
