### ISSUE TITLE
3.5.1: local help pages are not visible via the menu

### ISSUE THREAD

**Issue by Ponce** [audacity/audacity#6402]
### Bug description

Slackware64 15.0 (latest stable)

building audacity 3.5.1 from the bash script I maintain on SlackBuilds.org

https://slackbuilds.org/repository/15.0/audio/audacity/

and including the manual in the resulting package: for 3.5.1 the script should be amended with the following commit

https://git.slackbuilds.org/slackbuilds/commit/?id=27a3c98

the help pages are present in what has been, at least until 3.4.2 (if I recall correctly), the correct path
```
$ ls -la /usr/share/audacity/help/manual/
total 104
drwxr-xr-x 4 root root  4096 apr 24 17:39 .
drwxr-xr-x 3 root root  4096 apr 24 17:39 ..
-rw-r--r-- 1 root root 15086 apr 24 17:39 favicon.ico
-rw-r--r-- 1 root root 37399 apr 24 17:39 index.html
drwxr-xr-x 5 root root  4096 apr 24 17:39 m
drwxr-xr-x 3 root root 24576 apr 24 17:39 man
-rw-r--r-- 1 root root 10820 apr 24 17:39 quick_help.html
```
and (probably) detected also by audacity itself when running "help" -> "diagnostics" -> "show log"
```
09:48:42: Help button pressed: PageName Main_Page, releasePageName index.html
09:48:42: webHelpPage https://manual.audacityteam.org/index.html, localHelpPage /usr/share/audacity/help/manual/index.html
```
but they are not visible via the menu entries.
### Steps to reproduce

- install Slackware64-15.0
- install audacity and its dependencies from SlackBuilds.org
- launch audacity
- try to access the help html pages via the welcome page or the "help" -> "manual" or the "help" -> "quick help" menu entries

### Expected behavior

the local help pages open in the default browser of the session

### Actual behavior

I get redirected via the default browser of the session to the online help pages at https://manual.audacityteam.org/index.html

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Linux

### Additional context

obviously, if I manually open the help pages pointing the browser at them I am able to read them just fine.

FWIW this worked ok in the past.

**Comment by LWinterberg** [comment]
The offline manual was removed in Audacity 3.2, though the removal may not have been thorough enough until recently.
