### ISSUE TITLE
Missing header in WaveClip.cpp

### ISSUE THREAD

**Issue by mohd-akram** [audacity/audacity#6414]
### Bug description

I'm getting a build error on macOS 10.14 due to a missing `<cmath>` header in WaveClip.cpp.

### Steps to reproduce

1. Build the program

### Expected behavior

Builds successfully

### Actual behavior

```
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_audio_audacity/audacity/work/audacity-sources-3.5.1/libraries/lib-wave-track/WaveClip.cpp:1325:11: error: no member named 'round' in namespace 'std'; did you mean 'roundl'?
   return std::round(t * mRate) / mRate;
          ^~~~~~~~~~
          roundl
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/math.h:477:20: note: 'roundl' declared here
extern long double roundl(long double);
                   ^
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_audio_audacity/audacity/work/audacity-sources-3.5.1/libraries/lib-wave-track/WaveClip.cpp:1372:16: error: no member named 'floor' in namespace 'std'
   return std::floor(GetPlayDuration() * mRate + 0.5) < 2.0;
          ~~~~~^
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_audio_audacity/audacity/work/audacity-sources-3.5.1/libraries/lib-wave-track/WaveClip.cpp:1436:12: error: no member named 'ceil' in namespace 'std'
      std::ceil(quarters * secondsPerQuarter * GetRate()) / GetRate();
      ~~~~~^
```

### Audacity Version

other

### Operating system

macOS

### Additional context

[Full log](https://build.macports.org/builders/ports-10.14_x86_64-builder/builds/208918/steps/install-port/logs/stdio)

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
