### ISSUE TITLE
Malformed waveform display

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#6418]
### Bug description

On zooming in on the waveform it can be seen that the displayed waveform is damaged.

### Steps to reproduce

1. Generate a default 30 second chirp
2. Zoom in slowly ("Ctrl + Mouse Wheel")

### Expected behavior

Audacity 3.3.3

https://youtu.be/PMwsvME1pvU

### Actual behavior

Audacity 3.6.0

https://youtu.be/moZ82OAz9ro

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

Tested with Audacity 3.6.0 Commit ID: a55100
Expected behaviour demonstrated with Audacity 3.3.3 on same computer.

**Comment by petersampsonaudacity** [comment]
I confirm this behavior on W11 with 3.6.0 versus 3.5.1

**Comment by LWinterberg** [comment]
Duplicate of https://github.com/audacity/audacity/issues/6383 (and fixed now)
