### ISSUE TITLE
"Silence Audio" command silently fails

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#6421]
### Bug description

"Edit menu > Remove Special > Silence Audio (Ctrl + L)"  does nothing.

### Steps to reproduce

1. Generate a Chirp
2. Select part of the audio
3. Either "Ctrl + L" or "Edit menu > Remove Special > Silence Audio"

### Expected behavior

The selected audio to be silenced.

### Actual behavior

Nothing happens.

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

**Comment by petersampsonaudacity** [comment]
Something really odd is happening here, extendinf Steve's STRs

1. Generate a 30 second Chirp
2. Select part of the audio from 5-10 seconds
3. Either "Ctrl + L" or "Edit menu > Remove Special > Silence Audio"
4. Observe: the waveform remains unaltered - no apparent silencing
5. select from 15-20 seconds
6. Trim audio with button in the Edit toolbar or "Edit menu > Remove Special > Trim Audio" or Ctrl+T
7. Ctrl+Z to undo the Trim
8. Onserve the waveform from 5-10 secs bow shows as silence

"Edit menu > Remove Special > Silence Audio"

**Comment by petersampsonaudacity** [comment]
See also:
 **Waveform not updated correctly on pasting into a clip. #6422** 

which exhibits similar waveform display issues.

**Comment by dozzzzer** [comment]
No longer reproducible indeed
