### ISSUE TITLE
Incorrect font scaling in track's control panel

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#6427]
### Bug description

The text in the the control block on the left end of the track is scaled incorrectly.

### Steps to reproduce

1. Add an audio track.

### Expected behavior

![good](https://github.com/audacity/audacity/assets/11681097/d78b618e-734d-44f5-8771-6870b2054334)

Audacity  3.3.3

### Actual behavior

![font-scaling](https://github.com/audacity/audacity/assets/11681097/cf295ea5-c1b1-4191-9df4-2bb862bad63d)

Audacity 3.6.0 alpha Commit Id: a55100 

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

Both screenshots taken with Audacity running on the same system.

**Comment by petersampsonaudacity** [comment]
I cannot reproduce this on W11 with 3.5.1 or latest master alpha build for 3.6.0

![image](https://github.com/audacity/audacity/assets/50205984/d8162e5f-5528-4778-956c-cf0f8fe20b4f)

**Comment by SteveDaulton** [comment]
I suspect that this may be a Linux only issue, or perhaps  an XFCE only issue, but  as can be seen from the screenshots, the problem was not present in 3.3.3.

**Comment by LWinterberg** [comment]
This is due to the font scaling you have enabled to make Audacity usable on your HiDPI display, Steve. It also makes the "Snap" checkbox and clip header larger than it should be, and it doesn't seem to enlarge the scale everywhere evenly, because your ruler marks are smaller than they should be

**Comment by DavidBailes** [comment]
I've reopened the issue, because with the Windows display scaling set to 125%, the track panel looks awful.
