### ISSUE TITLE
Redundant "Enable" in View menu

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#6434]
### Bug description
@LWinterberg 

Hi Leo, here is another candidadte for your "cleanup" #5710 

In the View menu the "Enable" in the "Enable Extra Menus" is really redundant and could be removed - the enabling is already indicated by the "View" top level menu item.

### Steps to reproduce
1. launch Audaity
2. Select **View** menu
3. Observe: **Enable Extra Menus**

### Expected behavior
![image](https://github.com/audacity/audacity/assets/50205984/f716f5fd-5a48-4186-a399-796a29b4f4f5)

### Actual behavior
![image](https://github.com/audacity/audacity/assets/50205984/58addc6a-4ccf-4182-9ad8-c3810093a972)

### Audacity Version
3.5.1 and 3.6.0 alpha

### Operating system
Windows 11 - but assume all OS

### Additional context
This would just be consistent, you don't have:
a) View > Enable Toolbars
b) View > Enable Timeline

**Comment by petersampsonaudacity** [comment]
Testing on W11 with @nalin243 's test branch build for this:  audacity-win-3.6.2-alpha-20240804+b7808bc-x64

This looks good to go to me.

![image](https://github.com/user-attachments/assets/ea618604-c68d-4acf-bc9f-38f9a72358e9)

**Comment by chinakov** [comment]
Tested, thanks!
