### ISSUE TITLE
Audacity fails to find modules when installed in a directory with a dollar sign in its path

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#6448]
### Steps to reproduce

1. install Audacity to a non-default path containing a dollar sign (e.g. `D:\$Root\$Apps\Audacity\3.5.1\Audacity.exe`)
2. run Audacity
3. check Preferences > Modules

### Expected behavior

All modules show up

### Actual behavior

No modules are discovered by Audacity

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by chinakov** [comment]
Just tested, the issue is still present. I have tried to delete Audacity.cfg and create a Portable Settings folder, to no avail to rectify the issue. Bringing back to In Progress.

**Comment by dozzzzer** [comment]
Tested
