### ISSUE TITLE
Play at Speed dialog goes under the bottom edge of the Audacity window

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#6449]
1. Double-click the Play-at-Speed slider

Actual result:

![image](https://github.com/audacity/audacity/assets/70063970/cb1c8062-b004-4fe6-85e1-c4b174718433)

Expected result:

![image](https://github.com/audacity/audacity/assets/70063970/bd464220-5d4b-471d-a1dd-f2c0b14b20e7)

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @Kurtsley 's branch build: audacity-win-3.7.0-alpha-20240920+74967ad-x64

The Play-at-Speed dialog no longer obtrudes below the Audacity window which _strictly_ addresses the issue logged by @dozzzzer in the title of this issue  - and this is true for full screen Audacity window and reduced size Audacity window,

However it does obtrude beyond the right of the Audacity window which causes the dialog to be cropped on the right if the reduced size widow is close to the right of the screen.  
![image](https://github.com/user-attachments/assets/72df5886-4171-48e1-a625-cb528ce2778f)

Or in full screen mode if the user moves many toolbars from the upper tooldock to the lower tooldock
![image](https://github.com/user-attachments/assets/b94dbcfc-4d66-4211-b8ed-26680cabcc1c)
