### ISSUE TITLE
Master effects: capitalize "effects" in the name

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#6477]
<img width="369" alt="image" src="https://github.com/audacity/audacity/assets/70063970/d2ffddc6-647e-431e-81fd-00fd9a5806c2">

**Comment by petersampsonaudacity** [comment]
Perhaps also in these places too:

![image](https://github.com/audacity/audacity/assets/50205984/17f6dcb3-b1da-4814-b4b0-84520ebf68ae)

**Comment by LWinterberg** [comment]
I'd say no - title case for a title makes some sense, title case for sentences and buttons isn't necessary.
