### ISSUE TITLE
Freeze when attempting to play from non-zero starting position

### ISSUE THREAD

**Issue by Sainan** [audacity/audacity#6495]
### Steps to reproduce

1. Load any audio file
2. Move the cursor to a non-zero position in the track
3. Attempt to playback

### Expected behavior

The track would play from the selected position.

### Actual behavior

Audacity becomes unresponsive.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by petersampsonaudacity** [comment]
Testing on W10 with 3.5.1 current release and the latest master alpha build for the upcoming 3.6.0

I cannot reproduce this, works fine for me.

**Comment by Sainan** [comment]
tbf, I was on an older version when it was happening to me constantly, but it did happen again after I have upgraded Audacity. Now I have also done some processing and exporting with it, and it doesn't seem to happen anymore, so maybe it just needed to warm up a little.

**Comment by Sainan** [comment]
Just happened to me again. Might actually be somehow intertwined with #6496. Can you reproduce it when you reset your graphics driver via Win+Ctrl+Shift+B?

**Comment by dozzzzer** [comment]
> Can you reproduce it when you reset your graphics driver via Win+Ctrl+Shift+B?

I've tried but couldn't reproduce it either.
