### ISSUE TITLE
Freeze when pressing Escape on "About Audacity" dialog

### ISSUE THREAD

**Issue by Sainan** [audacity/audacity#6496]
### Steps to reproduce

1. Select Help > About Audacity
2. Press Escape

### Expected behavior

The dialog should close.

### Actual behavior

The program freezes.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by Sainan** [comment]
Actually, it seems this is just about any dialog in this program... god this shit is so bad.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with 3.5.1 current release and the latest master alpha build for the upcoming 3.6.0

I cannot reproduce this, works fine for me.

**Comment by Sainan** [comment]
Great, now I also can't reproduce it anymore after waking up again. I must be going insane. My best guess is that one of the programs I had open yesterday maybe caused a window message or something to be swallowed or delayed. But it's not like other software on my system ever exhibits the kind of freezing I see with Audacity.

**Comment by Sainan** [comment]
And now it happens to me again. Is there any log or something I could provide that would be useful?

**Comment by dozzzzer** [comment]
You can try Help > Diagnostics > Show Log

**Comment by Sainan** [comment]
No messages seem to be added when opening the About dialog or pressing Escape to it. However, these messages are in there when starting the program:
```
12:48:56: Audacity 3.5.1
12:48:56: Error: Failed to load shared library 'avformat-60.dll' (error 126: The specified module could not be found.)
12:48:56: FFmpeg libraries loaded successfully from: C:\Program Files\FFmpeg For Audacity\avformat-59.dll
12:48:57: Error: Failed to load shared library 'avformat-60.dll' (error 126: The specified module could not be found.)
12:48:57: FFmpeg libraries loaded successfully from: C:\Program Files\FFmpeg For Audacity\avformat-59.dll
```

**Comment by Sainan** [comment]
I've just opened Audacity again (been a hot minute since I last opened it) and it's back to freezing on every single interaction, like pressing spacebar on an update being available. Seriously, does this app need some sort of 5 minute warmup before it stops constantly freezing? What is this shit? I've never seen this with anything else.

**Comment by Sainan** [comment]
Another pretty consistent freeze for me is apparently using Ctrl+Scroll with a track. It seems to be frozen forever until I focus another window and press the key again (so either ctrl or escape). The key is seemingly stuck until then, and Audacity does not register it regardless.
