### ISSUE TITLE
Limiter graph: adding look-ahead delays the graph

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#6505]
### Steps to reproduce

1. Create a track with some audio
2. Add real-time limiter (or compressor)
3. Open limiter editor
4. Enable "Show graph" option
5. Set lookahead to maximum
6. Press play

### Expected behavior

Graph is synchronized with playback

### Actual behavior

Graph is noticeably delayed, likely by the amount of look-ahead specified.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

**Comment by dozzzzer** [comment]
Tested
