### ISSUE TITLE
Play head ghosting on playback and mouseover (while using OS integer scaling)

### ISSUE THREAD

**Issue by leogott** [audacity/audacity#6506]
### Bug description

A visual bug where ghosting occurs with the play head / cursor over the audio track, (only) when Gnome integer scaling is set to 200%

### Steps to reproduce

1. have a track with audio
2. move the mouse along the timeline or press play

### Expected behavior

the play head / cursor is only where the playback occurs / mouse pointer is respectively.

### Actual behavior

Windows XP vibes (see screen recording below)

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

### Additional context

Audacity installed via Flathub (3.5.1 x86_64)
Pop!_OS 22.04 LTS 64-bit
Gnome 42.9
X11

3840x2160 (16:9) screen (200% scaling, HiDPI daemon)
AMD® Radeon graphics / AMD® Radeon rx 580 series

![Audacity 2024-05-27 13-55](https://github.com/audacity/audacity/assets/61663141/875b7514-cd0a-4b9a-a438-2849f5395631)

**Comment by mrjpaxton** [comment]
I am also having the same problem on the Framework 13 laptop (AMD edition). I have version 3.2.4 installed from the Debian 12 repos.

**Comment by mrjpaxton** [comment]
I want to point out that Tenacity (from Flathub) does not seem to have this problem, at least for me.

For HiDPI, it can be run like this:

```
GDK_SCALE=2 GDK_DPI_SCALE=0.5 flatpak run org.tenacityaudio.Tenacity
```

**Comment by leogott** [comment]
Problem persists on audacity 3.7.0 . And as @mrjpaxton pointed out, is not present on tenacity, so it's probably a recent regression or a visual element not present on their default theme?

An interesting observation: The problem appears less when the project grows in size.

**Comment by LWinterberg** [comment]
I don't believe this can happen in Audacity 4 anymore.
