### ISSUE TITLE
Windows: Disabling audio device within OS lets Audacity run into "Send Feedback" dialog

### ISSUE THREAD

**Issue by bjoernmartin** [audacity/audacity#6518]
### Bug description

Audacity was using another playback device (built-in notebook audio instead of Bluetooth headset). So I disabled the built-in notebook audio. Instead of switching to the only available device left, Audacity "detected" an error and asked me to send a problem report (which I did). However, I think this should rather be detected / anticipated and dealt with, e.g. by selecting the next available device, showing a selection dialog or similar.

### Steps to reproduce

- Have at least two audio playback devices active on Windows (let's say A and B)
- Start Audacity and configure it to use A for playback
- Go to Windows Sound settings and disable A (Windows 11: "Don't allow" for usage)
- Go back to Audacity and try to playback audio

### Expected behavior

Audacity switches to B or offers to switch to B.

### Actual behavior

Audacity detects a problem it cannot deal with and asks for debug information to be sent to the developers. No comment can be added, hence the situation cannot be explained.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

Sound cards: 
- Realtek Audio (built-in device for the Lenovo Z16 Gen 2 notebook)
- Anker SoundCore Life Q30 Bluetooth headset (used in headphone mode)

OS details: Windows 11, Version 10.0.22631.3593
Audacity details: Version 3.5.1

**Comment by LWinterberg** [comment]
Audacity currently does not scan for device change. You need to hit Audio Setup -> Rescan audio devices first. The feature request to handle this automatically is #2409
