### ISSUE TITLE
Real-time effect latency handling incorrect during loops

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#6519]
### Bug description

The playback of a track with an effect with latency isn't handled properly, leading to the track being out of sync with the rest of the project.

### Steps to reproduce

1. Generate a pluck
2. Add a realtime compressor instance to the track, with relatively large lookahead (200ms+)
3. On another track, generate another pluck with different pitch
4. Enable looping
5. Press play

### Expected behavior

The two plucks are synchronized

### Actual behavior

After the first

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

### Additional context

After I experienced the issue, I looked into the code, and suspected
```cpp
            const auto toConsume = std::min(
               frames,
               mProcessingBuffers[iBuffer].capacity() - mProcessingBuffers[iBuffer].size()
            );
            //assert(toConsume == frames); //Sufficient size should have been reserved in AllocateBuffers
            produced = std::min(produced, toConsume);
```
to be responsible. So I did the experiment of increasing the capacity of `mProcessingBuffers[iBuffer]` so that a 1-second latency doesn't lead to `toConsume < produced`:
![image](https://github.com/audacity/audacity/assets/22740106/60126788-c12a-4595-a670-e63eff346f92)
The behaviour is then indeed as expected. But this isn't a proper fix.

Note that changing lookahead during playback brings the tracks out of sync as well, which is a bug, but a less severe one, as one can pause playback and resume to fix this. There is an issue for this: https://github.com/audacity/audacity/issues/3223

**Comment by Paul-Licameli** [comment]
Please, do not even attempt this.

**Comment by Paul-Licameli** [comment]
This will be a beast to fix.

Adding even more complexity:  the bounds of a loop might also be changed during playback, and desynchronization should not happen for that either.

My draft pull request has already consumed a lot of effort.

**Comment by vsverchinsky** [comment]
@Paul-Licameli me and @saintmatthieu discussed consequenses of the non-allocating policy and compared them to one allowing allocation, and decided that possible sound glitches on latency *change* is a lesser harm compared to playback synchronization issues, considering that the minimum latency value which was emperically discovered was around 100ms. If a large delay was set before playback then there will be only one reallocation at the very beginning of playback.
This is not considered to be a proper fix, but rather a hot-fix in time of transition.

**Comment by Paul-Licameli** [comment]
Make the hot fix, but I say, don’t try to develop the complete correct fix.  It would duplicate my recent efforts.

**Comment by Paul-Licameli** [comment]
Also #3223 requires other fixes I have not yet written.  It is not the same issue.

**Comment by dozzzzer** [comment]
Tested
