### ISSUE TITLE
Timecode

### ISSUE THREAD

**Issue by ianalarina** [audacity/audacity#6524]
Implement the 00h00m00s display with all its variants

- Visuals
- Update timecode format
- Manual timecode text entry
- Timecode / Playback cursor relationship

Designs: https://www.figma.com/design/i2A4pyP2E6VE2JiBFRIysK/Toolbars?node-id=1482-11118

**Comment by DavidBailes** [comment]
For moving between the digits using the keyboard, as well as being able to use left/right arrow, it's also very useful to be able to use Home/End to move to the first/last digit

**Comment by DilsonsPickles** [comment]
@DavidBailes - Arrow keys are included in spec but **Home/End** is a nice addition, thank you!
