### ISSUE TITLE
Toolbar: Shortcuts

### ISSUE THREAD

**Issue by ianalarina** [audacity/audacity#6529]
Various shortcuts to access functionality from the toolbar(tools, views, modes)

Designs: https://www.figma.com/design/i2A4pyP2E6VE2JiBFRIysK/Toolbars?node-id=1482-11223

**Comment by Eism** [comment]
Enabled shortcuts in https://github.com/audacity/audacity/pull/6881 and it works in general, all special cases should be resolved by separate issues
