### ISSUE TITLE
Docking

### ISSUE THREAD

**Issue by ianalarina** [audacity/audacity#6530]
Docking behavior of the toolbar (top and bottom)

Designs: 
- https://www.figma.com/design/i2A4pyP2E6VE2JiBFRIysK/Toolbars?node-id=1482-11254
- https://www.figma.com/design/i2A4pyP2E6VE2JiBFRIysK/Toolbars?node-id=1482-11254

**Comment by Eism** [comment]
Docking works in general, all special cases should be resolved by separate issues
