### ISSUE TITLE
Youlean Loudness Meter 2 causes Audacity to rescale the interface.

### ISSUE THREAD

**Issue by neutralvibes** [audacity/audacity#6535]
### Bug description

Adding Youlean Loudness Meter 2 free version (YLM2) to realtime effects causes Audacity to rescale the interface text and controls, making everything smaller. Seems to happen every time for me. 

Everything displays correctly until simply adding YLM2. Both the `VST` and `VST 3` versions cause the same issue. Only restarting Audacity seems to set things back to normal.

Removing the effect does not cause the interface items to return to their normal size. 

## Info
* Audacity 3.5.1 64bit 
* OS Windows 10 64bit
* Display resolution is 3200x1800 (recommended).
* Size of text apps and other items, 250% (recommended)
* Single display connected

### Steps to reproduce

Add Youlean Loudness Meter 2 to an existing track.

### Expected behavior

The effects appears without the Audacity interface being affected, with the only exception being if it is by design.

### Actual behavior

The Audacity interface gets scaled down.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

As shown below, the font size changes and everything gets much smaller, while the YLM2 meter seems fine.

![Screenshot Youlean](https://github.com/audacity/audacity/assets/26578830/8d3e39b9-4d3b-4b77-aa26-860ff35ac05c)

**Comment by neutralvibes** [comment]
> Are you sure that the issue with Audacity UI is connected with YLM? I have tried to reproduce, but to no avail.
Absolutely sure. I have other plugins I use with realtime effects without issue. Only YLM2 does this for me. It does it without even showing its own interface. Just adding it as an effect triggers the resizing response.

What I haven't done is reboot my machine. I will do this and see what happens.

**Comment by neutralvibes** [comment]
Rebooting didn't change the situation, but at least that has been done now.

'Below is what happens. Notice as soon as I selected the plugin the window size changes.

![audacityerror](https://github.com/audacity/audacity/assets/26578830/5d37a1a0-6b84-47a9-845a-372722a26778)

**Comment by dozzzzer** [comment]
Could not reproduce. Windows 11/Audacity 3.6.1

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/37782bc9-a22a-4e14-8eee-4212a66118b6">
