### ISSUE TITLE
New Compressor and Limiter RT graph can become blank after using Pause

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#6589]
### Bug description
Testing on W10 with the new Compressor and Limiter in the alpha test builds for 3.6.0

In the realtime graphs in both of these new/replacement effects if you press Pause to temporarily stop playback the graph continues scrolling but becomes blank from when the pause started.

a) If you press Pause  to restart playback while at least some of the graph is shown in the window then the graph will continue. However ...

b) If you press Pause again when all the active graph has scrolled off the screen with a totally blank graph - then the graphing display does not restart even though playback is active.  Nor does the graph restart if you change any of the realtime parameters.

### Steps to reproduce
1. get some audio
2. add Compressor (or Limiter) to the RT effects stack
3. Click on it in the RT stack to open the dialog
4. check on the Show graph
5. Press play
6. Observe the compression graph
7. Press pause
8. Observe: graph continues scrolling but blank beyond pause point
9. While some graph still shows press Pause to restart playback
10. Observe: graph continues where it left off (no gap)
11. Press Pause 
12. wait till all the graph scrolls of screen - leaving the graph blank
13. Press pause to restart the audio playback
14. Observe: graph does _**NOT**_ restart

### Expected behavior
Graph should always show when playback is arrive

### Actual behavior
Graph does not always show when playback is active

### Audacity Version
current master / alpha / nightly build

### Operating system
Windows 10

### Additional context
None

**Comment by dozzzzer** [comment]
Tested. A new related ticket has been created: https://github.com/audacity/audacity/issues/6675
