### ISSUE TITLE
Intuitive way to zoom the Y axis on tracks.

### ISSUE THREAD

**Issue by rin67630** [audacity/audacity#661]
The concept of zooming the y axis of a track is not very intuitive. 
It took me quite a long time to understand that's zooming occurs related to the mouse position. That concept is rather unusual and IMHO really confusing.
I always wanted to be able to shift the Y scale upon dragging the mouse and would have expected to zoom with the mouse wheel.
Wouldn't that be the intuitive way to get the thing done?
Thank you for considering.

**Comment by LWinterberg** [comment]
IMHO: 

* right-click > Zoom in/zoom out should become symmetric (always zooming from the center)
* Asymmetric zooming should only be available with View > Zoom > Advanced vertical zooming active.
* "scroll over vertical scale to move up/down" should become a thing in advanced mode.

I'd also generally support "ctrl+scroll over the vertical scale to zoom in/out symmetrically" becoming a thing even when not in advanced mode.

**Comment by LWinterberg** [comment]
vertical zooming now zooms around the center line
