### ISSUE TITLE
Add campaign info to audio.com requests

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#6618]
Add information to those requests so that we know where they originate from in the Audacity UI.

**Comment by saintmatthieu** [comment]
Interactions identified so far with the audio.com front-end, and provisional "buttonName" tags.

# 1
![image](https://github.com/audacity/audacity/assets/22740106/e6f6f33d-e821-46ac-9d6b-622ea5550958)
`Project_limit_reached_dialog_after_save-to-cloud_attempt`

# 2
![image](https://github.com/audacity/audacity/assets/22740106/2848dec4-20e9-45ad-8435-06691edc8e68)
`Save_Project-Save_to_Cloud`

# 3
![image](https://github.com/audacity/audacity/assets/22740106/b209d96e-19da-454d-8503-eb3ce69c180f)
`Save_Project-Save_to_Cloud`
(Currently not differentiated from **2**, todo)

# 4
![image](https://github.com/audacity/audacity/assets/22740106/34fc1eb5-36af-46d1-85bf-ea8ed730a83f)
`MakeShareAudioButton`

# 5
![image](https://github.com/audacity/audacity/assets/22740106/d1bbd04e-2cdc-4ee9-8f21-ebf72a449eb9)
`OnShareAudio`

# 6
![image](https://github.com/audacity/audacity/assets/22740106/4115b23a-6083-4970-830a-5e41156fa0f6)
`Update_Preview`

# 7
![image](https://github.com/audacity/audacity/assets/22740106/a9855749-960b-407c-be15-62a9c7709b32)
`Open_from_Cloud`

# 8
![image](https://github.com/audacity/audacity/assets/22740106/26882a11-8634-44bd-ba6c-b650df846af7)
`Export_Menu`

# 9
![image](https://github.com/audacity/audacity/assets/22740106/57b1eb82-3429-4ce8-bcbb-f72bfc111e08)
Do we want to tag this too ?

**Comment by dozzzzer** [comment]
Tested
