### ISSUE TITLE
Would it be extremely difficult to get the option to have absolute times on the x-axis?

### ISSUE THREAD

**Issue by rin67630** [audacity/audacity#662]
I would really love to be able to get the possibility to choose absolute time (hh:mm:ss) from the system time of recording on the x-axis of a track.
Would that be a huge issue, breaking a lot of other things, or would it be easily doable?
IMHO storing the time of starting the recording in the metadata and doing a bit if time math on the axis ribbon?

**Comment by SteveDaulton** [comment]
Yes, it would be extremely difficult if not impossible. If you import a file, Audacity has no idea which decade it was recorded, let alone the time. Even if Audacity did know the start time, as soon as you start editing, the times will be wrong.
There is however a plug-in that may fit your purpose. See this post on the forum: https://forum.audacityteam.org/viewtopic.php?p=337348#p337348
If you have further questions, please ask on the forum.

**Comment by rin67630** [comment]
Thank you, that helped.
