### ISSUE TITLE
Audacity Crashes when i Zoom in and out.

### ISSUE THREAD

**Issue by evansdaniel79** [audacity/audacity#6623]
### Bug description

I am running Linux and have installed audacity via flatpak. Everything seemed fine until i tried to zoom out with the touch-pad and ctrl. key. Audacity suddenly crashed! This is very frustrating  and could cause data lose. My exact OS details are in a screenshot.

### Steps to reproduce

Record and track, then use touch-pad and ctrl key to zoom in and out.

### Expected behavior

Zoom in and out

### Actual behavior

Audacity crashes

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

### Additional context

![Screenshot_20240606_081702](https://github.com/audacity/audacity/assets/155123241/ed08f822-e962-457d-b94a-308d593c4573)

**Comment by dozzzzer** [comment]
Could not reproduce (Ubuntu 22.04/Fedora 39); it zooms in and out just fine, both on mono and stereo tracks.

**Comment by evansdaniel79** [comment]
Sorry I have since switched to Fedora KDE 40 and have had no issues!!

**Comment by dozzzzer** [comment]
Fantastic!
