### ISSUE TITLE
[AU4] Clip action: enable-stretching

### ISSUE THREAD

**Issue by igorkorsukov** [audacity/audacity#6630]
### Description

called from clip context menu

**Comment by grliszas14** [comment]
QA bulletpoints:
* Stretch-to-match-tempo remembered for every clip separately
* Stretch-to-match-tempo saved into project file so it is remembered on next project open
* Enabling Stretch-to-match-tempo resets the tempo of the clip immediately to match project’s tempo
* Tempo change should affect clips view
* Trimming should be applied if any clips are going to overlap

**Comment by dozzzzer** [comment]
Tested
