### ISSUE TITLE
Change the audio volume

### ISSUE THREAD

**Issue by leonel-mendoza** [audacity/audacity#6632]
### Your idea

My idea is to be able to increase or decrease the volume of the spectrum visually, I know that there's a feature to amplify it but if it it's implemented by clicking on the audio and mouse the mouse to above (for example) to increase it or vice versa, to reduce it by clicking and move the mouse below. This would be a more quicker and efficient manner to increase or decrease it's spectrum size volume, and as having interacted with an artist that wanted this feature would be an advantage to have it on a software like this, getting more closer over time to other premium software without actually being one.

### Problem to be solved

Clicking on the spectrum audio, move the mouse vertically (Y) up so Y+, increase audio, the more is being incremented the value of Y more the sound level is increased, if Y is reduced like Y- when after clicking with the mouse it's moved Y- then the level of the sound is decreased.

**Comment by LWinterberg** [comment]
I'm a bit confused about that "visually" you're mentioning. Do you mean zooming in vertically? In that case, it'd bectrl+scrolling on the vertical ruler on the left of the waveform

**Comment by leonel-mendoza** [comment]
There's an option called "Amplifier" to increase the dB of an audio/song, but to access it you require to go to the toolbar and search for the options, what I want to do is the next:

- Click directly on the audio/song
- Sustain the click and by sliding the mouse vertically increase the sound volume (to amplify it)
- If the mouse is slid vertically not up but down to decrease the amplified volume.

This without requiring to go to the Amplify function, so that can be more efficient in cases such as having two different tracks and you require to put both in the same volume level. If a person doesn't know much about how much the volume amplifies it (because don't know that measurement), adding this feature I mention would make it less complicated.

**Comment by leonel-mendoza** [comment]
I think I figured out what I was looking for: The Envelope Function, to increase or decrease the volume of a sound or audio directly from the spectrum without requiring using the function of "Amplify".
