### ISSUE TITLE
In the File Menu Close and Exit would be better co-located

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#6644]
### Your idea

The Audacity commands for **Close** and **Exit** perform somewhat related (but more than subtly different) functions and thus it might make sense to co-locate them in the File menu.

**As it is now:**
![image](https://github.com/audacity/audacity/assets/50205984/5dd122cc-522b-49cc-bfbe-4d095dc5300c)

**Proposed rearrangement:**
![image](https://github.com/audacity/audacity/assets/50205984/e6b20c04-38a3-430f-a1df-0501029d39e2)

@DavidBailes  suggests later in this thread:
> So maybe:
> **Close Project**
> **Exit**

_I support that suggestion as it would provide greater clarity of purpose of the **Close** command._

### Problem to be solved

A recent posting in a thread on GitHub #1464 (9th post) shows that users can be confused as to the differences between Close and Exit - and indeed may even overlook the Close and only use Exit (when they don't really intend to close all open projects).

So it may make sense to co-locate them in the menu to encourage "discoverabilty" of the differences between the two.  

It would also the two commands to be co-located on the manual page for the File menu.

### Prior art

See above.

### Additional context

User @jpgreen3 wrote in #1464 

>F. Exiting Audacity via 'file' - 'exit' and the upper - right corner X produces different results. Using the 'X' only closes the running instance of audacity that is the focus at the moment, which seems to me the correct behavior - though I'm not sure closing this way invokes the 'compacting' routine when appropriate. The 'file' - 'exit' mode causes all currently running instances of Audacity to close, which to me is an unexpected and undesirable action. Both modes of exiting the program should close only the current instance, invoking the 'compacting' routine when appropriate, and prompting the user to save the project - or not - before close if unsaved edits exist.

----------------------------------------------------------------------------------

@LWinterberg I will add this to your Cleanup super-bug

**Comment by jpgreen3** [comment]
This is a great idea.  Out of habit, my eye always goes to the bottom of the ‘File’ menu looking for ‘Exit’.  

To make the distinction even clearer – though this is decidedly non-standard – the menu items could read: 

Close This

Exit All

 

Or something similar. 

John Green

 

From: Peter Sampson ***@***.***> 
Sent: Sunday, June 9, 2024 3:33 AM
To: audacity/audacity ***@***.***>
Cc: jpgreen3 ***@***.***>; Mention ***@***.***>
Subject: [audacity/audacity] In the File Menu Close and Exit would be better co-located (Issue #6644)

 


Your idea


The Audacity commands for Close and Exit perform somewhat related (but more than subtly different) functions and thus it might make sense to co-locate them in the File menu.

As it is now:
image.png (view on web) <https://github.com/audacity/audacity/assets/50205984/5dd122cc-522b-49cc-bfbe-4d095dc5300c> 

Proposed rearrangement:
image.png (view on web) <https://github.com/audacity/audacity/assets/50205984/e6b20c04-38a3-430f-a1df-0501029d39e2> 


Problem to be solved


A recent posting in a thread on GitHub #1464 <https://github.com/audacity/audacity/issues/1464>  (9th post) shows that users can be confused as to the differences between Close and Exit - and indeed may even overlook the Close and only use Exit (when they don't really intend to close all open projects).

So it may make sense to co-locate them in the menu to encourage "discoverabilty" of the differences between the two.

It would also the two commands to be co-located on the manual page for the File menu.


Prior art


See above.


Additional context


User @jpgreen3 <https://github.com/jpgreen3>  wrote in #1464 <https://github.com/audacity/audacity/issues/1464> 

F. Exiting Audacity via 'file' - 'exit' and the upper - right corner X produces different results. Using the 'X' only closes the running instance of audacity that is the focus at the moment, which seems to me the correct behavior - though I'm not sure closing this way invokes the 'compacting' routine when appropriate. The 'file' - 'exit' mode causes all currently running instances of Audacity to close, which to me is an unexpected and undesirable action. Both modes of exiting the program should close only the current instance, invoking the 'compacting' routine when appropriate, and prompting the user to save the project - or not - before close if unsaved edits exist.

  _____  

@LWinterberg <https://github.com/LWinterberg>  I will add this to you Cleanup super-bug

**Comment by LWinterberg** [comment]
fwiw, the traditional place for Close is to live together with Open, rather than Exit. 
<details><summary>Examples</summary>

![image](https://github.com/audacity/audacity/assets/87814144/77f82741-14ca-4ec3-aea9-9bf319cb8fa2)

Older Audacity versions did this too

</details>

However, more modern programs seem to have it at the bottom:

<details><summary>Examples</summary>

![image](https://github.com/audacity/audacity/assets/87814144/23041260-a951-42ab-a05c-1d09427ed82b)

![image](https://github.com/audacity/audacity/assets/87814144/8547db48-6fa1-4e0d-b0c8-be55f6e9d71c)

</details>

**Comment by petersampsonaudacity** [comment]
@LWinterberg 

So what is your call on this ?

**Comment by SakiPapa** [comment]
Apple has specified detailed guidelines for the interface. I don't think the order of the menus in the File menu should be changed in Audacity for the macOS platform.

[https://developer.apple.com/design/human-interface-guidelines/the-menu-bar#File-menu](url)

**Comment by petersampsonaudacity** [comment]
@SakiPapa 

I'm far from convinced that Apple should be the final arbiter in the design of Audacity menus, not least because Mac users of Audacity are a relative minority compared with Windows users.

I also note from following your link that Apple have no specification for an "Exit" command anywhere in their guidelines for a File menu, so the topic of Close and Exit co-location (the subject of this ENH thread) fails to be addressed by Apple.

**Comment by petersampsonaudacity** [comment]
I also note that, ib vontrast to Apple's guidleines, Microsoft makes no such precriptive latout recommendations for menus in apps.

But in their own Apps the Close goes right at the bottom

### Word
![image](https://github.com/audacity/audacity/assets/50205984/530c311a-17d0-4b6d-9752-1fbe9ca0a121)

### Excel
![image](https://github.com/audacity/audacity/assets/50205984/c6269426-1639-4c7c-9cd7-094d94fe40d6)

**Comment by petersampsonaudacity** [comment]
And these are Oracles's design guidelines - note that they have Close and Exit co-located at the bottom of suggested File menu layouts:
![image](https://github.com/audacity/audacity/assets/50205984/1a756392-15b6-4933-8d52-ffe868390eb3)


See: https://docs.oracle.com/cd/E19455-01/806-2915/6jc3nftni/index.html

**Comment by DavidBailes** [comment]
> To make the distinction even clearer – though this is decidedly non-standard – the menu items could read:
Close This
Exit All
Or something similar.

So maybe:
Close Project
Exit
(Which would be similar to Reaper)

**Comment by petersampsonaudacity** [comment]
> So maybe:
> Close Project
> Exit

Sounds good to me @DavidBailes  -  I like the clarity of purpose that that provides "Does what it says on the tin".

_Should I add your suggestion to the top post in this thread David?_

**Comment by DavidBailes** [comment]
> Should I add your suggestion to the top post in this thread David?

It can be added anywhere.

**Comment by LWinterberg** [comment]
yeah, HIGs are guidelines, not absolute rules. It's not uncommon to see different HIGs contradict each other, or examples being shown inside a HIG which don't "apply the HIG correctly". On a very related note, it's delightful to read HIGs from the 80s and 90s - it appears to me (though I cannot prove it exactly) that Apple's HIG on the use of ellipses in menus is *inspired by* Microsoft Excel (the then-macOS exclusive alternative to Microsoft Multiplan) as Apple software at the time does not use it. 

Anyway, for this bug: We decided to keep Close in the traditional-ish order (ie in the New/Open/Close/Save group, after which the Import/Export follows), though separated out a bit to prevent misclicks. 

I don't mind it being moved down, though I'd prefer seeing its name changed fora release first before being moved, just to ease confusion a bit. 

As for the final names and positions, I prefer
* Close Project
* Quit Audacity

at the bottom

(which, incidentally, would also make Ctrl+Q make sense for Quit again)

**Comment by petersampsonaudacity** [comment]
> As for the final names and positions, I prefer
> 
>     * Close Project
> 
>     * Quit Audacity
> 
> 
> at the bottom

That sounds good to me Leo :-)

**Comment by SakiPapa** [comment]
Please excuse the geographical time lag.

LWinterberg-san wrote,
> As for the final names and positions, I prefer
> 
> * Close Project
> * Quit Audacity
> 
> at the bottom

I agree with this idea.
If possible, please consider leaving it as it is in macOS.  It might be related to the development environment of Audacity.

Also I don't think Apple's HIG is an absolute standard to follow - many Audacity users use keyboard shortcuts or access keys, may not notice the change the change:)
Though, I know that a certain number of people are confused by a change in menu order.

I checked the "File" menu of proprietary and open source cross-platform apps,  Studio One / VLC mediaplayer / Handbrake / Google Chrome / Affinity Photo were compliant with Apple's HIG. Newer DTM app Studio One, only basic functions are available from the menu.  Most functions you must use from the panel interface.

When Apple moved the classic Mac OS to the UNIX-based Mac OS X more than 20 years ago, the "Application" menu was newly placed between the "Apple" menu and the "File" menu. At that time, Apple moved "Quit" ("Exit" in Windows) from the traditional "File" menu to the "Application" menu.  It might be small change. I remember the confusion and debate that erupted in the Mac community at the time.

It is interesting to see Microsoft, who values compatibility, is making a BIG change to the Windows GUI many time.

In any case, Windows OS and mac OS have developed in a mutually inspiring way.

LWinterberg-san,
 About "ellipsis", Mac OS System 1.0 (1984) had used "..." in the menu bar before Microsoft Excel 1.0 (1985) used in its menu.
https://winworldpc.com/screenshot/7ac2aec2-a20e-24e2-8098-11c3a4e284a2/d1a355f4-d600-11e7-a73f-fa163e9022f0

**Comment by irodweb4** [comment]
> ### Your idea
> The Audacity commands for **Close** and **Exit** perform somewhat related (but more than subtly different) functions and thus it might make sense to co-locate them in the File menu.
> 
> **As it is now:** ![image](https://private-user-images.githubusercontent.com/50205984/337961302-5dd122cc-522b-49cc-bfbe-4d095dc5300c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MzI5NzAsIm5iZiI6MTcxODgzMjY3MCwicGF0aCI6Ii81MDIwNTk4NC8zMzc5NjEzMDItNWRkMTIyY2MtNTIyYi00OWNjLWJmYmUtNGQwOTVkYzUzMDBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDIxMzExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4YmYzZmQ3Y2FjNzE5ZGYzZDllZmQ0NTQwZDQzNjg0NDg3ODZhMGQ5MWM4ZGI0NjgwNzc1NDYyZDY1MDc0N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.McKBoaMg_JJ69eDrK4K88blBA7RpmcqqfmWfi9iKoO0)
> 
> **Proposed rearrangement:** ![image](https://private-user-images.githubusercontent.com/50205984/337961330-e6b20c04-38a3-430f-a1df-0501029d39e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MzI5NzAsIm5iZiI6MTcxODgzMjY3MCwicGF0aCI6Ii81MDIwNTk4NC8zMzc5NjEzMzAtZTZiMjBjMDQtMzhhMy00MzBmLWExZGYtMDUwMTAyOWQzOWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDIxMzExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZDBkMjBkZWM4MTYwNDhhY2U5NGZlODhiNmJkYmI1MmU4MThhMjVhMzNjZWFmYTIzNGFhMWNiMGM3OGRmYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rer8H35o9G4ei7ouWUb6KKGHFu8e4J3EPPLzI2fiIVo)
> 
> @DavidBailes suggests later in this thread:
> 
> > So maybe:
> > **Close Project**
> > **Exit**
> 
> _I support that suggestion as it would provide greater clarity of purpose of the **Close** command._
> 
> ### Problem to be solved
> A recent posting in a thread on GitHub #1464 (9th post) shows that users can be confused as to the differences between Close and Exit - and indeed may even overlook the Close and only use Exit (when they don't really intend to close all open projects).
> 
> So it may make sense to co-locate them in the menu to encourage "discoverabilty" of the differences between the two.
> 
> It would also the two commands to be co-located on the manual page for the File menu.
> 
> ### Prior art
> See above.
> 
> ### Additional context
> User @jpgreen3 wrote in #1464
> 
> > F. Exiting Audacity via 'file' - 'exit' and the upper - right corner X produces different results. Using the 'X' only closes the running instance of audacity that is the focus at the moment, which seems to me the correct behavior - though I'm not sure closing this way invokes the 'compacting' routine when appropriate. The 'file' - 'exit' mode causes all currently running instances of Audacity to close, which to me is an unexpected and undesirable action. Both modes of exiting the program should close only the current instance, invoking the 'compacting' routine when appropriate, and prompting the user to save the project - or not - before close if unsaved edits exist.
> 
> @LWinterberg I will add this to your Cleanup super-bug

t`yb`

**Comment by nalin243** [comment]
@LWinterberg 

> I don't mind it being moved down, though I'd prefer seeing its name changed fora release first before being moved, just to ease confusion a bit.

I just changed the names. Should I make a pull request?

![Screenshot_20240803_080113](https://github.com/user-attachments/assets/8e8bd2c3-0c94-48de-acb4-2248c060d3f3)

**Comment by petersampsonaudacity** [comment]
> I just changed the names. Should I make a pull request?

@nalin243 

As @LWinterberg has said above in this thread that he approves of that as a first step, I would asy yes it would be sensible to submit the PR

**Comment by petersampsonaudacity** [comment]
Testing on W11 with @nalin243 's test brach build for this:  audacity-win-3.6.2-alpha-20240804+73bd8f9-x64

This looks good to go to me - as the first part of #6644

![image](https://github.com/user-attachments/assets/11108a1a-a325-4213-bf84-401c31d73c58)

**Comment by petersampsonaudacity** [comment]
@nalin243 

can I suggest _(in the absence of any negative comment about the wording change)_ that you go ahead and work on the second part of this issue by c-locating the two commands at the bottom of the File menu.

**Comment by nalin243** [comment]
@petersampsonaudacity 

I would rather wait for this to be merged first. Seeing as how release-3.6.2 will also be merged into master soon, I am going to be asked to rebase this one anyways so it would be better to do both in the new pull request together later.

**Comment by petersampsonaudacity** [comment]
> I would rather wait for some response on this from the maintainers.

@nalin243 

then I suspect that you may well be waiting some time - as I don't see it on ony of Muse's upcoming plans for future releases.

**Comment by LWinterberg** [comment]
3.6.2 got merged into master 5 mins ago, you can go ahead :)

**Comment by petersampsonaudacity** [comment]
@nalin243 

The Linux and Mac builds appear to have worked - but the Windows builds failed.

**Comment by nalin243** [comment]
@petersampsonaudacity 

I don't think it's due to something I did. The build itself seems fine but the tests seem to be failing by timing out. I have no idea what the issue could be.  The code change shouldn't warrant it, the changes are pretty basic. 

```
      Section( "Exit",
         // On the Mac, the Exit item doesn't actually go here...wxMac will
         // pull it out
         // and put it in the Audacity menu for us based on its ID.
         /* i18n-hint: (verb) It's item on a menu. */
         Command( wxT("Exit"), XXO("&Quit Audacity"), OnExit,
            AlwaysEnabledFlag, wxT("Ctrl+Q") )
```
This is probably the only thing I can think of that would cause mac build to fail, but the one in actions seems to have worked.

**Comment by kryksyh** [comment]
@nalin243 your changes are fine. The build fail is fixed in master, please rebase/merge your pr branch

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @nalin243 's latest branch build for this:  audacity-win-3.7.0-alpha-20240908+575662c-x64

![image](https://github.com/user-attachments/assets/c5ef555b-12c3-47b4-ba2d-ed30d1421706)

a)The new wording is implemented properly
b) the two commands are now co-located at the bottom of the File menu

But I'm failing to understand why we have (or need) a separator line between the two commands as they are both very closely related in functionality.

**Comment by dozzzzer** [comment]
@LWinterberg Do we really need a separator here? 

<img width="442" alt="image" src="https://github.com/user-attachments/assets/880bbd11-6202-439e-bf9b-3cfff568c75e">

**Comment by LWinterberg** [comment]
see discussion in https://github.com/audacity/audacity/pull/7275#issuecomment-2337530385 - it apparently is standard practice to have one between the two (could verify this in VScode and some others too), and also makes it slightly harder to misclick quit when you mean close.

**Comment by dozzzzer** [comment]
In this case, tested and good to go!
