### ISSUE TITLE
Integrating AppImage into system (AppImageLauncher, Gear Lever) causes startup warnings

### ISSUE THREAD

**Issue by MMachado05** [audacity/audacity#6645]
### Bug description

When the Audacity AppImage is executed directly from the file, everything launches exactly as expected. However, if an "integration" tool is used to add the app to your system menu, various pop-up windows with warning/error messages appear, which are described further down in this bug report. The most up-to-date stable versions of AppImageLauncher *and* Gear Lever were tested, and both showed the same behavior.

### Steps to reproduce

1. Download the Audacity AppImage bundle from the official download page.
2. Launch it an initial time to ensure no warning windows appear. (if testing with AIL, simply press "ignore and run once" when the pop-up appears)
3. Integrate into your system, either by...
    * Hitting the "Integrate" button when the AIL pop-up appears.
    * Dragging the AppImage into Gear Lever and choosing to "add to app menu."
4. Launch the Audacity AppImage from your system app menu.

### Expected behavior

Audacity launches with the same behavior as the initial test run.

### Actual behavior

The following errors appear in individual, sequential pop-up messages:

> GDK_BACKEND=x11 could not be found.
> 
> It has been removed from the list of recent files.

> UBUNTU_MENUPROXY=0 could not be found.
> 
> It has been removed from the list of recent files.

> audacity could not be found.
> 
> It has been removed from the list of recent files.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Linux

### Additional context

(K)ubuntu 22.04.3 LTS (both flavors exhibit the same issue)
Audacity e39f40

The following log is generated in both launch instances (that is, both *before* and *after* the app has been integrated):
```
14:50:45: Audacity 3.5.1
14:50:45: Error: Failed to load shared library 'libavformat.so.60' (error 0: Success)
14:50:45: Error: Failed to load shared library 'libavformat.so.59' (error 0: Success)
14:50:45: FFmpeg libraries loaded successfully from: /lib/x86_64-linux-gnu/libavformat.so.58.29.100
14:50:49: Error: Failed to load shared library 'libavformat.so.60' (error 0: Success)
14:50:49: Error: Failed to load shared library 'libavformat.so.59' (error 0: Success)
14:50:49: FFmpeg libraries loaded successfully from: /lib/x86_64-linux-gnu/libavformat.so.58.29.100
```

**Comment by mondele** [comment]
I found this issue report by searching for the text from the error message. It appears to be a problem with AppImage Launcher, rather than with Audacity per se. With the information from @MMachado05 I edited the launcher (in `~/.local/share/applications/`) and removed the command arguments that specified GDK_BACKEND, UBUNTU_MENUPROXY and the lone word "audacity" from the exec command. Audacity now launches without these error messages.

**Comment by MMachado05** [comment]
@mondele, your solution works!

It seems like the errors are not related to Audacity's functionality at all - just some faulty configuration on the part of the app's packaging/extraction process.

When launched from the terminal, arguments passed to Audacity are taken to be files the user wants to open, that were (likely, based on my guess) opened in a previous session. For some reason, integrating the AppImage makes the execution command in the `.desktop` file include some command-line arguments that just get perceived as attempts to open old files - files that do not exist. So, deleting these arguments should be a perfectly safe endeavor!

**Comment by DetachHead** [comment]
> It seems like the errors are not related to Audacity's functionality at all - just some faulty configuration on the part of the app's packaging/extraction process.

in that case can we re-open this issue? it still happens on the latest version (3.7.8)
