### ISSUE TITLE
Find reason for crashing unit tests

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#6646]
https://github.com/audacity/audacity/pull/6640

**Comment by saintmatthieu** [comment]
Looked into this. It looks like test cases using `MockedPrefs` segfault.
UTs must be green for PRs to get merged, so I suspect an upgrade in the MSVC sdk on Github to have started this?
I tried to update my MSVC compiler to reproduce the issue locally. Now I can't generate the solution anymore, the new compiler key 194 (was 193 before) causing problems during the installation of conan dependencies (so now using MSVC 2019 provisionally).
Since the crash seems to stem from mock-up code, I am less concerned now that it is as urgent for us to fix, still I'm leaving the P1 priority to make sure we don't release while this hasn't been clarified. @vsverchinsky has looked into this in the last few days and may have some ideas.

**Comment by LWinterberg** [comment]
Fwiw, #6640 also broke CI for Arch (which now gets stuck on "entering fake root" for 6 hours before timing out).

**Comment by vsverchinsky** [comment]
> Fwiw, #6640 also broke CI for Arch (which now gets stuck on "entering fake root" for 6 hours before timing out).

Seem to be a coincidence: https://github.com/vsverchinsky/audacity/actions/runs/9644840859/job/26597918286
