### ISSUE TITLE
Audacity causes JACK server to irreversibly hang on startup

### ISSUE THREAD

**Issue by ipatix** [audacity/audacity#665]
**Describe the bug**
I'm not quite sure since when Audacity does this, but I keep having this problem whenever Audacity starts, my JACK server starts to lock up. After that, using JACK is no longer possible until I reboot the machine. Apparently I can't even SIGKILL the jackdbus process so I'm only left with rebooting the computer. Stopping the JACK server from Cadence (kxstudio) isn't possible either.

This happens regardless of whether JACK or ALSA is selected as API.

My only current workaround for using Audacity is to stop JACK from Cadence, use Audacity, close Audacity, and restart the JACK server.

So far I have not had any problems with other programs, although I've come accross problems with PortAudio and the ALSA->JACK bridge before (although in that case the JACK server would not lock up).

**To Reproduce**
1. Open Cadence
2. Start the JACK server
3. Start the PulseAudio -> JACK bridge
4. Start the ALSA -> JACK bridge
5. Open Audacity
6. Opening Audacity takes a really long time (~30 seconds compared to like < 10 seconds)
7. Audacity will not crash, however the JACK server is now in the "locked up" state and is no longer usable.

**Expected behavior**
I would expect Audacity to not lock up the JACK server so I can keep using sound on the computer.

**Screenshots**
N/A

**Additional information (please complete the following information):**
 - OS: Debian Sid/Unstable
 - Audacity 2.4.2
 - Selected API: ALSA or JACK (happens with both)
 - Sound Cards available: Loopback, HDA Intel PCH, HDA ATI HDMI

**Additional context**
Here is a log file from Audacity's startup when JACK is running (and crashes afterwards):
[audacity.log](https://github.com/audacity/audacity/files/5210758/audacity.log)

Here is the support zip file (I stopped JACK before I generated this because I did not want to reboot the machine once again):
[Audacity_dbgrpt-2643-20200911T191232.zip](https://github.com/audacity/audacity/files/5210760/Audacity_dbgrpt-2643-20200911T191232.zip)

**Comment by ipatix** [comment]
One more thing I can add is that I have an identical software setup on a different machine and I cannot reproduce the issue on this other machine.

**Comment by ipatix** [comment]
I'm now bumping this once again because this problem is *extremely* annoying since it renders Audacity completely unusable.

I can offer some assistance in debugging, however, I have no idea of any Audacity internals. So if there is someone how could give me some tips for investigation, I'd be REALLY thankful.

**Comment by gstoehld** [comment]
I have the same issue on Manjaro with Audacity 2.4.1 and JACK2. 
Starting Audacity causes JACK to only output garbled audio that sounds kinda like trying to play back audio at a completely wrong sample rate, even for other clients. 
Even after closing Audacity, the problem persists and I have to kill JACK to restore it.

**Comment by IGBC** [comment]
I can also confirm this bug

**Comment by IGBC** [comment]
@ipatix what are your jack server settings?

namely sample rate, block size, and period?

**Comment by ipatix** [comment]
> @ipatix what are your jack server settings?
> 
> namely sample rate, block size, and period?

48000 Hz, 256 buffer size, 2 periods per buffer.

I've also used 512 samples per buffer in the past with the same result.

**Comment by ipatix** [comment]
Do I assume correctly this got solved? I'm probably not going to be that much of help anymore since I switched to pipewire since some time and I didn't run into this problem there at all.

**Comment by LWinterberg** [comment]
This is a [known issue](https://github.com/audacity/audacity/wiki/Known-Issues). We are not looking to fix this bug individually but may address it in larger structural changes.
