### ISSUE TITLE
Limiter graph: use lines to represent overshoot and undershoot

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#6659]
At the moment we are using areas for that. @Tantacrul brought forward convincing arguments why this should be using lines instead. The goal here is to improve intelligibility of the graph.

**Comment by dozzzzer** [comment]
@saintmatthieu On macOS, scales on both meters and timeline denotations are missing:

<img width="1180" alt="image" src="https://github.com/audacity/audacity/assets/70063970/9045329c-f1fc-4641-b558-3f420de448a2">

**Comment by dozzzzer** [comment]
Tested
