### ISSUE TITLE
Compressor & Limiter graph: VU meter enhancements

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#6662]
<img width="500" alt="image" src="https://github.com/audacity/audacity/assets/70063970/a1751c6c-aff3-4d29-b047-65916217f08c">

1. The lower boundary of -12 dB is too high, so I suggest we try to fit a greater range into that scale. For quiet sounds, the output meter may not display anything at all. For compression values greater than -12 dB, the "compression" bar may not be moving at all.
2. The current increment of 6 dB on the scale is too coarse. 1 dB would probably be much better.
3. The colors of the compression and the output bars should be red and green respectively.
4. Peak indicators for the compression and the output meters stick in the same place on the scale, even when the peak values change.

**Comment by chinakov** [comment]
Tested, thanks!
