### ISSUE TITLE
Only the first channel of files with more than 2 channels is shown

### ISSUE THREAD

**Issue by AbsenceJam** [audacity/audacity#6674]
### Bug description

[audacity-macOS-3.6.0-alpha-20240612+c5051c4-arm64](https://nightly.link/audacity/audacity/workflows/build/master/audacity-macOS-3.6.0-alpha-20240612%2Bc5051c4-arm64)
macOS Sonoma 14.5
ffmpeg 6 *or* 7 from Homebrew

When opening any of these (all I've tested so far):
DD 3.0, DD 4.0, DD 5.1, DD+ 5.1, FLAC 5.1, DTS-HD MA 5.1
Only the first channel is shown. DD 2.0 is okay.

Apologies if this is some sort of settings change!

### Steps to reproduce

- Clean install of Audacity
- Make sure ffmpeg is working
- Open one of the aforementioned formats

### Expected behavior

Each channel should be a seperate track as in 3.5.1.

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS, Windows, Linux

### Additional context

![3 5 1 - DD 3 0](https://github.com/audacity/audacity/assets/24455272/86394383-36a2-4659-b59b-c4ae2de68a8f)
![3 5 1 - DD 5 1](https://github.com/audacity/audacity/assets/24455272/0bd97519-d436-4e1f-8094-efe5642b7501)
![3 5 1 - FLAC 5 1](https://github.com/audacity/audacity/assets/24455272/b3b3d728-1b18-44cf-b054-f0e104580536)
![3 6 0 - DD 3 0](https://github.com/audacity/audacity/assets/24455272/74505795-4246-4cdb-9023-5b8bb15b3809)
![3 6 0 - DD 5 1](https://github.com/audacity/audacity/assets/24455272/889f38fb-9611-462e-92ae-bf377321310f)
![3 6 0 - FLAC 5 1](https://github.com/audacity/audacity/assets/24455272/b6fe4897-8ae3-4649-8c64-272fe1d1fef3)

**Comment by dozzzzer** [comment]
I've managed to reproduce this on macOS 14.5 and Windows 11.

**Comment by dozzzzer** [comment]
Bisects to https://github.com/audacity/audacity/commit/983dc1b7c7fd5008fd40420fefe6b63d68cd6a77 @Paul-Licameli

**Comment by dozzzzer** [comment]
The bug is **still reproducible** with the following formats: DTS-HD MA 5.1, DTS-HD MA 7.1, Dolby Digital 5.1, DTS:X, Dolby Digital Plus E-AC-3 5.1, 
The bug is **NOT reproducible** anymore with FLAC 5.1, FLAC 6.1, FLAC 7.1

**Comment by dozzzzer** [comment]
Tested and ready for merge. A new is created: https://github.com/audacity/audacity/issues/6858
