### ISSUE TITLE
Meters are squashed after resetting the configuration, or use Options in meter dropdown menus

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#6676]
### Bug description

If the User launches Audacity, and then resets the configuration, the User will be presented with misaligned values of the volume meter scale.

### Steps to reproduce

1. Launch Audacity
2. Reset Configuration via 'Tool -> Reset Configuration'
3. Observe Result
4. (Optional) Move the window or click on the meters to fix them.

### Expected behavior

The volume scale meter should not be misaligned upon launch of Audacity or resetting of the configuration.

### Actual behavior

The volume scale meter is misaligned.

![image](https://github.com/audacity/audacity/assets/139755141/42d8868c-4f10-4cd9-bdcc-b7d35f59eccf)

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

**Comment by petersampsonaudacity** [comment]
Also happens if you you use the Options in either of the meters' dropdown menus.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @vsverchinsky 's branch build for this:  audacity-win-3.6.0-alpha-20240624+638605e-x64

The meters are no longer squished/squashed after
a) Reset Configuration
b) use of Options in meter dropdown menus

Looks to be fixed in this branch build.

**Comment by dozzzzer** [comment]
Tested
