### ISSUE TITLE
Loop point is shown on the left edge on launch

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#6677]
### Bug description

A UI misalignment is present in the time toolbar, next to the settings button. 

### Steps to reproduce

1. Launch Audacity
2. Look at the left corner of the time toolbar

### Expected behavior

The UI should not be misaligned.

### Actual behavior

![image](https://github.com/audacity/audacity/assets/139755141/3b721438-b5e4-4c77-8cf5-58046c66ce2a)

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

**Comment by petersampsonaudacity** [comment]
This is a regression on 3.5.1 and earlier

**Comment by dozzzzer** [comment]
Tested
<img width="555" alt="image" src="https://github.com/audacity/audacity/assets/70063970/a9910f31-50bf-441e-9f73-41f53f75d84c">

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @vsverchinsky 's branch build for this:  audacity-win-3.6.0-alpha-20240624+55c88da-x64

The errant black/white (depending on Theme) triangle when there is no loop region is now no longer present in this branch build
