### ISSUE TITLE
Reset toolbars on upgrade to 3.6

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#6679]
otherwise mac users won't see a record button

**Comment by petersampsonaudacity** [comment]
Does not appear to affect Windows

**Comment by LWinterberg** [comment]
![image](https://github.com/audacity/audacity/assets/87814144/5d3f78ff-266b-495b-85a2-f168f3b2a3cb)

on windows, upgrading from a lower version would look like this

**Comment by chinakov** [comment]
This is implemented correctly, the task has been implemented. Thank you!
