### ISSUE TITLE
Missing tooltip text in transport toolbar buttons

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#6687]
<img width="223" alt="image" src="https://github.com/audacity/audacity/assets/70063970/04697ca7-1deb-4afd-8afd-687d6985bc12">

Bisects to https://github.com/audacity/audacity/commit/eb40d2e0b408535ddabf99f4745e2c27aea34b1f

**Comment by petersampsonaudacity** [comment]
This is a regression on 3.5.1 and earlier

**Comment by petersampsonaudacity** [comment]
No tooltip for **Loop Play** either
![image](https://github.com/audacity/audacity/assets/50205984/c2083321-29c3-454f-a168-0950732c00a8)

And no tooltip at all for  **Stop**

**Comment by LWinterberg** [comment]
It in fact doesn't show the first part of the tooltip for of the buttons. I see that ControlToolbar.cpp has a new `MakeControlToolBarButton` which takes an argument for label but doesn't use it at the moment. However, adding a `button->SetToolTip(label);` doesn't actually fix the problem, so I've got no idea where this goes wrong. I suspect that a9e849094d899d21ea61d29c02be02a6e6696205 is the exact commit which introduces this bug.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @vsverchinsky 's branch build for this:  audacity-win-3.6.0-alpha-20240624+cda5b49-x64

The Transport toolbar buttons' tooltips are now fully displaying properly in this branch build.

Here's an example:
![image](https://github.com/audacity/audacity/assets/50205984/7c31ef23-6e3f-47d1-8d4f-315a9ea2a336)

**Comment by dozzzzer** [comment]
Tested
