### ISSUE TITLE
Validation Message differs from actual minimum slider value

### ISSUE THREAD

**Issue by nalin243** [audacity/audacity#6694]
### Bug description

The validation message value is different from the actual slider value. The same issue is present in all the three compression curve slider. I am not sure if this is the only place this bug affects. 

### Steps to reproduce

1. Open up Limiter either in the realtime stack or via the main Effect menu.
2. In the compression curve area, for threshold and make up target move the slider to the beginning and observe the minimum value. For Knee width max out the slider and observe the maximum value. 
3. Now produce a validation error.

### Expected behavior

The validation message value should match the minimum or maximum slider value. 

### Actual behavior

The minimum slider value of -30.0 for both threshold and make up target does not equal the actual minimum value which we can input in the text box which is -300. 

The maximum slider value of 10.0 for knee width does not equal the actual maximum value which we can input in the text box which is 100. 

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

![issuepart1](https://github.com/audacity/audacity/assets/29351098/9aa1fb32-62da-4d90-929f-729ffe04e9c9)
![issuepart2](https://github.com/audacity/audacity/assets/29351098/f0ce6cb0-3225-4946-9cee-8fbd4aa9f6ec)

**Comment by nalin243** [comment]
@saintmatthieu Same issue in the Compressor effect.

**Comment by saintmatthieu** [comment]
@nalin243 thanks for your report!

**Comment by dozzzzer** [comment]
Tested
