### ISSUE TITLE
Effect menu new command has inconsistent capitalization for "Effects" - and incorrect ellipsis use

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#6697]
### Bug description
A new menu item has been added to the File menu for 3.6.0 "**Get more effects**"

It is inconsistent with the other items in the menu as "effects" is not capitalized.

UPDATE
and **Add AI effects** was also added to the menu with "effects" not capitalized.

_And BTW I thought we were trying to lose ellipses from menu commands, not add new ones)._
**Furthermore this particular use of ellipses in menu commands is incorrect as that should be used to indicate that a dialog will appear within the app that requires input or data from the user - BUT these two commands take the user away from Audacity and launch pages on two different websites.**

### Steps to reproduce
1. launch 3.6.0 alpha master
2. click on Effect menu
3. Observe: Effects is un-capitalized in "Get more effects..." and in "Get AI effects"

### Expected behavior
Menu item should be capitalized as:  **Get more Effects**

### Actual behavior
![image](https://github.com/audacity/audacity/assets/50205984/6403fed7-794e-4587-8291-1e2e2a23fa46)

**UPDATE**
Even worse now with 3.6 where **Get AI effects** was addede with Effects inconsistently un-capitalized:
![image](https://github.com/user-attachments/assets/9e20006c-7755-4505-ba03-3d4213f894da)

### Audacity Version
current master / alpha / nightly build

### Operating system
Windows 10 - but assume all OS

### Additional context
None

**Comment by petersampsonaudacity** [comment]
@LWinterberg @Tantacrul 

Thep use of ellipses in these two menu commands introduced in 3.6.0 is incorrect.

As that should be used to indicate that a dialog will appear within the app that requires input or data from the user - BUT these two commands take the user away from Audacity and launch pages on two different websites.

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444). We've redone, or plan on redoing, various things from scratch, including the entire UI, and the part this bug is about. As such, I'm closing this bug as it will be fixed there and we won't be fixing it for the final releases of Audacity 3.
