### ISSUE TITLE
Renaming the track name of a Note track also changes the name of the clip

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#6698]
### Bug description
Renaming the track name of a Note track also changes the name of the clip.

This is inconsistent with Audio tracks where the clip name is unchanged when you change the track name in the Track Control Panel

### Steps to reproduce
1. get a Note track (MIDI file)
2. change the track name in the TCP
3. Observe: the clip name also changes to the new track name

### Expected behavior
Renaming the track name of a Note track should **_NOT_** change the name of the clip.

### Actual behavior
Renaming the track name of a Note track also changes the name of the clip.

### Audacity Version
3.5.1 and latest alpha master for 3.6.0

### Operating system
Windows 10 - but assume all OS

### Additional context
This could effectively destroy a users carefully created clip name, thus this incurs data loss.

**Comment by LWinterberg** [comment]
Note tracks don't have clips, they just have a single track which can be offset.
