### ISSUE TITLE
8-bit FLAC samples are not imported correctly

### ISSUE THREAD

**Issue by sagamusix** [audacity/audacity#670]
**Describe the bug**
It seems like 8-bit FLAC samples are imported with a wrong amplification factor - to me it looks like the raw 8-bit values are interpreted as if they are from a 16-bit sample, so only the low 8 of 16 bits are ever used.

**To Reproduce**
1. Add https://sagagames.de/stuff/eeeeeeee.flac or any other 8-bit FLAC file to your Audacity project
2. Notice that it's practically silent
3. Normalize to see that there is actually data being imported

**Expected behavior**
The example file should peak at 0dB. You can use e.g. VLC to verify that this is correct.

**Additional information (please complete the following information):**
 - OS: Windows 10 x64
 - Version 2.4.2

**Comment by petersampsonaudacity** [comment]
I have logged this on Bugzilla our Audacity bugtracker
https://bugzilla.audacityteam.org/show_bug.cgi?id=2782
Bug 2782 - 8-bit FLAC samples are not imported correctly

Accordingly I will close this GitHub Issue in favor of that tracked bug.
