### ISSUE TITLE
audacity crashes on start if lv2 folder is present in user folder

### ISSUE THREAD

**Issue by enorrmann** [audacity/audacity#6701]
### Bug description

![Screenshot from 2024-06-16 17-20-22](https://github.com/audacity/audacity/assets/1006434/e33c12d5-4fa8-4583-88e7-c8fdfcad75b1)
if I put any lv2 plugin on 
/home/myuser/lv2 folder
the app fails to  start

### Steps to reproduce

create lv2 folder under user folder on linux
try to start audacity

### Expected behavior

the app sould show main gui

### Actual behavior

app shows error

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

**Comment by enorrmann** [comment]
update: if 
/home/myuser/lv2
folder contains ANY file, the app will crash on startup

**Comment by dozzzzer** [comment]
Could not reproduce this either on Fedora 39 or Ubuntu 22.04, both with random files in LV2 directory and actual plugins.

**Comment by enorrmann** [comment]
> Could not reproduce this either on Fedora 39 or Ubuntu 22.04, both with random files in LV2 directory and actual plugins.

tested with debian 12 and audacity installed from distro deb files
tthe logs files shown in the above message are all empty
is there a way to show other kind of logs ?

**Comment by enorrmann** [comment]
it could be, I tried to compile 3.6.0-alpha and the issue is not present
