### ISSUE TITLE
Focus border is hard to discern in new default Light theme for 3.6.0

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#6702]
### Bug description
For the new default Light theme introduced recently for 3.6.0 the focus border has been changed to a colour that is much harder to discern than it was previously - previously it was yellow and now it is blue against a blue-based background.

This is not a problem for the other 3 themes:
a) Classic is the old Light theme from 3.5 and earlier - and retains its yellow focus border
b) Dark has a blue/purplish Focus border that is readily discernible against the dark background
b) High Contrast has a light blueish Focus border that is also readily discernible against the dark background

### Steps to reproduce
1. launch latest 3.6.0 alpha master
2. get a few audio tracks
3. make one of them Focused
4. Observe: the Focus border is hard to discern

### Expected behavior
A more readily discernible Focus border for the Light theme.

Ideally yellow as that makes a good contrast against the blue, without being too much "in your face".
_And avoids a lot of updates in the manual_  👍 

**Update:**  _I have made the manual color-blind to the actual color of the Focus border, not least as the color you get depends on the theme you choose._

### Actual behavior
Here it is the second of the three tracks that has Focus, but it's darned hard to spot that.
![image](https://github.com/audacity/audacity/assets/50205984/871c8637-b1f6-48bb-8e1f-1cabd682cb15)

### Audacity Version
current master / alpha / nightly build

### Operating system
Windows 10 - but assume all OS

### Additional context
The main problem here is that the new Light is the default theme (which therefore most users will be using) and that is the one theme of the 3 where Focus is the hardest to spot.

I have put several P1s in the manual for pages that mention the yellow Focus border.

**Comment by DavidBailes** [comment]
> For the new default Light theme introduced recently for 3.6.0 the focus border has been changed to a colour that is much harder to discern than it was previously

I agree.

**Comment by LWinterberg** [comment]
@jessjwilliamson - I think we need a lighter color for the border around the focused track. Do you have a nice hex for me?

**Comment by jessjwilliamson** [comment]
> @jessjwilliamson - I think we need a lighter color for the border around the focused track. Do you have a nice hex for me?

Try 97A8FD :)

**Comment by chinakov** [comment]
Tested, thanks
