### ISSUE TITLE
New theming: some buttons have white stripes inside them

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#6706]
As soon as one hovers over such a button, the unwanted "cross" disappears.
<img width="816" alt="image" src="https://github.com/audacity/audacity/assets/70063970/ff09b869-b33b-495f-a73d-59afc9fe08f5">

**Comment by petersampsonaudacity** [comment]
@dozzzzer 

Sergey, this is fine in Windows - I know as I have been updating the Manual today and over the weekend for the new Light theme.

**Comment by LWinterberg** [comment]
what the fuck

**Comment by vsverchinsky** [comment]
👀 
> can you bisect the branch in which I added the theme? My strongest suspicion lies on https://github.com/audacity/audacity/commit/4ba129704a00f46a10d4e50e3ea5066dac1c886d at the moment and that it somehow causes a race condition.

From what I see it's likely related to nine-patches drawings

@dozzzzer 
Is it AppImage build or native, what distro is it running on?

**Comment by dozzzzer** [comment]
@vsverchinsky Appimage/Fedora 39

**Comment by vsverchinsky** [comment]
@dozzzzer I was not able to reproduce that issue with neither of CI-generated AppImages. Tried on Arch and Ubuntu, could you please try [this](https://github.com/audacity/audacity/actions/runs/9792050489) build and tell if the issue still present for you?

**Comment by dozzzzer** [comment]
@vsverchinsky yes, and both Fedora and Ubuntu still exhibit the same issue as before:
![image](https://github.com/audacity/audacity/assets/70063970/f685ac3b-06c0-4807-bbd7-65983954c1e2)

**Comment by LWinterberg** [comment]
I'm unable to reproduce this too

**Comment by LWinterberg** [comment]
I still don't see any people reporting this problem. Lowering prio and kicking it out of the milestone

**Comment by dozzzzer** [comment]
The issue appears to be caused by the option "Accelerate 3D Graphics" in the VMware Player.
