### ISSUE TITLE
Assertion failed when painting button in debug version

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#6708]
### Steps to reproduce

Open debug version of Audacity

### Expected behavior

No assertions.

### Actual behavior

Assertion, shown below. If you ignore it, you keep on getting these assertions quite frequently.

---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Assertion failed!

Program: U:\audacity\build\Debug\lib-theme.dll
File: U:\audacity\libraries\lib-theme\AColor.cpp
Line: 86

Expression: r.width >= bitmap.GetWidth() - mid

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts

(Press Retry to debug the application - JIT must be enabled)
---------------------------
Abort   Retry   Ignore   
---------------------------

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

### Additional context

Part of call stack:
```
 	lib-theme.dll!`anonymous namespace'::DrawNinePatch(wxDC & dc, wxBitmap & bitmap, const wxRect & r, int mid) Line 86	C++
 	lib-theme.dll!AColor::DrawFrame(wxDC & dc, const wxRect & r, wxBitmap & bitmap, int mid) Line 335	C++
	Audacity.exe!AButton::OnPaint(wxPaintEvent & __formal) Line 365	C++
```

**Comment by LWinterberg** [comment]
I ran into the same assertion earlier but thought I fixed it in https://github.com/audacity/audacity/commit/50990584c997b907b264c9e13ece5b9b84587e12 - at least after that SetFrameMid(2) (default was 1) the assert violation no longer occurred for me. 

I cannot reproduce it by just launching Audacity.

**Comment by nalin243** [comment]
I am still getting this as well.

**Comment by LWinterberg** [comment]
Ah, I think I know what's going on - the loop button is drawn too small for you because the toolbar hasn't reset for you yet. If you reset your toolbars (or apply any change in preferences), it should sort itself out. https://github.com/audacity/audacity/pull/6682 would fix that for everyone on upgrading.

**Comment by DavidBailes** [comment]
> If you reset your toolbars (or apply any change in preferences), it should sort itself out

Yes, that is the case.
