### ISSUE TITLE
Trying to enter digit 8 or 9 into project sample rates opens a dialog instead

### ISSUE THREAD

**Issue by sagamusix** [audacity/audacity#671]
**Describe the bug**
Trying to enter either the digits 8 or 9 into the project sample rate box pops up a dialog to either adjust the left or right border of the selection instead.

**To Reproduce**
1. Focus the project sample rate field
2. Type digit 8 into sample rate field
3. Close the dialog for adjusting the left selection border that just opened
4. Type digit 9 into sample rate field
5. Close the dialog for adjusting the right selection border that just opened

**Expected behavior**
I should be able to enter digits 8 and 9 for my project sample rate.

**Screenshots**

![record](https://user-images.githubusercontent.com/875883/93643275-fb851100-f9ff-11ea-86ed-0e10ee83d3a9.gif)

**Additional information (please complete the following information):**
 - OS: Windows 10 x64
 - Version Audacity 2.4.2
- German keyboard layout
- Fresh Audacity install on this system

**Additional context**

**Comment by petersampsonaudacity** [comment]
Works fine for me on W10 Home 64-bit with 2.4.2 English keyboard and the latest 3.0.0 alpha builds that I have

**Comment by sagamusix** [comment]
According to [this forum thread](https://forum.audacityteam.org/viewtopic.php?t=111403) it also happens with Norwegian keyboard layouts so maybe you could try to install a second keyboard layout? Maybe any ISO layout will do?

**Comment by DavidBailes** [comment]
I can confirm this bug using the german keyboard layout, and it will also
affect the norwegian layout.
There's a workaround. The keyboard shortcuts for left at playback position
and right at playback position are [ and ] respectively. If you either
clear them or set them to g and h, for example, that will fix the problem.

David.

**Comment by sagamusix** [comment]
@petersampsonaudacity is there a bugfix for this issue or why was it closed?

**Comment by petersampsonaudacity** [comment]
Sorry, I got confused with 2 other locale issues that we had - and that got fixed for 3,0.0 - so I reopened this

**Comment by petersampsonaudacity** [comment]
I have logged this as P3 Locale Bug #2781   in Bugzilla our bugtracker
https://bugzilla.audacityteam.org/show_bug.cgi?id=2781
Bug 2781 - German keyboard: Trying to enter digit 8 or 9 into project sample rates opens a dialog instead

Accordingly I shall close this GitHub Issue in favor of the Bugzilla entry
