### ISSUE TITLE
Compressor and limiter accessibility: using the non-linear sliders with arrow keys.

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#6714]
### Bug description

For the non-linear sliders in these effect dialogs, eg the sliders in the smoothing section:
1. Right arrow has not effect.
2. When the slider is near the left hand end, the slider position can't be changed using either left or right arrow.

So these sliders are unusable for keyboard users.

### Steps to reproduce

1. Open the compressor dialog.
4. Tab to the Lookahead slider.
5. Press Home, then Page Down the value is now 4.3.

Case A:
6. Press right or up arrow.

Case B:
4. Hold down left or down arrow, until the value stops changing.

### Expected behavior

Case A:
The value is increased.

Case B:
The final value is 0.

### Actual behavior

Case A:
The value is unchanged.

Case B:
The final value is 2.7

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

**Comment by DavidBailes** [comment]
@LWinterberg Please can this issue be added to 3.6.0 - I've submitted a PR to fix it.

**Comment by DavidBailes** [comment]
@dozzzzer . Please could you assign a priority to this?

**Comment by dozzzzer** [comment]
@DavidBailes yes, I've added it to 3.6

**Comment by dozzzzer** [comment]
Tested
