### ISSUE TITLE
There is no indication in EGAT dialogs of the prest settings currently in play

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#6720]
### Bug description
In all of the current EGATs here is no indication in their dialogs of the preset settings (factory presets or user-defined presets) currently in play for the EGAT.

IIRC this issue was discussed in the past but nothing ever came of it.

Now that the action buttons in all EGATs have been been moved back to the bottom of the EGAT dialog with the Presets button remaining at the top there is now sufficient room at the top alongside the Presets button to present this information to the user.

This was raised on the Forum today with regard to the EQ effects in particular:
https://forum.audacityteam.org/t/3-5-1-filter-curve-eq-issues-in-macos-sonoma-ui/109434

### Steps to reproduce
1. get some audio and select it
2. Effect > Filter curve EQ
3. Observe: no textual indication of the preset currently in use 

### Expected behavior
![image](https://github.com/audacity/audacity/assets/50205984/d6c7345f-9592-4b6f-af5a-91bd0bb1da88)

### Actual behavior
![image](https://github.com/audacity/audacity/assets/50205984/d21f4b30-50df-42d9-851d-cb48dd183dc4)

### Audacity Version
3.5.1 and latest alpha master test build for 3.6.0

### Operating system
Windows 10 - but assume all OS

### Additional context
None

**Comment by petersampsonaudacity** [comment]
A smaller EGAT dialog example:
![image](https://github.com/audacity/audacity/assets/50205984/bdf58e6c-b100-4451-a667-2bcf335bf478)

**Comment by LWinterberg** [comment]
> IIRC this issue was discussed in the past

yes, here: https://github.com/audacity/audacity/issues/5158

design is pretty much ready, but not quite a priority to implement. Might only make it to audacity 4.

**Comment by petersampsonaudacity** [comment]
@LWinterberg 

Thanks for that Leo.

It's a shame that we might have to wait till Audacity 4 though ...
