### ISSUE TITLE
Add 'Apply Realtime Effects' Buttons for UX improvement.

### ISSUE THREAD

**Issue by Pete-Lawrence** [audacity/audacity#6734]
### Your idea

# Add 'Apply Realtime Effects' Buttons for UX improvement.
Currently the way to apply realtime effects is really obtuse. You have to navigate to
**Tracks > Mix > Mix & Render (to New Track)**

This simple action of applying realtime effects, I couldn't figure out how to do on my own. **Tracks > Resample** looked promising but wasn't the right choice. [I only found out how by looking it up](https://support.audacityteam.org/audio-editing/using-realtime-effects).

I propose that adding the following two buttons to the bottom of the Realtime Effects sidebar would greatly improve UX.
**Apply Realtime Effects** | **Apply Realtime Effects to New Track**

These would act identically to **Mix & Render (to New Track)** but only affect the selected track. This would make it easier for the user to discover how to perform this basic action on their own.

### Problem to be solved

UX issue

**Comment by LWinterberg** [comment]
Why do you need to apply realtime effects in the first place?

**Comment by Pete-Lawrence** [comment]
There are plenty of reasons but I'll go over a few.
Some plugins in order for them to work add latency.
Some plugins are very CPU heavy.
This is very common when using audio repair tools like iZotope RX plugins.

All these downsides are negated when the FX get applied.

**Comment by LWinterberg** [comment]
yes, I know the theory. What's the specific problem you're running into that requires you to bounce the track?

**Comment by Pete-Lawrence** [comment]
I don't want to go over every use case for the simple action of bouncing audio. It's such a basic task and should be easy to perform right there in the Realtime Effects sidebar without menu diving.

**Comment by petersampsonaudacity** [comment]
> Currently the way to apply realtime effects is really obtuse. You have to navigate to
> **Tracks > Mix > Mix & Render (to New Track)**

@Pete-Lawrence 

What I would do if I was using this a lot would be to create a custom shortcut for the command.

See:  https://manual.audacityteam.org/man/keyboard_preferences.html#custom

**Comment by Pete-Lawrence** [comment]
> @Pete-Lawrence
> 
> What I would do if I was using this a lot would be to create a custom shortcut for the command.

Personalising and configuring shortcuts are for very specialised user-specific cases. Applying realtime effects should be simple to access for every user, right there in the realtime effects sidebar. It shouldn't be down to the user to compromise for bad UX every time they install.

**Comment by LWinterberg** [comment]
We're, for better and worse, not in the business of making "yet another DAW". Our objective is to make something that's simple to use and gets you 80% of the way there, and as such every button we add to the main UI needs to be carefully considered. 

We have decided against adding an "Apply realtime effects" button in the panel as that would cause confusion as to what realtime effects are - it creates a mental image of realtime effects being only a preview, and to actually include it in the project, they need to be applied. Likewise, the industry terms of bouncing, freezing and to a certain extent, rendering, are completely impenetrable by novices and would contribute to a perception of Audacity being scary to use. 

That said, adding the option to the tracks menu and/or track control panel is something we'd like to do, as discussed in https://github.com/audacity/audacity/issues/2418. The tracks menu needs some love in general; I think it's hiding too many options in submenus at the moment..

**Comment by petersampsonaudacity** [comment]
> We have decided against adding an "Apply realtime effects" button in the panel as that would cause confusion as to what realtime effects are - it creates a mental image of realtime effects being only a preview, and to actually include it in the project, they need to be applied. Likewise, the industry terms of bouncing, freezing and to a certain extent, rendering, are completely impenetrable by novices and would contribute to a perception of Audacity being scary to use.

@LWinterberg  and this approach is certainly consistent with long term usage in other parts of Audacity:

1) First example is the used of Pan and Gain sliders in tracks -the Audacity manual makes no suggestion or requirement that the user "bounces" the settings on the track or to a new track with mix&render - all they need to do is export.

2. Second use case is the use of a Time track,  Note carefully that at the end of the "A Tutorial on Time Warping" on this page:
https://manual.audacityteam.org/man/time_tracks.html
There is absolutely no mention of bouncing or mix&render - all is says is:
>To use the speed-changed audio in other applications, choose **File > Export Audio**

![image](https://github.com/audacity/audacity/assets/50205984/f1ba16a1-419e-4934-9121-7900ec33fa1f)

**Comment by petersampsonaudacity** [comment]
> That said, adding the option to the tracks menu and/or track control panel is something we'd like to do, as discussed in #2418. The tracks menu needs some love in general; I think it's hiding too many options in submenus at the moment..

Plus 1 for that

**Comment by LWinterberg** [comment]
Closing in favor of https://github.com/audacity/audacity/issues/2418.
