### ISSUE TITLE
Time Track Range setting would be much better as a single dialog

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#6736]
### Bug description
In the **Range** setting for a Time track (accessed via the tracks Track Control Panel context menu, or its Vertical Scale context menu)  the user is presented with not one but two similar dialogs presented one after the other with very similar input.  One for **Lower speed limit**, the other for **Upper speed limit**.

It would be much better if these were consolidated  into a single dialog, as is the case elsewhere in Audacity, giving consistency.

### Steps to reproduce
1. Tracks > Add New > Time Track
2. right click on the track name
3. in the context menu select range
4. Observe: two similar dialogs, one after the other

### Expected behavior
![image](https://github.com/audacity/audacity/assets/50205984/acb3fc8a-f715-4635-96d3-e7552949a4e1)

Apart from any other consideration it would be jolly useful to see both limits together.

### Actual behavior
![image](https://github.com/audacity/audacity/assets/50205984/6a50eca2-e1ac-4f9f-8810-885f8569e968)

followed by

![image](https://github.com/audacity/audacity/assets/50205984/05b8704c-2b49-41e3-bd7c-dc1e003e63fb)

### Audacity Version
3.5.1 (and earlier Audacity versions) - and the latest alpha master test build for 3.6.0

### Operating system
Windows 10, but assume all OS

### Additional context
A single dialog would not only be neater and more consistent - it would involve fewer clicks and thus a boon for RSI sufferers.

**Comment by nalin243** [comment]
@petersampsonaudacity 
@LWinterberg 

It seems the reason it was done this way is because the minimum value of the upper limit must always be one greater than the current lower limit.

![dialog](https://github.com/user-attachments/assets/43b37ddf-ec62-41b8-a9ef-e728c14ad8e6)

I was able to create a dialog just fine, but now if the lower limit is greater than the upper limit then it just silently fails. Should there be an error message that pops up and if so what should be it's contents?

**Comment by petersampsonaudacity** [comment]
@nalin243 
well what is does now with the two dialogs is that if you try to set a value for  the upper limit that is less than the lower limit, then it silently changes the upper limit to the lower limit plus 1, with no error message or warning shown to the user.

But yes, I would have thought that if you try to set an invalid limit  then there should be an error message and the action should be blocked.  

And note that yo may also try to change the lower limit to be higher than the upper limit (as well as the other way around).  However that may be seen as correct behavior as the user may want to make both limits much higher (or lower.  So any error message should probably not be triggered by changing either of the limits - but should be triggered by the user pressing the OK button when invalid limits are in place in the input fields.

As fir the content of the error message I would suggest
>Upper Speed Limit must be greater than the Lower Speed Limit

_And note that you are using non (audacity) standard OK and Cancel buttons - and non-standard increment/decrement in your mock-up above._

**Comment by nalin243** [comment]
@petersampsonaudacity 

> So any error message should probably not be triggered by changing either of the limits - but should be triggered by the user pressing the OK button when invalid limits are in place in the input fields.

That is what I was going to do anyways so that is fine. What should be the heading for the message?

> And note that you are using non (audacity) standard OK and Cancel buttons - and non-standard increment/decrement in your mock-up above.

This is how the previous dialog appeared to me as well. Might be a desktop environment and os thing.

**Comment by petersampsonaudacity** [comment]
> What should be the heading for the message?

How about
>**Invalid limits**

Texts will be easy to change later if Leo (@LWinterberg) doesn't like the text of this or the message itself.

**Comment by nalin243** [comment]
@petersampsonaudacity 

I blocked the user from applying the invalid limits. If the limits are invalid the range will remain the same with the last known valid values. 

If you could test this in a windows machine that would be great!

**Comment by petersampsonaudacity** [comment]
@nalin243 

I tested this on you latest branch:  

I get your new single dialog:
![image](https://github.com/user-attachments/assets/48a5e192-4492-4f7d-bcf1-aafc11eef28f)

But when I tried leaving the lower limit at 20 and setting the upper limit to a value below that, when I next invoke Range in the Time Track TCP dropdown menu I observe that the upper limit has been changed _(silently, with no warning to the user)_ to 21.

I get no error message or warning.

**Comment by petersampsonaudacity** [comment]
@nalin243 

But then I tried setting both limits to 100
and then I got the error message
![image](https://github.com/user-attachments/assets/f3125c31-ba9c-434b-8b1e-732dc0b53808)

It appears that if you set values of 10 or less then you get no error message but Audacity then (silently) sets a pair of values for you.

**Comment by petersampsonaudacity** [comment]
@nalin243 

You could simplify the error message and thus make it more readable and comprehensible, as
>**Upper Speed Limit must be grater than the Lower Speed Limit**

**Comment by petersampsonaudacity** [comment]
@LWinterberg 

What are your thoughts on all this, please?

**Comment by nalin243** [comment]
@petersampsonaudacity  @dozzzzer @LWinterberg 

> BUT I do note that this is the same as existing 3.6 behavior with the two dialogs where a range between 10% and 1000% is silently enforced.

Those are the minimum and maximum possible values for both the limits and I did not change that.

> It appears that if you set values of 10 or less then you get no error message but Audacity then (silently) sets a pair of values for you.

I figured out that this was happening because in the previous system when the upper limit dialog always came after the lower limit one we could enforce that the minimum value for upper limit must never be less than the currently set lower limit. Now that we have both in a single dialog that is no longer enforceable. The issue is fixed if I set the minimum possible value of the upper limit to be 10, just like the lower limit. 

I am committing the above for now along with the error message changes.

**Comment by petersampsonaudacity** [comment]
Tested on W10 with @nalin243 's latest test branch for this:

a)  The dialog box now has normal Audacity buttons/controls:
![image](https://github.com/user-attachments/assets/b3273875-2667-47aa-99cd-4123cfcd39f4)


b) The error message is much improved:
![image](https://github.com/user-attachments/assets/b28381bd-d461-4fd8-890e-1ca74007420a)

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @nalin243 's latest branch build for this:   audacity-win-3.6.2-alpha-20240724+ec2e1f3-x64

Now, after I dismiss the error dialog the "Change Speed Limits" dialog is re-displayed.

It disappears while the error message is displayed - I would prefer it if it remained visible (but inaccessible) while the error message is displayed, as then the user could move the message to observe the incorrect entries in the dialog - but I can live with it the way it is now, if need be.

**Comment by petersampsonaudacity** [comment]
@nalin243   many thanks for your work on this.  This is now in the 3.6.2 latest Beta test build.

This is mucch better I think, as it enables the user to see bith values at the same time.

I updated the Manual's page for Time Track with the new consolidated dialog.
