### ISSUE TITLE
TCP UI Breaks when dragging waveform splitter

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#6751]
### Bug description

If the User creates a stereo track and collapses it, then choosing to adjust the waveform via the waveform splitter, the TCP track menu UI will break.

### Steps to reproduce

1. Create Stereo Track
2. Add some audio
3. Collapse the track
4. Try to drag the waveform splitter
5. Observe result	

### Expected behavior

User should be able to use the waveform splitter to change the view of a stereo tracks' waveform

### Actual behavior

https://github.com/audacity/audacity/assets/139755141/0efa85f4-f0c5-4e05-b40d-27a50e01259e

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

**Comment by petersampsonaudacity** [comment]
Testing on W10 shows that this is a regression on 3.5.1

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @saintmatthieu 's branch build for this.

This now appears to work properly in Matthieu's branch build - attempting to drag the waveform splitter:
a) does not change the collapsed waveform - _this is expected behavior_
b) the collapsed TCP remains properly displayed

**Comment by chinakov** [comment]
Tested, thanks!
