### ISSUE TITLE
Black dots on TCP buttons

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#6752]
<img width="239" alt="image" src="https://github.com/audacity/audacity/assets/70063970/b9256a58-2059-494f-b372-24e0b073e42d">

TCP buttons - Delete track, Collapse track, Open Menu - have black dots on hover.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with latest alpha master:  audacity-win-3.6.0-alpha-20240625+8ea57fc-x64-msvc2022

I see this with the Open menu:
![image](https://github.com/audacity/audacity/assets/50205984/55b7d49b-9436-458b-a2dd-e9e963577e77)


But NOT with Collapse/Expand or Delete
![image](https://github.com/audacity/audacity/assets/50205984/f1c2fa56-04c8-4bc1-97f5-c830f5b04760)

![image](https://github.com/audacity/audacity/assets/50205984/c497996c-c2c6-458a-8ea7-3ea3d7b7de20)

**Comment by petersampsonaudacity** [comment]
This is NOT a regression, the same happened in 3.5.1 and earlier:
![image](https://github.com/audacity/audacity/assets/50205984/6bfb58d2-bf81-48ed-8461-f65d3b3673ab)

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @vsverchinsky 's test branch build for this.

This seems to work properly in Vitaly's branch build. 

I see no more black dots/framing around the TCP buttons for the X (delete), the chevron (collapse/expand) and the ellipsis (menu)

**Comment by dozzzzer** [comment]
Tested
