### ISSUE TITLE
Advanced vertical zoom config not visible

### ISSUE THREAD

**Issue by micsthepick** [audacity/audacity#6755]
### Bug description

Advanced vertical zooming is not configurable in preferences

### Steps to reproduce

Edit
Preferences
Tracks

### Expected behavior

Can see advanced vertical zoom config

### Actual behavior

Missing?

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Other

### Additional context

All tested systems have the same behaviour on current release

**Comment by LWinterberg** [comment]
The preference has been removed

**Comment by micsthepick** [comment]
for further discussion, please see #6755
