### ISSUE TITLE
[AU4] Track - Moving tracks

### ISSUE THREAD

**Issue by DilsonsPickles** [audacity/audacity#6759]
The ability to move tracks up and down in the list of tracks.

[Figma Link](https://www.figma.com/design/k5rS9tnZl60nYmhJhvI2vf/Track-headers?node-id=272-19038)

**Comment by chinakov** [comment]
Tested, thanks!

Re-ording with mouse dragging will be implemented in a separate task: https://github.com/audacity/audacity/issues/7656
