### ISSUE TITLE
[AU4] Track header - Renaming a track

### ISSUE THREAD

**Issue by DilsonsPickles** [audacity/audacity#6760]
[Figma Link](https://www.figma.com/design/k5rS9tnZl60nYmhJhvI2vf/Track-headers?node-id=274-34795)

**Comment by dozzzzer** [comment]
@kryksyh 

1. Upon entering a new name, if you click away or press Esc, the new name should be saved. Currently, it reverts to the previous name.


https://github.com/user-attachments/assets/db7d8eba-11d3-4203-a63c-3e6e29c6ed5d


2. When text is selected, pressing `↑`, `↓` as well as `Shift + ↑`, `Shift + ↓` doesn't work as expected: it simply quits the Edit mode instead.

**Comment by DilsonsPickles** [comment]
@dozzzzer I tested the build this morning and would like ESC to cancel the operation. All other actions however should confirm the name change. Agreed, we are missing the selection/cursor placement shortcuts.

**Comment by kryksyh** [comment]
@dozzzzer I've created a separate task regarding arrow keys

**Comment by dozzzzer** [comment]
Tested
