### ISSUE TITLE
Ability to export labels as chapter tags in the metadata of the audio files

### ISSUE THREAD

**Issue by Piciok** [audacity/audacity#678]
**Is your feature request related to a problem? Please describe.**
I would like to mark chapters in the Podcast episodes I produce and, although Audacity allows for labeling individual parts of an audio file, those labels cannot be integrated as metadata into the files.

**Describe the solution you'd like**
I would like Audacity to be able to save the labels I create for an audio file in their metadata so that other players can read them as Podcast chapters. specification exists for doing that in mp3, ogg, m4a and I believe flac.

**Describe alternatives you've considered**
I tried to use a Python script written by another developer that parses txt files written in a certain way and includes the chapters in an indicated file. unfortunately, after exporting the labels in Audacity, the resulting file requires heavy, manual modification in order to work with the script.

**Additional context**
Especially in longer pieces of audio such as Podcasts, it is good to include some kind of structure that makes it easier for the listener to navigate around the different parts, choosing those of interest and discarding the rest. Currently under Windows especially, there is no easy way of including these chapters. The only solutions I've found so far are either scripts that require a lot of manual input and knowledge on how to run them, commercial products or web platforms that in my case either did not work or require a premium account. The Audacity track labeling feature looks like a potentially good interface for such an enhancement, except it doesn't save the labels into the metadata of the resulting file at the moment.

**Comment by LWinterberg** [comment]
ID3 spec on chapters: https://id3.org/id3v2-chapters-1.0

Related (but different): 
* #2587 - Markers in WAV files

**Comment by LWinterberg** [comment]
Improving metadata handling is not planned for the moment, closing for now. There may be a bigger metadata release eventually, follow #1464 for that.
