### ISSUE TITLE
Rescan Audio Devices in the Transport menu is redundant as it duplicates the Audio Setup toolbar

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#6785]
### Bug description
Rescan Audio Devices in the Transport menu is redundant as it duplicates the Audio Setup toolbar.

Users really don't need two different routes to achieve a rescan - and removing this from the View menu would help to reduce manu bloat.

Apart from any other consideration Rescan is not really a Transport type action - and it seems much more appropriate in the Audio Setup toolbar

### Steps to reproduce
1. launch Audacity
2. Click on the Audio Setup toolbar/button
3. Observe: command for Rescan Audio Devices
4. Click on the Transport menu
5. Observe: another command, a duplicate, for Rescan Audio Devices

### Expected behavior
![image](https://github.com/audacity/audacity/assets/50205984/c790536b-fced-4456-a12d-06cd38d384e1)

![image](https://github.com/audacity/audacity/assets/50205984/0de2dab3-828d-43e2-99e8-03ca2c146355)

### Actual behavior
![image](https://github.com/audacity/audacity/assets/50205984/29fede14-e6eb-4e1b-b08e-d0653b1e9ee5)

### Audacity Version
3.5.1 and earlier - and latest alpha master 3.6.0

### Operating system
Windows 10 - but assume all OS

### Additional context
@LWinterberg  I will add this to your Cleanup superbug

**Comment by LWinterberg** [comment]
Most of the transport menu is redundant with the transport toolbar. It's likely going to be removed entirely in the Qt version at some point, but I don't think I'll remove it separately.
