### ISSUE TITLE
Change the text of "missing FFMPEG" message

### ISSUE THREAD

**Issue by rado84-github** [audacity/audacity#6794]
### Your idea

A recent update of ffmpeg uninstalled ffmpeg4.4 after which Audacity stopped working properly and kept telling me to install FFMPEG. But since that package is installed, that apparently wasn't true. With a command (in Arch) that lists all dependencies and then search the repo for ffmpeg, I discovered that Audacity actually uses FFMPEG4.4, not the other FFMPEG (without a version in its name). So, when ffmpeg4.4 is missing, it displays an error saying "Try installing FFMPEG".
Obviously this is something I'll have to report to the devs of ffmpeg but in case they refuse to do what I'll ask them to do, it would be better for us to know clearly what's missing.

### Problem to be solved

Simply change the message to specify: "Try installing ffmpeg4.4". This will accurately tell the user what's missing and save us the trouble of investigating why this message appears.

**Comment by LWinterberg** [comment]
The normal ffmpeg works too, except for when they release a new version which breaks compatibility as has happened recently. This will be fixed in 3.6.
