### ISSUE TITLE
Crash report from Audacity 3.5.1 (Windows, 64-bit)

### ISSUE THREAD

**Issue by KNTRO** [audacity/audacity#6795]
### Bug description

This is the log from a crash that could not be sent.

### Steps to reproduce

It's tricky to reproduce. It happened when Audacity tried to compact a project with a file size of around 4 GB.

### Expected behavior

Audacity should compact and save the project without any crash.

### Actual behavior

Audacity was unable to compact and save the project, first. When it crashed and shown the crash log, it wasn't able to send the report, then.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

### Additional context

[Audacity_Problem_Report.txt](https://github.com/user-attachments/files/16060593/Audacity_Problem_Report.txt)

**Comment by KNTRO** [comment]
Two more crash reports, generated under very similar scenarios.

[Audacity_Problem_Report_2.txt](https://github.com/user-attachments/files/16060608/Audacity_Problem_Report_2.txt)
[Audacity_Problem_Report_3.txt](https://github.com/user-attachments/files/16060609/Audacity_Problem_Report_3.txt)

**Comment by KNTRO** [comment]
**Steps to reproduce**

Something I could add about it. I think it happens in this manner:
1. Open or import an audio file.
2. Export it to FLAC and then export it to Opus.
3. Try saving the project now — The Audacity title bar will blink several times, and then Audacity will crash. The crash reporter will appear, but it will be unable to send the report.

At least, it happened with 44.1 or 48 kHz, stereo audio files with a duration of around 2 hours, or more. I don't know if these crashes are related to either RAM usage or drive space. My computer has 8 GB of RAM and I can remember that Audacity even crashed being the only program running. Drive space? Several TBs, spread in different drives, so it's not a drive-related issue either.

I don't know what else to say. 🤷

**Comment by LWinterberg** [comment]
Same issue as many others are having - we'll enable debugging of crash reports next time so we can figure out what's going wrong there.
