### ISSUE TITLE
Ability to drag&drop .txt label files

### ISSUE THREAD

**Issue by ghost** [audacity/audacity#680]
**Is your feature request related to a problem? Please describe.**
Drag&drop importing works intuitively for most supported file formats besides label files. Currently, a label file (.txt) will import fine using File -> Import -> Labels...  However, trying to drag&drop the same file into the editor will throw the "Audacity did not recognize the type of the file ..." error.

**Describe the solution you'd like**
Attempting to import .txt files as label files by default, only throwing the error if it fails.

**Describe alternatives you've considered**
I am new to the Audacity editor, so I am not entirely sure how .txt files are being used for other purposes in others workflows. If it proves to be a big hassle, the alternative is to go File -> Import -> Labels or assign a keyboard shortcut (which prompts a File Browser UI).

**Comment by petersampsonaudacity** [comment]
This sounds like a reasonable request for consistency - given that audio files can be exported and then imported by drag&drop it seems a reasonable exception to be able to do the same with external label files.  

I will raise an enhancement request for this on our Bugzilla bug-tracker.

Testing D&D of a label text file on W10 show that currently we have a less than helpful error message if you attempt this.

As you say the workaround is to use File > Import > Labels...

**Comment by petersampsonaudacity** [comment]
Logged as P3 ENH 2568
https://bugzilla.audacityteam.org/show_bug.cgi?id=2568

Thanks for the suggestion donbecki-neosensory

**Comment by petersampsonaudacity** [comment]
If you are wanting to import label text files a lot, you may want to set up a custom keyboard shortcut for Import Labels.

See: https://manual.audacityteam.org/man/keyboard_preferences.html

**Comment by AnitaBats** [comment]
Hi! 
During the grooming today we discussed this and team agreed that this is something we think is unnecessary

**Comment by LWinterberg** [comment]
(specifically, when a user selects import > label, it's clear to both the program and to them that they're now looking for a label file to import. However, with drag and drop, it no longer is clear whether the user even is aware of what a label file is)
