### ISSUE TITLE
Add Audacity's v3.5 UI dark theme to the Audacity v3.6 branch

### ISSUE THREAD

**Issue by deus-e-x** [audacity/audacity#6802]
### Your idea

The current Audacity development branch v3.6/3.7 replaced the previous UI dark theme of the v3.5 branch (orange/brown colors) with a grey-blue color UI dark theme.

1. Could you please add the v3.5 dark theme as an additional config choice?
2. Would you happen to have plans to add UI color configuration to Audacity?

### Problem to be solved

Add more variety to the user's choice of UI theming, and preserve a well-established UI theme for users who like to continue using it.

### Prior art

Screenshot of the Audacity v3.5 UI dark theme:

![01a](https://github.com/audacity/audacity/assets/45689656/9e36894b-797d-461c-93ab-b5d1c9876c08)

**Comment by LWinterberg** [comment]
the old dark and classic themes will remain available as custom themes at https://github.com/LWinterberg/classicTheme, but will no longer be part of the main repo.

**Comment by deus-e-x** [comment]
The steps required to create a custom theme are too complex, going way over the perspective of a casual end-user.

However, the instructions mention experimental theming options, that are disabled by default, allowing the export of the current theme and saving it to the file ImageCache.png.

![image](https://github.com/audacity/audacity/assets/45689656/6763ff4b-36ae-4abc-b241-e2b46d68231b)

Could you make a Windows binary with this option enabled available for download? This would ease the process from an end-user perspective tremendously.
