### ISSUE TITLE
[AU4] Track panel header - Volume slider  UI

### ISSUE THREAD

**Issue by DilsonsPickles** [audacity/audacity#6805]
Spec for logarithmic volume slider with tooltip

[Figma Link](https://www.figma.com/design/k5rS9tnZl60nYmhJhvI2vf/Track-headers?node-id=377-72837&t=nz14mBwwMmTHXTt2-4)

**Comment by dozzzzer** [comment]
The tooltip reads "-60dB" when the slider is at its minimum, whereas it should be "-∞dB"

<img width="313" alt="image" src="https://github.com/user-attachments/assets/ddb3452d-5f10-4bb7-af2f-3ad561dafe12">

**Comment by kryksyh** [comment]
@dozzzzer 1. We decided to go with -60 instead of -inf. @DilsonsPickles please confirm

**Comment by DilsonsPickles** [comment]
@kryksyh I don't wholly remember but that sounds reasonable to me. Leo or Martin are likely to have been the ones to suggest that.

**Comment by dozzzzer** [comment]
@kryksyh see item no.2 fro my prev comment, it remains not fixed

**Comment by kryksyh** [comment]
@dozzzzer yep, I will get back to it once I'll finish with cloud auth for au3
