### ISSUE TITLE
Audacity fails to load FFmpeg

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#6809]
### Bug description

If the User has configured FFmpeg correctly in previous Audacity versions (3.5.1or older),  and has installed the newest version of Audacity (3.6 release candidate), the User will be shown an unwarranted 'FFmpeg was configured in Preferences successffully loaded before, but this time Audacity failed to load it at startup'.  

![image](https://github.com/audacity/audacity/assets/139755141/dae9a64c-5048-442d-8776-f17c14b43ab8)

If the User then manually locates the '.dll' file, Audacity still won't be able to locate the FFmpeg file. If Audacity is restarted, the library is still not located. 

Clearing preferences and local data, reinstalling FFmpeg does not solve the issue. 

### Steps to reproduce

1. Install the newest 3.6.0 release candidate
2. Open Audacity
3. Observe unwarranted 'FFmpeg startup failed' error message
4. Navigate to Preferences -> Libraries
5. Locate FFmpeg
6. Observe Result

### Expected behavior

FFmpeg should be avialable after the User has located the correct file upon restart.

### Actual behavior

The FFmpeg library is not avialable if the User has located the correct library file upon restart.

### Audacity Version

other

### Operating system

Windows

### Additional context

This is only reproducible on 3.6.0 release candidate build. Not reproducible on latest Master build of Audacity. This is a regression from 3.5.1 version.

**Comment by vsverchinsky** [comment]
Which version of FFmpeg are you trying to load?

**Comment by chinakov** [comment]
@vsverchinsky 

![Image](https://github.com/audacity/audacity/assets/139755141/e4e097cb-b877-44b4-be8b-b22518d95dc1)

**Comment by chinakov** [comment]
Closing this task as the issue was solved for me - I had the x86 build installed. Many apologies!
