### ISSUE TITLE
Too many placeholders in strings making it harder to translate

### ISSUE THREAD

**Issue by scootergrisen** [audacity/audacity#681]
I don't like this way the following string was changed from a single string:

    Audacity is a free program written by a worldwide team of [[https://www.audacityteam.org/about/credits|volunteers]]. Audacity is [[https://www.audacityteam.org/download|available]] for Windows, Mac, and GNU/Linux (and other Unix-like systems).

To multiple strings using %s placeholders:

    %s is a free program written by a worldwide team of %s. %s is %s for Windows, Mac, and GNU/Linux (and other Unix-like systems).
    volunteers
    available

It makes it harder to read the string for translators and having to read comments about which strings go where which was unnessasary before.

Maybe something like this is better:

    %s is a free program written by a worldwide team of [[%s|volunteers]]. %s is [[%s|available]] for Windows, Mac, and GNU/Linux (and other Unix-like systems).

There is still the disadvantage that using %s for all the placeholders seems to give the translator no way to decide which order they go in which may or may not be wanted in some languages.

https://github.com/audacity/audacity/blob/master/src/AboutDialog.cpp#L332-L333

Same goes for the string:

    If you find a bug or have a suggestion for us, please write, in English, to our [[https://forum.audacityteam.org/|forum]]. For help, view the tips and tricks on our [[https://wiki.audacityteam.org/|wiki]] or visit our [[https://forum.audacityteam.org/|forum]].

That was changed to:

    If you find a bug or have a suggestion for us, please write, in English, to our %s. For help, view the tips and tricks on our %s or visit our %s.
    forum
    wiki
    forum

https://github.com/audacity/audacity/blob/master/src/AboutDialog.cpp#L350-L351

**Comment by petersampsonaudacity** [comment]
This needs changing anyway as Audacity is no longer "written by a worldwide team of volunteers", so this is no longer true.

Audacity is now written by a professional team of developers and others employed by Muse, with occasional contributions from external volunteers.
