### ISSUE TITLE
Crash when dragging an imported stereo clip of a different sample rate onto an empty track

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#6810]
### Steps to reproduce

1. Launch Audacity
2. Set the Project Rate (if needed) to 44.1 kHz
3. File > Open/Import > select a stereo track (e.g. [this one](https://drive.google.com/file/d/1meMYAv8JcM3P3PKv9MRipUgcFMdjcgBL/view?usp=sharing)) of a sample rate different than 44.1 kHz
4. Create a stereo track
5. Drag the clip from Track 1 to Track 2

### Expected behavior

No crash

### Actual behavior

A crash.

https://github.com/audacity/audacity/assets/70063970/0da78e1a-825f-4fe5-8efc-3903699ff099

### Audacity Version

[other](https://github.com/audacity/audacity/actions/runs/9767011107)

### Operating system

Windows, macOS

### Additional Context

If you change the track's rate to 44.1 kHz after import and then drag it onto another track, Audacity doesn't crash.

**Comment by dozzzzer** [comment]
Sentry log: https://sentry.audacityteam.org/share/issue/32288e03ea564fe18e5e71bdd60022c4/

**Comment by DavidBailes** [comment]
@dozzzzer Surely this needs to be fixed for 3.6.0, rather than 3.6.1?

**Comment by DavidBailes** [comment]
Alternative steps to reproduce:
1. Resample a stereo track.

**Comment by dozzzzer** [comment]
Tested
