### ISSUE TITLE
Track control panel: wrong button icons when track is expanded in dark and High Contrast themes

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#6815]
### Bug description

For the dark and high contrast themes, the expand icon is shown when the track is expanded.

### Steps to reproduce

1. Switch to Dark or High contrast theme
2. Create an audio track.
3. Look at the icon on the button for collapse/expand

### Expected behavior

When the track is expanded, the collapse icon shown be shown.

### Actual behavior

When the track is expanded, the expand icon is shown:
![image](https://github.com/audacity/audacity/assets/11887021/088127e4-004f-4bf8-8464-61b18426d06c)

![image](https://github.com/audacity/audacity/assets/11887021/713813d5-d887-4ea8-9954-190f04de5781)

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

**Comment by petersampsonaudacity** [comment]
This is a regression on 3.5.1 and earlier

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @nalin243 's latest branch build for this:  audacity-win-3.7.0-alpha-20240708+0b1a329-x64
_(and note the Mac builds for this failed to work)._

This now appears to work properly in this branch build with the correct icons now showing for collapse and expand in the TCP's of tracks for both Dark and High Contrast themes.

I tested>
1. stereo track
2. mono track
3. label track
4. time track

I tested these individually and with the **View > Track Size** commands for **Collapse** and **Expand**

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @nalin243 's latest branch build for this:  audacity-win-3.6.0-alpha-20240708+37df314-x64
_(and note the Mac builds for this failed to work)._

This now appears to work properly in this branch build with the correct icons now showing for collapse and expand in the TCP's of tracks for both Dark and High Contrast themes.

I tested>
1. stereo track
2. mono track
3. label track
4. time track

I tested these individually and with the **View > Track Size** commands for **Collapse** and **Expand**

_For completeness I also tested in Light and Classic themes - and these remain OK._


===============================================================

Now this test branch properly declares itself to be **3.6.0 alpha**

**Comment by dozzzzer** [comment]
Tested
