### ISSUE TITLE
Effect preview dialogue box doesn't disappear after playback

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#6818]
### Steps to reproduce

1. Grab some audio and make a selection
2. Open up any effect (e.g. Amplify) from the main Effect menu
3. Click Preview
4. Observe

### Expected behavior

As soon as the preview playback is finished, the dialogue closes.

### Actual behavior

Effect preview dialogue box doesn't close automatically and remains open after playback:

https://github.com/audacity/audacity/assets/70063970/0e3864bc-0893-491f-b81d-8da5fe938318

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

**Comment by petersampsonaudacity** [comment]
This is a regression on 3.5.1 and a;; earlier Audacity

**Comment by DavidBailes** [comment]
@LWinterberg @dozzzzer 
This issue is just one example of playback not automatically stopping when it should. Other examples of where this occurs include:
On the Transport menu:
    Play Once (shift + spacebar)
On Extra > Transport sub menu:
    Play one second (1)
    Play to selection (B)
    Play before selection start (Shift + F5), and all the similar commands to this

I think this needs fixing for 3.6.0.

**Comment by petersampsonaudacity** [comment]
>On the Transport menu:
Play Once (shift + spacebar)
On Extra > Transport sub menu:
Play one second (1)
Play to selection (B)
Play before selection start (Shift + F5), and all the similar commands to this

Testing on W10 with the latest 3.6.0 Beta I cannot reproduce what @DavidBailes reports

The playback for those (and related commands) stops where I expect it to stop

**Comment by dozzzzer** [comment]
@petersampsonaudacity I think what David means here is that the _display_ of the playback, rather than the sound of the playback, doesn't stop when it should.

**Comment by DavidBailes** [comment]
At the end of playback for the commands that I gave, Audacity remains in playback mode - it doesn't automatically stop. This is an example of Audacity after the play once command - note, for example, the status bar:

![image](https://github.com/audacity/audacity/assets/11887021/992fe280-dc55-4d11-a57c-d22687c4ce3a)

**Comment by dozzzzer** [comment]
Tested
