### ISSUE TITLE
Artist tag missing on M4A exports

### ISSUE THREAD

**Issue by timg7** [audacity/audacity#682]
Whenever exporting as M4A the Artist tag is missing from the exported file.
Other file formats are unaffected (MP3, OGG, FLAC...).
Tested with Audacity 2.4.1 and 2.4.2 on Windows 10 and MacOS 10.15.7.

**Comment by petersampsonaudacity** [comment]
Yes you are right - I tested on W10 with 2.4.2 and the latest alpha build I have for the upcoming 3.0.0 - I will be logging this on our Bugzilla bug-tracker

**Comment by timg7** [comment]
Hi Peter, Thanks for the confirmation. -Tim

**Comment by petersampsonaudacity** [comment]
Logged as P3 Bug 2564
https://bugzilla.audacityteam.org/show_bug.cgi?id=2564

And note the Year tag is also not exported.

But this looks like an old bug:
https://bugzilla.audacityteam.org/show_bug.cgi?id=1146
Artist and Year metadata is not exported or imported in FFmpeg 2.2.2
which we closed 2 year ago as WONTFIX (actually CANTFIX as it's an FFmpeg bug)

**Comment by petersampsonaudacity** [comment]
P3 Bug 2564  https://bugzilla.audacityteam.org/show_bug.cgi?id=2564

Was marked as RESOLVED FIXED on 27Jan21

Leland made the fix and I did the QA testing.
