### ISSUE TITLE
[AU4] Clips - Redistributing stereo channel height

### ISSUE THREAD

**Issue by DilsonsPickles** [audacity/audacity#6821]
Vertically resizing clips. Stereo lanes have special behaviour.

[Figma link](https://www.figma.com/design/01XLIICmy2AG6t1ieyTp66/Clips?node-id=521-68071)

**Comment by DilsonsPickles** [comment]
Hey @kryksyh, 

I've updated the spec to include some styling notes. Please see [this row](https://www.figma.com/design/01XLIICmy2AG6t1ieyTp66/Clips?node-id=1350-6699&t=kqs5Dz0hn5EYPp9I-4) of the design spec for styles.

Also, could you please tell me what percentage of white-color is being used for the 2px track spacer?

**Comment by kryksyh** [comment]
@DilsonsPickles track spacer is FFFFFF @ 10%
