### ISSUE TITLE
Audio device list not refreshing without restart

### ISSUE THREAD

**Issue by rahulserver** [audacity/audacity#683]
**Describe the bug**
When I add a new device (bluetooth headphones) to my system(OSX catalina) while audacity is running(even in background), it does not appear in list of the available audio output dropdown.

**To Reproduce**
1. Start audacity. 
2. Then connect bluetooth headphones
3. Try to record a track
4. On audio output dropdown, the device does not appear. 
5. If we even disconnect and reconnect the output device(while audacity is running), on trying to play through it, it shows the error "Error opening sound device. Try changing audio host, playback device and the project sample rate"
6. The device is able to play only after restarting audacity.(quit and start again)

**Expected behavior**
It should either have a button to manually refresh audio output devices or should refresh properly automatically. (Atleast a button can do if auto refresh is too complicated to implement)

**Screenshots**
![image](https://user-images.githubusercontent.com/5101740/95668289-baf85d80-0b8f-11eb-8afa-8d432aba5648.png)

**Additional information (please complete the following information):**
 - OS: MAC Catalina
 - Version Audacity 2.4.2
 - (if relevant) Sound Device Samsung Level U (bluetooth headphone)

**Comment by rahulserver** [comment]
Just tested. Same issue with wired headphones too.

**Comment by SteveDaulton** [comment]
"Rescan Audio Devices" (in the "Transport" menu)
https://manual.audacityteam.org/man/transport_menu.html

For future issues, please write to the help forum in the first instance: https://forum.audacityteam.org
