### ISSUE TITLE
We need to talk about Audacity's Effects menu

### ISSUE THREAD

**Issue by kaixoo** [audacity/audacity#6830]
### Your idea

![imatge](https://github.com/audacity/audacity/assets/174825714/98062fb0-2799-42a2-919d-8cdb8b9c575d)

In older versions, the Effects menu had all of its effects vertically displayed which wasted a lot of space and hide the main view of the program. Recently, this menu was redesigned to occupy less space. Now all effects are contained in a submenu called "Audacity".

![imatge](https://github.com/audacity/audacity/assets/174825714/85f50adf-0e8b-47ff-94d7-559f2af3d770)

I guess that this was made to allow for external effects to show up, but this solution is bad. Every time I need to apply any effect, which is a lot, I need to go into this menu, click, scroll down, wait a few ms, and then look for the effect.

### Problem to be solved

![imatge](https://github.com/audacity/audacity/assets/174825714/aa4a48c2-18a6-4d4d-a631-ca5ca39b2a6b)

Some have suggested organizing them by categories. This used to be the case a few versions prior, but the team discarted it because external effects developers didn't put a section to them.

1. Categorize effects by categories.
   - Force new extensions to choose a category for their effects. (and drop older-than-x-version extensions in an 'old-extra' category)
   OR:
   - Allow the user to intuitively put effects in the category they wish, or create new categories.
4. Rollback to old Effects menu with all wasted vertical space.
   - Put an "Extra:" submenu with all community effects.

### Additional context

If the older menus were bad, this is worse. It being contained inside a submenu isn't justified because of the extra time needed to look for the effect. Organizing by extensions and not by category doesn't make much sense either. An extension can have any number of very different-purpose effects. Then you have amplify-related effects in 3 different categories.

**Comment by LWinterberg** [comment]
You can set the ordering and grouping of effects in Preferences -> Effects.

**Comment by kaixoo** [comment]
> You can set the ordering and grouping of effects in Preferences -> Effects.

How are new users supposed to discover that without having to google, look into the forums, create a github account, add an issue...? Perhaps an "Effects settings" button could be added at the bottom?

```
-- Effects --
    - Audacity -> ...
    - Ksyplugin -> ...
    ---
    - Effects settings
```
