### ISSUE TITLE
Apple Silicon Support

### ISSUE THREAD

**Issue by ThatGuySam** [audacity/audacity#684]
With Apple possibly dropping the first Apple Silicon powered Mac as early as November what's the status of Audacity support for ARM-based Macs?

From what I've seen on other OSS projects they are basically ready to go and there's not much work needed to support it: 
[Handbrake Support](https://doesitarm.com/app/handbrake/)
[OBS Support](https://doesitarm.com/app/obs/)
[Blender Support](https://doesitarm.com/app/blender/) (Was directly mentioned in the Apple presentation)

**Additional context**
I'm putting together a list of reported support for Apple Silicon so people can quickly see if their favorite apps are supported yet.

**Comment by SteveDaulton** [comment]
It is known that Audacity can be built on Raspberry Pi.
You are welcome to try building Audacity on an ARM-based Mac if you have access to one - let us know how you get on.

**Comment by ThatGuySam** [comment]
That's good news. I usually work in Node JS environments but I can try doing a build. 

Are there any recommended resources/wiki articles for correctly running builds?

**Comment by SteveDaulton** [comment]
Here: https://github.com/audacity/audacity/blob/master/mac/cmake_build.txt

**Comment by ThatGuySam** [comment]
I've got the build environment setup after some troubleshooting and I'm trying to get Xcode's Universal Build working (Hopefully, that's an appropriate approach)

I can, however, confirm that the public 2.4.2 build works out of the box (because of Rosetta 2) on macOS Big Sur running on physical Apple Silicon with seemingly no issues.

**Comment by petersampsonaudacity** [comment]
Thanks for that useful feedback ThatGuySam - I'll close this off on the basis of your report

**Comment by EwoutH** [comment]
[CMake 3.19](https://cmake.org/cmake/help/v3.19/release/3.19.html) combined with [Xcode 12.2](https://developer.apple.com/documentation/xcode-release-notes/xcode-12_2-release-notes) should make universal binaries pretty easy. Both will be included soon in the macOS environment of GitHub Actions, CMake on the next release and Xcode 12.2 is already included, but will be the default on [November 30th](https://github.com/actions/virtual-environments/issues/2056).

**Comment by petersampsonaudacity** [comment]
Thanks for the update EwoutH

**Comment by nathancahill** [comment]
Looks like GitHub Actions is updated with the lastest XCode to allow this to be built! Exciting.

**Comment by EwoutH** [comment]
Unblocked the Xcode version in this PR: #814

**Comment by Wolfos** [comment]
Why was this issue closed? This will definitely have to be picked up at some point.

**Comment by MultifokalHirn** [comment]
> Unblocked the Xcode version in this PR: #814

but maintainers still didn't want to make this change..? @EwoutH

**Comment by floam** [comment]
What is the dealio? What is the big problem?
