### ISSUE TITLE
The interface freezes after pressing the Ctrl key

### ISSUE THREAD

**Issue by zhengqwe** [audacity/audacity#6841]
### Bug description

The interface freezes after pressing the Ctrl key after opening a file.

### Steps to reproduce

1. Start Audacity.
2. Drag in an audio file
3. When I want to zoom in the interface using Ctrl+mouse whell, the interface freezes, and it can only be turned off via Task Manager. Then I found that pressing only Ctrl also causes this problem.
![image](https://github.com/audacity/audacity/assets/103168200/c3f47f11-4931-4dca-b62e-7757ea4b5cad)

### Expected behavior

Working well.

### Actual behavior

Interface freezes

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by LWinterberg** [comment]
oh actually, this may be #805

**Comment by dozzzzer** [comment]
cannot reproduce this on Win 10 / latest master build.
