### ISSUE TITLE
Export of Audacity UI theme to ImageCache.png with built-in feature

### ISSUE THREAD

**Issue by deus-e-x** [audacity/audacity#6843]
### Your idea

The steps required at https://github.com/LWinterberg/classicTheme to create a custom theme are too complex, way over the head of a casual end-user.

Yet the instructions mention built-in experimental theming options, disabled by default, that allow the export of the current UI theme to a file ImageCache.png (see screenshot below).

![image](https://github.com/audacity/audacity/assets/45689656/f5198674-466e-41aa-a964-2be035ff4191)

### Problem to be solved

Can you please make a Windows compatible binary with this export option enabled available for download? This would ease the process of exportig UI themes for us, the end-users, tremendously. Thank you. 😊

**Comment by LWinterberg** [comment]
We don't really have the bandwidth to do that ourselves but feel free to publish such a version or ask in the forum if someone wants to maintain that. Note that editing the imagecache directly still works (though it will break if we change the UI further)
