### ISSUE TITLE
Audacity fails to detect and enable LV2 plugins properly

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#6846]
### Bug description

1. Audacity no longer enables LV2 plugins after scanning is finished; also, none have a proper "Category" in the Plugin Manager.

### Steps to reproduce

1. Have some valid LV2 plugins installed in your system directory `/Library/Audio/Plug-Ins/LV2`
2. Launch Audacity clean (remove `pluginregistry.cfg `beforehand)
3. Run plugin scanning
4. Open up Plugin Manager and filter by "Type: LV2, Category: All"

### Expected behavior

- "Type" column has "LV2".
- Each plugin has its "Category" attribute, so the list can be filtered by effect, generator etc.
- Upon scanning is over, all compatible plugins get enabled by default.
- The names of the plugins are correct.

### Actual behavior

- All plugins, regardless of their category (effect, generator, analyzer) are displayed in a single list.
- "Type" column is empty.
- No "Category" attribute for any of them, so the plugins can't be filtered by effect, generator etc.
- None of them got enabled by default (although it can be done so manually).
- The names of the plugins are hard to read and understand what is what compared to what was previously shown in 3.5.1.

### 3.5.1 - Plugin Manager after startup scanning is finished:

<img width="600" alt="image" src="https://github.com/audacity/audacity/assets/70063970/de3261e1-4cd3-4399-afbb-7ac6768aa1ea">

### 3.6.0-alpha after startup scanning is finished:

<img width="900" alt="image" src="https://github.com/audacity/audacity/assets/70063970/135f14af-1c88-4cd3-9033-d30c7708a689">

### Audacity Version

current master / alpha / nightly build

### Operating system

macOS, Windows

**Comment by chinakov** [comment]
This is also reproducible on Windows 11.

**Comment by dozzzzer** [comment]
@vsverchinsky bisects to https://github.com/audacity/audacity/commit/96275dbecaa8aceee237676d929dbc6725e73ae0

**Comment by dozzzzer** [comment]
Tested. LV2 plugins noe get enabled automatically, filtering by category can be done, and the names of the plugins are displayed correctly.

<img width="800" alt="image" src="https://github.com/user-attachments/assets/ec272dc7-97fc-4c05-a99c-0e9c4e4eecb5">
