### ISSUE TITLE
Audacity randomly speeding up tracks after update

### ISSUE THREAD

**Issue by AnikiTakaZ** [audacity/audacity#6849]
### Bug description

Since an update few months ago, Audacity when opening some AUP3 projects increases the speed of certain tracks, thus creating a sort of pitch

### Steps to reproduce

1. Creating a project
2. Recording my tracks
3. Saving my project
4. Closing it
5. Opening my project weeks after
6. Recording new tracks and listening previous ones

### Expected behavior

Not getting fucked up tracks that are speeded up for no reason

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

**Comment by Glevion** [comment]
It has happened to me two times already and screwed up two projects. Absolutely annoying.

**Comment by AnikiTakaZ** [comment]
Do you found any fix ?

**Comment by dozzzzer** [comment]
The issue is supposed to be fixed by https://github.com/audacity/audacity/pull/6880; the fix will be released in 3.6.0.

**Comment by AnikiTakaZ** [comment]
Thank you guys !
