### ISSUE TITLE
Auto-select all when selecting an effect

### ISSUE THREAD

**Issue by jkotlinski** [audacity/audacity#685]
**Is your feature request related to a problem? Please describe.**
I often open an audio file to apply some effect to it, e.g. normalize. When I select "normalize", I am met by the dialog "Select the audio for Normalize to use (for example, Ctrl + A to Select All) then try again." To me this seems like an unnecessary annoyance.

**Describe the solution you'd like**
When selecting an effect and no selection is made, automatically select all instead of showing a dialog.

**Comment by SteveDaulton** [comment]
Enable the "Select all audio, if selection required:" option in Preferences:
https://manual.audacityteam.org/man/tracks_behaviors_preferences.html
