### ISSUE TITLE
Older versions of Audacity are able to open newer versions' projects with unsupported effects in them

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#6855]
### Steps to reproduce

1. Create a track with some built-in effects in the stack (e.g. Reverb, Distortion, Compressor)
2. Save it and quit Audacity
3. Launch Audacity 3.2 (a version which already supports realtime effects but doesn't support the built-in ones yet) and try to open that project

### Expected behavior

An error message saying that "this project was made in a newer version" (feel free to refine this @LWinterberg).

### Actual behavior

No error message whatsoever. The audio can be played, but it's unusable on Linux due to extreme distortion. With the effects stack switched off, audio can be played normally. Trying to close them may cause a crash.
### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

**Comment by LWinterberg** [comment]
We do have a check for `SupportedProjectFormatVersion` which in theory should take care of that. It only gets written when certain features are used though, and we forgot to update it for 3.5 and 3.6 - `WaveTrackUtilities.cpp:418` and following lines have checks for 3.1 and 3.4. Interestingly, we also didn't add anything for 3.2, even though projects from 3.2 should not be openable in 3.1. Also, it doesn't appear that the functions that do these checks are called anywhere?

**Comment by LWinterberg** [comment]
@vsverchinsky @Tantacrul - The current approach does give some flexibility to users which didn't upgrade (so a person with 3.6 could collaborate with a user who thought 3.1.3 was the best version we ever released, and refuses to upgrade further, as long as the 3.6 user sticks to features which also are available in 3.1.3). 

It does add some issues for maintainability and scalability however: At the moment, we would need to iterate through __every clip in the project__ 3x at least (one for smart clips, one for stretching, one for pitch) for every save. If we instead as a general rule said that projects from 3.6 are incompatible with previous versions, we only need to do a single check - has this project been saved in this version yet, and if not, upgrade the version. That would save us from ever forgetting to add the check again. 

(We probably don't need to make patches incompatible, so 3.5.1 files can be opened in 3.5.0)

Out of these options, I prefer the latter.

**Comment by Tantacrul** [comment]
@LWinterberg I've done this multiple different ways in the past but ultimately, although backwards compatibility is always a must. Forwards compatibility is something we should not even attempt to do.

It adds more and more of a maintenance burden with every release.

We should create a widget in Audacity that checks to see what version a project was made in, and if it turns out the file was made in a newer version of Audacity, we should notify the user (with appropriate links) that they need to upgrade to see it.

**Comment by dozzzzer** [comment]
Tested
