### ISSUE TITLE
waveforms aren't updated when RMS pref gets reset

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#6856]
The RMS in the waveform is now off by default. 
However, if it's ON and there's a clip in the project, when I reset the config, the option goes back to OFF, but the waveform is not repainted and still shows the RMS. 

_Originally posted by @dozzzzer in https://github.com/audacity/audacity/issues/6852#issuecomment-2223356232_

**Comment by dozzzzer** [comment]
Tested
