### ISSUE TITLE
Put directory preferences all in the same place

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#6859]
### Your idea

Audacity has "Preferences > Directories".

My idea is to put all of Audacity's directory preferences in this section of Preferences.

### Problem to be solved

All of Audacity's directory preferences _except for_ the "Temporary Cloud files directory" are in the `Directories` section.

### Prior art

"Consistency" is a hallmark of good design.

### Additional context

The option should only exist when cloud services are enabled in the build.

**Comment by petersampsonaudacity** [comment]
There is a counter-argument in that it may be considered better to keep all the cloudy stuff together in preferences.

That is type of consistency too.

**Comment by SteveDaulton** [comment]
> There is a counter-argument

Yes, I did consider that but:

1. That same argument could be applied to the Export directory preference, but that is not what is done.
2. If you want to look up, or modify which _directory_ is used, the  obvious place to look is in the directories preferences, just as we do for the Export directory and all other directory preferences.

Not putting the "Temporary Cloud files directory" in the directories  preferences breaks a consistent and established pattern.

**Comment by LWinterberg** [comment]
All cloud prefs are in one page for technical reasons at the moment. We're revamping the entire menu structure for Audacity 4.
