### ISSUE TITLE
Saved projects may reopen with incorrect track sample rates

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#6875]
### Bug description

Track sample rates may change unexpectedly between sessions, causing the length and speed of clips to be incorrect.

### Steps to reproduce

1. Set the Project sample rate, and Default sample rate settings to 48kHz.
2. Generate a 30 second chirp.
3. Add a new track
4. Set the sample rate of the new track to 44100Hz
5. Generate a 30 second tone
6. Save to disk
7. Close Audacity
8. Relaunch Audacity and reopen the project
9. Apply the amplify affect to the second track
10. Quit Audacity and select **NO** when prompted to save.
11. Reopen the project

### Expected behavior

The project to be in the same state as in steps 6, 7 and 8.

### Actual behavior

The second track is now too short and plays at the wrong pitch (the track sample rate has changed to 48000 Hz).

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, Linux

### Additional context

Reported on the forum with Audacity 3.5.0: https://forum.audacityteam.org/t/track-sample-rates-change-when-closing-project/111711/1
Reproduced on Linux with Audacity 3.6 alpha.

Probably related (or the same issue) as https://github.com/audacity/audacity/issues/6611 but now with steps to reproduce on current Audacity versions.

Note this bug also occurs with imported tracks.
Note also that now that the track sample rate is not shown, users that import tracks with different sample rates are unlikely to notice that the cause of the problem is due to changed track sample rates.

**Comment by dozzzzer** [comment]
Bisects to https://github.com/audacity/audacity/commit/46bd0a9a8313c8db87ae785d066a253a4552b6e5

**Comment by chinakov** [comment]
This is fixed on Linux, tested on Ubuntu 22.04

**Comment by dozzzzer** [comment]
Same on Windows and MacOS
