### ISSUE TITLE
“关于”界面的copyright还停留在2018年

### ISSUE THREAD

**Issue by tasty0tomato** [audacity/audacity#688]
**Describe the bug**
“关于”界面的copyright还停留在2018年。

**To Reproduce**
1. 帮助
1. 关于Audacity
1. Audicity

**Expected behavior**
应该是2020年

**Screenshots**
<img width="394" alt="Snipaste_2020-11-10_22-45-18" src="https://user-images.githubusercontent.com/48764449/98689161-9c5fcf00-23a6-11eb-860b-09250b4043e0.png">

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version Audacity 2.4.2

**Comment by SteveDaulton** [comment]
You have a fake version of Audacity.
The genuine release version of Audacity is available via the Audacity website: https://www.audacityteam.org/download/windows/

**Comment by SteveDaulton** [comment]
Thanks.
Fixed.

**Comment by tasty0tomato** [comment]
> Fixed.

<img width="694" alt="Snipaste_2020-11-10_23-44-13" src="https://user-images.githubusercontent.com/48764449/98696672-0b412600-23af-11eb-834b-ccd5f3155436.png">

重新下载并换为了英文界面

**Comment by tasty0tomato** [comment]
问题并没有解决！！！请不要close issue！！！

**Comment by SteveDaulton** [comment]
I fixed it here: https://github.com/audacity/audacity/commit/0836ab12b4fc9771af017da1f506e6cadab6b043

**Comment by tasty0tomato** [comment]
> I fixed it here: [0836ab1](https://github.com/audacity/audacity/commit/0836ab12b4fc9771af017da1f506e6cadab6b043)

谢谢您！虽然只是一个微不足道的小问题，甚至对软件逻辑没有帮助，不过希望还是能尽量呈现出一个完美的软件。
