### ISSUE TITLE
Audacity Crashes when Pasting Mono Clip to Stereo Track

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#6882]
### Bug description

If the User pastes a mono clip into a stereo clip, Audacity crashes.

Crashreports: 
[crashreports.zip](https://github.com/user-attachments/files/16250442/crashreports.zip)

### Steps to reproduce

1. Launch Audacity
2. Create a Mono Track
3. Generate some audio in Mono Track
4. Create Stereo Track
5. Copy the mono clip, and paste it into the stereo track
6. Observe crash

### Expected behavior

The mono clip should be pasted into a stereo track, duplicating the right and left channel. 

### Actual behavior

Audacity crashes.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

### Additional context

This issue was introduced in 3.6, not reproduced on earlier builds.

**Comment by dozzzzer** [comment]
Tested
