### ISSUE TITLE
UI Artifacts on Button Corners in Dark Theme

### ISSUE THREAD

**Issue by CennoxX** [audacity/audacity#6892]
### Bug description

There are white points at the corners of some buttons in the Audacity UI. These artifacts can be seen in the attached screenshot. This issue affects the visual consistency and appearance of the interface.

### Steps to reproduce

1. open Audacity
2. activate dark mode

### Expected behavior

visual consistent appearance without white artifacts

### Actual behavior

![artifacts](https://github.com/user-attachments/assets/5197cb06-2d1e-4c37-9c8b-a2f3cdc1d3f3)

### Audacity Version

Audacity 3.6.0 (from audacityteam.org/download)

### Operating system

Windows 10

**Comment by dozzzzer** [comment]
Tested. I no longer see the original issue:

<img width="600" alt="image" src="https://github.com/user-attachments/assets/82395cd8-8b18-4287-8654-6990449e3a9e">
