### ISSUE TITLE
404-errored link

### ISSUE THREAD

**Issue by AvrahamTsaban** [audacity/audacity#690]
When opening any help content on audacity (clicking on the ? button on the egde of function window, for example), if I do not have the manual offline, I get:

 
> The Manual does not appear to be installed. Please view the Manual online or download the Manual.
> To always view the Manual online, change "Location of Manual" in Interface Preferences to "From Internet".

"the manual online" links to open the corresponding wiki page.

But on the Loudness Normalization function, it refers to 
[error 404](https://manual.audacityteam.org/man/loudness.html)
instead of
[this manual page](https://manual.audacityteam.org/man/loudness_normalization.html)

 - OS: Windows 10 20H2
 - Version: 2.4.2

**Comment by SteveDaulton** [comment]
Thanks. I've logged this on the bug tracker and hopefully it will be fixed in the next release.

**Comment by SteveDaulton** [comment]
Just a quick update. This has now been fixed for the next Audacity release.
