### ISSUE TITLE
Make Preset Name Visible

### ISSUE THREAD

**Issue by Gmitry** [audacity/audacity#6907]
### Your idea

When use a custom or default preset in for example Graphic EQ as shown in screen-cap below, it would be very helpful if the name of the preset could be visible in the top bare (for example at the right of the function name).

### Problem to be solved

Add the preset name or as well eventually he path to where it is saved or linked from, the date for insert it etc. 

### Prior art

![20240718_Name_Preset_Visible](https://github.com/user-attachments/assets/28edd9a0-aef9-4afa-a935-a96b087b0dbf)

**Comment by petersampsonaudacity** [comment]
This is a known issue that was previously logged last month:
 **There is no indication in EGAT dialogs of the preset settings currently in play** #6720 

It was closed by Muse in favor of:
 **Favorites, Presets dropdowns and plugin manager enhancement** #5158
