### ISSUE TITLE
Dark theme does not change title bar, context menus, etc.

### ISSUE THREAD

**Issue by BillyBob1354** [audacity/audacity#6908]
### Your idea

The Audacity dark theme should change things like the title bar, context menus, drop down menus, scroll bars, etc. to be dark or dark themed too.

![Screenshot 2024-07-17 220858 - Copy](https://github.com/user-attachments/assets/cc05e8a3-370c-4c90-9a47-2086c1b6b211)

### Problem to be solved

All these things (title bar, context menus, etc.) look out of place in the dark theme. Changing this would give the dark theme a more cohesive look.

### Additional context

**(Screenshots of Audacity taken in Windows 11 - Don't know if this affects macOS or Linux)**
<br>
_Example dark colored theme in Acoustica with more consistent coloring for the title bar, context menus, scroll bars, etc._

![Screenshot 2024-07-17 222105](https://github.com/user-attachments/assets/a032561d-78aa-4987-a511-ab75a3fbba5c)

**Comment by petersampsonaudacity** [comment]
This is a known and alreday logged issue:
 **Many parts of Dark theme Audacity are not really "dark"** #1296 

It was closed on 1st of May last year by Muse - as I believe that they will not address this in the 3.x series of Audacity.

Muse are currently working on v4 Audacity which will have a completely revised interface (at least that is my understanding) - so hopefully we may see a fully dark Dark theme there later.
