### ISSUE TITLE
Track centre line does not appear until zoomed in a very long way

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#6912]
### Bug description

When the zoomed in on the waveform close enough to see individual cycles, a horizontal centre line appears, which provides a visual reference for -inf dB. In recent versions of Audacity (observed in 3.6 alpha  and 3.6.0), the centre line does not appear until zoomed in very close.

### Steps to reproduce

1. Generate a default 30 second tone
2. Zoom in to view 0.1 seconds.

If you keep  zooming in, the horizontal line does eventually appear.

### Expected behavior

![expected](https://github.com/user-attachments/assets/aaba4736-539d-4ba1-9da8-857c323b49c0)

### Actual behavior

![actual](https://github.com/user-attachments/assets/24b11820-6f98-4d7e-bcdb-e04e37241566)

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux macOS

**Comment by petersampsonaudacity** [comment]
In contrast, on W10 with 3.5.1, this is where the center line first appears when zooming in:
![image](https://github.com/user-attachments/assets/b740c45f-9dbd-446a-931d-46c1e1f54ace)

**Comment by SteveDaulton** [comment]
One example of why it matters: https://forum.audacityteam.org/t/where-did-the-baseline-zero-line-go/112102/1

**Comment by LWinterberg** [comment]
This happens on mac and windows too

**Comment by dozzzzer** [comment]
Bisects to https://github.com/audacity/audacity/commit/3de5915b00e22aa5b6f5d7cbafd91c9493cd10cb

**Comment by petersampsonaudacity** [comment]
Testing on W11 with @vsverchinsky 's brach test build for this:  audacity-win-3.6.2-alpha-20240731+4ab9afd-x64

This now looks much better, the center line appears as soon as the solid wavecolor disappaers with the zoom level:

![image](https://github.com/user-attachments/assets/bf5dce60-15bf-4eeb-b1fb-4fc27022607c)
