### ISSUE TITLE
New Compressor and Limiter are not translated in Portguese

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#6920]
### Bug description

The New Compressor and Limiter are not translated in Portguese.

This makes it difficult for Portuguese users to understand how to use the new effects _(which are fairly complex/complicated)_ - as reported on the Forum
https://forum.audacityteam.org/t/melhorar-os-efeitos/112088

This is not the case for Deutsch for example, where the dialogs are translated.

_But there could well be other languages where these new effects are not translated - I have not tested._

### Steps to reproduce

1. get some audio and select it
2. Change language to Portugese
3. invoke teh Compressor or Limiter effect
4. Observe: the dialog is not tanslated

### Expected behavior

Tha dialogs should be translated into the user's chosen language

### Actual behavior

![image](https://github.com/user-attachments/assets/c71b9320-1bc5-4fe6-9a98-f3eb8286f8f9)

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by LWinterberg** [comment]
I don't think we had a pt translator this time around.

**Comment by BrunoRamalhete** [comment]
I am the Portuguese translator of Audacity (pt_PT, the European one), and I've been translating Audacity using Transifex. I translated this last version, you can see in Transifex that is 100% complete.

I have no idea why this is happening, have you been merging the translation files? I try to send the file by sourceforge mail account but gives me an error.

Perhaps I can send upload the file directly over here.

**Comment by LWinterberg** [comment]
I think this is fixed now
