### ISSUE TITLE
Dark theme improvements

### ISSUE THREAD

**Issue by xeophyte** [audacity/audacity#6922]
### Your idea

1. these corners look bad on Windows

![image](https://github.com/user-attachments/assets/42e6fc09-68d0-41ed-8c35-0da3d16187e5)

2. Will these elements ever be made in a dark theme? Also main menu and all the windows like settings or plugins manager?

![image](https://github.com/user-attachments/assets/ac05748f-f1c5-4775-9b4d-fd2c6232cbbc)

3. And why on the video there is a dark theme with a little different colors? Are they different for Mac?

![image](https://github.com/user-attachments/assets/86458291-fa73-41ef-8fa0-050d2e59a688)

Audacity 3.6.0
Windows 11

### Problem to be solved

Dark theme improved

**Comment by dozzzzer** [comment]
The issue is already fixed and will be delivered in the 3.6.1 release.
