### ISSUE TITLE
Incorrect waveform appearance when Envelope applied to clip offset from zero

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#6927]
### Bug description

When an Envelope is applied to a clip that starts after zero, the affect on the waveform is incorrectly offset.

### Steps to reproduce

1. Generate a 10 second tone
2. Apply a non-destructive fade-in to the first 2 seconds using the Envelope  tool.
3. Slide the clip to the right so that it starts at time = 5 seconds

### Expected behavior

The fade is expected to remain in the same place relative to the clip.

### Actual behavior

The fade appears to have stretched to the right, even though the Envelope control points are still in the correct places relative to the clip.

Image copied from bug report on the forum:

![67de7fdf763258eb8e582db34478f8f830646966](https://github.com/user-attachments/assets/bc6c51d5-2d6d-418b-afe5-09d5976d3c8d)

### Audacity Version

3.6.0 / Audacity 3.7.0-alpha

### Operating system

Linux, Windows, MacSO

### Additional context

Originally reported on the forum: https://forum.audacityteam.org/t/envelope-help-what-am-i-doing-wrong/112247
Confirmed on Linux.

This is a serious bug that also affects existing projects created in previous versions.

**Comment by time-less-ness** [comment]
I am seeing this same bug on MacOS. Reverted to 3.5.

**Comment by petersampsonaudacity** [comment]
Testing on W10 with @saintmatthieu 's test branch build for this:  audacity-win-3.6.2-alpha-20240725+21b4a4d-x64

This appears to work properly again in Matthieu's branch build.

**Comment by dozzzzer** [comment]
tested

**Comment by petersampsonaudacity** [comment]
@dozzzzer @LWinterberg 

Testing on W10 with the latest 3.6.2 Beta build, this now appears to be fixed.

I think thus that this can be closed.

**Comment by SteveDaulton** [comment]
I'm still seeing this  bug with commit id a634c3 (on Linux).

**Comment by petersampsonaudacity** [comment]
Testing on W10 with the newly released 3.6.2

This works fine for me.

_@SteveDaulton  any chance you can retest on Linux with 3.6.2?_

**Comment by SteveDaulton** [comment]
Commit id a634c3 is more recent than the Audacity 3.6.2 release. It successfully built, and runs, but ...

![Screenshot_2024-09-04_11-15-48](https://github.com/user-attachments/assets/7525896d-5ca9-4824-a7b0-83e659f2f1f8)



Attempting to launch the 3.6.2 AppImage using the "portable home" option gets as far as the splash screen and then freezes.

Attempting to run the 3.6.2 AppImage by extracting it first does launch, but then crashed.

**Comment by petersampsonaudacity** [comment]
@SteveDaulton 

So I just tested this on the latest 3.7.0 alpha build:  audacity-win-3.7.0-alpha-20240904+e71a22c-x64-msvc2022

Still works fine for me.

**Comment by LWinterberg** [comment]
https://github.com/audacity/audacity/commit/190105029fe4e9a2c45501ac7a4573c3f7f2009a doesn't appear to be a parent of https://github.com/audacity/audacity/commit/a634c3855b7c9da4d9795f3c70c31eef3cddea53, please try with a 3.7 master after 3.6.2 got merged back into it.

**Comment by saintmatthieu** [comment]
@SteveDaulton about your freeze/crash, I just tried on Ubunto and had an assert in debug, ran the release version without further investigation. Now there's no crash and the envelope seems to work fine.
I'm on a very fresh master. I believe your commit to be from master a few days old. Vitaly just merged back 3.6.2 into master, merge commit is e71a22c905bebd65bb00a568b20b8ffc42b22ab0. Could you re-test on this?

**Comment by SteveDaulton** [comment]
> I believe your commit to be from master a few days old.

It was committed to "master" yesterday: https://github.com/audacity/audacity/commit/a634c3855b7c9da4d9795f3c70c31eef3cddea53
(Sep 3, 2024).

Are you saying that the master branch was behind the release version? I assumed that the latest "master" was the most recent. If that is not the case, how do I know which is the latest version for testing?

**Comment by saintmatthieu** [comment]
We make a release branch to freeze development while we test. In the meantime, the master branch continues, and we typically merge back the release branch after testing is complete. Until then they are two different things to test.
What you reported was a bug introduced before the release branch was created but caught after. Fix will then go on the release branch, hence you not seeing it on master.
Could you confirm so that we can close?

**Comment by SteveDaulton** [comment]
Yes, it appears to be fixed in the master branch today.
