### ISSUE TITLE
Clip names not retained when pasted to another track

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#6928]
### Bug description

In previous versions, when copy and pasting a clip, the clip name would be retained, allowing the clip to be identified by  its name. This no longer works as the clip name is not retained with the copied clip

### Steps to reproduce

1. Generate a tone
2. Name the clip: "AAA"
3. Add a new track
4. Copy the clip from the first track, and paste into the second track

### Expected behavior

Both tracks to contain clips called "AAA"

### Actual behavior

The clip in the second track is called "Audio 2"

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Linux
**P.S.** and Windows - so assume all OS

### Additional context

I assume that this is not an intended but undocumented behaviour change.

Originally reported on the forum: https://forum.audacityteam.org/t/retain-clip-name-in-3-6/112237

**Comment by petersampsonaudacity** [comment]
Testing on W10 shows that this is a regression on 3.5.1

**Comment by petersampsonaudacity** [comment]
This is a duplicate of #6926

**Comment by SteveDaulton** [comment]
Closed as duplicate of https://github.com/audacity/audacity/issues/6926
