### ISSUE TITLE
Imported audio is now auto-selected, thereby destroying any prior selection that the user had

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#6929]
### Bug description
In 3.6.0 and 3.6.1 test builds - when you import an audio file audacity now selects that imported audio - and of course in so doing this replaces and thus destroys any selection that the user may have carefully made.

This is a regression on 3.5.1 and all earlier Audacity versions.

Reported by two users on the Forum:
https://forum.audacityteam.org/t/audacity-automatically-does-select-all-after-importing-file/112215
https://forum.audacityteam.org/t/audacity-3-6-is-out-now/111894/42

### Steps to reproduce
1. Import an audio file
2. Observe: the track is auto-selected
3. make a small selection on the track
4. Import a second audio track
5. Observe: this new track is selected, thus removing the selection made at step 3

### Expected behavior
Imported audio should **_not_** be auto-selected

### Actual behavior
Imported audio is auto-selected - removing any prior extant selection

### Audacity Version
3.6.0 and latest 3.6.1 test build

### Operating system
Windows 10 - but assume all OS

### Additional context
None

**Comment by DavidBailes** [comment]
@LWinterberg . I've created a PR to fix this, please can this be added to 3.6.1?

**Comment by DavidBailes** [comment]
> @LWinterberg . I've created a PR to fix this, please can this be added to 3.6.1?

I'm too late!

**Comment by dozzzzer** [comment]
3.6.2 it is then :)

**Comment by dozzzzer** [comment]
@DavidBailes feel free to open a PR once again.

**Comment by petersampsonaudacity** [comment]
Testing on GitHub with @DavidBailes 's test branch build for this:  audacity-win-3.6.1-alpha-20240722+2594629-x64

a) importing a file does not get that audio audio selected

b) **BUT** - when you import a file the time selection that was originally present gets transferred to the newly imported track:
![image](https://github.com/user-attachments/assets/b197bb29-ff9a-4404-8753-507048b0b32b)
And applying an effect show that the selection is indeed in the new track and this is **not** just a visual/display error

**Comment by petersampsonaudacity** [comment]
David Bailes wrote in the PR thread:
> This is the same behaviour as 3.5.1 and previous versions - the last imported track becomes selected. This PR does not change that, it only removes the change in the time selection.

Yes, I just tested that.

BUT that looks erroneous to me.  

@LWinterberg @dozzzzer 
Do we need a new issue for the time selection being moved to the newly imported tack?  I suspect that we do,

**Comment by dozzzzer** [comment]
Tested

**Comment by petersampsonaudacity** [comment]
@LWinterberg 

You have closed this as this now behaves the same as 3.5.1 and all earlier Audacity versions (including Dominic Mazzoni's original 1.0.0 release.

But to me (and the two Forum posters linked to in the initial post in this thread)this seems to most odd and undesired behavior.

Basically if the user makes a careful selection in a track or tracks that they already have and then import a new audio file, I would expect the selection to remain as-is and **NOT** be transferred. to the same temporal range in the new track thereby removing the
user's original careful selection

====================================================

Incidentally when I test this I get a crash bug when I exit - I will log this separately.

**Comment by LWinterberg** [comment]
I don't think the story of the "carefully made selection" really holds in practice. You just imported a new piece of audio, surely you want to do something with that audio now, no? 

The forum posters have a use case of using the selection as a bookmark for where they want to drag their imported file to. This restored behavior facilitates this bookmark use case at least. 

We know where we want to go with this behavior: Once we do overlapping clips and clip selections, imported clips should just appear in the current track, at the current cursor position. And for drag'n'drop, files should go in depending on the mouse cursor position. In both cases, the imported clips would be clip-selected Until we can make that work, I don't see much point in changing anything about import behavior.

**Comment by petersampsonaudacity** [comment]
> I don't think the story of the "carefully made selection" really holds in practice. You just imported a new piece of audio, surely you want to do something with that audio now, no?

In which case I would make a new selection in the new track, or select the whole of the new track.

I would not really expect to see the previous temporal selection to the new track, that looks most odd to me.

Rather than doing this it might be better to just remove any selection whatsoever on importing a new track.  _But hey it's been this way for 20-odd years or so why change it ..._
