### ISSUE TITLE
Option to lock the toolbars

### ISSUE THREAD

**Issue by ushuc** [audacity/audacity#6932]
### Your idea

It would be great if the toolbars could be locked. In locked mode the toolbar handles should disappear.

### Problem to be solved

There were many a times when I accidentally click on one of the toolbar handles in the front and mess up their layout and disturb my workflow. In many other programs there is an option to lock the toolbars to prevent accidental changes.

**Comment by LWinterberg** [comment]
We'll be switching to a different system with fewer toolbars but more internal customization for the toolbars for audacity 4. We're not planning on working on toolbars anymore in audacity 3.
