### ISSUE TITLE
Add pop-up for “Share Audio” button when it is clicked prior to saving project.

### ISSUE THREAD

**Issue by beanieyi** [audacity/audacity#6938]
### Your idea

When clicking on the “Share Audio” button prior to saving a project, a pop-up should show up indicting to the user that the project must be saved first prior to sharing audio. As of now, there is no pop-up, or no action at all when you click “Share Audio” prior to saving a project. This could leave people wondering whether the button is broken. While this is not a major usability issue, it could clear up any confusion that occurs from a no action.  

### Problem to be solved

As of now, clicking on “Share Audio” prior to saving results in no action at all. Adding the pop-up could dissipate any confusion as to why no action occurs when the button is clicked prior to saving.

**Comment by LWinterberg** [comment]
> As of now, there is no pop-up, or no action at all when you click “Share Audio” prior to saving a project.

This is not my observation, for me, the button works just fine provided there's any content in the project. For an empty project the button indeed does nothing.
