### ISSUE TITLE
Audacity fails to put the clip into a clipboard when being cut and then pasted

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#6941]
### Bug description

If copying a file on your file system before cutting a clip inside Audacity (Edit > Cut) and then pasting it, it will paste that audio file instead.

### Steps to reproduce

1. In your file system, copy an audio file A (Ctrl + C)
2. Drag a different audio file B into Audacity
3. Edit > Cut (Ctrl + X)
4. Edit > Paste (Ctrl + V)
5. Observe

### Expected behavior

The audio clip cut in step 3 is pasted.

### Actual behavior

The audio file copied in step 1 is inserted instead.

https://github.com/user-attachments/assets/cb33ec72-2fd8-416f-b405-12336d7d5cd2

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows, macOS

**Comment by dozzzzer** [comment]
@saintmatthieu it bisects to one of these three commits https://github.com/audacity/audacity/pull/6280/commits

**Comment by saintmatthieu** [comment]
Thanks @dozzzzer, [PR](https://github.com/audacity/audacity/pull/6951) ready for review.

**Comment by dozzzzer** [comment]
More precise commit that caused the issue: https://github.com/saintmatthieu/audacity/commit/4da9e21fd459edda9f88d6285d253937dd5a624c

**Comment by dozzzzer** [comment]
Tested
