### ISSUE TITLE
[AU4] Clips - Mono & Stereo

### ISSUE THREAD

**Issue by DilsonsPickles** [audacity/audacity#6944]

**Comment by DilsonsPickles** [comment]
@LWinterberg, not sure we need this task anymore. Any further designs regarding mono/stereo clips will have a more specific task created for them.

**Comment by Tantacrul** [comment]
What is this task for exactly?

- should we change it and give it a specific goal?

**Comment by DilsonsPickles** [comment]
Safe to close/delete!
