### ISSUE TITLE
[AU4] Clips - Responsive behaviour

### ISSUE THREAD

**Issue by DilsonsPickles** [audacity/audacity#6945]
Check AU3 behaviour -> Clip name is last to go.

**Comment by ianalarina** [comment]
@Tantacrul @grliszas14 please, confirm if its done

**Comment by Tantacrul** [comment]
I believe this refers to how clip headers truncate when clips are made smaller, and how they also move position when you drag them off-screen.

In both cases, I believe these are done. Right @grliszas14 ?

**Comment by grliszas14** [comment]
@Tantacrul That's correct, both cases are done. This task can be closed unless there's anything more to do, [Figma design](https://www.figma.com/design/01XLIICmy2AG6t1ieyTp66/02---Clips?node-id=521-68106&node-type=canvas&t=X4eNUyQRlPWyRFJR-0) is empty

**Comment by DilsonsPickles** [comment]
It seems these designs were implicitly implemented as part of other design tasks and general feedback. A design spec hasn’t been necessary, which is why the link is empty and the task is still marked as ‘todo.’

**Comment by Tantacrul** [comment]
Yep, I guessed. It's naturally going to happen I would imagine from time to time. Marking as complete.
