### ISSUE TITLE
Record to manually created selected track

### ISSUE THREAD

**Issue by phillitrOSU** [audacity/audacity#6952]
### Your idea

Audacity automatically creates a new recording track when recording with the "shift" key held. A user is able to continue recording on tracks that are generated using this method by clicking the playhead inside of the track. However, if a user manually creates a new track, selects and clicks the playhead to a specific point, they don’t automatically record to this track. It would be most intuitive if users are able to manually create a new track and then record to it by selecting it or setting the playhead inside of it.

### Problem to be solved

Users are not able to record to manually created tracks by selecting the track.

### Prior art

<img width="411" alt="Screenshot 2024-07-23 at 7 44 25 AM" src="https://github.com/user-attachments/assets/836ba394-1a29-4d93-b4dc-3c39727286f5">

<img width="757" alt="Screenshot 2024-07-23 at 7 39 08 AM" src="https://github.com/user-attachments/assets/2fb3e010-15b6-4ca9-9a68-cb549dd0c8f9">

**Comment by LWinterberg** [comment]
https://github.com/user-attachments/assets/794a954b-d999-44a0-85cb-6511cc78654d

Works for me - if I don't use "record to a new track" but just the normal "record" button.
