### ISSUE TITLE
Help Button(s) (with symbol ?) are missing

### ISSUE THREAD

**Issue by jserquera** [audacity/audacity#6957]
### Bug description

There are many windows where the Help Button, ussually on bottom-right, is missing.

For example on Effect windows.

### Steps to reproduce

1. Go to Reverb effect
2. When the Reverb window is on screen, see that the Help Button is missing.

### Expected behavior

to appear in nearly every window

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by petersampsonaudacity** [comment]
Muse took those away many releases back - they decided that such links to the Manual were no longer necessary.
