### ISSUE TITLE
[AU4] Implement "Create new" project

### ISSUE THREAD

**Issue by grliszas14** [audacity/audacity#6961]

**Comment by chinakov** [comment]
Tested, 'Create New' project feature has been implemented. Currently, it is still limited by a single-project opened concurrently in AU4.

**Comment by dozzzzer** [comment]
Clicking either of these two buttons crashes Audacity immediately on MacOS.

<img width="900" alt="image" src="https://github.com/user-attachments/assets/46650189-a48e-40cc-9b84-bcfc34027891">

**Comment by dozzzzer** [comment]
Tested
