### ISSUE TITLE
Data exchange with 2.3x versions?

### ISSUE THREAD

**Issue by RJVB** [audacity/audacity#697]
Apologies if this is covered somewhere else (but I didn't even see mention of the project file format change during several quick glances at the "what's new" documents)

Is there a way to save a project from 2.4.2 (or newer) such that it opens in older Audacity versions? I don't see anything like that in the current git head code; support for writing the legacy formats seems to have disappeared.

That bothers me for 2 reasons:
- I can't fall back to using, say, v2.3.2 (if I want or have to)
- I don't particularly trust sqlite3; I have seen it a few times too often on large datasets leading to complete data loss. The fact that the saved project file apparently isn't closed immediately after having been written doesn't exactly help in my trust department (I got disk full/unwritable errors about a remote parent directory of the project directory when I checked to see how well HFS compression would reduce the 600+Mb file corresponding to the 1st recording I made with the new build; naughty maybe but I don't think that ever caused me trouble with older versions). Same thing when "save as" gave me file that showed up as 0B small until at some point it wasn't anymore. If I save a copy of an open project I want to be able to hand off that file immediately when the save operation returns control to me, without having to wonder when the file will have been written completely.

I'm also not at all certain that using sqlite3 isn't overkill for most users using Audacity only for making straightforward (live) recordings, cutting out fragments and applying a few common filters. The old (compressed) format worked perfectly fine for that.

**Comment by petersampsonaudacity** [comment]
The project file structure has remained unchanged from 1.3.x Beta series all the way through to 2.4.2, - so compatibility should apply across all those versions.

This will alter dramatically with the upcoming 3.0.0 where we are implementing a unified project file structure such that each project exists in a single file.  Projects for 2/4/2 all the way back to 1.3.1 can be opened in 3.0.0 - but once saved in 3.0.0 (and later versions) the project can no longer be opened in older versions of Audacity.

I have been testing 3.0.0 alpha with some pretty large projects with no issues.

Yes the old project format worked well - but we had far too many users who failed to manage their multi-part projects and thus irretrievably lost data - we were (still are) burning folk like this at a run-rate of roughly 2 per week - hence our decision to move to the Unitary Project format.

**Comment by RJVB** [comment]
On Thursday December 03 2020 05:10:59 petersampsonaudacity wrote:

>Yes the old project format worked well - but we had far too many users who failed to manage their multi-part projects and thus irretrievably lost data - we were (still are) burning folk like this at a run-rate of roughly 2 per week - hence our decision to move to the Unitary Project format.

Moving to a new format doesn't mean an export or save-as facility in the old format cannot be maintained until there is sufficient (in my book, a few years) of proof that the new format is indeed reliable AND all common distributions have moved to the newer version. There might not even be a hard reason at all to strip the code for saving the old format (on life support, no need to introduce new features that aren't supported in older Audacity versions anyway).

You may well find out that I am not the only one who is questioning whether or not to keep the upgraded version or to stick to the current version because of this.
I had a quick look at when which code was stripped, but it looks like this was done during a mega change. Never a good idea unless you are obliged to burn all bridges behind you!

I hate to say it, but even Microsoft Word never moved to a new, backwards incompatible format this way...

**Comment by SteveDaulton** [comment]
If you don't feel comfortable with the new format, you can continue using Audacity 2.4.2. When you eventually decide to update, any old projects that you may have can be imported into the new version. It is incredibly frustrating for those of us that provide end user support to have to a constant stream of users losing work due to the old multi-file format and we will be extremely relieved when that is no more than a bad memory.
(We have considerably less resources available than Microsoft, so I don't really think that is a fair comparison.)

**Comment by RJVB** [comment]
No one should have to make that choice between updating because of bug fixes, improved support for newer wxWidgets versions (or any other reason) and not updating because you cannot afford to lose compatibility. No one should be obliged either to build from source because they're somehow stuck to a distribution or OS that doesn't provide the latest version - and for which you don't have the resources to do so either.

Remember, this affects not just people like me who happen to have different computers with different version of the same software. It also affects people who need to be able to exchange with others. And it's not like you get a big fat warning when (before!!) you start to record in the new version, so if your brand new recording's goal was to collaborate with someone who uses an older version ... well, you just lost your data too.

As I said, moving to a new format that will evidently be the default doesn't mean you can't preserve full support for the old format, but people should no longer lose data because of it. The alternative would be to write a small external converter utility which wouldn't even need to have a (fancy) UI. That shouldn't be too hard now that the old format output code is still rather fresh in the minds of those who worked on it - and thanks to the migration to CMake it's easy to add additional build targets.

BTW, there's also no build-time verification that the system version of sqlite3 is configured appropriately. I tested with the latest version in MacPorts and immediately got database errors (and crashes) which must be due to assumptions made about the sqlite build-time configuration. I am not getting involved with DB programming beyond very simple and robust ones like LMDB so I didn't try to figure out what went awry. I wouldn't be against helping with my other suggestions, but don't know the code (nor coding with wxWidgets).

**Comment by SteveDaulton** [comment]
I assume that you noticed the big version jump from 2.x to 3.x. THE big difference between the 2.x series and the 3.x series is the new single file project format. Yes there will be a "big fat warning" because this THE major difference in 3.0.0.

Unfortunately, Linux users being stuck on old versions of programs is a common problem. It would be nice if we had more experienced Linux developers working on Audacity to help keep distribution releases up to date, but in the absence of that we work with what we've got.

If you and I were working together on a Python script, we would have exactly the same problem if one of wanted to stick with the old 2.x series and the other wanted to upgrade to Python 3.x.

You can of course run both Audacity 2.4.2 and 3.0.0 on the same machine, just not both at the same time.

I'm not saying that it is good to break compatibility, but I think it is far more important to maintain support for work created in older versions, which Audacity 3.x does. There will frequently be problems with compatibility the other way because of new features that are not supported by older versions.

Personally I would welcome a conversion utility, though unfortunately I feel it is beyond my ability.

**Comment by petersampsonaudacity** [comment]
RJVB wrote
>I hate to say it, but even Microsoft Word never moved to a new, backwards incompatible format this way...

Not entirely true - it is not possible to open .docx documents from Word 365 in the old Word 2000, so not proper backwards compatibility.  Agreed that Microsoft do actually enable you to Save from Word365 in the old .doc format used by Word2000.

And no we haven't provided a similar Save utility in 3.0.0 to enable Audacity users to Save in the old AUP and associated _data folder with all  the little sound files.  As Steve explained earlier we are a very small (and I do mean very small) team of part-time volunteers.  We did think about about but decided that it was not a good use of our very limited resources.

If you wanted to volunteer to develop such a tool  we would be glad to QA test it and incorporate it, if it proved suitable.

**Comment by RJVB** [comment]
When I said big fat warning, I meant something in-your-face the 1st time you fire up the new version, not something in the release notes. I think I already mentioned that I didn't see any reference to the file format change in the current "what's new in" documentation, and certainly not to the fact that you can no longer write in the old format. And if it wasn't clear THAT is the decision I cannot get my head around. If nothing else changed drastically feature wise, why would it not have been possible to keep the old code

>If you and I were working together on a Python script, we would have exactly the same problem if one of wanted to stick with the old 2.x series and the other wanted to upgrade to Python 3.x.

Python is a language so this isn't really a good example. Typically one doesn't generate Python using the Python interpreter (disregarding editors written in Python of course), and besides it's perfectly possible to write code that runs under both versions of the interpreter (with or without the py2to3 converter). I also don't think there's a single distribution that doesn't provide both by now (but Apple may still only be including v2.7 in their OS).

I cannot think of a single application for data acquisition (and editing) where a new version introducing a new file format just dropped output in the old format if it didn't already have support for an exchange file format retaining most if not all of the features you might lose by exporting to some external format.

> You can of course run both Audacity 2.4.2 and 3.0.0 on the same machine, just not both at the same time.

Eh, even if you install them under different prefixes? Why is that? You can run multiple instances of the same version, no? If what you're saying is true you couldn't even copy/paste new data from the new into the old version...

>  As Steve explained earlier we are a very small (and I do mean very small) team of part-time volunteers. We did think about about but decided that it was not a good use of our very limited resources.

Supposing you didn't change the entire internal API at the same time, NOT stripping the old saving code outright would have actually cost less time that stripping it all out. Keeping old code around also doesn't have to cost more than making occasional changes to keep it compiling. I have code like that myself in some of my own projects. I know I can always spend the time required for cleaning things up if the code has been know not to work for long enough without that leading to any issues. That may sound sloppy, but it doesn't have to be if the code base was organised properly in the first place.

I do believe you're a very small *core* team, but don't forget how new collaborators come to projects ... more often than not it's because they have a reason to fix something that doesn't work. I would have been ready to take on some sort of responsibility to keep that legacy saving code on life support had it been kept around. I even might have considered reintroducing it had it been removed in one or a select few dedicated commits.

As it is, the code base is simply too big and alien for me to dive in, and without a central library providing the core functionality that one could call from a conversion utility means writing one is probably going to cost me more time and energy than I'm able and willing to invest.

Would it be possible to provide an "export to .aup" feature in a plugin (that reuses the legacy C++ code)? How much time would it take to bring back the legacy code in a (pair of) source file(s) of its own and get it to build (without any form of checking if it works as it should and when done by the team member most intimate with this part of the code)?

**Comment by SteveDaulton** [comment]
> I didn't see any reference to the file format change in the current "what's new in" documentation
You must be looking in the wrong place. Audacity 3.0.0 has not been released yet, so of course it's not in the current manual.
This is the "work in progress" 3.0.0 manual: https://alphamanual.audacityteam.org/man/New_features_in_this_release

The "Release Announcement" hasn't been written yet, but I'm fully expecting that the first new feature to be mentioned will be the new project format.

> I cannot think of a single application for data acquisition (and editing) where a new version introducing a new file format just dropped output in the old format
Agreed it is rare. This is the first and only time it has happened in Audacity's 20 year history. The only other case that comes to my mind was OpenOffice 2.0 (around 2005?).

If I understand correctly, this issue is a feature request to support creating old style "AUP" projects, either directly from Audacity or from a format converter app? If that's correct I can log that.

**Comment by petersampsonaudacity** [comment]
> I think I already mentioned that I didn't see any reference to the file format change in the current 
>"what's new in" documentation, and certainly not to the fact that you can no longer write in the old format. 

I'm afraid tour not entirely right there I wrote the What's New page for 3.0.0 and it clearly tells you about the lack of backward compatibility.  See the green note div in this section at the top of the What's New page:
https://alphamanual.audacityteam.org/man/New_features_in_this_release#aup3

In the light of you comments I may find some time to make that "in-your-face" - we do have a while still before 3.0.0 is ready for release.

I will try to find some to talk to the developers (The Release Manage basically) to see if there is any chance of changing the Save Project dialog to show such a warning on the first Save Project or first n Saves - with a "Do not show this warning again".  This may not be possible as we are getting close to "string-freeze" when the code is handed over to the translators and we can no longer change text in the app.  Such feedback as this would have been much more helpful earlier on in the dev cycle, giving us time to make such changes.

**Comment by petersampsonaudacity** [comment]
I have updated three pages in the 3.0.0 alpha Manual with "in-your-face" bolding advising on backwards incompatibility, adding a workaround for this.

1) What's new in 3.0.0
https://alphamanual.audacityteam.org/man/New_features_in_this_release#Unitary_Project

2) Managing Audacity Projects
https://alphamanual.audacityteam.org/man/Audacity_Projects#Save_Project

3) File Menu: Save Project
https://alphamanual.audacityteam.org/man/File_Menu:_Save_Project

And it will not be just in obscure Release Notes (which we know few people read, or read with any thoroughness) where we will inform users of this compatibility shift - in particular
a) On our website Downloaded pages we will clearly show this
b) On the release announcement I make on our Facebook page I will clearly state this
c) And on the independent Facebook page "Audacity Users" (of which I am an invited administrator) I will clearly state this with thr 3.0.0 release announcement I make there
d) Our sticky release announcement on the Forum will also explain this.

**Comment by petersampsonaudacity** [comment]
I did a little more work on this today and added a new FAQ and a related page for details on the workarounds

FAQ
https://alphamanual.audacityteam.org/man/FAQ:Opening_and_Saving_Files#compatibility

Workarounds
https://alphamanual.audacityteam.org/man/Moving_AUP3_projects_from_Audacity_3.x_to_Audacity_2.x

**Comment by RJVB** [comment]
On Friday December 04 2020 05:41:02 Steve Daulton wrote:
>If I understand correctly, this issue is a feature request to support creating old style "AUP" projects, either directly from Audacity or from a format converter app? If that's correct I can log that.

I've been MIA a bit, sorry for that. Yeah, you can consider this as a feature request.

There might be other workaround approaches that can be justified (have an interest) beyond backwards compatibility with the 2.x series (think compatibility with other multimedia content editors). The current workaround description is based on exporting manually through one or more .wav files.I can think of at least 2 container formats that (should) allow storing multiple tracks in lossless format: QuickTime's .mov and the .mkv containers. The former does have support for time tracks and all kinds of metadata but I don't know to what extent free and up-to-date library source code exists that allows reading and writing of .mov files. I have no first-hand experience with the latter (mkv) format.

**Comment by SteveDaulton** [comment]
> Yeah, you can consider this as a feature request.

Logged.

> The current workaround description is based on exporting manually through one or more .wav files.

Audacity can already export losslessly up to 32 channels as 32-bit float WAV. See: https://manual.audacityteam.org/man/advanced_mixing_options.html

**Comment by RJVB** [comment]
On Tuesday December 08 2020 07:24:18 Steve Daulton wrote:

>Audacity can already export losslessly up to 32 channels as 32-bit float WAV. See: https://manual.audacityteam.org/man/advanced_mixing_options.html

But apparently not time tracks, and on a more general note, why are exchange workaround instructions to export to multiple .wav files? Maybe I should re-read, but what I took home after the 1st read was that you'd be doing the manual monk's work to render multi-track recordings to multiple .wav files, including having to give them an appropriate numbering scheme and then import them.

Of course it would also not be a bad idea if one could do the exchange via a lossless compression codec (ALAC, for instance, which was open-sourced several years ago already).

**Comment by LWinterberg** [comment]
with smart clips, increased support for real-time effects and VST3s and other upcoming features, keeping backwards-compatible project files is becoming more and more impossible. Even if there was someone maintaining a logic that determines which of the new features get ignored/applied and how, it'll be completely unrecognizable by the time you get it opened back up in 3.x, kinda like an image-heavy magazine that gets sent through an OCR thing and now shows you a bunch of plain text files. Because of this, and since exporting into a common supported format (wav, flac, ...) is available as a workaround, I'm closing this request

**Comment by RJVB** [comment]
That's not at all a tad overly dramatic and besides the point, but whatever. I've been following what happened to what has become a "product" and will be using one of the forks in the future.

**Comment by petersampsonaudacity** [comment]
I think you'll find:

a) the forks are all based on 3.0.3 - or even 3.1.0 with the update checking and error reporting (networking stuff) removed.

b) At least one of the forks, the major one Tenacity, intend to be pulling future updates that Muse provide to the Open-source code in the future

Tenacity certainly seems to have adopted the modern clip handling for a start and as @LWinterberg pointed out above that leads to backwards incompatibility.

**Comment by SteveDaulton** [comment]
An interesting, and I believe relevant article here: https://www.soundonsound.com/techniques/transferring-projects-between-different-daws

**Comment by petersampsonaudacity** [comment]
> An interesting, and I believe relevant article here: https://www.soundonsound.com/techniques/transferring-projects-between-different-daws

See also Schofields First Law of Computing, which states:
>"Never put data into a program unless you can see exactly how to get it out."

See: https://www.theguardian.com/technology/2008/jul/10/it.security

_Jack Schofield was the technolgy columnist for The Guardian newspaper for many years. Over that time he gave me many useful computing insights through the medium of that paper.  sadly se is now dead RIP._
