### ISSUE TITLE
[Plugin issue] Crash when applying Soundly Shape It destructively

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#6971]
### Plugin

Soundly Shape It

### Plugin Format

Audio Unit

### Plugin source

MuseHub

### Steps to reproduce

1. generate chirp
2. select the plugin from the list
3. hit Apply button

### Expected behavior

The effect is applied.

### Actual behavior

A crash.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows, macOS

### Architecture

64 bit Intel/AMD processors, Apple Silicon (M1, M2, ...)

**Comment by saintmatthieu** [comment]
Looks indeed only to be for that plugin and only in destructive mode.

**Comment by saintmatthieu** [comment]
Spent an hour debugging and I'm already running out of ideas.
This seems to be the offending statement. Unfortunately this is `wxWidgets` code and I can't debug into it. I'd have to build the library, which I haven't managed out of the box.
The effect is from an extraneous company and is closed source, so I can't build it and debug. Just in case I sent a message to the company to see if we could get assistance.
![image (1)](https://github.com/user-attachments/assets/5700b932-6318-40cb-a5a4-787501b5fec8)

**Comment by petersampsonaudacity** [comment]
An underlying issue her is that ideally Audacity should "gracefully" handle the situation where 3rd party plugins fail to work and **NOT** inelegantly crash.

**Comment by saintmatthieu** [comment]
Of course, but so long as we execute third-party effects within the application process (and not spawn another process and implement inter-process communication), we cannot guarantee that it won't crash the application.

**Comment by saintmatthieu** [comment]
Just tested with a version of Shape it with a fix made available to me by @peterbjorgensen and team. Crash is gone - thanks for your help ! I expect it to be published to the Muse Hub in due time.

**Comment by peder1234** [comment]
Great! We've uploaded the fixed version to our website now as well, so you can get it at [here](https://getsoundly.com/tools/#shapeit).
