### ISSUE TITLE
visual bug when using the enveloppe tool

### ISSUE THREAD

**Issue by OperaG01** [audacity/audacity#6972]
visual bug when using the enveloppe tool

hello, I just updated to version 3.6.1 - now if I use the envelop tool to lower the volume of a track, and then raise it again - when I raise, the waves graphics remain practically flat, although I can hear the sound - it seems as if the graphic isnt picking up on the fact it needs to zoom back to the size according to the envelop factor.  similarly if on another track I try to lower the volume by reducing the envelope, the graphic stays as large although the sound is reducing as expected.

![image](https://github.com/user-attachments/assets/c36b43f9-a2af-4a01-8318-561c99972732)

**Comment by petersampsonaudacity** [comment]
This looks like this known and logged regression bug:
https://github.com/audacity/audacity/issues/6927

A developer worked on this yesterday and made a fix - I tested this in his test branch where it worked fine, so I would exp[ect to see this in the upcoming 3.6.2 release hopefully.

**Comment by OperaG01** [comment]
thank you - i apologize for the duplicate, I'm new to this referral process and wasnt familiar with where to look for other similar open issues.

thanks for sharing the info regarding the fix - looking forward to the new release :-)
