### ISSUE TITLE
Audacity 3.6.1 window goes black mid-recording of track.

### ISSUE THREAD

**Issue by jasonhoran** [audacity/audacity#6973]
### Bug description

Audacity 3.6.1 on Ubuntu 22.04.  When recording an audio track from the mic the dynamic display elements seem to go blank.  The track window disappears and the background goes to a darker black.  The timeline timer goes blank also, but the selection time remain.  The app can still record and the track can be paused, re-started, saved etc.  This happens at random time intervals.  Screenshots attached of i) normal behaviour when recording a track and ii) when the visual bug starts but recording can be paused/recommenced, etc.  Happens on multiple occasions at various short time intervals between 1 and 10 minutes.

![Audacity_1](https://github.com/user-attachments/assets/a7970997-68f6-4af5-8355-bc4405502656)

![Audacity_2](https://github.com/user-attachments/assets/7c83d054-b461-4d98-ae1c-6b23b1d425f3)

### Steps to reproduce

1 Commence recording of a track via the microphone
2 At some stage within the first number of minutes the Audacity window will go black/blank but recording will still continue.
3 Visible buttons seem to work.
4 Can be managed by i) saving project ii) exiting and iii) re-opening project.

### Expected behavior

This bug should not happen and normal visuals should continue throughout operation.

### Actual behavior

The track with waveform, timeline and scrollbar etc disappear.  The background colour changes to a deeper black and the timer goes blank.

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

File 1 - Track during normal operation
![Audacity_1](https://github.com/user-attachments/assets/87b9401c-9112-4b95-816a-20fbd18a27f2)

File 2 - Same track 8 minutes into recording where this visually occurs.
![Audacity_2](https://github.com/user-attachments/assets/b7b45026-3165-4884-8e47-4819816d61d6)

**Comment by wchouser3** [comment]
I can second this one. It's not just Ubuntu, I'm having the same problem on Arch, and Mint. It's not just recording either. I have the same thing happen right in the middle of editing. I tried the 3.7 Alpha and it has the same issue. I've also seen it on systems with Intel, AMD, and Nvidia cards. It effectively makes 3.6 and above useless until it's fixed.

**Comment by kryksyh** [comment]
@wchouser3 @jasonhoran could you try builds from this PR, to check if it fixes the issue for you?

**Comment by wchouser3** [comment]
It seems to have fixed it. I'm halfway through editing mintCast right now, and it hasn't gone blank yet

-- 
 Sent with Tuta; enjoy secure & ad-free emails: 
 https://tuta.com


Jul 26, 2024, 2:20 AM by ***@***.***:

**Comment by jasonhoran** [comment]
Can also confirm that it _appears_ fixed on single episode of testing.  Ran a recording for 11 minutes without incident.  That would be the longest that I have run a single segment without the problem occurring.

**Comment by emmFinalist** [comment]
Same specs here: Audacity 3.6.1 on Ubuntu 22.04

I think I have this exact same issue, but it happens when I'm scrolling or zooming. It can happen twice a second, or once every minute, so I'm not sure what triggers this behavior. I've added a video of 30s and could reproduce it twice. 
Scaling the window (in and out of full screen) redraws the dynamic display elements.

https://github.com/user-attachments/assets/1098b959-8ab6-422e-b995-422245a98466

**Comment by LWinterberg** [comment]
This will be fixed in 3.6.2, the fix is already merged.

**Comment by translateltd** [comment]
This has happened to me just now on ver 3.6.4 (Win 11).
