### ISSUE TITLE
Create new Legacy section for effects

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#6982]
### Your idea

Add a Legacy effects category containing 

* Classic Filters
* Legacy Compressor
* Legacy Limiter

### Problem to be solved

Currently, we remove obsolete effects, or ship them around disabled by default in the case of Classic Filters. in the case of Nyquist effects, this isn't catastrophic as they are just plugins, however, in the case of builtins, there's not really a way to use any effect we discontinue.

**Comment by petersampsonaudacity** [comment]
@LWinterberg  - you might want to consider adding back **Vocal Reduction and Isolation** to that Legacy section

**Comment by chinakov** [comment]
Tested. The Legacy plugins are usable, and are also available as macros.

**Comment by petersampsonaudacity** [comment]
I've already updayed the manual for this.

**Comment by QuantumGood** [comment]
👍
