### ISSUE TITLE
Audacity Hangs after Undo, and performing any action

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#6995]
### Bug description

If the User applies a destructive effect, undoes, and executes any new action - Audacity hangs. 

### Steps to reproduce

1. Launch Audacity
2. Add a Stereo Track
3. Generate a 12 hour chirp
4. Apply a destructive effect to the whole clip (Amplify, or Compressor)
5. Undo the destructive effect
6. Create a new Stereo Track
7. Observe Audacity hangs

### Expected behavior

Audacity shouldn't hang when a User executes a new action after undoing a destructive effect.			

### Actual behavior

Audacity hangs after executing a new action after undoing a destructive effect. 

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS, Linux

### Additional context

It seems that the bigger the 'undo buffer' is, the bigger the chance of it getting hanged. Simply, the longer the clip and the timeframe of the effect - the higher the chance.

**Comment by saintmatthieu** [comment]
The bug this commit fixed (but broke something else): https://github.com/audacity/audacity/issues/6321

**Comment by dozzzzer** [comment]
Tested. Discarding undo/redo history takes about 15 seconds on my machine, after which Audacity is fully operational.

<img width="500" alt="image" src="https://github.com/user-attachments/assets/9f33b853-2321-4f70-aa45-db61074578e1">
