### ISSUE TITLE
[AU4] Clips - Overlap trimming

### ISSUE THREAD

**Issue by DilsonsPickles** [audacity/audacity#6999]
Clips can overlap but on click release, the underlying clip is trimmed.

[Figma link](https://www.figma.com/design/01XLIICmy2AG6t1ieyTp66/Clips?node-id=1032-932)

**Comment by grliszas14** [comment]
QA bulletpoints:
* user should be able to move clip freely anywhere and above other clips (within the same track for now)
* overlapping logic should be triggered only on mouse release (when user holds left-mouse btn, nothing is done to other clips)
* if user releases mouse when clip hovers the other clip -> other clip gets trimmed, deleted or splitted into 2 (depending on a moved clip position)
* overlap logic is applied when: moving clips, trimming (extending) clips, and pasting from clipboard

**Comment by dozzzzer** [comment]
@grliszas14 

- When moving a clip to the zero time mark over another clip that starts from the zero time mark too, it produces a tiny clip at the beginning although it was supposed to be eaten by the other clip:

https://github.com/user-attachments/assets/f49e24c9-61b7-4771-b211-442e5819d3d7

**Comment by DavidBailes** [comment]
> Clips can overlap but on click release, the underlying clip is trimmed.
> 
> [Figma link](https://www.figma.com/design/01XLIICmy2AG6t1ieyTp66/Clips?node-id=1032-932)

I don't think this trimming is very user friendly. If the whole of the clip that the user is moving is not visible, then when moving a clip trimming/deletion can occur off-screen, and therefore not immediately noticed.
Are there any other audio editors/DAWs which have this behaviour?
It may be difficult to make this behaviour user friendly for users of screen readers.

**Comment by DavidBailes** [comment]
> We've designed this as a stepping stone towards our end goal of non-destructive overlapping clips. Both Ableton and Cakewalk Next have this behaviour.

@DilsonsPickles Do Ableton and Cakewalk have non-destructive overlapping clips, or this trimming behaviour?

**Comment by DilsonsPickles** [comment]
This trimming behaviour. I should also mention that technically this is non-destructive as the audio data is not removed, just trimmed. When I say non-destructive overlapping I should say "clips can overlap without the need for trimming".

**Comment by dozzzzer** [comment]
Tested
