### ISSUE TITLE
Export multiple with a master effect can lead to silence in exported files.

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#7001]
### Bug description

This only seems to effect export multiple for mono tracks.
The problem only occurs for some effects.
Effects that I tested where the problem occurs: the MuseFx effects: reverb, pitchfix and de-ess, and Tokyo dawn labs: TDR Kotelnikov. Reported on forum: Graillon 2.
Effects that I tested where the problem does not occurs: builtin reverb, and builtin bass and treble.

### Steps to reproduce

1. Create two audio tracks, and make sure they have different names.
2. Add the MuseFX reverb effect to the master effects.
3. Export multiple.
4. Import the two files that were just exported.

### Expected behavior

The audio in  the imported files should be as expected

### Actual behavior

The audio in the imported files is silence.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

### Additional context

Reported on forum: https://forum.audacityteam.org/t/master-effects-making-exports-silent/112780

**Comment by dozzzzer** [comment]
Tested
