### ISSUE TITLE
Export with a master effect can lead to silence in exported file

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#7002]
### Bug description

See related bug: https://github.com/audacity/audacity/issues/7001

Probably only occurs for some effects, as in the case of the related bug, but haven't tested.

### Steps to reproduce

1. Create a mono audio track
2. Add the MuseFX reverb effect to master effects.
3. Export the audio.
4. Import the file that was just exported

### Expected behavior

The audio in the imported file is as expected.

### Actual behavior

The audio in the imported file consists of silence.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by vsverchinsky** [comment]
Same with mono track with per track effects applied and exported using channel mapping (one to many)

**Comment by dozzzzer** [comment]
Tested
