### ISSUE TITLE
Crash when exporting audio as m4a

### ISSUE THREAD

**Issue by nimrodyanai** [audacity/audacity#7004]
### Bug description

When trying to export audio in m4a format, Audacity crashes. It worked fine with the previous version.
Exporting as mp3 worked.

### Steps to reproduce

1. Import or create any audio.
2. Go to file->export as
3. Try to save as m4a (make sure you have all the dependencies installed)

### Expected behavior

File is saved as m4a.

### Actual behavior

Crash.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

### Additional context

Sending crash reports doesn't work either, and the crash text is too long to paste here.

**Comment by dozzzzer** [comment]
Could not reproduce on Windows 11 VM as well as Windows 10.

https://github.com/user-attachments/assets/5e75689c-a916-42dd-9be9-08de96eca5be

**Comment by gpkwok** [comment]
This reproduced for me on Windows 11 with version 2.4.2 of ffmpeg for Audacity. Uninstalled that and reinstalled latest version 5.0.0 from https://lame.buanzo.org/ffmpeg.php and now it longer crashes.
