### ISSUE TITLE
All the UI does not respect fractional scaling on x11

### ISSUE THREAD

**Issue by Emily511511** [audacity/audacity#7005]
### Bug description

Audacity does not respect fractional scaling at all under x11 on Linux, all UI elements are tiny

### Steps to reproduce

1.Open Audacity
2.Look at the tiny UI

### Expected behavior

UI elements should scale

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

I have tested this on KDE 5.27.11 on x11

**Comment by LWinterberg** [comment]
HiDPI is not supported on Linux (or anywhere, for that matter) at the moment. We're in the process of switching UI framework which will have support for that.
