### ISSUE TITLE
crash on applying reverb to lossless audio

### ISSUE THREAD

**Issue by Matto58** [audacity/audacity#7006]
### Bug description

trying to apply reverb to an arbitrary piece of lossless audio crashes audacity

### Steps to reproduce

1. open any lossless audio file with audacity
2. select it
3. go to effect > audacity > reverb
4. click apply

### Expected behavior

reverb gets applied correctly

### Actual behavior

audacity shows a pre-processing window for a moment and then closes/crashes

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

i'm using a raspberry pi 5 btw

**Comment by dozzzzer** [comment]
No crash on my end. Ubuntu 22.04 VM; current master (Appimage).

https://github.com/user-attachments/assets/6e1a88bd-1c24-41cb-b50b-869f3cea9d6f

**Comment by Matto58** [comment]
weird, may be an issue with something on my end, i just followed the steps to build audacity as specified in BUILDING.md

**Comment by Matto58** [comment]
ok it seems to crash with lossless audio files, this being the output when it crashes:
```
11:38:39: Debug: LastOpenType is 
11:38:39: Debug: OverrideExtendedImportByOpenFileDialogChoice is 1
11:38:39: Debug: Appending libsndfile
11:38:39: Debug: Appending libav
11:38:39: Debug: Appending legacyaup
11:38:39: Debug: Appending liboggvorbis
11:38:39: Debug: Appending libflac
11:38:39: Debug: Appending libmpg123
11:38:39: Debug: Appending lof
11:38:39: Debug: Appending libwavpack
11:38:39: Debug: Appending portsmf
11:38:39: Debug: Appending libopus
audacity: /home/matto/audacity/libraries/lib-wave-track/WaveClip.cpp:2047: WaveClip::StrongInvariantScope::~StrongInvariantScope(): Assertion `mClip.StrongInvariant()' failed.
Aborted
```
i tried it with 2 lossy files (both mp3) and it doesnt crash when i apply reverb to them

**Comment by Matto58** [comment]
apparently i wasn't using the latest commit, i forgot to `git pull` as well when i `git fetch`ed and i was actually working with audacity as of 23rd july 1pm utc (caja claims Tue 23 Jul 2024 15:38:20 CEST), imma try recompiling audacity to see if this has been fixed suddenly

**Comment by LWinterberg** [comment]
heya! We don't support Arm at the moment, so we won't be fixing this. Note that assertions are only active in debug builds, if you build a release build (which you can get from the source tar.gz, not the ZIP file), it shouldn't happen. 

Alternatively, feel free to debug and send a patch/PR - it's just that we don't have the capacity to do anything about it.

**Comment by Matto58** [comment]
oh okay thanks!!
