### ISSUE TITLE
Copy & Paste not working in AppImage

### ISSUE THREAD

**Issue by lgmventura** [audacity/audacity#7007]
### Bug description

When a piece of a track is copied and pasted, a message box appearing telling the file format of the executable file itself is unknown.

### Steps to reproduce

1. Create a new file and record something or open an existing audio
2. Select something
3. Copy or cut
4. Put the cursor somewhere
5. Paste

### Expected behavior

The audio would be pasted at the cursor.

### Actual behavior

A message box of type "info" with the text `Could not open file /path/to/-audacity-linux-3.6.1-x64: Incorrect filetype`. (Notice the - just before the executable file name).

After clicking OK, another message box entitled "Error Importing" with the text:
```
Audacity did not recognize the type of the file '/path/to/audacity-linux-3.6.1-x64'.

For uncompressed files, also try File > Import > Raw Data.
```
This time without the -.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Linux

### Additional context

System: Ubuntu 22.04.

The executable file was downloaed automatically by version 3.5.1, with no extension ".AppImage". Appending the extension onto the file name doesn't change the behaviour except for showing it in the message boxes in the file name, of course.

In version 3.5.1 copy & paste is working fine.

**Comment by dozzzzer** [comment]
Could not reproduce it. Ubuntu 22.04 VM; 3.6.1 Appimage

https://github.com/user-attachments/assets/a6cc6eff-ba43-4776-8ce8-0f143f1afb9f

**Comment by lgmventura** [comment]
Today it's working. I don't know what the problem was, I think I haven't even logged out and in, only put the PC to sleep. I'll close then for now. Thanks, @dozzzzer
