### ISSUE TITLE
Replacing the word "insane" in the Quality drop-down menu in the Export Audio dialog with another word

### ISSUE THREAD

**Issue by carotteatomique** [audacity/audacity#7008]
### Your idea

The word "insane" has ableist roots, and even if it is (unfortunately) commonly used in English to create an exaggeration, it's still offensive to many disabled and neurodivergent people, because its ableist connotations are still there.

Replacing this word in the drop-down menu would be a very easy way to not make disabled and neurodivergent people uncomfortable while they use Audacity. This is also a good opportunity to express creativity by picking a word of exaggeration that's more fun!

Some personal suggestions: preposterous, unbelievable, outlandish, ludicrous, unconscionable…

All of these words get across the same idea that the audio quality is incredibly good, without using ableist language!

### Problem to be solved

![The Audacity Export Audio window, the drop-down menu for quality has the options Medium, Standard, Extreme, and Insane](https://github.com/user-attachments/assets/658dd4c2-2215-4fdd-8a0e-427746244e7d)

### Additional context

Please read this if you think this is a non-issue: [BBC article about the impacts of ableist language](https://www.bbc.com/worklife/article/20210330-the-harmful-ableist-language-you-unknowingly-use)

**Comment by LWinterberg** [comment]
Yeah, this is an artifact of early 2000s LAME preset naming. What needs to get across here is that

* Standard is transparent for most content
* Extreme (LAME -V0) is the highest VBR encoding and transparent for all content
* Insane (LAME -B320) maxes out the bits MP3 is allowed to use for no quality gain compared to Extreme

I wonder if Wasteful would be a good replacement for Insane here.

**Comment by petersampsonaudacity** [comment]
Curiously we have had the existing "Insane" and "Extreme" terminology in the MP3 Export dialog since version 1.3.3, which was released on 18May2007.

And no-one has ever mentioned this before ...

@LWinterberg wrote:
> I wonder if Wasteful would be a good replacement for Insane here.

I am minded to agree with Leo here - but I would suggest that in place of Insane we use **Profligate** or **Excessive**, with a minor preference for the former (my "Mystery-Shopper likes "Profligate" too)


**Use Case**
My son, _who is a bit of a purist_, insisted on using 320 when he was building his iTunes library and was surprised to find his iPod filled up well before he had completed the library!

**Comment by LWinterberg** [comment]
I like Excessive. It's the more common word, so non-native English speakers (including probably all of our translators) are more likely to have a good idea what we mean with that.

![image](https://github.com/user-attachments/assets/3b47305f-d853-4fbc-a92e-3915da40de96)

**Comment by petersampsonaudacity** [comment]
> I like Excessive.

OK, I'll buy that - **Excessive** will be absolutely fine as a replacement for **Insane**

**Comment by dozzzzer** [comment]
Tested

**Comment by petersampsonaudacity** [comment]
Tested on W11 with @BigDataStructure 's latest branch test build for this:  audacity-win-3.7.0-alpha-20240802+e26b6fa-x64

Looks good to me:
![image](https://github.com/user-attachments/assets/a7d10358-e5ed-44a3-8ce0-4e4508b1c91e)

@LWinterberg  is this for 3.6.2 or is it to wait till 3.7.0 ?

**Comment by LWinterberg** [comment]
We just sent out translations for 3.6.2, so 3.7 it is.

**Comment by petersampsonaudacity** [comment]
@LWinterberg 
Thanks for that.
I was primarily basking for documentation purposes, updating the manual.

And although we make the change here in the Audacity app, I note that the Manula has a LAME information link to the HydrogenAudio site, where, of course, thaey are still using "**Insane**"
https://wiki.hydrogenaud.io/index.php?title=LAME

I guess I could just remove that link, as I'm not convinced that users really need that level of detail.
Do you have any thoughts on that Leo?
https://manual.audacityteam.org/man/mp3_export_options.html#setup

**Comment by Gitoffthelawn** [comment]
@carotteatomique Thank you for this issue report and for teaching me a new English word, *ableist*.  I knew the concept, but I did not know there was a corresponding word in English.  Thanks! ❤️

**Comment by TheManFromBlackwater** [comment]
Grow a spine after you cry me a river.
