### ISSUE TITLE
Closing file with CTRL-W leads to Audacity crash

### ISSUE THREAD

**Issue by Germano0** [audacity/audacity#701]
Closing file with CTRL-W leads to Audacity crash
Fedora 33
audacity-freeworld-2.3.3-5.fc33.x86_64 from RPM Fusion repository
[audacity_crash_report.zip](https://github.com/audacity/audacity/files/5665460/audacity_crash_report.zip)

**Comment by SteveDaulton** [comment]
Thanks for the report.
If you are the package maintainer, please contact us via the [developer's mailing list](https://www.audacityteam.org/contact/mailing-lists/).
We are not able to do anything about this as Audacity 2.3.3 is an old version and we have no reports of this problem with the current version. The current release version is 2.4.2 and the development version is 3.0.0 alpha.
