### ISSUE TITLE
Native support of MSU1 format PCM files

### ISSUE THREAD

**Issue by edale2** [audacity/audacity#702]
**Is your feature request related to a problem? Please describe.**

I do a lot of audio work with PCM files (.pcm; not pcm encoded .wav) that use a non-standard 8-byte header. As a result of this, I am unable to drag and drop them into Audacity, and have to import them as raw data instead.

**Describe the solution you'd like**

I would like Audacity to support automated importing of these PCM files. Whether natively or through a plugin.

**Describe alternatives you've considered**

ATM, my only option is to manually import the files as raw data.

**Additional context**

The non-standard 8-byte header used by the PCMs, when viewed in a hex editor, is "MSU1####" (the #### is a pointer to the file's loop point, and can be ignored)

The audio settings for these files is:
Encoding: Signed 16-bit PCM
Byte Order: Little-endian
Channels: 2-Channels (Stereo)
Start Offset: 8 bytes
Amount to Import: 100%
Sample Rate: 44100 Hz

Any and all PCM files with the MSU1 header will have these settings.

![Untitled](https://user-images.githubusercontent.com/20962345/102021458-ef35f900-3d4d-11eb-97af-f5c5c37b7c83.png)

For context MSU1 format PCM files are used for MSU-1 mods to SNES games. An MSU-1 mod allows SNES games to play CD quality audio in such a way that the CD quality sound will even play on an original unmodded SNES system.
You can see an example of a MSU-1 mod in action here: https://www.youtube.com/watch?v=v788KslHvbU

**Comment by edale2** [comment]
Thought I'd provide some more info, in case it helps this get added:

Here's a MSU1 format PCM as viewed in a hex editor, with the 8 byte header highlighted:
![image](https://user-images.githubusercontent.com/20962345/102788737-1b1a3580-4371-11eb-8321-7dc9b57ed6c7.png)
That track is a non-looping track which is why the 4 byte loop value is all zeros (but like I said, Audacity can ignore that part of the header anyways).

And here's a short MSU1 format PCM that can be used for testing purposes:
[alttp_msu-1.zip](https://github.com/audacity/audacity/files/5724906/alttp_msu-1.zip)

**Comment by SteveDaulton** [comment]
I think this can be done  by writing a Nyquist Plug-in (https://wiki.audacityteam.org/wiki/Nyquist_Plug-ins_Reference)
using the "S-READ" command (https://www.cs.cmu.edu/~rbd/doc/nyquist/part8.html#index663).

If you require help writing a suitable plug-in, support is available via this board in the Audacity support forum:
https://forum.audacityteam.org/viewforum.php?f=39

As MSU1 files are very much a niche interest, I doubt that support will ever be incorporated into the main program, though a successful plug-in could be distributed via the Audacity wiki (https://wiki.audacityteam.org/wiki/Download_Nyquist_Plug-ins).
I shall therefore close this issue for now, but we can reopen it if it proves impossible to implement with Nyquist.

**Comment by Pokechu22** [comment]
Probably the right place to implement something like this would be in FFmpeg; they already implement a large number of esoteric audio formats.  (Though, Audacity also doesn't have the latest version of FFmpeg IIRC).
