### ISSUE TITLE
Crash on dragging audio samples into session

### ISSUE THREAD

**Issue by samuel-davidson** [audacity/audacity#7020]
### Bug description

When dragging an external audio sample into the session, audacity crashes.  Freezes for a second or two then crashes and closes out.  

### Steps to reproduce

1. Drag audio sample from original location into the session 

### Expected behavior

Audio file is placed into session in a new or current audio track.  

### Actual behavior

Crash

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS

**Comment by petersampsonaudacity** [comment]
I cannot reproduce this on W11 with 3.6.1 and tha latest Beta test build for 3.6.2

**Comment by dozzzzer** [comment]
@samuel-davidson could you try out 3.6.1 and see if it fixes your problem?
