### ISSUE TITLE
Importing a multi-channel OGG file (.mogg) will only import the first channel

### ISSUE THREAD

**Issue by daniel-rodrigue** [audacity/audacity#7025]
### Bug description

Prior to Audacity 3.6.0, opening a multi-track OGG file (.mogg) would load all the streams in separate tracks. Now, it will load only the first track. 

### Steps to reproduce

1. Open a .mogg file that has multi-tracks in it [SAMPLE](https://github.com/user-attachments/files/16520383/h9h6ru.mogg.zip)

2. Notice only the first track is loaded & displayed.

### Expected behavior

Expecting to see all the tracks contained in the file.

### Actual behavior

Only 1 track is loaded. Audacity 3.6.0 & 3.6.1 has the problem.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS, Windows

**Comment by genfail** [comment]
Just updated to 3.6.1
Tried with multiple mogg files, only opens first channel.
Tried with mogg files from the internet and also some own created. Same result. 
In my previous audacity version 3.4?? it just worked.

**Comment by dozzzzer** [comment]
Tested

**Comment by Aphexus** [comment]
Same.
