### ISSUE TITLE
Mac: Keyboard Navigation not working for Modal Dialogues? (ie. Popup Hotkeys broken)

### ISSUE THREAD

**Issue by BlinksTale** [audacity/audacity#7031]
### Bug description

Not sure if feature request or bug: In Photoshop and all other programs I know, a popup when closing an unsaved file says "Are you sure?" and "Save" "Don't Save" "Cancel". In all others, you can hit Cmd+S, Cmd+D, Cmd+C for each respective answer. In Audacity, this doesn't work. I couldn't find the formal name for this feature on Apple's docs, but is this supposed to work? It feels like a bug but it might be a feature request.

### Steps to reproduce

1. Open Audacity on latest MacOS with some file
2. Make some change, eg. copy/paste part of a track onto itself
3. Hit Cmd+W to close the file without saving
4. See modal dialogue / "Save changes?" popup
5. Press Cmd+N for "No" or Cmd+C for "Cancel"

### Expected behavior

Hotkeys would select relevant option, eg. "No" or "Cancel" here successfully

### Actual behavior

No changes, standardized hotkeys for this situation do not apply

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS

### Additional context

I'm on Audacity 2.4.2, but upgraded to 3.6.1 (or whatever latest is today) and found the issue applied in both, so I went back to 2.4.2 for now - the new interface looks like a major change and I don't want to relearn much if I have no benefit to upgrading.

**Comment by LWinterberg** [comment]
Are you certain it's Cmd here? On Windows, this works with Alt (which on mac usually translates to Option, though I see that accessibility is bound to Control in some cases too on macOS).

**Comment by BlinksTale** [comment]
> Are you certain it's Cmd here? On Windows, this works with Alt (which on mac usually translates to Option, though I see that accessibility is bound to Control in some cases too on macOS).

Fascinating - I looked into this, and for Photoshop: you are correct! Photoshop works with Ctrl, Options, and Cmd for these modal popups. For Audacity: none of them work.

However: Esc does work for "Cancel" for both, so that's good.

However However: Now I'm actually worried, because I am failing to find a second app where the Cmd+Letter is testable for modals this way on Mac. I feel very strongly that I've seen it before, but there's a chance it's actually just a photoshop thing. I really could have sworn this is in more than just that app? I'm so sorry if I'm wrong here. I really could swear, but I don't have evidence to reproduce it elsewhere yet.

Hopefully someone else sees this that is wiser than me and knows an app to confirm with, but otherwise we should just close this as my misunderstanding. I'm so sorry if so.

**Comment by LWinterberg** [comment]
@dozzzzer do you happen to know how to use keyboard accelerators on macOS?

**Comment by dozzzzer** [comment]
@LWinterberg no, not really, but I ran a quick test in Ableton, Reaper, Oceanaudio, Snagit and VSCode. None of them react to the keyboard accelerators when closing a project.

**Comment by LWinterberg** [comment]
@DavidBailes do you happen to know anything about this? If this is just macOS doing macOS things, I guess this can be closed

**Comment by DavidBailes** [comment]
> @DavidBailes do you happen to know anything about this? If this is just macOS doing macOS things, I guess this can be closed

my usage of MacOs is limited, but my understanding is that on macOS there isn't the equivalent of access keys in the names of controls in dialog, and there is no standard behaviour specified for having shortcuts such as Cmd+S, Cmd+D, Cmd+C for Save, don't save, etc. It's just a case of some software is written so that you can press  buttons using the first letter with or without a modifier.
In other words, this issue can be closed.

**Comment by BlinksTale** [comment]
Thanks for looking into this all! Rip Mac, my fault for thinking the OS standardized this. Might be a nice to have feature someday (I just love it in Photoshop is all, great for workflow imo, but I can look into alternatives for now)
