### ISSUE TITLE
Audacity locks onto audio device

### ISSUE THREAD

**Issue by tarun612** [audacity/audacity#7033]
### Bug description

Audacity locks onto audio device and doesn't let go of the audio device

### Steps to reproduce

1. Launch audacity.
2. Launch an application and play a music track in it.

### Expected behavior

Able to hear audio from the OS.

### Actual behavior

Unable to hear audio

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

**Comment by LWinterberg** [comment]
Can you check if that still happens with https://github.com/audacity/audacity/pull/6851 ?

**Comment by dozzzzer** [comment]
@tarun612 ^

**Comment by tarun612** [comment]
Works with the new alpha build
