### ISSUE TITLE
Missing tracks (instead of horizontal scrollbar)

### ISSUE THREAD

**Issue by Vladimyr0** [audacity/audacity#7036]
### Bug description

All tracks are missing after scroll

### Steps to reproduce

1. open or create a track (e.g. genetare dtmf tone)
2. zoom into it till horizontal scrollbar appeared
3. scroll it left and right for a few seconds (with scrollbar or mini-hand cursor, it doesn't matter)
4. track is gone! (scrollbar is still in place)
5. maximize or restore window to bring the track back

### Expected behavior

scrolling the track right and left flawlessly

### Actual behavior

track vanished

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

### Additional context

tested this on 3.6.1, installed by debs from there: [audacity - 3.6.1-0build1~ubuntu24.04](https://launchpad.net/~ubuntuhandbook1/+archive/ubuntu/audacity/+sourcepub/16282715/+listing-archive-extra) 
and there: [3.6.1+dfsg-1](https://launchpad.net/ubuntu/+source/audacity/3.6.1+dfsg-1)
Appimage version 3.6.1 on my system (Ubuntu 24.04 64-bit) has different decorations and has no horizontal scrollbar (as it was specified in the issue #2937) and hence no this problem 

fig.0 - deb package
![a0](https://github.com/user-attachments/assets/e976523e-b823-4a4c-847b-76ba4f5314aa)

it seems that disappearing scrollbar was fixed, but tracks were broken instead! 

fig.1 - Appimage
![a1](https://github.com/user-attachments/assets/572e6978-c43b-4c2a-b29f-700c40a06a99)

disappearing scrollbar is not fixed yet

**Comment by LWinterberg** [comment]
This is fixed by https://github.com/audacity/audacity/pull/6955, which will be released with 3.6.2
