### ISSUE TITLE
Multi-tool not "sticking" when selected before closing Audacity

### ISSUE THREAD

**Issue by raichea** [audacity/audacity#704]
**Describe the bug**
According to the manual, if the multi-tool is selected prior to Audacity beings closed, it should be active when Audacity is next opened. In v2.4.2, it isn't, the Select tool is always selected.

**To Reproduce**
1. Open Audacity
2. Select the multi-tool
3. Do some editing
4. Close Audacity
5. Open Audacity again to find the Select tool is active

**Expected behavior**
As per the description, the Multi-tool should be selected when Audacity is reopened

**Screenshots**

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version Audacity 2.4.2

**Additional context**
I hadn't used Audacity for a while, so updated to latest version and noticed I had to keep selecting the multi-tool, which I didn't have to for the previous version (didn't notice the version, sorry).

**Comment by SteveDaulton** [comment]
Thanks for the report. This was discussed recently but as far as I can see it was not logged, so I'll log it on the issue tracker.

**Comment by SteveDaulton** [comment]
Ignore  my previous comment - it was logged, I just failed to find it until I started logging it again.
https://bugzilla.audacityteam.org/show_bug.cgi?id=2503

Additional information: you can select the multi-tool with the F6 key.

**Comment by raichea** [comment]
Thanks - I was aware of F6.

I just took a look at the logged issue and see that it was closed leaving this behaviour as it is. I think that's a pity. As someone who does use multi-tool, it's irritating to have to click it each time I start the program. As I'm used to it sticking, it's usually after a moment of puzzlement as to why it's not working. 

I understand the problem of someone being "locked" in multi-tool mode, but it doesn't take long to figure that out. With things as they are, we multi-tool users are left having to remember to do that click every time we start the program. Making the behaviour an option would be the best solution, I guess, as noted in the bug, but even restoring the older behaviour would be better (in my, admittedly, biased opinion).

**Comment by SteveDaulton** [comment]
You would be surprised at the number of times we see this problem: https://forum.audacityteam.org/viewtopic.php?p=410597#p410597 (and no doubt there are many more that don't come to the help forum).

**Comment by raichea** [comment]
I'm sure you're right... IIRC, I ran into the issue myself when I first started using Audacity. Making it an option would be ideal, but no doubt I'll get used to the way things are now. It doesn't diminish Audacity in any way - still a nice bit of software.
