### ISSUE TITLE
[AU4] Add new track - Styling

### ISSUE THREAD

**Issue by DilsonsPickles** [audacity/audacity#7043]
Styling for add new track area at top of track header panel.

[Figma link](https://www.figma.com/design/nyZYwPeeStYTIzxIeKmYxa/Track-header-panel?node-id=393-7307)

**Comment by dozzzzer** [comment]
I believe the default state color for the button and the grab handle is wrong. @DilsonsPickles could you confirm?

<img width="459" alt="image" src="https://github.com/user-attachments/assets/c8fe508e-71d0-44e8-b304-1b721fb57a63">

**Comment by grliszas14** [comment]
@dozzzzer good one! I didn't notice it before: colors were set accordingly to the design but the default button's opacities were changing it a bit. Fixed this, you can have a look again

**Comment by dozzzzer** [comment]
@grliszas14 what about the hover state color? It feels a bit too light to me.

https://github.com/user-attachments/assets/c07136c0-2c52-4b1f-8026-de4061f86666

**Comment by DilsonsPickles** [comment]
Good spot, yeah that hover state is pretty bright! Other hover states look correct so perhaps it's local to that component.

**Comment by grliszas14** [comment]
Fixed it too, hope that's ok now 😄 (button didn't have underlying color set... so anytime you hovered over it, its color was set to proper color with proper opacity but it was blending with bare white...)
