### ISSUE TITLE
Audio Clip loses Data after Recording

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#7048]
### Bug description

If the User decides to record a stereo audio clip, then splitting the resulting audio clip, and recording again, after stopping the recording the resulting and previous audio clips become empty.

### Steps to reproduce

1. Launch Audacity
2. Make sure you're recording in Stereo, and record some audio
3. Split the resulting Stereo track into Mono tracks, or just split them.
4. Place playhead after the clip, press record again.
5. Stop the recording
6. Observe result

### Expected behavior

The resulting clips are empty.

### Actual behavior

The resulting clips shouldn't be empty.

https://github.com/user-attachments/assets/345bba58-3665-4343-a6f9-49f023e55ee0

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by dozzzzer** [comment]
Cannot reproduce on Windows 11 / Audacity 3.6.1:

https://github.com/user-attachments/assets/d3995aa4-2323-4f37-83dd-5eadf0f406d3

**Comment by chinakov** [comment]
Confirmed to be introduced together with the mentioned issue in https://github.com/audacity/audacity/commit/aaac5fd452549dfb6791b5d58d61fe97e04ebd75 

Thank you, @dozzzzer

**Comment by chinakov** [comment]
Tested, thanks
