### ISSUE TITLE
Right channel's data gets duplicated onto the left channel when recording in stereo on a split stereo track

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7050]
### Steps to reproduce

1. Generate chirp
2. Generate tone
3. Select both tracks and make a stereo track
4. Split stereo track
5. Make sure recording channels is set to '2'
6. Make sure the stereo input signal has distinct Left and Right channels that are different from one another
7. Put the cursor after the clips and click Record
8. Click Stop
9. Observe

### Expected behavior

As soon as the recording begins, the left and right channels' data remains untouched.
As soon as the recording is stopped, the data from the left and right channels is recorded in two separate clips. The two existing clips also remain unchanged.

### Actual behavior

As soon as the recording begins, the data of the left channel (chirp) gets duplicated onto the right channel (bottom mono track).
As soon as the recording is stopped, the recorded as well as existing audio data from the right channel is duplicated onto the left channel (the top mono track).

https://github.com/user-attachments/assets/b117150d-1190-446e-b9f1-6dbd71e589a5

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, macOS

### Additional context

Probably the same issue as https://github.com/audacity/audacity/issues/7048

**Comment by dozzzzer** [comment]
Bisects to https://github.com/audacity/audacity/commit/983dc1b7c7fd5008fd40420fefe6b63d68cd6a77

**Comment by dozzzzer** [comment]
More exact bisection: https://github.com/audacity/audacity/commit/aaac5fd452549dfb6791b5d58d61fe97e04ebd75

**Comment by dozzzzer** [comment]
Tested

**Comment by petersampsonaudacity** [comment]
@dozzzzer @kryksyh 

This looks to be fixed in that latest 3.6.2 Beta.

I think this isue could be closed.
