### ISSUE TITLE
Errors in windows build instructions and missing ASIO support in 2.4.2

### ISSUE THREAD

**Issue by SteveALee** [audacity/audacity#708]
**Describe the bug**

The Windows [build instructions](https://github.com/audacity/audacity/blob/master/win/build.txt) (also in wiki) have a couple of errors

1. [checkout 3.1.3](https://github.com/audacity/audacity/blob/master/win/build.txt#L28) is ambiguous. there is a tag `v3.1.3` but I'm guessing you meant branch `audacity_fixes_3.1.3` as that has more recent commits? That is the default branch anyway.
1. Cannot use cmake without installing it as VS 2017 comes with a version lower than that specified in the [CMakeLists.txt](https://github.com/audacity/audacity/blob/master/CMakeLists.txt)

I found these when updating my [easy ASIO build script](https://gist.github.com/SteveALee/da24c2be633340b8791066dd98eb5d0b/edit) to Audacity 2.4.2

**Comment by SteveALee** [comment]
The ASIO support also seems to have stopped working on 2.4.2 as well. Did something change there as well?

**Comment by SteveALee** [comment]
Yes the portaudio project file is missing the optional parts logic found in 2.4.1

**Comment by SteveDaulton** [comment]
I'm not sure if it's relevant, but I noticed a while back (2018) that PortAudio included ASIO SDK in their source code. I was surprised to see that as I was under the impression that Steinberg's license prohibited that. PortAudio have since removed the ASIO SDK from their source code.

**Comment by SteveALee** [comment]
@SteveDaulton Interesting slip there. The PortAudio v19 included in Audacity does not include the SDK code. hence the need to set up build and link to it, which is what has been dropped from Audacity 2.4.2

**Comment by SteveALee** [comment]
So having submitted PR #709 to Restore ASIO, I find there is a fix on master but not yet released. Just goes to show that you should always engage with the communit first or run this risk with "drive by" patches :) I did seach the issues but not those closed. Anyway, I learnt more about the code base and CMake. Plus it was some Christmas fun to distract me from practicing bass.

I'll leave this issue open as I made the mistake of mixed topics on one issue. For my [scripted build](https://gist.github.com/SteveALee/da24c2be633340b8791066dd98eb5d0b) I'll stick to 2.4.1 or point to my fork of 2.4.2 untill the ASIO support is restored in a future release.

**Comment by crsib** [comment]
ASIO is a build switch in 3.1+. There is no easy way to backport it to 2.4.2
