### ISSUE TITLE
Blank screen when recording

### ISSUE THREAD

**Issue by antonbutanaev** [audacity/audacity#7087]
### Bug description

I have two stereo tracks: first with some music, second empty. Then I start recording on 2nd track, caret moves to the right and at some point app screen, the area with tracks, gets blank. After resizing window, it gets correct again

There is no such problem in version 1:3.5.1-3, but it does appear in 1:3.6.1-2

Arch linux, xorg, xfce-4.18.6

### Steps to reproduce

1. Import audio in 1st stereo track
2. Add another stereo track
3. Start recording on 2nd track
4. After some time screen area with tracks becomes blank

### Expected behavior

Screen area with tracks always visible

### Actual behavior

Screen area with tracks becomes blank

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

**Comment by dozzzzer** [comment]
This is fixed by https://github.com/audacity/audacity/pull/6955, which will be released with 3.6.2
