### ISSUE TITLE
Audacity maxes out on a CPU core when recording in a minimized state

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7093]
### Steps to reproduce

1. Start Audacity
2. Minimize it
3. Observe the load on the CPU

### Expected behavior

CPU load remains the same as in the maximized (default) state of the Audacity window.

### Actual behavior

One CPU core will max out at around 100% when Audacity is minimized.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by DavidBailes** [comment]
See also: https://github.com/audacity/audacity/issues/4781

**Comment by dozzzzer** [comment]
Tested! CPU usage doesn't increase anymore when Audacity is minimized.
