### ISSUE TITLE
Waveform screen goes blank when zooming

### ISSUE THREAD

**Issue by ChandigarIT** [audacity/audacity#7108]
### Bug description

When I am zooming in on a section, the wave form tracks disappear and the window goes blank. Resizing the window sometimes fixes the problem but not always.

### Steps to reproduce

Use the Ctrl and mouse wheel. Works for so far, then flips to blank, see screen cast.

### Expected behavior

Should stay with the tracks showing.

### Actual behavior

https://github.com/user-attachments/assets/60a366b2-3e71-4bbe-bc94-b5bd55d815ff

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

### Additional context

Audacity 3.6.1

Program build date:
Jul 22 2024
Commit Id:
No revision identifier was provided
Build type:
CMake Release build (debug level 1), 64 bits
Compiler:
GCC 13.3.0
Installation Prefix:
/usr
Cache folder:
/home/malcolm/.cache/audacity
Settings folder:
/home/malcolm/.config/audacity
Data folder:
/home/malcolm/.local/share/audacity
State folder:
/home/malcolm/.local/state/audacity
Core Libraries
wxWidgets
(Cross-platform GUI library)
3.2.5
PortAudio
(Audio playback and recording)
v19
libsoxr
(Sample rate conversion)
Enabled
File Format Support
libmpg123
(MP3 Import)
Enabled
libmp3lame
(MP3 Export)
Enabled
libvorbis
(Ogg Vorbis Import and Export)
Enabled
libopus
(Opus Import and Export)
Enabled
libid3tag
(ID3 tag support)
Enabled
libflac
(FLAC import and export)
Enabled
libtwolame
(MP2 export)
Enabled
ffmpeg
(FFmpeg Import/Export)
Enabled
Features
Nyquist
(Plug-in support)
Enabled
LADSPA
(Plug-in support)
Enabled
Vamp
(Plug-in support)
Enabled
Audio Units
(Plug-in support)
Disabled
VST
(Plug-in support)
Enabled
LV2
(Plug-in support)
Enabled
PortMixer
(Sound card mixer support)
Enabled
SoundTouch
(Pitch and Tempo Change support)
Enabled
SBSMS
(Extreme Pitch and Tempo Change support)
Enabled

**Comment by LWinterberg** [comment]
Probably also fixed by https://github.com/audacity/audacity/pull/6955

**Comment by eric-gilbertson** [comment]
Is there some convenient way to refresh the lost track waveforms? Currently I try resizing the app until they reappear but this is pretty much hit & miss.

**Comment by mihailim** [comment]
@eric-gilbertson Yup. After it happens, go to Edit -> Preferences, don't change anything, but click the OK button (not the Cancel button, that won't help!) This will re-render the entire interface as a side effect, until it happens again of course. Annoying,b ut usable workaround.

@LWinterberg I can confirm #6955 fixes the bug: built 3.6.1 with just that patch and it doesn't reproduce for me any longer. Thank you for pointing us to it!
