### ISSUE TITLE
Color of waveforms

### ISSUE THREAD

**Issue by stefaniecg** [audacity/audacity#7111]
### Your idea

Make waveforms color user configurable:

a) more colors per theme 
b) customisable color palette for waveforms 

### Problem to be solved

Having color coded waveforms, makes it easier to work when one has 5+ different types of waveforms.
For example, i code each type of instrument with a color.

### Prior art

Regarding each of the features listed above:
a) currently there are only 4 colors
b) the current 4 available colors are not user-configurable 

### Additional context

Thank you !

**Comment by petersampsonaudacity** [comment]
I am minded to agree with this poster.  

I, personally do not use different waveform colors, but I find Instrument-1 and Instrument-2 far to similar _(slightly different shades of blue)_ in the new Light theme introduced for 3.6

![image|689x373](upload://lILLwcnVW28uowHN8SeYCzifKBC.png)


This originally aired as a Forum post today:
https://forum.audacityteam.org/t/color-of-waveforms/115164

**Comment by LWinterberg** [comment]
We'll allow more colors in Audacity 4. Current idea looks like this, though this isn't final: 

![image](https://github.com/user-attachments/assets/cbb45551-3112-42f4-84c2-1207d9b8cc1d)

More details shall be hashed out as part of #6893

FWIW: I'm aware that there's some prior art to arbitrary color selections, as well as gradient color selectors to create gradients across a range of tracks.

**Comment by petersampsonaudacity** [comment]
Thanks for the heads-up Leo.

**Comment by LWinterberg** [comment]
![image](https://github.com/user-attachments/assets/4035bd66-1375-4e56-b6c0-e86fb12795ee)
I suspect we'll expose these color definitions somewhat similar to MuseScore.
