### ISSUE TITLE
Waveform disappears after recording for a few minutes

### ISSUE THREAD

**Issue by alexthelion335** [audacity/audacity#7113]
### Bug description

I have an issue where after I start a recording, the waveform disappears and the recording counter flashes in and out. I am using the latest version of Audacity, version 3.6.1. My platform is Manjaro Linux on an AMD processor and graphics card. I also found Audacity doesn't know what color to make the background when I'm in dark mode, but I believe that's a separate issue.

### Steps to reproduce

1. Download Audacity from the Pacman Package Manager
2. Open Audacity
3. Start a Recording
4. Wait around 2-3 minutes

### Expected behavior

Continue looking like this:
![Screenshot_20240818_140853](https://github.com/user-attachments/assets/f5bde288-3268-438b-874e-39e17ada2753)

### Actual behavior

![audacity error](https://github.com/user-attachments/assets/6dbd488c-020d-412e-a1d7-9b97510aa44f)

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

**Comment by LWinterberg** [comment]
Fixed by https://github.com/audacity/audacity/pull/6955

**Comment by alexthelion335** [comment]
I was able to confirm after building the latest code from the 3.6.2 branch that it is fixed. Hopefully 3.6.2 gets released soon!

**Comment by dozzzzer** [comment]
@alexthelion335 It will be released in a few days.
