### ISSUE TITLE
[AU4] Update snapping dropdown width

### ISSUE THREAD

**Issue by DilsonsPickles** [audacity/audacity#7114]
Please update the width of the snap tool dropdown to be 80px: 

![Image](https://github.com/user-attachments/assets/efe6e64b-4cc0-45b5-bfed-589d20ece0a8)

[Figma link](https://www.figma.com/design/i2A4pyP2E6VE2JiBFRIysK/Main-toolbar?node-id=1795-4)

**Comment by Eism** [comment]
need a design how to trim text if it does not fit into the component

**Comment by DilsonsPickles** [comment]
@Eism - Please find design for truncated text [here](https://www.figma.com/design/i2A4pyP2E6VE2JiBFRIysK/Main-toolbar?node-id=1955-9270&t=smMhY7h4Z8oCxfhX-4).
