### ISSUE TITLE
Let ring effect tails

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#7119]
### Your idea

When the playback cursor reaches the end of the play region, when the stop button is pressed or similar, rather than stopping the processing, see if we can get the tail of effects to continue ringing.
This means letting the playback continue. This comes with several problems:
* A lot of operations are prohibited during playback (clip editing, tempo/time-signature change, etc.). Instead of prohibiting them, we'd stop playback as soon as one of these happen. `*`
* There is only one audio output and cursor state for all open projects. Ownership of this would probably be given to the last project which was called some playback-related action upon.

`*`: manipulations involving dragging (e.g. clip dragging, trimming, stretching) could benefit from a follow-up PR which postpones stopping playback until the drag is released.
Probably part of a follow-up ticket would also be to resume playback automatically where it was stopped after the user interaction is over.

There is a risk that this task reveals unexpected difficulties. Work on this may be discontinued if it turns out to become too big, and be postponed until Audacity 4.+.

Other things to keep an eye on:
- [ ] Level meters reflect tail
- [ ] Envelope tool
- [ ] Pencil tool

### Problem to be solved

Improve playback quality. Pave the way to less blocking operations to make a more fluid user experience.

**Comment by dozzzzer** [comment]
@saintmatthieu please also see https://github.com/audacity/audacity/issues/2617

**Comment by saintmatthieu** [comment]
Aha! Thank you!

**Comment by saintmatthieu** [comment]
Closing as duplicate of https://github.com/audacity/audacity/issues/2617
