### ISSUE TITLE
MacOS: Cannot open wav file from right click menu if Audacity is already open

### ISSUE THREAD

**Issue by intonarumori** [audacity/audacity#712]
**Describe the bug**
On Mac Catalina right click on a file and selecting open with Audacity doesn't open the file if Audacity is already open.

**To Reproduce**
1. Open any file in Audacity
1. Find a wav file in Finder
2. Right click on the file and go to Open With
3. Select Audacity
4. Audacity does not Open the file selected

**Expected behavior**
File is opened in a new Audacity window.

**Screenshots**
-
**Additional information (please complete the following information):**
 - OS: MacOS Catalina 10.15.6
 - Version Audacity: 2.4.2

**Comment by SteveDaulton** [comment]
Thanks for the report. This is already on the Audacity bug tracker.
