### ISSUE TITLE
MacOS: Cannot open wav by dropping file on Audacity icon if Audacity is already open

### ISSUE THREAD

**Issue by intonarumori** [audacity/audacity#713]
**Describe the bug**
If Audacity is already open dropping a wav file on the app icon does not open the file in Audacity.

**To Reproduce**
1. Open any file in Audacity
2. Leave the app open and drop another wav file on the application icon
3. Audacity doesn't open a new window with the wav file, a new Audacity instance seems to be getting opened and immediately closed, the the first Audacity icon "jumps" one time
4. File is not opened

**Expected behavior**
A new Audacity window should be opened with the wav file.

**Additional information (please complete the following information):**
 - OS: MacOS Catalina 10.15.6
 - Version Audacity 2.4.2

**Comment by petersampsonaudacity** [comment]
Thanks, this is already a known bug in or bug-tracker:  http://bugzilla.audacityteam.org/show_bug.cgi?id=2510

**Comment by petersampsonaudacity** [comment]
It has been fixed for the upcoming 3.0.0 release of Audacity
