### ISSUE TITLE
WavPack 5.1 files are opened with only 1 channel

### ISSUE THREAD

**Issue by Cygon** [audacity/audacity#7130]
### Bug description

I'm using WavPack to store some 5.1 (surround) audio tracks.

- In Audacity 3.4.2, I could open these files without issue and see all 6 audio channels.
- In Audacity 3.6.1, only the "front left" channel is loaded.

So this appears to be a regression.

I've done a bit of testing and the issue is limited to WavPack:

- **Open 5.1 FLAC file**: all channels present
- **Open 5.1 Microsoft Waveform file**: all channels present
- **Open 5.1 WavPack file**: loads only the first channel
- **Open stereo WavPack file**: loads both channels
- **Export 5.1 WavPack file**: exports all channels (if correct channel mapping selected)
- **Re-open exported 5.1 WavPack file**: loads only the first channel
- **Use `wvunpack` on a 5.1 WavPack file**: all channels present when opening the resulting `.wav` file

### Steps to reproduce

1. Create a 5.1 WavPack audio file (here's a small one that reproduces the issue: [wavpack-5dot1-int16le-v416.zip](https://github.com/user-attachments/files/16690701/wavpack-5dot1-int16le-v416.zip))
2. Drag & Drop the file onto the Audacity window

### Expected behavior

Audacity to load all 6 channels from the WavPack file:

![Loaded 5.1 channel audio file in Audacity](https://github.com/user-attachments/assets/936f3d28-8eed-4905-bb6c-e959a764149d)

### Actual behavior

Audacity only loads the first, "front left" channel from the WavPack file:

![Audacity showing only the first channel of a 5.1 audio file](https://github.com/user-attachments/assets/225564a0-6b9e-4749-b5cd-d23180d4eb8e)

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Linux

### Additional context

Gentoo Linux stable, desktop profile, PipeWire with PulseAudio compatibility layer, system wide installs of WavPack 5.7 and ffmpeg 6.1.1 present.

**Comment by LWinterberg** [comment]
possibly same fix as #7063
