### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by akhilesh-balaji** [audacity/audacity#714]
**Is your feature request related to a problem? Please describe. **
The current Audacity logo looks really outdated, and doesn't look that great on the start menu.

**Describe the solution you'd like**
I'd like to suggest a new logo for Audacity. I've actually redesigned the icon; have a look in the "Additional Context" section if you're interested. I've retained the headphones, as that's what makes the logo stand out. Other ideas are also welcome. I just want a redesigned icon that looks good.

**Describe alternatives you've considered**
N/A

**Additional context**
![1](https://user-images.githubusercontent.com/69246693/103435997-07a67e80-4c3d-11eb-980d-18d9acd272d9.png)
![2](https://user-images.githubusercontent.com/69246693/103435998-0a08d880-4c3d-11eb-80c5-16a7b9a82dbc.png)
![3](https://user-images.githubusercontent.com/69246693/103435999-0aa16f00-4c3d-11eb-85f7-01ab0006e81f.png)
![4](https://user-images.githubusercontent.com/69246693/103436000-0b3a0580-4c3d-11eb-8310-1a601e9b5485.png)
![5](https://user-images.githubusercontent.com/69246693/103436001-0bd29c00-4c3d-11eb-8601-99dfdefd22df.png)
![6](https://user-images.githubusercontent.com/69246693/103436002-0bd29c00-4c3d-11eb-941f-098a1087af19.png)
![7](https://user-images.githubusercontent.com/69246693/103436003-0c6b3280-4c3d-11eb-86bf-e72a38221a49.png)
![8](https://user-images.githubusercontent.com/69246693/103436004-0d03c900-4c3d-11eb-956a-cac2e0d67e95.png)
![9](https://user-images.githubusercontent.com/69246693/103436005-0d9c5f80-4c3d-11eb-82e9-1ad27da17c13.png)
![10](https://user-images.githubusercontent.com/69246693/103436006-0e34f600-4c3d-11eb-907a-0eab60577b41.png)
![11](https://user-images.githubusercontent.com/69246693/103436007-0e34f600-4c3d-11eb-9279-5f0ac03c43b3.png)

**Comment by petersampsonaudacity** [comment]
See the Audacity Forum:  https://forum.audacityteam.org/viewtopic.php?f=67&t=83108

**Comment by luzpaz** [comment]
please close ticket as the forum is where this should be discussed.
