### ISSUE TITLE
Add a setting and documentation for character encoding of ID3 tags

### ISSUE THREAD

**Issue by ByteEater-pl** [audacity/audacity#715]
**Is your feature request related to a problem? Please describe.**
The problem is I don't know what the encoding is and I see no way to set it in Audacity, so the resulting metadata is sometimes displayed wrong and sometimes doesn't even roundtrip, resulting in replacement characters instead of diacritical letters (mostly Polish, but sometimes I also add something else, even from Unicode astral planes, cf. The Pile of Poo Test™).

**Describe the solution you'd like**
First, document the status quo: what encoding is used. Here in a comment first – would be helpful to me and others searching for it and probably much sooner than in a future release of Audacity.
Second, implement a setting for it.

**Describe alternatives you've considered**
For the documentation issue, I tried asking on #audacity on IRC but got no reply. For setting the tags, I used other software, either from the start or upon noticing a problem in an MP3 file with tags inserted by Audacity.

**Comment by ByteEater-pl** [comment]
Since Audacity allows even characters from astral planes to be entered in the metadata dialog and they're displayed correctly there, I'd assume the used encoding can represent them, so it's probably some form of Unicode. But the observed effects make me doubt it.

**Comment by petersampsonaudacity** [comment]
Logged as P4 ENH #2780 in Bugzilla (our bug tracker)
https://bugzilla.audacityteam.org/show_bug.cgi?id=2780
Bug 2780 - ENH: Add a setting and documentation for character encoding of ID3 tags 

Accordingly I shall close this GitHub Issue in favor of the Bugzilla ENH entry
