### ISSUE TITLE
Question: Why don't we use ffmpeg.exe, rather than avformat-55.dll

### ISSUE THREAD

**Issue by Foxite** [audacity/audacity#716]
I get why ffmpeg is not included by default. Something to do with patent rights.

What I don't understand is why audacity wants a specific version of a library that's included with (a currently outdated version of) ffmpeg. I'm struggling to find the right download link with avformat-55.dll, because the latest builds use avformat-5**8**.dll.

Would it be easier for Audacity to use ffmpeg.exe instead? Several other programs (youtube-dl, to name one) use the exe, and I would think that the command-line interface is more stable - as in, breaking changes are not often introduced. But feel free to correct me on that.

Of course, I'm just going to solve my problems by manually converting my audio files into a format that Audacity can use natively, but that's less convenient than it could be.

**Comment by Natalia-Oreiro** [comment]
My school was looking for a suitable program for audio editing and compression to ACC.
She bought program sound forge because audacity uses old libraries with bugs.

this issue should be given higher priority.

**Comment by ValZapod** [comment]
> breaking changes are not often introduced

They are often introduced too.

**Comment by SteveDaulton** [comment]
> I'm struggling to find the right download link with avformat-55.dll

For any released version of Audacity, details are in the manual: https://manual.audacityteam.org/man/faq_installation_and_plug_ins.html#ffdown

**Comment by LWinterberg** [comment]
As of version 3.1, Audacity now has a method to easily add support for newer ffmpeg versions as they come along (currently: avformat 55, 57, 58).
