### ISSUE TITLE
Awareness: Opening projects with older versions/releases of audacity is no longer possible

### ISSUE THREAD

**Issue by LinkeHand** [audacity/audacity#7173]
### Your idea

With the implementation of PR#6910 it is no longer possible to open projects with older releases of audacity. 

If you are not aware of this, you will get problems in the following cases:

1. Fallback to a previous version in case of errors: If you need to install an older release you can't open newly created or changed/saved projects. If you habe no backups, you can't access to this projects with easy steps. 

2. Collaboration/exchange projects with users, that use oder version: Some users are still using for good reasons olders versions of audacity - f.e. Release 3.4.2. 

### Problem to be solved

Do an awareness in some kind.

1. Inform the user while saving, that this project can't be opened by older releases. The user should be able to supress  this message.
2. Inform the user on your homepage and/or in the splash screen while starting audacity

### Additional context

Look at Musescore 4. Some users run in this similar problem as they have to use Musescore 3.6.2 for good reasons.

**Comment by LWinterberg** [comment]
This is intentionally the case. For 3.6.0 we forgot to flag version incompatibility, so when opening a project made in that version in a previous one, it might corrupt the project. And data loss is much, much worse than prompting folks to upgrade. 

Forward compatibility in general is not something we really are looking to achieve given that upgrading to a new version is literally free and that we're looking to expand the set of functionality a lot. Additionally, it is possible to get things out of Audacity into WAV and back into any previous version. Backward compatibility we do want to maintain, to a point (Audacity 2.1 broke backward compatibility to <=1.2.x projects).

> Some users are still using for good reasons olders versions of audacity - f.e. Release 3.4.2.

Nebulous "good reasons" don't really help anyone. If you've got a specific gripe with a new version - go ahead and air it. For example, We've seen some feedback from folks who use Audacity in conjunction with a DAW, and who complained that our plugin scanning at the beginning of startup was slowing things down. We addressed that specific complaint in 3.5, and #6851 will further improve startup times in 3.7.
