### ISSUE TITLE
AI Vocal Remover

### ISSUE THREAD

**Issue by ghost** [audacity/audacity#718]
Can we integrate [this](https://github.com/tsurumeso/vocal-remover) into audacity? Is it possible?

**Comment by aksayushx** [comment]
I think this feature can be implemented under the Automatic Source Separation GSoC project using state-of-the-art audio source separation models like [Spleeter](https://github.com/deezer/spleeter). In addition to the vocal separation, we can also separate the audio into its musical instruments components.

**Comment by LWinterberg** [comment]
while this specific model won't be implemented, there's a branch for deep learning tools from a past gsoc project
