### ISSUE TITLE
[AU4] Track panel header - fix hover behavior

### ISSUE THREAD

**Issue by kryksyh** [audacity/audacity#7193]
Hovering over a child element would not remove the hover status from the parent.

The intended behavior:

https://github.com/user-attachments/assets/1fa8ac63-4b48-49a5-982f-979dcb12b2df

**Comment by DilsonsPickles** [comment]
Please pay special attention to the hover styling as it is currently not correct.

Designs can be found [here](https://www.figma.com/design/k5rS9tnZl60nYmhJhvI2vf/Track-headers?node-id=258-19809&t=0nN2C2jNNwEcoSiQ-4).

**Comment by dozzzzer** [comment]
Tested
