### ISSUE TITLE
Dark screen on audio track timeline

### ISSUE THREAD

**Issue by AlanReviews** [audacity/audacity#7198]
### Bug description

The audio track timeline disappears and is covered with a dark screen.

### Steps to reproduce

1. Enable Tile Windows on Pop!_OS 22.04
2. Open audacity
3. Record a track
4. Tile windows and open another application
5. Stop tiling applications by maximizing Audacity or disable Tile Windows

### Expected behavior

The audio track should show up when I stop tiling windows

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

### Additional context

The Linux operating system I use is Pop!_OS 22.04. I am using dark mode. Here is an image of what I am seeing
![Screenshot from 2024-08-28 13-48-42](https://github.com/user-attachments/assets/0769e58e-e171-45ad-bc8c-c8561631c59c)

**Comment by LWinterberg** [comment]
this will likely be fixed in 3.6.2

**Comment by AlanReviews** [comment]
In addition, if I zoom out, the dark screen appears.
