### ISSUE TITLE
After zooming, waveform disappears, audacity goes blank.

### ISSUE THREAD

**Issue by radiophonia** [audacity/audacity#7201]
### Bug description

Zooming in causes the waveform to disappear. The screen goes blank.

### Steps to reproduce

1. Zoom in.

### Expected behavior

Timebar is the only visible thing left. All else is blank.

### Actual behavior

Waveform & toolbars vanish.

### Audacity Version

stable version (from a Linux repository)

### Operating system

Linux

### Additional context

Version 3.6.1. From Flatpak. Using Arcolinux. I was not the first to bring this up on the audacity forum.

**Comment by Raykutan** [comment]
I have the same issue! I found that resizing the windows makes them reappear

**Comment by LWinterberg** [comment]
this will be fixed in 3.6.2
