### ISSUE TITLE
Nyquist plugins are not visible when using "Group by category" fx sorting

### ISSUE THREAD

**Issue by mrbumpy409** [audacity/audacity#7202]
### Bug description

When using the default effect menu organization setting "Group by category", Nyquist plugins do not appear in the effects list.

### Steps to reproduce

1. Go to Edit → Preferences → Effects, and set the effect menu organization to "Group by type" or "Group by type and publisher" and click "OK".
2. Open the Effect menu, and you will see a "Nyquist" entry containing a bunch of extra plugins that come with Audacity.
3. Go to Edit → Preferences → Effects, and set the effect menu organization to "Group by category" and click "OK".

### Expected behavior

The Nyquist plugins should be available.

### Actual behavior

The Nyquist plugins are nowhere to be found.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Linux

### Additional context

This bug happens with both the AppImage and also when compiled from source.

**Comment by petersampsonaudacity** [comment]
@mrbumpy409 

I cannot reproduce this on W10 with 3.6.2 or the latest release 3.6.3

I see the carious Nyquist listed under the carious categories they belong in - note that there is no visual cue to tell you whether any particular effect is Nyquist or not.

For example both of the green-ringed effects are Nyquist effects:
![image](https://github.com/user-attachments/assets/5e86bc78-f3ea-491a-b722-5937f9943f7c)

**Comment by mrbumpy409** [comment]
Revisiting this, I can also see the plugins you point out. I had been trying to access the older version of Audacity's limiter plugin, which shows up when sorting by "Type and Publisher" under "Nyquist" → "Steve Daulton" → "Limiter". My guess is that Nyquist plugins sharing a name with another plugin were being masked.

However, the current Audacity version now features these older plugin versions in the "Legacy" category, so they are accessible again. I will close this report.
