### ISSUE TITLE
VSTs behaving differently between "Apply" and "Play"

### ISSUE THREAD

**Issue by reedacartwright** [audacity/audacity#723]
**Describe the bug**
I'm experimenting with monitoring loudness via VSTs in Audacity and I'm getting inconsistent results. I'm using the LinVST wrapper to run the Youlean Loudness Meter 2 for Windows on Linux. When I load up the VST and click "apply", the loudness is correctly measured at -16 LUFS. When I use "play" instead, the loudness is measured at -13 LUFS. This effect also happens with several other loudness measuring VSTs. 

I assume this has to do with something about stereo and mono signals because of the +3 gain, but I'm not sure.

**To Reproduce**
1. Download reference audio file. https://developers.google.com/assistant/downloads/loudness/tts-reference.wav
2. Download https://youlean.co/download-youlean-loudness-meter/ for Windows
3. Install LinVST https://github.com/osxmidi/LinVst/
4. Convert Loudness meter to a Linux VST.
5. Enable Youlean loudness meter in Audacity
6. Open the reference in Audacity, select the entire file, and activate the Youlean VST
7. Click apply several times, and see that the integrated loudness is -16 LUFS.
8. Clear the graph. Click the play button several times and see that the integrated loudness is -13 LUFS.

The following Meters all show the same difference between play and apply.

- https://youlean.co/download-youlean-loudness-meter/ (Windows+LinVST)
- https://www.tb-software.com/TBProAudio/dpmeter5.html (Windows+LinVST)
- https://www.klangfreund.com/lufsmeter/ (Windows+LinVST)
- https://www.klangfreund.com/multimeter/ (Windows+LinVST)

LUFSMeter and Multimeter have linux VSTs, but there is a font problem with them. I think they are also affected by this, but I am not 100% sure.

**Expected behavior**
Loudness should be the same regardless of "play" vs "Apply"

**Screenshots**
After Clicking "Play" a few times:
![Screenshot from 2021-01-16 16-51-35](https://user-images.githubusercontent.com/101918/104827462-29962880-581b-11eb-8beb-8511f8cb3439.png)

After Clicking "Apply" a few times:
![Screenshot from 2021-01-16 16-50-58](https://user-images.githubusercontent.com/101918/104827467-30bd3680-581b-11eb-993e-ab29fb0f40fb.png)

**Additional information (please complete the following information):**
 - OS: Linux memnon 5.10.7-arch1-1 #1 SMP PREEMPT Wed, 13 Jan 2021 12:02:01 +0000 x86_64 GNU/Linux
 - Version: Audacity 2.4.1
 - Sound Device: Pulse Audio sound system.

**Comment by petersampsonaudacity** [comment]
I have transferred this issue to ou Bugzilla bugtracke and will alter close this GitHub Issue in favor of that.
https://bugzilla.audacityteam.org/show_bug.cgi?id=2791
Bug 2791 - Linux: VSTs behaving differently between "Apply" and "Play" 

@reedacartwright you logged this as an issue with 2.4.1 - is this still an issue  with 3.0.0 or the latest release  3.0.2 ?

**Comment by petersampsonaudacity** [comment]
Closing this in favor of the Bugzilla entry
