### ISSUE TITLE
[AU4] Fix track header responsive behaviour

### ISSUE THREAD

**Issue by DilsonsPickles** [audacity/audacity#7236]
#### Description
Please refer to the [Collapsing breakpoints](https://www.figma.com/design/k5rS9tnZl60nYmhJhvI2vf/Track-headers?node-id=280-47709&t=xME3VP33WOBCuO7H-4) designs. When the User shrinks the track header the controls should hide as per the specified breakpoints. 

Screenshot shows current behaviour where pan dial is still visible:
![Image](https://github.com/user-attachments/assets/98bccb48-8645-468e-95bb-d84f69531a51)

**Comment by chinakov** [comment]
Tested, tracks can now be collapsed with no issues. 

![image](https://github.com/user-attachments/assets/4ff28866-c756-473a-be83-06b40e15fb26)
