### ISSUE TITLE
Please add back track name as overlay, or otherwise allow much more than ten characters

### ISSUE THREAD

**Issue by QuantumGood** [audacity/audacity#7242]
### Discussed in https://github.com/audacity/audacity/discussions/7223

<div type='discussions-op-text'>

<sup>Originally posted by **QuantumGood** September  1, 2024</sup>
Truncating track name from dozens of characters down to ten (numeric characters) is a major feature loss

### PROJECT MANAGEMENT: VERSION CONTROL, FILENAMES AND BACKUP
_Around 99% of my track names are now not viewable._

1. Audacity allows track name to be exported as filename. So a typical filename with project name, date and user name (e.g. "IRS.Efile_1-5-2024_Kevin.Elin") was formerly readable as a track name. This is a major truncation of Audacity functionality and usefulness for professionals that use this feature as intended (limiting filenames to ten characters is not resonable for any user, forcing filenames and source tracks to have different names is counter-productive, etc.)
2. Knowing overlay was available, we adopted other standards for version and project tracking that use track names longer than ten characters

### VOICE RECORDINGS
_In voice recordings, portions are deleted (e.g. coughs, unused alts), and some sounds are truncated (silence) or reduced (e.g. breaths)._

Detailed track names are used for, among other things:

1. Splitting a track into more than one track helps to overlay silences between phrases for timing, especially when editing in or out alt takes. Recording on multiple tracks is common, then merging into one for export. **So keeping track of which tracks are used for what is very important**. Union standards assume it takes five hours to product one finished hour of audiobook, and all professional audiobook narrators refine their process to bring production time down as much as possible. 
2. Duplicating the track before editing is a good practice in case of errors (e.g. sounds not meant to be reduced or truncated), and **labeling the duplicated track clearly matters to find it later** when unexpected errors need to be fixed nearing deadlines.

With a large install base like Audacity has, removing long-available features that can be visible at all times likely affect the use case of many people (like removing the compression feature, then restoring it as "legacy compressor").</div>

**Comment by LWinterberg** [comment]
In Audacity 4, we'll have a lot more space in the track headers. We won't be bringing back the track name overlay. 

![image](https://github.com/user-attachments/assets/4ea7dd65-8637-4fa5-a6fe-7f823affc59e)
