### ISSUE TITLE
Exception code 0xc0000005

### ISSUE THREAD

**Issue by newbie-blip** [audacity/audacity#7274]
### Bug description

[Exception code 0xc0000005.txt](https://github.com/user-attachments/files/16917830/Exception.code.0xc0000005.txt)

### Steps to reproduce

1. This error always occurs when closing audacity. (Audacity 3.6.2 )
2. In previous versions never.

### Expected behavior

Normal closing

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows

**Comment by newbie-blip** [comment]
Sorry for the omission, the problem always occurs **after discarding a project** and trying to close audacity

**Comment by petersampsonaudacity** [comment]
See: #7131
