### ISSUE TITLE
[AU4] Mouse cursor doesn't change its type after clicking into the clip

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7289]
### Description

After clicking into the clip and moving the mouse away from it, the cursor doesn't change its type and remains in the "selection" state:

https://github.com/user-attachments/assets/7ad5de66-6864-4a44-913a-1afd0ee9107c

**Comment by chinakov** [comment]
This could be related: https://github.com/audacity/audacity/issues/7511

**Comment by dozzzzer** [comment]
Tested!
