### ISSUE TITLE
LINK: ZLib name should not be hardcoded.

### ISSUE THREAD

**Issue by carlo-bramini** [audacity/audacity#729]
Hello,
I have seen that you have hardcoded the name of ZLib here:
https://github.com/audacity/audacity/blob/0fcf9ffb520ff37d1fb79e9069b0d7a189dc3cfc/src/CMakeLists.txt#L1064
I don't know if there is a particular reason for doing this rather than letting CMake to detect it.
For example, on Windows, it could be `z` or `zdll` or `zlib1` depending on the compiler environment or if it is static or dynamic library.
What do you think about using the symbolic `$ZLIB_INCLUDE_DIRS` and `$ZLIB_LIBRARIES` for linking with ZLib?
Sincerely.

**Comment by carlo-bramini** [comment]
Nowadays, it seems to me that CMakeLists.txt already includes the imported target for ZLIB::ZLIB here:

https://github.com/audacity/audacity/blob/f98435bf8fbce0831e332b1bde406b5f8eeaef63/src/CMakeLists.txt#L1227

So this line:

https://github.com/audacity/audacity/blob/f98435bf8fbce0831e332b1bde406b5f8eeaef63/src/CMakeLists.txt#L1257

Could be just removed from the build script.

**Comment by crsib** [comment]
Makes a lot of sense. `pthread` line is not quite valid too.
