### ISSUE TITLE
[AU4] When clip size is reduced past a certain level,  the waveform on the clip disappears

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7297]
### Description

The size of the clip at which the waveform disappears from the clip is way too big. We should allow the display of a waveform on smaller clips.

@DilsonsPickles please specify the exact size of the clip

<img width="240" alt="image" src="https://github.com/user-attachments/assets/4ffd5bee-af9f-402d-a9d3-46bdd71b4631">

**Comment by chinakov** [comment]
![image](https://github.com/user-attachments/assets/96e08003-9763-4c94-91e6-6f392a8bb060)

I am quite satisified with this fix, as it feels much more fluid and logical.
