### ISSUE TITLE
[AU4] AU3 projects are played at slower speeds and the clips become stretched

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7304]
### Description

Some projects created using Audacity 3.x, when opened in AU4, are played at a lower speed and the clips appear to be stretched.

**Comment by dozzzzer** [comment]
@Tantacrul please re-check

**Comment by Tantacrul** [comment]
Just re-checked. This issue does appear to be fixed, when using a non-contaminated file.
