### ISSUE TITLE
Plugin scanning dialog during startup is blocked by the splash screen and cannot be accessed

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7309]
### Steps to reproduce

1. have some third-party plugins installed in your system
2. remove `pluginregistry.cfg`
3. start Audacity 3.6.2+
4. observe

### Expected behavior

The splash screen should disappear when Audacity starts spawning its first window, in this particular case it's the plugin scanning dialog.

### Actual behavior

The splash screen with the Audacity logo comes first and overlaps the plugin scanning dialog, which becomes blocked by it. It goes on like this until the scanning progress reaches 100% and Audacity window appears.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by petersampsonaudacity** [comment]
Testing on W10 with 3.6.3 I cannot reproduce this.

After totally clearing the Audacity settings folder and then launching 3.6.3 it launches fine and my 3rd party plugins are all available - and work in destructive and RT modes.

**Comment by dozzzzer** [comment]
UPD: I can reproduce the same issue in the latest master build for MacOS too.
