### ISSUE TITLE
noice suppression

### ISSUE THREAD

**Issue by promic1** [audacity/audacity#731]
**Describe the bug**

after selecting the part where i want the noice fix i go in effects and noice suppression but none of the option available there does alter the background noice i want to remove

**To Reproduce**
1. select the part
2. go on effects
3. noice suppression
4. none of these options does alter the noice 

**Expected behavior**
i am expecting to be able to alter and remove the background noice

**Additional information (please complete the following information):**
 - OS: [e.g. Mac High Sierra, Ubuntu 18.04, Windows 10]
 - Version any version
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]

**Additional context**

**Comment by NoobMaster1999** [comment]
I want to fix the problem

**Comment by JamesCrook** [comment]
I'm guessing the OP did not select a suitable section of noise.  For example they selected silence.
Anyway, Closing: WORKS-FOR-ME.
