### ISSUE TITLE
Database sometimes not being compacted

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#7312]
### Bug description

Some saved projects may be very much bigger than the data size. As an example, in  one test a project "AUP3" file was 2.4 GB although it contained less than 0.5 MB of data.

### Steps to reproduce

- Create a new project, and save to the disk
- Generate a 10m chirp
- Save the project and observe the file size, which should be ~100mb
- Delete the clip and save the project
- Close Audacity and observe the file size

### Expected behavior

Automatic compaction to reduce wasted disk space.

### Actual behavior

Some projects may be many GB larger than necessary.

### Audacity Version

current master / alpha / nightly build

### Operating system

Windows, Linux

### Additional context

Originally reported here: https://forum.audacityteam.org/t/superbig-project-files-after-audacity-update/117363
I have also reproduced the issue on Linux.

When conducting my tests, Audacity quit normally, so this does not appear to be directly related to the Windows crash on exit bug.

**Comment by petersampsonaudacity** [comment]
It could be useful to re-instate the Compact Project command.

**Comment by kryksyh** [comment]
@SteveDaulton @petersampsonaudacity @dozzzzer steps to reproduce were updated

**Comment by notsmoothsteve** [comment]
> > It could be useful to re-instate the Compact Project command.
> 
> @petersampsonaudacity As a user I would expect the app to do that automatically. However, I agree that there should be a failsafe to force it manually. I've created another issue #7313 to take care of that.

I agree with both - it should do it automatically (as it used to), but it could also be useful to have a way to force it manually (with a warning, if applicable, about possibly unwanted side effects like losing undo history).  Often while working on a project, my project file ends up being a few gigabytes, the vast majority of which would be undo data, and even in the absence of the bug that's causing Audacity to fail to compact the project on close, it wouldn't be a bad thing to have an option for shrinking the file other than closing and reopening it.

**Comment by chinakov** [comment]
Tested, fixed. Thanks!
