### ISSUE TITLE
[AU4] Fix crash when pasting stereo clips to mono tracks

### ISSUE THREAD

**Issue by Eism** [audacity/audacity#7326]
### Description

Need to process error and show message
<img width="302" alt="Screenshot 2024-09-13 at 1 59 55 PM" src="https://github.com/user-attachments/assets/f5375447-68dc-4d0c-89eb-f04367dc270f">

**Comment by grliszas14** [comment]
QA bulletpoints:
* check if pasting mono clip into stereo track is possible
* check if pasting stereo clip into mono track results in error dialog
* I did some code-reworking here so it may be advised to play with copy-paste a bit more to see if there is no regression
* check if this one is fixed too: https://github.com/audacity/audacity/issues/7378

**Comment by dozzzzer** [comment]
Tested
