### ISSUE TITLE
#SwitchToTenacity #dontstealmydata

### ISSUE THREAD

**Issue by ProgramminCat** [audacity/audacity#7331]
[Privacy policy which may violate the original project's GPL license](https://github.com/audacity/audacity/issues/1213)
[Contributor's License Agreement (CLA) which may violate the same GPL license](https://github.com/audacity/audacity/discussions/932)
[Attempts at adding telemetry using Google services for data collection](https://github.com/audacity/audacity/pull/835)

# #SwitchToTenacity

## REPO: https://codeberg.org/tenacityteam/tenacity

**Comment by LWinterberg** [comment]
You're a few years late, we already changed the privacy policy and removed telemetry. Maybe you should read the policy one day, specifically point 4: "we do not store our share personal information".

**Comment by ProgramminCat** [comment]
Audacity is still owned by a for-profit company.

**Comment by LWinterberg** [comment]
Hang on, you're moving goalposts now. I take your initial #dontstealmydata complaint is resolved then and you're happy with the current privacy policy?

As for the for-profit nature of Muse - yes, it is for-profit. Specifically in the context of Audacity, it's selling plugins on the Muse Hub and some audio hosting on audio.com. For this to be worthwhile, Audacity needs to be reasonably competent of an audio editor and DAW, which is what we're spending quite a lot of resources on, including open-sourcing proprietary tech existing inside Muse. All of Audacity still is free and open source, and is going to stay that way.
