### ISSUE TITLE
[AU4] Trim/stretch clip edge hover

### ISSUE THREAD

**Issue by DilsonsPickles** [audacity/audacity#7335]
#### Description

When the User hovers over the edge of a clip, their cursor will change to the trim or stretch cursor (depending on where they hover) and on click and drag, they'll be able trim/stretch the clip.

[Figma link](https://www.figma.com/design/01XLIICmy2AG6t1ieyTp66/Clips?node-id=1550-212062&t=ZyyRXdfGbAIRE63A-4)

**Comment by DilsonsPickles** [comment]
Kicked back as we will be following AU3 logic. Only a single hover area and stretch applied on keyboard modifier

**Comment by DilsonsPickles** [comment]
Updated to reflect AU3 behaviour.

**Comment by grliszas14** [comment]
Created separate follow-up task to fix issue found by @chinakov https://github.com/audacity/audacity/issues/7657
In the video you can see overlap trimming (but overlap trimming is not merged yet, it's a separate PR https://github.com/audacity/audacity/issues/6999). There is a chance that after merging both "overlap trimming" PR and this one - it will be fixed automatically.
