### ISSUE TITLE
[AU4] Effect panel - Selection behaviour

### ISSUE THREAD

**Issue by DilsonsPickles** [audacity/audacity#7345]
### Description

How selecting tracks/clips effects the selection state and therefore the effect list that is shown.

[Figma link](https://www.figma.com/design/w2kAh1gKKV5bu7htY7158W/Effects?node-id=4354-64543&t=TDZyHZwG7nOo0of7-4)

**Comment by saintmatthieu** [comment]
Completed by https://github.com/audacity/audacity/issues/7613 and https://github.com/audacity/audacity/issues/7647
