### ISSUE TITLE
Cannot build 2.4.2 on Fedora 33

### ISSUE THREAD

**Issue by tortured1** [audacity/audacity#735]
**Describe the bug**
When trying to compile Audacity 2.4.2, I get the following:

$ cmake -DCMAKE_BUILD_TYPE=Release -Daudacity_use_ffmpeg=loaded ..
-- The ASM_NASM compiler identification is NASM
-- Found assembler: /usr/bin/nasm
-- Build Info:
--   Host System: Linux-5.10.10-200.fc33.x86_64
--   Host System Name: Linux
--   Host System Processor: x86_64
--   Host System Version: 5.10.10-200.fc33.x86_64
-- 
--   Compiler: /usr/bin/c++
--   Compiler Version: 10.2.1
--   Compiler Standard: 14
--   Compiler Standard Required: ON
--   Compiler Extensions: 
-- 
--   Current Commit: unknown
-- 
-- Building for 64-bit target
-- Building for 64-bit target
-- ========== Configuring wxwidgets ==========
-- Using 'wxwidgets' system library
CMake Error at cmake-proxies/wxWidgets/CMakeLists.txt:202 (message):
  Unrecognized wxWidgets toolkit

-- Configuring incomplete, errors occurred!
See also "/usr/local/src/audacity-minsrc-2.4.2/build/CMakeFiles/CMakeOutput.log".
See also "/usr/local/src/audacity-minsrc-2.4.2/build/CMakeFiles/CMakeError.log".

There's nothing in either of those log files about wx...

Also, if it matters, I had to edit wxWidgets/include/wx/unix/glx11.h and remove the "OVERRIDE" token to get *that* to compile, and I have confirmed that wx-config will at least show me the help when I run it.

**To Reproduce**
$ mkdir build
$ cd build
$ cmake -DCMAKE_BUILD_TYPE=Release -Daudacity_use_ffmpeg=loaded ..

**Expected behavior**
I expect to get a good makefile.

**Screenshots**
N/A

**Additional information (please complete the following information):**
 - OS: Fedora 33 kernel 5.10.10-200.fc33.x86_64
 - Version Audacity 2.4.2

**Additional context**
I'm needing to build audacity myself, because the official Fedora build (both via dnf and flatpak) do not have ffmpeg support, and it would be a lot easier long-term for me to be able to open files directly in audacity without having to convert them manually.

**Comment by imsedgar** [comment]
You can use package audacity-freeworld from repository rpmfusion-free.
