### ISSUE TITLE
[AU4] Adding 10 or more tracks at once freezes Audacity

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7359]
### Description

1. Click "Add new track" button
2. Enter 10 or more tracks to be added
3. Click "Create"
4. (optional) try to scroll the list of tracks added
5. Observe

Act. result: Audacity freezes

**Comment by dozzzzer** [comment]
Re-check after the new add track flyout is implemented

**Comment by ianalarina** [comment]
https://github.com/audacity/audacity/issues/7354

**Comment by LWinterberg** [comment]
This looks fixed with the new add track flyout
