### ISSUE TITLE
Cloud upload registration flow changes 

### ISSUE THREAD

**Issue by ianalarina** [audacity/audacity#7362]
### Description

Implement an ability to register account within Audacity

**Comment by dozzzzer** [comment]
@kryksyh 

1. A typo: `and account` -> `an account`

<img width="450" alt="image" src="https://github.com/user-attachments/assets/a6367edd-2596-402d-8401-17b72625c90a">

2. "Unlink Account" should be changed to "Sign Out"

<img width="450" alt="image" src="https://github.com/user-attachments/assets/a9d5fe0b-95e4-4c16-97a4-35645487cd9d">

**Comment by kryksyh** [comment]
@dozzzzer 1, 2, 4, 5 are fixed in the latest build.

#3 is a tough one, I believe that we should pass on it for now, and create a separate ticket for it.

Our current authorization flow does not use any external servers (like audio.com). After the user selects a google/facebook account they are redirected to the app itself. The app is not able to provide any feedback to the login page, so it waits indefinitely. 

The solution would be to use a special landing page on audio.com which would be called after the cloud account selection and then calling to application running on a pc. That's the approach I see on most apps that support OAuth2.

Here is an "after-login" page in zoom
![image](https://github.com/user-attachments/assets/189163d6-cd09-44f5-8e82-9807b1bd87af)


@Tantacrul Martin, what are your thoughts on this? Should we implement it right now? There is not much work for audio.com guys, probably a few days. If the redirect page would just open audacity and close itself, then we would not need any designs for it.

**Comment by kryksyh** [comment]
@dozzzzer 
1. Can you clarify what buttons should be changed? I'm pretty much sure that both buttons you mentioned are already named as "Link Account"

![image](https://github.com/user-attachments/assets/43325562-20bd-4574-8764-b258c8200a2e)
![image](https://github.com/user-attachments/assets/1001b6af-5259-44c2-af40-7ac7819ab261)

**Comment by dozzzzer** [comment]
My bad, @kryksyh, please see the updated comment above

**Comment by chinakov** [comment]
@kryksyh - I have noticed a new issue with naming of projects. If a User names a project with cyrillic letters in the name, the project title in Audacity becomes corrupted, but the Audio.com version is fine. 

STR:
1. Launch Audacity
2. Authenticate any User
3. Generate some audio
4. Try to save the project to the cloud
5. Input cyrillic letters into the Project Name
![image](https://github.com/user-attachments/assets/9144a825-86db-4c84-ad5b-b83f4aac416a)
6. Sync the project to the cloud
7. Once the project has been uploaded, observe the original Audacity window project name (It should be corrupted).
![image](https://github.com/user-attachments/assets/bb4739c4-6cee-4684-9af7-a689e2a816a8)

8. Press 'Ctrl+S' to initialize the sync once again
9. Observe MORE symbols being added to the title of the Project in Audacity
10. If a User keeps 'syncing' the project, the User will be met with an 'Audacity failed to write to a file' error message. 
Here is the log: 
[150638 SQLite error (1) statement a.txt](https://github.com/user-attachments/files/17229042/150638.SQLite.error.1.statement.a.txt)

**Comment by kryksyh** [comment]
@dozzzzer The Cyrillic characters bug is a bit more complicated than I anticipated. It was not introduced during the work on this issue (it is present in 3.6.4 at least, but judging from the git history, it was always there). 
I have created a separate issue to track it there. In short, currently, audacity does not restrict the user from naming the user using whatever symbols they choose. There is a rudimentary escaping code, but it doesn't do it properly.

**Comment by kryksyh** [comment]
@dozzzzer @chinakov all issues (but the project name) should be fixed in the latest builds, please retest

**Comment by dozzzzer** [comment]
@kryksyh This still remains unfixed: 

4. If your audio.com's storage is full, after you've performed sign-in via Google in Audacity, you can't access your Audacity projects on audio.com.

STR:

1. Make sure your audio.com's storage is full
2. Make sure you signed out from your audio.com account in the browser
3. In Audacity, create a new project
4. Ctrl + S
6. Sign in with Google
7. Choose an account to sign in with
8. Click "Open Audacity" in the browser
9. Observe: "Your project storage limit has been reached" dialog
10. Click "Visit audio.com"
11. Observe: on audio.com, you're presented with only two tabs: Audio and Collections. There is no "Audacity Projects" tab. The user's profile image in the upper right corner doesn't match the one in the About section. Clicking it doesn't expand the dropdown menu. Instead, it takes you to the Sign In page.

**Comment by dozzzzer** [comment]
@kryksyh Currently, Sign In is the default view. We need to make Create Account the default view instead.

<img width="470" alt="image" src="https://github.com/user-attachments/assets/2a1100b0-4dde-4d2e-b319-d5dbc177adce">

**Comment by dozzzzer** [comment]
@kryksyh We also need to take the user to the new Sign In (Create Account) flow when the user clicks "Sign In" inside the open from cloud dialog (`File > Open from cloud`):

<img width="450" alt="image" src="https://github.com/user-attachments/assets/77ef2a55-febc-499c-af8c-a2855854edd6">

**Comment by chinakov** [comment]
The issue with modal windows on Linux has been fixed, thanks!

**Comment by kryksyh** [comment]
@dozzzzer 

> We need to make Create Account the default view instead

done

> eed to take the user to the new Sign In (Create Account) flow when the user clicks "Sign In" inside the open from cloud dialog (`File > Open from cloud`):

Does it make sense to open "Create Account" when the user wants to open an already existing project, though?

**Comment by kryksyh** [comment]
@dozzzzer could you doublecheck if the problem with "projects are not available when opened from the `storage is full` dialog" is fixed by refreshing the page. If so, then it could not be resolved on the audacity side.

**Comment by dozzzzer** [comment]
> the problem with "projects are not available when opened from the storage is full dialog"

I can no longer reproduce it

**Comment by dozzzzer** [comment]
> Does it make sense to open "Create Account" when the user wants to open an already existing project, though?

The current implementation, where the user sees the Sign In dialog first, is more sensible.

**Comment by Tantacrul** [comment]
@dozzzzer Yes. For sure.
