### ISSUE TITLE
Project edition time tracker

### ISSUE THREAD

**Issue by Nozalys** [audacity/audacity#737]
**Is your feature request related to a problem? Please describe.**
After working several hours spread out over several days on a project I wonder how many time I spent on it. Audacity doesn't provide such work-log tracker. Some software tracks the time spent on the edition of a document and keep this data in the document file itself.

**Describe the solution you'd like**
A _quick and dirty_  solution could be to start a second counter as soon as Audacity is launched, or when a project is opened or even when the first audio data is added/imported in the first audio track. The _`current_elapsed_second`_ counter is then saved in the `.aup` file, as a new attribute in the `project` XML node.
Having the edition time stored in seconds (or in `hh:mm:ss` format) in the XML file would be enough in a first step.
This implementation have benefits to be very fast to implement.

**Describe alternatives you've considered**
- We could also imagine that this edition time could be displayed in a small pop-up by an clicking item in the Extra menu.
- To be more accurate, the _`current_elapsed_second`_ counter could be paused when Audacity is no more in foreground, and resumed when it comes back as the front application. This would avoid increasing time if we reduce Audacity instead of closing it when we've done.
- To be even more accurate, the _`current_elapsed_second`_ counter could be paused after an arbitrary delay (i.e. 30 s) of inactivity. _"Inactivity"_ detection could be : no audio edition, no audio playback, no display events, no menu navigation. Or maybe no mouse move and no key pressed. This option is probably the most difficult to implement because it requires to collect a lot of various events.

**Additional context**
The goal of knowing the edition time, in addition of satisfying my curiosity (I don't see the time running when I'm editing music) is to be able to estimate the workload required for few minutes of final result.

**Comment by JamesCrook** [comment]
Sounds interesting and more useful to professional users.  We would not show the feature by default since most of our users are beginners, but having it there/available for more professional users would be worthwhile.

Are you a programmer as well?

**Comment by Nozalys** [comment]
> Are you a programmer as well?

Yes, but maybe not enough familiar with neither C/C++ nor Github to start implementing by myself. I don't know..

**Comment by JamesCrook** [comment]
Closing.  Can done with a third party app that is designed for work tracking.  On that you could also record time spent on client work writing emails, on the phone, etc.
