### ISSUE TITLE
Add advanced vertical zooming to the waveform view

### ISSUE THREAD

**Issue by Kurtsley** [audacity/audacity#7387]
### Your idea

As per discussion #6757, I am wondering if the advanced vertical zoom should be added back to the waveform view. I see that it already exists in the spectrogram view and am curious as to why it was removed. Looking at the code, it seems it was a deliberate decision to not include this in the waveform view.

### Problem to be solved

Currently, only the spectrogram view allows the user to drag the vertical ruler to zoom in.

### Additional context

I have a PR ready to go that seems to brings this functionality back, but would like some feedback before I submit it.

**Comment by LWinterberg** [comment]
I removed AVZ from waveforms because it feels rather awkward to use. I'd much rather have the drag gesture move the vertical scale up and down. Ocenaudio handles it this way, and it feels much nicer.

**Comment by Kurtsley** [comment]
I see your point, I downloaded Ocenaudio and have to agree. Thanks.
