### ISSUE TITLE
About Change Pitch

### ISSUE THREAD

**Issue by codeyr67** [audacity/audacity#7388]
### Description

hey can you add more semitones please like up and down 132 semitones you know one hundred and thirty two semitones and let it revert to -72 semitones and +72 semitones so it sounds like them and i actually wanted you to update this on october 3rd 2024 i would and that's so it does not have the original voice at the end with high pitch and makesure it does not go quiet with low pitch at the end

**Comment by LWinterberg** [comment]
Why? The further you pitch away from the original, the more distorted the sound will be. An octave (12 semis) in either direction allows this feature to match any key. What is it you are trying to do?

**Comment by codeyr67** [comment]
i am trying to pitch shift the song up and down 132 semitones i am and the reason why is is because i want to listen to it in godzilla roaring or a bear roar or crickets chirping at nighttime

**Comment by codeyr67** [comment]
hey remember add 132 semitones okay so i can listen to it in godzilla's roar and a bear roar and a cricket chirping or squeaking at night okay so i can save the mp3 files to my pc and that
