### ISSUE TITLE
[AU4] Remove selection on cut

### ISSUE THREAD

**Issue by DilsonsPickles** [audacity/audacity#7399]
Make an audio-data selection and then press the "Cut" icon. The audio data is removed, but the original selection persists. Please clear the selection on cut. Cut behaviour in AU3 can be used as a reference.

**Comment by DilsonsPickles** [comment]
@grliszas14 this is true of **all cut behaviour**. Any cut action should remove the selection as the action is now complete.

**Comment by grliszas14** [comment]
QA bulletpoints same as in [here](https://github.com/audacity/audacity/issues/7412#issuecomment-2377280814)

**Comment by dozzzzer** [comment]
Tested
