### ISSUE TITLE
[AU4] Always add extra space to the right of the rightmost clip

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7401]
### Description

When you move any clip to the right edge of the project window and try to scroll further horizontally at certain zoom levels, there is no extra space after the clip. However, upon zooming out, as can be seen in the video below, only minimal extra space appears after the clip. It should be extended to match the length of the project.

https://github.com/user-attachments/assets/986e41c9-a347-464f-8030-566c1717bee6

**Comment by chinakov** [comment]
Tested, thanks!
