### ISSUE TITLE
[AU4] Change the timeline color to match the color of the Add New Track button

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7402]
### Description

Change the color of the timeline to match the color of the Add New track button in Light and Dark modes correspondingly:

**#f0f0f5**

<img width="376" alt="image" src="https://github.com/user-attachments/assets/46a7279a-8032-402f-8b3f-e90c8a0b4639">

**#292e33**

<img width="418" alt="image" src="https://github.com/user-attachments/assets/480a4fef-cf5c-4d2c-bb4f-3ba54fa3a1c5">

**Comment by DilsonsPickles** [comment]
To clarify, timeline should be background-secondary-color.

**Comment by chinakov** [comment]
Tested
