### ISSUE TITLE
[AU4] Track list/canvas padding

### ISSUE THREAD

**Issue by DilsonsPickles** [audacity/audacity#7411]
#### Description

Some padding at the bottom of the track list to ensure that there's always some empty canvas space for the User to interact with.

[Figma link](https://www.figma.com/design/FWiArQcqiLRB4a01w9s1lV/Tracks?node-id=4546-2)

**Comment by chinakov** [comment]
This is implemented, the User can now always adjust the track height due to the padding. Thanks! 


https://github.com/user-attachments/assets/721ff458-3359-420b-83ca-7661bd36bd50
