### ISSUE TITLE
[AU4] Remove the selection after Split Cut or Split Delete is applied to the clip

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7412]
### Description

This is an intended change of behavior compared to AU3. 
As the title suggests, the selection should not be preserved after any of these two operations – Split Cut, Split Delete – is applied.

**Comment by grliszas14** [comment]
QA bulletpoints:
* selection area should **not** be preserved after: cut / split-cut / delete / split-delete
* additionally you can check if any delete action (on single clip or audio data) crashes the app. Before this PR I was able to crash app with following scenario:
1. delete part of the audio data at the end of the clip (btw this was doing basically nothing in the UI)
2. zoom in/out (whole clip content was disappearing suddenly)
3. grab clip and try to move it (crash)

**Comment by dozzzzer** [comment]
Tested
