### ISSUE TITLE
Wrong French translation commit

### ISSUE THREAD

**Issue by trebmuh** [audacity/audacity#742]
While updating the French translation for the next version, I looked at the fr.po file history. I then noted [this commit](https://github.com/audacity/audacity/commit/215abfb5a81e246ad06a34180bea948599d93ab8#diff-7492bbb6f390fea02fc9436169b1642bc06b1990cf3cf6354b6002264bcde3f2).

I'm very surprised because it didn't go through the ML or a PR on github if I'm not wrong, so I wouldn't have seen it without thinking to check the file history (which I don't usually do). That would have been unfortunate because everything this commit does is wrong:
- the "paramètrer" changes (3 times) are grammatically incorrect
- removing a mnemonic that works is also an error
- last thing, it move the header from `"PO-Revision-Date: 2020-08-10 15:00+0100\n"` to `"PO-Revision-Date: 2020-06-09 22:59+0100\n"` which seems to be a regression

@JamesCrook can you please ping me next time?
Thank you.

**Comment by JamesCrook** [comment]
Thanks.  Will fix.  See explanation on audacity-translations list.
