### ISSUE TITLE
Website Bug

### ISSUE THREAD

**Issue by winderine** [audacity/audacity#7423]
### Bug description

Button to "Download Audacity" does not download audacity, but some other suspicious program called "Muse Hub". 

Help article for installing audacity does not mention this program. There are no help articles for this program.

Is it spyware?

### Steps to reproduce

1. Go to https://www.audacityteam.org/ in Firefox, Windows 10
2. Click on "Download Audacity"

### Expected behavior

3. Receive Audacity installer for Windows 10

### Actual behavior

3. Receive unexpected executable file that isn't mentioned on the website anywhere

### Audacity Version

other

### Operating system

Windows

**Comment by petersampsonaudacity** [comment]
You can use the link just below the button to download Audacity directly (the one I have outlined in Orange.
![image](https://github.com/user-attachments/assets/d69f1e97-0ef2-4aa8-803a-1f98ebf46429)

These days Audacity is owned by Muse - MuseHub is theirs (and not spyware), following that button link to MuseHub will also enable you to download Audacity but with the MuseHub extras which I believe are extra plugins you can acquire.

**Comment by dozzzzer** [comment]
Thanks for the explanation, @petersampsonaudacity 
@winderine If you're interested to know more about Muse Hub and its benefits, feel free to visit [Audacity's FAQ page](https://www.audacityteam.org/FAQ/).
