### ISSUE TITLE
New UI hides format and sample rate

### ISSUE THREAD

**Issue by em00k** [audacity/audacity#7424]
### Bug description

The new UI layout now hides the sample and playback rate. It used to be displayed under the L/R sliders, you now have to click on the three dots and observe the value. 

There doesn't seem to be a way to turn this setting back on?

### Steps to reproduce

1. Open any sample
2. Look at the left-hand side, no longer able to see format 

I used this to be able to work with various formats. It's now hidden in an extra click then menu. 

New:
![image](https://github.com/user-attachments/assets/a8439ee9-e7ac-432e-a858-cfbafa1ca550)

Old:
![image](https://github.com/user-attachments/assets/c9731b4a-1b1f-447c-8015-bee97fbdb9e4)

### Expected behavior

Should be able to see format and playback rate

### Actual behavior

Its been removed. 

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

Windows

**Comment by petersampsonaudacity** [comment]
This is not a bug - Muse removed that by design in a recent release (to tidy up the Track Control Panel).

You can still see the same information by clicking in the tree little dots at the top right of the TCP ans selecting Rate and Format:
![image](https://github.com/user-attachments/assets/b53d446f-c7dc-4649-b527-39e69f54957e)

**Comment by em00k** [comment]
Thanks for the reply.

I know how I can now view this - but this change makes Audacity less useful now for my needs, as I need to now check each file that is open for the format/playback rate. Doing this for multiple files is two extra steps that slows down my workflow - now I am forced to use an older version & wasn't aware the auto update option was going to remove useful information :-/

Please consider at least adding this back as a user option.
