### ISSUE TITLE
[AU4] Increase ruler component height

### ISSUE THREAD

**Issue by DilsonsPickles** [audacity/audacity#7428]
### Description

Increase height of ruler and 'Add new track' button from 32px to 40px

[Figma link](https://www.figma.com/design/PIavx2Q7WayFAw2FQORrTw/09---Timeline?node-id=713-20118)

**Comment by grliszas14** [comment]
QA bulletpoints:
* check if "add new track" btn height matches new timeline ruler height
* additionally I've changed method of drawing playhead -> check for any unwanted behaviour (dragging should work the same), looks for any anti-aliasing artifacts (there shouldn't be any), check if playhead matches ticks on the ruler when cursor is snapped

**Comment by chinakov** [comment]
Tested, no regressions according to bulletpoints. elements are now 40 px in height
