### ISSUE TITLE
[AU4] Negative time and the cursor not moving when recording is initiated

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7431]
### Description

1. Load up a project with a blank audio track
2. Click Record 
3. Observe: 1) Negative time appears left to the cursor position; 2) the clip grows rightwards while the cursor is still

https://github.com/user-attachments/assets/0fa855d5-2870-45d0-a90c-e476d21c2216

**Comment by dozzzzer** [comment]
@Eism 

The negative time issue isn't reproducible anymore. However, the playhead still does not move when recording is initiated. Moreover, on Windows, clicking the Record button doesn't start recording.

MacOS:

https://github.com/user-attachments/assets/1cfdfdbf-8050-4b1a-93d6-80586f69dfc9


Windows:

https://github.com/user-attachments/assets/84f36d98-ab36-48dd-92d1-68874f4f0708

**Comment by Eism** [comment]
@dozzzzer 
I did some research
I would recommend fixing both issues in separate PRs, the solution seems non-trivial
The second issue on Windows has the same cause as #7564
