### ISSUE TITLE
Enable Audio.com login via OAuth for Linux builds

### ISSUE THREAD

**Issue by kryksyh** [audacity/audacity#7437]
### Your idea

Audacity on Linux should be able to Login via OAuth2 in the same manner as Windows and MacOS builds

### Problem to be solved

Users have to link cloud account manually by copying the auth token on audio.com.

### Prior art

All modern apps that support OAuth are able to do that

**Comment by chinakov** [comment]
FYI: Firefox is having a minor issue of not acting upon the new audacity://open?projectid=_____ link when the User tries to open a recently synced project on Audio.com

**Comment by chinakov** [comment]
Tested both login and registration OAUTH features, on all 3 platforms (E-mail, Facebook, Google). Everything seems to be in order, thank you!
