### ISSUE TITLE
[AU4] It's possible to extend the selection beyond the zero time mark

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7441]
### Description

<img width="500" alt="image" src="https://github.com/user-attachments/assets/ab03d0e5-04cc-4854-b883-f5baf1df20aa">

If you try to extend the selection all the way to the left, you'll be able to stretch it past the zero time mark, i.e. up until the Add New Track button/Track headers. See how the light grey selection area propagates beyond the playhead position.

**Comment by grliszas14** [comment]
QA bulletpoints:
* check if the issue in the description does not occur anymore
* I've also changed width of extend/reduce tool handles to be 8px as discussed on demo meeting (it was 4px before) - try if that's more comfortable to grab

**Comment by chinakov** [comment]
Hi, @grliszas14 - extend/reduce tool handles feel much more responsive now, and bug has been fixed. Thank you!
