### ISSUE TITLE
[AU4] Fix pasting audio selection into empty space

### ISSUE THREAD

**Issue by DilsonsPickles** [audacity/audacity#7455]
### Description

Select audio over multiple tracks, paste into last track - app crashes.

**Comment by dozzzzer** [comment]
@grliszas14 

When pasting into the empty space underneath the tracks, then undoing and pasting again, Audacity crashes:

https://github.com/user-attachments/assets/8404d924-3322-4b70-ac5c-f46a53f0e212

Also a very similar and perhaps related scenario: when pasting into the second track, over another clip, it does the job at first, but if you undo and try to paste again, it also crashes Audacity:

https://github.com/user-attachments/assets/3a36566d-091d-40d5-b404-050012852e10

**Comment by dozzzzer** [comment]
@grliszas14 Just discovered one more way to crash Audacity in this PR's build:

- Have an audio clip, copy some of its data
- Click in the empty space underneath the track and paste
- Undo
- Redo

This crashes Audacity every time I try it.

**Comment by dozzzzer** [comment]
Tested
