### ISSUE TITLE
Dark background to Time Toolbar in "Light" theme

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#7458]
### Bug description

With the (default) Light theme, the background colour of the Time Toolbar is light

### Steps to reproduce

Run Audacity 3.7.0-alpha id: e5a49f 

### Expected behavior

![Screenshot_2024-10-03_15-36-47](https://github.com/user-attachments/assets/2580f4fb-899e-438e-8a2f-5ace7ac0a89b)

### Actual behavior

![Screenshot_2024-10-03_15-33-06](https://github.com/user-attachments/assets/fb0e1983-6a63-431b-8675-a49502117e5e)

### Audacity Version

current master / alpha / nightly build

### Operating system

Linux

**Comment by petersampsonaudacity** [comment]
Same on Windows - but my understanding is that this is a deliberate design change by Muse.

**Comment by SteveDaulton** [comment]
> my understanding is that this is a deliberate design change by Muse.

Surely not.

**Comment by dozzzzer** [comment]
Yes, it's been changed to a different background colour on purpose.
