### ISSUE TITLE
Cannot Open A VST Effect Plugin

### ISSUE THREAD

**Issue by MrTeeXD** [audacity/audacity#746]
**Describe the bug**
For some reason and I dont know why but Audacity fails to open my EQ VST. The effect is not broken and it works in other programs

**To Reproduce**
1. Go to the plugins folder
2. Drop your EQ VST of Choice
3. Open Audacity and click add new plugins
4. Set the filter to New and try to enable that VST

**Expected behavior**
I remember clearly that in previous versions, this worked perfectly

**Screenshots**
This is the error I got when attempting to load the effect:
![audacity_jIE9Ums4cT](https://user-images.githubusercontent.com/37266538/107966710-ec0cf280-6fb4-11eb-8586-9dd287df2ea0.jpg)

**Additional information (please complete the following information):**
 - OS: Windows 10 64bit Home Edition
 - Version: Audacity 2.4.1
 - (if relevant) Sound Device: Windows WASAPI

**Additional context**
I am using the Zipped Version of Audacity

**Comment by SteveDaulton** [comment]
Audacity is currently a 32-bit app, so it only supports 32-bit VSTs.
End user support for Audacity is available via the Audacity forum: https://forum.audacityteam.org
