### ISSUE TITLE
[AU4] Fix vertical clipview slider

### ISSUE THREAD

**Issue by grliszas14** [audacity/audacity#7466]
When scrolling vertically, the slider on the right side changes its size.

1. Open project with multiple tracks so vertical slider appears on the right side of app.
2. Grab slider with a mouse and try to scroll down (notice how slider gets bigger and bigger. Apart from that, it spoils the smoothness of scrolling)

See attached screenshots:

<img width="1470" alt="Screenshot 2024-10-4 o 15 48 58" src="https://github.com/user-attachments/assets/0526d36c-0f0a-4a0f-a575-cf80c788cd04">
<img width="1470" alt="Screenshot 2024-10-4 o 15 49 04" src="https://github.com/user-attachments/assets/bcd224a0-c774-4916-9657-4303fbab8515">
<img width="1470" alt="Screenshot 2024-10-4 o 15 49 08" src="https://github.com/user-attachments/assets/a82c3119-ac4d-4d60-af33-084acef2ae0c">

**Comment by dozzzzer** [comment]
tested
