### ISSUE TITLE
SHA-256 checksum mismatch for audacity-macOS-3.6.4-arm64.dmg

### ISSUE THREAD

**Issue by McDutchie** [audacity/audacity#7471]
### Bug description

The SHA256 checksum for audacity-macOS-3.6.4-arm64.dmg listed on https://www.audacityteam.org/download/mac/ does not match the real SHA256 checksum of the file downloaded from https://github.com/audacity/audacity/releases/download/Audacity-3.6.4/audacity-macOS-3.6.4-arm64.dmg.

***This means the binary could be compromised.*** Of course it could also be a simple mistake on the maintainers' part.

### Steps to reproduce

1. go to https://www.audacityteam.org/download/
2. then click on macOS
3. then click on Download next to "ARM 64 dmg (Apple Silicon)"
4. note that page says the checksum is d00e89394a69f610bda86276fbdf90ca0fab37f433e6a3c4ef3128b23e09be30
5. get the real checksum from the downloaded file:  `openssl sha256 ~/Downloads/audacity-macOS-3.6.4-arm64.dmg`
6. note that the real checksum is 8d1aa3f7529e3e112aaf649385ae7ce7506a05955782f54743d09440cec14bfe

### Expected behavior

The checksums must match.

### Actual behavior

The checksums do not match.

### Audacity Version

latest stable version (from audacityteam.org/download)

### Operating system

macOS

**Comment by LWinterberg** [comment]
d00... is the linux appimage checksum, 8d1... is the correct one. The checksum in the releases' CHECKSUMS.txt is correct.
