### ISSUE TITLE
[AU4] Double click in clip to select audio data

### ISSUE THREAD

**Issue by DilsonsPickles** [audacity/audacity#7473]
### Description

Double clicking in clip body will select all audio data inside that clip.

[Figma link](https://www.figma.com/design/oQEvoOqeKHQlqabmFmM0Mp/10---Selection?node-id=427-81104)

**Comment by dozzzzer** [comment]
@grliszas14 

- When double-clicking the clip, the clip does get selected but the selection isn't reflected in the timeline area. Compare with the AU3 implementation:

<img width="600" alt="image" src="https://github.com/user-attachments/assets/c16553fa-2b69-4b06-aafb-330705e37b42">

<img width="600" alt="image" src="https://github.com/user-attachments/assets/ddcd578c-8271-450b-bfc8-2406f47c81a5">

- When double-clicking the clip, the cursor (aka playhead) is moved to the exact position where the first click occurs. Again, this is smth new compared to AU3 (see the screenshots above). Is this intended?

**Comment by grliszas14** [comment]
@dozzzzer
1. It was decided that we want to select a clip on double click (not the audio-data) hence there's no highlighting on the ruler. It basically behaves the same way as clicking once on the clip header. 
2. When you double click in AU3, the cursor is also moved to the exact position where the first click occurs - the difference is that we hide cursor on the second click while in AU4 cursor is always visible

**Comment by dozzzzer** [comment]
Got it. So, I'd ask @DilsonsPickles or @Tantacrul to confirm that this is desired:

> 2. When you double click in AU3, the cursor is also moved to the exact position where the first click occurs - the difference is that we hide cursor on the second click while in AU4 cursor is always visible

**Comment by dozzzzer** [comment]
@grliszas14 As it was agreed, let's go with the following:
1. When duble-clicking a clip, the selection should also be reflected in the timeline just like AU3 behaves at the moment.
2. When double-clicking a clip, the playhead _is_ displayed and is placed at the very start of the clip.

**Comment by dozzzzer** [comment]
Tested
