### ISSUE TITLE
[AU4] Double click in track to select all audio data

### ISSUE THREAD

**Issue by DilsonsPickles** [audacity/audacity#7474]
### Description

Double clicking in empty track space will select all audio data in track. 

[Figma link](https://www.figma.com/design/oQEvoOqeKHQlqabmFmM0Mp/10---Selection?node-id=427-99471)

**Comment by dozzzzer** [comment]
Tested

**Comment by dozzzzer** [comment]
@DilsonsPickles @Tantacrul FYI double-clicking in the track behaves the same as [double-clicking the clip](https://github.com/audacity/audacity/issues/7473#issuecomment-2413350984) in the sense that it puts the cursor where you click and doesn't hide it afterward (unlike AU3). Let us know if this is the desired behavior.

**Comment by dozzzzer** [comment]
@grliszas14 

- As was agreed, double-clicking in a track should place the playhead right at the beginning of the selection.

**Comment by dozzzzer** [comment]
Tested
