### ISSUE TITLE
[AU4] Implement a new Error Message for Pasting Stereo Tracks into Mono Tracks

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#7477]
### Description

As a user,
I want to be informed when I try to paste a stereo audio clip onto a mono track,
So that I understand why the action cannot be completed and know how to resolve it, instead of recieving a generic error. 

Error now: 
![image](https://github.com/user-attachments/assets/07826cdc-8786-4bad-9a17-379f536854db)

**The new error should state the following:** Error: Stereo audio clips cannot be pasted onto mono tracks. Please convert the stereo clip to mono before pasting.

**Comment by chinakov** [comment]
Instead of the Error message, show a Confirmation to the User that you want to paste Stereo into Mono.

**Comment by grliszas14** [comment]
Changed the error message. It was decided to leave it for now as getting proper stereo to mono functionality may be time-consuming.

**Comment by chinakov** [comment]
Tested, the new error message is implemented, thanks!
