### ISSUE TITLE
rename split cut/delete to cut/delete and leave gap

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#7486]

**Comment by petersampsonaudacity** [comment]
@LWinterberg 

I have added P1s to the manual for when this makes it into master for 3.7,0

_And there are more references to them than you might imagine..._

**Comment by chinakov** [comment]
Tested, thanks

**Comment by petersampsonaudacity** [comment]
> I have added P1s to the manual for when this makes it into master for 3.7,0

I have updated the 3.7.0 alpha manual for this change
