### ISSUE TITLE
Sliding Stretch / Sliding Time Scale and Pitch Shift crashes on multiple tracks

### ISSUE THREAD

**Issue by dlh-0492** [audacity/audacity#749]
**Describe the bug**
Hi, I've noticed that the Sliding Stretch utility keeps crashing when I apply it to more than one track. So, for example, when I apply Sliding Stretch to both channels of a stereo track at once, or to more than one mono track at once, it will go through the shifting but then Audacity will crash at the end.

**Expected behavior**

**Screenshots**

**Additional information (please complete the following information):**
 - OS: Linux (Ubuntu)
 - Version 2.4.2
 - Sound Device: ALSA

This wasn't an issue in the 2.3.x versions.

**Comment by SteveDaulton** [comment]
Thanks for the report.
It is a known bug and has been fixed for the next Audacity release (Audacity 3.0.0).

**Comment by dlh-0492** [comment]
Thanks!
