### ISSUE TITLE
[AU4] As soon as the mouse cursor position reaches track volume slider/pan knob, vertical scrolling stops

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7493]
### Description

<img width="527" alt="image" src="https://github.com/user-attachments/assets/f78cfac9-3e93-49f5-86ab-2c8ecee73ae4">

If you have multiple tracks and if you position your mouse cursor in the area where the volume slider exists in the track panel, scrolling the mouse wheel up/down doesn't scroll the track list.

**Comment by kryksyh** [comment]
@dozzzzer Right, what is happening here is that the volume slider handles mouse wheel events to adjust. But, because on the way snapping to 0  is implemented right now (snaps any value ∈ (-2; 2) to 0), it locks on 0.

How do we want to handle mouse wheel input on the volume slider? Perhaps we can use different thresholds for the mouse wheel and mouse drag. What do you think @DilsonsPickles ?

**Comment by DilsonsPickles** [comment]
I've just had a play and think that we should remove the mouse scroll wheel behaviour from the volume slider. 

I think mouse scroll wheel should be reserved purely for scrolling the project up and down. 

@dozzzzer @LWinterberg @Tantacrul thoughts?

**Comment by dozzzzer** [comment]
@DilsonsPickles I just realized the same goes for the pan knob. Shall we get rid of the mouse scroll behavior in the pan knob as well?

**Comment by DilsonsPickles** [comment]
I don't think it should happen on hover, perhaps if they click on the control (to set explicit focus) and then scroll it would work.

**Comment by Tantacrul** [comment]
This is a general problem we faced on MuseScore that I understand might now be fixable due to our move to a later version of Qt. @Eism - is that right?

**Comment by Tantacrul** [comment]
I'm also not sure the problem is that there's scrolling behaviour on those items. It's that the scrolling switches focus to different UI elements. It should know where you started scrolling and not move focus mid scroll to something else.

**Comment by Tantacrul** [comment]
Hey folks, we fixed this in MuseScore Studio by just removing mouse wheel interactions on all elements in scrollable panels.

- Knobs
- Sliders
- etc

Was a v.simple fix and now the issue is gone over there. We should just do that here too.

**Comment by chinakov** [comment]
As we're getting rid of the mouse wheel interaction for Knobs and Sliders, should the User be able to scroll the project vertically in both areas (1 and 2)? 

![audacity_pQvwjkIrBm](https://github.com/user-attachments/assets/8a337c42-93a2-4115-8526-53085f3798bb)

As for now, the build only allows to scroll vertically in area 2.

**Comment by chinakov** [comment]
It is an issue after all, brought back to 'In Progress'

**Comment by chinakov** [comment]
Update: this is only reproducible on Windows.

**Comment by Tantacrul** [comment]
Yeah, we want to be able to scroll both areas - we just need to disable scrolling (mouse wheel / trackpad) on volume and pan controls.
<img width="181" alt="image" src="https://github.com/user-attachments/assets/6546d2d7-0c01-4076-b7ce-407617529aec">

**Comment by kryksyh** [comment]
@dozzzzer @chinakov there is another issue: the user can't scroll the content in-between sections 1 and 2 on the screenshot, and the user can't select the track data of the clip starting from the beginning. Could you create a ticket for that?

**Comment by kryksyh** [comment]
I've checked AU3, and you can't do it there either, even though when I want to select the clip data starting from the beginning my first instinct is to drag the mouse from the empty area towards the clip.



![image](https://github.com/user-attachments/assets/1e5b2a45-d39c-4c6c-97ec-2a1eb2cd2e3f)

@DilsonsPickles @Tantacrul  do we have this behavior described in specs? Do we need this implemented?

**Comment by chinakov** [comment]
Bug has been fixed, thanks! Also addressed your question @kryksyh by creating another Enhancement Request so that this ticket can move on. https://github.com/audacity/audacity/issues/7813
