### ISSUE TITLE
[AU4] Trim and time-stretch handles should move as you resize the clip vertically

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7494]
### Description

If the clip is resized vertically, the handles remain in the same position. I think we should let them move up and down as the clip is being resized in order to not run into a situation like the one on the video. @DilsonsPickles could you spec this up?

https://github.com/user-attachments/assets/753b4802-19ae-4da6-b7f2-e898aec925ba

**Comment by DilsonsPickles** [comment]
Yup, good call. I'll see if I can get them to fit in that min track size.

**Comment by DilsonsPickles** [comment]
@dozzzzer 

Created spec and added to this task: https://github.com/audacity/audacity/issues/7500

**Comment by DilsonsPickles** [comment]
@dozzzzer closing as now handled by [#7500 ](https://github.com/audacity/audacity/issues/7500)

**Comment by DilsonsPickles** [comment]
@dozzzzer closing as now handled by [#7500 ](https://github.com/audacity/audacity/issues/7500)
