### ISSUE TITLE
[AU4] Multi-select - Cut/copy/paste/delete

### ISSUE THREAD

**Issue by DilsonsPickles** [audacity/audacity#7501]
### Description

Handling clipboard actions with multiple clips selected.

[Figma link](https://www.figma.com/design/oQEvoOqeKHQlqabmFmM0Mp/10---Selection?node-id=569-48617)

**Comment by DilsonsPickles** [comment]
Kicking back to design to include stereo to mono dialog

**Comment by grliszas14** [comment]
QA info:
* follow the design spec, almost everything should be possible except 'stereo to mono' paste which will be handled separately here https://github.com/audacity/audacity/issues/7876

**Comment by chinakov** [comment]
Tested:
- Cut/Copy/Paste/Delete actions for multiple clips
-  Pasting multiple clips
- Pasting without enough tracks
- Pasting into empty canvas space

I have yet to test the scenario of pasting into non-consecutive tracks, as the feature of de-selecting a track via Shift is not implemented yet. (https://github.com/audacity/audacity/issues/7776)
