### ISSUE TITLE
Incorrect LV2 path handling in WIndows

### ISSUE THREAD

**Issue by SMcCandlish** [audacity/audacity#751]
**Describe the bug**
According to Ardour (which makes much more use of LV2) and other sources, the canonical Windows 10 paths for LV2 plug-ins are
* `%APPDATA%\LV2\` – resolves to `\_UserName_\AppData\Roaming\LV2\` in English-language Windows 10
* `%COMMONPROGRAMFILES%\LV2\` – resolves to `\Program Files\Common Files\LV2\` in English-language Windows 10
* Presumably `\Program Files (x86)\Common Files\LV2\` is also supported for 32-bit plug-ins, as `\Program Files\` is only for 64-bit stuff (in Windows 7 and later, as I understand it).
* But Audacity will _only_ look in `\Program Files (x86)\LV2\` (it won't even look in `\Program Files\LV2\`). While it is easy enough to use `cd "\Program Files (x86)"` followed by `mklink /D LV2 "Common Files\LV2"` to make such a path exist, LV2 plug-ins that are not 32-bit do not belong here, and will not be installed to such a place by installers or when following typical plug-ins' installation instructions, which are going to expect the `\Program Files[ (x86)]\Common files\LV2\` paths.
* Sloppily working around this problem by moving x64 plug-ins into the x86 version of this directory is liable to cause breakage in other audio software that uses LV2 plug-ins, if you are running a 32-bit version for some particular purpose, since they are not capable of loading the 64-bit versions you dumped in there.
* (It is possible, actually, that Audacity will also look in `%APPDATA%\LV2\`; I did not test that and have no interest in storing my general-use software in a redundant per-user manner.)

**To Reproduce**
1. Install any `Foo.lv2\` plug-in folder in any (even all) of the above non-user-specific locations other than `\Program Files (x86)\LV2\`.
2. Start Audacity, and go to `Tools` > `Add / Remove Plug-ins...`, then sort by state to get those marked `New` to show up at the top. You will not find the added plug-in. Close Audacity.
3. Copy or move the LV2 plug-in from any of those locations into `\Program Files (x86)\LV2\` (or symlink one of those other `[...]\LV2\` folders to `\Program Files (x86)\LV2\`).
4. Start Audacity, and go to `Tools` > `Add / Remove Plug-ins...` again, and the plug-in will now be available to activate.

**Expected behavior**
* At bare minimum, Audacity should look in both `\Program Files (x86)\LV2\` and `\Program Files\LV2\`, as well as `%APPDATA%\LV2\`.
* Better, it should be looking in `%COMMONPROGRAMFILES%\LV2\` and whatever the x86 version of that is, and `%APPDATA%\LV2\`, and also (since Audacity has already established its own "counter-location") `\Program Files (x86)\LV2\` (and `\Program Files (x86)\LV2\`), presumably by `%` variables for localization.
* Best of all, it should stop hard-coding any such paths and simply ask people for them as it does for ffmpeg path.  Just give people a field in which to insert plug-in paths as they see fit (for LV2 or whatever).

**Additional information (please complete the following information):**
 - OS: Windows 10 Enterprise x64 v2004 build 19041.804
 - Version: Audacity 2.4.2

**Comment by SteveDaulton** [comment]
Audacity released for Windows is currently a 32-bit app and only supports 32-bit plug-ins.

**Comment by SMcCandlish** [comment]
Ah so.  Well, it should still support `\Program Files (x86)\Common Files\LV2\`, which is where these plug-ins are likely to be, or just not have hardcoded paths for this and instead ask the user where their 32-bit LV2s are.

**Comment by JohnColket** [comment]
Hmm...  I just happened to notice this web page:  https://manual.audacityteam.org/man/installing_effect_generator_and_analyzer_plug_ins_on_windows.html#lv2_install

It states where Audacity currently looks for 32-bit and 64-bit plugins.  (Note: for 64-bit Windows, you need to compile your own, or possibly "borrow" one from this site).  But specifically, it states, "Search paths where Audacity looks for LV2 plug-ins may also be specified by setting the LV2_PATH environment variable. "

Do you think you could make use of that LV2_PATH variable?

**Comment by petersampsonaudacity** [comment]
Audacity for Windows version 3.0.3 will be released as a 64-bit app.

I have updated the 3.0.3 Manual page
https://alphamanual.audacityteam.org/man/Installing_Effect,_Generator_and_Analyzer_plug-ins_on_Windows#lv2_install

**Comment by Ryan-Miller-Audacity** [comment]
(Issue List Cleanup) Retesting this still appears to be the case. LV2 paths/searching for plugins still look in the locations outline above.
