### ISSUE TITLE
Clicking the Polyspectral Multiband Compressor link on the welcome page gets a 404 error

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#7514]
### Bug description
Clicking the **Polyspectral Multiband Compressor** link on the welcome page gets a 404 error

Plus I get a vertical scroll bar for the "What's new" - BUT all that's hidden is empty space in the box.

![image](https://github.com/user-attachments/assets/9e42ce4e-cbc9-4e1c-9e31-1a7903b0f6c8)

### Steps to reproduce
1. launch master for 3.7.0
2. Click on **Polyspectral Multiband Compressor**
3. Observe: 404 error

### Expected behavior
Link to work

### Actual behavior
![image](https://github.com/user-attachments/assets/07613d7e-5e81-4dcb-bf80-00250b4e6fd6)

### Audacity Version
current master / alpha / nightly build for 3.7.0

### Operating system
Windows 10 - but assume all OS

### Additional context
None

**Comment by LWinterberg** [comment]
> Plus I get a vertical scroll bar for the "What's new" - BUT all that's hidden is empty space in the box.

that's only there because the alpha-.... string is so long. It won't be an issue for release. 

anyway, I gave the link a redirect for the time being. It may go to a more dedicated page on release, depending on how quick the musehub team is.
