### ISSUE TITLE
[AU4] Non-consecutive audio-data selection

### ISSUE THREAD

**Issue by grliszas14** [audacity/audacity#7516]
https://www.figma.com/design/oQEvoOqeKHQlqabmFmM0Mp/10---Selection?node-id=16-52334&node-type=frame&t=M26XuNHPSREHSOuF-0

**Comment by dozzzzer** [comment]
When I make a non-consecutive audio data selection on tracks 1 and 3, the marquee selection appears, which is correct. But then if I try to extend the selection by holding the Ctrl (Cmd) key and clicking in the desired spot, on the first click the non-consecutive selection I made previously will disappear, however, if I click once again while still holding the Ctrl key, the selection will appear. Observe how I demonstrate this behavior by clicking in the blank space of a track while holding the Ctrl key:

https://github.com/user-attachments/assets/dad41527-656e-4247-a3c9-8a0ba7cfb2f8

@DilsonsPickles Does this look right to you?

**Comment by DilsonsPickles** [comment]
The second click you make (when the selection appears again) is what I'd expect to see on the first click.

**Comment by grliszas14** [comment]
Fixed the behaviour
