### ISSUE TITLE
Undo history per track

### ISSUE THREAD

**Issue by juzzlin** [audacity/audacity#7519]
### Your idea

Now there's only a single global undo stack. It would be more useful if it worked per track.

### Problem to be solved

Making a bunch of destructive changes on different tracks renders undo stack pretty much useless. If I change tracks A, B, and C and then later want to undo my changes on track A it's AFAIK impossible without undoing also changes on track B and C first. This is one of my biggest pains with Audacity right now.

**Comment by LWinterberg** [comment]
We have added realtime effects to solve precisely your problem. https://support.audacityteam.org/audio-editing/using-realtime-effects

**Comment by juzzlin** [comment]
> We have added realtime effects to solve precisely your problem. https://support.audacityteam.org/audio-editing/using-realtime-effects

How do you do realtime LPF, HPF, and Auto Duck ?

**Comment by juzzlin** [comment]
Ok, sorry. I didn't realize you can install new effects as plugins!
