### ISSUE TITLE
Divide plug-in menus further

### ISSUE THREAD

**Issue by SMcCandlish** [audacity/audacity#752]
**Is your feature request related to a problem? Please describe.**
After adding even a moderate number of plug-ins, the menus relating to them (especially `Effect`) effective become unusable, at least in the Windows version.

Due to the old GUI framework used (I'm not sure what it is, but I've seen it before, since Audacity shares the following problem with several other apps, like xEdit), the long menu, which will exceed the top-to-bottom length of the screen, cannot be navigated with the scrollwheel of one's mouse/trackball (or the trackpad scrolling zone equivalent), it can only be scrolled very, very slowly via the `▼` and `▲` arrow icons at the bottom and top of the list, respectively (or by hovering mouse near the bottom one and jiggling the mouse around, but even this does not work on the top one), and a bit quicker by using the down and up arrow keys on the keyboard.  The UX for this menu interface appears to pre-date the existence of scrollwheels.

Even aside from that ergonomic issue, it's just really unhelpful to have 30, 50, 100 plugins, often with confusing names, in a huge list. There's a reason that our hard drives are subdivided into directories/folders instead of all files just being dumped into one huge directory.

**Describe the solution you'd like**
* Some means of dividing plug-ins more granularly, preferably in an arbitrary, user-defined manner.  While the extant division into separate menus of `Generate`, `Effect`, and `Analyze` is helpful (though the ability to sort within these menus by plugin-architecture much less so), some real control over this is needed, like that provided in the Adobe apps.
* One way to do this is just support sub-folders, and to treat each sub-folder as sub-menu (and sub-sub-menu in the case of a sub-sub-folder)
* Another would be to have a menu editor in the app.
* A combination could also work, doing the first by default, and permitting it to be modified in the editor.
* An adjunct to this could be a richer plug-in manager with visual previews, extensible notes, etc. (E.g., specify a simple format, like JavaScript-free HTML5, or XML, and plug-in authors/distributor could include a description/documentation file, while the local user could also add their own notes to it).

**Describe alternatives you've considered**
Just disabling/uninstalling plug-ins is pretty much the only "solution" right now, but this is undesirable as a major inconvenience, and is even antithetical to having a plug-ins collection. Given that most of them are poorly documented, and their effects are often very subjective, we only learn them and their capabilities and limits through experimentation, which is not something we'll do much if they're disabled – out of sight, out of mind.  Much of the strength of the multi-layer plug-in architectures of Photoshop, etc., is that they're arbitrarily large but still produce a tidy and compact (just deeper rather than lo-o-onger) menu, with meaningful subdivision.

The "just enable stuff as you need it" model only works well when there is a richly detailed plug-in manager like the ones built into major Web browsers, or 3D-asset management databases for Daz/Poser, or so forth. When we can't see at-a-glance detailed information about what a LADSPA plug-in named "SC2" does, or what a Nyquist one named Hyperexp is capable of, we'd have little reason to ever turn them on and experiment with them.

PS: If there is a known fix, at the code level, for making the current menus operable with scrollwheels, I would love to know what that tweak is, so I can pass that information on the xEdit developers.

**Comment by SteveDaulton** [comment]
Audacity has some options to divide effects in various groupings. This is an area that we want to improve, but this is what is available now: https://manual.audacityteam.org/man/effects_preferences.html

**Comment by petersampsonaudacity** [comment]
See: https://wiki.audacityteam.org/wiki/Proposal_Effect_Menu_Categorization

and https://wiki.audacityteam.org/wiki/Proposal_Improvements_to_the_Manage_Effects/Generators/Analyzers_GUI

**Comment by LWinterberg** [comment]
closing in favor of #501
