### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by Twig6943** [audacity/audacity#7520]
### Your idea

The app runs via xwayland on my plasma wayland session (idk if theres a flag to force wayland)

### Problem to be solved

The app runs via xwayland on my plasma wayland session (idk if theres a flag to force wayland)

### Prior art

The app runs via xwayland on my plasma wayland session (idk if theres a flag to force wayland)

### Additional context

The app runs via xwayland on my plasma wayland session (idk if theres a flag to force wayland)

**Comment by LWinterberg** [comment]
Wayland is unsupported in the current version of Audacity and if it were enabled, would cause a massive memory leak. Audacity 4 will support it though.

**Comment by rempas** [comment]
> Wayland is unsupported in the current version of Audacity and if it were enabled, would cause a massive memory leak. Audacity 4 will support it though.

I just run Audacity 4.0 and it runs under Xwayland

**Comment by IFEware** [comment]
> I just run Audacity 4.0 and it runs under Xwayland

I strings'd the app and it does not use the usual QT_QPA_PLATFORM env var but instead AU_QT_QPA_PLATFORM, set this env var to wayland and the application should start up under wayland natively

it works well using KDE and traditional wlroots but hyprland users may experience a quirk with this app that dragging an audio file by its handlebar or any audio to the app itself will cause the app to dim and the dimming will go away once the app is unfocused and refocused which is very annoying

**Comment by Twig6943** [comment]
> I strings'd the app and it does not use the usual QT_QPA_PLATFORM env var but instead AU_QT_QPA_PLATFORM, set this env var to wayland and the application should start up under wayland natively

I wonder if this is documented anywhere xD

**Comment by kryksyh** [comment]
@Twig6943 @IFEware, we had a few issues with wayland before (namely VST3 windows embedding and floating toolbar positioning), so we preemptively disabled it for the release. We will certainly get to it later.
