### ISSUE TITLE
[AU4] - Selection - Pasting empty space

### ISSUE THREAD

**Issue by DilsonsPickles** [audacity/audacity#7521]
### Description

When a User pastes empty track space, it is treated the same way as pasting audio data - eating into other clips.

[Figma link](https://www.figma.com/design/oQEvoOqeKHQlqabmFmM0Mp/10---Selection?node-id=656-52145)

**Comment by dozzzzer** [comment]
@grliszas14 

- Sometimes, when pasting empty space, it throws the "Paste error":

https://github.com/user-attachments/assets/3a17d079-bab3-407d-8aba-e77cb46bc4bd

**Comment by grliszas14** [comment]
@dozzzzer 
How frequently does it happen?
I couldn't reproduce it even once, tried on different zoom levels, copying audio data or empty space, undoing changes etc. I think I know why it's happening but without a method to reproduce it it's hard to precisely fix it

Maybe we can merge it as is (I fixed other 2 bugs that you found) and create a follow-up task? Maybe other devs will have more luck reproducing it?

**Comment by dozzzzer** [comment]
@grliszas14 yeah, it's a bit hard to reproduce. Let's merge it then.
