### ISSUE TITLE
[AU4] Volume slider: tooltip is slightly delayed when moving the slider swiftly

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7522]
### Description

If you move the volume slider quickly, the tooltip may not appear immediately, so it may take an extra moment to appear.

https://github.com/user-attachments/assets/58595f51-4e8e-4d4b-9094-34ca8b3cbe6c

**Comment by dozzzzer** [comment]
@kryksyh now the tooltip appears immediately, but after the mouse is released and the cursor is moved away from the slider, it takes extra second or so for it to disappear:


https://github.com/user-attachments/assets/0e23e2d5-35f6-44ad-a5d4-9d154a903803

**Comment by kryksyh** [comment]
> it takes an extra second or so for it to disappear

Yes, this is done intentionally to prevent flickering. Do you think this is should work differently?

**Comment by dozzzzer** [comment]
> Do you think this is should work differently?

I would like to see the tooltip disappear immediately after the mouse cursor leaves the hover area. @DilsonsPickles WDYT?

**Comment by dozzzzer** [comment]
@kryksyh as far as the Pan knob tooltip behavior, this now works just as well as the volume slider. Thanks!

Another thing to point out is that currently, the tooltip flickers very rapidly a few times every time before disappearing. The screen recording doesn't catch it, so I'm not posting the video here. But if you go ahead and play with it, you'll be able to see what I'm talking about.

**Comment by kryksyh** [comment]
@dozzzzer yes, i have noticed this, all the tooltips are behaving like this, you can check the toolbar for example. Would you mind creating an issue for it?

**Comment by dozzzzer** [comment]
Sure thing!

**Comment by DilsonsPickles** [comment]
> > Do you think this is should work differently?
> 
> I would like to see the tooltip disappear immediately after the mouse cursor leaves the hover area. @DilsonsPickles WDYT?

I agree, I'd like to see the tooltip disappear immediately. I also find it a little jarring that I can move the volume slider for a second before the tooltip pops in. 

@dozzzzer what do you think? Definitely agree about it taking too long to disappear.

**Comment by kryksyh** [comment]
@dozzzzer  I've updated the pr
