### ISSUE TITLE
undo/redo button in top bar

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#7549]
It's the thing in the top right corner that's in like all of the designs!

@DilsonsPickles may have some super spec, but it's exactly what it looks like

**Comment by DilsonsPickles** [comment]
Visual spec ticket created [here](https://github.com/audacity/audacity/issues/7557) - needs to pass through QA first.

**Comment by grliszas14** [comment]
![image](https://github.com/user-attachments/assets/1233de02-6c73-4db6-8421-066c35ee089c)
Padding is a bit off for now. I'm waiting for Elnur's changes to be merged: https://github.com/musescore/MuseScore/pull/25095 and I will be able to fix that then

Bulletpoints:
* check buttons on the top-right
* check if state of the top-right buttons is the same as in the Edit menu actions
* additionally there should not be dialogs with "undo/redo not available" anymore -> if something is not enabled, than you can't click it and it's greyed-out (https://github.com/audacity/audacity/issues/7371)

**Comment by chinakov** [comment]
Tested, thanks
