### ISSUE TITLE
Scrolling speed over the track panel should match the one of the main project area

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7550]
When scrolling vertically with the mouse cursor over the track panel area,

<img width="500" alt="image" src="https://github.com/user-attachments/assets/b1621a2f-6c2b-45da-9285-5705538143ee">

scrolling speed is significantly lower than the one when scrolling with the mouse cursor in the main project area

<img width="500" alt="image" src="https://github.com/user-attachments/assets/3486ef60-515a-4060-bb9a-82af8f68bd5f">

The latter one is the correct one. The slower scrolling behavior should be changed in order to match the correct one.

**Comment by chinakov** [comment]
Blocked by https://github.com/audacity/audacity/issues/7493, as the User can't scroll horizontally in the Tracks area currently.

**Comment by chinakov** [comment]
This is fixed, as the scrolling speed is now the same for both areas.
