### ISSUE TITLE
Track panel elements are misaligned vertically

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7551]
1. Increase a track's height
2. Observe

Act.: The name of the track is aligned to the centre, the rest is aligned to the bottom:
<img width="600" alt="image" src="https://github.com/user-attachments/assets/4cfe0341-85ef-4a85-a6ff-6cf80e01e8c3">

Expected: Everything is aligned to the top:
<img width="600" alt="image" src="https://github.com/user-attachments/assets/42fab8fc-818d-48b6-94b0-81decabdc748">

**Comment by chinakov** [comment]
Fixed.
