### ISSUE TITLE
A single click on the track's name area doesn't select the track

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7552]
Clicking in the area that is roughly marked on the screenshot below doesn't cause the track to become selected:

<img width="405" alt="image" src="https://github.com/user-attachments/assets/c8f99158-cc2f-454d-9011-274eb79ba26d">

**Comment by dozzzzer** [comment]
To be re-tested after #7687  is implemented

**Comment by chinakov** [comment]
This is fixed.
