### ISSUE TITLE
Display the user's email when they register on audio.com via Audacity

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7563]
### Steps to reproduce

1. Initiate Cloud project upload
2. Proceed to account creation
3. Go to Preferences > Cloud
4. Check out the user's name

### Expected behavior

the user's email address is displayed

### Actual behavior

"Account not linked" is displayed:

![image](https://github.com/user-attachments/assets/41372bdd-531e-4138-891a-0f6562d8e8e1)

### Audacity Version

Audacity 3.7.x

### Operating system

Other

**Comment by kryksyh** [comment]
@dozzzzer as per discussion we decided to display unique username not email address
