### ISSUE TITLE
Recording creates a track but UI does not update

### ISSUE THREAD

**Issue by grliszas14** [audacity/audacity#7564]
Steps to reproduce:
1. Create an empty project
2. Press 'record'
3. Observe

What's happening: the track is created under the hood, recording is saved but UI is not updating at this point at all. To be able to see that it's true, save project, close it and open it again -> recorded clip on a new track will appear.

**Comment by dozzzzer** [comment]
I think it might be the same problem I reported in another ticket https://github.com/audacity/audacity/issues/7431#issuecomment-2416100821

**Comment by chinakov** [comment]
Tested, thanks!
