### ISSUE TITLE
Extend theme manager to make it easier to switch between custom themes

### ISSUE THREAD

**Issue by coldspark29** [audacity/audacity#757]
As of now, you can only copy one theme into the audacity profile folder and then choose "custom". Would be nice if you could copy several themes in there and then choose from the menu.

I think it would also be great if these themes were added by default. They très chique.
[https://www.deviantart.com/podel1/art/Audacity-Clean-Dark-Theme-1-3-by-Podel-715604676](https://www.deviantart.com/podel1/art/Audacity-Clean-Dark-Theme-1-3-by-Podel-715604676)

**Comment by SteveDaulton** [comment]
It is unlikely that theme support will be developed further until there has been a significant amount of "under the hood" work done relating to the Audacity GUI, so I'm closing this feature request for now. When the "under the hood" work has been completed there will be a lot more scope for improving the appearance of Audacity.
