### ISSUE TITLE
Attempt to save a project to the cloud with special characters in its name causes an error

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7570]
### Steps to reproduce

1. Initiate project cloud upload
2. enter a name with a forward slash or a backslash symbol into the **Project Name** text box: `/\`
3. click Save
4. observe

### Expected behavior

1. The user will be prompted to log in / sign up, or if they are already logged in, the project upload will begin OR
2. The user will be given an appropriate error message saying that these symbols aren't allowed in the project name @LWinterberg please clarify

### Actual behavior

Project version conflict error dialog pops up:

https://github.com/user-attachments/assets/d1d13884-a9b6-4cd7-9b51-e417983811bb

### Audacity Version

Audacity 3.7.x

### Operating system

macOS

**Comment by LWinterberg** [comment]
We have code which should be replacing invalid characters with "_" (the ones you're at risk of actually entering anyway). For some reason, it doesn't work though.Let's make that work.

**Comment by kryksyh** [comment]
@dozzzzer @chinakov, this issue was addressed on the backend side and has already been pushed to production. So, is ready to test.

**Comment by dozzzzer** [comment]
Tested
