### ISSUE TITLE
A crash when trying to undo/redo adding and reordering of the effect on the master

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7573]
### Steps to reproduce

1. Generate a rhythm track
2. Add a built-in effect to the master (e.g. Bass and treble)
3. Turn OFF and then turn ON the entire master effects chain by clicking the blue power button
4. `Edit > Undo` x2
5. Observe: the rhythm track clip is gone
6. `Edit > Redo`
7. Observe: the rhythm track clip is back
8. Click Play
9. Click Stop
10. Ctrl (Cmd) + W -> "No"

### Expected behavior

No crash; the project is closed.

### Actual behavior

A crash:

https://github.com/user-attachments/assets/2509bed6-c704-451a-8915-6c46267da781

### Audacity Version

Audacity 3.7.x

### Operating system

macOS

**Comment by ianalarina** [comment]
Might be related with https://github.com/audacity/audacity/issues/7571

**Comment by DavidBailes** [comment]
Alternative steps to reproduce:
1. Add an audio track
2. Open the realtime effects panel
3. Press either of the two power buttons
4. Close the project

**Comment by saintmatthieu** [comment]
@ianalarina unfortunately not related.

**Comment by chinakov** [comment]
This is fixed, thanks!
