### ISSUE TITLE
Create layout for mobile devices

### ISSUE THREAD

**Issue by coldspark29** [audacity/audacity#758]
I would really like to see a layout for mobile devices like the Pinephone. As of now, it is not useable.

**Comment by SteveDaulton** [comment]
Audacity does not currently support mobile devices or mobile operating systems.
A mobile version of Audacity may be developed in the future.

**Comment by coldspark29** [comment]
The application itself works really well on the Pinephone. The problem is just the layout. To avoid misunderstanding: The Pinephone is a mobile phone that runs a full ARM-based Linux. I am not talking about Android. So there is just a need for proper scaling for the smaller screen.

**Comment by SteveDaulton** [comment]
To be really usable I think it would need extensive redesign of the interface rather than just scaling, which is on the cards for the future, but not the immediate future. Thanks for the clarification.

**Comment by coldspark29** [comment]
The developers of the phone said that the line input of the SoC is not connected to the jack anyway. So there would just be mic input and for that a simpler app would suffice. Linux phones are on the horizon though. Maybe in 1-2 years it would be worth the effort.
