### ISSUE TITLE
Implement base view for Reverb effect

### ISSUE THREAD

**Issue by igorkorsukov** [audacity/audacity#7589]
### Description

Perhaps the design will change, this is just a port of the view from au3, it is necessary in order to implement the work with presets

**Comment by dozzzzer** [comment]
@igorkorsukov 

- There is no input value validation, meaning you can enter any positive or negative value and apply the effect, which will cause Audacity to crash.
- The increment for effect parameters is 0.5%, as opposed to 1% in the AU3 implementation.

<img width="155" alt="image" src="https://github.com/user-attachments/assets/d15bd9d0-301c-4fdd-ad6f-071398203e7f">

- When no selection is made, an attempt to open up the Reverb should bring up the following error message:

<img width="450" alt="image" src="https://github.com/user-attachments/assets/276822d6-aff3-4442-b495-22ebb1985c60">

**Comment by dozzzzer** [comment]
@igorkorsukov 
- Make each text box a bit wider so that the fractional part isn't overlapped by the up/down controls anymore
<img width="450" alt="image" src="https://github.com/user-attachments/assets/3a0b15b3-96ae-4d4d-953e-862776ae1971">
- Decreasing the values using the down arrow is possible, but increasing the one by clicking the up arrow isn't:

https://github.com/user-attachments/assets/ac94d0d9-7afa-4932-902b-469b80dac2fe

- Change the error message copy when no audio is selected to
`Select the audio you want the Reverb to use and try again`

- Sometimes it throws an error when I try to apply the Reverb to a selection:

https://github.com/user-attachments/assets/72c54a22-9d6c-4077-b34c-7e76a2d25c64

**Comment by igorkorsukov** [comment]
* Make each text box a bit wider so that the fractional part isn't overlapped by the up/down controls anymore - fixed 
* Decreasing the values using the down arrow is possible, but increasing the one by clicking the up arrow isn't  -fixed 
* Change the error message copy when no audio is selected to - changed 
* Sometimes it throws an error when I try to apply the Reverb to a selection - couldn't reproduce, let's watch until we get details

**Comment by dozzzzer** [comment]
@igorkorsukov 

I'm still getting an error when I try to apply the effect to a selection:

<img width="400" alt="image" src="https://github.com/user-attachments/assets/c9d88500-d49b-49fc-a988-7143ab1d468c">

Please try to make a selection like on the screenshot and set every Reverb's parameter to a maximum. You can use my project if you wish: 
[pluck.aup3.zip](https://github.com/user-attachments/files/17873438/pluck.aup3.zip)

The issue can be reproduced on Windows and MacOS.

**Comment by igorkorsukov** [comment]
@dozzzzer 

* I'm still getting an error when I try to apply the effect to a selection: - I looked, the error is deep in the logic of the effect execution, it has nothing to do with the current task, to the implementation of the view settings. It is better to create a separate issue and assign it to @saintmatthieu 

```
void WaveTrackSink::DoConsume(Buffers &data)
{
...
if (mIsProcessor) {
         mOk = mOk &&
            mLeft.Set(data.GetReadPosition(0),
               floatSample, mOutPos, inputBufferCnt, mEffectiveFormat);

...
bool WaveChannel::Set(constSamplePtr buffer, sampleFormat format,
   sampleCount start, size_t len, sampleFormat effectiveFormat)
{

   for (const auto &clip: Intervals())
   {

                  // Test as also in WaveTrack::GetOne()
         if (clip->HasPitchOrSpeed())
            return false;   <--------------------------
```

**Comment by chinakov** [comment]
Tested, @igorkorsukov - here is your new issue https://github.com/audacity/audacity/issues/7797
