### ISSUE TITLE
Immersive Dark mode / Dark title bar (Windows)

### ISSUE THREAD

**Issue by Yakov5776** [audacity/audacity#7593]
### Problem to be solved

Dark mode which includes the title bar

### Your idea

I've been a long-time user of Audacity and I absolutely love the software, however, the bright white titlebar really sticks out and it would be very fitting to use Windows 10/11's so-called 'Immersive dark mode'.

```c
DWMAPI DwmSetWindowAttribute(
  HWND    hwnd,
  DWORD   dwAttribute,
  LPCVOID pvAttribute,
  DWORD   cbAttribute
);
```

(`dwmapi.dll` / `dwmapi.h`) using the documented constants `DWMWA_USE_IMMERSIVE_DARK_MODE = 20` (for Windows 10 versions 2004 and later)

I've attached a few screenshots illustrating how Audacity might look with a dark title bar. I believe this feature would improve the visual appeal for using Audacity.

### Prior art

Before:
![Audacity_j2Yc3LtUOX](https://github.com/user-attachments/assets/96c9e4a3-76ae-4c6d-babb-68e7d0a58728)
After:
![Audacity_URuK6Akqig](https://github.com/user-attachments/assets/a68eecdb-0dbe-4f77-ac44-10302d832cee)

**Comment by LWinterberg** [comment]
This is fixed in Audacity 4
