### ISSUE TITLE
Musical Import Length Detection

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#7598]
### Bug description

If the User tries to import a musical file (a rhythm track, for example) - the length of detection of the musical file, which should be 1 minute, is actually 57 seconds. This disallows the User to import musical files that are longer than 57 seconds but shorter than 1 minute. 

### Steps to reproduce

1. Launch Audacity
2. Create a 56 second stereo rhythm track, and import it into a new project
3. Observe musical file being detected
4. Create a 57 second stereo rhythm track, and import it into a new project
5. Observe result

https://github.com/user-attachments/assets/5624a0fe-d122-4270-bb79-8deda655e891

### Expected behavior

Files of length >1minute should be detected as musical files.

### Actual behavior

Files of length >1minute are not detected as musical files.

### Audacity Version

Audacity 3.7.x

### Operating system

Windows

### Additional context

This issue was introduced with the music detection issue - can be reproduced on any release that contains this issue.

**Comment by kryksyh** [comment]
@chinakov, does your 57'' file really have a length of 57 seconds? I've noticed that it was loaded as something closer to 64 seconds.

**Comment by chinakov** [comment]
Just re-checked the issue, @kryksyh - the issue not reproducible anymore.
