### ISSUE TITLE
Apple Silicon build (e.g. M1 processor)

### ISSUE THREAD

**Issue by vassudanagunta** [audacity/audacity#760]
**Is your feature request related to a problem? Please describe.**

A native build for Apple Silicon Macs will both perform better and use much less batter power. 

**Describe the solution you'd like**

Audacity released in an Apple universal binary that includes an Apple Silicon build.

**Describe alternatives you've considered**

Currently Audacity's Intel build works on M1 Macs using Rosetta translation software.

**Comment by Margen67** [comment]
#684

**Comment by vassudanagunta** [comment]
@JamesCrook @Margen67 I opened this issues because that one was closed for some reason. One of them should be re-opened... I think.

**Comment by myzhang1029** [comment]
@vassudanagunta I've made an experimental M1-only Audacity from the master branch at [myzhang1029/audacity](https://github.com/myzhang1029/audacity-applesilicon) as well as a FFmpeg binary that works with it, available with `brew install myzhang1029/myzhang1029/ffmpeg-audacity`. I haven't yet experienced any serious problems in my daily tasks. It is not a universal build though.

**Comment by vassudanagunta** [comment]
@myzhang1029 Thanks! 

But you should considered working on a fork of audacity that is not owned by Muse Group and has been stripped of telemetry and other bad things.

e.g. https://github.com/tenacityteam/tenacity
