### ISSUE TITLE
Crash when making a stereo track from mono tracks is cancelled

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7610]
### Steps to reproduce

1. Generate a 1-hour chirp
2. Duplicate it
3. Track Panel > Make stereo track
4. Click Cancel in the progress dialog
5. Observe

### Expected behavior

No crash; the process is terminated.

### Actual behavior

A crash.

https://github.com/user-attachments/assets/af7abab3-7e03-49a8-8be9-5986feda769a

### Audacity Version

Audacity 3.7.x

### Operating system

Windows, macOS, Linux

**Comment by dozzzzer** [comment]
Tested

**Comment by kryksyh** [comment]
@dozzzzer fixed that

**Comment by dozzzzer** [comment]
Tested
