### ISSUE TITLE
Neither consecutive nor non-consecutive track selection via marquee selection works

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7631]
<details>
<img width="942" alt="image" src="https://github.com/user-attachments/assets/cb3185ec-f08d-4c49-8ee5-d620ae21d231">
<img width="951" alt="image" src="https://github.com/user-attachments/assets/0bc6a40e-ce32-4cf8-bb89-376beb9fdb94">
</details>

When making a marquee selection, the corresponding tracks aren't marked selected.
Furthermore, after such an operation, clicking into the first track's track panel doesn't mark it as selected either. Also, observe how the third track remains always selected even after clicking into the second track.

See the video:

https://github.com/user-attachments/assets/592f4124-2455-4356-8ae9-82a6a5590710

**Comment by grliszas14** [comment]
@dozzzzer @chinakov please re-test, it works for me
