### ISSUE TITLE
Implementation task. When a user makes a selection, the play / stop behaviour matches AU3

### ISSUE THREAD

**Issue by Eism** [audacity/audacity#7648]
### Description

At the moment the player ignores the user's selection range. 
We should match behaviour found in Audacity 3.

https://github.com/user-attachments/assets/3e4cebc9-1556-470e-b387-474b49d9569e

Desired behaviour for Play (**Spacebar**)
- When there is a selection made, and the player has stopped, pressing play (or pressing spacebar), should play the audio from the beginning to the end of the selected audio and then stop.
- If the play function is active and the user makes a selection, once the player has stopped, the cursor should move back to the beginning of the audio selection.

Desired behaviour for Play/Return cursor (**Shift+Spacebar**)
- **shift+spacebar** should ignore audio selections. When pressing **shift+spacebar**, the cursor should play from it's current position and not stop at the end of the audio selection. If the user presses **shift+spacebar** again, then the cursor should behave as it does right now - returning the cursor back to wherever the user initially played from.

**Comment by DilsonsPickles** [comment]
@Eism do you require a spec to implement this behaviour? I don't want to spend time mocking up this behaviour in Figma if we can use AU3 as a reference. 

@Tantacrul I'm fine with this behaviour and would be hesitant to change it given that it's playback + selection (two of the core interaction areas)

**Comment by Tantacrul** [comment]
I can provide specific instructions when needed @Eism @DilsonsPickles. I agree, we don't need a spec for this.

**Comment by chinakov** [comment]
This is implemented, thanks.
