### ISSUE TITLE
Allow macros to run when recording, but stop the recording before running them

### ISSUE THREAD

**Issue by Timmmm** [audacity/audacity#765]
It would be nice to be able to stop the recording and perform some action with a single key press. Here are two examples from the forum:

* [Stop recording and save the file](https://forum.audacityteam.org/viewtopic.php?t=103088)
* [Stop the recording and delete the last 0.1s (to eliminate the keypress sound)](https://forum.audacityteam.org/viewtopic.php?f=46&t=116646)

According to a comment in the first thread macros can't be run while recording because recording is considered a critical function. That makes sense but I think we can solve this problem without affecting recording.

Audacity should allow macros to run while recording, but it should stop the recording before running the macro. That would solve both of these use cases without making anything else worse.

Let me know if you would accept a PR with this solution btw - I might have a go.

**Comment by Shreyansh252001** [comment]
what is macro like can you please clarify and where is the file from where it is  being operated in the software?
Actually i am beginner in GSOC and i know OOPS and c++ basic only!!but that's not an issue i will research and learn just tell me basically where are those places to make changes so that your demand of applying macros to stop recording is fulfilled!

**Comment by Timmmm** [comment]
Just Google "Audacity macro". I have no idea where they are handled in the code - I haven't looked into it yet.

**Comment by JamesCrook** [comment]
@Timmmm this sounds like a worthwhile enhancement.

We might want some safeguard against any old macro being run.  For example, we might want to have the first command be 'stop' to allow the macro to run (if recording).

Interested in a PR, though I'm not promising to personally shepherd it through the system.

**Comment by LWinterberg** [comment]
pressing stop and then applying the macro by hotkey is insignificantly slower than doing this. This is unlikely to be implemented any time soon, or at all.
