### ISSUE TITLE
Audacity crashes when the user opens "Extra\Adjust playback speed" dialog

### ISSUE THREAD

**Issue by kryksyh** [audacity/audacity#7652]
### Bug description

When the users clicks on "Adjust playback speed" item menu Audacity crashes

### Steps to reproduce

1. Enable Extra menus (View\Extra Menus)
2. Click on Extra\Play at speed\Adjust playback speed

### Expected behavior

Show a dialog

### Actual behavior

A crash

### Audacity Version

Audacity 3.7.x

### Operating system

macOS

**Comment by dozzzzer** [comment]
Tested
