### ISSUE TITLE
Timeline interaction improvement

### ISSUE THREAD

**Issue by Eism** [audacity/audacity#7659]
### Description

![image](https://github.com/user-attachments/assets/559ffc0b-972d-4489-821c-d3fac1bb2b86)

The timeline ruler that houses the cursor and ruler is split vertically into two parts.
- Top section
- Bottom section

Improvements:
- **Spacebar** should map to play / pause
- **Shift+Spacebar** should map to play / stop (exactly how Spacebar works in Audacity 3)
- **Ctrl+Spacebar** should map to 'play, ignoring loop' (in AU3 this is **shift+spacebar**)

- When Play is activated, the user can click anywhere on the bottom section of the timeline ruler. This moves the cursor immediately to that position and keeps playing.
- When Play is not activated, the user can click anywhere on the bottom section of timeline ruler, which plays from that position immediately (same as AU3).
- When Audacity has reached the end of the final clip in the project and stops, play should start from zero.

- The top section of the timeline ruler should not include any interactions for the cursor. The top section will be reserved for interactions related to looping only.

**Comment by Tantacrul** [comment]
Uploading AU4_Timeline_Ruler_Compressed.mp4…

**Comment by Tantacrul** [comment]
https://github.com/user-attachments/assets/dadb0555-e627-4ff3-87db-da692d777380

**Comment by Dinesh0N** [comment]
nice 🔥
