### ISSUE TITLE
Crash when copying and closing the project 

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7664]
### Steps to reproduce

1. Open a project with clips
2. Make a selection and hit Ctrl + C
3. Ctrl + W to close the project

### Expected behavior

No crash, the project is closed.

### Actual behavior

A crash.

### Audacity Version

Audacity 4 alpha

### Operating system

Windows, Linux

**Comment by chinakov** [comment]
Fixed via https://github.com/audacity/audacity/pull/7681, thanks!
