### ISSUE TITLE
It's possible to extend a clip beyond the zero time mark when un-trimming

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7668]
### Steps to reproduce

1. Trim a clip
2. Move it close enough to the zero time mark so that the left trim handle is visible
3. Grab the left trim handle and move it leftwards as far as you can
4. Observe

### Expected behavior

As soon as it reaches the zero time mark, it cannot go any further.

### Actual behavior

It can go past the zero time mark. Upon clicking the clip, its left edge gets aligned with the zero.

https://github.com/user-attachments/assets/0b6eeaa1-f4f9-4e41-aaf1-56e59cab9558

### Audacity Version

Audacity 4 alpha

### Operating system

Windows, macOS, Linux

**Comment by dozzzzer** [comment]
@DilsonsPickles Design is needed for this one

**Comment by DilsonsPickles** [comment]
Surely the solution here is just to prohibit the User from trimming a clip beyond 0?
