### ISSUE TITLE
Effects - Generate Silence

### ISSUE THREAD

**Issue by ianalarina** [audacity/audacity#7685]
### Description

Implement Generate Silence in Audacity 4

**Comment by kryksyh** [comment]
@dozzzzer fixed, please retest

**Comment by dozzzzer** [comment]
@kryksyh 
When a selection is made, the Duration format is `hh:mm:ss+milliseconds`

<img width="429" alt="image" src="https://github.com/user-attachments/assets/5a0b6a94-334c-49a3-8e64-3413f4e1809f" />

**Comment by kryksyh** [comment]
@dozzzzer please retest

**Comment by dozzzzer** [comment]
Tested
