### ISSUE TITLE
Effects - Generate DTMF

### ISSUE THREAD

**Issue by ianalarina** [audacity/audacity#7686]
### Description

Implement Generate DTMF in Audacity 4

**Comment by chinakov** [comment]
Tested, and compared against DMTF generator in AU3. No issues noticed, thanks. The same parameters generate idenrical files in AU3 and AU4.

https://private-user-images.githubusercontent.com/139755141/388940086-d5754778-e4fd-4bd7-a080-c58f2c4e07d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyODAzODgsIm5iZiI6MTczMjI4MDA4OCwicGF0aCI6Ii8xMzk3NTUxNDEvMzg4OTQwMDg2LWQ1NzU0Nzc4LWU0ZmQtNGJkNy1hMDgwLWM1OGYyYzRlMDdkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQxMjU0NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDRjYjA4MWFlYmRjZWI0OTQ2NWIxNjc1NGQ3MmIyMDAxYzVmYjRlNWNhMmI0YTRkZWI1YTg4NTg5MWNjNWFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5t3kUBFgBVQeznhRWC4J3k-r3uNOcjCWC8uotZONlBI
