### ISSUE TITLE
Add reloading of external files

### ISSUE THREAD

**Issue by dabrain34** [audacity/audacity#769]
**Is your feature request related to a problem? Please describe.**
To avoid managing too many windows, would be nice to have a "reload" option when you need to reload
a file which has been modified externally

**Describe the solution you'd like**
Add a reload option which will take the current window's file

**Describe alternatives you've considered**
Open the file and close the previous windows

**Additional context**

**Comment by ajaypanthagani** [comment]
Hi, I would like to work on this feature.

**Comment by LWinterberg** [comment]
This depends on an ability to load (as opposed to import) external files to begin with, which currently is not possible.
