### ISSUE TITLE
Wrong amplitude value calculated in the Amplify effect

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7704]
### Steps to reproduce

1. Load up a project with an audio clip
2. Open up the Amplify effect
3. Review the amplification/amplitude values

### Expected behavior

The values correspond to the clip's loudness and are calculated properly.

### Actual behavior

Both values are wrong and do not depend on the audio data selected. 

<img width="464" alt="image" src="https://github.com/user-attachments/assets/edd02cce-ca1b-4f02-87d3-0cd566e62a33">

### Audacity Version

Audacity 4 alpha

### Operating system

Windows, macOS, Linux

**Comment by embarc-gabriel** [comment]
@dozzzzer 
This is working fine on my linux machine on the project that I have. (Using the current master branch)
Can you send me the project you use to test it?

**Comment by dozzzzer** [comment]
It is no longer reproducible in the latest master build @embarc-gabriel
