### ISSUE TITLE
Split cut/delete deletes the entire clip

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity#7706]
### Steps to reproduce

1. select a clip partially
2. Right-click > Split cut or split delete

### Expected behavior

The selected area is cut/deleted and a gap remains

### Actual behavior

Sometimes the entire clip gets deleted, sometimes nothing happens

### Audacity Version

Audacity 4 alpha

### Operating system

Windows, macOS

**Comment by grliszas14** [comment]
QA bulletpoints:
* right click on the clip or left click on the '3 dots' should open clip context menu
* right click over selection should open selection context menu
* if selection covers whole clip -> left click on the '3 dots' should open clip context menu (range selection disappears)
* check if selection-extend handles still work as expected
* right click over empty area should trigger canvas context menu (the one with new track actions)
* check if actions triggered via context menus work as expected (bare in mind that some of them are not implemented yet: show master tracks / select all / clear selection)

**Comment by chinakov** [comment]
Tested, thanks!
