### ISSUE TITLE
Microphone Input Not Detected Until Restarting Audacity

### ISSUE THREAD

**Issue by askadityapandey** [audacity/audacity#7708]
### Bug description

It's hard to  make it enhancement request or bug report, When opening Audacity, if a microphone is connected, the app does not automatically detect it unless it is restarted. This issue causes inconvenience as users must close and reopen the application to get proper input recognition.

### Steps to reproduce

Open Audacity without restarting after connecting the microphone.
Attempt to select the microphone for input.
Notice that the microphone does not appear in the list or work as expected.
Close Audacity and reopen it.
The microphone is now detected correctly.

### Expected behavior

Maybe it detects just after that?

### Audacity Version

Audacity 3.7.x

### Operating system

Windows, Linux

**Comment by LWinterberg** [comment]
Audio setup -> Rescan audio devices
