### ISSUE TITLE
Timelineruler/gridlines calculation bug

### ISSUE THREAD

**Issue by grliszas14** [audacity/audacity#7709]
see how ruler values changes on the video:

https://github.com/user-attachments/assets/9d3adeeb-11c3-4d78-b5fa-2fc85ac3cfdc

**Comment by grliszas14** [comment]
QA bulletpoints:
This can be tested along with https://github.com/audacity/audacity/issues/7714
* timeline ruler labels should not overlap each other on any zoom level
* labels/ticks should not shift left/right by one tick width at any time
* pay attention to the first gridline on the left, it should be better handled than in current master (should appear sooner when you scroll horizontally)
* label on the left edge you gracefully wrap underneath left edge of clips view instead of disappearing as soon as it touches an edge (when you scroll horizontally)

**Comment by dozzzzer** [comment]
Tested
