### ISSUE TITLE
Use unambiguous units for "Measure RMS"

### ISSUE THREAD

**Issue by endolith** [audacity/audacity#771]
**Is your feature request related to a problem? Please describe.**
If you generate a full-scale sine wave and then use the `rms.ny` plugin to measure it, it says -3 dB:

![image](https://user-images.githubusercontent.com/58611/112539189-0e014e00-8d87-11eb-8446-f42150b63790.png)

But "dB" for an RMS level is ambiguous, with different meanings in different contexts.

**Describe the solution you'd like**

This is consistent with the dBov unit in ITU-T G.100.1 telephony standard, so it could be labeled "-3 dBov" and that would be unambiguous.

However, I'd prefer that it use the unit dBFS, which is more common in pro audio contexts.  This is defined in AES17, IEC 61606, etc.  This would require multiplying the level by √2 (+3.01 dB), and then it could be labeled "0.000 dBFS"  (= "0 dB down from a full-scale sine wave")

Likewise, if you generate a tone with amplitude 0.0001 it should say "-80.000 dBFS", etc.

**Comment by JamesCrook** [comment]
Thanks.
A contributor has provided a solution you can use: https://github.com/audacity/audacity/pull/772

We're not planning to use/distribute it though.

**Comment by endolith** [comment]
It should be part of the rms.ny file distributed with Audacity
