### ISSUE TITLE
Fixed beats&measures ruler on tempo change (instead of fixed minutes&seconds)

### ISSUE THREAD

**Issue by grliszas14** [audacity/audacity#7718]

**Comment by grliszas14** [comment]
QA bulletpoints:
* when tempo changes the beats&measures ruler doesn't expand/shrink (remains still)
* it's minutes&seconds ruler that expands/shrinks on tempo change
* playcursor doesn't move on tempo change
* speed of the playback changes on tempo change
* changed tempo,timecode,snapping icons (also BPM was renamed to Tempo) - all accessible from "Customize toolbar"

**Comment by grliszas14** [comment]
note: should be tested after https://github.com/audacity/audacity/pull/7715 is merged

**Comment by chinakov** [comment]
Tested, thanks!
