### ISSUE TITLE
Let the selection on the timeline follow along the clip as the project tempo changes

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7726]
### Problem to be solved

Currently, when selecting a clip and changing the project tempo, the selection on the timeline stays in place and doesn't follow the clip's movement.

![2024-11-15_13-41-08 (1)](https://github.com/user-attachments/assets/c443f6ab-fd52-4bab-96bd-35286a52d027)

### Your idea

The idea is to let the selection on the timeline follow the clip as the project tempo changes.
The selection should be tied to the interval in beats, not in seconds.

**Comment by chinakov** [comment]
Tested, the selection on the timeline now follows the clip along as the project tempo changes. 


https://github.com/user-attachments/assets/54762c48-c9f3-475e-a1d3-f1a23bbb5030
