### ISSUE TITLE
The BPM up and down arrows should change the tempo continuously while the LMB is pressed.

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7728]
At the moment you can only change the BPM value by 1 bpm at a time. Holding down the LMB should increase or decrease the value continuously, just as AU3 does.

<img width="308" alt="image" src="https://github.com/user-attachments/assets/8d2c02ae-f537-4b90-bd3a-eab18b09eba9">

**Comment by chinakov** [comment]
This is fixed, thanks!
