### ISSUE TITLE
 Mixing and rendering tracks into a new track ignores Master Effects

### ISSUE THREAD

**Issue by juzzlin** [audacity/audacity#7735]
### Bug description

I find it confusing and not-that-convenient that mixing and rendering tracks into a new track applies Realtime Effects, but not Master Effects even though they are enabled. 

### Steps to reproduce

1. Have some tracks
2. Have some Realtime Effects and Master Effects enabled
3. Select all tracks and render into a new track

### Expected behavior

Both Realtime Effects and Master Effects are applied on the new track - if enabled.

### Actual behavior

Only Realtime Effects are applied. The only way to apply Master Effects is to export. There's no hint or tool tip explaining the current behavior, only "Master Effects Applies to all tracks".

### Audacity Version

Audacity 3.7.x

### Operating system

Linux

**Comment by LWinterberg** [comment]
This is intentional as mix&render are per-track operations.
