### ISSUE TITLE
Internal error at DBConnection.cpp line 275. Please inform the Audacity team at https://forum.audacityteam.org/.

### ISSUE THREAD

**Issue by timtas** [audacity/audacity#774]
Projects cannot be saved

1. Create a new project, or open an existing one
2. Save it
3. Close it

An internal error box appears:

Internal error at DBConnection.cpp line 275. Please inform the Audacity team at https://forum.audacityteam.org/.

**Additional information (please complete the following information):**
 - Linux (Linux from Scratch 10.0)
 - Audacity 3.0.0
 - Sqlite 3.34.1

**Comment by JamesCrook** [comment]
Could you attach the log please?

**Comment by timtas** [comment]
I have now resolved this issue by adding "-Daudacity_use_sqlite=local" to cmake, forcing the use of the bundled library version, so the issue might be closed with this work-around.

I now however am stuck at opening aup3 files, always getting the error: "Failure parsing project information". But I guess I will open a separte issue for that.

**Comment by JamesCrook** [comment]
Note that we patched an issue for FreeBSD subsequent to 3.0.0 tag.  https://bugzilla.audacityteam.org/show_bug.cgi?id=2697

**Comment by timtas** [comment]
Ok, will rebuild with that, test and give you an answer. I'm not really optimistic though, as my problem also happens with newcly created projects. But it's certainly worth a try.

**Comment by timtas** [comment]
Sadly, I was right, this patch did not fix my issue. Is it advisable to delete the ~/.audacity-data directory after an upgrade, might there be something in there causing problems?

**Comment by JamesCrook** [comment]
Best bet is to use very latest code form GitHub, which has more reporting in it, compile with that, and post info from the logs (help->diagnostics).

Might as well delete ~/.audacity-data directory.  It's unlikely to be a problem, but good to rule out one more thing.

We only officially support Windows (32bit), macOS and Ubuntu.  We also only support builds using our patched wxWidgets 3.1.3.

**Comment by timtas** [comment]
Yes, I'm using your patched wxWidgets 3.1.3, and I previously never had any problems with building audacity from source. It's clear that you cannot support any odd platform, I will give git master a go and see where that gets me. In the meantime, I'm very happy with 2.4.2

**Comment by timtas** [comment]
So, very good news! I now compiled git master from source, and while I cannot open the previously created aup3 files, I can both:
- open old projects, store them as aup3 and then successfully open the new aup3 file
- create a new project, save it as aup3 and the re-open it.

So, to summarize, all my issues are resolved with git master audacity, and local sqlite

Thanks again for your help.

**Comment by JamesCrook** [comment]
Thanks timtas.  That's good to hear.
