### ISSUE TITLE
Turning off automatic tempo detection.

### ISSUE THREAD

**Issue by DavidBailes** [audacity/audacity#7740]
In the description of major features for 3.5, it is stated that:
"Automatic tempo detection can be turned off via Preferences -> Import/Export."

This is not completely accurate. See the table on this page:
https://github.com/audacity/audacity/pull/5570
If the pref is set to "do nothing" and the timeline is set to "beats and measures", then automatic tempo detection is used.

It can only be turned off if the pref is set to "do nothing" and the timeline is set to "minutes and seconds".

**Comment by chinakov** [comment]
This is tested, the tempo detection can be turned off with either timelines.

**Comment by petersampsonaudacity** [comment]
@LWinterberg @saintmatthieu @DavidBailes 

I have updated the 3.7 manual for the fix that Mattieu has made.

On the page for Import/Export Preferences it now says:
![image](https://github.com/user-attachments/assets/dcac4819-129a-4dee-9a7b-95ffad5951a7)

**Comment by DavidBailes** [comment]
> @LWinterberg @saintmatthieu @DavidBailes
> 
> I have updated the 3.7 manual for the fix that Mattieu has made.
> 
> On the page for Import/Export Preferences it now says: ![image](https://private-user-images.githubusercontent.com/50205984/390016345-dcac4819-129a-4dee-9a7b-95ffad5951a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MDEwODEsIm5iZiI6MTczMjcwMDc4MSwicGF0aCI6Ii81MDIwNTk4NC8zOTAwMTYzNDUtZGNhYzQ4MTktMTI5YS00ZGVlLTlhN2ItOTVmZmFkNTk1MWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDA5NDYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlZWExYjI1NjNhMDhkNmI5NzRiNWM1NTQ0YzZkMGUxY2U4ODNmNGU0MTA1N2UxODVhYzY3YWZkYjkwYWJiN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.k_j60CzeeldBcTlSQDx5OBW9cYwzGy8EJenzLudYZBE)

But there are now two settings:

![image](https://github.com/user-attachments/assets/dbe52492-48fb-44ef-9a42-2d2d2abf8129)

**Comment by petersampsonaudacity** [comment]
@DavidBailes   Thanks David, oh so it does - that'll teach me to be lazy and make assumtions ...

I can fix this later.

@saintmatthieu @LWinterberg 
This begs the question:  the prefs now only talk about "music loops" so
a) does this only apply to loops and nor normal full-track import,
b) what defines a loop?

**Comment by DavidBailes** [comment]
> This begs the question: the prefs now only talk about "music loops" so
> a) does this only apply to loops and nor normal full-track import,
> b) what defines a loop?

My understanding is that these are the methods used to try and detect the tempo of an audio file, and they are used in the following order:

1. The file's metadata (tags) are checked to see if a tempo is specified.
2. The filename, and its path are checked to see if it contains the tempo. The format must be a number followed by bpm. An example of such a filename is fred60bpm.mp3.
3. The file's audio is analysed, but this is only done if the length of the audio in the file is no more than 60 seconds.

**Comment by saintmatthieu** [comment]
Hi @petersampsonaudacity and @DavidBailes !
David is correct, but there is one precision worth being made: in 3., the analysis only tests whether it's a loop or not. A music import with clear and steady tempo, if not edited to be made loopable, should not be detected as loop. (It's a limitation of the algorithm more than a deliberate technical choice.)
This is probably why @Tantacrul chose the term of "music loops".
Now steps 1. and 2. don't care if it's a loop or not, which makes this choice of word less accurate. It may do the job, though: I expect users will look for this pref if they get false positives of loop detection, which mostly only occur when step 3 gets involved.

**Comment by DavidBailes** [comment]
> there is one precision worth being made: in 3., the analysis only tests whether it's a loop or not. A music import with clear and steady tempo, if not edited to be made loopable, should not be detected as loop.

@saintmatthieu . Thanks for the clarification.

**Comment by JamzTyson** [comment]
> in 3., the analysis only tests whether it's a loop or not. A music import with clear and steady tempo, 

While music loops often have a steady tempo, not all music loops do. For example, a loopable pad sound may not have a detectable tempo at all, or a loop may change tempo and then change back again, or a loop may begin with a "1 and 2 and" rhythm and change to a "1 2 3 4" rhythm (double tempo), or something else that cannot be detected as a "steady tempo".

I assume that in such cases, Audacity would choose not to consider it a "music loop" and the user would have to stretch it manually to fit the project tempo?

**Comment by saintmatthieu** [comment]
Yes.

**Comment by petersampsonaudacity** [comment]
@saintmatthieu @DavidBailes @Tantacrul 

So this is what the 3.7.1 manual now says (with an updated prefs pane image of course):

![image](https://github.com/user-attachments/assets/450b69c1-c507-4733-9dea-8433a7212f37)

**Comment by petersampsonaudacity** [comment]
@saintmatthieu 

That advice div (yellow block) talking about tempo changes and compound time was on that page long before your recent changes, I think from the time that Muse first introduced the Beats and Measures Timeline Ruler.

But If you think we should remove it - then I can do that.  Advice please ...

**Comment by saintmatthieu** [comment]
@LWinterberg , what do you say ?
