### ISSUE TITLE
Let the clip expand into another clip when its speed is reset to 100%.

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7746]
### Description

In a situation like the one shown in the screenshot below, when the clip speed is over 100%, it's impossible to reset the speed of the left clip by clicking on its speed indicator while holding down the Ctrl (Cmd) key. This would require the clip to expand into the right clip.

<img width="349" alt="image" src="https://github.com/user-attachments/assets/d4bd6320-9f2e-41c8-b41e-5b5e6cf501fa">

**Comment by dozzzzer** [comment]
@Eism 
If you change the clip's speed to e.g. 150%, and then to 110%, you'll see that the speed indicator shows 109% not 110%:

![2024-12-10_14-07-12 (1)](https://github.com/user-attachments/assets/ba44a695-520c-4936-98fb-62ae0b4e9cfe)

This is a regression against master.

**Comment by chinakov** [comment]
One issue noticed, talked with @Eism - we've decided to create a separate task for it, as this task is blocking some other things. Subsequent task - https://github.com/audacity/audacity/issues/7887
