### ISSUE TITLE
When toggling "stretch to match tempo" back on, the clip should retain its length and don't shrink or expand

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7750]
1. Place two clips next to each other
2. Disable "stretch to match tempo" on the left one
3. Decrease the tempo
4. Move the right-hand clip right next to the left one
5. Enable "stretch to match tempo" on the left one
6. Observe: 
- the clip expands as soon as you enable the "stretch to match tempo"

Act. result: the clip shouldn't change its size

https://github.com/user-attachments/assets/a2e105c5-0a5d-431b-a2a3-e6e2604af760

**Comment by chinakov** [comment]
Tested, fixed.
