### ISSUE TITLE
Disallow entering zero into the Speed text box of the Pitch and Speed dialog

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7751]
Entering zero into the Speed text box shouldn't be possible.

<img width="320" alt="image" src="https://github.com/user-attachments/assets/1a9b73ee-42e3-4658-9e97-dfaa209a3f9f">

**Comment by chinakov** [comment]
When 0 is entered into the Speed text box of the Pitch and Speed dialog, the clip header shows '0%' as its speed, while the dialog states '1.000%'.

![image](https://github.com/user-attachments/assets/e1697aea-5382-4b8b-a405-b545e10dc22a)


After 0 has been entered, it is impossible for the User to input any new value into the dialog, it gets reset to '1.000%'. 


https://github.com/user-attachments/assets/52ef3f43-34c0-4b6a-82c6-8d261c1bcdba


If the User now deletes the '0%' clip, a failure message is shown: 

![image](https://github.com/user-attachments/assets/f4720383-8682-4fdb-9f28-416db33bb924)

**Comment by dozzzzer** [comment]
Tested

**Comment by dozzzzer** [comment]
Tested
