### ISSUE TITLE
Allow entering the values with a fractional part into the Speed text box of the Pitch and Speed dialog

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7752]
...to reflect the AU3 behavior.

@LWinterberg @DilsonsPickles how many digits do we want to support? Does 3 sound good?

<img width="536" alt="image" src="https://github.com/user-attachments/assets/eaa9cfb8-db16-4719-8a98-92e144263a9d">

**Comment by chinakov** [comment]
3 digits.

**Comment by dozzzzer** [comment]
@DilsonsPickles I think you didn't take the % symbol into account bc currently it gets overlapped by the up and down arrows:

<img width="283" alt="image" src="https://github.com/user-attachments/assets/53563a7e-9614-4128-860d-5938a4d21e9a">

**Comment by DilsonsPickles** [comment]
That's because in my design I have the percentage symbol in the input label rather than in the field. I've checked MS4 and % goes inside so... new value will be 88.888% which is 88px + 8px padding right. So 96px.

Is max value 99.999 or 999.999?

**Comment by dozzzzer** [comment]
> Is max value 99.999 or 999.999?

The latter.

**Comment by dozzzzer** [comment]
@Eism anything more than 3 digits in the fractional part should be disallowed immediately, not when you click away:

![2024-12-10_14-01-48 (1)](https://github.com/user-attachments/assets/1dc6fcee-adaa-4664-8181-acfe2d1ac38e)

**Comment by chinakov** [comment]
![image](https://github.com/user-attachments/assets/457f0ccb-3d9b-4852-a167-bc3274f9a2e9)

- Text box now allows for percentage sign + biggest value allowed.
- The User can only input 3 additional digits in the fractional parts 

However, if the User adjusts the Body text size to 18pt in Preferences, then the text box can't fit the entire length. 

![image](https://github.com/user-attachments/assets/e3f5ff41-7cfb-44f0-a79f-b03832cec2eb)
