### ISSUE TITLE
(Re-)Add sample rate toolbar

### ISSUE THREAD

**Issue by DamagedUnicorn** [audacity/audacity#7755]
### Problem to be solved

Frequently changing between sample rates, can be a cumbersome task as it must be done from Audio Setup->Audio Settings.

### Your idea

Add the possibility to have a sample rate toolbar (as was the case in earlier versions). This would make it as easy to change sampling rate as it is to change device.

**Comment by DamagedUnicorn** [comment]
I am using Audacity in development to test devices that can operate at multiple sampling rates. Therefore, I frequently change the project sampling rate to match the device.

**Comment by LWinterberg** [comment]
yeah, that's not exactly a use case we want to actively support. I recommend just using any other older version instead, those record and test just as well.
