### ISSUE TITLE
[AU4] Audacity crashes on Split

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#7758]
### Bug description

If the User splits any track in AU4, the application will crash. 

https://github.com/user-attachments/assets/58b37cba-6b7e-453c-8d68-13fb066d39a1

### Steps to reproduce

1. Launch Audacity
2. Generate a tone or import a track
3. Position the playhead in the middle of the track
4. Split the track
5. Observe Result		

### Expected behavior

Audacity shouldn't crash.

### Actual behavior

Audacity crashes. 

### Audacity Version

Audacity 4 alpha

### Operating system

Windows

### Additional context

Reproducible on the latest Master.

**Comment by dozzzzer** [comment]
Tested
