### ISSUE TITLE
[Effects] Working with presets

### ISSUE THREAD

**Issue by igorkorsukov** [audacity/audacity#7761]
### Description

Make functionality for working with presets using presets for reverb as an example.

**Comment by chinakov** [comment]
Tested:
- Default presets are the same as they are in AU3
- New presets can be created, loaded, deleted, and are saved after re-launch
- Export/Import of presets is functional, and is backwards compatible with Audacity 3

Issues noticed:
- If the User decides to save a preset with a name that already exists, the preset is not overwritten, and the User is not informed about this. In Audacity 3, the User will be shown a 'Preset already exists' dialog window that allows the User to replace the old preset.

**Comment by chinakov** [comment]
Passing this task, create a separate task for the issue noticed: https://github.com/audacity/audacity/issues/7869
