### ISSUE TITLE
Split action doesn't split the selected region into a separate clip

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7766]
1. Select a region of audio, press Ctrl + I
2. Observe: the clip has only been split in one place, at the beginning of the selection.

<img width="660" alt="image" src="https://github.com/user-attachments/assets/3e85bfc2-02a0-42f3-ae98-a8c781e54319">

**Comment by chinakov** [comment]
Tracks are now split correctly, thanks. 

![image](https://github.com/user-attachments/assets/36a0a939-09ea-4480-afdc-28111b000b1a)
