### ISSUE TITLE
Generator Time Length Values are Corrupted

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#7769]
### Bug description

If the User enters values in 'bars:beats' mode for the length of a tone for the tone generator, then later changes the mode of the length (time format), the value will become corrupted. Also, no changes are reflected in bar:beat modes. 

### Steps to reproduce

1. Launch Audacity
2. Create Mono/Stereo Track
3. Open Tone Generator
4. Switch to bar:beat or bar:beat:tick
5. Input any value
6. Observe no values being registered
7. Switch duration mode to any other than 'bar:beat:tick' or 'bar:beat'
8. Observe

### Expected behavior

The User should be able to enter values in bar:beat modes. 

### Actual behavior

The User is not be able to enter values in bar:beat modes. 

https://github.com/user-attachments/assets/9dc2c739-9594-47f7-8e02-223cda01f9af

### Audacity Version

Audacity 4 alpha

### Operating system

Windows

### Additional context

This is reproducible on the original AU4 tone generator PR: https://github.com/audacity/audacity/actions/runs/11720272206

**Comment by dozzzzer** [comment]
Tested
