### ISSUE TITLE
On hover Effect menu is not visible

### ISSUE THREAD

**Issue by dev9414** [audacity/audacity#778]
**Describe the bug**
when hovering on the effect menu, the expanded menu hides the effect menu.

**To Reproduce**
1. open audacity
2. click on any menu except "effect menu" (i.e. file, edit, etc..)
3. now move the mouse towards effect menu/ directly hover on effect menu
4. See an error

**Expected behavior**

Expanded menu supposed to expand below effect menu so that effect menu can be visible
same as other menus
![Screenshot (175)](https://user-images.githubusercontent.com/46513305/112747917-0b486800-8fd6-11eb-92dd-540b3c3ccdb6.png)

**Screenshots**

![Screenshot (174)](https://user-images.githubusercontent.com/46513305/112747908-01bf0000-8fd6-11eb-8690-a5b1e02c9d72.png)

**Additional information (please complete the following information):**
 - OS: [Windows 10]
 - Version [Audacity 3.0.0]

**Comment by JohnColket** [comment]
And this also makes it difficult to get to the remaining menu items: Analyze, Tools, Extra, Help...

See also the comments posted under "Divide plug-in menus further" Enhancement Request
(#752 opened 12 days ago by SMcCandlish) and countless other posts on the forum.

Try this: Edit > Preferences > Effects > Sort or Group: Group by Publisher  (perhaps this should be set by default?)

**Comment by petersampsonaudacity** [comment]
Looks like a minor bug to me - I think I will log this on Bugzilla (but this may not be today)

**Comment by petersampsonaudacity** [comment]
This appears to be a Wndows-only issue - I cannot reproduce this on Mac - but Mac handles its app menus separate from any app itself, handle in the Mac menu bar at the top of the screen, with only the current active app showing menus

**Comment by petersampsonaudacity** [comment]
I have logged this as:
Bug 2728 - Win: Effect menu overlays menu bar
https://bugzilla.audacityteam.org/show_bug.cgi?id=2728

**Comment by petersampsonaudacity** [comment]
The developer who looked as this bug commented
>this is Windows doing this and there's nothing we can do to prevent it.

Accordingly I have closed 2728 as NOT-A-BUG

There are a couple of workarounds
1) In Effects preferences set the Maximum effects per group to say 10
or
2) In Effects preferences set the "Sort or group" to "Group by type"
