### ISSUE TITLE
Lossless MP3 editing

### ISSUE THREAD

**Issue by 03302024** [audacity/audacity#7792]
### Problem to be solved

MP3 is a lossy format. Editing MP3 files, require saving again, which means loosing more quality.

### Your idea

Please add "lossless MP3 editing" feature.

**Comment by LWinterberg** [comment]
Editing MP3 directly is very different from editing normal audio data (that is, PCM data) which is fundamentally incompatible with how things are done now.

There may be a path toward it, recording edit steps made on the PCM representation and replaying them onto a direct MP3 edit might work, but it'd probably depend on #762 and/or a different project format than is currently used. So if it happens, it'll be wayyy down the line. I recommend using mp3DirectCut in the meantime: https://mpesch3.de/
