### ISSUE TITLE
Changing project tempo should be undoable

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7795]
### Problem to be solved

The BPM changes aren't undoable.

### Your idea

- Tempo changes should be undoable/redoable
- The name of the Undo/Redo menu entry is: "Tempo Changed"
- When tempo changes occur in sequence, say, from 120 to 122, then to 130, undo/redo should interpret these actions as one and jump from 130 to 120 in one go. If the User is at 120, clicks the up arrow 10 times, then does Undo, the tempo changes immediately from 130 to 120 too.

**Comment by grliszas14** [comment]
QA info:
* this introduces undoing tempo and time signature. Multiple tempo changes actions result in one history undo item. Same goes for time signature change.
* additionally I've disabled tempo widget while playback is playing

**Comment by dozzzzer** [comment]
Tested. The correct undo/redo item naming wasn't implemented. A separate task is created: https://github.com/audacity/audacity/issues/7935
