### ISSUE TITLE
Error when Applying Reverb Effect to Selection

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#7797]
### Bug description

If the User tries to apply the reverb effect to a selection including a clip, the reverb won't be applied, and an error message will be shown to the User. 

### Steps to reproduce

1. Launch Audacity
2. Open Project 
[pluck.aup3 (1).zip](https://github.com/user-attachments/files/17920305/pluck.aup3.1.zip)
3. Make a selection:
<img width="300" alt="image" src="https://github.com/user-attachments/assets/0897e8af-dd3f-482c-9ea0-ad2fdc4e2c2b">

4. Apply Reverb
5. Observe the result

### Expected behavior

The reverb should be applied.

### Actual behavior

The reverb is not applied, error message is thrown:

<img width="579" alt="image" src="https://github.com/user-attachments/assets/0de93da0-d426-4a3f-b91c-74f5c500a0d7">

### Audacity Version

Audacity 4 alpha

### Operating system

All

**Comment by saintmatthieu** [comment]
@chinakov you've actually uncovered a bug that also exists in AU3:
1. new project,
2. create a clip
3. one the same track, create another clip with some space
4. stretch the second clip
5. make a selection greater than the clip: 
![image](https://github.com/user-attachments/assets/28244c52-6113-4f5a-98fd-17e44ecfc43c)
6. apply some effect

In AU3, nothing happens, the error isn't reported.
In AU4, we get the error dialog you mentioned.

**Comment by saintmatthieu** [comment]
[This PR](https://github.com/audacity/audacity/pull/7827), if it passes review and QA, can be patched onto AU4.

**Comment by dozzzzer** [comment]
Tested

**Comment by santalitrack-eng** [comment]
Janga Payal Jham Jham
