### ISSUE TITLE
Implement applying an effect to the selected clips

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7801]
### Description

Implement the application of an effect to the selected clips, including the selection of non-consecutive clips.

QA: also test the ability to run a preview on a clip selected by double-clicking.

**Comment by saintmatthieu** [comment]
#7799 should probably be fixed first: how IDs of tracks and clips behave when they are replaced should be clarified first - see [this comment](https://github.com/audacity/audacity/issues/7799#issuecomment-2528137834)
