### ISSUE TITLE
An attempt to close the project (Ctrl + W) during the playback or recording crashes Audacity

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7807]
An attempt to close the project (Ctrl + W or `File > Close project`) during the playback or recording crashes Audacity. The bug isn't always reproducible, so one might need to repeat it a few times.

https://github.com/user-attachments/assets/2036c68e-4761-4fd6-9ec3-20a20b43df60

**Comment by kryksyh** [comment]
@dozzzzer https://github.com/audacity/audacity/pull/7945 only fixes crashes when the app is closed during playback active.

**Comment by dozzzzer** [comment]
Tested. Confirm that both the recording and playback crash are no longer reproducible.
