### ISSUE TITLE
Cannot apply effect onto stretched clip

### ISSUE THREAD

**Issue by saintmatthieu** [audacity/audacity#7826]
### Bug description

As described [here](https://github.com/audacity/audacity/issues/7797#issuecomment-2511762296)

### Steps to reproduce

As described [here](https://github.com/audacity/audacity/issues/7797#issuecomment-2511762296)

### Expected behavior

Clip stretching is rendered and effect is applied.

### Actual behavior

Nothing happens.

### Audacity Version

Audacity 3.7.x

### Operating system

Windows, macOS, Linux

**Comment by chinakov** [comment]
Issue has been fixed. Tried to find issues by applying effects on different selection combinations, no issues noticed as well. Thanks!
