### ISSUE TITLE
Waveform Disappears on High Zoom Levels

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#7829]
### Bug description

If the User zooms in into any clip/waveform on the timeline, the waveform will disappear. 

### Steps to reproduce

1. Launch Audacity
2. Create a Stereo or Mono Track
3. Generate some audio into the track
4. Zoom into the waveform
5. Observe result	

### Expected behavior

Waveform should always be shown

### Actual behavior

The waveform is not shown.

https://github.com/user-attachments/assets/9e30a952-f564-4733-a0f3-8d74fcc563be

### Audacity Version

Audacity 4 alpha

### Operating system

Windows

### Additional context

This is reproducible on the latest Master.

**Comment by kryksyh** [comment]
@chinakov this is an expected behavior introduced in https://github.com/audacity/audacity/issues/7811
It will stay this way until the sample view is implemented.
