### ISSUE TITLE
Crash upon undo of the Reverb application

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7839]
Please follow the exact steps shown in the video.

1. Have a stretched mono clip
2. Copy a region
3. Add an empty stereo track and paste onto it
4. Copy another selection from Track 1
5. Make a new mono track and paste onto it
6. Make a selection including the entire clip on Track 3 and apply Reverb
7. Play audio for a few seconds and then stop
8. Undo
9. Observe: a crash

https://github.com/user-attachments/assets/960128be-050e-4db0-b08c-9f18c5603563

**Comment by chinakov** [comment]
Linked to https://github.com/audacity/audacity/issues/7799

**Comment by saintmatthieu** [comment]
Not sure that's good news, but to crash I just have to
1. open a project that contains a clip,
2. select the clip
3. play,
4. stop,
5. undo

**Comment by dozzzzer** [comment]
Tested
