### ISSUE TITLE
Internal error at DBConnection.cpp line 308 when closing audacity

### ISSUE THREAD

**Issue by monochromec** [audacity/audacity#784]
**Describe the bug**
Cf. title

**To Reproduce**
1. Open audacity
2. Work on a project
3. Save project
4. Close audacity and observe error

**Expected behavior**
audacity closes without error

**Screenshots**

**Additional information (please complete the following information):**
 - OS: Stock Groovy with wxrc 3.1
 - Current master (3.0.0)
 - Pulse on Alsa
 - libsqlite3-dev is 3.33.0-1ubuntu0 (stock Groovy)

**Additional context**
Please let me know if you need additional information - more than happy to help!

**Comment by monochromec** [comment]
After which audacity locks up and has to be killed.

**Comment by petersampsonaudacity** [comment]
3.0.0 and the latest alpha test build I have for the upcoming 3.0.1 both close fine at your Step 4

**Comment by timtas** [comment]
I had this issue, too, it went away after I 
- added -Daudacity_use_sqlite=local to the cmake command line
- switched to latest git master (that was at 2020-03-28)

Maybe you could try this as well?

**Comment by monochromec** [comment]
@timtas Great - works like a charm. Thanks for the hint. @Maintainers: Perhaps this hint can be included the docs?
