### ISSUE TITLE
Dissallow the User to interact with clip in Recording

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#7843]
### Bug description

If the User starts to record a new audio clip, the User is allowed to change the position of the clip. This can generate a crash, or loss of audio clips if the recorded audio clip is moved 'onto' those clips. 

https://github.com/user-attachments/assets/b01412d4-d420-42bd-9b40-5d79cac6881b

### Steps to reproduce

1. Launch Audacity
2. Create a Mono or Stereo track
3. Start recording into the track
4. Try to move the recorded clip
5. Observe result

### Expected behavior

The User should not be allowed to change position of any recorded clip. 

### Actual behavior

The User should is allowed to change position of any recorded clip. 

### Audacity Version

Audacity 4 alpha

### Operating system

Windows

**Comment by dozzzzer** [comment]
@saintmatthieu 

- While recording is in progress, it's possible to enter a new name for the clip. Entering the edit mode for the clip's name should be disabled.

**Comment by dozzzzer** [comment]
Tested
