### ISSUE TITLE
Crash or missing codec error when exporting audio in AMR format

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7844]
### Bug description

The lack of a suitable codec for the AMR format causes Audacity to crash or prevent audio from being exported.

### Steps to reproduce

1. Grab some audio, mono or stereo
2. File > Export Audio
3. Select the format: AMR or set it to `"Custom FFmpeg Export"` and then click the "Open custom FFmpeg format options" button and select AMR in the formats column
4. Select an arbitrary sample rate and bitrate (if applicable)
5. Click Export
6. Observe

### Expected behavior

Audio exported in AMR format.

### Actual behavior

[In some cases](https://forum.audacityteam.org/t/cannot-export-audio-in-3-7/122105/12), it causes a crash. In others, it throws the missing codec error message:

<img width="579" alt="image" src="https://github.com/user-attachments/assets/b956efb8-a62d-4d1f-bd13-e003e473f6be">

### Audacity Version

Audacity 3.7.x

### Operating system

Windows, macOS, Linux

**Comment by kryksyh** [comment]
@dozzzzer I can't reproduce the issue on macOS with ffmpeg 7.1 installed from homebrew.

**Comment by kryksyh** [comment]
I can't reproduce the issue on windows 10 with ffmpeg 7.1 installed from https://github.com/BtbN/FFmpeg-Builds/releases.
