### ISSUE TITLE
Undo Deletes Track after Recording

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#7845]
### Bug description

If the User records into a track, and then undoes the recording, the entire track will be deleted. 

### Steps to reproduce

1. Launch Audacity
2. Create 2 stereo tracks
3. Record a clip into the last track
4. Record another clip into the last track
5. Undo
6. Observe result

### Expected behavior

The last clip recorded should be undone. 

### Actual behavior

The entire track is deleted. 

### Audacity Version

Audacity 4 alpha

### Operating system

Windows

**Comment by dozzzzer** [comment]
Fixed by #7880
