### ISSUE TITLE
Small Selections can't be Made

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#7848]
### Bug description

If the User tries to make quite a small selection on the timeline, the selection will be reset. There's a threshold for how large a selection can be, otherwise it gets reset.

### Steps to reproduce

1. Launch Audacity
2. Create a Track
3. Try to make a tiny selection
4. Observe the result

### Expected behavior

The User should be able to make very small selections on the timeline. 

### Actual behavior

The User is unable to make very small selections on the timeline. 

https://github.com/user-attachments/assets/16899af3-7c4e-4abd-b619-d377c36a1d51

### Audacity Version

Audacity 4 alpha

### Operating system

Windows

**Comment by grliszas14** [comment]
QA info:
* changed minimal selection width to be 1px (it was 12px previously)

**Comment by dozzzzer** [comment]
Once the selection is made, and you try to resize it, its width expands and it cannot be made as small as it was before anymore.

https://github.com/user-attachments/assets/4b806e75-a5e9-45bc-9535-470f90147155

**Comment by dozzzzer** [comment]
Tested
