### ISSUE TITLE
Missing Time Shift Tool

### ISSUE THREAD

**Issue by karolina13399** [audacity/audacity#7867]
hi, 
ive just installed Audacity and unfortunately i cannot see time shift tool anywhere in the menu. Ive tried to restore default settings, downloaded different versions of Audacity (3.7, 3.6., 3.4), and even downloaded it on another computer. Non of that helped. Do you know what could be the issue? F5 is not working also

**Comment by LWinterberg** [comment]
Since 3.1 you can move clips by dragging on the clip header (the part at the top where the name is)
