### ISSUE TITLE
Unable to parse project information

### ISSUE THREAD

**Issue by CyberRex0** [audacity/audacity#787]
**Describe the bug**
Saved the project in the new aup3 format released in version 3.0.0.
However, I am unable to load it later.

**To Reproduce**
1. Record or edit project
2. Save as aup3 project format
3. Open project after close Audacity

**Expected behavior**
Audacity says "Unable to parse project information."

**Screenshots**
![image](https://user-images.githubusercontent.com/26585194/113370520-0e10d780-939f-11eb-89fd-a0a4db255597.png)

**Additional information (please complete the following information):**
 - OS: Windows 10 Build 2004 64bit
 - Version: Audacity 3.0.0 64bit
 - Language: Japanese ( I took a screenshot with English for upload to github )

**Additional context**
None in particular.

**Comment by Phroneris** [comment]
It seems that many CJK users are faced with this problem:

unable to parse project information - Audacity Forum
https://forum.audacityteam.org/viewtopic.php?t=116677

**Comment by ericwang2006** [comment]
I also encountered the same situation, this situation may only be reproduced on Windows systems
The language of my windows system is Chinese, I guess it may be related to the system language, but I have no evidence yet.

**Comment by Phroneris** [comment]
Fixed? -> https://github.com/audacity/audacity/commit/ffebbe0
