### ISSUE TITLE
noise reduction in macro: false sample rate mismatch 

### ISSUE THREAD

**Issue by simplesalt** [audacity/audacity#788]
After creating a noise sample from a file (m4a, aac, stereo, sample rate: 22.05 khz, 32-bit float), I tried to run a macro including "noise reduction" effect.  Every time, I get the error, "The sample rate of the noise profile must match that of the sound to be processed."  The sample rate (and all other codec spec details) do match.  noise profile file attached for your convenience.  Initial source file available upon request but is copyrighted so I'm not gonna publish it for everyone here.  

I notice that windows mentions a bitrate of 196kbps in the noise sample, and the source m4a reports a bitrate of 58kbps.  I created the noise sample by opening the source and deleting the non-"silence" parts and saving with default options, including a project rate of 22050, so if the bitrate was changed, it was audacity's decision, and there's nowhere I can see to adjust it in the UI.  

The issue doesn't happen with mp3s with stereo, sample rate 24k, 32-bit float.  

File:
[1-01 noise reduction sample.zip](https://github.com/audacity/audacity/files/6250252/1-01.noise.reduction.sample.zip)

**Additional information (please complete the following information):**
 - OS: Win10
 - Version Audacity 3.0.0

**Comment by SteveDaulton** [comment]
The important thing is the sample rate of the audio tracks (shown in the panel on the left end of the track).
Check that the sample rate of the track that you create the noise profile from and the sample rate of the track that you are applying noise reduction to are the same.
If you require further help, please ask on the Audacity help forum. https://forum.audacityteam.org
If you are still convinced that this is a bug, please post full details and step by step instructions to reproduce the problem to the Audacity forum.

**Comment by simplesalt** [comment]
It is exactly the same - that's what the ticket said.  Please read tickets before closing them.

**Comment by SteveDaulton** [comment]
I did read the ticket before closing.
The alleged bug is not reproducible for me. To pursue this issue further will require further discussion to determine how to reproduce the problem. That's unlikely to happen here on GitHub as we use the forum for discussion. When / if we can find how to reproduce the issue, or at least confirm that it occurs for multiple users, the bug will be logged on the Audacity bug tracker for fixing.

**Comment by simplesalt** [comment]
here's a video of the issue.  As you can tell, even if I switch the bitrate to match the original, it still complains about the sample rate.  https://youtu.be/c-NkNl_58Iw
