### ISSUE TITLE
Clip Speed Indicator shows Incorrect Value

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#7887]
### Bug description

If the User sets the clip's speed to 150%, and then to 110%, the clip speed indicator will show an incorrect value (109%)

### Steps to reproduce

1. Launch Audacity 4
2. Generate a Clip
3. Open Pitch and Speed dialog
4. Enter 150% and commit change
5. Enter 110% and commit change
6. Observe result

### Expected behavior

The clips speed indicator should be at '110%' 

### Actual behavior

The clip speed indicator is at '109%'

### Audacity Version

Audacity 4 alpha

### Operating system

Windows, macOS, Linux

**Comment by dozzzzer** [comment]
Tested
