### ISSUE TITLE
Filter Curve EQ, black ruler text not visible, white graph in Dark theme

### ISSUE THREAD

**Issue by cryham** [audacity/audacity#7888]
### Bug description

Debian 12 with KDE.
Theme: Breeze Dark, customized. But I don't think it matters.
I switched to white and this Filter Curve EQ window stays the same.
BTW. how can I remove/delete inserted curve point?

### Steps to reproduce

Set a dark theme in KDE.
Set Dark theme in preferences.
Open Filter Curve EQ.
Close eyes or 😎

### Expected behavior

Ruler text should be white or gray not black, when Dark theme is used.
In Dark theme, I'd also expect the curve to be white line on dark background,
not this bright white background, independed of theme used.

### Actual behavior

Black ruler number texts, while window background is nearly black too.

### Audacity Version

Audacity 3.7.x

### Operating system

Linux

### Additional context

![curve eq](https://github.com/user-attachments/assets/f10b5ef0-7b7b-4d0a-a803-c5d485d4fa4a)
![prefs](https://github.com/user-attachments/assets/b344c548-4f89-44c0-9e61-fafe3fd4db5e)

**Comment by LWinterberg** [comment]
This will be fixed in Audacity 4.
