### ISSUE TITLE
noise reduction in macro: false sample rate mismatch 

### ISSUE THREAD

**Issue by simplesalt** [audacity/audacity#789]
After creating a noise sample from a file (m4a, aac, stereo, sample rate: 22.05 khz, 32-bit float), I tried to run a macro including "noise reduction" effect.  Every time, I get the error, "The sample rate of the noise profile must match that of the sound to be processed."  The sample rate (and all other codec spec details) do match.  noise profile file attached for your convenience.  Initial source file available upon request but is copyrighted so I'm not gonna publish it for everyone here.  

I notice that windows mentions a bitrate of 196kbps in the noise sample, and the source m4a reports a bitrate of 58kbps.  I created the noise sample by opening the source and deleting the non-"silence" parts and saving with default options, including a project rate of 22050, so if the bitrate was changed, it was audacity's decision, and there's nowhere I can see to adjust it in the UI.  

The issue doesn't happen with mp3s with stereo, sample rate 24k, 32-bit float.  

File:
[1-01 noise reduction sample.zip](https://github.com/audacity/audacity/files/6250252/1-01.noise.reduction.sample.zip)

**Additional information (please complete the following information):**
 - OS: Win10
 - Version Audacity 3.0.0
 
 Re-opened from bug #778 that @SteveDaulton closed in error.
 
 Response on that bug included for convenience: 
 
> [Sample rate] is exactly the same - that's what the ticket said.  Please read tickets before closing them.  
> 
> ![image](https://user-images.githubusercontent.com/49482082/113478496-b762d680-944e-11eb-930f-37d76bef88d3.png)

**Comment by simplesalt** [comment]
The issue seems to affect mp3s as well.  I was able to get around the problem by encoding with different bitrates with ffmpeg first.  I had the same issue with another set I'm trying to process, you can see here in a video capture of the problem: https://youtu.be/c-NkNl_58Iw.

**Comment by petersampsonaudacity** [comment]
I cannot reproduce this on my W10 PC with 3.0.0, 3.0.2 or the latest alpha test build I have for 3.0.3

1) launch Audacity (default project rate 44100 Hz
2) Import audio file
3) change track rate to 22500
4) select the noise profile range
5) Noise Reduction => Get Noise Profile
6) Run my Macro on Project - all is does is Select All and then Noise Reduction
7) Observe:  success

Of course if I reverse steps 3 and 4 then I do get the error message as my noise sample is at 44100 Hz and my audio to be processed is at 22500 Hz - so of course there is a rate mismatch and the error message is tightly displayed.

@simplesalt  Can you please retest following my Steps to Reproduce?

**Comment by petersampsonaudacity** [comment]
Due to lack of response from OP and my testing as in previous comment I am going to close this issue
