### ISSUE TITLE
Unwarranted Effect Stack Change While Undo

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#7893]
### Bug description

If the User creates a track, and then adds an effect to it, does some additional actions, and then undoes the previous action, a new instance of an effect will be added to the stack.

### Steps to reproduce

1. Create a new Project
2. Add track, Generate a Clip
3. Add 'Reverb' Real Time effect to the track
4. Copy-paste the generated Clip
5. Undo
6. Observe Result

### Expected behavior

The FX stack should not change when an action of clip copy-past has been undone.

### Actual behavior

The FX stack changes when an action of clip copy-past has been undone.

### Audacity Version

Audacity 4 alpha

### Operating system

Windows

**Comment by dozzzzer** [comment]
Tested
