### ISSUE TITLE
Audacity Crash when Effect applied with No Project Open 

### ISSUE THREAD

**Issue by chinakov** [audacity/audacity#7899]
### Bug description

If the User has no project open, the User can 'apply' and effect via the navbar menu (Effect -> Built-in). If the User decides to apply any effect, Audacity 4 will crash. 

https://github.com/user-attachments/assets/ec6ae99f-f33c-41eb-ae6f-b49ef9108f19

### Steps to reproduce

1. Launch Audacity
2. Go to 'Effect -> Built-in'
3. Press any effect
4. Observe crash

### Expected behavior

Audacity should not allow the User to apply an effect if no project has been opened. 

### Actual behavior

Audacity allows the User to apply and effect if no project has been opened. 

### Audacity Version

Audacity 4 alpha

### Operating system

Windows

**Comment by dozzzzer** [comment]
Tested
