### ISSUE TITLE
Internal PortAudio error on Windows 10

### ISSUE THREAD

**Issue by ryrun** [audacity/audacity#79]
I've two audio devices working fine on windows 10. Sound is working on both in typical multimedia applications (media player, winamp, chrome browser). I use renoise on this system with DirectSound. No issues there, too. Audacity cant find any sound hardware. Try to start it with admin rights, too. But does not help. Tried lates nightly build and current stable build.

```
==============================
Default recording device number: -1
Default playback device number: -1
No devices found
```

Log show some missing dll files...

```
19:54:52: Audacity 2.1.1
19:54:52: Trying to load FFmpeg libraries...
19:54:52: Trying to load FFmpeg libraries from system paths. File name is 'avformat-55.dll'.
19:54:52: Looking up PATH environment variable...
19:54:52: PATH = ...
19:54:52: Checking that '' is in PATH...
19:54:52: FFmpeg directory is in PATH.
19:54:52: Checking for monolithic avformat from 'avformat-55.dll'.
19:54:52: Fehler: Laden der DLL 'avformat-55.dll' gescheitert (Fehler 126: das angegebene Modul wurde nicht gefunden.)
19:54:52: Loading avutil from ''.
19:54:52: Fehler: Laden der DLL '.dll' gescheitert (Fehler 126: das angegebene Modul wurde nicht gefunden.)
19:54:52: Loading avcodec from ''.
19:54:52: Fehler: Laden der DLL '.dll' gescheitert (Fehler 126: das angegebene Modul wurde nicht gefunden.)
19:54:52: Loading avformat from 'avformat-55.dll'.
19:54:52: Fehler: Laden der DLL 'avformat-55.dll' gescheitert (Fehler 126: das angegebene Modul wurde nicht gefunden.)
19:54:52: Fehler: Failed to load FFmpeg libraries.
19:54:52: Fehler: Es konnten keine passenden FFmpeg-Bibliotheken gefunden werden.
```

**Comment by lllucius** [comment]
Hi Andreas,

Which host interface are you attempting to use, MME, Directsound or WASAPI?  Have you tried the others?  Would you be willing to help us gather some info on this?  If so, can you give me a day or two to modify one of the portaudio test programs to display debugging information?

Thanks much,

Leland

**Comment by ryrun** [comment]
Not sure, what interface audacity try to use on the first start. I cant choose one of them in the config. The select box is empty. Sure i can help here. No problem.

**Comment by ryrun** [comment]
@lllucius Any news about this?

**Comment by lllucius** [comment]
Sorry Andrew…my second job has been taking up much of my spare time over the last few weeks.  I haven’t done much with Audacity because of that.  I “hope” to be freed up soon.

**Comment by david-alan** [comment]
Any updates on this issue?

**Comment by windinthew** [comment]
See http://audacityteam.org/download/windows#sysreq  . At a minimum we will be updating to latest PortAudio to pull in these two commits which may help:
https://www.assembla.com/spaces/portaudio/subversion/commits/1962
https://www.assembla.com/spaces/portaudio/subversion/commits/1963 .

Most people can get at least some version of Audacity working on Windows 10 by following http://wiki.audacityteam.org/wiki/Windows_10_OS#solutions .

**Comment by JamesCrook** [comment]
We have updated PortAudio.  If the issue persists, please make a new issue report.
