### ISSUE TITLE
Interface shows some elements in OS' display language instead of language set in Audacity preferences

### ISSUE THREAD

**Issue by Castigavi** [audacity/audacity#7906]
### Bug description

I have observed that when I change the language in Audacity settings to a different language than my OS' default one (so eg. from Polish to English), then some of the UI elements are still shown in OS' default language. This keeps happening even after removing Audacity, deleting the remaining files and installing everything all over again.

This bug was first reported in 2021 but was eventually closed as fixed. Unfortunately, it seems it is still happening in the newer Audacity versions. The original bug report was #801. I have first noticed it in Audacity 2.4.1 and it is still present in 3.7.1.

![obraz](https://github.com/user-attachments/assets/63681f60-6d76-4469-990a-d2bf4deecfe2)

### Steps to reproduce

1. Go to Edit/Preferences/Interface and change Language to anything different than your OS language (eg. if your OS is in Polish, change it to English). Click OK.
2. Click on Tools tab and notice how some of the elements in the menu are still in your OS' language.

### Expected behavior

All elements of UI should be shown in the language selected in the Preferences/Interface menu.

### Actual behavior

Some UI elements do not respect the selected language setting in the Preferences/Interface menu and instead show in a different language (OS' language).

### Audacity Version

Audacity 3.7.x

### Operating system

Windows

### Additional context

Operating System: Windows 11 Home 64-bit (10.0, Build 22631)
Language: Polish (Regional Setting: Polish)
Processor: AMD Ryzen 5 5600H with Radeon Graphics
Memory: 16384MB RAM
Card name: NVIDIA GeForce RTX 3060 Laptop GPU
Lenovo Legion 15ACH6H

**Comment by dozzzzer** [comment]
@Castigavi 
Here's my locale settings, as you can see the display language is set to Polish:

![image](https://github.com/user-attachments/assets/14ec3dbd-d6e6-47f8-8e9a-31054256e555)

Audacity's interface language is set to English, and is fully localized according to the selected language, including the Tools menu you're referring to:

![image](https://github.com/user-attachments/assets/9071da81-2e01-47ca-b41f-924dad2cc2ad)

This is Win 10, but my other Win 11 PC doesn't have such an issue either.

**Comment by Castigavi** [comment]
My OS is Polish as well but in my case the interface is half English half Polish in Audacity 
![obraz](https://github.com/user-attachments/assets/41160a26-7cd3-437d-9e27-aa7ec8cb0ff8)

![obraz](https://github.com/user-attachments/assets/d7a366eb-dd49-464d-a4ae-229cb7c68633)
![obraz](https://github.com/user-attachments/assets/9def166c-1068-4d11-a43e-0ed7207dc5cd)
![obraz](https://github.com/user-attachments/assets/734f003c-9c71-4a2b-83d7-1c55f65e8bfb)
![obraz](https://github.com/user-attachments/assets/b0177dbe-1da4-4be5-98ec-4f4a88ebae11)

I am not sure why this keeps happening. I have uninstalled Audacity, removed the leftover files, installed it again with resetting all settings. But it is still happening. I have went through the registries but there's nothing left from the installation. No idea what else to do at this point.

**Comment by LWinterberg** [comment]
I believe this is an old bug, from memory I named it something "nyquist
locale". Can't really check at the moment due to extremely spotty Internet

**Comment by dozzzzer** [comment]
That's right. Closing this ticket in favor of the existing one: https://github.com/audacity/audacity/issues/2764
