### ISSUE TITLE
Crash when pressing Ctrl (Cmd) + Z after pausing playback

### ISSUE THREAD

**Issue by dozzzzer** [audacity/audacity#7936]
### Steps to reproduce

1. Create a new project
2. Create a new mono track
3. Generate a tone or a chirp
4. Play it
5. Pause
6. Press Ctrl (Cmd) + Z

### Expected behavior

No crash

### Actual behavior

A crash

### Audacity Version

Audacity 4 alpha

### Operating system

Windows, macOS, Linux

**Comment by grliszas14** [comment]
I believe this is no more the case since this is merged: https://github.com/audacity/audacity/pull/7889 
Please re-test with the lastest master

**Comment by dozzzzer** [comment]
It doesn't crash anymore indeed, thx @grliszas14
