### ISSUE TITLE
Attract More Free Developers

### ISSUE THREAD

**Issue by CaBachhav** [audacity/audacity#7964]
### Problem to be solved

slow speed of development

### Your idea

Attract More Free Developers , programmers , coders , debuggers as audacity development is very very slow. Don't let a person run away from code contribution even if he knows python or very liitle programming language.But since he knows basic concepts of coding , you can motivate him to utilize AI aid for coding and modify them according to need

**Comment by LWinterberg** [comment]
Feel free to contribute
