### ISSUE TITLE
"Vocal Reduction and Isolation" effect disappeared

### ISSUE THREAD

**Issue by dikonov** [audacity/audacity#7965]
### Bug description

I updated my system and the update installed Audacity 3.7.1 instead of an older version. The 3.7.1 turned out to be lacking the "Vocal Reduction and Isolation" effect, which is CRUCIAL for what I do with Audacity. I cannot use 3.7.1 without it. 

Please return the Vocal Reduction and Isolation effect.

### Steps to reproduce

1. Update Audacity to 3.7.1.
2. Try using "Vocal Reduction and Isolation"
3. WTF???!!

### Expected behavior

Vocal Reduction and Isolation should be present in the Effects menu

### Actual behavior

The menu has no such plugin. Audacity 3.7.1 is unusable.

### Audacity Version

Audacity 3.7.x

### Operating system

Linux

**Comment by LWinterberg** [comment]
The plugin has been retired in favor of an openvino one.  You can download the old one fromhttps://plugins.audacityteam.org/nyquist-plugins/effect-plugins/filters-and-eq

**Comment by dikonov** [comment]
1) This and OpenVINO have nothing in common and do not substitute each other. 
2) OpenVINO  -  "Just does not work" TM    Have you seen its list of requirements?

**Comment by dikonov** [comment]
Thankfully I found the needed plugin (before I saw the link above), but I had to jump through hoops to find it and reinstall. 
It really should be bundled as a "classic" filter.
