### ISSUE TITLE
[Low Priority Feature request] Follow system theme

### ISSUE THREAD

**Issue by julianfairfax** [audacity/audacity#797]
**Is your feature request related to a problem? Please describe.**
Audacity has both a light theme and a dark theme but doesn't follow the system theme.

**Describe the solution you'd like**
Audacity should follow the system theme and change to the light theme or the dark theme automatically based on what the system theme is. I would really like if this feature was added, as it would improve the integration with the system, and it would be a welcome change for me. Thanks for all the work you've put into this wonderful app!

**Comment by julianfairfax** [comment]
I'm just going to close this due to it being such a small issue and the toolkit you're using most likely not supporting it anyway.

**Comment by julianfairfax** [comment]
Reopening this since I know it's possible. See https://docs.wxwidgets.org/trunk/classwx_system_appearance.html for reference

**Comment by julianfairfax** [comment]
Sorry for closing and opening this again, would you still be up for adding this functionality? Thanks for your wonderful app!

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
This feature is greatly required, not least because when compared to almost all other software that is for GNU/Linux, [Audacity](http://github.com/audacity/audacity) is incredibly unpleasant visually.

**Comment by SteveDaulton** [comment]
I find it's appearance OK, but functionality is more important to me.

![Audacity304](https://user-images.githubusercontent.com/11681097/132144057-4c5c8c19-6c01-4c97-9801-51fc2b6dfa3a.png)

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
> http://github.com/audacity/audacity/issues/797#issuecomment-913245218

What was the reason for the submission of http://user-images.githubusercontent.com/11681097/132144057-4c5c8c19-6c01-4c97-9801-51fc2b6dfa3a.png? Surely all that that does is contradict your previous statement by demonstrating how awful the appearance of [Audacity](http://github.com/audacity/audacity) is.

**Comment by SteveDaulton** [comment]
Maybe you need to read the words as well as looking at the picture.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
> http://github.com/audacity/audacity/issues/797#issuecomment-913255591

I have read them. If its functionality is adequate for you, and your only concern is whether its functionality shall remain as such, why bother to mention your opinion of whether its appearance is important?

**Comment by LWinterberg** [comment]
Closing in favor of 
* #2370
