### ISSUE TITLE
Recording slider lock

### ISSUE THREAD

**Issue by DinandDotNet** [audacity/audacity#7970]
### Problem to be solved

Often, recording level is changed by accident of mouse or touch.

### Your idea

Can the recording slider have a lock on/off. (On/off (or Enable/Disable) in the "right mouse click" popup in the screen of [recording options meter]. 
So it is still visible (to check for green or red) and not afterwards discover the recording is too hard or soft.  
It would be a nice feature. Thank you. 

### Additional context

So much thanks for this beautiful product. Lots of joy of each version you launch.
If you ever need help in .net development, reach out to me 
(15+ years development C# & .net, senior level, and architecture, 8+ years Blazor specialist)

**Comment by LWinterberg** [comment]
This will be fixed in Audacity 4: There, the slider needs to be explicitly opened (otherwise, only a meter will show next to the track)
