### ISSUE TITLE
Audacity doesn’t remember window position

### ISSUE THREAD

**Issue by rillig** [audacity/audacity#80]
Audacity seems to remember something like the last window position, but it often fails to restore the exact window position.

Windows version: 8.1
Audacity version: 2.1.1 (or any 2.1.2-alpha version)
1. Open Audacity 
2. Press Ctrl+W
3. Drag the window a little bit to the right
4. Press Ctrl+W. The window is now thinner than before
5. Drag the window to the bottom of the desktop so that only the title bar is visible
6. Press Ctrl+W. The window’s height is now so small that the client area is not visible anymore
7. In a two-screen setup, maximize Audacity to one of the screens
8. Press Ctrl+W
9. Maximize Audacity on the other screen
10. Press Ctrl+W

**Comment by JamesCrook** [comment]
Thank You!
This has been fixed now, but we never got round to adding a comment here or closing this bug.

**Comment by rillig** [comment]
Ah, beautiful. It works now exactly as expected. Even in half-screen mode and in full-screen mode. Thank you for fixing it and informing me.
