### ISSUE TITLE
limiter blocks on long recordings

### ISSUE THREAD

**Issue by djbenbe** [audacity/audacity#800]
- OS: Windows 10
 - Version  3.0.0

I have 1 hour recordings.
when I use the limiter it blocks.
it works for a short exposure.

**Comment by petersampsonaudacity** [comment]
This is bug that has already been fixed for the soon to be upcoming 3.0.2 (the Release Candidate RC)1 was made available for testing today.

See:  P1 Bug 2708 - Nyquist effects fail silently with One hour plus stereo 
https://bugzilla.audacityteam.org/show_bug.cgi?id=2708

**Comment by djbenbe** [comment]
thank you. i would like to test this version.

**Comment by JohnColket** [comment]
The latest RC is here: https://www.fosshub.com/Audacity-devel.html
