### ISSUE TITLE
System language display and setting language conflict

### ISSUE THREAD

**Issue by Rqcker** [audacity/audacity#801]
**Describe the bug**
First of all, after I compiled the software, I discovered that Audacity will display with the system language. I set the software language to **English** in the settings. Most of them can be displayed perfectly, but there are still some functions that cannot be fully displayed in the language I set. They are still displayed as system language.

**To Reproduce**
1. Go to 'Audacity'
2. Click on 'Generate'
3. Scroll down to 'Risset'
4. It can be found that the following three options are all displayed as system languages
  
Similarly, when I open other toolbars, I still find a mixed display of the system language and the set language. Toolbars with problems: **"Generate", "Effect", "Analyze", "Tools"**.

**Expected behavior**
The improvement goal is to achieve unity of language functions. All functions should be displayed in the language set by the user. (It shouldn't be a situation where multiple languages are mixed like this.)

**Screenshots**
The following screenshots take **English** and **Chinese** as examples. After setting the display language to English:
**1. Generate:**
![Generate](https://user-images.githubusercontent.com/20661419/114219409-8872c600-9962-11eb-9658-0bfd6dc92c06.png)
**2. Effect:**
![Effect](https://user-images.githubusercontent.com/20661419/114219667-dd164100-9962-11eb-9f26-07544daf29ba.png)
**3. Analyze:**
![Analyze](https://user-images.githubusercontent.com/20661419/114219839-1949a180-9963-11eb-8a9b-1af7cd9d9cd1.png)
**4. Tools:**
![Tools](https://user-images.githubusercontent.com/20661419/114219901-33837f80-9963-11eb-8780-81b4e850699a.png)

**Additional information (please complete the following information):**
 - OS: x64 Windows 10
 - Version: Audacity 3.0.1-alpha-Apr 9 2021
 - Sound: Device Realtek High Definition Audio

**Additional context**
Only the display interface is affected, and the specific functions implemented by the software are not affected.

**Comment by JohnColket** [comment]
I have seen this issue when switching to European languages then back to English.

**Comment by petersampsonaudacity** [comment]
Is Windows English or Chinese locale.  I.e. is default Audacity on your machine Chinese and you switch to English?

BTW there is a later version of Audacity out now 3.0.2 - and we never released a 3.0.1 we went straight from 3.0.0 to 3.0.2 so I am totally surprised that you say you were on 3.0.1.

Can you please
a) Upgrade to 3.0.2 with the EXE installation
b) accept the Reset options that occur during the upgrade an initial launch.
c) then post back and tell us if this still happens

**Comment by Rqcker** [comment]
> Is Windows English or Chinese locale. I.e. is default Audacity on your machine Chinese and you switch to English?
> 
> BTW there is a later version of Audacity out now 3.0.2 - and we never released a 3.0.1 we went straight from 3.0.0 to 3.0.2 so I am totally surprised that you say you were on 3.0.1.
> 
> Can you please
> a) Upgrade to 3.0.2 with the EXE installation
> b) accept the Reset options that occur during the upgrade an initial launch.
> c) then post back and tell us if this still happens

Hello Peter, 
  The defaults language of my win10 system is Chinese. I have switched the software to English. I am pretty sure that the version I am using is 3.0.1. I am a student participating in GSoC2021, this exe is after I compile the code. The screenshot is a screenshot of the software. I still encounter this problem in the latest version.

![image](https://user-images.githubusercontent.com/20661419/118501793-fdcf7480-b720-11eb-91e6-cffb79531ad9.png)

Thanks,
Junhao

**Comment by petersampsonaudacity** [comment]
You have an alpha test version of 3.0.1 - it had some bad bugs that's why we skipped it - You really need to install 3.0.2
https://www.audacityteam.org/download/windows/

**Comment by Rqcker** [comment]
Hello, the problem was successfully solved in version 3.0.2.
Thanks all, Cheers!

**Comment by petersampsonaudacity** [comment]
Thanks for the feedback @Rqcker  - glad it got sorted, so I'll close this.

Many thanks,
Peter.
