### ISSUE TITLE
Text in step 5 win/build.txt doesnt explain how to get the required vc_lib folder

### ISSUE THREAD

**Issue by jeroenbaas** [audacity/audacity#802]
**Describe the bug**
text in step 5 win/build.txt doesnt explain how to get the required vc_lib folder (only generates the dlls)

**To Reproduce**
N/A

**Expected behavior**
Should mention these steps to produce vc_lib:
Open Developer Command Prompt for VS 2019 (Visual Studio Command Prompt), then Build wxWidgets
cd %WXWIN%\build\msw
nmake /f makefile.vc BUILD=release
(found on https://medium.com/@khasburrahman/build-audacity-with-asio-using-visual-studio-2019-1863b5fe6d3d4)

**Screenshots**
N/A

**Additional information (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by jeroenbaas** [comment]
see https://github.com/audacity/audacity/pull/803

**Comment by JohnColket** [comment]
This folder is created in a prior step by the build of the solution file.  The nmake command is not needed here.
