### ISSUE TITLE
audacity shows LADSPA plugins when compiled with -Daudacity_use_ladspa:BOOL=false

### ISSUE THREAD

**Issue by yurivict** [audacity/audacity#809]
**Describe the bug**
See subject.

**Additional information (please complete the following information):**
 - OS: FreeBSD 12.2
 - Version Audacity 3.0.0

**Comment by LWinterberg** [comment]
Hello! We just [switched development to Audacity 4](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444) which uses a different build system. This bug should no longer be applicable.
