### ISSUE TITLE
When Audacity crashes, the dbgrpt workflow is not user-friendly

### ISSUE THREAD

**Issue by rillig** [audacity/audacity#82]
When Audacity crashes, it generates a debugging report and saves it into a zip file. The location of this zip file is shown in a dialog, ready to be copied to the clipboard.

It would be a great help if this dialog offered a “Focus in file manager“ as the default button.

When I had first encountered this dialog, I was so excited about the crash that I didn’t fully understand the dialog, clicked it away, and then I had no idea where the report had been saved. Had the button been the suggested Focus, I would have had an Explorer window open where I could take the file and send it by mail.

Ideally and additionally, there should be a “Send by mail” button that invokes the standard mail application using the preferred recipient address. Unless this is done, the typical user doesn’t have any clue where to send the report.

The “Focus/Open in file manager” should also be added to the big error reporting dialog where I can select which files to include in the generated zip file.

**Comment by windinthew** [comment]
Thanks for the useful suggestions. As far as I understand it we are using the wxWidgets Debug Report feature more or less "as is" right now. 

Our feedback address http://audacityteam.org/contact/#feedback does not require subscription or logging in to send us comments.

**Comment by LWinterberg** [comment]
We added an option to directly send crash reporting data with 3.0.3, so this has been implemented (abeit in a different way)
