### ISSUE TITLE
JACK detection broken on Linux in release 3.0.2

### ISSUE THREAD

**Issue by alienbob** [audacity/audacity#820]
Commit https://github.com/audacity/audacity/commit/5b4cd040ebdddc943925990819ff5de6fa52d729#diff-033fedc31a5937995b8e216fecda6fe78dff2b94b39ff68d68322a9bfb2875d3 was meant to fix building on Windows but the change of 'find_package( Jack )' to 'find_package( jack )' breaks the build on Linux.
While configuring portaudio, JACK will no longer be detected and the resulting audacity binary does not have support for JACK audio,

When I revert that change in ./cmake-proxies/portaudio-v19/CMakeLists.txt (changing 'jack' to 'Jack') the resulting binary does again offer "Jack Audio Connection Kit" next to "ALSA" in the Audio Host dropdown.

**Comment by JamesCrook** [comment]
Triaged to Bugzilla as a P2 bug, and DEVEL-FIX-MADE there.
https://bugzilla.audacityteam.org/show_bug.cgi?id=2758

Closing here, as we track it there rather than in multiple places.  Cross reference added.
