### ISSUE TITLE
Problems compiling audacity with wxwidgets 3.0.2

### ISSUE THREAD

**Issue by shevegen** [audacity/audacity#83]
I have some problems compiling audacity with wxwidgets-3.0.2

My GCC version is:

    g++ (GCC) 5.2.0

Configure statement was:

    ./configure --prefix=/Programs/Audacity/2.1.1 --with-libvorbis --with-libvorbis --with-ffmpeg  --with-lame --with-lame --with-libflac --with-libsndfile

Error is:

 ^
In file included from AudacityApp.cpp:26:0:
/usr/include/wx-3.0/wx/event.h:3683:22: note: declared here
         virtual bool TryValidator(wxEvent& WXUNUSED(event)), return false; )
                      ^
/usr/include/wx-3.0/wx/defs.h:615:43: note: in definition of macro 'wxDEPRECATED'
 #define wxDEPRECATED(x) wxDEPRECATED_DECL x
                                           ^
/usr/include/wx-3.0/wx/event.h:3682:5: note: in expansion of macro 'wxDEPRECATED_BUT_USED_INTERNALLY_INLINE'
     wxDEPRECATED_BUT_USED_INTERNALLY_INLINE(
     ^
AudacityApp.cpp:2159:1: warning: 'virtual bool wxEvtHandler::TryParent(wxEvent&)' is deprecated [-Wdeprecated-declarations]
 }
 ^
In file included from AudacityApp.cpp:26:0:
/usr/include/wx-3.0/wx/event.h:3686:22: note: declared here
         virtual bool TryParent(wxEvent& event), return DoTryApp(event); )
                      ^
/usr/include/wx-3.0/wx/defs.h:615:43: note: in definition of macro 'wxDEPRECATED'
 #define wxDEPRECATED(x) wxDEPRECATED_DECL x
                                           ^
/usr/include/wx-3.0/wx/event.h:3685:5: note: in expansion of macro 'wxDEPRECATED_BUT_USED_INTERNALLY_INLINE'
     wxDEPRECATED_BUT_USED_INTERNALLY_INLINE(
     ^
AudacityApp.cpp:2159:1: warning: 'virtual void wxWindowBase::SetVirtualSizeHints(int, int, int, int)' is deprecated [-Wdeprecated-declarations]
 }
 ^
In file included from AudacityApp.cpp:26:0:
/usr/include/wx-3.0/wx/window.h:459:32: note: declared here
     wxDEPRECATED( virtual void SetVirtualSizeHints( int minW, int minH,
                                ^
/usr/include/wx-3.0/wx/defs.h:615:43: note: in definition of macro 'wxDEPRECATED'
 #define wxDEPRECATED(x) wxDEPRECATED_DECL x
                                           ^
AudacityApp.cpp:2159:1: warning: 'virtual void wxWindowBase::MakeModal(bool)' is deprecated [-Wdeprecated-declarations]
 }
 ^
In file included from AudacityApp.cpp:26:0:
/usr/include/wx-3.0/wx/window.h:688:32: note: declared here
     wxDEPRECATED( virtual void MakeModal(bool modal = true) );
                                ^
/usr/include/wx-3.0/wx/defs.h:615:43: note: in definition of macro 'wxDEPRECATED'
 #define wxDEPRECATED(x) wxDEPRECATED_DECL x
                                           ^
AudacityApp.cpp:2159:1: warning: 'virtual void wxWindowBase::SetInitialBestSize(const wxSize&)' is deprecated: use SetInitialSize() instead. [-Wdeprecated-declarations]
 }
 ^
In file included from /usr/include/wx-3.0/wx/nonownedwnd.h:14:0,
                 from /usr/include/wx-3.0/wx/toplevel.h:20,
                 from /usr/include/wx-3.0/wx/frame.h:18,
                 from /usr/include/wx-3.0/wx/docview.h:21,
                 from AudacityApp.cpp:29:
/usr/include/wx-3.0/wx/window.h:1872:13: note: declared here
 inline void wxWindowBase::SetInitialBestSize(const wxSize& size)
             ^
AudacityApp.cpp:2159:1: warning: 'virtual bool wxEvtHandler::TryValidator(wxEvent&)' is deprecated [-Wdeprecated-declarations]
 }
 ^
In file included from AudacityApp.cpp:26:0:
/usr/include/wx-3.0/wx/event.h:3683:22: note: declared here
         virtual bool TryValidator(wxEvent& WXUNUSED(event)), return false; )
                      ^
/usr/include/wx-3.0/wx/defs.h:615:43: note: in definition of macro 'wxDEPRECATED'
 #define wxDEPRECATED(x) wxDEPRECATED_DECL x
                                           ^
/usr/include/wx-3.0/wx/event.h:3682:5: note: in expansion of macro 'wxDEPRECATED_BUT_USED_INTERNALLY_INLINE'
     wxDEPRECATED_BUT_USED_INTERNALLY_INLINE(
     ^
AudacityApp.cpp:2159:1: warning: 'virtual bool wxEvtHandler::TryParent(wxEvent&)' is deprecated [-Wdeprecated-declarations]
 }
 ^
In file included from AudacityApp.cpp:26:0:
/usr/include/wx-3.0/wx/event.h:3686:22: note: declared here
         virtual bool TryParent(wxEvent& event), return DoTryApp(event); )
                      ^
/usr/include/wx-3.0/wx/defs.h:615:43: note: in definition of macro 'wxDEPRECATED'
 #define wxDEPRECATED(x) wxDEPRECATED_DECL x
                                           ^
/usr/include/wx-3.0/wx/event.h:3685:5: note: in expansion of macro 'wxDEPRECATED_BUT_USED_INTERNALLY_INLINE'
     wxDEPRECATED_BUT_USED_INTERNALLY_INLINE(
     ^
AudacityApp.cpp:2159:1: warning: 'virtual void wxWindowBase::SetVirtualSizeHints(int, int, int, int)' is deprecated [-Wdeprecated-declarations]
 }
 ^
In file included from AudacityApp.cpp:26:0:
/usr/include/wx-3.0/wx/window.h:459:32: note: declared here
     wxDEPRECATED( virtual void SetVirtualSizeHints( int minW, int minH,
                                ^
/usr/include/wx-3.0/wx/defs.h:615:43: note: in definition of macro 'wxDEPRECATED'
 #define wxDEPRECATED(x) wxDEPRECATED_DECL x
                                           ^
AudacityApp.cpp:2159:1: warning: 'virtual void wxWindowBase::MakeModal(bool)' is deprecated [-Wdeprecated-declarations]
 }
 ^
In file included from AudacityApp.cpp:26:0:
/usr/include/wx-3.0/wx/window.h:688:32: note: declared here
     wxDEPRECATED( virtual void MakeModal(bool modal = true) );
                                ^
/usr/include/wx-3.0/wx/defs.h:615:43: note: in definition of macro 'wxDEPRECATED'
 #define wxDEPRECATED(x) wxDEPRECATED_DECL x
                                           ^
AudacityApp.cpp:2159:1: warning: 'virtual void wxWindowBase::SetInitialBestSize(const wxSize&)' is deprecated: use SetInitialSize() instead. [-Wdeprecated-declarations]
 }
 ^
In file included from /usr/include/wx-3.0/wx/nonownedwnd.h:14:0,
                 from /usr/include/wx-3.0/wx/toplevel.h:20,
                 from /usr/include/wx-3.0/wx/frame.h:18,
                 from /usr/include/wx-3.0/wx/docview.h:21,
                 from AudacityApp.cpp:29:
/usr/include/wx-3.0/wx/window.h:1872:13: note: declared here
 inline void wxWindowBase::SetInitialBestSize(const wxSize& size)
             ^
AudacityApp.cpp:2159:1: warning: 'virtual bool wxEvtHandler::TryValidator(wxEvent&)' is deprecated [-Wdeprecated-declarations]
 }
 ^
In file included from AudacityApp.cpp:26:0:
/usr/include/wx-3.0/wx/event.h:3683:22: note: declared here
         virtual bool TryValidator(wxEvent& WXUNUSED(event)), return false; )
                      ^
/usr/include/wx-3.0/wx/defs.h:615:43: note: in definition of macro 'wxDEPRECATED'
 #define wxDEPRECATED(x) wxDEPRECATED_DECL x
                                           ^
/usr/include/wx-3.0/wx/event.h:3682:5: note: in expansion of macro 'wxDEPRECATED_BUT_USED_INTERNALLY_INLINE'
     wxDEPRECATED_BUT_USED_INTERNALLY_INLINE(
     ^
AudacityApp.cpp:2159:1: warning: 'virtual bool wxEvtHandler::TryParent(wxEvent&)' is deprecated [-Wdeprecated-declarations]
 }
 ^
In file included from AudacityApp.cpp:26:0:
/usr/include/wx-3.0/wx/event.h:3686:22: note: declared here
         virtual bool TryParent(wxEvent& event), return DoTryApp(event); )
                      ^
/usr/include/wx-3.0/wx/defs.h:615:43: note: in definition of macro 'wxDEPRECATED'
 #define wxDEPRECATED(x) wxDEPRECATED_DECL x
                                           ^
/usr/include/wx-3.0/wx/event.h:3685:5: note: in expansion of macro 'wxDEPRECATED_BUT_USED_INTERNALLY_INLINE'
     wxDEPRECATED_BUT_USED_INTERNALLY_INLINE(
     ^
AudacityApp.cpp:2159:1: warning: 'virtual void wxWindowBase::SetVirtualSizeHints(int, int, int, int)' is deprecated [-Wdeprecated-declarations]
 }
 ^
In file included from AudacityApp.cpp:26:0:
/usr/include/wx-3.0/wx/window.h:459:32: note: declared here
     wxDEPRECATED( virtual void SetVirtualSizeHints( int minW, int minH,
                                ^
/usr/include/wx-3.0/wx/defs.h:615:43: note: in definition of macro 'wxDEPRECATED'
 #define wxDEPRECATED(x) wxDEPRECATED_DECL x
                                           ^
AudacityApp.cpp:2159:1: warning: 'virtual void wxWindowBase::MakeModal(bool)' is deprecated [-Wdeprecated-declarations]
 }
 ^
In file included from AudacityApp.cpp:26:0:
/usr/include/wx-3.0/wx/window.h:688:32: note: declared here
     wxDEPRECATED( virtual void MakeModal(bool modal = true) );
                                ^
/usr/include/wx-3.0/wx/defs.h:615:43: note: in definition of macro 'wxDEPRECATED'
 #define wxDEPRECATED(x) wxDEPRECATED_DECL x
                                           ^
AudacityApp.cpp:2159:1: warning: 'virtual void wxWindowBase::SetInitialBestSize(const wxSize&)' is deprecated: use SetInitialSize() instead. [-Wdeprecated-declarations]
 }
 ^
In file included from /usr/include/wx-3.0/wx/nonownedwnd.h:14:0,
                 from /usr/include/wx-3.0/wx/toplevel.h:20,
                 from /usr/include/wx-3.0/wx/frame.h:18,
                 from /usr/include/wx-3.0/wx/docview.h:21,
                 from AudacityApp.cpp:29:
/usr/include/wx-3.0/wx/window.h:1872:13: note: declared here
 inline void wxWindowBase::SetInitialBestSize(const wxSize& size)
             ^
AudacityApp.cpp:2159:1: warning: 'virtual bool wxEvtHandler::TryValidator(wxEvent&)' is deprecated [-Wdeprecated-declarations]
 }
 ^
In file included from AudacityApp.cpp:26:0:
/usr/include/wx-3.0/wx/event.h:3683:22: note: declared here
         virtual bool TryValidator(wxEvent& WXUNUSED(event)), return false; )
                      ^
/usr/include/wx-3.0/wx/defs.h:615:43: note: in definition of macro 'wxDEPRECATED'
 #define wxDEPRECATED(x) wxDEPRECATED_DECL x
                                           ^
/usr/include/wx-3.0/wx/event.h:3682:5: note: in expansion of macro 'wxDEPRECATED_BUT_USED_INTERNALLY_INLINE'
     wxDEPRECATED_BUT_USED_INTERNALLY_INLINE(
     ^
AudacityApp.cpp:2159:1: warning: 'virtual bool wxEvtHandler::TryParent(wxEvent&)' is deprecated [-Wdeprecated-declarations]
 }
 ^
In file included from AudacityApp.cpp:26:0:
/usr/include/wx-3.0/wx/event.h:3686:22: note: declared here
         virtual bool TryParent(wxEvent& event), return DoTryApp(event); )
                      ^
/usr/include/wx-3.0/wx/defs.h:615:43: note: in definition of macro 'wxDEPRECATED'
 #define wxDEPRECATED(x) wxDEPRECATED_DECL x
                                           ^
/usr/include/wx-3.0/wx/event.h:3685:5: note: in expansion of macro 'wxDEPRECATED_BUT_USED_INTERNALLY_INLINE'
     wxDEPRECATED_BUT_USED_INTERNALLY_INLINE(
     ^
AudacityApp.cpp:2159:1: warning: 'virtual void wxWindowBase::SetVirtualSizeHints(int, int, int, int)' is deprecated [-Wdeprecated-declarations]
 }
 ^
In file included from AudacityApp.cpp:26:0:
/usr/include/wx-3.0/wx/window.h:459:32: note: declared here
     wxDEPRECATED( virtual void SetVirtualSizeHints( int minW, int minH,
                                ^
/usr/include/wx-3.0/wx/defs.h:615:43: note: in definition of macro 'wxDEPRECATED'
 #define wxDEPRECATED(x) wxDEPRECATED_DECL x
                                           ^
AudacityApp.cpp:2159:1: warning: 'virtual void wxWindowBase::MakeModal(bool)' is deprecated [-Wdeprecated-declarations]
 }
 ^
In file included from AudacityApp.cpp:26:0:
/usr/include/wx-3.0/wx/window.h:688:32: note: declared here
     wxDEPRECATED( virtual void MakeModal(bool modal = true) );
                                ^
/usr/include/wx-3.0/wx/defs.h:615:43: note: in definition of macro 'wxDEPRECATED'
 #define wxDEPRECATED(x) wxDEPRECATED_DECL x
                                           ^
AudacityApp.cpp:2159:1: warning: 'virtual void wxWindowBase::SetInitialBestSize(const wxSize&)' is deprecated: use SetInitialSize() instead. [-Wdeprecated-declarations]
 }
 ^
In file included from /usr/include/wx-3.0/wx/nonownedwnd.h:14:0,
                 from /usr/include/wx-3.0/wx/toplevel.h:20,
                 from /usr/include/wx-3.0/wx/frame.h:18,
                 from /usr/include/wx-3.0/wx/docview.h:21,
                 from AudacityApp.cpp:29:
/usr/include/wx-3.0/wx/window.h:1872:13: note: declared here
 inline void wxWindowBase::SetInitialBestSize(const wxSize& size)
             ^
AudacityApp.cpp:2159:1: warning: 'virtual bool wxEvtHandler::TryValidator(wxEvent&)' is deprecated [-Wdeprecated-declarations]
 }
 ^
In file included from AudacityApp.cpp:26:0:
/usr/include/wx-3.0/wx/event.h:3683:22: note: declared here
         virtual bool TryValidator(wxEvent& WXUNUSED(event)), return false; )
                      ^
/usr/include/wx-3.0/wx/defs.h:615:43: note: in definition of macro 'wxDEPRECATED'
 #define wxDEPRECATED(x) wxDEPRECATED_DECL x
                                           ^
/usr/include/wx-3.0/wx/event.h:3682:5: note: in expansion of macro 'wxDEPRECATED_BUT_USED_INTERNALLY_INLINE'
     wxDEPRECATED_BUT_USED_INTERNALLY_INLINE(
     ^
AudacityApp.cpp:2159:1: warning: 'virtual bool wxEvtHandler::TryParent(wxEvent&)' is deprecated [-Wdeprecated-declarations]
 }
 ^
In file included from AudacityApp.cpp:26:0:
/usr/include/wx-3.0/wx/event.h:3686:22: note: declared here
         virtual bool TryParent(wxEvent& event), return DoTryApp(event); )
                      ^
/usr/include/wx-3.0/wx/defs.h:615:43: note: in definition of macro 'wxDEPRECATED'
 #define wxDEPRECATED(x) wxDEPRECATED_DECL x
                                           ^
/usr/include/wx-3.0/wx/event.h:3685:5: note: in expansion of macro 'wxDEPRECATED_BUT_USED_INTERNALLY_INLINE'
     wxDEPRECATED_BUT_USED_INTERNALLY_INLINE(
     ^
AudacityApp.cpp:2159:1: warning: 'virtual void wxWindowBase::SetVirtualSizeHints(int, int, int, int)' is deprecated [-Wdeprecated-declarations]
 }
 ^
In file included from AudacityApp.cpp:26:0:
/usr/include/wx-3.0/wx/window.h:459:32: note: declared here
     wxDEPRECATED( virtual void SetVirtualSizeHints( int minW, int minH,
                                ^
/usr/include/wx-3.0/wx/defs.h:615:43: note: in definition of macro 'wxDEPRECATED'
 #define wxDEPRECATED(x) wxDEPRECATED_DECL x
                                           ^
AudacityApp.cpp:2159:1: warning: 'virtual void wxWindowBase::MakeModal(bool)' is deprecated [-Wdeprecated-declarations]
 }
 ^
In file included from AudacityApp.cpp:26:0:
/usr/include/wx-3.0/wx/window.h:688:32: note: declared here
     wxDEPRECATED( virtual void MakeModal(bool modal = true) );
                                ^
/usr/include/wx-3.0/wx/defs.h:615:43: note: in definition of macro 'wxDEPRECATED'
 #define wxDEPRECATED(x) wxDEPRECATED_DECL x
                                           ^
AudacityApp.cpp:2159:1: warning: 'virtual void wxWindowBase::SetInitialBestSize(const wxSize&)' is deprecated: use SetInitialSize() instead. [-Wdeprecated-declarations]
 }
 ^
In file included from /usr/include/wx-3.0/wx/nonownedwnd.h:14:0,
                 from /usr/include/wx-3.0/wx/toplevel.h:20,
                 from /usr/include/wx-3.0/wx/frame.h:18,
                 from /usr/include/wx-3.0/wx/docview.h:21,
                 from AudacityApp.cpp:29:
/usr/include/wx-3.0/wx/window.h:1872:13: note: declared here
 inline void wxWindowBase::SetInitialBestSize(const wxSize& size)
             ^
AudacityApp.cpp:2159:1: warning: 'virtual bool wxEvtHandler::TryValidator(wxEvent&)' is deprecated [-Wdeprecated-declarations]
 }
 ^
In file included from AudacityApp.cpp:26:0:
/usr/include/wx-3.0/wx/event.h:3683:22: note: declared here
         virtual bool TryValidator(wxEvent& WXUNUSED(event)), return false; )
                      ^
/usr/include/wx-3.0/wx/defs.h:615:43: note: in definition of macro 'wxDEPRECATED'
 #define wxDEPRECATED(x) wxDEPRECATED_DECL x
                                           ^
/usr/include/wx-3.0/wx/event.h:3682:5: note: in expansion of macro 'wxDEPRECATED_BUT_USED_INTERNALLY_INLINE'
     wxDEPRECATED_BUT_USED_INTERNALLY_INLINE(
     ^
AudacityApp.cpp:2159:1: warning: 'virtual bool wxEvtHandler::TryParent(wxEvent&)' is deprecated [-Wdeprecated-declarations]
 }
 ^
In file included from AudacityApp.cpp:26:0:
/usr/include/wx-3.0/wx/event.h:3686:22: note: declared here
         virtual bool TryParent(wxEvent& event), return DoTryApp(event); )
                      ^
/usr/include/wx-3.0/wx/defs.h:615:43: note: in definition of macro 'wxDEPRECATED'
 #define wxDEPRECATED(x) wxDEPRECATED_DECL x
                                           ^
/usr/include/wx-3.0/wx/event.h:3685:5: note: in expansion of macro 'wxDEPRECATED_BUT_USED_INTERNALLY_INLINE'
     wxDEPRECATED_BUT_USED_INTERNALLY_INLINE(
     ^
AudacityApp.cpp:2159:1: warning: 'virtual void wxWindowBase::SetVirtualSizeHints(int, int, int, int)' is deprecated [-Wdeprecated-declarations]
 }
 ^
In file included from AudacityApp.cpp:26:0:
/usr/include/wx-3.0/wx/window.h:459:32: note: declared here
     wxDEPRECATED( virtual void SetVirtualSizeHints( int minW, int minH,
                                ^
/usr/include/wx-3.0/wx/defs.h:615:43: note: in definition of macro 'wxDEPRECATED'
 #define wxDEPRECATED(x) wxDEPRECATED_DECL x
                                           ^
AudacityApp.cpp:2159:1: warning: 'virtual void wxWindowBase::MakeModal(bool)' is deprecated [-Wdeprecated-declarations]
 }
 ^
In file included from AudacityApp.cpp:26:0:
/usr/include/wx-3.0/wx/window.h:688:32: note: declared here
     wxDEPRECATED( virtual void MakeModal(bool modal = true) );
                                ^
/usr/include/wx-3.0/wx/defs.h:615:43: note: in definition of macro 'wxDEPRECATED'
 #define wxDEPRECATED(x) wxDEPRECATED_DECL x
                                           ^
AudacityApp.cpp:2159:1: warning: 'virtual void wxWindowBase::SetInitialBestSize(const wxSize&)' is deprecated: use SetInitialSize() instead. [-Wdeprecated-declarations]
 }
 ^
In file included from /usr/include/wx-3.0/wx/nonownedwnd.h:14:0,
                 from /usr/include/wx-3.0/wx/toplevel.h:20,
                 from /usr/include/wx-3.0/wx/frame.h:18,
                 from /usr/include/wx-3.0/wx/docview.h:21,
                 from AudacityApp.cpp:29:
/usr/include/wx-3.0/wx/window.h:1872:13: note: declared here
 inline void wxWindowBase::SetInitialBestSize(const wxSize& size)
             ^
In file included from AudacityApp.cpp:216:0:
../images/AudacityLogoWithName.xpm:2:21: warning: 'AudacityLogoWithName_xpm' defined but not used [-Wunused-variable]
 static const char * AudacityLogoWithName_xpm[] = {
                     ^
AudacityApp.cpp:228:13: warning: 'void wxOnAssert(const wxChar*, int, const wxChar*)' defined but not used [-Wunused-function]
 static void wxOnAssert(const wxChar *fileName, int lineNumber, const wxChar *msg)
             ^
Makefile:2620: recipe for target 'audacity-AudacityApp.o' failed
make[1]: *** [audacity-AudacityApp.o] Error 1
make[1]: Leaving directory '/Depot/jj/audacity-2.1.1/src'
Makefile:716: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

------------------------------------------------

Any advice on how I could resolve it or should I just wait for a new release of audacity?

**Comment by JamesCrook** [comment]
2.1.1 isn't suitable for wxWidgets 3.0.2.  Recommend waiting for 2.1.2 to be released, or using GitHub master, if compiling with wxWidgets 3.0.2.  Also have a look at a recent automated build.... https://travis-ci.org/audacity/audacity/builds/89121174.  You're treating warnings as errors?
