### ISSUE TITLE
Please clarify copyright policy

### ISSUE THREAD

**Issue by Sciss** [audacity/audacity#844]
In order not to extend the already long comment thread on [#835](https://github.com/audacity/audacity/pull/835) - within it is buried now a post by @workedintheory

https://github.com/audacity/audacity/pull/835#issuecomment-834203391

mentioning multiple times CLAs (contributor license agreements) and the idea to have a "flexible" license, dual-licensing etc.

> Part of our commitment to open source is a commitment to transparency. Being fully transparent, the CLA of the open source projects we support does grant some form of flexibility in licensing. But what does this mean?
> 
> I will use the example of MuseScore. The MuseScore CLA does allow for the possibility to dual license the source code as GPL and proprietary, so long as it remains also available under GPL.
> 
> But why would we ever want to do this? How could this possibly be in service of the user and user choice?
> 
> [...] it is good to have more flexible options for limited scenarios such as alternative licensing for a specific build for a specific platform to solve a specific issue (ex: excluded from platform due to GLP as in VLC case).
> 
> In more simple terms, we view the potential of dual licensing as an insurance policy in order to ensure availability for the user on the platform of their choice.

As it stands, and regarding my understanding of the mechanisms of CLA, there _has never been_ a CLA system in place for this project. The contribution rules simply state the contributions _must be compatible with GPL_. No further rights were obtained from contributors through the regular channel of pull requests.

Since the project is decades old, and lists several contributors (perhaps a handful being responsible for the vast majority of commits ; but also the original authors Dominic Mazzoni and Roger Dannenberg not visible in the GitHub UI), could you clarify if and how you intend to add a CLA to the project? When Muse Group obtained the control of Audacity, did you obtain the licensing rights from all the main contributors, and how do you intend to deal with commits made by persons in the past that did not sign any CLA?

**Comment by Be-ing** [comment]
Using CLAs to enable [proprietary relicensing is not okay](https://sfconservancy.org/blog/2020/jan/06/copyleft-equality/).

As a an example of an acceptable CLA, consider [Signal's CLA](https://signal.org/cla/):

> Grant of Copyright License. Subject to the terms and conditions of this Agreement, You hereby grant to Open Whisper Systems and to recipients of software distributed by Signal Messenger a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable copyright license to reproduce, prepare derivative works of, publicly display, publicly perform, and distribute Your Contributions and such derivative works, as well as the right to sublicense and have sublicensed all of the foregoing rights, through multiple tiers of sublicensees, provided that in all cases, Signal Messenger will make Your Contributions available under an OSI-approved open source license.

**Comment by Sciss** [comment]
> Using CLAs to enable [proprietary relicensing is not okay](https://sfconservancy.org/blog/2020/jan/06/copyleft-equality/).

Well, this is more or less the spirit of [MuseScore's CLA](https://musescore.org/en/cla), so don't be surprised if this comes to Audacity soon.

**Comment by Be-ing** [comment]
> Well, this is more or less the spirit of MuseScore's CLA, so I would not be surprised if this comes to Audacity soon.

MuseScore's CLA is the worst possible kind of CLA. It gives MuseScore unilateral authority to license the code however they want with no strings attached. That's like an MIT license but even worse because only MuseScore has the legal authority to make proprietary versions. If any CLA like this comes to Audacity, it should be forked, regardless of what happens with the telemetry issue.

**Comment by simonsan** [comment]
> If any CLA like this comes to Audacity, it should be forked, regardless of what happens with the telemetry issue.

Yeah. `AuditCity` incoming ...

**Comment by Be-ing** [comment]
It is virtually impossible to impose a CLA on a 20 year old project with many contributors that has not had one before.

**Comment by simonsan** [comment]
> EDIT: This is confusing https://github.com/claytonotey/libsbsms/blob/main/LICENSE vs https://github.com/claytonotey/libsbsms/blob/main/COPYING

Good catch! Opened an issue.

https://github.com/claytonotey/libsbsms/issues/1

**Comment by simonsan** [comment]
They clarified the license @falkTX 

within https://github.com/claytonotey/libsbsms/commit/99691ede536f8d44b619472ce7126f15e2e32512 due to https://github.com/claytonotey/libsbsms/issues/1
