### ISSUE TITLE
Outdated Advice on Dependancies

### ISSUE THREAD

**Issue by rob-sanders** [audacity/audacity#845]
I'm trying to build audacity out of curiousity and came across references to the now dead googlecode repository.

https://github.com/audacity/audacity/blob/7e4e512739c98988197f54884634198a6abda0dd/lib-src/audacity-patches.txt#L214

it seems this whole section called "Crib notes on upgrading lib-src trees" is in need of switching to "git pull", the svn_load_dirs.pl script no longer exists.

$ find audacity -name svn_load_dirs.pl
(no output)

Sorry if this isn't how I'm meant to report this: I'm new to github. Anyway, good project guys.

**Comment by Be-ing** [comment]
See also: #840

**Comment by LWinterberg** [comment]
There currently is work being done on extracting most of these libraries, see https://github.com/audacity/audacity/projects/1 for progress. 

The patches list will be kept for historical purposes for now and may be removed when the extraction efforts are complete. 

Building instructions can be found on https://github.com/audacity/audacity/blob/master/BUILDING.md
