### ISSUE TITLE
TELEMETRY SHOULD NOT BE ADDED TO THIS GREAT PROJECT!!!!

### ISSUE THREAD

**Issue by jahway603** [audacity/audacity#846]
TELEMETRY SHOULD NOT BE ADDED TO THIS GREAT PROJECT!!!!

TELEMETRY SHOULD NOT BE ADDED TO THIS GREAT PROJECT!!!!

TELEMETRY SHOULD NOT BE ADDED TO THIS GREAT PROJECT!!!!

TELEMETRY SHOULD NOT BE ADDED TO THIS GREAT PROJECT!!!!

TELEMETRY SHOULD NOT BE ADDED TO THIS GREAT PROJECT!!!!

TELEMETRY SHOULD NOT BE ADDED TO THIS GREAT PROJECT!!!!

TELEMETRY SHOULD NOT BE ADDED TO THIS GREAT PROJECT!!!!

TELEMETRY SHOULD NOT BE ADDED TO THIS GREAT PROJECT!!!!

TELEMETRY SHOULD NOT BE ADDED TO THIS GREAT PROJECT!!!!

TELEMETRY SHOULD NOT BE ADDED TO THIS GREAT PROJECT!!!!

TELEMETRY SHOULD NOT BE ADDED TO THIS GREAT PROJECT!!!!

Thanks

**Comment by tilda** [comment]
this issue literally achieves nothing LOL
