### ISSUE TITLE
automated code style checking and linting

### ISSUE THREAD

**Issue by Be-ing** [audacity/audacity#847]
As demonstrated by https://github.com/audacity/audacity/pull/835#pullrequestreview-655027290 new developers do not automatically know how to keep code in a consistent style. I don't think anybody likes making noise about this in code reviews; it's better to let automated tools handle it and talk about the substantive changes. There are plenty of automated tools to do this. One of them should be run on CI to catch code style issues before merging.

I recommend using [pre-commit](https://pre-commit.com/) to catch these issues before even committing and advising new contributors to set this up. For C++ formatting, I suggest using clang-format with pre-commit. This can be set up to use clang-format only on the diff of the commit instead of needing to mass reformat the entire file and add a bunch of noise to the commit diff. On Mixxx, there is a [GitHub Actions workflow](https://github.com/mixxxdj/mixxx/blob/main/.github/workflows/pre-commit.yml) which uses pre-commit to clang-format and [variety of other automated code quality checks](https://github.com/mixxxdj/mixxx/blob/main/.pre-commit-config.yaml) only on the changed code. The GitHub Actions job uploads a patch with the automatic corrections as a GitHub Actions artifact so new developers can simply download that and apply the patch, then set up pre-commit locally to avoid future issues. There is a [separate GitHub Actions workflow](https://github.com/mixxxdj/mixxx/blob/main/.github/workflows/build-checks.yml#L88) which uses clang-tidy and clazy, which notably take approximately the same time to run as a full build and cannot use compiler caching.

**Comment by Be-ing** [comment]
cc @Holzhaus who set this up for Mixxx.

**Comment by BenBE** [comment]
Besides the formatting of the code usually the much greater issue is catching subtle bugs, like the integer overflow in multiplication. Given I've been working on various FLOSS projects over the years (GeSHi, htop, RRD, …) there always was the problem of not only getting the formatting right (smallest elephant in the room), but also check for these issues. From experience I found that, apart from locally run tools like [cppcheck](http://cppcheck.sourceforge.net/) you really want some external tooling like Coverity or LGTM to have a look at the code. Also having your build system able to create explicit debug builds with ASAN, TSAN, UBSAN and friends enabled, while forcing a zero-warning policy for code (at least `-Wall -Wextra -Werror -pedantic`, plus some specifics like e.g. `-Wformat=2` that aren't included in `-Wall` unfortunately).

Also providing people a tool to automagically format their code according to some baseline code style with a script maintained in the repository is a good start. But don't expect people to setup pre-commit hooks and other utilities just for some random PR they do: This will not work.

Thus while `clang-tidy` or `astyle` might be on the side of reasonable choices, anything that needs more than some `package-manager isntall tool` to setup will likely cause rejection to use that tool.

Another tool I'd suggest is [IWYU](https://github.com/include-what-you-use/include-what-you-use), which greatly helps to reduce the number of headers included senselessly. And on a side-note: You might want to define a clear order in which headers should appear. In my projects I found that alphabetical order, with system headers before project headers (own module header goes first before everything else) usually works quite nicely.

**Comment by BenBE** [comment]
Given that just pulling the sources and having all dependencies installed (except for that custom vendored wxWidgets version) this already FTBFS in the `cmake` step (demanding a custom, development version that you can't install on Ubuntu 20.04 LTS without jumping through hoops - which I don't intend to do), And yes, I've read why they want that version not available anywhere in the usual places.

And given the state of their build system and the way stuff is botched in there it's a waste of time trying to improve working with the system, unless the build system is cleaned up and improved first.

**Comment by Be-ing** [comment]
> don't expect people to setup pre-commit hooks and other utilities just for some random PR they do: This will not work.

In my experience, it actually does work quite well. Maintainers can simply tell contributors to download and apply the patch generated by GitHub Actions. Some don't and never respond, but those generally have more serious issues anyway.

**Comment by Be-ing** [comment]
> You might want to define a clear order in which headers should appear. In my projects I found that alphabetical order, with system headers before project headers (own module header goes first before everything else) usually works quite nicely.

clang-format can take care of this.

**Comment by rob-sanders** [comment]
I'm not sure if I'm missing something about the build, but why _isn't_ the patched wxWidgets in lib-src like all the other major dependencies?

Couldn't it compile the library into the audacity executable like most smaller libraries, saving us the conflict with other wxWidgets versions and allowing a cmake build from source?

**Comment by BenBE** [comment]
> > don't expect people to setup pre-commit hooks and other utilities just for some random PR they do: This will not work.
> 
> In my experience, it actually does work quite well. Maintainers can simply tell contributors to download and apply the patch generated by GitHub Actions. Some don't and never respond, but those generally have more serious issues anyway.
> 

If you have some ready patch they can apply to clean up this is a good way to go. But for anything more complex (and be it getting some explicit version of a random library you have to tell the build system about in a non-obvious way) you'll have quite a few people calling it quits.

> By the way, thanks for htop  It's usually one of the first packages I install after setting up a new Linux system.

Glad to hear. :heart:

NB: The build system in `htop` is `autotools` (we had a look at `cmake`, but in the end decided against because of compatibility with some platforms we need to support) and there are several libraries you can optionally chose to include for certain features (e.g. `libsystemd`, `libsensors`). The stand there is basically: If possible it's a compile-time dependency (and without much code, quite a bit is possible in that regard) only and at runtime things are checked if they are really available. Thus `htop` always uses the system libraries (and headers).

**Comment by BenBE** [comment]
> I'm not sure if I'm missing something about the build, but why _isn't_ the patched wxWidgets in lib-src like all the other major dependencies?

Just did a `git clone` and hoped for the build system to pick it up from the installed system package. With the default Ubuntu one it complained about it needing the custom patched one and after installing that one (3.1.5 from some repo where someone built it) it picked up on that new version but complained about not finding `wxWidgets_LIBRARIES` and `wxWidgets_INCLUDEDIRS`. And that was the point when the amount of debugging I wanted to invest into a simple build from source ended.

> Couldn't it compile the library into the audacity executable like most smaller libraries, saving us the conflict with other wxWidgets versions and allowing a cmake build from source?

Don't. wxWidgets is large enough that their maintainers already split it up into various sub-projects. You could go about building it statically, but then you'd end up having to compile all of its dependencies as static as well (which I'd call good luck with GTK3+) …

So the FTBFS issue here is that setting up the wxWidget stuff to be found while using that custom version is non-trivial and just allowing to build with the system-installed (3.0.x) libraries should work (and be it with a warning about the stability issues).

2ct

**Comment by Be-ing** [comment]
Please take discussion about the wxWidgets fork to #625.

**Comment by Holzhaus** [comment]
> > don't expect people to setup pre-commit hooks and other utilities just for some random PR they do: This will not work.
> 
> In my experience, it actually does work quite well. Maintainers can simply tell contributors to download and apply the patch generated by GitHub Actions. Some don't and never respond, but those generally have more serious issues anyway.
> 
> By the way, thanks for htop  It's usually one of the first packages I install after setting up a new Linux system.

One of the Mixxx devs here. I agree with this. We use `pre-commit` for quite a while. For long-term contributors/devs it's pretty nice because you can just set it up locally and stop caring about code style anymore. It takes care of it automatically on each commit. And it also prevents you from adding a big "reformat code" commit at the end, which makes the git history harder to read, because if you set it up locally every commit is clean in terms of code style.

For drive-by contributions, the CI setup is nice because it warns you about code style issues (and some of these may not even be visible in the GitHub diff, e.g. trailing whitespace). For these contributors, the CI automatically creates a patch that can be downloaded and applied with `git apply < pre-commit.patch`.

Sure, there are some contributors that don't do this and ignore your request to apply the patch and just abandon the PR instantly after opening it. But this would also happen if you don't have `pre-commit` and point out code style issues manually during review. And tbh, if you do point out them manually you'll likely pile up a large number of code style related review comments that may be even more intimidating to new contributors compared to a single message "please apply this patch".

**Comment by Paul-Licameli** [comment]
I am closing this.

I do not want petty white space wars creeping into the mix of all the other things to discuss now.

Reopen this idea in a few months after temperature at this GitHub project has cooled down, and after the more "substantive changes" like vendoring are fairly discussed.

**Comment by BenBE** [comment]
Whitespace changes is the smallest part in linting. The much more important part (yet less visible usually) is about looking for patterns that usually are signs of bugs, bad practices or risks of security issues creeping in.

**Comment by Holzhaus** [comment]
I suggest to move the last few comments to a new issue, because compiler warnings are distinct from pure code style issues because they can be signs of actual bugs. Discussing this in a closed issue about code style doesn't do the topic justice I think.

**Comment by Paul-Licameli** [comment]
I concur.  Locking the comments now.
