### ISSUE TITLE
Audacity Team not listening to Audacity community that they do not want Telemetry in this application they use

### ISSUE THREAD

**Issue by jg777** [audacity/audacity#850]
**Describe the bug**
The Audacity Team continues to not listen to the Audacity community when they have been very clear in PR #835 that they do not want Telemetry in this application they use.

**To Reproduce**
1. Go to PR #835 
2. See #835 that there are currently 3,310 thumbs DOWN ratings regarding this PR.
3. See #835 that there are currently 1,065 comments in this PR.
4. See #835 that tons of Audacity users and the Audacity community does not want Telemetry added to Audacity.

**Expected behavior**
For PR #835 to be closed and that no Telemetry be implemented.

**Screenshots**
N/A

**Additional information (please complete the following information):**
 - OS: [e.g. Mac High Sierra, Ubuntu 18.04, Windows 10]
 - Version [e.g. Audacity 2.5.1]
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]

**Additional context**
If the Audacity Team wants to still have a user base then they will listen to the people actually using Audacity.

**Comment by foreverxml** [comment]
I made a [comment](https://github.com/audacity/audacity/pull/835#issuecomment-835829214) describing this to the Muse Group, who apparently do not know about all the forks people are going to make.

**Comment by SteveDaulton** [comment]
While providing feedback is very welcome, repeatedly posting your opinion over and over again is considered spamming, and undermines the cause that you intend to promote.
