### ISSUE TITLE
Audacity Team not listening to Audacity community that they do not want Telemetry added into Audacity

### ISSUE THREAD

**Issue by jg777** [audacity/audacity#851]
Describe the bug
The Audacity Team continues to not listen to the Audacity community when they have been very clear in PR #835 that they do not want Telemetry in this application they use.

To Reproduce

Go to PR #835 

1. See #835 that there are currently 3,310 thumbs DOWN ratings regarding this PR.
2. See #835 that there are currently 1,065 comments in this PR.
3. See #835 that tons of Audacity users and the Audacity community does not want Telemetry added to Audacity.

Expected behavior
For PR #835 to be closed and that no Telemetry be implemented.

Screenshots
N/A

Additional information (please complete the following information):

OS: [e.g. Mac High Sierra, Ubuntu 18.04, Windows 10]
Version [e.g. Audacity 2.5.1]
(if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]
Additional context
If the Audacity Team wants to still have a user base then they will listen to the people actually using Audacity.

**Comment by jg777** [comment]
This is a REAL issue, so please stop closing my bug reports.

**Comment by foreverxml** [comment]
@jg777 This is, in fact, a real issue.

**Comment by jg777** [comment]
> @jg777 This is, in fact, a real issue.

Agreed. I had to open this issue as they closed Issue #850

**Comment by llacb47** [comment]
You can stop creating useless issues now.

**Comment by Jean1995** [comment]
https://github.com/audacity/audacity/pull/835#issuecomment-835880865 closed this issue
