### ISSUE TITLE
Multi User Recording

### ISSUE THREAD

**Issue by netpipe** [audacity/audacity#854]
would like something like Jamulus to be implemented into audacity for multiUserJamSessions or multiple midi recording devices also midi recording/editing ability would be handy to have too. 

qmidinet
https://github.com/williamweston/jamrouter.git
ninjam
multimidicast v1.3 (c) 2005..2011 by Dirk Jagdmann doj@cubic.org

might even be doable with just a simple ftp server for sharing same file and updates.

**Comment by prsmahajan** [comment]
Hi, I would like to work on this issue, can you suggest me to get started?

**Comment by netpipe** [comment]
i would say just try to jam jamulus into audacity somehow and/or put a ftp server into audacity and have it push and pull the audio project once saved. 

https://speex.org/docs/manual/speex-manual/node13.html there is this too.

**Comment by netpipe** [comment]
so its working now ?

**Comment by LWinterberg** [comment]
No, it's out of scope. Audacity doesn't even do multi channel recording yet (eg you can't record both the desktop audio and your voice at the same time), doesn't do MIDI recording, and doesn't upload files for you. The suggested functionality is beyond the scope of Audacity development for the forseeable future.
