### ISSUE TITLE
Using WxWidgets Qt backend?

### ISSUE THREAD

**Issue by falkTX** [audacity/audacity#861]
This is more of a question rather than a feature request.
As Musescore is done in Qt and Muse Group is hiring Qt developers, seems the interest is on Qt things.
Audacity is an old codebase, changing the entire toolkit is not a good decision at this point, too much core elements rely on WxWidgets.
If everyone working in the codebase is familiar with the same toolkit (say Qt) it makes the overall process much smoother.

Now with that said, WxWidgets has a WIP Qt backend.
Find more details in https://wiki.wxwidgets.org/WxQt

So I am opening this ticket to bring a discussion around this topic.
I see a few clear benefits from such move:

1. Easier to maintain, as less platform-specific solutions are needed (whatever WxWidgets does not do, Qt will)
2. Consistent look across all platforms (Qt allows custom themes)
3. More integrated into what Muse Group devs are working with right now.

I am not just opening a ticket to request things, I actually went ahead and spent some hours to try this out.
There are a few places in Audacity where code needs to be adapted, but it is only a few days work maximum.
I was able to hack around in a few places in Audacity code to make everything build and run.
As a bonus, I threw in my own custom color palette and style that I use in Carla.
Here are a few screenshots to show the result:

![Screenshot_20210510_233946](https://user-images.githubusercontent.com/1334853/117733850-2b309580-b1ea-11eb-9888-60801dc4b0fa.png)

![Screenshot_20210510_234834](https://user-images.githubusercontent.com/1334853/117733890-400d2900-b1ea-11eb-892a-a3148ca4041c.png)

native file dialog through qt:

![Screenshot_20210510_234937](https://user-images.githubusercontent.com/1334853/117733988-67fc8c80-b1ea-11eb-933c-c88c8409898a.png)

![Screenshot_20210510_235118](https://user-images.githubusercontent.com/1334853/117734085-a2fec000-b1ea-11eb-879d-574136f2b43f.png)

Colors can be changed of course, I just like this style in particular. It is a slightly modified Fusion theme from Qt.

Now the main question is... is there interest on this?

WxWidgets Qt backend is still work-in-progress yes, but on the other hand Audacity does not need the entire thing.
Fixing WxWidgets Qt side (and then submitting patches upstream) could be a way forward here.

Looking forward to comments and/or opinions.

**Comment by Be-ing** [comment]
> Consistent look across all platforms (Qt allows custom themes)

To clarify, does the theme come from Qt or wxWdigets? Sharing a Qt theme between Audacity and MuseScore could be an interesting idea.

**Comment by falkTX** [comment]
Theme is from Qt side.
Qt themes are done in C++, but there are a few "theme engines" like https://github.com/tsujan/Kvantum/tree/master/Kvantum that allow for SVG asset rendering.

**Comment by imciner2** [comment]
The wxQT backend is somewhat minimal currently - and if I recall only one main group was contributing to it for their own app support. There are many places in it that may end up just not working because parts haven't been implemented (one major place that hasn't been implemented is the OpenGL support and `wxGLCanvas`).

**Comment by imciner2** [comment]
Also, switching to the wxQT backend is a lot more work for packaging on Linux than just switching to QT, since linux distros don't build anything other than the wxGTK backend normally.

**Comment by falkTX** [comment]
From what I have tested and saw in the code, a lot of stuff already works. Some drawing issues seem to be due to transparency being used, so perhaps the ghosting is fixed by a simple QWidget::setOpaque() in the right places.
I didnt check OpenGL related things, is Audacity using those?

On a somewhat related topic...
I do not know what are Muse Group plans for Audacity, looking at the recent commits it seems to me the intention is to make an engine out of Audacity to be usable on some new GUI (is that what QML is for?)
Doing a brand new GUI from scratch is a lot of work, compared to fixing up something that mostly works already.
The fact that the same style could be applied to Musescore and Audacity (while retaining Audacity's iconic UI) is worth a lot.

**Comment by SteveDaulton** [comment]
There's also the much requested "Audacity for mobile" to consider. Does wxQt support Android or iOS yet? The last time I looked, it didn't.
