### ISSUE TITLE
Audacity segfaults on Fedora when connecting to a USB audio input 

### ISSUE THREAD

**Issue by limburgher** [audacity/audacity#878]
**Describe the bug**
https://bugzilla.redhat.com/show_bug.cgi?id=1951183

**To Reproduce**
See Fedora BZ

**Additional information (please complete the following information):**
Fedora 33, Mixmeister *ion USB recorder

**Comment by LWinterberg** [comment]
from the bugtracker

> This bug was fixed with the release of Audacity 3.0.2 - many thanks to all who were involved with doing it.
