### ISSUE TITLE
[i18n] Issue with some strings

### ISSUE THREAD

**Issue by Matthaiks** [audacity/audacity#887]
**Describe the bug**
Even if the translation file is complete, Audacity will display some strings in English. 

**To Reproduce**
1. Change Audacity's language to Dutch or Polish (or other 100% translated).
2. See translated strings in English.

**Expected behavior**
Fix these problematic strings.

**Screenshots**
![1](https://user-images.githubusercontent.com/3577122/118048015-ef2d3a00-b37b-11eb-842f-1511ac728017.png)
"Filter Curve" is missing from audacity.pot, there's Filter Curve EQ, though.
![2](https://user-images.githubusercontent.com/3577122/118048018-f05e6700-b37b-11eb-873a-e044a6bb077c.png)
![3](https://user-images.githubusercontent.com/3577122/118048021-f0f6fd80-b37b-11eb-8a44-3ecc035949bd.png)

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version Audacity 3.0.2

**Comment by JamesCrook** [comment]
See also Bugzilla bug https://bugzilla.audacityteam.org/show_bug.cgi?id=2741

**Comment by petersampsonaudacity** [comment]
Appears to be fixed with   CMake Build #1684: Commit 9e70fa7 pushed by JamesCrook :  https://github.com/audacity/audacity/actions/runs/838439781

See bug testing comments in P2 Bug #2741:  https://bugzilla.audacityteam.org/show_bug.cgi?id=2741

**Comment by Matthaiks** [comment]
"Interface" seems to be fixed, "Silence" and "Filter Curve" are still in English, though.

**Comment by petersampsonaudacity** [comment]
@Matthaiks  - the Filter Curve is a different issue - see this open bug https://bugzilla.audacityteam.org/show_bug.cgi?id=2339
Bug 2339 - On second run of Audacity "Filter Curve EQ" gets changed to "Filter Curve..." in the Effect menu

There is a translation for Filter Curve EQ on first use you get "Filterkurve-EQ" - but on next launch of Audacity you get "Filter Curve" untranslated (this was the old name for the effect.

**Comment by petersampsonaudacity** [comment]
@Matthaiks  - and yes I still see "Silence" in the Erzeugen menu and not "Stille"

**Comment by petersampsonaudacity** [comment]
Reopened the issue due to the untranslated in "Silence" auf Deutsch

**Comment by petersampsonaudacity** [comment]
This is only in the Erzeugen (Generate) menu that it is not translated - the generator banner correctly  says "Stille"

**Comment by Paul-Licameli** [comment]
> This is only in the Erzeugen (Generate) menu that it is not translated - the generator banner correctly says "Stille"

I observed that too and it is very puzzling.

**Comment by petersampsonaudacity** [comment]
I have logged the untranslated "Silence..." as new P3 Bugzilla entry Bug #2778
https://bugzilla.audacityteam.org/show_bug.cgi?id=2778
Bug 2778 - In German in the Erzeugen menu (Generator menu) "Silence..." is untranslated

I also noted that this affects other languages as @Matthaiks reports

And as the "Filter Curve" issue is already logged as:
https://bugzilla.audacityteam.org/show_bug.cgi?id=2339
Bug 2339 - On second run of Audacity "Filter Curve EQ" gets changed to "Filter Curve..." in the Effect menu

I shall close this GitHub thread

**Comment by petersampsonaudacity** [comment]
These translation issues are now fixed in the latest alpha test build for 3.0.3
