### ISSUE TITLE
[Portsmf] Cannot build Audacity anymore.

### ISSUE THREAD

**Issue by carlo-bramini** [audacity/audacity#892]
I'm getting this message when building the lib-src of Audacity:
```
In file included from /lib-src/portsmf/allegrowr.cpp:13:
/lib-src/portsmf/allegro.h: In member function ‘const char* Serial_read_buffer::get_string()’:
/lib-src/portsmf/allegro.h:602:33: error: ‘strlen’ was not declared in this scope
  602 |                          ptr += strlen(s);
      |                                 ^~~~~~
/lib-src/portsmf/allegro.h:52:1: note: ‘strlen’ is defined in header ‘<cstring>’; did you forget to ‘#include <cstring>’?
   51 | #include <assert.h>
  +++ |+#include <cstring>
   52 | #include <istream>
```
It seems that this call to `strlen()` has been added recently, because it was not existing before updating my source tree. However, the suggestion from GCC seems correct, it is better to add `cstring` to the list of the include files and not assuming that this file could be included elsewhere by other system includes.

Sincerely.

**Comment by LWinterberg** [comment]
The build system has changed since this was made, try again. Closing bug as stale.
