### ISSUE TITLE
For-profit Takeover of FOSS Software

### ISSUE THREAD

**Issue by a-leut** [audacity/audacity#897]
**Describe the bug**
Muse Group (a for profit company) "bought" Audacity and tried to retroactively add a CLA to the GPL license

**To Reproduce**
See this issue: https://github.com/audacity/audacity/issues/844

**Expected behavior**
Anonymous for-profit companies don't buy GPL software and start tracking users and making it worse

**Resolution**
All developers and users switch to this fork to maintain GPL ethos:
https://github.com/yonderbread/foss_audacity

**Comment by Firepal** [comment]
?
