### ISSUE TITLE
Set Tremolo Hz to a more precise value than a tenth of a Hz?

### ISSUE THREAD

**Issue by Wizek** [audacity/audacity#90]
Hello,

I've stumbled into this issue:
http://sound.stackexchange.com/questions/37600/in-audacity-how-to-apply-tremolo-effect-of-0-25-hz-15-cycles-minute

And am wondering how easy or difficult would it be to allow more precise values to be entered in the text field than a tenth of an Hz.

I'm also wondering that if I look for relevant sections of the code and prepare a patch, would you likely merge my pull request of a fix?

**Comment by SteveDaulton** [comment]
The Tremolo effect has been updating in the forthcoming Audacity 2.1.2 release and now allows values less than 0.1 Hz.

Steve

**Comment by Wizek** [comment]
Oh, really? I'm glad to hear that!

Just to note: I've also started to look at the code, and found this section: https://github.com/audacity/audacity/blob/ae5d29a04815cc41ccf36ef765a9f75636b8bd21/plug-ins/tremolo.ny#L22

It was surprisingly easy to tweak a value in here that allowed me to get the result I wanted even in Audacity 2.0.5.
Since you are saying this is fixed anyways in an upcoming release, I won't be making a pull request.

Thanks for the quick response!
