### ISSUE TITLE
Check the preferences dialog for the new spectrogram view. Make any changes needed and take a note of strings.

### ISSUE THREAD

**Issue by Tantacrul** [audacity/audacity#913]

**Comment by petersampsonaudacity** [comment]
Which new Spectrogram view is that ?

**Comment by Tantacrul** [comment]
The one being proposed by a community member - with the new colours. We need to sort out a few things first. Sorry! I created this task to remind me to add more detail later.

However, I understand that this new spectral view also requires a small number of string changes in Preferences.

**Comment by petersampsonaudacity** [comment]
> 
> 
> The one being proposed by a community member - with the new colours. 

OOH that's good - I did like that one

**Comment by LWinterberg** [comment]
this seems like it's a leftover from 3.0.3 and no longer relevant. Closing it.
