### ISSUE TITLE
Broken link to release notes on website

### ISSUE THREAD

**Issue by scott71** [audacity/audacity#92]
I hope it is OK to post this here. I couldn't send the devs messages on here or at least i couldn't figure out how to. 
The link: http://wiki.audacityteam.org/wiki/Release_Notes (on http://audacityteam.org/download/source)  is broken. "Forbidden You don't have permission to access /wiki/Release_Notes on this server."

FYI. TY! Awesome software! (=

**Comment by windinthew** [comment]
The feedback address http://audacityteam.org/contact/#feedback is the best way to contact us without having to subscribe or log in anywhere.  

http://wiki.audacityteam.org/wiki/Release_Notes is working for me as I write. 

http://downforeveryoneorjustme.com/http://wiki.audacityteam.org/wiki/Release_Notes

**Comment by scott71** [comment]
I see it working now too. either way. thank you for reply. (=
