### ISSUE TITLE
Better handling of Orphan Blocks

### ISSUE THREAD

**Issue by JamesCrook** [audacity/audacity#925]
Currently if Audacity detects orphan blocks, it just deletes them silently.

Orphan blocks are an inconsistent state in an .aup3 project file that simply should not arise.  However, we've seen two cases/examples in corrupt projects where they have arisen.  We need to discuss and work out what to do with these orphan blocks when they are found, and implement.

**Comment by Paul-Licameli** [comment]
Related: https://bugzilla.audacityteam.org/show_bug.cgi?id=2761

I was thinking of writing a fix for this today.  This much is uncomplicated.
