### ISSUE TITLE
Audacity doesn't remember working directory when opening new file through menu (Mac)

### ISSUE THREAD

**Issue by flothesof** [audacity/audacity#93]
Hi there,

I use Audacity 2.1.1 on Mac (El Capitan). Whenever I use the open file dialog, Audacity sets me back to my home directory instead of the directory I opened the last file in.
I expect Audacity to remember the working directory I am in when opening new files. Is my expectation wrong, or might this be a bug? 
Thanks in advance for your help, I've been unable to find anything related in the FAQ or googling.

Best,
Florian

**Comment by windinthew** [comment]
Hi,  Please note this is not a guaranteed support address or bug reporting line. For support, Audacity Forum http://forum.audacityteam.org/viewforum.php?f=47 . For bug reports, http://audacityteam.org/contact/#feedback .

The last file open location is stored at "DefaultOpenPath" in the audacity.cfg settings file.  You could try deleting that file ( ~/Library/Application Support/audacity/audacity.cfg ).  If that does not solve the problem then check if the path is getting written to audacity.cfg. If not you may have permissions failure on the file - see https://discussions.apple.com/thread/7292563?start=0&tstart=0 .

**Comment by JamesCrook** [comment]
Sorry for not getting back to this sooner.
Audacity on Mac does (now) remember the last location you opened from (not the last location you saved to) so this is fixed now, and probably was some time ago.
Thanks for the bug report.
