### ISSUE TITLE
Status bar message change

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#930]
**Is your feature request related to a problem? Please describe.**
A recent German-speaker on the Forum pointed out that "Actual Rate" in the Status bar was not clear in what it meant.  In German we have "Aktuelle Rate" which translates in English to "Current Rate" - see this Forum post: https://forum.audacityteam.org/viewtopic.php?f=70&t=118238

The same issue arose from a different Forum poster four years ago.  At that time Gale Andrews (RIP) suggested:
>"Would 'Sent Rate' for playback and 'Received Rate' when recording be any better?"
See:  https://forum.audacityteam.org/viewtopic.php?t=94782
At the time the OP never responded and Gale sadly died not long after so this issue ran to ground, but I think Gale's suggestion is an excellent one that gives greater clarity of purpose, greater "discoverability" of what that rate data is about.

**Describe the solution you'd like**
change the Status Bar "Actual rate to be:
- **Received Rate** for playback
- **Sent Rate** when recording

I created a Wiki>Wording entry for this, see:  https://wiki.audacityteam.org/wiki/Wording#Status_Bar

**Comment by SteveDaulton** [comment]
"Actual Rate: 44100 Hz" is very clear to me - it is the actual (real) sample rate that Audacity is currently running.
(It may differ from the "Project Rate" in certain cases).

I've no idea what "Received Rate for Playback" or "Sent Rate when recording" mean - received from where? sent to where?

**Comment by petersampsonaudacity** [comment]
It's really only "clear" when you know what the "Actual" is referring to, probably once you've read the Manual.

Alternatives

- **Sound Card Rate**

or

- **Playback Rate**
- **Recording Rate**

**Comment by petersampsonaudacity** [comment]
If I was designing this from scratch I'd have a Toolbar for "**Sound Card Rate**"
- not have it in the Status bar 
- and it would probably be "off" by default.

**Comment by JamesCrook** [comment]
Closed as NOT-A-BUG.
It's a feature/change request, requested on the forum twice in the last five years, and (per Steve's comment) a contentious change, as people are used to the existing wording.  'Sound Card Rate' _is_ probably clearer than 'Actual rate', but it is not sufficiently that much clearer to merit  making the change at this time - and we'd probably need to argue through whether it should be 'Audio Device' rather than 'Sound Card'.  :-)  There are bigger fish to fry.
