### ISSUE TITLE
Update Manual for new spectral colors

### ISSUE THREAD

**Issue by Paul-Licameli** [audacity/audacity#969]
Pages to change:
https://manual.audacityteam.org/man/extra_menu_scriptables_i.html#set_track_visuals (Gray scale checkbox is replaced with a choice)

https://manual.audacityteam.org/man/scripting_reference.html (parameters for Set Track Visuals command)

https://manual.audacityteam.org/man/spectrograms_preferences.html (Spectrogram preferences)

**Comment by petersampsonaudacity** [comment]
The new spectral colors habe not been pulled into the Master trunk yet, so it is not timely yo update the MAnual

**Comment by petersampsonaudacity** [comment]
I see this from Extra>ScriptablesI
![image](https://user-images.githubusercontent.com/50205984/121703757-6ff26980-cad3-11eb-88d1-f575a3ad8ac9.png)

Which then gets me
![image](https://user-images.githubusercontent.com/50205984/121703994-a203cb80-cad3-11eb-9dbe-1a0f4db5e886.png)

I assume that that is what you expect to see

**Comment by petersampsonaudacity** [comment]
Other changes

1) This one is a biggy
https://alphamanual.audacityteam.org/man/Spectrogram_View

2) This one will need some work too
https://alphamanual.audacityteam.org/man/Multi-view

3) https://alphamanual.audacityteam.org/man/Audacity_Selection#spectral

4) https://alphamanual.audacityteam.org/man/Audacity_Waveform#alternate

5) https://alphamanual.audacityteam.org/man/Audio_Track_Dropdown_Menu

6) https://alphamanual.audacityteam.org/man/Audio_Tracks#display

7) https://alphamanual.audacityteam.org/man/Click_removal_using_the_Spectrogram_view

8) https://alphamanual.audacityteam.org/man/Spectral_Delete

9) Another biggy
https://alphamanual.audacityteam.org/man/Spectral_Selection

10) https://alphamanual.audacityteam.org/man/Spectrogram_Settings

That's a fair few - and quite a lot of work ...



Pro tem - these two pages could be left as-is but with a note dive to explain that they are using the "classic" colorway.

**Comment by petersampsonaudacity** [comment]
An alternative to udating the many, many inages and pages with spectrograms would be to continue with the original colorway as the default and offer the new one as an option to select in Spectrograms Preferences.

But that would have implications for the strings which would need to change - as we would need nomenclature for the new colorway.

**Comment by petersampsonaudacity** [comment]
> as we would need nomenclature for the new colorway.

If I were choosing nomenclature I would call the two colorways
a) Light
b) Dark

Light being the original colorway of Paul's (works well with Light Audacity theme)
Dark - the new one fron dofuuz, this works nicely with Dark Audacity theme

**Comment by Paul-Licameli** [comment]
> Light being the original colorway of Paul's (works well with Light Audacity theme)

I can't take credit for the classic Audacity spectrogram colors.  They predate all my work.

**Comment by petersampsonaudacity** [comment]
I note that as of latest alpha Audacity-3.0.3-alpha-20210613+7d76e06-32bit

this new spectral colorway has still not been pulled into the Master builds.

_So unless and until that happens this is not an "open issue" as such - it is just a "plan" ..._

**Comment by petersampsonaudacity** [comment]
I have set P1s in the manual for pages that MUST be updated for the new Spectrogram colorway(s) - and I have set ntes on other pages advising that the images are usin the non-default Classic colorway - wit a P2 for future uodtae when time and manpower allows.

I will probably not have time to deal with the P1 until the weekend or early next week.
