### ISSUE TITLE
Noise source in  audacity/src/effects/Noise.cpp is poor

### ISSUE THREAD

**Issue by milasudril** [audacity/audacity#97]
Is there any reason to not use a more descent random generator for noise. In C++11

    std::mt19937 randgen;
    std::uniform_real_distribution<float> U(-1,1);

    buffer[i]=mAmp*U(randgen);

If C++11 is not an option yet, boost might be.

**Comment by SteveDaulton** [comment]
Is there a practical use case where "more random than now" is required ?
If you think that there is a strong case for why changing this will benefit Audacity users, please raise the issue on the mailing list: https://lists.sourceforge.net/lists/listinfo/audacity-quality
As we have limited resources, we don't really want to be spending time on things that have no significant benefit for users.

**Comment by milasudril** [comment]
The most obvious benefit is that you will get the same quality on all platforms. In particular, Windows users will have the most benefit, because this engine is very poor.
