### ISSUE TITLE
"Cancel" track spectrogram settings does not cancel

### ISSUE THREAD

**Issue by SteveDaulton** [audacity/audacity#974]
After opening "Track menu > Spectrogram Settings", clicking the "Cancel" button does not cancel a potential change.

**To Reproduce**
1. Generate a chirp from 1 Hz to 20000 Hz.
2. Set track view to "Spectrogram".
3. Zoom out vertically to see from 0 to Nyquist frequency (0 to 22050 by default)
4. "Track dropdown menu > Spectrogram settings".
5. Click the "Cancel" button.
6. Observe that the vertical zoom changes back to default (0 to 8000 Hz by default)

**Expected behaviour**
No  change (action cancelled)

**Additional information (please complete the following information):**
 - OS: Xubuntu 20.04 LTS (UPD: and Win 10 x64)
 - Version: Audacity 3.0.3 alpha Commit Id: 744455 (reproduced in 3.0.3 RC)

**Additional context**
The same problem occurs when using "Esc" to escape from the track spectrogram settings.
See also: Bug 2685 - Track Spectrogram settings may change global preferences

**Comment by LWinterberg** [comment]
I don't see us fixing this any time soon
