### ISSUE TITLE
Ability to color code labels

### ISSUE THREAD

**Issue by equant** [audacity/audacity#976]
**Is your feature request related to a problem? Please describe.**
While podcast editing, I end up with many labels and it can be hard to find/read/organize them all in my workflow.

**Describe the solution you'd like**
I'd like to be able to color code labels.  This way a certain color could represent tasks to be done (e.g. "Add slide whistle drop") and a different color could be a logistical marker (e.g. "Recording interrupted by riding lawnmower gang") while another color could describe the audio (e.g. "Discussion about catastrophic zipper failures")

**Describe alternatives you've considered**
I've tried to organize labels by using multiple label tracks. I find this doesn't work because it's hard to create labels in a particular spot since all label tracks have to be at the bottom (of all tracks) in order to preserve time synchronization, so only the top most label track can have a new label created using ctrl+b/crtrl+m.  Also I can't move labels between label tracks.

**Comment by LWinterberg** [comment]
Color-coding labels is too niche a feature for the current roadmap, and I'm also not sure if it's even wise to support them - I'd like labels to be interoperable with other audio metadata (eg wav CUE, or CART markers) eventually. 

That said, label tracks serving double-duty for breaking up sync-lock is fairly bad, and that particular behavior will be changed in the near-ish future when clip grouping becomes a thing.
