### ISSUE TITLE
Build failure on Mac

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity#979]
Cliff Scott reportes this just now on the Quality email list:

Went to build Audacity last evening and the build failed so started a new bld directory and the configuration fails now. Last build I did was a couple of weeks ago as I only have occasional Internet at the moment. Help!! Output log attached.

Configuration failure:

Building Audacity

-- The C compiler identification is AppleClang 11.0.0.11000033
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at cmake-proxies/cmake-modules/conan.cmake:795 (message):
  Conan executable not found! Please install conan.
Call Stack (most recent call first):
  cmake-proxies/cmake-modules/conan.cmake:841 (conan_check)
  cmake-proxies/cmake-modules/AudacityDependencies.cmake:4 (conan_add_remote)
  CMakeLists.txt:156 (include)

-- Configuring incomplete, errors occurred!
See also "/Users/CMac/Downloads/Audacity/BuildEnvironment/audacity/bld/CMakeFiles/CMakeOutput.log”.

Cliff

**Comment by crsib** [comment]
Hi! We require Conan to build Audacity now. Detailed instructions are here: https://github.com/audacity/audacity/blob/master/BUILDING.md
