### ISSUE TITLE
Use clear text names for OSS devices on FreeBSD

### ISSUE THREAD

**Issue by probonopd** [audacity/audacity#990]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when sound devices are shown as `/dev/pcmX` rather than with their speaking names such as `NVIDIA (0x0060) (HDMI/DP 8ch)` or `USB audio`.

**Describe the solution you'd like**
Audacity should use the information, e.g., from
```
FreeBSD% cat /dev/sndstat 
Installed devices:
pcm0: <NVIDIA (0x0060) (HDMI/DP 8ch)> (play)
...
pcm3: <USB audio> (play/rec) default
...
```

to convert device names like `/dev/pcmX` into speaking names such as `NVIDIA (0x0060) (HDMI/DP 8ch)` or `USB audio`.

**Additional context**

In this example, I have selected `/dev/dsp3` for recording and `/dev/dsp4` for playback. Thing is, most people don't know what `/dev/dsp3` and `/dev/dsp4` are but they do know the difference between `NVIDIA (0x0060) (HDMI/DP 8ch)` and `USB audio`.

![image](https://user-images.githubusercontent.com/2480569/122300301-6ddb4100-ceff-11eb-953e-20b809bd832e.png)

Reference:
https://github.com/helloSystem/Utilities/issues/71#issuecomment-862754348

**Comment by LWinterberg** [comment]
While we may accept patches for freeBSD support, we're currently not looking into actively supporting it ourselves.
