### ISSUE TITLE
Stackable effects

### ISSUE THREAD

**Issue by AnitaBats** [audacity/audacity#992]
Ability to add one or more effects per track, which are realtime and non-destructive (unless "frozen"/applied destructively), and can be stacked as an effects chain on top of each other.

It should also be possible to reorder the position of the effects in the chain.

This issue is meant as a spec for developers (in progress until closed). For discussion around the feature, please do it on the Audacity Discord server #real-time channel - https://discord.gg/KHzWJTHU - rather than on this issue.

**Comment by jounih** [comment]
![effects 1@2x](https://user-images.githubusercontent.com/10109867/124128748-f9fb7580-da74-11eb-8a00-73d0309481a1.jpg)
![effects 2@2x](https://user-images.githubusercontent.com/10109867/124128759-fd8efc80-da74-11eb-9cc3-2fc0df42ab68.jpg)
![effects 3@2x](https://user-images.githubusercontent.com/10109867/124128765-fec02980-da74-11eb-95e8-9a545e576d6b.jpg)
![effects 4@2x](https://user-images.githubusercontent.com/10109867/124128769-fff15680-da74-11eb-83f1-4f9274ce60ef.jpg)
![effects 5@2x](https://user-images.githubusercontent.com/10109867/124128773-0089ed00-da75-11eb-95af-d49118b6036e.jpg)
![effects 8@2x](https://user-images.githubusercontent.com/10109867/124128775-01228380-da75-11eb-9814-d34350a122ae.jpg)
![effects 9@2x](https://user-images.githubusercontent.com/10109867/124128777-01bb1a00-da75-11eb-807b-1537b382a007.jpg)
![effects 10@2x](https://user-images.githubusercontent.com/10109867/124128780-0253b080-da75-11eb-97ee-bca86a03e75b.jpg)
![effects 11@2x](https://user-images.githubusercontent.com/10109867/124128782-02ec4700-da75-11eb-9ac1-6bdd4de2c7e7.jpg)
![effects 12@2x](https://user-images.githubusercontent.com/10109867/124128785-0384dd80-da75-11eb-9766-5fd67b6b4907.jpg)
![effects 13@2x](https://user-images.githubusercontent.com/10109867/124128790-041d7400-da75-11eb-9a6a-0c19c6465588.jpg)

**Comment by AnitaBats** [comment]
Design is ready, feature planned for Milestone 3.2
