### ISSUE TITLE
Context menu rework

### ISSUE THREAD

**Issue by AnitaBats** [audacity/audacity#998]
### User Story
As a user, I would like to access some frequent functions directly in context, to save time.

### Description

Currently audio tracks don't have any context menus (right click menus) in Audacity. In most DAWs the most often used actions are also exposed through context menus (in addition to main menus and keyboard shortcuts). This saves users time and helps new users find commonly used actions quickly in context.

We would like to add a handful of often used actions as context menus when right clicking on an audio track, or in the empty space. We can add more actions over time, but this would be a good starter set.

Context menu over audio track:

![1 0 audacity3 menu on audio clip@2x](https://user-images.githubusercontent.com/10109867/125430957-fc5d9057-668b-438b-9dc3-79572facbc2b.jpg)

Content menu outside audio track:

![1 0 audacity3 menu on empty@2x](https://user-images.githubusercontent.com/10109867/125431792-e3063672-5db1-41c4-8365-ad4c7fb10331.jpg)

Discussion at #867 

### Scope, Restrictions and Сourner-cases

- in release 3.1 new context menu is applicable only to Mono and Stereo tracks
- context menu on blank space is different to the context menu on audio tracks (see the screenshots above, please)
- time tracks and label tracks are not in the scope of this task in release 3.1. Time and label tracks are still the same.

**Comment by jounih** [comment]
There is a design here - https://github.com/audacity/audacity/discussions/867

I have a few suggestions there for items to go in the context menus, but we need to decide on a full list together

**Comment by Penikov** [comment]
@jounih Jouni, could you, please, point what functions/actions are required in the new context menu?

**Comment by AnitaBats** [comment]
Ready for development

**Comment by gera-gas** [comment]
**Description of task decomposition.**
All estimation times have two borders: this is not 100% precision time frame, this is the approximate time window for solving task.

1. Add context menu
1.1 Create event handler for right mouse click in `ProjectManager` (this class already support mouseevent `ProjectWindow::OnMouseEvent`, but seems necessary passed up right click event additionally).
1.2 Create context  menu by `wxMenu` and bind (connect) handler for popup context menu callback.
Estimate: 2 - 3 hrs.

2. Call methods from context menu
2.1 Call exist methods from context menu callback, like `OnNewWaveTrack(const CommandContext &context)` for create a mono track or `void OnPaste(const CommandContext &context)`, etc, but it should doing carefully for support right `CommandContext` content.
2.2 Final behavior tests (2,4) hrs.
Estimate: 8 - 10 hrs.

**Total estimate:** 10 - 13 hrs.
